### ISSUE TITLE
Add a reload button to the window's title bar

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#10007]
## Summary

Loading content such as notes, pages, user profiles, etc., in a window may fail or take too long.
![image](https://user-images.githubusercontent.com/31585494/220066612-23281d67-aa8c-4cda-b4dc-11d6c37e1fe8.png)
If it fails, the content must be located again and reopened.
Sometimes content can be loaded quickly by retrying to load it, even if it is just taking a long time to load.
However, in an ultra-fast timeline environment such as misskey.io's global timeline, it can be very difficult or even impossible to find the note you want to retry loading again.
So I would like a button to reload the contents of the window.

**Comment by syuilo** [comment]
ノートなどの読み込みにタイムアウト設定してノートなどのページ側で再試行できるようにした方がよさそう

**Comment by tamaina** [comment]
ページ一つ一つにリロードを仕込んでいくのは非現実的な気もする
