### ISSUE TITLE
can't select audio 1x playback speed.

### ISSUE THREAD

**Issue by TsubasaKawajiri** [syuilo/Misskey#10014]
## 💡 Summary
playback speed selection is only shown in the the note box, and Not scrollable.
So can't select undisplayed playback speed.

<img width="236" alt="スクリーンショット 2023-02-21 13 38 12" src="https://user-images.githubusercontent.com/39114857/220249301-ab9c1ee0-3761-42c3-abec-c3099cf8867e.png">
<img width="319" alt="スクリーンショット 2023-02-21 13 38 05" src="https://user-images.githubusercontent.com/39114857/220249321-4caa756e-f9f9-48f5-8fdb-a4cd2d70a83f.png">

## 🥰 Expected Behavior
It should be foreground than note, like a hover. or, Scrollable.

## 🤬 Actual Behavior
I can't select 1x playback speed.

## 📝 Steps to Reproduce

1. upload mp3
2. show playback speed option for it

## 📌 Environment

Misskey version: 13.6.1
Your OS: macOS 12.6
Your browser: Google Chrome 108.0.5359.124

**Comment by mappi-pr** [comment]
ライブラリの提供元、PlyrのIssueにも同様の内容が起票されていました。
 - https://github.com/sampotts/plyr/issues/1347

https://github.com/sampotts/plyr/issues/1347#issuecomment-559845836
のコメントにあった解決策は、上部に突き抜けたメニューを下部に表示する案だったので、misskeyにそのまま適用しても、今度は下に突き抜けてしまうため個別の対応が必要そうです。
<img width="324" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/159b21fe-7a18-49f4-8971-0772d0be813e">

**Comment by mappi-pr** [comment]
resolve? 8b33a70fc488219495fb899e2b4e9ff562047e24
（Plyrの利用をやめたため、事象が発生しなくなりました）

ただし、ブラウザネイティブのAudio要素を表示するようになったので
FirefoxやSafariなどのブラウザでスピードコントローラーが表示されなくなってます。
EX)Firefox
<img width="498" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/821d8289-a213-4f58-b288-602210f0e4e4">

**Comment by tamaina** [comment]
右クリックでコンテキストメニュー表示するとコントロールできるものの、Misskeyのノートのコンテキストメニューに上書きされてしまっている

**Comment by mappi-pr** [comment]
NYARUHODO😿
<img width="354" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/ba74245a-db20-4392-bf66-15c6cb2df8f5">

<img width="394" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/7f2f7ffc-7e6e-4723-8df2-6fc7767247ec">

**Comment by mappi-pr** [comment]
(Draft)
Audio要素を右クリックするときには、Misskeyのノートのコンテキストメニューが表示されないようにする。
※タブレットや、スマートフォンの挙動を見ていないので残りの課題があるかどうか不明です
https://github.com/mappi-pr/misskey/commit/3aa64abc56f6a72ce9336f521d868fac6c6578cb
<img width="666" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/a812b462-60aa-4f83-9818-a52be6e54768">
