### ISSUE TITLE
タイムライン上からアカウントをミュート・ブロックできるようにする

### ISSUE THREAD

**Issue by cocu-tan** [syuilo/Misskey#10019]
## Summary

Add "mute user" and "block user" items to note menu 

![hoge](https://user-images.githubusercontent.com/46195901/220375224-e636cb0d-2b9e-41c0-9bc6-96f70862885a.png)

**Comment by cocu-tan** [comment]
自分でやろうかと思ってたんですけど規則上できないっぽいので調べた実装方針だけ書いておきます……

## 実装方針
- Put menu items to `get-note-menu.ts` ([link](https://github.com/misskey-dev/misskey/blob/63df2c851e31a30dda3b7e9edefb2a97e4c1daa6/packages/frontend/src/scripts/get-note-menu.ts#L215))

**Details**
- Move [existing code to open a dialog for selecting mute period in `get-user-menu.ts`](https://github.com/misskey-dev/misskey/blob/63df2c851e31a30dda3b7e9edefb2a97e4c1daa6/packages/frontend/src/scripts/get-user-menu.ts#L45-L72) to newly created file `frontend/src/scripts/show-mute-user-dialog.ts`
- Do not add those items when the note is posted by the current user.
- Will not support unmute or unblock in the menu, because it is a bit complicated to get the state of block / mute from `appearNote.user`.
  - ちゃんと読んでませんが、 タイムライン上において [`apperNote.user`](https://github.com/misskey-dev/misskey/blob/63df2c851e31a30dda3b7e9edefb2a97e4c1daa6/packages/frontend/src/scripts/get-note-menu.ts#L28)が `UserLite`であって `User`でないならば、isMutedやisBlockingがなくtoggleを実装するのが非自明なのかもです(menu開くたびにendpoint叩くようにしないといけない?)

**Comment by futchitwo** [comment]
（アカウントアイコンをホバーして出てくるカードのメニューからミュートブロックできるので、それで十分な気もします）
<img width="300" src="https://user-images.githubusercontent.com/74236683/220597451-eabc90ff-0eea-433b-8f4d-86af8e1df53e.jpg"></img>

**Comment by syuilo** [comment]
モバイルだとカード出せないのよね

**Comment by futchitwo** [comment]
出せなくはない(これはAndroid chrome)けど確かに出しづらい
iosだと無理かも

**Comment by futchitwo** [comment]
(iPadでも出せた)
