### ISSUE TITLE
アンテナとリストの「特定の日付へジャンプ」が壊れている

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10024]
## 💡 Summary
アンテナとリストの「特定の日付へジャンプ」が動作しません

## 🥰 Expected Behavior
特定の日付へジャンプできる

## 🤬 Actual Behavior
コンソールにエラーが出て動作しない  
![Screenshot from 2023-02-22 20-55-46](https://user-images.githubusercontent.com/61890205/220613235-884479a3-25ee-4d20-aa61-e8baa84f294d.png)

## 📝 Steps to Reproduce

1. アンテナかリストで「特定の日付へジャンプ」を使う
2. 何も起こらない
3. コンソールにエラーが残ってる

## 📌 Environment

Misskey version: v13.7.0 と v13.6.1 で確認
Your OS: Fedora37
Your browser: Firefox110

**Comment by zyoshoka** [comment]
重複のためクローズします🙏

Duplicate of #5137
