### ISSUE TITLE
productionかつtscでビルドできない？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10025]
https://fedibird.com/@noellabo/109908285713599357/references

**Comment by tamaina** [comment]
p1.a9z.devでビルドしてるのが問題ないのはswcでビルドしてるからなんだわ

**Comment by syuilo** [comment]
CIが通ってるのはなぜ

**Comment by tamaina** [comment]
まずjestはtscじゃないし、じゃあDockerでビルド通ってるのはなぜ

**Comment by syuilo** [comment]
e2eとかtscじゃないっけ

**Comment by tamaina** [comment]
developmentだから問題なく通っているというか、devDependenciesないとテストは動かないし

https://github.com/misskey-dev/misskey/actions/runs/4241083015/jobs/7370865946

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/220617006-5b57b16e-94ee-41c9-a590-8385f74299a3.png)

主要因はこれか

**Comment by tamaina** [comment]
ビルドはswcでするようにすれば良くない…？

**Comment by tamaina** [comment]
decDependencies必要説は憶測すぎたので名前変えた

**Comment by tamaina** [comment]
待ってこのバグ放置してどっか行かないで？！ @syuilo
