### ISSUE TITLE
通知欄が無限リロードに陥ることがある

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#10022]
## 💡 Summary

通知欄が何らかの原因で無限リロードに陥る。

## 🥰 Expected Behavior

必要なときに、1回だけリロードされる。

## 🤬 Actual Behavior

1回リロードが走ると延々とリロードが行われてしまう。
`/api/i/notifications` にひたすらアクセスし続けサーバーに負担がかかる。
何回リロードしても症状は1度でも発生するとしばらく収まらない。

## 📝 Steps to Reproduce

通知欄を見る

## Additional Info
連続で `/api/i/notifications` にアクセスするときのペイロードを確認すると `untilId` が毎回異なる。
ページネーションにバグがある？

また、同時に以下のようなエラーも発生している。
<img width="602" alt="image" src="https://user-images.githubusercontent.com/26585194/220552688-c3425cfb-2cfe-46d2-99fe-a467481a24e3.png">

## 📌 Environment
Misskey version: 13.6.1
Your OS: macOS Monterey
Your browser: Chrome 110.0.5481.100 (Official Build) （arm64）

**Comment by syuilo** [comment]
misskey.ioがCASCADE削除を無効にしていることが原因
