### ISSUE TITLE
LTLをデフォルトロールで無効化している場合、ウェルカムページのタイムラインを見てみるが 問題が発生しました になる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10021]

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/220545764-03aeddf4-857b-4bdc-8b96-e47e34ef6a61.png)

**Comment by syuilo** [comment]
非ログインならLTL見れるようにするか

**Comment by tamaina** [comment]
それは違うと思う
