### ISSUE TITLE
tsc-aliasが実行されない

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#10030]
## 💡 Summary

5ec07ede7ce904ab135cad1d425a4957515de3a9 から型エラーが全部無くなったことによってbackendのbuildコマンドの
```
tsc -p tsconfig.json || echo done. && tsc-alias -p tsconfig.json
```
のtsc-aliasまで実行されない

## 🥰 Expected Behavior

ビルドが正常に終わる

## 🤬 Actual Behavior

tsc-aliasまで実行されない

## 📝 Steps to Reproduce

1.pnpm clean
2.pnpm build

## 📌 Environment

Misskey version: 5ec07ede7ce904ab135cad1d425a4957515de3a9 ～
Your OS: Windows 10

**Comment by syuilo** [comment]
謎

**Comment by kabo2468** [comment]
型エラーが出るとexit codeで0以外を返す
そしてコマンドの`a || b`は「aが失敗したときにbを実行する」という意味なので、型エラーが無いとtsc以降のコマンドが実行されない

**Comment by syuilo** [comment]
なるほど
ただ13.7.1からはビルドにswc使うようになったから影響は軽微かも

**Comment by syuilo** [comment]
多分直った

**Comment by kabo2468** [comment]
直った

**Comment by kabo2468** [comment]
swcはWindowsだと(?)このエラーが出てビルドできない
要検証
```
packages/backend build$ swc src -d built -D
│ failed to read swcrc file (src/config.ts)
│ Caused by:
│     0: failed to canonicalize base url using the path of .swcrc
│        Dir:
│        (Used logic for windows)
│     1: 指定されたパスが見つかりません。 (os error 3)
│ failed to read swcrc file (src/decorators.ts)
│ Caused by:
│     0: failed to canonicalize base url using the path of .swcrc
│        Dir:
│        (Used logic for windows)
│     1: 指定されたパスが見つかりません。 (os error 3)
...
```

**Comment by syuilo** [comment]
しゅいろさんもビルドできなかった

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
こんな感じ
![image](https://user-images.githubusercontent.com/4439005/220804265-ecdc4f49-5f21-48d4-828b-68b74e7c5c23.png)

**Comment by syuilo** [comment]
tscに戻すか

**Comment by tamaina** [comment]
Windows開発環境でだけtsc使うようにしてほしい

**Comment by cffnpwr** [comment]
`failed to canonicalize base url`で調べたら本家swcのIssueにhttps://github.com/swc-project/swc/issues/702 というのがあって、ここに書いてあるとおり`.swcrc`で
```
baseUrl: "src",
paths: {"@/*": ["*"]},
```
としたら手元のWindows11でビルドが通りました

**Comment by cffnpwr** [comment]
今、Docker環境でビルドしているので正常動作していそうだったらPR飛ばします
