### ISSUE TITLE
photoswipe（画像の拡大表示）がなんか変

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10037]
- backdrop-filterが効いてない
- z-indexの問題からかウィンドウが前面に来てしまう

**Comment by acid-chicken** [comment]
なんか変で言うと object-fit も一致してなさそうな気がする

**Comment by syuilo** [comment]
photoswipeに対応してもらうしかないんだけど説明が面倒でIssue立ててない

**Comment by tamaina** [comment]
画像拡大、自分たちで作りたい気分はあるけど面倒だなぁ

**Comment by tamaina** [comment]
調査が面倒で退屈そうだけど解決するか

**Comment by syuilo** [comment]
勘だけどアップデートしたことによってクラス名が変わったんだと思う

**Comment by tamaina** [comment]
クラス名は変わっていないけど、.pswpなどに設定される値が増えたみたい

**Comment by tamaina** [comment]
別の話題だけど: 

styleでv-bind(pswpZIndex)を指定してもなぜか機能しないと書いてあるの、v-bindがコンポーネントの実体のルートにvarを指定して実現しているのに対し.pswpはbody直下に作られるわけで、それは機能しないよなという感じがある

**Comment by tamaina** [comment]
> object-fit も一致してなさそう

それは前から（これも解決策があれば教えて欲しい）

**Comment by acid-chicken** [comment]
> 画像拡大、自分たちで作りたい気分はあるけど面倒だなぁ

これするとしたとき必須要件はどんなもんなの

**Comment by syuilo** [comment]
ピンチで拡大できたりスワイプで他の画像に切り替えたりできることかな

**Comment by acid-chicken** [comment]
ふーむ
