### ISSUE TITLE
media-proxyのファイルをダウンロードするとimage.webpなどとして保存されるが、リモートの名前を尊重してほしい

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#10036]
## 💡 Summary

The links to all attachments, including images, are all accompanied by `image.webp`.
And the proxy does not keep the metadata of the attachment, making it impossible to know the file type after download.
## 🥰 Expected Behavior

Only links to images are appended with `image.webp`,files can be downloaded normally.
## 🤬 Actual Behavior

Anomalies occur when downloading.
## 📝 Steps to Reproduce
Use https://github.com/misskey-dev/media-proxy

## 📌 Environment

Misskey version:13.6.1
Your OS:Windows 11
Your browser:Edge 110

In addition, after setting the proxy, downloading attachments will jump on this page, you can consider setting it to open in a new tab.

**Comment by tamaina** [comment]
本体側のプロキシも同様に修正する必要がある

**Comment by tamaina** [comment]
Content-Dispositionを指定すると良さそう

**Comment by tamaina** [comment]
外部メディアプロキシは0.0.14で修正

本体内蔵メディアプロキシはめちゃくちゃ面倒
