### ISSUE TITLE
x3 ・ x4 を引用 RN した時にノートが畳まれない

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#10031]
## 💡 Summary

13.7 より MFM の x3 ・ x4 を使用するとたたまれた表示になり、TL の占領を防ぐ事ができるようになりましたが、これを引用 RN した時はたたまれず、大きく表示されたままになってしまいます。
<
## 🥰 Expected Behavior

引用 RN された時もたたまれる状態になるのが理想的でしょう

## 🤬 Actual Behavior

**💡 Summary** の通り

## 📝 Steps to Reproduce

再現は 13.7 以降が必要です。

1. MFM の `x3` または `x4` を使用して一度ノート
2. そのノートを引用 RN
3. タイムラインで表示を確認

## 📌 Environment

Misskey version: Misskey 13.7.1
Your OS: Windows 10（OS に関係ないと思われます）
Your browser: Chrome 110.0.5481.104（ブラウザに関係と思われます）

**Comment by fu-sen** [comment]
画像を付けた方が良いと思ったので……
`x4` 付のノート
https://misskey.04.si/notes/9bk1paj4iq
上のノートを引用 RN
https://misskey.04.si/notes/9bk1q11dit
で次のタイムラインになります。
![スクリーンショット 2023-02-23 12 39 50](https://user-images.githubusercontent.com/5434159/220816818-22ddb81c-fa13-43ae-bad3-4810df72ed1a.jpg)

**Comment by nexryai** [comment]
リプライでも同様っぽいです。場合によってTL埋め尽くされるみたいなので修正していただけると助かります
![IMG_20230223_191555](https://user-images.githubusercontent.com/61890205/220879037-dddc0f80-d774-410e-8042-38d54f577d4b.jpg)  
![IMG_20230223_191528](https://user-images.githubusercontent.com/61890205/220879044-ecbe65fe-e29e-4ceb-a8f1-fe55a4428ecc.jpg)

**Comment by kabo2468** [comment]
related to #7478

**Comment by fu-sen** [comment]
そうですねぇ……重複で Close しても良さそうですが、
今のままだと悪用の恐れがあるので、なにか対応とれないか、
あえてこのまま維持してみる事にします。
