### ISSUE TITLE
スマホの場合、チャンネルの投稿フォームに自動でフォーカスしないようにしたい

### ISSUE THREAD

**Issue by arrow2nd** [syuilo/Misskey#10045]
## Summary

チャンネルをスマートフォンで開いた際、キーボードが表示されて投稿が見づらくなってしまうので、自動でフォーカスを当てないようにすると良さそうだなと思います。

### Screen record

![demo](https://user-images.githubusercontent.com/44780846/220887196-dd48be38-a27d-4002-bb9d-9285cab3a144.gif)

**Comment by syuilo** [comment]
done
