### ISSUE TITLE
「ローカル限定」がユーザーとの認識にズレがある。 Misperceptions of the 'local-only' publication level.

### ISSUE THREAD

**Issue by argxentakato** [syuilo/Misskey#10055]
## Summary

「ローカル限定」公開範囲はユーザーに誤解されているかもしれない。

- ローカル限定が、名前から本当にローカルにしか公開されないと思われている。実際は普通に見れる。

→ ローカライズの変更が必要?
→ 警告画面を出す?
→ ログインしなければ見えないようにする?

**Comment by hdmr14** [comment]
実際、「ローカルのみ(local only)」の表記はインスタンス内からしか参照できなくさせるための機能だと勘違いしてしまうと思います。正直言いまして私は勘違いしていました。
「連合上で非表示(no federation)」のように具体的な内容に変えるべきだと思います。

また注意喚起としてフラグを立てた際に

- 投稿したノートは連合に共有されないだけでインターネット上のどこからでも閲覧可能なこと
- ノートへのリンクを張られるだけでリモートのインスタンスからも間接的に閲覧されうること
- リモートのフォロワーから直接閲覧できないこと

等を表示したらどうかと思います。
ユーザ同士のコミュニケーションに対する副作用があり、情報閲覧の公開範囲の限定には実質的な効果が無い特殊な用途のフラグだとユーザに周知するべきだと思います。

ローカル限定のノートをログインしなければ見えなくする件は表示上の修正と違って新しい機能になるので、ここは 「ローカルのみ」表記によってユーザの認識に齟齬が生じている問題に絞って別のイシューにしてはいかがでしょうか。

**Comment by argxentakato** [comment]
@hdmr14 実際どうするかはまだ決まっておらず、とりあえず議論しておく場所を確保する目的をIssueを立てました。(ぶっちゃけDiscussionでやるべきだけど、誰も見てなさそうだし…)

**Comment by syuilo** [comment]
どうでっしゃろ
![image](https://user-images.githubusercontent.com/4439005/221067300-3b843623-b4f9-402f-aa22-49207eecb8ec.png)
![image](https://user-images.githubusercontent.com/4439005/221067354-1569c03d-459b-4a2d-a105-d9a3c06204f0.png)

**Comment by L1n4r1A** [comment]
一モデレーター兼ユーザーとしてはわかりやすくて良いと思います

**Comment by argxentakato** [comment]
@syuilo [ｎｏｉｃｅ](https://youtu.be/Akwm2UZJ34o?t=13) 

欲を言うなら、警告文をもっと具体的に… 例えば「無効にしても外部のユーザーが投稿を見ることができます」とかにすると良いかもしれない。
