### ISSUE TITLE
noteに画像を16枚以上添付して投稿できてしまう

### ISSUE THREAD

**Issue by NikanRGB** [syuilo/Misskey#10079]
## 💡 Summary

ioで確認しました。
画像を一度に16枚以上貼ることができてしまい、そのままnoteを投稿できてしまいます。
表記がマイナスになっているにも関わらずエラーも出ません。
![image](https://user-images.githubusercontent.com/96659017/221328967-efc3bdf4-6dc6-4ae5-b500-0aeda2d61b31.png)

## 🥰 Expected Behavior

画像を16枚以上添付しようとすると拒否される

## 🤬 Actual Behavior

画像が16枚以上添付でき、投稿できる

## 📝 Steps to Reproduce

1.noteに画像を16枚以上添付する。
2.投稿する。
3.投稿できちゃった……

## 📌 Environment

Misskey version:13.6.1
Your OS:Windows 10
Your browser: Fire fox 110.0 (64 ビット)

**Comment by mei23** [comment]
ここで`anyOf`に入れたバリデーションが効いてなさそうな
https://github.com/misskey-dev/misskey/pull/9762
