### ISSUE TITLE
auto-play animated media attachments not working regardless of settings for animated images

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#10093]
## 💡 Summary
Animated attachments (such as GIFs) should autoplay if you disable `don't play animated images` in settings. However, animated images seem to appear as a static thumbnail no matter what your setting for animated images is. It's really weird that the setting `don't play animated images` seems to now only affect animated emojis but not attachments. This is really confusing as 'animated images' by meaning includes animated media attachments as well. The only workaround without changing codes seem to be turning on `Load original images instead of showing thumbnails`. However, this would largely lower the speed of image processing, and it is not supposed to be used for autoplaying animated media attachments.

## 🥰 Expected Behavior

Turn off `don't play animated images`, animated media attachments should autoplay (like in previous versions).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/106132975/221370687-84cdd5e4-5f7e-4a6f-ab0d-8e4ebf04352c.gif)

## 🤬 Actual Behavior
Animated media attachments appear as static image even when you enable animated images and disable `Load original images instead of showing thumbnails`.

<img width="756" alt="Screen Shot 2023-02-26 at 4 22 11 am" src="https://user-images.githubusercontent.com/106132975/221370810-456d6cfa-272e-4e29-bce2-57a3de7b0b03.png">

Here's the CSS codes for the static thumbnail.

<img width="598" alt="Screen Shot 2023-02-26 at 4 22 35 am" src="https://user-images.githubusercontent.com/106132975/221370776-953dd03a-0197-4a40-be4c-3dc26581f83d.png">

## 📝 Steps to Reproduce

1. Open an instance with misskey version >= 13.5.6
2. turn off `don't play animated images` and `Load original images instead of showing thumbnails` in settings. For reference, here's my settings <img width="408" alt="Screen Shot 2023-02-26 at 4 09 24 am" src="https://user-images.githubusercontent.com/106132975/221370909-7a370d2a-a188-401e-8dad-723326bb2ebc.png"> )

3. post an animated image 
4. the animated image won't autoplay (appear as static image)

I understand the efforts that have been put into creating a safer environment for people with photosensitive epilepsy as discussed in issue #9821, but this just seems like a bug to me that enabling auto-play animated media attachments becoming totally impossible regardless of settings as the setting `don't play animated images` now only affects animated emojis.

It is also very misleading, as by turning off `dont play animated images` users would assume static pictures they see are actually static, but in fact animated media attachments appear as static images under this setting, which could lead to users missing plenty of information as they wouldnt know animated images are animated unless they click on everyone of them.

## 📌 Environment

Misskey version: v13.7.5
Your OS: macOS, iOS, iPadOS 
Your browser: firefox, chrome, safari

**Comment by saschanaz** [comment]
Fixed by #10287
