### ISSUE TITLE
Play の「ソースを表示」にシンタックスハイライトを当てる

### ISSUE THREAD

**Issue by sopisoft** [syuilo/Misskey#10105]
## Summary
シンタックスハイライトが当てられていたほうが読みやすいと思います。
## Image
![syntax_highlighting](https://user-images.githubusercontent.com/53455523/221399866-6a6a9567-ae75-4f66-af34-f3ad68340a90.png)

**Comment by sopisoft** [comment]
Assignees になりたいです！
権限がないので、誰かアサインをお願いします。

**Comment by syuilo** [comment]
👍

**Comment by sopisoft** [comment]
Merged 👍
