### ISSUE TITLE
検索キーワードがリセットされない

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#10118]
## 💡 Summary

v13.8系から導入された新しい検索画面、検索から戻ってTL等を開いた後に再度検索しようとしても前回のキーワードが残ったままで前回のキーワードを消して検索し直さなければならない

## 🥰 Expected Behavior

キーワードが消える。結果表示も消えてまっさらな状態に戻るのが望ましい？

## 🤬 Actual Behavior

キーワードが消えないまま前回の結果が残る

## 📝 Steps to Reproduce

1.検索画面を開きキーワードを入力して検索
2.TL等別の画面に切り替える
3.再度検索を押す
4.Wow!

## 📌 Environment

Misskey version:13.8.1
Your OS:Windows
Your browser:Microsoft Edge 110

**Comment by tsaito18** [comment]
対応します。
