### ISSUE TITLE
Renote with visibility set to 'followers' causes federation problems

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#10127]
## 💡 Summary

When creating a renote with visibility set to 'followers' (see Payload 2), federation not work and deleting the renote fail. However, this issue can be avoided by setting the visibility to localOnly (see Payload 3).

## 🥰 Expected Behavior

Even if visibility is set to 'followers' and renote, federation must be possible and deletion requests must be processed normally.

## 🤬 Actual Behavior

Renotes with visibility set to 'followers' not be federated, and deletion attempts fail.

### 📃 Log

1. When a renote is created with visibility set to 'followers':
```
Error: renderAnnounce: cannot render non-public note
    at ApRendererService.renderAnnounce (file:///misskey/packages/backend/built/core/activitypub/ApRendererService.js:63:19)
    at NoteCreateService.renderNoteOrRenoteActivity (file:///misskey/packages/backend/built/core/NoteCreateService.js:542:155)
    at file:///misskey/packages/backend/built/core/NoteCreateService.js:443:53
    at NoteCreateService.postNoteCreated (file:///misskey/packages/backend/built/core/NoteCreateService.js:477:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
2. When attempting to delete this renote:
```
ERR  * [api]   Internal error occurred in notes/delete: renderAnnounce: cannot render non-public note
{
  ep: 'notes/delete',
  ps: { noteId: '9bp4vq6ox3', i: '[redacted]' },
  e: {
    message: 'renderAnnounce: cannot render non-public note',
    code: 'Error',
    stack: 'Error: renderAnnounce: cannot render non-public note\n' +
      '    at ApRendererService.renderAnnounce (file:///misskey/packages/backend/built/core/activitypub/ApRendererService.js:63:19)\n' +
      '    at NoteDeleteService.delete (file:///misskey/packages/backend/built/core/NoteDeleteService.js:63:133)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async file:///misskey/packages/backend/built/server/api/endpoints/notes/delete.js:70:13\n' +
      '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:260:16)',
    id: '7caed071-7c71-4346-a94d-08eeb8fc1ee2'
  }
}
```

### 1. General renote request
`{"renoteId":"9bp4zeufxu","i":"[redacted]"}`

### 2. Request renote with visibility 'followers':
`{"renoteId":"9bp4zeufxu","localOnly":false,"visibility":"followers","i":"[redacted]"}`

### 3. Renote with visibility 'followers' set to localOnly
`{"renoteId":"9bp4zeufxu","localOnly":true,"visibility":"followers","i":"[redacted]"}`

## 📝 Steps to Reproduce

1. Send a renote request using the payload 2.
2. Attempt to delete the renote.

## 📌 Environment

Misskey version: v13.8.1
Your OS: Windows 11 Pro Insider Preview 25300.1000
Your browser: Microsoft Edge 111.0.1660.14 (Official build) dev (64-bit)

**Comment by saschanaz** [comment]
https://github.com/misskey-dev/misskey/blob/787404638addb83a567fb59b4f871931f11bc5af/packages/backend/src/core/activitypub/ApRendererService.ts#L88-L96

("Announce" in AP means renotes) Maybe this should also cover `visibility === 'followers'`?

**Comment by saschanaz** [comment]
But what does it mean by follower-only renote? Should it even be supported? 🤔 (Follower-only quote exists, so maybe? 🤷)

@tamaina どう思いますか？

**Comment by saschanaz** [comment]
Should followers-only quote also CC the writer of the original post? ~~Currently it does not...~~ Oh it does, it's just that I turned the notification off.

**Comment by tamaina** [comment]
フォロワー限定Renoteは想定されていますので、これはバグです

**Comment by saschanaz** [comment]
CCはどう動くのです？

**Comment by tamaina** [comment]
ActivityPubわからない

**Comment by saschanaz** [comment]
質問を変えて

* followers-only リノートのnotificationを元投稿者に渡す
* 渡さない

どっちにしましょう

**Comment by tamaina** [comment]
> followers-only リノートのnotificationを元投稿者に渡す

引用RNは元投稿者に通知することになっているので、Renoteも通知するのが自然

**Comment by saschanaz** [comment]
引用RNのccにもtoにも元投稿者は入ってないのにどうやって通知行くのかちょっと謎…

**Comment by tamaina** [comment]
引用RNのccに元投稿者が入っていないのなら、それはローカルの挙動とは異なる

**Comment by saschanaz** [comment]
連合は確かに動いていますがどうやって動いているのかが謎です

**Comment by saschanaz** [comment]
CCやtoとは関係なくここで渡すようにできていました (cc使っていたらこれ要らなくなりません？🤔)

https://github.com/misskey-dev/misskey/blob/65b1524f928d546ecb885be98655f7eb39c9cba2/packages/backend/src/core/NoteCreateService.ts#L626-L629

渡される側ではここ

https://github.com/misskey-dev/misskey/blob/65b1524f928d546ecb885be98655f7eb39c9cba2/packages/backend/src/core/NoteCreateService.ts#L584-L591
