### ISSUE TITLE
ノートに添付された画像を拡大表示すると、背景が真っ黒になる

### ISSUE THREAD

**Issue by Steve-0628** [syuilo/Misskey#10137]
## 💡 Summary

ノートに添付された画像を拡大表示すると背景が黒くなります。

## 🥰 Expected Behavior

黒くならない、透過される、ブラーがかかる

## 🤬 Actual Behavior

黒くなる

## 📝 Steps to Reproduce

1. 画像つきで投稿する or 画像付きの投稿を見つける
2. 画像を押す
3. 黒くなる

## 📌 Environment

Misskey version: 13.8.1 / 13.8.1-p1.7
Your OS: Windows 11
Your browser: Firefox 110.0 / Chrome 110.0.5481.178

**Comment by tamaina** [comment]
Duplicate of #10037
