### ISSUE TITLE
After update 13.6 to 13.8.1 misskey not started

### ISSUE THREAD

**Issue by DarkShyMW** [syuilo/Misskey#10135]
## 💡 Summary

I was try to update my misskey instance from 13.6.1 to 13.8.1, but after `service misskey restart` i take error:
 > misskey@13.8.1 start
 > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
  sh: 1: pnpm: not found

## 🥰 Expected Behavior

Misskey should started

## 🤬 Actual Behavior

```
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
Feb 27 09:01:06 bronyfurry misskey[3393]: > misskey@13.8.1 start
Feb 27 09:01:06 bronyfurry misskey[3393]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:01:06 bronyfurry misskey[3404]: sh: 1: pnpm: not found
Feb 27 09:01:07 bronyfurry misskey[3406]: > misskey@13.8.1 start
Feb 27 09:01:07 bronyfurry misskey[3406]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:01:07 bronyfurry misskey[3419]: sh: 1: pnpm: not found
Feb 27 09:01:08 bronyfurry misskey[3420]: > misskey@13.8.1 start
Feb 27 09:01:08 bronyfurry misskey[3420]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:01:08 bronyfurry misskey[3431]: sh: 1: pnpm: not found
Feb 27 09:03:50 bronyfurry misskey[3721]: > misskey@13.8.1 start
Feb 27 09:03:50 bronyfurry misskey[3721]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:03:50 bronyfurry misskey[3732]: sh: 1: pnpm: not found
Feb 27 09:03:50 bronyfurry misskey[3735]: > misskey@13.8.1 start
Feb 27 09:03:50 bronyfurry misskey[3735]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:03:50 bronyfurry misskey[3746]: sh: 1: pnpm: not found
Feb 27 09:03:51 bronyfurry misskey[3747]: > misskey@13.8.1 start
Feb 27 09:03:51 bronyfurry misskey[3747]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:03:51 bronyfurry misskey[3758]: sh: 1: pnpm: not found
Feb 27 09:03:52 bronyfurry misskey[3760]: > misskey@13.8.1 start
Feb 27 09:03:52 bronyfurry misskey[3760]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:03:52 bronyfurry misskey[3773]: sh: 1: pnpm: not found
Feb 27 09:03:53 bronyfurry misskey[3774]: > misskey@13.8.1 start
Feb 27 09:03:53 bronyfurry misskey[3774]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
Feb 27 09:03:53 bronyfurry misskey[3785]: sh: 1: pnpm: not found

```

## 📝 Steps to Reproduce

1. update from 13.1.6 to 13.1.8

## 📌 Environment

Misskey version: 13.1.6->13.1.8
Your OS: Ubuntu 22.04
Your browser: Firefox

**Comment by momoirodouhu** [comment]
In my case,it was solved by adding this to service file.
`Environment="PATH=/home/misskey/.local/share/pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"`

I don't know if this is the right solution.

**Comment by DarkShyMW** [comment]
but if i use pnpm start
all works

**Comment by DarkShyMW** [comment]
@momoirodouhu this my misskey.service

[Unit]
Description=Misskey daemon

[Service]
Type=simple
User=misskey
ExecStart=/home/misskey/.nvm/versions/node/v18.14.1/bin/npm start
WorkingDirectory=/home/misskey/misskey
Environment="NODE_ENV=production"
TimeoutSec=60
StandardOutput=journal
StandardError=journal
SyslogIdentifier=misskey
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by MomentQYC** [comment]
https://github.com/misskey-dev/misskey/blob/647a0183626042f29834c3b4dd8dbba88a799c4c/package.json#L19
You can modify it to look like this:
`"start": "cd packages/backend && node ./built/boot/index.js",`

**Comment by momoirodouhu** [comment]
pnpm path is written in bashrc.
But systemd doesn't use it.
So systemd can't solve command`pnpm`

**Comment by anatawa12** [comment]
It looks this is not issue of misskey, is issue of your environment configuration (especially PATH environment variable) and very old so closing this issue.
If you still have same issue, please try configuring PATH or ask help community on discussions.

Misskeyの問題ではなく、環境の設定(特にPATH環境変数)の問題のようで、また古いため、Closeします。
もしまだ問題が発生している場合には、PATH環境変数の設定を試す、またはdiscussionsで助けを求めてみてください。
