### ISSUE TITLE
Add an option for antennas not to pick up remote notes from other instances of Misskey or other implementations

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#10139]
## 💡 Summary

In order to ease finding newcomers' Notes, it would be nice to have an option for antennas not to pick up remote notes from other instances of Misskey or other implementations.
Ideally, there would be a separate options for:
- Rejecting notes from remote Misskey
- Rejecting notes from remote instance of other ActivityPub implementations

**Comment by KisaragiEffective** [comment]
duplicated by #11869, implemented in https://github.com/MisskeyIO/misskey/commit/3ebed5aa3e18cb66359c62f1f77443d120aa9f02
