### ISSUE TITLE
通知設定に通知を全て無効にしたら何も通知されなくなる旨を表示する

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#10159]
## Summary

通知設定で全ての通知を無効にした場合、通知欄に何も通知が表示されなくなります。
しかし、全ての通知を無効にしてもリプライは表示されると思っていると、急に通知が出て来なくなったと勘違いしてしまうため、その旨を通知設定に記述すると勘違いすることが減りそうです。

**Comment by acid-chicken** [comment]
> しかし、全ての通知を無効にしてもリプライは表示されると思っている

リプライ通知をオフにしたのにリプライ通知が届くことを期待するシナリオがよく分からない

**Comment by massongit** [comment]
リプライはどうやっても消せないデフォルトの通知であるという前提の元でリプライ以外の通知を消すために `全てを無効にする` ボタンを押下する、というシナリオはあり得るのかなと。

**Comment by massongit** [comment]
少々シナリオの考慮が足りなかった感じがするので一旦closeします。
