### ISSUE TITLE
ウィンドウを開いてから画像を開くとウィンドウの裏に表示される

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#10164]
## 💡 Summary

ウィンドウを開いてから画像を開くとウィンドウの裏に表示される

## 🥰 Expected Behavior

ウィンドウより上に表示される

## 🤬 Actual Behavior

ウィンドウの裏に表示される

## 📝 Steps to Reproduce

1.画像を添付した投稿をする
2.ウィンドウを開いてから画像を開く
3.ウィンドウの裏に表示される

## 📌 Environment

Misskey version: 13.7.0 ～
Your OS: Windows10
Your browser: Vivaldi, Chrome

**Comment by acid-chicken** [comment]
Duplicate of #10070
