### ISSUE TITLE
AWS SDK v2がdeprecatedらしいのでv3にアップデートする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10170]
## Summary
AWS SDK v2はdeprecatedらしい

**Comment by saschanaz** [comment]
https://github.com/awslabs/aws-sdk-js-codemod こんなものがありましたので使ってみましたが、なんかタイプエラーがでたので https://github.com/awslabs/aws-sdk-js-codemod/issues/454 に報告しました

**Comment by yszkst** [comment]
手動書き換えでよいならこのIssue引き取りたいですが良いですが？

**Comment by saschanaz** [comment]
どうぞご自由に。codemod使ったら結構いい感じになるので参考にしたらいいでしょう (https://github.com/awslabs/aws-sdk-js-codemod/issues/454#issue-1607441768 のActual result)

**Comment by yszkst** [comment]
ありがとうございます      
すみません、文末が`か？`のつもりで`が？`になっていました。 含みはありません。

**Comment by saschanaz** [comment]
（気づきませんでした）

**Comment by saschanaz** [comment]
Fixed by #10363
