### ISSUE TITLE
ノート全体を詳細画面へのリンクにする

### ISSUE THREAD

**Issue by tsaito18** [syuilo/Misskey#10172]
## Summary

Twitter や Mastodon、Calckey などを触っていて、ツイートやノートのどこを触っても詳細画面に飛べるのは便利だと感じるので、
ノート全体を詳細画面へのリンクにすることを提案します。

それとも、あえて投稿時間からのみ詳細画面へリンクしている理由があるのでしょうか…？

**Comment by syuilo** [comment]
こちらをご覧ください
https://github.com/misskey-dev/misskey/issues/8804
