### ISSUE TITLE
設定のバックアップ の「削除」の文字がない

### ISSUE THREAD

**Issue by KusaReMKN** [syuilo/Misskey#10195]
## 💡 Summary

設定のバックアップをクリックすると表示されるメニューには「削除」の文字がなく、ゴミ箱のアイコンのみがあります。

## 🥰 Expected Behavior

他の項目のように「削除」の文字が表示されるべきです。

## 🤬 Actual Behavior

Summary の通りです。

## 📝 Steps to Reproduce

1. **設定** から **設定のバックアップ** を開きます。
2. **作成したバックアップ** からバックアップ済の項目をクリックします。
3. 表示されるメニューの最下段にはゴミ箱のアイコンのみがあります。

## 📌 Environment

Misskey version: 13.9.0
Your OS: FreeBSD 13.1
Your browser: 110.0.1 (64 ビット)

**Comment by Fuji-P** [comment]
preferences-backups.vue内の
`text: ts._preferencesBackups.delete,`
が原因ですかね？
_preferencesBackupsにdeleteが定義されていないので定義するかdeleteを使用する？
