### ISSUE TITLE
ユニークな値を検索したときに直接ページに飛ばないようにしたい

### ISSUE THREAD

**Issue by momoirodouhu** [syuilo/Misskey#10199]
##内容
ユニークな値(acctやnoteへのURL)を検索にかけたときそのページに直接飛ぶが、一度検索結果に表示させるようにしたい

##メリット
- 勝手にページ移動しないので混乱しない
- 入力途中でマッチするものがあっても大丈夫

##デメリット
- 詳細を見るのに1クリック手間が増える

**Comment by naskya** [comment]
URL を入力した際に（例えばそれがこの GitHub Issue の URL であっても）必ず Fetching from the Fediverse... が走るのも気にはなりますね
わざわざその対処のために（例えば検索ボタンと取得ボタンをそれぞれ作るなどして）UI を複雑化させるべきかというのはまた別の議論ではありますが（取得は勝手に失敗するだけだし）

**Comment by momoirodouhu** [comment]
別の意図からだけど、 PR に検索ボタンを作る話は上がってるみたいなので、それで一緒にfetchも減りそう。

取得ボタンを作るのは、fediverseの仕組みを知らないユーザーには混乱を招く気がします。

**Comment by syuilo** [comment]
fixed
