### ISSUE TITLE
Identiconがローカルとリモートで異なって見える

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10200]
IdenticonはuserIdを鍵としてgenIdenticonされているが、userIdはインスタンスごとに異なる。そのため、Identiconはインスタンスごとに異なって見える。

username@hostでIdenticonを生成したほうが良さそう

**Comment by rinsuki** [comment]
そもそもリモートでも見た目共通したいんだったら Mastodon とかの単純に単一イメージ出す実装も考えて identicon 自体をアイコンとして AP に流すべき
