### ISSUE TITLE
iPad (iPadOS 16.4 Public Beta 2)のPWAで新規登録/ログインボタンが表示されない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10202]
![IMG_0220](https://user-images.githubusercontent.com/7973572/222917314-b17ed085-da8a-4cd8-9367-b59089618be1.png)

## 📌 Environment

Misskey version: 13.9.1
Your OS: iPadOS 16.4 Public Beta 2
Your browser: PWA (Safari)

**Comment by tamaina** [comment]
13.6.1のmisskey.ioでも発生する

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/222917887-32951079-532b-4cba-a521-1f4713331e83.png)

言語がnullになることなんてある？

**Comment by tamaina** [comment]
CloudflareでRocket LoaderやAuto Minifyを有効にしているわけではないし

**Comment by tamaina** [comment]
boot.jsをbodyの最後に持っていくみたいな原始的なことをしてみたが無駄だった

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
応急処置として lang が null もしくは文字列として'null'だったらフォールバックするようにする？

**Comment by syuilo** [comment]
既に
``` ts
// Fallback
if (lang == null) lang = 'en-US';
```
はあるんだけど何らかの理由でそこに到達してないと思われる

**Comment by tamaina** [comment]
navigator.languageがnullになっていてもこうはならんのよな

**Comment by fruitriin** [comment]
nullになった時英語か日本語にフォールバックするのがお手軽かも？

**Comment by fruitriin** [comment]
あ、すでにあるのか。むむ

**Comment by tamaina** [comment]
Security Response (a) とやらで修正されたっぽい？

**Comment by tamaina** [comment]
とりあえずclose
