### ISSUE TITLE
バッジがたくさんあるとユーザーページのバッジ表示部分が崩れる

### ISSUE THREAD

**Issue by arrow2nd** [syuilo/Misskey#10219]
## 💡 Summary

スマートフォンなどの横幅が狭いデバイスでバッジがたくさんあるユーザーを表示すると、バッジの一部が途中で折り返されてしまって読みづらくなっている

![image](https://user-images.githubusercontent.com/44780846/222958126-240d5997-daa5-49ac-9d4d-d0c259dd27f9.png)

## 🥰 Expected Behavior

適切に折り返された状態で表示されてほしい

## 🤬 Actual Behavior

- バッジの一部が途中で折り返されている
- 折り返した部分が上のバッジと重なっている

## 📝 Steps to Reproduce

1. https://misskey.io/@syuilo をスマートフォン等の横幅が狭いデバイスで表示する

## 📌 Environment

Misskey version: 13.6.1 (misskey.io)
Your OS: Android 13
Your browser: Firefox 110.1.0

**Comment by KawaneRio** [comment]
<ruby>直<rp>《</rp><rt>なほ</rt><rp>》</rp></ruby>ってないかも。

Misskey version: `v13.9.1` (Misskey.io 2023/03/06)
OS: `Kubuntu 22.04.1 LTS x86_64`
Browser: `Mozilla Firefox 110.0`

![image](https://user-images.githubusercontent.com/61252570/222971009-370c9889-d1a4-45bd-ab10-1b195ee0ae45.png)

**Comment by KawaneRio** [comment]
ごめん、.ioは<ruby>最新版<rp>《</rp><rt>さいしんばん</rt><rp>》</rp></ruby>じゃないかも。
