### ISSUE TITLE
Dev Containers初回起動時にJestが自動で起動し、実行に失敗する

### ISSUE THREAD

**Issue by Ry0taK** [syuilo/Misskey#10211]
## 💡 Summary
https://github.com/misskey-dev/misskey/commit/c54712233cfe212b090a16c567cb1c1ed8cc8058 で加えられた変更により、Dev Containers使用時に`Orta.vscode-jest`が勝手にインストールされるようになったが、この拡張機能はワークスペースを開いた際に自動でJestを実行する。
しかしながら、Dev Containersの初回起動時においては`pnpm install`の実行が完了していないため、Jestの実行に失敗してしまう。

## 🥰 Expected Behavior
Jestの実行が自動で始まらない

## 🤬 Actual Behavior
Jestの実行が自動で始まり、失敗する

## 📝 Steps to Reproduce

1. Dev Containersを開く。
2. Jestが自動で実行され、失敗することを確認する。

## 📌 Environment

Your OS: Windows 10

**Comment by tamaina** [comment]
jestのプロセス自体がコケることは普段もあるのでjestの再実行ができればいいんだけど、そういう機能がなさそう

**Comment by Ry0taK** [comment]
一旦自動起動を無効にして対応したいです (そもそも拡張機能を自動インストールするのはなんだかなあという気持ちもありますが、一旦ここでは取り扱わない)

**Comment by tamaina** [comment]
> 拡張機能を自動インストールするのはなんだかなあ

Dev Containerってそういうものではない？
