### ISSUE TITLE
検索ページのユーザータブで最初に@を入力するとエラー

### ISSUE THREAD

**Issue by danominium** [syuilo/Misskey#10226]
## 💡 Summary
ユーザの検索をするために@から入力したところ、エラーが表示されました。

## 🥰 Expected Behavior
検索条件の入力が継続される。

## 🤬 Actual Behavior
「問題が発生しました」が表示される。

/api/users/show
400
{"error":{"message":"No such user.","code":"NO_SUCH_USER","id":"4362f8dc-731f-4ad8-a694-be5a88922a24","kind":"client"}}

この状態でページをリロードすると下記エラーが表示される。
(再試行ボタンではなく /@ ページを開き直す)
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of undefined (reading 'startsWith')"}

## 📝 Steps to Reproduce

1. 検索ページを開く(/search)
2. ユーザタブを選択
3. @を入力する

## 📌 Environment

Misskey version: 13.9.1
Your OS: ChromeOS
Your browser: Google Chrome

**Comment by tsaito18** [comment]
関連: #10199
入力が妨害されるのはよくないですね…直リンクを入力した時にどんな感じの UI にすれば分かりやすいのかが思いつきませんが

**Comment by syuilo** [comment]
fixed
