### ISSUE TITLE
カスタム絵文字をWebPにするとJPEGに変換され、マストドンに認識されなくなる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10224]
## 💡 Summary

https://github.com/misskey-dev/misskey/blob/824398509d805a62bd656aaf3a5c2114b1d24cb4/packages/backend/src/core/DriveService.ts#L322-L323

DriveServiceによってJPEG/WebP/AVIFは全てJPEGに変換するようにできていますが、マストドンはWebPは認識してもJPEGは拒否するのでむしろ見えなくなります。https://github.com/mastodon/mastodon/issues/23968

## 🥰 Expected Behavior

WebPをWebPやPNGにする

## 🤬 Actual Behavior

WebPがJPEGになってマストドンでは見えなくなる

## 📝 Steps to Reproduce

1. WebPのカスタム絵文字をアップロード
2. マストドンで見えるのか確認

## 📌 Environment

Misskey version: 13.8.1
Your OS: Windows 11
Your browser: Firefox

**Comment by saschanaz** [comment]
毎回ミスって空のIssue上げてしまっている…

**Comment by tamaina** [comment]
> JPEG/WebP/AVIFは全てJPEGに変換するようにできています

そこそこ問題のある仕様だということに今更気づくなど

（だからと言ってpngにするわけにもいかない）

**Comment by saschanaz** [comment]
>（だからと言ってpngにするわけにもいかない）

PNG以外に選択肢ないんじゃないですか？GIFはalpha channelがないからだめですので

（WebPにしてPawooサポート捨てちまう選択肢もまあありますが）

**Comment by acid-chicken** [comment]
WebP にしようぜ

**Comment by tamaina** [comment]
webpにしようぜ2

**Comment by saschanaz** [comment]
Pawooすてようぜ？:wakaru:
