### ISSUE TITLE
GIF映像やAltメッセージ付いている映像にはバナーを見せる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10235]
## Summary

アニメーション再生しないオプションを適用するとGIFかどうかタップする前にはわかる方法がないので、ここはツイッターのようにバナーを見せてらいい感じになると思います

Altもモバイルではあるかどうかタップする前にはわからないので同様です

**Comment by kabo2468** [comment]
related to #10054 ?
