### ISSUE TITLE
#1792のタイムラインで連続して同じNoteがRenoteされている場合、省略した表示をする件

### ISSUE THREAD

**Issue by MedesIf** [syuilo/Misskey#10253]
下記にて対応された表題の件
https://github.com/misskey-dev/misskey/issues/1792

こちらの機能、現状も正しく動作しておりますでしょうか？
上記リンク先の図のように省略されたRNですが、ほぼほぼ滅多に見ることができず、
同ユーザ、同RNであっても省略されて表示されないように見受けられます。
認識違いでしたら申し訳ございません。

**Comment by tamaina** [comment]
misskey.ioでしょうか？

**Comment by syuilo** [comment]
Noteを見たかどうか判定するのが難しかったから途中から自分がリアクションしたかどうかで判定するようにした

**Comment by syuilo** [comment]
だからリアクションしなければいくら見ても隠されることがない

**Comment by MedesIf** [comment]
なるほど、承知しました。
ありがとうございます。
