### ISSUE TITLE
FIDO2で生体認証ができない

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#10257]
FIDO2対応のYubikeyを使って2段階認証をしようとしたんですが、

> Endpoint: i/2fa/register-key
> Info: {"e":{"message":"incorrect password","code":"Error","id":"bd28b6d5-387e-49a4-bb8f-877e746005ce"}}
> Date: 2023-03-07T06:42:47.958Z

というエラーが出て使えませんので報告します。

**Comment by nexryai** [comment]
`incorrect password`とあるので単純にパスワードを間違えている可能性はありませんか？

**Comment by PYU224** [comment]
パスワードを間違えていました。
ただそこから「セキュリティキー・パスキーを登録する」で登録しようとしても

Invalid param.
3d81ceae-475f-4600-b2a8-2bc116157532

と表示されて登録ができません。

**Comment by PYU224** [comment]
すみません解決できました。
FIDO2の仕様を勘違いしていてました。
指紋認証ではないんですね。

**Comment by tamaina** [comment]
>  指紋認証ではないんですね。

んー？

## Android

指紋認証というか画面ロックをWebAuthnで登録できる  
**が、**Chromeでのセキュリティキー登録はMisskeyが現状非対応

https://github.com/misskey-dev/misskey/issues/9344

## iOS, macOS Safari

普通に操作するとパスキーの登録になる  
登録・認証時はFace ID, Touch IDもしくはパスコードが要求される

## Windows

デバイスにWindows Hello（立体顔認証、指紋認証）があればそれを鍵にできる

## セキュリティキー
各ブラウザでYubiKeyなどのハードウェアセキュリティキーを鍵にできる  

（キーにタッチするのは指紋認証とかではない）

**Comment by PYU224** [comment]
これを読んでようやく理解しMisskeyに設定できました。
お騒がせして申し訳ございませんでした。
https://pj-tc.com/yubikey-review-2/
