### ISSUE TITLE
登録時の重複チェックが間違った結果を返すケースがある

### ISSUE THREAD

**Issue by Ry0taK** [syuilo/Misskey#10262]
## 💡 Summary
https://github.com/misskey-dev/misskey/blob/8bf6911d4b7222af1a85212aada0c8a23da47631/packages/frontend/src/components/MkSignup.vue#L146-L152
ユーザー登録時のフォームにおいてユーザー名/メールアドレスが使用可能であるかどうかの確認が非同期で行われているため、以下のような状況で誤った結果が表示されます。 (`admin`という名前のユーザーが作成されている状態を仮定)
1. ユーザーが登録フォームを開く
2. ユーザー名フィールドに対して`admin`と高速に入力する
3. それぞれ`a`、`ad`、`adm`、`admi`、`admin`に対してユーザー名の存在確認が走る。
4. `admin`の存在確認に対するレスポンスが帰ってくる。
5. その他の存在しないユーザー名の存在確認に対するレスポンスが帰ってくる。
6. `admin`と入力されているにも関わらず、内部的には`adm`等の存在確認の結果を持つようになる。
(#10238 で追加したテストにより発覚)

## 🥰 Expected Behavior
入力されたユーザー名/メールアドレスと使用可否の表示が一致している

## 🤬 Actual Behavior
入力されたユーザー名/メールアドレスと使用可否の表示が一致していない

## 📝 Steps to Reproduce

1. `admin`という名前のユーザーを作成する
2. ユーザー登録ページを開く
3. ユーザー名フィールドに対して、高速で`admin`と入力する
4. 既に使用されているにも関わらず、利用可能となることを確認する (確認できなかった場合は再度手順3からやり直してください)

**Comment by Ry0taK** [comment]
どうやって治すのかが悩ましいですね... (フォーカスが外れたタイミングで確認を走らせるようにすれば一旦は解決する？)

**Comment by saschanaz** [comment]
ローカルではuncaught errorも発生していたので #10265 を提出しました。

**Comment by saschanaz** [comment]
>どうやって治すのかが悩ましいですね

`api()`をabortできるようにして、AbortControllerを使って前回のリクエストをabortするようにしたらどうでしょう。
