### ISSUE TITLE
misskey sidebar does not scroll

### ISSUE THREAD

**Issue by trwnh** [syuilo/Misskey#10260]
## 💡 Summary

misskey 13 is unusable on small mobile screens due to sidebar not scrolling. i cannot get to settings

## 🥰 Expected Behavior

the sidebar should scroll on overflow

## 🤬 Actual Behavior

the sidebar is static and the overflow is hidden offscreen

## 📝 Steps to Reproduce

1. open the sidebar on a small screen

## 📌 Environment

Misskey version: 13.9.2
Your OS: iOS
Your browser: Safari

![72135AAA-436C-40DB-89E4-6D71C0F9A27B](https://user-images.githubusercontent.com/10606431/223449181-af2a55ee-0126-4013-af03-efa5a44fdc8a.png)

also the bot warning is annoying and completely useless. it should be removed

**Comment by sata6945** [comment]
[](url)Hi, you probably need to describe the iOS version at the same time.
Assuming your device is an iPhoneSE, I tried to reproduce this with ChromeDevTools, but it did not occur. Is Chrome viable on your device? Just to be sure, try running Misskey in Chrome and see if the same problem occurs.
By the way, you may be mistaken about how the Bot is handled within Misskey: the Bot is run by a human, but if you want to run the Bot (e.g., get a weather forecast from a certain site and automatically note it), you should use the MisskeyAPI to control the Bot from the console, etc.
![Animation](https://user-images.githubusercontent.com/47621879/223676325-9a549cc8-a7c1-4cf9-928b-bd4e10fed20c.gif)

**Comment by trwnh** [comment]
- ios 15, because the iphone se does not have ios 16 update.
- it happens the same in safari and in chrome. misskey 12 did not have this issue -- i only observe it after my instance updates to misskey 13.
- i want to be a bot. i do not need to be warned about this.

**Comment by acid-chicken** [comment]
> also the bot warning is annoying and completely useless. it should be removed

This is an intended behavior. Bot users are often used to provide services, and most cases of human login are for temporary operations or mishandling.

> Assuming your device is an iPhoneSE, I tried to reproduce this with ChromeDevTools, but it did not occur. Is Chrome viable on your device? Just to be sure, try running Misskey in Chrome and see if the same problem occurs.

Chrome is not Safari, and Chrome on iOS is not Chrome in technically.

**Comment by fruitriin** [comment]
I think Misskey v13 not support iOS15.
My iPhone SE 3rd Gen(iOS 16) work with safari able to scroll sidebar
