### ISSUE TITLE
Opening the control panel for the second time will not automatically redirect to overview

### ISSUE THREAD

**Issue by launchpad001** [syuilo/Misskey#10263]
## 💡 Summary

Opening the control panel the second time will not automatically redirect to overview.

## 🥰 Expected Behavior

In any case, opening the control panel should automatically redirect to the overview.

## 🤬 Actual Behavior

When the control panel is opened for the second time, a bad UI is displayed. It does not automatically jump to overview.

## 📝 Steps to Reproduce

1. Open Control Panel (`/admin`)

## 📌 Environment

Misskey version: v13.9.2
Your OS: Windows 11.0.22000.194
Your browser: Brave v1.48.171, Chromium: 110.0.5481.177 (64-bit)

**Comment by futchitwo** [comment]
This problem also occurs in /settings
