### ISSUE TITLE
MkMediaListで「アニメーション画像を再生しない」オプションの有効無効に関わらずアニメーション画像が停止する

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10274]
APIのgetThumbnailUrlが、thumbnailUrlがnullであった場合プロキシのstaticを返すようになってしまったため

 https://github.com/misskey-dev/misskey/blob/116dd097bda66196d69d81cf42c8e0bb7f32b141/packages/backend/src/core/entities/DriveFileEntityService.ts#L88

**Comment by kunimei** [comment]
good
