### ISSUE TITLE
プロフィールで設定した情報が削除できない

### ISSUE THREAD

**Issue by yupix** [syuilo/Misskey#10279]
## 💡 Summary

誕生日やニックネーム等プロフィールで一度設定した情報を削除できない
フォーラムに建っていたものの移植です。 https://forum.misskey.io/d/114

## 🥰 Expected Behavior

一度設定したプロフィール情報を削除できる

## 🤬 Actual Behavior

以下のように削除できない

![image](https://user-images.githubusercontent.com/50538210/223955772-66a1b56b-acec-4414-8a9e-f396c1aba5ad.png)

## 📝 Steps to Reproduce

1.誕生日やニックネームを設定して保存する
2.誕生日やニックネームをクリアして保存する

## 📌 Environment

Misskey version: 13.9.2
Your OS: Windows 11
Your browser: Microsoft Edge

**Comment by rxy** [comment]
misskey.io , 自分の開発環境 ( 93ea9c20337a652d ) で再現しました。
誕生日だけではなさそうです。

`/api/i/update` に送られるリクエストで、既定値が空 (null) であり、ユーザーがなにも触っていなければ `null` が送られます。
一度設定したものを空にした場合は、`null` でなくて空文字 `""` がセットされて送られることで `nullable` と指定されているものでもエラーが返されるように見えます。

対処方法は二通り思いつきます。
1. backend 側で "" を許容するか、null と置き換える
2. frontend 側で "" を null と処理して `/api/i/update` に送る

**Comment by yupix** [comment]
こちらでも確認したので、Issueのタイトルと内容を変更しました。補足ありがとうございます。
