### ISSUE TITLE
Safariで誕生日を設定するとき、カレンダーとテキストボックスの日付が異なる

### ISSUE THREAD

**Issue by momocus** [syuilo/Misskey#10278]
## 💡 Summary

iOS/Safariで自分の誕生日を編集するとき、カレンダーとテキストボックスに表示される日付がずれている。
未精査だが、たぶん1500年代以前を設定したら起こる。(現実的な1900〜2000年代を誕生日に設定していたら起こらないかも)

## 🥰 Expected Behavior

iOS/Safariで誕生日を入力するとき、カレンダーで選択している日付とテキストボックスの日付が同じになる。

## 🤬 Actual Behavior

`/settings/profile` ページでの誕生日編集時。
カレンダーで333/3/3を選択しているとき、テキストボックスには333/3/2が表示されている。
![image](https://user-images.githubusercontent.com/6294782/223942554-dbeaba10-a866-4ee9-b852-c2e57f38aff7.jpeg )
↓
保存ボタンを押したあと。
`/settings/profile` ページでは、3/2になっている。
![image](https://user-images.githubusercontent.com/6294782/223942691-8d827064-2bf9-4625-8ab0-3b6bdd7894dd.jpeg)

`/@user` のページでは、カレンダーで選択した方の3/3になっている。
![image](https://user-images.githubusercontent.com/6294782/223942910-e15fb308-1d50-463a-af7c-a85dafdf5848.jpeg)

## 📝 Steps to Reproduce

1. SafariでMisskeyを開き、設定→プロフィール でプロフィール編集画面にゆく
2. 誕生日を1500年代以前くらいで設定する

## 📌 Environment

Misskey version: 13.9.1
Your OS: iOS 16.3.1 (20D67)
Your browser: Safari

**Comment by rinsuki** [comment]
純粋にSafariの `<input type="date">` のバグっぽい (単純に `<input type="date">` を置くだけで再現する) ので WebKit/Apple 側にバグレポートしてください

**Comment by fruitriin** [comment]
なんかうるう年周りの処理のような気がする
Safariはバグがたくさん埋まってるからしょうがないね

**Comment by momocus** [comment]
ほんとうだ、[MDNのサンプルコード](https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/date#%E4%BE%8B)でさえiOS Safariだとバグってら……
MacのSafariだとまともに動いたので、iOS Safariだけのバグのようですね。
