### ISSUE TITLE
音楽ファイル再生の際は指定した地点からでも再生が可能なようにしてください

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#10273]
## Summary

要望です。
MP3を貼るとファイルが再生するのは良いのですが、再生バーを動かして指定した場所からの再生もできるようにお願いします。

**Comment by yuriha-chan** [comment]
1. シークバーを移動する
2. 再生ボタンを押す

の操作で指定した場所から再生されませんか？

**Comment by t1nyb0x** [comment]
半年以上返答がないようなのでクローズさせていただきます。
何かありましたら、リオープンお願い致します。
