### ISSUE TITLE
Support for Age Verifcation API like id.me

### ISSUE THREAD

**Issue by TechnicallySky** [syuilo/Misskey#10285]
ピッチ

Misskey のサインアップ プロセス中に id.me のサポートを追加し、API をデフォルトで米国のホスト用に構成する必要があります
モチベーション

ソーシャル メディア プラットフォームがユーザーが 18 歳であるかどうか、またはユーザーが保護者の許可を持っているかどうかを確認することを要求する複数の法律が米国全土で提案されています。

提案された法案は、

https://www.arkleg.state.ar.us/Bills/FTPDocument?path=%2FBills%2F2023R%2FPublic%2FSB396.pdf
https://le.utah.gov/~2023/bills/static/SB0152.html

**Comment by TechnicallySky** [comment]
English 

Pitch

Add support for id.me during the Mastodon sign up process and require api be configured for US hosts by default
Motivation

Multiple laws have been proposed across the United States requiring that social media platforms verify if the user is 18, or the users has parental permissions, failure to verify via a third party provider this could result in serve liability fines.

Bills proposed are

https://www.arkleg.state.ar.us/Bills/FTPDocument?path=%2FBills%2F2023R%2FPublic%2FSB396.pdf
https://le.utah.gov/~2023/bills/static/SB0152.html

**Comment by saschanaz** [comment]
Seems cross-posted https://github.com/mastodon/mastodon/issues/24057

**Comment by acid-chicken** [comment]
> (C) "Social media platform" does not include a social media platform that is controlled by a business entity that has generated less than one hundred million dollars ($100,000,000) in annual gross revenue;

この制約からして該当するサーバーは現時点で存在しないし、その規模のサーバーを営む事業者は自身の責において実装すべきなので、対応不要。

**Comment by TechnicallySky** [comment]
Though my issue is closed, I would like to mention that the Utah bill does not have an exclusion from what I Can see, nor is it impossible that fed is not targeted in the future, While I do not want want to bring politics into a GitHub project,  we must discuss the various ways people in power are targeting social media in general and how US ( the fediverse will resolve that )

**Comment by saschanaz** [comment]
The Utah bill also says:

> 159          (8) "Social media company" means a person or entity that:
> 160          (a) provides a social media platform that has at least 5,000,000 account holders
> 161     worldwide; and
> 162          (b) is an interactive computer service.

There's no AP server that meets such condition. (The largest Mastodon server has less than 1,000,000 accounts, per https://mastodon.social/api/v1/instance, and we should discourage such large server after all. And especially the largest Misskey server has only 100K accounts.)
