### ISSUE TITLE
Linuxディストリビューションによってはサーバーメトリクスのメモリ使用率が不正確になる

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10295]
## 💡 Summary
サーバーメトリクスのメモリ使用率が不正確です

## 🥰 Expected Behavior
サーバーメトリクスのメモリ使用率は、物理メモリのアプリケーションによる（ディスクキャッシュを含めない）使用率を元に計算される

## 🤬 Actual Behavior
サーバーメトリクスのメモリ使用率がswapの使用量（かディスクキャッシュ？）も含めた使用量を元に計算されている  
![Screenshot from 2023-03-11 07-46-56](https://user-images.githubusercontent.com/61890205/224442509-42bf770f-1e4c-42c1-b1ed-acaac49cb2ab.png)

## 📝 Steps to Reproduce

1. swapが使われているサーバーにmisskeyを建てる
2. サーバーメトリクスを見る
3. 

## 📌 Environment

Misskey version: v13.9.2
Your OS: ArchLinux
Your browser: Firefox最新安定版

**Comment by nexryai** [comment]
これはディストリビューションによって発生するようです。CentOS 9 の場合、以下のようにディスクキャッシュがメモリ使用率にカウントされてしまっています。またUbuntu 22.04では発生しないようです。

![image](https://user-images.githubusercontent.com/61890205/234486105-9defdc64-a71c-400e-af73-4171036bdccd.png)

**Comment by nexryai** [comment]
100%を超えることもあるので単純にavailableとfreeを取り違えてるとかではなさそう

![Screenshot from 2023-04-26 21-55-13](https://user-images.githubusercontent.com/61890205/234581590-16a9cc14-870f-4b57-bd0b-03f0573c3f65.png)
![Screenshot from 2023-04-26 21-55-02](https://user-images.githubusercontent.com/61890205/234581606-abe6b39e-c251-495c-a76e-33032681dfed.png)

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/52a1d962189489316667949f15bf6346fad8714e/packages/backend/src/daemons/ServerStatsService.ts#L43

**Comment by tamaina** [comment]
total - availableにしてみるとか？

**Comment by nexryai** [comment]
参考になるか分かりませんが該当環境の/proc/meminfoの値の一部です。色々な環境で試してみましたが知識不足もありこれが原因かは分かりませんでした。が、`total - available`の方が確実である気はします
```
MemTotal:        4011664 kB
MemFree:          225500 kB
MemAvailable:    1847088 kB
Buffers:           68908 kB
Cached:          1808948 kB
SwapCached:           40 kB
Active:          1240240 kB
Inactive:        2118092 kB
Active(anon):     148836 kB
Inactive(anon):  1507428 kB
Active(file):    1091404 kB
Inactive(file):   610664 kB
```

**Comment by nexryai** [comment]
MergeされたのでClose
