### ISSUE TITLE
Reactivity Transform (Ref sugar) Dropped

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10302]
Reactivity Transform (Ref sugar)がドロップされたため、使わない方式に書き換える必要がある

https://github.com/vuejs/rfcs/discussions/369#discussioncomment-5059028

**Comment by futchitwo** [comment]
vue macros で引き継がれてるからそっちで使い続けることもできる
https://vue-macros.sxzz.moe/features/reactivity-transform.html

**Comment by syuilo** [comment]
macro使うか.value使うかどっちが良いかしら

**Comment by syuilo** [comment]
Vue哲学に則って.valueに統一するか

**Comment by syuilo** [comment]
手動で書き換えるの抜けが出たりして大変になることが予想されるのでvolarあたりに変換機能があることを期待したい

**Comment by futchitwo** [comment]
> 手動で書き換えるの抜けが出たりして大変になることが予想されるのでvolarあたりに変換機能があることを期待したい

こういうのがあるっぽい
https://github.com/edison1105/drop-reactivity-transform
https://twitter.com/edison11051/status/1673594046621831168
