### ISSUE TITLE
ノートをクリックしたらノートの詳細を表示する

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#10309]
## Summary

https://misskey.io/notes/97czztwrvq

上記ノートで言及されているように、ノートの投稿時刻をクリックするとノートの詳細が表示される、という仕様を分かりづらいと感じる人は一定数いそうです。
従って、Twitterと同様にノートをクリックしたらノートの詳細が表示される形にすると分かりやすくなりそうです。

**Comment by acid-chicken** [comment]
Duplicate of #8804
