### ISSUE TITLE
schema中のavatarBlurHash/bannerBlurHashの型を絞り込みたい

### ISSUE THREAD

**Issue by Cj-bc** [syuilo/Misskey#10308]
## Summary
`packedUserLiteSchema` 内にある `avatarBlurHash` と `packedUserDetailedNotMeOnlySchema` 内にある `bannerBlurHash` について、現在は `type: 'any'` となっている所を `type: 'string'` と限定したいです。

https://github.com/misskey-dev/misskey/blob/258bd3c9056e3959e9ed72d08da7fc31cc28782e/packages/backend/src/models/json-schema/user.ts#L31-L34
```diff
   avatarBlurhash: { 
-   	type: 'any', 
+   	type: 'string', 
   	nullable: true, optional: false, 
   }, 
```
https://github.com/misskey-dev/misskey/blob/258bd3c9056e3959e9ed72d08da7fc31cc28782e/packages/backend/src/models/json-schema/user.ts#L95-L98

```diff
   bannerBlurhash: { 
-   	type: 'any', 
+   	type: 'string', 
   	nullable: true, optional: false, 
   }, 
```

## 背景
[misskey-hubの`src/.vuepress/api.json`](https://github.com/misskey-dev/misskey-hub/blob/main/src/.vuepress/api.json)のOpenAPIドキュメントを利用してクライアントコードを生成しようとしています。しかし、OpenAPIでは `"type": "any"` が適切なものではないらしくそのままだと利用出来ませんでした。そこで、anyを取り除きたいと考えました。
`"type": "any"` が使われている場所4箇所のうち、現在もmisskeyに残っているのは `avatarBlurHash`/`bannerBlurHash` の2箇所のみとなっているためそこの変更をしたいです。

#### 実際に使用されている場所に於いて、string型を期待されている
Github上で検索をした所、 `avatarBlurHash` は以下の行のみであり、そこで使われている関数は引数としてstringを取るように実装されています。

使われている部分:
https://github.com/misskey-dev/misskey/blob/63df2c851e31a30dda3b7e9edefb2a97e4c1daa6/packages/frontend/src/components/global/MkAvatar.vue#L57

`extractAvgColorFromBlurhash`関数:
https://github.com/misskey-dev/misskey/blob/6c4fa1bc8b814fdb3c1c983da36aec90a0fcaad9/packages/frontend/src/scripts/extract-avg-color-from-blurhash.ts#L1-L9

同様に `bannerBlurHash` についても検索した所、こちらはそもそも実際に使用されている箇所が見付かりませんでした。

#### 似た用途と思われるプロパティはstring型となっている。

又、似た用途であろう `drive-file` 内の `blurHash` はstring型として定義されています。
https://github.com/misskey-dev/misskey/blob/18dbcfa0b09715a234a4eca0288e17d5cbf7622c/packages/backend/src/server/api/endpoints/admin/drive/show-file.ts#L73-L76

#### 型はなるべく厳格である方が良い(個人主観)
これは完全に個人的な主観ではありますが、型は可能な限り厳格に定義しておいた方が良いものと考えています。
勿論言語によって変化することではあると思いますし、時には曖昧さが便利である時もあると思います。
しかし、今回は曖昧にしておく必要性がないように感じたため、issueを建てさせて頂きました。

### OpenAPIv3(JSON schema)的にはanyは不適切な表現である

Misskeyに於いてOpenAPIドキュメントがどういった立ち位置にあるのか分からないため対応する優先度が低いかもしれませんが、OpenAPIドキュメントとしては正しくない出力となっています。

OpenAPIv3内で`Schema Object`の定義に使われている[JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00)に於いて `type: 'any'` というのが有効な値として存在しないようです。 `"type": ` は プリミティブを値に取ると定義されており([Assertions and Instance Primitive Types](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#section-7.6.1))、プリミティブとして定義されている型は `null`/`boolean`/`object`/`array`/`number`/`string` の6種類のみです。

尚、JSON Scheme自体では「JSON Schema Vocabularyでは新しい型システムを定義することが出来る」とありますが、上でも述べた通りプリミティブ型として表現出来そうなのでそれをする必要はないのではないか、と考えています。
(後ここの文章に関しては、プリミティブの型を追加出来るのか否かが若干理解しきれていないです)

> Note that JSON Schema vocabularies are free to define their own extended type system. This should not be confused with the core data model types defined here. As an example, "integer" is a reasonable type for a vocabulary to define as a value for a keyword, but the data model makes no distinction between integers and other numbers.
> > https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-instance-data-model

**Comment by Cj-bc** [comment]
実装自体は簡単なので書いてありますが、意外な影響があったら怖いことと、PRより先にIssueを建てた方が良いように見えたので先に建てさせて頂きました
通してよさそうならPR出します

https://github.com/Cj-bc/misskey/commit/964b747a8f386cf0c66ab5a4a922a76719c3af1b

**Comment by syuilo** [comment]
よさそう

**Comment by Cj-bc** [comment]
ありがとうございます!
PR出す前にテスト回すのを忘れていたので、それが終わり次第PRにして出します

**Comment by Cj-bc** [comment]
closed by #10319
