### ISSUE TITLE
検索を無効化する機能

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10318]
## Summary
Misskeyの検索機能は大変DBに負荷がかかり、小規模なサーバーを使用しているとDBサーバーのCPU使用率が100%近くなる上に2台のSATA SSDでRAID0を組んでいてもディスクアクセスが間に合わずクエリがタイムアウトすることが多々あります。  
DDoSのリスクを減らすためにも、インスタンスの管理者が検索機能を無効にできるかロールで設定できると助かります。  
![Screenshot from 2023-03-13 17-18-39](https://user-images.githubusercontent.com/61890205/224644825-0c3b586d-9835-4036-b83d-afcbeb822dca.png)

**Comment by syuilo** [comment]
これやろうとおもってた
