### ISSUE TITLE
BookWyrm instance links don't open 

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10311]
## 💡 Summary

**BookWyrm** instance links don't open on click

## 🥰 Expected Behavior

**BookWyrm** instance link should open in a new tab as it happens with other Fediverse instances

## 🤬 Actual Behavior

Nothing happens when clicking on `"View on remote instance"`

A user at tomes.tchncs.de in this example.

![mk hw2k com -  2023 - 03 - 12  14 - 38](https://user-images.githubusercontent.com/58190287/224548807-f0087862-d118-49a4-bd89-4daf4759342e.jpg)

## 📌 Environment

Misskey version:  13.9.2
Your OS: Debian 11
Your browser: all

**Comment by saschanaz** [comment]
Indeed the link doesn't have `href` set. `/api/users/show` somehow returns `url: null, uri: (real uri)`.

**Comment by saschanaz** [comment]
Turns out Bookwyrm does not provide `url` field in ActivityPub. I guess either the API or the profile page should fall back to `uri` in this case.

Edit: [The AP spec](https://www.w3.org/TR/activitypub/#actor-objects) says

> url: A link to the actor's "profile web page", if not equal to the value of id. 

So it is optional.

**Comment by ghost** [comment]
I tested the above post / link with a mastodon account. There it works `¯\_(ツ)_/¯`

**Comment by saschanaz** [comment]
Yup, Mastodon correctly falls back. Misskey should too.
