### ISSUE TITLE
Critical error when opening web client in Misskey 13.9.2

### ISSUE THREAD

**Issue by reinhart1010** [syuilo/Misskey#10328]
## 💡 Summary

A critical error with the error code: `APP_IMPORT` with no useful diagnostic data (`{}` when opening the accordion) after upgrading the Misskey version to 13.9.2.

![image](https://user-images.githubusercontent.com/17312341/225100386-02895872-7ed5-4b76-baf6-03c68efb3afc.png)

There's an "invalid character" error on the web console as well.

Note that the affected instance name contains special characters (`(>_ ) (#_ ) ($_ )`), however I have verified that the name is not the cause of the issue and also worked before 13.9.2. https://bots.reinhart1010.id/vite/app-5bf4c53f.js

## 📝 Steps to Reproduce

1. Have an existing pre-13.9.2 instance set up
2. Completely remove the Misskey directory and install from the bash script (v3) with same DB credentials
3. Revisit the website

## 📌 Environment

Misskey version: 13.9.2
Server OS: Ubuntu 22.04 LTS
Your OS: Windows 11
Your browser: Vivaldi 5.3

Also reproducible in Firefox 109 on Android 13, Vivaldi 5.3 on macOS 13

**Comment by futchitwo** [comment]
Do you have Cloudflare auto minify enabled?
Misskey automatically minifies at build time, so this setting is not necessary.
(see https://github.com/misskey-dev/misskey/issues/9791#issuecomment-1416704170)

**Comment by reinhart1010** [comment]
> Do you have Cloudflare auto minify enabled?
> 
> Misskey automatically minifies at build time, so this setting is not necessary.
> 
> (see https://github.com/misskey-dev/misskey/issues/9791#issuecomment-1416704170)

Yes, I have them enabled domain-wide, and it has been working fine for years. I have recently disabled them and still stuck in the same issue.

**Comment by reinhart1010** [comment]
![image](https://user-images.githubusercontent.com/17312341/225980110-54f37e33-69fe-4bdc-8a34-108b5a156b2a.png)
Rebuilt the website today using the same version and it's working

**Comment by reinhart1010** [comment]
Update: Still reproducible in mobile (regardless of private/incognito mode) in Firefox for Android. Works fine on Chrome, though.

**Comment by Smartich0ke** [comment]
I'm still having this same issue across firefox,safari, and chrome on ios 15.8

**Comment by tamaina** [comment]
Misskey only supports the latest iOS.
