### ISSUE TITLE
非ログイン時にインスタンス情報を開き、「I ❤ #Misskey」をクリックするとノート投稿画面が出る

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10327]
## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by CyberRex0** [comment]
duplicate of #9486

**Comment by kakkokari-gtyih** [comment]
記入途中でSubmitしてしまった

申し訳ございません
