### ISSUE TITLE
misskey.jsをこのレポに統合

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10322]
## Summary

新APIの追加のような変化はmisskey.jsも一緒にアプデしないといけないのに、ほとんどアプデされてないのは別のレポであるのが問題だと考えられます。もうworkspace使っているし、こっちで管理したほうがいいと思います

**Comment by tamaina** [comment]
Concrete of #8168

**Comment by syuilo** [comment]
やりたい
