### ISSUE TITLE
ナビゲーションバーから自分のプロフィールを一発で呼び出せるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10330]
## Summary

左端のナビゲーションバーから自プロフィールを開くには、アカウントアイコンをクリック→プロフィールという２つの手順を踏むことになり煩雑なため、こんな感じにナビゲーションバーから一発で呼び出せるようにしてはいかがでしょうか？

![image](https://user-images.githubusercontent.com/67428053/225185970-6fab1159-5511-4302-b32c-baf08e696280.png)

反応が良さそうであれば、PRを立てさせていただきます…！

**Comment by syuilo** [comment]
YOSASOU

**Comment by kakkokari-gtyih** [comment]
やったあ

PRたてますね

**Comment by kakkokari-gtyih** [comment]
デフォルトでこの設定入れておきますか？それとも設定で任意追加にするか

**Comment by syuilo** [comment]
後者で良いかも
