### ISSUE TITLE
通報の管理をロールで制御できるようにして欲しい

### ISSUE THREAD

**Issue by Mogyuchi** [syuilo/Misskey#10359]
## Summary

v13.9.2 でもカスタム絵文字の管理権限のみをポリシー設定で切り替えることができるが、それと同様のことを通報の管理でも行いたい。

関連: #10357

**Comment by syuilo** [comment]
「通報の管理」は通報の一覧の表示と、通報の削除という認識で合っていますか？

**Comment by Mogyuchi** [comment]
そうですね
`コントロールパネル > 管理 > 通報` の UI でできることを指しています。
通報の一覧を表示できることと 「対応済みにする」ボタンを押せることになるでしょうか。

[追記]
可能ならば、未解決しか見られない・対応済みにするボタンは押せない などの設定もできると運用の柔軟性が増してより良いかと思いましたが、当方としては必須要件ではありません。

**Comment by Sayamame-beans** [comment]
モデレーションを分業するような場合に欲しいかもしれないです
(アクセストークンの権限と同じような形で細かく設定出来ると分担しやすいかもしれません)

**Comment by Sayamame-beans** [comment]
duplicate of #3395
