### ISSUE TITLE
お気に入りと同じアクション数で特定のクリップを操作したい

### ISSUE THREAD

**Issue by okinjp** [syuilo/Misskey#10351]
## Summary
お気に入りと同じアクション数で特定のクリップを操作したい。

## Reason
特定のクリップを頻繁に利用するとき、操作が煩わしいため。

## Solution
少ないアクション数でクリップを操作できる仕組みを導入する。

## Ref

> >2アクションあるいは3アクションで削除になるクリップをお気に入りの上位互換と捉えるのは厳しいかと・・・

> クリップをメニューピン留めできるようにするなどして1クリックで入れられるようにすれば済む

_Originally posted by @syuilo in https://github.com/misskey-dev/misskey/issues/10348#issuecomment-1474765768_

**Comment by tamaina** [comment]
まだ実装されていない変更について新しくIssueを建てるのはやめていただきたく…

**Comment by okinjp** [comment]
ごめんなさい、誤爆しました。

**Comment by syuilo** [comment]
まあ現状でもクリップはお気に入りと比べて手順が多いのは事実

**Comment by tamaina** [comment]
本当に収集がつかなくなるので

**Comment by syuilo** [comment]
done
