### ISSUE TITLE
権限周りの問題

### ISSUE THREAD

**Issue by Zel9278** [syuilo/Misskey#10357]
## Summary

権限周りの自由度が低すぎる
用意されたプリセットの中からしか選べないのは辛いし，そのプリセットも「管理者」か「モデレーター」かの2つしかない
プリセットを増やすか，或いは権限設定を自由に変更出来るようにしてほしい

**Comment by syuilo** [comment]
個々のポリシー設定では不十分ということですか？
具体的に必要になる権限を教えてください。

**Comment by Mogyuchi** [comment]
@syuilo 
要件把握しているので代わりに答えます。

> 具体的に必要になる権限を教えてください。

具体的に述べますと、今現在当方のサーバーで必要となっているのは、通報を管理する権限です。
実現したいことは、「一般ユーザーの権限 をベースに 通報を管理する権限のみ追加で与えたロール」を作成することとなります。

---

現状でもカスタム絵文字の管理のみをポリシー設定で与えるということができますが、それと同様なことを(通報に限らず)他の管理項目でも行いたいというのが本issueの趣旨となります。

**Comment by syuilo** [comment]
なるほど
それでしたらその必要になる権限ごとにIssueを作成いただければ助かります。
例: 通報の管理をロールで制御できるようにして欲しい

**Comment by Mogyuchi** [comment]
承知いたしました。
こちらの issue は閉じた方がよろしい ~~でしょうか。~~ のであればそちらで閉じてくださいませ。

**Comment by Sayamame-beans** [comment]
#10359
