### ISSUE TITLE
エクスポートデータの拡張子が壊れている

### ISSUE THREAD

**Issue by na2204** [syuilo/Misskey#10368]
## 💡 Summary
`インポートとエクスポート`でエクスポートされたデータの拡張子の末尾に不要な`.unknown`が付いている

## 🥰 Expected Behavior
`hoge.json`や`hoge.csv`の形式で出力される。

## 🤬 Actual Behavior
`hoge.json.unknown`や`hoge.csv.unknown`の形式で出力される。

## 📝 Steps to Reproduce

1.設定から`インポートとエクスポート`を開く
2.適当な項目をエクスポートする
3.ドライブで確認する

## 📌 Environment

Misskey version: 13.9.2
Your OS: iOS16.3.1
Your browser: Safari

**Comment by syuilo** [comment]
@tamaina 確認してもらえると助かる

**Comment by tamaina** [comment]
把握してる

csvがbrowsersafeではないのでこうなる

**Comment by tamaina** [comment]
txtじゃなくてunknownだからテキストファイルとしては認識されてないってことか

**Comment by tamaina** [comment]
FILE_TYPE_BROWSERSAFEにtextが含まれていないだけだわ

**Comment by tamaina** [comment]
でもfileTypeFromFileにtxtやcsvを食わせてもundefinedが返ってきた

**Comment by tamaina** [comment]
> This package is for detecting binary-based file formats, not text-based formats like .txt, .csv, .svg, etc.
https://www.npmjs.com/package/file-type

はい
