### ISSUE TITLE
投稿に2回リアクションをつけると取り消せない

### ISSUE THREAD

**Issue by na2204** [syuilo/Misskey#10372]
## 💡 Summary
任意の投稿に、任意のリアクションを選択した際に、1度目は取り消しができますが2度目以降でリアクションを選択した際に取り消しができません。(少なくともUI上で)

## 🥰 Expected Behavior
何度リアクションを付け直してもリアクションをつけたり消したりできる

## 🤬 Actual Behavior
2回目以降でリアクションを付け直そうとすると取り消せない

## 📝 Steps to Reproduce

1.任意の投稿にリアクションを選択
2.リアクションを取り消す
3.再度、同投稿にリアクションを選択
4.リアクションを取り消す

## 📌 Environment

Misskey version: 13.9.2
Your OS: iOS16.3.1 / iPadOS16.3.1
Your browser: Safari(PWA)

**Comment by saschanaz** [comment]
多分rate limitじゃないでしょうか。いまでも取り消せませんか？

**Comment by na2204** [comment]
説明不足でした。リアクションが取り消せなくなる問題はリロードをすることで正常に取り消すことができます。なのでレートリミットの問題ではないと思います。
画像のようにリアクションの選択と取り消しを1回以上繰り返した時にリアクションが取り消せなくなる問題が発生します。
![image](https://user-images.githubusercontent.com/78205092/226452926-0fb6b66a-8547-4921-9c67-9f11474640b1.png)

**Comment by saschanaz** [comment]
>リアクションが取り消せなくなる問題はリロードをすることで正常に取り消すことができます。なのでレートリミットの問題ではないと思います。

レートリミットはかなり早く解除されます。何秒間待ってまた取り消してみればどうなりますか？

**Comment by saschanaz** [comment]
https://github.com/misskey-dev/misskey/blob/75888a55c35eb8bb81186fc44abcf7d476db6d74/packages/backend/src/server/api/endpoints/notes/reactions/delete.ts#L15-L19

ちなみにリアクション取り消しは3秒に一回に限定されていて、それ以上に早くしたらレートリミットにかかります

一回消したあとまた消す場合はそのレートリミットにかかることになると。

Edit:  すみません一秒じゃなくて3秒でした

**Comment by na2204** [comment]
(Machine translation)
I'm saying it's not a rate limit issue.  I'm not sure if this is an iOS specific issue or a global issue, but at least I don't think it's a rate limit issue.

(Original)
私はレートリミットの問題ではないと言っています。これがiOS特有の問題か全体的な問題かは確認していませんが、少なくともレートリミットの問題では無いと思います。

**Comment by saschanaz** [comment]
リフレッシュしたら取り消しできるからレートリミットじゃないとは言えないです

実際パソコンのウェブブラウザで同じことをしたらF12 consoleにこんなエラーがでます

>Uncaught (in promise) 
>Object { message: "Rate limit exceeded. Please try again later.", code: "RATE_LIMIT_EXCEEDED", id: "d5826d14-3982-4d2e-8011-b9e9f02499ef", kind: "client" }

何秒間待ってまた試してみたら今度はできるようになります

**Comment by na2204** [comment]
私のPC環境(Win11)で検証してみたところ、特にエラーやレートリミットによる制限は発生しませんでした。(正常に動作)
そのため、この問題はiOS特有、または携帯端末の問題の可能性が高いです。

**Comment by saschanaz** [comment]
うむ…設定は確かに3秒に一度だけ許可するようになっていて、こう再現できますが

[video-misskey2.webm](https://user-images.githubusercontent.com/3396686/226459349-a041618c-160d-45b8-bcfa-4303216ff3b8.webm)

なぜかmisskey.ioでは再現できませんでした

3秒に一回はちょっとハードル高くないかなと思います（ノートの取り消しは一秒に一回ですのでもっと緩いです）

**Comment by na2204** [comment]
先程までの発言を全て訂正します。

あなたが言ったようにレートリミットによる制限に引っ掛かっていたようです。

PCとモバイル端末でレートリミットの間隔が異なるのか、(秒針を聞きながら)ほぼ同じ感覚で操作した場合でもPCではレートリミットのエラーになることはなく正常に動作していたため気がつくことができませんでした。(PCでは1秒、モバイル端末では2-3秒程度待つ必要がありそうです)

ありがとうございました👍
