### ISSUE TITLE
An error occurs when you press the Play button of Misskey Play / Misskey PlayのPlayボタンを押した時にエラーが発生する

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#10381]
## 💡 Summary

v13.10.0 で Misskey Play の Play ボタンを押すとエラーが表示されます。Play は実行可能です。
An error is displayed when pressing the Play button of Miisskey Play in v13.10.0. Play is executable.

## 🥰 Expected Behavior

エラーは発生せず、Play が実行されます。
Play runs without error.

## 🤬 Actual Behavior

Playボタンを押した時に次のAIScriptエラーが表示されます。
I get the following AIScript error when I press the Play button.
```
AiScript Error
Cannot read properties of undefined (reading 'type')
```

## 📝 Steps to Reproduce

1. Play へ移動する / Go to Play
2. 適当な Play へ入り、Play ボタンを押す / Enter the appropriate Play and press the Play button

## 📌 Environment

Misskey version: v13.10.0 (Includes development version from v13.9.2 to v13.10.0)
Your OS: Windows 10 (Encounter regardless of OS)
Your browser: Google Chrome 111.0.5563.110 (egardless of browser)

**Comment by fu-sen** [comment]
Servers with known errors
- https://mattyaski.co/ (v13.10.0, Updated immediately after release)
- https://warpday.net/ (v13.9.2, but on the way to v13.10.0)

**Comment by kanoekakihito** [comment]
warpday.netでのエラーに関して数日前にディスカッションで書いたので、リンクを貼っておきます。

[Misskey Playでの不具合報告（Ui:render実行時にエラーダイアログ表示が出る）](https://github.com/misskey-dev/misskey/discussions/10346#discussion-4974888)

環境：Misskey 13.9.2(13.10.0の開発途中版)、AiScript 0.13.0。
現象：Ui:render関数を使用すると画面に「AiScript Error Cannot read properties of undefined (reading 'type')」のダイアログが表示されます。レンダリングそのものは成功しているものの、実行のたびにエラーダイアログが表示されています。
再現手順：同環境のスクラッチパッドにてUi:render([])を実行すると再現できます。

補足１）アップデート前後でソースコードの変更がないMisskey Playアプリでも上記ダイアログが出たのを確認しています。更新前については当該Play群を触ったことがありませんが、特にダイアログの話は出ていませんでした。
補足２）コンソールから確認したところ、AiScript/src/interpreter/index.tsのInterpreterクラス、_runメソッドにてUi:renderを実行後の返り値がオブジェクト({type: null})ではなくundefinedになっているせいで、直後に実行結果のtypeプロパティを読み出そうとして失敗している模様です。
