### ISSUE TITLE
返信・引用 RN で時間と絵文字アイコンが重なる / Reply or quote RN overlaps time and emoji icon

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#10391]
## 💡 Summary

v13.10.0 より投稿フォームの絵文字ピッカーを表示するアイコンの場所が変わっていますが、返信または引用 RN を行う場合に時間と重なって表示されます。
From v13.10.0, the location of the icon that displays the emoji picker on the submission form has changed, but it will overlap with the time when replying or quoting.

reference (from [-akku-](https://misskey.04.si/@akku) )
https://discord.com/channels/874926746745569280/874926746745569283/1088070574758178897
https://misskey.04.si/notes/9cn74t8qkn

## 🥰 Expected Behavior

返信・引用 RN の場合は時間の下にずらして表示されるのが理想です。
In the case of reply/quote RN, ideally the icon should be displayed staggered under the time.

## 🤬 Actual Behavior

重なって表示されてしまいます。
displayed overlapping

## 📝 Steps to Reproduce

1. v13.10.0 以降で任意のノートから 返信 または RN - 引用 操作を行う
Reply or Quote from any note in v13.10.0 or later

## 📌 Environment

Misskey version: v13.10.0-v13.10.2
Your OS: Windows 10 (any environment)
Your browser: Chrome 111.0.5563.111 (environment except for some apps)

**Comment by tamaina** [comment]
Duplicate of #10390
