### ISSUE TITLE
リモートユーザーの検索について正しく検索できていない様子がある

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#10393]
## 💡 Summary

13.9.2までとユーザー検索の挙動が異なっているように見受けられる。

## 🥰 Expected Behavior

- `@<username>@<server-domain>` 形式で検索すると該当の人物が表示される
- 入力が停止したら一定時間で自動的に検索が走る（コレは不便であればas isを仕様とするのもアリだと思う）

## 🤬 Actual Behavior

13.9.2までは検索欄に `@<username>@<server-domain>` 形式で入力し検索すると
該当ユーザーが表示されたが、「ユーザーはいません」となる。
このとき、 `@<username>` のみで検索すると該当するユーザーが表示される場合がある。
また、今までは自動で検索が走っていたが、走らなくなった。（Change Logに無い様に見受けられたのでバグでは無いか）

## 📝 Steps to Reproduce

1. 検索ページに進む
2. ユーザー検索タブに移動する
3. `@<username>@<server-domain>` 形式で検索する

## 📌 Environment

Misskey version: 13.10.2
Your OS: Windows 11 / OS X Ventura / iOS 16.3.1
Your browser: Google Chrome / Safari

**Comment by tamaina** [comment]
> 13.9.2までとユーザー検索の挙動が異なっている

仕様です。メニューから「照会」を選択してください。
