### ISSUE TITLE
投稿ダイアログの絵文字ピッカーの場所が変？

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10390]
## 💡 Summary
![image](https://user-images.githubusercontent.com/18308639/226897230-212ecb62-8dce-456e-aad1-1517e99eff7e.png)

## 🥰 Expected Behavior

他のメニュー項目と並んでいる

## 🤬 Actual Behavior

リアクションピッカーが投稿ダイアログの右上にある
連合してないときの警告や、入力の文字と重なる場合もある

## 📝 Steps to Reproduce

1.13.10.2にアップデート
2.投稿ダイアログを開く
3.

## 📌 Environment

Misskey version: 13.10.2
Your OS: iOS 16.3.1
Your browser: Safari

**Comment by tamaina** [comment]
バグではないけどとても悪い仕様変更

（解決策募集中）

**Comment by tamaina** [comment]
![IMG_0244.jpeg](https://user-images.githubusercontent.com/7973572/226908978-b4f0a9c7-afe0-498b-8c54-da8324af026c.jpeg)

個人的な案

**Comment by fruitriin** [comment]
スマホ的にはよく使うボタンは下の方にある方がさわりやすい

**Comment by 417Nazuna** [comment]
PCだとこんな感じで入力してる最中の文章にかぶって非常に邪魔です！！
![image](https://user-images.githubusercontent.com/53173999/227835455-52544027-4df7-4758-ac4c-552c25a286cf.png)

**Comment by tamaina** [comment]
これだけはどうにかしないと…

**Comment by tamaina** [comment]
> スマホ的にはよく使うボタンは下の方にある方がさわりやすい

じゃあヘッダーの下でいいか…

**Comment by tamaina** [comment]
MkPostFormをそこそこ改造している
