### ISSUE TITLE
ノートのURLを検索箱に入れたときに表示してくれない

### ISSUE THREAD

**Issue by Steve-0628** [syuilo/Misskey#10397]
## 💡 Summary

タイトルのとおりです。リモートのノート、ローカルのノート、のどちらでも発生します。

## 🥰 Expected Behavior

これまで(具体的なバージョンは不明)は、そのノートが開かれていました。

## 🤬 Actual Behavior
ノートはありません、と表示される

## 📝 Steps to Reproduce

1. ノートする
2. URLをコピーする
3. ノートが見つからない

## 📌 Environment

Misskey version: v13.10.2 / v13.10.2 fork
Your OS: Windows 11 Pro
Your browser: Firefox 111.0.1

**Comment by syuilo** [comment]
これは仕様になります。
URLからノートを開きたい場合はメニューから「照会」を選択してください。

**Comment by ghost** [comment]
なに！?

2023年3月23日(木) 18:10 Acid Chicken (硫酸鶏) ***@***.***>:
