### ISSUE TITLE
存在しない長いリアクションコードを使ったらoverflowする

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10396]
## 💡 Summary

タイトル通り

## 🥰 Expected Behavior

overflowしない

## 🤬 Actual Behavior

overflowする

## 📝 Steps to Reproduce

1.　`:three_black_circles_with_white_outlines_are_too_simple_and_therefore_ineligible_for_copyright_protection__publicdomain:`を入力
2. どうなるのか確認

## 📌 Environment

Misskey version: 13.10.2-p1.1
Your OS: macOS 13.2.1
Your browser: Firefox

**Comment by KawaneRio** [comment]
Misskey `13.10.3` では再現しにゃいね。 
![image](https://user-images.githubusercontent.com/61252570/227760337-dfdb2346-6b8e-42e5-9a41-46b9a843be0a.png)
OS: `Ubuntu 22.04.2 LTS`
Browser: `Mozilla Firefox 111.0.1`

**Comment by saschanaz** [comment]
あ、これ絵文字コードじゃなくMFMのせいでした
それなら多分想定内ですのでcloseします!
