### ISSUE TITLE
カスタム絵文字のお気に入り機能(フォルダ)について

### ISSUE THREAD

**Issue by kagiroi** [syuilo/Misskey#10401]
## Summary
現在カスタム絵文字の総数が3000を超えたということで、目当ての絵文字を見つけるのも一苦労になってきました。
そこで、カスタム絵文字に☆マーク等お気に入り機能のフラグをたてて、自分専用のカスタム絵文字フォルダを作って欲しいです。（100個以上、出来れば無制限）
場所としては、ノートの絵文字選択ウィンドウの、最近使用とカテゴリフォルダの間がいいです。
![image](https://user-images.githubusercontent.com/128761263/227397002-59b5141f-0b0f-4261-8dfa-a94cfe061c32.png)

お忙しいとは思いますが、何卒よろしくお願いいたします。

**Comment by futchitwo** [comment]
設定→リアクションから任意の絵文字を絵文字ピッカーのトップに設定できます。
また、絵文字を大量に登録していた場合、フォルダ分けをしていてもおそらく探すのに時間がかかるので、絵文字検索機能などを併用することも検討してみてください。
