### ISSUE TITLE
CSS bugs for cat ears in user profiles on iPad

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#10413]
## 💡 Summary
Recent redesign of cat ears (#10039) results in CSS bugs for cat ears in user profiles on iPad.

## 🥰 Expected Behavior

Cat ears should look normal both on the header and on the main profile panel.

<img width="701" alt="Screen Shot 2023-03-26 at 1 02 18 pm" src="https://user-images.githubusercontent.com/106132975/227751238-bd11b544-4f40-4780-873a-4161dbb6dde2.png">

## 🤬 Actual Behavior

On the header the cat ears is not showing up normally and on the main panel the cat ears appear to have different colors on different sides.

![3C18E924-B0CB-4C80-8236-2C6660A51BD1 jpeg copy](https://user-images.githubusercontent.com/106132975/227751309-a2201f2a-7eab-4af9-a54f-95718419c89e.jpg)

## 📝 Steps to Reproduce

1. Use an iPad
2.  Open a v13.10.3+ instance
3. Open a profile with the user set themselves as a car

## 📌 Environment

Misskey version: v13.10.3
Your OS: iPadOS v16.3.1
Your browser: Safari

**Comment by acid-chicken** [comment]
水玉が出る問題はここを切ると直るけどなぜそうなるのか謎

https://github.com/misskey-dev/misskey/blob/a529b0e5a3421dd9f14d48b54f298d0e447419d3/packages/frontend/src/components/global/MkPageHeader.vue#L244

**Comment by acid-chicken** [comment]
> https://github.com/misskey-dev/misskey/blob/a529b0e5a3421dd9f14d48b54f298d0e447419d3/packages/frontend/src/components/global/MkPageHeader.vue#L244

この `overflow` 自体挙動おかしくない？

**Comment by tamaina** [comment]
> この overflow 自体挙動おかしくない？

おかしい

**Comment by acid-chicken** [comment]
@tamaina #10420 でひとまず抑制できたはずなので見てほしい

**Comment by acid-chicken** [comment]
> on the main panel the cat ears appear to have different colors on different sides.

I forgot to mentions this, but this is the expected behavior for now.
