### ISSUE TITLE
13.10.3 Broken image uploading (Object Storage)

### ISSUE THREAD

**Issue by RaZZlom** [syuilo/Misskey#10419]
## 💡 Summary

After uploading image to drive can't open this image.

## 🥰 Expected Behavior

See image.

## 🤬 Actual Behavior

"The image cannot be loaded" error.

When copy image URL from drive and open it in new tab "Not Found The resource could not be found." error.

![Screenshot 2023-03-26 at 11-47-56 A Quiet Place](https://user-images.githubusercontent.com/73530026/227765340-f438f23c-b655-4a08-b3df-0019bd6ea357.png)
![Screenshot 2023-03-26 at 11-50-30 A Quiet Place](https://user-images.githubusercontent.com/73530026/227765345-c512403d-d4a2-4633-9d0b-28af0a6ea7da.png)
![Снимок экрана от 2023-03-26 11-51-13](https://user-images.githubusercontent.com/73530026/227765358-72868012-c102-4cea-9c17-bfac36764af7.png)

## 📝 Steps to Reproduce

1. Upload image to drive.
2. Post note with this image.

## 📌 Environment

Misskey version: 13.10.3
Your OS: Debian GNU/Linux 11 (bullseye) x86_64
Your browser: Firefox, Vivaldi Android.

**Comment by nexryai** [comment]
Please check #10408

**Comment by RaZZlom** [comment]
> Please check #10408

I don't have `Error: Region is missing` and region in Control Panel filled.

**Comment by nexryai** [comment]
Please check that you have only the domain (like `example.com`, not `https://example.com`) set in the endpoint settings. If it still does not work, try changing the value of `s3ForcePathStyle`.

**Comment by RaZZlom** [comment]
> Please check that you have only the domain (like `example.com`, not `https://example.com`) set in the endpoint settings. If it still does not work, try changing the value of `s3ForcePathStyle`.

Oh, this works. But with previously versions of Misskey i don't have this error. :thinking: 
Thank you very much, @nexryai ! :heart: 

> Leave this empty if you are using AWS S3, otherwise specify the endpoint as '<host>' or '<host>:<port>', depending on the service you are using.

Maybe need to improve this help message?

**Comment by nexryai** [comment]
> Maybe need to improve this help message?

In PR #10410, if the region is set to empty, Misskey will use the value `undefined` for the region to prevent errors. So from the next version, there should be no problem even if the region is empty. However, I think that explanations should be added to important configuration items such as `s3ForcePathStyle` and that major changes should be made known in CHANGELOG.

**Comment by yszkst** [comment]
> if the region is set to empty, Misskey will use the value undefined for the region to prevent errors.So from the next version, there should be no problem even if the region is empty.

This is not correct.  Region is necessary for aws-sdk even if the object storage service don't use Region.    
If specified region is empty, aws-sdk trys to find a value from a config file or environment variables.

This is a clear explanation. 
https://docs.digitalocean.com/products/spaces/reference/s3-sdk-examples/
> Due to an AWS-specific behavior in all versions of the SDK except Python 3, to successfully create a new bucket, you must specify an AWS region, such as us-east-1, in your configuration. This is because, when creating a bucket, the SDK sends an entirely different payload if a custom region is specified, which results in an error. Region does not affect any other examples listed in this page.

This issue's error behaivor comes from #10363 with bump aws-sdk version from v2 to v3.  I missed out the spec chages and including them to CHANGELOG and updating descriptions on the form.
