### ISSUE TITLE
カスタム絵文字名に"-"が含まれるのを許容したい

### ISSUE THREAD

**Issue by totegamma** [syuilo/Misskey#10423]
## Summary
現状[emoji/add](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/admin/emoji/add.ts#L51)では`/^[a-z0-9_]+$/`、[emoji/update](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/admin/emoji/update.ts#L34)では`^[a-zA-Z0-9_]+$`、[CustomEmojiService](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/CustomEmojiService.ts#L88)では`/^(\w+)(?:@([\w.-]+))?$/`のvalidateが入っており、どれもカスタム絵文字中に"-"が含まれるのを許容しない。

ところが、組み込み絵文字では`-1`や`e-mail`など、"-"が含まれている。

組み込み絵文字で使われている文字が、カスタム絵文字で使用できないのはちょっとかなしい。
ので、ルールを`/^[\w-]+$/`に統一したい。

**Comment by rinsuki** [comment]
Mastodonとかとの相互運用性がアレなのと - と _ の両方あるとややこしい

**Comment by acid-chicken** [comment]
`-` は単語選択で区切りになってしまいがちなのがつらいのと、そもそも組み込み絵文字と*後から*被ると競合してしまうので組み込み絵文字的なスラングは避けるのが無難みたいな気持ちがあります

**Comment by totegamma** [comment]
> Mastodonとかとの相互運用性がアレ

たしかに！　これは結構クリティカルですね。misskeyがmastodonに歩み寄るべきなのだとすると、そうかもしれません。

>  `-` と `_` の両方あるとややこしい

これはある程度同意はしつつ、実際に混乱を招くようであればサジェスト側で解決する問題なような気もします。

> そもそも組み込み絵文字と後から被ると競合してしまうので組み込み絵文字的なスラングは避けるのが無難みたいな気持ち

たしかに～～という感じはしつつ、'-'が含まれない組み込み絵文字が追加されてもカスタム絵文字と衝突する可能性はあるので、`-`が含まれるものだけでも分離するほどなのか？という気持ちはなくはないですね。


使えてもいいんじゃないかな～～～くらいの温度感ではあるので、他に同意される方がいなかったらほどなくしてcloseしようと思います。

**Comment by MineCake147E** [comment]
検索窓で文字`_`が条件`-`にヒットするようにするのはどうでしょうか。
`_`はPCだとShiftキーを押さないと入力できない他、スマホキーボードだと記号一覧でしか入力できないソフトもある(実際GBoardの12キーには`_`を記号一覧を開かずに直接入力できる方法が辞書登録以外ない)ので、サジェストのみ`-`で`_`を検索できるようにするのがいいと思います。

**Comment by totegamma** [comment]
絵文字をエクスポートしたときの互換性かな？とも思いましたが、ハイフンが含まれているノート(as toot)は普通にmastodonから絵文字として見えなくなっちゃうんですね。これはダメかも。Closeします。

**Comment by totegamma** [comment]
#8905 が実現されるのであればその際にこの辺が再考される余地はある気がするのでメモ
