### ISSUE TITLE
Fediverse/ActivityPub account migration

### ISSUE THREAD

**Issue by parpok** [syuilo/Misskey#10426]
# Feature in question

Add better support for importing/exporting accounts made across different Fediverse/ActivityPub-based platforms.
Misskey already supports imports and exports, however, it's very limited. Can't move posts or favourites from 1 account to another, the only moveable things are lists of users, followers, mutes and blocks. 

## Why add such a feature

Services like Mastodon or even Plernoma offer such features. 
Sure it's mostly because their account data import/export has more data compared to Misskeys, but weren't all those Fediverse applications about interoperability? It's cool being able to communicate with people who use different services from my Misskey instance and having more migration features working would it make a more interoperable SNS.
Also having account migration could be one of many reasons to try it since it could let people try it out without losing their posts and the community they've gathered.

### Is it possible?
In theory yes - there are already Misskey forks like Calckey that include Fediverse migration features
Also, the fact that services like Mastodon or Pleroma have them should already say that it is possible

**Comment by tamaina** [comment]
I am aware that the posts cannot be transferred.

As follower migration: #5475

**Comment by tassoman** [comment]
This is [documentation for mastodon](https://docs.joinmastodon.org/user/moving/)

**Comment by kallisti5** [comment]
This would be nice (tm).    Posts can't be transferred, but followers could be theoretically if Misskey supported this.

**Comment by tassoman** [comment]
Already solved into #10592. Since summer 2023 (13.11.x).
Can be closed.

**Comment by kallisti5** [comment]
Oh! You're right!  ```/settings/migration``` for anyone else lurking.  Thanks!
