### ISSUE TITLE
Impossible to "import" note by URL in search.

### ISSUE THREAD

**Issue by RaZZlom** [syuilo/Misskey#10435]
## 💡 Summary

Previously, you could "import" a post to an instance by entering its URL in the search box. In version 13.10.3 an error appears instead.

## 🥰 Expected Behavior

Open the post after entering a link in the search box.

## 🤬 Actual Behavior

Error after entering a link in the search field.
![Screenshot 2023-03-29 at 11-09-59 A Quiet Place](https://user-images.githubusercontent.com/73530026/228470266-d016a3f1-5b32-4d89-8e1b-c08e4babe1be.png)

## 📝 Steps to Reproduce

1. Click search.
2. Type URL.

## 📌 Environment

Misskey version: 13.10.3
Your OS: Debian
Your browser: Firefox, Vivaldi

**Comment by RaZZlom** [comment]
Found this in CHANGELOG.md

> APオブジェクトを入力してフェッチする機能とユーザーやノートの検索機能を分離

Translation by Deepl

> Separated the function of typing and fetching AP objects from the function of searching users and notes

So, it's not possible to "import" note by URL in search box anymore?
How i and users can "import" notes now?

**Comment by dakkar** [comment]
there's now a "look up" function, which may be hidden under the "more" icon on the navigation bar
![image](https://user-images.githubusercontent.com/86328/228643996-b2f0973c-9582-46c6-9bd1-21501be541f7.png)

that function works with URLs

(yes, some clearer notes in the Changelog would have been nice)
