### ISSUE TITLE
duplicated results for user search

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#10432]
## 💡 Summary

searching for users, some results are duplicated

## 🥰 Expected Behavior

I don't expect to find duplicated cards of the same profile

## 🤬 Actual Behavior

![immagine](https://user-images.githubusercontent.com/92727/228370655-f2d5f3a8-ae05-4d6c-865d-dfd03745d075.png)

## 📝 Steps to Reproduce

1. open new user search page
2. search an user
3. see same profile twice

## 📌 Environment

Misskey version: 13.10.3
Your OS: docker
Your browser: any

**Comment by tassoman** [comment]
First and last are duplicated (local profile)

![immagine](https://user-images.githubusercontent.com/92727/228371336-b14d99b0-264c-41c2-9b7a-4ab1b0dabd8f.png)

**Comment by Nanashia** [comment]
confirmed.

/search の ユーザー検索は users/search エンドポイントを使いますが、 users/search はuntilId指定をサポートしておらずoffset指定のみです。
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/users/search.ts#L130

しかしfrontendではoffsetModeをしておらず、 untilIdでpaginationしようとします。
https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/pages/search.vue#L97

結果としてpaginationができておらず、検索結果の先頭ユーザーが繰り返し表示されてしまっています。

**Comment by tassoman** [comment]
In version 13.13.2 this has been transformed into an endless infinite loop search  😆

[Kazam_screencast_00029.webm](https://github.com/misskey-dev/misskey/assets/92727/ee6415a7-bc37-43d7-b099-873d8bd115ba)

**Comment by tassoman** [comment]
Fixed in 2023.11.0   
Can't reproduce
