### ISSUE TITLE
リストタイムラインが殆どのミュートを貫通する

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#10443]
## 💡 Summary

リストタイムラインが以下のミュートを尊重せず、投稿を貫通してしまう不具合がある。HTTP APIとストリーミングの両方で確認済み。

* ユーザーミュート
  * RenoteやReply経由で貫通する
* ワードミュート
* サーバーミュート
* チャンネル投稿
  * ミュートとは違うが、そもそもフォローしていないチャンネル投稿が引っかかるのはあんまり良くなさそう

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: Misskey 13.10.3
Your OS: Windows 11
Your browser: Chrome

**Comment by tamaina** [comment]
user-list-timelineエンドポイントだけブロック・ミュートのクエリが書かれていない（どうしてかは知らないので手出ししてない

**Comment by EbiseLutica** [comment]
joinとサブクエリ地獄になって機能しなくなるから説はありそう

**Comment by EbiseLutica** [comment]
直すためにはおそらく #9325 が必須？

**Comment by tamaina** [comment]
> 必須？

必須というわけではないのでは（ただ単に忘れたと推測してる

**Comment by anatawa12** [comment]
~~issue探し忘れてましたが #11480 で治ってるかもです~~

**Comment by anatawa12** [comment]
streamの方のワードミュートは確認してないので治ってないかもですがuser muteはそれっぽい実装あります

https://github.com/misskey-dev/misskey/blob/ec229dbd3b50fdb644dd9e6903e0544be21e55f1/packages/backend/src/server/api/stream/channels/user-list.ts#L98-L101

nirila鯖でのユーザからのレポートによりユーザミュートはstreamでは動いてるっぽいという報告があります

**Comment by samunohito** [comment]
（ミュート貫通系はちょっと気になってる）

@syuilo 
2点ほど確認させてほしいです（良さげなら👍だけでも）

①あえて現状にしているわけではない…で相違ございませんか？

②①がYesの場合、手を入れる方針としては以下で問題ございませんか？

- ユーザーミュート
→考慮する。Renote先やReply先にミュートユーザがいる場合はリストに流さない
- ワードミュート
→考慮しない。フロント側に移ったので
- サーバーミュート
→考慮する。ミュートしたサーバであればリストに流さない
- チャンネル投稿
→考慮する。自分がフォローしていないチャンネルに対しての投稿はリストに流さない

**Comment by anatawa12** [comment]
チャンネルについてはチャンネルフォローしたくないけどみてたい、または逆があるから選択可能にしてほしいです

**Comment by syuilo** [comment]
> ①あえて現状にしているわけではない…で相違ございませんか？

yes

> ②①がYesの場合、手を入れる方針としては以下で問題ございませんか？

yes

**Comment by syuilo** [comment]
> チャンネルについてはチャンネルフォローしたくないけどみてたい、または逆があるから選択可能にしてほしいです

これは他のTLでも言える話だから別Issueかな
