### ISSUE TITLE
迷惑になる可能性のある投稿について、設定中の公開範囲を考慮するようにしたい

### ISSUE THREAD

**Issue by na2na-p** [syuilo/Misskey#10455]
## Summary

一番目立つボタンがホームへ投稿になっています。
これ自体は役に立つ機能かと思いますが、仮にfollowersで投稿した際にも出てしまうのは不便に感じています。
そこで、公開範囲がpublicの場合にのみこちらの確認モーダルを出すようにしたいのですがどうでしょうか？

![image](https://user-images.githubusercontent.com/49822810/229391540-8f6ddc05-404f-4e86-aa31-78015fed101e.png)

## 備考

必要ならすぐPR出せます

**Comment by acid-chicken** [comment]
Duplicate of #9947

**Comment by acid-chicken** [comment]
とはいえバグも同然だとは思うので PR は歓迎します。

**Comment by na2na-p** [comment]
こっちcloseしますね
