### ISSUE TITLE
Notification TableにnoteIdのIndexが存在しない？

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10459]
## 💡 Summary
表題どおり

もしかしたら投稿の削除時に極端に重くなることがあるのが改善するかも
（NoteのCascade Deleteの対象にNotificationが含まれているので）

スロークエリログは見たけどプレースホルダがわかんなかったのでEXPLAINまではしてない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
今NotificationをRedis上に保存するようにしてるからそれで解決しそう

**Comment by syuilo** [comment]
↑やった
