### ISSUE TITLE
RedisにReplyError: ERR Invalid stream ID specified as stream command argumentと言われる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10464]
アンテナ, 通知保存系でReplyError: ERR Invalid stream ID specified as stream command argumentと言われる

```
ReplyError: ERR Invalid stream ID specified as stream command argument
    at parseError (/home/misskey/misskey/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/misskey/misskey/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xadd',
    args: [
      'p1.a9z.dev:notificationTimeline:8mlfoo032b',
      'MAXLEN',
      '~',
      '300',
      '1680586162655-*',
      'data',
      '{"id":"9d5dx7mnxd","createdAt":"2023-04-04T05:29:22.655Z","type":"reaction","notifierId":"8z3f8hha6z","noteId":"9d5dvmqkt7","reaction":":igyo2@misskey.04.si:"}'
    ]
  }
```

### ANSWER: HOW TO RESOLVE THIS ISSUE
You must upgrade redis to 7.

**Comment by tamaina** [comment]
なんか呪文が必要とかなのかしら

**Comment by syuilo** [comment]
Redisのバージョン古い可能性とかない？

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/229696508-4e6dd86e-fc09-4e49-8273-c8b2938db75c.png)

7じゃないとダメか

**Comment by syuilo** [comment]
かも

**Comment by tamaina** [comment]
PostgreSQLのバージョンが新しすぎるとマネージドDBが対応していない問題があるけど、Redis 7はAmazon ElastiCacheは対応してるからひとまず大丈夫？

**Comment by tamaina** [comment]
Redis 7にしたら通知やアンテナが永続化されるようになった

**Comment by tamaina** [comment]
（バージョンとかのせいだろうなと思いつつ、検索される可能性があるのでとりあえずIssueを書いてみた）

**Comment by willin** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1890238/235494025-c16be112-4935-48ce-8c6e-aee78f094665.png">
still this

**Comment by willin** [comment]
redis             7-alpine                  0b405767398c   2 weeks ago   29.9MB
