### ISSUE TITLE
ドライブクリーナーのページネーション結果がおかしい

### ISSUE THREAD

**Issue by kiyo4act** [syuilo/Misskey#10461]
## 💡 Summary

ドライブクリーナーでページネーションが発生した時の挙動が期待通りでない
（ドライブに十分な数のファイル数がある時）

## 🥰 Expected Behavior

各ソート種類を選択して下にスクロールした時、スクロール後も全体でソート状態が維持されたまま、下にファイルが追加される

## 🤬 Actual Behavior

①ソートが「サイズが大きい順」の時
→既に出現したことのあるファイルが再登場する

②ソートが「追加日が古い順」の時
→そもそもページネーションしない

## 📝 Steps to Reproduce

1. ドライブにファイルを複数アップロード（理論上最低でも n ＞11）
2. 設定→ドライブ→ドライブクリーナー
3. ソートが「サイズが大きい順」になっていることを確認
4. 下にスクロール👈①発生
5.  ソートを「追加日が古い順」に設定
6.  下にスクロール👈②発生

## 📌 Environment

Misskey version: 13.10.3
Your OS: Windows
Your browser: Chrome
（下記同様の事象があった別の環境）
 -デバイス:iPhone、iPad(どちらもios16.3.1)、MacBook Air(big sur11.7.4)
 -ブラウザ:iosのChrome(バージョン111.0.5563.101、Apple Store上の最新)  

## 備考

サーバー内で報告があったので調査したところ、①に関しては下記が怪しいと思いました。
[files.ts](https://github.com/misskey-dev/misskey/blob/master/packages/backend/src/server/api/endpoints/drive/files.ts)
```ts
@Injectable()
export default class extends Endpoint<typeof meta, typeof paramDef> {
	constructor(
		@Inject(DI.driveFilesRepository)
		private driveFilesRepository: DriveFilesRepository,

		private driveFileEntityService: DriveFileEntityService,
		private queryService: QueryService,
	) {
		super(meta, paramDef, async (ps, me) => {
			const query = this.queryService.makePaginationQuery(this.driveFilesRepository.createQueryBuilder('file'), ps.sinceId, ps.untilId)
				.andWhere('file.userId = :userId', { userId: me.id });

			if (ps.folderId) {
				query.andWhere('file.folderId = :folderId', { folderId: ps.folderId });
			} else {
				query.andWhere('file.folderId IS NULL');
			}

			if (ps.type) {
				if (ps.type.endsWith('/*')) {
					query.andWhere('file.type like :type', { type: ps.type.replace('/*', '/') + '%' });
				} else {
					query.andWhere('file.type = :type', { type: ps.type });
				}
			}

			switch (ps.sort) {
				case '+createdAt': query.orderBy('file.createdAt', 'DESC'); break;
				case '-createdAt': query.orderBy('file.createdAt', 'ASC'); break;
				case '+name': query.orderBy('file.name', 'DESC'); break;
				case '-name': query.orderBy('file.name', 'ASC'); break;
				case '+size': query.orderBy('file.size', 'DESC'); break;
				case '-size': query.orderBy('file.size', 'ASC'); break;
			}

			const files = await query.take(ps.limit).getMany();

			return await this.driveFileEntityService.packMany(files, { detail: false, self: true });
		});
	}
}
```

ページネーションは最初11個、以降は31個追加で取得して、untilIdに下から2番目のIDを入れて続きを取得しています。
このメソッドはuntilIdで11個ないし31個取得した後にswitch文で並び替えているように見えます。
先に並び替えたものについてuntilIdしないと期待通りの動作にならないと思いました。

さすがにmasterに入っているコードはテストされているはずなので、的外れだったらごめんなさい。

**Comment by tamaina** [comment]
とりあえず番号若い方を残します

Duplicate of #10460

**Comment by acid-chicken** [comment]
Duplicate of 構文は他に文言が入ってると機能しない
