### ISSUE TITLE
Menubar is not shown in Classic UI 

### ISSUE THREAD

**Issue by ltlapy** [syuilo/Misskey#10470]
## 💡 Summary
クラシックUIでメニューバーが表示されない
* メニューの位置は関係ない
* CSS関連のブラウザー交換性とは別に、`sidebar` クラス以来のhtmlが生成されない

## 🥰 Expected Behavior
クラシックUIでメニューバーが表示されて、操作にも問題がない

## 🤬 Actual Behavior
クラシックUIでメニューバーが表示されない

## 📝 Steps to Reproduce
> 現時点で https://k.lapy.link と https://p1.a9z.dev から再現可能
* 「UI切り替え」メニューから「クラシック」を選択

## 📌 Environment

Misskey version: 13.10.3+58f3a2e+klapy (k.lapy.link) / 13.10.3-p1.19 (p1.a9z.dev)
Your OS: Debian GNU/Linux 11 (bullseye) 5.10.162-1 x86_64
Your browser: Chromium Version 111.0.5563.110 (Official Build)

**Comment by ltlapy** [comment]
`classic.sidebar.vue`と`classic.header.vue`から`$i`の情報が読み込めてないのが原因の一つに見えます
特徴としては両方setupを使ってないこと
![image](https://user-images.githubusercontent.com/19978840/229772322-9754e76e-a02b-46ea-982f-d0e95117bf7b.png)

**Comment by tamaina** [comment]
Storybookでグローバル変数削除したのでそれ
