### ISSUE TITLE
[Client] データセーバーモード（タップするまで画像を読み込まない）

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10471]
## Summary

タイトルの通り

閲覧注意画像と同じような機構を全画像に設けるオプションを追加

**Comment by kakkokari-gtyih** [comment]
これでできるみたいですが、初見の人がこの設定項目にたどり着けるとは思えないので設定を独立させたほうが良さそう

![image](https://user-images.githubusercontent.com/67428053/229825188-3a728bd8-5042-450f-9811-a19324fcb471.png)

あと、これだと全部「閲覧注意」になってしまうのでやはり設定分けたほうが良さそう

**Comment by acid-chicken** [comment]
項目はそのままで文言を

メディアの表示

- 全て表示
- 閲覧注意のみ隠す
- 全て隠す

とすれば良いのでは

**Comment by kakkokari-gtyih** [comment]
![image](https://user-images.githubusercontent.com/67428053/229828698-2327fb92-1ffb-419b-b468-d9451308ddc3.png)

これでどうでしょう

**Comment by acid-chicken** [comment]
ややこしいので「手動で表示するまでメディアを読み込まないため」と言い切って良い気がする

**Comment by KawaneRio** [comment]
これは恐らく別issue案件ですが、Misskeyにもpawooのやうな「非表示のメディア」と「閲覧注意」の区別が欲しいです。特に「常にメディアを隠す」を通信量節約目的でした場合などにはメディアを開く前の判斷に必須かと思ひます。

**Comment by kakkokari-gtyih** [comment]
@KawaneRio  今から出そうとしてるPRでは、

- 「すべて隠す」になっている状態で
- 閲覧注意ではない画像に当たったとき

「閲覧注意」ではなく画像サイズを表示するようにしてあります（画像サイズはTwitterリスペクト）。こういう実装はいかがでしょう？

![image](https://user-images.githubusercontent.com/67428053/229830801-ca63103e-0169-40c1-b2eb-ebeebae19892.png)

**Comment by acid-chicken** [comment]
どちらかというと非 NSFW を隠したときに NSFW って出るのがバグ

**Comment by tamaina** [comment]
正直これは私がやりたい感じがある

**Comment by tamaina** [comment]
> どちらかというと非 NSFW を隠したときに NSFW って出るのがバグ

基本的にはこれ

**Comment by kakkokari-gtyih** [comment]
> 正直これは私がやりたい感じがある

いちおうやってみましたので供養

https://github.com/kakkokari-gtyih/misskey/commit/15ff40e48cc7d64ae6835224e1b4263b192e4d77

**Comment by tamaina** [comment]
> いちおうやってみました

あ、これで良さそう

**Comment by kakkokari-gtyih** [comment]
PR出しますー

**Comment by KawaneRio** [comment]
は、早い...

**Comment by acid-chicken** [comment]
> どちらかというと非 NSFW を隠したときに NSFW って出るのがバグ

これが解消していなさそう

**Comment by kakkokari-gtyih** [comment]
修正します

**Comment by kakkokari-gtyih** [comment]
> > どちらかというと非 NSFW を隠したときに NSFW って出るのがバグ
> 
> これが解消していなさそう

@acid-chicken  修正しました

https://github.com/kakkokari-gtyih/misskey/commit/eeab8cdcfe676e3ae1eb5ded0dcd1dde2bb36633
