### ISSUE TITLE
チャンネルTLをRedisにキャッシュしていない時代の投稿がチャンネルTLに表示されない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#10473]
Old notes from the period when the channel timeline was not cached in Redis do not appear in the channel timeline

## 💡 Summary
https://github.com/misskey-dev/misskey/commit/b53d6c7f8ca1a712eab44967e8d05a0cc7bcc034 で、チャンネルのタイムラインをRedisから読み込むようになったが、それ以前に作成したチャンネルの投稿がチャンネルタイムラインに表示されない

## 🥰 Expected Behavior

以前の投稿も表示される
## 🤬 Actual Behavior
以前の投稿が表示されない

## 📝 Steps to Reproduce

1. https://github.com/misskey-dev/misskey/commit/b53d6c7f8ca1a712eab44967e8d05a0cc7bcc034 より古いバージョン(~13.10.3)でチャンネルに投稿
2. https://github.com/misskey-dev/misskey/commit/b53d6c7f8ca1a712eab44967e8d05a0cc7bcc034 より新しいバージョンに移行
3. チャンネルTLを表示

## 📌 Environment

Misskey version: 13.9.2 -> develop
Your OS: windows
Your browser: chrome

**Comment by syuilo** [comment]
通常のタイムラインに関しても、一定期間内の投稿しか表示されないようになってるしそう考えると仕様と言っても良い挙動ではある

**Comment by syuilo** [comment]
パフォーマンスを犠牲にすることなく過去までさかのぼれる仕組みが求められる

**Comment by futchitwo** [comment]
> 通常のタイムラインに関しても、一定期間内の投稿しか表示されないようになってるしそう考えると仕様と言っても良い挙動ではある

- https://github.com/misskey-dev/misskey/issues/9205#issuecomment-1368397522 で効果がなかったともあるし、 #10063 の動作はバグというか戻し忘れだと思ってたんだけど
- あまり頻繁に更新されないチャンネルだと何も表示されない期間が長そう
- しりとりチャンネルとかがやり直しになりそう

データベースから消え去ったわけではないのでRedisにない投稿は必要に応じてDBから引っ張ってきてもいい気がする

**Comment by futchitwo** [comment]
https://github.com/misskey-dev/misskey/commit/fa67fb42b1baf616d860c54f6cdf9123fc7ed57a のやり方だとRedisに1件でも投稿があれば遡れなくなりそうな気がするんだけどどうなんだろう
