### ISSUE TITLE
ReplyError: ERR The ID specified in XADD is equal or smaller than the target stream top item

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10482]
```
ReplyError: ERR The ID specified in XADD is equal or smaller than the target stream top item
    at parseError (/home/misskey/misskey/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/misskey/misskey/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xadd',
    args: [
      'p1.a9z.dev:antennaTimeline:98vnb5j45s',
      'MAXLEN',
      '~',
      '200',
      '1680699939456-*',
      'note',
      '9d79nudcbb'
    ]
  }
```

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
新しく追加するエントリは既存の最も新しいエントリの持つIDより新しいIDでなければならないけど、何らかの理由で既に追加しようとしたものより新しいIDを持つものが追加されているから怒られている？

**Comment by syuilo** [comment]
Misskeyの処理上タイミングによってはちょっと古いノートが追加されることもありうるだろうし、「新しく追加するエントリは既存の最も新しいエントリの持つIDより新しいIDでなければならない」っていう縛りはちょっときついわね

**Comment by syuilo** [comment]
やっぱりそうっぽい

> When a user specified an explicit ID to XADD, the minimum valid ID is 0-1, and the user must specify an ID which is greater than any other ID currently inside the stream, otherwise the command will fail and return an error.

https://redis.io/commands/xadd/

**Comment by syuilo** [comment]
ID生成をRedisに任せるしかなさそうだけど、そうした場合ページングどうしようかしら

**Comment by syuilo** [comment]
あー現状も結局は時間での比較だから問題ないかも
