### ISSUE TITLE
通知インジケータが光りっぱなしになる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10480]
通知をRedisに保存することになり、単一の通知を既読にするということができなくなった結果、通知リストを読むかmark-all-as-readしないと通知インジケータが消えないようになってしまった

（notifications/readを復活させて、その内容(の値の一番大きいもの)がlatestReadNotificationIdより大きければlatestReadNotificationIdとする・latestNotificationIdと等しいか大きければreadAllNotificationsを発行…とかの実装を考えた

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/229986457-48997b6d-cc86-471d-9914-b3bc69a9868d.png)

~~これってifの条件逆じゃない…？~~

**Comment by tamaina** [comment]
関数の役割的にそんなことなかった

**Comment by syuilo** [comment]
通知リストを読まないけど通知が既読になる＝通知インジケータを消したい場合ってどんなとき？
PWA通知クリック時は notifications/mark-all-as-read 呼ぶようになってるしそれ以外で

**Comment by tamaina** [comment]
以前までは、画面を開いている間に通知が届いた時は通知インジケータが光らない仕様だった

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/6798effbabe52e1afb9c83767f971679306c3428/packages/frontend/src/ui/_common_/common.vue#L56

**Comment by syuilo** [comment]
謎

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/10479

あ、こっちが原因かも

**Comment by tamaina** [comment]
stream.send('readNotification');は生きてるならこっちはclose

**Comment by tamaina** [comment]
mark-all-as-readしてもインジケータが光りっぱなしになることがあった

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/230085535-5749f480-3541-403c-9ff1-507fab62b0b5.png)

stream.send('readNotification');がオブジェクトじゃなくてstringになっとる？

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/230104482-a706c321-191e-4349-a64e-fabc9869228c.png)

ほう（readNotificationを送ってreadAllNotificationsがきた後にunreadNotificationが来ている

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/230106239-057fa82f-75dc-4d30-9fcf-b0c1cd0533d5.png)

あ〜〜
