### ISSUE TITLE
plainブロックをnyaize（Cat変換）の例外とする

### ISSUE THREAD

**Issue by NyaightHazard** [syuilo/Misskey#10492]
## 説明
引用（```）やコードブロック（>）ど同様に、`<plain>...</plain>`をCatモードの文章変換の例外とする

## 用途
ユーザー側が意図してCatモードのままCat変換を無効化する時に
固有名称に言及する、会話文を書く、など

## 実装
NoteEntityService.tsのnyaizeNodeに`if (node.type === 'plain') return;`を加える
（手持ちの実装環境が無いので未検証だが動くはず？）

## 影響
過去のノート全てに反映するので破壊的変更とも言えるが、`<plain>`の認知度と用途からして影響度は低いと予想

**Comment by syuilo** [comment]
Catは基本的に問答無用でnyaizeすることが目的の(ジョーク)機能だからあまり回避する方法を作ると個人的には困るというのがあります

**Comment by NyaightHazard** [comment]
それもちょっと思いましたが、猫耳を付けるためにCatモードにしているユーザーもいる（私も無効化できるなら付けたい）ので提案しました

**Comment by acid-chicken** [comment]
猫耳はどちらかというと副次的効果（後付け）で、主機能は不自由さの獲得になります

**Comment by acid-chicken** [comment]
Related to #3081
Related to #5221
Related to #6107

**Comment by NyaightHazard** [comment]
なるほど、Catモードはnyaizeを発生させるのが主機能で、
猫耳は外部からCatモードを判別するための副機能なんですね。
ユーザー側からだとどちらが主機能か分かり辛いのが難点ですね…
理解したのでこの件はCloseします。
