### ISSUE TITLE
ユーザーに対して自分用のメモを残せる機能

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#10490]
他のユーザーに対して、自分用にメモ書きを作成できる機能。

Mastodonや、
<img width="242" alt="image" src="https://user-images.githubusercontent.com/7106976/230176595-78354aff-b3ca-47ba-b119-83ff3bd403fb.png">

Discordにもある。
<img width="248" alt="image" src="https://user-images.githubusercontent.com/7106976/230177005-a605cd50-daeb-4f4c-bfb1-93dff2bc05d4.png">

### ユースケース例

* 「以前～～された為ブロック」など、ブロック理由を書く
* そのユーザーに関連する出来事をメモる（4月になったら遊びに誘う、など）

### 備考

既に実装して自鯖で動かそうとしています。
https://github.com/shrimpia/misskey/pull/31

<img width="593" alt="image" src="https://user-images.githubusercontent.com/7106976/230178021-2b3b85c8-d95e-4c13-9a1f-23a37810d86e.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/7106976/230178173-893e91ed-f666-4c3c-b12c-2d5c243431a7.png">

**Comment by syuilo** [comment]
> 既に実装して自鯖で動かそうとしています。
https://github.com/shrimpia/misskey/pull/31

PRいただければ 🙏🏻
