### ISSUE TITLE
プッシュ通知操作によりZen UIなクライアントでもページ遷移が行われる場合がある

### ISSUE THREAD

**Issue by okayurisotto** [syuilo/Misskey#10497]
## 💡 Summary

プッシュ通知、もしくはそのボタンをクリックしたときには、クライアントが起動されます。このとき、既存のクライアントがすでに起動していた場合、新たにクライアントが起動されることはなく、その既存のクライアントのページが遷移します。ただし、Zen UIなクライアントについては、起動していたとしてもその存在は無視されます。しかしこの、クライアントがZen UIかどうかの判定処理に問題があるようで、無視されない場合があります。

## 🥰 Expected Behavior

Zen UIなクライアントがすでに起動している状況でプッシュ通知を操作したときには、必ずZen UIなクライアント以外のクライアントが使われる（もしくは新たに作られる）。

## 🤬 Actual Behavior

Zen UIなクライアントが使われ、そのクライアントのページが遷移してしまう場合がある。

## 📝 Steps to Reproduce

1. 通知を受け取るアカウント（hoge）を作成する
2. hogeのプッシュ通知機能を有効化する
3. 適当なノートを作成する
4. `https://misskey.example/share?text=foobar&zen`のようなURLでZen UIなクライアントを開き、そのまま開いておく
4. また別にアカウント（fuga）を作成する
5. 手順3でhogeが作ったノートにfugaがリアクションを送る
6. リアクションを受け取った旨のプッシュ通知がhogeに送信されるので、そのプッシュ通知を押下する

## 📌 Environment

Misskey version: v13.11.0.beta-1 3c04fef8d
Your OS: Windows 11
Your browser: Microsoft EdgeとMozilla Firefoxでは確認されました

---

おそらく[この部分](https://github.com/misskey-dev/misskey/blob/3c04fef8d/packages/sw/src/scripts/operations.ts#L62)の処理がよくないのだと思われます。修正できたらPRを作成します。

このIssueは #10477 のPRでAdditional infoとして書き残した内容と関連しています。

**Comment by syuilo** [comment]
ZenUI自体ポップアウト表示にしか使ってないし廃止しても良さそう

**Comment by okayurisotto** [comment]
個人的には、共有ページでZenUIを使いたいのでZenUI自体は今後も使えるとありがたいです。

Misskeyでは`https://misskey.example/share?text=foo`のようなURLで共有用リンクを作成することができますが、そのURLで読み込まれるページには（デフォルトUIの場合）ナビゲーションバーやウィジェットが含まれます。となると、ウィジェットの内容にもよりますが、いくらかの通信が行われることになります。私は、共有ページはノートを投稿して必要なくなった時点ですぐに閉じたいと思っていて、そのため共有ページにはできる限り軽量であってほしいので、ZenUIのようなものがあるとありがたいのです。

ただ共有ページでのZenUIの使用においては、ZenUIな共有ページでノートを作成したあと、そのページ自体は閉じずにページ上の「閉じる」ボタンを押すとZenUIのままトップページへ遷移してしまう挙動が少し問題になるかもしれません。また、そもそもデッキUIを使っていた場合はまったく関係のない話になります。

ZenUI自体特殊なUIであるようですので、ポップアウト表示でしか使うことが想定されていないのであれば、ポップアウト表示がZenUIなしに機能するようになる変更がされたタイミングでZenUI自体を廃止してもよいと感じます。

このIssueを修正するPRはすでに作成できる状態にありますので、とりあえず作成だけしておきます。（ZenUI廃止などでPRが必要なくなった場合はマージせず閉じます。）

**Comment by okayurisotto** [comment]
PRがマージされたのでとりあえずこのIssueは閉じてしまいたいと思います。ありがとうございました！
