### ISSUE TITLE
Minimize/Fold button for windows

### ISSUE THREAD

**Issue by 2minwia** [syuilo/Misskey#10505]
## Summary

occasionally, i open a whole lot of windows of notes for reading later while i scroll the timeline.  
i found myself making those windows very small so they wouldnt take up the whole screen.  
so a minimize button would be quite useful for this scenario.

i made a prototype of this feature, [live on my instance](https://misskey.heonian.org/notes/9d9zk5fw5a). if this seems like a good feature, i could clean up the code and try pull-requesting it.  
try shift-clicking the date, so the note appears in a window, and then try clicking the new minimize button.
here's a video, too:
https://user-images.githubusercontent.com/2979581/230596215-c3dc2eaa-3b09-4a15-8a9c-09a81b5cdbac.mp4

**Comment by syuilo** [comment]
LGTM

**Comment by 2minwia** [comment]
Could I get assigned to this, then? c:
