### ISSUE TITLE
Can't react with custom emoji リアクションできない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10502]
リアクションしようとしてもできない

```
TypeError: JSON.parse(...).map is not a function
    at RedisSingleCache.fromRedisConverter (file:///home/misskey/misskey/packages/backend/built/core/CustomEmojiService.js:285:68)
    at RedisSingleCache.get (file:///home/misskey/misskey/packages/backend/built/misc/cache.js:129:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RedisSingleCache.fetch (file:///home/misskey/misskey/packages/backend/built/misc/cache.js:138:29)
    at async ReactionService.toDbReaction (file:///home/misskey/misskey/packages/backend/built/core/ReactionService.js:256:50)
    at async ReactionService.create (file:///home/misskey/misskey/packages/backend/built/core/ReactionService.js:76:24)
    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/notes/reactions/create.js:76:13
    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:275:16) f4a067a1-4b39-46e8-99b8-8a17aa033c65
```

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/230553504-1c51b32e-acc9-4aab-9dd4-a3b7199fd21c.png)

**Comment by syuilo** [comment]
謎

**Comment by tamaina** [comment]
何もしてないけどなおった

**Comment by tamaina** [comment]
うーん、また発生した

**Comment by fu-sen** [comment]
13.11.0 のサーバーでこの問題を確認できています。分かっている事として
Unicode 絵文字でリアクション可能、カスタム絵文字はリアクションできない状態です。

**Comment by fu-sen** [comment]
13.11.0 へ更新したサーバーのローカル内だけ不具合の対象で、
連合からのリアクションはカスタム絵文字も表示できてます。

**Comment by tamaina** [comment]
調べるか〜

**Comment by fu-sen** [comment]
サーバーによっては正常なところもあるのを確認しました。

**Comment by tamaina** [comment]
localEmojisが(empty array)の時は`{}`が返ってくるっぽい？

**Comment by syuilo** [comment]
> ![image](https://user-images.githubusercontent.com/7973572/230553504-1c51b32e-acc9-4aab-9dd4-a3b7199fd21c.png)

localEmojisというキーで保存されているわけではないのでこれは正しいことは注意
(実際は`singlecache:localEmojis`)

**Comment by syuilo** [comment]
ローカルではどうやっても再現しないし謎過ぎる

**Comment by fu-sen** [comment]
不具合が出るサーバーで、その後確認した限りでは、
リアクションできる時と、リアクションしても反応しない時がありました。
タイミングがよくわかりません。

**Comment by Mogyuchi** [comment]
お茶濁し修正でこのissue閉じちゃっているけれどそれで良いのか疑問

**Comment by tamaina** [comment]
とりあえず動くし…

（原因調べたければごゆっくりどうぞという感じ

**Comment by okaits** [comment]
13.11.0の当サーバーでも同じ問題が発生しました。
時間を置くとできることもありますが、高確率で同じ問題が発生するようです。ローカル/リモート関係なく発生しています。

**Comment by fu-sen** [comment]
13.11.1 で解決しているように見えます。アップデートして下さい。

**Comment by okaits** [comment]
アップデートしました。ありがとうございました！

**Comment by chimorium** [comment]
素人ですがすみません。13.11.1の環境（VPS上）で、本件の修正箇所だけ修正前の状態に戻して調査しました。
```
systemctl restart misskey
```
で再起動すると、カスタム絵文字でのリアクションが出来ない状態となり、
そのまま30分程度放置しておくと、リアクションが出来るようになりました。

このツリーで言及されている、Redisのキーについてですが、
リアクションが出来ない間は
```
127.0.0.1:6379> get "example.tld:singlecache:localEmojis"
"{}"
```
と返ってきました。それが、リアクションができる状態になったとき、
```
127.0.0.1:6379> get "example.tld:singlecache:localEmojis"
(nil)
127.0.0.1:6379> keys "example.tld:singlecache:localEmojis"
(empty array)
```
に変わっていました。そして、実際にリアクションをした後になると、
```
127.0.0.1:6379> get "example.tld:singlecache:localEmojis"
"{}"
```
になっていました。それ以降はそのまま問題なくリアクションできています。

内部処理が全く分からないためこれ以上のことを述べられないのですが、
将来的に一助にもなればと思い、初めてコメントさせていただきました。
（これを踏まえて結局今回の修正で合っているということになりましたら、すみません）

**Comment by shibaobun** [comment]
Hello, I just wanted to say that I was having this issue on 13.11.0 at misskey.bubbletea.dev and updating to 13.11.1 immediately fixed it

**Comment by chimorium** [comment]
> ```
> 127.0.0.1:6379> get "example.tld:singlecache:localEmojis"
> "{}"
> ```
> になっていました。それ以降はそのまま問題なくリアクションできています。

上記、誤りがありました。3分間はリアクション出来るのですが、その後は30分程度リアクション出来なくなります。

原因を深く調査したところ、以下のように処理が進んでいると分かりました。
- Redisのキー"example.tld:singlecache:localEmojis"が存在しないとする。このときはリアクション出来る。
- リアクションを行うと、Redisの上記キーに不正な値"{}"が登録される。ただし、3分間はメモリキャッシュが使われるため、問題なくリアクション出来る。
- 3分経過すると、上記不正な値の影響でリアクションが出来なくなる。
- 30分経過すると、lifetimeを終えて上記キーが削除される。
- 以下繰り返し。
- Redisを再起動したときは前回値が入っているため、不正な値が入った状態の場合はリアクション出来ないことになる。

それではどうして不正な値が登録されているのか、色々調べたところ、JSON.stringifyの引数にMapIteratorが入ると、"{}"という結果になってしまうことが分かりました。
これを修正する形で、プルリクエストを出させていただきたいと思います。

長々とコメント失礼いたしました。

**Comment by nexryai** [comment]
13.11.2で再び発生しています

**Comment by syuilo** [comment]
Redisに古いキャッシュが残っている影響かも

**Comment by tamaina** [comment]
Redisのキャッシュをパージってできるの

**Comment by nexryai** [comment]
`redis-cli`から`del example.com:singlecache:localEmojis`したらリアクションできるようになりました

**Comment by syuilo** [comment]
Misskeyからの操作としてはできない
あと全パージは通知とかも消えるから不便そう

**Comment by tamaina** [comment]
> del example.com:singlecache:localEmojis

redis-cliとか経由でいいのか

**Comment by nexryai** [comment]
redis-cliで入って実行しました

**Comment by tamaina** [comment]
xargs使えばいい感じに処理できる感じがある

https://blog.morugu.com/entry/2018/01/06/233402

**Comment by ghost** [comment]
13.11.2アップデート後に同様の症状出ましたが、自分も以下の対処で症状治りました。
(redis-cliで`<domain>:singlecache:localEmojis`をdel)

```
$ sudo docker exec -i -t <redis container id> /bin/sh
/data # redis-cli
127.0.0.1:6379> get example.com:singlecache:localEmojis
"{}"
127.0.0.1:6379> del example.com:singlecache:localEmojis
(integer) 1
127.0.0.1:6379> get example.com:singlecache:localEmojis
(nil)
```

**Comment by HEPPy4869** [comment]
13.11.2においてredis-cliでの操作は行ったのですが，カスタム絵文字でリアクションを行うと以下のようなエラーが発生してリアクションできないことがあります．（時間を空けると正常にリアクションできる場合もある）
```ERR  *  [api]   Internal error occurred in notes/reactions/create: emoji.updatedAt.toISOString is not a function
{
  ep: 'notes/reactions/create',
  ps: { noteId: '9dgu01sgoq', reaction: ':test:', i: 'Di7EY8y95ZnkH5Ih' },
  e: {
    message: 'emoji.updatedAt.toISOString is not a function',
    code: 'TypeError',
    stack: 'TypeError: emoji.updatedAt.toISOString is not a function\n' +
      '    at ApRendererService.renderEmoji (file:///misskey/packages/backend/built/core/activitypub/ApRendererService.js:143:64)\n' +
      '    at ApRendererService.renderLike (file:///misskey/packages/backend/built/core/activitypub/ApRendererService.js:226:22)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async ReactionService.create (file:///misskey/packages/backend/built/core/ReactionService.js:147:63)\n' +
      '    at async file:///misskey/packages/backend/built/server/api/endpoints/notes/reactions/create.js:76:13\n' +
      '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:275:16)',
    id: '0a5a2a0c-1754-4006-9324-54bdad63f479'
  }
}
```

**Comment by syuilo** [comment]
直します

**Comment by syuilo** [comment]
done https://github.com/misskey-dev/misskey/commit/d06d1e868263e89de1a8f7dbd6636c6cc37df607
