### ISSUE TITLE
タイムセンシティブなコンポーネントの正確な描画

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#10510]
## Summary

MkAnalogClock や MkDigitalClock などはパフォーマンスに影響を与えないようにわざと精度を悪くしているが、最悪 1 秒ズレるのはズレすぎな気がする
`requestAnimationFrame` をいろんなところで呼ぶのが多分良くないと思われるので、グローバルで 1 コールにしたり、あるいは `requestIdleCallback` を活用できないだろうか

**Comment by acid-chicken** [comment]
API への理解が間違っていなければこう？

![image](https://user-images.githubusercontent.com/20679825/230724391-e824d112-bd21-43b2-ad6a-643d5819e738.png)

**Comment by tamaina** [comment]
> requestAnimationFrame をいろんなところで呼ぶのが多分良くないと思われる

API全く理解してないけどいろんなところで呼んじゃいけないんだ…

**Comment by acid-chicken** [comment]
> API全く理解してないけどいろんなところで呼んじゃいけないんだ…

いろんなところで闇雲に呼ぶと（UA は優先度がわからないので）単純に時間がなくなる→そのためしゅいろは避けているはずという説明が正確か

**Comment by acid-chicken** [comment]
`requestIdleCallback` で直接更新すると今度は描画をやり直しになるので却って逆効果のはず

**Comment by acid-chicken** [comment]
Related to #1689

**Comment by syuilo** [comment]
ブラウザによるレンダリングというより、Vueによるコンポーネントのレンダリング(vdom再構築)が高価だからそれを避けたいというのがある

**Comment by syuilo** [comment]
それを考えると https://github.com/misskey-dev/misskey/pull/10547 の効果はあまりない(か、むしろ悪化する？)気がする

**Comment by acid-chicken** [comment]
実際のパッチは変更なし（`MkAnalogClock`）か少数のノード（`MkDigitalClock`）だと思うけどそこまで VDOM のパフォーマンスって悪いのかな

**Comment by syuilo** [comment]
MkTimeに関してはかなり同時に存在することになるわね

**Comment by acid-chicken** [comment]
とここで気づいたけど VDOM 相手だと `requestAnimationFrame` は間に合わない説ある

**Comment by EbiseLutica** [comment]
そもそも時計みたいなコンポネはVDOMで描画すべきじゃないのかもしれない。

**Comment by acid-chicken** [comment]
> MkTimeに関してはかなり同時に存在することになるわね

キャッシュというかインスタンスごとに比較が高速に行われるような改善を加えるべきそう

**Comment by acid-chicken** [comment]
というか MkTime の正確性は割とどうでもいいからこれは setTimeout でいいじゃ

**Comment by acid-chicken** [comment]
MkTime は

- 現行の実装にする
- パッチした実装に加えて「ビューポート上に見えているなら更新する」ロジックを加える

の 2 パターンを実際に比較してみたい

**Comment by acid-chicken** [comment]
> MkTimeに関してはかなり同時に存在することになるわね

@syuilo 戻した

**Comment by acid-chicken** [comment]
@syuilo これ懸念点は残っている？

**Comment by syuilo** [comment]
確認する

**Comment by acid-chicken** [comment]
@syuilo どうだった？
