### ISSUE TITLE
swで使用しているesbuildが古いため一部の構文が認識されず、その構文を使った開発ができない

### ISSUE THREAD

**Issue by okayurisotto** [syuilo/Misskey#10525]
## 💡 Summary

Misskeyのswで使用しているesbuildが古く、`satisfies`のような一部の構文が認識されないため、ソースコードにそれが含まれていたときビルドに失敗する状況になってしまっています。しかしTypeScript自体は新しいため、型チェックなどではその問題に気付けません。今のところ`satisfies`を使ったようなソースコードはないため問題は起きていませんが、問題になる前に更新しておくべきだと考えます。

（私がこのことに気付いたのは、リファクタリングとして`satisfies`を使おうとしたところビルドできなかったためです。）

## 🥰 Expected Behavior

`satisfies`などの、比較的最近追加されたTypeScriptの構文が正常に認識され、ビルドに成功する。

## 🤬 Actual Behavior

`Expected ")" but found "satisfies"`のようなエラーにより、ビルドに失敗する。

## 📝 Steps to Reproduce

1. `packages/sw/src/sw.ts`など適当なファイルで、`satisfies`を使った何かを書く

## 📌 Environment

Misskey version: 13.11.0-beta.6 0f328e847
Your OS: -
Your browser: -

---

私のフォークの方で、esbuild更新で必要になる作業をしてみる予定です。ただここ最近のesbuildでは（下で補足するように）いくつかの破壊的な変更が行われているようであるため、時間がかかると思われます。

<details>
<summary>補足情報</summary>

この問題は、`packages/sw/package.json`にあるTypeScriptのバージョンは`5.0.3`と高く`satisfies`に対応しているにも関わらず、ビルドに使用しているesbuildのバージョンが低いため起きてしまっているものです。Misskeyのswでは`0.14.42`のesbuildが使われていますが、esbuildが`satisfies`オペレータに対応したのは`0.15.13`からです。

https://github.com/evanw/esbuild/releases/tag/v0.15.13

現在のesbuildの最新バージョンは`0.17.15`です。更新が必要だと考えます。

esbuildは`0.16.0`から、`define`の設定として文字列のみを受け入れるようになりました。ですので、現在`build.js`でしているような真偽値を渡すことはできません。

https://github.com/evanw/esbuild/releases/tag/v0.16.0

実際には、現在のMisskeyのswが使用しているバージョンにおいても、真偽値を渡そうとするとTypeScriptでは型エラーが出力されるようになっています。`@ts-check`コメントなどで型チェックを有効化すると、そのエラーが確認されます。しかしこのバージョンのesbuildでは、実行時に自動的に文字列に変換されるようになっていたため、型チェックをしていなかった`build.js`には影響がありませんでした。

そもそも`define`機能は値を渡すようなものではなく、JavaScriptのコードの文字列を渡すものだったそうです（私もまだあまり理解できていないので、詳しくは上記リンク先のリリースノートを参照してください）。ですので現在真偽値を渡している部分を、事前に`JSON.stringify`によって文字列にした真偽値を渡すように変更することで、今まで通りの動作をさせることができると考えられます。

また、esbuildには`0.17.0`から、インクリメンタルなビルドに関連する新たなAPIとして、`context`というものが導入されました。

https://github.com/evanw/esbuild/releases/tag/v0.17.0

`build()`関数が廃止されたわけではありませんが、`build()`の設定としてこれまで通り`watch`を渡してしまうと、ビルド時にエラーが出力されます。

</details>

**Comment by tamaina** [comment]
swのパッケージそもそもアップデートしてないのでかなり古そう

**Comment by tamaina** [comment]
（いうほどswはそこまでパッケージなかった

**Comment by tamaina** [comment]
https://swc.rs/docs/configuration/bundling

swcのバンドル使えないかしら（under constructionだけど

**Comment by okayurisotto** [comment]
```
$ pnpm outdated
┌──────────────────┬─────────┬─────────┐
│ Package          │ Current │ Latest  │
├──────────────────┼─────────┼─────────┤
│ typescript (dev) │ 5.0.3   │ 5.0.4   │
├──────────────────┼─────────┼─────────┤
│ eslint (dev)     │ 8.37.0  │ 8.38.0  │
├──────────────────┼─────────┼─────────┤
│ esbuild          │ 0.14.42 │ 0.17.15 │
└──────────────────┴─────────┴─────────┘
```

とのことですので、とりあえずはesbuildを更新したいです。

swcを使うという選択肢については、私にはswcについての知識がないのでなんとも言えません…。

**Comment by okayurisotto** [comment]
esbuildを更新するPRがマージされたのでこのIssueは閉じます。ありがとうございました！
