### ISSUE TITLE
Firefoxでサインアップする時、メールアドレスがユーザー名として認識される

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10523]
Firefoxでサインアップする時、メールアドレスがユーザー名として認識される

usernameを登録させたい

firefox, signup, register, email, password manager

**Comment by Mogyuchi** [comment]
iPadOS（16.3?） でも同様。

**Comment by tamaina** [comment]
サーバールール周りのやつでも変わらなかったか

**Comment by Mogyuchi** [comment]
> サーバールール周りのやつでも変わらなかったか

最新版で試してない
すまない。

**Comment by mappi-pr** [comment]
> サーバールール周りのやつでも変わらなかったか

@tamaina 
https://github.com/misskey-dev/misskey/pull/10660
のコミットで解消済であることを確認しました！

firefox 112.0.2 (64 ビット)
※iOS未確認

<img width="385" alt="image" src="https://user-images.githubusercontent.com/75538777/236797900-db5f5fb3-1e86-428b-9ae8-941472be9d16.png">

**Comment by Mogyuchi** [comment]
ん
うち、issueが指している事象を誤認してる？。

@tamaina 
「パスワードマネージャーに email と password のペアが登録される」
「username と password のペアを登録するべき」
で合ってますか？

**Comment by tamaina** [comment]
yes

**Comment by tamaina** [comment]
emailフォームが出現する際に問題になる

**Comment by mappi-pr** [comment]
@tamaina @Mogyuchi 
事象理解しました！ありがとうございます。

ということであれば、残念ながら事象解消しておらず
改めてDevelopブランチの最新版(13.12.0-beta.5)で試してみましたが、
~~Chromeも~~Firefox~~も~~はデフォルトはメールアドレスを登録するような挙動に見えました。。。
（プルダウンで選択は可能）

```
ユーザー名：mp
メールアドレス：mp@example.com
```

■Chrome（112.0.5615.138）
→パスワードマネージャーによる登録フォームが表示されない
~~画像は誤りのため削除~~

■Firefox（112.0.2）
<img width="291" alt="image" src="https://user-images.githubusercontent.com/75538777/236840443-479a8ebe-a4fe-4a9f-b5bc-ac7c9995fdb1.png">

**Comment by mappi-pr** [comment]
@tamaina @Mogyuchi 
昨日はissueの事象説明補足いただきありがとうございます！！

事象自体は、
/packages/frontend/src/components/MkSignupDialog.form.vue(L.12)に`autocomplete="username"`を追加することで、解消しそうです。
※/packages/frontend/src/components/MkSignin.vue(L.9)を参考にしました
```
<MkInput v-model="username" type="text" pattern="^[a-zA-Z0-9_]{1,20}$" :spellcheck="false" autocomplete="username" required data-cy-signup-username @update:model-value="onChangeUsername">
```

```
ユーザー名：username
メールアドレス：mail@example.com
```

■Firefox（112.0.2）
※プルダウンのデフォルトがusernameになったことを確認
<img width="495" alt="image" src="https://user-images.githubusercontent.com/75538777/236972013-80723f56-451d-4734-bef9-78038fce5469.png">

■Safari (iOS 16.4.1(a))
※自動入力されたPWを採用して登録
<img width="495" alt="image" src="https://user-images.githubusercontent.com/75538777/236973604-9eeebab2-0e36-4933-8939-128e7074c77f.png">
