### ISSUE TITLE
data loss upgrading to 13.11.0

### ISSUE THREAD

**Issue by dakkar** [syuilo/Misskey#10535]
## 💡 Summary

as part of the db migrations in 13.11.0, there's these two https://github.com/misskey-dev/misskey/blob/develop/packages/backend/migration/1680582195041-cleanup.js https://github.com/misskey-dev/misskey/blob/develop/packages/backend/migration/1680491187535-cleanup.js

```sql
DROP TABLE "notification";
DROP TABLE "antenna_note";
```

I don't see any code that tries to copy the data out of those tables and into redis.

## 🥰 Expected Behavior

no data loss

## 🤬 Actual Behavior

notifications are lost

## 📝 Steps to Reproduce

1. have a misskey < 13.11.0
2. have some notifications
3. upgrade to 13.11.0

## 📌 Environment

Misskey version: 13.11.0
Your OS: linux
Your browser: any

## questions

are notifications considered not important? would it be possible to have at least a script to run before the db migrations to copy notifications into redis?

**Comment by tamaina** [comment]
> are notifications considered not important?

Yes they are not.

**Comment by dakkar** [comment]
For people who may find this issue in the near future, have *not yet upgraded* past 13.11.0, and want to keep their old notifications:

First of all, stop Misskey. Then update your code &c. You may want to change the `300` around line 100 of [NotificationServices.ts](../tree/develop/packages/backend/src/core/NotificationService.ts) to a larger value, so more notifications will be kept for each user, but of course that will mean that Redis will take more RAM.

**Before** running `pnpm run migrate`, run:
```shell
psql -U misskey -d misskey -t -X -c \
    'select to_jsonb(n) from notification n order by "createdAt" asc' | \
  jq -cr '.notifieeId + " " + (with_entries(select(.value and .key != "notifieeId" and .key != "isRead")) | tojson)' | \
  perl -nle 'my ($id,$json) = split " ",$_,2;
    my $key="s.thenautilus.net:notificationTimeline:$id";my $key_len=length($key);my $json_len=length($json);
    print "*5\r\n\$4\r\nXADD\r\n\$${key_len}\r\n${key}\r\n\$1\r\n*\r\n\$4\r\ndata\r\n\$${json_len}\r\n${json}\r\n" ' | \
 redis-cli --pipe
```

(you **do need** to change that `s.thenautilus.net` with your instance hostname; you may need to change the `-U` username and `-d` database name, and if your Redis needs credentials, add them to the `redis-cli` command)

Now you can carry on with `pnpm run migrate` and restarting Misskey.

Explanations at https://s.thenautilus.net/notes/9dkaa6o1f3
