### ISSUE TITLE
ピン留めユーザーに同じアカウントが複数表示される

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#10530]
## 💡 Summary

ピン留めユーザーに同じアカウントが複数表示される

## 🥰 Expected Behavior

1つだけ表示される

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/10798675/230729396-f686ff25-c60f-4fd2-82f5-f6998f4c62b7.png)

## 📝 Steps to Reproduce

1. サイドバーの「見つける」を押す
2.ユーザーをクリック
3.ピン留めユーザーまでスクロール

## 📌 Environment

Misskey version: 13.11.0
Your OS: macOS 13.3
Your browser: Safari

**Comment by syuilo** [comment]
fixed
