### ISSUE TITLE
ユーザープレビューが表示されない / MkUserPopupがでない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10540]
## 💡 Summary

何故かここで`this`がクラスのインスタンスではなくHTMLの`el`要素になっている
https://github.com/misskey-dev/misskey/blob/004ace396dcda9d020f9be32c4aa458f46efdb91/packages/frontend/src/directives/user-preview.ts#L73

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by saschanaz** [comment]
多分 152247bfda62f96e7d3c1be9609692f4cedb5629 ?

**Comment by syuilo** [comment]
あーそれだ

**Comment by syuilo** [comment]
でもなぜこうなるのかは謎

**Comment by saschanaz** [comment]
https://github.com/misskey-dev/misskey/blob/b9d022f1649a0fd350303c08217b06c11479dcee/packages/frontend/src/directives/user-preview.ts#L16-L24

bindよりattachが先に呼ばれるのでbindなしになってしまいます

bind使わなくて普通に`.addEventListener('mouseover', () => this.onMouseover())`しても良さそうです

**Comment by syuilo** [comment]
> bindよりattachが先に呼ばれるのでbindなしになってしまいます

なるほど

> bind使わなくて普通に.addEventListener('mouseover', () => this.onMouseover)しても良さそうです

そうすると

`this.el.removeEventListener('mouseover', this.onMouseover);`

が効かなくならない？

**Comment by saschanaz** [comment]
あー、それはそうですね
