### ISSUE TITLE
「タイムライン上部に投稿フォームを表示する」のフォームでアカウントのアイコンの位置がずれている

### ISSUE THREAD

**Issue by Akkiesoft** [syuilo/Misskey#10545]
## 💡 Summary

「タイムライン上部に投稿フォームを表示する」を有効にしたときの投稿フォームで、アカウントのアイコンの位置が左端ずれているようにみえます。

## 🥰 Expected Behavior

アイコンの左に12pxくらいmarginかpaddingがあるとそれっぽいかと思います（ノートボタンのpaddingの値が12pxだったため）。

<img width="411" alt="アイコンにpadding-left: 12px相当のCSSを適用した" src="https://user-images.githubusercontent.com/422590/230752454-71f620b1-f8aa-4ba8-801e-e55e90f92cb6.png">

## 🤬 Actual Behavior

現状はアイコンが左端に寄っています。

<img width="419" alt="アイコンが左端に寄っている" src="https://user-images.githubusercontent.com/422590/230752441-7fcc2d6f-4565-4d41-abdd-8f5631604eb8.png">

## 📝 Steps to Reproduce

1. 「タイムライン上部に投稿フォームを表示する」を有効にする
2.  タイムラインの投稿フォームを確認する

## 📌 Environment

Misskey version: 13.11.0, 13.11.1
Your OS: macOS 13.3.1
Your browser: Google Chrome 111.0.5563.146

**Comment by MineCake147E** [comment]
Deckのウィジェットでも再現しています。
![image](https://user-images.githubusercontent.com/31585494/230766545-c3947090-5b2e-44fd-a8eb-ff3368494bf8.png)

**Comment by Akkiesoft** [comment]
13.12.1で解消していることを確認しました。
