### ISSUE TITLE
MkUserPopupが出て来ない

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10542]
## 💡 Summary

ユーザーアバタの上でホバーしても何も出ません。コードはあるので廃止ではなさそうです

## 🥰 Expected Behavior

Popupが出る

## 🤬 Actual Behavior

でない

## 📝 Steps to Reproduce

1. ユーザーアバタの上でホバーする
2. 何か出るのか確認

## 📌 Environment

Misskey version: 13.11.0
Your OS: Windows 11
Your browser: Firefox

**Comment by syuilo** [comment]
duplicate of https://github.com/misskey-dev/misskey/issues/10540 ?
