### ISSUE TITLE
ユーザページの画像欄がすぐ閉じる

### ISSUE THREAD

**Issue by nryeouo** [syuilo/Misskey#10552]
## 💡 Summary

ユーザページ（`https://instance.tld/@{user}`）を開いたとき、右上の画像欄がすぐ閉じる

## 🥰 Expected Behavior

サムネイルが8枚くらい出てくる

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/43399370/230765764-504f7b63-0163-4a53-9185-c643b7dbba5e.png)
サムネイルが一瞬出てきて、すぐ上にシューッと畳まれる
開こうとしても、矢印の上下が替わるだけでサムネイルが出てこない

## 📝 Steps to Reproduce

1. https://misskey.io/@notify
2. 右上を見る
3.

## 📌 Environment

Misskey version: 13.11.1
Your OS: macOS 13.3.1
Your browser: Chrome 111.0.5563.146（Official Build） （arm64）

**Comment by fruitriin** [comment]
same here 

13.11.1 https://misskey.systems/

**Comment by takeyaqa** [comment]
上の方のPRで直ってますが、調べた分だけ一応書いときます

- サムネ4枚まで大丈夫で5枚以上で発生
- developmentビルドだと再現せず、productionビルドの時だけ発生

**Comment by syuilo** [comment]
fixed
