### ISSUE TITLE
通知のフィルタができない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10550]
通知はありませんになる

![image](https://user-images.githubusercontent.com/7973572/230761080-30a68099-e461-4383-869b-15c51eceec0b.png)

**Comment by tamaina** [comment]
なぜかリアクションだけはできる？

**Comment by tamaina** [comment]
謎というか条件がわからない

**Comment by tamaina** [comment]
（ログとか通信とかをまだ調べてない

**Comment by mappi-pr** [comment]
@tamaina 
フィルタしたときに、（まず1回）Limit10件でAPIリクエストしていたので
画面の表示上にフィルタ対象となる項目が存在しても、
配列の11件目以降になっているとフィルタに拾われずに「通知はありません」が表示されてしまうようです。

■フィルタ成功パターン
・フィルタ対象が10件目以内にある場合
<img src="https://github.com/misskey-dev/misskey/assets/75538777/96123f33-0abb-4de5-a67d-c265ab1d8541" width="480">
・フィルタが成功する
<img src="https://github.com/misskey-dev/misskey/assets/75538777/9dc8ff3f-6ac8-4232-8f36-ec9970c569a8" width="480">

■フィルタ失敗パターン
・フィルタ対象が11件目以降にある場合
<img src="https://github.com/misskey-dev/misskey/assets/75538777/d8d71866-f3d0-4a07-92a1-a338f25e5cba" width="480">
・フィルタが失敗する
<img src="https://github.com/misskey-dev/misskey/assets/75538777/d7e8784b-a134-454c-97c7-8e1923d15a5f" width="480">


【参考情報】
10件目以内にフィルタ対象が存在すると、Limit30件で再度リクエストを投げて取得できた情報でフィルタしてました。

**Comment by mappi-pr** [comment]
・フィルタしたときのAPIリクエスト
<img src="https://github.com/misskey-dev/misskey/assets/75538777/f90c0121-6b5a-47b7-b8f1-b366ce873520" width="480">

**Comment by mappi-pr** [comment]
（もしかしたら）フィルタかけるたびにpaginationされている？
さっきioでフィルタ連打していたらRatelimitに引っかかったような挙動が見えたので
https://github.com/misskey-dev/misskey/blob/06b1250d4791dbc0c64c1d667e61a0c57a4d371f/packages/frontend/src/components/MkNotifications.vue#L36-L43

**Comment by syuilo** [comment]
される

**Comment by Sayamame-beans** [comment]
自動じゃなくて良いので"もっと見る"(もっと読み込む?)ボタンが表示されると良さそうですね…(2024.2.0の通知カラム(デッキ)と通知ページのフィルタで確認)

**Comment by tamaina** [comment]
Duplicate of #13413
