### ISSUE TITLE
ライブ配信中のYouTube URLを投稿した際、その配信のOGP情報が表示されない

### ISSUE THREAD

**Issue by stakagi** [syuilo/Misskey#10567]
## 💡 Summary

ライブ配信中のYouTube URLを投稿した際、その配信のOGP情報が表示されない。
なお、同一のURLをYouTube上でアーカイブ化された後に投稿すると、OGP情報およびプレーヤーが表示される。

## 🥰 Expected Behavior

ライブ配信中のYouTube URLを投稿した場合でも、アーカイブ後と同様のOGP情報（配信タイトル、サムネなど）が表示される。
（下記のスクリーンショットは、アーカイブ後に投稿したもの）
![image](https://user-images.githubusercontent.com/570189/230846856-d4b61bca-f927-437a-81f1-b853b5648bee.png)

## 🤬 Actual Behavior

ライブ配信中のYouTube URLを投稿した場合、下記スクリーンショットのようにYouTubeサイト全体の説明が表示される。
![image](https://user-images.githubusercontent.com/570189/230846545-a7c880db-2040-4d8e-aa09-25e320382321.png)

## 📝 Steps to Reproduce

1. ライブ配信中のYouTube URLをコピーする
2. コピーしたURLをノートで投稿する

## 📌 Environment

Misskey version: 13.10.3
Your OS: macOS Ventura 13.1
Your browser: Google Chrome 111.0.5563.146

**Comment by stakagi** [comment]
こちらの問題は自分のサーバにて確認していたのですが、試しに他のサーバで再現するか確認してみたところ、misskey.cloudでは再現しませんでした。
サーバ設定の問題かなと思い設定を精査したところ、Summaly Proxyの設定を外すとこの現象が発生しなくなることがわかりました。

そしてcurlコマンドでSummaly Proxyのレスポンスを確認してみたところ、ライブ配信中のURLを与えると下記のレスポンスが返ってきているということまでわかりました。

```
J33778:~/environment $ curl https://summaly.arkjp.net?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDgHU1sZ5Tiw
{"title":"- YouTube","icon":"https://www.youtube.com/s/desktop/932eb6a8/img/favicon.ico","description":"YouTube でお気に入りの動画や音楽を楽しみ、オリジナルのコンテンツをアップロードして友だちや 家族、世界中の人たちと共有しましょう。","thumbnail":null,"player":{"url":null,"width":null,"height":null},"sitename":"www.youtube.com","sensitive":false,"url":"https://www.youtube.com/watch?v=DgHU1sZ5Tiw"}
```

**Comment by tamaina** [comment]
summaly.arkjp.netはyoutubeにリクエストしすぎてアクセスを拒否されることが多い

内蔵summalyもプロキシ通るようになったのでsummaly proxyいらないかも

**Comment by stakagi** [comment]
ローカルにsummaly proxy立てて動かしてみたら問題なかったので、おっしゃる通りyoutubeから弾かれた結果のようです。
問題ないようなのでcloseさせていただきます。

**Comment by acid-chicken** [comment]
> summaly.arkjp.netはyoutubeにリクエストしすぎてアクセスを拒否されることが多い
> 
> 内蔵summalyもプロキシ通るようになったのでsummaly proxyいらないかも

Summaly Proxy の存在意義は他のプロキシと同じではない（アクセス先への負荷を減らす）ためいらなくはない
