### ISSUE TITLE
ヘッダーメニューの参加チャンネルリストが「なし」になる

### ISSUE THREAD

**Issue by takeyaqa** [syuilo/Misskey#10562]
## 💡 Summary

<img width="425" alt="スクリーンショット 2023-04-10 0 28 22" src="https://user-images.githubusercontent.com/13767532/230781820-da0506ac-305a-4988-b7f2-a44f56c6ce34.png">

参加しているチャンネルが存在するにも関わらず、常に「なし」と表示されます。
`/api/channels/my-favorites` の戻りが空っぽいです。

## 🥰 Expected Behavior

参加しているチャンネルのリストが表示される

## 🤬 Actual Behavior

常に「なし」が表示される

## 📝 Steps to Reproduce

1. 任意のチャンネルに参加する
2. ヘッダーメニューのチャンネルアイコンをクリックする

## 📌 Environment

Misskey version: 13.11.1
Your OS: macOS 13.3.1
Your browser: Chrome 112

**Comment by tsaito18** [comment]
これは Misskey v13.11 系からの仕様で、フォロー中のチャンネルではなくお気に入りに登録したチャンネルのみ表示されるようになりました

**Comment by takeyaqa** [comment]
お気に入りにしたら出てきました！クローズします〜
