### ISSUE TITLE
webhookの表示が無限にでる

### ISSUE THREAD

**Issue by magroan** [syuilo/Misskey#10564]
13.11.1においてWebhookの画面を表示すると、登録されているWebhookが無限に表示されてしまう。

**Comment by hidori-11** [comment]
同じような現象が
APIトークン管理画面等でも見受けられます
![rapture_20230410041012](https://user-images.githubusercontent.com/62839406/230792038-2d107227-f13e-40eb-9d8d-0b4d8a3a391f.png)
misskey version: 13.11.1
クライアント: windows 10, google chrome  111.0.5563.111
