### ISSUE TITLE
#5817 が打ち消されている？

### ISSUE THREAD

**Issue by okaits** [syuilo/Misskey#10563]
## Summary
v13.11.1で、リモートのノートにリモートサーバーのユーザーがしたリアクションを見れません。
#5703 で解決していると思ったのですが、どうやらコミット b75184ec8e3436200bacdcd832e3324702553d20 らへんで元通りになってしまったようです。
（あまりmisskeyの構造に詳しくないので、何か間違いがあったら指摘してくれると嬉しいです。）

**Comment by okaits** [comment]
（Enterキーで誤爆してしまいました。すみません...）

**Comment by EbiseLutica** [comment]
@okaits 今後、不具合がある場合は「🐛 Bug Report」をIssue Templateとして選択して内容を埋めていただくようお願いします！

想定通りの挙動が確認できていたのは、どのバージョンのMisskeyでしょうか？

**Comment by okaits** [comment]
あ、すみません...
Issueを作ろうとしたときはもともと最初から存在しない機能だと思っていたので間違えてしまいました...

想像通りの挙動が確認できているバージョンですが、もともと機能追加で作ろうと思っていて調べている時に #5817 を発見したので、こちらでは確認できていません。 すみません...

**Comment by okaits** [comment]
...どうやらいろいろと勘違いしていたようです...
当時のバージョンでいろいろと試してみた結果、どうやら #5817 の意味（というか解釈というか）を間違え、既にあったはずの機能が消えていると思い込んで、要旨が違うIssueを作ってしまっていたことが分かりました...
新しくIssue立てます。お騒がせしました...
