### ISSUE TITLE
アカウントを削除するとそのユーザーが作成したカスタム絵文字が消える

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10576]
## 💡 Summary
アカウントを削除するとそのユーザーが作成したカスタム絵文字が消える

account, user, delete, remove, custom emoji

## 🥰 Expected Behavior
消えない

## 🤬 Actual Behavior
消える

## 📝 Steps to Reproduce
未検証

1. 
2.
3.

## 📌 Environment

Misskey version: 13.6.1
Your OS:
Your browser:

**Comment by EbiseLutica** [comment]
システムドライブ使ってないのよね

**Comment by Sayamame-beans** [comment]
duplicate of #9526
