### ISSUE TITLE
Page機能の文字数上限の緩和をしてほしい

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10574]
## 機能要望

Page機能の文字数上限の緩和をしてほしい

## なぜ必要か

小説・字書き向けのMisskeyサーバーであるノベルスキーを運用しています。
ページ機能に小説を転載されるユーザーが多いのですが、Pageの文字数上限に引っかかって投稿できないという話を高頻度で受けています。

## 現在の状態

調査したところ、ページのセクションなしでシングルバイト文字で3万字、日本語等のマルチバイト文字で1万字程度しか投稿できないことがわかりました。それを超過すると、サーバーから `Failed to load resource: the server responded with a status of 413 ()` が返され保存できません。（エラーダイアログもでず無反応になります）

```
{"statusCode":413,"code":"FST_ERR_CTP_BODY_TOO_LARGE","error":"Payload Too Large","message":"Request body is too large"}
```

原因としてはEndpoint API用のFastifyの[bodyLimit](https://www.fastify.io/docs/latest/Reference/Server/#bodylimit)として一律で `{ bodyLimit: 1024 * 32 }` が設定されているためです。
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/ApiServerService.ts#L92

ページに関してはcontentはDBにjsonbで保存されるためパフォーマンスを考えなければ最大1GB程度までは保存できるはずです。
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/models/entities/Page.ts#L81
もちろん1GBはやりすぎですが、日本語で1万文字は文字量として少ないと考えられます。json形式ですのでセクションで分けた場合はもっと最大文字数が減ることになります。

## 希望する状態

+ 少なくともページ用APIに関してbodyLimitをセクションなしでマルチバイト文字10万文字程度まで緩和いただきたい(現在の10倍)
+ 可能であれば最大文字数を超過した場合はエラーダイアログを表示していただきたい

**Comment by syuilo** [comment]
32倍にしてみました

**Comment by acid-chicken** [comment]
> 59ca0d21a1722fcf0c8494005c51886cffd3aa4e

で 4 万字になったけど、まだ足りる時と足りない時がありそうだしいっそのこと 1MB (約 35 万文字) とかでもいい気がする

**Comment by acid-chicken** [comment]
と思ったら行き違いだった @ 43eee54f2d98f29f2d473671c7b32fd9505e9e52

**Comment by syuilo** [comment]
Pages以外でも管理者用絵文字管理APIあたりで一度に大量に操作する場合1MBくらい行く可能性もありそうだなと思ったから1MBにした

**Comment by ghost** [comment]
ありがとうございます！
