### ISSUE TITLE
13.11.2でカスタム絵文字のリアクションができない。（デフォルトの絵文字は可能）

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10584]
## 💡 Summary

13.11.2でカスタム絵文字のリアクションができない。（デフォルトの絵文字は可能）

## 🥰 Expected Behavior

カスタム絵文字でリアクションできる。

## 🤬 Actual Behavior

カスタム絵文字でリアクションできない。
`POST https://novelskey.tarbin.net/api/notes/reactions/create 500` が返ってくる

## 📌 Environment

Misskey version: 13.11.2
Your OS: Windows10
Your browser: Google Chrome バージョン: 111.0.5563.147

**Comment by ghost** [comment]
レスポンスです。
```
{
    "error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "JSON.parse(...).map is not a function",
                "code": "TypeError",
                "id": "d3ab04e6-1e7b-4c6a-9d09-bf54150f8bde"
            }
        }
    }
}
```

**Comment by tmd45** [comment]
こちらと関係する話っぽい
https://github.com/misskey-dev/misskey/issues/10502#issuecomment-1502786825

**Comment by tamaina** [comment]
Duplicate of #10502

**Comment by ghost** [comment]
対応メモです。以下で対処できました。
https://github.com/misskey-dev/misskey/issues/10502#issuecomment-1502889268
