### ISSUE TITLE
ロールタイムライン

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10581]
## Summary

指定したロールを持つ人の投稿だけが流れるタイムライン

### ユースケース
- 新規ユーザーが入るコンディショナルロールを作って新規ユーザーTLを見れるようにし新規ユーザーを見つけやすくする

**Comment by EbiseLutica** [comment]
タイムラインの表示範囲を、各ロールごとに
* 表示しない
* ロールを持つ人のみ表示する
* 表示する

って感じにしたら、ロール保有者限定のTLも作れそう

**Comment by syuilo** [comment]
仕組み上コンディショナルロールは予めどのユーザーが該当するかは知ることができない(あるユーザーが与えられたとき、そのロールに該当するかどうかを知ることしかできない)からロールTLを実装する場合アンテナと同じような仕組みになりそう
