### ISSUE TITLE
フォローしているユーザーについた全てのリアクションを他のサーバーから受け取りたい

### ISSUE THREAD

**Issue by okaits** [syuilo/Misskey#10587]
## Summary
フォローしているユーザーが投稿したノートについたリアクションを、別のサーバーからも全て見れるようにしてほしいです。

**Comment by tamaina** [comment]
Related to https://github.com/misskey-dev/misskey/issues/10167 ?

**Comment by okaits** [comment]
検索に引っかかりませんでした...
既にあったんですね、失礼しました...
