### ISSUE TITLE
antennas/notesのsinceId, sinceDateが無視される

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10599]
paramDefには残っている

対応予定はある？

**Comment by syuilo** [comment]
仕組み上は対応可能そう？

**Comment by tamaina** [comment]
RedisミリしらだけどuntilIdができてるんだからsinceIdもできるのでは

**Comment by blackwingcat** [comment]
これに関係して
https://misskey-hub.net/docs/api/endpoints/i/notifications.html
こっちの sinceIdも無視されてないです？
他のクライアントでいつまでも通知が表示されてるのもこれが原因の様な気がしてる･ω･

**Comment by blackwingcat** [comment]
そもそも、 server/api/endpoints/i/notifications.ts
見たら実装してない事に気づいた ･ω･

@syuilo
