### ISSUE TITLE
カスタム絵文字を含むノートの配送ができない・リモートにカスタム絵文字でリアクションしても届かない

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10603]
## 💡 Summary
リモートにカスタム絵文字でリアクションしても届かない

## 🥰 Expected Behavior
リモートにカスタム絵文字でリアクションすると届く

## 🤬 Actual Behavior
ジョブキューには特にエラーは残っていません

### カスタム絵文字
![image](https://user-images.githubusercontent.com/61890205/231451046-4b41a12d-9b90-4c38-9317-df13e8531112.png)
![image](https://user-images.githubusercontent.com/61890205/231450996-2da28be0-60ff-4062-a72d-2fe7bfb9de3c.png)

### Unicode絵文字
![Screenshot from 2023-04-12 21-02-45](https://user-images.githubusercontent.com/61890205/231451223-0f7168de-833f-469d-bc92-246c9417643f.png)
![image](https://user-images.githubusercontent.com/61890205/231451138-88667ec3-4455-4427-8385-6388b25cceb4.png)

## 📝 Steps to Reproduce

1. リモートにカスタム絵文字でリアクション
2. 
3.

## 📌 Environment

Misskey version: v13.11.2
Your OS: Rocky Linux
Your browser: Firefox

## 参考情報（？）

 - アップデート後しばらくは順調に動いていたのですが突然できなくなりました（設定も弄ってないので本当に突然）
 - Unicode絵文字でのリアクションやリアクション取り消し、カスタム絵文字を含まないリプライは正常に遅延なく行われます

### 試してだめだったこと
 - Misskey再起動
 - `del example.com:singlecache:localEmojis`

**Comment by nexryai** [comment]
これリプライにカスタム絵文字が入ってても同じ現象が発生することがあるみたいです。
![image](https://user-images.githubusercontent.com/61890205/231451835-049737dc-e4aa-473e-a0e2-5db73ad0a991.png)
![image](https://user-images.githubusercontent.com/61890205/231452044-ff521ce0-7b59-4701-a52a-16be960f7efd.png)

**Comment by nexryai** [comment]
~~RedisをFLUSHALLで爆破したら治りました~~ 即再発

**Comment by nexryai** [comment]
これカスタム絵文字を含むノートの配送自体が死んだっぽいです

**Comment by nexryai** [comment]
journaldに`emoji.updatedAt.toISOString is not a function`というログが残ってました（配送できないのと関係あるんでしょうか？）
![image](https://user-images.githubusercontent.com/61890205/231468709-52f0377d-bbed-4727-a6d6-010d01a0fe7a.png)

**Comment by okayurisotto** [comment]
4c0ef07 時点で`git grep 'emoji.updatedAt.toISOString'`したところ、[`ApRendererService.ts`](https://github.com/misskey-dev/misskey/blob/4c0ef07/packages/backend/src/core/activitypub/ApRendererService.ts#L176)でその処理が行われている（そこでしか行われていない）ようでした。なのでおそらく配送できない問題と関係があると思われます。

**Comment by okayurisotto** [comment]
このIssueはこのコミット（とそれに関連したいくつかのコミット）により解決しているかもしれません。
https://github.com/misskey-dev/misskey/commit/d06d1e868263e89de1a8f7dbd6636c6cc37df607

journaldに残されたログの内容は、配送を担うActivityPubの処理が行われる`ApRendererService`において、`Date`型ではないRedisから得たデータに`Date`型専用の`toISOString()`を呼び出していることによって`TypeError`が発生したことを示しています。

配送を担う処理をする場所で起きたエラーですので、このエラーとこのIssueは関連があると思われます。

上記PRではRedisからのデータ取り出し時にあらかじめ`Date`型へ変換しておく処理がされています。そのため、このエラーは上記PRが適用されたバージョンであれば起きないものと思われます。

そもそもの上記PRがどういった経緯で作成され、上記PRで修正された「カスタム絵文字でリアクションできないことがある問題」がこのIssueの内容を含んでいるかについては情報を追えていないのでわかりませんが、少なくともjournaldに残されたログの件については解決済みだと思われます。

**Comment by nexryai** [comment]
ご丁寧にありがとうございます！！！  
該当コミットを適用してみたところ、無事に動作しました。本当にありがとうございます🙏  
この不具合の影響範囲はリアクションできないどころかカスタム絵文字が絡む連合関係の処理がほとんど全滅してたので早急にアップデートで出すべきだと考えます。

**Comment by nexryai** [comment]
これカスタム絵文字が本文になくてもリアクションに入ってるノートも配送されてない可能性（13.11.2のioで観測した）

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/10502 と同じだと思う

**Comment by remador** [comment]
Estou fazendo uma ocorrência policial.
Muito obrigado!
@remador
