### ISSUE TITLE
ユーザーを検索するとHITした値が無限に羅列される

### ISSUE THREAD

**Issue by magroan** [syuilo/Misskey#10607]
検索よりユーザーアカウントを検索すると、スクロール時に該当者が無限に表示されてしまう。

**Comment by fruitriin** [comment]
same here 
みすてむず 13.11.3

![スクリーンショット 2023-04-14 0 33 39](https://user-images.githubusercontent.com/18308639/231810587-57844a35-6420-47e0-861e-3e8b0df48aa7.png)

**Comment by Nanashia** [comment]
dup? #10432

**Comment by zagan-the-gun** [comment]
私もmisskey.ioで同じ現象出ました
"全て" や "ローカル" で自分を検索したら大量に自分が表示される
"リモート" で他鯖の自分の垢を検索すると "ユーザーはいません"
一度でもユーザはいません表示が出ると再び "全て" や "ローカル" で表示されてたユーザを検索しても表示が変わらず
全体的に挙動が変？
![スクリーンショット 2023-08-02 11 58 32](https://github.com/misskey-dev/misskey/assets/3014836/9580b94e-6bb2-4bbf-bc50-52f2408d9063)

**Comment by yulog** [comment]
ユーザ検索のページネーションがおかしいようです。
DevToolsで見ると`untilId`を指定しているようですが、
APIコンソールで見ると`untilId`はなさそうでした。

```
{
  query: '',
  offset: null,
  limit: null,
  origin: '',
  detail: false,
}
```

初回は最初の10件表示して、そのあとはスクロールされるたびに最初の30件が順次表示されるだけのようです。

**Comment by yulog** [comment]
@zyoshoka misskey.ioで確認した限りでは、まだ解消していないように思います。
スクロールすると無限に増えますし、一意にならない検索では最初の30ユーザ以外は全部重複です。

エンドポイントを `untilId` 対応にするか、フロントエンドを `offset` 使うようににするかしないといけないのではないでしょうか。

**Comment by tai-cha** [comment]
@yulog 
> misskey.ioで確認した限りでは、まだ解消していないように思います。
> スクロールすると無限に増えますし、一意にならない検索では最初の30ユーザ以外は全部重複です。

mi.taichan.site, misskey.backspace.fm, misskey.niri.la, misskey.systems の4サーバーで試して再現しないのでmisskey.io特有の症状の可能性があります

**Comment by yulog** [comment]
本当ですね…
ほかのサーバーでは再現しませんでした。

**Comment by zyoshoka** [comment]
https://github.com/MisskeyIO/misskey/commit/13e8dbaf96b41c45ff1b8bfd491d1f57190e7b39

確認したところ上記コミットが revert されているようなので恐らくそのようです。

**Comment by yulog** [comment]
ありがとうございます。
misskey.io固有の問題なんですね。
若干不便ですが、致命的ではないので何れ直るのを待ちます。
