### ISSUE TITLE
チャンネル内で返信する際に公開範囲を選べるが、ダイレクトなどに変更してもチャンネル内ノートになる

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [syuilo/Misskey#10619]
## 💡 Summary

チャンネル内で返信する際に公開範囲を選べるが、ダイレクトなどに変更してもチャンネル内ノートになる

## 🥰 Expected Behavior

選んだ公開範囲になる
もしくは、返信時に公開範囲を変更できなくする

## 🤬 Actual Behavior

公開範囲を変更できたように見えるが、実際にはチャンネル内ノートのまま

## 📝 Steps to Reproduce

1. チャンネル内のノートに返信をする
2. 公開範囲をダイレクトに変更する
3. ノートする

## 📌 Environment

Misskey version: 13.11.2
Your OS: Windows 10 Home 22H2
Your browser: Chrome

**Comment by Sayamame-beans** [comment]
triage: 恐らく解決済み(範囲変更不可に見える)
