### ISSUE TITLE
本人のプロフィールにはロールを表示するがexploreには載せないオプション

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10629]
## Summary
私のサーバーではシャドウバンみたいな感じにはしたくないのでサイレンスロールを公開にしているのですが、ロールタイムラインが実装された影響でサイレンスされた人間の投稿しか流れてこないタイムラインが誕生してしまいました。
本人のプロフィールにはロールを表示するがexploreには載せたくないという場合に使えるオプションがあると大変助かります。

**Comment by syuilo** [comment]
> ロールタイムラインが実装された影響でサイレンスされた人間の投稿しか流れてこないタイムラインが誕生してしまいました。

それが問題だとするとexploreに載せないというよりタイムラインとして利用不可にできた方が良さそう

**Comment by nenohi** [comment]
これに関して試しにコード書いてるけど、
ロールタイムラインが無いの場合、ユーザー一覧もそのオプションに合わせたほうがいいよね？

**Comment by syuilo** [comment]
よさそう
その場合オプション名は isExplorable とかかしら

**Comment by nenohi** [comment]
ロールタイムラインメインで作ってたから
isRoleTimelineとかの名前にしちゃってた

**Comment by syuilo** [comment]
一括置換しようぜ

**Comment by nenohi** [comment]
これに関してはTLを無効化するオプションだけでは難しいかも？

**Comment by nenohi** [comment]
@nexryai これでどうでしょう？
ロールタイムラインの無効化を行いました。
ロールがついている一覧には人が出てきますが。。。。。。。。。。。
#10677

**Comment by nexryai** [comment]
ありがとうございます🙏
無事解決できるのでCloseします
