### ISSUE TITLE
V13.11.x系のサーバーにおいて、他のサーバーの情報が取得できない

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#10631]
## 💡 Summary

v13.11.x系のサーバーから他のサーバーのNoteを表示させたときに、
Noteに表示されるべきサーバー名・アイコン・サーバーカラーが反映されない

## 🥰 Expected Behavior

全てのリモートユーザーのNoteに適切なサーバー名が表示され、サーバーカラーの背景がつき、サーバーアイコンが表示される

## 🤬 Actual Behavior

A -> B を「AのサーバーでBのNoteを見た際」としたとき、以下の条件でサーバー情報がNoteに表示されない

v13.11.x -> v13.11.x
v13.11.x -> v13.10.x
v13.11.x -> v.13.9.x
v13.11.x -> Mastodon系サーバー

なお、逆向きは反映される。（検証不十分な可能性はあり）
ただし、どうやら以前から連合になっているサーバーの情報などは問題なく表示されている。

## 📝 Steps to Reproduce

1. v13.11.x系でc13.11.xへのアップデート以前から連合関係にないサーバーのNoteを閲覧する
2. サーバー情報がない

## 📌 Environment

Misskey version: v13.11.3 / v13.10.3
Your OS: CentOS Stream 8
Your browser: Chrome 112.0.5615.87

**Comment by nexryai** [comment]
v13.11.x → dolphinで再現しました（v13.10.xからは正常に取得できているのでDolphin側での問題ではなさそう）

https://misskey.io/@nexryai@s.nexryai.online

**Comment by nexryai** [comment]
[`/instance-info`](https://misskey.io/instance-info/s.nexryai.online)から見ると普通に取得できてるっぽいです

![image](https://user-images.githubusercontent.com/61890205/232266088-c38863d6-b674-4826-91b3-d680d4e9f14a.png)

**Comment by GrapeApple0** [comment]
こちらの方でいろいろ試した結果、https://github.com/misskey-dev/misskey/commit/1377ea4178ffb49cc76466df56ef945fc4c2f713 が原因になっていました(これ以前のコミットをチェックアウトするとちゃんと動いたため)。

**Comment by tamaina** [comment]
（RedisKVCache系の実装、副作用多くない？）

**Comment by sasagar** [comment]
packages/backend/src/core/entities/UserEntityService.ts
において、 1377ea4178ffb49cc76466df56ef945fc4c2f713 で大幅に削除された**だけ**の部分があるのは良いのでしょうかね...？
L122あたりからの部分が削除されて代替の記述は増えていない様子でした。

**Comment by GrapeApple0** [comment]
初期状態(id/host/firstRetrievedAtのみ書き込まれている)のデータを削除して再度取得させると正しく表示されたので、おそらく更新に失敗している感じだと思います。

**Comment by ghost** [comment]
こちら自分も再現しました。
<img width="608" alt="image" src="https://user-images.githubusercontent.com/23691696/233774669-a2acbb6a-86ef-4c63-8a49-0ed3f9ca5a60.png">
Redisの`<domain>:kvcache:federatedInstance:<host>` にnullが入ってるようですね。
連合先のサーバーで `redis-cli --scan --pattern '<domain>:kvcache:federatedInstance:*' | xargs redis-cli DEL` でキャッシュを消すと解消しました。

**Comment by GrapeApple0** [comment]
強制的にアップデートするようにした結果ちゃんと動くようになった(https://github.com/GrapeApple0/misskey/commit/e366aa965ebbdf6fa4e7894dbf4e09c1305ba050 )ので作成時のデータをずっと引きずってる感じです。

**Comment by syuilo** [comment]
メモリキャッシュを3min、Redisキャッシュを30minに短くしたのと、更新があったときにRedisキャッシュにも反映させるようにしてみた

**Comment by fu-sen** [comment]
古い Issues を上げますが。サーバー管理者関連の Discord でこの問題が出ている報告を受けています。
この原因がどうも単に OS パッケージによる Redis 6 系を維持していて Redis 7 へ更新していないのが原因のようです。
これを経験している場合、公式の最新 Redis を使用するようにして下さい。
https://misskey-hub.net/docs/releases.html#_13-11-0

**Comment by zyoshoka** [comment]
現在では解決されているようですのでクローズします。
