### ISSUE TITLE
CI: Cypressが落ちてる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10644]

**Comment by tamaina** [comment]
nodeバージョンを上げたのが原因…？

**Comment by syuilo** [comment]
落ちるかどうかはランダムっぽい

**Comment by syuilo** [comment]
tasukete

**Comment by acid-chicken** [comment]
>  Warning: Unexpected input(s) 'headless', valid inputs are ['record', 'auto-cancel-after-failures', 'config', 'config-file', 'env', 'browser', 'command', 'start', 'start-windows', 'build', 'install', 'install-command', 'runTests', 'wait-on', 'wait-on-timeout', 'parallel', 'group', 'tag', 'working-directory', 'headed', 'publish-summary', 'spec', 'project', 'command-prefix', 'ci-build-id', 'cache-key', 'quiet', 'component']

これは `headless: false` じゃなくて `headed: true` ってことでは

**Comment by syuilo** [comment]
> > Warning: Unexpected input(s) 'headless', valid inputs are ['record', 'auto-cancel-after-failures', 'config', 'config-file', 'env', 'browser', 'command', 'start', 'start-windows', 'build', 'install', 'install-command', 'runTests', 'wait-on', 'wait-on-timeout', 'parallel', 'group', 'tag', 'working-directory', 'headed', 'publish-summary', 'spec', 'project', 'command-prefix', 'ci-build-id', 'cache-key', 'quiet', 'component']
> 
> これは `headless: false` じゃなくて `headed: true` ってことでは

直した

**Comment by syuilo** [comment]
成功確率10%くらいな気がする

**Comment by syuilo** [comment]
エラーメッセージが無いというのが困る

**Comment by syuilo** [comment]
今は
EncodingError: The source image cannot be decoded
で落ちてる

**Comment by samunohito** [comment]
今のところ落ちてないのでcloseします
また落ちたら別途起票という事で…
