### ISSUE TITLE
「タイムラインにノートへの返信を表示する」がプロフィール設定にあるのはおかしい気がする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10646]
showTimelineReplies, flagShowTimelineReplies

クライアント設定 - 全般 あたりに移動した方が適切そう

**Comment by syuilo** [comment]
設定はアカウントに保存されてAPI/サードパーティアプリにも適用されるから「Webクライアント設定」ではないのは確かなんだけど、プロフィールにあるのもおかしいのはそうなんだよな

**Comment by tamaina** [comment]
他のページにあってi/updateで更新する項目もあるので…

**Comment by syuilo** [comment]
どこから叩いたかに関わらずAPIのレスポンスを変えるオプションがクライアント設定にあるのは違うかもと思った感じ

**Comment by syuilo** [comment]
この設定の挙動自体を再考した方が良さそう(アカウント設定で一律に適用されるのではなくてAPI呼び出ごとにパラメータで指定できるようにするとか)

**Comment by syuilo** [comment]
そうすれば心置きなくクライアント設定に移動できる

**Comment by tamaina** [comment]
@syuilo

**Comment by syuilo** [comment]
やるわ

**Comment by syuilo** [comment]
そもそもタイムラインにフォロイーの他人のノートへの返信を表示する必要ある？

**Comment by Steve-0628** [comment]
> そもそもタイムラインにフォロイーの他人のノートへの返信を表示する必要ある？

あります、少なくとも私はこのオプションを有効にしています

**Comment by syuilo** [comment]
なんで必要？

**Comment by Steve-0628** [comment]
自分のタイムラインには、フォローしている人の投稿を表示したい、それが知らない人へのリプライであっても表示したい、と思っています。

**Comment by nexryai** [comment]
好みの問題なので理由を問われると難しいところではあるけど、有効にする理由としては
 - TLが賑やかになる
 - 交流の幅が広がる
 
とかが多そう（自分も有効にしている）

**Comment by tamaina** [comment]
> 必要ある？

ある
