### ISSUE TITLE
お知らせの画像URLを空にできない

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#10657]
## 💡 Summary

お知らせの画像URLに入力して保存後、再度URLを空にして保存しようとするとエラーが発生する

## 🥰 Expected Behavior

画像URLが空でも保存できるようにする。

## 🤬 Actual Behavior

エラーダイアログが発生する

## 📝 Steps to Reproduce

1.お知らせを作り、画像URLを記載して保存する
2.作ったお知らせから画像URLを削除する

## 📌 Environment

Misskey version: 13.11.3
Your OS: iOS13.4
Your browser:Safari

**Comment by Sayamame-beans** [comment]
maybe fixed by #10878
