### ISSUE TITLE
削除した投稿に関する通知があるときに通知欄が無限にリロードされる

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10650]
## 💡 Summary
タイトルの通り

レートリミットに引っかかるので厄介

## 🥰 Expected Behavior
- 削除した投稿に関する通知が出ない
- 無限リロードが発生しない

## 🤬 Actual Behavior
- 通知欄が表示されない
- レートリミットになるまで（なっても）リロードがかかる

![image](https://user-images.githubusercontent.com/67428053/232284217-c37dbe2f-44d2-4f48-a7f1-b3970e790c8c.png)

## 📝 Steps to Reproduce

1. ノートを作成
2. リアクションなどで通知を入れてもらう
3. ノートを削除
4. 画面再読み込み
5. 通知欄を表示する

## 📌 Environment

Misskey version: 13.11.3
Your OS: Windows 11 Version 22H2 (Build 22621.1413)
Your browser: Google Chrome 112.0.5615.86 (Official Build) （64 ビット） (cohort: Stable)

**Comment by syuilo** [comment]
再現できなかった

**Comment by syuilo** [comment]
最初に読み込まれる通知全てが削除されたノートに対するものである場合も確認したけどやっぱり再現しなかった

**Comment by syuilo** [comment]
@kakkokari-gtyih 
これローカル環境で発生したものですか？

**Comment by kakkokari-gtyih** [comment]
直近で事象を確認したのはioですが、前に似たようなことが別サーバーで起きた覚えがあるんですよね

どこかは忘れました（すみません）
