### ISSUE TITLE
アカウントをブロックしてもすでに貰った通知は消えない

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10652]
## 💡 Summary

タイトル通り。フロントエンドでブロックリストをキャッシュしてフィルタリングできそうです（バックエンドでするのはちょっとリソース使いすぎになるかも？）

## 🥰 Expected Behavior

通知が消える

## 🤬 Actual Behavior

消えない

## 📝 Steps to Reproduce

1. スパムアカウントをブロック
2. 通知が消えたのか確認

## 📌 Environment

Misskey version: 13.10.3
Your OS: Windows 11
Your browser: Firefox

**Comment by Sayamame-beans** [comment]
ブロックはどちらかというと相手から自分を見えなくするものなので、違いそうです。
(ブロックと通知に関する怪しい挙動自体はあったのでそっちに移行で… #14984 )

**Comment by saschanaz** [comment]
ミュートしたら消えますか？（試してない）
