### ISSUE TITLE
プロフィールページでアカウントを切り替えても表示が変わらない

### ISSUE THREAD

**Issue by chimorium** [syuilo/Misskey#10664]
## 💡 Summary
複数アカウントを管理しているとき、プロフィールページを開いた状態でアカウントを切り替えられない。

## 🥰 Expected Behavior
選択したアカウントのプロフィールページが表示される。

## 🤬 Actual Behavior
元のアカウントのプロフィールページが再表示される。（内部的にはアカウントは切り替わっている）

## 📝 Steps to Reproduce

1. 複数アカウントA,Bを持った状態にする。
2. アカウントAのプロフィールページを開く。
3. アカウントをクリックし、ポップアップからアカウントBを選択する。

## 📌 Environment
Misskey version: v13.11.3
Your OS: Windows 11
Your browser: Google Chrome

---
packages/frontend/src/account.ts login関数でunisonReload();を引数無しで呼んでいるため、現在のページがリロードされてしまいます。しかしタイムラインを表示した状態の場合はその動作で正しく、修正方針を決めかねたので、Issueとさせていただきました。

**Comment by nenohi** [comment]
例えをそのまま使わせていただきたいのですが、
この場合、別なユーザーページCを開いていた状態でもBに切り替わってしまうということではなく、
自分のプロフィールの際に表示が切り替わってほしいということでしょうか？

**Comment by chimorium** [comment]
自分ではないユーザーページCを開いた状態でも、左下のアカウントポップアップからアカウントBを選択したら、
アカウントBのユーザーページに切り替わってほしいかなと思いました。
（現在はユーザーページCが再表示されている）

**Comment by nenohi** [comment]
モデレーション観点で少しお話を
複数のページで色々なユーザーページを開いたり情報を見たりしているので、全てのページでBに切り替わってしまうと
だいぶ不便を感じると思います。

また、この人こっちのアカウントからフォローしようなどの行為の際にアカウント切り替え時に自分のアカウントが表示されるのは煩わしく感じるのではということも考えられます

**Comment by chimorium** [comment]
なるほど。
プロフィールページはいわゆるマイページではなく、あくまでも＠～のユーザーを表示しているだけ、
という見方をすれば、おっしゃることが納得できました。
閉じます。
