### ISSUE TITLE
アンテナの新規通知が死んでいる

### ISSUE THREAD

**Issue by DJMIMA** [syuilo/Misskey#10678]
## 💡 Summary

おそらく13.11系列になってから、アンテナの設定で「新しいノートを通知する」をオンにしても通知されなくなっている。

## 🥰 Expected Behavior

アンテナに新規ノートがあった場合に、アンテナ名の横に緑の丸が表示される（通知される）

## 🤬 Actual Behavior

新規のノートがあってます通知されない。

## 📝 Steps to Reproduce

1.任意のアンテナを作成
2.「新しいノートを通知する」をON

## 📌 Environment

iOSのPWA、Windows環境で確認。

Misskey version:13.11.3
13.10.3では再現しないことを確認。

**Comment by Sayamame-beans** [comment]
13.14.2現在でも同様です。

**Comment by samunohito** [comment]
（アンテナにヒットした時に通知を投げる処理がバックエンドから無くなっている説が濃厚。動いてた当初の挙動がわからないので当時の実装を追う必要あり…）

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/compare/13.10.3...13.11.3#diff-e2b26cba839deeaaa3619fe028cb6dc17315367c257cfe3d33333fcbad073fb5L94-L141

アンテナのRedis化で消えたっぼい

https://github.com/misskey-dev/misskey/compare/13.10.3...13.11.3#diff-d05ba00fc2af36446f0d4eb49e872af625db241bc10ab3f9e5ee94aec88b37e6L174-L216

当初の実装だとnoteが読まれたタイミングで通知が生成されてるけど現行実装だと既読管理大変そうですし辛いし用途的にもこっちのほうが良さそうだと思うので、アンテナ追加時(ノート投稿時)に通知で実装するのが良さそうですかね

**Comment by fruitriin** [comment]
ノートひとつにつき通知が作られて既読管理をするというのがパフォーマンス的に厳しいねということでその処理が削除されたような記憶があります
リストやチャンネルの新着通知が見に行った時にあるかないか知りたいくらいなら、個別に既読管理をする必要は多分なくて、最後に投稿された時間と、最後にアクセスした時間があればよいように思います。
最後にアクセスした時間はlocalStorageかRegistryにJSONで入れておくとよいのではないかと温めていたので供養します

**Comment by anatawa12** [comment]
そもそも通知の仕様を勘違いしてました。(通知欄に追加だと思っていました。)フレンドに確認して音がなるのがメインの仕様だと理解しました。

元々の仕様は[アンテナに新着noteが来て、2秒以内に読まれない場合に音を鳴らす]のがメインの仕様ということで間違いなさそうですかね。

既読処理は2秒以内の部分で使用されてるようですが、２秒以内に読まれない場合という条件の意図を理解できませんでしたのですが既読管理の意図としては何なのでしょうか。

**Comment by meronmks** [comment]
> 2秒以内に読まれない場合に音を鳴らす

推測多めだけど、おそらく通知音をWebAudioで鳴らす前は同時再生不可だったのもあり例えば2つ同時に再生要求するとどっちかが鳴らない or 両方鳴らないとかになってしまうかで、ならもう重なることがほぼ前提の通知音系はわざとディレイかけてたのでは説・・・？

**Comment by syuilo** [comment]
アンテナの通知は廃止されてるので、通知オプションの消し忘れかしら

**Comment by anatawa12** [comment]
元々が消し忘れだったとしても、需要があるから投稿直後の音を鳴らすだけでいいから復活させたいが私のやりたいことです

**Comment by syuilo** [comment]
パフォーマンス的に難しそう

**Comment by anatawa12** [comment]
音ながすイベント発行だけでもきつい感じですか

**Comment by syuilo** [comment]
アンテナに投稿が追加されるたびにストリーミングにイベント流すとなるとかなり影響があると思われる

**Comment by meronmks** [comment]
> アンテナの通知は廃止されてる

あれじゃあこのIssueとはズレますがもしやチャンネルの新着通知音が鳴らないのも廃止されてるけどオプションから消し忘れてるオチだったります？

**Comment by syuilo** [comment]
かも

**Comment by samunohito** [comment]
（実装方針と難易度の話だからずれるかもしれないです）

音を出すだけであれば…
antenna-timeline.vueがアンテナの情報を持ってるので、通知がONのアンテナはTL更新時に発音、みたいな感じでいけませんかね？（antenna-column.vueにはないので、同様の仕組みを用意する必要ありますが）

通信は圧迫せず、あくまでクライアント側の解決みたいな感じで

**Comment by syuilo** [comment]
それなら可能だけどあまり実用的ではないかも(見ているアンテナの通知音出されても役にたつことは少なそう)

**Comment by anatawa12** [comment]
カラムの数が多いと音なるのは嬉しいです。隠れてること多いので。

**Comment by samunohito** [comment]
（アンケート中。ちなみに僕もデッキ表示してて横に一杯あるので音が鳴ると嬉しいです）

https://misskey.systems/notes/9n03rqa7sq

**Comment by samunohito** [comment]
@syuilo 
↑をみるかぎり需要ありそうだし、負担がかからない形なら実装してもよいとおもいました
いかがでしょう

**Comment by anatawa12** [comment]
今実装を進めてて思ったのですが、deck uiのアンテナカラムに限った実装になる方針なので、アンテナに限らず他のカラムについてもopt-inで新規noteで音がなる設定があればいいと思ったのでそのように一旦実装します。
