### ISSUE TITLE
/api/users/notes のsinceDateとuntilDateが壊れている

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10679]
## 💡 Summary
/api/users/notes のsinceDateとuntilDateが壊れている

## 🥰 Expected Behavior
 - `sinceDate`や`untilDate`にUNIX時刻を入れればそれが反映されたノート一覧が返ってくる

## 🤬 Actual Behavior
 - `untilDate`は0以外を入れると空の配列が返ってくる
 - `sinceDate`は何を入れてもそのユーザーの最初から`limit`番目までのノートが返ってくる

## 📝 Steps to Reproduce

1. `curl -X POST -H "Content-Type: application/json" -d '{"userId": "idididididid", "sinceDate": 適当な数字, "limit": 10}' https://example.com/api/users/notes`
2.
3.

## 📌 Environment

Misskey version: v13.11.3
Your OS: Rocky linux
Your browser: curl

**Comment by futchitwo** [comment]
sinceDate等はミリ秒単位なので、UNIX時刻*1000してください。

**Comment by nexryai** [comment]
ありがとうございます。言われたとおりミリ秒にしたら想定通り動きました🙏
