### ISSUE TITLE
リモートの投稿で投票に使われたカスタム絵文字が絵文字として描画されない

### ISSUE THREAD

**Issue by Steve-0628** [syuilo/Misskey#10689]
## 💡 Summary
タイトルの通りです。

## 🥰 Expected Behavior
絵文字として描画される

## 🤬 Actual Behavior
文字になる

## 📝 Steps to Reproduce

1. 投票に絵文字を使う
2. 別のサーバーでその投稿を見る
3.

[リモートでの表示例](https://honi.stesan.dev/notes/9ds71lzuqx)
[リモートでの表示例2](https://mk.shrimpia.network/notes/9ds71lzum9)
[元の投稿](https://misskey.io/notes/9ds71lzull)

## 📌 Environment

Misskey version: 13.11.3
Your OS: Windows 11
Your browser: Firefox 112

**Comment by Sayamame-beans** [comment]
duplicate of #11763 (統合します)
