### ISSUE TITLE
ノートのリモートサーバーの情報の表示に失敗することがある

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10691]
## 💡 Summary

ノートのリモートサーバーの情報の表示に失敗することがある

## 🥰 Expected Behavior

ノートのリモートサーバーの情報の表示を正しく行う

## 🤬 Actual Behavior

ノートのリモートサーバーの情報の表示に失敗する

<img width="608" alt="image" src="https://user-images.githubusercontent.com/23691696/233773428-7f911c40-5f78-4c9b-bc7a-e60dfbd932bc.png">

## 📝 Steps to Reproduce

1. 新しいサーバーを建てる
2. 他のサーバーと連合する
3. 連合先でサーバーの情報が正しく表示されない
4. 連合先のサーバーで`redis-cli --scan --pattern '<domain>:kvcache:federatedInstance:*' | xargs redis-cli DEL` でキャッシュを消すと解消する

## 📌 Environment

Misskey version: v13.11.3
Your OS: Windows 10
Your browser: Chrome

**Comment by ghost** [comment]
ここらへんでなにか失敗してそうな感じがします。
https://github.com/misskey-dev/misskey/blob/567c66567e85e4077365386e06e96c85c78e206a/packages/backend/src/core/entities/UserEntityService.ts#L349
https://github.com/misskey-dev/misskey/blob/567c66567e85e4077365386e06e96c85c78e206a/packages/backend/src/core/FederatedInstanceService.ts#L25

**Comment by ghost** [comment]
おそらくキャッシュの値にnullが入ってる場合に再取得が走らないようです。

**Comment by nexryai** [comment]
#10631 の重複かも

**Comment by ghost** [comment]
あー重複ですね。こちらはCloseします。
