### ISSUE TITLE
Cannot follow people who are using Misskey

### ISSUE THREAD

**Issue by yuowo39** [syuilo/Misskey#10692]
## 💡 Summary

After I reinstall my Mastodon instance, I cannot follow the same people who are using Misskey.

## 🥰 Expected Behavior

I can follow the same people who are using Misskey on my Mastodon instance after I reinstall it.

## 🤬 Actual Behavior

I tried to follow the same accounts as I followed before, which are not protected, and then I saw I needed to wait for their following approvals.

**Update:
I cannot follow anyone on special Misskey servers.
Please move on to the below.**

## 📝 Steps to Reproduce

1. Follow people who are using Misskey on Mastodon and their accounts are not protected;
2. After reinstalling a Mastodon instance, create an account using the same username and domain;
3. Try to follow them.

## 📌 Environment

Mastodon version: 4.1.2
Misskey version: 13.11.3
OS: macOS 12.6.3
Browser: FireFox 112.0.1

**Comment by yuowo39** [comment]
![follow request](https://foxbox.moe/yu/public-library/-/raw/main/cannot-follow-someone-using-misskey.png)

**Comment by tamaina** [comment]
When you say reinstall, do you mean you initialized the database?

Is it possible to follow back TO another Mastodon even if the Mastodon's database is initialized?

**Comment by yuowo39** [comment]
Yes, I mean that it is a new Mastodon instance.

I can follow people who are using Misskey and have never been followed before.

However, I cannot follow people who are using Misskey and have been followed before.

The reason I think is that I am using the same username and domain and tried to follow them again.

**Comment by yuowo39** [comment]
Update:

Also, I found that I cannot follow anyone on the servers, including someone I have never followed before.

**Now, I am not sure it is a bug about Misskey, Mastodon, or ActivityPub.**

**Comment by yuowo39** [comment]
Update 2:

I can follow someone who is using Mastodon.

**Comment by tamaina** [comment]
This is a known bug, and if you look for it, you will find several similar Issues.

Because of the way ActivityPub works, we recommend that you do not initialize the database, as such inconsistencies do occur.

**Comment by yuowo39** [comment]
OK.

I will try to solve it myself.

**Comment by yuowo39** [comment]
Turn the security level on Cloudflare to low; now, my instance has no problems connecting to misskey.io and misskey.cf.
