### ISSUE TITLE
メール送信テスト時に宛先が空でも送れてしまう

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10706]
## 💡 Summary
<img width="463" alt="スクリーンショット 2023-04-24 21 05 47" src="https://user-images.githubusercontent.com/18308639/233991194-da2008fd-8308-4a67-ac6e-93e4db610bc6.png">
↑これはプレースホルダ

- プレースホルダーが既に入力済みのように見える文字の濃さ
- 空欄でもOKが押せてしまう
- エラーメッセージは「Invalid Prams」　それはそうなんだけど…

## 🥰 Expected Behavior

- 宛先が空欄のときはOKが押せない
- プレースホルダに管理人のメールアドレスが採用されているが、 test@example.com などにするといいかも

## 🤬 Actual Behavior
- 宛先が空欄でもOKが押せるが絶対Invalid Params

## 📝 Steps to Reproduce

1. コントロールパネルを開く
2. メール
3. テスト送信

## 📌 Environment

Misskey version: 13
Your OS:Mac
Your browser: Chrome

備考）鯖缶互助会で二人ほどハマって沼ったのが確認されました

**Comment by ghost** [comment]
これプレースホルダーだったんですか！？毎回エラーになるからバグで送れないものだと思ってました……

**Comment by ghost** [comment]
修正してPR作成しました。
https://github.com/misskey-dev/misskey/pull/10719

**Comment by ghost** [comment]
こちら修正したPRマージされました。
