### ISSUE TITLE
使用できないユーザー名の設定がしたい

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#10704]
## Summary
＠admin や ＠root、＠system など、公式やシステムと誤解されそうなユーザー名、またその他取得してほしくないユーザー名で第三者がアカウントを取得するのを防ぐため、あらかじめ設定できるようにしたい。

判定方法は完全一致が望ましい。

**Comment by syuilo** [comment]
他にデフォルトで設定されているべきユーザー名募集中

**Comment by nexryai** [comment]
infoとかnotifyとかproxyとか

**Comment by syuilo** [comment]
`"admin", "administrator", "root", "system", "i", "me", "everyone", "all", "user", "account", "official", "help", "support", "misskey"`

**Comment by syuilo** [comment]
`"admin", "administrator", "root", "system", "i", "me", "everyone", "all", "user", "users", "account", "accounts", "official", "help", "helps", "support", "supports", "info", "information", "informations", "announce", "announces", "announcement", "announcements", "misskey"`

**Comment by na2204** [comment]
`"maintainer","host","mod","moderator","owner","master","superuser","notice","dev","developer","tech","auth","staff"`

**Comment by ghost** [comment]
弊サーバーで例えばeveryoneさん先に取られちゃったんですが、機能実装するとしたら新規登録時(未ログイン時のトップページでの新規登録/ログイン時の左下メニューから「アカウントを追加 > アカウントを作成」)のダイアログの判定でのみ使用できない形になる認識で大丈夫でしょうか。
<img width="169" alt="image" src="https://user-images.githubusercontent.com/23691696/234859565-509fa824-76b9-4cc2-a85a-e4f66fd5467e.png">

あと一般ユーザーは登録禁止にしたいんですが管理者は例えばadminというユーザーを作りたいケースがあると思うので、管理者ログイン時のコントロールパネルの「ユーザー > ユーザーを追加」には影響しないなどになりますでしょうか？
(一旦外して素早く登録でもそれほど問題ではないかもですが・・・）

**Comment by syuilo** [comment]
> 機能実装するとしたら新規登録時(未ログイン時のトップページでの新規登録/ログイン時の左下メニューから「アカウントを追加 > アカウントを作成」)のダイアログの判定でのみ使用できない形になる認識で大丈夫でしょうか。

はい

> あと一般ユーザーは登録禁止にしたいんですが管理者は例えばadminというユーザーを作りたいケースがあると思うので、管理者ログイン時のコントロールパネルの「ユーザー > ユーザーを追加」には影響しないなどになりますでしょうか？

はい

**Comment by syuilo** [comment]
`"admin", "administrator", "root", "system", "maintainer", "host", "mod", "moderator", "owner", "superuser", "staff", "auth", "i", "me", "everyone", "all", "mention", "mentions", "example", "user", "users", "account", "accounts", "official", "help", "helps", "support", "supports", "info", "information", "informations", "announce", "announces", "announcement", "announcements", "notice", "notification", "notifications", "dev", "developer", "developers", "tech", "misskey"`

**Comment by MineCake147E** [comment]
`ai` (藍)
`.*_official` (正規表現で`_official`とつくユーザー名を全て予約しておく)
とかどうでしょうか。

**Comment by syuilo** [comment]
nice to haveだわね

**Comment by ghost** [comment]
@syuilo 
> 予約するユーザー名を改行で列挙します。ここで指定されたユーザー名はアカウント作成時に使えなくなりますが、管理者によるアカウント作成自はこの制限を受けません。また、既に存在するアカウントも影響を受けません。

すみません誤字見つけました。`アカウント作成自` → `アカウント作成時`
