### ISSUE TITLE
Duplicate users in local user search

### ISSUE THREAD

**Issue by ssmucny** [syuilo/Misskey#10700]
## 💡 Summary

When searching for users in local instance, the the displayed user is repeated a lot.
![image](https://user-images.githubusercontent.com/17689855/233854934-b3aa9dc7-c8af-4a17-981b-09b13d6fd215.png)

## 🥰 Expected Behavior

Unique users should only appear once

## 🤬 Actual Behavior

User is repeated.

## 📝 Steps to Reproduce

1. Go to user search page at /search
2. search for a local user
3. view results

## 📌 Environment

Misskey version: 13.11.3
Your OS: Fedora Kinoite 38
Your browser: Firefox 111.0.1

**Comment by Morethanevil** [comment]
I second this. Tested it with my instance too

Same Misskeyversion (13.11.3) on Ubuntu 22.04 with Docker
![search](https://user-images.githubusercontent.com/110860055/233860311-8821c684-e411-47c5-8f4e-68a8964a8d2a.png)

**Comment by dakkar** [comment]
possibly relevant: the frontend runs a `POST /api/users/search` with payload `{i:…,limit:10,origin:"combined",query:…}`, then another one with payload `{i:…,limit:10,origin:"combined",query:…,untilId:…}`

The backend is not honoring the `untilId` (checked via the api console)

**Comment by twocs** [comment]
Seems to be duplicate issue #10432

**Comment by tassoman** [comment]
Looks like fixed in 2023.11.0 please give an eye.
Maybe this issue can be closed.

**Comment by zyoshoka** [comment]
Fixed by #11066
