### ISSUE TITLE
コンディショナルロールがリモートユーザーにも適用されている

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#10711]
## 💡 Summary

コンディショナルロールがリモートユーザー(の表示？)にも適用されている

<img width="545" alt="image" src="https://user-images.githubusercontent.com/23691696/234167118-9f8ad748-2a41-4194-9f04-728c507e3040.png">

![image](https://user-images.githubusercontent.com/23691696/234166903-5e261789-565f-4e47-981a-4bc7323063a1.png)

## 🥰 Expected Behavior

ロールはローカルユーザーのみにしか適用されない

## 🤬 Actual Behavior

ロールがリモートユーザーにも適用されている

## 📝 Steps to Reproduce

1.コンディショナルロールを作成する
2.ソーシャル/グローバルTL等で条件に該当するユーザーを選択する
3.コンディショナルロールが適用されている

## 📌 Environment

Misskey version: 13.11.3
Your OS: Windows 10
Your browser: Chrome

**Comment by usbharu** [comment]
コンディショナルロールの設定にリモートユーザー、ローカルユーザーの設定があるのでそれを使えばいいと思います。

**Comment by tar-bin** [comment]
あ、たしかにリモートユーザーの設定もありましたね。ローカルユーザー限定かと思ってました。
ただ複合条件って今できない？ので以下のような条件がリモートユーザーに適用されるのは変だなという印象が……
<img width="463" alt="image" src="https://user-images.githubusercontent.com/23691696/234169065-bbc6f584-c1cf-49ee-a27c-e361b5633d78.png">

**Comment by ghost** [comment]
ロールの複合条件できないと勘違いしてました、こちらはクローズします。
