### ISSUE TITLE
Separate cat ears and Nyaize

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#10713]
## Summary

I have observed people giving up their cat ears that they liked so much, because of Nyaize.
Since Nyaize has other problems, such as converting NAS (Network Access Storage) to "NYAS," I thought it would be better to separate cat ears and Nyaize.

**Comment by ThatOneCalculator** [comment]
This has already been implemented in https://codeberg.org/calckey/calckey/pulls/9798 if the devs want to reference/use our implementation :)

**Comment by acid-chicken** [comment]
Duplicate of #2556

**Comment by MineCake147E** [comment]
> Duplicate of https://github.com/misskey-dev/misskey/issues/2556

The shape of the icon has nothing to do with this issue. So it isn't an exact duplicate of #2556.  
It may be more like a https://github.com/misskey-dev/misskey/issues/6584 thing, but as a feature request to separate those two.

**Comment by tar-bin** [comment]
@MineCake147E 
It seems that it is a policy not to implement separate options for enabling / disabling cat ears and icon shapes
https://github.com/misskey-dev/misskey/issues/2556#issuecomment-419475497

**Comment by MineCake147E** [comment]
@tar-bin Again, **icon shapes has nothing to do with Nyaize**.
I am asking to implement separate options for enabling / disabling cat ears and NYAIZE, NOT ICON SHAPE.

**Comment by ghost** [comment]
(なんか読み間違いしたので前のコメントは削除しました)
たしかに猫耳にしたいけど"にゃ"にはしたくないって人がちらほら見かけるのでありかもです

**Comment by ghost** [comment]
@MineCake147E sorry i read it wrong.

**Comment by MineCake147E** [comment]
@tar-bin Don't worry, I noticed that you removed the previous comment after I posted the comment above.

**Comment by acid-chicken** [comment]
> The shape of the icon has nothing to do with this issue. So it isn't an exact duplicate of https://github.com/misskey-dev/misskey/issues/2556.

#2556 の Issue のタイトルが分かりづいらだけで

> - [ ] 猫耳のアイコンの有効化・無効化オプションの追加

と書いています

**Comment by MineCake147E** [comment]
> > The shape of the icon has nothing to do with this issue. So it isn't an exact duplicate of #2556.
> 
> #2556 の Issue のタイトルが分かりづいらだけで
> 
> > * [ ]  猫耳のアイコンの有効化・無効化オプションの追加
> 
> と書いています

https://github.com/misskey-dev/misskey/issues/2556#issuecomment-419475497
> このIssueの旨が「猫耳の有効化・無効化とアイコンの形のオプションを分けてほしい」というものなので、それに関しては実装しない方針なのでCloseしました。

とのことなので、https://github.com/misskey-dev/misskey/issues/2556 はNyaizeと分離してほしいという内容ではないというように感じていましたがいかがでしょうか。

**Comment by ghost** [comment]
個人的な意見ですが日本語は"にゃ"にしても全然読めるんですけど、英語圏だとスペルがかわるんでかなり可読性に難がでてるんじゃないかなぁというところはあります。分けない方針でも英語圏(en-US)はそもそも適用しないとかでもいいのかなと。
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/misc/nyaize.ts#L6

**Comment by acid-chicken** [comment]
> とのことなので、https://github.com/misskey-dev/misskey/issues/2556 はNyaizeと分離してほしいという内容ではないというように感じていましたがいかがでしょうか。

当該 Issue の後者については引用部が意思決定になっていて、前者の方（すなわちこの Issue と duplicate している内容）は https://github.com/misskey-dev/misskey/issues/2556#issuecomment-417803570 で意思の合意があったという認識

**Comment by ghost** [comment]
@MineCake147E オプション分離については消極的な感じなので、en-USのnyanificationを削除するリクエストでIssueを建てるとかいかがでしょうか？そっちのほうが受け入れられやすそう。

I feel passive about option separation, so how about creating an issue with a request to delete en-US nyanification? That seems more acceptable.

**Comment by MineCake147E** [comment]
> 当該 Issue の後者については引用部が意思決定になっていて、前者の方（すなわちこの Issue と duplicate している内容）は [#2556 (comment)](https://github.com/misskey-dev/misskey/issues/2556#issuecomment-417803570) で意思の合意があったという認識

#10713 の主目的は、現状Cat(`にゃああああああああああああああ！！！！！！！！！！！！`)という一つのオプションにまとめられた、アイコンの猫耳とNyaizeを分離することにあります。
#2556 ではそもそもNyaizeに対する言及はなく、Nyaizeがアイコンの猫耳と分離されることを良しとしないことの合意には見えないと判断していました。

> 個人的な意見ですが日本語は"にゃ"にしても全然読めるんですけど、英語圏だとスペルがかわるんでかなり可読性に難がでてるんじゃないかなぁというところはあります。分けない方針でも英語圏(en-US)はそもそも適用しないとかでもいいのかなと。 https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/misc/nyaize.ts#L6

国内のユーザーでも分けてほしいという意見は結構見受けられる他、真面目な投稿等Nyaizeしたくない理由も複数あるので、分けることが適切だと思います。

**Comment by ghost** [comment]
第三者が解釈バトルしてもというところありますので @syuilo さんのコメントを頂いたほうがいい気がしますね・・・。

**Comment by acid-chicken** [comment]
当時の合意を取りに行った私が第三者扱いなのは謎だけど今の話は Issue 本題とは関係ない話で脱線していっていてもう面倒なのでとりあえず取り消します

**Comment by acid-chicken** [comment]
なお isCat 機能の解釈としては #10492 あたりの話がまとまっていると思います

**Comment by fruitriin** [comment]
Nyizeは面白い機能だと思っているのを表明
(猫耳にしたらにゃいずされてしまうのも含めて)

**Comment by syuilo** [comment]
猫耳が生えるが言葉がnyaizeされてしまうという一長一短を味わってほしい
