### ISSUE TITLE
ワードミュートなど `String#includes` をリストで回す処理のパフォーマンスを改善する

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#10715]
## Summary

SSIA
パフォーマンスが悪い可能性があるので RE2 含めて要調査

Spidermonkey
--

![image](https://user-images.githubusercontent.com/20679825/234263074-02bda40f-fa91-4849-9ba8-c46fce66b80e.png)

V8
--

![image](https://user-images.githubusercontent.com/20679825/234263856-8135c1e8-4dc5-424d-9843-14d8e1811ac8.png)

**Comment by yuriha-chan** [comment]
リストの最初が「a」だからsomeが即trueを返してしまいリストで回すのが速く見える罠
RegExpをビルドするところまでsetupで実行すれば(=キャッシュしておけば)RegExpが速い(V8)
![image](https://user-images.githubusercontent.com/121590760/234429863-f1964bf9-be13-4076-9513-e16831c720a9.png)
そうでなければあんまり変わらない？（リストの大きさや判定対象文字列長で変わってくると思う）
![image](https://user-images.githubusercontent.com/121590760/234432554-2831f0df-4de1-4fab-b611-32fde4a28211.png)

**Comment by acid-chicken** [comment]
Aho-Corasick algorithm が良さそう https://github.com/misskey-dev/slacc
![image](https://user-images.githubusercontent.com/20679825/234468222-ccb86963-2b7b-4328-941b-5ca423b9b112.png)
