### ISSUE TITLE
フォローリクエストを承認した後も通知欄で許可/拒否ボタンが出続ける

### ISSUE THREAD

**Issue by GrapeApple0** [syuilo/Misskey#10722]
## 💡 Summary
フォローリクエストを承認した後でも通知欄では許可/拒否ボタンが出続けています。

## 🥰 Expected Behavior
承認/拒否後にボタンが出ない

## 🤬 Actual Behavior
承認/拒否後でもボタンが出る

## 📝 Steps to Reproduce

1. フォローリクエストを承認する
2. リロードする
3. 通知欄を見る

## 📌 Environment
Misskey version: v13.11.3
Your OS: Windows 10
Your browser: Vivaldi

**Comment by futchitwo** [comment]
- duplicate of #10611
