### ISSUE TITLE
"Note search is unavailable"

### ISSUE THREAD

**Issue by genewitch** [syuilo/Misskey#10727]
## 💡 Summary

Search button on left menu opens a page that says "Note search is unavailable."

## 🥰 Expected Behavior

A search box should appear.

## 🤬 Actual Behavior

"User" search tab works on that page, but i cannot search hashtags or notes

## 📝 Steps to Reproduce

1. fully update ubuntu
2. run update.sh
3. reboot

## 📌 Environment

misskey is the only service on the dedicated machine, 16GB ram VM, 600GB storage, 4 CPU, gigabit.

Misskey version: 13.11.3
Your OS: ubuntu 20.04.6
Your browser: firefox 112.0.1

**Comment by CyberRex0** [comment]
Duplicate of #10399

**Comment by genewitch** [comment]
> Duplicate of #10399

Sorry about that. I asked a question in #10399 regarding why it's disabled
