### ISSUE TITLE
Account Moveのテスト落ちてる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#10738]

**Comment by syuilo** [comment]
revertしたいけどなんか上手くできない

**Comment by tamaina** [comment]
どうして落ちるようになったんだろう

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/235631260-a9da1268-9a5a-49de-860e-e00b9424eafc.png)

原因これ…？

**Comment by tamaina** [comment]
違うな（たまたまmute expired checkが入っただけだけどそれが落ちるのも微妙だ）

**Comment by tamaina** [comment]
データベースが吹っ飛んでるようにも見えるけどなぜそうなるのかわからない

（Local to LocalのbeforeAllでもう一度初期化をかけてもエラーが出る…）

**Comment by tamaina** [comment]
わかったusername制限のせいでrootユーザーが取れないんだ

**Comment by tamaina** [comment]
初回ユーザー登録時にはpreservedUsernamesを無視するようにした

**Comment by yuriha-chan** [comment]
また落ちてる、原因はこれ

https://github.com/misskey-dev/misskey/commit/f3e43a0fc63d9beee74dfd1f29679ff95ef1e130#r111483902

**Comment by tamaina** [comment]
修正しました:pray:
