### ISSUE TITLE
Mysterious tab stop in reaction picker and custom emoji picker

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#10744]
## 💡 Summary

In reaction picker, after I pressed Tab key in the search box, this happens.
![image](https://user-images.githubusercontent.com/31585494/235581340-765a038a-0e2f-42ec-a3c7-e68da6ed4a48.png)
In custom emoji picker, after I pressed Tab key in the search box, this happens.
![image](https://user-images.githubusercontent.com/31585494/235579629-6139b453-3b6f-4346-babd-3360659185af.png)

## 🥰 Expected Behavior

Such a green bar should not be selected.

## 🤬 Actual Behavior

Such a green bar appears.

## 📝 Steps to Reproduce

1. Open any instance's web client on browser.
2. Open the new note dialog.
3. Open the custom emoji picker.
4. Select the search box.
5. Press the Tab key in your keyboard.
6. See what happens. This appears no matter whether you typed anything in the search box or not, just at different places.

## 📌 Environment

Misskey version: 13.11.3
Your OS: Windows 10 Home 22H2 19045.2846
Your browser: Mozilla Firefox 112.0.2

**Comment by mappi-pr** [comment]
Misskey v13.11.3、firefox 112.0.2 で再現しました。
Firefoxの仕様で、overflow: auto;が適用されている要素にtabでフォーカスが当たるようになっているようです。

.emojis に当たっている、overflow-yをhiddenにすることで事象が発生しなくなることを確認しております。
~~/misskey/packages/frontend/src/components/MkEmojiPicker.vue(L.529)のfixで解消するかもしれないです。~~
→overflow-yをhiddenにすると、カスタム絵文字エリアをスクロールできなくなるのでこの方法は不可でした。

![image](https://user-images.githubusercontent.com/75538777/235609634-8970307b-b57b-46e5-a640-acf374f9a016.png)

**Comment by mappi-pr** [comment]
もしかしたらFirefoxのBugかもしれないので、放置が正解かもしれないです…
https://bugzilla.mozilla.org/show_bug.cgi?id=1795509

**Comment by MineCake147E** [comment]
最終更新が三ヶ月も前ですが本当に修正入るんでしょうか...

**Comment by mappi-pr** [comment]
https://github.com/misskey-dev/misskey/issues/10744#issuecomment-1531044495
コメントのUPDATEの通り、
overflow-yをhiddenにすると、カスタム絵文字エリアをスクロールできなくなる
ので、この方法はfixとしては不可でした。

cssはそのままに、tabindex="-1"とすることでフォーカスが当たらなくなることは確認しております。
![image](https://user-images.githubusercontent.com/75538777/236785639-5f4fbf42-6ed4-4007-9b38-0b0e32edd796.png)

ただし、Chromeなどのブラウザで動作検証した際に、カスタム絵文字ピッカーのスクロール動作時に再描画されない事象も発生するので、既知の事象かどうか追加検証が必要な状況です。
<img width="271" alt="image" src="https://user-images.githubusercontent.com/75538777/236786098-2b41197e-0274-479b-81c6-901f5bdcdfc1.png">

**Comment by mappi-pr** [comment]
> ただし、Chromeなどのブラウザで動作検証した際に、カスタム絵文字ピッカーのスクロール動作時に再描画されない事象も発生するので、既知の事象かどうか追加検証が必要な状況です。

修正前後の環境で改めて比較してみましたが、私の手元環境の問題のようなのでPR作成してみます。
