### ISSUE TITLE
Twitchのプレイヤーをiframe埋め込みで開けない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10759]
summaly関連？

**Comment by tamaina** [comment]
```
{
	"title": "magronachan",
	"icon": "https://p1.a9z.dev/proxy/preview.webp?url=https%3A%2F%2Fstatic.twitchcdn.net%2Fassets%2Ffavicon-32-e29e246c157142c94346.png&preview=1",
	"description": "余",
	"thumbnail": "https://p1.a9z.dev/proxy/preview.webp?url=https%3A%2F%2Fstatic-cdn.jtvnw.net%2Fjtv_user_pictures%2F2ff09c5a-d673-4260-9723-a74b389a8859-profile_image-300x300.png&preview=1",
	"player": {
		"url": "https://player.twitch.tv/?channel=magronachan&player=facebook&autoplay=true&parent=meta.tag",
		"width": 620,
		"height": 378,
		"allow": [
			"autoplay",
			"encrypted-media",
			"fullscreen"
		]
	},
	"sitename": "Twitch",
	"sensitive": false,
	"url": "https://www.twitch.tv/magronachan"
}
```

↓

![image](https://user-images.githubusercontent.com/7973572/236274887-0e676e4e-2f0f-45e3-8eaf-18647d947744.png)

**Comment by tamaina** [comment]
https://support.mozilla.org/ja/kb/xframe-neterror-page?as=u&utm_source=inproduct

X-Frame-OptionsかCSPが悪いらしい

**Comment by tamaina** [comment]
今試したらplayerが消えてた

**Comment by mei23** [comment]
Twitchがフレーム埋め込みをいわゆる許可リスト制にしちゃってるからかも
```
Content-Security-Policy: 
frame-ancestors
https://reddit.com
https://www.reddit.com
https://old.reddit.com
https://new.reddit.com
https://www.redditmedia.com
https://twitter.com
https://cards-frame.twitter.com
https://tweetdeck.twitter.com
https://discordapp.com
https://discord.com
https://embedly.com
https://cdn.embedly.com
https://facebook.com
https://www.facebook.com
https://vk.com
```

微妙に日本ではマイナーなSNSも入ってるから、みんなでリクエストすれば追加してくれるのかしら…

**Comment by acid-chicken** [comment]
> 微妙に日本ではマイナーなSNSも入ってるから、みんなでリクエストすれば追加してくれるのかしら…

オリジンが別だから回避用の共通オリジンを持つとかしないと無理そう

**Comment by mei23** [comment]
https://dev.twitch.tv/docs/embed/video-and-clips/
埋め込みURLを `parent=example.com` みたいにしたらCSPに入れてもらえた
`Content-Security-Policy: frame-ancestors https://example.com`

なお、ogの生成だと`parent=meta.tag`というダミーっぽいのが設定されてて出てこない。

**Comment by acid-chicken** [comment]
なら summaly のプラグインとして追加すれば良さそう

**Comment by mei23** [comment]
summalyの応答はインスタンス間で共用されることがあるからそこに入れたくないかも。
Misskeyがsummalyの応答受け取ってPlayer呼ぶときに書き換えたほうがいいかも。

**Comment by acid-chicken** [comment]
あー

**Comment by acid-chicken** [comment]
> 今試したらplayerが消えてた

あとこれは単純に Twitch のバグくさい

**Comment by mei23** [comment]
> Misskeyがsummalyの応答受け取ってPlayer呼ぶときに書き換えたほうがいいかも。

それぞれのMisskeyサーバーがクライアントに返すタイミング
つまり Misskey backend の /url endportで書き換えるのが良さそう

**Comment by tamaina** [comment]
summaly proxy廃止しようぜというのがよぎった

**Comment by acid-chicken** [comment]
> summaly proxy廃止しようぜというのがよぎった

ターゲットウェブサイトのスパイクは軽視すべきではない
