### ISSUE TITLE
「URLから」の画像アップロードが機能しない

### ISSUE THREAD

**Issue by Zel9278** [syuilo/Misskey#10756]
## 💡 Summary

画像のアップロード時に「URLから」を選択し、画像へのリンクをアップロードしても何も起こりません
（V12インスタンスでは正常に動作します）

## 🥰 Expected Behavior

正常に画像のアップロードができる

## 🤬 Actual Behavior

![chrome_vW0KisVe0e](https://user-images.githubusercontent.com/43949163/236127719-f53d5eee-f9f0-4111-906e-6aefedbf59cf.png)
DevToolsでは、エラーは一切ないです。
![WindowsTerminal_XD5PLOe4VJ](https://user-images.githubusercontent.com/43949163/236128714-1eebba9a-9547-49ac-8d90-5776e6a2408c.png)
サーバー側でもこの表示以外には何も出てこないです。

## 📝 Steps to Reproduce

1. ノート投稿画面で画像をアップロードするドロップダウンで「URLから」を選択する
2. URLを入力して「OK」を押す
3. アップロードがされない

## 📌 Environment

使用したURL: 
- https://files.eov2.com/2j1g.png (出来ない)
- https://files.misskey.art//238347fd-56b5-4c14-a1ff-23a0a3015289.png (出来る)

Misskey version: 13.10.3(misskey.art), 13.11.3(misskey.io / m.c30.life)
Your OS: Windows 10 (19045.2846)
Your browser: 112.0.5615.139（Official Build） （64 ビット）

**Comment by chocolate-pie** [comment]
自分の場合、ちゃんと動作しました
<img width="1127" alt="スクリーンショット 2023-05-04 17 21 15" src="https://user-images.githubusercontent.com/106949016/236149313-231ffca9-1ea8-4755-9cc1-4e834331d500.png">

**Comment by Zel9278** [comment]
> 自分の場合、ちゃんと動作しました <img alt="スクリーンショット 2023-05-04 17 21 15" width="1127" src="https://user-images.githubusercontent.com/106949016/236149313-231ffca9-1ea8-4755-9cc1-4e834331d500.png">

オブジェクトストレージって使ってますか？

**Comment by chocolate-pie** [comment]
> > 自分の場合、ちゃんと動作しました <img alt="スクリーンショット 2023-05-04 17 21 15" width="1127" src="https://user-images.githubusercontent.com/106949016/236149313-231ffca9-1ea8-4755-9cc1-4e834331d500.png">
> 
> オブジェクトストレージって使ってますか？

特に使ってないですね...それを使って起きるバグなのかも

**Comment by CyberRex0** [comment]
オブジェクトストレージは何を使ってますか?

**Comment by Zel9278** [comment]
Cloudflare R2です
（オブジェクトストレージを切ってアップロードも出来ませんでした）

**Comment by Zel9278** [comment]
> オブジェクトストレージは何を使ってますか?

Cloudflare R2です
（オブジェクトストレージを切ってアップロードも出来ませんでした）

**Comment by CyberRex0** [comment]
Cloudflare R2には「リージョン」の概念がないので、今までは未入力にしていても問題なかったのですが
ここ最近のMisskeyのバージョンでは依存しているライブラリの影響で入力が必要になっています
適当にus-east-1などと入れていれば使えます

**Comment by Zel9278** [comment]
> Cloudflare R2には「リージョン」の概念がないので未入力に今までしていても問題なかったのですが ここ最近のMisskeyのバージョンでは依存しているライブラリの影響で入力が必要になっています 適当にus-east-1などと入れていれば使えます

ちゃんとリージョンは指定しています（指定していないと画像投稿自体ができなかったので）

**Comment by Zel9278** [comment]
> > オブジェクトストレージは何を使ってますか?
> 
> Cloudflare R2です （オブジェクトストレージを切ってアップロードも出来ませんでした）

すみません、ちょっと情報不足のまま返信してしまいました
misskey.artはIDrive e2です
m.c30.lifeはCloudflare R2です

**Comment by CyberRex0** [comment]
問題が発生しているのはどちら？

**Comment by Zel9278** [comment]
> 問題が発生しているのはどちら？

どちらもです
misskey.io
misskey.art
m.c30.life
（すべて13.x系統です）
で試しましたがすべてURLからアップロードが出来ませんでした
V12のサーバーではアップロードが出来ました。（kokuzei.cyouで試しました。）

**Comment by CyberRex0** [comment]
https://cyberrex.jp/image-format-test/images/test.jpeg
この画像を使用しましたが問題なくURLアップロードできました。

**Comment by Zel9278** [comment]
> https://cyberrex.jp/image-format-test/images/test.jpeg この画像を使用しましたが問題なくURLアップロードできました。

この画像はmisskey.art, m.c30.lifeでもアップロードできました

**Comment by Zel9278** [comment]
![UA1HX2WDD5](https://user-images.githubusercontent.com/43949163/236160380-4341ea86-a661-487e-ab55-bcc564349d21.png)
ファイルサーバー側でもログを見たのですが正常に動いてそうなんですよね...

**Comment by Zel9278** [comment]
すみません、ファイルサーバーのヘッダー不足のせいでした。
解決しました。
