### ISSUE TITLE
[question] MiAuthの認証後にそのアプリ内ブラウザ内で他の操作をさせたくない

### ISSUE THREAD

**Issue by taka84makiba** [syuilo/Misskey#10770]
## Summary

MisskeyAPIを使用してiOSモバイルアプリを開発しております。

現在、MiAuthを使用して認証を行っているのですが、認証後にユーザーがブラウザ内でMisskeyを利用できてしまうことが問題となっております。

<img src="https://user-images.githubusercontent.com/50735539/236497116-749f6f62-81e7-404a-adff-6d50cbb1e5c5.png" width="800">

本来の目的である認証のためにブラウザにアクセスする必要があるため、認証後にブラウザ内で本来行うべきでない操作ができてしまうことは好ましくないと考えております。

この問題を解決する方法として、ユーザーが不要な裁量を持たずに認証を行うことができる方法があるのか、ご教示いただければ幸いです。

---

本題とは多少ズレますが、モバイルアプリにとって、上記の仕様は少し都合の悪いものとなっています。
リリースしているアプリをアップデートする際に以下の理由でAppleの審査がRejectとなりました。

- Noteの投稿の際にカメラを開こうとするとクラッシュしてしまう。
    -  アプリ内のブラウザに対して、カメラへのアクセス権限を付与することは少し難しい気がしています。。。
<img src="https://user-images.githubusercontent.com/50735539/236493758-3d0a6185-46f9-4b17-b2ac-c483d5221590.png" width="400">

- サービスへの寄付をアプリを介してではなくブラウザから行えてしまう
   - iOSアプリは基本的にコンテンツ購入や寄付などの課金機能をアプリ内で行われなければいけない仕様となっています。 

お手数をおかけし申し訳ありません。以上が今回のissue内容となります。今後のMisskeyの品質向上に役立てていただけると幸いです。

**Comment by tamaina** [comment]
クエリ文字列に`zen`を加えてアクセスすると解決しないでしょうか。

**Comment by taka84makiba** [comment]
ありがとうございます :bow:
アドバイスの通り`https://{host}/miauth/{uuid}?zen=`で解決することができました。

<img src="https://user-images.githubusercontent.com/50735539/236509043-dc2c6269-7068-4296-b664-79bfc215e236.png" width="400">

迅速に対応していただきありがとうございます 😄
