### ISSUE TITLE
[13.12.0-beta.2] Meilisearchの検索結果の時系列がバラバラになる

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#10776]
## 💡 Summary

Meilisearchを有効化した状態で検索すると、検索結果の時系列がバラバラになることがある。

## 🥰 Expected Behavior

投稿時間の時系列順になる(新しい投稿から古い投稿の順番がこれまでと同じ挙動でしょうか。。)

## 🤬 Actual Behavior

時系列順にならない

## 📝 Steps to Reproduce

1.  Meilisearchを有効化する
2. 検索する
3.

## 📌 Environment

Misskey version: 13.12.0-beta2
Your OS: macOS 13 (最新版)
Your browser: Safari (最新版)

**Comment by syuilo** [comment]
謎

**Comment by nakkaa** [comment]
迅速に対応していただきありがとうございました。
