### ISSUE TITLE
MkImgWithBlurhashのBlurhash描画の最適化

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10781]
## Summary
M1 iPad ProでMisskeyを使っていると、ノートの画像表示時に特にフリーズしており、Blurhashの描画が悪いのではないかと疑っている

Blurhash描画をWorker(OffscreenCanvas)で行うなどすればパフォーマンスが改善しそうだと思った

**Comment by tamaina** [comment]
（あとblurhash decode自体も最適化できるようなことを @acid-chicken が言ってた）

**Comment by acid-chicken** [comment]
> （あとblurhash decode自体も最適化できるようなことを @acid-chicken が言ってた）

同期的に CanvasRenderingContext2D で描いてるしパフォーマンスの問題があるのはほぼ明白

**Comment by acid-chicken** [comment]
WebGPU で書こうかなと思ってたんだけど一回 [blurhash-to-css](https://www.npmjs.com/package/blurhash-to-css) 試してみようぜ

**Comment by tamaina** [comment]
誰が実装する？

**Comment by tamaina** [comment]
やるか

**Comment by tamaina** [comment]
https://github.com/JamieMason/blurhash-to-css/blob/a92f6fc20f53fab596bc4d4491e135ec92664596/package.json#L45

なんで？

**Comment by tamaina** [comment]
Next.js用に作られてるっぽい？

**Comment by syuilo** [comment]
CSSのブラーフィルタ使うみたいだけど、それはそれで重そう

**Comment by tamaina** [comment]
わかる〜

**Comment by tamaina** [comment]
でも https://blurhash-to-css.vercel.app/ を見た感じ爆速

**Comment by tamaina** [comment]
> なんで？

今「めんどくせぇな〜」で手を止めているところ

**Comment by tamaina** [comment]
とりあえず現状の処理をWorkerに逃す

**Comment by acid-chicken** [comment]
![image](https://user-images.githubusercontent.com/20679825/236660404-5c8c31e5-432a-4375-a78a-ec7867489321.png)

速くなったけどブラーが汚くなったので調整中

**Comment by syuilo** [comment]
blurhash自体オフにするオプションあってもよさそう

**Comment by tamaina** [comment]
ThumbHashなるものがあるらしい

**Comment by acid-chicken** [comment]
良さそうだけどマイグレーションしなきゃだしアルゴリズム変更はちょっと乗り気ではない

**Comment by tamaina** [comment]
> マイグレーション

クライアントに後方互換性持たせれば良いと思ってた

> アルゴリズム変更はちょっと乗り気ではない

なぜ

**Comment by acid-chicken** [comment]
複数アルゴリズムが共存するのはもっと嫌

**Comment by acid-chicken** [comment]
そこまでして得られるメリットが乏しい

**Comment by syuilo** [comment]
ThumbHash見た感じBlurhashよりもアーティスティックさがない

**Comment by syuilo** [comment]
再現性を重視するか見た目を重視するか

**Comment by acid-chicken** [comment]
> ![image](https://user-images.githubusercontent.com/20679825/236660404-5c8c31e5-432a-4375-a78a-ec7867489321.png)
> 
> 速くなったけどブラーが汚くなったので調整中

とりあえずこの時点のやつ（w/WebGL2）を https://github.com/misskey-dev/buraha に投げた

**Comment by tamaina** [comment]
ThumbHashはいいや

（ところでSafariのOffscreenCanvasがWebGL対応してないとかいうのを聞いたことがある）

**Comment by acid-chicken** [comment]
いい感じになったくね
![](https://user-images.githubusercontent.com/20679825/236683512-388cf1a7-6d25-4373-ba0f-b0c3c27d5984.png)

**Comment by tamaina** [comment]
メインスレッドでいいか

**Comment by tamaina** [comment]
https://ics.media/entry/19043/#offscreencanvas%E3%81%AE%E5%AF%BE%E8%B1%A1%E7%92%B0%E5%A2%83

![image](https://user-images.githubusercontent.com/7973572/236684389-4c370683-d5a1-4a29-8806-e9f6bbec5492.png)

これ本当？

**Comment by u1-liquid** [comment]
んー its Safari....

**Comment by acid-chicken** [comment]
まぁ Web Worker 側でコンテキストが取れなかったらメインスレッドにフォールバックするのがまるそう

**Comment by tamaina** [comment]
>  In Safari 16.4 we’ve added Offscreen Canvas support for 2D operations. Support for 3D in Offscreen Canvas is in development.
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/

なるほど

**Comment by acid-chicken** [comment]
@tamaina https://github.com/misskey-dev/buraha の取り込みお任せしてしまって良い？

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/236685680-c0527e21-2a1f-495c-be38-f725e23418c0.png)

↓

![image](https://user-images.githubusercontent.com/7973572/236685657-f66dd1b7-e1e1-4d53-895d-375434cd7934.png)

**Comment by tamaina** [comment]
Safari Technology Preview Release 169 (Safari 16.4, WebKit 18616.1.12.2)でも非対応だった

**Comment by tamaina** [comment]
npm公開してないんか()

**Comment by acid-chicken** [comment]
browser-image-resizer とかで直接参照してるっぽかったからその方が都合いいのかと思ったけどそうでもないなら公開する

**Comment by tamaina** [comment]
直接参照でいいかと思ってるけどちょっと調整中

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/236689130-b6f79214-0eb8-47cb-ad28-84f4c76f2f34.png)

はい

**Comment by tamaina** [comment]
mountごとにworker生やしたらいけた

**Comment by tamaina** [comment]
Warn; `WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.` と言われる

**Comment by acid-chicken** [comment]
> Warn; `WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.` と言われる

fixed @ https://github.com/misskey-dev/buraha/commit/340d8bd748aefa57a3cd0bf0e4b48947b97d4c5c

**Comment by acid-chicken** [comment]
ん？ ![](https://user-images.githubusercontent.com/20679825/237027563-654e2555-7fe0-4255-8627-3f93b08c6d16.jpeg)

**Comment by acid-chicken** [comment]
↑レンダリングは失敗してるけど Web Worker に分離できていることでもっさり感が解消している気がする
