### ISSUE TITLE
[13.12.0-beta.5] Cannot read properties of undefined (reading '0')  at FederatedInstanceService.update 

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10787]
## 💡 Summary
May 07 10:13:57 MisskeySystems misskey[7704]: TypeError: Cannot read properties of undefined (reading '0')
May 07 10:13:57 MisskeySystems misskey[7704]:     at FederatedInstanceService.update (file:///root/misskey/packages/backend/built/core/FederatedInstanceService.js:62:35)
May 07 10:13:57 MisskeySystems misskey[7704]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

これによって何が起きているのかは調べてない
13.11の不正データかも

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/f94f3dae8bbd7d65607904103988c79d4814896d/packages/backend/src/core/FederatedInstanceService.ts#L53-L57


ここら辺？

**Comment by fruitriin** [comment]
https://github.com/misskey-dev/misskey/blob/f94f3dae8bbd7d65607904103988c79d4814896d/packages/backend/src/core/FederatedInstanceService.ts#L75

ここのthen でreturn response.raw[0] したものが　await の戻りのresultになって、　result.raw[0] から値とってるけどこれあってるかな？
斜め読みだから自信はない

**Comment by sasagar** [comment]
same hereです。
一応13.10.3からのアップデートで発生。

**Comment by syuilo** [comment]
謎

**Comment by nexryai** [comment]
同様の問題が発生しました。ログをリアルタイムでみてると少なくとも5秒に1回は発生しててヤバそう
![image](https://user-images.githubusercontent.com/61890205/236993337-50c1b2aa-8bc7-49ef-97fc-e0a742ed70ec.png)
![image](https://user-images.githubusercontent.com/61890205/236994458-505ba278-704d-4083-b752-8e29152ec78b.png)

**Comment by syuilo** [comment]
あーローカルでも再現

**Comment by syuilo** [comment]
tasukete

**Comment by ryanho** [comment]
After upgraded my instance I got the same error message. Using 13.12.0 docker image.

`TypeError: Cannot read properties of undefined (reading '0')
    at FederatedInstanceService.update (file:///misskey/packages/backend/built/core/FederatedInstanceService.js:62:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by syuilo** [comment]
うーむ問題ないはずなんだけど
https://stackoverflow.com/a/64116762

**Comment by syuilo** [comment]
あー

**Comment by fruitriin** [comment]
:igyo:
