### ISSUE TITLE
Vulnerability: Misskeyの設定に関わらずURLプレビューがプライベートアドレスでも行われる

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10786]
## 💡 Summary
allowedPrivateNetworksを一度設定した後、コメントアウトしても反映されない

## 🥰 Expected Behavior
allowedPrivateNetworksを設定したことがあってもコメントアウトすれば全てのIPは許可されない

## 🤬 Actual Behavior
allowedPrivateNetworksを一度設定した後コメントアウトしても引き続き該当IPが許可される

## 📝 Steps to Reproduce

1. allowedPrivateNetworksを設定して起動
2. コメントアウトして再起動
3. ログにブロックされた趣旨のメッセージは出ない + プレビューされる（キャッシュ消去などは試したけど効果なし）
4.

## 📌 Environment

Misskey version: v13.11.3
PostgreSQL version: 15
Redis version: 7.0
Your OS: Ubuntu22.04 Docker `netowork_mode=host`
Your browser: Firefox112

**Comment by nexryai** [comment]
ログ側に残ってたのでやはりブロックされていない感じで間違いないです
![image](https://user-images.githubusercontent.com/61890205/236670409-a4c6bc76-3ec4-4f59-84a9-b748831499dd.png)

**Comment by nexryai** [comment]
これなんか触ってるうちに何入れてもプライベートIP許可されるようになってしまいました...（Dockerのコンテナ再生成しても同じ）
`curl http://127.0.0.1:3000/url?url=http://127.0.0.1:3000`で対象マシンから直接調べたのでキャッシュとかではない

**Comment by u1-liquid** [comment]
念のため確認したいですが、development 環境で動いてませんか？

https://github.com/misskey-dev/misskey/blob/d526cd70fd8f9a20c5cb29cd536362e107143253/packages/backend/src/core/DownloadService.ts#L71-L76

**Comment by nexryai** [comment]
Dockerのデフォルトテンプレートベースで動かしているので確実に本番環境です
![image](https://user-images.githubusercontent.com/61890205/236672969-2ac2e6e4-589a-4f68-a108-974850cc8509.png)

**Comment by mei23** [comment]
そもそも https://github.com/misskey-dev/misskey/pull/9905 以降、URLプレビューには常にプライベートアドレス除外が効かなくなってそう。

https://github.com/misskey-dev/summaly/blob/709ca51b6ca289aecadc3e642447487b52c9d7d9/src/utils/got.ts#L46
```ts
const allowPrivateIp = process.env.SUMMALY_ALLOW_PRIVATE_IP === 'true' || Object.keys(agent).length > 0;
```

https://github.com/misskey-dev/misskey/blob/d526cd70fd8f9a20c5cb29cd536362e107143253/packages/backend/src/server/web/UrlPreviewService.ts#L73-L76

**Comment by nexryai** [comment]
それが原因で間違いないようです。`/proxy/`で試したらちゃんとブロックされました

![image](https://user-images.githubusercontent.com/61890205/236674308-155322e9-7ab6-45df-97d7-c5218eb57964.png)

**Comment by nexryai** [comment]
Cockpitとかの管理コンソールのポートとか調べ放題になるのでセキュリティ上の懸念があるのは確かかも（現に私のサーバーでもその趣旨の報告を受けた）
Summaly Proxyを外部サーバーのにすれば回避できそうです

**Comment by mei23** [comment]
URLプレビューはMisskey本体のDownloadServiceを使わないので/proxy/などは関係ないはずだわ

**Comment by mei23** [comment]
URLプレビューは`allowedPrivateNetworks`には従わない仕様。
URLプレビューはプライベートアドレスを除外し、環境変数`SUMMALY_ALLOW_PRIVATE_IP=true`でのみ迂回できる仕様。
↓
しかし実際には、URLプレビューはプライベートアドレスを常に許可してしまう。
