### ISSUE TITLE
ユーザー選択ダイアログが表示されない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#10809]
## 💡 Summary

ユーザー選択ダイアログが表示されない

## 🥰 Expected Behavior

ダイアログが正しく表示される

## 🤬 Actual Behavior

タイトルバーだけ表示される
![Screenshot_20230509-120622~2](https://user-images.githubusercontent.com/26585194/236983933-f6011d84-323f-4f3b-a764-b8d103c5c2bd.png)

## 📝 Steps to Reproduce

メンション追加やロールアサインでユーザー選択ダイアログを出す

## 📌 Environment

Misskey version: 13.12.0
PostgreSQL version: 15
Redis version:
Your OS: macOS Monterey
Your browser: Chrome 112

**Comment by fruitriin** [comment]
same here〜

**Comment by tamaina** [comment]
何もいじってないのにMkUserSelectDialogが壊れた？

**Comment by syuilo** [comment]
MkModalWindowのbodyのcontainer-typeをinline-sizeからsizeにしたのが原因と思われる
そこは変えたくないからMkUserSelectDialogで高さを明示するようにすれば良さそう
