### ISSUE TITLE
センシティブ設定された画像を開くとき一瞬レイアウトが崩れる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10801]
## 💡 Summary

https://user-images.githubusercontent.com/4439005/236783611-7de6a861-8b55-48f9-88cf-7525f302bec7.mp4

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: 13.12.0-beta.5
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
これ以降発生してるっぽい
https://github.com/misskey-dev/misskey/commit/15761a0fa8f65bc8663cc5bbeaacde7ca5760e21

**Comment by syuilo** [comment]
いったん無効化する

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/pull/10782 で直した
