### ISSUE TITLE
AI学習用データセットからの除外宣言（noai, noimageai） / Declaration of exclusion from AI datasets

### ISSUE THREAD

**Issue by Nanashia** [syuilo/Misskey#10819]
## Summary

DeviantArtという英語圏のイラスト・CG・小説投稿サイトが、投稿データをAIの学習データセットに含めないように宣言するmetaタグとHTTPヘッダを提唱しています。

https://www.deviantart.com/team/journal/UPDATE-All-Deviations-Are-Opted-Out-of-AI-Datasets-934500371
![image](https://github.com/misskey-dev/misskey/assets/1283235/b2fe99b5-04b2-4ec1-821a-ca3e824b0fd3)
![image](https://github.com/misskey-dev/misskey/assets/1283235/44e68553-5edd-495a-a20a-eb34787c689d)

> For Developers: Implementing noai or noimageai
> 
> Developers can implement these directives in two ways.
> Meta Tag
> `<meta name="robots" content="noimageai">`
> and/or
> `<meta name="robots" content="noai">`
> 
> HTTP Response Header
> `X-Robots-Tag: noimageai`
> and/or
> `X-Robots-Tag: noai`
> 

クローラー拒否（noindex）と似た感じの記法で、ユーザーごと or ファイルごと or 投稿ごとに設定できるようになって欲しいです。

この記法はあまり流行っているとはいい難いですし、noindex同様にクローラーへの強制力はありませんが、
文章・静止画・動画・音楽問わず、生成AIに対する関心が高まっているのでこういった選択肢を用意することはMisskeyで活躍するアーティストさんたちの応援になると考えます。

**Comment by nexryai** [comment]
もしやるならnoindexとは違って、あくまでもこれはまだ提唱段階にあるということを明示した方がいいと思う。

**Comment by syuilo** [comment]
やるか

**Comment by syuilo** [comment]
HTTP Response Headerがちょっと面倒そう

**Comment by syuilo** [comment]
そうでもないか

**Comment by syuilo** [comment]
HTTP Response Header忘れてた

**Comment by Nanashia** [comment]
早速の実装どうもありがとうございます！ 🙏🙏🙏🙏 

少し文言について、利用者が誤解してしまう可能性があるのでコメントさせてください。
https://github.com/misskey-dev/misskey/blob/ae5a72a2dfdb31806e7ccccb3d053c60a13b549f/locales/ja-JP.yml#L1041-L1042
このプロトコルは、あくまで学習を望まないという意思を表明するものであって、AIの学習を完全に「防止」するものではありません。画像に加工を施して学習を妨害する、みたいな機能と誤解されるととてもマズいです。

そのうえで、下記のような感じがよいかも、と思いますがいかがでしょうか。
cc @nexryai 

- `"AIによる学習を望まない"`
- `"投稿したノート、添付した画像などのコンテンツを学習の対象にしないようAIに要求します。これはnoaiフラグをHTMLレスポンスに含めることによって実現されます。この機能は実験的であり、AIによる学習を完全に防止するものではありません"`

**Comment by nexryai** [comment]
> "投稿したノート、添付した画像などのコンテンツを学習の対象にしないようAIに要求します。これはnoaiフラグをHTMLレスポンスに含めることによって実現されます。この機能は実験的であり、AIによる学習を完全に防止するものではありません"

この文言はとてもいいと思います。誤解を生むことも少なそう。

**Comment by syuilo** [comment]
> 投稿したノート、添付した画像などのコンテンツを学習の対象にしないようAIに要求します。

とあるから現状でも問題ないと考えます

**Comment by Nanashia** [comment]
見解どうもありがとうございます！ 

` preventAiLarning: "AIによる学習を防止" `
そのうえでのコメントですが、ここの文言だけでも変えられないでしょうか。防止って言っているのにAIに学習された！Misskeyはウソをついている！みたいなクレームに発展しないかを心配しています。
（この辺、ナイーブな人も多いのでちょっと慎重になっています。気にしすぎかもしれませんが。）

**Comment by syuilo** [comment]
「軽減」にするかしら

**Comment by syuilo** [comment]
「許可しない」でも良いかも

**Comment by Nanashia** [comment]
候補としてはこんな感じ？
「AIによる学習を軽減」　← ママ案
「AIによる学習を望まない」　←意思を強調
「AIへの利用を拒否」　←インデックス拒否みたいな感じ

**Comment by syuilo** [comment]
タイトルを「AIによる学習を拒否」にして「この機能は実験的であり、AIによる学習を完全に防止するものではありません」を追加する

**Comment by Nanashia** [comment]
> タイトルを「AIによる学習を拒否」にして「この機能は実験的であり、AIによる学習を完全に防止するものではありません」を追加する

個人的にはこちらの方針で問題ございません！

**Comment by tamaina** [comment]
実験的というより尊重されない可能性があることを言ったほうがよさそう

**Comment by Nanashia** [comment]
迅速に実装いただき、また細かい文言の相談まで対応いただきましてありがとうございました 🙏🙏🙏 

一点補足ですが、提唱元のサイトはこのオプションをデフォルト"OFF"にしたところ、
利用者から[猛反発があってデフォルト"ON"](https://www.deviantart.com/team/journal/UPDATE-All-Deviations-Are-Opted-Out-of-AI-Datasets-934500371)に舵を切った経緯があります。
ですので、残念ながらどちらをデフォルトにしようが反発は起きてしまうでしょう。つらい。

**Comment by u1-liquid** [comment]
この件、結局尊重してくれるかも分からないフラグでどっちにしても反発が起きるということを事前に知ってたら実装自体反対してたかも

**Comment by EbiseLutica** [comment]
まあそもそもAIに対する是非って未だ全世界的に結論は出てなくて、話すことそのものが疲れるような段階にあるので、Misskeyにこれを導入した時点でその白熱的な議論に巻き込まれることは覚悟すべきだったかも（この機能が実装されることを追えてなかったので、これをもっと早く言えばよかった）

**Comment by kanasaki15** [comment]
横槍失礼します

ひとまずサーバー側のコントロールパネルでデフォルト値を設定できるようにしませんか？

**Comment by tamaina** [comment]
デフォルトで有効にすると反発が起きるとはまったく思っていなかった

**Comment by u1-liquid** [comment]
> デフォルトで有効にすると反発が起きるとはまったく思っていなかった

個人的には
* 自分のデータの公開範囲が勝手に変わったと思えばあまり好ましくはない、勝手にAI反対って趣旨のタグが付いたのと同じなのでちょっとアレ
* おいしいBOT、れいじゅぼっとなどが急にグレーになったのも微妙
* APで連合された場合結局尊重されそうにないフラグなので更に微妙

って感じだった

**Comment by tamaina** [comment]
テキストはあんま考えてなかったけど…グレーになるのは仕方ないかも

ところで、自動NSFWで機械学習使っときながらユーザーのデータを使うのデフォルトでNGというのはちょっと矛盾がある気がする

**Comment by acid-chicken** [comment]
> ところで、自動NSFWで機械学習使っときながらユーザーのデータを使うのデフォルトでNGというのはちょっと矛盾がある気がする

train じゃないから話は別じゃない？
train じゃない利用を含めると自動翻訳などが使えなくなる

**Comment by acid-chicken** [comment]
> APで連合された場合結局尊重されそうにないフラグなので更に微妙

とりあえずこれが問題点として大きいのでほぼ効果のない宣言をしているとして差し戻してもいいレベルに感じている

**Comment by u1-liquid** [comment]
`no-ai-train`じゃなく`no-ai`で、一番上にリンクされてる記事にも`non-human usage`、`AI datasets prevent to use your content`など、特に学習に限って制限するニュアンスではないかも

NSFW判定もAIツールにINPUTとして渡すので、AI DatasetがUSEするのでは？といえばUSEしてる

**Comment by acid-chicken** [comment]
> NSFW判定もAIツールにINPUTとして渡すので、DatasetがUSEするのでは？といえばUSEしてる

ちょっとよく意味が分からないけどモデルデータはオフラインなのになぜここで主語が Dataset になるの？

**Comment by tamaina** [comment]
オフラインでも将来的なデータセット向上に使おうとした場合に使えないのはどうなの（ということになるのではないか）という話

**Comment by acid-chicken** [comment]
話がややこしいし続けてもこれからややこしくなるから続きは別で切ることにして本題に戻りたい

**Comment by u1-liquid** [comment]
> ちょっとよく意味が分からないけどモデルデータはオフラインなのになぜここで主語が Dataset になるの？

一番上のDevianArtsの説明がAI Datasetがなんとかかんとかになってるのでそれです
オンラインオフライン関係なくAIデータ集合ではある

追記
もうちょいまとめるとNSFWプラグもAIでNSFWというプラグ（ラベル）を生成してるので、使われてるといえば使われてるって話です

**Comment by acid-chicken** [comment]
> 話がややこしいし続けてもこれからややこしくなるから続きは別で切ることにして本題に戻りたい

あとこの話の不毛な点として、単なる利用において AI か否かとかどこまでが利用なのかという議論が着地しない
例えばユーザーが iPhone を使っていたとき AI 「利用」禁止のコンテンツに iOS の「翻訳」機能が使えないどころか「Siri からの提案」に含まれるのを阻止するためそもそも閲覧すべきでないとか頓珍漢な話に突入しかねない

**Comment by u1-liquid** [comment]
結局 noai 自体定義が曖昧で現実的ではないかも
