### ISSUE TITLE
Global メニューでキーボードショートカットの監視時、d,s,n,p,esc,tしか見てない

### ISSUE THREAD

**Issue by blackwingcat** [syuilo/Misskey#10818]
## 💡 Summary

Misskeyのグローバルメニュー内で
app-cbddf100.js 内のキーボードイベントをモニタしてみたところ
キーボードイベントの
d: ダークテーマのトグル
s: 検索
n/p: note
esc: 
t: ターゲット変更
しか処理していない

https://gist.github.com/syuilo/1a6e2e7dde2c9c9c4412a608ccd78cb1
に書かれてるH, ? / Z などの主要なショートカットキーが機能していない。

## 📝 Steps to Reproduce

1. Homeで何かキーボードを押す
2. イベントキーのパターンマッチングを行っているが、３種類、５パターンしかスキャンしていない。

![hook](https://github.com/misskey-dev/misskey/assets/6497825/1449782c-a413-45be-addc-6683c44f472f)

## 📌 Environment

Misskey version:  v13.11.3
PostgreSQL version:
Redis version:
Your OS: Windows  10.0.19043.1706 (x64)
Your browser: Chrome 112.0.5615.140 x64

**Comment by syuilo** [comment]
https://gist.github.com/syuilo/1a6e2e7dde2c9c9c4412a608ccd78cb1
は5年くらい前の記事で今とは全く違うので見ないほうが良いですね

**Comment by blackwingcat** [comment]
> https://gist.github.com/syuilo/1a6e2e7dde2c9c9c4412a608ccd78cb1 は5年くらい前の記事で今とは全く違うので見ないほうが良いですね

https://wiki.misskey.io/ja/function/keyboard_shortcut
Wikiも似たような内容なので、
h/?のショートカットが効かないとオンライン探さざる得ないので
最新のマニュアルがどれだか分かればよいなぁ ･ω･
