### ISSUE TITLE
投稿範囲が「フォロワーのみ」のノートが検索できない

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#10817]
## 💡 Summary

meilisearchを有効にした状態で検索を行う。

## 🥰 Expected Behavior

postgresql検索時と同様にフォロワーのみの投稿も検索結果に表示される。

## 🤬 Actual Behavior

フォロワーのみの投稿が検索結果に表示されない。

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: 13.12.1(docker)
PostgreSQL version: 15.1
Redis version: 7
Your OS: iOS13.4.1
Your browser: Safari
meilisearch: 1.1.1

**Comment by Steve-0628** [comment]
今のところは仕様っぽいです
https://github.com/misskey-dev/misskey/blob/69afd0480e176b105ad1482c7fc72480ecd1b51a/packages/backend/src/core/SearchService.ts#L99

**Comment by nakkaa** [comment]
なるほど。
Meilisearchを使うことによる制限（仕様）ということでしたら、その旨を記載していただければCloseで構わないです。

**Comment by mappi-pr** [comment]
@nakkaa 
> その旨を記載していただければ

私がうまく読み取れなかっただけかと思いますが、、、
どこに記載されているべき（しておいてほしかった）とお考えでしょうか？

- Misskey Hub(meilisearchに関する記事が現状ないのでそこからですが)
　⇒Misskey HubのIssueとして起票したほうがよいかも？
- CHANGELOG
- ソースコード内のコメント
- その他

**Comment by nakkaa** [comment]
言葉不足で失礼しました。
運用者としてはソースコードまで読むのはしんどいので、CHANGELOGのnote欄やMisskeyHubに記載があると親切かなと思いました。

**Comment by samunohito** [comment]
#10979 にてCHANGELOG.mdに記載されたようなので、closeします。
また、別線でMisskeyHub側にissueを立ててきたので、そちらでも記載されることになるかと思います。
