### ISSUE TITLE
v13.12.0においてユーザープロフィール関連の画像が消失する

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#10811]
## 💡 Summary

v13.10.3からv13.12.0へアップデートを行った結果、ローカルリモートを問わず、全てのプロフィール関連画像が表示されなくなった。（ユーザーアイコンはデフォルトに戻されている）

## 🥰 Expected Behavior

全てのアイコン・プロフィールが適切に表示される

## 🤬 Actual Behavior

ユーザーアイコンがデフォルトに戻され、プロフィール画像のバナーが消えている。

ただし、手動取得を行うと表示される。ローカルユーザーについて手動取得の手段が無いので画像が抜け落ちたままになっている。
おそらく初めて表示されるユーザーについては情報が取得できていると思われれる。

## 📝 Steps to Reproduce

1. v13.12.0へのアップデートをMisskey Hubの指示に従って行う
2. タイムラインを表示する

## 📌 Environment

Misskey version: v13.12.0 on Docker (update from v13.10.3)
PostgreSQL version: v15
Redis version: v7
Your OS: CentOS Stream 9
Your browser: Chrome (Stable / latest)

**Comment by syuilo** [comment]
ローカルでは再現しないので謎

**Comment by sasagar** [comment]
なお、Rawで見ても情報は適切に取得できています。

**Comment by sasagar** [comment]
ローカルユーザーについてはドライブから選択し直すと反映されました...。

**Comment by sasagar** [comment]
DB内のuserテーブルにおいて軒並みavaterUrl, bannerUrl等がnullになっていることを確認しました。

**Comment by Nanashia** [comment]
bd1c2ab で過渡期対応を消したのでv13.11を経由しないと中途半端な状態になってしまう？

**Comment by tamaina** [comment]
確かにv13.11を経験してないとダメそう

https://github.com/misskey-dev/misskey/commit/521eb95dbc89d1825867f9ab4dc3510cbd504ba9

**Comment by sasagar** [comment]
様々なアドバイスを頂きまして。
https://github.com/misskey-dev/misskey/commit/bd1c2abffc7554be16558b66189e5406df04d340
ここで消されているmigrationを復活させたところ全て取得されるようになりました。

どんな対応が適切なのかは正直わからないです。（バックエンド側殆どコード見れていないので。）
