### ISSUE TITLE
カスタム絵文字が編集できない

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#10813]
## 💡 Summary
カスタム絵文字が編集できない

## 🤬 Actual Behavior
![image](https://user-images.githubusercontent.com/61890205/237005908-f658fc24-4e84-4b6c-a27f-9f5cb1aecab4.png)

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: v13.12.0
PostgreSQL version: 15
Redis version: 7
Your OS: ubuntu
Your browser: firefox

**Comment by syuilo** [comment]
修正されています:pray:
