### ISSUE TITLE
Discord等で、Misskeyのノートに添付された画像のサムネが表示されてほしい

### ISSUE THREAD

**Issue by 417Nazuna** [syuilo/Misskey#10821]
## 現状
今のところ、Misskeyの画像つきノートのリンクをdiscordにのせても
以下スクショの通り「投稿者の名前」「投稿した文字列」と、ファイル件数を示すクリップ絵文字と数字の文字列しか出てこない
（[discordに実際にリンクをのせた書き込みはこちらから](https://misskey.io/notes/9db8kod2cs)）
![image](https://github.com/misskey-dev/misskey/assets/53173999/658329ad-42ef-431c-9cb8-9827cc76d222)

## どうなってほしいか
Twitterの公式なリンクや、あるいはvxtwitter（[レポジトリはこちら](https://github.com/ryuuzake/BetterTwitFix)）
（URLを少しいじるだけでツイートに添付された動画をサムネ表示するもの）のように
「画像や映像を添付されたノートは、それがサムネ表示される」
ようになってほしい、あるいはそういうものが欲しい
![image](https://github.com/misskey-dev/misskey/assets/53173999/073fdbb2-983e-4390-96d2-8fc950ce6e56)

既にそういう外部ツールがあるなら、その紹介でもＯＫ
（どうすればいいのか、プログラムを組むこと等に関する実践的な知見が自分にあまりないので
misskeyのIssueとして投稿しました）

**Comment by mappi-pr** [comment]
面白そうな構想だったので、Discord側の仕様を見ておくべく
htmlの実験ページにTwitterとmisskeyのOGPタグを悪魔合体させながら移植してみたのですが、
どうやらdiscord側に「Twitterドメインのリンクだった時」に特別な表示にするような仕様が入っていそうな感じがしました。

misskey側で、「ユーザのアイコン」と「記事内に埋め込まれた画像」の両方のデータを持った状態に修正してもDiscord側でそれを読み取ってくれるように変更してもらわないとTwitterリンクが張られた時のような挙動を完全に反映するところまではいけないかもしれないです。

>「画像や映像を添付されたノートは、それがサムネ表示される」

ということであれば、記事内に画像がある場合はそれを優先してアイコンは表示しない
とかはできるのかも？
（まだあまりmisskeyのコード読めてないので、本当にできるかどうかはわからないです。NSFWの問題もあるからちょっと大変かも）

<details>
<summary>discord URL貼り付け実験</summary>

■Twitterのリンクが張られたとき
・左上にツイッターアイコンを表示できる
・ツイートの本文を引用できる
・ツイートに埋め込まれた画像を表示できる
<img width="374" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/da9cffde-9ad6-436c-abf3-299ba915274f">

■独自ページのリンクが張られたとき
Twitterと同じ記事のOGP属性が埋め込まれていても、
サイトの概要を表示するタグのみが優先して（？）引用されて、
本来ツイートに埋め込まれていた画像などは引用されない
<img width="430" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/5a2364ab-2e08-46cc-8c0b-3a46fe27289d">
</details>

<details>
<summary>【為参考】悪魔実験のダミーhtml</summary>

```
<html>
    <head>
        <meta charset="utf-8">
<!-- misskeyから拝借したOGP -->
        <meta property="og:type" content="article">
        <meta property="og:title" content="パイングミ:verifinking: (@pinegumi)">
        <meta property="og:description" content=":blobcatsweatflips: (📎1)">
        <meta property="og:url" content="https://misskey.io/notes/9db8kod2cs">
        <meta property="og:image" content="https://nos3.arkjp.net/avatar.webp?url=https%3A%2F%2Fs3.arkjp.net%2Fmisskey%2Fa5965cc1-4fad-48a3-952b-4cca8de0df53.png&amp;avatar=1">

<!-- Twitterから拝借したOGP -->
        <meta property="og:site_name" content="Twitter">
        <title>まっぴーさんはTwitterを使っています: 「本の残部数少なくなってきてるので特別に1ページだけ共有しますー🌅
        ね！！これは解釈一致すぎませんか✨✨ https://t.co/8iinM48Obg」 / Twitter</title>
        <meta content="article" property="og:type" data-rh="true">
        <link href="https://publish.twitter.com/oembed?url=https://twitter.com/mappi_pr/status/1652281512640024579" rel="alternate" title="まっぴーさんはTwitterを使っています: 「本の残部数少なくなってきてるので特別に1ページだけ共有しますー🌅
        ね！！これは解釈一致すぎませんか✨✨ https://t.co/8iinM48Obg」" type="application/json+oembed" data-rh="true">
        <meta description="" name="description" data-rh="true">
        <link href="https://publish.twitter.com/oembed?url=https://twitter.com/mappi_pr/status/1652281512640024579" rel="alternate" title="まっぴーさんはTwitterを使っています: 「本の残部数少なくなってきてるので特別に1ページだけ共有しますー🌅
            ね！！これは解釈一致すぎませんか✨✨ https://t.co/8iinM48Obg」" type="application/json+oembed" data-rh="true">
        <meta content="https://twitter.com/mappi_pr/status/1652281512640024579" property="og:url" data-rh="true">
        <meta content="まっぴーさんはTwitterを使っています" property="og:title" data-rh="true">
        <meta content="“本の残部数少なくなってきてるので特別に1ページだけ共有しますー🌅
        ね！！これは解釈一致すぎませんか✨✨”" property="og:description" data-rh="true">
        <meta content="https://pbs.twimg.com/media/Fu4VRmZagAIRyPR.jpg:large" property="og:image" data-rh="true">
    </head>
    <body>
        dummy page
    </body>
</html>
```

</details>

**Comment by futchitwo** [comment]
- Related to #5964
  -  ただそちらでは Discord での見え方には言及してない

**Comment by mappi-pr** [comment]
@futchitwo 
OGPについてのIssueご紹介いただきありがとうございます！

@417Nazuna 
https://github.com/misskey-dev/misskey/issues/5964#issuecomment-1416801356
こちらのコメントで紹介されているforkの内容を取り込んだサーバを利用すれば、
meta要素にコンテンツのサムネイルを持つことができるようになるので、
discord上での表示を最適化するために変換を噛ますためのサービスを別途開発すれば、
やりたいことができるようになるのかなといった現状と認識しております。

>既にそういう外部ツールがあるなら、その紹介でもＯＫ

（そもそもNOTE画面見たときに、/api/notes/show/からコンテンツのサムネイルが取れるので、それを利用した短縮URL作成的な外部サービスを作ればいいのかも、、、）
