### ISSUE TITLE
CSS Moduleのクラス名が変わらないようにする（カスタムCSS）

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10827]
## Summary

ビルド毎にカスタムCSSが崩れるのでなんとかしたい

**Comment by kakkokari-gtyih** [comment]
一部分だけでも規則性のある名前を維持できればセレクタが使える（`[class^="foobar"]`）

**Comment by tamaina** [comment]
ん、これ一回解決したような

**Comment by kakkokari-gtyih** [comment]
> ん、これ一回解決したような

ほんまや（アップデート時に狂ったところがあったみたいなのでIssueにしたのですが）

**Comment by syuilo** [comment]
変わらないように保証すると内部的なリファクタも何もできなくなるので不可能

**Comment by syuilo** [comment]
よってカスタムCSS自体非推奨
