### ISSUE TITLE
MeiliSearch設定時、ユーザー名でユーザーの検索ができない

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/Misskey#10826]
## Summary

MeiliSearch 側にユーザー名（@name）のフィールドがインデクシングされていないので、ユーザー名で検索するとその人に飛んできたメンションが出るだけで、その人の投稿を検索することはできない

**Comment by syuilo** [comment]
ユーザー名をクエリに入力することで特定のユーザーの投稿を取得する用途は考えてないためこれは仕様

**Comment by syuilo** [comment]
今後特定のユーザーのみ検索対象にする機能を実装する場合はいったんユーザー名→ユーザーＩＤの変換をバックエンド側でやるようにする

**Comment by syuilo** [comment]
なのでMeilisearch側でユーザー名を持つ必要性がなさそう

**Comment by tamaina** [comment]
backendのソースコードを読むと実はnotes/search, searchNote自体はuserIdで絞る機能を持っている

(クライアントでは実装されていないが)

**Comment by syuilo** [comment]
ユーザー指定検索実装するか
