### ISSUE TITLE
ノート検索でURLを入力するとエラーになる

### ISSUE THREAD

**Issue by mappi-pr** [syuilo/Misskey#10839]
## 💡 Summary
ノート検索画面で、"https://"から始まるURLを検索するとプロンプトにメッセージが空のエラーが表示される。
開発者ツールを参照するとAPIが500エラーで返却されている。

## 🥰 Expected Behavior
入力したURLを含むノートの検索結果が表示される。

## 🤬 Actual Behavior
![image](https://github.com/misskey-dev/misskey/assets/75538777/6cdb4b1c-2e27-4bab-9882-f690388e0bce)

## 📝 Steps to Reproduce

1.ノート検索画面を開く
2.「 https://www.youtube.com/watch?v=Efrlqw8ytg4 」で検索する
3.エラー発生

## 📌 Environment

Misskey version:13.12.2
PostgreSQL version:?(Misskey.io)
Redis version:?(Misskey.io)
Your OS:mac OS 13.3.1 (a)
Your browser:Google Chrome 113.0.5672.92

**Comment by tamaina** [comment]
（リンクをリモートのユーザー/投稿として参照してしまっているのが原因）

**Comment by mappi-pr** [comment]
@tamaina アドバイスいただきありがとうございます！
\packages\frontend\src\pages\search.note.vue(L.69～)
'https://'で検索された際に「照会(ap/show)」の挙動になるため、
「照会」できないURLが入力されてしまったときに、
ap/showのINTERNAL_ERRORが返却されてしまうということだったんですね。。。

- #10582

https://github.com/misskey-dev/misskey/issues/10582#issuecomment-1514035517

>1. ノート検索/照会　という感じでボタンを置く
>2.  検索を押したら、ユーザーが照会可能ならノート検索の上にユーザーを表示、ハッシュタグが入力されたらハッシュタグ検索結果を表示

先行Issueあったので、重複扱いでクローズさせていただきます。
