### ISSUE TITLE
ページにて画像貼付後表示されない

### ISSUE THREAD

**Issue by nenohi** [syuilo/Misskey#10837]
## 💡 Summary
ユーザーからの問い合わせにて発覚
ページ作成時に画像をページにて追加後、保存しても画像がページに表示されない

API上では保存されているが、コンテンツとして表示されていない模様

## 🥰 Expected Behavior
ページにて画像が表示される

## 🤬 Actual Behavior
ページにて画像が表示されない

## 📝 Steps to Reproduce

1.ページ作成
2.ページのコンテンツにて画像を選択
3.ページ保存
4.ページを見ると画像が表示されない

## 📌 Environment

Misskey version:13.12.2
PostgreSQL version:
Redis version:
Your OS:Windwos
Your browser:Chrome

**Comment by kanasaki15** [comment]
こちらの環境(13.12.1)でも事象発生を確認しました
