### ISSUE TITLE
frontend: init.tsをmain-boot.ts/sub-boot.tsのように分ける

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10838]
## Summary

main-boot.tsはinit.tsと同様

sub-boot.tsはmain-bootを簡略化したもので、UIもZenUIにする
シェアページやMiAuth認証ページなどにアクセスされた際に、main-bootではなくsub-bootで読み込むことでパフォーマンスの向上やフルUIで開いてしまう問題を解決する

**Comment by acid-chicken** [comment]
Storybook の preview でやってるワークアラウンドが解決するような minimum boot があると嬉しい

**Comment by syuilo** [comment]
Viteで複数のエントリポイント(？)をビルドするように設定するのが面倒かも(そもそもできるのかしら)

**Comment by tamaina** [comment]
init.tsでは条件によってsub-boot.tsとmain-boot.tsをdynamic import＆boot関数実行するだけにするとか？

**Comment by syuilo** [comment]
それでも良いか

**Comment by tamaina** [comment]
（Zen UIを考えた時、sub-bootにファイル分割して削ぎ落とせるものって少ない気がする…）

**Comment by syuilo** [comment]
dynamic importだとHTTPリクエストが1増えるから初回アクセス時の表示速度という観点では今より悪化するかも

**Comment by syuilo** [comment]
done
