### ISSUE TITLE
MeiliSearch設定されたサーバーの検索で、検索がミュートを考慮しない？

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#10844]
## 💡 Summary

従来の検索ではそのような動作をしなかったと思われるのだが、MeiliSearchはユーザーミュート設定を考慮した結果を返してこないようです

## 🥰 Expected Behavior

ユーザーミュート設定を考慮して結果を返す

## 🤬 Actual Behavior

ユーザーミュート設定を考慮しないで結果を返す

**Comment by tkmrgit** [comment]
#12575 にて修正された模様。動作が正常であれば`close`してください

**Comment by samunohito** [comment]
@tkmrgit 
最新に追従している＆Meilisearch使っているところで確認しました。問題なさそうなのでcloseします
