### ISSUE TITLE
MeiliSearch設定されたサーバーの検索で外部サーバーの投稿が結果に出ない場合がある

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#10845]
## 💡 Summary

MeiliSearch設定されたサーバーの検索で外部サーバーの投稿が結果に出てこないワード？がある

## 🥰 Expected Behavior

外部サーバーの投稿を含めた結果が返される

## 🤬 Actual Behavior

外部サーバーの投稿が含まれていない結果が返される

## 📝 Steps to Reproduce

1.ioで「Misskey」または「Misskey しゅいろ」と検索
2.「Misskey」の場合は外部サーバーが出てくるが、「Misskey しゅいろ」の場合に出てこない

## 📌 Environment

Misskey version:13.12.2

**Comment by syuilo** [comment]
ioは昔の投稿についてはローカルしか取り込まなかったはず

**Comment by tkmrgit** [comment]
ioのインデックスが原因か。
しかしMeiliSearchだと何か以前にも増して元の投稿の文に近いワードじゃないとヒットしないわね

もし別の原因あったらreopenしてください

**Comment by syuilo** [comment]
以前というと？

**Comment by syuilo** [comment]
ElasticSearch時代のことなのかPostgreSQL時代のことなのか

**Comment by syuilo** [comment]
PostgreSQLの方は単純な部分一致検索なのでMeilisearchよりも精度という意味では高い

**Comment by tkmrgit** [comment]
> 以前というと？

DB検索だった頃と比べて極端にヒットが少ない。p1.a9z.dev(未導入?)で「Misskey しゅいろ」検索すると他にもいろんなioを含む投稿がヒットするが、ioだと直近でも3ヶ月前だったりしにゃい

**Comment by syuilo** [comment]
「しゅいろさん」とかが含まれる文章はMeilisearchでは「しゅいろ」ではヒットしないわね

**Comment by syuilo** [comment]
形態素解析の限界そう

**Comment by tkmrgit** [comment]
😭

**Comment by tamaina** [comment]
p1.a9z.devはPGroongaなんだけど、（日本語では）PGroongaのほうがいいらしい？

**Comment by miiton** [comment]
いきなり失礼します。Twitterで見かけて気になったのでコメントしにきました。

`しゅいろ` という文字列が、 `し` と `ゅいろ` に分割されてしまうので起きる問題かなと推察します。

|||
|----|----|
|![image](https://github.com/misskey-dev/misskey/assets/468745/24f7f92e-64ac-42d2-bd8d-de9902cb1589)|![image](https://github.com/misskey-dev/misskey/assets/468745/2a42d537-f8c1-4287-85e2-330f4a4b5a33)|

Ref: https://www.atilika.com/ja/kuromoji/

実際に手元でやってみたところ結果は返ってはくるのですが、やはり `し` と `ゅいろ` に分かれてしまうので、ランキング的に下の方に行ってしまっているのかも？（ MeiliSearch v1.1.1 です）
![image](https://github.com/misskey-dev/misskey/assets/468745/31dbb756-1b8c-4734-bd3c-b44f895a7af9)
[TypoToleranceを今は無効にしておられる](https://github.com/misskey-dev/misskey/blob/9166a58c5fa422c0cd5989bdff39ee6c62e382bf/packages/backend/src/core/SearchService.ts#L87-L89) のでそれを有効にしたらまた違った結果が返ってくるかもしれません（手元の少ないデータでは違いは無かったです）

~~ちなみに manticore search だと綺麗にヒットしました。~~
![image](https://github.com/misskey-dev/misskey/assets/468745/78067e28-8fc1-464f-80aa-63b34a80e84f)

（追記）manticore-searchが単純にハイライト部分をマージして結果を出しているだけかもしれないのでこの部分は訂正します。すいません。

MeiliSearchの改善ポイントかなと思いますので、時間作ってIssue立ててみます。

**Comment by syuilo** [comment]
@miiton 

> しゅいろ という文字列が、 し と ゅいろ に分割されてしまうので起きる問題かなと推察します。
Ref: https://www.atilika.com/ja/kuromoji/

Meilisearchは内部的に日本語の形態素解析にkuromojiを使用している感じですかね？そういうわけではない？

> MeiliSearchの改善ポイントかなと思いますので、時間作ってIssue立ててみます。

ありがとうございます！！！

**Comment by acid-chicken** [comment]
> Meilisearchは内部的に日本語の形態素解析にkuromojiを使用している感じですかね？そういうわけではない？

kuromoji をベースに開発された kuromoji-rs の fork である lindera を使用している

**Comment by miiton** [comment]
本件、もしかして冒頭に書いていただいている `Misskey しゅいろ` みたいに `英単語 + にほんご` が駄目っぽいですかね？
`しゅいろ` だと検索できますよね？

**Comment by tamaina** [comment]
わかる

（しゅいろで検索できてMisskeyと検索すると出てこないのは少々おかしい）

**Comment by u1-liquid** [comment]
ちなみにCJK対応に関してちょっと問題があるので使うMeilliSearchのバージョンはこっちにした方がいいです

https://github.com/meilisearch/meilisearch/pull/3588

**Comment by miiton** [comment]
> ちなみにCJK対応に関してちょっと問題があるので使うMeilliSearchのバージョンはこっちにした方がいいです

はい、検索が日本語と英単語だけならそれが良いと思います。中国や台湾のユーザーさんも視野に入れるならちょっと考えたほうがいいかもしれません。（中国語対応を外して日本語強制しているバージョンなので）


----
英単語 + 日本語で問題無い文字列と問題がある文字列があるみたいなので、いくつかパターン出してバグ報告してきます

**Comment by miiton** [comment]
いくつかパターンを書いてみて試したのですが、結局 `英語+ 日本語` とかではなく

* `しゅいろ` という文字列が、 `し` と `ゅいろ` に分割されてしまう
* [Ranking Rulesのwords rule](https://www.meilisearch.com/docs/learn/core_concepts/relevancy#1-words) によって、複数ある検索ワードのうち最初のキーワードが結果に優先される

のあわせ技によって検索結果がおもてたんとちゃうになっているようです。（二転三転しました 🙇 ）

要は固有名詞（Misskeyの場合はユーザーのお名前など）を適切に扱えるようになれば良いと思いますので、日本語対応のスレッドにて確認中です。
https://github.com/meilisearch/product/discussions/532#discussioncomment-5895057

（良い例文がぱっと思い浮かばなくて、しゅいろさんをたくさん出してしまいました）
