### ISSUE TITLE
ユーザー向けの開発者モードを追加する

### ISSUE THREAD

**Issue by yupix** [syuilo/Misskey#10846]
## Summary

MisskeyのAPIなどを使用するうえで、ノートのcontextmenuからユーザーIDやノートIDをコピーしたいと思うことが多いから。

### 解決方法

コピーするのが少し手間なので、Discordにあるような開発者モードを用意し、有効になっている場合のみcontextmenuに項目を追加する

### Discordでの見た目

<img width="126" alt="image" src="https://github.com/misskey-dev/misskey/assets/50538210/c77dbcb9-9360-4f8b-a337-3ac8e0da7f13">
<img width="341" alt="image" src="https://github.com/misskey-dev/misskey/assets/50538210/d62a4fa5-fa1c-4f26-8448-2ee7572bc060">

## 実際にMisskeyに実装した際の見た目

<img width="449" alt="image" src="https://github.com/misskey-dev/misskey/assets/50538210/bbded211-dd7d-4094-a797-4209ac3b2dc1">
<img width="150" alt="image" src="https://github.com/misskey-dev/misskey/assets/50538210/37c9c5d0-2965-4e08-9b88-aceda0224a8e">
<img width="300" alt="image" src="https://github.com/misskey-dev/misskey/assets/50538210/60c99b51-8afe-4a8f-aa30-f2e259391795">

**Comment by syuilo** [comment]
YOSASOU
