### ISSUE TITLE
ハッシュタグのノート一覧ページに、そのハッシュタグで投稿するボタンか投稿フォームがあるとよい

### ISSUE THREAD

**Issue by yuba** [syuilo/Misskey#10854]
■現状

ハッシュタグのノート一覧をみて自分でも発言しようと思った場合、
1. ハッシュタグの文字列を選択してコピーする
2. 投稿ダイアログで、 `#` を打つか `#` ボタンを押す
3. ハッシュタグをペーストする
という手間が入ってしまいます。

■こうなるといい

1. ハッシュタグのノート一覧ページに、ハッシュタグで投稿するボタンがある
2. そこから投稿ダイアログを開くと、最初からハッシュタグが設定済の投稿ダイアログが開く  
タイムライン上部に投稿フォームが表示される設定の場合、ハッシュタグが設定済の投稿フォームとなっている

■こうなるとよい理由

ハッシュタグがチャンネルほど有効活用されていないのは、投稿するのに小さなハードルがあるためと思われるので、
それを取り除いてあげることで他サーバーとも交流ができるハッシュタグの利用を広げられそう。

**Comment by mappi-pr** [comment]
> 1. ハッシュタグのノート一覧ページに、ハッシュタグで投稿するボタンがある

こんな感じでしょうか？
（backendなんもわからんなのでfrontendだけのモックです）
<img width="960" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/0064c5bd-fafd-49a2-87e0-9ab4dc112f53">

**Comment by syuilo** [comment]
lgtm

**Comment by mappi-pr** [comment]
> 2. そこから投稿ダイアログを開くと、最初からハッシュタグが設定済の投稿ダイアログが開く
タイムライン上部に投稿フォームが表示される設定の場合、ハッシュタグが設定済の投稿フォームとなっている

1.のボタン押したときに、投稿画面に表示されているハッシュタグの連携ができそうなので2.もできるかも。。。
![image](https://github.com/misskey-dev/misskey/assets/75538777/8ffe57f7-8fef-4b90-a595-7df64bd36f8e)

**Comment by chocolate-pie** [comment]
一応それっぽいものはできたので、明日プルリク送ります。

**Comment by Sayamame-beans** [comment]
1は実装済みのようですね。
2は #13028 で実現されようとしていることと方向性は近い気がします。

**Comment by yuba** [comment]
#10878 で解決いただきました。ありがとうございました。
