### ISSUE TITLE
アカウント初期設定ウィザードを完了した後再起動すると無のウィザードが出てくる

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#10850]
## 🥰 Expected Behavior

アカウント初期設定ウィザードが完了しているので何も出てこない

## 🤬 Actual Behavior

何も中身がないウィザードが出る

## 📝 Steps to Reproduce

1. アカウント初期設定ウィザードを完了する
2. クライアントを閉じる
3. ブラウザのストレージをリセットする
4. クライアントを開く

## 📌 Environment

Misskey version: 13.12.2
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
これでどうかしら
https://github.com/misskey-dev/misskey/commit/86f952e659005099330e648ee133a408f29c87cc

**Comment by chocolate-pie** [comment]
@syuilo 解決してないですね、、ちなみに履歴削除した直後です。<br />
<img width="863" alt="スクリーンショット 2023-05-15 8 36 55" src="https://github.com/misskey-dev/misskey/assets/106949016/33339d3f-843a-4691-ad56-493eb14c5e17">

**Comment by syuilo** [comment]
これで直ったかも
https://github.com/misskey-dev/misskey/commit/c066013c5723587ecadb20ff1bfd9397af85647a

**Comment by chocolate-pie** [comment]
@syuilo 直りました👍
