### ISSUE TITLE
日本語入力中にescで変換キャンセルしたとき投稿ダイアログまで閉じてしまわないようにする

### ISSUE THREAD

**Issue by yuba** [syuilo/Misskey#10866]
## Summary

日本語入力中、入力した未確定文字を全部取り消すにはescキーを押しますが、  
このescキーイベントはJSにも拾われて投稿ダイアログが閉じてしまいます。

■こうなってほしい

compositionstart イベントで日本語変換セッションを検知したら、セッション終了のcompositionendが発生するまではescキーによるダイアログクローズをスキップする

**Comment by Sayamame-beans** [comment]
> 日本語入力中、入力した未確定文字を全部取り消すにはescキーを押しますが、
> このescキーイベントはJSにも拾われて投稿ダイアログが閉じてしまいます。

私の環境だと再現出来ないのですが、どのような状態でしょうか…?
(こちらの環境はWindows10で、Google日本語入力とMicrosoft IMEで確認しました)

**Comment by yuba** [comment]
@Sayamame-beans  
試してみたのですが、WindowsだとATOKでもMS IMEでもこの問題は発生しませんね。  
Macだと、標準日本語でもATOKでも、またChromeでもSafariでもこうなってしまいます。

画面動画、これだとEscキーを押したことがわかりにくいですが一枚目はChrome+ATOK、二枚目はSafari+標準日本語キーボードです。

https://github.com/user-attachments/assets/1c424b28-313a-4040-a989-fbc9c95df6f0


https://github.com/user-attachments/assets/74df19fc-29f4-4bd9-a24b-41bae62a996b

**Comment by Sayamame-beans** [comment]
なるほど…
