### ISSUE TITLE
デッキUIで、メインカラムが存在しないと、ページやプロフィールなどが表示されない

### ISSUE THREAD

**Issue by alpaca-honke** [syuilo/Misskey#10871]
## 💡 Summary

デッキUIを組んだ際、そこにメインカラムがないと、/@ユーザー、/pagesや/shareなどにアクセスしても表示されないので、表示されるようにしていただきたいです

## 🥰 Expected Behavior

サーバーのルート以外のURLにアクセスした際に、Misskey上のウィンドウで、該当のウェブページを開いて欲しい

## 🤬 Actual Behavior

サーバーのルート以外のURLにアクセスしても、ルートにアクセスした際と同じ内容しか表示されない

## 📝 Steps to Reproduce

共有フォームの場合

1. UIをデッキにし、メインカラムを削除する
2. <サーバーのドメイン>/share にアクセスする
3. 共有フォームが表示されない

## 📌 Environment

Misskey version:13.12.2
PostgreSQL version:不明
Redis version:不明
Your OS:Android13
Your browser:KiwiBrowser112

Misskey.io鯖で使用しています

**Comment by syuilo** [comment]
`/`以外にアクセスした場合はDeckを表示しないようにした
