### ISSUE TITLE
ユーザーのプレビューは自己紹介が長すぎて見栄えが悪い

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10870]
## Summary
ユーザーをホバーした時やユーザー一覧などでは自己紹介を短くして欲しい

![image](https://github.com/misskey-dev/misskey/assets/7973572/6bd8bbe8-efcb-458e-bbcd-73ce2bbbbb21)

**Comment by syuilo** [comment]
あら3行に制限するCSSがいつの間にか効かなくなってるのかしら

**Comment by tamaina** [comment]
こんなんだっけと思ってたけどバグだったか

**Comment by tamaina** [comment]
これ治りにくいの

**Comment by syuilo** [comment]
多分直った

**Comment by mappi-pr** [comment]
@syuilo 
💕
<img width="689" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/9c9957be-54b0-41b6-b0b5-3919aa260ce5">

@tamaina 
> ユーザーをホバーした時

こっちも対象でしょうか？
<img width="365" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/222c87a4-6e57-4404-ab2c-668357a28229">

**Comment by tamaina** [comment]
なおってないですね

**Comment by tamaina** [comment]
なおすか？
