### ISSUE TITLE
Content of "Page" is not rendered

### ISSUE THREAD

**Issue by ztrehagem** [syuilo/Misskey#10872]
## 💡 Summary

Content of "Page" is not rendered when view and edit it on v13.13.0-beta.1 and beta.2.

v13.13.0-beta.1とbeta.2で、「ページ」の本文が閲覧画面・編集画面ともに描画されていません。

## 🥰 Expected Behavior

- 「ページ」の閲覧画面と編集画面で、本文が表示される。

## 🤬 Actual Behavior

- 「ページ」の閲覧画面と編集画面で、本文が表示されない。
- `POST /api/pages/show` のレスポンスには、本文が含まれている。

https://t1.ztrehagem.dev/@ztrehagem/pages/terms_of_use

## 📝 Steps to Reproduce

1. v13.12.2以前から存在する「ページ」の閲覧画面を開く
   - 本文が表示されません
2. v13.12.2以前から存在する「ページ」の編集画面を開く
   - 本文が表示されません
3. 「ページ」の編集画面で、何らかのブロックを追加する
   - 追加したブロックが表示されません 

## 📌 Environment

Misskey version: v13.13.0-beta.2
PostgreSQL version: 15.3
Redis version: 7.0.11
Your OS: Windows 10 / macOS Ventura 13.3.1 (a)
Your browser: Chrome 113.0.5672.127 / Chrome 113.0.5672.126

**Comment by tar-bin** [comment]
https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/components/page/page.block.vue#L2

pageプロパティが渡ってないのとcomponentのtypeが取れてないようです、とりあえずこんな感じにしたら動きました。

```
<template>
<component :is="type" :key="block.id" :page="page" :block="block" :h="h"/>
</template>

<script lang="ts" setup>
import { onMounted, shallowRef, defineAsyncComponent } from 'vue';
import * as Misskey from 'misskey-js';
import { Block } from './block.type';

const props = defineProps<{
	block: Block,
	h: number,
	page: Misskey.entities.Page,
}>();

const type = shallowRef();

onMounted(() => {
	switch (props.block.type) {
		case 'text':
			type.value = defineAsyncComponent(() => import('./page.text.vue'));
			break;
		case 'section':
			type.value = defineAsyncComponent(() => import('./page.section.vue'));
			break;
		case 'image':
			type.value = defineAsyncComponent(() => import('./page.image.vue'));
			break;
		default:
			type.value = defineAsyncComponent(() => import('./page.note.vue'));
			break;
	}
});

</script>
```

**Comment by ztrehagem** [comment]
13.13.0-beta.3 → 13.13.0-beta.5 にアップデートしたところ、修正されているようでしたのでCloseします
