### ISSUE TITLE
theturtle32/WebSocket-Node をやめる

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/Misskey#10883]
## Summary

だいぶ前から更新されていないし、恐らくメモリリークの原因になっている
websockets/ws にしたほうがいいかも

**Comment by syuilo** [comment]
パフォーマンスもtheturtle32より良さそう
https://github.com/websockets/ws#opt-in-for-performance

**Comment by syuilo** [comment]
型定義が微妙かも
ドキュメント通りに書いても怒られる https://github.com/websockets/ws#client-authentication
![image](https://github.com/misskey-dev/misskey/assets/4439005/70745b7f-158c-4d81-aeb2-486f71ae54b2)

**Comment by syuilo** [comment]
あー間違ってたかも

**Comment by syuilo** [comment]
いや合ってる

**Comment by mei23** [comment]
`wss.on('connection'`
`wss.emit('connection'`
の3つめ以降の引数 (例だとclientと書いてあるやつ) は、実は自由に追加できる引数だから
onの方でemitに対応するようにtypeは指定する必要があるわ。

https://github.com/mei23/misskey/pull/4578/files#diff-4c72119e2b25c4f9c7d8b7738e6caa5df2e5d80be4aa3600059b183272c6c40c
