### ISSUE TITLE
バックエンドのJestが遅い

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10889]
e2eテストが多いからだと思われる

- 基本的にユニットテストの方を充実させたい
- 基本的に実行するテストをサンプリングして、リリースPRの時だけ全実行するとか

**Comment by Nanashia** [comment]
- テスト開始時のjestのtransformが泣けるほど遅い（キャッシュ効いてても200-300秒くらいかかる）
  - 8e6f1508ed465069cebffdd8003904a9096617f9 で改善が入っているけどまだ厳しい
- 毎回schema作り直すためにmigrate走るので遅い（startServer()ごとに20秒くらいかかる）
- 毎回アカウントのサインアップなどの準備処理を実行するので二重になっている
  - ↑2つはe2e系のテストファイルを統合してstartServer()を減らせば改善できるかもしれない

**Comment by Nanashia** [comment]
> ↑2つはe2e系のテストファイルを統合してstartServer()を減らせば改善できるかもしれない

e2e内のmove.tsとfetch-resource.ts以外のファイルをendpoints.tsあたりに統合して何秒改善するか試してみるか～

memo: 手元だと変更"前"で `pnpm jest e2e` で 2740s ~= 45m / 758 cases total

**Comment by Nanashia** [comment]
途中経過：とりあえずつないで動かした結果e2e内の実行時間-45%くらいになった
`pnpm jest endpoints.ts\|2fa.ts\|move.ts\|fetch-resource.ts`
```
Tests:       36 failed, 2 skipped, 16 todo, 704 passed, 758 total
Snapshots:   0 total
Time:        1488.824 s
```
2740s(45m) → 1488s(25m)

**Comment by Nanashia** [comment]
syuilo https://github.com/misskey-dev/misskey/pull/10912#issuecomment-1566555946 
> 実行時間が半減するのは魅力的だけど6300行の1つのファイルになるというのが厳しいかもしれない 今後もテストが増えていくことが予想されるからこの方法だとメンテナンスが難しそうなのと結局は長い時間がかかりそう いくらテストが増えても実行時間をほぼ一定にできるサンプリング処理を実装した方が良いかもしれない？

Nanashia https://github.com/misskey-dev/misskey/pull/10912#issuecomment-1566941722 
> 一般論として：ソフトウェアは大きくなるとテストも大きくなっていくのでこれは仕方ない気がする。
> 基本的な動作を一通り実行するSmoke Testを別途用意したほうが良いかもしれない。

**Comment by Nanashia** [comment]
> 基本的に実行するテストをサンプリングして、リリースPRの時だけ全実行するとか

jestに[--changedSince](https://jestjs.io/ja/docs/cli#--changedsince)というオプションがあって、特定コミットからの差分になるファイル群に依存するテストだけ実行できるらしい。
これは使えるかも？
- [github actionsのjobを高速にするために取った対策](https://qiita.com/itouoti/items/37e0420b232a1c694288#after)
- [jest-changedSince-in-github-actions.md ](https://gist.github.com/bnb/9de89a07278e9f57cd058a535ab89a9b)
- [Jest and the `--changedSince` flag in GitHub Actions CI](https://dev.to/bnb/jest-and-the-changedsince-flag-in-github-actions-ci-468i) 

ただ、--changedSinceにしてもそれ以外のサンプリングにしても共通することとして、
PR毎のフルテスト実行をやめるとPR毎のテストカバレッジの増減が計算できなくなるのでCodeCovのうまみが半減する気がする（[How to get jest coverage only for changed files?](https://stackoverflow.com/questions/59064287/how-to-get-jest-coverage-only-for-changed-files)）
