### ISSUE TITLE
Use `notes` as meilisearch index when index name is not set

### ISSUE THREAD

**Issue by ltlapy** [syuilo/Misskey#10880]
## Summary
https://github.com/misskey-dev/misskey/commit/1cc106b8de558b867adbd545310b9e43f314c0fa でインデックス名のprefixを決めるようになって、従前Meilisearchを利用してきたサーバー全てにマイグレーション作業が必要となりました。
このような作業が煩わしいと思われることが多いと予想されるので、MeilisearchをMisskeyでのみ利用するなどの場合、マイグレーション作業を省略する選択肢を与えるのはどうでしょうか？

**Comment by syuilo** [comment]
今一時凌ぎでそうしたとしても結局は https://github.com/misskey-dev/misskey/issues/10835 が実装されたらインデックス名は変えないといけなさそう
