### ISSUE TITLE
Vitestが落ちている

### ISSUE THREAD

**Issue by chocolate-pie** [syuilo/Misskey#10886]
## 💡 Summary
Vitestが落ちている
<img width="1352" alt="スクリーンショット 2023-05-24 17 46 39" src="https://github.com/misskey-dev/misskey/assets/106949016/dde3c6a2-9b98-4d11-992d-b21c2b3a8c6d">

## 🥰 Expected Behavior
テストが落ちない

## 🤬 Actual Behavior
テストが落ちる

## 解決方法
この[パッチ](https://gist.github.com/chocolate-pie/b2afcc5eaccc15e616a26d6e866afc78)をあてて```pnpm install```する。

## 📌 Environment

Misskey version:
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by acid-chicken** [comment]
> この[パッチ](https://gist.github.com/chocolate-pie/b2afcc5eaccc15e616a26d6e866afc78)をあててpnpm installする。

違う。
test-webgl2 はテストエントリではないのでこれでは本番で TestWebGL2 が使えない。

**Comment by chocolate-pie** [comment]
これ、よく見たらMkImageWIthBlurHashで呼び出してますね。じゃあこれをテストエントリから外せばいいだけですか。
