### ISSUE TITLE
非ログイン時に実績を見るとローディングのまま進まなくなる

### ISSUE THREAD

**Issue by chocolate-pie** [syuilo/Misskey#10890]
## 💡 Summary
非ログイン時に実績を見るとローディングのまま進まなくなる
<img width="1439" alt="スクリーンショット 2023-05-25 8 37 37" src="https://github.com/misskey-dev/misskey/assets/106949016/a0f541fe-e4ce-4133-aecf-082ae4712175">

ここでログインしていないと見れなくなっていることが原因
https://github.com/misskey-dev/misskey/blob/30cb791e93c58c13f4e718aaa822ccc97d54cb83/packages/backend/src/server/api/endpoints/users/achievements.ts#L7

## 🥰 Expected Behavior
もしログインしないと実績が見れないことが正しい挙動の場合、非ログイン時は実績をタブから削除する。
もしログインしないと実績が見れないことが間違った挙動の場合、```meta.requireCredential```を```false```にし、非ログイン時にも実績を見れるようにする。

## 🤬 Actual Behavior
非ログイン時に実績を見れない

## 📌 Environment

Misskey version:
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
falseで良さそう
