### ISSUE TITLE
(Android) /shareをzen uiで開きたくない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10898]
## Summary
Androidだと/shareをzen uiで開くと微妙な感じがする

**Comment by syuilo** [comment]
どう微妙なの

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/commit/406e5d297ba3c2d45734de538c2cad078182190d だとAndroid以外でも通常UIになる

**Comment by tamaina** [comment]
1. shareに遷移してMisskeyが開かれる
2. 投稿後もし閉じるではなく、戻るやアプリ切り替えで元のアプリに戻ると
3. あとでMisskeyを開いたときに閉じるが表示されたままになり、Misskeyを再起動する必要がある
4. 共有後Misskeyを使い続けたい場合も再起動する必要があり不便

**Comment by tamaina** [comment]
> Android以外でも通常UI

Windowsかつ通常デッキUIの場合は不便？と思ったけどデッキって/以外ウィンドウで開くようになったんだっけ

**Comment by syuilo** [comment]
> * shareに遷移してMisskeyが開かれる
> * 投稿後もし閉じるではなく、戻るやアプリ切り替えで元のアプリに戻ると
> * あとでMisskeyを開いたときに閉じるが表示されたままになり、Misskeyを再起動する必要がある
> * 共有後Misskeyを使い続けたい場合も再起動する必要があり不便

ZenUIでも解決する手段はありそう

**Comment by tamaina** [comment]
閉じるの横にlocation.href = '/'するボタンを置くということかしら

**Comment by syuilo** [comment]
それが一番手っ取り早そう

**Comment by tamaina** [comment]
(デッキ以外で)通常UIになって困ったことが一度もないんだけどなんで:-1:なの

**Comment by acid-chicken** [comment]
変更すべきことが明らかならまだしもそうでない変更の直コミットが横行して欲しくない気持ち

**Comment by tamaina** [comment]
> Windowsかつ通常デッキUIの場合は不便？と思ったけどデッキって/以外ウィンドウで開くようになったんだっけ

ウィンドウじゃなくてzen uiで開かれるっぽくて相当アレ
