### ISSUE TITLE
アンテナが時間経過で無効化された際に再度有効化する手段がない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#10903]
## 💡 Summary

54630edb0f8cf91480e19f4e8e56c05158bc3a8f にてアンテナが7日間アクセスされていないと無効化されるようになっているが、一度無効化されると再度有効化する手順が存在しない(アンテナを再度作成するなどしかない)

## 🥰 Expected Behavior

api/antennas/notes などにアクセスした際に復活させるなどをして再度有効化させるなどする？

https://github.com/misskey-dev/misskey/blob/fb54c58a661bee64365b7ec0c52d456062aaa200/packages/backend/src/server/api/endpoints/antennas/notes.ts#L115-L117

あたりに
```typescript
isActive: true,
```
を入れる？

## 🤬 Actual Behavior

一度無効化されるとどうにもできない

## 📝 Steps to Reproduce

1. アンテナを作る
2. 見ずに7日放置する
3. 有効化する手順がない

## 📌 Environment

Misskey version: 13.12.2 (misskey.io)
PostgreSQL version: 
Redis version: 
Your OS: 
Your browser:

**Comment by ltlapy** [comment]
Related with #10476

**Comment by syuilo** [comment]
fixed
