### ISSUE TITLE
デッキモードかつ外部アプリなどから/以外に移動したときにデッキが表示されない（Zen UIになる）

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10905]
## 💡 Summary
デッキモードかつ外部アプリなどから/以外に移動したときにデッキが表示されない（Zen UIになる）

別の操作ができなくなる

## 🥰 Expected Behavior
デッキが表示される（メインルーターに表示されるべき内容はウィンドウで表示）

## 🤬 Actual Behavior
Zen UIになってしまう

## 📝 Steps to Reproduce

1. デッキモードにする
2. /以外のページを直接表示しようとする（例: https://p1.a9z.dev/@aqz )

## 📌 Environment

Misskey version: 13.13.0-beta.3

**Comment by tamaina** [comment]
05507a4beaf6340d42f806621aa685a73dbebeaf でそうなってるのか…どうして…

**Comment by syuilo** [comment]
/以外にアクセスしたときにDeck UIが表示されて困ることはあるけど(そのアクセスしたページの内容さえ見れればよいため)、Deck UIが表示されずに困るというのが理解できていない

**Comment by tamaina** [comment]
/以外にアクセスしたときにDeck UIが表示されなくて困ることはあるけど(PWAを再起動する必要があるため)、Deck UIが表示されて困るというのが理解できていない
