### ISSUE TITLE
ファイル名をminifyしたい

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10924]
現在こんな感じで、dynamic importなどしている個所でファイル名がそのまま含まれている(例: `"MkDateSeparatedList-4769c9b3.js","MkDateSeparatedList-f694761d.css"`)
![image](https://github.com/misskey-dev/misskey/assets/4439005/194f13e5-f3fd-4980-9927-dd7569664c66)

これらが大量に存在するのでバンドルサイズの増加に繋がるしランタイムで元のファイル名を持っておく必要はないと思われるため改善したい(例でいうと`"4769c9b3.js","f694761d.css"`だけで良さそう)
あとついでにjsとcssで別々にimportされているのが気になる

**Comment by syuilo** [comment]
viteの設定でいい感じにできないかしら

**Comment by syuilo** [comment]
viteというよりrollupの範疇かも

**Comment by syuilo** [comment]
これ？
https://rollupjs.org/configuration-options/#output-chunkfilenames

**Comment by syuilo** [comment]
> これ？ https://rollupjs.org/configuration-options/#output-chunkfilenames

これだったけどなぜか一部まだ変わってない

**Comment by syuilo** [comment]
一部っていうか半分くらい

**Comment by syuilo** [comment]
assetFileNames も変えないとダメだった

**Comment by acid-chicken** [comment]
初期設定だとハッシュが hex だから衝突しそうで怖い

**Comment by syuilo** [comment]
> 初期設定だとハッシュが hex だから衝突しそうで怖い

カスタム関数で生成しようとしたけどコンテンツ内容から独自のハッシュを算出する方法がよくわからず断念した
