### ISSUE TITLE
絵文字ピッカーでloveで検索しても🥰が出てこなくなった

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#10921]
## 💡 Summary
バンドル削減で辞書を消した？

## 🥰 Expected Behavior
今まではloveで検索すると🥰が出てきていた

## 🤬 Actual Behavior
loveで検索すると🥰が出てこない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: 13.13.0-beta.4 (develop)

**Comment by syuilo** [comment]
各絵文字のkeyword情報を消した
- サイズがデカい
- 英語固定なのが微妙
- 固有の絵文字名では検索できるから消しても極端には困らなそう

**Comment by EbiseLutica** [comment]
慣れの問題ではあるけど地味に使いづらさ出てきそう

**Comment by syuilo** [comment]
使いづらいのは確実

**Comment by CyberRex0** [comment]
これぐらいは消さなくても…

**Comment by EbiseLutica** [comment]
ロードにかかる時間より絵文字探すのにかかる時間のほうが増えてお釈迦になるくらいならここは消しちゃだめかも。

**Comment by syuilo** [comment]
dynamic importするのも考えたけど色々なところで同期的に参照されてるから困難だった

**Comment by syuilo** [comment]
- Misskeyの読み込みが少し速くなるメリットを優先する
- 絵文字名では検索できるからkeywordsは消す

**Comment by tamaina** [comment]
以前も(キャッシュがあれば)そこまで遅いと感じたことはなかった。利便性をとってほしい。

**Comment by CyberRex0** [comment]
ちなみに絵文字の辞書を残した場合、今の最大限軽量化した状態からどのぐらい元に戻る？

**Comment by tamaina** [comment]
(ちなみに: 今回の諸々の削減でトータル300kbぐらい減ったっぽい)  
(スクリプトサイズは転送速度だけでなくRAM消費についても絡みそうなことは覚えておきたいかも)

**Comment by syuilo** [comment]
キーワード部分だけdynamic importするような仕組みにすれば初回読み込みを高速化したまま多言語対応もできそう
けど初回検索時にちょっと待たないといけなくなりそう

**Comment by tamaina** [comment]
これすぐ直す気ないのか

**Comment by syuilo** [comment]
一応意図した変更

**Comment by tamaina** [comment]
めちゃくちゃ不便だから戻して
