### ISSUE TITLE
アドミン機能の監査

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/Misskey#10936]
## Summary

アドミン・モデレーション関係で権限を駆使した時ちゃんと残す

残しておきたい項目（全ての項目は監査ログが書かれた時点の物をそのまま保存する）
- 時間
- ユーザー
- 該当ユーザーの一番高い権限
- セッション情報（接続IPなど）
- セッションの認証方法（ウェブがアプリか、アプリならアプリ情報も）
- 操作（呼び出されたAPI）（カテゴリ・重要度表記もいいかも）
- 影響されたエンティティ
- （オプショナル、でも可能な限り）影響を受ける以前の状態
- 影響を受けた後の状態

できれば検索もほしいかも…？

**Comment by syuilo** [comment]
収集したいイベント募集中

**Comment by u1-liquid** [comment]
思いつく範囲でまとめると

- （本人以外の）ノートの削除
- （本人以外の）ファイルの削除
- （本人以外の）NSFWフラグ変更
- ロールの付与・剥奪（期限付きの場合その期限も）
- ユーザーの凍結・パスワードリセット・削除・モデレーションノートの変更
- ロールの作成・編集・削除
- カスタム絵文字の追加・編集・削除
- 連合サーバーの配送中止設定の変更
- 連合サーバーのブロック設定の変更
- お知らせの作成・編集・削除
- 広告の作成・編集・削除
- 通報の解決
- サーバーのmetaの変更（名前・説明文・規約など）

~~かな~~

まだあったので追記
- チャンネルのアーカイブ化
- （本人以外の）ページの削除←これはまだできないかも
- （本人以外の）Playの削除←これもまだできないかも
- （本人以外の）ギャラリーの削除
- （本人以外の）ギャラリーの閲覧注意フラグの変更
- サーバーブロックリストの変更
- 新規登録できるようにする・メアドを必須にするフラグの変更
- 予約ユーザー名リストの変更
- センシティブワードリストの変更
- カスタム絵文字のセンシティブ設定の変更

- 通報からのDMの閲覧←まだできない
