### ISSUE TITLE
misskey pageページでピン留めを解除することができない不具合

### ISSUE THREAD

**Issue by nan8ra** [syuilo/Misskey#10950]
## 💡 Summary

（ノート、note、ピン留めで検索してヒットしなかったのでissueさせていただきます。）
自分で作成したmisskeyページをピン留めした後、解除を押すと「パラメータエラー　リクエストパラメータに問題があります。通常これはバグですが、入力した文字数が多すぎる等の可能性もあります。」と表示され解除することができない。

## 🥰 Expected Behavior

ピン留めを解除と書かれているため正常に動作する場合は解除が行われるべきと考えます。

## 🤬 Actual Behavior

「パラメータエラー　リクエストパラメータに問題があります。通常これはバグですが、入力した文字数が多すぎる等の可能性もあります。」と表示され、リクエストは飛んでいるのか確認するため更新を押した場合でも解除されていない表示（ピン留めを解除）がされます。

## 📝 Steps to Reproduce

1.エラーとなっているパラメータの修正

## 📌 Environment

misskey.io/misskey.cfで確認済み

Misskey version:13.12.2
Your OS:Windows 10 Pro
Your browser:Firefox13.12.2

**Comment by chocolate-pie** [comment]
こうすれば直ったかも
```patch
diff --git a/packages/backend/src/server/api/endpoints/i/update.ts b/packages/backend/src/server/api/endpoints/i/update.ts
index d10f690a3..8f5e6177c 100644
--- a/packages/backend/src/server/api/endpoints/i/update.ts
+++ b/packages/backend/src/server/api/endpoints/i/update.ts
@@ -146,7 +146,7 @@ export const paramDef = {
 		alwaysMarkNsfw: { type: 'boolean' },
 		autoSensitive: { type: 'boolean' },
 		ffVisibility: { type: 'string', enum: ['public', 'followers', 'private'] },
-		pinnedPageId: { type: 'string', format: 'misskey:id' },
+		pinnedPageId: { type: 'string', format: 'misskey:id', nullable: true },
 		mutedWords: { type: 'array' },
 		mutedInstances: { type: 'array', items: {
 			type: 'string',

```

**Comment by nan8ra** [comment]
迅速なご対応ありがとうございます。
確認いたしました。本件はクローズさせていただきます。

**Comment by chocolate-pie** [comment]
いや、違います。この変更はコミットされていないので閉じないでください。
