### ISSUE TITLE
TypeError: JSON5.parse is not a function

### ISSUE THREAD

**Issue by CaffeeLake** [syuilo/Misskey#10955]
## 💡 Summary
When update to Misskey v13.13.0
Can't open Misskey with Server Error: `TypeError: JSON5.parse is not a function`

## 🥰 Expected Behavior

Display normal Misskey pages.

## 🤬 Actual Behavior

Can't open Misskey.
(Failed to load)

Server log
```
ERR  *	[api]	Internal error occurred in meta: JSON5.parse is not a function
{
  ep: 'meta',
  ps: { detail: true },
  e: {
    message: 'JSON5.parse is not a function',
    code: 'TypeError',
    stack: 'TypeError: JSON5.parse is not a function\n' +
      '    at file:///misskey/packages/backend/built/server/api/endpoints/meta.js:353:86\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:285:16)',
    id: ''
  }
}
TypeError: JSON5.parse is not a function
    at file:///misskey/packages/backend/built/server/api/endpoints/meta.js:353:86
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:285:16)
```

## 📝 Steps to Reproduce

1. Update to v13.13.0
2. Clear browser cache
3. Open Misskey

## 📌 Environment

Misskey version: 13.13.0
PostgreSQL version: 15.1.0
Redis version: 7.0.11
Your OS: Fedora 38
Your browser: Firefox 113

**Comment by tamaina** [comment]
Did you try pnpm install?

**Comment by CaffeeLake** [comment]
> Did you try pnpm install?

No, I'm using `misskey/misskey` Docker image on Kubernetes.

**Comment by syuilo** [comment]
他にも同様の症状が出ている人がいるけど、手元でpnpm clean-allした後にpnpm iして試したけどエラーは出ず謎

**Comment by syuilo** [comment]
テストも全部通ってるし謎

**Comment by CaffeeLake** [comment]
ServerでJSON5から変換するように移した際、
`import JSON5 from 'json5';`
から
`import * as JSON5 from 'json5';`
に変更されている部分は関係ないですか?

https://github.com/misskey-dev/misskey/commit/8f14b42e81ba891744cad19e4c6aa0d2d30f5e53#diff-bd46fc82f24b800cdef8d7d710094695cd5a56effe599cf048167b9040561e30R3

**Comment by syuilo** [comment]
関係ありますね

**Comment by syuilo** [comment]
なぜエラーになる環境とならない環境の二種類あるのかが謎

**Comment by syuilo** [comment]
正しい方は`import JSON5 from 'json5'`っぽい
https://www.npmjs.com/package/json5

**Comment by syuilo** [comment]
だとするとなぜテストや手元の環境ではエラーにならないのかしら

**Comment by tamaina** [comment]
> なぜ

```
  defaultLightTheme: null,
  defaultDarkTheme: null,
```

だからでは

**Comment by CyberRex0** [comment]
今は起きているのはjson5のインポートエラー
