### ISSUE TITLE
CHANGELOGに記載されているnode versionのtypo

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#10968]
## 💡 Summary

バグというより記載の不備だと思うのですが、
CHANGELOG.mdの13.12.0に記載されている `Node.js 18.6.0以上が必要になりました` は18.16.0のtypoではないでしょうか？

## 🥰 Expected Behavior

18.16.0

## 🤬 Actual Behavior

18.6.0 (typo?)

## 📝 Steps to Reproduce

1.
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  

### 🛰 Backend (for instance admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 18.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by EbiseLutica** [comment]
> 13.16.0のtypoではないでしょうか

13じゃなくて18かも

**Comment by nakkaa** [comment]
失礼しました。node versionは13ではなく18ですね。
summaryも修正しました。

**Comment by mappi-pr** [comment]
CHENGELOG修正するときに、これも・・・？
Related to 
- https://github.com/misskey-dev/misskey/issues/10817

あと、Misskey Hubの修正も必要そう

**Comment by samunohito** [comment]
#10979 にて修正されたようですので、closeします。
