### ISSUE TITLE
モバイル端末でスライドして再読み込みができない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#10964]
## 💡 Summary

モバイル端末のブラウザで上からスライドして再読み込みすることができない。

## 🥰 Expected Behavior

再読み込みができる

## 🤬 Actual Behavior

スライドしても何も起こらない

https://github.com/misskey-dev/misskey/assets/26585194/4f351878-85ca-479b-9ef0-b98f6c5d2260

## 📝 Steps to Reproduce

ページ上部から下にスライドする

### 💻 Frontend
* Model and OS of the device(s): Sony Xperia 5 IV (Android 13)
* Browser: Chrome 114.0.5735.57 (Official Build) （64 ビット）、Edge 113.0.1774.63 (公式ビルド) (64 ビット) 、Firefox 113.2.0 (Build #2015952075)
* Server URL: mi.cbrx.io

### 🛰 Backend (for instance admin)
* Installation Method or Hosting Service: manual
* Misskey: 13.13.1
* Node: 20.2.0
* PostgreSQL: 15.3
* Redis: 7.0.11
* OS and Architecture: Ubuntu 22.04.2 LTS

## Memo
タイムラインでのみ操作不可。その他画面やポップアップが前面にいる状態では可能。

**Comment by syuilo** [comment]
related https://github.com/misskey-dev/misskey/issues/9119

**Comment by syuilo** [comment]
仕様のためclose

**Comment by acid-chicken** [comment]
不便に感じる

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/issues/9119 が求められる

**Comment by acid-chicken** [comment]
ちょっと違うというか PWA 以外では以前のままで達成できていた

**Comment by syuilo** [comment]
ブラウザによるかも

**Comment by CyberRex0** [comment]
Environmentにも書いたけどほとんどのブラウザで使えなくなってる

**Comment by syuilo** [comment]
> Environmentにも書いたけどほとんどのブラウザで使えなくなってる

意図してる

**Comment by syuilo** [comment]
- bodyをスクロール可能にしないといけない縛りがめんどい
- ブラウザによって異なる挙動にしたくない
- TLのpull to refreshを実装した際に競合する

**Comment by syuilo** [comment]
当該ブラウザの方にIssueというか要望送ってみる手もありそう

**Comment by CyberRex0** [comment]
まだ実装する見通しがないなら戻してもいいんじゃない？

**Comment by syuilo** [comment]
いくつかの問題に対処するための変更だから戻すとなるとそれらの問題が復活するのがアレ

**Comment by syuilo** [comment]
とりあえず設定でメニューにリロードボタンを置いておくとリロードしやすくなると思う

**Comment by syuilo** [comment]
> まだ実装する見通しがないなら戻してもいいんじゃない？

一週間以内には実装できそうな気もする

**Comment by acid-chicken** [comment]
とりあえずワークアラウンドは `.xpACr{overscroll-behavior:none}` をカスタム CSS に適用でマシになる

**Comment by acid-chicken** [comment]
マシになる（pull to refresh できる時とできない時がある）
