### ISSUE TITLE
v13.13.0において Too many active WebGL contexts.のWarningが多数表示される。

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#10960]
## 💡 Summary

v13.13.0において、 `WARNING: Too many active WebGL contexts. Oldest context will be lost.` が複数表示される。

## 🥰 Expected Behavior

Warningが表示されない

## 🤬 Actual Behavior

特にデッキ表示において多数のWARNINGが表示される。

## 📝 Steps to Reproduce

1. v13.13.0のMisskeyを開く。
2. デベロッパーツールでWarningを確認する。

### 💻 Frontend
* Model and OS of the device(s):
  Windows 11 22H2
* Browser:
  Chrome 114.0.5735.90
* Server URL:
  misskey.bktsk.com / ikaskey.bktsk.comで確認

### 🛰 Backend (for instance admin)

* Installation Method or Hosting Service: docker compose
* Misskey: 13.13.0
* Node: 18.16.0
* PostgreSQL: 15.3
* Redis: 7.0.11
* OS and Architecture: CentOS Stream 9

**Comment by syuilo** [comment]
やっぱりavatarはblurhash使わない方が良いかも

**Comment by tamaina** [comment]
Warningが表示されても(今のところ)問題ないし、Avatarからblurhashを外しても表示されていたはず

**Comment by syuilo** [comment]
warning出すってことはパフォーマンス上の影響がありそうな気がした

**Comment by sasagar** [comment]
> warning出すってことはパフォーマンス上の影響がありそうな気がした

自分もその認識でIssue上げました。
再描画の頻度が高くなることで他のウインドウに影響を与えていそうです。
（v13.13.0のクライアントを表示させているとYouTubeの動画が止まる頻度が激増したりしたので）

**Comment by tamaina** [comment]
パフォーマンスの話で言えばblurhash自体が重たい（のでAvatarは平均色塗りつぶしだけのモードを用意して描画するのがいいかも）

Warningが出るのはWorkerのOffscreenCanvasの破棄がうまく行ってない  
(もしかしたらバグやらブラウザが非対応かで、メインスレッドでHTMLCanvasElementに描画しているかもしれない、がそれもまた破棄がうまくできていないということではある)

**Comment by acid-chicken** [comment]
buraha をデーモンっぽく立ち上げて一定数の WebGL コンテキストしか理論上立たないようにしないとダメなんかな

**Comment by sasagar** [comment]
なんだかざっと調べた感じ、上限数がWebkit系では15らしく、Mozilla系では100以上はあるという話なので、
ブラウザ依存で起こる可能性は十分ありそうでした。

ただ、現状Chromeユーザーの比率が多いと思われるので、ある程度対策した状態にした方が良さそうだなぁと思ったところでした。

**Comment by tamaina** [comment]
Blurhash周りについては #10782 参照

**Comment by sasagar** [comment]
関連するかはわからないのですが、動きのあるGifをアイコンにしているユーザーから「（自分の）アイコンが表示されるまでが遅い」という話がありました。
PCブラウザではあまり再現性が無く、iPhoneでは再現しました。何かのヒントになれば...。

**Comment by tamaina** [comment]
@acid-chicken Canvasに直接描画できない時点でいろいろ破綻してると思うの

burahaを2Dコンテキストで頑張れないの

**Comment by acid-chicken** [comment]
> @acid-chicken Canvasに直接描画できない時点でいろいろ破綻してると思うの
> 
> burahaを2Dコンテキストで頑張れないの

ハードウェアアクセラレーションをかけたいので本末転倒では

https://github.com/misskey-dev/misskey/blob/8ccf954065a4930a8b2577b79ae3a87d5dd05449/packages/frontend/src/workers/draw-blurhash.ts#L11

どうせ 64 以上行かないんだったら 64x64 固定で OffscreenCanvas シングルトンでいい説ない？

**Comment by tamaina** [comment]
> iPhone

SafariがOffscreenCanvasのWebGL2に対応していないためメインスレッドで頑張ってるからだと思われる

**Comment by tamaina** [comment]
Canvas使いまわそうぜってことか()

**Comment by acid-chicken** [comment]
> Canvas使いまわそうぜってことか()

サイズが変わらないならコンテキストは使い回されるはず
