### ISSUE TITLE
WebSocketのPing/Pongをプロトコル制御フレームの物で判別する

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/Misskey#10969]
## What

https://developer.mozilla.org/ja/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#ping_%E3%81%A8_pong_websockets_%E3%81%AE%E9%BC%93%E5%8B%95

>ハンドシェイク後の任意の時点で、クライアントまたはサーバーのどちらかが、相手に ping を送信することを選択できます。 ping が受信されると、受信者はできるだけ早く pong を返さなければなりません。 これを使用して、たとえばクライアントがまだ接続されていることを確認できます。
>
>ping や pong は単なる通常のフレームですが、制御フレームです。ping のオペコードは 0x9、pong のオペコードは 0xA です。ping を取得したら、ping と同じペイロードデータを持つ pong を送ります（ping と pong の場合、最大ペイロード長は 125 です）。ping を送信することなく pong を取得することもできます。その場合はこれを無視してください。

## 参考
https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by syuilo** [comment]
これだとタブが表示されてなくてもコネクション生きてる判定になりそう

**Comment by syuilo** [comment]
タブが非表示になってしばらくたったらコネクション切るコードをクライアント側に入れればいいか

**Comment by EbiseLutica** [comment]
それ普通に不便そう　裏に回しててﾍﾟｺってなったら見に行く　ができなくなる

**Comment by syuilo** [comment]
なるほど

**Comment by CyberRex0** [comment]
これどうにかならない？

**Comment by syuilo** [comment]
どれ？

**Comment by CyberRex0** [comment]
大規模でシビアなサーバではタイムアウト短くして、小規模のところでは余裕あるから比較的長めに、とかできるようにconfig.ymlで変えられるようにすればいいのではと思ったり

**Comment by syuilo** [comment]
それは何のため？

**Comment by CyberRex0** [comment]
Misskey開いて裏に回しといて、通知音が鳴ってから見に行く人が多いから
プッシュ通知は目障りになる場合がありそのような方法を取る人もいる(自分もそう)

**Comment by EbiseLutica** [comment]
6182a1cb2c80cce573a17193e9309fbbbce3b08c では

> タブが非表示になってしばらくたったらコネクション切るコードをクライアント側に入れればいいか

はやってないと思うから多分現状のdevelopで問題ないと思うんだけど、認識違うかしら

**Comment by syuilo** [comment]
待って、現状何が問題になっているのか教えて欲しい

**Comment by EbiseLutica** [comment]
@syuilo 多分

> タブが非表示になってしばらくたったらコネクション切るコードをクライアント側に入れればいいか

って言ったあとにやるかやらないかのどっちを選択したか不明瞭なままissueが閉じられたので、最終的にどう実装されたのかわからず混乱している人がいる

**Comment by syuilo** [comment]
ほむん
コミット見てもらえればわかるように現状 WebSocketのPing/Pongをプロトコル制御フレームの物で判別する しかやってない

**Comment by CyberRex0** [comment]
バックグラウンドに回ったからって自動切断とかはしてないってこと？

**Comment by syuilo** [comment]
してない

**Comment by tamaina** [comment]
Safariはタブやウィンドウが表示されてないと積極的にWebSocketを切りに行く感じがする

**Comment by EbiseLutica** [comment]
まあSafariだし（諦め）
