### ISSUE TITLE
2要素認証リカバリーコードの実装

### ISSUE THREAD

**Issue by daima3629** [syuilo/Misskey#10970]
## Summary
2要素認証のリカバリーコードを取得することができず、認証器を紛失したらアカウントから締め出されてしまうためリカバリーコードの実装をしたい
DBに新たなカラムを追加しないといけないのでちょっとコストがかかりますが絶対にあったほうが良いと思うので近々PR出します

**Comment by tamaina** [comment]
Duplicate of #3566

**Comment by daima3629** [comment]
🙏
