### ISSUE TITLE
設定の閲覧注意メディアの表示・非表示をAPIから取得できるようにしたい

### ISSUE THREAD

**Issue by taka84makiba** [syuilo/Misskey#10985]
## Summary
タイトルの通りです。

設定画面の`クライアント設定`>`全般`>`閲覧注意`項目の内容がAPIで取得できると課題を満たせると考えています。

<img src="https://github.com/misskey-dev/misskey/assets/50735539/98f3cfef-4221-4758-b45c-fb739fc72214" width=500>

もし自分の詰めが甘く取得できるEndpoinr等があればご教示ください.

##  Background

Misskey APIでiOSクライアントアプリを開発しています。
センシティブメディアの閲覧の可否はアプリ内で設定できるようにしていたのですが。AppStoreのガイドラインが改定されたのか、その設定はアプリ内ではなくAPIを提供しているサービスを通じて行わなければならないようです。。。。

**Comment by syuilo** [comment]
当該設定はデバイス固有の設定なので、APIから取得できるようにするのは困難かも

**Comment by taka84makiba** [comment]
おぉ。。。そうなんですね 😢 

ご対応いただきありがとうございます 🙇
