### ISSUE TITLE
たくさんのユーザーが一斉に自分のアカウント情報を見るとサーバーが過負荷でアクセス不能になる

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10998]
## 💡 Summary
設定→その他→アカウント情報の処理がかなり重い
これをTLで見せ合う感じになると一斉にアクセスが殺到してサーバーが一時アクセス不能になる

できればジョブキューのような仕組みにできないか

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: 13.13.1
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
廃止したい

**Comment by syuilo** [comment]
重いのはDBなので、ジョブキューにしたところで変わらない

**Comment by fruitriin** [comment]
えっ、機能としては面白かったのに残念

**Comment by EbiseLutica** [comment]
#8442 を使ったリワークができないかなーって思ってる
