### ISSUE TITLE
カスタム絵文字登録の際にファイル名が絵文字名として採用されなくなった

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#10997]
## 💡 Summary
ファイルを選択しても絵文字名が空
13.12以前はファイル名から採用→できなければファイルの内部IDだったような思う

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:Misskey 13.13.1
PostgreSQL version:
Redis version:
Your OS:
Your browser:

**Comment by tamaina** [comment]
これ治った？

**Comment by syuilo** [comment]
直った
