### ISSUE TITLE
Client: 絵文字のみで投稿した際に絵文字を自動で $[x2 ] に内包する設定を追加

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10991]
## Summary

Discordと似た機能を使えるようにする設定をオプションで追加（大きくなる絵文字の個数制限・改行がある場合は適用しないなどを適切に設定）

**Comment by syuilo** [comment]
これと実現したいことは同じそう
https://github.com/misskey-dev/misskey/issues/5014

**Comment by syuilo** [comment]
dup of https://github.com/misskey-dev/misskey/issues/5014
