### ISSUE TITLE
/shareのurlパラメータに渡した内容が完全にデコードされてしまうため、日本語を含むURLがMFMに正しく認識されない

### ISSUE THREAD

**Issue by alpaca-honke** [syuilo/Misskey#11002]
## 💡 Summary

/shareに渡すパラメータのうち、urlに渡した値のURIエンコードが全てデコードされてしまうため、URLに日本語などが含まれていた場合それ以降がURLとして認識されないため、すべて正しくURLとして認識されるようにしていただきたい

## 🥰 Expected Behavior

ふたつのオプションが考えられます
①urlパラメータに渡された値のうち、日本語部分などのみデコードを行わないことで、MFMに認識されるようになる
②MFMがURLを認識する際に日本語などを含んでいても認識されるようになる

## 🤬 Actual Behavior

/shareに渡すurlパラメータに日本語などが含まれると、投稿する際にそれ以降がURLとして認識されない

## 📝 Steps to Reproduce

1. /shareに渡すurlパラメータに、1度だけURIエンコードをかけた、日本語を含むURL（例えば、 https://github.com/alpaca-honke/twishare-to-misskey/wiki/よくある質問 ）を渡す
2. 投稿フォームに日本語にデコードされたURLが入り、日本語部分以降がURLとして認識されない

### 💻 Frontend
* Model and OS of the device(s):Redme Note    10 JE, MiUI Global 14.0.12 (Based on Android 13 TKQ1.220905.001) 
* Browser: Kiwi Browser 112.0.5615.137
  
* Server URL: ①misskey.io ②misskey.noellabo.jp
  
* Misskey:
  ①13.12.2 ②13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 18.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture: 

## 備考
当然ではありますが、二重エンコードすれば正常に動作することを確認しています。
当分は二重エンコードしてtextの末尾に含めることで（修正後も）対応可能かと考えてはいます。

**Comment by acid-chicken** [comment]
挙動としては正しそう（つまり二重エンコードすべきよう）に思う

**Comment by tamaina** [comment]
日本語部分がURLであるかどうかをMisskey側では判断できないし…

**Comment by acid-chicken** [comment]
URL パラメータって URLSearchParams そのもののことではなく `url` パラメーターの話か

https://github.com/misskey-dev/misskey/blob/f5dfb64a528d705970d606d3f84ec9de2ef55d84/packages/frontend/src/pages/share.vue#L48

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/misskey/blob/f5dfb64a528d705970d606d3f84ec9de2ef55d84/packages/frontend/src/pages/share.vue#L63

ここを `<${url}>` とすれば直る

**Comment by tamaina** [comment]
あ〜

**Comment by esperecyan** [comment]
`<` `>` で囲むようにしても、URLに `>` が含まれている場合はうまくいきません。
https://misskey.io/share?url=https%3A%2F%2Fexample.com%2F%3C%E6%97%A5%E6%9C%AC%E8%AA%9E%3E
![](https://github.com/misskey-dev/misskey/assets/3625160/91711784-0a16-4a01-9b16-3a27cd9c636f)

URLパーサーにかけた結果を本文に入れるのが良いのではないかと思います。
```ts
new URL('https://example.com/<日本語>').href
// ※URLとして取り扱えない文字列に対しては例外が出るので対処が必要
```
→ `https://example.com/%3C%E6%97%A5%E6%9C%AC%E8%AA%9E%3E`
![](https://github.com/misskey-dev/misskey/assets/3625160/52344600-e83c-4c81-b0d8-2f7d8795e747)

**Comment by Sayamame-beans** [comment]
> `<` `>` で囲むようにしても、URLに `>` が含まれている場合はうまくいきません。

こちらの現象はDiscord等でも同様のようです。
MFMで使われる`]`などについても同様なので、気にしなくて良いのではないでしょうか…?

**Comment by anatawa12** [comment]
MFM層でURLに`>`がそのまま含まれてる場合に対応しないのは問題ないと思いますが、`?url=`に関しては対応したほうが良さそうに思います。URL Standardのparserはvalidation errorは出しますがパースは続行され`>`がURLEncodeされるのが定義されているため
