### ISSUE TITLE
iOSを最新版にしないと読み込み時エラーになってしまう（らしい）

### ISSUE THREAD

**Issue by yuriha-chan** [syuilo/Misskey#11016]
## 💡 Summary
iOSが最新版でないと、OffscreenCanvasのReferenceErrorがエラー画面として表示されてしまう（らしい）。

## 🥰 Expected Behavior
エラーが表示されず、ホーム画面が表示される

## 🤬 Actual Behavior

エラー画面が表示される

## 📝 Steps to Reproduce
1. iOSを更新しない
2. Misskeyのトップ画面にアクセスする

### 💻 Frontend
Misskey 13.13.2

**Comment by tamaina** [comment]
iOSの更新をお願いします:pray:
