### ISSUE TITLE
デッキUIでチャンネルカラムを追加・編集するとき、リストにフォローしたチャンネルが何も表示されない

### ISSUE THREAD

**Issue by karakufire** [syuilo/Misskey#11023]
## 💡 Summary
デッキUIにて、チャンネルのカラムを追加・編集するとき、「チャンネルを選択」で表示されるドロップダウンリストに何も表示されない。

## 🥰 Expected Behavior
フォローしているチャンネルが全て「チャンネルを選択」のドロップダウンリストに表示される。

## 🤬 Actual Behavior
フォローしているチャンネルが全て「チャンネルを選択」のドロップダウンリストに表示されず、「なし」の選択不可項目だけがある。

## 📝 Steps to Reproduce

1. 何らかのチャンネルをフォローする
2. デッキUIを表示し、チャンネルカラムを追加、あるいはすでに追加されたチャンネルカラムの上部タブメニューから「チャンネルを選択」を押下
3. 「チャンネルを選択」ダイアログのドロップダウンリストを押下し、ドロップダウンリストの内容を表示する。

### 💻 Frontend
* Model and OS of the device(s):
  Windows 10 Pro 22H2
* Browser:
  Mozilla Firefox 114.0.1 64bit
  Google Chrome 114.0.5735.134 64bit
  Microsoft Edge 114.0.1823.51 64bit
* Server URL:
  misskey.io
  misskey.design
* Misskey:
  v13.13.2(misskey.io)
  v13.12.2-md.2(misskey.dev)

**Comment by karakufire** [comment]
追記: iOS用misskeyクライアントMissRiricaではデッキUIでのチャンネルカラムのチャンネル選択ダイアログにてフォローしているチャンネルの一覧が表示された。

**Comment by syuilo** [comment]
フォローしたチャンネルではなく、お気に入りにしたチャンネルが選択肢に表示されます

**Comment by karakufire** [comment]
> フォローしたチャンネルではなく、お気に入りにしたチャンネルが選択肢に表示されます

返答ありがとうございます。
仕様変更かと思ってリリースログの確認もしていましたが、チャンネルのお気に入り機能が追加された13.11.0以降のいかなるリリースログにおいてもその旨が記載されてないのでバグかどうかが判然としませんでした。
