### ISSUE TITLE
「おかえりなさい」のtoastのユーザー名をMFM対応にしたい

### ISSUE THREAD

**Issue by sasagar** [syuilo/Misskey#11022]
## Summary

ログイン時などに表示される「おかえりなさい」のメッセージについて、ユーザー名がMFMになっていない。  
絵文字を使っている場合などに長くなりすぎることを含めて、実際の表示と異なる場合があるので直感的では無いのでは？ということから提案します。

**Comment by sasagar** [comment]
自力で対応してみようと思ったモノの、どこに何をすれば良いのかわからなくなってしまったので、issue化しました。

**Comment by futchitwo** [comment]
- Duplicate of #8321
