### ISSUE TITLE
sparkle内にリンクを入れるとクリック不能になる

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#11021]
## 💡 Summary
sparkleで装飾したリンクがクリック不能になっている
（一応下に表示されるプレビュー部分で遷移可能ではある）

おそらくsparkleの`.root`に`pointer-events: none;`が指定されていてその配下のリンクには`pointer-events`の指定がないため反応しない？

## 🥰 Expected Behavior
リンクをクリック・タップした際にリンク先に遷移できる

## 🤬 Actual Behavior
sparkle以下のリンクはクリックしても何も起きない

## 📝 Steps to Reproduce

1. 次のMFMを入力
    - `$[sparkle https://example.com]`
2. リンク部分をクリック

### 💻 Frontend
* Model and OS of the device(s): Windows 11 22H2(Build 22621.1702)
  

* Browser: Chrome 114.0.5735.110
  

* Server URL: misskey.io
  

* Misskey: 13.13.2

**Comment by tai-cha** [comment]
仕様な気もしてきた、どうなんだろう

**Comment by mappi-pr** [comment]
@taichanNE30 
> おそらくsparkleの.rootにpointer-events: none;が指定されていてその配下のリンクにはpointer-eventsの指定がないため反応しない？

これを削除しただけだと、キラキラしてるsvgのオブジェクトが前面に出てきてaタグのクリッカブルなところを覆ってしまっているので、クリックができませんでした。。。

例えば、キラキラが文字よりも背面に潜り込んでもらったりするとかでクリックはできそうなのですが、
キラキラが潜り込んじゃうとこんな感じ↓になっちゃうなぁと思いました。
（あとレイヤーの階層を変えちゃうと他のMFMと組み合わせたときの挙動がかわるかも？）

■sparkleのsvgを暫定的に`z-index : -10`にして文字の背面に潜り込ませたイメージ 
<img width="459" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/f445b8e4-5893-4ef1-91ae-c1126f0a3377">

**Comment by mappi-pr** [comment]
> （あとレイヤーの階層を変えちゃうと他のMFMと組み合わせたときの挙動がかわるかも？）

bgと組み合わせた時の見た目が変わることを確認してます。
■現行（クリックできないけどsparkleが前に来る）
<img width="155" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/49e632b5-0712-4ebe-b760-2aff53bb7822">

■暫定（クリックできるけどsparkleが後ろに潜る）
<img width="194" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/a118e37f-d72e-4b79-8b8e-7d208bfb8239">

**Comment by mappi-pr** [comment]
.rootじゃなくて、svg要素を直接pointer-events: none;としたら、
sparkle貫通してクリックできそうでした。
![image](https://github.com/misskey-dev/misskey/assets/75538777/1299b18b-9d79-4278-af29-ad055e87cae3)

**Comment by tai-cha** [comment]
🙏
