### ISSUE TITLE
Windows Helloを二段階認証のセキュリティキーとして登録することができない

### ISSUE THREAD

**Issue by momizi06** [syuilo/Misskey#11040]
## 💡 Summary

MIsskeyの設定→基本設定→セキュリティのセキュリティキー・パスキーで、Windows Helloの指紋認証を登録しようとするとエラーが表示され、登録することができない。

## 🥰 Expected Behavior

正常に登録され、ログイン時に二段階認証の要素として利用することができる。

## 🤬 Actual Behavior

画像のように登録時にエラーが表示され、登録することができない。
![image](https://github.com/misskey-dev/misskey/assets/63577263/329e08ba-4a4f-45f7-86ea-71af7f359456)

エラー情報を以下に示す。
```
Endpoint: i/2fa/key-done
Info: {"e":{"message":"unsupported fmt","code":"Error","id":"6ebb78b2-303f-472a-80bc-e6f2969e5fe6"}}
Date: 2023-06-22T06:00:18.501Z
```

## 📝 Steps to Reproduce

1. Misskeyのクライアントの設定画面を開き、そこから二段階認証のセキュリティキーの登録画面まで進める。
2. Windows側からWindows Helloを利用したセットアップを求められるので、指紋リーダに指をあてる。
![image](https://github.com/misskey-dev/misskey/assets/63577263/f6abcca9-e161-4cf0-963a-d925e367ea71)
3. エラーが発生する。

### 💻 Frontend
* Model and OS of the device(s): HP Pavilion 15-eg2029tu, Windows 11 Home 22H2 (22621.1848)
  
* Browser: Ablaze Floorp 10.14.0, Chrome 114.0.5735.134
  
* Server URL: misskey.io, misskey.04.si
  
* Misskey: 13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 18.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by u1-liquid** [comment]
related: #8691

**Comment by Ryosuke-Asano** [comment]
Floorp は 現在内部的には Firefox 102（ESR） に基づいています。近いうちに ESR のアップグレードを行うので、完全に対応する必要はありませんが、Firefox 115 または、Floorp 11.0.0 (https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp.en-US.win64.installer.exe) でテストしてください。

**Comment by syuilo** [comment]
指紋リーダ is 何

**Comment by syuilo** [comment]
たぶん解決
