### ISSUE TITLE
チャンネルを持つアカウントを削除するとモデレーターからもチャンネルの設定に入るボタンが消える

### ISSUE THREAD

**Issue by chikage8640** [syuilo/Misskey#11048]
## 💡 Summary

チャンネルを持つアカウントを削除すると、チャンネルの設定画面に入るボタンがモデレーターにも表示されなくなる。

## 🥰 Expected Behavior

チャンネルを持つアカウントが消えてもチャンネルの設定に入るボタンがモデレーターには表示される。

## 🤬 Actual Behavior

チャンネルを持つアカウントが消えると、チャンネルの設定のボタンがモデレーターからも消える。

## 📝 Steps to Reproduce

1.チャンネルAを一般ユーザーBが作成
2.一般ユーザーBがアカウントを削除する
3.チャンネルAの設定にはモデレーターCすらアクセスできなくなる。
(4.直接 https://mi.example.com/channels/[channel_id]/edit にアクセスすると表示はできる。)

### 💻 Frontend
* Model and OS of the device(s): Windows 11 Pro 22H2
  
* Browser: Firefox 114.0.2 (x64)
  
* Server URL: https://yurisskey.yubarira.net
  
* Misskey: 13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Misskey install shell script, ConoHa VPS
* Misskey: 13.13.2
* Node: 18.16.0
* PostgreSQL: 15.2
* Redis: 7.0.11
* OS and Architecture: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-73-generic x86_64)

**Comment by Sayamame-beans** [comment]
duplicate of #12023
