### ISSUE TITLE
Ai Mascot widget isn't transparent, no more

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#11057]
## 💡 Summary

Ai Mascot used to have transparent background or same colour of widget's bacground. Even if "transparent" option was flagged or not.

## 🥰 Expected Behavior

as user I'd like to see Ai Mascot seamless in the widgets column

## 🤬 Actual Behavior

![immagine](https://github.com/misskey-dev/misskey/assets/92727/8af07269-9103-45c5-8280-11762e74df0b)

## 📝 Steps to Reproduce

1. install misskey
2. put mascot widget
3. check transparent option

### 💻 Frontend
* Model and OS of the device(s): Debian
* Browser: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0
* Misskey: 13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Docker
* Misskey: 13.13.2

**Comment by tassoman** [comment]
note: yellow is my browser's setting for default background colour.  
Useful to understand when `<body>` tag is missing background color instead of white.

**Comment by kakkokari-gtyih** [comment]
Related to [misskey-dev/misskey-hub-next#45](https://github.com/misskey-dev/misskey-hub-next/issues/45)

**Comment by tassoman** [comment]
I managed to fix for both Firefox and Chromium in my pull-request.
Maybe the class `class="mkw-aichan"` is missing some scss parameters for dark/light themes?  
There's no css class definition, inside the vue component.
