### ISSUE TITLE
パスキーのサポート

### ISSUE THREAD

**Issue by u1-liquid** [syuilo/Misskey#11054]
## Summary

現在一部媒体でしか利用できないセキュリティキー機能を作り直してパスキーに対応させる

related: #8691
related: #9344
related: #9249
related: #11040

参考: https://ja.wikipedia.org/wiki/%E3%83%91%E3%82%B9%E3%82%AD%E3%83%BC

**Comment by tamaina** [comment]
Duplicate of #9249

**Comment by tamaina** [comment]
ちがう

**Comment by tamaina** [comment]
related to #9344

**Comment by syuilo** [comment]
やるか

**Comment by u1-liquid** [comment]
MisskeyIO/misskey#149 をマージするつもりなら MisskeyIO/misskey#134 も一部（か全部）入れたほうがいいと思う
（エラーハンドリングとEntityService周りを結構変えたので）

**Comment by syuilo** [comment]
見てみたらどっちもdiffが多くて大変そうだった

**Comment by syuilo** [comment]
実装された方に報奨金を進呈

**Comment by syuilo** [comment]
やる人いない？

**Comment by syuilo** [comment]
やるか

**Comment by syuilo** [comment]
Chromeはパスキー対応してないのかしら

**Comment by CyberRex0** [comment]
してる(のでioで使えている)

**Comment by syuilo** [comment]
対応してないって出る

**Comment by CyberRex0** [comment]
Bluetoothやパスキー対応の認証装置がないとそうなる可能性はある

**Comment by syuilo** [comment]
かなしいはなし
