### ISSUE TITLE
AndroidのFirefoxでインストールしたPWAでノートの投稿時にIMEが正しく表示されない

### ISSUE THREAD

**Issue by goru** [syuilo/Misskey#11063]
## 💡 Summary

AndroidのFirefoxでインストールしたPWAでノートの投稿時にIMEが正しく表示されない
PWAでなくFirefoxアプリ上でノートの投稿ボタンを押したときや
ChromeやChromeからPWAをインストールした場合は問題ありませんでした
(Firefox側の問題の可能性もあるかなという気もします)

## 🥰 Expected Behavior

ノートの投稿ボタンを押した時に投稿画面と同時にIMEが表示されること

## 🤬 Actual Behavior

一瞬表示されて閉じられるような動作をしているように見えます

## 📝 Steps to Reproduce

1. FirefoxアプリでMisskeyを開く
2. Firefoxのメニューを表示してインストールを選択
3. インストールされたPWAに切り替えてノートの投稿ボタンを押す

### 💻 Frontend
* Model and OS of the device(s):
  
  Pixel 6a (Android 13)
* Browser:
  
  Firefox 114.2.0
* IME:
  Gboard 13.1.07.536370540-release-arm64-v8a
* Server URL:
  misskey.io
* Misskey:
  13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 18.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by saschanaz** [comment]
IMEの情報も提供できますか？SwiftKeyとSamsungキーボードでは問題ありませんでした

**Comment by goru** [comment]
すみません大事な情報を忘れていました
Gboard 13.1.07.536370540-release-arm64-v8a でした

**Comment by u1-liquid** [comment]
Android 13
Firefox Beta 115.0b9
GBoard 13.1.08.536370540-beta-arm64-v8a
こちらの環境では再現できませんでした

**Comment by goru** [comment]
おふたりとも確認ありがとうございます
Misskey側の問題ではなく端末依存ですかね…

**Comment by goru** [comment]
他に同じ問題に遭遇している人はいなさそうなので閉じてしまいます

**Comment by haborite** [comment]
同様の症状が継続的に見られているのでコメントします。
Gboardではなくflickを用いた場合でも全く同じ症状が現れました。
goruさん同様、私もPixelシリーズ（Pixel 4, Pixel 4a）× Firefox の組み合わせです。

📌 Environment
💻 Frontend
- Model and OS of the device(s): Pixel 4 & Pixel 4a (Android 13)
- Browser: Firefox 128.0.2
- IME: 
  - Gboard 14.3.10.x-release-arm64-v8a
  - flick 2.20.2677.x
- Server URL: misskey.io, misskey.noellabo.jp
- Misskey: 2024.3.1

**Comment by saschanaz** [comment]
コメントあいがとうございます。私のGalaxy S22 Ultraでは確認できませんでしたが、複数のPixelデバイスからの不具合報告があったため、一応Firefox側にも報告しておきました。

https://bugzilla.mozilla.org/show_bug.cgi?id=1912649
