### ISSUE TITLE
Project built failed

### ISSUE THREAD

**Issue by hatsuyuki2333** [syuilo/Misskey#11062]
## 💡 Summary

I'm trying to create a new instance.After normally set up DB and redis ,I use `NODE_ENV= production yarn build`,then it threw out this error.   
I **do not have any experience** before.

## 🥰 Expected Behavior

Everything goes well...then I can get a new instance.

## 🤬 Actual Behavior

I stuck at it for over 5 times.
Here is the log.
```
misskey@yobian:~/workspace/misskey$ NODE_ENV=production yarn build
yarn run v1.22.19
$ pnpm build-pre && pnpm -r build && pnpm gulp

> misskey@13.13.2 build-pre /home/misskey/workspace/misskey
> node ./scripts/build-pre.js

Scope: 4 of 5 workspace projects
packages/misskey-js build$ tsc
│ src/streaming.ts(1,30): error TS2307: Cannot find module 'eventemi…
│ src/streaming.ts(2,35): error TS2307: Cannot find module 'reconnec…
│ src/streaming.ts(122,8): error TS2339: Property 'emit' does not ex…
│ src/streaming.ts(137,9): error TS2339: Property 'emit' does not ex…
│ src/streaming.ts(162,7): error TS2339: Property 'emit' does not ex…
│ src/streaming.ts(166,9): error TS2339: Property 'emit' does not ex…
│ src/streaming.ts(226,15): error TS2339: Property 'on' does not exi…
│ src/streaming.ts(270,15): error TS2339: Property 'off' does not ex…
│ src/streaming.ts(326,8): error TS2339: Property 'removeAllListener…
│ src/streaming.ts(356,8): error TS2339: Property 'removeAllListener…
└─ Failed in 24s at /home/misskey/workspace/misskey/packages/misskey-js
/home/misskey/workspace/misskey/packages/misskey-js:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  misskey-js@0.0.16 build: `tsc`
Exit status 2
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## 📝 Steps to Reproduce

1.git clone -b develop https://github.com/misskey-dev/misskey.git
2.cd misskey && yarn
3.NODE_ENV=production yarn build

## 📌 Environment

    
misskey v13.13.2
Debian 12(sid) ARM64
Nodejs v18.13.0
NPM v9.2.0
Yarn v1.22.19
pnpm v8.6.5

**Comment by chocolate-pie** [comment]
> WARN   Local package.json exists, but node_modules missing, did you mean to install?
error Command failed with exit code 1.

Try to run command as follows:
```bash
cd ~/workspace/misskey
pnpm install
```

**Comment by saschanaz** [comment]
Indeed, `misskey@yobian:~/workspace/misskey$ NODE_ENV=production yarn build` this looks wrong, you should run pnpm instead.

**Comment by hatsuyuki2333** [comment]
pnpm process always killed on my device.
i will try it on github codespace to see if it goes wrong again.

**Comment by hatsuyuki2333** [comment]
pnpm killed again and again
what's the recommended spec? I can't allocate it more than 4g ram.

**Comment by hatsuyuki2333** [comment]
> pnpm killed again and again what's the recommended spec? I can't allocate it more than 4g ram.

there isn't any problems when using yarn.
sorry for my English.

**Comment by tamaina** [comment]
Please try 

```
pnpm --workspace-concurrency 1 build
```

**Comment by hatsuyuki2333** [comment]
huh? i have not  successfully run `pnpm install`  yet.

**Comment by tamaina** [comment]
Are you unable to pnpm install? Network speed may be an issue.

**Comment by tamaina** [comment]
What does "killed" mean? Please show me the log.

**Comment by hatsuyuki2333** [comment]
yes. 
As i said, the pnpm process always killed. I think network is fine.

**Comment by hatsuyuki2333** [comment]
```
$ pnpm install --frozen-lockfile
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2505
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2505, reused 2427, downloaded 0, added 0, done
node_modules/.pnpm/@tensorflow+tfjs-node@4.4.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjnode_modules/.pnpm/@tensorflow+tfjs-node@4.4.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, done in 931ms
Killed
```

**Comment by tamaina** [comment]
Please try `NODE_OPTIONS=--max-old-space-size=4096 pnpm install --frozen-lockfile`

**Comment by tamaina** [comment]
> I can't allocate it more than 4g ram.

Can you make swap?

**Comment by hatsuyuki2333** [comment]
> Please try `NODE_OPTIONS=--max-old-space-size=4096 pnpm install --frozen-lockfile`

It didn't work.
I tried 3072 and 1024, but still so.

**Comment by hatsuyuki2333** [comment]
> > I can't allocate it more than 4g ram.
> 
> Can you make swap?

No. I'm using docker and I can't contact the owner for a privileged container.

**Comment by yuriha-chan** [comment]
I run the following command on arm64 (1vCPU, 4GB RAM) machine on GCP and It run successfully without an error.
```sh
sudo apt-get install git nodejs npm
sudo npm install -g corepack
sudo corepack enable
git clone -b develop https://github.com/misskey-dev/misskey.git
cd misskey
pnpm install --frozen-lockfile
```
```
npm --version: 9.2.0
node --version: 18.13.0
corepack --version: 0.19.0
uname -a: Linux #1 SMP Debian 6.1.27-1 (2023-05-08) aarch64 GNU/Linux
lscpu: Model Name: Neoverse-N1
```

**Comment by hatsuyuki2333** [comment]
My device is a little special....and old, Wingtech Redmi 2 (MSM8916, 2GB RAM).
My x86 computer has 4GB RAM, I'm trying to run `pnpm install` on it, then move data to my device.
Sounds unrealistic, doesn't it?But that's the only way I can think of.

**Comment by hatsuyuki2333** [comment]
> My device is a little special....and old, Wingtech Redmi 2 (MSM8916, 2GB RAM). My x86 computer has 4GB RAM, I'm trying to run `pnpm install` on it, then move data to my device. Sounds unrealistic, doesn't it?But that's the only way I can think of.

 I have faced the same problem on it so I tried this way.

**Comment by yuriha-chan** [comment]
This project includes building of native node module as dependencies (e.g. re2), so it seems that cross-compiling is needed. I think it requires hassles even if it is possible.

**Comment by hatsuyuki2333** [comment]
What a pity....maybe I should try another ways.

**Comment by yuriha-chan** [comment]
I hope you good luck!

**Comment by hatsuyuki2333** [comment]
Thanks.
