### ISSUE TITLE
Allow cropping photos before/after uploading

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#11074]
## Summary

新しいユーザーからcrop機能の要請がありました

機能自体はプロフィール写真とかでもう使われているから何とかてきますが、アップロード前のクロップは今のクライアント設計ではできなさそうです（ファイル選べたらすぐアップロードされてしまうので）

**Comment by saschanaz** [comment]
>ファイル選べたらすぐアップロードされてしまうので

プロフィール写真設定のように、ファイル選択したらクロップするか聞くようにする？🤔

**Comment by syuilo** [comment]
そのうちOS側で実装されそう

**Comment by saschanaz** [comment]
デスクトップOSでの実装は遠いような気が

**Comment by saschanaz** [comment]
ドライブや選択されたファイルのクロップ機能はプロフィール写真クロップ機能を使ってすぐできそうです（OS側でもうすぐ実装されるとしても、もうアップロードしたものをクロップしたいという希望はありそう）
