### ISSUE TITLE
タイムラインを遡った時に位置が記憶されない件

### ISSUE THREAD

**Issue by yukimikudayo** [syuilo/Misskey#11083]
## Summary

タイムラインにおいて、過去の投稿を閲覧することが多々あります。
過去の投稿を読み込んで、その際にリンクやプロフィールアイコンなどをクリックすると画面が遷移します。
その後、ブラウザの戻るボタンなどで戻ってくると、タイムラインには最新の投稿が表示されます。
過去に遡っていた場所を記憶しておく仕様の方が使いやすいと感じますが、そのように実装して頂けませんでしょうか？

よろしくお願い申し上げます。

**Comment by chocolate-pie** [comment]
Related to #10980?

**Comment by sugartarou** [comment]
#11068
同件ぽい

**Comment by syuilo** [comment]
修正済み
