### ISSUE TITLE
Bullmqをどうにかしてほしい

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#11089]
## Summary
duplication #11000 #11001 
そのままです。
ChangeLogには書いていないので修正されたのか不明なのでもう一度Issueとして投げておきます
![image](https://github.com/misskey-dev/misskey/assets/56515516/1199afca-73c1-45df-b179-6c4015c80e52)
やはりサーバーに余裕があってもwatingが出てしまいます。

**Comment by nexryai** [comment]
同意です。オンラインユーザー急増で自分のサーバーではやむを得ずジョブキューに関する変更をrevertして運用しています。
少し連続でノートやリアクションしただけでwaitingが1000超えます。

**Comment by tamaina** [comment]
Duplicate of #11000
