### ISSUE TITLE
リアクションごとにノートのリアクション情報が更新されるのは重い

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11093]
## Summary

Issueあった気がしたけど見当たらなかった

例えば1秒間に100回リアクションがつく場合リアクションレコードの挿入に加えて、100回ノートレコードの更新(=PostgreSQLでは実質的にノートテーブルの新規挿入&削除)が走ることになりかなり負荷が高い

そのためノートレコードごとにリアクション情報を非正規化して持つのをやめたいが、ノート取得するたびにリアクションを集計してくるのもかなり負荷が高いと思われるので、何かいい解決策を考える必要がある

例えばRedisにうまいことキャッシュできないかしら

## 案
- Redisにキャッシュして定期的にDBにベイクする(つまりRedis→DB)
  - 懸念: 結局ベイクが重そう、実装が難しそう
- Redisにキャッシュしてキャッシュがある場合はそれを使い、ない場合はDBから集計+キャッシュ追加(つまりDB→Redis)
  - 懸念: DBから集計が重そう
- 非正規化リアクション情報用DBを別に用意できるようにする

**Comment by syuilo** [comment]
もしくは非正規化して持っててもいいけど、更新は定期的にまとめて行うようにするとか

**Comment by syuilo** [comment]
SlackとかDiscordがどういう実装してるのか気になるな

**Comment by yuriha-chan** [comment]
投稿とかリノートされた時にブワーってつく傾向にあるから、Redisで短期間のキャッシュを持ち、反応が落ち着いたらDBに反映というのが良さそう

**Comment by syuilo** [comment]
問題は、RedisはJSONに対応してないからオブジェクトの特定のキーの値をアトミックにインクリメントするみたいな処理がおそらく出来ないこと

**Comment by syuilo** [comment]
`reactionsCache:<noteId>:<reaction>`
みたいなキーで持っておけば良いかも

**Comment by syuilo** [comment]
1. Redisにキーを追加する
2. 定期的にRedisからキーを読み出し、DBに反映する
3. Redisからキーを削除する

という流れになると思うけど、2を処理している最中に新しくキーが追加されたらそれが処理されないまま3に進んでキーが削除され、間違った値がDBにベイクされてしまう問題が発生するなど、意外と面倒かも

**Comment by syuilo** [comment]
良い実装方法募集中

**Comment by syuilo** [comment]
あとノートの数が多い場合、今よりだいぶマシになるとはいえやっぱり2の負荷が高そう
それを考えると究極的には「非正規化して持つのをやめる」しないといけないんだけどなかなか難しい

**Comment by tamaina** [comment]
PostgreSQLにおいて、あるレコードに対して1秒間に大量の書き換えがある場合の、一般的なパフォーマンス改善策ってなんだろう

**Comment by syuilo** [comment]
> ノート取得するたびにリアクションを集計してくるのもかなり負荷が高いと思われる

クエリの書き方によっては別にそうでもない可能性はあるな

**Comment by syuilo** [comment]
Redisにキャッシュしつつ、Redisにキャッシュがない場合だけDBから集計する感じでいけないかな

**Comment by syuilo** [comment]
reactionsテーブルに対してノートIDの配列を渡したら以下のような結果が返ってくるSQL募集中
``` js
[{
  noteId: "hoge",
  reactions: {
    'foo': 10,
    'bar': 5,
  }
}, {
  noteId: "huga",
  reactions: {
    'foo': 20,
    'buzz': 4,
    'bar': 2,
  }
}, {
  ...
}]
```

**Comment by syuilo** [comment]
投稿日時が今からT以内の投稿であれば、リアクションされていれば高確率でRedisにキャッシュされているはずなのでRedisからキャッシュを読み、全面的にそれを採用しRedisになかったとしてもDBには問い合わせない(「その投稿にリアクションがされていない」ことと「リアクションされているがRedisにキャッシュされていない」ことの区別が不可能なため、パフォーマンスを優先しRedisにない場合はリアクションされていないと見做す)
投稿日時がTより前の投稿であれば、Redisにキャッシュされていないかキャッシュが消えている可能性が高まってくるため、Redisにキャッシュがあるか確認し、なければDBから集計+キャッシュ更新

が良いかも
ここで T = 3時間とか？

**Comment by syuilo** [comment]
問題としては

> 投稿日時がTより前の投稿であれば、Redisにキャッシュがあるか確認し、なければDBから集計+キャッシュ更新

の負荷が高い可能性があるという点

**Comment by syuilo** [comment]
実際にいっぱいリアクション付いた投稿に対して`reactionsテーブルに対してノートIDの配列を渡したら以下のような結果が返ってくるSQL`を投げてみてどれくらいの負荷になるか確認したい

**Comment by tamaina** [comment]
> 以下のような結果が

```sql
SELECT "noteId", "reaction", COUNT(*) AS "reactionCount"
FROM note_reaction
WHERE "noteId" IN ('9dh0bkw15q', '9dmmip9y48')
GROUP BY "noteId", "reaction";
```

で`[noteId, reaction, reactionCount][]`が返ってくるけどそれ以上は私はわからなかった（しSQLの仕事ではないかも？）

**Comment by syuilo** [comment]
> で[noteId, reactionName, reactionCount][]が返ってくる

よさそう

**Comment by syuilo** [comment]
同じ種類のリアクション100個にたいして100レコードが返ってくるというのを避けられればどんな形式でも良い

**Comment by tamaina** [comment]
でもCOUNTって絶対遅いよね

**Comment by syuilo** [comment]
インデックスあっても遅いかしら

**Comment by tamaina** [comment]
note_reactionが762万レコードあるけど↑のようなSQLだと一瞬だったわ（INだと流石にインデックスが効いてるか）

**Comment by yuriha-chan** [comment]
> 問題は、RedisはJSONに対応してないからオブジェクトの特定のキーの値をアトミックにインクリメントするみたいな処理がおそらく出来ないこと

できるっぽい
https://redis.io/commands/hincrby/

**Comment by syuilo** [comment]
> > 以下のような結果が
> 
> ```sql
> SELECT "noteId", "reaction", COUNT(*) AS "reactionCount"
> FROM note_reaction
> WHERE "noteId" IN ('9dh0bkw15q', '9dmmip9y48')
> GROUP BY "noteId", "reaction";
> ```
> 
> で`[noteId, reaction, reactionCount][]`が返ってくるけどそれ以上は私はわからなかった（しSQLの仕事ではないかも？）

ioのDBでめちゃくちゃリアクション付いてる投稿とかめちゃくちゃ古い投稿とか全くリアクション付いてない投稿などいろいろ指定してクエリしてみてどれくらい時間かかるか計測しようとしている

**Comment by syuilo** [comment]
ちなみにioではnote_reactionレコードは1億くらいあるっぽい

**Comment by tamaina** [comment]
（ちなみにSQLはChatGPT頼り）

**Comment by pumpkin2048b** [comment]
> PostgreSQLにおいて、あるレコードに対して1秒間に大量の書き換えがある場合の、一般的なパフォーマンス改善策ってなんだろう

https://github.com/misskey-dev/misskey/discussions/10173
ここらへんで触れてますが、1度の処理で書き込める状況ならBulk updateがいいかと思われます。
一般的なデータ投入でもパフォーマンスの改善として使われる手法だと認識してます。

**Comment by syuilo** [comment]
> ioのDBでめちゃくちゃリアクション付いてる投稿とかめちゃくちゃ古い投稿とか全くリアクション付いてない投稿などいろいろ指定してクエリしてみてどれくらい時間かかるか計測しようとしている

150msくらいだった
この速度だとちょっと現実的ではないな(数十msであってほしい)

**Comment by syuilo** [comment]
今後もリアクションのレコード数は増加していくことを考えると、やっぱりノートからreactionsを消すことは現実的ではなさそうで、「noteにreactionsは持ちつつもその更新は一定間隔でbulk updateする」が落としどころかもなあ

**Comment by syuilo** [comment]
おごごごご

**Comment by tamaina** [comment]
Redisのリアクションイベントを拾って一定間隔（実行完了から1秒後みたいなインターバルにする？）でDBに適用するというDBキューがあればいいのか

**Comment by tamaina** [comment]
リアクションイベントをメモリに保持しておく必要があるんだからキューじゃダメでデーモンじゃないとか

**Comment by MineCake147E** [comment]
ノート←絵文字と(ノート←絵文字)←ユーザーのテーブルを分けるのはいかがでしょうか。
ノート←絵文字のテーブルにカウントをキャッシュしておくことも出来ると思います。ただし、この場合整合性の担保にはトランザクションが必須になります。
同じ絵文字リアクションの個数を表示するタイミングと、それを誰が送信したかを表示するタイミングがUI上では異なることを利用出来ると思います。

**Comment by syuilo** [comment]
それが今の状態ですね

**Comment by syuilo** [comment]
あーテーブルは同じか

**Comment by syuilo** [comment]
テーブル分けたとしても結局そのテーブルの更新が重くなる

**Comment by tamaina** [comment]
テーブルを分けるならそれをRedisに保持しておくほうがいいんじゃないかと（整合性は知らない）

**Comment by MineCake147E** [comment]
ノートのreactionsを毎回更新するのとどちらが重いのでしょうか。

**Comment by yuriha-chan** [comment]
要するに以下のような要求がある。
「アクティブ状態」のときにはRedisのHashを参照すれば正確なカウントが得られる。
「非アクティブ状態」ときにはPostgreSQLの非正規化テーブルを参照すれば正確なカウントが得られる。

これを実現するには以下のようにすればよいはず。

**読み出し方法**
Redis にキーが存在するかを確認し、存在すればRedisから読み、存在しなければPostgreSQLの非正規化テーブルを読む。

**書き込み方法**
書き込み時にRedisのhash`reactions:<noteId>`が存在しない場合は、ノートの年齢が`T`未満なら、Redisのハッシュテーブルを作成する。そうでないなら、非正規化テーブルをRedisへとコピーする。
Redis のhashのリアクションカウントをインクリメントし、hash全体のexpireを`T`に更新する。
expireする前に余裕をもって、PostgreSQLの非正規化テーブルへ値をコピーする操作をスケジュールする。すでにその操作が予定されている場合は、その操作を延期する。
（特殊な事情により、書き込み操作を行う前にRedisのhash`reactions:<noteId>`がexpireしてしまっていたら、このスケジュールされた操作は、PostgreSQLの正規化テーブルから非正規化テーブルを更新する。）

この方法の肝は、PostgreSQLの非正規化テーブルへ値をコピーする操作の後にリアクションが入って、Redisのexpireが延期された（「Redisからの削除がやっぱりなしで」になった）としても、PostgreSQLの非正規化テーブルが予定より早く更新されたというだけで、全体の不整合を引き起こさない点にあります。

**Comment by syuilo** [comment]
> Redisにキャッシュして定期的にDBにベイクする(つまりRedis→DB)

PostgreSQL(というかTypeORM)、それぞれ異なる値でのbulk updateに対応してない可能性があるな

**Comment by syuilo** [comment]
やっぱり対応してなかった
https://github.com/typeorm/typeorm/issues/7326

**Comment by syuilo** [comment]
やる必要がある

**Comment by syuilo** [comment]
> 問題は、RedisはJSONに対応してないからオブジェクトの特定のキーの値をアトミックにインクリメントするみたいな処理がおそらく出来ないこと

hash使えそう
