### ISSUE TITLE
プロフィールでのリンク検証機能

### ISSUE THREAD

**Issue by sorairolake** [syuilo/Misskey#11099]
## Summary

プロフィールの追加情報などに書かれたリンクがそのアカウントのものであると検証できれば、本人確認の手段としてある程度有効だと思います。具体的にはMastodonの[リンク検証](https://docs.joinmastodon.org/ja/user/profile/#verification)機能と同じようなものです。

**Comment by syuilo** [comment]
どうやって検証しようかしら

**Comment by kakkokari-gtyih** [comment]
この辺が参考になるかと
（プロフィール更新時と定期的なタイミングでrel=meのタグを見に行く）

https://git.joinfirefish.org/search?search=%20verifyLink&nav_source=navbar&project_id=7&group_id=4&search_code=true&repository_ref=develop

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
PR募集

**Comment by syuilo** [comment]
やるか
