### ISSUE TITLE
効果音などのアセットのライセンスを変更してほしい

### ISSUE THREAD

**Issue by grj1234** [syuilo/Misskey#11098]
効果音などのアセットはMisskey本体と同様にAGPLv3でライセンスされていますが、ライセンスを変更して頂けませんか。
というのも、アセットはMisskey本体に付随することからAGPLv3となっていますが、意図的にアセットをAGPLv3でライセンスしているとは少々考えにくいためです。
また、アセットのライセンスにAGPLv3が採用されていることによって、アセットを基とした二次創作を作成することが難しくなっています。
(実際に、効果音を耳コピして作成したMMLをニコニコ大百科へ投稿したところ、ライセンス違反を理由に削除されております。)
現実的には、アセットに関する権利を保有している方々のご意向もありますから、ライセンスの変更は難しいかもしれません。
自分勝手な理由で申し訳御座いませんが、何卒ご検討頂けないでしょうか。

**Comment by syuilo** [comment]
misskey-assetsに移すか

**Comment by grj1234** [comment]
記憶が合っていれば、効果音などについては複数の方が関わっていたと思います。
ライセンスを変更する場合は関係する方々に許可を得る必要があると思いますが、この点についてはどのように解決しますか？

**Comment by syuilo** [comment]
変更というか、今そもそもライセンスが特に決まってない状態と認識してる(AGPLはソースコードに対して適用されることを想定してる)

**Comment by syuilo** [comment]
ちなみに自分以外の効果音についてはいわゆる著作権譲渡的な感じで提供してもらった

**Comment by hilot06** [comment]
Related to [assets#3](https://github.com/misskey-dev/assets/issues/3) ?

**Comment by hilot06** [comment]
一応grjさんに口出しした存在なのでこのIssueは見守ってみます

**Comment by grj1234** [comment]
なるほど、アセットへのAGPLv3適用は想定外でしたか。勘違い失礼致しました。
移動できるようでしたらmisskey-assetsへ移動して頂けますとありがたいです。

**Comment by hilot06** [comment]
効果音以外のものでもAGPL-3.0を適用する意図がないものはRepoの切り分けが必要かもしれないですね。

**Comment by sorairolake** [comment]
リポジトリを分けなくても[これ](https://github.com/keepassxreboot/keepassxc/blob/develop/COPYING)みたいな感じで別々のライセンスを適用することは可能ではあると思います。

**Comment by hilot06** [comment]
なるほど！でも管理が大変ではありますね…
「ここに示したファイル以外は全部AGPL-3.0だよ！」ってすれば問題ないのか…？

**Comment by grj1234** [comment]
リポジトリを分けるか分けないかは、私には(知識や経験がないので)どちらが良いのかが分かりません…

**Comment by sorairolake** [comment]
[上記の著作権標示の仕様](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/)を見た感じでは、全体にAGPL-3.0を適用して、そうでないファイルに別のライセンスを適用する感じでしょうか。

```
Files: *
Copyright: 2023 Misskey
License: AGPL-3.0-or-later

Files: assets/*
Copyright: 2023 Misskey
License: CC-BY-4.0
```

みたいな感じで。

これを使う場合、`AGPL-3.0-only`なのか`AGPL-3.0-or-later`選ぶのが若干面倒な気はします。

**Comment by hilot06** [comment]
個人的には既に分かれているのでそれなら他も入れようっていう方がいいのかなと思います。
が、Repoが分かれるとそれはそれで不便かなという気もしています。
どっちがいいかは開発チームに一任ですね…

**Comment by grj1234** [comment]
完全にoff-topicになってしまいますが、このIssueに関して謝罪させてください。
このIssueはmisskey-devへの嫌がらせのために立てたものであり、意味のあるIssueではありません。
したがって、このIssueはCloseとします。
ご迷惑をおかけして申し訳ありませんでした。
