### ISSUE TITLE
「NodeJSを辞めて他に移行するか」に関して

### ISSUE THREAD

**Issue by EdamAme-x** [syuilo/Misskey#11101]
[例のIssue](https://t.co/g2CuRryi09) を一通り見たけど
NodeJSから移行すべき理由があんまり話されてないように思える。
逆に移行先の候補の問題点ばかり上がっていて、ただの叩き合いの様な状態でとても建設的な会話とは思えなかった。　
まずは問題点を挙げるべき、そこから選定(移行先)を始めるべき　

後記
この話題について掘り返す気はない
他の話題でも共通する事だと思って見てほしい

**Comment by L1n4r1A** [comment]
それはそうかも知れないけど今の荒れ方的に『この話題』自体をすべきではないと思います。

個人でMisskeyで書くだけ書き散らしてもなんの話にならないので念のためコメント。

**Comment by EdamAme-x** [comment]
まぁそうやね…
他の話題にも共通する事だと思って見てくれるとありがたい

**Comment by takecchi** [comment]
> 他の話題でも共通する事だと思って見てほしい

僕は逆に　軽いノリで提案できる=心理的安全性が保たれた　環境で開発が行われていたのかなとポジティブに捉えました。

本質的な部分に関してはちゃんと指摘が入っているようですし、突然やってきて是正しようとするのはただのノイズだし非生産的かなと。
(開発コミュニティ内で問題視されていたのかもしれませんが...)

僕も今回の件でmisskeyというものを知った部外者でしかありません。

ですが、今回の一件を億劫と感じ、今後の開発がクローズドな場に閉じてしまう方が勿体無いと感じたためコメントさせて頂きます。

**Comment by EdamAme-x** [comment]
なるほど…
そういう考え方なのですね
まぁ私も今回の騒動でIssueを拝見し、問題点を垂れてるだけの部外者に過ぎないですから 口を出されるのも迷惑なのでしょうね…
指摘された考え方を尊重します。
失礼しました。
