### ISSUE TITLE
「閲覧注意」という表記をやめる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#11119]
## Summary
NSFWの意味をうまく訳せていない上に、作品に対して閲覧注意と言う言葉を使うことは良くないため

**Comment by syuilo** [comment]
センシティブじゃだめかな

**Comment by tamaina** [comment]
良さそう

**Comment by u1-liquid** [comment]
むしろセンシティブ・NSFWで分離してくれたら助かるかも（えっちなものとキモいコンテンツの見分けが難しいため）

**Comment by EbiseLutica** [comment]
それするくらいなら注釈つけれるようにしたほうが良さそうだし要らないと思う（CWで十分）
「キモい」も「エッチ」も主観であり、性癖によってどっちになるかは人それぞれかも

**Comment by u1-liquid** [comment]
わたしが言いたかった「キモい」は性癖の話ではなく虫や（最近戦争中なのでよく見かける）死体の画像などの話だった
CWで注釈を付けているとしても外国語などで書かれていて読めない場合があるので、選べる選択肢としての分類表記がほしい

参考（ついったーのUI）

![image.png](https://github.com/misskey-dev/misskey/assets/17376330/b9d5f47b-e194-436f-a19d-19f6f8c93feb)

**Comment by EbiseLutica** [comment]
なるほどなるほど…
実装が地味に難しそうではある

**Comment by tamaina** [comment]
〇〇に対応してくれというのが無限に増えそう

**Comment by Nanashia** [comment]
（実装の手間とか連合どうするを無視した無邪気なアイデアとして、）
どういう画像をNSFW(click to display)に設定するべき、という方針はサーバーごとに異なるので、Roleのようにサーバーごとに定義できる「メディア用タグ」を作って文言を変えられる運用ができるとよいかもしれません。
・R15, R18, 水着, NSFW, 暴力, 性的表現, グロ, 顔出し, ネタバレ, 虫, 飯テロ, etc...
・プリセットで「センシティブ」「ヌード」とか

某鯖で見た「R18じゃなければNSFWつけなくてよい」みたいな勘違いも文言を変えられることで減らせるかも、と思いました。

**Comment by yuriha-chan** [comment]
Related: https://github.com/misskey-dev/misskey/issues/11031

**Comment by syuilo** [comment]
とりあえずセンシティブにしようぜ

**Comment by syuilo** [comment]
ついでに「NSFW」「閲覧注意」と表記ゆれしてるのを是正した

**Comment by EbiseLutica** [comment]
原語を変えるときはキーも変えたほうが、他の言語でも変更後の意図通りに新たに翻訳されていい感じになりそう

キーを使い回すと閲覧注意という意味の表現が他の言語で残りかねないかも

どうします？

**Comment by syuilo** [comment]
キーも変えた

**Comment by EbiseLutica** [comment]
sensitive: "閲覧注意" だったやつとかは、まあキーがsensitiveだから問題ないか

**Comment by robflop** [comment]
英語とドイツ語のストリングを「NSFW」に残すか「センシティブ」に更新したいか？

**Comment by syuilo** [comment]
「センシティブ」に変えたい

**Comment by robflop** [comment]
👍

**Comment by robflop** [comment]
`_role._options.alwaysMarkNsfw`はまだ「NSFW」が書いてる

**Comment by syuilo** [comment]
そこちょっと変えるのが面倒そうだからいったんそのままで
