### ISSUE TITLE
Threadsがドットがついたusernameを連合してくる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#11135]
## Summary
Threadsがドットがついたusernameを連合してくる可能性が高い

不具合が出そう？

**Comment by EbiseLutica** [comment]
思いつく懸念点はMFMのパースくらい

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/misskey/issues/8503#issuecomment-1102543051

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/misskey/issues/8503#issuecomment-1102543051 で既に述べているが、RFC 7565 形式でメンションがパースされないのはバグであるべき

**Comment by acid-chicken** [comment]
Duplicate of #9036

**Comment by tamaina** [comment]
なるほど

**Comment by mei23** [comment]
来たわ
```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1"
  ],
  "id": "https://threads.net/ap/users/THREADS_USER_DBID/",
  "type": "Person",
  "name": "DISPLAY_NAME",
  "preferredUsername": "foo.bar",
  "summary": "<p>DESCRIPTION</p>",
  "url": "https://threads.net/@foo.bar/",
  "inbox": "https://threads.net/ap/users/THREADS_USER_DBID/inbox/",
  "outbox": "https://threads.net/ap/users/THREADS_USER_DBID/outbox/",
  "followers": "https://threads.net/ap/users/THREADS_USER_DBID/followers/",
  "follobarg": "https://threads.net/ap/users/THREADS_USER_DBID/follobarg/",
  "endpoints": {
    "sharedInbox": "https://threads.net/ap/inbox/"
  },
}
```

多くの連合は`https://threads.net/ap/users/THREADS_USER_DBID/`で行われるから問題ないだろうけど、メンション系は修正が必要そうだわ。

**Comment by zyoshoka** [comment]
https://github.com/misskey-dev/misskey/blob/7c22a64b8c505f6e6c9da0fec16902fcd9af773f/packages/frontend/src/pages/admin-user.vue#L25

username にドットが入っているとシステムアカウントとして表示されるのも直す必要がありそうですね

**Comment by tamaina** [comment]
> Duplicate of #9036
