### ISSUE TITLE
本来対象でもないユーザーにも初回のウィザードが表示される場合がある

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#11144]
## 💡 Summary

アイコンなどを設定しているにもかかわらず、初回のウィザードが表示される場合がある。ウィザード搭載前バージョンより前に設定済みの状態でアップデート後だと本来対象でもないユーザーにも表示がされてしまう場合がある？

## 🥰 Expected Behavior

設定済みなら初回のウィザードが表示されない

## 🤬 Actual Behavior

設定済みなのに初回のウィザードが表示される

## 📝 Steps to Reproduce?

1.ウィザード前のバージョン(13.12.0より前)のサーバーを使ってプロフィールを設定
2.ウィザード搭載後のバージョン(13.12.0以降)にアップデートする
3.Wow!

**Comment by acid-chicken** [comment]
範囲ではなく、具体的なバージョンを書いてもらえますか？

**Comment by tkmrgit** [comment]
報告を確認すると`misskey.art`のみのようなのでこちらはフォークを利用しておりフォークの問題かもしれないです。一旦閉じます
