### ISSUE TITLE
招待機能の改善

### ISSUE THREAD

**Issue by hideki0403** [syuilo/Misskey#11158]
## Summary
現状の招待機能は

- 招待コードの発行後に招待コードを確認する方法が無い
- 発行数の制限を設けられないため、ユーザーの流入量の調節ができない

等の問題があるため、それらを改善したほうがよいかと感じています。
また #11156 でも言及されているように、招待コードに有効期限をつけることで総当り攻撃への対策にもなると感じました。

（もしよければ招待機能の改善等やってみたいのですが、大丈夫でしょうか？）

**Comment by syuilo** [comment]
> （もしよければ招待機能の改善等やってみたいのですが、大丈夫でしょうか？）

ぜひ🙏

**Comment by EbiseLutica** [comment]
可能なら

* 複数個の一挙生成機能
* ロールごとの月あたりに生成可能数な個数制限

があるともっと嬉しいです
