### ISSUE TITLE
ソースコードに`SPDX-License-Identifier`を追加してほしい

### ISSUE THREAD

**Issue by sorairolake** [syuilo/Misskey#11155]
## Summary

`SPDX-License-Identifier`はPleromaのソースコードにも書かれていますし、これを追加することによるデメリットは特に無いと思います。これによってMisskeyのソースコードを部分的に再利用する場合に、それが簡単になると思います。

**Comment by syuilo** [comment]
広範囲な変更だから意見とかあれば伺っておきたい
@misskey-dev/dev

**Comment by acid-chicken** [comment]
ライセンスした当時と違って今は org になったわけだけど、ライセンス表記はそのままにしたいかどうかかしら。しゅいろ次第ではある

**Comment by syuilo** [comment]
- 各ファイルにライセンス表記を追加するかどうか
- する場合、どのようなライセンス表記にするか

かな

**Comment by saschanaz** [comment]
Mozillaでは

```
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
```

Chromiumでは

```
// Copyright 2019 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
```

Appleでは

```
/*
 * Copyright (C) 2022 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```

のようになっています

**Comment by acid-chicken** [comment]
https://spdx.dev/ids/

**Comment by acid-chicken** [comment]
Related to #9040

**Comment by syuilo** [comment]
Appleスタイルは長すぎて開発に支障をきたしそう

**Comment by saschanaz** [comment]
https://reuse.software/tutorial/

> ## 2. Add copyright and licensing information to each file
> 
> Now that you have a license, you need to indicate in the relevant files that these files fall under that license. You edit the comment header of src/main.c as such:
> 
> ```
> /*
>  * SPDX-FileCopyrightText: 2019 Jane Doe <jane@example.com>
>  *
>  * SPDX-License-Identifier: GPL-3.0-or-later
>  */
> ```

👀

**Comment by sorairolake** [comment]
機械可読性の観点やISO規格であることから従来の著作権標示よりSPDXを使う方が良いと思います

**Comment by acid-chicken** [comment]
> 機械可読性の観点やISO規格であることから従来の著作権標示よりSPDXを使う方が良いと思います

> Copyright notices
>
> SPDX IDs are intending to express information about licenses. Copyright notices ‐ statements about who owns the copyright in a file or project ‐ are outside the scope of SPDX short-form IDs.
>
> Therefore, you **should not** remove or modify existing copyright notices in files when adding an SPDX ID.
&mdash; https://spdx.dev/ids/

とあるように「著作権標示」は SPDX-License-Identifier の範疇外なので

> https://reuse.software/tutorial/
> 
> > ## 2. Add copyright and licensing information to each file
> > Now that you have a license, you need to indicate in the relevant files that these files fall under that license. You edit the comment header of src/main.c as such:
> > ```
> > /*
> >  * SPDX-FileCopyrightText: 2019 Jane Doe <jane@example.com>
> >  *
> >  * SPDX-License-Identifier: GPL-3.0-or-later
> >  */
> > ```
> 
> 👀

といったように併記すべき

**Comment by sorairolake** [comment]
Misskeyのライセンスは`AGPL-3.0-or-later`ではなく`AGPL-3.0-only`で間違いないでしょうか?

**Comment by syuilo** [comment]
多分👍🏻

**Comment by acid-chicken** [comment]
@syuilo `SPDX-FileCopyrightText` どうする

**Comment by syuilo** [comment]
とりあえず`syuilo and other misskey contributors`とか

**Comment by acid-chicken** [comment]
年はいらない感じでいいか

**Comment by syuilo** [comment]
あった方が良いとかある？

**Comment by acid-chicken** [comment]
推奨フォーマットは `SPDX-FileCopyrightText: [year] [copyright holder] <[email address]>` だけど必須ではない

**Comment by syuilo** [comment]
とりあえず無しで

**Comment by sorairolake** [comment]
`COPYING`の著作権標示を基にreuse-toolを使って以下のように追加しておきましたが修正しますか?
```ts
// SPDX-FileCopyrightText: 2014-2023 syuilo and contributers
//
// SPDX-License-Identifier: AGPL-3.0-only
```

**Comment by acid-chicken** [comment]
`and other misskey contributors` あんま機械的じゃないなーというのは思ったかも（別に良いのだけど）

REUSE によれば `The Chromium Authors` のように書いて実際の AUTHORS 一覧は別ファイルにまとめるのが望ましいっぽい

https://reuse.software/faq/#many-copyright-statements

**Comment by acid-chicken** [comment]
あ違うこれ引っかかってるの misskey が小文字スタートだからか

**Comment by syuilo** [comment]
ソースコードにSPDX-License-Identifierが正しく追加されているか判定するworkflow欲しくなってきた
