### ISSUE TITLE
Make the invitation code longer to prevent brute force attacks.

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#11156]
## Summary

https://github.com/misskey-dev/misskey/blob/d5c4e77c44a0d72670e3679294219329898c8e00/packages/backend/src/server/api/endpoints/invite.ts#L45-L47

Currently, the invitation code space is only $32^8 = 2^{40} = 1,099,511,627,776$.
Let us consider generating random invitation codes by pseudo-random numbers that allow non-reciprocal extraction, such as LCG in 40-bit state, to obtain valid invitation codes.
The probability that there are exactly k valid invitation codes out of n generated invitation codes is by hypergeometric distribution,
$$\frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}}$$
K is the number of valid invitation codes and N is the total number of possible invitation codes.
Also, the expected number of valid invitation codes if n invitation codes are generated,
$$n\times \frac{K}{N}$$
And the expected value of the number of generation times required to obtain one valid invitation code is,
$$\frac{N}{K}$$
As the number of valid invitation codes increases, the number of required generations decreases.
For example, Misskey.io has 240,000 users. If all of them created 16 invitation codes each without using it, there would be $240,000*16=3,840,000$ of valid invitation codes.
The expected number of invitation codes to generate before one valid invitation code is obtained is
$$\frac{1,099,511,627,776}{3,840,000}=286,331.1530666... $$
and that means that at most 290,000 attempts will yield one valid invitation code.
290,000 is a lot of attempts for a single person to get an invitation code. However, if more than one person performs a random attempt with a script or other means, and even one successful attempt is made, the successful experience will be spread. As a result, more people may try random invitation code generation, resulting in many people being able to create accounts through fraudulent means.

To avoid this situation, I think the invitation code needs to be longer, e.g., 16 characters.
With 102 characters, the invitation code space would be $32^{16}=1,208,925,819,614,629,174,706,176$, and the expected number of random attempts required to illegally obtain one valid invitation code out of $3,840,000$ valid invitation codes is $3.148244321913096809130666... × 10^{17}$.

**Comment by tamaina** [comment]
Bot認証で十分では？

**Comment by syuilo** [comment]
CAPTCHAを有効にしていればプログラムで自動で試行したりができないから問題ないと思われる

**Comment by MineCake147E** [comment]
- 突破する方法が存在する
- 突破する方法がなくても解いてくれるサービスが有る(中で人間がCAPTCHAを解いている)
- それを使わなくても多くの人が施行した結果偶然有効な招待コードを引き当てる可能性がある

等回避方法はあるので念のため招待コードを伸ばしたほうが良いかと思いました。

**Comment by syuilo** [comment]
ほむ

**Comment by ghost** [comment]
これ、新規登録試みるのレートリミットあるから別に長くしなくてもいいのではと思ったり思わなかったり。
あとそもそも招待コードって発行されないと使えないんじゃなかったっけ

**Comment by MineCake147E** [comment]
>あとそもそも招待コードって発行されないと使えないんじゃなかったっけ

過去に発行された未使用の招待コードをランダム試行により確率で引き当てることを想定しています。

**Comment by u1-liquid** [comment]
招待コードは事前に用意するものではなくユーザー（またはアドミン）が要請した時発行されるので、通常は総当たりされても問題ないです。
もし横取りされたとしても有効な資格がある人なら発行してくれた人にもう一度聞いて発行してもらえばいいので、そんなに問題にはならないはず
総当たりか偶然拾えた方はおめでとう！くらいでいいんじゃないでしょうか・・・
本当に会員管理をしてるサーバーならモデレーターが気付くはずですし

**Comment by u1-liquid** [comment]
> 過去に発行された未使用の招待コードをランダム試行により確率で引き当てることを想定しています。

こちらについてはもし対応が必要であればどっちかというと招待コードの使用期限を設定したほうがよさそうです

**Comment by ghost** [comment]
使用期限設定は賛成だわ🙂

**Comment by MineCake147E** [comment]
>もし横取りされたとしても有効な資格がある人なら発行してくれた人にもう一度聞いて発行してもらえばいいので、そんなに問題にはならないはず
総当たりか偶然拾えた方はおめでとう！くらいでいいんじゃないでしょうか・・・

FÅNB◯XやPa丁re∘n等有料サービスにより招待コード発行権を配布しているサーバーがある以上、招待コードの横取りへの対策は必要かと思われます。招待コード発行にレートリミットがある場合は尚更問題になり得ます。

**Comment by syobocat** [comment]
長くするのには賛成ですが、102文字はさすがに長すぎるかと  
言われているような使用期限設定を設けた上で16文字程度にするのがよいのでは

**Comment by nenohi** [comment]
文字数を増やす、というよりはMisskeyのAdminやモデレーターが招待コードを管理できる画面を用意するだけで十分な気がします

**Comment by syobocat** [comment]
招待コードの管理画面があった方が良いのは確かだと思います

**Comment by MineCake147E** [comment]
>長くするのには賛成ですが、102文字はさすがに長すぎるかと

エンコードをBase64にすれば、同じ招待コード空間を保ちつつ、約85文字に抑えることができます。

>言われているような使用期限設定を設けた上で16文字程度にするのがよいのでは

この場合、存在しうる招待コードの総数は $1,208,925,819,614,629,174,706,176$ 個になります。

**Comment by CyberRex0** [comment]
もう少し現実を見て利便性を考えてほしい

**Comment by syuilo** [comment]
手打ちではなくコピペで使われる場合が多いとしてもまあ16文字程度が上限かな

**Comment by meronmks** [comment]
んーーこの提案で招待コードのセキュリティ高められるとして・・・
誰がどういう得を得れるんだろうか？

**Comment by syuilo** [comment]
今の8文字が短いのであれば10文字くらいで良いんじゃねと思った

**Comment by tamaina** [comment]
100文字とか85文字とかにしろと言うのは開発を妨害しているのに近いと思う

**Comment by ghost** [comment]
招待コードの管理画面の実装だけで充分だと思う
そもそも招待制にしているサーバーなんて大体が小規模なんだから危惧するようなことではないと(そもそも招待コード売れてるところ見たことないし招待コードビジネスなんてすぐなくなると思う)

**Comment by MineCake147E** [comment]
>100文字とか85文字とかにしろと言うのは開発を妨害しているのに近いと思う

申し訳ありません。102文字は長すぎました。訂正します。

**Comment by u1-liquid** [comment]
なんとですね、クレカのCVCは3桁の数字なんですよ・・・

**Comment by ghost** [comment]
まぁioには招待コード総当たりページがあるからセキュリティー上げる必要なさそうなの

**Comment by yuriha-chan** [comment]
招待コードを長くした場合、招待コードを当てるより既存のユーザーのパスワード当てて乗っ取る方が簡単そう
（私は16文字程度のパスワードを使うことが多い）

**Comment by sorairolake** [comment]
有効期限を先に決めてから、その期間内には総当たり攻撃で破られないであろう文字数に変更するのが良いと思います。
