### ISSUE TITLE
まだ発見していないリモートユーザーのノートを照会するとエラーになる？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#11161]
## 🥰 Expected Behavior
一発で表示される

## 🤬 Actual Behavior
最初は500

``` 
 { message: "Internal error occurred. Please contact us if the error persists.", code: "INTERNAL_ERROR", id: "5d37dbcb-891e-41ca-a3d6-e690c97775ac", … }

{ message: 'Could not find any entity of type "User" matching: {\n "id": "9gvtzlclpu"\n}', code: "EntityNotFoundError", id: "3b3c6d5f-426a-4bfd-aeba-79ab16aa3265" }
```

もう一度照会するとちゃんと表示される

## Env.
misskey.io

**Comment by EbiseLutica** [comment]
さっき別件で照会しまくってたけど、出たのioだけだったので、ioの不具合な気もする…

**Comment by tamaina** [comment]
まじか

**Comment by syuilo** [comment]
EntityNotFoundErrorが出るのは大抵の場合PostgreSQLのレプリケーションの同期遅延が起因だと思われる(ioでなくてもレプリケーションで運用している場合発生する可能性がある)

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/issues/10897

**Comment by tamaina** [comment]
こちらに関しては

https://github.com/misskey-dev/misskey/blob/71d74676f04c1f92266fac95f8e07b28025b875d/packages/backend/src/core/activitypub/models/ApPersonService.ts#L289

ここでユーザーを取得した直後にuriPersonCache（インメモリキャッシュ）に保持するとかすれば多少緩和するかもしれない
