### ISSUE TITLE
見たRenoteを省略する機能で自分のnoteのrenoteも省略ほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11165]
## Summary

#1792 で実装されたrenoteを閉じる機能ですが、自分のnoteのrenoteも省略してほしいです。

**Comment by syuilo** [comment]
既にされるかも
どういう条件かしら

**Comment by anatawa12** [comment]
自分のしたrenoteは閉じられますが自分のnoteのrenoteはされません。

**Comment by anatawa12** [comment]
いまpullreq作っています

**Comment by anatawa12** [comment]
リンクミスってましたねすみません
