### ISSUE TITLE
チャンネル宛ノートのRN選択肢は通常RNが一番上にあってほしい

### ISSUE THREAD

**Issue by Spoonail-Iroiro** [syuilo/Misskey#11178]
## Summary
- 通常RNをしようとして間違ってチャンネル内RNをするのを防止する
- そもそもチャンネル内RNの使用を抑制したい

等の観点から、チャンネル宛ノートのRNボタンを押したときに通常RNが選択肢の一番上にあってほしい。

現状：
チャンネル内Renote
チャンネル内引用
Renote
引用

理想：
Renote
引用
チャンネル内Renote
チャンネル内引用

## 「通常RNをしようとして間違ってチャンネル内RNをするのを防止する」とは
ユーザーからすると、RNボタン→1行分カーソルを下に→クリックという同じ操作で
- 通常のノートであれば通常のRN
- チャンネル宛ノートはチャンネル内RN

と結果が違ってしまうため、通常RNをしようとして間違ってチャンネル内RNすることが起こりやすい。

## 「そもそもチャンネル内RNの使用を抑制したい」とは
特定のジャンルのユーザーが集まる以上、1つのチャンネル内で投稿するユーザーは少数のケースが大半と考えられる。
投稿が少ないのにチャンネル内RNをしても効果がない・同じ投稿が並ぶスパムになるだけなので、そもそもチャンネル内RNは使用
しにくいか、廃止するくらいでも良いのではないかと思う。

**Comment by tai-cha** [comment]
チャンネル外でRNしてほしくない（NSFW系など）の意見もよく見るような気がしますけれど…

インスタンスやチャンネルにもよりますが
>特定のジャンルのユーザーが集まる以上、1つのチャンネル内で投稿するユーザーは少数のケースが大半と考えられる。
>投稿が少ないのに

ここはioなど大きめサーバーのアクティブなチャンネルとかだと普通にユーザーが（サーバーのアクティブユーザーに対して）少なくても投稿数は多かったりがあるのでもう少し根拠がないと弱い気がします

**Comment by Spoonail-Iroiro** [comment]
アクティブユーザーが他サーバーと一桁違うのを鑑みるとioは例外的に大きいインスタンスだと考えてるので、逆にioのケースを却下理由にするのはよくないのではないかと思います。

あとこのissue自体はチャンネルRN自体を選択肢から消すわけではないので2番目の理由はあくまでサブです（書き方が悪かったかもしれませんが）。
1番目の理由がメインですので、そこを後続のコメントには考えてほしいと思っています。

**Comment by Spoonail-Iroiro** [comment]
v2024.5.0現在、チャンネル内ノートでも通常RNが一番上にある状態になっています。
（変更自体はもう少し前のバージョンでされていたかと思います）
対応いただきありがとうございました。
