### ISSUE TITLE
webp→webp変換で元ファイルの可逆と非可逆を考慮する

### ISSUE THREAD

**Issue by Narazaka** [syuilo/Misskey#11170]
## Summary

#9370 の実装でwebp→webp変換がとりあえず非可逆圧縮になっている。

元ファイルが可逆か非可逆かに応じてあわせた方が良いかも。

https://github.com/mooyoul/node-webpinfo で判定出来る

可逆か非可逆かだけ判定する最小構成な感じではなかったので自分でも作った
https://github.com/Narazaka/webp-is-lossless

コピペするかnpm iするか他のを使うか

**Comment by tamaina** [comment]
「オリジナル画像を保持」でユーザーが選択できるので非可逆でいい

ブラウザサイドで非可逆にするのが大変そうだし、それをするならいっそavifへ変換したい

**Comment by tamaina** [comment]
avifの非可逆もやらない方針

（png→avif変換は限りなく品質を維持しつつ可逆でやりたい）

**Comment by Narazaka** [comment]
まあたしかにツイとか他サービスとかも一般に気軽にjpgにしてくるしよいのかも
