### ISSUE TITLE
ドライブ: フォルダのページネーションが機能しない

### ISSUE THREAD

**Issue by abyssluke** [syuilo/Misskey#11180]
## 💡 Summary

ドライブにおいて、同一フォルダ内(ルート含む)にフォルダが31個以上ある場合、フォルダのページネーションが機能しない。
ファイルのページネーションは機能する。
![0168dacdad7d2cf8c97e73a334f20c34](https://github.com/misskey-dev/misskey/assets/97727/65d34898-7afb-437d-8425-c130db656b7c)
上記動画の例だとフォルダ数は70個あるが、そのうち最新の30個しか表示されない。
DevToolsを確認したところエラーメッセージやAPIへの追加のリクエストは確認できなかった。

## 🥰 Expected Behavior

自動的に、または「もっと」押下で31個目以降のフォルダの一覧が表示される。

## 🤬 Actual Behavior

31個目以降のフォルダの一覧が表示されない。「もっと」を押しても無反応。
続きのフォルダ一覧を取りに行くAPIリクエストが発生していない。

## 📝 Steps to Reproduce

1. ドライブ内に31個以上のフォルダを作成する。
2. リロードや他のフォルダに推移してからフォルダを作成した場所を開きなおす。
3. 31個目以降のフォルダが表示されない。

### 💻 Frontend
* Model and OS of the device(s):
  Windows 10 (64bit) 22H2(19045.3086) / iOS 16.5.1
* Browser:
  Chrome 114.0.5735.199 / Safari 16.5.1
* Server URL:
  misskey.io
* Misskey:
  13.13.2

**Comment by yupix** [comment]
実装を見た感じフォルダーにはファイルでいう`fetchMoreFiles`にあたる物が無いようなので、作成しようと思います。こちらで実装しても大丈夫でしょうか?

**Comment by syuilo** [comment]
お願いします🙏
