### ISSUE TITLE
パスワードリセットのメールに記載されているリンクがおかしい

### ISSUE THREAD

**Issue by BATOER-0605** [syuilo/Misskey#11208]
## 💡 Summary

パスワードリセットのメールが送信された後、添付のリセット用URLの
表記は正しいのですが、ホバーしてみると「**example.com**」の形ではなく
「**example..com**」(「.」が二つある)になっているため、ブラウザでアクセスできない。

※アドレスバーでドメイン部分の修正すればアクセスは可能です。
<img width="531" alt="スクリーンショット 2023-07-09 14 22 44" src="https://github.com/misskey-dev/misskey/assets/81146621/ebc45b58-3291-4ebe-a08c-edd1c2107101">

## 🥰 Expected Behavior

ホバーされた時の表示が「example.com」になるように、
URLのドメイン部分にある余分な「.」を削除する

## 🤬 Actual Behavior

ホバーされた時の表示が「example..net」

### 💻 Frontend
* Server URL: https://misskey.snmochizuki.net
  
* Misskey:
  13.13.2

**Comment by nenohi** [comment]
.configに記載されているドメインは正常に記載されておりますでしょうか？

**Comment by u1-liquid** [comment]
https://github.com/misskey-dev/misskey/blob/5059d4d7e1fc98c5a86ebe73997e21b8c9bda0f7/packages/backend/src/server/api/endpoints/request-reset-password.ts#L89-L94

ソースコード的にはリンクとリンクのテキストに同じ値が入るはずです

**Comment by BATOER-0605** [comment]
私もソースコードを確認しましたが、 @u1-liquid さんがおっしゃる通り、ソースコード自体は問題なかったです。
misskey.ioでパスワードリセットのリクエストを出してみましたが、こちらは問題がないことから
クライアント側の問題だと思い、メーラーを Microsoft Outlook(macOS版)からApple純正の方のメーラーに変えて
試してみましたが、こちらだとうまく行く(href=で指定したlinkが正常に反映されている)ようです。
<img width="269" alt="スクリーンショット 2023-07-09 15 26 36" src="https://github.com/misskey-dev/misskey/assets/81146621/ad68a4f0-66ce-401c-ad2d-8c595bb44675">


にしてもOutlook(mac版)ではうまくいかなかったのはなぜなんでしょうか...

**Comment by t1nyb0x** [comment]
解決済みとしてクローズいたします。
何か問題がありましたら、リオープンお願い致します。
