### ISSUE TITLE
画像を隠している際の文言（「センシティブ」など）をcondensedにする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#11212]
## Summary
折り返すのは見栄えが悪いため

**Comment by yuriha-chan** [comment]
inline-block とかで折り返し位置を指定するほうが良くない？

**Comment by tamaina** [comment]
枠自体のスペースが狭いので…

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/624cd3c0-8807-4c40-a704-4cab629f1b9b)

うーんww

**Comment by syuilo** [comment]
そもそも狭い画面でメディアを横に並ばせるのをやめた方が良いわね
