### ISSUE TITLE
遡れる通知の数をサーバーごとに設定可能にしてほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11227]
## Summary

タイトルの通り、遡れる通知の数をサーバーごとに設定可能にしてほしいです。

misskeyにおいてリアクション通知の数が多くなり直近のフォロー通知が見えなくなることがあるため、サーバーごとに変更可能にし、負荷(等)にあわせた調整可能にしてほしいです。

おそらくですがここの300が設定可能だと解決すると思いました

https://github.com/misskey-dev/misskey/blob/1a096c557e6fd7bea2a3321fc99b42a8ad218270/packages/backend/src/core/NotificationService.ts#L100-L104

**Comment by tamaina** [comment]
ロールだと難しい？

**Comment by anatawa12** [comment]
これよく見たらすでに実装されてるのでclose as completedしていいやつですね。

meta(guiから設定可能)ではなくconfig名の少し気になるけど。あとはロールで再実装はしても良さそうですが

f53cffaeb29a5663e28259e8eab85a15b1cb9044
https://github.com/misskey-dev/misskey/blob/9be3890827b92e1f6c56b6528ffa5e1b1391903d/packages/backend/src/core/NotificationService.ts#L150-L154

**Comment by tamaina** [comment]
FTTはmetaからいじれるのに
