### ISSUE TITLE
CWがサーバートップのTLに隠されず表示されてしまう

### ISSUE THREAD

**Issue by nakajima0528** [syuilo/Misskey#11221]
## 💡 Summary
ログインしていないサーバーのトップに表示されるTLピックアップにおいて、本来CWで隠されている内容が表示されてしまう

## 🥰 Expected Behavior
CWは本来のTLと同じく隠された状態で表示される

## 🤬 Actual Behavior
![無題](https://s3.invillage-outvillage.com/misskey/01cac1b9-537c-4838-9556-90119f981ab9.png)
↑TLでの表示（隠すボタンを押すことで展開されている）

![無題](https://s3.invillage-outvillage.com/misskey/4516c77c-42d8-499a-91ad-4279d45cd200.png)
↑サーバートップにピックアップされた際の表示（CWで伏せた部分が隠されず表示され、注釈もなくなっている）

## 📝 Steps to Reproduce

1. ノート投稿画面で「隠す」を選ぶ
2. 注釈と伏せたい部分を入力する
3. 投稿する

## 📌 Environment

Misskey version:13.13.2
Your OS:Windows10
Your browser:chrome

以前投稿したissueと関連するかもしれません（CWがプレビューで伏せテキストと注釈が逆になる #10622）。

**Comment by tai-cha** [comment]
この現象でR-18なノートが普通に伏せられずにトップに出てたのでびっくりした

**Comment by EbiseLutica** [comment]
改善案いくつかあると思ってて

* CWのUIを表示するよう改善する
* そもそもCWのついたノートは除外する

かなあって感じ　CWでがついている理由を考えると、個人的には後者を推します

**Comment by acid-chicken** [comment]
後者は CW 使用によるエンゲージメントのディスアドバンテージを促進させるので反対

**Comment by u1-liquid** [comment]
非ログイン時に流れるパブリックな画面なのでCWの投稿は流れない方がいいと思います。
なんならNSFW画像が付いてるノートも流れない方がよさそう

**Comment by syuilo** [comment]
NSFW除外してた気がしたけど気のせいか

**Comment by u1-liquid** [comment]
`notes/featured`を描画してるだけじゃなかったっけ特に除外処理はしてないかも
ちなみに非ログイン時の「タイムラインを見てみる」にもNSFWは流れてるかも

**Comment by EbiseLutica** [comment]
> 後者は CW 使用によるエンゲージメントのディスアドバンテージを促進させるので反対

非ログインページの右がエンゲージメントにそこまで影響を与えているかというと個人的には何とも言えない感触ある。

ただ、よくよく考えたら隠す必要はないね。ハイライトに載っている以上パブリック公開範囲だし。
むしろサーバーを探している人に対し、恣意的に編集されたハイライトを見せる方が悪手かもと思ったので、やはりCWボタンの表示がいいかも

（ユーザー名やアイコンも出したほうが良くない？とは思うけど）
