### ISSUE TITLE
通知欄で、引用ノートなのにただのRenoteとして表示される場合がある（ノート本文がない場合？）

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#11222]
## 💡 Summary
これ

ttps://p1.a9z.dev/notes/9gzguso5l6

**Comment by yuriha-chan** [comment]
https://github.com/misskey-dev/misskey/issues/10682
画像だけ、投票だけの引用リノートはそうなりますね。

（調査報告だけして直した気になっていた人）
