### ISSUE TITLE
Deploying To Vercel Failing

### ISSUE THREAD

**Issue by solomonshalom** [syuilo/Misskey#11237]
## 💡 Summary

I tried misskey on vercel but for some reason the deployment didn't go through and rather threw an error instead -

![Screenshot_20230711-073753_Chrome](https://github.com/misskey-dev/misskey/assets/71135230/b60ed006-42c8-429b-a1f1-97b697f298d6)

Can someone help me fix it? 😫 

P.S - If possible, please make and add a vercel deploy button for ease of deployment + the cost would be cut massively for developers to host it too! 

## 📝 Steps to Reproduce

1. Go to vercel
2. Click new project
3. Select third-party github repository
4. Add misskeys github repository
5. click continue
- Misskey's github repository will be cloned to your github account in this step
6. Click Okay or Continue
7. Deployment should 

## 📌 Environment

NodeJS 18.x

**Comment by tamaina** [comment]
It seems git submodules are not downloaded (the repository not cloned recursive).

Try to add

```
git submodule update --init;
```

at the first of build process.

**Comment by solomonshalom** [comment]
Hi! @tamaina 

Thank you for the quick reply but I am not sure how to do this in vercel, or should this be done in the package.json file? 

If it's alright, can you share me a step by step process on how to do it? 

Would love to know!

**Comment by acid-chicken** [comment]
btw I think Vercel is not suitable for deploying Misskey.

**Comment by tamaina** [comment]
@solomonshalom  Sorry, I don't know how to use Vercel well.

**Comment by fu-sen** [comment]
> btw I think Vercel is not suitable for deploying Misskey.

I've been using Vercel for a long time (I've been using it since the days of now) and I agree with this.

**Comment by solomonshalom** [comment]
> > btw I think Vercel is not suitable for deploying Misskey.
> 
> I've been using Vercel for a long time (I've been using it since the days of now) and I agree with this.

Hmm, I understand but there's gotta be a workaround, right?

**Comment by acid-chicken** [comment]
> > > btw I think Vercel is not suitable for deploying Misskey.
> > 
> > I've been using Vercel for a long time (I've been using it since the days of now) and I agree with this.
> 
> Hmm, I understand but there's gotta be a workaround, right?

Unfortunately, no.
