### ISSUE TITLE
storybook publishが壊れてる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#11246]
https://github.com/misskey-dev/misskey/pull/11245#issuecomment-1631694780

```
Build and open your Storybook locally and check the browser console for errors.
Visit your published Storybook at https://6428f7d7b962f0b79f97d6e4-knlemknljj.chromatic.com/
The following error was encountered while running your Storybook:

"undefined" is not valid JSON
    → Failed to publish build
undefined
/home/runner/work/misskey/misskey/packages/frontend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  frontend@ chromatic: `chromatic "--exit-once-uploaded" "-d" "storybook-static" "--branch-name" "pag-back"`
```

**Comment by chocolate-pie** [comment]
https://github.com/misskey-dev/misskey/blob/9845ccec5b70501b36e05a84206e38a1f53957c4/packages/frontend/src/config.ts#L14
↓ ここにundefinedが入っている?

<img width="530" alt="スクリーンショット 2023-07-12 10 06 44" src="https://github.com/misskey-dev/misskey/assets/106949016/d56deb51-7c41-4727-8b4b-f784a961d923">

**Comment by saschanaz** [comment]
#11204 の影響かも

**Comment by acid-chicken** [comment]
![image](https://github.com/misskey-dev/misskey/assets/20679825/3ae24867-7dc3-4d91-8dae-5f245dcec392)

**Comment by chocolate-pie** [comment]
ちなみに↓は
https://github.com/misskey-dev/misskey/blob/9845ccec5b70501b36e05a84206e38a1f53957c4/packages/frontend/.storybook/preload-locale.ts#L2

https://github.com/misskey-dev/misskey/blob/9845ccec5b70501b36e05a84206e38a1f53957c4/gulpfile.mjs#L11
が正しい書き方だと思うけどそれで直ったりします？

**Comment by saschanaz** [comment]
#11259 でpublishは解決できましたがテストが落ちてます

最後に成功したのは c065b97140f29ad93d6499b06c59c5d98d194fc2 で、たぶん https://github.com/misskey-dev/misskey/compare/c065b97140f29ad93d6499b06c59c5d98d194fc2...b97694b083aca7df07d0763202aab4cd1ff33c01 でなにかが起こったかも
