### ISSUE TITLE
アニメーションがオフのとき、スマホで子メニューの選択ができない

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#11257]
## 💡 Summary

遅延がないことが原因
これはノートのメニューでも起こる

アニメーションあり
![2023-07-13_03-11-00_chrome](https://github.com/misskey-dev/misskey/assets/28654659/6a8832c3-4374-414c-9f1e-050c7a7b3dbc)

アニメーションなし
![2023-07-13_03-11-52_chrome](https://github.com/misskey-dev/misskey/assets/28654659/17504009-6c2f-4af6-9702-7eb8317720be)

## 🥰 Expected Behavior

選択ができる

## 🤬 Actual Behavior

選択ができず、タップした場所にある子メニューが選択される

## 📝 Steps to Reproduce

1.「UIのアニメーションを減らす」を有効にする
2.子メニューがあるものを押す

### 💻 Frontend
* Model and OS of the device(s):
Windows 10
Android 8
* Browser:
Chrome 114.0.5735.199
Vivaldi 6.1.3035.110
* Server URL:
misskey.io
mi.kabo.cab
* Misskey:
io: 13.13.2
mi.kabo.cab: 13.13.2-kabocab2 (ちょっといじっただけでメニュー関連は何もしていない)

### 🛰 Backend (for server admin)
mi.kabo.cab

* Installation Method or Hosting Service: Misskey install shell script on Vultr
* Misskey: 13.13.2-kabocab2
* Node: 18.16.0
* PostgreSQL: 15.2
* Redis: 7.0.11
* OS and Architecture: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-73-generic x86_64)

**Comment by syuilo** [comment]
解決策募集中

**Comment by acid-chicken** [comment]
遅延がないためなら遅延をつければ良いのでは

**Comment by syuilo** [comment]
ほむん
