### ISSUE TITLE
デフォルトでプレビューを表示するオプションがほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11254]
## Summary

デフォルトでプレビューを表示するオプションがほしいです。

pullreq作成予定です

**Comment by futchitwo** [comment]
フォークで「プレビューの表示状態を記憶する」ように変更を加えているところを見たことがあります
もしかしたらそっちの方が設定を変える必要がない分便利かもしれません

**Comment by EbiseLutica** [comment]
> フォークで「プレビューの表示状態を記憶する」ように変更を加えているところを見たことがあります
もしかしたらそっちの方が設定を変える必要がない分便利かもしれません

私のフォークにこれ導入していますね　設定項目を増やすよりも表示状態の記憶を入れたほうが良いかなーって思います。次回以降に残ってて嫌だったことが特にないので。
