### ISSUE TITLE
絵文字検索の表示件数を増やしてほしい

### ISSUE THREAD

**Issue by ibuki2003** [syuilo/Misskey#11263]
## Summary

絵文字ピッカーの検索にて、表示される件数が8つに制限されてしまっていますが、もっと多いと嬉しいです。スクロールもできるので無制限にしてもよさそうと思いました

**Comment by ibuki2003** [comment]
PRを作成したいのですが、制限数の具体的な目安に議論の余地があると考えています。 多すぎると処理負荷やDL量の問題があり、いっぽう少なすぎると本問題の解決にならないと思われるためです。
手元の実験では、misskey.ioのような絵文字数のとき無制限では負荷が高すぎるように感じ、100件程度ならスマートフォンでも問題なく表示できました。
しかし、スペックの差異のほか携帯の通信容量の個人差もあるため、助言いただきたく思います。

**Comment by tamaina** [comment]
100件ぐらいでいいのでは

**Comment by ibuki2003** [comment]
ありがとうございます、では100件で一度PRを立てようと思います
