### ISSUE TITLE
チャンネルにチャンネル外へのRenoteを制限する機能を追加して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#11269]
## Summary

チャンネルの用途によっては、チャンネル外にRenoteされるべきではない場合が考えられます。
現在、このような場合でのチャンネル外Renoteは、チャンネル概要やそのピン留め投稿に記述された注意事項によって抑制されていると考えられますが、機能として制限する方法が存在する方が良いのではないか?と思いました。

**Comment by samunohito** [comment]
@syuilo 
以下で行けるかと考えています。

- channelテーブルにisRenotableみたいなカラムを生やす
- バックエンド側のnotes/create.tsの[このへん](https://github.com/samunohito/misskey/blob/7015cc937bd872e9c7ebafb56bdaea4ca138e0df/packages/backend/src/server/api/endpoints/notes/create.ts#L289-L288)にリノート可能かどうかをチェックする処理を書く
- フロントエンド側のMkNote.vueの[このへん](https://github.com/samunohito/misskey/blob/e85b8217c0eda4b0cb2ebf5642cabd2af7212140/packages/frontend/src/components/MkNote.vue#L308-L307)にリノート可能かどうかでメニューを出し分ける条件を書く

方針に問題なさそうでしょうか？？
問題なさそうであれば、自分が対応してみようと思います。

**Comment by syuilo** [comment]
ノートのURL投稿すれば共有可能なわけだし、チャンネル外にRenote禁止する運用は間違っていると思うけど、ニーズがあるのであればその実装方法で良さそう

**Comment by samunohito** [comment]
@syuilo 
ありがとうございます。やってみます。

> ニーズがあるのであればその実装方法で良さそう

ニーズとしては、以下があるかと考えます。
- リノートする側として、チャンネル内にリノートするつもりがHTL/LTLに流してしまった…などの誤爆防止
- TLを見てる側として、リノートが推奨されないチャンネルの内容を見ずに済む（誤爆・故意問わず）

> ノートのURL投稿すれば共有可能

これも仰るとおりだと思います。…ですが、
- 「ノート」としてTLに表示されるよりもプレビューとして表示されたほうが圧倒的に情報量が減る
- 大抵の場合、リンクを貼って引用リノートとしないパターンよりも、リノート／引用リノートを使用する（はず）

かと考えており、メリットは十分にあるかなと考えています。

**Comment by Sayamame-beans** [comment]
PRがmergeされているので、このissueは閉じても良いのでしょうか…?

**Comment by samunohito** [comment]
閉じます！ありがとうございます:pray:
