### ISSUE TITLE
storybookのplay functionが並列で2回動く（MkAdのテストが落ちる）

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#11267]
理解できない変なエラーはあれが原因です

なぜそうなるのかは不明

**Comment by saschanaz** [comment]
`pnpm build-storybook && pnpm --filter frontend storybook exec dev`では問題なく最初の`play()`の実行が終わるまでまってもう一度実行される

chromaticにアップロードされたビルドではそうではない

ここを１，

https://github.com/misskey-dev/misskey/blob/df5480668d52e2fcf6ac03b4df22e5e00d258322/packages/frontend/src/components/global/MkAd.stories.impl.ts#L29

ここを２としたら、

https://github.com/misskey-dev/misskey/blob/df5480668d52e2fcf6ac03b4df22e5e00d258322/packages/frontend/src/components/global/MkAd.stories.impl.ts#L39

ローカルでは：１，２，１，２の順
Chromaticでは：１，１，２，２の順

なぜでしょう @acid-chicken

**Comment by acid-chicken** [comment]
えー

**Comment by acid-chicken** [comment]
Chromatic のバグじゃね……と思いたいんだけどなぁ
とりあえずセマフォを用意すればワークアラウンドになる……？

**Comment by zyoshoka** [comment]
このバグのせいで不可逆的な操作を伴うテスト（例えば #13830 で言えば `MkClickerGame` でボタンが押されたらカウンターが1になることのテスト）が書けないのでなんとかしたいです

深くは調べてませんが v8.1 で実験的に追加された Playwright CT で書き直すのも手？
https://storybook.js.org/blog/portable-stories-for-playwright-ct/

**Comment by zyoshoka** [comment]
これ普通に
https://github.com/misskey-dev/misskey/blob/9849aab40283cbde2184e74d4795aec8ef8ccba3/packages/frontend/.storybook/preview.ts#L113
で `FORCE_REMOUNT` してるのが原因な気がしてます（ここをコメントアウトすると直る）
