### ISSUE TITLE
Cat ears seems awkward on reply modal.

### ISSUE THREAD

**Issue by RieLCho** [syuilo/Misskey#11279]
## 💡 Summary

On reply modal, the cat ear seems quite awkward. Tried on Firefox 115.0.2 & Chrome 114.0. 5735. 199 and both seems wrong. I've tried to search this issue with 'cat', 'ear' to prevent making duplicated issue, but I'm really sorry if this issue is duplicated. 

## 🥰 Expected Behavior

![제목 없음](https://github.com/misskey-dev/misskey/assets/13748138/26d1999a-8281-4c67-b20a-febb858d4992)

I think cat ears should be seen fully on reply modal.

or

![fixed](https://github.com/misskey-dev/misskey/assets/13748138/310cb306-7d9d-4d03-9c91-da836f13c75c)
giving a tag a margin-top:10px might fix this problem, but for only cat eared profiles.

## 🤬 Actual Behavior

![image](https://github.com/misskey-dev/misskey/assets/13748138/72d12e9d-e835-488d-b9ae-f0ce615e1b30)

## 📝 Steps to Reproduce

1. Write a note. 
2. Get a reply from anyone who have a cat ear.
3. Try to reply.

### 💻 Frontend
* Model and OS of the device(s): Windows 10 Education 22H2
* Browser: Firefox 115.0.2 & Chrome 114.0.5735.199
* Server URL: sns.lemondouble.com
  
* Misskey: 13.14.0-beta.2

**Comment by saschanaz** [comment]
I can confirm: 
![The cat ears are cut at the top boundary in the reply form](https://github.com/misskey-dev/misskey/assets/3396686/601e264b-5942-408f-a26a-a26e7e09ecaf)

**Comment by RieLCho** [comment]
I think there could be two options.

1. fix margin/padding
 - giving margin-bottom: -10px at components-MkPostForm-header & padding-top: 10px at .components-MkPostForm-targetNote
<img width="462" alt="스크린샷 2023-07-18 오후 2 28 14" src="https://github.com/misskey-dev/misskey/assets/13748138/12a27bf3-e8a9-4b1e-b58e-3eed9b8d1727">

2. fix z-index issue 
- every components are set to static so z-index will not work at all. needs more investigation.

I guess second option is better for future maintenance and component reuse. I really like your project and want to contribute. so I'll try to find out how to make this better.
