### ISSUE TITLE
チャンネルをNSFW(センシティブ)に設定出来るようにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#11270]
## Summary

チャンネルの用途の1つに、NSFWな内容の棲み分けが考えられます。
現在、このような場合でのチャンネル利用では、バナーやタイトルにNSFWな内容を利用しないという制限が利用規約等で課せられていることが多いですが、チャンネルをNSFWとして設定することで、バナー画像を表からは見えないようにしたり、チャンネルがNSFWであることを分かりやすくすることが可能と考えます。
更に、現在はチャンネル外へのRenoteによってNSFWな内容がLTLに流れることがあります。
チャンネルをNSFW設定にすることにより、当該チャンネルの投稿をチャンネル外にRenoteした場合はホーム投稿としてRenoteされるようになれば、非常に良いと思います。

**Comment by setaria430** [comment]
isSensitive == true なNSFWチャンネルに投稿があった場合、チャンネル -> トレンド（と言いつつ最新投稿順）に載らない方がよさそうに思うのですが、いかがでしょう…？
