### ISSUE TITLE
スポンサーを整理する？

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#11284]
敬称略
READMEやMisskey Hubなどのスポンサー表記について、

- Skebがスポンサーになったようなので追加する
- スポンサーとは別にMask NetworkとDC ADVirth.がスペシャルサンクスとして「Misskeyについて」ページに記載されているがこれはスポンサーとは別なのか？

**Comment by syuilo** [comment]
「スポンサー」は「継続して支援してくれている法人」という意味ではなくて、「一度でも寄付してくれた法人」という意味で使ってた
今現在例えば毎月これくらい資金提供しますよ、という法人は存在しない

Special Thanksはスポンサーとの表記揺れだからどっちかに統一するか

**Comment by syuilo** [comment]
SkebもSpecial Thanksに追加したはずだけどまだリリースはされていない
