### ISSUE TITLE
Renote対象ではなくRenote自体も通報可能にして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#11285]
## Summary

#11268 と関連するのですが、現在はユーザーかノートに対してのみ通報が可能であり、Renote自体に対しては通報する術が無いことを失念していました。

**Comment by syuilo** [comment]
Renote自体を通報したいケースが思い浮かばなかった

**Comment by acid-chicken** [comment]
#11270 なチャンネルの投稿をパブリックに Renote されてほしくないので #11268 とそれに伴う通報は欲しい

**Comment by Sayamame-beans** [comment]
> #11270 なチャンネルの投稿をパブリックに Renote されてほしくないので #11268 とそれに伴う通報は欲しい

概ねその通りです。
問題あるノートのRenote等を常習的に繰り返すような人である場合は、ユーザーを通報すれば問題無いと考えられますが、そうでない場合は対象となるRenoteを直接指定して通報出来た方が良いのかな?と思います。
(少なくとも、私が通報対応作業を行う上ではそうなっていた方がありがたいな、と思います。)

**Comment by syuilo** [comment]
> #11270 なチャンネルの投稿をパブリックに Renote されてほしくないので #11268 とそれに伴う通報は欲しい

それだけが理由なのであればパブリックにRenoteできるか否かを設定可能にした方が良さそうに思った

**Comment by acid-chicken** [comment]
それについてはそうかも
それはそれとして他にも Renote の通報ができた方が自然なケースは色々あるのも事実
例えば日本においては公職選挙法で投票時当日に選挙運動にあたる Renote ができないと解釈するのが自然なので、伴って Renote に対して通報できないと都合が悪いなど

**Comment by acid-chicken** [comment]
特定のチャンネルに対して他人の無関係のノートを Renote しまくる荒らし行為は、Renote に対して通報を発行すべきなど

**Comment by syuilo** [comment]
ほむん
