### ISSUE TITLE
vitest 落ちてる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#11287]
https://github.com/misskey-dev/misskey/actions/runs/5561125165/jobs/10158584989

🤔

**Comment by syuilo** [comment]
謎

**Comment by saschanaz** [comment]
たぶんhappy-domのアップデートが問題？ 9a5bc78eb47d8fa4a3bcd6396b36d29e67d99cbb

**Comment by saschanaz** [comment]
リポートして見ました https://github.com/capricorn86/happy-dom/issues/992
