### ISSUE TITLE
新着ノート通知音をデフォルトオフにしておく

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11296]
## Summary

すべてのノートに反応するのでうるさい（→どっちにしろ切る人が多い気がする）

Related to #10276

**Comment by syuilo** [comment]
うるさいと思った人は切ればいいだけと思われる(デフォルトでオフだと、うるさいと思わない人がわざわざ設定を見てオンにすることがなさそう)

**Comment by syuilo** [comment]
closeされた理由は何でしょう？

**Comment by kakkokari-gtyih** [comment]
> うるさいと思った人は切ればいいだけと思われる(デフォルトでオフだと、うるさいと思わない人がわざわざ設定を見てオンにすることがなさそう)

そのとおりだと思ったので（ちゃんと言ったほうが良かったですね、すみません）

**Comment by syuilo** [comment]
あるIssueを開いたままにしておくか、閉じるか(やるかやらないか)はMisskeyチームが判断します 🙏🏻

**Comment by kakkokari-gtyih** [comment]
了解です、気をつけます🙏
