### ISSUE TITLE
document.querySelectorAll('body *')が重い

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11303]
「任意の場所をクリックしたら何かをする」という処理を実現するために
``` ts
for (const el of Array.from(document.querySelectorAll('body *'))) {
	el.addEventListener('mousedown', onMousedown);
}
```
のようなコードを書いている個所がいくつかあるけど、DOMの数が多い場合負荷が高い

全ての要素に対してイベントを設定する以外に「任意の場所をクリックしたら何かをする」を実現する方法募集中

「画面いっぱいに広がるダミーの背景となる要素を作ってそれにイベントを設定する」方法が考えられる(実際モーダルダイアログとかの実装はすでにそうなっている)が、以下の問題があり、現在`document.querySelectorAll('body *')`を使っている場所全てで適用可能な方法とは思えない

- マウスカーソルのアイコンが下の要素のものを反映しない
- 背景要素をクリック/mousedownしたときに下の要素にイベントが伝わらない(やりようによっては伝えられるかも)

**Comment by syuilo** [comment]
コンテキストメニューなら「マウスカーソルのアイコンが下の要素のものを反映しない」場合でも問題ないけど、テキスト入力中に表示するオートコンプリートとかはそれだとユーザビリティが低下するから困る

**Comment by syuilo** [comment]
DOMとか関係なくマウスの状態を取得するAPIとかないかしら

**Comment by yahuli** [comment]
MkContextMenuとMkAutocompleteに対して
```document.querySelectorAll('body *')```じゃなくて```document.querySelectorAll('body')```に変えては何かの問題があるの？

**Comment by syuilo** [comment]
小要素はイベントをキャンセルすることができるから必ずしもbodyのイベントが発火するわけではない

**Comment by syuilo** [comment]
まあ実際キャンセルする場合多くないからbodyだけでいいか

**Comment by yahuli** [comment]
このプロジェクトはまだ完全に読んだことがないので、子要素イベントをキャンセルの例を挙げてもいですか
