### ISSUE TITLE
storybook buildまた落ちてる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#11318]
54c0ed2ed782307f5c40fcf90fa96d5f1702bf4c の後で壊れました

update depsをPRにして欲しいかも

**Comment by syuilo** [comment]
`Cannot access 'ro' before initialization`

roはResizeObserverかしら

**Comment by syuilo** [comment]
謎

**Comment by chocolate-pie** [comment]
おそらく↓で```Storage```が初期化される前に呼び出されていることが原因です。
https://github.com/misskey-dev/misskey/blob/ad9bb773c55418a94b9871dd7fd1dcf98c7c5bc5/packages/frontend/src/store.ts#L40

失敗しているジョブのChromaticを見ると圧縮を解除した状態で5656行目で```Storage```（この場合だと```ro```）が呼びだされていますが、```Storage```（この場合だと```ro```）が定義されているのは6747行目で、定義する前に呼び出されています。逆に成功したジョブのChromaticを見てみると（例えば[このジョブ](https://github.com/misskey-dev/misskey/actions/runs/5583686681/jobs/10204248324?pr=11032)）```Storage```が定義されているのは1978行目、呼び出されているのは全てその後になっています。

**Comment by syuilo** [comment]
Chromatic側の問題？

**Comment by chocolate-pie** [comment]
```sh
NODE_OPTIONS="--max-old-space-size=4096" pnpm run build-storybook && npx http-server ./
open "http://127.0.0.1:8080/storybook-static/?path=/story/components-mkabusereport--default"
```
これでローカルでも再現するのでChromatic側の問題ではないかも

**Comment by syuilo** [comment]
🤯

**Comment by syuilo** [comment]
解決方法が分からないから戻すしかないわね

**Comment by acid-chicken** [comment]
https://github.com/storybookjs/storybook/issues/23465#issuecomment-1638223449 ?

**Comment by syuilo** [comment]
> 解決方法が分からないから戻すしかないわね

戻したところで結局 https://github.com/misskey-dev/misskey/issues/11267 があるんだった

**Comment by acid-chicken** [comment]
これわけわかんないし一旦 play 吹き飛ばそうぜ
