### ISSUE TITLE
お知らせ機能の強化

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11328]
全体としてのお知らせではなく、ユーザー個別に運営 or システムからお知らせを送りたい時がある

## ユースケース
- 規約違反した際の警告
- データのインポート/エクスポートジョブが完了/失敗したときの通知

## 実装案
- 「お知らせ」に「あなた宛て」タブを作る？
- 通知の種類にお知らせを追加する？
- その他？

Related #7151

**Comment by syuilo** [comment]
規約違反した際の警告とか、必ず読んでほしいお知らせの場合、Misskey Webアクセス時にダイアログで強制的に表示するとかもしたいから、そうすると「通知の種類として『お知らせ』を新設する」はちょっと違うかも

**Comment by syuilo** [comment]
そのお知らせに対してユーザーが返信したりできるようにするかによっても実装が変わる

**Comment by syuilo** [comment]
返信までできるようにすると急激に実装コストが跳ね上がるから多分やらない

**Comment by tamaina** [comment]
そういうロールのユーザーからダイレクトノートが届くと目立つように表示されるみたいな感じでいいのでは

**Comment by syuilo** [comment]
送信元ユーザーの存在が必要なのは微妙

**Comment by YTJVDCM** [comment]
既存の通知カラムに表示 + クライアント起動時に画面全体に表示(アップデート時の表示みたいな感じで)とかはどうでしょう?
通知内容に重要フラグをつけて、重要な内容であれば画面全体表示や一定期間は常時最上部に表示を行うとかでも

**Comment by syuilo** [comment]
通知は揮発性がある設計だから見逃して困るような重要な情報は置きたくないというのがある

**Comment by syuilo** [comment]
announcementに宛先ユーザーと表示の仕方を設定できるようにするのが一番良さそう

**Comment by syuilo** [comment]
表示の方法
- お知らせページ掲載(今まで通り)
- お知らせページ掲載 + バナー表示
  - メンテナンスのお知らせとか
- お知らせページ掲載 + ダイアログ表示
  - 何らかの警告とか

**Comment by syuilo** [comment]
あとバナー表示とかにする場合、新規ユーザー/長期間使っていなかったユーザーだと過去のお知らせの表示で埋め尽くされかねないから、お知らせの期限を設定できるようにしたり、登録以前のお知らせは既読扱いにするようにしたい

**Comment by syuilo** [comment]
期限を設定できるようにするのもそうだし、管理者が手動でお知らせを済んだものとしてマークできるようにしたい(削除だと後から見直せないのが不便そう)

**Comment by syuilo** [comment]
あとメールで送るかどうかも設定できるようにしてもいいかもしれないけど、読んだかどうかを判定できないからMisskey開いたときにすでに見たお知らせが再度表示されることになるのは微妙

**Comment by syuilo** [comment]
やるか

**Comment by syuilo** [comment]
バナーとかダイアログで表示することを考えるとMisskey Web読み込み時に何らかの方法でannouncementsを取得する必要があるな

**Comment by syuilo** [comment]
metaで良いかしら

**Comment by syuilo** [comment]
metaに入れちゃうとキャッシュできなくなるな(announcementはユーザーによって異なる可能性があるため)

**Comment by syuilo** [comment]
あんまり読み込み時のリクエスト増やしたくないけどapi/announcements叩かせるしかないか

**Comment by syuilo** [comment]
効率のみ考える場合 api/i に入れるのが良さそうだけど不自然

**Comment by syuilo** [comment]
既にhasUnreadAnnouncements返してるしそこまで不自然でもないか

**Comment by Sayamame-beans** [comment]
過去に送信済みのお知らせについて、管理者側が表示順を並び替えられる機能もあると嬉しいかなと思うのですが、いかがでしょうか?
> 通知は揮発性がある設計だから見逃して困るような重要な情報は置きたくないというのがある

というコメントから、お知らせとして置くべきものでは無いのかもしれませんが、重要度が比較的低いお知らせが上の方に残ってしまい、後から来た方が気付きづらいことがあります。
"重要なお知らせ"という区分が出来たとしても、その中の古い物の方が重要度が高いようなケースで、見逃されやすい可能性があるかもしれません…?

**Comment by syuilo** [comment]
> 効率のみ考える場合 api/i に入れるのが良さそうだけど不自然

iに入れると非ログイン時にお知らせ表示できないわね
