### ISSUE TITLE
request for uzbek localization

### ISSUE THREAD

**Issue by orzklv** [syuilo/Misskey#11331]
## Summary

I'm from Uzbekistan and I'm really interested on the project. For the time being, I'd like to contribute to the project by adding Uzbek localization. Therefore, I wanted ask whether can we get Uzbek localization file?

**Comment by rafucuk** [comment]
You can use crowdin for translation but I think there is only translation from japanese. I suggest that you can duplicate "locales/en_US.yml" and translate by hand or you can use crowdin's multilingual and select Uzbek & English at the same time.
![image](https://github.com/misskey-dev/misskey/assets/33981808/64a968a7-0559-4991-9a78-f2f49d2e1674)

**Comment by rafucuk** [comment]
I realized there is no Uzbek language file, sorry for misunderstanding.

**Comment by aelloc** [comment]
so we can create file for Uzbek language, right?

**Comment by orzklv** [comment]
it has been added and under heavy contribution... i'd like to show my gratitude for letting us translate this project and make it accessible for uzbek people!
https://crowdin.com/project/misskey/uz
