### ISSUE TITLE
チャンネルを開いている最中通常のノートボタンを隠す or something

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#11344]
## Summary

チャンネルに投稿するつもりでLTL投稿してしまうのを防ぎたい

1. デフォルトレイアウト/クラシックレイアウトで現在のページがチャンネルのボタンのときに通常のノートボタンを…
    1. 隠す
    2. 押したときに、チャンネルを投稿先にする
2. チャンネルを開いているときの投稿ショートカットを押したときに
    1. 反応しない
    2. 投稿先をチャンネル宛に変更する

**Comment by EbiseLutica** [comment]
> 押したときに、チャンネルを投稿先にする

で良さそう。既存のボタンを消すと「チャンネルに投稿するボタンがなくなった」と誤解されそうなので、初回のみバルーンでヒント出してあげたい
