### ISSUE TITLE
Androidでフォント/表示サイズを変更するとサーバー紹介画面でのチャートの表示が壊れる

### ISSUE THREAD

**Issue by Skyvvv2** [syuilo/Misskey#11349]
## 💡 Summary

Androidでフォントサイズや表示サイズを変更して使用している場合、サーバー紹介画面でのチャートの表示がおかしく表示されてしまう

## 🥰 Expected Behavior

![Screenshot_20230722-180426](https://github.com/misskey-dev/misskey/assets/140240244/cb6f17b4-0dcc-4524-b5a0-584431d20670)

## 🤬 Actual Behavior

![gif-20230722-180511](https://github.com/misskey-dev/misskey/assets/140240244/f63291f3-bc4d-4b5f-a57a-51d6d0ee50f3)

![gif-20230722-180708](https://github.com/misskey-dev/misskey/assets/140240244/42b16318-b7b0-4dc3-9af5-d1157a1335ee)

## 📝 Steps to Reproduce
（1つ目のgif）
1.Androidのディスプレイ設定からフォントサイズを標準以外の大きさにする(私の環境では4段階あり、標準以外の全てがだめだった)。

2.https://ikaskey.bktsk.com/  等、適当なサーバーを開く。

(2つ目のgif)
1.Androidのディスプレイ設定から表示サイズを「大」(4段階中の下から3つ目の大きさ)にする

2.https://ikaskey.bktsk.com/  等、適当なサーバーを開く。

## 📌 Environment
13.14.1

### 💻 Frontend
* Model and OS of the device(s):
Android 12; motorola edge 20 Build/S1RGS32.53-18-22-30
* Browser:
Chrome 114.0.5735.196
* Server URL:
https://ikaskey.bktsk.com/
* Misskey:
13.14.1

**Comment by futchitwo** [comment]
- related to  #10604
