### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by iambeingtracked** [syuilo/Misskey#11353]
## 💡 Summary

Basically I can't build because `NODE_ENV=production pnpm run build` throws this out

> misskey@13.14.1 build /home/misskey/misskey
> pnpm build-pre && pnpm -r build && pnpm gulp

> misskey@13.14.1 build-pre /home/misskey/misskey
> node ./scripts/build-pre.js

Scope: 4 of 5 workspace projects
packages/misskey-js build$ tsc
└─ Done in 2.8s
packages/backend build$ swc src -d built -D
│ sh: swc: not found
└─ Running...
packages/frontend build$ vite build
└─ Running...
packages/sw build$ node build.js
└─ Running...
/home/misskey/misskey/packages/backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  backend@ build: `swc src -d built -D`
spawn ENOENT
 ELIFECYCLE  Command failed with exit code 1.
 
 (sorry I can't wrap it like code in markdown because github won't let me close it properly)
 
 At first it also couldn't find tsc, but I could install it with npm and then it couldn't find vite and swc and I also did an `npm install swc vite -g`, seems like vite is there but swc isn't

## 🥰 Expected Behavior

It should build
## 🤬 Actual Behavior

It doesn't
## 📝 Steps to Reproduce

1. Alpine Linux 3.8 in an LXC container
2. Try to build
3. Fail

## 📌 Environment

Alpine Linux 3.8 in an LXC container
Can't tell the version of Misskey as I couldn't install it but I did it today with the master branch

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: <!-- Example: docker compose, k8s/docker, systemd, "Misskey install shell script", development 
* Node: 20.5.0
* PostgreSQL: 15.3
* Redis: 7.0.12
Manual installation

**Comment by EbiseLutica** [comment]
@iambeingtracked If logs of `pnpm install` contain `Killed`, it may be the error is caused by the out-of-memory. Though it depends on the environment, in my environment, about 2GB of RAM is required to build Misskey.

**Comment by iambeingtracked** [comment]
@EbiseLutica Yes, I think logs of it did contain killed, but then I decided to give that LXC more RAM, so I now have 4 gigs, but it still doesn't build

**Comment by iambeingtracked** [comment]
Seems like it did really lack RAM, I raised the limit up to 8 gigs and after that it build successfully, closing the issue.
