### ISSUE TITLE
「もっと見る」ボタンを使用した後読み込まれるはずのコンテンツが正しく表示されない

### ISSUE THREAD

**Issue by Milix-M** [syuilo/Misskey#11355]
## 💡 Summary
「もっと見る」ボタンを使用した後読み込まれるはずのコンテンツが正しく表示されない

## 🥰 Expected Behavior

続きのコンテンツが正しく表示されるようになる

## 🤬 Actual Behavior

コントロールパネル内のユーザー一覧、サーバー情報の連合ページ等に設置されている「もっと見る」ボタンを使用した後に読み込まれるべきコンテンツ(ページの続き)が正しく表示されない。(GIF参照.)

![無題の動画-Made-with-Clipchamp](https://github.com/misskey-dev/misskey/assets/70957923/c99c6655-4757-4751-b12c-069451aa6108)

## 📝 Steps to Reproduce

1. {サーバーURL}/about#federation　等「もっと見る」ボタンが設置されているページを開く
2. 「もっと見る」ボタンをクリックする
3. ページを下方向にスクロールする

## 📌 Environment

Misskey 13.14.1

### 💻 Frontend
* Model and OS of the device(s):
Windows11 22H2, Android 13; Pixel6a Build/TQ3A.230605.010
* Browser:
Chrome 114.0.5735.248, Chrome(Android) 114.0.5735.196
* Server URL:
kawaiivrc.site
* Misskey:
 13.14.1

### 🛰 Backend (for server admin)

* Misskey: 13.14.1
* Node: v18.17.0
* PostgreSQL: 15.3(Ubuntu 15.3-1.pgdg22.04+1)
* Redis: 7.0.12
* OS and Architecture: Ubuntu 22.04 aarch64

**Comment by syuilo** [comment]
謎

**Comment by tamaina** [comment]
MkPagination壊した？と思ってリクエストを探ったところ...

## 1回目

要求: `limit: 10`  
応答: `misskey.io, sushi.ski, misskey.cf, ...`

## 2回目

要求: `limit: 30, offset: 10`  
応答: `misskey.io, sushi.ski, misskey.cf, ...`

## 3回目

要求: `limit: 30, offset: 40`  
応答: `misskey.io, sushi.ski, misskey.cf, ...`

となったので、 081a14d6f3ca3664aabdd06aaf06080dcba17c25 のせいでoffset式ページングのAPIが壊れたっぽい

**Comment by kleuzjatob** [comment]
本チケットの Actual Behavior にコンテンツが勝手に消える現象が映っていますが、これがv13.14.2でも直っていない様です。
ページングという点では直っていますが勝手に消える方が依然続いております。
joinmisskeyからv13.14.2で動いているサーバの /about#federation をサンプリングに巡りましたが全てで発生している様です。
少なくとも手持ちのPC上のGoogle ChromeとFirefoxでは発生しており、おま環とは考えにくいです。
画面の縦幅が発生条件を握っている（少なくとも1080pxでは発生）？と一時的に縮めて対応するもそれでも偶に発生したり、発生条件が判りませんが…。

**Comment by tamaina** [comment]
フロントエンドのページネーションの「スクロールを上に持っていったらdisplayLimitだけ表示する」という処理が悪さしてそう

**Comment by tamaina** [comment]
50ぐらいにしてみた

https://github.com/misskey-dev/misskey/commit/722a731c267bdb647c1a0b532c053fb70d3b72d6

**Comment by kleuzjatob** [comment]
https://github.com/misskey-dev/misskey/commit/722a731c267bdb647c1a0b532c053fb70d3b72d6 は /about#federation にのみ対応された物でしょうか？他の画面にも対応が必要そうです。
https://github.com/misskey-dev/misskey/issues/11904
