### ISSUE TITLE
開いたメディアをEscapeキーで閉じれない

### ISSUE THREAD

**Issue by nekobato** [syuilo/Misskey#11364]
## 💡 Summary

メディア表示に使用している`PhotoSwipeLightbox`はデフォルトで`Escape`キーによる閉じる動作を持っているが、
メディアを開いた後、`Escape`キー入力はMisskey Noteのキーボードショートカット設定に吸われてしまう

グローバルショートカットキー改修に踏み込まずとも`PhotoSwipeLightbox`にfocusTrapを実装すれば正しく動作する模様、そしてfocusTrapの方がa11y上正しくはある

問題なければPR作ります

## 🥰 Expected Behavior

メディアを開いた後、ユーザーは`Escape`キーを押すことで`PhotoSwipeLightbox`は閉じることができる

## 🤬 Actual Behavior

- Chrome (114.0.5735.106): 反応なし
- Safari (16.5): 2回連続でEscを押すと閉じる
- Firefox (103.0.1): 反応なし
- Edge ( 115.0): 反応なし

## 📝 Steps to Reproduce

1. タイムラインからメディアを開く
2. そのままマウス操作せずに`Escape`キーを押す

### 💻 Frontend
* Model and OS of the device(s): Macbook Air (M2), macOS Ventura 13.4
  
* Browser: Actual Behaviorに記述
* Misskey: 13.14.1 develop

**Comment by kanade** [comment]
このissueに進展はないでしょうか

**Comment by samunohito** [comment]
@syuilo @kakkokari-gtyih 
👀

**Comment by zyoshoka** [comment]
#14157 で直った気がします

**Comment by kanade** [comment]
developブランチを実行したところ、Escキーで画像を閉じられることが確認できました！
ありがとうございます！
