### ISSUE TITLE
ユーザ詳細ページから特定のチャンネル投稿を見えなくしたい

### ISSUE THREAD

**Issue by meronmks** [syuilo/Misskey#11376]
## Summary
#11270 に少し関連して、チャンネルへの投稿をゾーニング目的として利用していた場合
ユーザ詳細ページから投稿が見えると少し困ってしまうことがあるため、何らかの形で表示・非表示を決められると良いかもしれません。
理想はユーザーが個別で設定できることですが、チャンネル単位でもいいかもしれません。

**Comment by EbiseLutica** [comment]
APIとしては `/users/notes` のみの配慮で良さそう？

**Comment by syuilo** [comment]
そうね

**Comment by anatawa12** [comment]
一応にりら部的にはクライアント処理でhideしてます。見れなくなるのが正しいとは思ってないので

- https://github.com/niri-la/misskey.niri.la/pull/35
- https://github.com/niri-la/misskey.niri.la/pull/46
