### ISSUE TITLE
Can't bulk import emoji

### ISSUE THREAD

**Issue by iambeingtracked** [syuilo/Misskey#11374]
## 💡 Summary
I am not able to import emojis. Just to test this I made a folder with all of the emojis I need, followed the [guide](https://misskey-hub.net/en/docs/admin/emoji.html) and tried to make one work, here's the meta.json:
```
class Meta {
	metaVersion: number;
	host: string;
	/**
	 * Date and time representation returned by ECMAScript `Date.prototype.toString`.
	 */
	exportedAt: string;
	emojis: Emoji[];
}

class Emoji {
	downloaded: true;
	fileName: alert-blue.gif;
	emoji: {
		name: alert-blue;
		category: things;
	};
}
```
then I packed it all into a zip, and tried importing. This is what the logs say:
` ERR  1	[queue import-custom-emojis]	SyntaxError: Unexpected token 'c', "class Meta"... is not valid JSON `

## 🥰 Expected Behavior
They should import and proper syntax should be used

## 🤬 Actual Behavior
It doesn't import

## 📝 Steps to Reproduce

1. Be an admin of a Misskey instance
2. make a zip archive with meta.json (code above) and a corresponding file
3. Try importing it

## 📌 Environment

Misskey is ran in Alpine Linux 3.8 LXC container
### 💻 Frontend
* Model and OS of the device(s):
GNU/Linux
* Browser:
  
  Firefox 115.0.2
* Server URL:
  
  mk.wherelinux.xyz
* Misskey:
  13.14.1

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
Manual installation
* Misskey 13.14.1
* Node: 20.5.0
* PostgreSQL: 15.3
* Redis: 7.0.12
* OS and Architecture: x86-64

**Comment by syuilo** [comment]
That example only represents the data structure in terms of classes for convenience, and does not mean that the actual data is described in that way. The actual meta information is expressed in JSON.

**Comment by iambeingtracked** [comment]
Found out how to make it work, here's a sample
```
{
  "metaVersion": 2,
  "emojis": [
    {
      "fileName": "alert_blue.gif",
      "downloaded": true,
      "emoji": {
        "name": "alert_blue",
        "host": null,
        "category": "things",
        "uri": null,
        "type": "image/gif",
        "aliases": [],
        "license": null,
        "localOnly": false,
        "isSensitive": false,
        "roleIdsThatCanBeUsedThisEmojiAsReaction": []
      }
    },
    {
      "fileName": "alert_red.gif",
      "downloaded": true,
      "emoji": {
        "name": "alert_red",
        "host": null,
        "category": "things",
        "uri": null,
        "type": "image/gif",
        "aliases": [],
        "license": null,
        "localOnly": false,
        "isSensitive": false,
        "roleIdsThatCanBeUsedThisEmojiAsReaction": []
      }
    }
  ]
}
```
