### ISSUE TITLE
v13.14.1 でユーザーリストの[もっと見る]が機能しない

### ISSUE THREAD

**Issue by 49372s** [syuilo/Misskey#11373]
## 💡 Summary
v13.14.1において、[コントロールパネル][ユーザーリスト]のもっとみるボタンが機能しません。

## 🥰 Expected Behavior
もっと見るが機能し、全ユーザーが見れる

## 🤬 Actual Behavior
もっと見るを押しても読み込みスピナーだけが表示され、もっと見るボタンが元に戻り、最初の数人のみしか見ることができない

## 📝 Steps to Reproduce

1.コントロールパネルを開く
2.ユーザーを開く
3.もっと見るを押す
4.発生する

### 💻 Frontend
* Model and OS of the device(s): Windows 10
  
* Browser: Microsoft Edge 115.0.1901.183
  
* Server URL: https://m.tkngh.jp
  
* Misskey:
  13.14.1

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.14.1
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture: Ubuntu Server 20.04 LTS

**Comment by prlg25** [comment]
https://github.com/misskey-dev/misskey/issues/11355

これと同じですかね
私も発生していて、困っています

**Comment by tamaina** [comment]
Duplicate of #11355
