### ISSUE TITLE
プライバシーポリシーを設定できるようにする

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11385]
## Summary

利用規約のほかにプライバシーポリシーを設けるインスタンスが一般敵っぽい

**Comment by acid-chicken** [comment]
ついでにガイドラインも（利用規約と分けて）追加したい

**Comment by syuilo** [comment]
どんな内容を想定してる？

**Comment by acid-chicken** [comment]
センシティブの使い方や、ローカル TL などのローカルルールなど？

**Comment by syuilo** [comment]
ほむん

**Comment by acid-chicken** [comment]
Misskey じゃないけど UGC サービスは設けがち

https://site.nicovideo.jp/base/guideline
https://www.pixiv.net/terms/?page=guideline
https://www.tiktok.com/community-guidelines/ja-jp/

**Comment by tamaina** [comment]
サーバールールとかアカウントの追加情報みたいに好きなだけ登録できるようにすればいいんじゃね

**Comment by syuilo** [comment]
それはちょっと思った

**Comment by kakkokari-gtyih** [comment]
Done in #11925
