### ISSUE TITLE
画面の小さいデバイスから二要素認証を設定できない

### ISSUE THREAD

**Issue by Aila-dis-cord** [syuilo/Misskey#11390]
## 💡 Summary
・ビューポートの狭いスマートフォンから二要素認証を設定できない

## 🥰 Expected Behavior
・二要素認証設定UIをスクロールできる、またはボタンが画面内にある

## 🤬 Actual Behavior
・iPhone SE(第2世代)などで設定UIを開いた際、
　「次へ」ボタンが画面外かつスクロール不可なため操作できない
・QRコードがでっかい
・ドメイン名の長いサーバーだとURIが長くなり、追いやられたボタン要素が画面外にはみ出してしまう

## 📝 Steps to Reproduce
1.ビューポートを375x667px(以下)に設定する
2.二要素認証の設定UIを開く
3.「デスクトップアプリでは次のURIを入力します:」で表示されるURIのドメイン部分を28文字にする

### 💻 Frontend
* Model and OS of the device(s):
  iPhone SE (2nd generation) - iOS 16.5.1 (c)
* Browser:
  Safari/604.1

* Server URL:
  [misskey.always-we-need.games](https://misskey.always-we-need.games/)
* Misskey:
  13.13.2

**Comment by tamaina** [comment]
13.14.2で修正されます
