### ISSUE TITLE
CURRENT_URLを改善する

### ISSUE THREAD

**Issue by setaria430** [syuilo/Misskey#11392]
## Summary

以前のIssue( https://github.com/misskey-dev/misskey/issues/11232 )で現在のURLを取得するPRを書いたが、変数代入では画面遷移後に再読み込みしなければURLが変化せず、使い勝手が良くないため関数での呼び出しに変えたい

これにより、プラグイン等何らかのトリガを元に実行するAiScriptでは再読み込み不要で表示中のURLを取得できる
また関数にするとall capsがそぐわないため他と格好を合わせる形(例 Mk:url)にしたい

**Comment by zyoshoka** [comment]
Fixed by #11393
