### ISSUE TITLE
画面を横画面にした後、縦画面にすると、ノートのフォントサイズが大きくなる

### ISSUE THREAD

**Issue by mf2fox** [syuilo/Misskey#11412]
## 💡 Summary
モバイル端末の画面回転機能を使い、タイムラインで画面を縦から横に回転させた後、縦に戻すとノートのフォントサイズが大きく表示されます。(既出だったらすみません)

## 🥰 Expected Behavior
ノートのフォントサイズが設定値通りに表示される。

## 🤬 Actual Behavior
ノートのフォントがクソデカくなる。

## 📝 Steps to Reproduce

1.タイムラインを開く
2.画面を横に回転させる
3.画面を縦に回転させる

### 💻 Frontend
device: iPhoneSE3 / iOS16.6
browser: safari(pwa)
misskey: 13.14.1 & 13.14.2

**Comment by futchitwo** [comment]
Duplicate of #11486
