### ISSUE TITLE
Pages(ページ)機能にてページリンクがエスケープされていない。

### ISSUE THREAD

**Issue by Misaki0331** [syuilo/Misskey#11418]
## 💡 Summary

任意の文字を入力できるため、ページのURLを指定する場所に制御文字を入れると自分のページからの遷移あるいは編集中に「ページを見る」をクリックした場合、ページが正常に遷移できない。
(例として「/」の場合、ページを閲覧する場所は制御文字を「%2F」とエスケープされているが、リンク先が「/」のまま)
以下の内容は「ページを見る」にカーソルを合わせた状態(左下にリンク先が表示されている)
![image](https://github.com/misskey-dev/misskey/assets/60120497/e5111aa3-3d72-4864-830e-650e42b6182b)
https://misskey.io/@ms/pages/a%3Ftest%3D1
![image](https://github.com/misskey-dev/misskey/assets/60120497/1ee13d12-cfbf-4f9f-ad70-1226f575ac19)
https://msk.nenohi.net/@MisakiTest/pages/path%2Fa%3Ftest%3D1

## 🥰 Expected Behavior

「a?test=1」とページリンクに指定された場合「https://{インスタンス名}/@{ユーザー名}/pages/a%3Ftest%3D1」にリンクする

## 🤬 Actual Behavior
上記の場合、エスケープされずに「https://{インスタンス名}/@{ユーザー名}/pages/a?test=1」にリンクされるのでページが見れない

### 💻 Frontend
* Model and OS of the device(s):
  Windows 11 Pro 64bit (GALLERIA XA7C-R38)
* Browser:
  Brave バージョン: 1.56.14 Chromium: 115.0.5790.114（Official Build） （64 ビット）
  Microsoft Edge バージョン 115.0.1901.188 (公式ビルド) (64 ビット)
* Server URL:
   misskey.io
   msk.nenohi.net
* Misskey:
  13.14.2-io.2 (misskey.io)
  13.14.2 (msk.nenohi.net)

**Comment by ZerglingGo** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/11171
