### ISSUE TITLE
Changes to account visibility settings (followers/follows, reactions) not reflected on other instances

### ISSUE THREAD

**Issue by SeleDreams** [syuilo/Misskey#11417]
## 💡 Summary

When an account on a misskey instance sets their follows/followers to private and/or reactions, this change does not get reflected on other instances and followers/follow count as well as reactions all stay public, this is potentially a problem as this basically make this setting useless in any federated instance.

## 🥰 Expected Behavior
followers/follows should be made private in other instances as well, same for reactions.

## 🤬 Actual Behavior
followers, follows stay public, same for reactions

## 📝 Steps to Reproduce
1. Set your follows to private in confidentiality settings of your instance
2. Check your account on another instance
3. The follow list and the reactions are all public

## 📌 Environment
13.14.1

### 💻 Frontend
* Model and OS of the device(s):
 Windows 11 PC 64-bit
 ryzen 7 3700x,rtx 2080, 32gb ram ddr4 3200mhz
* Browser:
  Brave Browser [Version 1.56.14 Chromium: 115.0.5790.114 (Official build) (64 bits)]

### 🛰 Backend (for server admin)
docker compose

**Comment by zyoshoka** [comment]
Closing this issue as there are separate, more active issues for each follower/follow and reaction topic: #13362, #12964
