### ISSUE TITLE
build fails on preparation step pnpm install

### ISSUE THREAD

**Issue by Martin1995** [syuilo/Misskey#11425]
## 💡 Summary

I was trying to build misskey on an arch kvm server while following the manual

## 🥰 Expected Behavior

`pnpm install --frozen-lockfile` installs all necessary dependencies

## 🤬 Actual Behavior
running the command fails after trying to install re2 it seems
```
misskey@random_server ~/misskey (git)-[master] % pnpm install --frozen-lockfile
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2511
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/misskey/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/@tensorflow/tfjs-core/4.4.0: 6.73 MB/6.73 MB, done
Downloading registry.npmjs.org/typescript/5.1.6: 7.15 MB/7.15 MB, done
Downloading registry.npmjs.org/@tensorflow/tfjs-layers/4.4.0: 6.01 MB/6.01 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.70: 15.3 MB/15.3 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.70: 18 MB/18 MB, done
Downloading registry.npmjs.org/three/0.154.0: 6.11 MB/6.11 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.56: 17.2 MB/17.2 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.56: 17 MB/17 MB, done
Downloading registry.npmjs.org/typescript/5.0.4: 7.05 MB/7.05 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.69: 15.3 MB/15.3 MB, done
Downloading registry.npmjs.org/@tsd/typescript/5.0.2: 9.4 MB/9.4 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.69: 18 MB/18 MB, done
Downloading registry.npmjs.org/@tensorflow/tfjs/4.4.0: 29.7 MB/29.7 MB, done
Progress: resolved 2511, reused 0, downloaded 2444, added 2511, done
node_modules/.pnpm/@nestjs+core@10.1.0_@nestjs+common@10.1.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core: Running postinstall script, done in 1.5s
node_modules/.pnpm/core-js@3.29.1/node_modules/core-js: Running postinstall script, done in 562ms
node_modules/.pnpm/sharp@0.31.3/node_modules/sharp: Running install script, done in 3.7s
node_modules/.pnpm/sharp@0.32.3/node_modules/sharp: Running install script, done in 3.5s
node_modules/.pnpm/bufferutil@4.0.7/node_modules/bufferutil: Running install script, done in 1s
node_modules/.pnpm/utf-8-validate@6.0.3/node_modules/utf-8-validate: Running install script, done in 593ms
node_modules/.pnpm/@swc+core@1.3.69/node_modules/@swc/core: Running postinstall script, done in 334ms
node_modules/.pnpm/@swc+core@1.3.70/node_modules/@swc/core: Running postinstall script, done in 346ms
node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script, done in 329ms
node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild: Running postinstall script, done in 359ms
node_modules/.pnpm/msgpackr-extract@3.0.2/node_modules/msgpackr-extract: Running install script, done in 643ms
node_modules/.pnpm/cypress@12.17.1/node_modules/cypress: Running postinstall script, done in 1.3s
node_modules/.pnpm/@tensorflow+tfjs-node@4.4.0_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, done in 20.6s
node_modules/.pnpm/msw@1.2.2_typescript@5.1.6/node_modules/msw: Running postinstall script, done in 575ms
node_modules/.pnpm/re2@1.19.1/node_modules/re2: Running install script...
 ELIFECYCLE  Command failed.
pnpm install --frozen-lockfile  263,81s user 237,47s system 231% cpu 3:36,35 total

```

## 📝 Steps to Reproduce

1. install necessary software
2. git clone misskey including all the git setup
3. start install

## 📌 Environment

OS: Arch Linux x86_64
Kernel Release: 5.18.12-arch1-1
Processor Type: Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
base and base-devel packages are installed

### 💻 Frontend 
-> (setup does not go far enough to specify a frontend)
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)
server specifications are under enviroment

* Installation Method or Hosting Service: installing manually on a kvm hosted server running system mentioned above
* Misskey: 13.14.2
* Node: 20.4.0-1
* PostgreSQL: 15.3-2
* Redis: 7.0.12-1
* OS and Architecture: Server specifications are under enviroment

**Comment by saschanaz** [comment]
Can you install re2 in a new Node.js project? Does it error too?

**Comment by Martin1995** [comment]
so far I tried if node-gyp builds it and it didn't throw an error.
I'll have to look in to it if I can add and install it in an independent node.js project.

**Comment by Martin1995** [comment]
just found the error,...
npm was missing all together...

the [manual](https://misskey-hub.net/en/docs/install/manual.html) says:
```
Dependencies 📦
[Node.js](https://nodejs.org/en/) (20.4.x)
[PostgreSQL](https://www.postgresql.org/) (15.x)
[Redis](https://redis.io/)
[FFmpeg](https://www.ffmpeg.org/)
```

but I after I installed the packages above pnpm was missing,...

thanks to you I found the problem as npm was also missing....

I couldn't know that as the official manual, which I was following along didn't mention to install those two packages as well,....

now after installing npm as well:

```
misskey@random_server ~/misskey (git)-[master] % pnpm install --frozen-lockfile
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2511
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2511, reused 2444, downloaded 0, added 0, done
node_modules/.pnpm/re2@1.19.1/node_modules/re2: Running install script, done in 2m 0.7s
node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext: Running postinstall scrnode_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext: Running postinstall script, done in 320ms
Done in 2m 34s
pnpm install --frozen-lockfile  30,73s user 36,81s system 43% cpu 2:34,32 total
```

thank you💖
your question made me find the problem

**Comment by saschanaz** [comment]
> npm was missing all together...

> but I after I installed the packages above pnpm was missing,...

I don't really follow what really happened, but congrats for solving the issue!

**Comment by Martin1995** [comment]
thank you💖
the official manual did not say that I had to install pnpm and npm...

**Comment by saschanaz** [comment]
`corepack enable` should install pnpm, and your system definitely had it as you were able to run pnpm. Not sure about npm, I don't understand how one could install Node.js without installing npm 🤔

**Comment by Martin1995** [comment]
well I think yay just installed nodejs...
I did a `yay -Sy nodejs postgresql redis ffmpeg` at first

but when I tried pnpm it didn't work at first,...

then a quick `yay -Sy pnpm` installed that,...
then these issues were happening
then I found out that npm was also not installed
so again `yay -Sy npm` and then it worked,...

but I didn't know `corepack enable` would also add the necessary software

**Comment by saschanaz** [comment]
So `yay` only installs Node.js without npm? That's interesting.

Anyway, it's worth mentioning that installing Node.js from package managers is not what I would recommend, as the installation behavior depends solely on each package manager: https://nodejs.org/en/download/package-manager

>Note: The packages on this page are maintained and supported by their respective packagers, not the Node.js core team. Please report any issues you encounter to the package maintainer. If it turns out your issue is a bug in Node.js itself, the maintainer will report the issue upstream.

**Comment by Martin1995** [comment]
If I had installed npm it would have installed nodejs and node-gyp as well

**Comment by saschanaz** [comment]
Generally npm is bundled with Node.js by default, thus the documentation. It might be worth noting in the doc that some package managers don't do that.
