### ISSUE TITLE
未読のお知らせの「わかった」をクリック・タップしてもその場で「わかった」が消えない

### ISSUE THREAD

**Issue by 417Nazuna** [syuilo/Misskey#11432]
## 🥰 Expected Behavior
「わかった」をクリックしてすぐに「わかった」ボタンが消える

## 🤬 Actual Behavior
何度クリックしても消えないが、クリックした判定はあるのか、すべての「わかった」をクリックすると通常時のようにメニュー欄のお知らせアイコンにつく未読時の緑丸アイコンは消える
また、「わかった」をクリックしてからお知らせのウィンドウ・ページを開きなおすと「わかった」は消える

Misskey: 13.14.2
AndroidとWindowsのGoogle Chromeにてこの症状を確認しています。

**Comment by tamaina** [comment]
あ〜
