### ISSUE TITLE
AndroidのFirefoxでドラッグ操作ができない。

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#11444]
## 💡 Summary

AndroidのFirefoxでドラッグ操作ができない。

## 🥰 Expected Behavior 

AndroidのFirefoxでプロフィールの追加情報欄の並べ替えやナビゲーションバーの設定で並べ替えができない。
AndroidのEdgeでは正常に動作した。

## 🤬 Actual Behavior

本来ならドラッグして並べ替えが可能なはずが動かない。

## 📝 Steps to Reproduce 

1. AndroidのFirefoxでプロフィールの追加情報欄やナビゲーションバーの設定より、並べかえを行う。

## 📌 Environment

Android 10
Mull Browser (Firefox fork) 
116.0.0 (Build #21160021), f24b2b787e+
GV: 116.0-20230801155828
AS: 116.0

### 💻 Frontend
* Model and OS of the device(s):
  P710 (Rakuten Hand) Android 10
* Browser:
  Mull Browser (Firefox fork) 116.0.0
* Server URL:
  misskey.04.si
* Misskey:
  13.14.2-pie.1

**Comment by saschanaz** [comment]
Firefox 116.0, Firefox Nightly 118.0a1 2023-08-01 両方で「基本設定➡️プロフィール➡️追加情報を編集」の並べ替えに問題はありませんでした🤔

**Comment by ghost** [comment]
追加情報

有効Addon
- Firefox Relay
- Misskey Now
- Offline QR Code
- TWP
- User-Agent Manager

**Comment by ghost** [comment]
116.0.0 (Build #21160021), f24b2b787e+
GV: 116.0-20230801155828
AS: 116.0
にアップデートしましたが不可能でした。

**Comment by ghost** [comment]
> 追加情報
> 
> 有効Addon
> 
>     * Firefox Relay
> 
>     * Misskey Now
> 
>     * Offline QR Code
> 
>     * TWP
> 
>     * User-Agent Manager

全て無効化して試してみましたがだめでした。

**Comment by ghost** [comment]
他サイトでもドラッグ操作ができないこと、他のFirefox Forkブラウザではドラッグできることが分かりましたのでMullが原因だと思われます。
お騒がせしてすみませんでした。
