### ISSUE TITLE
misskey-jsのAPI Endpointsの情報が不足している？

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#11440]
## 💡 Summary

misskey-jsのAPI Endpointsの情報が不足している
## 🥰 Expected Behavior
emojisがEndpointとして利用できる

## 🤬 Actual Behavior
emojisがEndpointにない

## 📝 Steps to Reproduce

1. typescriptを用いてmisskey-jsからemojisをrequestしようとする
2. 存在しないのでエラーが起きる

## 📌 Environment

misskey-js 0.0.16

**Comment by tamaina** [comment]
（抜本的に解決しようと思ったPRは作ったけどデータの移行が面倒になって停滞している）

https://github.com/misskey-dev/misskey/pull/10752

**Comment by samunohito** [comment]
#12410 で生成されるようになっている＆/api-docで存在を確認したので、closeしてしまいますね。
