### ISSUE TITLE
server metrics widget not showing anything in v13.14.x

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#11459]
## 💡 Summary

After I upgraded my instance to v13.14.2, the server metrics widget is no longer showing anything.

## 🥰 Expected Behavior
Server metrics widget actually show you something.
![image](https://github.com/misskey-dev/misskey/assets/106132975/dae173dc-b7f9-44e2-8e23-de1e8b115c3e)

## 🤬 Actual Behavior
It's basically empty now. Both on my instance and on other instances such as misskey.io

![image](https://github.com/misskey-dev/misskey/assets/106132975/ea1835dd-3c54-43b8-96e2-df5ff411c320)

## 📝 Steps to Reproduce

1. add server metrics to your widget
2. have a look at it 
3.

### 💻 Frontend
* Model and OS of the device(s): macOS Ventura 13.4
  
* Browser: Firefox
  
* Server URL: 
  
* Misskey: 13.14.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.14.2
* Node: 19.7.0
* PostgreSQL: 15.2
* Redis: 5.0.7
* OS and Architecture: Ubuntu 20.04

**Comment by syuilo** [comment]
パフォーマンス上の理由で、デフォルトでサーバーのメトリックは無効になりました。コントロールパネルから有効にできます。
