### ISSUE TITLE
Can't follow user, stuck on processing

### ISSUE THREAD

**Issue by ewof** [syuilo/Misskey#11457]
## 💡 Summary

If you make an account and follow a remote user then delete the postgres db without unfollowing the user when you remake the db and make the account again you won't be able to follow that remote user, it will be stuck on processing. Misskey will create the remote and local user but the original account that followed the remote account without unfollowing it before the postgres db wipe cannot follow the remote account. If you unfollow the remote user before wiping the postgres db you can follow them when you remake your account after wiping the postgres db. Accounts with different usernames can follow the user just fine too.
## 🥰 Expected Behavior

It follows the user correctly
## 🤬 Actual Behavior

The follow request is stuck on processing.
## 📝 Steps to Reproduce

1. Create a misskey instance following https://misskey-hub.net/en/docs/install/manual.html
2. Create an account
3. Follow a remote user
4. Wipe the postgres db by dropping the table and user
5. Recreate the postgres db/user be following the instructions linked in step 1
6. Create an account with the same name as done in step 2
7. Try to follow remote user

## 📌 Environment

[b465bcd](https://github.com/misskey-dev/misskey/commit/b465bcd601d1c4b04ef804df5ce02ed12c853565)

### 💻 Frontend
* Model and OS of the device(s): pc with 5600x and a 3060 artix linux
  

* Browser: LibreWolf Firefox 116.0-1
  

* Server URL: misskey.marroq.xyz
* Misskey: 13.14.2
  

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.14.2
* Node: 20.5.0
* PostgreSQL: 15.3
* Redis: 7.0.12
* OS and Architecture: 5.15.0-78-generic Ubuntu SMP

**Comment by ewof** [comment]
if i try to send follow request manually to someone i was following before i deleted the db i get
```json
{
  message: 'Internal error occurred. Please contact us if the error persists.',
  code: 'INTERNAL_ERROR',
  id: '5d37dbcb-891e-41ca-a3d6-e690c97775ac',
  kind: 'server',
  info: {
    e: {
      message: 'duplicate key value violates unique constraint "IDX_d54a512b822fac7ed52800f6b4"',
      code: 'QueryFailedError',
      id: '59e7c5c9-c788-4c90-9a08-3673ae2cff7d',
    },
  },
}```

**Comment by ghost** [comment]
This is a known issue that has not been fixed yet. I have tested it multiple times, and the general observations are as follows:

1. Prepare two servers, SA, and SB. SA runs Mastodon, while SB runs Misskey.
1. Create user UA on SA and user UB on SB.
1. UA follows UB, and then use the Mastodon CLI command "tootctl account delete" to delete UA.
1. Confirm that SB can no longer retrieve UA's information properly.
1. Check SB's database and confirm the ID of the deleted UA.
1. Recreate user UA on SA and have them follow UB again.
1. At this point, an error appears in SB's server log, indicating that the user XXX cannot be found. XXX is a newly generated ID that cannot be found in SB's database.
1. After restarting server SB, using UA to follow UB again, this time the follow action is successful.

**Comment by ghost** [comment]
In summary, if you follow a remote user, and subsequently, due to some reason, your account or DB disappears, then until the remote server restarts or the cache expires, the deleted username will be unable to follow anyone on this remote server again.
