### ISSUE TITLE
can start via systemd

### ISSUE THREAD

**Issue by Canorus** [syuilo/Misskey#11452]
## 💡 Summary

can't start misskey server via systemd. manual start with `pnpm start` works. similar to #7008 but the issue was closed as stale.

## 🥰 Expected Behavior

misskey instance should start

## 🤬 Actual Behavior

log from `journalctl`

```
8월 03 16:07:12 ubuntu-desktop misskey[3453412]: > misskey@13.14.2 start
 8월 03 16:07:12 ubuntu-desktop misskey[3453412]: > pnpm check:connect && cd packages/backend && node ./built/boot/index.js
 8월 03 16:07:12 ubuntu-desktop misskey[3453423]: sh: 1: pnpm: not found
 8월 03 16:07:12 ubuntu-desktop systemd[1]: misskey.service: Main process exited, code=exited, status=127/n/a
 8월 03 16:07:12 ubuntu-desktop systemd[1]: misskey.service: Failed with result 'exit-code'.
 8월 03 16:07:13 ubuntu-desktop systemd[1]: misskey.service: Scheduled restart job, restart counter is at 5.
 8월 03 16:07:13 ubuntu-desktop systemd[1]: Stopped Misskey daemon.
 8월 03 16:07:13 ubuntu-desktop systemd[1]: misskey.service: Start request repeated too quickly.
 8월 03 16:07:13 ubuntu-desktop systemd[1]: misskey.service: Failed with result 'exit-code'.
 8월 03 16:07:13 ubuntu-desktop systemd[1]: Failed to start Misskey daemon.
```

## 📝 Steps to Reproduce

1. install as in documentation from https://misskey-hub.net/en/docs/install/manual.html#_1-install-dependencies
2. test by `pnpm run` from /home/misskey/misskey, and `sudo systemctl start misskey.service`
3. check log by `sudo journalctl -u misskey.service`

## 📌 Environment

Ubuntu 22.10
Kernel 5.19.0-46-generic

* Server URL:
msk.canor.kr
* Misskey:
  13.14.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: manual installation, systemd
* Misskey: 13.14.2
* Node: 18.17.0
* PostgreSQL: 15.3 (Ubuntu 15.3-1.pgdg22.10+1)
* Redis: 7.0.4-1
* OS and Architecture: Ubuntu 22.10

**Comment by MomentQYC** [comment]
`sh: 1: pnpm: not found`

**Comment by Canorus** [comment]
> `sh: 1: pnpm: not found`

Yes. But the thing is running 'pnpm start' manually actually works. I tried to add npnm path via environment but it didn't work. I ran out of ideas at that point.

**Comment by saschanaz** [comment]
I feel like this should go StackExchange instead as this is basically a Linux systemd question.

**Comment by Canorus** [comment]
understood. thanks.

**Comment by saschanaz** [comment]
If you are still having problem, maybe this can help: https://serverfault.com/questions/675505/why-systemd-service-files-dont-know-common-path

**Comment by Canorus** [comment]
for those of you who may come across this issue in the future:

check if `pnpm` PATH is declared in `~/.bashrc` or wherever that `~/.bashrc` refers. That's where bash looks at when starting non-interactive shell, in this case

```
User=misskey
```
