### ISSUE TITLE
【質問？　要望？】ナビゲーションバーのカスタマイズを他のブラウザに簡単にコピペしたい

### ISSUE THREAD

**Issue by 417Nazuna** [syuilo/Misskey#11468]
バージョン番号を忘れてしまったのですが、ナビゲーションバーがテキスト（`notifications`みたいなのを一行ずついれるあれ）だったときはテキストを全文コピペすればカスタマイズが他のサーバーやブラウザでも簡単に引き継げました。
しかし、最近（バージョン忘れた）のGUI形式になってからそれができなくなって困っています。
アカウント引継ぎの欄もたぶん違うしな……と困っています。

私はスマホやPCブラウザなどいくつかの環境でmisskeyを閲覧するのですが、閲覧環境を統一するのがこういった部分でちょっと手間になるのが困っています。
例えばブラウザの環境がAとBとCの３つあるとして、Aでちょっと変更をくわえ、それが良かったのでBとCにも適用しようと思うと、今の仕様はコピペできないので手動でポチポチするのが本当に大変です。

ほかにもリアクションの絵文字スロットはAとBとCとで統一されるのに、その列の数や高さなどは統一されないみたいな、他の部分においても機種間・ブラウザ環境間で引き継がれないところがちまちまあるのは手間になります。

とりあえず、優先順位が最も高いナビゲーションバーだけでもコピペできると嬉しいのですが、どうにかできないでしょうか？
検討のほどよろしくお願いいたします。

**Comment by tamaina** [comment]
「設定のバックアップ」をご利用ください。
