### ISSUE TITLE
リモートユーザーに付与したロールのバッジが表示されない

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11474]
## 💡 Summary
リモートユーザーに対してロールを付与すると、個人プロフィール上では権限バッジを確認できるものの、ノートのユーザー欄ではバッジが表示されない

## 🥰 Expected Behavior
![image](https://github.com/misskey-dev/misskey/assets/67428053/4fb93d77-150d-4ddc-bc70-18afde2d6420)

## 🤬 Actual Behavior
![image](https://github.com/misskey-dev/misskey/assets/67428053/c8afc2b1-a269-4177-8c99-c7257425871f)

## 📝 Steps to Reproduce

1. リモートユーザーにロールを付与
2. 当該ユーザーのプロフィールをローカルで参照

## 📌 Environment
Misskey v13.14.2-io.4

### 💻 Frontend
* Model and OS of the device(s): Surface Laptop Go 2, Windows 11 Version 10.0.22621.1992
  
* Browser: Google Chrome 115.0.5790.170 (Official Build) （64 ビット） (cohort: 115_170 Stable Control(A)) 
  
* Server URL: misskey.io
  
* Misskey: v13.14.2-io.4

**Comment by syuilo** [comment]
パフォーマンス上の理由によりこうなってます

**Comment by samunohito** [comment]
意図的であるため、仕様通りとしてcloseします
