### ISSUE TITLE
画像クロップの画質が悪すぎる

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#11489]
## 💡 Summary

Related to #8808

## 🥰 Expected Behavior

オリジナルのサイズのままクロップされる

## 🤬 Actual Behavior

MkCropperDialog の表示サイズまでバイリニアで縮小されたクロップデータがそのまま出力されている？

## 📝 Steps to Reproduce

1. 画像をアップロードする
2. MkCropperDialog に入る
3. クロップする

### 💻 Frontend
* Model and OS of the device(s):
  Mac mini (M1, 2020), macOS Ventura 13.4.1 (22F82)
* Browser:
  Firefox 118.0a1 (2023-08-07) (64-bit)
* Server URL: 
  p1.a9z.dev
* Misskey:
  13.14.2-p1.66

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/misskey/blob/c2370a1be631355e709c47d3b5e9469906116b84/packages/frontend/src/components/MkCropperDialog.vue#L66

ここ `getCropperSelection()?.$toCanvas()` じゃなくて `getCroppedCanvas()` じゃね

**Comment by tirr-c** [comment]
cropperjs v2は使い方がちょっと違います

https://fengyuanchen.github.io/cropperjs/v2/api/cropper-selection.html#tocanvas

ここで試してみても画質めっちゃ悪い

**Comment by tamaina** [comment]
メディアプロキシ周りの使い方が間違ってる説もありそう

**Comment by tamaina** [comment]
> メディアプロキシ周りの使い方が間違ってる説もありそう

ない

**Comment by tamaina** [comment]
> MkCropperDialog の表示サイズまでバイリニアで縮小されたクロップデータがそのまま出力されている？

っぽい

**Comment by tamaina** [comment]
> Reset the scaleX and scaleY values of the CropperImage to 1, and set the scalable property to false.
https://github.com/fengyuanchen/cropperjs/issues/998

こういう仕様らしい…？？？

**Comment by tamaina** [comment]
age

**Comment by kakkokari-gtyih** [comment]
これも内製するか…？（画像サイズに合わせたcanvasを裏で生成して、UIから与えられた範囲情報を拡大して当てはめたうえでクロップするぐらいしか思いつかなかった）

**Comment by tamaina** [comment]
> （画像サイズに合わせたcanvasを裏で生成して、UIから与えられた範囲情報を拡大して当てはめたうえでクロップするぐらいしか思いつかなかった）

そういうライブラリがあっても良さそうなのにどういうわけか見つけられない

**Comment by kakkokari-gtyih** [comment]
UIさえなんとかなれば切り抜きをする部分の構造自体は単純そうなのでなんとかなりそう

**Comment by tamaina** [comment]
なんとかならないから世の中にないのではとも思ったり

**Comment by tamaina** [comment]
（どうせなら回転とかしたいよねとか言い出すとキリがなくなる？

**Comment by kakkokari-gtyih** [comment]
> なんとかならないから世の中にないのではとも思ったり

cropper-js、クロッパーUIのdom内で完結させようとしてるのでは（ちゃんと見てない

**Comment by kakkokari-gtyih** [comment]
> （どうせなら回転とかしたいよねとか言い出すとキリがなくなる？

ウワーッ

**Comment by tamaina** [comment]
お

https://advanced-cropper.github.io/vue-advanced-cropper/guides/recipes.html#changing-a-stencil

**Comment by tai-cha** [comment]
これやりたいモチベが今ある

**Comment by tai-cha** [comment]
```ts
const croppedCanvas = await cropper?.getCropperSelection()?.$toCanvas({ width: 400 });
```
こういうの指定するとなんかきれいになるから上手くやれば上手くいくのかもしれない（画像も選択範囲もDOMを見ればよさそうなので力技でねじ伏せられる予感）

**Comment by tai-cha** [comment]
Cropper-jsのままでも実装自体はできそうだけどvue-advanced-cropperのほうがスマホでの使用感が良さそうな雰囲気も感じてはいる

**Comment by syuilo** [comment]
vue-advanced-cropper、OptionsAPIだった

**Comment by tamaina** [comment]
Options API、Composition APIから扱う上で何か不都合あるっけ？

**Comment by tai-cha** [comment]
cropper-jsを使用するFixは多分できた

**Comment by tai-cha** [comment]
> （どうせなら回転とかしたいよねとか言い出すとキリがなくなる？

上記PRで割りと簡単に直せちゃった感じがあるけどこっちも別issueにしてでもやりたさがある
