### ISSUE TITLE
PWAにする際Miのアイコンではなくサーバーのアイコンにしてほしい

### ISSUE THREAD

**Issue by waya0125** [syuilo/Misskey#11481]
## Summary
![image](https://github.com/misskey-dev/misskey/assets/42435123/8ca0dc82-24ad-4034-a49f-0d988df5aeb1)
~~把握している限りではスマートフォン環境を除き、PWAアプリとして作成する際に強制的に![image](https://github.com/misskey-dev/misskey/assets/42435123/c41e1735-7a1b-4227-8926-a32d43c085ac)のロゴになってしまう。~~
【2023/08/29追記】
iOS及びiPadOSを除いて![image](https://github.com/misskey-dev/misskey/assets/42435123/c41e1735-7a1b-4227-8926-a32d43c085ac)になっていました。
おそらく根本的にPWAの制御方式が違うからだと思われますがご参考までに。

![image](https://github.com/misskey-dev/misskey/assets/42435123/d9ec4988-197b-4413-bdc3-4f9beb99e629)
![image](https://github.com/misskey-dev/misskey/assets/42435123/fc21a4d8-dcce-4e21-8d98-52c3819293cd)
理想としてはサーバーのアイコンに設定されているアイコンをPWAする際に指定してほしい。
（現状ではビルド時に`packages/backend/src/server/web/manifest.json`をもとにする形になっているのでこれを変更すれば変えられる~~が非常に億劫である~~）

（一応[他のリポジトリ](https://codeberg.org/firefish/firefish#customize)ではサポートされている場合があるが公式でもこれを逆輸入してほしい）

**Comment by EbiseLutica** [comment]
manifest.jsonを動的生成する感じになるのかな

**Comment by syuilo** [comment]
manifest.jsonを動的に生成する必要はないけど動的に生成した方が名前とか変えられて便利そう

**Comment by EbiseLutica** [comment]
そっか、アイコンの方を動的にすればいいだけなのか

**Comment by tamaina** [comment]
manifest.jsonは動的に生成していいと思う

**Comment by syuilo** [comment]
やるか

**Comment by cobalto** [comment]
もしそれが可能であれば、お願いします。それはインスタンスのブランディングを向上させるでしょう。

**Comment by acid-chicken** [comment]
Related to #10901

**Comment by syuilo** [comment]
今iconsって
``` js
	'icons': [{
		'src': '/static-assets/icons/192.png',
		'sizes': '192x192',
		'type': 'image/png',
		'purpose': 'maskable',
	}, {
		'src': '/static-assets/icons/512.png',
		'sizes': '512x512',
		'type': 'image/png',
		'purpose': 'maskable',
	}, {
		'src': '/static-assets/splash.png',
		'sizes': '300x300',
		'type': 'image/png',
		'purpose': 'any',
	}],
```
みたいに定義してるけど、192x192消したら何か問題あるかな

**Comment by tamaina** [comment]
192は（たしかChromeあたりで）必要だから存在してるはず

**Comment by syuilo** [comment]
ふーむめんどくさい

**Comment by syuilo** [comment]
(大は小を兼ねるから良いやろ)

**Comment by tamaina** [comment]
> An icons property that includes a 192x192 px and a 512x512 px icon

https://developer.chrome.com/en/docs/lighthouse/pwa/installable-manifest/

**Comment by tamaina** [comment]
一回512だけにしてPWAがインストール不可になった時期があった記憶がある

**Comment by fruitriin** [comment]
げむすきのmanifest.jsonは以下のようにしてる

{"short_name":"ゲームすきー","name":"ゲームすきー","start_url":"/","display":"standalone","background_color":"#313a42","theme_color":"#86b300","icons":[{"src":"https://misskey.gamelore.fun/storage/files/7fff21fc-fefe-4868-885e-9114fe208c8f.png","sizes":"144x144","type":"image/png","purpose":"maskable"},{"src":"https://misskey.gamelore.fun/storage/files/7fff21fc-fefe-4868-885e-9114fe208c8f.png","sizes":"144x144","type":"image/png","purpose":"any"}],"share_target":{"action":"/share/","method":"GET","enctype":"application/x-www-form-urlencoded","params":{"title":"title","text":"text","url":"url"}}}

ここの書式が結構厳格で、sizesに指定したサイズとファイルの大きさがあってないといけないらしいのと、正方形である必要があるはず
https://developer.mozilla.org/ja/docs/Web/Manifest/icons

誤りがある場合、ChromeのDevtoolのアプリケーションタブに出ると思う
