### ISSUE TITLE
ドライブに上げたファイルの拡張子が変わる

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11482]
## 💡 Summary

ドライブに上げたファイルの拡張子が変わります

- `.unitypackage`が`.unitypackage.gz`に
- `.tgz`が`.tgz.gz`に
- `.jar`が`.jar.zip`に

動作からして内部的に使われている有名なファイル形式に誤判定を食らってます。

<details>
<summary>同様にバグりそうだと思ったけどバグらなかった例</summary>

- `.xlsx`はzipファイルであることが知られてますが`.xlsx`のまま問題なくuploadできました

</details>

## 🥰 Expected Behavior

`.unitypackage`/`.jar`のまま保存される

## 🤬 Actual Behavior

`.unitypackage.gz`/`.jar.zip`として保存される

## 📝 Steps to Reproduce

1. `unitypackage`や`jar`ファイルをドライブにアップロードする

### 💻 Frontend
* Model and OS of the device(s): `macOS 13.3.1 22E261 arm64`  `MacBookPro18,4`
  
* Browser: `firefox 114.0.2 (64 ビット)`
  
* Server URL: `misskey.niri.la` / `localhost:3000`
  
* Misskey: `13.14.2-kinel.3` / db5046ed

### 🛰 Backend (for server admin)

(localhost)
* Installation Method or Hosting Service:  development environment without dev container
* Misskey: db5046ed
* Node: `v18.16.0` installed via tj/n
* PostgreSQL: 15.x.x (docker image de94692755c6)
* Redis: 7.x.x (docker image edc5c8801dc6)
* OS and Architecture: `macOS 13.3.1 22E261 arm64`  `MacBookPro18,4`

**Comment by tamaina** [comment]
https://www.npmjs.com/package/file-type 由来っぽい

**Comment by tamaina** [comment]
拡張子を書き換えているのはMisskeyなので、書き換えないように例外を作る必要がありそう

**Comment by anatawa12** [comment]
そもそもなんですがファイルの拡張子を変える理由は何なんでしょうか

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/pull/10150 でなんとなく変えたけど変える必要ない気がしてきた

**Comment by tamaina** [comment]
（でもセキュリティとか整合性とかを考えると割と不安）

**Comment by anatawa12** [comment]
pngから変換されたwebp等必要な例は多少ありそうですが少なくともzip, gzのような汎用形式では中身がどんな形式が期待されてるかわからないので下手に変えてほしくないです(変更するにしてもblacklist等にしてほしいです)
