### ISSUE TITLE
Mk:apiの第三引数にnullを使いたい(トークン無しでエンドポイントを叩けるようにしてほしい)

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#11495]
## Summary

`Mk:api()`では第一引数にURLそのものを渡すことが出来るため、リモートのエンドポイントも叩くことが出来ますが、トークン情報はローカル用のものが付与されてしまうため、手動で上書きする必要があります。
第二引数内に入力した`i`プロパティは無視されるため、第三引数にトークンを入れて上書きすることになりますが、ここで`""`を渡すと空文字のトークンとして認識されて認証エラーに、`null`を渡すと以下の部分により型エラーとなります。
https://github.com/misskey-dev/misskey/blob/dc8a130570db0cd69dbd5a8a833a4913bbab1093/packages/frontend/src/scripts/aiscript/api.ts#L35-L40

第三引数に`null`を渡すことが出来れば、credentialが不要なエンドポイントをトークン無しでそのまま叩けるようになるはずです。

## 参考

第一引数でURLそのものを渡すことが出来る理由と思しき場所
https://github.com/misskey-dev/misskey/blob/dc8a130570db0cd69dbd5a8a833a4913bbab1093/packages/frontend/src/scripts/api.ts#L26
`null`を渡せばトークン無しで叩けると考える理由
https://github.com/misskey-dev/misskey/blob/dc8a130570db0cd69dbd5a8a833a4913bbab1093/packages/frontend/src/scripts/api.ts#L21-L23

追記:
ログアウト状態で`Mk:api()`を使った場合はtokenがnullになるようになっていました。
https://github.com/misskey-dev/misskey/blob/dc8a130570db0cd69dbd5a8a833a4913bbab1093/packages/frontend/src/scripts/aiscript/api.ts#L43
そのため、型チェックのところだけ修正出来れば対応出来そうですね…

**Comment by syuilo** [comment]
> Mk:api()では第一引数にURLそのものを渡すことが出来るため、リモートのエンドポイントも叩くことが出来ますが、

Mk:apiはそのサーバーのAPIを叩くことを想定しているので、リモートのエンドポイントを叩けてしまうことがバグかも

リモートサーバーのAPIを叩きたいユースケースがあるのであればそれ用の関数を新たに用意した方が良さそう

**Comment by Sayamame-beans** [comment]
> リモートサーバーのAPIを叩きたいユースケース

`Mk:api()`でリモートのAPIが叩ける挙動は、こちらのプラグインの作成に協力した際に発見しました。
> 当該ノートをリモートサーバーで開くメニューを追加するプラグインです
> https://misskey.io/notes/9i6v7qwpf5

ローカルで完結するプラグインならローカルのAPIが叩ければ問題無いですが、リモートの情報や自アカウントを絡めた動作を行いたい場合は必要になってくると思います。(例えば、投稿したノートを別のサーバーの自アカウントにRenoteさせるためのプラグインなど。この例はRenoteのためにトークンが必要ですが…)

(※この挙動を見つけるまでは、ローカルで完結しない動作を行う場合はブラウザ拡張を作成するしかないと思っており、それは面倒だな…となっていました)

**Comment by FineArchs** [comment]
将来的にPlayに権限を設定できるようになったら「外部との通信」の項目を入れてもいいかもしれませんね

**Comment by Sayamame-beans** [comment]
#11883 により目的が達成されなくなったのでCloseします。
