### ISSUE TITLE
他人が投稿したときに通知する機能

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11499]
## Summary

他人がnoteしたときに通知する(通知欄に乗せる)機能の需要を観測したのでissueにしました

https://misskey.niri.la/notes/9i7ek1rgvx

**Comment by tamaina** [comment]
アンテナを使えばいいかも

**Comment by Sayamame-beans** [comment]
アンテナでは、特定ユーザーの全投稿の取得と通知は出来ない(受信ワードが空のアンテナは作成出来ないようになっているため)と思っているのですが、出来るのでしたっけ…?
また、アンテナは通知欄に載らないと記憶しています。

**Comment by syuilo** [comment]
やるか
