### ISSUE TITLE
一度フォローしてその後フォローを解除したチャンネルの投稿がLTLに流れてきてしまう

### ISSUE THREAD

**Issue by yutaro1985** [syuilo/Misskey#11647]
## 💡 Summary

タイトルのとおりです。
あるチャンネルをフォローしたのですが、やはりNot for meだと思ってそのフォローを解除しました。
しかし、解除後もLTLには該当チャンネルで新規投稿された投稿がLTLに表示されてしまいます。
それらはブラウザ更新すると消えるのですが、その後も新規投稿されたものはLTLに表示されてしまいます。

## 🥰 Expected Behavior

- フォロー解除したチャンネルの投稿がLTLに表示されないこと。
- 新規投稿がLTLに追加されないこと。

## 🤬 Actual Behavior

- 一度フォローし、フォロー解除したチャンネルの新規投稿がLTLに表示されてしまう
- ブラウザを更新するなどして読み込み直すと追加された投稿は消える
  - 過去の投稿は消えるが、LTLを表示している間に新規投稿された分はLTLに表示される

## 📝 Steps to Reproduce

1. あるチャンネルをフォローする
2. 1.でフォローしたチャンネルのフォローを解除する
3. 2.でフォローを解除したチャンネルで誰かが新規投稿をする

### 💻 Frontend
* Model and OS of the device(s):
  
  MacBook Pro (14inch,2021),13.4.1（22F82）
* Browser:
  
  Sidekick 114.49.2.35027（Official Build） （arm64）
* Server URL: 
  
  https://misskey.systems
* Misskey:
  13.14.1

**Comment by syuilo** [comment]
キャッシュがあるので、しばらくすると消えます

**Comment by u1-liquid** [comment]
FYI: キャッシュが残ってるのが問題で、30分くらい経つと直ります

**Comment by u1-liquid** [comment]
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/CacheService.ts#L147-L147

フォローが解除された時このキャッシュを更新してあげる必要はありそう

**Comment by yutaro1985** [comment]
ご教示いただいた通り、少し間を空けて確認したところ消えていました。
失礼いたしました…。
