### ISSUE TITLE
カスタム絵文字の管理ウィンドウでスクロールできなくなる場合がある

### ISSUE THREAD

**Issue by AppleNectar** [syuilo/Misskey#11656]
## 💡 Summary

サーバー情報＞カスタム絵文字＞カスタム絵文字の管理 で開くウィンドウにおいて、ウィンドウを一定以上のサイズにした場合に絵文字のリストをスクロールしても先頭にもどされてしまい続きが見れない。

トリガーとなるウィンドウサイズ（以下どちらも満たした場合に発生）
横：826px 以上
縦：645px 以上

## 🥰 Expected Behavior

- カスタム絵文字の管理ウィンドウで絵文字のリストが正常にスクロールできること

## 🤬 Actual Behavior

- カスタム絵文字の管理ウィンドウで絵文字のリストをスクロールしても先頭に戻される

## 📝 Steps to Reproduce

1. 絵文字の管理権限を持つアカウントで、ページ左上のロゴをクリックして「サーバー情報」を開く
2. 「カスタム絵文字」タブを開く
3. 「カスタム絵文字の管理」ボタンを押下
4. 「カスタム絵文字の管理」ウィンドウのサイズが 826x645 px 以上になるよう拡大する
5. 「カスタム絵文字の管理」ウィンドウ内でスクロールを行う

### 💻 Frontend
* Model and OS of the device(s): Windows11 22H2 / LinuxMint 21.2
* Browser: Chrome 115.0.5790.170
* Server URL: sns.mochimochi-planet.com
* Misskey: 13.14.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: docker compose
* Misskey: 13.14.2
* Node: 20.3.1
* PostgreSQL: 15.3
* Redis: 7.0.11
* OS and Architecture: Ubuntu 22.04.2 LTS x86_64

**Comment by zyoshoka** [comment]
重複のためクローズします🙏

Duplicate of #11449
