### ISSUE TITLE
データセーバーモードでアカウントのアイコンを読み込まないようにする

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#11754]
## Summary

現状データセーバーモードを有効にしていてもアカウントのアイコンが読み込まれます。これは通信制限時など帯域が制限されている場合にかなり負担です (※通常、アカウントのアイコンではなくノートを見るはずです)。
そこで、データセーバー時にデフォルトのidenticonにフォールバックするかどうかの設定を追加してほしいです。

**Comment by kotonefami** [comment]
デフォルトのアイコンでもいいのですが、avatarBlurHash があるので、そこから読み込むのが一番見た目を落とさずに通信量を削減できるのかなと思いました。

**Comment by kakkokari-gtyih** [comment]
MkAvatarはデフォルトでavatarBlurHashを使っています

**Comment by kakkokari-gtyih** [comment]
アバターはたいていリンクとなっているため、データセーバー時にBlurhashで隠れる仕様にしてしまうと、アバターを見る術が非常に限られるので非現実的です。そのため代わりに #11814 は実装しました
