### ISSUE TITLE
webhookのペイロードにサーバー自体のルートのURLがほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#11751]
## Summary

misskeyのwebhookをdiscordに送りなおすツール(サーバ)作ってるのですがnote等のurlを構築する際にmisskeyのサーバーをwebhookを受ける側の知識として知っている必要があるのが汎用ツールとして作るための阻害となったためURLを渡してほしいです

**Comment by syuilo** [comment]
webhookを登録するにはそのサーバーのURLを知っている必要があるから受信者はURLは知っているのではないかしら

**Comment by anatawa12** [comment]
受信者本人は知っていますが受信者の登録するwebhookのproxyサーバーは知らない事が考えられます。

**Comment by anatawa12** [comment]
登録者は知っていますが登録するwebhookのproxyサーバーは知らない事が考えられます。

**Comment by anatawa12** [comment]
想定しているwebhook proxyサーバーの作りとして、誰かが立てたproxyサーバーを、別の人が任意のmisskeyサーバーでwebhookを指定することを想定しています。
この場合、proxyサーバーの作者は任意のmisskeyサーバーからのリクエストを想定するため、webhook送信元サーバーのURLの知識は(URL等で渡さない限り)ありません。
