### ISSUE TITLE
フォローしたチャンネルのノートを常にHTLに流したい

### ISSUE THREAD

**Issue by esperecyan** [syuilo/Misskey#11765]
## Summary

フォローしたチャンネルのノートについて、ユーザーをフォローしていなくても常にHTLに流すように出来ないでしょうか。

フォローしたチャンネルのノートは、リロードせずにHTLを表示し続けた場合に、その間に投稿されたノートは表示されますが、リロードしたりタイムラインを遡ったりすると、チャンネルのノートは表示されません。

タイムラインを切り替えずに、一度にフォローしているすべてのチャンネルのノートが見たいので、これを常に表示されるようにしたいです。

**Comment by samunohito** [comment]
@syuilo 
この件、notes/timelineに対してフォロー中のノートを結果に含めるような実装を入れても良いでしょうか？
問題なさそうであれば、プルリクを作成しようと思います

**Comment by syuilo** [comment]
> @syuilo この件、notes/timelineに対してフォロー中のノートを結果に含めるような実装を入れても良いでしょうか？ 問題なさそうであれば、プルリクを作成しようと思います

お願いします 🙏🏻

**Comment by samunohito** [comment]
@esperecyan 
リリースされましたので良さそうであればcloseお願いします:pray:

**Comment by esperecyan** [comment]
修正お疲れ様です！　有り難うございます！
