### ISSUE TITLE
たまにGitHub Actionsが失敗する

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11787]
![image](https://github.com/misskey-dev/misskey/assets/4439005/b83bd242-6504-4ffd-9c41-2e00e87f98bb)

**Comment by anatawa12** [comment]
https://github.com/actions/checkout/issues/1448
https://www.githubstatus.com/incidents/frdfpnnt85s8

**Comment by syuilo** [comment]
失敗したとき自動で何回かリトライできるようにできないかしら

**Comment by anatawa12** [comment]
そもそもgithub actionsのrunnerの初期化処理なので無理だと私は思います。issueではcheckout v4だと治るという話が多いので #11786 をマージしてみるのがいいと思います。
