### ISSUE TITLE
【v2023.9.0】 画像がビューワーではなく別ページで開いてしまう

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#11802]
## 💡 Summary

添付された画像をクリックしたときに、ビューワーではなく別ページで開くようになってしまってる

## 📝 Steps to Reproduce

1. 画像をクリックする
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser: Chrome 116.0.5845.142
  
* Server URL: mk.shrimpia.network
  
* Misskey: 2023.9.0-beta.5

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
謎だけど https://github.com/misskey-dev/misskey/commit/22d966e92dabffba23178a4afb5853882ba7249e をrevertしたら直った

**Comment by mappi-pr** [comment]
（メモ書き）
さっきシュリンピアとio比較して、クリック時にonThumbnailsClickが発火してないなぁって思ってました。。。

**Comment by kakkokari-gtyih** [comment]
> 謎だけど [22d966e](https://github.com/misskey-dev/misskey/commit/22d966e92dabffba23178a4afb5853882ba7249e) をrevertしたら直った

リンク / ビューワを発火しないオプションを実装する際に `@click` を `@click.stop` にしていました・・・すみません

https://github.com/kakkokari-gtyih/misskey/blob/87e36bbd0febd6f5fe3a8524a6a7f323812712c3/packages/frontend/src/components/MkMediaImage.vue#L6-L7

（修正済みPRを再度出しています #11806 ）
