### ISSUE TITLE
データセーバーモードでアニメーションするアバターのアイコンを止める

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#11814]
## Summary

データセーバーモードを有効にしてもアカウントのアバターがアニメーションする画像を使用していた場合、通常通り通信量に計上されるため、規模の大きいインスタンスをナローバンドで日常的に見る私のようなヘビーユーザーの通信制限の原因になっています。

これを解決するために、データセーバーモードではアバターがアニメーションする場合、1フレーム目など元画像から簡単に生成できる代替画像を使用することを提案します。

related #11754

**Comment by ibuki2003** [comment]
「アニメーション画像を再生しない」設定をするとアバター含めほとんどの画像が静止画として読み込まれるようです。
他にも影響が出るため完全な解決とはいきませんが、お試しください。
