### ISSUE TITLE
"Add Moderation Note" string can't be translated

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#11818]
## 💡 Summary

"Add Moderation Note" button label can't be translated, you can see into user profile's page view as administrator.

## 🥰 Expected Behavior

as translator I want to be able to translate this string on Crowdin

## 🤬 Actual Behavior

String is missing into Crowdin app.

## 📝 Steps to Reproduce

1. login as administrator
2. open a local profile
3. read "add moderation note" button in english

### 💻 Frontend
* **Misskey: 13.14.2**

* Installation Method or Hosting Service: docker compose, develop branch
* Misskey: 13.14.2

**Comment by mappi-pr** [comment]
@tassoman 
I have modified the program so that I can now add translations with crowdin.
Could you please confirm?

**Comment by tassoman** [comment]
Confirmed, I can translate strings into Crowdin app.

**Comment by EbiseLutica** [comment]
Fixed by #11819
