### ISSUE TITLE
ALT を設定してないファイルに対してクロップ機能を使用すると空文字の ALT が付与される

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#11813]
## 💡 Summary

SSIA

## 🥰 Expected Behavior

ALT が設定されない

## 🤬 Actual Behavior

空文字の ALT が設定される

## 📝 Steps to Reproduce

1. 画像をアップロード
2. 画像をクロップ
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  p1.a9z.dev, misskey.cloud
* Misskey:
  13.14.2

**Comment by tai-cha** [comment]
comment(日本語名: キャプション)だと思うので#11489のついでに直す
