### ISSUE TITLE
絵文字の名前の重複を確認する

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#11834]
## Summary
タイトル通りで現在のバージョン(2023.9.0-beta.6までのバージョン)では絵文字の名前が重複していても登録できてしまいます。
絵文字の名前が重複していたらエラーを吐いて登録できないようにするのが理想だと思われます。

**Comment by tai-cha** [comment]
まあもうちょっと前だけどねむすぎーフォークとかで対策してたりしたので参考にでも
FYI: https://github.com/Secineralyr/misskey.dream/pull/15/

**Comment by Sayamame-beans** [comment]
triage: インポート時が未チェックのまま？

**Comment by Sayamame-beans** [comment]
#10553
