### ISSUE TITLE
リアクションボタンの枠線でレイアウトシフトが起こる

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11842]
## 💡 Summary
リアクションのデザイン変更で、つけたリアクションにはborderが付く仕様になってるせいで若干レイアウトシフトが起こってしまっている

![image](https://github.com/misskey-dev/misskey/assets/67428053/329f2c5e-1014-4fc3-a39d-3ff074122048)

## 🥰 Expected Behavior
リアクションをクリックしてもレイアウトシフトが起こらない（ボタンが動かない）

## 🤬 Actual Behavior
borderがつくので、2pxくらい動く

## 📝 Steps to Reproduce

1. リアクションをつける

## 📌 Environment
p1.a9z.dev

### 💻 Frontend
* Model and OS of the device(s): Windows 11 22H2 (Version 10.0.22621.1992)
  
* Browser: Google Chrome 116.0.5845.180 (Official Build) （64 ビット） (cohort: Stable) 
  
* Server URL: p1.a9z.dev
  
* Misskey:
  2023.9.0-beta.6-p1.1

**Comment by syuilo** [comment]
good catch
