### ISSUE TITLE
Imprint and data protection general regulation

### ISSUE THREAD

**Issue by ThesiiNCey** [syuilo/Misskey#11845]
## Summary

Could you please give us the opportunity to edit the dashboard using the page editor so that you can, for example, place 2 buttons there that lead to an imprint and a general data protection regulation, as an example because in Germany it is mandatory that this is clearly visible on the home page

**Comment by kakkokari-gtyih** [comment]
@ThesiiNCey I think it is possible to write HTML for the "server description" that appears on every page that visitors without an account sees so you can add legal links in the field, but do you mean that it also needs to appear on the screen after logging in?

**Comment by ThesiiNCey** [comment]
Yes, unfortunately in Germany this has to be clearly visible on every page

**Comment by kakkokari-gtyih** [comment]
Oh no, that's going to require a new implementation...

**Comment by kakkokari-gtyih** [comment]
How about something like this? @ThesiiNCey 

- 運営者情報 … Impressum
- 利用規約 … Terms of service
- プライバシーポリシー … Privacy policy

![image](https://github.com/misskey-dev/misskey/assets/67428053/3909d6af-5778-4871-a22e-ba379d967c84)

![image](https://github.com/misskey-dev/misskey/assets/67428053/f277e7b2-dea8-4c37-acb7-3dd192dc3c42)
