### ISSUE TITLE
Dockerイメージがx86_64以外のアーキテクチャ向けにビルドできない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#11847]
## 💡 Summary
https://github.com/misskey-dev/misskey/commit/0d505f8131af0dd277d16ed9ecc6a8686edf7288
このコミットでjemallocが使用されるようになりましたが、ライブラリのパスがx86_64でハードコートされているためaarch64向けなどにビルドができません

## 🥰 Expected Behavior
x86_64以外のアーキテクチャ向けにもビルドできる

## 🤬 Actual Behavior
aarch64などではそのパスにライブラリが存在しないためエラーが発生

## 📝 Steps to Reproduce

1. docker build -t misskey:latest .
2.
3.

### 💻 Frontend
* Misskey:
  [2023.9.0-beta.6](https://github.com/misskey-dev/misskey/releases/tag/2023.9.0-beta.6)

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Docker
* Misskey: [2023.9.0-beta.6](https://github.com/misskey-dev/misskey/releases/tag/2023.9.0-beta.6)
* OS and Architecture: aarch64 ubuntu 22.04

**Comment by syuilo** [comment]
ふーむ
x86_64以外のアーキテクチャを使用するケースってどれくらいあるのかしら

**Comment by sim1222** [comment]
aarch64に関してはRaspberry Pi、AWS EC2のGravitonインスタンスやOracleCloudのA1、一部ではM1 macでサーバーを実行しているところを観測しています

**Comment by syuilo** [comment]
なるほど
アーキテクチャというのは変更するのは難しい感じかしら

**Comment by sim1222** [comment]
基本的にネイティブで実行しないと速度が圧倒的に劣ってしまうので、アーキテクチャの変更は難しい気がします。
主流はx86_64がほとんどですが、最近aarch64(arm)も増えてきているのでできればaarch64は対応してほしい気持ちがあります。
jemalloc自体は他のアーキテクチャにも対応しているのでdocker用に起動時のLD_PRELOADを動的に変える起動スクリプトを用意するといいかも

**Comment by syuilo** [comment]
とりあえずrevertするか

**Comment by tamaina** [comment]
ライブラリのパスがハードコードされていることだけが問題なんじゃん

**Comment by tamaina** [comment]
p1.a9z.devもaarch64で動いているし対応しておきたい

**Comment by tamaina** [comment]
メモ？

ENVでこれができるかわからんけど

https://zenn.dev/ytdrep/articles/d65c26201042eb
