### ISSUE TITLE
エラーが発生しサイトにアクセスできない

### ISSUE THREAD

**Issue by 2288-256** [syuilo/Misskey#11846]
## 💡 Summary

一部のios端末でエラーが発生しサイトにアクセスできない

## 🥰 Expected Behavior

一部のios端末で
```
ERROR CODE: SOMETHING_HAPPENED
"TypeError: undefined is not an object (evaluating 'e.getContext')"
```
が発生しサイトにアクセスできない

## 🤬 Actual Behavior

現在、手元にMacが無いためconsoleログが取得不可

## 📝 Steps to Reproduce

1. ログイン or 未ログインの状態でmisskeyを使用しているサイトにアクセスする
2. 発生

## 📌 Environment

少なくとも[13.14.2](https://github.com/misskey-dev/misskey/releases/tag/13.14.2)以降で発生
詳細はわからない

### 💻 Frontend
* Model and OS of the device(s): 
  iPadOS 16.6.1
  
* Browser:
  Safari/605.1.15
  
* Server URL: 
  misskey.io等のmisskeyを使った全サーバー
  
* Misskey:
  13.14.2以降(現在確認済み)

### 🛰 Backend (for server admin)

利用者のため取得不可

### 補足
アドブロッカーの無効化・キャッシュ削除・OS、ブラウザの最新版への更新
はすべてしています

**Comment by syuilo** [comment]
misskey.io以外で試されたサーバーを教えてください👀

**Comment by 2288-256** [comment]
未ログイン状態では
https://misskey.04.si/
https://mi.7mi.site/
が同様の不具合を確認できました。

ログイン状態で発生するのかは今から調査します

あと、misskey.ioになりますが
https://support.misskey.io/hc/ja/community/posts/7754448637583-エラーが発生してアクセスできない
にも報告があります

**Comment by 2288-256** [comment]
ログイン状態ですと
https://misskey.gamelore.fun/
https://misskey.cloud/
が同様の不具合を確認できました
(AndroidやWindowsでは正常に動作していてiosで開こうとするとmisskey.ioと同じエラーが発生しアクセスできない)

**Comment by syuilo** [comment]
うーむ謎

**Comment by syuilo** [comment]
他に発生する人いるかしら

**Comment by syuilo** [comment]
自分では再現しない

**Comment by CyberRex0** [comment]
iPadOS 17.0, Safari & Chrome で再現せず

**Comment by syuilo** [comment]
getContextはcanvas関連だろうけど何だろう

**Comment by syuilo** [comment]
`globalThis.OffscreenCanvas`が`undefined`になるときがある？

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
iPadOS 16.6.1ってOffscreenCanvas対応してるしなあ

**Comment by syuilo** [comment]
でもそこくらいしかundefinedになりそうな箇所がない

**Comment by syuilo** [comment]
ioの方では修正されたっぽい

**Comment by syuilo** [comment]
持ってくるか

**Comment by syuilo** [comment]
やっぱりOffscreenCanvasっぽいけどなぜundefinedになるのかは謎

**Comment by tamaina** [comment]
（最近のSafariはおかしいのでどういうバグが起きても不思議ではない）

**Comment by tamaina** [comment]
数日以内に騒ぎになっているということはおそらく16.6.1だけに起きている？

**Comment by tamaina** [comment]
globalThisにぶら下がってるのがtruthyで直接触っているのがundefinedならglobalThisにぶら下がってる方を使えばいいのでは

（空オブジェクトとかぶら下がってたら最悪だけど）

**Comment by riku6460** [comment]
undefined になるのは OffscreenCanvas が実装される前のバージョンか、Safari の設定から OffscreenCanvas を無効化することで再現できるはずです

**Comment by syuilo** [comment]
iPadOS 16.6.1でなってる人は自分で設定から無効にしてるってことかしら

**Comment by riku6460** [comment]
iOS/iPadOS 16.2以上17未満の場合はその可能性が高そうですね。確認してませんが、17からは実験的機能から外れてるっぽいので無効化できなさそう

**Comment by syuilo** [comment]
多分直った

**Comment by 2288-256** [comment]
不具合が発生していたiPadから正常に読み込めることを確認しました。
多分無いと思いますが、再発しましたら再度別のissueを開きますね
対応ありがとうございました

**Comment by syuilo** [comment]
確認されたサーバーってどこですか？

**Comment by 2288-256** [comment]
確認の結果
https://misskey.io/
https://misskey.gamelore.fun/
https://misskey.cloud/
は正常にアクセスができていて

https://misskey.04.si/
https://mi.7mi.site/
はいまだにアクセスができません(まだこの修正が入る前のバージョンを使用しているため)

なお、今回の不具合は[2023.9.0-beta.1](https://github.com/misskey-dev/misskey/releases/tag/2023.9.0-beta.1)以降のバージョンと[2023.9.0-beta.1](https://github.com/misskey-dev/misskey/releases/tag/2023.9.0-beta.1)以降のforkで確実に発生するエラーのようです
なお、[13.14.2](https://github.com/misskey-dev/misskey/releases/tag/13.14.2)のサーバーで一時的に発生していた原因は不明です
(https://misskey.gamelore.fun/ と https://misskey.cloud/ が該当)
