### ISSUE TITLE
スリープ無効化機能 (Screen Wake Lock API)

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11853]
## Summary

スマホ等の画面が消える端末をMisskey専用端末として使用する際などのためにスリープを無効化できる機能を設ける（Screen Wake Lock APIとか使ったらできたはず）

https://support.misskey.io/hc/ja/community/posts/7888892288655

**Comment by syuilo** [comment]
Firefox対応してないのか
