### ISSUE TITLE
リアルタイム更新(WebSocket)を無効化するオプションを追加

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11855]
## Summary

WebSocket経由の更新を無効化し、notes/timelineへのfetchだけでTLを更新するオプションを設ける（もうあるかもしれないが見当たらなかった）

https://support.misskey.io/hc/ja/community/posts/6737028225807-%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%A9%E3%82%A4%E3%83%B3%E8%87%AA%E5%8B%95%E6%9B%B4%E6%96%B0%E3%81%AE%E3%82%AA%E3%83%B3%E3%82%AA%E3%83%95%E6%A9%9F%E8%83%BD%E3%81%8C%E6%AC%B2%E3%81%97%E3%81%84

**Comment by syuilo** [comment]
これかしら
https://github.com/misskey-dev/misskey/issues/9119

**Comment by kakkokari-gtyih** [comment]
> これかしら #9119

手動でTLの強制再読み込みをかけるという点では共通しているけど、こっちではWebSocket経由での新着ノートの読み込みをしない設定を作りたいという点でちょっと違うかと

**Comment by kakkokari-gtyih** [comment]
タイトルを若干わかりやすくした
