### ISSUE TITLE
アンテナの収集対象をローカルのみにするオプションがほしい

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#11869]
## Summary

連合しているサーバー全てから収集したいアンテナもあるが、
エゴサのようにローカルのみを収集したいアンテナもある

**Comment by nakamu2473** [comment]
中村と言いますが、カレーの中村屋や中村玉緒さんが収集されてしまうためローカルのみにするオプション欲しいです！

**Comment by fruitriin** [comment]
全国のリンさんがひっかかってしまう
