### ISSUE TITLE
[2023.9.0 beta11] 1つのリアクションが30個以上ついているとき、「もっと見る」ボタンの挙動が怪しい

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#11868]
## 💡 Summary

なにか読み込みが行われているが読み込みに伴うガタツキが起きるだけで内容に変化はない

https://github.com/misskey-dev/misskey/assets/18308639/3e26437d-7ef4-4590-a8bc-b9c5b7bc82de

https://github.com/misskey-dev/misskey/assets/18308639/b3fd7fc0-6c41-4e96-8a5b-a0fe387c79f9

## 🥰 Expected Behavior

「もっと見る」を押すと31人目以降が見れる
（適切にページネーションされる）

もしくは「もっと見る」ボタンがない

## 🤬 Actual Behavior
再度リクエストを行っているが次のページを取得できていない

## 📝 Steps to Reproduce

1.
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
これは以前からありそう

**Comment by syuilo** [comment]
多分直った
