### ISSUE TITLE
(v2023.9.0-beta.11) リアクション一覧が種別ごとにフィルタできない

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11865]
## 💡 Summary
タイトル通りそのまま

## 🥰 Expected Behavior
リアクション絵文字を押すと、その絵文字を選んだユーザーごとにフィルタできる

## 🤬 Actual Behavior
押しても何もおこらない

## 📝 Steps to Reproduce

1. ノート詳細ページを開く
2. 「リアクション」タブを開く
3. リアクション絵文字のボタンを押す
4. うごかん

### 💻 Frontend
* Model and OS of the device(s): Windows 11 Version 22H2 (Build 22621.1992)
  
* Browser: Google Chrome v116.0.5845.188 (Official Build) （64 ビット） (cohort: Stable) 
  
* Server URL: https://misskey.cloud/ と https://misskey.cloud/
  
* Misskey:
  v2023.9.0-beta.11

**Comment by fruitriin** [comment]
Same here
https://github.com/misskey-dev/misskey/assets/18308639/e4af6fcb-013f-4f0b-bac7-1d85dfcefd4a

https://misskey.gamelore.fun/notes/9jxzv80g03

v2023.9.0-beta.11

**Comment by syuilo** [comment]
🙏🏻
