### ISSUE TITLE
AiScript: Mk:apiで外部サーバーのAPIを叩く時はトークンを付与すべきではない

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#11881]
## Summary
（そもそもMk:apiで外部サーバーを叩けるのが正しい仕様なのかは分かりませんが、）

現状ではMk:apiを使用すると（宛先が外部・内部の区別なく）リクエストに権限の小さいトークンが付与されるようになっています。

これは外部サーバーへのリクエストが不正なトークンにより弾かれる弊害を生むだけでなく、将来的にPlayなどに権限が設定されるようになった時、その権限を持つトークンを外部サーバーに流出させることができるというセキュリティ上の懸念にも繋がります。

よってMk:apiの宛先が外部である場合には、第三引数で明示的に設定された場合以外トークンを付与すべきでないと考えられます。

**Comment by syuilo** [comment]
Mk:apiは自サーバーのAPIを叩く目的なのでバグですね
