### ISSUE TITLE
Playを非公開にできない (2023.9.0-rc.3)

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#11884]
## 💡 Summary
Playを非公開に設定できず、パブリックになってしまいます

## 🥰 Expected Behavior
Playを非公開に設定できる

## 🤬 Actual Behavior
パブリックにしか設定できない

## 📝 Steps to Reproduce

1. Playを編集
2. 公開範囲を非公開にする
3. 保存を押す
4. 非ログイン状態で自分のプロフィールページに行ってPlayの項目を見ると作成したPlayが表示される

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
  Chrome 117.0.5938.92
* Server URL:
  
  https://mattyaski.co/
  https://mi.taichan.site
* Misskey:
  2023.9.0-rc.3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
@taichanNE30 🙏🏻
