### ISSUE TITLE
ノートのリアクションが多い場合に表示される「もっと！」がリンクにならない

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#11888]
## 💡 Summary

リアクション一覧の表示仕様が変わったことで、「もっと」ボタンの挙動が壊れている

押したら詳細表示に遷移し、かつリアクションタブが選択状態であると望ましい

あるいは全表示でもいいかも？

## 🥰 Expected Behavior

「もっと」ボタンによって追加のリアクションが表示される

## 🤬 Actual Behavior

ボタンになっていない

## 📝 Steps to Reproduce

1.
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser: Chrome 116.0.5845.188
  
* Server URL: mk.f72u.net
  
* Misskey: 2023.9.0
  

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/commit/907d519da36c550dde0a39970057bce22ffdcc5f#r139256130

これはなぜ

**Comment by tamaina** [comment]
（実装に深く関わった私が6ヶ月間気づかなかったという事実によってボタン機能はそんなにいらないことが証明されてしまった）（でも省略するとなるとボタン機能つける方が自然）

**Comment by 1STEP621** [comment]
(個人的にはボタン機能がないのまあまあ不便に感じています)

**Comment by tamaina** [comment]
Related to https://github.com/misskey-dev/misskey/pull/9841

**Comment by tamaina** [comment]
> [907d519#r139256130](https://github.com/misskey-dev/misskey/commit/907d519da36c550dde0a39970057bce22ffdcc5f#r139256130)
> 
> これはなぜ

あ〜MkReactedUsersDialog.vueがなくなったのか
