### ISSUE TITLE
アクセストークン発行の画面の権限が表示されない (2023.9.0-rc.2)

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#11880]
## 💡 Summary
![image](https://github.com/misskey-dev/misskey/assets/56515516/96cf1274-ba70-4669-bada-5e5097c6094f)
この画像のようにアクセストークン発行の画面の権限が表示されません

## 🥰 Expected Behavior
権限が表示される

## 🤬 Actual Behavior
権限が表示されない

## 📝 Steps to Reproduce

1.アクセストークン発行の画面を出す

### 💻 Frontend
* Model and OS of the device(s): Windows 11 10.0.22621 ビルド 22621
  
Browser: Vivaldi 6.2.3105.51 (Stable channel) (64-bit)
Server URL: https://mattyaski.co/
Misskey: 2023.9.0-rc.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: systemd 
* Misskey: 2023.9.0-rc.2
* Node: 20.5.1
* PostgreSQL: 15.3
* Redis: 7.0.12
* OS and Architecture: Debian 6.1.37-1 x86_64

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
@mattyatea 🙏🏻
