### ISSUE TITLE
error while choosing notification type

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#11897]
## 💡 Summary

I was selecting which notification types I wanted.

## 🥰 Expected Behavior

Save notification types on/off list

## 🤬 Actual Behavior

```
Endpoint: i/update
Info: {"e":{"message":"invalid input value for enum user_profile_mutingnotificationtypes_enum: \"note\"","code":"QueryFailedError","id":"3377f73f-fcac-4248-90a2-84570b2c4c68"}}
Date: 2023-09-24T17:13:18.372Z
```

## 📝 Steps to Reproduce

1. open notification settings (types)
2. select on, only for: mention, reply, achievement, application
3. push save button

### 💻 Frontend
* Model and OS of the device(s): Linux Debian
* Browser: firefox 117.0.1
  
* Server URL: misskey.social
  
* Misskey: 2009.09.0

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service:  docker compose, build master
* Misskey: 2009.9.0
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:  docker

**Comment by syuilo** [comment]
fixed 🙏🏻
