### ISSUE TITLE
もっと見るするとはちゃめちゃに荒ぶる

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#11904]
## 💡 Summary
もっと見るがあらぶる

![emojibug](https://github.com/misskey-dev/misskey/assets/56515516/f0c9a085-930e-455b-a5b1-217731d87752)

## 🥰 Expected Behavior
ちゃんともっと見るってやっても普通の挙動をする

## 🤬 Actual Behavior
めちゃめちゃ荒ぶる

## 📝 Steps to Reproduce

1.コントロールパネルの絵文字管理にいく
2.もっとみるをする
3.スクロールする

## 📌 Environment
まっちゃすきー。などでも確認

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser: 6.2.3105.51 (Stable channel) (64-bit) 
  
* Server URL:https://prismisskey.space
  
* Misskey:
  2023.9.1-prismisskey.1

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: systemd
* Misskey:  2023.9.1-prismisskey.1
* Node: 20.5.1
* PostgreSQL: 15.3
* Redis: 7.0.12
* OS and Architecture:: Debian 6.1.37-1 x86_64

**Comment by fruitriin** [comment]
手元ではウィンドウの横幅が広いと起きるなどした

・もっとみるが画面に入ったら次を読み込もうとする
・上にスクロールすると読み込んだ内容を破棄する？

この辺がかみあって次が読み込めなくなるような気がする

**Comment by zyoshoka** [comment]
Duplicate of #11656

**Comment by fruitriin** [comment]
closeしてよさそう

**Comment by mattyatea** [comment]
現象が見られなくなったのでclose
