### ISSUE TITLE
自分で自分のノート一覧を開いた時はセンシティブチャンネルへの投稿を表示する

### ISSUE THREAD

**Issue by wizsia** [syuilo/Misskey#11903]
## Summary

#11797 にて「センシティブチャンネルはユーザーのノート一覧から除外」されたが、ユーザー自身のノート一覧を開いた場合は表示されるようにしてほしい。

**Comment by samunohito** [comment]
2023.12.0-beta.5時点ではすでに修正されているように見受けられましたため、closeします。
他に何か問題点がある場合、そこをピックアップした別issueを立てていただけますと幸いです。

◎センシティブ設定されたチャンネル
<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/cbac4833-9783-4dba-8722-4f53b5057e07" />

◎センシティブチャンネルへ投稿したユーザ自身のノート一覧
<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/ce11c122-b341-4531-9cc1-70686dd65920" />

◎ほかのユーザから見た場合
<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/19e42270-8df8-471d-80ec-997c48121bca" />
