### ISSUE TITLE
リアクションに対する通報機能

### ISSUE THREAD

**Issue by 49372s** [syuilo/Misskey#11916]
## リアクションに対する通報
「死ね」や「殺すぞ」といったリアクションを使うユーザーが、やはり一定数存在するため、そういったユーザーに対応するためにもリアクションの絵文字を通報できる機能が欲しい

**Comment by kakkokari-gtyih** [comment]
通報というよりかは、いやなリアクションをユーザー側で選択して「♥」マーク等にすべて置き換えできるようにするほうがいいと思った

リアクション単位でモデレーションするのはさすがに厳しいかと思うので

**Comment by acid-chicken** [comment]
Related to #11772

**Comment by syuilo** [comment]
ユーザーを通報するのではダメかしら

**Comment by 49372s** [comment]
> ユーザーを通報するのではダメかしら

その手があったか
