### ISSUE TITLE
連合する編集機能

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#11929]
## Summary

お世話になります。
Misskey 2023.9.2にての編集機能が実装されました。
待ちわびていた機能の一つで大変嬉しく思っています。ありがとうございます。

さて、本機能を使っていて気になったのですが、
編集後の投稿は他のサーバー(MastodonやFirefish)には反映されないように見えました。
(MastodonやFirefishは編集機能が連合するようです)

時間的(あるいは技術的)に難しいのかもしれませんが、
他のサーバーにも編集内容が反映(連合)されるよう編集機能の拡張を考えていただけないでしょうか。

以上、ご確認の程よろしくお願いいたします。

---

ガバガバ英訳

The edited postings did not appear to be federated to other servers (Mastodon or Firefish).
Could you please consider extending the edit function so that edits are federated to other servers as well?

**Comment by tai-cha** [comment]
Related: https://github.com/misskey-dev/misskey/issues/8364

**Comment by mei23** [comment]
編集出来たように見えて他で出来てないのはトラブルの元なので
(ただMastodon仕様で連合したとしても履歴が残るので、連合ありの場合どちらにしろクリティカルな編集には使えないが)
とりあえず、ローカルのみ公開範囲のみ可にするとか、デフォルト無効にするとか、注意出すとかしたほうがいい気がしたのだわ。

**Comment by tai-cha** [comment]
> 注意出すとかしたほうがいい

そもそも新規投稿と編集でフォームが一緒で編集なのか分かりづらいのもあるのでこれはやろうとなんとなく思ってはいた

**Comment by kakkokari-gtyih** [comment]
個人的には最優先 (High Priority) で実装すべき機能だと思う（ものの、私はバックエンド専門外なので下手なことできない）

**Comment by tai-cha** [comment]
実装するのは頑張ればできるのだけど編集の仕様についてあんまりよく練られてないからそのまま動くのもなあ、そもそもどういう仕様に落ち着かせるのっていうのが今の私

前の編集の議論ではそもそも入れないという意見や連合してないものだけ編集できればいいんじゃないの意見とか意見が割れているようにも見えるし

（編集が実装された以上何らかの対策を早めにとるべきだろうという点には完全に合意）

**Comment by kakkokari-gtyih** [comment]
> 実装するのは頑張ればできるのだけど編集の仕様についてあんまりよく練られてないからそのまま動くのもなあ、そもそもどういう仕様に落ち着かせるのっていうのが今の私

実装されてしまったのを削除したり変更したりするのはあまり合理的ではないので、今の仕様をベースに拡張していくほかないと思います

**Comment by tai-cha** [comment]
> 実装されてしまったのを削除したり変更したりするのはあまり合理的ではない

（たくさんの消えたり変更されたりした機能を横目に）そうかもしれない…そうかも…そうだな…

**Comment by tamaina** [comment]
一旦ノート編集機能は撤回されました 🙏🏻
