### ISSUE TITLE
spotify.linkでもプレイヤーを開けるようにする

### ISSUE THREAD

**Issue by 1673beta** [syuilo/Misskey#11932]
## Summary

スマホ版Spotifyアプリの共有URLがopen.spotify.comからspotify.linkに変わったので、spotify.linkでもプレイヤーを開けるようにしてほしい

**Comment by kakkokari-gtyih** [comment]
Summaly 側の問題だった（修正PRを立ててありますのでマージされれば解決すると思われます）

**Comment by kakkokari-gtyih** [comment]
~~ま だ マ ー ジ さ れ な い https://github.com/misskey-dev/summaly/pull/13~~ マージされました
