### ISSUE TITLE
「ファイル付きのみ」のTLでファイル無しの新着ノートが表示される

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#11939]
## 💡 Summary
タイムライン右上から「ファイル付きのみ」をONにすると、その時はファイル付きのノートのみ表示されるのですが、その後の新着ノートはファイル無しのものも表示されます。

## 🥰 Expected Behavior
新着もファイル付きのみ表示

## 🤬 Actual Behavior
新着はファイル無しも表示される

## 📝 Steps to Reproduce

1. タイムライン右上から「ファイル付きのみ」をONに
2. ファイル無しのノートをする
3. 表示される

### 💻 Frontend
* Model and OS of the device(s):
HUAWEI P30 lite MAR-LX2J,
EMUI 12.0.0
  
* Browser:
  Chrome 117.0.5938.60
  
* Server URL:
  https://misskey.takehi.to/
  
* Misskey:
  2023.9.3

### 🛰 Backend (for server admin)

  不明

**Comment by FineArchs** [comment]
ストリーミングAPIにwithFilesのオプションが存在していないっぽい？

**Comment by syuilo** [comment]
🙏🏻
