### ISSUE TITLE
ノート編集時、メディアの追加が実際にはできないのに投稿者だけ追加できているように見える

### ISSUE THREAD

**Issue by shiosyakeyakini-info** [syuilo/Misskey#11936]
## 💡 Summary

ノートの編集時に、連合のオン・オフ、公開範囲、リアクションの受け入れ、メディアや投票も編集可能となっていますが、実際にこれらの編集をすることはできません。

特にメディア（画像）については、画像の追加後即座にタイムラインにも画像の追加が反映されますが、リロードを行うと追加した画像が消える現象が発生します。（追加されたと思って安心すると実際には追加されていないという現象になります。）

## 🥰 Expected Behavior

ノートの編集は連合のオン・オフや公開範囲、メディアをあとから編集することはできないので、これらの操作はできないことが正しい

## 🤬 Actual Behavior

ノートの編集時に連合のオン・オフや公開範囲をあとから編集することができるように見える

## 📝 Steps to Reproduce

1. ノートを投稿する
2. 編集する
3. 画像を追加する

### 💻 Frontend
* Model and OS of the device(s):
  Windows 11
* Browser: Chrome 116.0.5845.179
  Server URL: stg.miria.shiosyakeyakini.info
* Misskey:
  stg.miria.shiosyakeyakini.info: 2023.9.3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Misskey install shell script
  Misskey: 2023.9.3
* Node: v20.5.1
* PostgreSQL: psql (PostgreSQL) 15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)
* Redis: Redis server v=7.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3af367a78d5e21e9
* OS and Architecture: Ubuntu 23.04 (GNU/Linux 6.2.0-25-generic x86_64)>

**Comment by tai-cha** [comment]
ノート編集が撤回されているので閉じちゃいますね
