### ISSUE TITLE
ロールタイムラインのRenoteで、Renoteした人がしたリアクションが押された状態で表示されることがある？

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11940]
## 💡 Summary
ロールタイムラインにRenoteされたノートが表示されると、Renoteした人のリアクションが押された表示で出てくることがある
（実際ユーザー自身はリアクションを押していないにもかかわらず）

## 🥰 Expected Behavior
自分がリアクションしていない場合はどのリアクションも押された表示にならない

## 🤬 Actual Behavior
押されている

## 📝 Steps to Reproduce

※io独特のバグの可能性があるので、ioでの再現手順を記載しています

1. ロールタイムライン「Verified」を表示する
2. リアルタイム更新させる（待つ）
3. ロールに所属している人のRenoteのリアクション欄を見る
4. 見覚えのないリアクションがついていた場合は、そのノートを詳細表示で見てみる  
   （ついていたリアクションがなくなっている＝ノート単体で見た場合はちゃんと見える）

### 💻 Frontend
* Model and OS of the device(s): Microsoft Surface Laptop Go 2, Windows 11 Version 22H2 (Build 22621.2283)
  
* Browser: Google Chrome 117.0.5938.92 (Official Build) （64 ビット） (cohort: Stable) 
  
* Server URL: misskey.io
  
* Misskey:
  13.14.2-io.7

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/337e64cf-1436-4976-9a2b-0e5df176cd33)

![image](https://github.com/misskey-dev/misskey/assets/67428053/e9445d85-01a0-4877-aa3c-3888406fdeab)

**Comment by kakkokari-gtyih** [comment]
API読み込みでは起こらず、WS経由での更新時のみおかしいっぽい

**Comment by syuilo** [comment]
これねぇ
自分も前調べたけどio固有のものなのかすら分からなかった

**Comment by syuilo** [comment]
考えられる原因としてはどこかでオブジェクト参照を使い回しているとか

**Comment by kakkokari-gtyih** [comment]
これ、どうやらその人がどれに投票したかも見れるようになってるっぽいのでまずいかも

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/c1c4da4e-3264-4bd5-8b2d-e51137e5a6c4)

**Comment by syuilo** [comment]
謎すぎる

**Comment by syuilo** [comment]
io以外で再現できた人いるかしら

**Comment by kakkokari-gtyih** [comment]
https://github.com/MisskeyIO/misskey/pull/183 で改善した

**Comment by syuilo** [comment]
io固有だった感じ？

**Comment by kakkokari-gtyih** [comment]
それはわからないですがとりあえずioでは起こらなくなりました（同様の実装がこっちにあるならそこを直せば解決するかも）

**Comment by riku6460** [comment]
この問題は、Misskey.io 固有の問題とそうでない問題が重なっていて、おそらく本家ではリアクション/投票をしていても、表示上はされていない扱いになるはずです
(他人のリアクション/投票が見えるという現象は再現しないはず)

また、実際に確認していないのですが、このコミットですべてのタイムラインにおいて RN の投票が反映されない現象が発生しそうな気がしています https://github.com/misskey-dev/misskey/commit/3f4ee9840560d8c423111f1ab93b2e36218a1314

**Comment by Sayamame-beans** [comment]
triage: まだ発生していますか?
