### ISSUE TITLE
[2023.10.1.beta-1] アップグレード以前にTLを遡れない

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#11958]
## 💡 Summary

世界5分前仮説

https://misskey.systems

10月3日21時43分ごろより前のノートを主要な導線で見ることができない

お気に入りやクリップからなら見ることができるので、データが消滅したわけではないらしい

## 🥰 Expected Behavior

アップデート前のノートも見ることができる

## 🤬 Actual Behavior

過去のノートを見ることができない

## 📝 Steps to Reproduce

1. TLを表示する
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2o23.10.1.beta1
* Node: v18.17.1　←古い！
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture: Ubuntus

**Comment by syuilo** [comment]
これは意図したものになります🙏

**Comment by fruitriin** [comment]
えっ

**Comment by syuilo** [comment]
TLがPush型に変更されたからPushされない限り表示されない

**Comment by fruitriin** [comment]
https://misskey.systems/@fruitriin
自分の投稿したノートも遡ることができない？

**Comment by syuilo** [comment]
そうね、それが特に重かったため

**Comment by syuilo** [comment]
今後投稿されていく分は遡り可能

**Comment by acid-chicken** [comment]
長期運用したらその方が重くならない？

**Comment by fruitriin** [comment]
🤯

**Comment by tkmrgit** [comment]
これ仕様ににゃったらあちこちで混乱起きるのでは

**Comment by fruitriin** [comment]
リアルタイムに今そのときにいるユーザーとのやりとりを楽しむ分にはよいのだけど、過去のノートを資産と捉えているユーザーが一定数いるので過去の投稿のマイグレーション手段がほしい

**Comment by CAT5NEKO** [comment]
タイムラインを遡って交流を楽しむっていう挙動を封じて、特定の投稿を探し当てて表示させるようにするっていう方法になってしまうと、SNSというよりも「検索データベース」になってしまうのではないでしょうか。😭
偶然の出会いが乏しいのは処理向上の期待を上回る懸念点であると思います。

**Comment by syuilo** [comment]
> タイムラインを遡って交流を楽しむっていう挙動を封じて、特定の投稿を探し当てて表示させるようにするっていう方法になってしまう

どういうことかしら？
これから投稿されるものは遡りは可能

**Comment by syuilo** [comment]
以前から遡りできる範囲は限られている

**Comment by syuilo** [comment]
なのでマイグレーションしたとしてもマイグレーションされた投稿が遡れなくなるまでの数日〜数週間便利になるだけだからモチベーションとしては低いかも？

**Comment by CAT5NEKO** [comment]
POST型採用した以前にしか投稿してない方は探さないと全く表示されなくなる？

**Comment by tkmrgit** [comment]
> 以前から遡りできる範囲は限られている

そうかにゃ？もっと見る操作繰り返せば一番最初まで戻れたように思うけどにゃ？

**Comment by kakkokari-gtyih** [comment]
> TLがPush型に変更されたからPushされない限り表示されない

*(若干 Off-topic)* なら、せめてノートがないタイミング（初期ローディング）で「ありません」と出すのではなく「新しいノートがあればここに表示されます」みたいな文言に変えるべきでは

**Comment by syuilo** [comment]
- 遡れる範囲に制限があるのは昔から(API的にもクライアントの負荷的にも)
- これから投稿されるものは従来通り遡り可能
- 今遡れる範囲にあるものをマイグレーションしたとしても結局しばらく経つとそれらの投稿は遡れなくなる(前述したように古い投稿は遡れなくなるのは昔からの仕様)から効果は少なそう

**Comment by VillSnow** [comment]
さかのぼれる範囲が限られていると言うのは具体的にどのような範囲ですか？

**Comment by tkmrgit** [comment]
[ノート]タブでは見える投稿が[全て]タブに出てこないのはバグ？ → https://github.com/misskey-dev/misskey/issues/11960

**Comment by CAT5NEKO** [comment]
あるユーザーのより過去の投稿を遡って読みたい利用者が現れた時のために、プロフにTL読み込ませるボタン設けておいたらニーズに応えられるかも

**Comment by slofp** [comment]
横からですいません

> 遡れる範囲に制限があるのは昔から

`notes/local-timeline`などは10日前までを取得するような制限がありましたが`users/notes`の場合はそのような制限がないので実質過去すべての投稿が見れるようになっていました。

**Comment by tkmrgit** [comment]
>`notes/local-timeline`などは10日前までを取得するような制限がありましたがusers/notesの場合はそのような制限がないので実質過去すべての投稿が見れるようになっていました。

やっぱりそんな感じした。前に1年前くらいまで遡って見れた覚えがあったので

**Comment by kakkokari-gtyih** [comment]
`users/notes` などを遡れないのはキツい（ユーザーページの投稿は遡ることが多い）

**Comment by VillSnow** [comment]
> 横からですいません
> 
> > 遡れる範囲に制限があるのは昔から
> 
> `notes/local-timeline`などは10日前までを取得するような制限がありましたが`users/notes`の場合はそのような制限がないので実質過去すべての投稿が見れるようになっていました。

私の経験と一致しますね

**Comment by yuriha-chan** [comment]
そもそも、Redisに無限にたまっていくと容量的にきつくなりそうですし、事故でオンメモリデータベースが吹き飛んだときに大変になるので、Redis になかったらデータベースを見に行く実装がよさそうです。

**Comment by syuilo** [comment]
難しそう

**Comment by yuriha-chan** [comment]
（発言したからには私が実装やってみるべきかな…）

**Comment by syuilo** [comment]
ｵｯ

**Comment by kakkokari-gtyih** [comment]
（普通に質問） `users/notes` 等もTL扱いということですか？

**Comment by syuilo** [comment]
はい、ノートが時系列で並ぶものはタイムラインと呼称してます

**Comment by tkmrgit** [comment]
検索で`*`が使えるのでユーザー指定検索にしてワードを`*`にすれば検索のほうから遡る動作ができることは確認(取得できてもPushはされない模様)。ただし現状MisskeyにMeilisearchの検索には問題が多数 #10844 #11322 etc... あるので検索で遡る動作が適切なのかは不明

**Comment by futchitwo** [comment]
> そもそも、Redisに無限にたまっていくと容量的にきつくなりそうですし、事故でオンメモリデータベースが吹き飛んだときに大変になるので、Redis になかったらデータベースを見に行く実装がよさそうです。

チャンネルでやってるやつかもしれないので参考に
- #10539

**Comment by yuriha-chan** [comment]
https://github.com/misskey-dev/misskey/pull/11976 こんな感じの実装でよいですかね…？
（実装というより、必要なところをrevertしただけですが）

**Comment by grarich** [comment]
push型のTLにすること自体はいいと思うけれど、新しくリモートサーバーの人をフォローするときに過去のTLが見れないので何を上げていたのかわからない。

https://github.com/misskey-dev/misskey/issues/11958#issuecomment-1744974192
にもある通りユーザーのTLは遡れるように実装してあったほうが良さそう。
(実装が可能かどうかは不明)

**Comment by syuilo** [comment]
> 新しくリモートサーバーの人をフォローするときに過去のTLが見れないので何を上げていたのかわからない。

これって今まで見れていたっけ？

**Comment by grarich** [comment]
> > 新しくリモートサーバーの人をフォローするときに過去のTLが見れないので何を上げていたのかわからない。
> 
> これって今まで見れていたっけ？

ローカルからリモート参照するのは見れません（subしていないので当たり前だと思っています。）
リモートで表示したときに見れるかどうかですね。
今まではリモートで表示から閲覧することで過去TLを参照できていましたが、push型に変更になったあとはピン留め以外が見れません。

**Comment by syuilo** [comment]
修正しました 🙏🏻

**Comment by grarich** [comment]
> 修正しました 🙏🏻

有難うございます🙏🏻🙏🏻🙏🏻

この修正でアップデート前のTLも全部見れたので意図した修正か確認するといいかもしれません。
また、ユーザーのハイライトの場所にも取得できているノートを表示してもらえたらTLを遡れない問題も解決されるような気がします。

**Comment by fruitriin** [comment]
みすてむず、プロフィールから過去のノートまでみれるようになった（beta-7の次まで入れた）

**Comment by grarich** [comment]
> みすてむず、プロフィールから過去のノートまでみれるようになった（beta-7の次まで入れた）

これまた取れなくなったね。。

**Comment by ityuki** [comment]
ここにつなげても良いのかな……？

通常TL系が遡れないのは遡れるようにすると負荷増えるって話は聞いているのですが、ローカルタイムラインで生きてるようなサーバだと、ローカルTL消えるのは、かなりしんどいです。

各TLに対して、Redis になかったらデータベースを見に行く実装を管理者権限からオプションで出来るようにしてほしいです……

**Comment by syuilo** [comment]
PR募集中🙏

**Comment by syuilo** [comment]
ローカルTLの遡りできなくなるのは流速にもよるけど1日程度だからそんなに影響はなさそうな気がする

**Comment by ityuki** [comment]
のんびりLTLで話すタイプのインスタンスだと、１週間分ぐらい出てるのは普通なので、一時的にしろ消えてなくなるのは、しんどかったです

少人数インスタンスの方が影響範囲が大きそうな気はします

**Comment by ityuki** [comment]
ふと思ったのですが、流速あればローカルTLがほとんどredisに乗るのであれば、チェックボックスとか無しでも負荷はかかりにくいのでは……

**Comment by syuilo** [comment]
投稿が数億くらいになってくるとそれでも負荷は無視できなくなってくる

**Comment by ityuki** [comment]
表現悪くてすみません。

ローカルTL表示するのに、DBにアクセスしに行く処理って、規模の大きいサーバだとユーザが意図しない限り起きないのでは？（普段見る部分は全部redisにいるのでは？）　と思いました。

**Comment by syuilo** [comment]
たしかに

**Comment by ityuki** [comment]
規模の大きいサーバ
　→ 普段見える部分は全部redisに残るので、ユーザが意図しない限りDBにはアクセス行かない
規模の小さいサーバ
　→ 見たい部分はDBにいることも多いが、規模が小さいのでDBにアクセスしに行ってもたかがしれている

とすれば、特にチェックボックスとか無くて、「redisに無ければDBに読みに行く」を実装しても問題ないかなぁと思いました

**Comment by tai-cha** [comment]
これってリストTLは対応しない感じでしょうか？
そうなるとredisがリセットされた際や2023.9.3までからのアプデ後、相変わらずリストTLは遡れなくなるかなと思ったのですが

**Comment by syuilo** [comment]
リストに関しては今のところ対応予定ないわね

**Comment by tai-cha** [comment]
なるほど

**Comment by anatawa12** [comment]
STLどのような感じですか？パージが入ったことにより、新たにフォローしてリロードするとSTLからHTL成分が消えそうな気がするのですが

**Comment by syuilo** [comment]
修正しました 🙏🏻

**Comment by tetradice** [comment]
同じ問題にハマる人がいるかもしれないため、v2023.10.2で私が遭遇した問題をここでコメント・共有させていただきます。
（Issueとして上げたかったのですが、手順内にバージョンアップを含むことから、再現できるかどうかの確認が難しかったので……）

1) v2023.10.1にバージョンアップして、ソーシャルタイムラインに過去のノートが表示されなくなる
2) ノートを1つ以上新規投稿
3) v2023.10.2にバージョンアップする

という手順を踏むと、2)で投稿したノートのみしかソーシャルタイムラインに表示されず、過去のノートが表示されないままとなる現象が起きました。

暫定対応として、redis-cliコマンドからauth→flushallでredis内のデータを全削除することで、再びソーシャルタイムラインに過去のノートが表示されるようになりました。
※ただしこれにより、過去のプッシュ通知の履歴はすべて削除されてしまうようです

**Comment by tai-cha** [comment]
アンテナや通知を残しながらTLのキャッシュを消したい場合に
```bash
redis-cli KEYS "list:homeTimeline*" | xargs redis-cli DEL
redis-cli KEYS "list:localTimeline*" | xargs redis-cli DEL
```
みたいな方法は使えるかもしれないです（手元できちんと動かしてはいないですが）
