### ISSUE TITLE
FastifyDeprecation: You are accessing the deprecated "request.routerPath" property

### ISSUE THREAD

**Issue by AlfredSK** [syuilo/Misskey#11953]
## 💡 Summary

Misskey error log is showing a lot of Fastify deprecation warnings for `request.routerPath`.

## ⚠️ Warning message

```
(node:1962) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

## 📌 Environment

* Server URL: https://misskey.de/
* Misskey: 2023.9.3
* Node: 18.17.1
* PostgreSQL: 14.9
* Redis: 7.2.1
* OS and Architecture:  Ubuntu 22.04.3 LTS

**Comment by CyberRex0** [comment]
maybe fixed in next release.
#11935 

If you don't need to see debug log, set `production` to `NODE_ENV` environment variable may help.

**Comment by saschanaz** [comment]
> If you don't needed to see debug log, set `production` to `NODE_ENV` environment variable may help.

Somehow it doesn't help in this case.
