### ISSUE TITLE
[2023.10.1.beta-1] [ノート]タブでは見える投稿が[全て]タブに出てこない

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#11960]
## 💡 Summary

※これはbeta版についてのIssueです。
Beta版採用サーバーにてユーザーページからタブを切り替えて表示する際、[ノート]タブには出てくる投稿が[全て]タブでは何も出てきません

## 🥰 Expected Behavior

[全て]タブには全ての投稿が表示される

## 🤬 Actual Behavior

[ノート]タブに表示されている投稿でさえも[全て]タブに表示されなくなってしまっている

## 📝 Steps to Reproduce

1.投稿する
2.自分のユーザーページに行く
3.[全て]タブに切り替える

## 📌 Environment

Misskey 2023.10.1.beta-1

**Comment by syuilo** [comment]
🙏🏻
