### ISSUE TITLE
[2023.10.1.beta-2] users/notesとnotes/user-list-timelineにチャンネル投稿が含まれていない

### ISSUE THREAD

**Issue by setaria430** [syuilo/Misskey#11965]
## 💡 Summary
（センシティブでない）チャンネルへのノートが、ユーザーのノート一覧とリストに含まれていない
あるいは仕様であれば、センシティブフラグが無意味になってしまう

## 🥰 Expected Behavior
ノートが含まれる

## 🤬 Actual Behavior
ノートが含まれない

## 📝 Steps to Reproduce
1. チャンネルのトレンド等から直近のチャンネルノートを見つける
2. そのノートのユーザのホームへ行きノート一覧を確認する

## 📌 Environment
確認したのは2023.10.1.beta-2ですが、2023.10.1.beta-1で混入した可能性もあります

### 💻 Frontend
* Model and OS of the device(s):
  Windows 10 pro
* Browser:
  Google Chrome 117.0.5938.132
* Server URL:
  https://misskey.systems/
* Misskey:
  2023.10.1.beta-2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
チャンネル投稿は基本的にチャンネル内でのみ表示されるものなので users/notesとnotes/user-list-timelineにチャンネル投稿が含まれないのは仕様になります。
ただ users/notes に関してはオプションでそのユーザーのチャンネル投稿も含められるようにしたいですね

**Comment by setaria430** [comment]
なるほど
最近「投稿と返信」の名称が「全て」になりましたが、名称次第であのタブ欄が活用できそうですね
