### ISSUE TITLE
ノートの「編集」を行った時、 note.tags フィールドや hashtag テーブルが更新されない

### ISSUE THREAD

**Issue by pooza** [syuilo/Misskey#11967]
## 💡 Summary

ノート本文の「編集」を行ったとき、データベース上の、

- noteテーブルのtagsフィールドが更新されない。
- hashtagテーブルが更新されない。

## 🥰 Expected Behavior

両テーブルが更新されること。

## 🤬 Actual Behavior

両テーブルが更新されていない。

## 📝 Steps to Reproduce

1. ノートの編集を許可されたロールを用意。
2. このロールを持ったユーザーを用意。
3. このユーザーで適当なノートの投稿を行う。
4. そのノートの「…」メニューから「編集」メニューを選択。
5. ノート本文にハッシュタグを追記し、もう一度投稿。

### 💻 Frontend
* Model and OS of the device(s):
MacBook Air M2 2022 macOS 13.6

* Browser:
Chrome 117.0.5938.132

* Server URL:
https://st.misskey.delmulin.com/

* Misskey:
2023.9.3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 自宅サーバのKVM, Dockerなし
* Misskey: 2023.9.3
* Node: v18.17.1
* PostgreSQL: 14.8
* Redis: 6:7.0.11
* OS and Architecture: Ubuntu 22.10 x86_64

**Comment by pooza** [comment]
#11944 でも触れられているでしょうか。

**Comment by syuilo** [comment]
まさに編集された際のハッシュタグやメンションの扱いなど考慮すべきことが多く、検討の結果クオリティの高い実装にすることはコストに見合う価値がないとの判断から、次のリリースからノート編集機能は削除されることになりました 🙏🏻
