### ISSUE TITLE
[2023.10.1.beta-1] sinceIdやsinceDateを利用してTLを取得することができない

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#11961]
## 💡 Summary

タイムラインの取得時に従来使えたsinceIdやsinceDateのオプションを指定するとTLの取得ができなくなる

外部アプリでこれらを使っている場合は動かなくなる

## 🥰 Expected Behavior

sinceIdを利用すると従来通りにTLが取得可能になる、もしくはこれらオプションの廃止をする

## 🤬 Actual Behavior

タイムラインの取得時に従来使えたsinceIdやsinceDateのオプションを指定するとTLの取得ができなくなる

## 📝 Steps to Reproduce

1. `api/notes/local-timeline`にてsinceIdに任意のノートIDを指定してリクエストをする
2. なにも返ってこない

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
🙏🏻
