### ISSUE TITLE
Federated timeline is empty GTL

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#11973]
## 💡 Summary

I've installed a 2023.10.0-beta.1 from scratch, made some federation, but federated GTL it's empty 

https://beta.Misskey.social

Maybe related to #11958

## 🥰 Expected Behavior

I want to see remote public notes from federation 

## 🤬 Actual Behavior

I can't see no federated posts. Only Home, Local, Social timeline is populated. 
HTL LTL STL

## 📝 Steps to Reproduce

1. Git checkout develop branch 
2. Install docker compose environment 
3. Federate some servers
4. See GTL empty 

### 💻 Frontend
* Model and OS of the device(s): any
  
* Browser: any
  
* Server URL: https://beta.Misskey.social
  
* Misskey:
  2023.10.0-beta.3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service:   docker compose develop 
* Misskey:   2023.10.0-beta.3
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by horaceyoung** [comment]
I have a similar issue with timelines not being correctly populated. Is there a method to manually force rebuild timelines?

**Comment by syuilo** [comment]
fixed 🙏🏻

**Comment by tassoman** [comment]
confirmed beta6
