### ISSUE TITLE
各種「ありません」表記をユーザーフレンドリーにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11979]
## Summary

「ありません」だけではなく、どうすればこの機能を使用できるかなどの簡単な説明と画像が出るようになるといいかも

- クリップ
- ドライブ
- リスト
- アンテナ
- お知らせ
- ページ
- Play

**Comment by kakkokari-gtyih** [comment]
Related to #10472

**Comment by syuilo** [comment]
👍

**Comment by tamaina** [comment]
Duplicate of #2809
