### ISSUE TITLE
[2023.10.0-beta.7+] ノートを途中から遡れなくなることがある

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#11984]
## 💡 Summary

※これはbeta版についてのIssueです。
Beta版採用サーバーにてノートを正常に遡ることができない状況が存在する

※このIssueは分割されました※ 遡ろうとして日付が飛ぶ件は→ #11404

## 🥰 Expected Behavior

~~どんな状況でも正常に遡れる~~→途中から遡れなくならない

## 🤬 Actual Behavior

~~遡ることができない状況が存在する~~→途中から遡れなくなる
https://github.com/misskey-dev/misskey/pull/11963#issuecomment-1751700021
https://github.com/misskey-dev/misskey/pull/11963#issuecomment-1751704020

## 📝 Steps to Reproduce

1-1. https://misskey.systems/@syuilo@misskey.io で「ノート」を遡る
1-2. https://misskey.systems/@cv_k@misskey.dev で「ノート」「全て」を遡る
2.Wow

## 📌 Environment

Misskey 2023.10.0-beta.7+ (04c8a7077fc60c415b3004a38416c5346e62b9bb)

**Comment by syuilo** [comment]
再現できなかった

**Comment by tkmrgit** [comment]
> 再現できなかった

当該URLでは非ログインプライベートブラウジングでも確認できたので再現できにゃいことにゃいと思ったけどにゃ。開発環境では起きてないとかかな

**Comment by syuilo** [comment]
https://misskey.systems/@cv_k@misskey.dev を遡ってみたけど特に異常が見当たらなかった

**Comment by tkmrgit** [comment]
> https://misskey.systems/@cv_k@misskey.dev を遡ってみたけど特に異常が見当たらなかった

「ノート」「全て」が4日前 (2023/10/5 0:28:38) より前を遡れない、ファイル付きであれば遡るみたいな挙動をしている

**Comment by syuilo** [comment]
多分直りました 🙏🏻

**Comment by tkmrgit** [comment]
![ehehejh](https://github.com/misskey-dev/misskey/assets/28042693/78f2d3c6-926a-43a1-97ae-11a9728f2a66)
残念にゃがら日付が飛んでしまう...

**Comment by syuilo** [comment]
これは以前のバージョンではそうではなかったということ？

**Comment by syuilo** [comment]
2023.10.0-betaから発生した問題とは考えにくい
ローカルユーザーでも再現できる？

**Comment by tkmrgit** [comment]
> ローカルユーザーでも再現できる？

https://misskey.systems/@p さんの「ノート」「全て」でも起きる模様

**Comment by syuilo** [comment]
> > ローカルユーザーでも再現できる？
> 
> https://misskey.systems/@p さんの「ノート」「全て」でも起きる模様

こっちで遡ってみたけど再現しなかったわね

**Comment by tkmrgit** [comment]
7ヶ月前からのユーザーだけど6日前までしか見えていにゃい

**Comment by syuilo** [comment]
ふむ
それは

> 残念にゃがら日付が飛んでしまう...

とはまた別の症状になるわね

**Comment by syuilo** [comment]
> 残念にゃがら日付が飛んでしまう...

の可能性としては

1. リモートユーザーの古い投稿が飛んでくる
1. RedisにpushされるときはXADDを使うため、Redis上のTLの先頭に追加される(=IDは最新になる)
1. クライアントでTLを取得した際は古い投稿は古い位置に含まれる
1. クライアントでページネーションを行う際、末尾の要素のIDを untilId として指定する
1. その際、偶然その古い投稿が untilId に指定される
1. サーバーは untilId より古いRedisのエントリを取得する
1. RedisのエントリIDは投稿が作成された日時ではなくRedisへの追加日時に基づくため、「作成された日時が古い投稿」のIDより古いIDをもつRedisエントリは存在しない
1. 空が返る

が考えられる(これが原因と思われる現象は前からアンテナTLで起きていた)

**Comment by syuilo** [comment]
↑の解決策が思いつかないわね

RedisにXADDする際はIDを手動で指定できるけど、それをしても先頭にしか新しいエントリを追加できないというのは変わらない(先頭にあるIDより古いIDを持つエントリを追加できない)
だからリモートから古い投稿が飛んでくるシチュエーションに対応できない

**Comment by tkmrgit** [comment]
**正常に遡れないことできない**がこのIssueにゃので
・遡れなくなる (私のユーザーページとpさんのユーザーページで起きている現象)
・遡るが日付を飛ぶ (しゅいろさんのioのユーザーページ「ノート」タブと私のユーザーページの一部で起きてる現象)
という感じなのよにゃ。

ファイル付きだけが遡れるので何かの問題が起きてるのではにゃいかと思っている。解決策が難しいかもしれないけどこのままリリースしても同じような報告来ることになるんじゃないかにゃと思う。。

**Comment by syuilo** [comment]
> 正常に遡れないことできないがこのIssueにゃので

Issue分割するか

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/issues/11994

**Comment by syuilo** [comment]
多分直った

**Comment by fruitriin** [comment]
beta12でなおったっぽい

**Comment by syuilo** [comment]
🙏🏻
