### ISSUE TITLE
アンテナなど、Redisを使ってTLを構築している個所で、途中から遡れなくなることがある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#11994]
可能性としては

1. リモートユーザーの古い投稿が飛んでくる
1. RedisにpushされるときはXADDを使うため、Redis上のTLの先頭に追加される(=IDは最新になる)
1. クライアントでTLを取得した際は古い投稿は古い位置に含まれる
1. クライアントでページネーションを行う際、末尾の要素のIDを untilId として指定する
1. その際、偶然その古い投稿が untilId に指定される
1. サーバーは untilId より古いRedisのエントリを取得する
1. RedisのエントリIDは投稿が作成された日時ではなくRedisへの追加日時に基づくため、「作成された日時が古い投稿」のIDより古いIDをもつRedisエントリは存在しない
1. 空が返る

が考えられる

RedisにXADDする際はIDを手動で指定できるけど、それをしても先頭にしか新しいエントリを追加できないというのは変わらない(先頭にあるIDより古いIDを持つエントリを追加できない)
だからリモートから古い投稿が飛んでくるシチュエーションに対応できない

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/11404 関係ある？

**Comment by syuilo** [comment]
ありあり

**Comment by syuilo** [comment]
duplicate of https://github.com/misskey-dev/misskey/issues/11404
