### ISSUE TITLE
[2023.10.1.beta-7] リノートするとリノートされたノートもTLに表示される

### ISSUE THREAD

**Issue by grarich** [syuilo/Misskey#11997]
## 💡 Summary
push型TLでリノートするとリノートされたノートもTLに表示されます。

## 🥰 Expected Behavior

リノートのみ表示され、リノートされたノートは表示されない。

## 🤬 Actual Behavior

Summaryの通り。

## 📝 Steps to Reproduce

1. 数ヶ月前のTLに流れないであろうノートをリノートする
2. TLをリノートされたノートまで遡る
3. 該当の事象が発生します。

## 📌 Environment

Misskey 2023.10.1.beta-7

### 💻 Frontend
* Model and OS of the device(s):
Ubuntu 22.04.3
* Browser:
Chrome 117.0.5938.149
* Server URL:
https://misskey.grawlily.com/
* Misskey:
  2023.10.1.beta-7

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.10.1.beta-7
* Node: 20.5.1
* PostgreSQL: 15.4-2
* Redis: 7.2.1
* OS and Architecture: Ubuntu 22.04.3 LTS amd64
*

**Comment by syuilo** [comment]
2023.10.0-beta.15でも発生しますか？

**Comment by grarich** [comment]
v2023.10.1 時点で発生しませんでした。ありがとうございます。

**Comment by grarich** [comment]
closeして頂いて問題ありません。
