### ISSUE TITLE
meilisearch not working

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#11998]
## 💡 Summary

I have done my best to follow this guide https://gist.github.com/Akkiesoft/d9b705b53de1181e6ce8d1288d49bc10 to setup meilisearch, and then filled out the fields from the example.yml, but the search is not performed, tested by disabling the meilisearch and the results shows up.

```yml
meilisearch:
  host: localhost
  port: 7700
  apiKey: '<API-KEY>'
  ssl: false
  index: 'matrix-rocks'
  scope: local
```

```bash
curl -X GET http://localhost:7700/indexes -H "Authorization: Bearer $MEILI_ADMIN_API_KEY" | jq .
```

```json
{
  "results": [
    {
      "uid": "matrix-rocks",
      "createdAt": "2023-10-09T20:08:00.00136376Z",
      "updatedAt": "2023-10-09T20:08:00.001938596Z",
      "primaryKey": "id"
    },
    {
      "uid": "matrix-rocks---notes",
      "createdAt": "2023-10-09T20:25:26.76001146Z",
      "updatedAt": "2023-10-09T20:36:05.67290309Z",
      "primaryKey": "id"
    }
  ],
  "offset": 0,
  "limit": 20,
  "total": 2
}
```

## 🥰 Expected Behavior

Same search results as without meilisearch, just way faster.

Whitout meilisearch
![image](https://github.com/misskey-dev/misskey/assets/44526987/eaf194e4-0f5f-4abc-902b-b9dce558eebc)

Whit meilisearch

![image](https://github.com/misskey-dev/misskey/assets/44526987/71c5c354-5484-4bc4-88a0-ee8b5f40f72c)

## 🤬 Actual Behavior

Empty results, and no log entries indicating failures.

## 📝 Steps to Reproduce

1. Follow the guide mentioned above
2. Setup the `.config/default.yml`
3. Do a search https://matrix.rocks/search ie `Stephanie Branton`

### 💻 Frontend
* Model and OS of the device(s):
  ANY
* Browser:
  ANY
* Server URL:
  https://matrix.rocks/
* Misskey:
  

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.9.3
* Node: v20.5.1
* PostgreSQL: 15.4-2.pgdg22.04+1
* Redis: 7.2.1 malloc=jemalloc-5.3.0 bits=64 build=95712a67f5005c28
* OS: Ubuntu 22.04

**Comment by fruitriin** [comment]
misskey doesn't have migrate notes into meilisearch

I think you can find new notes.


You can also run migrate script

https://github.com/dev-hato/aminome

**Comment by spirillen** [comment]
Thanks @fruitriin 

This is leaving me with two questions for now

1. Version comparability
    1. it say Misskey v13.12.2
    2. Meilisearch v1.1.1
    3. I am using newer versions, is it compatible?
2. If you need a third party script to launch the use of meilisearch, can misskey then update meilisearch with new contents, and how about after a reboot/restart?

**Comment by fruitriin** [comment]
> Version comparability
it say Misskey v13.12.2
Meilisearch v1.1.1
I am using newer versions, is it compatible?

I think meiliserach has compatible.
I don't know details for misskey had compatible or not.

as long as I can remember, stored index key change is only changed around meilisearch.

> If you need a third party script to launch the use of meilisearch, can misskey then update meilisearch with new contents, and how about after a reboot/restart?

meilisearch not need to restart.
misskey need restart after enable meilisearch. (if you enabled meilisearch and run script, not have to restart)

**Comment by spirillen** [comment]
> meilisearch not need to restart.
> misskey need restart after enable meilisearch

And when you reboot the server for security updates like the kernel :wink:

**Comment by spirillen** [comment]
Tested the script... van confirm it is still working on `2023.10.1`

Thanks for your help @fruitriin
