### ISSUE TITLE
外部サイトからプラグイン・テーマの導入ができるようにする（改ざん防止実装案）

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#11992]
## Summary

Misskey Hubで提供予定？のプラグインストア・テーマストアのための布石となる実装
Related to https://github.com/misskey-dev/misskey-hub/issues/2 

プログラムの改ざんを防止するために以下のような手法で照合する

- プラグインサイト: `https://plugin.example.com/`
- Misskeyサーバー: `https://misskey.example.com/`

として説明

1. プラグイン配布サイト側から  
  `https://misskey.example.com/install?type=plugin&url=【プラグイン提供用API URL】&hash=【ソースコードのSHA-512ハッシュ】` に飛ばす
2. Misskeyクライアントで、Misskey APIを発火 `https://misskey.example.com/api/get-external-resources` 
3. Misskeyサーバーサイドでクエリパラメータに渡されたURLにアクセス、プラグインのデータを取得したうえで、クエリパラメータに渡されたSHA-512ハッシュとソースコード（`data`の中身。**改行はLFに統一される**）を照合する
4. 問題ないことが確認出来たら、Misskey API経由でプラグインのデータをクライアントに返す（照合できない場合はインストール却下）
5. インストール実行

### プラグイン配布サイトが提供するAPI

```json
{
    "type": "plugin",
    "data": "for (let i, 100) {\n  <: if (i % 15 == 0) \"FizzBuzz\"\n    elif (i % 3 == 0) \"Fizz\"\n    elif (i % 5 == 0) \"Buzz\"\n    else i\n}"
}
```

### テーマ配布サイトが提供するAPI

```json
{
    "type": "theme",
    "data": "{id:'6c445bcb-4e3a-4cb6-9afe-a9a984c2ccd7',base:'dark',desc:'discord',name:'discord風',props:{bg:'rgb(32, 34, 37)',fg:'rgb(228, 228, 228)',link:'rgb(0, 176, 244)',navBg:'#2f3136',navFg:'#8e9297',panel:'rgb(54, 57, 63)',accent:'rgb(113, 136, 217)',header:'rgb(47, 49, 54)',renote:'rgb(67, 181, 129)',hashtag:'@accent',mention:'@accent',navActive:'#ffffff',navHoverFg:'#dcddde',fgHighlighted:'#ffffff',scrollbarHandle:'rgb(32, 34, 37)'},author:'Zheneha'}"
}
```

#### リクエストペイロード
```json
{
    "url": "https://plugin.example.com/api/plugin/xxx",
    "hash": "f2374dcc1930523f69d4214c1cbf5d12"
}
```

#### レスポンス
```json
{
    "type": "plugin",
    "data": "for (let i, 100) {\n  <: if (i % 15 == 0) \"FizzBuzz\"\n    elif (i % 3 == 0) \"Fizz\"\n    elif (i % 5 == 0) \"Buzz\"\n    else i\n}"
}
```

**Comment by kakkokari-gtyih** [comment]
配布元の信頼については担保できないが、インストールの際に警告を出す等で幾分かマシにはなるはず

**Comment by KisaragiEffective** [comment]
何点か提案:

1. plugin[.]comは実在するので例示をplugin.example.comに書き換えた方がベターです
2. テーマのレスポンスがJSONではないのはなにか理由がありますか？
3. MD5はやめましょう。暗号学的に安全ではありません。SHA-512にするべきです。
4. URLクエリパラメーターに任意のURLを含められると悪意のあるプラグインを返すURLへアクセスする危険性があるので確認画面が欲しいです

**Comment by kakkokari-gtyih** [comment]
> 何点か提案:

1, 3…反映しました。ありがとうございます🙏🏻

4…コメントで言及済み

2…データの型を合わせたほうがいいと思ったので（`type`で区別できる説はあるが）

**Comment by KisaragiEffective** [comment]
> typeで区別できる説

はい。特段の理由がなければサードパーティにとっては構造化されてた方が嬉しいと思います

**Comment by kakkokari-gtyih** [comment]
テーマのほうもハッシュで照合することを考えるとやっぱり文字列に統一したほうがいいかも

**Comment by syuilo** [comment]
Misskey APIでもテーマはJSONではなく文字列として扱ってる
