### ISSUE TITLE
統合後のミュート設定についても引き続きソフト相当かハード相当か保持する

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#12007]
## Summary

フィルターをクライアント側に寄せるという目的があるのは理解しました(別ソースから)。
破壊的変更であるにも関わらずどう変わったのか**変更履歴の書き方が不十分**なのは置いておきます。
現行の実装がどうなっているのか知りませんが、ソフトをハードに移行してもハードをソフトに移行しても混乱を産むことは必至です。
今ならまだ間に合うのでソフト相当かハード相当か保持するようにしてください。

related: #12003

**Comment by syuilo** [comment]
「ソフト相当かハード相当か保持する」という意味がよくわかってないです

**Comment by fruitriin** [comment]
めちゃくちゃエスパーすると、

タイムラインに誰が発言したかわかるミュートと痕跡もでないミュートの2つの区分がある仕様を残してほしい

という解釈を得た

めちゃくちゃ怪文書だけど

**Comment by syuilo** [comment]
ほむん

**Comment by tkmrgit** [comment]
#7575 実現しないかなぁ...

**Comment by KisaragiEffective** [comment]
> よくわかっていないです

現状(`<= 2023.9.*`)では
* ソフトミュートが「TLに現れ、折り畳まれるが開ける」
* ハードミュートが「TLに現れない」

という仕様になっていますが、 #12003 を見る限りではソフトミュートを廃止し、ハードミュートのみにしたということでしょうか？それなら的外れだという指摘は当たるものだと思います。

**Comment by massongit** [comment]
IssueのDescriptionを読む限り、内部のデータ構造に言及しているように見えますが、データ構造を変えることによって内部処理にもたらされるメリットが示されていないため、意味が取れない文章になっているように思われます。
もし、ユーザーから見える部分での変化を望むのあれば、それが伝わるような書き方 (データの持ち方を変えるのではなくて、振る舞いを変えてほしいという旨が伝わるような文章) をすると良いのではないでしょうか？

**Comment by syuilo** [comment]
> ソフトミュートを廃止し、ハードミュートのみにしたということでしょうか？

どちらかを廃止してもう一方のみにしたということではなく、統合して新しい仕様になったという感じですね
サーバー側で処理できることはサーバー側で行い、それができないシチュエーションではクライアントでやるという感じ

**Comment by syuilo** [comment]
「ソフト相当かハード相当か保持する」という意味がよくわかってないけど、

> タイムラインに誰が発言したかわかるミュートと痕跡もでないミュートの2つの区分がある仕様を残してほしい

というのがこのIssueということで合っているのかしら

**Comment by KisaragiEffective** [comment]
リリースPRを追いきれていないので推測を重ねますが、ハードミュート(相当の機能)は実際に削除されたわけではなく、クライアントに処理を寄せるためにバックエンドのデータ構造が変わっただけというコミットですか？

**Comment by tamaina** [comment]
>  現行の実装がどうなっているのか知りませんが、ソフトをハードに移行してもハードをソフトに移行しても混乱を産むことは必至です。

ということなので、まあつまりソフトとハードを分けたままにしてほしいというのが結論ではないかしら

**Comment by fruitriin** [comment]
ソフト(クライアント処理)とハード(サーバー側で処理)の話とソフト(ワンクッションで見れる)とハード(全く見えない)を使い分けよう

ワンクッションミュートと全く見えないミュートの2つある仕様を残してというように理解した

**Comment by tkmrgit** [comment]
ソフトミュートとハードミュート統合とのことだけど、サードパーティークライアントでも消えるハードミュートは実質無くなった？ということにににゃる？ ※off-topic

**Comment by KisaragiEffective** [comment]
> ソフト(クライアント処理)とハード(サーバー側で処理)の話とソフト(ワンクッションで見れる)とハード(全く見えない)を使い分けよう
> 
> ワンクッションミュートと全く見えないミュートの2つある仕様を残してというように理解した

その通りです。

**Comment by samunohito** [comment]
ハードミュート相当の機能は #12375 で実装されているので、同件と思われるこのissueもcloseします。
未解決な部分がある場合、その件をピックアップした別issueを立てていただけますと幸いです。
