### ISSUE TITLE
リプライを含めてlocal timelineを見る機能を戻してほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12001]
## Summary

LTLで話してるのを追ってるときに必要

**Comment by tamaina** [comment]
仕様なのか忘れただけなのかわからない

（HTLはリプライ含められるらしいけど）

**Comment by futchitwo** [comment]
ユーザー別で設定するようになったらしい？けどTLの全員をいちいち設定するのは大変そう（）

**Comment by anatawa12** [comment]
ユーザ別にoverrideがあってもいいとはおもうけど全体で設定がほしいと思う。

**Comment by fruitriin** [comment]
デフォルトで見える、個別に見えなくなるのほうがうれしいかも

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/803e0fe2-06f5-4157-a0d9-fd15a84498fd)

これがなくなったということか

**Comment by ikasoba** [comment]
リプライ先が投稿者によるもの(セルフ返信)はTLに流れてくるっぽい？

**Comment by anatawa12** [comment]
> ![image](https://user-images.githubusercontent.com/7973572/273913557-803e0fe2-06f5-4157-a0d9-fd15a84498fd.png)
> 
> これがなくなったということか

それがなくなって、

- Home TL: フォローしてるユーザごとに切り替えられるように
- List TL: ユーザとリストごとに切り替えられるように
- Local TL: 切り替えがない
- Global TL: 切り替えがない

という状態になってます。Localと(できればGlobal)TLで表示させる機能を復活させてくれというのがこのissueです

> リプライ先が投稿者によるもの(セルフ返信)はTLに流れてくるっぽい？

これは把握した上でissueを書きました。

**Comment by syuilo** [comment]
作業中
