### ISSUE TITLE
ミュートの文字数の緩和

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#12014]
## Summary

ハードミュートとソフトミュートが一つになった
一方で、ソフトミュートの文字数は2048文字らしい

これでは足りない人がいるみたい

**Comment by fruitriin** [comment]
2048文字じゃなかった、200文字しか保存できない

**Comment by syuilo** [comment]
ロールで設定できなかったっけ？

**Comment by fruitriin** [comment]
おお、知らなかった！ありがとう
