### ISSUE TITLE
UI icons are not displaying correctly on Firefox / Firefox Nightly

### ISSUE THREAD

**Issue by KirbyJoe** [syuilo/Misskey#12017]
## 💡 Summary

I was browsing [Misskey.io](misskey.io) on Firefox Nightly, but I noticed that the user interface icons are not displaying correctly. I also tried accessing other Misskey instances such as [Misskey.design](Misskey.design) and [KindWorld](misskey.kindworld.one), but the icons are still not displaying correctly. When I browse Misskey instances on Chrome (which is my default browser), the icons are displayed correctly. 

## 🥰 Expected Behavior

The icons should display correctly as shown below (screenshot from Chrome):
![image](https://github.com/misskey-dev/misskey/assets/20151551/1eaec03a-b801-45e2-ac94-8aa6b149d5d9)

## 🤬 Actual Behavior

The icons are displayed as garbled text/mojibake (screenshot from Firefox):
![ioアイコン表示バグ2 (ポストへのリアクション)](https://github.com/misskey-dev/misskey/assets/20151551/92677efc-2dbf-407e-98ef-5179a821d0dd)

## 📝 Steps to Reproduce

1. Access to any Misskey instances with Firefox

### 💻 Frontend
* Model and OS of the device(s):
  Alienware Aurora R7, Windows 10 Pro 22H2
* Browser:
  Firefox Nightly 120.0a1 (2023-10-11) (64bit)
* Server URL:
  misskey.io, misskey.design, misskey.kindworld.one
* Misskey:
  13.14.2-io.10 (Misskey.io), 2023.9.3-md.3 (Misskey.design), 2023.9.3 (KindWorld)

**Comment by CyberRex0** [comment]
https://github.com/webcompat/web-bugs/issues/118081

**Comment by futchitwo** [comment]
#10371

**Comment by zyoshoka** [comment]
Close as duplicate of #10371.
