### ISSUE TITLE
iPhone端末で撮影した特定のサイズの写真をアップロードすると、正常にアップロードされない

### ISSUE THREAD

**Issue by t1nyb0x** [syuilo/Misskey#12026]
## 💡 Summary
iPhone端末で撮影した写真をアップロードすると、失敗するのか真っ黒の画像になる

## 🥰 Expected Behavior
写真が正常にアップロードされること

## 🤬 Actual Behavior

iPhoneで撮影した写真を、iPhoneのPWAからアップロードしようとしたところ真っ黒の画像になりました。
この事象はSafariでアップロードした際にも確認しています。

同じ写真データをPCのブラウザからアップロードする分には問題なくアップロードできることを確認済みです。

また、以下の条件で検証を行いました。
1. 5712 x 4284 で、約4.5MBの写真をiPhoneのPWAからアップロードする
2. 5712 x 4284 で、約4.5MBの写真をiPhoneのSafariからアップロードする 
3. 5712 x 4284 で、約210KBの画像をiPhoneのPWAからアップロードする
4. 5712 x 4284 で、約210KBの画像をiPhoneのSafariからアップロードする 
5. 5712 x 4284 で、約4.5MBの写真をPCのブラウザからアップロードする

結果

|アップロード成功|アップロード失敗|
|:--:|:--:|
|3, 4, 5|1, 2|

そのため、ある一定のファイルサイズの画像をiPhoneでアップロードすると、失敗するのではないかと推測しているのですが
いかがでしょうか・・・

[ナンとカレーの写真](https://drive.google.com/file/d/1W-uFbj2asxx_-zhoZ6amG6RWCIKUEQ0M/view?usp=sharing)
[5812 x 4284のダミー画像](https://drive.google.com/file/d/1qM-cDU00SbBs1j6ECSeTxn2Hp64QU_Db/view?usp=sharing)
上記URLの写真を利用して、再現確認を行いました。

## 📝 Steps to Reproduce

1. 5712 x 4284 で、一定のファイルサイズ（今回約4.5MBの写真使用）の画像をiPhoneからアップロードする
2. アップロードに失敗して、黒い画像になる

### 💻 Frontend
* Model and OS of the device(s): iPhone 15 Pro
  
* Browser: PWA, Safari
  
* Server URL: misskey.t1nyb0x.cloud
  
* Misskey: 2023.10.0

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.10.0
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:  AlmaLinux9

**Comment by acid-chicken** [comment]
クライアント側の圧縮処理に問題がありそう

**Comment by mappi-pr** [comment]
iPhoneからアップロードして真っ黒になる画像（5712 x 4284）、マストドンだといい感じに小さく（1663x 1247）なってアップロードされてますね
アップロード周りの処理にヒントがあるといいのですが。。。

**Comment by acid-chicken** [comment]
> 謎ですね

ほんまか

https://github.com/misskey-dev/browser-image-resizer/issues/6#issuecomment-1787087413

**Comment by t1nyb0x** [comment]
ちなみに、オリジナル画像を保持を有効にしてアップする分には問題なく画像のアップロードができることを確認しています。

**Comment by samunohito** [comment]
こんな感じにすればいけるかも？というのを書いてきました
https://github.com/misskey-dev/browser-image-resizer/issues/6#issuecomment-1900011749
