### ISSUE TITLE
Invalid parameters on save in Control Panel → General

### ISSUE THREAD

**Issue by tastytea** [syuilo/Misskey#12020]
## 💡 Summary

in the Control Panel → General it says on save:  
> **Invalid parameters**  
> The request parameters are invalid. This is normally caused by a bug, but may also be due to inputs exceeding size limits or similar.”

even when i change nothing. there is nothing in the logs.

## 🥰 Expected Behavior

the settings are saved

## 📝 Steps to Reproduce

1. open Control Panel
2. go to General
3. click save

### 💻 Frontend
* Model and OS of the device(s):
  desktop pc / xiaomi mi 8 (LineageOS 20 (Android 13))
* Browser:
  firefox 115.3.1 (linux) / firefox 105.1.0 (android)
* Server URL:
  very.tastytea,de
* Misskey:
  2023.10.1

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.10.1
* Node: 20.6.1
* PostgreSQL: 15.4
* Redis: 7.0.13
* OS and Architecture: Gentoo Linux amd64

**Comment by ryanho** [comment]
I have the same problem too, in "General" and "Moderation".

**Comment by syuilo** [comment]
プライバシーポリシーに適当な文字列を入れてから保存するといけるかも

**Comment by ryanho** [comment]
@tastytea
Quick fix before 2023.10.2(?).
In General page, input some text in "Impressum URL" field and press "Save" button, the setting should be saved.
Then the error message won't show anymore.

**Comment by tastytea** [comment]
that worked, thank you! (it can be set to nothing later and saving will continue to work)

**Comment by spirillen** [comment]
Me too #12039
