### ISSUE TITLE
[2023.10.1] フォローしているチャンネルの投稿がLTLに表示されない

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#12029]
## 💡 Summary

フォローしているチャンネルの投稿がLTLに表示されない。
HTLとSTLには表示される。

## 🥰 Expected Behavior

フォローしているチャンネルの投稿がLTLに表示される。

## 🤬 Actual Behavior

フォローしているチャンネルの投稿がLTLに表示されない。

## 📝 Steps to Reproduce

1.
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  13.x.x

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service:docker compose
* Misskey: 2023.10.1
* Node: 20.x.x
* PostgreSQL: 15.3.x
* Redis: 7.x.x
* OS and Architecture: Ubuntu 22.04.2 LTS

**Comment by syuilo** [comment]
LTLはそのサーバーのパブリックな投稿が流れるTLだから正常かも？

**Comment by acid-chicken** [comment]
前がおかしかったような気もする

**Comment by prlg25** [comment]
こちら、2023.10.1にて類似の事象を確認しているのですが挙動としては
・LTLを開いている間に投稿されたチャンネル投稿がLTLを開いている間だけLTLに表示される
・STLに移動してLTLに戻るなどすると、取得したチャンネル投稿の部分のみタイムラインがリセットされる

という現象が起こっています。
こちらで話されている事象と同じか断定できないのですが、
例えばデッキ等でLTLを開きっぱなしにしていると今まで通りの挙動と同等で、新規のチャンネル投稿はLTLに流れてきますが、
デフォルトのレイアウトで、HTLやSTLなど頻繁に行き来している場合、LTLを見ている間に投稿されたチャンネル投稿しかLTLに表示されず、LTLを開くたびにチャンネル投稿がリセットされてしまうという挙動になります。

**Comment by nakkaa** [comment]
> LTLはそのサーバーのパブリックな投稿が流れるTLだから正常かも？
> 前がおかしかったような気もする

ありがとうございます。仕様ということで承知しました。

@prlg25 さん
記載されている事象は別問題のように見えますので、別途Issueを建てていただけますか。

本Issueはcloseします。
