### ISSUE TITLE
Social and Local Timeline empty after update

### ISSUE THREAD

**Issue by horaceyoung** [syuilo/Misskey#12028]
Hi Devs! Thank you for your help in advance.

## 💡 Summary

Using docker to upgrade misskey to 2023.10.1. Home and Local timeline are reset with no history notes.

## 🥰 Expected Behavior

Home and local timelines are normal.

## 🤬 Actual Behavior

There's only one note after me posting it.

![image](https://github.com/misskey-dev/misskey/assets/32321396/30a332f3-bef0-4745-a31d-b20495ea973d)

![image](https://github.com/misskey-dev/misskey/assets/32321396/872358bb-14bf-49fa-bfe9-e3ffb956cb03)

This has happened with a previous update as well.

## 📝 Steps to Reproduce

1. Update to 2023.10.1
2. Timelines are reset

### 💻 Frontend
* Model and OS of the device(s):
  MacBook Pro 16-inch 2023 13.5.2 (22G91)
* Browser:
  Chrome 117.0.5938.149
* Server URL:
  cafe.otter.homes
* Misskey:
  2023.10.1

* Installation Method or Hosting Service: docker compoese
* Misskey: 2023.10.1
* Node: v20.8.0
* PostgreSQL: postgres:15-alpine
* Redis: redis:7-alpine
* OS and Architecture: Debian 5.10.162-1 (2023-01-21) x86_64

**Comment by rakino** [comment]
I found the behaviour [noted](https://github.com/misskey-dev/misskey/releases/tag/2023.10.0) in 2023.10.0 release: 

> アップデートを行うと、タイムラインが一時的にリセットされます

**Comment by horaceyoung** [comment]
> I found the behaviour [noted](https://github.com/misskey-dev/misskey/releases/tag/2023.10.0) in 2023.10.0 release:
> 
> > アップデートを行うと、タイムラインが一時的にリセットされます

Hi thank you for your reply. I'm not sure if I'm understanding it correctly but temporarily shouldn't mean the timeline is reset permanently right? In our case it still hasn't recovered.

**Comment by HighDoping** [comment]
Same issue here. Remote notes not updating in home and social timeline. Global timeline works fine. Unfollow and follow again may solve the problem, but not efficient to do for every user.
Similar issue: #12029

**Comment by tai-cha** [comment]
duplicate of https://github.com/misskey-dev/misskey/issues/11958 and its merged.
This will be fixed on next release.
