### ISSUE TITLE
nyaizeを投稿時にやる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12030]
## Summary

サーバーサイドでノートをpackするたびにパーサー起動させて変換処理を行うのは若干重いため

**Comment by fruitriin** [comment]
isCatはずしたとにに元のテキストが

このコミットの前　> 元に戻る
このコミットのあと > にゃいずされたまま

ってことであってる？

**Comment by syuilo** [comment]
そうね

**Comment by anatawa12** [comment]
これnyaize先にされるせいで検索引っかからなくなったりしませんか？

**Comment by syuilo** [comment]
検索用はnyaize前のものを入れれば問題なさそう

**Comment by syuilo** [comment]
ただ検索のことなどを心配するのであればそもそもnyaize使わない方が良さそう

**Comment by anatawa12** [comment]
どっちかというとnyaizeする人の投稿を検索(含アンテナ)できなく(しづらく)なる方向で気になる人間です(私はnyaizeしする人じゃないけど)

個人的にはdbのデータ量増えちゃうけどnyaizedTextとかDBにはやして検索ではtextとかにできたりしないかなとか思ってます

**Comment by sim1222** [comment]
個人的には検索やアンテナからは除外して欲しくないです。
ユーザーはnyaizeされることを了承した上でCatにしているはずなので、nyaizeによって検索結果に出にくくなる（文字が一致しない）以外の意図的な制約は不要だと考えています。

**Comment by syuilo** [comment]
クライアントで表示時に変換すれば解決しそう(すでにクライアントではparseしているためパフォーマンスコストは発生しない)

**Comment by syuilo** [comment]
クライアントが対応してないとnyaizeされないデメリットはある

**Comment by fruitriin** [comment]
nyze前のテキストとnyze後のテキストを両方DBにいれとくのが個人的にはうれしみ

**Comment by syuilo** [comment]
それはあまりに非効率な気がする

**Comment by fruitriin** [comment]
nyzeされたものだけをDBに残すととオリジナルのテキストに戻らないことだけが気がかり

**Comment by syuilo** [comment]
> nyzeされたものだけをDBに残すととオリジナルのテキストに戻らないことだけが気がかり

> クライアントで表示時に変換すれば解決しそう(すでにクライアントではparseしているためパフォーマンスコストは発生しない)

で解決しそう

**Comment by anatawa12** [comment]
私は元の問題意識である検索/アンテナ時にNyaize前で引っかかるようなのでクライアントでいいと思ってます

**Comment by mei23** [comment]
クライアント依存で変換するようにしたら人々を困らせることが出来なくなるわ

**Comment by syuilo** [comment]
それもデメリットとしてあるんだけどパフォーマンスを犠牲にすることなくnyaizeする方法がそれくらいしかなさそう

**Comment by syuilo** [comment]
昔のような単純な文字列置換ならパースしなくていいからパフォーマンスへの影響は無視できてたんだけど

**Comment by syuilo** [comment]
あと猫耳付けたいけどnyaizeしたくないというクレームがやっぱり多くて人間を困らせない方が良いかもしれなくなってきた
クライアントでやればnyaizeするかどうかを自由に決められるからそれにも対応できる(ただ猫耳云々に関しては構想中のアバターデコレーション機能で解決できるけど)

**Comment by CAT5NEKO** [comment]
nyaizeを識別するために猫耳つけて遊んでるんだったら、分離したらただの飾りになっちゃう気がする。
後々アイコンのカスタムアイテムとして拡充していくんだったらありだと思うけど...

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/mfm.rs 活用したら速くなる説

**Comment by fruitriin** [comment]
今後のMFMの拡張にmfm.jsとmfm.rsのメンテが必要になってめんどくさいのでは（あとmfmのパースをサーバーサイドで行いたくないのでは）

**Comment by acid-chicken** [comment]
fn 構文がある以上将来的に変更を加える可能性は少ないのと、どうせ Swift 実装とかそのうち作らないといけないので統一はどの道無理

**Comment by mei23** [comment]
今回3→2になったけど
1. 投稿前クライアントで行う (クライアントで1回負荷, 困る人間=全員, オプトアウトできる人間=投稿者)
2. 投稿時サーバーで行う (サーバーで1回負荷, 困る人間=全員, オプトアウトできる人間=投稿者？)
3. 送信時サーバーで行う (サーバーで毎回負荷, 困る人間=対応サーバー, オプトアウトできる人間=サーバー実装？)
4. 表示時クライアントで行う (各クライアントで1回負荷, 困る人間=対応クライアント, オプトアウトできる人間=閲覧者)

負荷の問題はこれでよくて
仮にnyaizeと猫耳を分離したいとか投稿ごとに制御したいという需要がある場合でも1 or 2で実現可能と思ってるのだわ。

結果的に投稿者が全て制御出来るようになって、閲覧者はオプトアウト出来る抜け穴がなくなる。

**Comment by mei23** [comment]
2 vs 4だと、現行投稿時にもサーバーでメンション/ハッシュタグ/絵文字のためにMFM解析してるので、MFM解析回数は変わらないと思うのだわ。

~~このコミットの状態だと、サーバー上でのMFM解析が2回になっちゃってるかもだわ。
https://github.com/misskey-dev/misskey/commit/061e389340a7e5683be2ba0da4e1a1048597ccb6~~
patsedText が解析後オブジェクトだからそんなことなかったわ

**Comment by syuilo** [comment]
投稿はそんなに高頻度で行われないから投稿時に何回パースしてもそこまで影響ないんだけど、pack処理はものすごい数実行されるからそこを減らしたい

**Comment by syuilo** [comment]
1と2だとDBにnyaize後のものが保存されるから検索に引っかからない問題とかうまく翻訳できなくなる問題がありそう

**Comment by syuilo** [comment]
で3は負荷が高い問題があるからそうなると4しかない

**Comment by mei23** [comment]
>閲覧者はオプトアウト出来る抜け穴がなくなる。

isCatを付けちゃうと、旧バージョン/サードパーティ/他実装はnyaizeしちゃうわね

**Comment by syuilo** [comment]
> 1と2だとDBにnyaize後のものが保存されるから検索に引っかからない問題とかうまく翻訳できなくなる問題がありそう

これに関しては個人的にはそういった不便を含めてのジョーク機能だからそれで良いんじゃないかという気もするけど

**Comment by mei23** [comment]
> 検索に引っかからない問題とかうまく翻訳できなくなる問題

思いっきり名詞が変換されたりしない限りはにゃんとなくイケそうな気がしてるわ

**Comment by FineArchs** [comment]
投稿時にパースだけしてDBには原文とnyaのインデックスを保存ではダメですか？

**Comment by syuilo** [comment]
> 投稿時にパースだけしてDBには原文とnyaのインデックスを保存ではダメですか？

あまりにも無駄な感じがある

**Comment by syuilo** [comment]
やっぱりクライアントで表示時にやりたくなってきた

**Comment by Nanashia** [comment]
> 3. 送信時サーバーで行う (サーバーで毎回負荷, 困る人間=対応サーバー, オプトアウトできる人間=サーバー実装？)
> 4. 表示時クライアントで行う (各クライアントで1回負荷, 困る人間=対応クライアント, オプトアウトできる人間=閲覧者)

単なるアイデアだけど、各TL取得APIで disableNyaizeみたいなパラメタ生やしてWebクライアントの場合はdisableNyaize: true指定でnyaizeスキップ(4)、既存のサードパーティークライアントはデフォルトでnyaizeされたテキストがもらえる(3.)とサードパーティークライアントの実装の負担を減らせないかしら。

現実的に大半の利用者はWebだと思うのでサーバー負荷軽減の目的は達成しつつ、（nyaize対応してない）サードパーティークライアントだとnyaizeされないみたいな利用者視点でバグっぽい挙動をなくせると思った

**Comment by syuilo** [comment]
それでも良さそう
