### ISSUE TITLE
The request parameters are invalid

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#12039]
## 💡 Summary

While trying to set more or less any settings whit a input field as admin, provides this error msg

```
The request parameters are invalid. This is normally caused by a bug, but may also be due to inputs exceeding size limits or similar.
```

## 🥰 Expected Behavior

Changes to be committed

## 🤬 Actual Behavior

When trying to apply new reserved usernames to the Moderation options

![image](https://github.com/misskey-dev/misskey/assets/44526987/2601358e-c338-4c29-908a-78b04268d1e5)

![image](https://github.com/misskey-dev/misskey/assets/44526987/25a2b2ab-498d-43d7-8489-b094cfeedb0c)

## 📝 Steps to Reproduce

1. open control panel
2. choose moderation
3. type in some reserved usernames
4. press `save`

## 📌 Environment
2023.10.1

### 💻 Frontend
* Model and OS of the device(s):
  `5.15.0-86-generic`
* Browser:
  FireFox + Tor
* Server URL:
  [](https://matrix.rocks/about)
* Misskey:
  2023.10.1 (This is the second location you ask for this!!)

### 🛰 Backend (for server admin)
`5.15.0-86-generic`

* Installation Method or Hosting Service: "Misskey install shell script"
* Misskey: 2023.10.1 (This is the third location you ask for this!!)
* Node: v20.5.1
* PostgreSQL: 15.4-2.pgdg22.04+1
* Redis: 7.2.1 build=95712a67f5005c28
* OS and Architecture: Ubuntu 22.04 LTS x86_64

**Comment by kakkokari-gtyih** [comment]
Duplicate of #12020
