### ISSUE TITLE
URLを含むノートをした際にプレビューが表示されない

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12035]
## 💡 Summary
URLを含むノートをした際、プレビューが正常に表示されない。
考えられる原因としてはSummaly Proxyだが、空欄にしても解決しなかった。
（現在は `https://summaly.arkjp.net` を使わせてもらっています）
自分で立てたサマリープロキシでも同様です。
私の管理するサーバー以外でも発生している鯖缶さんがいます。

特定のページで発生するわけではなく、あるとき表示できていなくてもあとで見直すと表示できるときもある。

## 🥰 Expected Behavior
ページのタイトルや画像がノートに埋め込まれて表示される

## 🤬 Actual Behavior
ごくたまに正常に表示されるが、大半は以下の画像のように「プレビューできません」状態になる。
同一サーバー内のチャンネルのURLなどでも駄目。
![image](https://github.com/misskey-dev/misskey/assets/732664/6d8ce6ab-de3e-4e81-adb7-aa17faa08e51)

ブラウザのコンソールで確認すると
https://[server url]/url?url=https%3A%2F%2Fwww.itmedia.co.jp%2Fmobile%2Farticles%2F2310%2F08%2Fnews042.html&lang=ja-JP
を読み込む際 422 が返ってきてしまっている。
`{"error":{"code":"URL_PREVIEW_FAILED","id":"09d01cb5-53b9-4856-82e5-38a50c290a3b","kind":"client"}}`

本来であればこのURLはサマリープロキシ経由のURLになるべきではないか？

## 📝 Steps to Reproduce

1. URLを含むノートを投稿する
2. TLでノートを表示する

## 📌 Environment
2023.9.3
2023.10.1

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  2023.10.1

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture: Ubuntu 22.04.2 LTS

**Comment by syuilo** [comment]
ローカルでは再現できなかったわね

**Comment by CyberRex0** [comment]
summaly.arkjp.netは利用できなくなっていると思います

**Comment by kanade** [comment]
> ローカルでは再現できなかったわね

ご確認ありがとうございます。
不思議なことにここ数日はプレビューが正常に表示される頻度が上がっています。
しかしTLをさかのぼったりすると、過去表示できていたものでも表示できないこともあり悩ましいです。

**Comment by kanade** [comment]
> summaly.arkjp.netは利用できなくなっていると思います

そうなんですか？！ それは知らなかったです…

`https://summaly.arkjp.net/url?url=https://google.co.jp`
これで応答があるので使えるものだと思い込んでいました。

すると今後は自前でサマリープロキシを立てるか、あるいは未指定で使う必要があるということでしょうか？

**Comment by kanade** [comment]
Cloudflare TunnelsとApplicationsを使っているのですが、本件に影響しそうな設定などありますでしょうか。

**Comment by kanade** [comment]
しゅいろちゃんの https://github.com/syuilo/summaly こちらをGCPに立てて試したところ、URLのプレビューは正常に表示されるようになりました。
この件はMisskey本体とは別の問題でしたので、このIssueはクローズしますね。
