### ISSUE TITLE
System msg not delivered

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#12046]
## 💡 Summary

System msg not delivered

![image](https://github.com/misskey-dev/misskey/assets/44526987/e8787b48-88e7-4d60-97bb-c834a4b7f3a3)

## 📌 Environment
2023.10.1

### 💻 Frontend
* Model and OS of the device(s):
  `5.15.0-86-generic`
* Browser:
  FireFox + Tor
* Server URL:
  [](https://matrix.rocks/about)
* Misskey:
  2023.10.1 (This is the second location you ask for this!!)

### 🛰 Backend (for server admin)
`5.15.0-86-generic`

* Installation Method or Hosting Service: "Misskey install shell script"
* Misskey: 2023.10.1 (This is the third location you ask for this!!)
* Node: v20.5.1
* PostgreSQL: 15.4-2.pgdg22.04+1
* Redis: 7.2.1 build=95712a67f5005c28
* OS and Architecture: Ubuntu 22.04 LTS x86_64

**Comment by Mar0xy** [comment]
This is also intended as it literally is something that just runs daily see "will run at:" below "added at:"

**Comment by spirillen** [comment]
~~ Hmm don't see the run at, but is they are "cronjob" maybe they should have a comment about it like cron or timed ~~

Found it... the entry is clickable :smile: 

Again, the manual :unamused:

Thanks for your feedback.
