### ISSUE TITLE
Mk:apiExternalの対象を連合中のインスタンスだけにする

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#12040]
## Summary
悪意のあるPlay・プラグイン作者によりトークン等が外部に送信されるリスクを低減させるため、Mk:apiExternalでリクエストを送ることのできる相手を`federation/instances` `{blocked: false}`で取得可能なサーバーに限定することを提案します。

**Comment by kakkokari-gtyih** [comment]
連合先のユーザーが悪意あるプログラムを組むかどうかまでを気にすることはできないし、仮になにかされたとしたら対応方法がサーバーブロックだけになってしまう（＝サーバーに所属している悪事に加担していないユーザーのノートとかも流れなくなる）のもなんか違う気がするのでむずそう

**Comment by FineArchs** [comment]
@kakkokari-gtyih 連合先のプログラムが自動で実行できるわけではないので、連合先のユーザーが悪意あるプログラムを組む心配はないような？

**Comment by kakkokari-gtyih** [comment]
それはそうか

**Comment by syuilo** [comment]
mk:apiExternalってトークンとか送信できるようになってたっけ

**Comment by FineArchs** [comment]
@syuilo 
- 第四引数に指定すれば送信可能です
- 適当なパラメータにトークンを含めれば送信可能です

**Comment by syuilo** [comment]
それってユーザーが自分で設定する必要があるはずだから意図せず送信されることはなくないかしら？

**Comment by FineArchs** [comment]
Xのサーバーに送ると称して影でYのサーバーにも送るようなケースを想定しています

**Comment by syuilo** [comment]
ほむん

**Comment by fu-sen** [comment]
たまたま見たのでコメント入れます。Mk:apiExternal を経由して匿名のノートができる Play が作成された事例があり、その経緯が note に投稿されました、これに影響してこの issues が建った、という経緯のようです。
https://note.com/yuki_20020924/n/n2515ac1e7339

**Comment by syuilo** [comment]
Mk:apiExternal 自体が使えなくなった

**Comment by KisaragiEffective** [comment]
> Mk:apiExternal 自体が使えなくなった

メモ: https://github.com/misskey-dev/misskey/commit/fcf0f5f6b52efc9d7c42d4968de5590554b042f9
