### ISSUE TITLE
endedPollNotification: not delivered for a week

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#12045]
## 💡 Summary

endedPollNotification: not delivered for a week

![image](https://github.com/misskey-dev/misskey/assets/44526987/a173ccff-832d-4ab3-972e-779640c17fbc)

## 📌 Environment
2023.10.1

### 💻 Frontend
* Model and OS of the device(s):
  `5.15.0-86-generic`
* Browser:
  FireFox + Tor
* Server URL:
  [](https://matrix.rocks/about)
* Misskey:
  2023.10.1 (This is the second location you ask for this!!)

### 🛰 Backend (for server admin)
`5.15.0-86-generic`

* Installation Method or Hosting Service: "Misskey install shell script"
* Misskey: 2023.10.1 (This is the third location you ask for this!!)
* Node: v20.5.1
* PostgreSQL: 15.4-2.pgdg22.04+1
* Redis: 7.2.1 build=95712a67f5005c28
* OS and Architecture: Ubuntu 22.04 LTS x86_64

**Comment by Mar0xy** [comment]
This is intended as the endedPollNotification is only suppose to be delivered/triggered when the note's poll has ended as it triggers the poll has ended notification for users

**Comment by spirillen** [comment]
OK, just seems weird, but ok.

This should be added to the docs, which I'm missing a lot.
