### ISSUE TITLE
ツイート→ポストに変更

### ISSUE THREAD

**Issue by nryeouo** [syuilo/Misskey#12050]
## Summary
expandTweetを「ツイートを展開する」から「ポストを展開する」に

https://github.com/misskey-dev/misskey/pull/11436#issue-1828585241
（2023-07-31）
> 「ツイート」の文言については現状変更が発表されていない

↑「ポスト」が浸透してきたから、そろそろ替え時かもしれない
<img width="711" alt="image" src="https://github.com/misskey-dev/misskey/assets/43399370/51e78c07-3e99-49a9-b154-6fd0ca8f0a0f">

**Comment by mappi-pr** [comment]
手元ソースを「tweet」と「ツイート」でGrepした限りでは、
https://github.com/misskey-dev/misskey/blob/e9db0680c42cab649d105897a7c6628a2d2f8d85/locales/ja-JP.yml#L595
ここだけ直してPR出して、マージされたらCrowdin更新する感じ？に見えました

**Comment by nryeouo** [comment]
merged
