### ISSUE TITLE
コードブロックのシンタックスハイライトを拡充する(AiScript等)

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#12054]
## Summary

AiScriptやMFMはMisskeyで使用されている言語です。
AiScriptのシンタックスハイライトは現状JSのものを使っているようで、今のところそれらしく表示されてはいますが、今後文法が変わるにあたりJSのシンタックスハイライトをそのまま使えなくなる可能性があると思います。
また、MFMには現状シンタックスハイライトがありません。

### Misskeyに関連する言語
- AiScript (`aiscript`, `is`)
- MFM      (`markup-language-for-misskey`, `mfm`)
- TypeScript
- Vue
- JSON
- YAML

### その他の言語
C#やC++等[Prism](https://prismjs.com/)が対応している言語([Autoloader](https://prismjs.com/plugins/autoloader/)を使用?)

**Comment by kakkokari-gtyih** [comment]
バンドルサイズが肥大化するのでいたずらに複数言語のハイライティングに対応するのは微妙かもしれない

**Comment by kakkokari-gtyih** [comment]
AiScript・MFMのシンタックスハイライティングについては賛成（VSCode拡張などで使うことも考えて別リポジトリを立ててもいいかも）

**Comment by MineCake147E** [comment]
CDNは利用できないのでしょうか。
https://prismjs.com/index.html#basic-usage-cdn

**Comment by kakkokari-gtyih** [comment]
> バンドルサイズが肥大化するのでいたずらに複数言語のハイライティングに対応するのは微妙かもしれない

たしかに元コメントで言及されているとおり https://prismjs.com/plugins/autoloader/ を使うといけるかも（言語定義ファイルを別で持たせればいけそう）

**Comment by MineCake147E** [comment]
ちなみに少しOff-topicですがVSCode向けのAiScriptシンタックスハイライトは既にあるようです(私も使ってます)
https://github.com/tubone24/aiscript-syntax-vscode

**Comment by kakkokari-gtyih** [comment]
> ちなみに少しOff-topicですがVSCode向けのAiScriptシンタックスハイライトは既にあるようです(私も使ってます) https://github.com/tubone24/aiscript-syntax-vscode

公式で用意してもいいかなぁと思った（今思いついただけなので決定ではない）

**Comment by kakkokari-gtyih** [comment]
- Prism → Shiki にする（tmLanguageが使えるようになる）
- AiScriptのハイライティングを[ここ](https://github.com/aiscript-dev/aiscript-vscode)から持ってくる

がメンテ楽そうでいいかも

**Comment by MineCake147E** [comment]
確かにその方が言語定義を統一出来て整備性が良さそうですね。
