### ISSUE TITLE
“つながりの公開範囲”がフォロー・フォロワー個別設定できるように

### ISSUE THREAD

**Issue by MizuiMiduki** [syuilo/Misskey#12072]
## Summary
プライバシー設定の“つながりの公開範囲”を、現状のフォロー・フォロワーで括るのではなく、それぞれ個別に設定できたほうが便利かと思います。

考えられるニーズとしては、
- フォロー数は見られてもいいけど、誰をフォローしているか見られたくない
- 全年齢向けのノート・リノートしかしていないが、NSFWやR15以上の内容をノートするユーザーをフォローしているのでフォローだけ隠しておきたい(クリエイターなどは特に個人・ブランドイメージなどの問題も関わると思われる)
- 関係者のみフォローしているので公開したいがフォロワーは非公開にしたい
などがあります。

**Comment by zyoshoka** [comment]
Resolved by #12702
