### ISSUE TITLE
ダイアログの本文が表示されない

### ISSUE THREAD

**Issue by ikasoba** [syuilo/Misskey#12076]
## 💡 Summary

ダイアログの本文が表示されないようです。

## 🥰 Expected Behavior

ダイアログの本文が表示されること。

## 🤬 Actual Behavior

ダイアログの本文が何故か、表示されない。

## 📝 Steps to Reproduce

1. 適当な投稿へリアクションをする
![image](https://github.com/misskey-dev/misskey/assets/57828948/c7aeb6ba-5a26-46ae-a62c-02e251af42e9)
2. リアクションを取り消そうとする
![image](https://github.com/misskey-dev/misskey/assets/57828948/1f8eaf8a-bd31-4eac-8b3d-3fa01fa1ca4d)

### 💻 Frontend
* Model and OS of the device(s):
  windows 10
* Browser:
  118.0.5993.71 (Official Build) （64 ビット） (cohort: Control) 
* Server URL:
  misskey.systems
* Misskey:
  2023.10.2-beta.2

**Comment by syuilo** [comment]
これで直ったかも
https://github.com/misskey-dev/misskey/commit/721cbe085b39dc8feeb4e57cf75d9c801a5db66d

**Comment by ikasoba** [comment]
ありがとうございます！ m(_ _)m
