### ISSUE TITLE
「フォロワーの解除」の確認ダイアログの「OK」ボタンの表示を10秒間遅延させる

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#12077]
## Summary

「フォロワーの解除」等の操作を行う際に表示される
![image](https://github.com/misskey-dev/misskey/assets/31585494/1130eb17-c4d6-4d9c-984f-b87673489bdf)
このような確認ダイアログの「OK」ボタンが表示されるのを10秒間遅延させることにより、衝動的な操作を防ぐことができる可能性があります。

**Comment by syuilo** [comment]
衝動的な操作というのはどういったものを指していますか？

**Comment by MineCake147E** [comment]
任意の感情により突き動かされるまま、理性を取り戻す前に操作を完了し、後から後悔するような操作を指します。

**Comment by kakkokari-gtyih** [comment]
10秒はさすがに通常の操作での確認にしては長すぎる気がするので5秒くらいにしても良さそう

**Comment by SanMurakami** [comment]
いらない
自分は結構海外からDMスパムとか来ますが、ブロックする時にいちいち時間待たされるのは嫌すぎるので

**Comment by syuilo** [comment]
個人的には不便にしか感じない気がする

**Comment by MineCake147E** [comment]
すみません。スパムへの考慮が欠けていました。

**Comment by kakkokari-gtyih** [comment]
たしかに「ブロック」「フォロー解除」に関しては、したところであとから戻せるので要らないかも

**Comment by SanMurakami** [comment]
そもそもブロックするほど嫌な相手なら理性を取り戻してブロックを解除しても、結局関わってるうちに嫌になってブロックする可能性の方が高いと思う

**Comment by MineCake147E** [comment]
「フォロワーの解除」にしぼりましたが、多くの👎がついたのでClose致しました。
