### ISSUE TITLE
各タイムラインの説明を簡略化する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12086]
## Summary
現状の文章ベースの説明をアカウント登録時のチュートリアルに統合して、タイムライン側ではMkInfoでそれぞれ表示する（簡潔な文で）

Firefishにあったこれが良いなぁと思ったので提案
![image](https://github.com/misskey-dev/misskey/assets/67428053/21e0dfbd-c7e1-432a-a2be-79ef7782830d)

**Comment by syuilo** [comment]
🆒

**Comment by syuilo** [comment]
> 現状の文章ベースの説明をアカウント登録時のチュートリアルに統合

これは実装にもよるけど検討の余地があるかも

**Comment by syuilo** [comment]
> タイムライン側ではMkInfoでそれぞれ表示する（簡潔な文で）

こっちは確実に欲しい

**Comment by kakkokari-gtyih** [comment]
> > 現状の文章ベースの説明をアカウント登録時のチュートリアルに統合
> 
> これは実装にもよるけど検討の余地があるかも

２つとも表示されるのは場所取りすぎるのと、Misskeyの使い方に関する説明なので初回だけダイアログ内で表示でよさそう

**Comment by kakkokari-gtyih** [comment]
あとはチュートリアルを再度行うメニューをつけるとか

**Comment by kakkokari-gtyih** [comment]
https://github.com/misskey-dev/misskey/pull/12141 でやってみた
