### ISSUE TITLE
HTLがリセットされ続ける

### ISSUE THREAD

**Issue by trpgerasami** [syuilo/Misskey#12088]
## 💡 Summary
2023.10.xへupdateしてからHTLがリセットされ続ける。
→3時間ほどアクセスしないとHTLがリセットされる。
（全員ではないが、複数のアカウントがリセットされ続けている）

## 🥰 Expected Behavior
HTLのリセットはアップデート直後の1度のみ

## 🤬 Actual Behavior
HTLのノートがリセットされ続ける。

## 📝 Steps to Reproduce

0.HTLがリセットされている。
1.ノートを投稿すると1〜2時間ほど前までのHTLは表示されるようになる
2.2〜3時間以上過去のHTLを遡ることはできない（ノートが表示されない）
3.3時間ほど放置すると0に戻る

※LTL/チャンネル/通知欄においては問題なく過去のノートを遡ることができる

### 💻 Frontend
* Model and OS of the device(s):スマホPC問わず。複数のアカウントに発生している。

* Server URL:https://trpger.us/

* Misskey:
  2023.10.1

### 🛰 Backend (for server admin)

* Misskey:  2023.10.1
* Node: 20.5.1
* PostgreSQL: 15.4.x
* Redis: 7.2.1
* OS and Architecture: Ubuntu 22.04.3 LTS

**Comment by syuilo** [comment]
自分では再現できず謎

**Comment by syuilo** [comment]
Redisの永続化の設定ができていないとか？(それでもフォールバックされそうだけど)

**Comment by camilla-ett** [comment]
2023.10.2 へのアップデート以降、https://kasei.ski/ でも同様の報告がありました。
（2023.10.1 の時から報告がなかっただけであったのかも？
（私自身が現象を再現出来ていないので、手元で再現方法を模索中……

**Comment by syuilo** [comment]
RedisにTLをキャッシュすること自体をオフにできるようにするか

**Comment by miyakogi** [comment]
フロントエンドのコードを少し変更していますが、同様の症状が発生していたサーバーでRedisのTLキャッシュ (FTT) 無効化を試しましたのでご参考までに報告いたします。
なお、一旦バニラの状態に戻しても症状は発生し続けていました。

2023.10系以降、https://empire.miyaco.moe/ にて同様の症状が一部アカウントのHTL/STLにおいて発生していました。
2023.11.0-beta.3にアップデート後FTTを無効にしたところ、症状の発生していたタイムラインも遡れるようになりました。
再度FTTを有効にすると、症状の発生していたタイムラインでは症状が再発しました。

**Comment by hideki0403** [comment]
https://misskey.yukineko.me でも同様の現象が発生していましたが、Redis側にキャッシュしてあったノートがミュート等でフィルタされ、返すことのできるノートが0件だった場合にHTLが空になる（リセットされる）ことを確認できました。

以下の手順で再現することができます。
1. 新しくアカウントを2つ作成し、アカウントAからアカウントBをフォローする
2. アカウントAで何かしらノートする
3. アカウントBで10件以上ノートする
4. アカウントAでアカウントBのことをミュートする
5. アカウントAのHTLが空になり、手順2で投稿したノート（およびそれ以前のノート）が見れなくなる

この問題を修正したPR (#12124) を作成しましたので、お手数をお掛けしますがご確認頂けますと幸いです🙏

**Comment by miyakogi** [comment]
ローカル環境で確認しただけですが、#12124 でホームタイムラインの問題が解消することを確認しました。
ただ、他のタイムライン(ローカル、ソーシャル)でも同じ条件を満たすと空になってしまうようです。

**Comment by setaria430** [comment]
チャンネルもですね
