### ISSUE TITLE
[UI]コンソールパネル内の一部項目で、表示が崩れている

### ISSUE THREAD

**Issue by mf2fox** [syuilo/Misskey#12099]
頑張れば操作できることに気がついたのでclose

## 💡 Summary
コンソールパネルの"サーバーブロック・サイレンス"及び、"ジョブキュー"項目の上部メニューが崩れている。
![image](https://github.com/misskey-dev/misskey/assets/137166103/4d790a6f-4026-41cd-9c5b-946c7cbf4469)

## 🥰 Expected Behavior
オーバーフローを水平方向のスクロールを可能にするなどして、メニューを選択できるようにする。

## 🤬 Actual Behavior
見切れてしまって項目が選択できない。

## 📝 Steps to Reproduce

1.コンソールパネルを開く
2.ジョブキュー||サーバーブロック・サイレンスを画面幅が狭い端末で開く

### 💻 Frontend
Device: iPhoneSE3
Browser: Safari(PWA)
Misskey: 2023.10.2

**Comment by zyoshoka** [comment]
水平方向のスクロール自体は可能ですが、改行されるようにした方が便利ですね（実際「カスタム絵文字」ではそうなっています）
