### ISSUE TITLE
ユーザーのプロフィール内の「ノート」をクリックしたときノート一覧のページに遷移するように

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12108]
## Summary
ユーザーのプロフィール（概要ページ）にある「ノート」をクリックしたとき、そのユーザーのノート一覧のページに飛ぶように変更することを提案します。

現状、「ノート」をクリックしてもそのユーザーの概要ページに留まるだけです。ただ、2023.10.0 からユーザーの概要ページにはハイライト（featured）のノートが載るようになったので、「ノート」をクリックした際には全てのノートが閲覧できるノートページに遷移するほうが（「ノート」に付された全ノート数を踏まえると）より直感的な挙動であると思います。

**Comment by lynlynlynx** [comment]
ノート一覧に行ってしまうのはさすがにbio見たいっていう気持ちに反する気がするので、v2023.10の感じで行くのであればmei23/misskeyみたいにちょっと覗けるようにするのは良いかもしれない。

**Comment by lynlynlynx** [comment]
これ、現在のバージョンでは解消されているのでcloseしてもいいと思います。
