### ISSUE TITLE
リストTLからフォロワー限定ノートが消える

### ISSUE THREAD

**Issue by kleuzjatob** [syuilo/Misskey#12110]
## 💡 Summary

リストTLを表示させた状態で取得対象のユーザがフォロワー限定ノートを投稿すると（表示権限があれば）そのリストTLに流れるのは従来通りかと思いますが、別の画面に切り替えて戻るとそのノートが消えております。
また、当該リストTLを表示させていなかった場合の切り替え時もノートは表示されません。

ダイレクトノートは問題なく継続的に表示される様です。（https://github.com/misskey-dev/misskey/issues/11991 のお陰？）

## 🥰 Expected Behavior

リストTLでフォロワー限定ノートが継続的に表示される

## 🤬 Actual Behavior
リストTLに表示されたフォロワー限定ノートが画面切り替えで消失する

## 📝 Steps to Reproduce

1. 自分を取得対象としたリストを作成する
2. 1.のリストTLを表示する 
3. フォロワー限定ノートを投稿する
4. 1.のリストTLに3.のフォロワー限定ノートが表示される
5. 1.のリストTLから別の画面に切り替える
6. 1.のリストTLを再度表示する
7. 3.のフォロワー限定ノートが消えている

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  Chrome 118.0.5993.89, Firefox 118.0.2
* Server URL:
  gp.tsukimi.club
* Misskey: 2023.10.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: systemd
* Misskey: updated from 2023.9.3 to 2023.10.2
* Node: 18.18.0
* PostgreSQL: 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
* Redis: 7.0.8
* OS and Architecture: Ubuntu 20.04.1 LTS x86_64

**Comment by lynlynlynx** [comment]
うち（v2023.10.2 と v2023.11.0-beta.1）でも発生しています。
自分を含むリストで自分のフォロワー限定の投稿がページ更新で消えます。でも他人のフォロワー限定の投稿は消えてない。

以下の箇所で `userListUserId` と 自分のIDが同じ場合も条件に入れないといけなさそう？（よくわからない）
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/NoteCreateService.ts#L869

**Comment by syuilo** [comment]
🙏🏻

**Comment by kleuzjatob** [comment]
修正ありがとうございます。
アップデート間もない事で調査不足でしたが、自分のノートのみの現象なのですね。
フォロイーのノートはv2023.10.2でも映る事を後に確認しております。ありがとうございました。
