### ISSUE TITLE
特定状況でフォロワー限定投稿が見えてしまう

### ISSUE THREAD

**Issue by setaria430** [syuilo/Misskey#12117]
## 💡 Summary
自分がフォローしていない人（Aとする）のフォロワー限定ノートに、自分がフォローしている人（B）がリプライを送った場合、Aのノートが見えてしまう
Streamでのみ発生する（リロードしたり、Bの個人ページからノート一覧を見ても発生しない）

## 🥰 Expected Behavior
Aのノートは(非公開)と表示され、見えない

## 🤬 Actual Behavior
ノート本文がすべて表示される

## 📝 Steps to Reproduce

1. 「TLに他の人への返信を含める」にチェックを入れておく
2. 任意のアカウント（A）がフォロワー限定ノートを行う
3. そのノートに、自分がフォローしているアカウント（B）がリプライを送る

## 📌 Environment
![Image 206](https://github.com/misskey-dev/misskey/assets/125631064/133bd36d-d9ed-4877-b789-ff035204d557)
![Image 207](https://github.com/misskey-dev/misskey/assets/125631064/82167020-1a10-4e93-bb34-e0f588d32c7c)

### 💻 Frontend
* Model and OS of the device(s):
  Windows 10 pro
* Browser:
  Chrome 118.0.5993.71
* Server URL:
  https://misskey.gamelore.fun/
* Misskey:
  2023.10.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by syuilo** [comment]
これはどのタイムラインで発生しますか？

**Comment by setaria430** [comment]
ホームとソーシャルタイムラインで発生します。リストには出ませんでした
ホームタイムラインには「TLに他の人への返信を含める」の設定がありませんが、フォローボタン横のメニューより同項目を有効にすることで再現できます。（反映まで少しラグがあるかもしれません）

**Comment by syuilo** [comment]
🙏🏻
