### ISSUE TITLE
pull_req時にAPI diffの実行ができない

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#12122]
## 💡 Summary

pull_req時にAPI diffの実行ができない

## 🥰 Expected Behavior

API diffの実行をしてコメントが投稿される

## 🤬 Actual Behavior

権限が足りなく実行できない

## 📝 Steps to Reproduce

1. MisskeyにPRを送る
2. CIが走る
3. 失敗する

**Comment by tai-cha** [comment]
https://github.com/misskey-dev/misskey/pull/12105#issuecomment-1774268218
https://github.com/misskey-dev/misskey/pull/12105#issuecomment-1774351064

**Comment by tai-cha** [comment]
Misskey以外からPRを送った際に実行できない問題、自分のPRでは動いていたので完全に見落としていた

**Comment by tai-cha** [comment]
数日中、遅くとも今週中にはやる

**Comment by anatawa12** [comment]
着手してもいいです？

**Comment by tai-cha** [comment]
@anatawa12 可能であればお願いします！自分のassign外しておきます:pray:

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/runs/6620608207

やっぱりpullreqの取得失敗してる(`github.event.workflow_run.pull_requests`が空になってる)のでartifacts経由でpullreq番号渡すのに戻したほうが良さそうなので戻すpullreqなげます。

```
Run # find first pull requests that targets this repository
  # find first pull requests that targets this repository
  PR_NUMBER="$(echo "$PULL_REQUESTS" \
      | jq --arg REPO_ID "$REPO_ID" '[.[] | select ($REPO_ID == (.base.repo.id | tostring)) | .number ][0]')"
  echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash -e {0}
  env:
    PULL_REQUESTS: []
    REPO_ID: 77326607
```

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/pull/12124#issuecomment-1776548292
🎉 動いてそうですね
