### ISSUE TITLE
プロフィールがにゃいずされる

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#12130]
## 💡 Summary
![](https://misskey.systems/storage/files/c2cbffa1-1f67-4421-8573-d71e8d2b9854.webp)
![](https://misskey.systems/storage/files/54d4f166-48f0-485e-b2a9-0a83144b3479.webp)

![スクリーンショット 2023-10-24 17 19 15](https://github.com/misskey-dev/misskey/assets/18308639/a344e9fc-b890-429f-a2d4-0fe0448e5e6b)

![スクリーンショット 2023-10-24 17 19 20](https://github.com/misskey-dev/misskey/assets/18308639/3030b410-085e-414f-bd90-3e5c51d820c0)

## 🥰 Expected Behavior
にゃいずされない

## 🤬 Actual Behavior
にゃいずされている

## 📝 Steps to Reproduce

1.
2.
3.

### 💻 Frontend
* Model and OS of the device(s):
  
* Browser:
  
* Server URL:
  
* Misskey:
  2023.11.3

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by kakkokari-gtyih** [comment]
これはわざとでは…？

**Comment by fruitriin** [comment]
いままでにゃいずされてなかったはず？意図的な変更？

**Comment by kakkokari-gtyih** [comment]
これのせいっぽい（当該ユーザーが猫の場合、MFMが使えるすべてのユーザー入力部分がにゃいずされてる）

https://github.com/misskey-dev/misskey/blob/1d9b5ae1ba6d98cb496367d955fd691371d31f71/packages/frontend/src/components/global/MkMisskeyFlavoredMarkdown.ts#L63-L65

**Comment by kakkokari-gtyih** [comment]
@syuilo これ仕様にしておきますか？（個人的には、ユーザー名だけnyaize回避すればbioはnyaizeしてもいいと思います）

**Comment by syuilo** [comment]
とりあえず今まで通りnyaizeは投稿内容だけで

**Comment by kakkokari-gtyih** [comment]
やるか

**Comment by fruitriin** [comment]
ありがとう〜！ ❤️
