### ISSUE TITLE
一部のURL入力フォームがtype="text"になっている

### ISSUE THREAD

**Issue by 7ka-Hiira** [syuilo/Misskey#12137]
## 💡 Summary

一部のURL入力フォームがtype="text"になっている

## 🥰 Expected Behavior

すべてのURL入力フォームがtype="url"になっている

## 🤬 Actual Behavior

一部のURL入力フォームがtype="text"になっている
例:
New Announcement，Advertisements の Image URL,
Terms of Service URL, Privacy Policy URL
Summaly Proxy URL

## 📝 Steps to Reproduce

1. Misskeyを読み込み，上記のようなURL入力フォームを確認する。

### 💻 Frontend
* Model and OS of the device(s):
  iPhone 11, iOS 17.1(21B74)
* Browser:
  Firefox Focus 119.0 / Safari 17.1
* Server URL:
  local, misskey.io
* Misskey:
  2023.11.0-beta.3, 13.14.2-io.12

### 🛰 Backend (for server admin)

development environment
* Misskey: 2023.11.0-beta.3
* Node: 20.8.1
* PostgreSQL: 15.4
* Redis: 7.2.2
* OS and Architecture: Arch Linux x86_64

**Comment by syuilo** [comment]
🙏🏻
