### ISSUE TITLE
Regression: リモートユーザーの情報を強制更新する機能が消えている

### ISSUE THREAD

**Issue by frfs** [syuilo/Misskey#12152]
## 💡 Summary
リモートユーザーの情報を強制更新する機能が消えています。
どうやら以下のコミットでコメントアウトされている模様。
https://github.com/misskey-dev/misskey/commit/bbef2a953ebf2f7f063641e6764ec8571cd78b75

## 🥰 Expected Behavior
リモートユーザーの情報を強制更新する機能が使える

## 🤬 Actual Behavior
リモートユーザーの情報を強制更新する機能が消えている

### 🛰 Backend (for server admin)

* v2023.10.2

**Comment by mattyatea** [comment]
api自体は残ってるぽい?

**Comment by GrapeApple0** [comment]
エンドポイントは`federation/update-remote-user`として残っているので、該当ユーザーのuserIdを取得して更新することは可能だと思います

**Comment by mattyatea** [comment]
#12172 
👀

**Comment by kakkokari-gtyih** [comment]
Done in #12172
