### ISSUE TITLE
80MB以上のデータをアップロードできない

### ISSUE THREAD

**Issue by penginn-net** [syuilo/Misskey#12155]
## 💡 Summary
80MB以上のデータをアップロードできない

## 🥰 Expected Behavior
オブジェクトストレージの制限かmaxFileSizeで指定したサイズ以下のファイルをアップロードできる

## 🤬 Actual Behavior
79MBまでのファイルはアップロードに成功する。
80MB以上だと100%まで行ってノート添付に表示されず、ドライブにもない。

## 📝 Steps to Reproduce

1.ファイルをアップロードする
2.100%になる
3.ドライブにない

## 📌 Environment
オブジェクトストレージ:Cloudlare R2

### 💻 Frontend
* Model and OS of the device(s):
  hp envy x360 15-ee0000(windows11 22621.2428)
* Browser:
  Chrome 118.0.5993.90
* Server URL:
 (https://gc-key.xn--vusz0j.life/)
* Misskey:
  2023.10.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: docker compose,(Misskey install shell script)
* Misskey: 2023.10.2
* Node: 20.9.0
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:  Ubuntu 22.04.2 LTS

#9910 で言及された無料プランの100MB等のプラン別制限は今はないかもしれません。(無料プランでR2のダッシュボードでは300MB、R2マウントソフトでGB単位のファイルをアップロードできます)

maxFileSizeを指定しないと80MBでファイルサイズエラーが出る(MissKey)

URLアップロードでは80MB以上でもアップロードできました。(R2→R2)

**Comment by mattyatea** [comment]
Misskey-hubにある構築の手引きに書いてあるnginxの設定ファイルのclient_max_body_sizeが80MBなのでそれに引っかかっているのではないかと思います👀

**Comment by penginn-net** [comment]
client_max_body_size　80m;になってました...
変更したら100MB以下のファイルをアップロードできるようになりました。
ありがとうございます！。

CF側100MB制限について
URLアップロードで100MB以上のアップロードができたのはCloudflareを通してのPOSTではなかったからのようです。
プロキシを有効にしたままの状態で100MB以上アップロードするとMisskeyでファイルサイズエラーになりました。

別Issueの制限をR2の制限だと思っていたのですが、サイトへの制限でした。
