### ISSUE TITLE
検索の詳細設定のアコーディオンを減らす

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12162]
## Summary

いくつも入れ子のフォルダを開けるのは面倒なので、表のような形にしてまとめるのがよさそう

Related to https://support.misskey.io/hc/ja/community/posts/8186931476623-%E6%A4%9C%E7%B4%A2%E3%81%AE%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3-%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E6%8C%87%E5%AE%9A%E3%81%BE%E3%81%A7%E3%81%AE%E9%9A%8E%E5%B1%A4%E3%81%8C%E6%B7%B1%E3%81%84

![image](https://github.com/misskey-dev/misskey/assets/67428053/f90d238e-8ffe-4e24-a2f5-6da828b91236)

**Comment by syuilo** [comment]
デフォルトで開いた状態にしておくのではダメかしら

**Comment by kakkokari-gtyih** [comment]
それでもいいか

**Comment by tai-cha** [comment]
今の長さなら開けておくので十分そう
項目が増えたら再考の余地がありそう
