### ISSUE TITLE
[2023.10.x～]ノート取得時にノート数がlimitよりも少ない事がある

### ISSUE THREAD

**Issue by uboar** [syuilo/Misskey#12160]
## 💡 Summary
TLをRedisに保持するバージョンにて、`notes/timeline`などノート取得系のAPIをコールした際、充分なノート数があるにも関わらずレスポンスで`limit`で指定した件数より少ない数のノートが返ってくる事があります。（推測ですが、Redisへの割当メモリが少ない場合に顕著です。）

## 🥰 Expected Behavior
ノート取得系のAPIをコールした際、（充分なノート数がある場合）`limit`数のノートがレスポンスとして返される。

## 🤬 Actual Behavior
ノート取得系のAPIをコールした際、`limit`数に満たないノートがレスポンスとして返される場合がある。
- サードパーティクライアント等で、「limitより少ないノートが返ってきた場合、TLの終わりと判断しそれ以上更新しない」というロジックが組まれている場合、TLの途中にも関わらずそれ以上の更新が行えなくなってしまいます。
- こちらで再現出来ていないのですが、極稀にlengthが0で返ってくる場合があるようです。(Redisへの割当メモリが少ない場合？)

## 📝 Steps to Reproduce

1. APIコンソール等から`notes/timeline`をコール、この際`limit: 10`を指定する。
2. 最後のノートIDを`untilId`に指定し、再度APIをコール。
3. 2を繰り返し、返却された配列の長さを調べると長さが10に満たない場合がある。

### 💻 Frontend
* Model and OS of the device(s): Windows11 / Android 14(Pixel 6a)
  
* Browser: Vivaldi 6.4.3160.34 / MissRirica
  
* Server URL: nicomedkey.cc
  
* Misskey: 2023.10.2-nmk1.1.3(フロントエンド改修のみのFork)

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 2023.10.2-nmk1.1.3(フロントエンド改修のみのFork)
* Node: 20.5.1-bullseye(Docker)
* PostgreSQL: 15(Vultr Managed Database)
* Redis: 7-alpine(Docker)
* OS and Architecture: Ubuntu 22.04.3 LTS

### 💻 Frontend
* Model and OS of the device(s): Windows11 / Android 14(Pixel 6a)
  
* Browser: Vivaldi 6.4.3160.34 / MissRirica
  
* Server URL: misskey.systems
  
* Misskey: 2023.11.0-beta.3

**Comment by kakkokari-gtyih** [comment]
（フォールバックが効いていない…？）

**Comment by tai-cha** [comment]
> 「limitより少ないノートが返ってきた場合、TLの終わりと判断しそれ以上更新しない」というロジックが組まれている場合

これ、おそらくDBのフォールバックがきちんと効いている場合でも今の実装だと起こる可能性がある…？（たしかRedisにキャッシュされているものが0になったときにDBにフォールバックしますよね？）
