### ISSUE TITLE
11以上されているリアクションにおいてツールチップで示されるリアクション数が本来よりも1多い

### ISSUE THREAD

**Issue by trrk** [syuilo/Misskey#12174]
## 💡 Summary

11以上されているリアクションでは、そのツールチップの表示から導けるリアクション数が正しいリアクション数より1多い

## 🥰 Expected Behavior

（11以上されているリアクションで）
ツールチップの表示から導けるリアクション数が正しいリアクション数である

## 🤬 Actual Behavior

（11以上されているリアクションで）
ツールチップの表示から導けるリアクション数が正しいリアクション数よりも1多い

![image](https://github.com/misskey-dev/misskey/assets/13601547/13aa158b-8824-4e35-a71b-4b8dbcc48c05)
例えば、この画像ではリアクション数が次となっている
正しい値: 170 
ツールチップの表示から導ける値: 11 (ユーザー表示の数) + 160 = 171

## 📝 Steps to Reproduce

1. リアクション数が11以上のノートを探す
2. 表示を確認する

### 💻 Frontend
* Model and OS of the device(s): ?, Microsoft Windows 11 Home 10.0.22621
* Browser: Vivaldi 6.2.3105.58 (Stable channel) (64-bit) 
* Server URL: misskey.io
* Misskey: v13.14.2-io.12b

## 個人的意見など

どちらかで修正できると思う
- ツールチップでのユーザー表示を 10 個までとする
- ツールチップでの +1 といった表示で今よりも 1 少ない値を示す

**Comment by kakkokari-gtyih** [comment]
それぞれStreamとAPIで取得している以上、多少のズレは発生する気がします

**Comment by kakkokari-gtyih** [comment]
そういうことではないかも

**Comment by trrk** [comment]
そうですね

単に数字が合っていないようにみえます
11件分のユーザーを表示しながら、見えていない分の数として リアクション数 - 10 を表示していると思います

**Comment by Srgr0** [comment]
ユーザー表示数の上限値と、カウント制御での減数が一致していないのが原因ですね。
それぞれハードコードされているので、ハードコードをやめるかどうかも含めて検討が必要かと思います。

該当部分
[ユーザー表示数の上限値 = 11 / MkReactionsViewer.reaction.vue#L99](https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/components/MkReactionsViewer.reaction.vue#L99)
[カウント制御 リアクション数が10より多いときに、count - 10の値を表示 / MkReactionsViewer.details.vue#L18](https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/components/MkReactionsViewer.details.vue#L18)
