### ISSUE TITLE
ねこみみモードをオンにしてると投稿が見れなくなる (2023.11.0-beta.4)

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#12182]
## 💡 Summary
![image](https://github.com/misskey-dev/misskey/assets/56515516/17d8f7b5-96d0-4a4c-a0d7-2bd96b31de79)
(画像はhttps://prismisskey.space/@meimei氏)
上記の用になる

## 🥰 Expected Behavior
ちゃんと見えるようになる

## 🤬 Actual Behavior
見えない

## 📝 Steps to Reproduce

不明(原因は特定してます)

### 💻 Frontend
* Model and OS of the device(s):iOS 
  
* Browser:Safari
  
* Server URL:https://prismisskey.space
  
* Misskey: 2023.11.0-beta.4

**Comment by anatawa12** [comment]
古いSafariだとRegexの<=使えなくて壊れるというのは聞いたことあります

**Comment by syuilo** [comment]
iOSのバージョンが古そう

**Comment by syuilo** [comment]
Misskeyは以前からiOS 16を必須にしてる
