### ISSUE TITLE
HTLに未フォローチャンネルノートが含まれてしまう

### ISSUE THREAD

**Issue by setaria430** [syuilo/Misskey#12181]
## 💡 Summary
ホームタイムラインに、フォローアカウントの未フォローチャンネルが含まれる
streamingでは発生せず、遡った時の`api/notes/timeline`のレスポンスに混入する
未フォローアカウントの未フォローチャンネルノートは含まれない
ホームタイムライン上部の設定（リノートを表示・ファイル付きのみ）を何れの組み合わせにしても影響しない
フォローが少ない別のアカウントでは再現しなかったため、条件が絞りきれていない

## 🥰 Expected Behavior
未フォローチャンネルはHTLに含まれない

## 🤬 Actual Behavior
含まれる

## 📝 Steps to Reproduce

1. HTLを遡る（もっと見る）
2. 以上
3.

## 📌 Environment
![Image 220](https://github.com/misskey-dev/misskey/assets/125631064/8e974aaf-fb77-48d1-a2e1-7e2bf34704f2)

### 💻 Frontend
* Model and OS of the device(s):
  Windows 10pro
* Browser:
  Chrome 118.0.5993.89
* Server URL:
  misskey.gamelore.fun
* Misskey:
  2023.11.0-beta.4

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.x.x
* Node: 20.x.x
* PostgreSQL: 15.x.x
* Redis: 7.x.x
* OS and Architecture:

**Comment by samunohito** [comment]
@syuilo 
#12179 の対処が甘かったようです。すみません。
自分が引き続き対処しても問題ありませんか？

**Comment by syuilo** [comment]
> @syuilo #12179 の対処が甘かったようです。すみません。 自分が引き続き対処しても問題ありませんか？

お願いします 🙏🏻

**Comment by tai-cha** [comment]
修正済みなので閉じます
https://github.com/misskey-dev/misskey/pull/12186
