### ISSUE TITLE
Profile decoration, wrong margin inside "profile button", navigation menu

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#12198]
### 💡 Summary

Since 2023.11.x you can add image profile decorations like this

![immagine](https://github.com/misskey-dev/misskey/assets/92727/65e6e516-b883-431d-a14a-027a44648748)

### 🥰 Expected Behavior

profile button without margins

### 🤬 Actual Behavior

Profile button, inside navigation menu, have top and bottom margin.

### 📝 Steps to Reproduce

1. design a square decoration 512px
2. fill at most 384px with graphics
3. save it on control panel
4. apply to a local profile
5. see navigation menu: decoration have margins

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: https://beta.misskey.social
* Misskey: 2023.11.0-b6
```

**Comment by tassoman** [comment]
![immagine](https://github.com/misskey-dev/misskey/assets/92727/0cefd34a-1d8e-441b-9725-c1a905002344)

**Comment by tassoman** [comment]
![immagine](https://github.com/misskey-dev/misskey/assets/92727/e12b0f15-4415-4b62-b187-79db8a868fbe)

えっと

**Comment by tassoman** [comment]
あの。。。@zyoshokaさん

![immagine](https://github.com/misskey-dev/misskey/assets/92727/7d5cbf54-3d3c-4f4c-b7d4-5770e3644368)

**Comment by tassoman** [comment]
CSSの`min-height: 384px`です
![immagine](https://github.com/misskey-dev/misskey/assets/92727/2b0c284c-a0f3-4bcb-aac2-f9fb874ba9a2)

**Comment by zyoshoka** [comment]
ご報告ありがとうございます、ノートプレビューについても修正しておきました！
