### ISSUE TITLE
ホームだけミュート機能(ミュートと別・フォローしている)

### ISSUE THREAD

**Issue by kohakuto589** [syuilo/Misskey#12195]
## Summary

投稿を見たい人をフォローするから必要ない、というのは正しいかもしれませんが…
**○○したら特典つくよ、というものが最近多く**なってきていますし、
といってフォロー解除はちょっとな…とも思っております。
ホーム画面が自分の投稿で埋め尽くされたい方もおられると思います。

**Comment by syuilo** [comment]
ホームタイムラインは使わず、リストタイムラインで運用するのはどうでしょう

**Comment by kohakuto589** [comment]
なるほど、ありがとうございます

**Comment by samunohito** [comment]
流れを見る限り解決されていそうなのでcloseします 🙏
