### ISSUE TITLE
初期設定ウィザードでプロフィールを編集しても実績解除しない

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12207]
### 💡 Summary

書いてあるとおり

### 🥰 Expected Behavior

プロフィールを編集したら実績解除する（ウィザードの場合は最後までやりきったら実績解除でもいいかも）

### 🤬 Actual Behavior

実績が解除されない

### 📝 Steps to Reproduce

1. 初期設定する
2. プロフィールをいじる
3. 実績解除されない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 22H2
* Browser: 
* Server URL: (localhost)
* Misskey: v2023.11.0-beta.6
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
ウィザードで設定できるプロフィールは限りがあるからちゃんとプロフィール設定画面開いて編集した時だけ実績が解除される今の仕様で問題ない気もする

**Comment by kakkokari-gtyih** [comment]
まあチュートリアルのこともあるしそれでもいいかもしれませんね

**Comment by kakkokari-gtyih** [comment]
> ちゃんとプロフィール設定画面開いて編集した時だけ実績が解除される今の仕様で問題ない

> まあチュートリアルのこともあるし

そういうことにしておきますか
