### ISSUE TITLE
`/api/admin/show-user` で `ffVisibility` に関わらず FF 関係のユーザー情報を取得できるようにする

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#12214]
### Summary

フォロワー数をファームするため？にアカウントを何個も作ってまわる行為が報告されていて、特にリモート越しの場合は不要な Activity が配送される実害があるが、この際 `ffVisibility` を `public` 以外にすると、データベースを直接覗かない限り実態を調査できない。

**Comment by syuilo** [comment]
FF 関係のユーザー情報 って followingCount と followersCount ？

**Comment by acid-chicken** [comment]
最低限数字はあった方がいいけど実情に即すならユーザー情報もあった方が良い

**Comment by zyoshoka** [comment]
`/api/admin/show-user` で取得できるようになったわけではないですが、#14375 で
> データベースを直接覗かない限り実態を調査できない

という問題は解決されましたので一先ず close します。
