### ISSUE TITLE
CWの見出し空で投稿できなくしてほしい

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#12217]
### Summary

CW投稿のCWが隠れている間、リアクションが表示されなくなりました。[2023.11.0 beta8]

これにより、隠れている内容を一切予測できません。
これは自分にとって読みたい内容か読みたくない内容か判別する要素を一つ失ったことになります。
今のところ見出しとなるテキストは空白が許可されているので、この場合判断材料が一切ないことを意味します。

CWの見出し（隠していない部分）が空の場合、投稿できなくなってほしいです

**Comment by CAT5NEKO** [comment]
投稿を隠すという事で
①全員に見られて欲しくない投稿をするときに使う
②ショッキングな内容を隠す
という効果が考えられると思うんですけど、CWの見出しが空で入力出来てしまうと②の効果を発揮する事が難しいと思います。
自衛面、機能面を問わず総合的に考えても何故隠すのかという根拠を明示するのは大切ではないかと

**Comment by zyoshoka** [comment]
リアクション非表示自体は revert されたものの、そもそもリアクションが一切付いていなければ空注釈の CW 投稿の内容は判断のしようがありませんし、空注釈投稿は以前から #10615 (#11419) のような問題を抱えていますから、空注釈を禁止する価値は依然としてあると思います。

**Comment by kakkokari-gtyih** [comment]
> リアクション非表示自体は revert された

これはおそらく動作に問題があったためだと思われます…（Transitionが効いて意図しない挙動が起こった）

**Comment by syuilo** [comment]
まあ空を禁止しても「あ」みたいに注釈を設定して事実上「隠れている内容を一切予測できない」状態で投稿されるようになりそうだわね
