### ISSUE TITLE
In deck layout, replies option is not saved after refresh

### ISSUE THREAD

**Issue by 900809** [syuilo/Misskey#12228]
### 💡 Summary

10.2 fixed "show replies" option not being remembered after a page refresh for default layout, but the bug remains in the deck layout.

![image](https://github.com/misskey-dev/misskey/assets/104532529/8f375bfc-f910-4437-9c26-2c429be647c8)

After refresh:

![image](https://github.com/misskey-dev/misskey/assets/104532529/fe9d7c0f-4182-4e93-b678-cbb90ac73c4b)

### 🥰 Expected Behavior

The "show replies" should stay on after a page refresh.

### 🤬 Actual Behavior

The "show replies" option is off after a page refresh.

### 📝 Steps to Reproduce

1. Enable replies in timeline in deck layout
2. Refresh the page

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: any
* Server URL:
* Misskey: 2023.10.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.10.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
🙏🏻
