### ISSUE TITLE
スマホ/タブレットでドライブのファイルのURLをコピーする手段がなくなっている

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12220]
### 💡 Summary

クリックするとコンテキストメニューではなく詳細ページが開いてしまう

### 🥰 Expected Behavior

メニューが開きその中に詳細ページへの動線がある

### 🤬 Actual Behavior

コンテキストメニューを開く手段がない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kakkokari-gtyih** [comment]
詳細ページにファイルURLのコピーボタンを設けたい（Off-topic）
