### ISSUE TITLE
通知にて複数の人としてカウントされている

### ISSUE THREAD

**Issue by kohakuto589** [syuilo/Misskey#12264]
### 💡 Summary

通知にて、誤爆か何らかの理由により、1人で複数人としてカウントされているということが起こっております。

### 🥰 Expected Behavior

![Screenshot 2023-11-06 16 33 21](https://github.com/misskey-dev/misskey/assets/148501199/1cc6724c-8f3c-433e-9788-02c15eb82726)
最新の絵文字の表示へと変更されるようにしたいと考えております。

### 🤬 Actual Behavior

![Screenshot 2023-11-06 16 29 22](https://github.com/misskey-dev/misskey/assets/148501199/831545b3-06e6-4594-ad1c-a2b8046f1124)
通知誤爆等をした際に1人なのに、といったリアクションをつけた回数でカウントされる仕組みなようで、ややこしいな、と感じております。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kakkokari-gtyih** [comment]
こういうシチュエーションになったらリアクションをまとめないだけに留める、もしくは文言だけ変えるのがいいと思う（通知欄芸が使えなくなってしまうので）
