### ISSUE TITLE
プラグインでノートにMFMを追加しても反映されない

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12281]
### 💡 Summary

ノートに含まれる指定ワードを太字赤字にするプラグインを作って使っていました。
https://github.com/kanade/misskey-plugin/blob/main/misskey-plugin-highlight-text.txt
たとえば「hogehoge」というワードを含むnote.textを「`**$[fg.color=f00 hogehoge]**`」と置換するものです。
2023.11.0にアップデートしたあとだと思いますが、このプラグインでテキストを装飾することができなくなりました。

ノートの内容をコピーしてみると「`**$[fg.color=f00 hogehoge]**`」になっているのですが、表示もDOMも通常のテキストのままになっています。
なお全般設定の高度なMFMと動きのあるMFMは両方とも有効にしています。

自分の発言で対象ワードをノートしたあと、削除して編集 → なにも編集せず投稿するとMFMによる装飾は反映されます。

Misskeyそのもののバグなのか分からないのですがこちらで相談させてください。

### 🥰 Expected Behavior

従来通りプラグインでノートにMFMによる文字装飾を追加したい。
指定ワード

### 🤬 Actual Behavior

MFMによる文字装飾が反映されず、通常のテキストとして表示される。
ただしノートの内容をコピーするとプラグインで追加したMFMは正常に含まれている。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by samunohito** [comment]
原因わかったのでプルリク作りますね（プラグインではなく、本体フロントエンド側の問題でした）

**Comment by kanade** [comment]
調査とご対応ありがとうございます。
フロントエンドの問題だったんですね。
よろしくお願いいたします！

**Comment by samunohito** [comment]
@kanade 
developに取り込まれました。
差し支えないようでしたら、ご確認頂けますと幸いです…！

**Comment by kanade** [comment]
@samunohito
対応ありがとうございます！
先ほどdevelopブランチ動かしまして、無事に修正の確認が取れました！

**Comment by samunohito** [comment]
@kanade 
良さげならcloseいただけると…:pray:

**Comment by kanade** [comment]
解決しましたのでCloseさせていただきます！
