### ISSUE TITLE
大量にフォローしているユーザーのTLへの投稿の追加はサンプリングできるようにする

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12289]
### Summary

大量にフォローしているユーザーのTLに律儀にすべてのフォロイーの投稿を追加するのは無駄

**Comment by kanade** [comment]
TwitterもTLを間引いていますがかなりの反感を買いTwitterそのものから離れる人も多かったので、慎重になるべきかと思います。
具体的にどのくらいフォローしている人が対象なのか分からないですが、仮に実装するなら管理者が任意でフォロー数の閾値を変えたりサンプリングを適用するしないを選べるといいかな？

**Comment by syuilo** [comment]
むしろ間引かないと早すぎてタイムラインを見れなくなり、ユーザーは困ることになる

**Comment by syuilo** [comment]
related: https://github.com/misskey-dev/misskey/issues/10269

**Comment by syuilo** [comment]
👎されてもその理由がコメントされないので困る

**Comment by syuilo** [comment]
> むしろ間引かないと早すぎてタイムラインを見れなくなり、ユーザーは困ることになる

例えば一秒間に10個くらいタイムラインに投稿が流れてきて誰が嬉しいのかという話

**Comment by mattyatea** [comment]
私的には見にくくなったらミュートなどを使うのでサーバー側でする必要はないと考えます
そもそも見たくないとフォローしないと思うしそこに関してはユーザーに任せていいと思います

**Comment by syuilo** [comment]
ミュートは影響が大きすぎる

**Comment by syuilo** [comment]
> 見たくないとフォローしないと思うし

そんなことはなくなってきている

**Comment by syuilo** [comment]
フォローはタイムラインにそのユーザーの投稿を表示するという以上の意味を持ってきているから、そのユーザーの投稿を見たくなくてもフォローはする場合は多い

**Comment by kanasaki15** [comment]
TLの流速が早くなって追いつかなくなった時のためにリストを利用すればいいので
TLをサンプリングして間引くのは反対です

・・・って👎とリアクションしてる人はそう思ってるんだと思います

**Comment by syuilo** [comment]
あと投稿を見たい人が単に多い場合もある

**Comment by syuilo** [comment]
> TLをサンプリングして間引くのは反対です

サンプリングをオフにすればいいだけではない？

**Comment by kanasaki15** [comment]
多分最初はオフで必要に応じてオンにできるって感じなら反対は少ないと思います

(自分自身はどっちでもいいので)

**Comment by syuilo** [comment]
ああ、「できるようにする」と書いたつもりが「するようにする」になってたわね

**Comment by tribela** [comment]
1. It should be based on Posts/time, Not following count
2. Users can select what they want to follow
> フォローはタイムラインにそのユーザーの投稿を表示するという以上の意味を持ってきているから、そのユーザーの投稿を見たくなくてもフォローはする場合は多い

Mastodon have "exclusive list" feature. If add users onto that exclusive list, the posts will not be added to home TL, But the list do. Similar approach could be good enough

**Comment by kanade** [comment]
間引くのをユーザー側で任意に設定できるなら機能の実装自体は問題ないと思いますが、強制適用だと悪しきTwitterの例を追うことになってしまわないか心配でした。

**Comment by Yatoigawa** [comment]
するようにする、だと思ってたのでビックリしましたが、オプションなら良いと思います

**Comment by syuilo** [comment]
Twitterの悪さというのがあまり実感がなかった

**Comment by mattyatea** [comment]
ユーザー、サーバー側で変更できるなら良いと思います

**Comment by kanade** [comment]
> Twitterの悪さというのがあまり実感がなかった

良い悪いというよりデータの扱いについてユーザーに選択肢を与えなかったのがよくなかったのかなって。
ユーザーが離脱してしまうという意味で悪い例として挙げましたが他意はありません。

**Comment by syuilo** [comment]
> > むしろ間引かないと早すぎてタイムラインを見れなくなり、ユーザーは困ることになる
> 
> 例えば一秒間に10個くらいタイムラインに投稿が流れてきて誰が嬉しいのかという話

大量(例えば一秒間に10個以上)にタイムラインに投稿が流れてきて欲しいユースケースがあれば知りたい

**Comment by samunohito** [comment]
（オプションなのであれば、issueのタイトルを変えといたほうが良いと思いました。いまのままだと人がいっぱい集まってきそう）

**Comment by anatawa12** [comment]
強制適用だとタイトルから判断し:-1:しましたがサンプリングできるようにするであれば取り下げますがどちらですか？未だにタイトルは"する"であり強制適用にみえます

**Comment by syuilo** [comment]
仮に強制適用だとしても👎になるのがよくわかってないわね
タイムラインが速すぎて見れない問題を解決して困ることはない気がするけど

**Comment by Yatoigawa** [comment]
>タイムラインが速すぎて見れない問題を解決して困ることはない気がするけど

解決する手段として用意されるのと、それを強制されるのとではユーザが受け取る感触に大きく差があると思います
特にTLの作り方や見方はユーザ次第でしかないので、最低限オプションであって選択出来ることが必要だと思います

**Comment by syuilo** [comment]
ふむ
ただ一秒間に何十個も投稿を流すと耐えられるサーバー&ブラウザはなかなかないと思うからオプションとはいえ実際はサンプリング有効にするしかなくなりそう

**Comment by CyberRex0** [comment]
そこら辺の設定をユーザーに委ねるのではダメ？

**Comment by shiosyakeyakini-info** [comment]
今動いているbotが正しく動作しなくなる可能性がある（334Rankerが計測できなくなったり、TLのワードに重みをつけながら動いているしゅうまいが正しくTLから読み込めなくなったり）

**Comment by tamaina** [comment]
ストリーミングだけをサンプリングするの？過去のTLもサンプリングするの？

**Comment by junx-x** [comment]
(1)間引くのを誰がどのように決めるのか？
(2)間引くとして「間引き方」の正当性をユーザーに説明できるのか(特定のユーザーがたくさん(優先的に)表示される等が発生しないのか)
この2点が気になります。

現状では「大量のフォロー」に関して目安のフォロー数が明示されていないため、具体的な数値を示していただいたほうが議論しやすいと思います。
100フォローでも間引かれるのか、1,000あるいは10,000といった単位の話なのか。

ユーザーとしては、Twitterが意図的に、ユーザーに説明や断りなく、一部のユーザーを優先的に表示していた件に起因して運営に不信感を持ち、Twitterを離れる要因の1つとなったので、Misskeyでどのような仕様になるのか重大な関心があります。

**Comment by syuilo** [comment]
> ストリーミングだけをサンプリングするの？過去のTLもサンプリングするの？

両方やらないとつじつまが合わなそう

**Comment by syuilo** [comment]
> 現状では「大量のフォロー」に関して目安のフォロー数が明示されていないため、具体的な数値を示していただいたほうが議論しやすいと思います。

タイムラインに一秒間に最大何個まで投稿が流れるかをサーバー管理者またはユーザーが設定しておいて、それを超過したら上限に合うようにサンプリングする感じになると思う

related: https://github.com/misskey-dev/misskey/issues/10269

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/issues/10269 とduplicateな気がするので続きはそちらで
