### ISSUE TITLE
X（旧 Twitter）のリンクを展開したカード上のリンク先がX（旧 Twitter）のものだった場合ブロックされる

### ISSUE THREAD

**Issue by meronmks** [syuilo/Misskey#12291]
### 💡 Summary

X側の仕様変更な気もするのでここに書くべきなのか・・・なところもありますが、
1枚目のカードとして展開されたリンク先が`twitter.com`であった場合、ブロックされてしまいリンク先が読めなくなっているようです。
なお右下の「i」ボタンだけは機能します。

![image](https://github.com/misskey-dev/misskey/assets/12034371/ed7a9cbd-5434-4e9a-900f-41b0709f6c09)
![image](https://github.com/misskey-dev/misskey/assets/12034371/a386b705-8462-4a81-9c97-8d25f84482fe)

### 🥰 Expected Behavior

カード内のリンク先をクリックすると適切なページへ遷移する

### 🤬 Actual Behavior

ブロックされてしまい閲覧ができない

### 📝 Steps to Reproduce

1. 適当なXのポストのリンクをノートする
2. ノートの「X ツイートを展開する」を押す
3. 展開されたポストのリンクをクリック

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11
* Browser: Google Chrome 119.0.6045.106
* Server URL: misskey.niri.la misskey.io
* Misskey: (misskey.niri.la)v2023.9.3-kinel.4 (misskey.io)v13.14.2-io.15a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Srgr0** [comment]
X公式の埋め込み機能を使用しても正常に読み込まれないため、X側の修正を待つのがよいかと思います。
https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fmeronmks%2Fstatus%2F1719932347469205611&widget=Tweet
