### ISSUE TITLE
グラフが無限に縮小を繰り返してしまう

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12290]
### 💡 Summary

かなり前から発生していたのですが、AndroidのChromeにおいてダッシュボードのグラフやサーバートップのグラフが縮小 → 戻るを無限に繰り返してしまいます。
他にはユーザーページを開いた際のアクティビティのグラフでも発生していた気がします。

手元ではiPhoneだと発生せず、Pixel 8 ProなどのChromeのみ発生しています。
伝えづらいので動画を録りました。

https://github.com/misskey-dev/misskey/assets/732664/52ff6f94-7208-4f95-9f82-af09b2fc8419

https://github.com/misskey-dev/misskey/assets/732664/dc81349c-50fb-4737-a3a9-be4bdbf9b2c2

### 🥰 Expected Behavior

グラフが正常に表示される

### 🤬 Actual Behavior

グラフが縮小を繰り返して正しく見ることができない

### 📝 Steps to Reproduce

AndroidのChromeでダッシュボードやサーバートップを見る

### 💻 Frontend Environment

```markdown
直近で確認したバージョン

Pixel 8 Pro ( 以前所持のPixel 7でも発生していました )
Android 13, Android 14
Chrome 119.0.6045.66
Android WebViewの実装 118.0.5993.111
Misskey 2023.11.0
```

**Comment by hideki0403** [comment]
related to #10604

Misskey側ではなくChart.js側のバグのようです:eyes:
https://github.com/chartjs/Chart.js/issues/11224

**Comment by kanade** [comment]
なるほど、ライブラリ側のバグだったんですね。ありがとうございます！
管理画面を見るとき地味にストレスだったので改善されるといいのですが…Chart.js側の修正を待ってみようと思います。

**Comment by kakkokari-gtyih** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/10604
