### ISSUE TITLE
プロフィールページのノートタブで誤ってリノートが含まれることがある

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#12306]
### 💡 Summary

2023.11.0(stable)で確認。プロフィールページで「全て」タブではなく「ノート」タブではリノートが表示されないはずなのだが、何らかの条件によりリノートが誤って含まれている
![rsyeryey](https://github.com/misskey-dev/misskey/assets/28042693/ff43e4e4-8dc5-4074-a993-78cc3e1ee159) 

### 🥰 Expected Behavior

「ノート」タブにリノートは含まれない

### 🤬 Actual Behavior

「ノート」タブにリノートが含まれる

### 📝 Steps to Reproduce

※発生条件不明。考えられるのはアップデート前にしか投稿が存在しないこと。
ex : https://misskey.systems/@misskey_dev

なお、アップデート後に何らかの投稿操作を行うと解消される(他アカウントにてそのような動作を確認)
Redisが関係している模様※下記**参考情報**を参考

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): All
* Browser: All
* Server URL: misskey.systems
* Misskey: 2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by tkmrgit** [comment]
### 参考情報 
>みてきた。バグです。
>- 「リノートを含むか」というフラグが2種類あり、Redisから取る時とDBから取るときで違うフラグを見ていた
>- フロントから渡しているフラグは1種類のみ（Redisから取る時にのみ使用されるフラグだけ）
>
>1度投稿すると直るのは、Redisにキャッシュされて意図したフラグを使う方の処理に流れるからだと思う。過去のにリノートが紛れ込むのは、Redisにノートが無くてDBまでフォールバックし、正しくないフラグを使って「リノートを含むか」を判定したから
https://misskey.systems/notes/9lx3q8ofhm

**Comment by samunohito** [comment]
↑のノートは自分の書き込みなので、このまま自分が対応します。

**Comment by samunohito** [comment]
@tkmrgit 
develop最新にて対応済みです:pray:
