### ISSUE TITLE
アンテナが更新されない

### ISSUE THREAD

**Issue by penginn-net** [syuilo/Misskey#12303]
### 💡 Summary

作成したアンテナが新しい投稿を拾わなくなります。
同時期に作成した別のアンテナは更新されてます

同じ設定でアンテナを作成すると新しい方は更新されます。

~~設定~~
~~すべてのノート~~
~~返信含む~~
~~受信キーワードのみ指定~~
~~その他プション全部無効~~

### 🥰 Expected Behavior

アンテナが更新され続ける

### 🤬 Actual Behavior

アンテナの更新が止まる

### 📝 Steps to Reproduce

1.アンテナを作成する
2.いつの間にか更新されなくなる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:chrome
* Server URL:gc-key.xn--vusz0j.life　/　misskey.io
* Misskey:2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:2023.11.0
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by penginn-net** [comment]
他サーバも見たところ設定に関係なく、作成から2,3ヶ月経過すると更新されなくなるみたいです

**Comment by syuilo** [comment]
自分は再現したことないわね

**Comment by samunohito** [comment]
（ご参考までに）

一定期間更新がなかったアンテナは非アクティブ化されてノートが配信されなくなるような実装になっていました。
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/queue/processors/CleanProcessorService.ts#L49-L55

配信先のアンテナを取得する箇所
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/AntennaService.ts

実装を見る限り、以下の条件で再アクティブ化が出来るようです。
1. アンテナのエンドポイントからノート一覧を取得しようとする（アンテナのタイムラインを表示してリロードなど）
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/antennas/notes.ts#L88-L91
2. アンテナの設定を更新する
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/antennas/notes.ts#L88-L91

**Comment by samunohito** [comment]
なので…アンテナのTLを表示したり、アンテナの設定から保存ボタンを押したら動き出したりしませんか？？

**Comment by penginn-net** [comment]
アンテナのTLは定期的に見てるんでけど変わらなかったです。
保存ボタンを押してからキーワードを含むノートをしても拾われなかったです。（新しい方には追加されました）

**Comment by penginn-net** [comment]
ioの方見に行ったら更新されてました(アンテナTLをすこし前に開きました)
自分のサーバだと変わらないですね...

**Comment by samunohito** [comment]
```ts
		if (!this.antennasFetched) {
			this.antennas = await this.antennasRepository.findBy({
				isActive: true,
			});
			this.antennasFetched = true;
		}
```

`antennasFetched`でAntennaServiceが初期化された直後の状態しか持たないようになってる…？
もしかしたらですが、再起動後に反映されるかもしれません…

**Comment by samunohito** [comment]
@syuilo 
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/antennas/notes.ts#L88-L91
↑ここでisActiveがfalseからtrueに変わった時、[アンテナ更新時](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/antennas/update.ts#L128)と同じようにantennaUpdatedを配信したほうが良いように思えるのですが、どうでしょう

**Comment by syuilo** [comment]
YOSASOU

**Comment by penginn-net** [comment]
開きっぱなしのタブ全部閉じたりして今日見たら動き始めてました！。
ありがとうございます

**Comment by samunohito** [comment]
（issueは閉じられましたが、antennaUpdatedの配信対応は必要だと思うので、後々対応します）
