### ISSUE TITLE
絵文字追加のときのファイルなどをユーザー側に依存させない

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#12300]
### Summary

絵文字追加のときにファイルがアップロードしたユーザーに依存してしまう。
絵文字追加のときに指定されたファイルをsystemで再アップロードするようにしてほしい。

### Purpose

追加したユーザーがアカウントを削除しても絵文字が消えてしまう。
このような問題を解決できると考えている。

**Comment by CyberRex0** [comment]
#10576

**Comment by samunohito** [comment]
> systemで再アップロードする

すでに各ユーザ向けの機能として実装されているドライブのシステム用みたいなのが欲しいですね。
コントロールパネルに導線があって、管理者ロール持ちのみがアップロードや削除などの管理が出来るみたいなのを想像してます。

**Comment by atsu1125** [comment]
https://github.com/misskey-dev/misskey/issues/9526

**Comment by Sayamame-beans** [comment]
duplicate of #9526
