### ISSUE TITLE
Roles Admin fieldset, missing translation

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#12325]
### 💡 Summary

Role Admin Page have two accordion/fieldsets can't be translated using Crowdin

- Manual roles
- Conditional roles

### 🥰 Expected Behavior

Crowdin translation

### 🤬 Actual Behavior

![immagine](https://github.com/misskey-dev/misskey/assets/92727/6baa7f0e-4b0c-4ebd-8b3e-d183f2ccf417)

### 📝 Steps to Reproduce

1. open admin panel
2. visit roles page

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: beta.misskey.social
* Misskey: 2023.11.0
```

**Comment by mappi-pr** [comment]
ロール新規作成などの画面見ると、
日本語でも「マニュアル」、「コンディショナル」という表記になっているので
該当箇所もローカライズ対応できていた方がよさそうだと思いました！

https://github.com/misskey-dev/misskey/blob/c6ed06d783a2d49ca029cdf5284150bbfd3c9976/locales/ja-JP.yml#L1552-L1556

**Comment by mappi-pr** [comment]
@tassoman 
There are other words on the control panel that are not localized.
I think it would be better to fix it in the same way, what do you think?

<img width="695" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/a248629b-1710-4314-8425-e4cdf6a81198">

**Comment by tassoman** [comment]
Hello @mappi-pr thank you for taking care of this issue.  
Good point! The whole **Dashboard** page inside Administrator Control Panel is totally missing i18n (internationalization).
I think it must be discussed in a separate issue. I can open a different issue in the next hours if needed.  

Generally speaking, I expect to have the whole interface translated into the local language. That's because, as you noted, there are languages very different from latin / English. For example: Japanese, Chinese, Korean and Arabic also (it's a RTL language).   
While, I bet, Arabic isn't widely used language, the other Asian languages are very important for the community.

Let me know if you need a different issue. Thank you!

**Comment by mappi-pr** [comment]
@tassoman The fixes have been merged and can now be edited with crowdin.

**Comment by tassoman** [comment]
I added Italian translation!
ありがとうございました
