### ISSUE TITLE
予めビルドしたコードを提供する

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12327]
### Summary

Issueあった気がしたけど見当たらなかった
Misskeyのバックエンド/フロントエンドのコードは環境変数などが埋め込まれるわけではなく、どの環境でビルドしたとしても全く同じコードが生成されるため予めビルドしたコードを提供しておけばサーバーごとにビルドする手間が省ける
特にビルドはメモリを多く使用するためVPSのメモリが1GBだとビルドできないことがあるがそれを解決できる

### Purpose

無駄の削減

**Comment by syuilo** [comment]
既にDockerではビルドしたものが提供されてると思うけど非Dockerでもそのようにしたい

**Comment by acid-chicken** [comment]
Docker イメージから出してこればいいのでは

**Comment by futchitwo** [comment]
> Issueあった気がしたけど見当たらなかった

- #9411 ?

**Comment by syuilo** [comment]
👍👍👍
