### ISSUE TITLE
Disable the losing connection to the server warning

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#12329]
### Summary

Misskey does not have an option to disable the warning about lost connection to the server, which can be an annoyance as that warning is often a false alarm.

### Purpose

A new option on the dropdown menu under the "When losing connection to the server" setting would be added called "Do nothing", that will not do any actions when connection is lost.

**Comment by kakkokari-gtyih** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/12210

**Comment by miraikumiko** [comment]
@kakkokari-gtyih Hi! You marked this as a duplicate, but such functionality has not been implemented yet.
I just made [this option](https://github.com/miraikumiko/misskey/tree/disable-reconnect-alert) and would like to ask if I can make a Pull Request?
