### ISSUE TITLE
アップデート時にShiki周りでエラーが出る

### ISSUE THREAD

**Issue by masada-tea** [syuilo/Misskey#12324]
Ubuntu22.04のサーバーでミスキーを最新版にアップデートしようとしたところ以下のようなエラーがでています。

packages/frontend build$ vite build
│ vite v4.4.11 building for production...
│ transforming...
│ ✓ 1368 modules transformed.
│ ✓ built in 44.22s
│ [vite]: Rollup failed to resolve import "shiki" from "/home/misskey/misskey/package…
│ This is most likely unintended because it can break your application at runtime.
│ If you do want to externalize this module explicitly add it to
│ `build.rollupOptions.external`
│ error during build:
│ Error: [vite]: Rollup failed to resolve import "shiki" from "/home/misskey/misskey/…
│ This is most likely unintended because it can break your application at runtime.
│ If you do want to externalize this module explicitly add it to
│ `build.rollupOptions.external`
│     at viteWarn (file:///home/misskey/misskey/node_modules/.pnpm/vite@4.4.11_@types…
│     at onRollupWarning (file:///home/misskey/misskey/node_modules/.pnpm/vite@4.4.11…
│     at onwarn (file:///home/misskey/misskey/node_modules/.pnpm/vite@4.4.11_@types+n…
│     at file:///home/misskey/misskey/node_modules/.pnpm/rollup@3.29.4/node_modules/r…
│     at Object.logger [as onLog] (file:///home/misskey/misskey/node_modules/.pnpm/ro…
│     at ModuleLoader.handleInvalidResolvedId (file:///home/misskey/misskey/node_modu…
│     at file:///home/misskey/misskey/node_modules/.pnpm/rollup@3.29.4/node_modules/r…
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
└─ Failed in 48.4s at /home/misskey/misskey/packages/frontend

これはどこかのファイルに何かしら追記すればいい感じでしょうか？

**Comment by mattyatea** [comment]
`pnpm i --frozen-lockfile ` 
をしてから 
`NODE_ENV=production pnpm build` 
をしてみてほしいです👀

**Comment by masada-tea** [comment]
ありがとうございます。
試してみたところ上記のエラーは消えたのですが、代わりに今度はメモリ不足エラーが出ています。
vpsのメモリは1GBでスワップ領域は8GB確保しているのですが、スワップメモリは使えない感じでしょうか？

**Comment by samunohito** [comment]
メモリ不足エラーは恐らく #13177 と同件です。13177の方が詳細に記載されているため、そちらを活かします。

**Comment by samunohito** [comment]
Duplicate of #13177
