### ISSUE TITLE
閲覧権限を持たないノートが閲覧できる場合がある

### ISSUE THREAD

**Issue by setaria430** [syuilo/Misskey#12323]
### 💡 Summary

本文「非公開」として通知されたダイレクトメッセージに返信すると、本来見えないはずのノート本文が見えてしまう
streamで流れてくる場合のみ。一度更新をかけると (非公開) に戻る
これ自体はクリティカルな要因ではありませんが、他の不具合と合わさるとよろしくない気配がします。

本文が非公開で通知される（された）例:
- 公開範囲: ダイレクトのノートで、mentionを手打ちする（アカウントを宛先に追加しない）
- 過去のIssue https://github.com/misskey-dev/misskey/issues/12262

### 🥰 Expected Behavior

閲覧権限の無いノートに返信しても、返信元の本文はわからない

### 🤬 Actual Behavior

返信元の本文がわかる

### 📝 Steps to Reproduce

1. 公開範囲: ダイレクトのノートで、mentionを手打ちして（アカウントを宛先に追加しない）送信する
2. その相手がDMに返信する
3. 返信元が表示される
![Animation](https://github.com/misskey-dev/misskey/assets/125631064/03da991b-1e14-4a8f-8352-b55ab2185735)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows10 pro
* Browser: Chrome 119.0.6045.123
* Server URL: misskey.gamelore.fun
* Misskey: 2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by zyoshoka** [comment]
閲覧権限を持たないノートに対して返信できるのを禁止したほうが良さそうな気がします（実際、リアクションについては[禁止されています](https://github.com/misskey-dev/misskey/blob/dd533eb948a3ba533e452312e0f3915f37e5e06e/packages/backend/src/core/ReactionService.ts#L114-L117)）。
