### ISSUE TITLE
入力フォームで絵文字を選択する時も、ノートの＋ボタンから表示されるリアクションピッカーを使うようにしたい

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12336]
### Summary

今現在、入力フォームから表示される絵文字選択画面は以下のようになっています。

◎PC表示時
<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/85fc6671-140e-4cff-967f-4c6ba567fb2b" />

◎モバイル表示時
<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/95684cd4-0a64-45f0-90ab-c58f254a6142" />
　
それを、以下のようにしたいです。
（ノートの＋ボタンから表示されるリアクションピッカーを使うようにしたい）

◎PC表示時
<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/e345a0e3-ea94-4bb6-bd27-cb2aed125fb7" />

◎モバイル表示時
<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/67b2df61-613c-4303-b6da-cfa1563de8da" />

### Purpose

以下のメリットがあると考えています。

- モバイル表示時の視認性・操作性が圧倒的に良くなる
- 絵文字の表示数などの設定が効くようになる（表示数を多くしているユーザはその恩恵にあずかれる）
- 投稿後に絵文字選択画面は残ってしまう現象の改善（都度閉じる必要がなくなる）

**Comment by syuilo** [comment]
＋ボタンから表示されるリアクションピッカーだと絵文字を連続して入力するのが難しそう

**Comment by syuilo** [comment]
投稿フォームに埋め込んで表示するのが良いと思った

**Comment by samunohito** [comment]
@syuilo 
> ＋ボタンから表示されるリアクションピッカーだと絵文字を連続して入力するのが難しそう

ローカルで試作したんですが、この挙動は僅かな修正で制御出来ました
<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/e86421a1-df4e-42aa-90aa-cd787e60f9f3" />

> 投稿フォームに埋め込んで表示

こっちのほうがいいですかね？

**Comment by samunohito** [comment]
一応埋め込みも試してるんですが、アンケートとかCWとか使うと下部のボタンが隠れてしまって…
MkPostFormの表示領域制御が大変そうなので、そのあたりの仕組みが既に実装されているMkEmojiPickerDialogを使う形でやるほうが楽かなと考えております…

<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/2ba82a7d-c66e-4c21-932c-9ab8a8a6303f" />

<img width=40% src="https://github.com/misskey-dev/misskey/assets/46447427/ab7725ee-51e5-4faf-abad-35864e7c65e9" />

**Comment by syuilo** [comment]
非埋め込みでいいか

**Comment by samunohito** [comment]
MkEmojiPickerDialogでPRしましたので、よろしくお願いします:pray:

**Comment by samunohito** [comment]
マージ感謝 :pray:
