### ISSUE TITLE
特定の条件下でノートがnyaizeされない

### ISSUE THREAD

**Issue by Kur0den** [syuilo/Misskey#12331]
### 💡 Summary

- catモードのユーザーのノートを引用RNした際、引用元のノートがnyaizeされない
![image](https://github.com/misskey-dev/misskey/assets/69957747/0ce1c955-3f9e-49c5-bbfe-00c80e0f5493)

- 返信を一覧で表示した際、catモードのユーザーの返信/引用RNがnyaizeされない
![image](https://github.com/misskey-dev/misskey/assets/69957747/4184f527-fe54-432a-9061-86cc4c5ae4a6) ![image](https://github.com/misskey-dev/misskey/assets/69957747/7f955112-7dcb-4646-ae8e-266284adfa58)

### 🥰 Expected Behavior

catモードのユーザのノートがnyaizeされる

### 🤬 Actual Behavior

catモードのユーザのノートがnyaizeされない

### 📝 Steps to Reproduce

- 引用
    1. catモードをonにしているアカウントでnyaizeされるノートを投稿する
    2. 投稿したノートを引用RNする

- 返信
    1. catモードをonにしているアカウントでnyaizeされる返信を適当なノートに送信する
    2. 返信を一覧から確認する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 Home
* Browser: Vivaldi 6.4.3160.42 (Stable channel) (64-bit) 
* Server URL: https://koliosky.com ,  https://gc-key.xn--vusz0j.life
* Misskey: 2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by setaria430** [comment]
通知でもNyaizeされない事を確認しました
