### ISSUE TITLE
「サウンドを出力しない」と「Misskeyがアクティブ時のみサウンドを出力する」オプションを追加

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12341]
### Summary

設定->サウンドと遷移して表示される設定画面に、「サウンドを出力しない」と「Misskeyがアクティブ時のみサウンドを出力する」オプションを追加したいです。これは、Misskeyの音声出力周りに以下の挙動を加えるためのオプションです。
- サウンドを出力しない
マスターボリューム等の設定に関係なく、一切音を出さない
- Misskeyがアクティブ時のみサウンドを出力する
Misskeyを開いているタブとは別のタブを開いた時、ブラウザを最小化した時（スマホの場合はブラウザをバックグラウンドにした時、ロック画面にした時）に音を出さない

### Purpose

主にスマホでMisskeyをみている各位に向けての機能になるかと思います。

- 音声フォーカス対策（バックグラウンド再生中の音楽の音量が下がってしまうなど）
- 画面ロック時にTL更新による音が出続けるのを回避できる
- 音声は不要派の人向け（マスターボリュームを0にも出来るが、スイッチがあったほうが尚やりやすいと思うので）

**Comment by syuilo** [comment]
画面ロック時は音というよりそもそもMisskeyの更新自体停止したい

**Comment by samunohito** [comment]
> Misskeyの更新自体停止したい

別途考えないとですね…（電池持ち良くなりそう）

**Comment by samunohito** [comment]
ちょっと考えてみましたが、このissueでやるには規模が大きく、考えることも多いのではという結論になりました。
非アクティブ化時に止めて再アクティブ化で動かすようにするには、#12227 による仕組みがベースに必要だと考えています。

なので、一旦は音だけ止めるのもアリかなと思っており…

**Comment by samunohito** [comment]
マージ感謝:pray:
