### ISSUE TITLE
[2023.11.1] Safariでアイコンデコレーションが表示されなくなる

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#12344]
### 💡 Summary

overflow-clip-marginはSafariが対応していません
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-clip-margin

### 🥰 Expected Behavior

アイコンデコレーションがiPhoneでも表示される

### 🤬 Actual Behavior

アイコンデコレーションがiPhoneでも表示されない

### 📝 Steps to Reproduce

1. MacOSまたはiPhoneでデコレーションをみる（プロフィールでの設定画面でも可能）

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: https://misskey.gamelore.fun/
* Misskey:2023.11.1-beta.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
iPad OS 17.2では再現できなかったわね

**Comment by fruitriin** [comment]
なんか極一部の人しか起きてないっぽいので一旦クローズにしておいてください
お騒がせしました

**Comment by fruitriin** [comment]
CORS絡みでした　申し訳ない

**Comment by syuilo** [comment]
overflow-clip-margin ってどこで使われてた？

**Comment by fruitriin** [comment]
![スクリーンショット 2023-11-16 11 09 44](https://github.com/misskey-dev/misskey/assets/18308639/d0e35030-eda8-4433-af40-044af39496b2)
UserAgent Stylesheetじゃん！これはもう五体投地
