### ISSUE TITLE
iOSにおいてMisskeyの発する音声とOSのメディアプレイヤーが干渉してしまう

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12340]
### 💡 Summary

iOSにて、Misskeyの通知音がなるとOSのメディアプレイヤーから再生される＝バックグラウンド再生のMusic等が停止してしまう問題が発生しているようです。

### 🥰 Expected Behavior

それぞれが独立して発音する（同時に音を鳴らせる）

### 🤬 Actual Behavior

Misskeyの通知音がなるとバックグラウンド再生中の音声が止まってしまう

### 📝 Steps to Reproduce

1. iOSでメディアプレーヤーを起動し、任意の音楽を再生
2. Misskeyを開き、任意の音を出す（通知を受ける、ノートを受信するなど）

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iOS
* Browser: ？
* Server URL: https://misskey.systems/　※今は仮修正版が乗っています
* Misskey: 2023.11.1-beta.1
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

**Comment by syuilo** [comment]
これAndroidでは発生しないのかしら

**Comment by yuriha-chan** [comment]
Android でも発生します。（バックグラウンドの音楽などは止まらないが、通知音が鳴っている間音量がかなり小さくなる）

**Comment by tai-cha** [comment]
マージ済みでAndroidでも改善しているようなのでcloseします（対応ありがとうございます🙏）

**Comment by acid-chicken** [comment]
#12339 以降 Android の Spotify が止まるらしい（自分は Android デバイスを所有していないので確認できていないが）

**Comment by samunohito** [comment]
Issue化しました。
