### ISSUE TITLE
[2023.11.1-beta.2] MFM unixtimeのプレビューがリアルタイムで反映されない

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#12350]
### 💡 Summary

`$[unixtime 1700000000]` から `$[unixtime 1800000000]` に修正してもプレビュー機能では変わらない。再度プレビューを非表示にして表示すると表示することができる。

### 🥰 Expected Behavior

MFMのプレビューはリアルタイムで反映される

### 🤬 Actual Behavior

MFMのプレビューがリアルタイムで反映されない

### 📝 Steps to Reproduce

1. 投稿画面を開く
2. $[unixtime 1700000000]を入力してプレビューを表示
3. $[unixtime 1800000000]に修正
4. Wow

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):ALL
* Browser:ALL
* Server URL:p1.a9z.dev
* Misskey:2023.11.1-beta.2-p1.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
🙏🏻
