### ISSUE TITLE
絵文字のオートコンプリート強化

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12364]
### Summary

いま現在、絵文字のオートコンプリートは前方一致および部分一致で絞り込まれたものが表示されます。
これを強化し、若干曖昧な形でもオートコンプリートの候補として表示されるようにしたいです。

`neko_think_nya`という名前のカスタム絵文字があったとき、今までは`neko_thi`のようにアンダースコアまで入れないと候補から外れてしまっていたのを、`nethi`でもヒットするように改修を加えようと思っています。

↓こんなかんじ
![image](https://github.com/misskey-dev/misskey/assets/46447427/1a8c0754-dade-4f11-a6b9-b8ac363fe4c4)

### Purpose

オートコンプリートで絵文字を素早く入力しやすくなる。

**Comment by samunohito** [comment]
実装もこのまま自分がやります

**Comment by syuilo** [comment]
パフォーマンスを低下させずに実装するのは難しそう

**Comment by samunohito** [comment]
@syuilo 
じつはもうサンプルを作ってあるのですが、パフォーマンスの劣化は感じませんでした。
検索のためのループも増えてはいますが、ループ回数が増えないように工夫を加えています

https://github.com/misskey-dev/misskey/pull/12365

**Comment by kakkokari-gtyih** [comment]
> パフォーマンスを低下させずに実装するのは難しそう

PR見たけどさほどパフォーマンスに影響はなさそうだし、ユーザビリティーの向上につながるので実装してほしい

もしパフォーマンス低下が気になるなら当該機能をOFFにできるような設定を追加すればいいのでは

**Comment by samunohito** [comment]
マージ感謝:pray:
