### ISSUE TITLE
unixtimeの引数にDateが受け付けない数値を入力するとMisskey外に配送できない

### ISSUE THREAD

**Issue by syobocat** [syuilo/Misskey#12378]
### 💡 Summary

unixtimeにあまりにも大きい数値を入力すると、ISO 8601への変換に失敗しMisskeyでないインスタンスに配送されません。

参考: https://syo.bar/notice/AbxeQYdI6AKw9LRfdI

### 🥰 Expected Behavior

Misskey外に配送できる

### 🤬 Actual Behavior

Misskey外に配送されない

### 📝 Steps to Reproduce

`$[unixtime 8640000000001]`のように、極端に大きい数値をunixtimeの引数に入れる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syobocat** [comment]
unixtimeの引数に数値でないものを入れた場合も同様のようです。

**Comment by kakkokari-gtyih** [comment]
#12420 マージ後に対応予定（当該箇所周辺のコード構造を変更しているため）

**Comment by kakkokari-gtyih** [comment]
何度もマージしてもらうの面倒だし #12420 で一括でやっちゃう
