### ISSUE TITLE
word muteの制限をなくす

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12374]
### Summary

#7574 で追加された制限ですがワードミュート処理がクライアント処理になったのでいらないのではないかと思いました。

ハードミュート相当(TL上で一切表示されないタイプのミュート)実装試行中なのですがword muteの制限の必要性がない気がしました

### Purpose

必要性がない気がしたため。なくす積極的な理由もないので制限を残す理由があればClose as Not Plannedでいいと思います

**Comment by syuilo** [comment]
今は未実装だけどサーバー側でできるとこはサーバー側でやる予定だから制限は要りそう

**Comment by syuilo** [comment]
> ハードミュート相当(TL上で一切表示されないタイプのミュート)実装試行中なのですが必要性がない気がしました

ニーズはあるっぽい
https://github.com/misskey-dev/misskey/issues/12007

**Comment by anatawa12** [comment]
> ハードミュート相当(TL上で一切表示されないタイプのミュート)実装試行中なのですが必要性がない気がしまし

言い方が悪かったですね。"必要性がない"は"word muteの制限の必要性がない"です

**Comment by anatawa12** [comment]
ハードミュート相当のニーズ自体は  https://github.com/niri-la/misskey.niri.la/issues/71#issuecomment-1755688216 で認知しててそれに合わせて実装してるかんじです

**Comment by syuilo** [comment]
あー

**Comment by syuilo** [comment]
まあサーバーのマネタイズには便利かもしれない(例えばpixivはミュートは有料会員しか使えなかった)

**Comment by anatawa12** [comment]
とりあえず残す理由ありそうなのでCloseします

**Comment by Sayamame-beans** [comment]
> 今は未実装だけどサーバー側でできるとこはサーバー側でやる予定だから制限は要りそう

@syuilo 現時点での方針をお伺いしてみてもよろしいでしょうか?
(私としては、しばらくフロント処理だけのままなら制限が無くても良いのかな、となっています。バックエンドでやる分も生えるなら、その際にフロント処理の分とバック処理の分で機能やオプションとして分ける等も検討出来るかなとは思ったりするのですが…)

**Comment by syuilo** [comment]
サーバーによってはフロントで完結する処理でもマネタイズ目的で制限してたりする例があるから、運営者の裁量で制限を設けられるようにする意義はありそう

**Comment by Sayamame-beans** [comment]
> サーバーによってはフロントで完結する処理でもマネタイズ目的で制限してたりする例があるから、運営者の裁量で制限を設けられるようにする意義はありそう

なるほど。制限を設けたい場合に制限出来るようにするというのは(従来がそうであることも踏まえて)良いと思います。
対して、運営者の意図として制限を設けたくないような場合(或いはマネタイズ目的で制限を無しに出来るメリットを与えたい、でも同様です)についてはいかがでしょうか?
(ロールポリシーで"上限無し"を設定出来るようにもするなど)

**Comment by Sayamame-beans** [comment]
(とはいえ、ミュート系はそれこそプラグインやサードパーティクライアントで迂回できるようにも思うので、制限するのがマネタイズに適切かと言われると若干疑問があったりはしますけれど…)

**Comment by syuilo** [comment]
> > サーバーによってはフロントで完結する処理でもマネタイズ目的で制限してたりする例があるから、運営者の裁量で制限を設けられるようにする意義はありそう
> 
> なるほど。制限を設けたい場合に制限出来るようにするというのは(従来がそうであることも踏まえれば)良いと思います。 対して、運営者の意図として制限を設けたくないような場合(或いはマネタイズ目的で制限を無しに出来るメリットを与えたい、でも同様です)についてはいかがでしょうか? (ロールポリシーで"上限無し"を設定出来るようにもするなど)

9999とかにすれば良さそう

> (とはいえ、ミュート系はそれこそプラグインやサードパーティクライアントで迂回できるようにも思うので、制限するのがマネタイズに適切かと言われると若干疑問があったりはしますけれど…)

どのように運営するかというのは我々が口を出すことでもないと思ってる

**Comment by Sayamame-beans** [comment]
> 9999とかにすれば良さそう

無制限のものを有限の高めの値にして誤魔化すのはちょっとどうなんだろうという感じはします(上手く言語化出来ないですが)

**Comment by syuilo** [comment]
本当に「無制限」(=∞)が必要なのかというのはあるわね
マネタイズ云々抜きにしても、あまりに膨大な量の設定が行われるとクライアントが壊れるからどのみちハードリミット的なものは必要で、真に無制限にしたいことって実はない可能性がある

**Comment by syuilo** [comment]
サーバーに保存される可能性があるからサーバーにも関わってくるわね

**Comment by Sayamame-beans** [comment]
それもAPI(エンドポイントのオプション内容の最大文字数とか)で弾けませんか…?

**Comment by syuilo** [comment]
その場合サーバーによってコントロールすることができなさそう

**Comment by Sayamame-beans** [comment]
"クライアントが壊れないようにするための閾値"はMisskeyプロジェクトとして決めるものである気がしています
(各サーバーでそこを調整するならforkの範疇なような)

**Comment by Sayamame-beans** [comment]
"クライアントが壊れないようにするための閾値"はMisskeyプロジェクトとして決めるものである気がしています(各サーバーでそこを調整するならforkの範疇なような)
が、DB都合とかの場合にサーバー制御が必要…?

**Comment by syuilo** [comment]
クライアントというかサーバーもだわね
サーバーの環境によって好ましい値は変わりそう

**Comment by Sayamame-beans** [comment]
とすると、configとかコントロールパネルのパフォーマンス欄とかの設定としてあるべきな感じだったりしないでしょうか…? (ロールポリシーとは意味合いが異なるため)

**Comment by Sayamame-beans** [comment]
それはそれでややこしいか…
