### ISSUE TITLE
hard mute(相当)

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12375]
### Summary

TL上で非表示にする(展開がない)mute

#12007 は設定の話しかしていないためhard muteの話を分割するためにissue

クライアント側でのフィルタで実装施行中です

### Purpose

使い分けてる人はいる模様なので。

https://github.com/niri-la/misskey.niri.la/issues/71#issuecomment-1755688216

**Comment by syuilo** [comment]
クライアント側でhard mute相当を実装するのはなんか不都合が発生しそうな気が漠然としている

**Comment by tai-cha** [comment]
ソフトとハードの違いをTL上に表示されるかどうかだとすると当てるCSSを変えるだけでも体験は近くなるかもしれない

**Comment by tkmrgit** [comment]
> ソフトとハードの違いをTL上に表示されるかどうかだとすると当てるCSSを変えるだけでも体験は近くなるかもしれない

いちいちカスタムCSS設定するのも一般人にとっちゃちょっとわかりにくいので #7575 の実現待ち...

**Comment by tai-cha** [comment]
あー

> クライアント側でhard mute相当を実装するのはなんか不都合が発生しそうな気が漠然としている

これに対する返答ですね

カスタムCSSは奥の手的な感じで思ってるのでカスタムCSSで当てられる内容でも機能として欲しいものはあるべきだよねと思います

**Comment by tai-cha** [comment]
出して欲しいものとそうでないものがあるという認識なのでこれができると私もうれしい

現状だとカスタムCSSで消す以外にはプラグインのregister_view_interrupterで表示を消す方法だとハードミュートっぽく見える（というかノート自体が見えなくなるはず）
