### ISSUE TITLE
虚無ノートが投稿できる

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#12381]
### 💡 Summary

何かの拍子に無入力でも MkPostForm の canPost が true になる？
その場合にそのまま投稿ボタンを押すと無が投稿される
実際に

```sql
SELECT COUNT(*) FROM "public"."note" WHERE ("userHost" IS NULL) AND ("visibility"::TEXT = 'public') AND ("text" IS NULL) AND ("renoteId" IS NULL) AND ("cw" IS NULL) AND ("fileIds"::TEXT = '{}') AND ("hasPoll" = false)
```

すると何件か存在が確認できる

### 🥰 Expected Behavior

- 投稿できるべきでないときは投稿ボタンが押せるべきでない
- 投稿できるべきでないリクエストは失敗すべき

### 🤬 Actual Behavior

- 投稿できるべきでないときもまれに投稿ボタンが押せる
- 投稿できるべきでないリクエストが失敗しない

### 📝 Steps to Reproduce

再現方法は色々ある（被リンク参照）

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by acid-chicken** [comment]
Related to #3361

**Comment by zyoshoka** [comment]
https://github.com/misskey-dev/misskey/issues/9902#issuecomment-1427083278 で既に指摘されていますが、変換確定前の日本語入力のテキストが投稿されるノートに含まれないにも関わらず文字数の判定に含まれているので、変換確定前に投稿用のショートカットキーを押下することで虚無投稿を作成できるようです。
https://github.com/misskey-dev/misskey/blob/95095ee8d11a07938c183d4391de0a76ade31d44/packages/frontend/src/components/MkPostForm.vue#L240-L242
