### ISSUE TITLE
Pageの公開範囲 Page Visibility

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#12397]
### Summary

ノートと同様、ページにも公開範囲を設定できるようになればいいなと思いました。

### 提案する公開範囲

- パブリック
- フォロワー限定
- 非表示
  - プロフィールの「ページ」欄及び「最近の投稿」欄で非表示
- 非公開

### Purpose

- パブリック: 現状通り
- フォロワー限定: フォロワーのみに共有したいページ等需要がありそう
- 非表示: JSONデータ等が格納されたPageをPlay等のAiScript機能から参照し、AiScriptがパース等の処理を行って使用するデータを隠したい(見栄えを良くしたい)
- 非公開: Page自体の下書きなどを想定

**Comment by nenohi** [comment]
Related #6948

**Comment by samunohito** [comment]
対応後の閉じ忘れ防止に #7402

**Comment by t1nyb0x** [comment]
Issue1本化のため、クローズします。

今後確認の際は、#6948 でお願いします。
