### ISSUE TITLE
misskey-jsをnpmにpublishしてほしい

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#12406]
### Summary

npmから利用できるmisskey-jsが5か月前のものとなっているので更新が入ったものをnpmから利用できるようにしてほしい

GitHub Actionsからのpublishも検討してもいいと思います

ref: https://www.npmjs.com/package/misskey-js

### Purpose

新しいmisskey-jsをmisskey外でも気軽に使いたい

**Comment by tai-cha** [comment]
あとリポジトリの情報もモノレポ化する前かもしれない

**Comment by kakkokari-gtyih** [comment]
misskey-jsを新Misskey-hubで使うことになった（今は無理やり外部ツールを使ってこのレポのやつを参照させてる）のでぜひpublishしてほしい

**Comment by kakkokari-gtyih** [comment]
> misskey-jsを新Misskey-hubで使うことになった（今は無理やり外部ツールを使ってこのレポのやつを参照させてる）のでぜひpublishしてほしい

この外部ツールが使えなくなってしまったので Misskey Hub の misskey-js を v0.0.16 まで戻すことになってしまった

**Comment by samunohito** [comment]
その場しのぎも良いところだけど、とりあえずはsubmoduleとsparsecheckoutでmisskey-jsだけを取り出して使えたりは…？

**Comment by kakkokari-gtyih** [comment]
> その場しのぎも良いところだけど、とりあえずはsubmoduleとsparsecheckoutでmisskey-jsだけを取り出して使えたりは…？

移動: https://github.com/misskey-dev/misskey-hub-next/issues/84#issuecomment-1869461987

**Comment by kakkokari-gtyih** [comment]
APIの型とかはモノレポ担っているおかげで基本的にバージョンに追従しているはずなので、misskey-jsの次期バージョンはmisskeyのバージョンと合わせても良いかも

`v0.0.16` → `v2023.12.0`

**Comment by anatawa12** [comment]
misskeyがsemverじゃないから`0.0.yyyyMMp`と思ったけどnpm文化圏あんまりsemver気にしてないからいいのか

**Comment by kakkokari-gtyih** [comment]
たぶんMisskey本体のバージョン番号とマッチしていないほうがややこしいと思うのでSemantic Versioningを要求されてないのならMisskeyのバージョン番号に合わせたほうがいいと思った

**Comment by kakkokari-gtyih** [comment]
となるとリリース時に同時にnpmにpublishすることになるのでやはり #12807 と一体でリリース時の作業自動化のToDoに含めてもらったほうがいいかも

**Comment by tamaina** [comment]
別にon-releaseで動かすので #12807 とは切り離しても良さそう
