### ISSUE TITLE
バックエンドから出力されたapi.jsonを使ってmisskey-jsの型生成を行いたい

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12410]
（機能要望？とは違う気もするので空テンプレートで失礼します）

## 概要

今現在、misskey-jsの型定義は以下の問題を抱えています。

- そもそも型定義が存在しない（TODOになっているものがいくつか）
- 使う分しか実装されておらず歯抜けになっている
- バックエンドに追従できていない

JavaScriptにトランスパイルされるためエラーとはなりませんが…補完が効かないこと、IDE上でエラー扱いされることなど、開発体験はあまり良くありません。そこで、api.jsonから型定義を生成し、それをmisskey-jsに取り込んで使用できるようにすることを提案したいです。

以下の過去issue解決により、上記も現実的になっていると思うので…

#12311
#12402

## 対象者

Misskey本体のフロントエンドを改修する開発者、またはmisskey-jsを使うサードパーティアプリ開発者各位

**Comment by samunohito** [comment]
書くの忘れてた
実装は自分がやるつもりでいます

**Comment by tai-cha** [comment]
related
https://github.com/misskey-dev/misskey/issues/11440
https://github.com/misskey-dev/misskey/pull/10752

**Comment by tamaina** [comment]
( https://github.com/misskey-dev/misskey/pull/10752 をやりたかったけど根気と速度がなくて諦めた
