### ISSUE TITLE
非ログイン時に「内容を隠す」で隠した内容が見えてしまうので隠してほしい

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#12413]
### Summary

非ログイン時に「内容を隠す」で隠した内容が見えてしまうので隠してほしい

### Purpose

政治や精神系の話題といったデリケートな話題を見てUターンしてしまう方もいますし、発言をした方々を守って欲しいからです。
伝わりにくいかもしれませんが、お願いします。

**Comment by anatawa12** [comment]
#11221 と同じかな？

**Comment by PYU224** [comment]
あったんですね。
