### ISSUE TITLE
カスタム絵文字のカテゴリを並べ替えれるようにしたい

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#12411]
### Summary

タイトルの通りです。
投稿画面のカスタム絵文字のカテゴリの並びをカスタマイズできるようにして欲しいです。

### Purpose

私のサーバーの投稿者がとある絵文字のカテゴリを一番上にさせたいとして要望がありました。
よろしくお願いします。

**Comment by tai-cha** [comment]
現状文字列順ですが前に0などのプレフィックスを付けて運用しているサーバーさんはそこそこあるような気がします
ioさんも001のような番号を振っていますね

なので目的自体は名前を変更することでも実現可能ですね～

**Comment by PYU224** [comment]
ありがとうございます。
カテゴリの名前の一括変更って可能ですか？

**Comment by tai-cha** [comment]
カスタム絵文字の画面での検索欄はカテゴリ名でも検索可能だと思います

Select modeというトグルがあるのでオンにしていただき、
その状態で下まですべてスクロールして絵文字を全て読み込んでいただいたあとに、「Select all」をすると一括選択できます

選択後に「Set category」を押すことでカテゴリ名を一括で書き換えることが可能です

ただし検索を利用するので書き換え対象にはご注意ください

（MisskeyのUIを使わない方法としてはAPIを利用して変更する方法もあるはずです）

**Comment by PYU224** [comment]
ありがとうございます。
やってみます。

**Comment by PYU224** [comment]
できました。
ありがとうございます。

**Comment by t1nyb0x** [comment]
目的を達成できているようなので、閉じさせていただきます。
