### ISSUE TITLE
更新が一気に大量に入ると通知音がダブって音割れする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12412]
### 💡 Summary

WebAudioになったので音が重複できるようになった

そのため、複数の通知が同時に入ると音が同時に複数回なって音割れすることがある

### 🥰 Expected Behavior

~~同時に音声が鳴ったときは重複させない~~ 重複数にリミットをかける

### 🤬 Actual Behavior

すべての通知に音が鳴るので音割れする

### 📝 Steps to Reproduce

1. ノート更新通知をオンにする
2. 複数のノートを一気に流す

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Surface Laptop Go 2 Windows 11
* Browser: Chrome 119.0.6045.160 (Official Build) （64 ビット） (cohort: Stable) 
* Server URL:misskey.io
* Misskey: v2023.11.0-io.1.b
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by acid-chicken** [comment]
> 同時に音声が鳴ったときは重複させない

重複は（幾つ通知が来たかわかるメリットがあるため）維持して代わりにリミッターかけてもいいかも

**Comment by kakkokari-gtyih** [comment]
完全に同時に鳴るとどっちにしろ音割れする気がするので、前の音が鳴ってからnミリ秒（50msくらい？）以内は追加で音がならないようにとかにすると良さそう
