### ISSUE TITLE
カスタム絵文字をzipからインポートする操作が動作しない

### ISSUE THREAD

**Issue by camilla-ett** [syuilo/Misskey#12421]
### 💡 Summary

2023.11.1 で確認
表題の通り、一度zipでエクスポートしたカスタム絵文字を、別のサーバー等でインポートしても正しく動作しない

### 🥰 Expected Behavior

カスタム絵文字が正しくインポートされる

### 🤬 Actual Behavior

カスタム絵文字がインポートされない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kanade** [comment]
かなり前から私のサーバーでも同様の問題を抱えています。
FirefishやSharkeyなどでは正常にインポートできます。

これに該当するかもしれません。
https://github.com/misskey-dev/misskey/issues/10778

**Comment by tai-cha** [comment]
@camilla-ett この現象は現在も続いていますか？
もし続いている場合かつあなたがサーバー管理者の場合、現象再現のためにnodeやOSのバージョンを確認し、埋めて頂けると助かります。（#10780 にて解決済みの可能性が高いため一度closeさせて頂きます。問題が続いている場合はreopenしていただけると助かります）

**Comment by kanade** [comment]
@tai-cha 
横から失礼します。検証用の環境を用意し、最新の2024.5.0にて確認してみました。
230MBほどのZIPファイルから絵文字のインポートが正常に行われていることが確認できました。
