### ISSUE TITLE
`user-info.vue`を復活させる Revive `user-info.vue`

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#12429]
### Summary

https://github.com/misskey-dev/misskey/blob/a8d7b69fbd56a9d64a941bcccbe5416c94e60f8d/packages/frontend/src/pages/user-info.vue
[bbef2a953ebf2f7f063641e6764ec8571cd78b75](https://github.com/misskey-dev/misskey/commit/bbef2a953ebf2f7f063641e6764ec8571cd78b75#diff-ee16b8f82f6e0372dcc608775c5275863932c3670cb62c6bf07a10ceb69c5943)で管理者専用(?)になってしまったようです。
デバッグやPlay等の制作に重宝していたので、なくなってしまい不便になっています。
(実際carefulBot関連の不具合を突き止めるのに役立ちました。)

### Purpose

* Misskey上のバグの原因を調べるため
* Playやプラグインを作る際に使うため

**Comment by kakkokari-gtyih** [comment]
具体的にどのメニューを使用していました？

（そこだけ既存のプロフィールページに追加するかたちで対応しても良いかなと思ったので）

**Comment by MineCake147E** [comment]
> 具体的にどのメニューを使用していました？

主にRawとOverviewです。

**Comment by syuilo** [comment]
ユーザーページが二種類(モデレーションページも含めたら三種類)あることになるのはスマートじゃないから user-info を復活させることはないかも

**Comment by kakkokari-gtyih** [comment]
RawデータとUser IDを引っ張れるページを作って追加した（こんな感じでいかが？）

![image](https://github.com/misskey-dev/misskey/assets/67428053/a1ce258b-9836-459f-b97e-ab201b0b3ee6)

**Comment by syuilo** [comment]
YOSASOU

**Comment by MineCake147E** [comment]
とても良さそうです!
ありがとうございます。
