### ISSUE TITLE
特定の条件下で一部のタイムラインが更新されなくなる

### ISSUE THREAD

**Issue by hideki0403** [syuilo/Misskey#12430]
### 💡 Summary

チャンネルとユーザープロフィールのノートタブにおいて、FanoutTimelineを有効にした状態で投稿してから無効に変更すると、無効にした後に投稿したノートが表示されなくなります。

### 🥰 Expected Behavior

該当するタイムラインに最新のノートが表示される

### 🤬 Actual Behavior

該当するタイムラインに最新のノートが表示されない

### 📝 Steps to Reproduce

1. FanoutTimelineが有効の状態でチャンネルに投稿する
2. FanoutTimelineを無効にする
3. チャンネルに投稿する
4. (3)で投稿したノートがチャンネルに表示されない

(ユーザーのノート一覧についても同様の手順で再現できます)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Any
* Browser: Any
* Server URL: Any
* Misskey: 2023.11.1
```

**Comment by hideki0403** [comment]
問題なさそうであれば修正も自分がやります

**Comment by syuilo** [comment]
> (3)で投稿したノートが表示されない

これは具体的にどのタイムラインでしょう？

**Comment by hideki0403** [comment]
チャンネルです...！追記しておきます:pray:
