### ISSUE TITLE
受信キーワード、除外キーワードの両方を空にしたアンテナが作れなくなった

### ISSUE THREAD

**Issue by esperecyan** [syuilo/Misskey#12445]
### 💡 Summary

受信キーワード、除外キーワードの両方を空にしたアンテナが新規作成できなくなり、既存のアンテナの変更もできなくなっています。

既存のアンテナの動作自体は、正常に行われています。

ユーザーページからアンテナへユーザーを追加しようとして気付きました。

### 🥰 Expected Behavior

アンテナの新規作成、変更が行われる。

### 🤬 Actual Behavior

以下のエラーダイアログが表示される

> サーバー内部エラー
> サーバー内部で予期しないエラーが発生しました。

![](https://github.com/misskey-dev/misskey/assets/3625160/84aaf8b7-188f-4f8a-ab21-9f9058fb3976)

「エラー情報をコピー」の内容は以下の通り。

> Endpoint: antennas/update
> Info: {"e":{"message":"either keywords or excludeKeywords is required.","code":"Error","id":"5c8fc16a-7a99-4acc-a690-0e50f2b69c9e"}}
> Date: 2023-11-25T02:34:58.703Z

### 📝 Steps to Reproduce

1. アンテナの「追加」ページを開く
2. 「名前」へ任意の文字を入力する
3. 「受信ソース」を「指定した一人または複数のユーザーのノート」にする
4. 「ユーザー」を入力する
5. 「保存」する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Windows 10 Home 22H2
* Browser:Firefox 120.0
* Server URL:https://misskey.io/
* Misskey:2023.11.1-io.2a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
これは仕様ですね

**Comment by esperecyan** [comment]
@syuilo いちおう除外キーワードに無意味な文字列を入れれば回避できそうですが、なぜこのような仕様があるのでしょうか……？

**Comment by syuilo** [comment]
受信キーワード、除外キーワードが空というのはアンテナ機能の目的に反するためです

**Comment by esperecyan** [comment]
なるほど、そのような利用方法はリスト側の機能ということになるでしょうか。

検索したらたしかに希望している動作はこちらのissueと重複していました。
https://github.com/misskey-dev/misskey/issues/8760

失礼いたしました。
