### ISSUE TITLE
Apple Deviceにおいて,「デバイスの画面を常にオンにする」と読み込めなくなる

### ISSUE THREAD

**Issue by x86taka** [syuilo/Misskey#12462]
## 概要
Apple Deviceにおいて,クライアント設定の「デバイスの画面を常にオンにする」と読み込めなくなる

### iPhone12 Safari においてのエラー表示
![image](https://github.com/misskey-dev/misskey/assets/19627440/b464a862-bd44-4c38-b22d-cdc968f6b980)

### 該当の設定項目
![image](https://github.com/misskey-dev/misskey/assets/19627440/9db1341d-1545-4c39-a531-25f6f7cdc9b9)

### 試した環境と動作

○ => 該当の設定を有効化後,問題なく読み込める
X => 該当の設定を有効化後,「Failed to load」ページが表示される.

- iPhone X 
  - Safari X
  - Chrome X
  - Firefox(元々ブラウザがAPIに非対応) ○
- MacOS △
  - Safari X
  - Chrome ○
  - Firefox(元々ブラウザがAPIに非対応) ○
## 一時的な解決方法

**ブラウザキャッシュをクリアの`://{host}/flush`にアクセスしても解決しない.**

SafariのWebサイトデータからデータの消去を行うと問題が解決する.

### 🥰 Expected Behavior

「デバイスの画面を常にオンにする」を有効化した場合に,最低限サイトにアクセスできなくなることを防ぐ.

できれば,サポートされていない場合に設定画面を表示しない動作が望まれる.

### 🤬 Actual Behavior

「デバイスの画面を常にオンにする」を有効化した場合に,サイトにアクセスできなくなる.

iPhoneの場合,設定アプリからSafariを開き,Webサイトデータから該当のドメインのデータを削除を行わないと,回復しない.

### 📝 Steps to Reproduce

1. 設定 => クライアント設定 => 全般 => 動作
2. 「デバイスの画面を常にオンにする」を有効にする
3. ページのreloadを求められるため,reloadを行う
4. 「Failed to load」ページになる

*「clear preferences and cache」を行っても回復しない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iPhone12 iOS 17.1.1
* Browser: Safari
* Server URL: misskey.gg (Problems occur on other servers.)
* Misskey: v2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: k8s(Official docker image tag 2023.11.1)
* Misskey: v2023.11.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kakkokari-gtyih** [comment]
~~Safariで無理なら多分その機能は対応していない~~**対応してるらしい**が、そのエラーを回避するためのtrycatchが入っていないかも

**Comment by x86taka** [comment]
traycatchで対応するのは同じことを考えておりました.

**Comment by ragujp** [comment]
Safariは対応してるっぽいけど...
https://developer.mozilla.org/ja/docs/Web/API/WakeLock#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%83%BC%E3%81%AE%E4%BA%92%E6%8F%9B%E6%80%A7
navigator.wakeLock.requestでエラーでてるぽい

**Comment by zyoshoka** [comment]
エラーの原因は、以下の `navigator.wakeLock.request('screen');` を実行したときにパーミッションエラーになるためです。

https://github.com/misskey-dev/misskey/blob/d60f645d1dc731d7ef6eff16081d2b5615412690/packages/frontend/src/boot/common.ts#L205-L207

Safari においても [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) は対応しているものの、Safari ではこれを実行するためにはユーザーによる有効化のあとに実行される必要があるようです[^1]。WebKit 以外では（MDN のドキュメントを見る限りだと）この API を実行するためにユーザーによる有効化を待つ必要がないようです[^2]。

なので、エラーページが表示されるまでの間にクリックを連打すると一応このエラーを回避できたりします。

[^1]: https://webkit.org/blog/13862/the-user-activation-api/
[^2]: https://developer.mozilla.org/en-US/docs/Web/Security/User_activation
