### ISSUE TITLE
ノート表示から、動画等に対しても"センシティブとして設定"を行えるようにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#12478]
### Summary

投稿済みのノートにおいて、本人/モデレーターはそのノート表示から画像を"センシティブとして設定"することが可能ですが、動画等については当該ボタンが無く、この操作を直接行うことは出来ません。

画像の場合
![image](https://github.com/misskey-dev/misskey/assets/61457993/ca409bcd-5afa-4f35-8d02-6f14549e855a)
動画の場合
![image](https://github.com/misskey-dev/misskey/assets/61457993/ccfce7da-4f3c-4403-a78d-2f904b4fb8fb)

### Purpose

動画等をセンシティブに設定するためには、本人のドライブからファイルに対して設定を変更する必要があり、不便です。
画像と同じように、直接設定出来れば便利かもしれないと考えました。
(音声等は埋め込みの問題で実装が複雑かもしれません。動画だけでも対応があると嬉しいです。)

**Comment by kakkokari-gtyih** [comment]
動画プレイヤーのcontrolsを自前で持つか・・・？
（そうしないとブラウザUIとバッティングして面倒くさそう）

**Comment by kakkokari-gtyih** [comment]
> 動画プレイヤーのcontrolsを自前で持つか・・・？ （そうしないとブラウザUIとバッティングして面倒くさそう）

plyrがもうすぐdeprecatedになるのでその後継（vidstack）を試しに導入してみたけど、うまいこと動かなかったので、別の方法を試す必要がありそう

**Comment by Sayamame-beans** [comment]
#12093 と被ってたかもしれません(今気付きました)
ただ、これbugというよりfeatreqではある気がします。(コントロールパネルを通じた操作で閲覧注意付与自体は可能であるため)
