### ISSUE TITLE
通知のグルーピング表示の設定変更が、デッキ表示の通知カラムのリロードだけでは反映されない

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#12470]
### 💡 Summary

`通知をグルーピングして表示する`の設定を変更した場合、通知ページをウィンドウで開いた時はウィンドウ単位のリロードで変更が反映されることが確認出来ますが、通知カラムではカラム単位のリロードを行っても変更が反映されず、Misskeyを開いているタブごとリロードする必要があります。

### 🥰 Expected Behavior

デッキ表示において
1. `通知をグルーピングして表示する`の設定を変更する
2. 通知カラムをリロードする
3. 設定変更が反映された状態で表示される

### 🤬 Actual Behavior

デッキ表示において
1. `通知をグルーピングして表示する`の設定を変更する
2. 通知カラムをリロードする
3. 設定変更が反映されていない状態で表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 10 Pro 22H2
* Browser: Google Chrome 119.0.6045.160
* Server URL: https://misskey.niri.la/
* Misskey: 2023.11.1-kinel.1 (2023.11.1がベースです)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by samunohito** [comment]
以下理由から、リロードしないと反映されないような形になっています。
- グルーピングの設定値がリアクティブになっていない
- MkPaginationがエンドポイント変更契機でのリロードに対応していない

https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/components/MkNotifications.vue#L46-L58
https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/components/MkPagination.vue#L189

**Comment by samunohito** [comment]
（夜になっても誰もアサインされてなければ自分が対応します）

**Comment by syuilo** [comment]
反映するにはリロードが必要ですダイアログを出すと良さそう

**Comment by samunohito** [comment]
@syuilo 
リロードするダイアログを出すでも全然構わないのですが、

- フロントエンドの起動シーケンスに関わる
- 各ノートから参照されるなどリアクティブにするとパフォーマンスの劣化が予想される

…にあたる設定項目でもなさそうなので、リアクティブ対応にしても良さそうだなと思いました。
というのも、設定変更による再起動が必要な箇所を最低限に抑えたほうが良いかと思っており…（変えるときは一気に変えることが予想されるので、その都度再起動を求められるのはちょっと辛いかも）

**Comment by syuilo** [comment]
ほむん

**Comment by samunohito** [comment]
❤ついてるし↑でやっちゃいますね
