### ISSUE TITLE
iPadでdeck uiでマウスでスクロールできなくなった

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12477]
### 💡 Summary

iPadでdeck uiでマウスでスクロールできなくなった

### 🥰 Expected Behavior

スクロールできる

### 🤬 Actual Behavior

スクロールできない

### 📝 Steps to Reproduce

1. deck uiにする
2. マウスをつなぐ (universal controlを使用してテストしてます)
3. スクロールしようとする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iPad mini (6th gen) A2568 iPad OS 17.0.3
* Browser: PWA / Safari
* Server URL: misskey.niri.la / misskey.io
* Misskey: 2023.11.1-kinel.1 / 2023.11.1-io.3
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Srgr0** [comment]
Related?: #11733

**Comment by anatawa12** [comment]
そのものですね

Duplicate of #11733
