### ISSUE TITLE
サーバーの招待コードを発行できない

### ISSUE THREAD

**Issue by TanadaMizuki** [syuilo/Misskey#12475]
### 💡 Summary

Misskeyのバージョンを2023.9.3から2023.11.1にアップデートしたところ、サーバーの招待コードを発行できなくなった

### 🥰 Expected Behavior

コントロールパネルから招待コードを発行できる

### 🤬 Actual Behavior

「招待コードを発行」を押すと、×とだけ書かれたダイアログが表示されて招待コードを発行できない
![Screenshot_20231126-171125~2](https://github.com/misskey-dev/misskey/assets/134439683/e1523f89-7af7-4ccb-844a-17876d8c0f3f)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2023.11.1
* Node: 18.17.1
* PostgreSQL: 15.5.1
* Redis: 7.2.3
* OS and Architecture: Ubuntu 22.04 LTS
```

**Comment by syuilo** [comment]
再現できなかった👀

**Comment by samunohito** [comment]
手元の環境で連打など試してみましたが、それらしい現象は再現せずでした。
エラーコードすら出ないことから、本当に想定外のことが起こっているものと思われますが…

> Installation Method or Hosting Service: systemd

可能であれば、journalctlなどから現象発生時のログを取得いただけるとスムーズかもしれません。

**Comment by TanadaMizuki** [comment]
返答が遅れてすみません。

> 可能であれば、journalctlなどから現象発生時のログを取得いただけるとスムーズかもしれません。

招待コード発行時に以下のログが排出されました。
```
TypeError: this.idService.genID is not a function
    at file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/admin/invite/create.js:88:40
    at Endpoint.exec (file:///home/misskey/misskey/packages/backend/built/server/api/endpoint-base.js:42:20)
    at ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:25)
    at file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:100:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 3eccd3fb-6d83-4606-b74a-1d88ad3a42bb
```

何かお気づきの点があればご教授願います。

**Comment by syuilo** [comment]
> this.idService.genID

現在Misskeyにそのようなコードは無いので、アップデートがうまくいってなさそうですね

**Comment by TanadaMizuki** [comment]
> 現在Misskeyにそのようなコードは無いので、アップデートがうまくいってなさそうですね

ありがとうございます。
折を見てアップデートをやり直したいと思います。

**Comment by u1-liquid** [comment]
MisskeyのソースコードをForkして利用しているのであれば変更点のMerge時にミスがあったかもしれません
運用している環境がDockerなどてはなくソースコードから直接ビルドして動いているのであれば
一旦サーバーを止めて
```
pnpm clean （もしくは pnpm clean-all ）
pnpm i
pnpm build
```
してからサーバーを起動してみると良いかもしれません
サーバーのスペックによりますが5分ほどかかると思います

**Comment by TanadaMizuki** [comment]
結局いろいろ試してもうまくいかなかったのですが、先日Misskeyのバージョンを2023.12.0にアップデートしたところ、正常通り招待コードを発行できました。ご指摘の通り、2023.11.1へのアップデートがうまくいっていなかったからだと思われます。
ご対応いただきありがとうございました。
