### ISSUE TITLE
Shareページでの投稿完了時に`postMessage`を発火する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12504]
### Summary

https://developer.mozilla.org/ja/docs/Web/API/Window/postMessage

投稿が完了したら、これを発火

### Purpose

iframe、もしくは名前付きポップアップWindowでMisskeyのシェアページを読み込んだ際に、その親サイトと連携を取りやすくする

**Comment by kakkokari-gtyih** [comment]
[下手に作成したノートの生データとかを渡しても良くない気がする](https://developer.mozilla.org/ja/docs/Web/API/Window/postMessage#targetorigin)ので、単純に「投稿が成功した」という内容を送信するのがよさそう

将来的に`postMessage`を使用するときのことを考えて拡張性を残しておくならこういうオブジェクトを渡すのが良いかも？

```js
{
    type: "misskey:shareForm:shareComplete",
    payload: null,
}
```

**Comment by syuilo** [comment]
良さそう
