### ISSUE TITLE
フォロー後、特定条件下でSTLのHTL相当のノートが消える（表示できなくなる）

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#12513]
### 💡 Summary

フォローを行った後、フォローしている誰かがノートを行うとSTLにてそれ以前のHTL分のノートが取得できなくなる

### 🥰 Expected Behavior

STLにHTL分のノートが表示されている

### 🤬 Actual Behavior

フォロー中のユーザーが最初にノートした以前のHTL相当のノートがSTLで見られなくなる

### 📝 Steps to Reproduce

1. なんらかのHTL相当のノートをしておく（ホーム、フォロワーのみなど）
2. 誰かをフォローする
3. フォローしているユーザのうちだれかが何らかのノートを行う
4. STL上からHTL相当部分のノートが消える

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:2023.11.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by anatawa12** [comment]
間違ってました(以下参照)

https://github.com/misskey-dev/misskey/blob/37cff405ed620a9a885475f63067446c56c58415/packages/backend/src/server/api/endpoints/notes/hybrid-timeline.ts#L122-L142

witgReplies/withFilesがオンのときにhTLか空でもDB fallbackしないようになってるのがダメそう

**Comment by tai-cha** [comment]
この手順だとwithFilesじゃなくてもそもそもHTLが空じゃなくなるので取得できないノートが出てくるはず

**Comment by tai-cha** [comment]
ノート数が1以上になるはずなので

**Comment by anatawa12** [comment]
あー、なるほどです
