### ISSUE TITLE
画像拡大後、Escキーで閉じたい

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12515]
### Summary

画像を拡大表示したあとEscキー押下で閉じたいです。
TweetDeckなどではそのように動作していました。

### Purpose

ヘビーユーザーのストレスが減ると思います。

**Comment by kakkokari-gtyih** [comment]
現状のコード見た感じすでにEscで閉じれてもおかしくないはずなんだけど、何かが引っかかって閉じれないっぽい

**Comment by zyoshoka** [comment]
これですかね: #11364

**Comment by kanade** [comment]
バグとして既出だったんですね。
もし対応が難しくなさそうであれば解決してもらえたら嬉しいなと思います。

**Comment by kakkokari-gtyih** [comment]
Duplicate of #11364

↑こっちに統合します
