### ISSUE TITLE
ハッシュタグトレンドにNGワードを設定できるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12510]
### Summary

センシティブなタグがトレンドに上がることを防ぐ

クライアント側のワードミュートを使うか、コントロールパネル側のNGワードで切るか

### Purpose

↓これどうにかしたい（2023-11-30 00:10 JST の misskey.io）

![image](https://github.com/misskey-dev/misskey/assets/67428053/385541d4-8285-40ff-b26b-d8d3f16119cc)

**Comment by acid-chicken** [comment]
トレンドに限る必要がなさそう（サジェストなども同じ設定でコントロールされるべき）
