### ISSUE TITLE
音声ファイルの再生UIが一部隠れてしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#12521]
### 💡 Summary

デッキUIなどの場合において、(ブラウザ標準と思われる)音声再生用のUIが部分的に隠れてしまうことがあります。
![image](https://github.com/misskey-dev/misskey/assets/61457993/a9533ef5-4a4b-42eb-806b-bd9b19766d76)

音量が操作出来ないと不便なので、(可能かどうか存じないのですが)縮小するなどして対応していただけると嬉しいです。
独自UIを作る必要がある場合は #12478 も少し関連してきそうですかね…?

### 🥰 Expected Behavior

再生用UIが隠れない。

### 🤬 Actual Behavior

再生用UIの一部が隠れ、操作が困難である。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 10 Pro 22H2
* Browser: Google Chrome 119.0.6045.161
* Server URL: https://misskey.niri.la/
* Misskey: 2023.11.1-kinel.2 (2023.11.1をベースにcherry pickなどを行っているバージョンです)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kakkokari-gtyih** [comment]
> 独自UIを作る必要がある場合は https://github.com/misskey-dev/misskey/issues/12478 も少し関連してきそうですかね…?

この際両方独自にしてしまうのも手
