### ISSUE TITLE
アイコンデコレーションを簡単に外せるようにしたい

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12529]
### Summary

「設定」>「プロフィール」>「アイコンデコレーション」において、アイコンデコレーションが既に設定されている場合には「外す」ボタンをトップレベルに表示するようにしたいです。

### Purpose

アイコンデコレーションを外すためには、現状では自分の設定しているアイコンデコレーションを探し出してダイアログを開く必要があり、インスタンスのアイコンデコレーションの数が多い場合には手間がかかります。トップレベルに「外す」ボタンがあれば、この手間を省くことができます。

**Comment by kakkokari-gtyih** [comment]
「なし」っていう項目を置くほうが良さそう

**Comment by syuilo** [comment]
実装方法によってはデコレーション複数つけられるようにする実装と相性が悪そう

**Comment by kakkokari-gtyih** [comment]
なら、今ついているデコレーションを選択画面上部にリストで出しておくといいかも（各項目右にバツ印をつけて一つずつ消せるようにする）

**Comment by zyoshoka** [comment]
Related to #12256

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/522c106c-9ce1-437a-880c-a37477c9067b)

良さそう

**Comment by kakkokari-gtyih** [comment]
すべて外すボタンが実装されたのでClose
