### ISSUE TITLE
特定の状況下で連合無しノートが連合される

### ISSUE THREAD

**Issue by Kur0den** [syuilo/Misskey#12531]
### 💡 Summary

連合無しノートがピン止めしてある状態でそのアカウントを照会したことがない別インスタンスからそのユーザーを照会するとピン止めされている連合無しノートが連合されてしまう

一度連合されたノートは既に連合済みのインスタンスからでも閲覧/リアクション等ができる

### 🥰 Expected Behavior

連合無しノートは連合されない

### 🤬 Actual Behavior

連合無しノートが連合されてしまう

### 📝 Steps to Reproduce

1. 連合なしのノートを作成
2. 作成したノートをピン止め
3. そのユーザーを照会したことがない別インスタンスからそのユーザーを照会する
4. ピン止めされた連合無しのノートが見える

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: koliosky.com, その他
* Misskey: 2023.11.1, 2023.12.0-beta1
    - 2023.11.1以前でも連合無しノートが連合されている状況を見たことがある
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by penginn-net** [comment]
連合済み（FF関係,リレー参加）のサーバーでも
リモートユーザの更新を行えば流れてきました

**Comment by Srgr0** [comment]
> 連合済み（FF関係,リレー参加）のサーバーでも リモートユーザの更新を行えば流れてきました

以下の環境では再現できませんでした。
送信：＠srgr0＠misskey.srgr0.com
受信：misskey.io、nijimiss.moe (それぞれ＠srgr0でFF関係)
※送信側でノート投稿(連合なし)&ピン留め後、受信側でリモートユーザーの更新

**Comment by penginn-net** [comment]
自分の場合
送信:@penginn@gc-key.xn--vusz0j.life
受信:@penginn_0@misskey.io,@penginn@koliosky.com
だと再現できるんですよね....

**Comment by 1673beta** [comment]
下記のアカウントで、送信側がピン留めしている状態でリモートユーザーの情報が更新されると再現しました。
送信: @esurio1673@kasei.ski
受信: @esurio1673@koliosky.com

**Comment by setaria430** [comment]
これ不具合だったのですね。ピン留めノートはユーザ情報の中に入るので、リモートに送られるのも自然かと思ってました
チャンネルのノートを強引に連合させるのに便利で…

**Comment by Srgr0** [comment]
> apiというかピン度目ノートはユーザーの情報にそのままrenderされるから連合したときに連合ありなし関係なく連合されてしまう
https://misskey.srgr0.com/notes/9mqb0fhmgw

「連合なし」のノートをピン留めするときに警告出して、ピン留めされたら「連合なし」状態を解除するくらいが良いのかも

**Comment by Srgr0** [comment]
fixed in #12541 ?
