### ISSUE TITLE
テーマエディタでテーマプレビューが見れない。

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#12533]
### 💡 Summary

テーマエディタでテーマのプレビューが指定されたURLに該当するページはありませんでした。と表示されプレビューがみれない。
![image](https://github.com/misskey-dev/misskey/assets/89781396/26186f63-c2c8-4e8f-8d35-4e14a10e6501)

### 🥰 Expected Behavior

テーマのプレビューが見れる。

### 🤬 Actual Behavior

`/preview`が存在しないため、指定されたURLに該当するページはありませんでした。と表示される。

### 📝 Steps to Reproduce

1. 設定を開く
2. テーマを開く
3. テーマを作るを開く
4. 右上に表示されている目のアイコンを開く
5. 指定されたURLに該当するページはありませんでした。と表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows11 22H2
* Browser: chrome 119.0.6045.200, firefox 119.0.6045.200
* Server URL: misskey.io, misskey.moe
* Misskey: 2023.11.1-io.3a, 2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by futchitwo** [comment]
😮 https://github.com/misskey-dev/misskey/commit/3d4a90b08a284f416564fc950a9216936c1a8e99

**Comment by nullnyat** [comment]
手をつけて見てるかも

**Comment by samunohito** [comment]
@syuilo 
https://github.com/misskey-dev/misskey/commit/3d4a90b08a284f416564fc950a9216936c1a8e99#diff-0af10927c0c66fc83b6a4c7e2de6faf9f4430350acee604a97e663d358effbf2L245-L247
↑にてpreviewのページが消されているように見えますが、プレビュー機能そのものは廃止となっているのでしょうか？

**Comment by Sayamame-beans** [comment]
リアルタイム反映されるようになっているかも?

**Comment by nullnyat** [comment]
この機能をほしがっているユーザーが多い気がしているのと、一ページぱっと見ただけで、ボタンの色やタグの色などを確認できるしあったほうがいいかなぁと。。。。

<img width="491" alt=" 2024-06-17 9 24 31" src="https://github.com/misskey-dev/misskey/assets/89781396/4fc8f819-4cb6-4852-8c1a-2fd32f240d2f">
