### ISSUE TITLE
コンディショナルロールに割り当てられている人の一覧がほしい

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12563]
### Summary

コンディショナルロールにおいて、そのロールが割り当てられているユーザーを一覧で見たいです。
「ユーザーを見つけやすくする」オプションとは違い、管理者しか見れないようなものが理想的ですが…実現可能でしょうか？
マニュアルでアサインしたロールと同様の表示でもかまいません。

### Purpose

例えば「~~パトロン~~Patreonで500円以上支援している」というコンディショナルなロールがあった場合、そのロールが割り当てられているユーザーをリスト化して見られたら便利です。

**Comment by syuilo** [comment]
コンディショナルロールに割り当てられている人の一覧を取得することは不可能です。

> 例えば「パトロンで500円以上支援している」というコンディショナルなロールがあった場合

コンディショナルロールは予めMisskey側で用意された条件しか使用できないので、「パトロンで500円以上支援している」というような条件は使用できません。

**Comment by kanade** [comment]
@syuilo 
混同していて表現が正確ではなかったです、すみません！
たとえばこういうロールを作った際の話です。
Misskey側で用意された条件でかまいません。
![image](https://github.com/misskey-dev/misskey/assets/732664/f033b09e-a276-4580-9440-c3cb29d6c699)

**Comment by kanade** [comment]
> コンディショナルロールに割り当てられている人の一覧を取得することは不可能です。
不可能な理由はなんでしょうか、後学のため教えてください。

**Comment by kanade** [comment]
閉じます！
