### ISSUE TITLE
絵文字ピッカーでも予め設定した絵文字デッキを使いたい

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12560]
### Summary

#12337 の最後に行われた対応（ a3b2ec4  ）にて、リアクションデッキで設定した絵文字一覧を絵文字ピッカー側から使用できなくなりました。絵文字ピッカーでよく使う絵文字とリアクションピッカーでよく使う絵文字をまとめて兼用にしていたユーザがそれなりに観測できており（自分も）、今のままでは若干不便かと思いました。

そこで…以下のいずれかを提案したいです。
- a3b2ec4 を戻す
- 絵文字ピッカー用の設定項目としてリアクションデッキと同等のものを用意する（行列のサイズと絵文字一覧）
リアクションピッカーと同じ値を流用するオプションがあるとなお◎

### Purpose

いずれの方針でも、絵文字を入力するときに自分の気に入っている絵文字を入力しやすくなる

**Comment by syuilo** [comment]
やっぱり投稿フォームに埋め込んだ方が良いかも(サイズ設定を設ける必要性が無くなる)

**Comment by anatawa12** [comment]
「リアクションピッカー」という名称だったのはそうですが実質的には「絵文字ピッカー」になってたので「絵文字ピッカー」に名前もしてリアクションデッキ(絵文字デッキ)を復活させるのではだめですかね

**Comment by syuilo** [comment]
一般に投稿内で使いたい絵文字とリアクションとして使いたい絵文字は異なりそう

**Comment by syuilo** [comment]
> 絵文字ピッカー用の設定項目としてリアクションデッキと同等のものを用意する（行列のサイズと絵文字一覧）

だと何か問題あるのかしら(設定UIが煩雑になりそうという以外)

**Comment by samunohito** [comment]
@syuilo 
ひとまず、

1. a3b2ec4 を戻すプルリクを作る
2. 絵文字ピッカー用の設定項目としてリアクションデッキと同等のものを用意する（行列のサイズと絵文字一覧）＋リアクションピッカーと同じ値を流用するオプションを搭載するプルリクを次のリリースまでに作る

で対応しようと思いますが、いかがでしょう？

**Comment by syuilo** [comment]
1 の必要性がわからない

2 のサイズ設定は不要にしてピッカーの表示方法を考え直した方が良さそう

**Comment by samunohito** [comment]
@syuilo 
> 1 の必要性がわからない

これは、「いずれ修正されるからあえて戻す必要はない」ということですか？

> 2 のサイズ設定は不要にしてピッカーの表示方法を考え直した方が良さそう
もしくはサイズ設定はリアクションピッカーと統合しても良さそう

これは複雑になるから…で相違ないでしょうか？

**Comment by syuilo** [comment]
> これは、「いずれ修正されるからあえて戻す必要はない」ということですか？

それもあるし、仮に改修される予定が無かったとしても間違った仕様ではないから戻す必要性が感じられなかった

> これは複雑になるから…で相違ないでしょうか？

yes
