### ISSUE TITLE
メール通知が来ない

### ISSUE THREAD

**Issue by penginn-net** [syuilo/Misskey#12573]
### 💡 Summary

別端末で開いていたのを閉じたり、5分程待っても変わりませんでした。

### 🥰 Expected Behavior

メール通知が来る

### 🤬 Actual Behavior

メール通知が来ない

### 📝 Steps to Reproduce

1.メール通知条件の事が起きる
2.メールが来ない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:Chrome 119.0.6045.163
* Server URL:
gc-key.xn--vusz0j.life,koliosky.com
* Misskey:2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by 49372s** [comment]
もはや仕様だと思ってた😅

**Comment by zyoshoka** [comment]
重複のためクローズします🙏

Duplicate of #9032
