### ISSUE TITLE
ローカルのみにチェックをつけて検索するとエラー画面が表示される

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12589]
### 💡 Summary

MeiliSearch使用環境下で発生するものと思われます。
有志が回収してくれたエラーログを見る限り、文法エラーが起こっていそうです。

```
Was expecting an operation `=`, `!=`, `>=`, `>`, `<=`, `<`, `IN`, `NOT IN`, `TO`, `EXISTS`, `NOT EXISTS`, `_geoRadius`, or `_geoBoundingBox` at `userHost IS NULL))`.\n3:21 ((userHost IS NULL))
```

### 🥰 Expected Behavior

ローカルに絞り込んだ検索が行える

### 🤬 Actual Behavior

エラーが出て検索できない

### 📝 Steps to Reproduce

検索→オプションでローカルのみにチェックをつけて検索

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Any
* Browser: Any
* Server URL: https://misskey.systems/
* Misskey: 2023.12.0-beta.2
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

**Comment by nakkaa** [comment]
2023.12.0-beta2(commit id: e6d01e)とMeilisearch 1.5.0で確認しましたが再現しませんでした。
みすてむずが利用しているMeilisearchのバージョンが古かったりしませんか？

**Comment by samunohito** [comment]
情報ありがとうございます。
先ほど管理者の方が更新作業を終えたようでエラーが出なりました。

Meilisearchのリポジトリを確認したところ、v1.2.0でリリースされた機能でした（2023年6月5日公開とのこと…）
https://github.com/meilisearch/meilisearch/releases/tag/v1.2.0

**Comment by samunohito** [comment]
原因がはっきりして対処もわかったので、このissueは閉じます。
ありがとうございました :pray:

（ざっと見る限り、meilisearchの必須バージョンはMisskeyHubなどにも記載がなく…バージョンの明記が必要ですね）
