### ISSUE TITLE
翻訳が見つからなかった時に翻訳キーを表示するようにして欲しい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12592]
### Summary

タイトルの通りです

### Purpose

開発時にキャッシュを消さないと何も表示されないで見ずらいため

**Comment by CyberRex0** [comment]
翻訳のフォーマッティングでエラーが発生した場合、現状抑制しているので、エラーをthrowするか同じようにキーを表示するようにしてほしいです

**Comment by anatawa12** [comment]
一応Proxyとかその系統で作ることできないかなぁと思ってたりしました。

**Comment by anatawa12** [comment]
> 万が一実装漏れでキーのままリリースされたとしても一般人にキーを見せるわけには行かないので

逆に何も表示されないほうが困ると思うのですがこの考えの理由は何でしょう？英語である程度意図を示されてるものが表示される方がマシだと思います

**Comment by kakkokari-gtyih** [comment]
> > 万が一実装漏れでキーのままリリースされたとしても一般人にキーを見せるわけには行かないので
> 
> 逆に何も表示されないほうが困ると思うのですがこの考えの理由は何でしょう？英語である程度意図を示されてるものが表示される方がマシだと思います

よくわからない文字列（翻訳キー）が出るよりかは「未翻訳」などの文字列 or 日本語などへのフォールバックが出たほうがいいのかなと思っただけです（何もださないのはUIを破壊する可能性があるので）

**Comment by samunohito** [comment]
> 日本語などへのフォールバック

こっちのほうがいいと思いました。どのキーを翻訳すべきか定義から探しやすくなると思います。

> など

ベースは日本語の認識なので、日本語へのフォールバックが確実かと
（ベース以外だとフォールバック先まで欠けているリスクもあってしんどい）
