### ISSUE TITLE
`secure: true` なエンドポイントの型が misskey-js に含まれていない

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12598]
### 💡 Summary

#12434 にてバックエンドの生成する api.json から misskey-js の型が作られるようになりましたが、api.json の生成において `secure: true` なエンドポイント（たとえば `i/update-email` など）は省かれているので、このような（一部の？）エンドポイントの型が misskey-js に含まれなくなっています。これらについても misskey-js の型が生成されているべきです。

### 🥰 Expected Behavior

`secure: true` なエンドポイントが misskey-js の型に含まれている

### 🤬 Actual Behavior

`secure: true` なエンドポイント（`i/update-email` など）が misskey-js の型に含まれていない（元々含まれていた？）

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.0-beta.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
非公開APIだけどmisskey-jsに含めない理由はなさそう

**Comment by samunohito** [comment]
非公開APIとなると…

misskey-js → ふくめる
/api-doc（とそこから落とせるapi.json） → ふくめない

みたいな感じですかね？

**Comment by syuilo** [comment]
api-docについても含めても良いんじゃないかしら

**Comment by syuilo** [comment]
非公開という但し書きは必要
