### ISSUE TITLE
[EN/JA] Question about adding dialects / 方言を追加することに関する質問

### ISSUE THREAD

**Issue by GimGaram** [syuilo/Misskey#12595]
Hello.
I saw that there is the Kansai dialect in the languages of Misskey. So, I wonder if it is possible to add some dialects from other languages (e.g. Korean (Gyeongsang dialect) or Japanese Korean).
Now, I have translated about 400 of the strings into the Gyeongsang dialect (ko-gs?) as a trial. And if it can be added, I am going to finish translating the rest of the strings.
Thank you.

こんにちは。
Misskeyの言語の中で関西弁があるのを見ました。もし、他の言語の方言も追加出来るのかを知りたいです。（例：韓国語（慶尚方言）や在日朝鮮語）
現在、慶尚（キョンサン）方言（ko-gs？）は試しに約400個のストリングを翻訳してみましたが、追加出来れば残りの翻訳もしてみようと思います。
ありがとうございます。

안녕하세요.
Misskey의 언어 가운데 간사이 방언을 보았습니다. 혹시 다른 언어의 방언도 추가할 수 있는지 궁금합니다.(예: 한국어(경상방언)나 재일조선어)
현재 경상방언(ko-gs?)은 시험 삼아 스트링 가운데 약 400개를 번역해 보았고 추가할 수 있다면 나머지 번역도 해 보려고 합니다.
감사합니다.

**Comment by GimGaram** [comment]
I forgot to write it, but I already know some people who are interested in the translations.
書き忘れましたが、私はすでにその翻訳に興味深い人を何人か知っています。

**Comment by kakkokari-gtyih** [comment]
Then we can add it to the list 👍

（Off-topic: 方言を許容するとメンテナンスすべき言語の数がとんでもないことになりそうだけどまあいっか）

**Comment by kakkokari-gtyih** [comment]
- Language name: Korean (Gyeongsang)
- The dialect of: Korean
- Locale: ko-gs

かも

**Comment by syuilo** [comment]
done
