### ISSUE TITLE
`/_info_card_` を廃止する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12608]
### Summary

- Misskey Hub Nextでは当該ページを使用せず jm api 経由でデータを取得しているので、**Nextがリリースされ次第**削除していい気がする
- Githubの検索をかけたが、当該ページを利用している他プロダクトは見当たらなかった（あったらコメントまでご連絡ください）

### Purpose

メンテナンスコストの削減

**Comment by syuilo** [comment]
/_info_card_ をサーバーの死活監視に使ってる事例があったような気がしないでもない

**Comment by kakkokari-gtyih** [comment]
そうなんだ

**Comment by kakkokari-gtyih** [comment]
需要があるなら無理に消すこともない
