### ISSUE TITLE
ノートの詳細表示から閲覧できるノート後のノート履歴の順番がおかしい

### ISSUE THREAD

**Issue by Kur0den** [syuilo/Misskey#12625]
### 💡 Summary

ノートの詳細表示からそのあとのノート(上矢印のやつ)を見るとノートの順番が新しいものから表示される

### 🥰 Expected Behavior

そのノート/リノートをした直後の古いノートから表示される
![image](https://github.com/misskey-dev/misskey/assets/69957747/0b7e4cf7-0e12-430f-ad78-6ccfabe4efbe)

### 🤬 Actual Behavior

最新のノートから順に表示される
![image](https://github.com/misskey-dev/misskey/assets/69957747/959300fa-b059-4bd0-b675-fe34852b6ec2)

### 📝 Steps to Reproduce

1. ノートの投稿か既存のノートのリノートを行う
2. そのノートの詳細表示からそのあとのノート(上矢印のやつ)を表示する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: koliosky.com
* Misskey: 2023.12.0-beta.3
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by acid-chicken** [comment]
https://github.com/misskey-dev/misskey/pull/12564#issuecomment-1840982354 で確認していて #12586 で対応されたものと思っていたけど直ってない感じかしら

**Comment by acid-chicken** [comment]
> フロント側で逆順にしている説ないですか…？
> 
> 
> 
> https://github.com/misskey-dev/misskey/blob/406b4bdbe79b5b0b68fcdcb3c4b6e419460a0258/packages/frontend/src/pages/note.vue#L80

このパラメーターはページネーション方向（に伴ってページの結合処理方向）のパラメーターじゃなかったかしら

**Comment by samunohito** [comment]
このフラグはMkPaginationにもわたっているんですが、そちらでは仰る通りの実装になっているように見えます。

ただ…中継地点にあるMkDateSeparatedListの中で以下を付与するフラグにも使用されており、これが悪さしてるんじゃないかなと予想してます
```css
flex-direction: column-reverse
```

**Comment by samunohito** [comment]
issueの現象を起こす→数ノート投稿する→もっと見るを押下した様子。
<img width=70% src="https://github.com/misskey-dev/misskey/assets/46447427/de6e6c43-e4ed-4638-90da-6d07214bc033" />

積み上がり方もおかしいので、リリース後にゆっくり見ます…

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/blob/9784d10c62e294b32cf62b7374bed7ce57a42b9d/packages/backend/src/server/api/endpoints/notes/hybrid-timeline.ts#L179

ここみてsinceIdだけ指定のときもAPIから戻ってくるtimelineは今>過去だと解釈してたのですが逆順なかんじですか？

**Comment by samunohito** [comment]
や、バックエンド側に相違はないと思います。
フロント側の見せ方がちょっとおかしい可能性が大きいです

**Comment by kakkokari-gtyih** [comment]
> このフラグはMkPaginationにもわたっているんですが、そちらでは仰る通りの実装になっているように見えます。
> 
> ただ…中継地点にあるMkDateSeparatedListの中で以下を付与するフラグにも使用されており、これが悪さしてるんじゃないかなと予想してます
> 
> ```css
> flex-direction: column-reverse
> ```
> 
> なんか分からなくなってきた、後で試します

これな気がする（`flex-direction: column`にしたら改善された）

**Comment by syuilo** [comment]
FTT有効時にAPIのレスポンスが期待したものとは逆の順番になることが原因と思われる

**Comment by syuilo** [comment]
sinceIdを指定してリクエストした場合、結果は古いものが先頭に来ることが期待されているけど、FTT有効だとそれとは逆に新しいものが先頭になる
