### ISSUE TITLE
Modlog diff visualize will leak confidential configurations

### ISSUE THREAD

**Issue by Candinya** [syuilo/Misskey#12622]
### 💡 Summary

Modlog (/admin/modlog) has a different visualization, which will include some unrelevant configurations as context. But since it's the full server configuration object, it may include some other configurations. 

Modlog can be accessed by normal moderators, but some admin-only confidential configuration (swPrivateKey, deeplAuthKey) would also be leaked.

### 🥰 Expected Behavior

Should not leak the confidential configurations.

### 🤬 Actual Behavior

![image](https://github.com/misskey-dev/misskey/assets/20502130/a6529db2-ef24-4d93-a913-7f0da3f57ec6)

### 📝 Steps to Reproduce

1. Edit blocked instance list or silence a instance
2. Go to modlog to check moderation logs
3. Check the latest mod logs

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 (22H2 22621.2715)
* Browser: Chrome 119.0.6045.200
* Server URL: https://nya.one/
* Misskey: 2023.11.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker compose
* Misskey: 2023.11.1
* Node: (docker image built-in)
* PostgreSQL: 15.5
* Redis: 7.2.3
* OS and Architecture: Debian 11 amd64
```

**Comment by syuilo** [comment]
モデログ閲覧できるのは管理者だけにするか

**Comment by saschanaz** [comment]
これCVE出さなくて大丈夫でしょうか？
