### ISSUE TITLE
トレンドの非表示ハッシュタグの設定を即時反映するようにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#12635]
### Summary

非表示ハッシュタグの設定にタグを追加しても、トレンドからすぐには消えないようです。
該当部分?: https://github.com/misskey-dev/misskey/blob/7f85d7a1f9b05e1d918dff189ccdfbfa219f2008/packages/backend/src/core/HashtagService.ts#L162

### Purpose

モデレーション等の観点から、追加された対象の非表示もすぐに行われて欲しいです。

関連issue:
https://github.com/misskey-dev/misskey/issues/12591
https://github.com/misskey-dev/misskey/issues/11401

**Comment by anatawa12** [comment]
実装案としてはhiddenTags更新時にZREMするか、`getHashtagsRanking`の`threshold`処理前にフィルタリングするかだけど、`getHashtagsRanking`は呼ばれる回数多くて `hiddenTags` 更新の頻度は高くなさそうだから [ZREM](https://redis.io/commands/zrem/) でいいのかな
