### ISSUE TITLE
ページでも公開範囲を指定出来るように

### ISSUE THREAD

**Issue by sexy9no1** [syuilo/Misskey#12637]
### Summary

ページでもノートのように
「全体公開」
「フォロワー限定公開」
など公開範囲を指定可能にしてほしい
_（一時的な「非公開」も可能にしてほしい）_

### Purpose

昨今では独自機能によりページではMFMではない一般的な形式でのルビ振りが可能となっているサーバーも存在する
そのためカクヨム・なろう作家や字書きの同人作家（二次創作・特に女性向け）には潜在的ニーズが高いと思われるが
現状の仕様ではフォロワー限定で公開したいテキストの発表は**外部サイトの併用が必須**
しかし公開範囲の選択が可能になればMisskey一本で執筆・発表→反応から交流を深めることも、宣伝→新たなフォロワー獲得も、全てを済ますことが可能

**ミス廃が進む**

**Comment by acid-chicken** [comment]
Duplicate of #6948

**Comment by t1nyb0x** [comment]
Issue1本化のため、クローズします。

今後確認の際は、#6948 でお願いします。
