### ISSUE TITLE
pnpm devからbuildの処理が消えている？

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12632]
### 💡 Summary

pnpm dev しても pnpm build と同じ効果が得られず、watch するのみになっている？

### 🥰 Expected Behavior

pnpm devを行うとまずTypeScriptのビルドやlocaleファイルのビルドが行われ、そのあとにファイルの監視やサーバーの起動が行われる

### 🤬 Actual Behavior

pnpm devを行うとファイルの監視やサーバーの起動のみ行われているように見える

### 📝 Steps to Reproduce

1. pnpm clean する
2. pnpm dev する
3. エラーになる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
具体的に困るシチュエーションとしては、ブランチの切り替え時
開発中はPRのレビューなどのため頻繁にブランチを切り替えることがあるけど、pnpm devだけではビルドされず前のブランチの内容が残っているため切り替える度にいったん pnpm build してから pnpm dev しなければらなず面倒

**Comment by fruitriin** [comment]
BEなら entry.jsを起動するだけになってるからたぶんそう
https://github.com/misskey-dev/misskey/blob/7f85d7a1f9b05e1d918dff189ccdfbfa219f2008/packages/backend/package.json#L19

ts-node src/boot/entry.ts 
とかできないかなーちょっとためしてない

**Comment by fruitriin** [comment]
この前のビルドチェーンの変更で dev.mjsを使わないようになってるので、この内容がいい感じに移植されるとよい
https://github.com/misskey-dev/misskey/blob/develop/scripts/dev.mjs

**Comment by samunohito** [comment]
バックエンドのpnpm devの動きとしては、リンさんが書いてくれた通りで…
サーバの再起動については、もともとその仕組み自体がなかったように思えます。

**Comment by syuilo** [comment]
再起動？

**Comment by fruitriin** [comment]
ちょっと近くバックエンドのビルドチェーン直します
1日ほど待ってほしい

**Comment by samunohito** [comment]
> 再起動？

空目でした
なんでもないです

**Comment by syuilo** [comment]
off topic?
2023.12.0-beta.3 で pnpm build したのになぜか ja-JP.2023.12.0-beta.2.json を読みに行こうとして怒られるようになった
![image](https://github.com/misskey-dev/misskey/assets/4439005/54bb98c2-5db5-4669-8f71-e586a562a189)

![image](https://github.com/misskey-dev/misskey/assets/4439005/21067a08-8052-43c6-8796-2c13847e92f5)
sw.jsが更新されてなさそう

**Comment by syuilo** [comment]
pnpm cleanしたけど効果なかった
tasukete

**Comment by syuilo** [comment]
もちろんChrome側でDisable cacheしてるし謎

**Comment by samunohito** [comment]
sw.jsのその部分は…

sw.js　→　vite.config.tsで作られてる定数　→　プロジェクトルートのpackage.json

みたいな感じで参照されてるので、pnpm devを起動しなおせば直ったりしませんか？

**Comment by syuilo** [comment]
pnpm cleanしてもpnpm buildしてもpnpm devしても直らないですね...

**Comment by samunohito** [comment]
oh...

**Comment by fruitriin** [comment]
急ぎたい気配を感じたのでいまからなおす

**Comment by syuilo** [comment]
あれ、devモード時ってローカリゼーションの読み込み処理どこで行われてる？

**Comment by syuilo** [comment]
backend\src\server\web\boot.js の await window.fetch(`/assets/locales/${lang}.${v}.json`); に相当する処理がdevモードでは無いように見える

**Comment by syuilo** [comment]
クライアント起動より前にローカリゼーションの読み込みが行われないから config.ts の `miLocalStorage.getItem('locale');`でnullが返ってきてしまっている

**Comment by samunohito** [comment]
@syuilo 
いろいろ直してみたんですけど、どうでしょう…
sw.jsもpackage.jsonを監視して再生成しなおすようにしてるので、もしかしたら直るかも…
