### ISSUE TITLE
リアクション・ノートへの返信・フォローができないユーザーがいる

### ISSUE THREAD

**Issue by Yuliy-JM** [syuilo/Misskey#12644]
### 💡 Summary

表題の通り、こちらからノートが見えているのにも関わらず、リアクションやノートへの返信、フォローができないユーザーがいます。

### 🥰 Expected Behavior

リアクション、返信、フォローを通常通り行える
あるいはノートやユーザーページなどを閲覧できない

### 🤬 Actual Behavior

リアクション、返信、フォローを行えない
また、それにも関わらずノートやユーザーのページを閲覧することができる

### 📝 Steps to Reproduce

1.該当するユーザーのノートで絵文字一覧を開き、絵文字を選択するが反映されないことを確認
また、既についているリアクションも反応せず
2.該当するユーザーのページに行き、フォローボタンを押すが正常にフォローができないことを確認
3.該当するユーザーのノートにて返信のマークをクリックする。「返信」ボタンを押すが"You have been blocked by this user.
b390d7e1-8a5e-46ed-b625-06271cafd3d3"とのメッセージが出る。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Android 10 / Windows11 PC
* Browser:Brave 1.61.100/FireFox 120.1.0
* Server URL:misskey.io
* Misskey:2023.11.1 (おそらく
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
ブロックされているとリアクション・ノートへの返信・フォローはできなくなります

**Comment by Yuliy-JM** [comment]
ブロックされている場合、該当するユーザーのコンテンツが見えなくなると思っていましたが、これは認識違いでしょうか？

**Comment by syuilo** [comment]
コンテンツが見れなくなる場合もありますが、ブロックの基本的な働きとしてはそのようなアクションが行えなくなるものになります

**Comment by Yuliy-JM** [comment]
承知しました。本件はクローズとさせていただきます、ありがとうございました
