### ISSUE TITLE
検索画面においてEnterキー押下で検索できるように

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12664]
### Summary

`/search` や `/channels/${channel.id}` の「検索」タブでは「検索」ボタンを押すことで検索できる仕様となっていますが、このボタンを押さずとも入力欄内での Enter キー押下で検索できるようにしたいです。

### Purpose

ボタンを押す手間を減らすため

**Comment by k0range** [comment]
Pull Requestを作ってみました。#12752
