### ISSUE TITLE
絵文字ピッカー設定画面のレイアウト・文言改善提案

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12669]
### Summary

ベータ版を適用したサーバのユーザから、文言とレイアウトについてのフィードバックを受けました。
- 登場する単語の名称が統一されているほうが分かりやすい
- 「コピーする」よりも「上書きする」のほうが分かりやすい
- コピーボタンは破壊的変更を伴うのでレイアウトを隔離したほうが事故率が減る
- 危険な操作であることをボタンの見た目で分かるようにしたほうが事故率が減る

フィードバックを受けて仮組したレイアウトがこちら↓
※事故ってピン留め（リアクション）側の絵文字を吹き飛ばしてしまったユーザ数人からも、これなら良さそうとのFBあり

![image](https://github.com/misskey-dev/misskey/assets/46447427/280a47da-215b-4eb8-a363-3002c81804ac)

### Purpose

誤ってピン留め設定を上書きしてしまうユーザが減る

**Comment by samunohito** [comment]
↑でよさそうなら、実装は自分がやります。
マージされたらCrowdinの更新も（外国語ほんとうにダメなのでDeepLの結果をコピペするだけになりそうですが）

**Comment by syuilo** [comment]
添付されたイメージを見た感じでは過剰に感じますね👀
コピーという表現を上書きに変更するだけで良さそうに思いました

> 危険な操作であることをボタンの見た目で分かるようにしたほうが事故率が減る

これはすでにMisskeyのデザイン言語として danger タイプのボタンで表現されてるので、それよりさらに区分を追加する必要性は今のところ薄そう

> コピーボタンは破壊的変更を伴うのでレイアウトを隔離したほうが事故率が減る

これはデフォルトに戻すボタンも該当しそう

あと「(確認ダイアログがあったとしても)間違って望まない操作を行なってしまう」というのはこの操作に限らずあるので、ボタン長押ししないと実行できないUIとかも考えていて、実装されたらそれ使うようにするとか

**Comment by samunohito** [comment]
> Misskeyのデザイン言語として danger タイプのボタンで表現されてる

dangerとprimaryを両方適用したらこの表示になったので、想定されていたものだと思っていました…（CSSもそうなってたし）

> ボタン長押ししないと実行できないUI

これは…ついでに作って、デフォルトに戻すボタンのほうでも使うようにしますか。

**Comment by samunohito** [comment]
ダイアログの文言を添付し忘れてました

![image](https://github.com/misskey-dev/misskey/assets/46447427/15218734-5aec-4986-a8db-4ea23f4cdbee)

**Comment by syuilo** [comment]
> dangerとprimaryを両方適用したらこの表示になったので、想定されていたものだと思っていました…（CSSもそうなってたし）

あーー
これは昔の名残かしら 今はどこでも使ってなさそう

**Comment by acid-chicken** [comment]
「からコピー」って多分逆の「へコピー」であるべきで、今たまたま 2 つあるために主副が 1:1 になっているものの、たとえば項目が 3, 4 と増えていったとき、前者の場合項目分ボタンを並べていかないといけないが、後者は一括動作を表すなら常に 1 つであり続けるため、おそらく後者が自然

**Comment by samunohito** [comment]
たしかに

**Comment by samunohito** [comment]
@syuilo 
まずは最低限の対応として、ボタンの文言だけ変更してみました。
違和感なさそうであれば、いったんプルリクをつくろうとおもいます

コピー　→　上書き
絵文字設定　→　全般設定（名前をそろえた）
![image](https://github.com/misskey-dev/misskey/assets/46447427/06bbb38f-592f-4d21-967a-3e8c6251f70a)

**Comment by syuilo** [comment]
👍
