### ISSUE TITLE
Unicode 15.0 の絵文字のサポート

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12673]
### Summary

twemoji の取得に使われている [`@discordapp/twemoji`](https://www.npmjs.com/package/@discordapp/twemoji) が2週間ほど前に Unicode 15.0 対応のバージョンをリリースしたので、これをサポートすることを提案します。

### Purpose

新しく追加された絵文字[^1]をリアクションに使う需要が考えられるため

[^1]: https://www.unicode.org/emoji/charts-15.0/emoji-released.html

**Comment by zyoshoka** [comment]
リアクションについてはこのリポジトリで解決できるとして、ノートの方に関しては mfm.js のパースを修正する必要がありそうですね

**Comment by syuilo** [comment]
v2023.12.0に入れたいわね

**Comment by syuilo** [comment]
mfm-js更新した
