### ISSUE TITLE
タイムラインの設定に「センシティブな投稿を非表示」のオプションが欲しい

### ISSUE THREAD

**Issue by ikakonbu** [syuilo/Misskey#12691]
### Summary

タイムライン右上の表示設定に「センシティブなメディアのあるノートを非表示」のオプションが欲しい
<img width="273" alt="image" src="https://github.com/misskey-dev/misskey/assets/82440954/2ca1f4ab-ae9c-4951-842b-f63ca6084a97">

### Purpose

・外で閲覧する際に、誤爆タッチの恐れがあるので投稿ごと非表示にしたい
・見たくないセンシティブ投稿でTLを圧迫したくない

**Comment by kakkokari-gtyih** [comment]
プラグインで制御できなくはないけどデフォルトで持たせておくのもいいかも

ただそのときは完全非表示ではなくワードミュートと同様の表示（〜さんがなにか言いました）にしたほうが、万一見たいときに展開できていい気がする

**Comment by samunohito** [comment]
本体の機能として持たせることについては賛成です。
…が、

> 〜さんがなにか言いました

専用文言を別途用意したほうがいいように思えます。「センシティブな投稿が非表示にされました」みたいなイメージです。
ワードミュートと見分けがつかないので、万一見たいときにしんどいかなと

**Comment by ikakonbu** [comment]
ワードミュートなどと同様に非表示にしたことを明示するのは考えていませんでしたが、確かにそうする方が良さそうですね
