### ISSUE TITLE
画像だけの引用が引用として通知されずRenoteとして通知される

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#12700]
### 💡 Summary

画像だけ(添付ファイルのみ)の引用が引用(quote)として通知されない (renoteとして表示される)

### 🥰 Expected Behavior

画像だけの引用でも引用(quote)として

### 🤬 Actual Behavior

renoteとして表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: p1.a9z.dev
* Misskey: 2023.12.0-beta.5-p1.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2023.12.0-beta.5-p1.1
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by kakkokari-gtyih** [comment]
`text == ''` でリノート判定してる…？

**Comment by 1STEP621** [comment]
Duplicate of #11222 ？

**Comment by tamaina** [comment]
なるほど
