### ISSUE TITLE
CWの中に画像を添付した場合、その画像が見られないことがある

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#12719]
### 💡 Summary

「画像が1枚のみのメディアリストの高さ」を「デフォルト」以外に設定していると、CWの中に添付された画像が見られないことがあります。

### 🥰 Expected Behavior

画像が見られる

### 🤬 Actual Behavior

画像が見られない

### 📝 Steps to Reproduce

1. 「画像が1枚のみのメディアリストの高さ」を「デフォルト」以外に設定する
2. CWの中に画像が添付されているノートを閲覧する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Ubuntu 22.04.3 LTS
* Browser: Firefox 120.0.1
* Server URL: ローカル環境, misskey.backspace.fm, misskey.systemsで再現
* Misskey: 2023.12.0-beta.5
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by 1STEP621** [comment]
https://github.com/misskey-dev/misskey/blob/21882b69ec6f093ce76e02c751927eeb6de08e0c/packages/frontend/src/components/MkMediaList.vue#L113
ここで`display: none;`のものに対してclientWidthを得ようとして0が返ってきている気がする
