### ISSUE TITLE
ロールアサインの通知がある状態でページをリロードすると通知欄に何もでなくなる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12729]
### 💡 Summary

ロールアサインの通知が来た直後は平気ですが、その状態からリロードすると以下のようなエラーが出て通知一覧が出なくなります。
![image](https://github.com/misskey-dev/misskey/assets/46447427/caae3a57-7282-4a0c-8472-74a218fb2d07)

### 🥰 Expected Behavior

リロードしても正常に通知一覧が表示されること

### 🤬 Actual Behavior

通知一覧が出ない

### 📝 Steps to Reproduce

1. ロールアサインの通知を受け取る
2. リロードする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: any
* Misskey: develop(15b0d2a)
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

**Comment by syuilo** [comment]
謎

**Comment by samunohito** [comment]
ロールに画像URLを設定してるんですけど、その画像URLがなさそう？
![image](https://github.com/misskey-dev/misskey/assets/46447427/9c01dd9a-ad83-4595-a2bf-a78bd64cace1)

**Comment by syuilo** [comment]
role自体が入ってないわね
コード見てもちゃんとrole入るように思えるんだけど

**Comment by samunohito** [comment]
notificationsのほうは発生せず
![image](https://github.com/misskey-dev/misskey/assets/46447427/c5b996b3-0359-41f5-9754-61e15f742f18)

**Comment by syuilo** [comment]
あーーーーーーーーー

**Comment by syuilo** [comment]
🙏🏻
