### ISSUE TITLE
`ap/show`に存在しないノートのURLやActivityPubでないURLを投げると500が返ってくる

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12736]
### 💡 Summary

`ap/show` に対して、存在しないノートの URL や ActivityPub でない URL を `uri` に指定してリクエストを送信すると `INTERNAL_ERROR` が返ってきます。しかし本来はここで `NO_SUCH_OBJECT` エラーが返ってくるべきです。

Related to: https://github.com/misskey-dev/misskey/pull/3704, https://github.com/misskey-dev/misskey/issues/10839#issuecomment-1547498540

### 🥰 Expected Behavior

`NO_SUCH_OBJECT` エラーが返ってくる

### 🤬 Actual Behavior

`INTERNAL_ERROR` が返ってくる

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.0-beta.6
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by GrapeApple0** [comment]
ここでエラーハンドリングをしてNO_SUCH_OBJECTを返してあげるのが適切ですかね?
https://github.com/misskey-dev/misskey/blob/7ca0af9e7e2a325171d2f26414165078af5d5249/packages/backend/src/core/activitypub/ApResolverService.ts#L106-L108

**Comment by GrapeApple0** [comment]
でもNO_SUCH_OBJECTではなくINVAILD_OBJECTを返すべきな気もします

**Comment by zyoshoka** [comment]
もうこの行で `catch` して `NO_SUCH_OBJECT` を返すようにしちゃってよいと思います（あと API の仕様変えてまで `INVAILD_OBJECT` を返すようにするモチベーションは薄そうです）

https://github.com/misskey-dev/misskey/blob/7ca0af9e7e2a325171d2f26414165078af5d5249/packages/backend/src/server/api/endpoints/ap/show.ts#L101
