### ISSUE TITLE
Latest Tor Browser not working properly with latest Misskey

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#12737]
### 💡 Summary

Latest Tor Browser not working properly with latest Misskey

### 🥰 Expected Behavior

It's working like it used to

### 🤬 Actual Behavior

![image](https://github.com/misskey-dev/misskey/assets/62551256/f7fb745a-0b5e-4786-a48a-5a85e1d4d18b)
(misskey.io)

### 📝 Steps to Reproduce

1. Open the latest version of Tor Browser
2. Visit misskey.io

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Debian 12.4
* Browser: Tor Browser 13.0.8 (Firefox 115.6.0esr)
* Server URL: misskey.io
* Misskey: 2023.11.1
```

**Comment by KisaragiEffective** [comment]
triage: assuming #12776 is best thing that Misskey can done. Please re-open if there's more.
