### ISSUE TITLE
[2023.12.0-beta.6] 引用RNが引用RNとして処理されていない？

### ISSUE THREAD

**Issue by 1673beta** [syuilo/Misskey#12739]
### 💡 Summary

2023.12.0-beta.6のサーバーから2023.11.1以前のバージョンのサーバーの投稿を引用RNすると、引用RNではなくRNとして扱われている挙動を取っている。

### 🥰 Expected Behavior

![image](https://github.com/misskey-dev/misskey/assets/60435625/9fb29ea1-0186-4c63-8387-431efc7397dc)
引用RNが引用RNとして表示される

### 🤬 Actual Behavior

引用RNをしたのにも関わらずRNとして扱われる
1枚目: 2023.11.1環境から　https://kasei.ski/notes/9nj25xsydi
2枚目: 2023.12.0-beta.6環境から　https://koliosky.com/notes/9nj26568i9
3枚目: v11系のサーバーから

![image](https://github.com/misskey-dev/misskey/assets/60435625/32c5dfe4-f0c5-430a-932c-e1cf46757956)
![image](https://github.com/misskey-dev/misskey/assets/60435625/edfb2e95-0762-483d-ac14-17755ba85c67)
![image](https://github.com/misskey-dev/misskey/assets/60435625/3ccb5314-afc1-46e5-8e31-96c12bb38dd8)

### 📝 Steps to Reproduce

1. 2023,11,1以前のバージョンを使用しているサーバーから投稿する
2. 2023.12.0-beta.6の環境から引用する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: koliosky.com, kasei.ski, gc-key.幼女.life, misskey.systems
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.0-beta.6
* Node: 20.10.0
* PostgreSQL: 16
* Redis: 7.2.3
* OS and Architecture: Ubuntu 22.04 LTS
```

**Comment by samunohito** [comment]
2023.12.0-beta.6系サーバと2023.11.1系サーバで試してきました。
仰る通り、本来はタイムラインと通知欄に引用リノート形式でノートが表示されるのが正解ですが、動きを見るとどちらもリノートとして表示されてしまいますね。
逆のパターンの時はしっかりと引用リノートとして扱われていました。タイムライン、通知欄ともに引用リノートの内容が表示されています。

以下、試したときの内容です。
それぞれのサーバにある自分のアカウントを相互フォロー状態にして、お互いのノートを自分のタイムラインで確認できる状態にしています。

①12.0-beta.6から11.1のノートをリノートした時の12.0-beta.6側ノート
<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/967dfc81-7e81-4608-a125-3999541f5edd" />

②①のノートを受信した11.1側ノート
<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/dfd2276f-5f47-481c-a7ee-916b5a2c2560" />

受信したノートのオブジェクトにあるはずの本文が抜け落ちているように見えます。
なので…アタリをつけるとしたら連合周辺だと思いました

**Comment by samunohito** [comment]
左：リノートのオブジェクトがあり、かつ本文がなく、かつアンケートでもなく、かつファイルもない
右：リノートのオブジェクトがあり、または（本文があり、またはCWがあり、またはファイルがあり、またはアンケートである）

（寝起きなんでボケてたらごめんなさい）
