### ISSUE TITLE
[2023.12.0-beta.6] RNの通知が正常ではない?

### ISSUE THREAD

**Issue by 1673beta** [syuilo/Misskey#12742]
### 💡 Summary

RNされた際の通知がAcutual Behaviorの画像のようになる。

### 🥰 Expected Behavior

画像のようになる
![image](https://github.com/misskey-dev/misskey/assets/60435625/782cdd4f-56d7-44af-a060-9066f2acb0e5)

### 🤬 Actual Behavior

こうなる
![image](https://github.com/misskey-dev/misskey/assets/60435625/610cca7a-8803-440d-8de5-0b412593f4ef)

### 📝 Steps to Reproduce

1. 2023.12.0-beta.6環境でRNされる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: koliosky.com, WSL上に建てた検証環境
* Misskey: 2023.12.0-beta.6
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2023.12.0-beta.6
* Node: 20.10.0
* PostgreSQL: 16
* Redis: 7.2.3
* OS and Architecture:
```

**Comment by 1STEP621** [comment]
#12744 で修正されていそうです🙏

**Comment by samunohito** [comment]
> RNされた際の通知がAcutual Behaviorの画像のようになる

リモートのノートをリノートした時…でしょうか？
であれば、12744で改善されていそうです

**Comment by 1STEP621** [comment]
ローカル→ローカルへのRNでも起こるバグだったかと思いますが、12744でisQuoteの判定も修正されたことで同時に直ったと思われます
https://github.com/misskey-dev/misskey/commit/2fb94b79148403a007661289ded4e129a29ac6e3

**Comment by 1673beta** [comment]
返信おw暮れて申し訳ございません。修正で直ったのを確認したので閉じます。

**Comment by 1673beta** [comment]
対応ありがとうございました。
