### ISSUE TITLE
Alternative to verifymail.io

### ISSUE THREAD

**Issue by Mar0xy** [syuilo/Misskey#12741]
### Summary

Verifymail is a very expensive service and I think it would be best to also offer another service as an alternative

https://debounce.io/free-disposable-check-api/
https://disposable.debounce.io/?email=test@mailinator.com

Proper API Docs: https://developers.debounce.io/reference/disposable-email-detector

### Purpose

Debounce offers a free API for disposable email checking so if instance admins don't want to go and spend time figuring out a ton of disposable email domains to block as per PR https://github.com/misskey-dev/misskey/pull/12740 they can use this as a fallback

**Comment by Mar0xy** [comment]
As this endpoint also doesn't need an API Key it could easily be made into a simple toggle in the moderation tab or email tab

**Comment by u1-liquid** [comment]
I may be overstepping, but I'd like to voice my opposition in advance to any consideration of *'**completely replacing**'* the verification feature of `verifymail.io`. (However, I am in favor of incorporating `disposable.debounce.io` as an additional method for email address verification.)

After testing with a few disposable domains, I have found that the accuracy and scale of `disposable.debounce.io`'s database does not seem superior to that of `verifymail.io`. The absence of public criteria for determining disposable addresses, along with the lack of information beyond the disposable status of an address, leads me to consider it as a potential low-cost option, but not as a sufficient replacement.

Considering medium to large servers that require email address verification, the personnel costs associated with managing emerging spam accounts using disposable email addresses could exceed `verifymail.io`'s monthly fee of $25. Therefore, I do not deem this price to be overly expensive.

Relying solely on `disposable.debounce.io` for email address verification could result in only partially blocking disposable email addresses, which may ultimately prove ineffective in combating the creation of spam accounts.

**Comment by Mar0xy** [comment]
Well I never talked about replacing it I just said alternative.

> Considering medium to large servers that require email address verification, the personnel costs associated with managing emerging spam accounts using disposable email addresses could exceed verifymail.io's monthly fee of $25. Therefore, I do not deem this price to be overly expensive.

I have already ran into some people that find that price too much for essentially what debounce.io does for free even if it is a bit worse.

**Comment by Insert5StarName** [comment]
> Considering medium to large servers that require email address verification, the personnel costs associated with managing emerging spam accounts using disposable email addresses could exceed `verifymail.io`'s monthly fee of $25. Therefore, I do not deem this price to be overly expensive.

considering that most fediverse instances have from 10-2000 users 25$ or 50$ is way to much that is more than like 40% of instances pay monthly for their servers

**Comment by u1-liquid** [comment]
> Well I never talked about replacing it I just said alternative (this can quite frankly also be taking as another option besides the already existing one)

I understand that this issue is not intended to 'completely replace' the existing feature, but in Misskey, when similar functionalities are present, often only one is retained and the original feature gets removed. That's why I wanted to write in advance that such a replacement should not be done.

> useful features only get unlocked at $50 per month on verifymail.io plans.

Misskey already implements MX record verification through [deep-email-validator](https://www.npmjs.com/package/deep-email-validator), so there is no need to use the $50 plan unless additional API slots are required. Please refer to the following code for guidance: 
https://github.com/misskey-dev/misskey/blob/52b94dbc4ab60aa6efba927ef8df509a3bb0d046/packages/backend/src/core/EmailService.ts#L174-L181

> a lot of moderators on a lot of instances are not paid

Even if it's volunteer work, it doesn't mean that the effort is valueless. Please consider this as a matter of opportunity cost.

**Comment by u1-liquid** [comment]
> instances have from 10-2000 users 25$ or 50$ is way to much that is more than like 40% of instances pay monthly for their servers

I don't believe that this feature is essential for the operation of Misskey, especially for instances of that scale.  
It's possible to query email addresses for free on the [web](https://verifymail.io/email/test@gmail.com) without needing to contract with `verifymail.io`'s API.

**Comment by Mar0xy** [comment]
Since https://github.com/misskey-dev/misskey/pull/12850 was added and the package misskey uses makes use of a free disposable API I will close this as the alternative provided in that PR is good enough.
