### ISSUE TITLE
Misskey fails to build on Alpine Linux 3.19

### ISSUE THREAD

**Issue by Dactylic-hexameter** [syuilo/Misskey#12750]
### 💡 Summary

On a fresh install of Alpine Linux v3.19, building Misskey 2023.11.1 (and earlier versions up to 2023.10.1) fails because an old version of sharp (v0.31.3) is being used by a package. This issue did not occur on Alpine Linux v3.18.

This issue is probably due to Alpine Linux changing how version strings are handled: https://github.com/lovell/sharp/issues/3641

### 🥰 Expected Behavior

Misskey should successfully build.

### 🤬 Actual Behavior

Misskey fails when installing a specific version of sharp.
```
~/misskey $ NODE_ENV=production pnpm install --frozen-lockfile 
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1194
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1194, reused 1194, downloaded 0, added 0, done
node_modules/.pnpm/sharp@0.32.6/node_modules/sharp: Running install script...
node_modules/.pnpm/sharp@0.31.3/node_modules/sharp: Running install script, failed in 997ms
.../sharp@0.31.3/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
│ sharp: Installation error: Invalid Version: 1.2.4_git20230717
│ sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
└─ Failed in 998ms at /var/www/misskey/misskey/node_modules/.pnpm/sharp@0.31.3/node_modules/sharp
 ELIFECYCLE  Command failed with exit code 1.
```
v1.2.4 is the latest musl libc version.

### 📝 Steps to Reproduce

1. Install Alpine Linux v3.19
2. Follow the steps on https://misskey-hub.net to install misskey, up to `NODE_ENV=production pnpm install --frozen-lockfile`

### 💻 Frontend Environment

```markdown
N/A (server problem)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Direct installation from git
* Misskey: 2023.11.1
* Node: 21.4.0
* PostgreSQL: N/A
* Redis: N/A
* OS and Architecture: Alpine Linux v3.19, linux-virt on VPS, x86_64
```

**Comment by Dactylic-hexameter** [comment]
Misskey builds successfully on Alpine Linux v3.19 by bumping the sharp version in sharp-read-bmp (https://github.com/misskey-dev/sharp-read-bmp/pull/2), pointing package.json to a local repository, and running `NODE_ENV=production pnpm install` (without `--frozen-lockfile`).

**Comment by zyoshoka** [comment]
Fixed by https://github.com/misskey-dev/sharp-read-bmp/pull/2
