### ISSUE TITLE
連合一覧等のページネーションが壊れている

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#12766]
### 💡 Summary

<video src="https://github.com/misskey-dev/misskey/assets/86859447/a1ef9211-ef24-489c-ae81-f3102c7d8949"></video>
連合一覧をスクロールしたときのページネーションが壊れています。
#11355 と同様の現象が再発していそうです。

### 🥰 Expected Behavior

正しく読み込まれ、スクロールできる

### 🤬 Actual Behavior

スクロールできない

### 📝 Steps to Reproduce

1. サーバーの連合一覧ページを開く(/about#federation)
2. スクロールする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Ubuntu 22.04.3 LTS
* Browser: Firefox 121.0 (64bit)
* Server URL: misskey.systems
* Misskey: 2023.12.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by Cnly** [comment]
This also happens on 2023.12.2, but the problem seems to disappear if the page is opened in a window.

**Comment by k0range** [comment]
コントロールパネルの絵文字一覧でも同等の現象が発生するようです。

**Comment by Sayamame-beans** [comment]
triage: 全画面表示にしている時だけ起こったりするので、表示されている幅が影響している?
私の環境においては、絵文字一覧では弱めに発生している(一瞬戻されるが進むことも出来る。表示量がギリギリページネーションが必要な程度の少なさだと進めない可能性あり?)
また、コントロールパネルのユーザー情報内の、ドライブのファイル一覧では強めに発生する(稀に進めることがある)

**Comment by Sayamame-beans** [comment]
related: #11449
