### ISSUE TITLE
Starting Misskey via "systemd" no longer works

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#12762]
### 💡 Summary

I have updated my Misskey instance to version **2023.12.0.**
Unfortunately, starting via `systemd` no longer works. 

`NODE_ENV=production pnpm run start` directly from the Misskey directory works fine.

### 🥰 Expected Behavior

Misskey should start with systemd script:

```
[Unit]
Description=Misskey daemon

[Service]
Type=simple
User=misskey
ExecStart=/usr/bin/npm start
WorkingDirectory=/home/misskey/misskey
Environment="NODE_ENV=production"
TimeoutSec=60
StandardOutput=journal
StandardError=journal
SyslogIdentifier=misskey
Restart=always

[Install]
WantedBy=multi-user.target
```

### 🤬 Actual Behavior

Misskey doesn't start

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Git
* Misskey:2023.12.0
* Node: v20.10.0
* PostgreSQL: 16.1
* Redis_version:7.2.3
* OS and Architecture: Debian 11
```

**Comment by fruitriin** [comment]
realy systemd run v20.10.0 nodejs?

I need to install nodejs into /usr/local/bin for run from systemd

**Comment by samunohito** [comment]
If you can post an error log of the problem that can be retrieved with "journalctl -xe", it will make it easier for us to help.

**Comment by memo-567** [comment]
@fruitriin 

I did, but for the Misskey user only. 

Installed node 20.10.0 systemwide and everything works perfect again.

Thanks for your hint 😀

**Comment by fruitriin** [comment]
woot!
