### ISSUE TITLE
CI: Changelogの編集対象をマージ前に確認する

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12772]
リリースをまたいだプルリクをマージするときに古いリリース部分にchangelogを追加してしまってるのを気づかずにリリースしちゃってる事例がまぁまぁ(メジャーのたびに一回くらいづつ)あるので何かしらチェックを入れられると良さそうと思いました。

**Comment by samunohito** [comment]
ディレクトリ切って、そのなかにリリースごとのファイルを作るとか…？

**Comment by syuilo** [comment]
YOSASOU

**Comment by syuilo** [comment]
あー待てよ

**Comment by anatawa12** [comment]
普通にCIでdiff見るでもいい気はする。
リリース時に結合とかバージョン名にリネームという手もあるけど

**Comment by syuilo** [comment]
それやったとしても

> リリースをまたいだプルリクをマージするときに古いリリース部分にchangelogを追加してしま

は解決できないわね

**Comment by samunohito** [comment]
想定とは違うファイルに変更が入るので目が届きやすくなるかな？と思ったりしてました
根本的にやるなら、もうCIパワーでどうにかするしかなさそうですね…

**Comment by tamaina** [comment]
Related to #12807 ?
