### ISSUE TITLE
MFM要素の追加ボタンをノート投稿ウインドウに追加したい

### ISSUE THREAD

**Issue by YAVIIGI** [syuilo/Misskey#12787]
### Summary

ノート投稿ウインドウにMFM要素(jump, jelly, rainbow, など)の一覧を出すボタンを追加して`:`の入力してオートアクションせずに使えるようにしたい

### Purpose

普段使用している中で後から選択範囲を囲むようにMFM要素を追加したい場面が多々あるのですが、その際に`:`の後に出てくる自動補完を使うと最後の`]`を移動したりする必要が出てきたり特にスマートフォンユーザーは手間がかかってしまうように思います。
e.g., `:hoge:` を rainbow で囲いたいときに `$[rainbow ]:hoge:` と保管されてしまう

そのため、MFM要素を追加するボタンを投稿ウインドウに追加して、選択範囲の文字列を囲むようにMFM要素を加えられるようにしたいです。

**Comment by YAVIIGI** [comment]
この後PR提出します

**Comment by kakkokari-gtyih** [comment]
Done in #12788
