### ISSUE TITLE
`ApiServerService.ts`に直接書かれているエンドポイントの情報が`api.json`に含まれていない

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12796]
### 💡 Summary

[`/packages/backend/src/server/api/ApiServerService.ts`](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/ApiServerService.ts) に直接書かれているエンドポイントの情報が `api.json` に含まれていません。

対象となるエンドポイント：
- `signup`
- `signin`
- `signup-pending`
- `v1/instance/peers`
- `miauth/:session/check`

### 🥰 Expected Behavior

これらのエンドポイントの情報が `api.json` に含まれており、ひいては `misskey-js` にも含まれている

### 🤬 Actual Behavior

これらのエンドポイントの情報が `api.json` に含まれておらず、`misskey-js` にも含まれていない

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.0
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

**Comment by syuilo** [comment]
それらは他のAPIと性質が異なるから仕様だわね

**Comment by samunohito** [comment]
- signup
アカウント作成
- signin
パスワード認証
- signup-pending
アカウント作成（emailに埋め込まれたURL経由）
- v1/instance/peers
Mastdon互換API
- miauth/:session/check
miauthのトークン取得時に使用

…みたいな感じなので、`miauth/:session/check` 以外はmisskey-jsに載せる必要は無いと考えます。

**Comment by samunohito** [comment]
oh..

**Comment by samunohito** [comment]
> miauth/:session/check

これはサードパーティアプリからも叩きたいのでは…と思ったんですが

**Comment by samunohito** [comment]
@syuilo 
> miauth/:session/check

これはサードパーティアプリからも叩きたいのでは…と思いましたが、載せない感じです？

**Comment by syuilo** [comment]
載せたい

**Comment by syuilo** [comment]
ただ非推奨だから載せるように改修するほどではなさそうだわね

**Comment by samunohito** [comment]
> signup
> signin
> signup-pending
> v1/instance/peers

これらについても同様です？

**Comment by syuilo** [comment]
そうね

**Comment by zyoshoka** [comment]
フロントエンドで `signup` や `signin` にリクエストしている部分が複数あって、そこらでエンドポイントが存在しないと怒られているのが何か微妙だなという気持ちがあるんですが、いかがでしょうか？

（実際 https://github.com/misskey-dev/misskey/commit/336416261a0a9f46467f90e93854d81ca01292d9 より前は `signup` だけは存在していました）

https://github.com/misskey-dev/misskey/blob/864827f788cd1671a4db2ebc159c1c8ab031b7ad/packages/misskey-js/src/api.types.ts#L575-L588

**Comment by samunohito** [comment]
- このissueで取り上げられたエンドポイントと同様、管理画面等の`secure: true`なエンドポイントも内部向けの位置づけだが、前者はapi.jsonに載せる必要は薄い（性質上、サードパーティアプリから使用するようなものではない）
- api.jsonに載っていないというよりも、フロント側で型エラーになっているのを直したい（上記書き込みより）

…なので、api.jsonの生成ロジックやスキーマ定義に手を入れるよりも、`packages/misskey-js/src/api.types.ts`を以下のように直せば最小限の規模で抑えつつ型エラーを修正できると思いました。

<img width=50% src="https://github.com/misskey-dev/misskey/assets/46447427/1890ccb6-26db-43b5-826c-35513e3cb096" />
