### ISSUE TITLE
リリース運用の再考

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#12807]
### Summary

文章力が限界なので考えてることを箇条書きします

- 機能が壊れているなど急を要する場合は即時リリースが出来るような感じにしたい（master -> hotfixブランチ -> masterみたいな）
- リリースの規模を小さくしたい（大規模な修正が1件、小規模な修正が数件くらいのサイズ）
- 小さくした分、少しリリース間隔を狭めたい（だいたい1週間前後目安で）

なぜこんなことを考えたかというと、

- リリース時の負荷が高い（確認作業など）
- betaを長くとっても網羅しきれない（意識して確認しておきたいところが分からない）
- バグフィクスをmasterに届けるのが遅くなる

### Purpose

- リリース時の負荷が減る
- 確認点が明確になることでバグを取り除きやすくなる（品質が上がる）
- バグフィクスをリリースしやすくなりサーバ管理者各位・ユーザ各位にとってやさしい

**Comment by samunohito** [comment]
過去にあった提案。これを軸にしてもいいかもしれない
https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465

**Comment by syuilo** [comment]
> 過去にあった提案。これを軸にしてもいいかもしれない [#10806 (comment)](https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465)

そんな感じが理想だけどその通り運用できる自信がないわね(色々忘れそう)

**Comment by kakkokari-gtyih** [comment]
> > 過去にあった提案。これを軸にしてもいいかもしれない [#10806 (comment)](https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465)
> 
> そんな感じが理想だけどその通り運用できる自信がないわね(色々忘れそう)

Issueを自動でGithubのマイルストーンに紐付けるBotを組んで運用すればいいかも

**Comment by syuilo** [comment]
🆒

**Comment by samunohito** [comment]
さすがすぎる

**Comment by kakkokari-gtyih** [comment]
↑とは提案してみたものの時間が取れなさそうなので誰かやって♥

**Comment by samunohito** [comment]
マイルストーン機能の認識すらしてなかったのでgoodjob

**Comment by syuilo** [comment]
ここにMisskeyリポジトリの運用を一部自動化するためのBotを作ろうとした残骸がある
https://github.com/misskey-dev/github-keeper

**Comment by samunohito** [comment]
- GitHubのマイルストーン機能を使えば管理の自動化が出来そう
- 入れるタイミングはタグにより判断できそう
- リポジトリは既にあるので、そこに機能を増やしていけばよさそう

手段はなんとかなりそうなので、あとはその手段を活かすためのルールか…

**Comment by samunohito** [comment]
- https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465 でいく
- 今の運用を小粒にしたイメージ（ただし冒頭の内容のように取り込み数を制限する）でいく

でだいぶ変わってきますが、どっちでいきますか

**Comment by syuilo** [comment]
前者にするかしら

**Comment by samunohito** [comment]
> 例えば第三日曜でそのリリースに入れる機能の受付を締め切ってリリース用ブランチを切り
> レビュー期間に入って第四土曜以降に最初のリリースを行い

このあたりのスケジュール間隔はそのままでよさそうですか？
書き込み当時の様子を知らないので何とも言えないのですが、今はだいぶ活発なように見えるので調整の余地があると考えてます

**Comment by tamaina** [comment]
カレンダーバージョニングにする=もうちょっとリリース間隔が短くなると考えていたけどそうならなかったので個人的には拍子抜けしてた

**Comment by syuilo** [comment]
Misskey Hubの更新なども含めてリリース作業自体を自動で行ってくれるBotが欲しくなってきた(人間はapproveするだけ)

**Comment by tamaina** [comment]
どんな手動作業があるのかしら

**Comment by tamaina** [comment]
（リリースノートなら https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes がある程度解決しそう？

**Comment by syuilo** [comment]
> どんな手動作業があるのかしら

様々なボタンをぽちぽちする

**Comment by syuilo** [comment]
リリースノート然り、package.jsonバージョンの更新とか、GitHub Releaseのバージョン名入力とか、人間がやるとミスしそうなポイントがいくつもある(実際ミスしてる)

**Comment by samunohito** [comment]
tamainaさんの貼ってくれたやつとかActionsとか組み合わせたらうまいこと解決できそうではあるかも

**Comment by anatawa12** [comment]
https://github.com/anatawa12/AvatarOptimizer/blob/master/.github/workflows/release.yml

リースノートは人間向けなので次度以下はあまり良くないと思ってますが(validationは賛成) package.json等の更新は現在進行系で使ってる例があります(master一本運用なのでマージ等改修必須ですが)

**Comment by kakkokari-gtyih** [comment]
> Misskey Hubの更新なども含めて

これはビルド時にChangelogを取得して反映とかでうまいことできそう

**Comment by tamaina** [comment]
package.jsonが変だったらマージを防止するぐらいでもいいような気はするけど、そもそも「次のリリース名の定義の正式名」ってどうやって持たせればいいんだ

**Comment by samunohito** [comment]
（今日明日は忙しいけど、一息ついたらここまでの流れと残課題を整理＆botの要件取りまとめをしたい）

**Comment by anatawa12** [comment]
> そもそも「次のリリース名の定義」ってどうやって持たせればいいんだ

一応私の回してる自動リリースでは
- 次のバージョンのベータで示す
- ベータの中の次のバージョンは数字の部分を-1した状態(=前回のベータリリースの状態)でブランチにおいておく

という形で回ってるのでどうにかはなります

**Comment by tai-cha** [comment]
年末年始は時間があるしある程度のそういう自動化は得意分野なので取り組むのであれば私も何かしらはできるかもしれないですね〜

**Comment by samunohito** [comment]
memo:

注意点
package.jsonの変更をわすれないように
squah mergeしないように
GitHub Release作成時にブランチをmasterにするように
GitHub Release作成時にタイトルをバージョン名にするように

**Comment by samunohito** [comment]
### ◎ツール
- 基盤とする仕組みはGitHubのMilestone。そのうえでリリースする機能やbugfixのissueをまとめて管理する
- botを使用してブランチの作成、リリース準備を行う

### ◎運用方針
https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465

1. 実装期間→レビュー期間→バグフィクス期間を繰り返す
2. レビュー期間に突入したらリリースブランチを切り、レビューを開始する。
3. バグフィクス期間に突入したら初回リリースし、以降はリリースブランチに対するbugfixのみ受け付ける

### ◎決めたい or わからない
- 1リリースのサイクル
  - https://github.com/misskey-dev/misskey/issues/12807#issuecomment-1869438092 。まだ決まっていない認識
- https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465 の読み方
  - "init release"のリリース先はdevelop？master？タグを作る？
  - 2枚目を見る限り、サイクルが並列して走ってるように見えるけどあってる？"init release"したらリリースブランチの面倒を見ながら次のサイクル？
  - 2枚目のyyyy.MM.0は1枚目のどこに相当する？"init release"のこと？
- beta版
  - そもそもやる？
  - レビュー開始時点（リリースブランチ作成時点）でbetaと銘打つか、レビュー完了時にbetaと銘打つか（いっそ両方？）

**Comment by samunohito** [comment]
僕の考え（こだわりはないので変だったら訂正して欲しい）

- 1リリースのサイクル
→2週間くらい
- カレンダーバージョニングにする
  - "init release"のリリース先
→タグを切る
  - サイクルが並列して走ってる
→出来れば並走させたくない（管理がしんどいので）
  - 1枚目のどこに相当
→init releaseに相当
- beta版
  - そもそもやる？
→やりたい。betaとして公開したほうが分かりやすいと思う
  - betaとするタイミング
→レビュー開始時でbeta.0にしちゃっていいと思う

**Comment by syuilo** [comment]
> 僕の考え（こだわりはないので変だったら訂正して欲しい）
> 
> * 1リリースのサイクル
>   →2週間くらい
> * カレンダーバージョニングにする
>   
>   * "init release"のリリース先
>     →タグを切る
>   * サイクルが並列して走ってる
>     →出来れば並走させたくない（管理がしんどいので）
>   * 1枚目のどこに相当
>     →init releaseに相当
> * beta版
>   
>   * そもそもやる？
>     →やりたい。betaとして公開したほうが分かりやすいと思う
>   * betaとするタイミング
>     →レビュー開始時でbeta.0にしちゃっていいと思う

👍

**Comment by samunohito** [comment]
こんなイメージ

```mermaid
sequenceDiagram
  participant master
  participant develop
  participant release

  activate develop
  develop ->> develop: 機能追加等

  develop -)+ release: リリースブランチ作成
  
  release ->> release: リリースブランチ切ったら<br>betaリリース1（tag: yyyy.MM.0.beta-0）

  rect rgb(200, 150, 255)
    note left of release: レビュー期間
    release ->> release: 問題点修正等
  end

  release ->> release: レビュー期間終わったら<br>betaリリース2（tag: yyyy.MM.0.beta-1）

  rect rgb(200, 150, 255)
    note left of release: beta期間
    release ->> release: bugfix等<br>※マージ次第都度betaリリース
  end

  release ->> master: マージ
  master ->> master: タグ切ったりしてリリース<br>（tag: yyyy.MM.0）

  master ->> develop: マージ

  develop ->> develop: 次のサイクルへ

  deactivate develop
```

**Comment by syuilo** [comment]
リリース後の master → develop へのマージって必要？

**Comment by syuilo** [comment]
package.json の version とかをdevelopに反映させるために必要か

**Comment by syuilo** [comment]
あれ、というかそもそも master ブランチって要る？(役割が分からなくなった)

**Comment by syuilo** [comment]
vueとかnestとかいくつかリポジトリ見て回ったけど、develop / master のように分かれてるリポジトリ無かったから要らない可能性あるわね

**Comment by syuilo** [comment]
既存の master ブランチは廃止した上で、現在の develop を master にリネームするとかで良いかもしれない

**Comment by syuilo** [comment]
> 既存の master ブランチは廃止した上で、現在の develop を master にリネームするとかで良いかもしれない

操作上は単にmasterを今までのdevelopのように運用し、既存のdevelopブランチを削除する感じになるわね

**Comment by samunohito** [comment]
developは

>第三日曜以降の機能はそれはそれとして develop に取り込まれ次の月に持ち越される

の部分を実現するのは必要だと思ってました。
…が、リリースブランチが切られたらリリースブランチへのプルリク（レビュー対応やバグフィクスなど）以外の取り込みをすべて止めるのであれば、developも不要になるかも。

**Comment by samunohito** [comment]
（リリースブランチ切られたら関係あるプルリクやissue以外の受付を一切止めるほうが管理上は楽ではある…）

**Comment by syuilo** [comment]
> 第三日曜以降の機能はそれはそれとして develop に取り込まれ次の月に持ち越される

これの実現には develop / master のようにブランチが分かれている必要性はないように思ったけど認識間違ってたかしら

**Comment by samunohito** [comment]
あ〜、言われてみれば…

**Comment by samunohito** [comment]
明日になったら反映版を書きます

**Comment by samunohito** [comment]
改定ver1

### ◎運用方針
ベース：https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465

- 実装期間 -> レビュー期間 -> bugfix&patchリリース期間を繰り返す
- 取り込むissueはMilestoneに登録して管理
- 1サイクルは2週間程度（最近のペース的に機能実装1週間、レビュー＆バグフィクスで1週間ほどにして様子を見たい）

- 実装期間
  - 機能実装issueやバグissueを順次マージ（1リリースあたりのサイズが肥大化しないように調節）
- レビュー期間
  - 期間になったらリリースブランチ作成＆betaリリース（タグ打ち：`yyyy.MM.0-beta-0`）
  - 問題点の修正など順次対応
- bugfix&patchリリース期間
  - 期間になったらbetaリリース2発目（タグ打ち：`yyyy.MM.0-beta-1`）
  - bugfixのプルリクを取り込むたびにbetaリリース（タグ打ち：`yyyy.MM.0-beta-2, 3, 4...`）
  - 期間終了時にリリース（タグ打ち：`yyyy.MM.0`）＆masterへマージ

### ◎ベース（ https://github.com/misskey-dev/misskey/issues/10806#issuecomment-1560844465 ）からの変更点
- "init release"の代わりにレビュー開始時・終了時にそれぞれリリースするようにしている
- 2枚目の画像をみるに、前のサイクルのリリースも面倒見るようになってると読み取れる。
…が、1サイクルでスパッと切るようにしている（管理負担の都合上）

### ◎既存の運用からの変更点（告知が必要）
- developが廃止され、masterと各releaseの運用になる
- ブランチベースのリリースからタグベースのリリースになる

### ◎個人的にこうしたい
- 実装期間中以外はmasterへの取り込みも一切止めたい
（次リリースに持ち越しだと事故りそうなので、やるとしてもMilestoneへの登録くらい）

**Comment by kakkokari-gtyih** [comment]
実装期間のPRをマージするのはどこになるのかしら

**Comment by syuilo** [comment]
> 実装期間のPRをマージするのはどのブランチになるのかしら

master

**Comment by samunohito** [comment]
bot仕様草案。例のごとく突っ込みどころが多いと思うのでばしばし突っ込んでほしいです

Actionsでもいいけど…しんどそうなのでTypeScriptあたりでスクリプト書くのがベターか？
Actionsで作ってくれる人がいれば嬉しいが…

- Milestone作成機能
  - 期限は実行時点から2週間後（調節できると◎）
  - 同じ名前のMilestoneは作らないようにする（期間中のMilestoneがある場合は作らないようにしたりとか）
  - `release-yyyy.MM.x`の命名規則で作成される
    - `yyyy.MM`は年月であり、リリースされる年月の数値が入る。  
    例えば2024年1月31日にMilestoneを作ったとしても、リリース月は2月になるので`release-2024.02.0`となる。
    - `x`はリリース回数であり、同じ`yyyy.MM`がつけられたMilestoneの数をカウントして付与する。
- リリースブランチ作成機能
  - Milestoneの期限が残り1週間になったらその時点のmasterからリリースブランチを作成する
  - `release-yyyy.MM.x`の命名規則で作成される（考え方はMilestoneと同じ）
- リリース機能
  - リリースブランチ作成時点のコミットにタグを打つ（`release-yyyy.MM.x-beta-0` の形式）
  - リリースブランチと同名のプルリクを作成する
    - 事故防止のためdraftで作る
    - 内容はその時点のCHANGELOG.mdの当該リリース部分を持ってくる
    - betaリリースが進行するたびに都度取得し直されて更新される
  - misskey-devによるapproveがついたらレビュー終了としてタグを打つ  
  （`release-yyyy.MM.x-beta-1` の形式／approveの数は要検討）
  - 以降、betaで上がってきた不具合がマージされるたびに新たなタグを切っていく
  - Milestoneの期限が到来したらリリースプルリクのDraftを解除する
  - リリースプルリクのcloseを確認したらマージコミットにタグを打つ（`release-yyyy.MM.x` の形式）

package.jsonの更新も都度必要か…
というか、npmにpublishしてるわけでもないし、package.jsonのバージョン更新いるかしら…

**Comment by syuilo** [comment]
> package.jsonのバージョン更新いるかしら

別にpackage.jsonじゃなくても良いけど自身のバージョンを知れる必要がある

**Comment by samunohito** [comment]
あ〜

**Comment by tachibana51** [comment]
https://github.com/misskey-dev/misskey/issues/12807#issuecomment-1873265420
の仕様草稿から読んだ内容を整理して図に起こしてみました。  
ワークフローとしての流れをつかむ助けになれば。
![memo](https://github.com/misskey-dev/misskey/assets/29031994/be33653f-467f-4440-9289-e67930273d9a)

**Comment by Sayamame-beans** [comment]
少し気になったのですが、`yyyy.MM.x-beta-0`じゃなくて`yyyy.MM.x-beta.0`だったりします…?
(semverでないことは認識していますが)semver風の表記だと、betaに繋ぐのは`-`で、その先は再び`.`というイメージがあります
(`yyyy.MM.x-rc.0`など)

**Comment by samunohito** [comment]
別口でコメントいただいてましたね…反映したつもりが出来ていませんでした、ありがとうございます

**Comment by tachibana51** [comment]
> (前後の文章を見て)少し気になったのですが、`yyyy.MM.x-beta-0`じゃなくて`yyyy.MM.x-beta.0`だったりします…? (semverでないことは認識していますが)semver風の表記だと、betaに繋ぐのは`-`で、その先は再び`.`というイメージがあります (`yyyy.MM.x-rc.0`など)

軽い変更なので差し替えますね

**Comment by tachibana51** [comment]
https://github.com/misskey-dev/misskey/issues/12807#issuecomment-1879542814
を差し替えました

**Comment by tamaina** [comment]
ブランチをrelease-プレフィクスつけてタグを従来通りrelease-なしにするのではだめなのかしら

**Comment by tamaina** [comment]
ブランチの関係はこうしたい感じがある(develop-masterはとりあえず温存して間にreleaseブランチを加える

![misskey-releas-n](https://github.com/misskey-dev/misskey/assets/7973572/cabef1b2-23af-4b58-b1fc-6cb6436c5004)

**Comment by tamaina** [comment]
リリースのたびにパラレルにコードベースが増えていくの、大きな脆弱性やバグがあってreleaseブランチとmasterへ適用するのに大きくコードが異なる場合に詰みが発生しそう

（気持ちとしては大きなシステムを作るのではなく今まで通りのシリアルな開発を改良していった方がいいのではと思っていたりする）

**Comment by tamaina** [comment]
今深夜テンションでworkflowを書いてる

**Comment by tamaina** [comment]
masterのversionが定まらない気がするんだけどどうするんだろう

**Comment by tamaina** [comment]
新バージョン-beta.0のコミットをmasterに追加してからブランチきる（次のバージョンが出るまでほったらかし）ということにしておくか

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/ded2dafa-ae00-4596-9d97-9f609ec8ba4d)

デフォルトだとGitHub ActionsがPR作れないようになってるのね（一番下

**Comment by tamaina** [comment]
- バージョン上げる
- ブランチ作る
- タグ作る
- リリース作る
- CHANGELOG.mdからリリースやPRにリリースノートを転記

あたりをGitHub Actionsで自動化できた

https://github.com/tamaina/sandbox-actions-release

**Comment by tamaina** [comment]
- PR開いたら(focus on release期間は)masterブランチをロックする？（リリースPRだけマージさせられるような設定にできるか不明
- beta/rcのバージョンインクリメント・リリース作成にも対応したい

**Comment by samunohito** [comment]
すごい（すごい）

**Comment by tamaina** [comment]
administration権限じゃないとrulesetがいじれないの厄介

**Comment by tamaina** [comment]
https://zenn.dev/suzutan/articles/how-to-use-github-apps-token-in-github-actions#github-apps-%E3%81%AE-app-id-%E3%81%A8%E3%80%81%E7%99%BA%E8%A1%8C%E3%81%97%E3%81%9F-private-key-%E3%82%92%E5%8F%96%E5%BE%97%E3%81%97%E3%80%81secrets-%E3%81%AB%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B

![image](https://github.com/misskey-dev/misskey/assets/7973572/76bf3f2f-b85b-4645-88be-dca980ca90c9)


詰んだ

**Comment by tamaina** [comment]
（rulesetのenforcementをdisabledにしたりactiveにしたりしてmasterブランチへpush禁止したい

**Comment by kakkokari-gtyih** [comment]
リリースに限らず全体的な運用についても一体で整備したほうがいい気がしました（ #13051 のoff-topic参照）

**Comment by tamaina** [comment]
こんなんでどうじゃろ（割と議論ガン無視で味付けしたけど

![新規ドキュメント 1 2024_01_24_04_14_24 0](https://github.com/misskey-dev/misskey/assets/7973572/9eb240a0-df47-4755-9450-e3495f391374)

**Comment by tamaina** [comment]
時間的な要素はMisskeyの開発に似合うかわからんのでとりあえず考えないことにしたい気がする

**Comment by tamaina** [comment]
もしかして: releaseブランチは削除していい

**Comment by samunohito** [comment]
> 割と議論ガン無視で味付け

概要だけでもいいので内容を教えてほしいです。
見た限り以下が変わってそうですが…
- バージョンの刻み方にrcが増えている
- tagを打つ操作が消えている？
- 具体的な期間の記載が消えている？

**Comment by samunohito** [comment]
> 時間的な要素はMisskeyの開発に似合うかわからん

リリースの半自動化により負荷が下がり、こまめにリリースできるようであれば問題ないかと思います。

しかし、期間が延びて取り込む差分が増えると、元の木阿弥になってしまうので注意が必要です。
もともとは以下を課題に感じて考えた話なので
- リリース時の負荷が高い（確認作業など）
-  betaを長くとっても網羅しきれない（意識して確認しておきたいところが分からない）
- バグフィクスをmasterに届けるのが遅くなる

**Comment by tamaina** [comment]
> バージョンの刻み方にrcが増えている

突っ込めそうなので付け足した（できればrcで24時間程度さらに様子を見たい）

> tagを打つ操作が消えている？

リリースコミットが発生すればタグとリリースはついてくる

**Comment by tamaina** [comment]
現状の運用でも（昔から）どうしてこんなにリリース期間を大きく取ってるのか理解できてない

（そしてそういう方に対してここで挙げられているようなリリースフローを提案しても却下されるだけだろうと思っている

**Comment by syuilo** [comment]
> 現状の運用でも（昔から）どうしてこんなにリリース期間を大きく取ってるのか理解できてない

リリースが多すぎて追いつけないみたいな意見が多かった

**Comment by tamaina** [comment]
> リリースが多すぎて追いつけない

開発速度が異常な以上はついてきてもらうほかないんじゃない 
あと昔と違ってDockerが割とまともに整備されている（たぶん）のでついてこれるサーバーは多くなっていると思う

（個人的には2日おきにリリースしてもいいと思っている）

**Comment by tamaina** [comment]
> （個人的には2日おきにリリースしてもいいと思っている）

なんか世間的には2日おきはついてこれないレベルらしい(

**Comment by FineArchs** [comment]
開発が早すぎて変更の把握が追いつかないってことはまああると思うんですけど、それがリリース期間を長く取ることで改善されるわけではないように思います。（時間あたりの変更量は変わらないため）

**Comment by FineArchs** [comment]
あるいは、リリースの度に必ずしも毎回取り込む必要はなく、何回分か飛ばす選択肢もあるということが周知されていない？

**Comment by syuilo** [comment]
> こんなんでどうじゃろ（割と議論ガン無視で味付けしたけど
> 
> ![新規ドキュメント 1 2024_01_24_04_14_24 0](https://private-user-images.githubusercontent.com/7973572/299092487-a39b2338-bfbc-4d3c-883d-ef9cc89962e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzMxODIsIm5iZiI6MTcwNjA3Mjg4MiwicGF0aCI6Ii83OTczNTcyLzI5OTA5MjQ4Ny1hMzliMjMzOC1iZmJjLTRkM2MtODgzZC1lZjljYzg5OTYyZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDUwODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA4YjY0NmRiNzhlMjM0YjhmZGI5NTY5YmQ0MjE2MmExOTM5ODIwNTkyMmRjZDRmNjdmMzM1YjBkMTBjYjQxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.crup8QdJUbhVXMLDTiQ28w6KcROPWlf1ORD4ZW8mZgc)

人間がやることは任意のタイミングでpackage.jsonのversionを更新することとPRをready/マージすることだけ？

**Comment by tamaina** [comment]
> 人間がやることは任意のタイミングでpackage.jsonのversionを更新することとPRをready/マージすることだけ？

人間がpackage.jsonやPRのマージに触ってはいけない(readyは触る)

workflow dispatchで全自動で行われる

**Comment by syuilo** [comment]
package.jsonの更新とPRの作成は勝手にスケジュールに沿って行われる感じかしら

**Comment by tamaina** [comment]
現状workflow dispatchとcronはお好みで

**Comment by samunohito** [comment]
やりたい

**Comment by syuilo** [comment]
新しい運用方法まとめあるかしら

**Comment by tamaina** [comment]
![](https://raw.githubusercontent.com/misskey-dev/release-manager-actions/9a01978d867dd9596c9adfe7a5656e5b90c981d1/flow.png)

**Comment by tamaina** [comment]
( https://github.com/joinmisskey/release-actions で動いているので実際に動かすとわかりやすいかもしれない

**Comment by syuilo** [comment]
自分の知能では理解できなさそう

**Comment by tamaina** [comment]
## Workflows
リポジトリに3つのワークフローを置く

1. Workflow Dispatch(Run workflow)で操作するメインワークフロー
2. CHANGELOG.mdが変わった時にPRの説明を書き換えるワークフロー
3. Ready for Reviewした時自動的にrcリリースを作成するワークフロー

## 「リリースコミット作成」とは
「リリースコミット作成」機能は次の操作が実行される

- package.jsonのversionを書き換え
- gitタグの追加
- GitHubでリリース
  この時CHANGELOG.mdの内容がリリースの説明文に追加される

## Phase 0: 開発
masterブランチで新機能の取り込みをする

## Targetの作成
リリースPRがない状態でメインワークフローをDispatchすると、次の操作が実行される

1. 次のバージョンを決定
2. リリースブランチ作成
3. ブランチをもとにリリースPRを作成
4. beta.0リリースコミット作成
5. CHANGELOG.mdのUnreleasedタイトルをバージョンに書き換え
6. rulesetの切り替え
   整合性のためにmasterブランチをロックする

## Phase 1: リリースに専念
やること

- バグ取り
- CHANGELOG.mdの編集

ここでメインワークフローを(`MERGE...`にチェックを入れずに)操作すると、betaリリースが作成される

## Ready for Review
PRをReady for Reviewにするとrcリリースが発行される

（rcリリースの番号はbetaの続き、GitHubの使用上draftに戻せるがそれだとコンフリクトするため）

## Phase 2: Release Candidate
RCで最終確認する

## Phase 3: Publish The Release
メインワークフローを`MERGE RELEASE BRANCH TO MAIN`にチェックを入れてDIspatchすれば、正式リリースが発行される

次の操作が実行される

- まずマージ可能性をチェックする
  * Approveが必要
- 正式版リリースコミットを作成
- rulesetの切り替え
  masterブランチのロック解除
- CHANGELOG.mdにテンプレートを追加

→ Phase 0に戻る

**Comment by tamaina** [comment]
release/ブランチができるの議論の流れとは逆だけど、PRベースでやるにはそうするしかない

（そういう面ではmaster-developの方がいいのだけれど？）

**Comment by tamaina** [comment]
release(もしくはdevelop)と並行してmasterへ機能をマージするのは破綻が発生する（正式リリースでマージする際にコンフリクトが発生したりreleaseのバグ修正をmasterへ反映しにくくなるため）

（こういった面でもmaster-developの方がいいのだけれど？）

**Comment by tamaina** [comment]
(master-developシステムを推奨したからと言ってmaster-develop用のスクリプトが準備されているわけではない)

**Comment by tamaina** [comment]
> release(もしくはdevelop)と並行してmasterへ機能を追加するのは破綻する（正式リリースでマージする際にコンフリクトが発生したりreleaseのバグ修正をmasterへ反映しにくくなるため）

（他のプロジェクトは結構やってるらしいけど、Misskeyの場合(？)バグフィックスと機能追加が絶望的に相性が悪いことがままあるため、そんなことはしない方がいいと思っている）

**Comment by samunohito** [comment]
> release(もしくはdevelop)のバグフィックスと並行してmasterへ機能を追加するのは破綻する

？
作ってもらったActionsはmasterをロックするようにしてもらったような

**Comment by tamaina** [comment]
> > release(もしくはdevelop)のバグフィックスと並行してmasterへ機能を追加するのは破綻する
> 
> ？ 作ってもらったActionsはmasterをロックするようにしてもらったような

https://github.com/misskey-dev/misskey/issues/12807#issuecomment-1872922447 らへんのコメントを見たので

（あとロック未実装のActionsを試している時に間違ってmasterを更新したら面倒な話になったので念押しした）

**Comment by samunohito** [comment]
何が課題として残っているのか知りたい

- 本格導入するには、もっと手順を簡略化する必要がある…？　→手順書があれば解決する？
- そもそも導入の機運が低い　→issueのclose

**Comment by syuilo** [comment]
やるか
