### ISSUE TITLE
LTLを複数持てるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12815]
### Summary

チャンネルほど閉鎖的なものではないけど、トピック別にLTLを分けて投稿できるようにする（トピックは鯖缶が決めて追加できる）
このトピックは内部的な振り分けにすぎず、別サーバーのGTLやローカルのHTLにはトピック関係なく従来どおりすべてのノートが流れるし、そのノートがどのトピックに属しているか自体も連合されない

### Purpose

全体LTLの速度低減のための一つのオプションとして提供
（トピックLTLはすごくざっくりとした棲み分けにする＋そもそもLTLがあまり早くなければ使わないという前提）

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
「パブリック」での投稿時にどのLTLに流すかを選べる仕様がいいかも

**Comment by syuilo** [comment]
ハッシュタグとかじゃダメかしら

**Comment by kakkokari-gtyih** [comment]
> ハッシュタグ

あくまでも全体LTLの速度低減のための一つのオプションとして提供したいので

**Comment by samunohito** [comment]
「トピック別」という観点ではハッシュタグやチャンネルで良さそうですが、「全体LTLの速度低減」という観点では補えないかなと思いました。

- ハッシュタグ
  - ユーザが能動的につける必要がある
  - そもそもLTLの流速軽減にはならない
- チャンネル
  - LTLと同列に扱うには導線が少々奥まったところにある（もっと！→チャンネル一覧→LTLチャンネルみたいな）
…故に、公式でアナウンスするなど運用の手間が必要
  - 連合されない

**Comment by samunohito** [comment]
（LTLがふえるということは…STLもふえる…？LTL＋HTLだから…）

**Comment by kakkokari-gtyih** [comment]
STLはユーザーが選択したトピックLTL or 全体LTLと、HTLを合体でいいと思う

**Comment by syuilo** [comment]
チャンネルとの使い分けはどうなるかしら

**Comment by kakkokari-gtyih** [comment]
> チャンネルとの使い分けはどうなるかしら

チャンネルは、より狭いコミュニティベースでのモデレーションが効くので、鯖缶側で指定された広めのトピックよりもさらに深くニッチな内容を話す場として活用できるとおもう

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by 1STEP621** [comment]
現状の4本TLがある状態でさえ、Twitterから以降した人などにとってやや混乱がある気がするので、
これ以上TLが増える & STLの状態も選択によって切り替わる という状態になるとかなりややこしくなってしまうのではと思う

**Comment by syuilo** [comment]
サーバー公式のチャンネルを作れてそれを分かりやすい場所にピン留め表示する機能とかで十分な気がするわね

**Comment by GrapeApple0** [comment]
(話が若干それますが)個人的には おすすめチャンネル一覧のページネーションを強化とチャンネルの検索ができるとありがたいです

**Comment by 1STEP621** [comment]
Off-topic:
幅の狭いスマートフォンだとTL選択UIが一部隠れてしまっているのをなんとかしたい

![Screenshot_20231227-184642_Chrome.png](https://github.com/misskey-dev/misskey/assets/86859447/96ed1089-9b80-4295-b09e-d70ef6b24a36)

**Comment by kakkokari-gtyih** [comment]
> サーバー公式のチャンネルを作れてそれを分かりやすい場所にピン留め表示する機能とかで十分な気がするわね

👍

**Comment by samunohito** [comment]
（細かいけど、タイトル変えるか新しく切りなおすかしたほうがいいかも）

**Comment by kakkokari-gtyih** [comment]
きりなおしましょう

**Comment by anatawa12** [comment]
=>  #12825
