### ISSUE TITLE
frontendでsatisfiesが使えない

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12817]
asだと正しくない型でも通っちゃうのでできる限りsatisifiesにしたいけど使えないのをどうにかしたい

**Comment by KisaragiEffective** [comment]
#14183 のCIが通ったので本件はcloseできる

**Comment by anatawa12** [comment]
とりあえず閉じちゃって良さそう。使えないのをどうにかしないとというモチベで開いたので
