### ISSUE TITLE
Docker使用時にエラー吐いて落ちる

### ISSUE THREAD

**Issue by chikage8640** [syuilo/Misskey#12822]
### 💡 Summary

DockerでMisskey 2023.12.1起動時、エラーを吐いて終了します。

### 🥰 Expected Behavior

エラーなく起動する

### 🤬 Actual Behavior

Dockerで起動した際、以下のようなエラーを吐いて落ちます。
```
Error: Cannot find package '/misskey/packages/backend/node_modules/misskey-js/package.json' imported from /misskey/packages/backend/built/server/oauth/OAuth2ProviderService.js
    at legacyMainResolve (node:internal/modules/esm/resolve:205:26)
    at packageResolve (node:internal/modules/esm/resolve:831:14)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
これは公式イメージでも自分でビルドしたイメージでも発生します。

### 📝 Steps to Reproduce

1. Misskeyの公式Dockerイメージ(2023.12.1)を起動する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.1
* Node: v20.10.0
* PostgreSQL: 
* Redis: 
* OS and Architecture: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
* Docker: 24.0.7, build afdd53b
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
memo: `import { permissions as kinds } from "misskey-js";` が悪そう。今までどうやらbackendからmisskey-jsを参照してることがなくて今回発覚したっぽいです。ごめんなさい。

**Comment by kakkokari-gtyih** [comment]
> memo: `import { permissions as kinds } from "misskey-js";` が悪そう。今までどうやらbackendからmisskey-jsを参照してることがなくて今回発覚したっぽいです。ごめんなさい。

とりあえずこのFixだけでも取り込んで明日中にv2023.12.2出しちゃいましょうか

**Comment by anatawa12** [comment]
ですね。今修正pullreq作ってます

**Comment by tamaina** [comment]
テストでdockerの立ち上げについて確認してないんだっけ（ビルドはするけど起動テストはしない？）

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/workflows/docker-develop.yml 見る感じビルドだけですね

**Comment by tamaina** [comment]
定期的にdockerで起動しないと言われているので起動までテストしたほうがよさそう

**Comment by kakkokari-gtyih** [comment]
> 定期的にdockerで起動しないと言われているので起動までテストしたほうがよさそう

#12827
