### ISSUE TITLE
センシティブ画像をバナーに設定できる

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12839]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/67428053/a38ba04b-dce3-45d6-9d13-cd0e440c4071)

### 🥰 Expected Behavior

センシティブ設定になっていたら弾く

### 🤬 Actual Behavior

弾かれず普通に登録できる

### 📝 Steps to Reproduce

1. 画像をアップロード、センシティブに設定する
2. バナーを変更→ドライブから→センシティブな画像を選択

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 22H2
* Browser: Chrome v120.0.6099.111 (Official Build)
* Server URL: (local)
* Misskey: v2023.12.2 (develop)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
多分これアイコンも設定できるやつちゃいますか

**Comment by zyoshoka** [comment]
Duplicate of #7311?
