### ISSUE TITLE
検索でhttps://から始まるものを検索すると自動的に照会になる

### ISSUE THREAD

**Issue by GrapeApple0** [syuilo/Misskey#12832]
### 💡 Summary

(仕様な気もしますがバグで立てます)
検索でhttps://から始まるもの(https://google.comなど)を検索すると自動的に照会になってしまいます

### 🥰 Expected Behavior

自動的に照会にならない/またはモードを設定できる

### 🤬 Actual Behavior

自動的に照会になる

### 📝 Steps to Reproduce

1. 検索でhttps://から始まるものを検索する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): HP Z240
* Browser: Vivaldi 6.5.3206.48 (Stable channel) (64-bit) 
* Server URL: misskey.04.si
* Misskey: 2023.12.2-pie-3.0.9
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by caipira113** [comment]
![Screenshot_20231228_144615_Chrome Dev](https://github.com/misskey-dev/misskey/assets/54402969/96d78ea5-4037-49a0-9083-a2f56188ff71)
💡 If it's added, I'd like to see it integrated with the existing search options.

**Comment by zyoshoka** [comment]
既に閉じられてしまっていますが #10839 と同じですね。

まず #12736 を直して、`ap/show` へのリクエストで `NO_SUCH_OBJECT` が返ってきた場合に普通のクエリとして検索するようにするのが良さそうな気がしています。

**Comment by Sayamame-beans** [comment]
#13858 で照会を行うかどうか確認を入れるようにしました
