### ISSUE TITLE
notes/local-timelineをsinceId付きで叩いた時に不自然に新しいノートが返される

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#12842]
### 💡 Summary

misskey APIのエンドポイント`notes/local-timeline`を`sinceId`を指定して叩くと、不自然に新しいノートの情報が返されます。

例：sinceIdに2ヶ月前のノートのIDを指定したにもかかわらず、帰ってきたのは６時間前のノートの情報

### 🥰 Expected Behavior

sinceIdに指定したノートと時間的に隣接したノートが返される

### 🤬 Actual Behavior

新しいノートが返される

### 📝 Steps to Reproduce

apiコンソールなどで`notes/local-timeline`を
```
{
  sinceId: <古いノートのID>,
  limit: <1~100の整数>
}
```
で叩く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
EMUI 12
* Browser:
Chrome
* Server URL:
https://misskey.systems
* Misskey:
2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by setaria430** [comment]
related to https://github.com/misskey-dev/misskey/issues/12625
