### ISSUE TITLE
`pnpm dev`でテストサーバー開けたら`SOMETHING_HAPPENED_IN_PROMISE`エラーが発生

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#12861]
### 💡 Summary

devtoolsでは`Uncaught (in promise) ReferenceError: LANGS is not defined`エラーが見える

`pnpm --filter backend build`でswcがboot.jsをビルドしてしまっているのが原因（`pnpm build-assets`の結果を上書きする）

### 🥰 Expected Behavior

エラーが発生しない

### 🤬 Actual Behavior

する

### 📝 Steps to Reproduce

1. `pnpm dev`
2. ブラウザで`localhost:3000`にアクセス

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11
* Browser: Firefox 123
* Server URL: http://localhost:3000
* Misskey: `develop`
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: `pnpm dev`
* Misskey: `develop`
* Node: v21.4.0
* PostgreSQL: docker v15
* Redis: docker v7
* OS and Architecture: Windows 11
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by saschanaz** [comment]
swcrcで何とかexcludeしたいですができなくて謎

**Comment by kakkokari-gtyih** [comment]
多分viteのhmr関係で、フロントエンドはlocalhost:5173から開けるようになってるはず

**Comment by saschanaz** [comment]
昔は3000だっだのにいつから？！

5173もなぜかECONNREFUSEDで動きませんので謎です

```
11:46:19 [vite] http proxy error at /favicon.ico:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:46:22 [vite] ws proxy error:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:46:22 [vite] http proxy error at /api/meta:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:46:22 [vite] http proxy error at /api/emojis?:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:46:22 [vite] http proxy error at /sw.js:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:46:22 [vite] ws proxy error:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1114:18)
```

**Comment by saschanaz** [comment]
あ、test.yml使ってないんだ

**Comment by saschanaz** [comment]
:3000でアクセスしたら警告が出るようにしたいですがどうしたらいいでしょう

**Comment by Hoto-Cocoa** [comment]
私も同じエラーを受けています。
奇妙な点はログインしているタブでは正常に動作しますが、そうでないゲストタブではエラーが発生します。

**Comment by Hoto-Cocoa** [comment]
ひとまずは `pnpm build-assets` で解決できましたが変更したコードに frontend の変更はありませんでした。

**Comment by tamaina** [comment]
> 昔は3000だっだのにいつから？！

https://github.com/misskey-dev/misskey/pull/12593

**Comment by tamaina** [comment]
> :3000でアクセスしたら警告が出るようにしたいですがどうしたらいいでしょう

よさそう

**Comment by ToshihitoKon** [comment]
同様のエラーが本番環境で出るようになったのですが、こちらのIssueに関連するものですかね？
こちらはdev環境の話っぽいのでprodだと違うのかもしれません
別原因そうであれば別でIssue建てようかなと思っております

動作環境のsystemdサービス定義抜粋
```
[Service]
User=root
ExecStart=/usr/bin/npm start
WorkingDirectory=/home/misskey/misskey
Environment="NODE_ENV=production"
```

現象:
PCブラウザからトップを開こうとすると`Failed to load`となり、コンソールに`Uncaught (in promise) ReferenceError: LANGS is not defined`と出る

再現:
PCのChrome(123.0.6312.87)で100%再現、Cookie削除やプライベートタブを利用しても変わらず
拡張のAdBlock等は利用していません
PWAで入れておいたAndroidからは問題なく利用できています

Misskey環境: GCP GCE上
```
$ uname -a
Linux misskey 5.10.0-28-cloud-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

$ git log -1
commit 78ff90f2cc3bdb3b4119f51617614d1a32afd960 (HEAD -> master, tag: 2024.3.1, origin/master)
Merge: 7e706ea66 3afdafed6
Author: syuilo <4439005+syuilo@users.noreply.github.com>
Date:   Sat Mar 2 17:06:46 2024 +0900

    Merge pull request #13493 from misskey-dev/develop

    Release: 2024.3.1
```

きっかけ？:
突然
最近MisskeyアップデートしたりChromeを久々にアップデートしたりして再起動したら起きまして継続中です

**Comment by samunohito** [comment]
> pnpm --filter backend buildでswcがboot.jsをビルドしてしまっているのが原因（pnpm build-assetsの結果を上書きする）

バックエンドの変更があると↑でビルドするようにしていますが、build-assetsまで出来ていないのでLANGSがそのまま出てしまってるものかと思います（本来、LANGSは文言ファイルのパスに置き換えられなければいけない）。

自分のミスです。ごめんなさい。何とかできないか見てみます。


@ToshihitoKon 
> PCブラウザからトップを開こうとするとFailed to loadとなり、コンソールにUncaught (in promise) ReferenceError: LANGS is not definedと出る

同じ現象かと思います。

こちらは`pnpm build`でビルドしていただくと改善される可能性があります。ビルド後にMisskeyを開いても改善しない場合、1度フロント側にあるjsファイルなどのキャッシュを捨てていただく必要があるかもしれません。
お手数ですが、一度試して頂けますと幸いです。

**Comment by ToshihitoKon** [comment]
@samunohito ビルドし直したところ解消されました、ありがとうございます！
