### ISSUE TITLE
バッテリーセーバー/軽量モード

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#12876]
### Summary

通常UIでブラウザのリソース消費を削減するボタンが欲しい（ナビゲーションバーで切り替えられるようにしたいかも）

例えば次のようなことをやりたい

- WebSocketを不使用にする
- 一部ウィジェットの無効化？
- アニメーション・ぼかし強制無効化
- グラデーション無効化
- ダークモード強制
- 画像プレビューでBlurhashを計算しないように、画像スタイルの計算量削減（height直接指定）
- インスタンス情報表示でアイコンを表示しない

### Purpose

- バッテリーが限られた状況でも使いたいため
- /cliは単機能すぎるため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by anatawa12** [comment]
ダークモード/ライトモードは液晶か有機ELかでどっちがローパワーか変わるので固定はよくなさそう

**Comment by kakkokari-gtyih** [comment]
このissue立ってた気がする

**Comment by tamaina** [comment]
Duplicate of #10561
