### ISSUE TITLE
緊急時お知らせ（お知らせ機能の拡張）・日本における津波情報との連携機能

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12877]
### Summary

- 緊急時（災害時等）のMisskeyの使用方法のダイアログを全ユーザーに一斉表示できる機能を追加（既存のお知らせ機能を拡張）
  - Misskeyはバッテリーを消費するため充電が利用できない環境では使用しないこと
  - その他、必要に応じて一般的な災害時のSNSの利用に関する注意事項を掲載（←ここは各鯖管がいじれるように）
- 津波情報発令・解除時に自動で有効・無効にできるようにする（[p2Quake](https://www.p2pquake.net/develop/json_api_v2/#/P2P%E5%9C%B0%E9%9C%87%E6%83%85%E5%A0%B1%20API/get_history)と連携？）
  - 日本国外の場合や、手動で有効にすべきその他の緊急時には、サーバー管理者が必要に応じて災害時モードをONにできるようにする
  - 日本国外の災害情報プロバイダにも追って対応できるようにする

### Purpose

- 緊急時の情報を適切にモデレーションするため
- 非常時に携帯電話のバッテリー消費を削減するため  
  （Misskey本体を軽量化するのが先だ！という意見もあるかもしれないが、考えることが多くなかなか進まない気がするので、とりあえずお知らせできる機能を持たせてもいいんじゃないかしら）

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
イメージ

![image](https://github.com/misskey-dev/misskey/assets/67428053/38186840-3a23-454a-a79d-a075b8a8e0b7)

**Comment by PYU224** [comment]
良い機能ですね。

**Comment by fruitriin** [comment]
本体の機能として組み込んでしまうと有効にしても無効にしても管理人のスタンスの表明になってしまうので、できれば採用されてほしくない

ネガティブな情報に触れ続けると少しずつ心が磨耗するということもあり、私のサーバーでは災害情報についてチャンネルに誘導してLTLではこの話題に触れることについて禁止としてある
