### ISSUE TITLE
Safari not playing videos due to missing functions when using `/files`

### ISSUE THREAD

**Issue by Mar0xy** [syuilo/Misskey#12881]
### 💡 Summary

We got a report on our fork that safari does not play videos due to the videos missing a byte range header and another function with a ton of information about them: https://git.joinsharkey.org/Sharkey/Sharkey/issues/292

Copy and Pasted from linked issue:

(I don't know if this affects S3 storage as well)
Starting playback of any video hosted in /files does not work in Safari or any browser on iOS/iPadOS. This also affects Safari on macOS.
Safari requires Byte-Range support for video playback, see the [Safari Web Content Guide](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6).
Setting some headers is not enough, since Safari actually first sends a request for bytes 0-1 and then checks the response.

[Here](https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/) is another writeup of this behaviour, although there are many others.

### 🥰 Expected Behavior

Videos should play

### 🤬 Actual Behavior

Videos do not play

### 📝 Steps to Reproduce

1. Open any video on safari

### 💻 Frontend Environment

```markdown
From reporting user:

* Model and OS of the device(s): iPhone 15, iOS 17.2.1
* Browser: Safari / AppleWebKit 605.1.15
* Server URL: shonk.social
* Sharkey: 2023.12.0 (equivalent to Misskey 2023.12.2)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
Working on it in #12909
