### ISSUE TITLE
メールサーバーを登録しても送信に失敗する

### ISSUE THREAD

**Issue by Okakajp25** [syuilo/Misskey#12883]
### 💡 Summary

自分はメールサーバーをsakuraでやっていてしっかりその設定をmisskeyに登録しているのですがこのようなエラーコードが出てできません。
翻訳をすると挨拶が届かないと言っていたので色々設定を変えてましたし前はできたのでmisskey側のBugなのではないかと考えています
```markdown
Endpoint: admin/send-email
Info: {"e":{"message":"Greeting never received","code":"Error","id":"b5eda607-f466-44ac-b475-f6619159825e"}}
Date: 2024-01-02T02:49:02.602Z
```

### 🥰 Expected Behavior

メールサーバーが保存出来てテストメールなどのmisskey関係のメールが送信できる

### 🤬 Actual Behavior

メールサーバーは保存できるもののmisskeyからのメールが送信できない
![スクリーンショット 2024-01-02 124739](https://github.com/misskey-dev/misskey/assets/115696838/b398bccc-55c5-4a0c-84a6-97a948581641)

### 📝 Steps to Reproduce

なし

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows11 Pro
* Browser: Chrome
* Server URL: https://m.okakey.com
* Misskey: 2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Method:systemd Service:AWS FC2
* Misskey: 2023.12.2
* Node: 20.10.0
* PostgreSQL: 15
* Redis: 最新
* OS and Architecture: Ubuntu22.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by CyberRex0** [comment]
メールサーバーがSSL/TLSを強制している可能性があります。
案内されているポート番号を確認し、それでも解決しないときは
メールサーバー設定の「SMTP 接続に暗黙的なSSL/TLSを使用する」をオンにしてみてください。

**Comment by Okakajp25** [comment]
メールサービスを変えたらできたのでクローズします
ありがとうございました
