### ISSUE TITLE
2要素認証によるログインに失敗する

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#12882]
### 💡 Summary

アプリと物理キーによるログインが以下のようなエラーを返してきて通らない
```
{"id":"cdf1235b-ac71-46d4-a3a6-84ccce48df6f"}
```

### 🥰 Expected Behavior

なし

### 🤬 Actual Behavior

なし

### 📝 Steps to Reproduce

なし

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):PCとiPhone13
* Browser:ChromeとOpera
* Server URL:misskey.puyuyu.com
* Misskey:2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:systemd
* Misskey:2023.12.2
* Node:20.10
* PostgreSQL:15
* Redis:最新
* OS and Architecture:Ubuntu22.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by PYU224** [comment]
二段階認証時の日本語でのエラーメッセージは「サーバー内部で予期せぬエラーが発生しています」です。

提案なんですが、管理者や本人のログインできている端末から2段階認証をストップさせる機能が必要では？と思っています。

**Comment by PYU224** [comment]
> 同じgoogleアカウントのものが2つ表示されるようになってしまいました。
> メアドは同じなのに、それぞれ違う6桁の数字が表示されています。
> https://support.google.com/accounts/thread/218177930/google-authenticator%E3%81%AE6%E6%A1%81%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E5%89%8A%E9%99%A4%EF%BC%88%E7%AE%A1%E7%90%86%EF%BC%89?hl=ja
これが起きていました。

**Comment by Kur0den** [comment]
一度二段階認証を解除して再度登録しなおすのではだめなのでしょうか…?

**Comment by PYU224** [comment]
それが2段階認証の解除にも2段階認証が必要で、解除すらできない状態なんです。

**Comment by PYU224** [comment]
2要素認証の解除は精々パスワード程度で良くない？と思いますが・・・

**Comment by Kur0den** [comment]
二段階認証セットアップ時に表示されるバックアップコードを入力するのはどうでしょうか?

**Comment by syuilo** [comment]
> 2要素認証の解除は精々パスワード程度で良くない？と思いますが・・・

パスワードが漏れた場合の砦となるのが2faだと思ってるので、パスワードだけで2faの解除が行えるとすると機能の意味が全くなくなりそうな気がしたけど認識間違ってるかしら

**Comment by PYU224** [comment]
セットアップ時にバックアップコードが出なかった記憶があります。

> パスワードだけで2faの解除が行えるとすると機能の意味が全くなくなりそうな気がした
そのシチュエーションはログインできる端末を他人に手にされているという事なので、その時点でダメなような気がします。

**Comment by Kur0den** [comment]
バックアップコードは必ず出てくる気が…?

バックアップコードを控えてないのであれば二段階認証の解除時に複数あるワンタイムトークンを一つづつ試してみるのはどうでしょうか?
登録ができているということは恐らくどれかは正常だと思うのですが…

**Comment by syuilo** [comment]
あー2fa解除APIを叩くにはログインしている必要がある=叩けるということは(少なくとも過去1度は)2faクリアしているということだからパスワード認証だけでもセキュリティは担保されるかも…？

**Comment by u1-liquid** [comment]
> あー2fa解除APIを叩くにはログインしている必要がある=叩けるということは(少なくとも過去1度は)2faクリアしているということだからパスワード認証だけでもセキュリティは担保されるかも…？

`i`などトークンが漏えいされているケースがあるので担保されていません

**Comment by PYU224** [comment]
> 複数あるワンタイムトークンを一つづつ試してみる
問題に陥る前に間違えて片方を削除してしまいました。

iのトークンか。難しいですね。

**Comment by PYU224** [comment]
勘違いと手違いに対するリカバリー策はもう少し欲しいです。

**Comment by Kur0den** [comment]
> 問題に陥る前に間違えて片方を削除してしまいました。
リカバリーとかもできない感じですかね…?
トークンを失くしたのであればもうログインする手段はないかと…

**Comment by PYU224** [comment]
google authenticatorを使っていますが、削除した二段階認証のキーを復帰させる事ができればそれはそれで問題は解決するんですが、方法が見当たりません。
管理者がサーバーを新設して早々にこれはまずい。

**Comment by Kur0den** [comment]
サーバー管理者で新設したばかりならサーバーを建て直すのはどうでしょうか?

**Comment by PYU224** [comment]
どうにもならないのでしたらそうします。

**Comment by Kur0den** [comment]
トークンを削除してしまってリカバリーコードも控えてないのであればMisskey自体にセキュリティガン無視のウルトラCがない限りもうどうしようもないかと

**Comment by PYU224** [comment]
分かりました。
では立て直します。

**Comment by Kur0den** [comment]
次二段階認証をセットアップする際はバックアップコードを控えるのを忘れないようにしてくださいね…

**Comment by PYU224** [comment]
そうします・・・後は不必要に認証アプリのキーを削除しない事も意識します。

**Comment by samunohito** [comment]
これ以上はissueが動かなさそうなのでcloseとさせていただきます。
