### ISSUE TITLE
リモートユーザのプロフィールページに対する照会のリクエストに対してリダイレクトを返す

### ISSUE THREAD

**Issue by tesaguri** [syuilo/Misskey#12892]
### Summary

リモートユーザのプロフィールページ（例：<https://misskey.io/@Gargron@mastodon.social>）に対して`Accept`ヘッダに`application/ld+json`や`application/activity+json`が設定されたリクエストを受けたときに、オリジナルのサーバ上のプロフィールページへのリダイレクトで応答する。

現行の挙動：

```console
$ curl -I --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' 'https://misskey.io/@Gargron@mastodon.social'
HTTP/2 404
[…]
```

提案したい挙動：

```console
$ curl -I --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' 'https://misskey.io/@Gargron@mastodon.social'
HTTP/2 302
[…]
location: https://mastodon.social/users/Gargron
[…]
```

### Purpose

misskey.io以外のFediverse上のアカウントを他人に対して紹介するときに、本来のサーバにおけるプロフィールページの代わりにmisskey.ioにおける当該アカウントのプロフィールページを示すと伝わりやすいという一種のライフハックがあるようです：

<https://misskey.nokotaro.com/notes/818cc7516957ebcc543b6f2e>

ただ、FediverseのアカウントをフォローするときはそのアカウントのプロフィールページのURLを照会するという原則を知っているユーザが相手である場合は、まずこのmisskey.ioのプロフィールページのURLを照会しようとする可能性が考えられます。しかし、現行のMisskey（misskey.io）の実装ではこのプロフィールページで照会しても意図通りにプロフィールを開けません。

Mastodonにも同様にリモートユーザのプロフィールを表すエンドポイント（例：<https://mastodon.social/@syuilo@misskey.io>）がありますが、こちらのURLの場合はオリジナルのサーバにリダイレクトするため、そのまま照会にかけても問題なく意図したプロフィールが開かれます。

Misskeyでも同様にリモートユーザのプロフィールページに対する照会のリクエストに対してオリジナルのサーバへのリダイレクトで返せば、ユーザの混乱が少なくなるのではないかと思います。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by momoirodouhu** [comment]
どなたか実装している方はいますか？

**Comment by samunohito** [comment]
誰もアサインされていないので、誰も着手していないと見なしてよいと思います
