### ISSUE TITLE
「おかえりなさい◯◯さん」のトーストを無効にするオプションが欲しい

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#12890]
### Summary

現状だと2時間以上経過するとリロードしたときにトーストが出ますが、タブが重くなってリロードするたびに出るのが鬱陶しく感じてしまうので出なくするオプションがほしいです。

### Purpose

PWAなど画面サイズが限られているデバイスでは、おかえりなさいトーストはさらに不要かもしれません。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
鬱陶しくないように改修すればよさそう

**Comment by kanade** [comment]
ご確認ありがとうございます。
TLで見かけただけなのでどこのサーバーか分からないのですが、このようなオプションがあるサーバーもあるみたいです。
鬱陶しくないというと表示させる位置とかですかね？
![Screenshot_20240103-065456](https://github.com/misskey-dev/misskey/assets/732664/557a033b-9cee-49a5-9b88-daef93b7f657)

**Comment by syuilo** [comment]
位置以外にもいろいろ考えられそう

**Comment by kanade** [comment]
表示非表示のオプションと、表示する場合は非表示にするまでの時間を設定できる…とかでしょうか？
ちょっと発想力が乏しいのでパッと思い付かなくてすみません。
なにかしらご検討いただけたら嬉しいです！

**Comment by kakkokari-gtyih** [comment]
ログボを実装するのと同時に廃止で良い気がする

**Comment by zyoshoka** [comment]
👀
https://github.com/misskey-dev/misskey/commit/45d88574c309dcbf014e1ebc7895caca0b8dbed6
