### ISSUE TITLE
https,httpのドメイン接続、httpのip接続ができない

### ISSUE THREAD

**Issue by Okakajp25** [syuilo/Misskey#12895]
### 💡 Summary

ページに接続しようとすると以下のようにエラーになる
- ドメイン接続
・http -> サーバーが見つからなくて開けない
・https -> 大量のリダイレクトが発生して開けない
- IP接続
・http -> nginxのデフォ画面が出てくる
・https -> ちゃんとしたmisskeyのページが出てくる

何度かcloudflareの方で設定もして治んなくて再インストールをしようとしても同じドメインを使えないのでできないのでmisskeyの方のエラーと考えます(間違ってたらすいません)解決したらこれはクローズします

### 🥰 Expected Behavior

ドメイン,IPの両方で正常にmisskeyのページにアクセスできる

### 🤬 Actual Behavior

Summaryのように開けないことがある

### 📝 Steps to Reproduce

なし

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iPhone13,2
* Browser: Safari
* Server URL: https://m.mokakey.com(今はhttps://13.115.127.147/でしかアクセスできない)
* Misskey: 2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Method -> systemd Hosting -> amazon web service(fc2)
* Misskey: 2023.12.2
* Node: 20.10
* PostgreSQL: 15
* Redis: 最新
* OS and Architecture: Ubuntu 22.04.2 LTS
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by GrapeApple0** [comment]
cloudflareのssl設定をFullまたはFull(Strict)にしてみてください
https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full/

**Comment by Okakajp25** [comment]
できました！
~~やる時に見たと思ったけどなー~~
