### ISSUE TITLE
Misskey Playの説明欄でURLを扱えるように(リンクになるように)して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#12898]
### Summary

タイトル通りです。
Play一覧ページでは引き続きURLがリンクにならなくても良いと思いますが、それぞれのPlayページにおける説明画面(Playを押す前)ではURLがリンクになって欲しいと思います。
MFM等は現状使えないので、単に記載したURLがリンクになるだけ(表示を変えたりも出来ない形)であれば、特に問題になることは無いと考えています。

### Purpose

関連する別のPlayを併記しておきたい場合など、何らかの別ページを参照出来るようにしたい場合に、現状ではURLがただの文字列になってしまい、ユーザー側は開くのが面倒であるため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
MFM対応にするか
