### ISSUE TITLE
デッキ表示、カラムの設定で「ファイル付きノートのみ表示」ができるようにしてほしい

### ISSUE THREAD

**Issue by watcheye25** [syuilo/Misskey#12900]
### Summary

デッキ表示時のカラムごとの個別設定にて、表示するノートをファイル添付の有無でフィルタリングしたいです。
現在の「リノートを表示」と同じところに出すのか、
カラムの設定画面の「幅を自動調整」のところに出すのかはどちらでも構いません。

### Purpose

絵描きさんのみのリストを作って絵関連のノートのみを見たいと思っています。
当然画像付きであれば絵以外のノートも拾ってしまいますが、
日常のテキストノートが減るだけでかなり見やすくなると思っています。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by esperecyan** [comment]
https://github.com/misskey-dev/misskey/issues/8760 と重複してそうです。

**Comment by watcheye25** [comment]
検索不足で、失礼しました。

**Comment by kakkokari-gtyih** [comment]
Duplicate of #8760
