### ISSUE TITLE
絵文字サジェストの表示順がおかしい

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12908]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/4439005/ff9eaec0-81f9-48df-b4e0-9aba8d02aa52)

### 🥰 Expected Behavior

okが一番上に出る(一致率が一番高いため)

### 🤬 Actual Behavior

そうなっていない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment]
一致率でスコアを算出すると名前が短い絵文字ほど上に出てくるようになってしまい不便になりそうなので、完全一致だけを優遇して上に出すのが良いかもしれないです
