### ISSUE TITLE
音声・映像UIを内製する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12909]
### Summary

#12093 #12478 #12521 #12912 に対応

### Purpose

ブラウザデフォルトのUIには限界があるので内製する
ついでに再生キューとかもつけられると良いかも

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
どうかしら・・・

**Comment by syuilo** [comment]
やりたい

**Comment by kakkokari-gtyih** [comment]
やるか

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/309af98d-76c8-4fac-abdf-74df9f610e49)
