### ISSUE TITLE
相手がGoneを出していなくても死んだ判定をできるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12903]
### Summary

通信できなくなって何度か試しても無理なら（などの基準で）、相手サーバーが死んだ判定をできるようにする

### Purpose

サ終してもGoneを出してくれないところがやはりある＋ドメインの有効期限ぎりぎりまで運用してNSごと吹っ飛ぶみたいなパターンも考えられるため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
すでにできるのならごめんなさい（もうちょっと早い段階で死んだ判定を出しても良いかも？）

**Comment by Sayamame-beans** [comment]
それで言うと、復活した判定もあると少し嬉しいですね。(配送停止後、復活させるのを忘れそうになることがあるので…)
手動で or Goneで配送停止した場合は復活チェック無し、このissueによる機能での自動停止の場合は復活チェック有り、みたいな感じになるでしょうか…?
復活しているかのチェック頻度は少し気を付けないと数が増えた時に結構な負荷になりそうではあります。(半日、1日、3日、1週間と徐々にチェック予定日の間隔を広げて、半年ぐらい経ったら最終的にチェックしないことにする?)

**Comment by kakkokari-gtyih** [comment]
> 復活した判定

相手から照会なり配送なりが来たらとかでいいのでは

**Comment by Sayamame-beans** [comment]
> > 復活した判定
> 
> 相手から照会なり配送なりが来たらとかでいいのでは

確かにその通りですね…
