### ISSUE TITLE
センシティブ設定された動画にも左上にマークが欲しい

### ISSUE THREAD

**Issue by esperecyan** [syuilo/Misskey#12912]
### Summary

メディアを隠していない状態の場合、画像は左上にセンシティブマークが表示されますが、動画には表示されません。
動画にも表示するように出来ないでしょうか。

![](https://github.com/misskey-dev/misskey/assets/3625160/3fd43e14-6e85-40e2-aa3b-99acb76a33d7)
![](https://github.com/misskey-dev/misskey/assets/3625160/fd05e91b-f674-46fb-8308-e0c435e7189f)

### 関連
- https://github.com/misskey-dev/misskey/issues/3579
- https://github.com/misskey-dev/misskey/issues/12093
- https://github.com/misskey-dev/misskey/issues/12478

### Purpose

「センシティブなメディアの表示」設定で「センシティブ設定されたメディアを隠さない」を設定している場合に
- 隠すボタンを押す手間を踏まずにセンシティブ設定されたメディアかどうかわかる
- センシティブ未設定と勘違いされるのを防ぐ

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
#12909 で一括対応予定
