### ISSUE TITLE
「チャンネルヘリノート」機能が欲しい

### ISSUE THREAD

**Issue by k0range** [syuilo/Misskey#12921]
### Summary

![image](https://github.com/misskey-dev/misskey/assets/93308122/ca611038-b9a2-4701-89ee-8cf9e9efc945)
リノートする際に、特定のチャンネルにリノートする機能がほしい。

### Purpose

 - チャンネルで特定のノートをみんなに見せたい場合などに使えるため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
Related: #11238 #12687 (投稿フォームを空にして引用するとRNになるため)
参考として、私のチャンネルへRNする用のプラグイン( https://misskey.niri.la/notes/9gsxxkxjhw )では、フォローしているかお気に入り登録をしているチャンネルにRN出来るようにしています。この2種類に対してのRNに需要があると思います。

**Comment by k0range** [comment]
空引用でRNになるのは初めて知りました。教えていただきありがとうございました。

**Comment by setaria430** [comment]
https://github.com/misskey-dev/misskey/pull/12687 が適用されているサーバーに居ますが、プラグイン要らずでチャンネルにRNできてとても便利です
