### ISSUE TITLE
MkCodeEditorの行がずれてしまう

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#12927]
### 💡 Summary

MkCodeEditorのコードハイライトが実際の字の位置とずれてしまいます。
少なくともコードブロックにAndale Monoが適用される環境、Ubuntu Monoが適用される環境ではずれることを確認しました。
![Screenshot from 2024-01-06 20-15-56](https://github.com/misskey-dev/misskey/assets/86859447/afc19940-9874-4232-a151-6d946c855716)
![Screenshot from 2024-01-06 20-16-00](https://github.com/misskey-dev/misskey/assets/86859447/2462cdd9-5aa1-4e25-9891-d24daf1fafaa)

### 🥰 Expected Behavior

ずれない

### 🤬 Actual Behavior

ずれる

### 📝 Steps to Reproduce

1. MkCodeEditorに長めのコードを書く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Ubuntu 22.04 LTS
* Browser: Firefox 121.0 (64bit)
* Server URL: misskey.systems
* Misskey: 2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
line-heightは統一したはずなんだけどな…なんでだ

**Comment by 1STEP621** [comment]
こちらの環境では違う値が指定されてた(カスタムCSS等は設定していないです)

textareaのほう
![Screenshot from 2024-01-11 01-19-11](https://github.com/misskey-dev/misskey/assets/86859447/b6094e78-6d72-4d72-924a-a979aed4da5a)
highlighterのほう
![Screenshot from 2024-01-11 01-19-16](https://github.com/misskey-dev/misskey/assets/86859447/1a6d283f-c3e1-4639-bf7d-50aa2dada2bd)

**Comment by 1STEP621** [comment]
これ直ってなさそう

**Comment by 1STEP621** [comment]
![Screenshot from 2024-02-06 21-18-20](https://github.com/misskey-dev/misskey/assets/86859447/646dc0d8-23d0-489e-8ae4-db735ac292d1)
これくらいずれる

**Comment by kakkokari-gtyih** [comment]
Firefox Developer Edition v123.0b6 (Windows 11 22H2) で再現しなかった

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/04e2348e-bbfc-4d52-998e-c84364d3072f)

**Comment by 1STEP621** [comment]
同じFirefoxでもWindows(11)だと再現しなかった

**Comment by kakkokari-gtyih** [comment]
Browser-specificだし私はmac持ってないので対応できない🫠

**Comment by 1STEP621** [comment]
(弊環境はUbuntu 22.04)
フォントによる差の可能性もあるかも

**Comment by 1STEP621** [comment]
#13175 の修正が入る前はUbuntu Monoでもずれが再現していたけど、Ubuntu Monoでは再現しなくなっている

**Comment by 1STEP621** [comment]
`font-family: Consolas,Monaco,Andale Mono,Ubuntu Mono,monospace`(自分の環境では最終的に`Andale Monoが適用される`)
と
`font-family: Andale Mono`
で挙動が異なる🤯
後者だとずれない

**Comment by kakkokari-gtyih** [comment]
textareaかshikiどちらかに別のフォントが適用されている可能性

**Comment by 1STEP621** [comment]
![image](https://github.com/misskey-dev/misskey/assets/86859447/d1b1b593-a75a-4564-9ed8-5a3c49dffbd4)
Shikiのルートにある`<pre>`には`monospace`が設定されていた
`Consolas,Monaco,Andale Mono,Ubuntu Mono,monospace`の指定がUAスタイルシートに負けている...？？
