### ISSUE TITLE
Drop & Fusionにスコアをシェアするボタンが欲しい

### ISSUE THREAD

**Issue by k0range** [syuilo/Misskey#12933]
### Summary

新しく追加されたDrop & Fusionに、ゲームオーバーになったときに最終スコアをノートするボタンが欲しい。

### Purpose

スコアを共有できると面白いと思ったため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
ゲーム画面をファイルとして添付できるようにもしたい(以前のMisskey PagesではそのようなPageも作れた)

**Comment by k0range** [comment]
> 以前のMisskey PagesではそのようなPageも作れた
 
 そうなんですね！良いと思います

**Comment by acid-chicken** [comment]
遊んでる時は良さそう（？）だけどリザルトの画面が急に流れてきたら集合体恐怖を煽る可能性がありそう

**Comment by kakkokari-gtyih** [comment]
センシティブにしておく or 投稿自体をcwにしてやるといいかも

**Comment by kakkokari-gtyih** [comment]
シェア機能自体はすでに実装済みなのでClose
