### ISSUE TITLE
notes/createでtext: nullだけでもノートできる

### ISSUE THREAD

**Issue by GrapeApple0** [syuilo/Misskey#12968]
### 💡 Summary

notes/createでtext: nullのみでもノートが可能になっています
`text: ''`ではノートできないのでnullもできないのが適切だと思います

### 🥰 Expected Behavior

text: nullのみでノートできない

### 🤬 Actual Behavior

text: nullのみでノートできる

### 📝 Steps to Reproduce

1. API Consoleで`notes/create`にパラメーターを`text: null`にし実行する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): HP Z240
* Browser: 6.5.3206.50 (Stable channel) (64-bit) 
* Server URL: https://misskey.04.si
* Misskey: 2023.12.2-pie-3.1.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2023.12.2-pie-3.1.2
* Node: 20.10.0
* PostgreSQL: PostgreSQL 15.5 (Ubuntu 15.5-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
* Redis: 7.2.4
* OS and Architecture: Arch Linux 6.6.10-arch1-1
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by acid-chicken** [comment]
Duplicate of #12381
