### ISSUE TITLE
リバーシ復活

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#12962]
### Summary

昔あったリバーシを復活させる

### Purpose

要望が多いため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
（オフトピかも）ゲームの数をいたずらに増やすとメンテナンスコストが増大するので、Playで部屋作成やリアルタイム通信を可能にして、あとはユーザーに任せたほうがいいかも？

Related to https://github.com/misskey-dev/misskey/issues/12596

**Comment by syuilo** [comment]
ゲームは意外とそれ単体で完結する機能だから増えてもそこまでコストは増えない傾向がある
グラフィカルな対戦ゲームをPlayでやるのは色々と厳しい
