### ISSUE TITLE
バブルゲームのサーバー内ハイスコア

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#12961]
### Summary

バブルゲームにサーバー内ハイスコア・サーバー内ランキングがほしいです

### Purpose

ユーザー内で競って遊べたら楽しそうだと思ったため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
チート対策を考える必要があるわね

**Comment by syuilo** [comment]
エンジンがfully deterministicになったから、クライアントからはスコアを自己申告するのではなく操作ログとゲームシードを送り、サーバー側でそれを再生してスコアを計算するようにすればチート出来なくなりそう
