### ISSUE TITLE
バブルゲームのプレイ時間を記録・表示できるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#12974]
### Summary

簡易的にプレイ時間を記録・表示できるようにする（フロントエンド完結）
（今日 / 累計の２つで良さそう）

### Purpose

バブルゲームのやりすぎを抑止する機能を実装する必要がある

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by t1nyb0x** [comment]
https://github.com/misskey-dev/misskey/pull/12976#issuecomment-1902566941
こちらで一旦なしとのことでしたので、一度クローズ致します。

必要になりましたら、リオープン等お願い致します。
