### ISSUE TITLE
ユーザー名を指定してブロックする機能

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#12982]
### Summary

フォロワー解除やブロックする際、ユーザーのプロフィールページを開く必要があるが、プロフィールページを開かずにユーザー名指定でブロックやフォロワー解除ができるようにしてほしい

### Purpose

以下のようなケースで有効かと考えています
1）相手のサーバーが死んでいてプロフィールページが開けなくなっている場合
2）プロフィールページを見たくない場合（バナーの画像がキツいなど）

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
> 相手のサーバーが死んでいてプロフィールページが開けなくなっている場合

照会から開けませんか？

**Comment by lssnana** [comment]
> 照会から開けませんか？
このIssueを上げたときには読み込み中で開けなくなり困っていたのですが、時間を空けてリトライしたら読み込めました。ので開けなくなっていたのはタイミングの問題かもしれません。
優先度は下げていただいて大丈夫です。

**Comment by kakkokari-gtyih** [comment]
> このIssueを上げたときには読み込み中で開けなくなり困っていたのですが、時間を空けてリトライしたら読み込めました。

照会の動作に問題がないのであれば照会で事足りる気がするのですが…

**Comment by t1nyb0x** [comment]
照会で要件を満たせると判断できるため、クローズ致します。
必要ありましたら、リオープンお願い致します。
