### ISSUE TITLE
「外部サイトからインストール」のパスが `/install-extensions` ではなく `/install-extentions` になっている

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#12990]
### 💡 Summary

「外部サイトからインストール」のパスが `/install-extensions` ではなく `/install-extentions` になっています。

ブラウザの拡張機能[^1][^2]などに見られるように、extension の方が一般的かと思います。

[^1]: https://addons.mozilla.org/en-US/firefox/extensions/
[^2]: https://chromewebstore.google.com/category/extensions

### 🥰 Expected Behavior

`/install-extensions` になっている

### 🤬 Actual Behavior

`/install-extentions` になっている

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2023.12.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by k0range** [comment]
PRを作ってみました。#12991

**Comment by kakkokari-gtyih** [comment]
🤯
