### ISSUE TITLE
未ログインユーザーの場合、その人のサーバーに移動してから動作を行う導線を作る

### ISSUE THREAD

**Issue by k0range** [syuilo/Misskey#12998]
### Summary

現在のMisskeyでは、未ログイン状態でログインが必要な動作（リアクション・Playなどのノート共有・フォローなど）を行おうとするとログイン画面に移動されます。
![image](https://github.com/misskey-dev/misskey/assets/93308122/6f75f89c-b386-4775-aaaf-0a646d176660)

ですが、その人は別のサーバーにすでに登録しているかもしれないので、その人が登録しているサーバーでノートの共有やリアクションなどを行えるようにするためにそのサーバーに移動してから動作を行うような機能を作ることを提案します。

例:
 - ノートにリアクションする → サーバーのドメイン名の入力を求めてから別サーバーでそのノートを開く
 - Playのノート共有 → サーバーのドメイン名の入力を求めてから別サーバーで`/share`を開く
 - フォロー → サーバーのドメイン名の入力を求めてから別サーバーでそのユーザーを開く

例えば、Mastodonで未ログイン状態で他人のノートをお気に入り登録しようとするとこうなります：

![image](https://github.com/misskey-dev/misskey/assets/93308122/7c2d52c3-f598-48df-8d6a-6090868a6a9f)

### Purpose

未ログインユーザーが別サーバーですでにアカウントを持っている場合があるため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
それぞれの動作を行うためのrouteを用意する必要がありそう

**Comment by samunohito** [comment]
「未ログインで見ているのサーバ」と「その人が登録しているサーバー」が連合しているか、連合していても該当ノートのコピーが届いているかも加味する必要がありそう？

**Comment by k0range** [comment]
単に同じパスのノートを開けばいいと思っていましたが、結構難しそうですね...（URL内のドメイン名を変えるだけじゃ同じノートは表示されなかった）

**Comment by k0range** [comment]
> 連合していても該当ノートのコピーが届いているかも加味する必要がありそう
 
（別サーバー側で）ノートのURLを照会したときと同じ動作になるようにできれば解決できそう？

**Comment by kakkokari-gtyih** [comment]
相手がMisskeyではない場合とても面倒くさそう

**Comment by samunohito** [comment]
「未ログインで見ているのサーバ」→これはMisskey前提で良いと思います
「その人が登録しているサーバー」→連合経由で相手がMisskeyの対応バージョン or それ以外が分かれば懸念はないと思います。未対応or分からなかったのであれば未対応である旨のメッセージ＆今まで通りのフローでいいんじゃないかなと

**Comment by tamaina** [comment]
Mastodonの仕組みを真似すればいいと思う（しそういうIssueはすごい昔に立ってる気がする

**Comment by tamaina** [comment]
> それぞれの動作を行うためのrouteを用意する必要がありそう

ボタンの動作を未ログインかどうかで分ければいいんじゃね

**Comment by kakkokari-gtyih** [comment]
> > それぞれの動作を行うためのrouteを用意する必要がありそう
> 
> ボタンの動作を未ログインかどうかで分ければいいんじゃね

移動先のMisskeyでの動作を制御するための何かしらを用意する必要があるよね、ということ

**Comment by k0range** [comment]
> 移動先のMisskeyでの動作を制御するための何かしらを用意する必要があるよね、ということ

これはフロントエンド側に照会を行うページ(`/lookup`?)を用意すればほとんどは解決しそうな気がします

例えば
 - ノートにリアクション → `(移動先サーバーのドメイン)/lookup?q=(移動元サーバーのノートのURL)`に移動
 - フォロー →  `(移動先サーバーのドメイン)/lookup?q=(移動元サーバーのユーザーのURL)`に移動、など

**Comment by k0range** [comment]
「未ログイン状態でアカウント登録が必要な動作」をまとめたほうがいいかも

**Comment by okinjp** [comment]
Mastodonだと`authorize_interaction`というパスにuriというクエリを渡すことで移動先サーバーでユーザーや投稿のページに誘導してます。
これに合わせて貰えるとMastodonサーバーともリモートフォローなどがうまく行くのでいいと思います。

うちのサーバーではNginxでauthorize_interactionのパスにPHP製のアプリを置いてこの挙動に対応しているので、そこのロジック部をgistに上げました。Mastodon本来の挙動とは違い連合からPlayを含む照会できないリンクを/shareに飛ばすので概ねIssueのSummary通りの挙動になると思います。

https://gist.github.com/okinjp/886a219b83945043a233b8900ef2f344

動作例
https://mi.okin-jp.net/notes/9oil8al4ke

**Comment by LeviSnoot** [comment]
Adding to the voices here, I'd be very stoked to see something like this for Misskey! I'm not sure if it was mentioned in this thread, but I think it would also be good if we added a cookie so the remote user doesn't have to fill in their username and instance on every interaction.

As for implementation, there is a project called [AP Follow](https://github.com/mwt/apfollow) which could be helpful to implementing this feature.

(Apologies for the english, but I won't be machine translating my comments per the contribution guidelines)

**Comment by k0range** [comment]
> I think it would also be good if we added a cookie so the remote user doesn't have to fill in their username and instance on every interaction.（リモート ユーザーがインタラクションのたびにユーザー名とインスタンスを入力する必要がないように、Cookieを追加することも良いと思います。）

I see, I think it's good. Instead of Cookie, LocalStorage may be fine.
なるほど、良いと思います。CookieではなくLocalStorageでも良いかもしれません。

**Comment by syuilo** [comment]
Misskey Hubに中継させるので良いんじゃないかしら

**Comment by kakkokari-gtyih** [comment]
> Misskey Hubに中継させるので良いんじゃないかしら

Misskey Hubなら、`/mi-web/?path=/foo` とやれば /foo に飛べる

**Comment by k0range** [comment]
Misskey Hubに中継リンク機能があるのは知りませんでした。
たしかにMisskey Hubの機能で済むならそれが一番良い気がします。

**Comment by KisaragiEffective** [comment]
確かにプレイを他のサーバーでノートできると少し便利
<details>
<summary>off-topic: 将来の拡張</summary>
インスタンスの絵文字を引っ張ってくるタイプのPlayを他のサーバーでノートできるようにしてもありがたみが薄いのでPlay側に対して他のサーバーでノートできないようなオプションを作るべきかもしれない
</details>
