### ISSUE TITLE
タイムラインを横方向スワイプで切り替えられるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13003]
### Summary

スマートニュースのアレ

![image](https://github.com/misskey-dev/misskey/assets/67428053/bd265705-1a6d-404a-87dc-f522b1f0f78a)

### Purpose

タッチ画面でのUXが大幅に向上する

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by 1STEP621** [comment]
Related to #8759

**Comment by kakkokari-gtyih** [comment]
今やっている
