### ISSUE TITLE
バブルゲームのランキングにスコアが反映されない

### ISSUE THREAD

**Issue by atsunii0801** [syuilo/Misskey#13010]
### 💡 Summary

バブルゲームのスコアを更新しましたがランキングに反映されません
想像ではありますがプレイ途中にバブルゲームのプレイ方法がツールからMisskey Gamesに移動したのが原因なのではと考えています

![Screenshot_20240116_142014_Chrome](https://github.com/misskey-dev/misskey/assets/156792330/22cdc4f7-8ced-492d-a963-7db80e21e98e)
![Screenshot_20240116_142032_Chrome](https://github.com/misskey-dev/misskey/assets/156792330/5243e4b1-6d64-4073-b5fa-d79d121b0def)

### 🥰 Expected Behavior

ランキングにスコアが反映される

### 🤬 Actual Behavior

ランキングにスコアが反映されない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Android 13
* Browser:chrome 120.0.6099.217
* Server URL:misskey.io
* Misskey:2023.12.2-io.2f
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
サーバーとの通信が失敗したか、プレイ時間が長すぎ(1時間以上)て登録が受け付けられなかったなどが考えられます

**Comment by atsunii0801** [comment]
プレイ時間が長いと登録されないんですね…返信ありがとうございます
今後プレイ時間が長い場合でも登録されるようになるアップデートをする予定等はありますでしょうか？

**Comment by syuilo** [comment]
2時間以内に変更するかしら

**Comment by atsunii0801** [comment]
助かります

**Comment by syuilo** [comment]
延長しました 🙏🏻

**Comment by atsunii0801** [comment]
ありがとうございます🙏🙏🙏
