### ISSUE TITLE
ビデオコントローラーのクリック判定を広げてほしい

### ISSUE THREAD

**Issue by L8F92587** [syuilo/Misskey#13025]
### Summary

ビデオコントローラーのボタンやシークバーを余白部分でも押せるようにしてほしいです。
現状余白部分をクリックすると動画が一時停止するので、特に細いシークバーなどで誤操作がよく起きます。

### Purpose

ミュートやシーク時に誤って一時停止することがなくなる
細いシークバーを正確にエイムせずに済む

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
とりあえずコントロールUI周辺ではビデオの再生停止のクリック判定が入らないようにするか
