### ISSUE TITLE
(nirax) リダイレクトを設定できるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13029]
### Summary

パスの変更などで変更元のパスに飛んできた場合に転送できるようにしたい

### Purpose

便利。今後なにかと必要になる

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by taiyme** [comment]
PR misskey-dev#12991 に活用できそうです
