### ISSUE TITLE
【横スワイプ】画面がはみ出ることがある(特にSafari)

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13034]
### 💡 Summary

MkHorizontalSwipe直下の要素がはみ出る

手元の端末では確認できなかったが、以下のようにすごいはみ出方をする場合があるみたい（iOS Safari）
https://misskey.io/notes/9onid2w1zfsv0loa

### 🥰 Expected Behavior

はみでない

### 🤬 Actual Behavior

はみでる

### 📝 Steps to Reproduce

何もしなくてもこうなる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: misskey.io
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
iOSのバージョンが古いとか

**Comment by syuilo** [comment]
スクショ見た感じはみ出てる以外にもおかしな点がいくつか見受けられるからその可能性が高そう

**Comment by kakkokari-gtyih** [comment]
Android Chromeでも1か所だけ軽微なはみ出しがあったのでそれを抑制できるようにはしたい

**Comment by kakkokari-gtyih** [comment]
> iOSのバージョンが古いとか

最低動作バージョンっていくらでした？

**Comment by syuilo** [comment]
16.なんちゃらだったと思う

**Comment by Sayamame-beans** [comment]
現状だとiOS 16.3以上のサポートだったと思います

**Comment by kakkokari-gtyih** [comment]
> Android Chromeでも1か所だけ軽微なはみ出しがあったのでそれを抑制できるようにはしたい

これは原因特定したのでPR立てます
