### ISSUE TITLE
pnpm devで依存関係の更新が反映されない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#13043]
### 💡 Summary

pnpm devだと、例えば packages/misskey-bubble-game を編集したとしても古い内容が使われ続ける
以下を試しても変わらなかった

- pnpm clean
- pnpm build

なお、pnpm build からの pnpm start した場合は正常に読み込まれる(その後 pnpm dev するとやはり古い内容に戻る)

### 🥰 Expected Behavior

更新が反映される

### 🤬 Actual Behavior

更新が反映されない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
ブラウザを変えても変わらなかったから、ブラウザのどこかにキャッシュされてるとかでもなさそう

**Comment by kakkokari-gtyih** [comment]
そもそもpnpm devではpackages/misskey-games系がビルドされなかった（要検証）

**Comment by syuilo** [comment]
自分の環境だとビルド自体はされるわね

**Comment by kakkokari-gtyih** [comment]
/scripts/dev.mjsをいじってないとか？

**Comment by syuilo** [comment]
あーーーそれかも

**Comment by kakkokari-gtyih** [comment]
clean.jsにも当該の記述がないので同様かも

**Comment by syuilo** [comment]
clean.jsにmisskey-jsが無いのは意図してるのかしら

**Comment by kakkokari-gtyih** [comment]
わからない

**Comment by syuilo** [comment]
意図してなさそうな雰囲気だから直すか

**Comment by kakkokari-gtyih** [comment]
> clean.jsにも当該の記述がないので同様かも

pnpm buildでゲーム系のpackageがビルドされないのもどこかに記述が入っていないからだと思われ（どこかは分からなかった）

**Comment by syuilo** [comment]
なんか Could not resolve "misskey-js" が出るようになった

**Comment by kakkokari-gtyih** [comment]
package.json の workspace と pnpm-workspace.yaml の記述が食い違ってるのって何か意図があるのかしら

**Comment by syuilo** [comment]
あー

**Comment by kakkokari-gtyih** [comment]
> package.json の `workspace` と pnpm-workspace.yaml の記述が食い違ってるのって何か意図があるのかしら

関連のpnpmのissueとかを見てきたけどあまり関係なさそうかも？

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/commit/44b8ac135fdc0778e1eb4d57f6afdd798f007870
いろいろ直したけど pnpm dev すると Could not resolve "misskey-js" が出るようになってしまった

**Comment by syuilo** [comment]
pnpm build からの pnpm start は問題なし

**Comment by samunohito** [comment]
https://github.com/misskey-dev/misskey/commit/44b8ac135fdc0778e1eb4d57f6afdd798f007870#diff-0559901a4c3b5be9b8257debd3cd795b0424df2de22427404d0c1c82beb8311bR25-R29

このあたりに

```
await execa('pnpm', ['--filter', 'misskey-js', 'build'], {
	cwd: _dirname + '/../',
	stdout: process.stdout,
	stderr: process.stderr,
});
```

とか入れると直るかも

**Comment by kakkokari-gtyih** [comment]
他のパッケージより先にmisskey-jsがビルドされておく必要があるのか

**Comment by samunohito** [comment]
（devいじったときに漏れてて申し訳ない）

**Comment by syuilo** [comment]
直った 🙏🏻  🙏🏻  🙏🏻  🙏🏻  🙏🏻  🙏🏻  🙏🏻

**Comment by syuilo** [comment]
あれ直ってないかも

**Comment by syuilo** [comment]
> pnpm devで依存関係の更新が反映されない

が直ってないわね

**Comment by syuilo** [comment]
viteのバグかしら

**Comment by syuilo** [comment]
viteのキャッシュってどこにあるんだろ

**Comment by samunohito** [comment]
夜でよければ見ます

**Comment by tamaina** [comment]
https://ja.vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude ?

**Comment by tamaina** [comment]
これかも

https://github.com/vitejs/vite/issues/14099

**Comment by syuilo** [comment]
かも

**Comment by syuilo** [comment]
> https://ja.vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude ?

これは既に設定されてる

**Comment by syuilo** [comment]
> > https://ja.vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude ?
> 
> これは既に設定されてる

いや嘘

**Comment by acid-chicken** [comment]
> viteのキャッシュってどこにあるんだろ

node_modules/.cache/vite みたいなのない？

**Comment by samunohito** [comment]
（自分のローカル環境だとあっさり反映されてしまった…）

**Comment by kakkokari-gtyih** [comment]
(off-topic) Dockerも同様に記載がないので失敗している

**Comment by taiyme** [comment]
(最新のdevelopでdocker compose buildに失敗しています)

**Comment by syuilo** [comment]
> (off-topic) Dockerも同様にmisskey-games系のパッケージの記載がないので失敗している
> 
> ref: https://mk.taiy.me/notes/9opel9peuc

直ったかも

**Comment by kanasaki15** [comment]
(もしかして今のdevelop最新コミットで非docker環境でビルドがコケるのってこのissues関係してます？)

**Comment by fruitriin** [comment]
追加されたリバーシとバブルゲームが一度もビルドされてないとpnpm devできないと思う(misskey-jsも同様なので今に始まったことではない）

**Comment by syuilo** [comment]
困ったわね

**Comment by kakkokari-gtyih** [comment]
(off-topic) https://misskey.io/notes/9oxy5xhutbry088q

**Comment by syuilo** [comment]
あと pnpm dev するとパッケージを import してるとこが Cannot find module 'misskey-bubble-game' or its corresponding type declarations みたいになってしまう(VSCode再起動すれば直るけど、pnpm dev するたびに再起動必要というのは意味がなくなってしまっている)

**Comment by samunohito** [comment]
@syuilo 
たぶんなおったとおもいます

**Comment by syuilo** [comment]
あれ、ビルドしたときに型定義が生成されない気がする

**Comment by syuilo** [comment]
pnpm build したときに built 内に esm しか生成されない

**Comment by samunohito** [comment]
esbuild化されたときにそうなってましたね。
<s>怖かったのでbuildのほうは触ってないです</s>

**Comment by syuilo** [comment]
ふぅ～む
