### ISSUE TITLE
[Misskey Games] ランダムマッチのマッチ通知 Matching Notification

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#13048]
### Summary

マッチング待機時間に画面が非アクティブな場合など、マッチしたかがわからない状況があります。
音による通知や、ブラウザの通知機能を利用した通知があったらいいなと思いました。

### Purpose

* マッチした場合に気付けるようにする
* 相手が無駄に待たされずに済む

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
音出すか
