### ISSUE TITLE
(sw) オフライン表示のデザインを改善する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13050]
### Summary

コレのデザインをマシにしたい

![image](https://github.com/misskey-dev/misskey/assets/67428053/05e7b7db-cd31-4fbe-9b3b-f75ad925e082)

### Purpose

見やすくするため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
わかる

**Comment by syuilo** [comment]
~~Dinoゲームみたいなの実装したい~~

**Comment by kakkokari-gtyih** [comment]
![localhost_5173_settings](https://github.com/misskey-dev/misskey/assets/67428053/5e54536e-b2b1-4370-bfba-b600b3281427)

**Comment by 1STEP621** [comment]
インターネットに接続されていないとは限らないような気がします(サーバーが落ちているなど)

**Comment by kakkokari-gtyih** [comment]
「サーバーに接続できません」とかにするか

**Comment by tamaina** [comment]
> Dinoゲームみたいなの実装したい

これIssueなかったっけ
