### ISSUE TITLE
2024-01-22 10:50時点のdevelopにてCIがコケている

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13059]
### 💡 Summary

#13045
![image](https://github.com/misskey-dev/misskey/assets/46447427/c5c42150-f087-4203-a0f5-e8ff76b812ef)

推測できる原因：
①api.jsonの書式が壊れてる
②devDependenciesに含まれているパッケージが降ってこなくて死んでる
③vitestは…↑を修正して直らなかったら細かく見る

### 🥰 Expected Behavior

CIが全部passしている

### 🤬 Actual Behavior

現状

### 📝 Steps to Reproduce

CIを動かす

### 💻 Frontend Environment

```markdown
なし
```

### 🛰 Backend Environment (for server admin)

```markdown
なし
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
やばいのは直ったとはいえ、まだちょっと残ってるのでreopen

**Comment by tamaina** [comment]
swc使ってビルドするようにすれば

**Comment by tamaina** [comment]
esbuildの方がいいかも

**Comment by syuilo** [comment]
解決🙏
