### ISSUE TITLE
MkHorizontalSwipe内で開かれたポップアップメニュー(ノートのメニューなど)の動作がおかしい

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#13055]
### 💡 Summary

MkHorizontalSwipe内で開かれたポップアップメニュー(ノートのメニューなど)の動作がおかしい

- 二回クリックしないと閉じない
- 子メニューの表示位置がおかしくなる時がある

### 🥰 Expected Behavior

おかしくない

### 🤬 Actual Behavior

おかしい

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: iPadOS Chrome
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
設定からスワイプによる切り替え無効にしても発生するわね

**Comment by kakkokari-gtyih** [comment]
> 設定からスワイプによる切り替え無効にしても発生するわね

「UIのアニメーションを減らす」を入れるとどうなります？

**Comment by syuilo** [comment]
「二回クリックしないと閉じない」は直した(イベントハンドラにpassive指定することで解決)

**Comment by syuilo** [comment]
「子メニューの表示位置がおかしくなる時がある」は未解決(謎)

**Comment by syuilo** [comment]
> 「子メニューの表示位置がおかしくなる時がある」は未解決(謎)

これはMkHorizontalSwipeは関係ないかも
