### ISSUE TITLE
外部メディアプロキシを利用しているとサウンド設定の「ドライブの音声を使用する」が利用できない

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#13053]
### 💡 Summary

外部メディアプロキシを利用していると、CORSの制約でサウンド設定の「ドライブの音声を使用する」が利用できません。

### 🥰 Expected Behavior

利用できる、あるいは「ドライブの音声を使用する」のメニューが出ない

### 🤬 Actual Behavior

利用できないのに「ドライブの音声を使用する」のメニューが出ている

### 📝 Steps to Reproduce

1. 外部メディアプロキシを利用したMisskeyサーバーを用意する
2. サウンド設定でドライブのファイルを選択する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Ubuntu 22.04 LTS
* Browser: Firefox 121.0.1 (64bit)
* Server URL: misskey.backspace.fm
* Misskey: 2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
このために本体のプロキシをもう一度通すのもアホらしいし、かといってこの機能を潰すのもなんかなぁという感じで悩ましい

**Comment by kakkokari-gtyih** [comment]
> このために本体のプロキシをもう一度通すのもアホらしいし、かといってこの機能を潰すのもなんかなぁという感じで悩ましい

外部プロキシってデフォルトでは`Access-control-allow-origin: *`になってなかったっけ？（モノによるけど公式のやつ）

**Comment by kakkokari-gtyih** [comment]
> このために本体のプロキシをもう一度通すのもアホらしいし、かといってこの機能を潰すのもなんかなぁという感じで悩ましい

というか外部プロキシを使っていてCORSが通っていないのは普通にサーバー側の設定ミスな気がするけど（ほかにも何らかおかしいところが出ていそう）

**Comment by GrapeApple0** [comment]
そもそもメディアプロキシが音声ファイルに対応していない気がします

**Comment by 1STEP621** [comment]
メディアプロキシ側の問題か
https://github.com/MisskeyIO/media-proxy/commit/c57db1bc93ab11c11b0c3ed2f76ee74c702ba1f9

**Comment by kakkokari-gtyih** [comment]
メディアプロキシに改修入れるか

**Comment by kakkokari-gtyih** [comment]
> 外部メディアプロキシを利用していると、CORSの制約でサウンド設定の「ドライブの音声を使用する」が利用できません。

@1STEP621 これ本当にCORSエラーでした？

**Comment by GrapeApple0** [comment]
個人的にはメディアプロキシ今の状態でもかなり重たいものなので動画とかが入ってきたら落ちるレベルの負荷がかかるので動画には使って欲しくないです

**Comment by 1STEP621** [comment]
![image](https://github.com/misskey-dev/misskey/assets/86859447/d69c8a4a-1372-4349-bcdf-a63e2e4d5eda)
CORSエラーだと思ったのはこれを見たからなんですが詳しくないのでよくわからないです...🙇

**Comment by kakkokari-gtyih** [comment]
ばすきー見に行きます

**Comment by kakkokari-gtyih** [comment]
サーバー落ちた

**Comment by kakkokari-gtyih** [comment]
反動でミスってcloseした

**Comment by kakkokari-gtyih** [comment]
見てきたけどこれ単にばすきーの設定が悪いだけですね

**Comment by kakkokari-gtyih** [comment]
公式プロキシが音声や動画を通さない問題に関しては https://github.com/misskey-dev/media-proxy/issues/11 で議論するのでこっちはCloseしておきます
