### ISSUE TITLE
ページのタイトルが切り替わらないことがある

### ISSUE THREAD

**Issue by taiyme** [syuilo/Misskey#13069]
### 💡 Summary

次のページに遷移する場合、ページのタイトル (document.title) が切り替わらないことがある。
ただし、再度そのページに戻ると正常に切り替わる。

- リスト管理 (/my/lists/:id)
- ユーザープロフィール (/@:username)
- アンテナタイムライン (/timeline/antenna/:id)
- チャンネル (/channels/:id)
- クリップ (/clips/:id)
- リスト (/list/:id)
- ノート詳細 (/notes/:id)
- ページ (/@:username/pages/:slug)
- ユーザーリストタイムライン (/timeline/list/:id)

### 🥰 Expected Behavior

ページに遷移すると document.title が書き換わる

### 🤬 Actual Behavior

ページに遷移しても document.title が書き換わらない

### 📝 Steps to Reproduce

1. デフォルトまたはクラシックUIで適当なページを開く
2. 上記の対象ページに遷移する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacBook Air (13-inch, 2020), macOS Ventura 13.5
* Browser: Google Chrome 120.0
* Server URL: https://misskey.io/
* Misskey: 2023.12.2-io.2h
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by taiyme** [comment]
問題が発生しているページで共通しているものとして、下記のようにdefinePageMetadata関数の引数がnullになる可能性のあるコードがあります。

```ts
definePageMetadata(computed(() => note.value ? {
  // ...
} : null));
```

**Comment by 1STEP621** [comment]
Related to #12393
