### ISSUE TITLE
センシティブ画像を含むノートの一括ミュートを可能にして欲しい

### ISSUE THREAD

**Issue by Acid002** [syuilo/Misskey#13062]
### Summary

センシティブ画像を含むノートを一括ですべてミュートし、全年齢向けTLをつくれる機能を実装してほしい

### Purpose

io内や他インスタンスにおいて、「TLに18禁画像ばかり流れてきて嫌気が差す」「分散型SNSを謳っているのに苦手なエロ絵ばかり流れてきてノートが流れてしまい、なんのために登録したのかわからない」といった意見が散見される。私も日頃からRNミュートや個別ミュートで対応しているが、到底間に合わない。センシティブな画像を含むツイートを一括してTLから除外する機能の実装を希望します。

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
スイッチで無効にできる機能を既に実装しております

**Comment by kakkokari-gtyih** [comment]
> スイッチでセンシティブなメディアを含むノートをすべてミュートにできる機能を既に実装しております

https://github.com/misskey-dev/misskey/pull/12848 これでは満足できませんでしたか？

**Comment by CyberRex0** [comment]
1/22時点でioには取り込まれていないみたいです

**Comment by kakkokari-gtyih** [comment]
（まあ昨日マージされたところなので反映されていなくても不思議ではない）

**Comment by Acid002** [comment]
確認しました、ありがとうございます

**Comment by kakkokari-gtyih** [comment]
Duplicate of #12691
