### ISSUE TITLE
プロフィール編集後にプロフィール画面に行ってもリロードをしないと編集内容が反映されない。

### ISSUE THREAD

**Issue by mesichicken** [syuilo/Misskey#13078]
### 💡 Summary

プロフィール編集後にプロフィール画面に行ってもリロードをしないと編集内容が反映されない問題があります。

https://github.com/misskey-dev/misskey/assets/57591417/043624d1-6afd-43aa-b452-0f14b116391e

### 🥰 Expected Behavior

リロードを行わなくてもプロフィール編集内容が反映されること

### 🤬 Actual Behavior

リロードをしないとプロフィール編集内容が反映されない

### 📝 Steps to Reproduce

1. 「プロフィールを編集」から自己紹介などを編集して保存します。
2. リロードを行わずに自分の「プロフィール」に移動します。
3. プロフィールを確認すると編集した内容が反映されていません。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 自作PC windows11 22H2
* Browser: Google Chrome 120.0.6099.225
* Server URL: https://misskey.systems/
* Misskey: 2024.2.0-beta.5
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
ページのキャッシュ（suspense？）の問題だと思うので、それを活かしながらもちゃんとfetchしなおす機構を作らないといけないのでちょっと大変かも（即時性のあるnotificationなどと違いプロフィール情報はめったに更新されることがないので安易に`onDeactivated`で情報を破棄しないほうがいい気がする）

**Comment by mesichicken** [comment]
承知しました
キャッシュを活かして、プロフィールが編集されたときのみfetchし直せないか私のほうでちょっと検討してみます

**Comment by kakkokari-gtyih** [comment]
> プロフィールが編集されたときのみfetch

eventemitter（globalEvents）を使ってsuspenseのキャッシュを強制的に削除とかでも良いかも

**Comment by kakkokari-gtyih** [comment]
vueのKeepAliveのmax値を一瞬0にしてからルート遷移挟めばキャッシュ消えるのでは…！？

**Comment by kakkokari-gtyih** [comment]
> vueのKeepAliveのmax値を一瞬0にしてからルート遷移挟めばキャッシュ消えるのでは…！？（ためしてない）

概ねそういう方法で行けた

**Comment by kakkokari-gtyih** [comment]
> > vueのKeepAliveのmax値を一瞬0にしてからルート遷移挟めばキャッシュ消えるのでは…！？（ためしてない）
> 
> 概ねそういう方法でキャッシュ削除に成功した

→ #13180
