### ISSUE TITLE
[Reversi] リバーシの対局を共有できない Unable to share Reversi game properly

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#13083]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/31585494/bbd508ee-f8d1-4394-a86f-aaf9212c61b1)

![image](https://github.com/misskey-dev/misskey/assets/31585494/f5801410-61db-44b2-9909-fff9e2a544ef)

![image](https://github.com/misskey-dev/misskey/assets/31585494/00864163-9325-4e44-80fd-f4f1bc6fed4d)

### 🥰 Expected Behavior

![image](https://github.com/misskey-dev/misskey/assets/31585494/92f0b49d-1ff7-4e4a-ba5f-8e00f2f9e57e)

### 🤬 Actual Behavior

![image](https://github.com/misskey-dev/misskey/assets/31585494/00864163-9325-4e44-80fd-f4f1bc6fed4d)

### 1.
![image](https://github.com/misskey-dev/misskey/assets/31585494/54db95ec-c5f7-4a34-b7ff-500255c3acdb)
### 2.
![image](https://github.com/misskey-dev/misskey/assets/31585494/a20bfdee-07d6-4286-840e-c05cd61b56ce)
### 3.
![image](https://github.com/misskey-dev/misskey/assets/31585494/bbd508ee-f8d1-4394-a86f-aaf9212c61b1)
### 4.
![image](https://github.com/misskey-dev/misskey/assets/31585494/f5801410-61db-44b2-9909-fff9e2a544ef)
### 5.
![image](https://github.com/misskey-dev/misskey/assets/31585494/00864163-9325-4e44-80fd-f4f1bc6fed4d)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
  - PC: Custom built PC
    - OS: Windows 11 Home 22H2 (22621.3007)
    - CPU: Intel(R) Xeon(R) w5-2455X   3.19 GHz
    - RAM: 32 GB DDR5 ECC RDIMM
    - Graphics: NVIDIA GeForce GTX1060(6 GB)
    - Storage: 
      - OS(C:) : WD_BLACK SN770 1TB PCIe 4.0 NVMe M.2 SSD
      - DATA (D:) : Western Digital WDC WD10EZEX-22MFCA0 1000.2 GB 7200RPM SATA HDD
      - WORKSPACE (E:) : Seagate ST1000DM003-1ER162 1000.2 GB 7200RPM SATA HDD
* Browser: Mozilla Firefox 122.0
* Server URL: misskey.io
* Misskey: 2024.1.0-io.1c
* Server URL: misskey.systems
* Misskey: 2024.2.0-beta.7
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
ref: https://github.com/misskey-dev/misskey/pull/13750#issuecomment-2174716997
