### ISSUE TITLE
Renote をいい感じにまとめる機能

### ISSUE THREAD

**Issue by yulog** [syuilo/Misskey#13107]
### Summary

同じ投稿の Renote が短期間(画面上の一定範囲)にいくつも表示されることがあります。

Renote されるのは良いことですが、あまり連続すると見づらいので、良い感じにまとまってほしいです。  
例えば投稿の隅にリノートした人数名のアイコンと+N人のような表示がでるような。  
(せっかく Renote されたのに目立たないのは良くないので表示の工夫は必要な気がします。まとまると+Nが大きくなるとかね…！)

いい感じにというのが難しい気がしますが、例えば1分以内の分はまとまる…とか。

可能かわかりませんが、ご検討いただければ。

### Purpose

見やすさの向上です。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
Duplicate of  #1792
