### ISSUE TITLE
MFM検索窓機能で検索エンジンを選べるようにする

### ISSUE THREAD

**Issue by Mai-Shinano** [syuilo/Misskey#13126]
### Summary

![image](https://github.com/misskey-dev/misskey/assets/107112367/e56ff952-477c-4cb3-b00c-e65c3d833bcc)
ノートでの検索窓機能の検索エンジンがGoogle以外に変更できるようにしてほしい。
→もしできるのならブラウザのデフォルトエンジンにする
無理ならMisskeyクライアント上で設定できるようにする
↑これは基本的なエンジンは選択肢として置いといて、その他のエンジンは「URL+検索語句(検索キーワードの部分は「%s」に置き換えたりする)」で設定できるようにする。

### Purpose
Googleの検索エンジンを使いたくないが検索窓機能を使いたい人が変更できるようにする目的
要するに検索エンジンを変えたい人が変更できるようにする目的
ただし需要があるかは不明

**Comment by t1nyb0x** [comment]
重複のため、クローズさせていただきます。

**Comment by DA-TENSHI** [comment]
重複でしたか、失礼いたしました
