### ISSUE TITLE
「見たことのあるリノートを省略して表示」が効いていない？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13131]
### 💡 Summary

「見たことのあるリノートを省略して表示」が効いていない？

### 🥰 Expected Behavior

リアクションをつけたノートのリノートが畳まれる

### 🤬 Actual Behavior

リアクションをつけたノートのリノートが畳まれない

### 📝 Steps to Reproduce

1. タイムラインでリアクションをつけたノートのリノートを見る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 14'' MacBook Pro
* Browser: Firefox
* Server URL: p1.a9z.dev
* Misskey: 30b48df9d95ee931117070468442d5d6738fb3e8
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Manual
* Misskey: 30b48df9d95ee931117070468442d5d6738fb3e8
* Node: v20.11.0
* PostgreSQL: ?
* Redis: ?
* OS and Architecture: Ubuntu
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/927292a5-d6b8-4f42-85d8-070c9080d414)

a6a91fec3af5314472b0a70402c1ef7e73a478ef

これが原因？

**Comment by tamaina** [comment]
特に似たものは見つからなかったわね

**Comment by syuilo** [comment]
> [a6a91fe](https://github.com/misskey-dev/misskey/commit/a6a91fec3af5314472b0a70402c1ef7e73a478ef) 、なんかめっちゃ変更突っ込まれてるけどなんなん
> 
> （他のところでも類似したバグが発生している可能性があるがこれでは追えない）

他にもチャートでクリックに反応しない不具合もありそう
