### ISSUE TITLE
check-misskey-js-autogen may have problems

### ISSUE THREAD

**Issue by dakkar** [syuilo/Misskey#13147]
### 💡 Summary

`check-misskey-js-autogen` checks that the files in the PR and the re-generated files are identical.

But the files include the timestamp when they were generated, so they'll always be different

### 🥰 Expected Behavior

a PR with no changes to types, or a PR with changes generated by `pnpm run build-misskey-js-with-types`, should pass all its checks

### 🤬 Actual Behavior

https://github.com/misskey-dev/misskey/actions/runs/7757223154/job/21156225090?pr=13146 and https://github.com/misskey-dev/misskey/actions/runs/7757239915/job/21156270587?pr=13145 failed even after I ran `pnpm run build-misskey-js-with-types`

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by zyoshoka** [comment]
Since this problem is caused by the version bump (https://github.com/misskey-dev/misskey/commit/66714d94fcb25e10314418e8ec7ee27b1d8357f8) and not timestamps, updating the branch seems to fix the problem. That said, need to add that to the message when CI fails.

**Comment by zyoshoka** [comment]
`misskey-js` そのものには影響しないですし `autogen` 内の `version` の整合性チェックは取り除いても良い気がします。

Related to #13173

**Comment by zyoshoka** [comment]
#13185 で対応されたので close して良さそうです。
