### ISSUE TITLE
ノートの下書きは原則自動復元ではなく明示的に呼び出すように

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13154]
### Summary

- 書きかけのものを放置してある程度の時間（5分以上？）が経った場合は、下書きを復元させずにまっさらの投稿フォームを出す
- その場合でも、過去の下書きを呼び出せるようにする

### Purpose

- 下書きが不本意に消えるのを防げる
- 前に書いたことが残っていて、そっちも書きたいけど先に新しいことを書きたい…という場合に前に書いたことをコピペしてどこかに置いておく必要がなくなる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
Related to #7098

**Comment by tamaina** [comment]
duplicate ofでいいかしら

**Comment by kakkokari-gtyih** [comment]
よさそう

**Comment by tamaina** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/7098
