### ISSUE TITLE
emojisエンドポイントにlocalOnlyを含めてほしい

### ISSUE THREAD

**Issue by 1Step621** [syuilo/Misskey#13158]
### Summary

emojisエンドポイントにlocalOnlyの情報を含めてほしいです。

### Purpose

localOnlyの絵文字をフィルターしたいときなどに、大量のAPIリクエストをすることになってしまうため。(https://github.com/misskey-dev/misskey/pull/13134#issuecomment-1921904247)

すでにisSensitiveは含んでいるため、localOnlyを含めるのも妥当だと思います。

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by anatawa12** [comment]
1STEP621 さんがバックエンド実装できるなら #13134 で追加しちゃっていい気がする。実装のために必要な範囲になると思うし
