### ISSUE TITLE
連合向けのノートの配信が冗長

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#13191]
### Summary

Noteを配信する際に、AP標準のHTML表現 (content) の他に、Misskey生表現 (_misskey_content, source...) も配信しているが、
少なくとも テキスト, タグ, 絵文字, URL, メンション のみの投稿であれば、AP HTML (content) のみで安全にやりとり出来るはず。
なので、現状ほとんどのノートで冗長な表現で配信している。

また、不要なspanも多い状態である。
```
  content: '<p><span>テキスト </span><a href="https://example.com/tags/タグ" rel="tag">#タグ</a><span> </span><a href="https://example.com/">https://example.com/</a><span> </span>🍊<span> </span>​:emoji:​<span> </span><a href="https://example.com/@b" class="u-url mention">@b</a></p>',
  _misskey_content: 'テキスト #タグ https://example.com/ 🍊 :emoji: @b',
  source: {
    content: 'テキスト #タグ https://example.com/ 🍊 :emoji: @b',
    mediaType: 'text/x.misskeymarkdown'
  },
```

### Purpose

長いテキストはネットワークトラフィックの他に署名等の付加も増えるので可能なら減らしたい

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
Related to https://github.com/misskey-dev/misskey/issues/10228

**Comment by kakkokari-gtyih** [comment]
> Related to #10228

Duplicateかも

**Comment by mei23** [comment]
> Related to https://github.com/misskey-dev/misskey/issues/10228

建てて全然忘れてたわね

**Comment by mei23** [comment]
こっちの方がふさわしいのでこっちいかす
