### ISSUE TITLE
コードブロックで言語名"aiscript"が反応しなくなった

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#13204]
### 💡 Summary

MFMのコードブロックで言語名`aiscript`が認識されなくなっているようです。
`is`、`ais`は正常に認識されています。
また、代わりに`AiScript`が認識されるようになったようです。

### 🥰 Expected Behavior

言語名`aiscript`のコードブロックがAiScriptの文法でハイライトされる

### 🤬 Actual Behavior

フォールバックのJavaScript文法でハイライトされる

### 📝 Steps to Reproduce

````
```aiscript
@(some){ `{ code }here` }
```
````

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
EMUI12.0.0
* Browser:
Chrome
* Server URL:
misskey.io
* Misskey:
2024.2.0-io.1c
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
shiki v0では大文字小文字の区別がなかったのが、区別されるようになったとかかし（とくに当該箇所は変更してないのでshiki側が変わった説が濃厚）

**Comment by kakkokari-gtyih** [comment]
vscode拡張のほうを修正した
