### ISSUE TITLE
外部リンクに使用できるURLを制限する機能

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13207]
### Summary

投稿に含まれる外部リンクを検査し、許可されていないドメインが含まれていた場合は投稿を許可しない機能をオプトインでつける

### Purpose

技術的な制約により、中央集権型のプラットフォームと比べて万が一のときの後始末が難しいため。
具体的には昨日のすしすきーとbackspace.fmに現れたスパマー対策のため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
「昨日のすしすきーとbackspace.fmに現れたスパマー」というのがわからないけど、例えば`example. com`みたいにいくらでも回避ができそう

**Comment by samunohito** [comment]
> 例えばexample. comみたいにいくらでも回避ができそう

MFMパーサによってリンクとして認識されなければ一定の効果はあるのではと思います。
リンク文字列にもならないし、URLプレビューにもならないし…

**Comment by syuilo** [comment]
> 一定の効果

これはどんな効果？
スパムが減るということ？

**Comment by KisaragiEffective** [comment]
![image](https://github.com/misskey-dev/misskey/assets/48310258/46488b6e-fde3-436f-9b30-dccbae7d1a76)

具体的にはこれの話をしています(※具体的な名称は伏せています)

**Comment by KisaragiEffective** [comment]
> > 一定の効果
> 
> 
> 
> これはどんな効果？
> 
> スパムが減るということ？

それも込みです。あとは「モデレーションの手間」が高くなることを防げます。

**Comment by syuilo** [comment]
これかしら
![IMG_5862](https://github.com/misskey-dev/misskey/assets/4439005/a14b2f57-54fb-4d21-9847-5b8b29956b1a)

**Comment by tamaina** [comment]
あったわ（管理画面から見つけられなかった

**Comment by kakkokari-gtyih** [comment]
それの投稿禁止版を用意すると確実そう

**Comment by samunohito** [comment]
上記はチャンネルには効かないし、冒頭の機能も検討したほうが良いように思える

**Comment by u1-liquid** [comment]
https://github.com/misskey-dev/misskey/issues/13114 とやりたいことは同じな気がする

**Comment by samunohito** [comment]
オプトインとのことだし、そこまで大きな反対の声は無いように思えます。
デフォルトは空欄だろうし、それなら挙動も変わらないはず

**Comment by tamaina** [comment]
（とはいえ現状の実装のセンシティブワードも、引用元や返信先に通知されないことが望ましい気もする）

**Comment by KisaragiEffective** [comment]
実際にどのような運用が為されるかは未知数ですが、提案の意図としてはサーバーの発展に寄与しない明らかなスパムに対して適用されることを想定しています

**Comment by tkmrgit** [comment]
機能しないリンク貼るスパム来た。
スパムアカウントはソースが公開されていてこちらが仕込まれている模様
ttps://github.com/EdamAme-x/misskey-nuke

**Comment by samunohito** [comment]
- ノート投稿時にmetaの情報を使ってキーワード検索し、ヒットしたらエラーを返却
- コントロールパネル -> モデレーション -> センシティブワードの下に追加。設定内容および設定方法の方式はセンシティブワードを踏襲

…で実装していいです？

**Comment by syuilo** [comment]
> * ノート投稿時にmetaの情報を使ってキーワード検索し、ヒットしたらエラーを返却
> * コントロールパネル -> モデレーション -> センシティブワードの下に追加。設定方法の方式はセンシティブワードを踏襲
> 
> …で実装していいです？

👍
