### ISSUE TITLE
7fc1d77 以降に更新するとタイムラインが正常に表示・操作できなくなる

### ISSUE THREAD

**Issue by okinjp** [syuilo/Misskey#13219]
### 💡 Summary

7fc1d77893631f7bc792c7d6d5398aba65a331c9 以降に更新するとタイムラインが正常に表示・操作できなくなる

### 🥰 Expected Behavior

すべてがうまくいく

### 🤬 Actual Behavior

TLが表示できなくなりTL切り替えやページ遷移なども作動せずコンソールにエラーが残る
ユーザーページや個別投稿のURLを直接開くことは可能

コンソールログ
[a1.miclear.casa-1707482555884.log](https://github.com/misskey-dev/misskey/files/14221804/a1.miclear.casa-1707482555884.log)

https://github.com/misskey-dev/misskey/assets/38905988/d46fb628-2aa3-4bb3-895a-50ddd0722eec

### 📝 Steps to Reproduce

1. 7fc1d77893631f7bc792c7d6d5398aba65a331c9 に更新する
2. TLが空になりまともに操作できなくなる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2
* Browser: Microsoft Edge 121.0.2277.83 (公式ビルド) (64 ビット)
* Server URL: https://a1.miclear.casa
* Misskey: 2024.2.0-beta.10 (7fc1d77893631f7bc792c7d6d5398aba65a331c9)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker compose
* Misskey: 2024.2.0-beta.10 (7fc1d77893631f7bc792c7d6d5398aba65a331c9)
* Node: 20.10.0
* PostgreSQL: 15
* Redis: 7
* OS and Architecture: Ubuntu 22.04.3 LTS amd64
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
なんか無限ループが走ってそう

**Comment by tamaina** [comment]
too much recursion (firefox

![image](https://github.com/misskey-dev/misskey/assets/7973572/eba8b186-235d-429e-b9a3-6bf7979a4cca)

**Comment by tamaina** [comment]
vue 3.4.16以降がだめ

**Comment by tamaina** [comment]
https://github.com/vuejs/core/issues/10214 / https://github.com/vuejs/core/pull/10232 に関係がありそう

**Comment by tamaina** [comment]
Vue Landに投げてみた(

https://discord.com/channels/325477692906536972/1205559733101010984

**Comment by tamaina** [comment]
- Vueのバージョンを下げれば動きはするが、今後一歳vueのバージョンが上げられないのは相当まずいのでこの問題は後回しにできない
- 私はVueの内部構造に詳しいわけではないので何が起きているのかわからない（解決策がわからない
  * （読み解けばいい話だけど私が読むより詳しい人に聞いた方が早そう）

**Comment by tamaina** [comment]
tasukete

**Comment by syuilo** [comment]
3.4.15にするか

**Comment by kakkokari-gtyih** [comment]
timeline.vueの`src`周りの実装が良くないみたい（コンポーネントを消したりつけたりして総当りした）

**Comment by kakkokari-gtyih** [comment]
`withReplies`と`onlyFiles`が悪さしてそう

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/004a068f-5275-4e6f-a034-db7f0d2941ad)

computed内で別のcomputedの値を参照したら無限ループに入るっぽい（ここを消したら普通に動いた）

**Comment by syuilo** [comment]
あーそれはアカンわね

**Comment by kakkokari-gtyih** [comment]
なんで今まで動いてたんだろう（）

**Comment by syuilo** [comment]
むしろなぜ今まで動いてたのか

**Comment by kakkokari-gtyih** [comment]
じゃあどう対応すればいいのかしら（これ構造的にお互いに影響し合う値なので…）（watch使うとか？）

**Comment by tamaina** [comment]
computedじゃなくてただのfunctionを作って見れば良いんじゃないかしら

**Comment by kakkokari-gtyih** [comment]
![image](https://github.com/misskey-dev/misskey/assets/67428053/c150a30b-e59b-4528-b6c0-6e3b52ada274)

**Comment by tamaina** [comment]
↑functionが無限ループするだけだわ

**Comment by syuilo** [comment]
> じゃあどう対応すればいいのかしら（これ構造的にお互いに影響し合う値なので…）（watch使うとか？）

そのような構造にしないのが正攻法

**Comment by kakkokari-gtyih** [comment]
> これでいけた

の方法はどう？

**Comment by tamaina** [comment]
`{ withReplies: boolean; onlyFiles: boolean; }`を吐き出す関数を作る方がスマートな気がした

**Comment by tamaina** [comment]
（もしくはそういうcomputedにしちゃうとか

**Comment by kakkokari-gtyih** [comment]
> { withReplies: boolean; onlyFiles: boolean; }を吐き出す関数を作る方がスマートな気がした

なるほど

> （もしくはそういうcomputedにしちゃうとか

これはMkPopupMenuから値のセットができなくなるのであかんかも

**Comment by kakkokari-gtyih** [comment]
とりあえずなおした #13248

**Comment by tamaina** [comment]
> これはMkPopupMenuから値のセットができなくなる（そのために煩雑な処理を追加する必要がありそう）のであかんかも

（MkSwitch、popupが呼ばれるごとに新しくref/computedを作るのがベターではあったりする）
