### ISSUE TITLE
リアクションが多いときに表示される"もっと！"からノートの詳細を開けるようにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#13213]
### Summary

リアクションの種類が多い時、TL等では"もっと！"という表示だけがあり、そこを押してもノートの詳細(リアクションが全て表示される)やリアクション一覧が表示される訳ではないのが、表示に対して少し非直感的な気がしたので、ノートの詳細が開くようになれば良いのではないかと思いました。

### Purpose

何も起こらないのに時々押してしまうため
より直感的な表示にするため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by 1STEP621** [comment]
WIP in #12935

**Comment by Sayamame-beans** [comment]
issue検索は掛けたつもりでしたが、見つけられていませんでした…
ありがとうございます。
duplicate of #11888
