### ISSUE TITLE
pagesのリンクを張ったとき、OGPのアドレスが間違ったものになっている

### ISSUE THREAD

**Issue by osapon** [syuilo/Misskey#13214]
### 💡 Summary

マストドンにリンクを張ったときに気がつきましたが、OGPのURLでは「/pages」が抜けているようで、リンク先のカードの方をクリックするとページが開きません。
（参考） https://mstdn.nere9.help/@osapon/111900010857524107

### 🥰 Expected Behavior

OGPのリンク先が
https://misskey.io/@AureoleArk/pages/30min
になる

### 🤬 Actual Behavior

OGPのリンク先が
https://misskey.io/@AureoleArk/30min
になる

### 📝 Steps to Reproduce

1. pagesのリンクをマストドンに貼る。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Windows 10
* Browser:Firefox 123.0b8
* Server URL:misskey.io
* Misskey:2024.2.0-io.1f
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by acid-chicken** [comment]
👀 https://github.com/misskey-dev/misskey/blob/7a8cf274ca8a3a738f7bf7045ee7c97b22482d71/packages/backend/src/server/web/views/page.pug#L6
