### ISSUE TITLE
リアクションでノートを検索できるようにする

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13253]
### Summary

現在の検索UIに、リアクションがついているかどうかの判定を加えてほしい

### Purpose

1. ワードチョイスというのはバラバラで、現在の検索やアンテナのUIだとそれらを統一して拾うのが難しい→リアクションで検索できるようになったら(おおよそ)そのノートがどういったジャンルに分類されるのか見当がつくのでトピックごとにノートを見たい時に便利
2. 無言のノートが検索で拾われる確率が上がる

(将来に向けての拡張: このリアクションがこれだけついている、などノート内のリアクションに占める割合や、絶対数を検索できるようになるとなお良さそう)
### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #13426
