### ISSUE TITLE
フォロー解除のモーダルでユーザー名がMFMの通常のレンダリングがされてしまう

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13258]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/7973572/a024a322-6d18-4c61-a438-010c4a7853fe)

https://koliosky.com/notes/9pl0ml6dwy

### 🥰 Expected Behavior

MFM簡易レンダリング

### 🤬 Actual Behavior

MFM通常レンダリング

### 📝 Steps to Reproduce

1. あるユーザーの名前にMFMを設定する
2. そのユーザーをフォロー解除しようとする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey: 2024.2.0-beta.9
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
一番簡単な解決方法はユーザー名を`<plain>`で囲むことだけどちゃんと直したい気がする
ただそうなるとモーダルでMFMを使ってるところ（特にPlayなど）は打撃を受けるのでちゃんとpropsなりで制御できるようにする必要がありそう

**Comment by 1STEP621** [comment]
Related to #9957 (Duplicateかも)

**Comment by zyoshoka** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/9950#issuecomment-1431761653, #9957
