### ISSUE TITLE
新規ノートが投稿されたときの音を再生するかどうか、デフォルト値を切り替えられるようにする

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13255]
### Summary

新規ノートが投稿されたときの音のデフォルト値を切り替えられるようにする

### Purpose

特にmisskey.ioだと新規登録した後にLTLへ切り替えた瞬間にピコピコうるさい+設定の動線が微妙に良くないので、切り替えるまでの間ずっとあの音を聞くことになり辛いため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
個人的にははじめからオフでいいと思っている

**Comment by Sayamame-beans** [comment]
その辺り、サーバーによって思想の違いがありそうなので、 https://github.com/misskey-dev/misskey/issues/12952 で上手く解決出来ないでしょうか…

**Comment by kakkokari-gtyih** [comment]
もちろん #12952 で全部解決するけど、技術的な懸念点が多くてウエイトが重そう（実装に時間がかかりそう）なので暫定的にどうすべきかなぁといった感じ
（それはio独自アプデで解消してくれって話かもしれないけど）

**Comment by kakkokari-gtyih** [comment]
→ #12952 でまとめてやるので良さそう

**Comment by kakkokari-gtyih** [comment]
Duplicate of #12952
