### ISSUE TITLE
禁止ワードを含んでいてもリモートノートはエラーにならない ←なぜ？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13279]
### Summary

禁止ワードを含んでいてもリモートノートはエラーにならない ←なぜ？

### Purpose

なぜ？

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
結構緊急的に直しちゃったけど、なぜこうなっていたかは教えて欲しい

**Comment by samunohito** [comment]
- あくまでローカルへの投稿を抑止する認識でいたため
- リモートは抑止機能が他にもあるため（サーバミュート等）

リモートはどうするか当時のissueで聞けばよかったと反省

**Comment by tamaina** [comment]
普通のサーバーから来るので他の機能で抑止できないっす…
