### ISSUE TITLE
Custom feeds機能

### ISSUE THREAD

**Issue by uwajam** [syuilo/Misskey#13270]
### Summary

Blueskyのようにユーザーが独自のアルゴリズムでタイムラインを構築できる機能

### Purpose

Blueskyのが便利だったため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Funyami** [comment]
Blueskyではアンテナの強化版をユーザーがホストしてるはず

**Comment by syuilo** [comment]
> Blueskyのように

詳しく知らないので詳細をお願いしたいです

独自のアルゴリズムというのは具体的にどのようなものかしら

**Comment by Funyami** [comment]
misskeyでのAntennaServiceの一部をサードパーティーにホストさせてcheckHitAntennaを自由に条件付けできるようにしたようなものです

**Comment by 1STEP621** [comment]
既にアンテナとして似たような機能があるのであれば、ユーザーがホストする機能として新たに生やすと混乱しそう

**Comment by Funyami** [comment]
新しい機能として生やさなくてもアンテナに共有とセルフホスト付けたら済む気はする

**Comment by anatawa12** [comment]
サードパーティがホストするというのがあまり理解できてないです。HTTP POSTが投稿のたびに送られるみたいなものです？

**Comment by anatawa12** [comment]
アンテナの共有は #11132 が既存にあります

**Comment by 1STEP621** [comment]
Blueskyのカスタムフィードは単に負荷分散のためにユーザー側でホストするようにしていると思うので、Misskeyでやるにはメリットが薄そう(特に中〜小規模なサーバーではわざわざセルフホストしてまで細かい調整をやりたいと思う人は少なそう)

**Comment by Funyami** [comment]
ユーザーによるアンテナのホストでアンテナを細かく調節できるようになれば、ユーザ発のツールがアンテナとしてmisskey内で完結できるようになるので利便性が向上するはず(Blueskyには renotes.io に相当するカスタムフィードが存在する)

**Comment by anatawa12** [comment]
> サードパーティがホストするというのがあまり理解できてないです。HTTP POSTが投稿のたびに送られるみたいなものです？

に対する :+1: は肯定と受け取っていいですかね

アンテナがGTLを対象にしてる以上GTLの各noteに対してHTTP POST作成すると送信コスト(ネットワーク的)がまぁまぁ無視できなくなってきそうだと思いました。

**Comment by syuilo** [comment]
現実的ではないわね

**Comment by anatawa12** [comment]
全GTL投稿を外部に送信するのは現実的ではなく、またアンテナを共有したいという要望は別途 #11132 が存在するためClose as not planned (duplicate / won't fix)としますね

**Comment by anatawa12** [comment]
(closeしたけどクライアント向けwebsocket使えば似たこと独自に実装は可能かもと思いました)
