### ISSUE TITLE
メモリやRedisでキャッシュするのをやめる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13277]
### Summary

CacheService (メモリ/Redisで別腹でデータを保持するの)をやめる

### Purpose

- データベースの他にデータを保持する箇所があるのは複雑
- リードレプリカが設定できるようになったためそれで十分では
- Redisに保持する場合そちらに負荷がかかる
- メモリに保持する場合、Misskeyマシンで消費するメモリが増える（メモリリークの原因になるかもしれない）

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by samunohito** [comment]
FTTを取っ払うという事でしょうか…？

**Comment by tamaina** [comment]
FTTじゃない、CacheServiceだけ

**Comment by syuilo** [comment]
リードレプリカあるといってもポスグレよりRedisの方がコストが安そう&スケールしやすそう

**Comment by tamaina** [comment]
わかる、まあ複雑なのは気をつけてuserはラッパーをつければいいか… 

Redisのmessageを積極的に使いたい感がある（ユーザー削除とかで

**Comment by u1-liquid** [comment]
TTLは長くても30分程度でいい説はある
