### ISSUE TITLE
ノートが自動で畳まれる条件をコンポーネントの実際の大きさにしたい

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#13286]
### Summary

現在は特定のMFM断片の検知や文字数カウントなどによってノートを畳む条件を決めていますが、
それを「ノートのclientHeightが一定値を超える」という条件一つに変更したいです。

### Purpose

- MFM関数の引数によって畳むかどうか分けるのが困難
- 抜け道が出来やすい

といった問題を解消できると思います。

具体的な手順としては、
- ノートの畳むべき領域を<div ref="collapsibleArea">で囲っておく
- 初期状態ではノートは畳まれているが「もっと見る」ボタンは表示されないようにしておく
- onMountedイベントでcollapsibleArea.value.clientHeightを計測し、一定値を上回るなら「もっと見る」を表示、下回るなら畳み状態を解除

という感じになります。
コンポーネントが一度レンダリングされるまで大きさが分からない以上どうしてもチラつき覚悟の処理になりますが、この手順で違和感を最小限に抑えられると思います。

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by anatawa12** [comment]
Duplicate of #13266
