### ISSUE TITLE
禁止文字列を正規表現で与えられるようにする

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13281]
### Summary

continuation of #13207: 禁止文字列を正規表現でも与えられるようにする。	

### Purpose

ダミーの区切り文字を入れてマッチングを妨害する行為が見られるため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
なってない？？

**Comment by KisaragiEffective** [comment]
そうなんですか？？固定文字列しか与えることができないと思っていたので、コードを読んでみます

**Comment by tamaina** [comment]
なんなら説明書きにも書いてあるし…

**Comment by KisaragiEffective** [comment]
なってました、ごめんなさい
