### ISSUE TITLE
「リモートはいいねのみ」でリアクションがいいねに変換された際、❤ではなく❤️になる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13298]
### 💡 Summary

「リモートはいいねのみ」でリアクションがいいねに変換された際、通常の❤=\u2764ではなく❤️=\u2764\ufe0f になり別のリアクションとして扱われる

…これ仕様だったりする？

### 🥰 Expected Behavior

❤ (U+2764)になる

### 🤬 Actual Behavior

❤️ (U+2764, U+fe0f)になる

### 📝 Steps to Reproduce

1. 「リモートはいいねのみ」としたノートを投稿
2. リモートからカスタム絵文字などいいねではないリアクションをつける

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 
* Browser:
* Server URL: p1.a9z.dev ↔︎ misskey.io
* Misskey: 2024.2.0-beta.11
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2024.2.0-beta.11
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
(多分違いそうです)

**Comment by mei23** [comment]
正規化後にリアクションを上書きする場合、正規化後の`U+2764`を使用する必要があるから多分バグだわね

**Comment by nryeouo** [comment]
↓のハートには `U+FE0F` がついている
https://github.com/misskey-dev/misskey/blob/b8800b8b95712ed25266ba294850963b4643f04f/packages/backend/src/core/ReactionService.ts#L123

**Comment by tamaina** [comment]
（仕様なのかバグなのかしゅいろから回答もらわないと…

**Comment by tamaina** [comment]
これバグだったんだ…

**Comment by tamaina** [comment]
UI上で外から来た:heart:に自分のを押せないんだけど

**Comment by KisaragiEffective** [comment]
？？？

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/2c6f25b710b4f8095458fe88ddd56e6c6a41d006/packages/frontend/src/emojilist.json#L1257

が[ "2764", "fe0f" ]しかなくて正規化後のリアクションがユニコード絵文字として参照されていない

**Comment by KisaragiEffective** [comment]
つまりいたいじせれくたがついたものをそのJSONファイルの追加したらうまく行くようになる可能性がある…？

**Comment by tamaina** [comment]
異体字セレクタなしに置き換えちゃった方が良さげ

**Comment by tamaina** [comment]
んーこれでもアレだな、

https://github.com/misskey-dev/misskey/blob/0a0af6887a829a45d2982bc61c319e76445f66a9/packages/frontend/src/store.ts#L122

も異体字セレクタありなんだな

**Comment by tamaina** [comment]
「サーバーから送られてきた異体字セレクタなしをクライアントでは異体字セレクタありに読み替える」みたいな感じでいいんじゃない（クソ適当）

**Comment by KisaragiEffective** [comment]
それは新規設定が変わるだけなのでそんなに問題なさそう(？)

**Comment by tamaina** [comment]
古い設定のひとが異体字セレクタなしに置き換えると、多分ReactionViewerのリアクションを押した瞬間などになしが履歴に残り続ける可能性がある（のでクライアント側はありで統一したほうがいいのではという話
