### ISSUE TITLE
ノートの文字装飾をボタンなどで挿入またはコピーできるようにしてほしい

### ISSUE THREAD

**Issue by HitoshiroKyoka** [syuilo/Misskey#13296]
### Summary

ノートの文字装飾をボタンなどで挿入またはコピーできるようにしてほしい。
たとえばノート入力のモーダルウィンドウにボタン一覧が折りたたまれているとか。

### Purpose

いま文字装飾への導線が存在しないので、ユーザーが独自にまとめたノートや記事をもとに手打ちしていますが、これをボタンでできるようになると利便性が高まると思います。

※余談
私は[このノート](https://misskey.io/notes/9b5s4x3fip)の作者です。一年前のノートにもかかわらず毎日リノートされているので、misskeyの機能でなんとかならないかなあ……と思いました。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Srgr0** [comment]
少し分かりにくいかもしれませんが、機能としては既に実装されています。
<img width="900" alt="ScreenShot 2024-02-14 15 47 43" src="https://github.com/misskey-dev/misskey/assets/66754887/77a04f65-9ef7-4307-826f-745ae18a1226">
<img width="901" alt="ScreenShot 2024-02-14 15 48 30" src="https://github.com/misskey-dev/misskey/assets/66754887/da9bf7a3-95dc-4e67-b766-7769ec92280e">

**Comment by HitoshiroKyoka** [comment]
あったんですね💦　まったく気づいていなかったです。ありがとうございます。
当issueはCloseしますね。
