### ISSUE TITLE
"update SPDX-FileCopyrightText"を一回revertしてほしい

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#13290]
### 💡 Summary

Cypressのworkflowが落ちていますが、 9b5aeb76d8c9372d67058c512597152b6bf222f2 をrevertすることで復旧できることを確認しています。
どうやらこのコミットにSPDX-FileCopyrightTextに関係ないソースコードの変更が紛れ込んでいるようです。
diffがあまりにも見づらいのでバグの原因の発見が困難です。SPDX-FileCopyrightTextの変更が機械的に行えるのであれば、一回revertしてからSPDX-FileCopyrightTextの変更とそれ以外の変更を分けて再コミットをお願いします。

### 🥰 Expected Behavior

9b5aeb76d8c9372d67058c512597152b6bf222f2 はSPDX-FileCopyrightTextの変更だけを含んでいる

### 🤬 Actual Behavior

9b5aeb76d8c9372d67058c512597152b6bf222f2 はSPDX-FileCopyrightTextに関係ないソースコードの変更を含んでおり、それが原因でテストが落ちている

### 📝 Steps to Reproduce

revert 9b5aeb76d8c9372d67058c512597152b6bf222f2

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
git diffを機械的にフィルタした結果以下の変更が混ざってそう。
なんかVSC等のformat on saveが意図せず紛れ込んだのが多そう。`?.`が`.`になってるのがちょくちょくあるのでそれが影響受けてそうではある


https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-ac79d1aac38b5e88ea35cd1613ce46ae2dc99261d815b83fc7d99b13eb96a9a2
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-565c9366e30749f7ea62869180a3d3558539f34930e7fde8c945ed39803be27f
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-214fa38c5741ce56db200b6def1962dedf8a5afd1b507100ed9c7002fb4b78f6
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-2de51083287e0e8b0f9694df3642dcd40761b041a98c98a3bbf5a66e977e3b64
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-6e45f35eb4973471c0b352207882a3aa77949653f498012aeaf621b8c905d907
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-38840c79d94daf50733180ac2123fd0a1d5a659800e43249dd6e78673b65c6f7
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-a9a38437fa14259f6fea0248c527d691b8c13862fbae0321c4c539c1991f73e3
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-34f1b9013dd55862b056b4ce48006dc052e12234b9edcf1512240dbeb44f4228
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-e2aa1d6f54c1d6c73dadd800a15a89eb363f5470fd6387547a0205f0e1b9cd79
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-abee36d56ff6b42e1f347f172aa90821e23c438d2f233adbc7cabad3edfea921
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-809809e7d732b2e663ea2a1922ccc40f389e9ea68f12f87c5f3a999fb9253457
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-9b79537fce705c159671c9f892e89ee617684f97394691bb6e70b2abc26743a0
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-d9325ab759ee5edb9f945f7b211e5a5490c67abef1664544a829354537af069f
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-460b96c6922c0410a68ec034ced9b5460dead41685e1cbee5378342f5b739598
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-8ffc5ad4c7de35088558d95b2241a9236e32a1d562dd465b12a6a894ca146d63
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-ab2ecf2ba80776001bf846feac43719358b3a79d5c465c958d395c4c123348f2
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-2fe901a235d07f38fcdf7cdca144915263d5cd7c22f02708564a642591182808
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-c5f536ca886ebae9218712d9198c21714440b7c34ec4c5ee328d5c22187c3dff
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-adf0aced036c26d107732eef4eebb85119dbb37c3e155b140bc7a9fc3a73c7a8
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-c4397fba304034cc48831eaa6c2c30c1264aabcff5b0da20c88da1eb0f08a1a8
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-b40dfa2cff0cf76f082787df49124e58fd8dfe125fd5d58580954ca841ee8867
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-060e6f6bb76363f32a54f54f04efe715a36babd91f4b45ba248122c0bbb09391
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-0b6a4d139c154efde885e259dd740d8bb986553f46284e7269f3025e62881dba
https://github.com/misskey-dev/misskey/commit/9b5aeb76d8c9372d67058c512597152b6bf222f2

**Comment by tamaina** [comment]
目grep中

候補1

https://github.com/misskey-dev/misskey/compare/6afd2dc6322ff0746a34d98227bc1b0ca4b0b0d9...9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-c4397fba304034cc48831eaa6c2c30c1264aabcff5b0da20c88da1eb0f08a1a8

**Comment by tamaina** [comment]
2

[packages/frontend/src/ui/visitor.vue](https://github.com/misskey-dev/misskey/compare/6afd2dc6322ff0746a34d98227bc1b0ca4b0b0d9...9b5aeb76d8c9372d67058c512597152b6bf222f2#diff-0b6a4d139c154efde885e259dd740d8bb986553f46284e7269f3025e62881dba)

**Comment by tamaina** [comment]
以上？

**Comment by mei23** [comment]
頑張れば探し出せるけど、探し出したところで結局やることはrevertなのでSummaryの通りとっととrevertした方がいい気がするのだわ

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/e0c32da2-c13b-4cb2-bc49-f933ae7cf44e)

なんかまだ怪しい感じがある

**Comment by tamaina** [comment]
なら大丈夫そう

**Comment by anatawa12** [comment]
落ちてる[Docker](https://github.com/misskey-dev/misskey/actions/runs/7889245277/job/21528652541)は #13268 ですね。

https://github.com/misskey-dev/misskey/actions/runs/7889245925/job/21528654105 はなんか別そう。

cypressが関連する frontend は 通ってますね: https://github.com/misskey-dev/misskey/actions/runs/7889245922

**Comment by tamaina** [comment]
e2eはなぜかre-runしたらなおった
