### ISSUE TITLE
Moderators cannot access the list of assignee in Role page, even if the role is assignable by moderators

### ISSUE THREAD

**Issue by ltlapy** [syuilo/Misskey#13301]
### 💡 Summary

>「モデレーターのメンバー編集を許可」がオンであるロールでも、モデレーターは（コントロールパネルのロールページから）アサインされたユーザー一覧を閲覧できない

モデレーターによる一括管理ができず、Adminを介しなければならない

### 🥰 Expected Behavior

「モデレーターのメンバー編集を許可」がオンであれば、モデレーターにもロールページからアサインされたユーザー一覧が閲覧できるようになる

### 🤬 Actual Behavior

Adminロールを付与しない限りモデレーターは閲覧できない

### 📝 Steps to Reproduce

1. （isAdminフラグがfalseで、Adminロールにアサインされていない）あるユーザーにモデレーターロールを付与する
2. 「モデレーターのメンバー編集を許可」がオンにされているロールを作成する
3. ①で付与したユーザーから、コントロールパネルから②のロールページにアクセスする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Debian GNU/Linux 11.8 (bullseye) with Linux 5.10.0-27-amd64
* Browser: 120.0.6099.199 (Official Build) built on Debian 11.8, running on Debian 11.8 (64-bit) 
* Server URL: https://hoto.moe
* Misskey: 2023.12.2
```

### 🛰 Backend Environment (for server admin)

```markdown
Unknown
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Hoto-Cocoa** [comment]
As server administrator of hoto.moe instance, I will left some backend information to here.

### 🛰 Backend Environment (for server admin)
```
* Installation Method or Hosting Service: Docker
* Misskey: 2023.12.2
* Node: 20.10.0
* PostgreSQL: 15.3
* Redis: 7.0.11
* OS and Architecture: Ubuntu 20.04.2, amd64 (Docker host)
```

**Comment by ltlapy** [comment]
Fixed by https://github.com/misskey-dev/misskey/commit/2b41b1f631e6a3135ac201a4dceca4e38db7a0e4. Closing.
