### ISSUE TITLE
ユーザー検索で`@user@host`形式がヒットしてほしい

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#13300]
### Summary

検索→ユーザーで、`user`や`@user`は部分一致でヒットするのに`@user@host`は完全一致でもヒットしない。ヒットしてほしい。
また、`https://example.com/@user`的なリモートユーザーを指定したときは未知ユーザーでも照会が走るのに、`@user@host`では照会が走らない。照会してほしい。

### Purpose

以前はヒットしたはず＆「検索欄に`@user@host`を入れればリモートユーザーを自サーバーに持ってこれる」といったのがあるので、かかってほしい。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
https://github.com/misskey-dev/misskey/blob/3b075c9c441e8fe2d7446a7201cd1950437ba0b6/packages/backend/src/server/api/endpoints/users/search.ts#L60 https://github.com/misskey-dev/misskey/blob/3b075c9c441e8fe2d7446a7201cd1950437ba0b6/packages/backend/src/server/api/endpoints/users/search.ts#L64-L66
が原因
