### ISSUE TITLE
凍結されたユーザーによって発生した通知は表示しない/削除して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#13316]
### Summary

凍結してもノートの情報は残り、通知欄に表示され続けてしまう(はず)ので、消えるようにして欲しいです。
即時が望ましいですが、即時でなくても(リロードが必要でも)良いと思います。
Related?: https://github.com/misskey-dev/misskey/issues/7198

### Purpose

スパム等によって発生した通知が消えない

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by meronmks** [comment]
利用者側としては以下のように通知欄に残り続けてしまう為、モデレーターによって適切に対処されたのか分かりにくいのもあります。（マウスオーバーしたりクリックすると永遠にロード中になったり、エラー画面になったりはしますが）
<img width="305" alt="image" src="https://github.com/misskey-dev/misskey/assets/12034371/35f63ce8-a451-459d-9cb4-923eaf00dcb6">
ただ他の削除関連のIssuesとかもあるので単純に物理削除すればOK、とはいかないかもですが

**Comment by tamaina** [comment]
なおるか？（コードを表面的に見たところisSuspendedを見ている様子はなかった（簡単にしくめそうではある

**Comment by tamaina** [comment]
@kakkokari-gtyih
