### ISSUE TITLE
通知を削除する方法を提供して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#13317]
### Summary

タイトル通りです。

### Purpose

何らかの理由( https://github.com/misskey-dev/misskey/issues/13316 関連など?)で通知を消したい場合があります。
現状、発生した通知を消す方法は存在しないため、消せるようになると良いと思います。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
全削除ではなく個別削除が理想なので、最終的には個別削除が実装されることを望みます

**Comment by tai-cha** [comment]
通知を個別削除する場合、グループ化されたリアクションの削除とかどうするか悩ましいな

**Comment by samunohito** [comment]
個人的にですが、むしろ全削除より個別の方が欲しいです

**Comment by tai-cha** [comment]
個別削除はできると嬉しい（特に反応が少ないアカウントだと嫌な通知が残り続ける場合がある）

**Comment by syuilo** [comment]
そもそも削除自体要らない気がするわね

> 特に反応が少ないアカウントだと嫌な通知が残り続ける場合がある

嫌な通知というのがあまり想像できないけど、我慢してもらう

> 特定条件で削除するなどのスクリプトを組めるようになる

それやるならそもそも通知を作成する前の段階でやれるようにするべき

> 実績や嬉しいリアクションやメンションなどの通知が消えるのは悲しい

通知は揮発的だからそういう通知が残ることは期待してはならない

**Comment by tai-cha** [comment]
> 嫌な通知というのがあまり想像できないけど
  - ネガティブや弯曲的に嫌がらせとなりうるリアクション
  - 関係を切るほどの人間じゃない人間から飛んできたメッセージ（これも嫌な通知には個人差がある）
  - 管理者の対応が間に合わない場合のスパム
  - etc...
 
> 通知を作成する前の段階でやれるべき
- 例えば #11772 があるが、これは一度通知が来たら消えないものだと思われる
- ブロックしたら通知が作成されないとしても後からブロックしたら残る
  - これはミュートなどを考慮すれば問題がないかも 
- システムや規約的に問題ない投稿でも不快な通知というものはある（これにも個人差がある）

> 通知は揮発的だから
DBに保存されていないという意味ではそうだけどそれはあまりユーザーに伝わっている気がしないしその感覚はない
Redisもバックアップとっているところがそこそこある気がする[要出典]

そのほか
- #13337 のように非表示にする手段をユーザー任せにするという方法もなくはない

**Comment by syuilo** [comment]
> DBに保存されていない

RedisというDBには保存されてる
ただ保存される数に制限を設けている

**Comment by syuilo** [comment]
やるとしたら全削除

**Comment by Sayamame-beans** [comment]
> ただ保存される数に制限を設けている

- #11227 のように数を増やしたいという要求もあり(私もそう思っています)、ユーザーと温度感が噛み合っていない気がします

**Comment by tai-cha** [comment]
まあ全削除ならキーを削除するだけなのでパフォーマンス面の懸念は落ちる（保存されているものを読みにいく必要がない）
ただそれを踏まえても需要があるとは思っているし通知が個別削除できた方が利便性は高いと思う、天秤にかけてどちらが上になるかは完全に言い切れないけれど

**Comment by Sayamame-beans** [comment]
> 管理者からするとそうではない場合がある

私個人としては、それを各サーバーの管理者が選べるように(optionalに)するために設定項目や機能が存在すると思っています…

**Comment by syuilo** [comment]
個別削除できれば便利だし需要はあるけど、それをやると機能の趣旨が意図しない方に寄ってしまう

**Comment by syuilo** [comment]
> > 管理者からするとそうではない場合がある
> 
> 私個人としては、それを各サーバーの管理者が選べるように(optionalに)するために設定項目や機能が存在すると思っています…

それにもコストが発生するし、機能の設計思想がブレることになる

**Comment by tai-cha** [comment]
機能の趣旨をどう捉えているかに齟齬がありそう

**Comment by tai-cha** [comment]
というよりはMisskey内での通知とスマートフォンやGitHubなどの通知の概念が少し違うから理解しずらい？（他での通知があまり揮発的なイメージがない）

**Comment by syuilo** [comment]
スマホとかの通知は勝手にどんどん消えるから揮発性のイメージ

**Comment by tai-cha** [comment]
オフトピに近いけど勝手に消えないからめっちゃ溜まってる

**Comment by syuilo** [comment]
設計思想というより利用者のメンタルモデルと言った方が近いかも
個別に削除することができると、逆に考えると「削除しなければ残り続ける」みたいな印象を与える可能性が高まる

**Comment by anatawa12** [comment]
ユーザ視点としてはスパムが目障りだから消したいに対する答えとして全部消えるは強い違和感があります

**Comment by syuilo** [comment]
スパム関連であればそのユーザーをミュートなりする方が良さそう

**Comment by tai-cha** [comment]
ミュートしても通知消えないのでそれはそれでやった方がいい

**Comment by syuilo** [comment]
ミュートしたら通知消えるようにすれば良さそう

**Comment by tai-cha** [comment]
ただスパム対策だけのIssueではないと思っているのでスパム対策に限った話で終わらせたくないかも

**Comment by syuilo** [comment]
スパム以外では不要と思ってる

**Comment by tai-cha** [comment]
必要か不要かの考えは通知が流れていってあまり留まらない場合と結構通知がきて流れていく場合でも変わってきそうだと思っている（有名人に個別削除機能はあまり必要ないと思う）

**Comment by tai-cha** [comment]
ここまでで全く考えが変わらないのであればMisskeyのオーナーはしゅいろさんなのでMisskey自体には入れないのでもいいんじゃないという考えはある（けど議論し尽くせてはいないと思う）

**Comment by syuilo** [comment]
> スパム以外では不要と思ってる

個人的に必要か不要かということではなくて、現時点でソフトウェアとして当該機能は不要という判断

**Comment by syuilo** [comment]
ユーザーが望む機能を、無秩序に追加していくことはできない

**Comment by syuilo** [comment]
あと通知はデフォルトでグループ化されるから、「個々の通知」みたいなメンタルモデルにはなってないからUIが悩ましいことになる

**Comment by tai-cha** [comment]
> ユーザーが望む機能を、無秩序に追加していくことはできない

これには同意なので基本的にプラグインで解決できる方法を推してはいる
その上で私はこれに関してはMisskeyに入れるメリットがあると思っていたので全くないという判断なのであればプラグインのフックを増やしたりフォークを使えばいい話になってくるかなとは思います

**Comment by tai-cha** [comment]
> あと通知はデフォルトでグループ化されるから、「個々の通知」みたいなメンタルモデルにはなってないからUIが悩ましいことになる
これスマホの通知みたいに展開できればいいのでは？

**Comment by tai-cha** [comment]
> ミュートしたら通知消えるようにすれば良さそう
探したけど意外とIssueない？探し方が悪いかしら

**Comment by samunohito** [comment]
似たようなものはありました。
https://github.com/misskey-dev/misskey/issues/12751

…が、ユーザのミュートに追従してという切り口ではなさそうです

**Comment by samunohito** [comment]
結論としては…

- 通知を削除する機能は「設けない」
- 別issueで考える
  - ユーザミュートを通知に反映させる
  - 通知にプラグインのhookを生やす

でOKでしょうか

**Comment by samunohito** [comment]
（やらないならやらないで、closeしたい気持ちが強い）

**Comment by tamaina** [comment]
個人的には、ミュートや凍結がしっかり反映されていれば通知を消す機会はないかなと

**Comment by tamaina** [comment]
（FTTも全削除機能欲しい）
