### ISSUE TITLE
リアクションの総数を表示するモードを作ってほしい

### ISSUE THREAD

**Issue by pan090908097** [syuilo/Misskey#13338]
### Summary

リアクションの総数を表示するモードを作ってほしい

### Purpose

フォルダで展開するように1000リアクション＞展開してリアクションが出るような?
上部に表示しても構わない

どれくらいの反応があるか？というのがSNS移住、仕事につかえるかの判断基準になる
部分があるとXでミスキーについて皆の会話を検索していて感じた

数値的にバズりを可視化することも求められている

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by 1STEP621** [comment]
Related to #13212
