### ISSUE TITLE
Migration "Reversi1705475608437": Do we have the table `reversi_matching`?

### ISSUE THREAD

**Issue by outloudvi** [syuilo/Misskey#13360]
### 💡 Summary

Seems that a new migration, "Reversi1705475608437", asks for some change on the table `reversi_matching`, which doesn't seem to exist in the code.

### 🥰 Expected Behavior

The migrations should be finished correctly.

### 🤬 Actual Behavior

```
Error during migration run:
QueryFailedError: index "IDX_b604d92d6c7aec38627f6eaf16" does not exist
```

### 📝 Steps to Reproduce

1. Run `pnpm migrateandstart`

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): N/A
* Browser: N/A
* Server URL: 
* Misskey: 2024.2.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Docker
* Misskey: 2024.2.0
* Node: 20.10.0
* PostgreSQL: 12.2
* Redis: 7.0
* OS and Architecture: Linux, x86_64
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
There is migration creating `reversi_matching` table in init.js.

https://github.com/misskey-dev/misskey/blob/b0030d148db99b76d6283a8692a89671760665d0/packages/backend/migration/1000000000000-Init.js#L143

**Comment by outloudvi** [comment]
Thanks, @anatawa12! Seems that there's something missing from my side.
