### ISSUE TITLE
フォロー、フォロワーの一覧を非公開にしていてもリモートサーバーで表示するとそのリモートサーバーにいるフォロワー分に限り見えてしまう

### ISSUE THREAD

**Issue by meronmks** [syuilo/Misskey#13362]
### 💡 Summary

フォローおよびフォロワーの一覧を非公開にしていたとしてもリモートサーバーで表示すると見えてしまう。
ただしすべてではなくあくまで該当のリモートサーバーのユーザをフォロー、フォロワーの一覧のみ
（#12964 と同じくこの二つについても公開設定が連合していない？）

### 🥰 Expected Behavior

フォローおよびフォロワーの一覧の公開をオフにするとリモートサーバーからもそれぞれ表示されなくなる。
※ただし #13127 のようにモデレーションに影響が出ることが考えられる為権限がある場合は見えるように

### 🤬 Actual Behavior

フォローおよびフォロワーの一覧を非公開にしていてもリモートサーバーからは一覧が表示される

### 📝 Steps to Reproduce

1. フォローもしくはフォロワーの公開設定をオフにする
2. リモートサーバーでプロフィールを表示し、フォロー、フォロワーの数等の表示がある（そのリモートサーバーにフォローしている人、フォロワーが居なければ0と表示されるが、いる場合はその人数とユーザが閲覧できる）

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):any
* Browser:any
* Server URL:any
* Misskey:2024.2.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:any
* Misskey:2024.2.0
* Node:any
* PostgreSQL:any
* Redis:any
* OS and Architecture:any
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
#14375 で修正されたのでラベルを付け替え
