### ISSUE TITLE
通知の受信設定で「フォロー∪フォロワー」が欲しい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13372]
### Summary

「フォロー」「フォロワー」「相互フォロー = フォロー∩フォロワー」はあるがフォロー∪フォロワーがないので欲しい

![image](https://github.com/misskey-dev/misskey/assets/7973572/7d5cee4d-5aea-4f6c-9b36-7aa4b637f7d3)

### Purpose

個人的には使いたい

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by KisaragiEffective** [comment]
related: #13357 #13358
