### ISSUE TITLE
チャートのラベルが消えている

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13371]
https://focalorus.io/notes/9ptwew0f6i

**Comment by zyoshoka** [comment]
もともと付いてたラベルは `'Active: '` だったはずでそこまで必要性が感じられなかったので消しましたが、どうでしょうか・・・

https://github.com/misskey-dev/misskey/pull/12967#issue-2076216588

**Comment by zyoshoka** [comment]
すみません、上記は関係なかったです。↓での変更が影響してそうです。

https://github.com/misskey-dev/misskey/pull/12926/files#diff-247c29afc852d8025b6f2055c529b57de4fd0b556f9395c8d0d89c4f9be6f38dR242-R244
