### ISSUE TITLE
リモートのアンケートに含まれるカスタム絵文字が画像にならない

### ISSUE THREAD

**Issue by kozakura913** [syuilo/Misskey#13422]
### 💡 Summary

ローカルのアンケートであればカスタム絵文字が画像として表示されるが、リモートのアンケートはカスタム絵文字が画像化されず、idが表示される

### 🥰 Expected Behavior

ローカルとリモートで同一の挙動
画像化する方が好ましい？

### 🤬 Actual Behavior

アンケートに含まれるカスタム絵文字の表示がローカルとリモートで異なる

### 📝 Steps to Reproduce

1. アンケートを投稿する
2. 他インスタンスから表示する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:2024.2.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment]
Duplicate of #10689

**Comment by kozakura913** [comment]
"アンケート"で検索したため、把握漏れしてました
