### ISSUE TITLE
サーバーへのリアクション送信を数秒遅らせる

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13432]
### Summary

内部でデータを保持し、数秒経ってから送信する
送信するまでの間に変化があった場合はそこからまた数秒待つ

### Purpose

間違えた際など、とっさにリアクションを変更したときにいちいちデータが送信されてレートリミットに引っかかるのを防げる

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
(リアクションしてからすぐにタブを閉じたりリロードしたりすると「押したのにリアクションされてなかった」が発生しそう…?)

**Comment by tai-cha** [comment]
リアクション芸人しづらくはなるな…（リアクション割り込まれが起きまくりそう）
（リアクション芸人自体が何回かリアクションのリクエストを送るという意味ではよくないが）

**Comment by tamaina** [comment]
Service Worker使えばいける気がする
