### ISSUE TITLE
pnpm devしてもエラーになることがある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#13443]
### 💡 Summary

サーバー側は問題なく起動している
![image](https://github.com/misskey-dev/misskey/assets/4439005/b3dc2abb-2401-4210-b544-a534e25c44fe)

### 🥰 Expected Behavior

no error

### 🤬 Actual Behavior

error

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
やっぱりdevと非devでポート違うのどうにかできないかしら

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/blob/30fe0726069a90fe1ced88a8e4fbdec19fe13078/CONTRIBUTING.md#mk_dev_preferbackend-pnpm-dev

こっちのバージョンの pnpm dev 使えばいいと思います

**Comment by tamaina** [comment]
> HMR may not work in some environments such as Windows.

**Comment by tai-cha** [comment]
```zsh
MK_DEV_PREFER=backend pnpm run dev
```
これすると起動できないの自分だけかしら
https://github.com/misskey-dev/misskey/issues/13450

**Comment by tai-cha** [comment]
![image](https://github.com/misskey-dev/misskey/assets/40626578/f49d2136-ecb8-4893-8b81-6e58de1c59f1)

**Comment by zyoshoka** [comment]
それは裏で `pnpm build-assets` を走らせると一応治ります（#10367、#12861）
