### ISSUE TITLE
起動できないことがある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#13444]
### 💡 Summary

ここから永遠に進まないことがたまにある
![image](https://github.com/misskey-dev/misskey/assets/4439005/667df240-14c8-4234-b547-677c319fb5e6)

``` ts
const mem = await sysUtils.mem();
```
で詰まってそう

### 🥰 Expected Behavior

起動する

### 🤬 Actual Behavior

起動しない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
`const mem = await sysUtils.mem();`消したら起動するようになる

**Comment by anatawa12** [comment]
とりあえずsysteminformationが少し古いようなので更新してみるとどうだろう

**Comment by anatawa12** [comment]
また、OSは何ですか？ (systeminformationの中身見るとOS依存処理がまぁまぁ走ってるのでOSによって調査する対象が変わります)

**Comment by syuilo** [comment]
> とりあえずsysteminformationが少し古いようなので更新してみるとどうだろう

5.22.0でも変わらなかったわね

> OS

Windows11

**Comment by syuilo** [comment]
PCを再起動すると直るけど、この現象が発生するたびに再起動しなければならないのは面倒

**Comment by syuilo** [comment]
あー、Powershell自体起動しないわね

**Comment by syuilo** [comment]
この状態で止まる
![image](https://github.com/misskey-dev/misskey/assets/4439005/0e867f05-3a2e-471b-8834-37cfabe802e4)

**Comment by anatawa12** [comment]
ではそれが原因そう...でもその状態になるの聞いたことないな...

**Comment by syuilo** [comment]
コマンドプロンプトは起動できた

**Comment by KisaragiEffective** [comment]
`PowerShell.exe -NoProfile` だと起動したり…？

**Comment by syuilo** [comment]
> `PowerShell.exe -NoProfile` だと起動したり…？

![image](https://github.com/misskey-dev/misskey/assets/4439005/06b2f348-062e-48f8-beb0-14c79a10361a)

ダメだった

**Comment by anatawa12** [comment]
https://github.com/sebhildebrandt/systeminformation/blob/9d852bcc8807207b8dec116db0c062013eb9bd85/lib/util.js#L380-L507

一応system information内でもnoprofile

**Comment by syuilo** [comment]
この起動し損ねたPowershellはウィンドウを閉じてもプロセスとしては残り続けてるっぽい & そのプロセスをタスクマネージャーから殺そうとしても無反応

**Comment by syuilo** [comment]
変わらないっぽい

**Comment by anatawa12** [comment]
https://serverfault.com/questions/1017031/what-would-be-causing-powershell-exe-to-hang-upon-opening-on-multiple-systems なんかそれっぽいのstackexchange(=stackoverflow)で見つけた

**Comment by syuilo** [comment]
症状は同じだわね

**Comment by syuilo** [comment]
Misskeyではどうしようもなさそう
