### ISSUE TITLE
MkReactionViewerで❤️が押せない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13459]
バックエンドは❤=\u2764に正規化するがフロントエンドは❤️=\u2764\ufe0fのみをユニコード絵文字として認識するため、MkReactionViewerで❤️が押せない（カスタム絵文字扱い？になる

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/13298#issuecomment-1963009736

**Comment by tamaina** [comment]
ぐえ

**Comment by mei23** [comment]
なんか`["♟️", "chess_pawn", 4],`とかも押せないわね

**Comment by mei23** [comment]
> （カスタム絵文字扱い？になる

クライアント側の判定ロジックどうなってるのかしらね

**Comment by tamaina** [comment]
Fixed by 7565f7bec60f37d5229ebd1cf602fc0a42ecba3b

(多分)

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/blob/26d4c5fd94638e332b93feed8dff749ab5564d6a/packages/frontend/src/components/MkReactionsViewer.reaction.vue#L57-L59
がundefinedになるわね

**Comment by tamaina** [comment]
> https://github.com/misskey-dev/misskey/blob/26d4c5fd94638e332b93feed8dff749ab5564d6a/packages/frontend/src/components/MkReactionsViewer.reaction.vue#L57-L59
> 
> がundefinedになるわね

https://github.com/misskey-dev/misskey/commit/7565f7bec60f37d5229ebd1cf602fc0a42ecba3b が？
