### ISSUE TITLE
Is there anyone handle security problem?

### ISSUE THREAD

**Issue by Drun1baby** [syuilo/Misskey#13461]
### Summary

rt

### Purpose

rt

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by temtemy** [comment]
You can report a security bug privately to the developers at https://github.com/misskey-dev/misskey/security/advisories/new

**Comment by Drun1baby** [comment]
> You can report a security bug privately to the developers at https://github.com/misskey-dev/misskey/security/advisories/new

actually I had reported it but no one handle it at all

**Comment by Drun1baby** [comment]
![image](https://github.com/misskey-dev/misskey/assets/75228348/2f829216-36fd-4491-87f9-4857327f2711)

I don't know what should I do for this mail……

**Comment by Drun1baby** [comment]
I received a mail from you but I don't know what to do……
