### ISSUE TITLE
ピン留め or 履歴に表示されるカスタム絵文字がサーバから削除されるとリアクションが出来なくなる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13485]
### 💡 Summary

ピン留めに登録されているカスタム絵文字がコントロールパネルから削除され、その後にリアクションしようとすると何も表示されなくなります（コンソールを見るとエラーが出ている）。
一部処理にて「サーバにはないがピン留めには存在する」という状態を考慮しきれておらず、意図せぬundefinedが返るようになっており、undefinedを想定していない後続処理でエラーとなり…という状態に陥っていました。これをundefinedではなく絵文字名を返すようにし、後続処理に繋がるようにします（後続処理はstringが想定されている）

### 🥰 Expected Behavior

エラーが出ずにレンダリングされること

### 🤬 Actual Behavior

エラーが出てレンダリングが途中で止まり操作に支障が出る

### 📝 Steps to Reproduce

1. ピン留め（リアクション／全般）に任意のカスタム絵文字（Unicode絵文字ではない）が登録されている状態である
2. コントロールパネルから1の絵文字を削除
3. リロード
4. ＋ボタンからリアクションしようとする（TLや通知の状態によってはこの段階でエラーが出ていることもある）
5. wow

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Any
* Browser: Any
* Server URL: Any
* Misskey: 2024.3.0
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
同件っぽいです

**Comment by samunohito** [comment]
Duplicate of #13484

**Comment by samunohito** [comment]
（僅差すぎる）

**Comment by tamaina** [comment]
逆

**Comment by samunohito** [comment]
こっちの方が後かと思ってた

**Comment by tamaina** [comment]
着順より詳細な方を残したい感じがある

**Comment by Sayamame-beans** [comment]
#13484 ではIndexedDBのpizzax::baseを消したら直るとされていますが、ピン留めはサーバー側で保持しているアカウント単位情報なので不可解です。
また、ブラウザによって発生したりしなかったりするユーザーを複数人観測しています。(IndexedDBの削除で解決します)
そのため、IndexedDBのpizzax::baseに保存されているクライアント単位情報である、リアクション履歴においても同様の現状が発生している可能性があるのではないかと推測しています(要検証)

**Comment by Hoto-Cocoa** [comment]
きっと最近使った絵文字についても同じだと思いますが、ちょうどサーバーから何も絵文字が消えていないのに同じ問題が発生することがありました。 （もともとIndexedDBにあったカスタム絵文字もすべてサーバーに残っていました）
いろいろ試してみましたがうまくいかなかったのでIndexedDBでkeyを消す方法で解決しましたが再発しました。

**Comment by u1-liquid** [comment]
FYI: https://github.com/MisskeyIO/misskey/pull/480
関連PR https://github.com/MisskeyIO/misskey/pull/485 https://github.com/MisskeyIO/misskey/pull/488 https://github.com/MisskeyIO/misskey/pull/490

**Comment by Hoto-Cocoa** [comment]
"❓" これを使って以来、いつも開かれなくなりましたが、ioの488番PRが同じ問題を解決しているようです。

**Comment by samunohito** [comment]
Unicode絵文字もアカンかったか…

@u1-liquid @Hoto-Cocoa 
情報提供ありがとうございます

**Comment by samunohito** [comment]
@Sayamame-beans 
発見した際の操作がピン留めだったので、ピン留めで起票してました。仰る通り、履歴でも同様の現象が起こると思います。
原因はキャッシュしている絵文字一覧の中にピン留めor履歴の絵文字が存在しないケースのハンドリングが甘かったことなので…

> また、ブラウザによって発生したりしなかったりするユーザーを複数人観測しています

以下は自分が実際に検知した例です。他にもパターンはあるかもしれませんが、把握してる限りでは何れもプルリクで修正している範囲に落ち着くと考えています。

絵文字削除のタイミングと、ユーザさんがMisskeyを開いていたタイミングによって発生する・しないがあるようです。
- 絵文字削除時にMisskeyを開いている
→WebSocket経由で絵文字の削除イベントが配信され、ローカルのキャッシュから絵文字が消える　→現象発生
- 開いていない
  - キャッシュの有効期限内
→削除イベントを受け取っていないのでキャッシュに残っている　→現象は発生しない（リアクションに使うと❤にフォールバックされる）
  - キャッシュの有効期限外
 →新しくバックエンドから取り直しキャッシュを更新　→現象発生

**Comment by samunohito** [comment]
テキストスタイル絵文字とカラースタイル絵文字（U+FE0Fが後ろにつくやつ）と、絵文字の辞書ファイルとして使用されている`emojilist.json`まわりの処理が噛み合っていなかったようでした。
`emojilist.json`にはカラースタイル化された絵文字が記載されておらず、MapからのUnicode絵文字情報取得に失敗→undefinedが返る→カスタム絵文字と同じ状況になっていたようです。

ひとまず、カラースタイル絵文字が見つからない場合はテキストスタイル絵文字でMapを検索するようにフォールバック処理を追加しました（プルリク参照）

**Comment by samunohito** [comment]
随所で不具合報告あがってるので強火（これだけでもリリースしたい気持ちが強い）
