### ISSUE TITLE
広告がMisskeyと同一ドメインの場合はRouterで遷移する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13481]
### Summary

書いてあるとおり

### Purpose

同一サイト内でタブが分かれるのはしんどい

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
個人的には、ウィンドウで開かれるのであればタブが分かれない方が嬉しい気はしますね…?
直接遷移だと好みが分かれそうな気は少しします
