### ISSUE TITLE
[compatibility]twitter .com 形式のリンクを再び機能するようにする

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#13516]
### Summary

`@hoge@twitter.com` 形式でのリンク機能がいつの間にか削除されており直接`twitter.com/hoge`などへのリンクをしなくなってしまっている。`twitter.com`がActivityPubに対応する可能性は限りなく0であり、利便性の面でも従来仕様に合わせたほうが混乱を招くことなく済む

### Purpose

後方互換性対応

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by EbiseLutica** [comment]
`x.com` リンクも追加で対応したいところ

**Comment by syuilo** [comment]
相応のやむを得ない理由があって削除したはずだから復活させることはできなそう

**Comment by tkmrgit** [comment]
>相応のやむを得ない理由があって削除

何か重大が理由があったのか...ちょっと存じてなかった

**Comment by EbiseLutica** [comment]
この辺しか追えなかった
https://github.com/misskey-dev/misskey/issues/5168

けど、おそらく

* フロントエンド依存機能のためサードパーティアプリには対応が丸投げとなる
* 現状こう書くと twitter.com 等の対象URLに対しAPの問い合わせをしてしまう
* リモート向けのHTMLにて対応がなされていない
  * するためにはメンションの仕組みそのものに特殊対応が必要で地味にめんどい

などの問題があり、おまけにしては実装コストが高すぎるために一度実装そのものをやめたのかなーと

確かにこれめっちゃめんどい

**Comment by syuilo** [comment]
あとどのサービスは対応してどのサービスは対応しないかの線引きが難しい

**Comment by syuilo** [comment]
互換性を持たせるには今更感あるし機能として見ても別にURL書けば良いだけなので復活はさせないことにします
