### ISSUE TITLE
ファイルに連合なしを指定できるようにする

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13535]
### Summary

ファイルを連合なしにできるようにする
連合なしにした場合でも、ノートにそのファイルを添付した際には、連合なしのファイルが有るという事実が連合先に届くようにする（→ #13533）

### Purpose

サーバー単位でJASRACへの包括契約を行うなどした場合、著作権管理を外部委託している音楽・映像等を連合すると著作権周りで怒られそうだが、ノート自体を連合なしにすると外部サーバーに共有できなくなってしまうのでそれも避けたい
→じゃあ問題のファイルだけ連合できなくすればいいじゃん！

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
サーバー単位でJASRACへの包括契約を行うなどする場合は稀有じゃないかしら

**Comment by KisaragiEffective** [comment]
FYI: https://m.tkngh.jp/notes/9wd4ycjrfpm10ega
