### ISSUE TITLE
ドライブファイル`properties`を連合する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13533]
### Summary

ドライブのファイルの追加メタデータについて、

- `_misskey_fileMeta`などのフィールドを作り、`properties`を入れて連合させる

とすると、いろいろなファイル情報を汎用性高く保持共有できて良さそう（ただ内部構造が変わると面倒かも。v1, v2などの識別子も持たせる？）

### 保持したいデータの例

（個別具体的にやるかやらないかを議論するというよりかは、こういうものが保持できそうという例として挙げてあります）

- https://github.com/misskey-dev/misskey/issues/12345
- https://github.com/misskey-dev/misskey/issues/13535

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
https://github.com/tamaina/misskey/blob/aa7f8e98b00f77b22fa8aa43d8a313359e85bd67/packages/backend/src/models/DriveFile.ts#L79

じゃダメなんだろうか

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/11031 はちゃんとカラムとして設定したほうが良さそう
