### ISSUE TITLE
投稿画面でノートを添付する際の表示を改善したい

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#13547]
### Summary

投稿画面でローカルのノートの URL をペーストすると引用を添付できる機能がありますが、この際の添付の表示を引用リノートする際の表示と同じにしたいです。

<img src="https://github.com/misskey-dev/misskey/assets/107108195/90a7aa6f-0a81-4d7e-a65f-f2ddb1b15fcc" alt="ノートを添付した投稿画面のスクリーンショット" width="520">

### Purpose

- 何を引用しているのかが投稿画面上で分からないので
- あまりイケてないので

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
Duplicate of #10598 ?

**Comment by zyoshoka** [comment]
Duplicate of #10598
