### ISSUE TITLE
refactor(backend): UserEntityService.packMany()を早くする

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13546]
### Summary

現状の造りだと、`packMany()`に渡されたユーザの数だけDBへの問い合わせが発生するようになっている（[UserEntityService.getRelation()](https://github.com/misskey-dev/misskey/blob/64953fadc92abf3fd83186733282bcf4f39bdb49/packages/backend/src/core/entities/UserEntityService.ts#L141-L211)が呼び出される）。

### Purpose

`UserEntityService.packMany()`を使う箇所全体に恩恵がある。
- 通知
- セットアップ時のピン留めユーザ一覧
- ユーザ検索
- ユーザ一覧（コントロールパネル→ユーザ）
- バブルゲームランキング

etc...

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
> 現状の造りだと、packMany()に渡されたユーザの数だけDBへの問い合わせが発生するようになっている（[UserEntityService.getRelation()](https://github.com/misskey-dev/misskey/blob/64953fadc92abf3fd83186733282bcf4f39bdb49/packages/backend/src/core/entities/UserEntityService.ts#L141-L211)が呼び出される）。

正確には packMany かつ schema が UserLite 以外のときだわね

**Comment by syuilo** [comment]
セットアップ時のピン留めユーザ一覧とかはそもそも UserLite で良い感がある

**Comment by syuilo** [comment]
基本的に UserDetailed が使われるのは特定のユーザーを単体で取得する場合のみを想定している(一覧で返ってくるようなエンドポイントでは UserLite を想定している)

**Comment by syuilo** [comment]
それで言うとバブルゲームランキングとかも UserDetailed である必要は全くないわね

**Comment by samunohito** [comment]
上記は、作成したプルリクに対し何か追加で処置が必要であることの示唆でしょうか…？
