### ISSUE TITLE
ボイスレコーダー（ボイスメモ）機能

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13541]
### Summary

https://developer.mozilla.org/ja/docs/Web/API/MediaStream_Recording_API を使ってマイクから音声を収録し、そのままドライブにアップロードできる機能を用意する（写真・映像はネイティブのアップロード機能に「カメラで撮る」が備わっていることが多いが音声はあまり見かけない）

### Purpose

![image](https://github.com/misskey-dev/misskey/assets/67428053/d1619009-d725-45f4-a0c6-de75ffacd611)
（Xの音声ツイート）を簡単にできるようにする
声を公開しているクリエイター等にとっては助かる機能かもしれない

Ref:
https://misskey.io/notes/9qkhmbk9qekr05tp
https://misskey.io/notes/9qkhq9lzaei9006w

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
音声もそのうちネイティブに実装される可能性はありそう
