### ISSUE TITLE
shareページにおいて絵文字ピッカーが開けない

### ISSUE THREAD

**Issue by kanade** [syuilo/Misskey#13554]
### 💡 Summary

Androidにおいて任意のアプリで文字列を選択した状態でMisskeyのPWAに向けてシェアしたり、あるいはブラウザからページのURLをPWAに向けてシェアする際、PWAに遷移したあとノート入力画面で絵文字のピッカーが開きません。
そのあとテキストの入力ができなくなりますが、アカウントの切り替えなどは反応します。

私の所有するAndroid 14のほか、OSバージョンは不明ですが弊サーバー内の複数人から同様の報告を受けています。
他サーバーでも発生するようで、試しにdevelopブランチのソースで新規インストールした環境でも発生します（絵文字の登録なし）。
カスタムCSSなどを一切インストールしていない、作りたてのアカウントでも発生します。

ちなみにピッカーは開きませんがセミコロンを入力するとサジェストは表示されます。

### 🥰 Expected Behavior

絵文字ピッカーが正常に表示される

### 🤬 Actual Behavior

絵文字ピッカーが表示されない。
この事象が発生したあとはテキストの入力ができないが、アカウントの切り替えや公開範囲のボタンなどは反応する。

### 📝 Steps to Reproduce

1. ブラウザで任意のページ表示 or 文字列を選択 などしてなにかしらをPWAに共有する
3. ノート入力画面で絵文字ピッカーを開こうとすると発生

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Android 14 ( Pixel 8 Pro )
* Browser: Chrome　122.0.6261.105
* Server URL: *
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
triage: 生きている

**Comment by Sayamame-beans** [comment]
shareページ自体の問題。PC環境でも発生する模様。
例: https://mi.7mi.site/share
