### ISSUE TITLE
「今日誕生日のユーザー」に前日誕生日だったユーザーが表示される

### ISSUE THREAD

**Issue by chikage8640** [syuilo/Misskey#13556]
### 💡 Summary

ウイジェット「今日誕生日のユーザー」に、前日誕生日だったユーザーが表示されます。（一日遅れる）
通信を見ると、クライアントは`/api/users/following`の取得時、`birthday`に前日の日付を投げているようです。

### 🥰 Expected Behavior

今日誕生日のユーザーが表示される

### 🤬 Actual Behavior

前日に誕生日だったユーザーが表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows11 23H2
* Browser: Firefox 123.0.1 (64 ビット)
* Server URL: https://mi.chikage.net
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment]
WIP on #12835
