### ISSUE TITLE
misskeyの利用時間を図る機能

### ISSUE THREAD

**Issue by kohakuto589** [syuilo/Misskey#13577]
### Summary

misskeyの利用時間を図る機能の提案
アピアランスのボタンを押しONにした場合、ウィジェット「アクテビティ」に追加される。
### イメージ画像
![無題300_20240315080321](https://github.com/misskey-dev/misskey/assets/148501199/de2fe242-1fab-45c5-a36b-1df2126f7bce)↩![無題301_20240315081904](https://github.com/misskey-dev/misskey/assets/148501199/8efdf684-4496-4632-aef4-d2a72be7de12)

### Purpose

数あるミス廃だったり学生のmisskey依存症防止(SNSの使い方を考え直す)
サーバーによっては小中学生等の学生がほぼ半数を占めるところもある。
そのため、学業に支障をきたしては困るだろうと思ったため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
実装が難しそう

**Comment by kohakuto589** [comment]
申し訳ない…。
