### ISSUE TITLE
Markdownの斜体にする構文を使っても反映されない

### ISSUE THREAD

**Issue by WinLinux1028** [syuilo/Misskey#13584]
### 💡 Summary

Markdownには`*あああ*`のようにすると *あああ* のように斜体になる構文があります
しかし､Misskeyでは日本語が入っている場合､この構文が適用されないようです

### 🥰 Expected Behavior

`*あああ*`と入力して *あああ* のように斜体で表示される

### 🤬 Actual Behavior

そのまま`*あああ*`と表示される

### 📝 Steps to Reproduce

1. 2つのアスタリスクの間に何らかの文字列を挟んだ投稿をする
2. 何らかの条件(ASCII以外の文字が入る?)で斜体にならない
![image](https://github.com/misskey-dev/misskey/assets/68107676/81c7ae5e-255a-4b09-9d55-b0ed3de15b3f)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 自作PC, Manjaro Linux
* Browser: Firefox 124.0b9
* Server URL: https://misskey.io/
* Misskey: v2024.3.1-io.1c
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment]
こちらは仕様だったかと思います
https://github.com/misskey-dev/mfm.js/issues/102

**Comment by WinLinux1028** [comment]
了解
