### ISSUE TITLE
[CI] Cypressがfailになる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13605]
### 💡 Summary

Cypressのテストが正常に動作しなくなっている模様。
CypressのUIを起動した状態で動きを見てみると、最初のLoading画面でフリーズしたままタイムアウトしている。

### 🥰 Expected Behavior

passする

### 🤬 Actual Behavior

failになる

### 📝 Steps to Reproduce

cypressで作られた任意のテストを起動

### 💻 Frontend Environment

```markdown
-
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
以下推測

直近では #13591 にて上記箇所の修正が施されているが、これは直接的な原因ではないと考える。
元々は
```js
cy.window(win => {
  win.indexedDB.deleteDatabase('keyval-store');
})
```
のような実装になっていたが、cy.window()にはラムダを引数に取る機能は存在しておらず、ただcy.window()を呼び出していただけだった。TypeScript化されたことにより正しく呼び出せていないことが表面化し、現在の形に修正されたことで表出したのではないかと推測。

ただ…13591でもコメントされている通り、上手く行ったパターンもあるとのこと…
環境依存的なものもあるのかもしれない（自分のローカルではうまくいかなかった）

**Comment by dakkar** [comment]
it did, yes

**Comment by dakkar** [comment]
but I may have tested before "fixing" the call to `deleteDatabase`; I'll test again tomorrow

**Comment by dakkar** [comment]
you're all correct, "fixing" the call to `deleteDatabase` made the tests fail

just delete the lines
```ts
cy.window().then(win => {
  win.indexedDB.deleteDatabase('keyval-store');
});
```
from `cypress/support/commands.ts` and everything works again.

Apologies for breaking your build!

**Comment by lunaisnotaboy** [comment]
@dakkar that's not a good thing. that's what resets the client's IndexedDB between tests, so it can have a fresh start. another fix needs to be found. i'll see what i can do.

**Comment by dakkar** [comment]
well, the code before we "fixed" it, was passing a lambda to the `cy.window()` function, which completely ignored it, so the IndexedDB was *never reset*

apparently the tests actually rely on that?

**Comment by lunaisnotaboy** [comment]
hmmm...

then i guess deleting the lines would do it

**Comment by lunaisnotaboy** [comment]
i don't get it... because the way we did it is _exactly_ how we're supposed to do it...

**Comment by lunaisnotaboy** [comment]
related: https://github.com/cypress-io/cypress/issues/1208

**Comment by tamaina** [comment]
とりあえずidb-proxyでlocalStorageを強制するのはどうかしら

**Comment by lunaisnotaboy** [comment]
> とりあえずidb-proxyでlocalStorageを強制するのはどうかしら

Maybe... that could work.

**Comment by anatawa12** [comment]
> https://developer.mozilla.org/ja/docs/Web/API/IDBFactory/deleteDatabase に記載のある `注: この機能は Web Worker 内で利用可能です` が関係している？

この注は数多くのweb APIがweb worker内で使えないのに対して、このAPIが(比較的)例外的に使えるAPIであることを示しているだけで非web worker内で使えないという話ではないと思います。

**Comment by anatawa12** [comment]
少し調査してみたところ、chromeのバグに起因してる可能性がありそうでした。

まず現状の動作を確認したところ、なぜか ``win.indexedDB.deleteDatabase('keyval-store')`` が完了しない[^1]ことがわかりました。
また、cypressの内部のmisskeyがローディングで止まる原因を調査したところ[こちらの`await iset('idb-test', 'test')`](https://github.com/misskey-dev/misskey/blob/d60f645d1dc731d7ef6eff16081d2b5615412690/packages/frontend/src/scripts/idb-proxy.ts#L19)内で呼ばれている `indexedDB.open`も完了しなくなっている模様でした。

また、firefox環境ではcypressが問題なく通ることも確認したため、chrome固有の動作であろうことがわかりました。

そして、おそらくcypressは`iframe`の`contentWindow`を使ってる推測し、この`contentWindow`を経由した`indexedDB`の操作周りにchromeにバグが有るのではないかと予測しました。

これを確認するために、以下のようなhtmlファイルを作成し、これをhttp経由でchromeで開いたところ、`innerWindow.indexedDB.deleteDatabase`が正常に完了しない動作が再現できたため、chromeのバグであると考えました。
(firefoxでは問題なく完了することも確認しました)

```html
<!doctype html>
<iframe></iframe>
<script>
	const search = new URLSearchParams(location.search);
	if (search.has("inner")) {
		// this is the inner iframe
	} else {
		// this is the outer iframe
		const iframe = document.querySelector("iframe");
		iframe.src = location.href + "?inner";
		const innerWindow = iframe.contentWindow;

		const request = innerWindow.indexedDB.deleteDatabase("test-db");
		request.onsuccess = () => {
			console.log("Database deleted");
		};
		request.onerror = () => {
			console.error("Error deleting database");
		};
		request.onblocked = () => {
			console.error("Blocked deleting database");
		};
		request.onupgradeneeded = () => {
			console.error("Upgrade needed deleting database");
		};
		console.log(request);
	}
</script>
```



[^1]: いくらまっても戻り値の`IDBRequest.readyState`が`'done'`にならず、また`IDBRequest.onsuccess`, `IDBRequest.onerror`, `IDBOpenDBRequest.onblocked`, `IDBOpenDBRequest.upgradeneeded`イベントのいずれも発火しない。

**Comment by tamaina** [comment]
> indexedDB.deleteDatabaseが正常に完了しない

これChromiumのバグトラッカーないかしら（前から気になってはいた

**Comment by anatawa12** [comment]
https://issues.chromium.org/issues?q=indexedDB%20deleteDatabase https://issues.chromium.org/issues?q=indexedDB%20iframe で調べた感じ、https://issues.chromium.org/issues/40827490 が関係あるかもしれないくらいでそのものっぽいのは見当たらなかった
