### ISSUE TITLE
`TypeError: node-fetch cannot load bear`でinboxが詰まる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#13608]
Fedibirdなどでサークル機能実現のために使用されているBearcaps URLが原因

Related to https://github.com/misskey-dev/misskey/issues/13201

**Comment by tamaina** [comment]
とりあえずbearで始まるidのactivityはスキップするべき

**Comment by tamaina** [comment]
https://github.com/MisskeyIO/misskey/pull/330 もあるけどよくわからん（サークル機能だとtoにhttps://example.com/contexts/:id（が唯一のアイテムの配列）が入っててこれが何を解決するのか不明）

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/misskey/assets/7973572/24e324d2-f157-4db9-91d6-c3f735588bcb)

はぁ

**Comment by tamaina** [comment]
（ https://github.com/misskey-dev/misskey/issues/13201 の実装の話になっちゃうけど）Fedibirdの実装って、各ユーザーのプライベートのinboxに送って、各ユーザーにbearcaps urlを解決させる（という体裁をとる）ことで機密性を保っているということなのか

（そしてGroupのitemsにユーザーのコレクション書かないことで閲覧可能なユーザーを非公開にしている？）

**Comment by u1-liquid** [comment]
一応これらを全部入れるとサークル機能の投稿がDMとして届くようになる

https://github.com/MisskeyIO/misskey/pull/330
https://github.com/MisskeyIO/misskey/pull/361
https://github.com/MisskeyIO/misskey/pull/365
https://github.com/MisskeyIO/misskey/pull/368
https://github.com/MisskeyIO/misskey/pull/386
https://github.com/MisskeyIO/misskey/pull/388

サークル機能は非対応にするとしても今後他の用途にBearcaps URLが使われる可能性は十分あると思うので
拒否するより https://github.com/MisskeyIO/misskey/pull/330 だけ入れてエラーが発生しなくするのがいいと思うけど

**Comment by mei23** [comment]
> TypeError: node-fetch cannot load bear

そもそもnode-fetchに意図してないプロトコルを渡っちゃているのがいけない気がするのだわね
もしもリクエストライブラリがunix:とかfile:サポートしてたらどうなる？？？
