### ISSUE TITLE
AP向けHTMLにおいて<や>、&といった記号がエスケープされていない

### ISSUE THREAD

**Issue by syobocat** [syuilo/Misskey#13626]
### 💡 Summary

AP向けHTMLを生成する際に特殊記号がエスケープされていないため、連合先で正しく表示されない場合があります。

![image](https://github.com/misskey-dev/misskey/assets/46315199/1402f617-e665-4822-a949-5be21f8b68e9)
![image](https://github.com/misskey-dev/misskey/assets/46315199/73d6c8d8-eac0-410d-9469-67868feacb0c)

### 🥰 Expected Behavior

特殊記号がエスケープされて送信される

### 🤬 Actual Behavior

特殊記号がエスケープされていない

### 📝 Steps to Reproduce

1. 投稿に<などの特殊記号を含める
2. 送信する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: misskey.io, etc...
* Misskey: v2024.3.1-io.3, etc...
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by mei23** [comment]
createTextNode使ってるのにエスケープされずに出てきてしまう時点でおかしいと思って
https://github.com/misskey-dev/misskey/blob/20eb4bc29600975ea9b6d74426204b8f6871bc27/packages/backend/src/core/MfmService.ts#L428
https://developer.mozilla.org/ja/docs/Web/API/Document/createTextNode

JSDOMの時は起きてなくてhappy-domにしてから起きてそうなので https://github.com/misskey-dev/misskey/pull/10016
happy-dom自体の挙動を見た方がいいように思えるわ。

リモート向けはリモートでバリデーションを行うだろうから大丈夫だけど、ローカル向けのHTMLで使ってたら脆弱性ではと思うのだわ。

**Comment by mei23** [comment]
happy-domがおかしい？

**jsdom**
```ts
import { JSDOM } from 'jsdom';
const { window } = new JSDOM('');
const doc = window.document;
doc.body.appendChild(doc.createTextNode('<script>alert(1)</script>'));
console.log(doc.body.innerHTML);
```
↓
```
&lt;script&gt;alert(1)&lt;/script&gt;
```

**happy-dom**
```ts
import { Window } from 'happy-dom';
const { window } = new Window();
const doc = window.document;
doc.body.appendChild(doc.createTextNode('<script>alert(1)</script>'));
console.log(doc.body.innerHTML);
```
↓
```
<script>alert(1)</script>
```
