### ISSUE TITLE
コンディショナルロールの付与条件増強

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13667]
### Summary

以下を新たな条件として設定できるようにします。

- ドライブの使用容量（DriveFileEntityService#calcDriveUsageOf）
- botかどうか（user.isBot）
- サスペンドされているか（user.isSuspended）
- ユーザ情報の更新日時（user.updatedAt）
- セキュリティキーの有無（userEntityService.packのsecurityKeysと同じ条件）
- email認証済みか否か（user_profile.emailVerified）
- 2fa設定済み（user_profile.twoFactorEnabled）
- パスワードログイン設定済み（user_profile.usePasswordLessLogin）

### Purpose

- ロールにより制御可能な機能の恩恵と各値を結びつけることによるモデレーションコストの軽減
- バッジの付与で2fa設定の促進…みたいなのにも使えるかも？

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by samunohito** [comment]
他にもコレが欲しい等あればここに書き込み願います

**Comment by samunohito** [comment]
（ほかにもいくつか抱えてるので実際の着手はしばらく後の予定）

**Comment by Sayamame-beans** [comment]
partially duplicate of #9545

**Comment by meronmks** [comment]
- 「投稿数が～」があるので似たようなノリで「リアクションした数が～」「リアクションされた数が～」
  - 集計で負荷がそこそこありそうなのが懸念点？
- 設定された誕生日かどうか
  - 誕生日限定ロールやバッジ付与に使えそう

**Comment by Sayamame-beans** [comment]
- 通算ログイン日数
  - 実績のために恐らく既に存在するデータ
  - ユーザーがどのくらい利用しているかがノート数よりも測りやすいかも?
  - (ROM専かどうかはノート数で分かる(ただしRNしかしていないようなケースもあり得そう。これは判断出来ない))

**Comment by Sayamame-beans** [comment]
リノートの数、アカウントの統計情報にあったんですね(リアクションは記憶していましたがリノートやそれ以外のもは覚えてないです)
統計情報って本家だと無くなってるんでしたっけ…?

**Comment by syuilo** [comment]
本家以外でもリノート数などをデータベースに持っている実装は無いと思う

**Comment by Sayamame-beans** [comment]
> 本家以外でもリノート数などをデータベースに持っている実装は無いと思う

ioにはあると耳にしています
https://github.com/MisskeyIO/misskey/pull/258

**Comment by syuilo** [comment]
> > 本家以外でもリノート数などをデータベースに持っている実装は無いと思う
> 
> ioにはあると耳にしています [MisskeyIO#258](https://github.com/MisskeyIO/misskey/pull/258)

特にデータベースは変更してなさそう

**Comment by Sayamame-beans** [comment]
ありませんか?
> ![画像](https://media.niri.la/misskey/82cd3c8c-b8d4-40c8-90d8-f8d377b1fa95.png)
> https://misskey.niri.la/notes/9rr7vkanhl より

**Comment by syuilo** [comment]
都度集計してるだけでデータベースにはなさそう

**Comment by Sayamame-beans** [comment]
> 都度集計してるだけでデータベースにはなさそう

なるほど、そういうことでしたか…

**Comment by samunohito** [comment]
以下で実装します。

- ドライブの使用容量（DriveFileEntityService#calcDriveUsageOf）
- botかどうか（user.isBot）
- サスペンドされているか（user.isSuspended）
- ユーザ情報の更新日時（user.updatedAt）
- セキュリティキーの有無（userEntityService.packのsecurityKeysと同じ条件）
- email認証済みか否か（user_profile.emailVerified）
- 2fa設定済み（user_profile.twoFactorEnabled）
- パスワードログイン設定済み（user_profile.usePasswordLessLogin）
- 設定された誕生日かどうか （user_profile.birthday）
- 通算ログイン日数（user_profile.loggedInDates.length）
- リアクションした数（note_reaction.userId）
- リアクションされた数（note_reaction + note.userId）
- リノートした数（note.userId + note.renoteId IS NOT NULL）
- リノートされた数（note.renoteUserId）
- リプライした数（note.userId + note.replyId IS NOT NULL）
- リプライされた数（note.replyUserId）
- 投票した数（vote.userId）
- 投票された数（vote + note.userId）

**Comment by syuilo** [comment]
〇〇した数系はデータベースに持っていない(もしくは持ってても精度が低い)のがほとんどで、コンディショナルロールで使うのは現実的ではないかも

**Comment by syuilo** [comment]
どうしても使いたい場合は、データベースにカラムとして持つようにした上で、PostgreSQLのトリガ定義してカウントするようにした方が良さそう

**Comment by samunohito** [comment]
> 〇〇した数系はデータベースに持っていない(もしくは持ってても精度が低い)のがほとんどで、コンディショナルロールで使うのは現実的ではない

負荷の面で負担になりそうな懸念はたしかにあります。
数十万件のレコードを作ってみて、実際に動かしたときの挙動次第で判断しようとしていました。

完全にオミットするか、コンディショナルロールの算出結果をCacheServiceよろしく特定期間保存するか…

**Comment by syuilo** [comment]
コンディショナルロールの判定は場合によっては大量に行われるから同期的な処理だけで済ませたい

**Comment by samunohito** [comment]
結果のキャッシュやジョブで付与したものを取り出すだけにするのでも厳しいでしょうか…？
同期限定だと、今後登場するであろう別の条件の選択肢も狭まってしまうので

**Comment by syuilo** [comment]
コンディショナルロールは参照される機会が桁違いに多いからキャッシュする場合数千とか数万の量になってメモリ的に厳しそう

**Comment by syuilo** [comment]
> > 同期的な処理だけで済ませたい
> 
> これはPromiseを使わずに実現できる範囲であればOK…ということでよいです？

そうね

**Comment by samunohito** [comment]
（ちなみに、コンディショナルロールのアサインをDBに持たず都度判定してるのって何か歴史的経緯があるんでしょうか？）

**Comment by syuilo** [comment]
> （ちなみに、コンディショナルロールのアサインをDBに持たず都度判定してるのって何か歴史的経緯があるんでしょうか？）

https://github.com/misskey-dev/misskey/issues/12563#issuecomment-1837449088

**Comment by samunohito** [comment]
> あるユーザーが与えられた際にそのユーザーが条件に合致するか判定しロールを算出

なぜこうなっているのか知りたく

**Comment by syuilo** [comment]
> 例えるなら、地球上からランダムに人をピックアップしてその人が男性か女性かを判定することは容易でも、地球上のすべての男性もしくは女性を列挙するのは不可能(一人一人調べていたら途方もない時間がかかるから)という感じです

が理由

**Comment by Sayamame-beans** [comment]
> データベースに存在するすべてのユーザーに対して条件に合致するか都度調べる必要があり

条件の判定が最短で1回/日や1回/週となるようなキャッシュ保持を検討することは困難なのでしょうか?
(ユーザーごとに「そのユーザーに対してコンディショナルロールの条件が最後に確認された日」を保持し、そこを見てexpiredなら今と同じように全コンディショナルロールを再チェック、期間内ならマニュアルロールと同じようにロールキャッシュから取得)
(もちろん、コンディショナルロールに毎秒レベルの精度が必要であればこの案は不可能ですが…)

**Comment by syuilo** [comment]
> 条件の判定が最短で1回/日や1回/週となるようなキャッシュ保持を検討することは困難なのでしょうか?

https://github.com/misskey-dev/misskey/issues/13667#issuecomment-2058645363

**Comment by Sayamame-beans** [comment]
日付情報1つを`user`と同様に常に持っておくことによる参照負荷はそれほど高いものなのでしょうか…?

**Comment by syuilo** [comment]
日付情報だけでなく、ロール情報もキャッシュが必要じゃないかしら？
その場合、メモリ負荷は高くなるわね

**Comment by syuilo** [comment]
コンディショナルロールはどんなリモートユーザーにも無条件で適用されるという点は留意しないといけない

**Comment by syuilo** [comment]
適用されるコンディショナルロールが無いということもキャッシュしなければならないから最大で全てのFediverseユーザーに対してのキャッシュが必要になる

**Comment by samunohito** [comment]
あ～

**Comment by Sayamame-beans** [comment]
ふむ…では、ローカルに限ったり出来るなら(出来ないかも)少し話が変わる感じでしょうか?

逆の、ロール側ではなく情報側を持つ方向で検討する場合は、個人的には
> email認証済みか否か
> 2fa設定済み
> パスワードログイン設定済み
> 通算ログイン日数

はロールの条件として利用する価値が十分高いと感じているのですが、それらの内容も現状user_profile内にあるため、更新頻度(少ない)によらず厳しいということですよね…
(userと一緒に持つように変更するなどの迂回策は、恐らくuserは他の処理と併用していると思うので、何らかの処理の際に本人以外のユーザーに見えてしまう危険性がありますかね?)

**Comment by syuilo** [comment]
> ふむ…では、ローカルに限ったり出来るなら(出来ないかも)少し話が変わる感じでしょうか?

ローカルに限ったとしてもユーザー数が多い場合結局はメモリの問題が出てくるわね
適用されるロールが無い場合も無いという情報をキャッシュしなければならないというのが他のキャッシュと比べてメモリを圧迫する理由のひとつ

> 逆の、ロール側ではなく情報側を持つ方向で検討する場合は、個人的には

それらはuserで持つようにしても良さそう
ただ連続ログイン日数は実装が難しそう

**Comment by Sayamame-beans** [comment]
> ただ連続ログイン日数は実装が難しそう

("連続"ではなく、現存する"通算"の日数です)

**Comment by syuilo** [comment]
通算日数は保持してなくて、厳密にはログインした日付の配列だったと思う

**Comment by samunohito** [comment]
諸々了解しました。コンディショナルロールについては「非同期なく即時判定可能なもの」で実装します。

**Comment by samunohito** [comment]
（off-topic）
以下のような前提付きの「特定条件により自動的に付与・剥奪されるマニュアルロールに近いもの」とかだったら検討の余地ありだったりします？

- ローカルユーザ限定
- 処理上の振る舞いとしてはマニュアルロールに準拠（role_assignmentで管理）
- ジョブで定期実行し、そのうえで判定される（実行間隔は設定可。OFFも可）
- 全ユーザを一気にやらずに小出し（1回で処理する人数は設定可）で判定する

role_assignmentのレコード数は増えますが、逆に言えばそれだけだと思うので…

**Comment by syuilo** [comment]
実際そのようなものは考えてたし検討の余地はあるわね
あとMisskey本体での実装ではなくても既に外部ツールとして特定条件を満たしたユーザーに自動でマニュアルロールを付けたり外したりするものもある
Misskey本体での実装を考えると現状コストに見合う需要はないかも

**Comment by samunohito** [comment]
なるほど、ありがとうございます。需要が見込めたら別途issueを建てようと思います。
