### ISSUE TITLE
feat(frontend): opt-out nyaize by viewer's setting

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13713]
### Summary

nyaizeを閲覧する側の設定で切れるようにしてほしい

### Purpose

専門用語が化けて (inter**na**l, alter**na**tive) TLを見るときにやや困るため

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by anatawa12** [comment]
しゅいろさんが切れるようにしたくないけどフロントでやるようにしたからできるようになっちゃったというふうな発言をどこか(の記事)で言ってた記憶があるのでしゅいろさんは切れないようにしたくないと認識してる

**Comment by anatawa12** [comment]
古い発言だけど

https://github.com/misskey-dev/misskey/issues/4615#issuecomment-478342163

> > 困ることはありますか？
> 
> 問答無用でnyaizeされるという機能なので、問答無用でなくなった時点で機能の意味がなくなる

とか

**Comment by anatawa12** [comment]
あたらしめ(わたしがみたもの)はこれですね

> nyaizeに関してはもともとユーザーを困らせることが目的のひとつとして実装されたものです。

https://gihyo.jp/article/2023/11/misskey-08

**Comment by syuilo** [comment]
実装しない方針

**Comment by t1nyb0x** [comment]
実装しない方針のため
