### ISSUE TITLE
Pixelfedの投稿を正しく受信できていない？

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#13711]
### 💡 Summary

Pixelfedのサーバーを建て、Misskeyサーバーからリモートフォローしたのですが、フォローは通るもののINBOX内で詰まってしまいます。
Mastodon系のサーバーからは見えているのでMisskey側で処理できていないように見えます

### 🥰 Expected Behavior

Pixelfedの投稿がMisskeyのホームで閲覧できる

### 🤬 Actual Behavior

INBOX内で下記エラーが発生する

> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)
> Error: unexpected schema of note.id: http://fedi.7graphics.studio/p/nana/684989693962874884
>     at ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:132:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApInboxService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:364:13)
>     at async ApInboxService.create (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:343:13)
>     at async ApInboxService.performOneActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:139:13)
>     at async ApInboxService.performActivity (file:///home/misskey/misskey/packages/backend/built/core/activitypub/ApInboxService.js:125:13)
>     at async InboxProcessorService.process (file:///home/misskey/misskey/packages/backend/built/queue/processors/InboxProcessorService.js:169:13)
>     at async Worker.processJob (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28)
>     at async Worker.retryIfFailed (/home/misskey/misskey/node_modules/.pnpm/bullmq@5.4.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)

### 📝 Steps to Reproduce

1. Pixelfedのユーザーをフォローする
2. Pixelfedのユーザーが投稿する
3. Misskeyでホームタイムラインを更新する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): -
* Browser: -
* Server URL: https://m.7shiro.com/
* Misskey:2024.3.1

[Pixelfed]
* Server URL: https://fedi.7graphics.studio/
* Pixelfed:v0.11.13
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey:2024.3.1
* Node:v20.12.2
* PostgreSQL:16.2
* Redis:7.2.4
* OS and Architecture:Ubuntu 22.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
note.idがhttpsでないことに起因してそう。Misskey実装だとhttpsを必須としているのが直接の原因ではあるけどprefixedがhttpで投げてきている理由の方も気になる。

**Comment by 7shironana** [comment]
> Pixelfedがhttpで投げてきている理由の方も気になる。

ありがとうございます。こちらは別途Pixelfedの方のIssueも確認してみようと思います。

**Comment by 7shironana** [comment]
すみません！自己解決しました。
Pixelfed側の設定ファイル内でURLの欄がデフォルトでhttpになっていることに気づかず、そのままFQDNだけを記入していたのが原因でした。
httpsに変更し設定を反映することで解消しました。
