### ISSUE TITLE
frontend: 公開範囲をダイレクトにしてノートを書きかけの状態で閉じて開くと宛先が消える

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13714]
上: 閉じる前
下: 閉じた後

![before](https://github.com/misskey-dev/misskey/assets/48310258/f8d9ff2e-acf3-492e-98ab-ad75fad6a053)
![after](https://github.com/misskey-dev/misskey/assets/48310258/a70a5029-f501-4e7c-b59a-d9f89705e5bb)

Misskey 2024.3.1

**Comment by Sayamame-beans** [comment]
メンションに入っていて宛先に入っていないダイレクト投稿は、相手に通知は届きますが読めないという仕様なので(微off-topic:そしてそれを後から確かめる術はAPIでノートのパラメーターを見る以外無かったりする)割と困ると思います。
一応警告は表示されていますが、何度か追加し忘れるミスをやったことがあります…
