### ISSUE TITLE
kbin(またはそのフォーク)での"Link"のタイプの投稿がMisskeyでは読み込めずエラーになる

### ISSUE THREAD

**Issue by blue0a6m5c** [syuilo/Misskey#13729]
### 💡 Summary

kbinなどのユーザーをフォローしていても"Add new Link"もしくは"新しいリンクを追加"で投稿されたものはエラーとなってTLに表示できない様子です。
照会を行ってもエラーになっています。

### 🥰 Expected Behavior

Misskey側でも投稿として認識される

### 🤬 Actual Behavior

Apr 17 15:14:19 hostname misskey[1466939]: INFO *        [remote ap]        Creating the Note: https://mbin.kyanos.one/m/hr_hm/t/4
Apr 17 15:14:19 hostname misskey[1466939]: ERR  *        [api]        Internal error occurred in ap/show: invalid image: url not provided {
Apr 17 15:14:19 hostname misskey[1466939]:   ep: 'ap/show',
Apr 17 15:14:19 hostname misskey[1466939]:   ps: {
Apr 17 15:14:19 hostname misskey[1466939]:     uri: 'https://mbin.kyanos.one/m/hr_hm/t/4/Rainbow-I-Surrender',
Apr 17 15:14:19 hostname misskey[1466939]:     i: 'KleXdjuHFAo7JXx5'
Apr 17 15:14:19 hostname misskey[1466939]:   },
Apr 17 15:14:19 hostname misskey[1466939]:   e: {
Apr 17 15:14:19 hostname misskey[1466939]:     message: 'invalid image: url not provided',
Apr 17 15:14:19 hostname misskey[1466939]:     code: 'Error',
Apr 17 15:14:19 hostname misskey[1466939]:     stack: 'Error: invalid image: url not provided\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at ApImageService.createImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:52:19)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async ApImageService.resolveImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:94:16)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async Promise.all (index 0)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:194:23)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async _class.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:150:141)\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:111:28\n' +
Apr 17 15:14:19 hostname misskey[1466939]:       '    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16)',
Apr 17 15:14:19 hostname misskey[1466939]:     id: '88ac9835-a69c-40bc-b595-40761445f073'
Apr 17 15:14:19 hostname misskey[1466939]:   }
Apr 17 15:14:19 hostname misskey[1466939]: }
Apr 17 15:14:19 hostname misskey[1466939]: Error: invalid image: url not provided
Apr 17 15:14:19 hostname misskey[1466939]:     at ApImageService.createImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:52:19)
Apr 17 15:14:19 hostname misskey[1466939]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Apr 17 15:14:19 hostname misskey[1466939]:     at async ApImageService.resolveImage (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApImageService.js:94:16)
Apr 17 15:14:19 hostname misskey[1466939]:     at async Promise.all (index 0)
Apr 17 15:14:19 hostname misskey[1466939]:     at async ApNoteService.createNote (file:///home/misskey/misskey/packages/backend/built/core/activitypub/models/ApNoteService.js:194:23)
Apr 17 15:14:19 hostname misskey[1466939]:     at async _class.fetchAny (file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:150:141)
Apr 17 15:14:19 hostname misskey[1466939]:     at async file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/ap/show.js:111:28
Apr 17 15:14:19 hostname misskey[1466939]:     at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:317:16) 88ac9835-a69c-40bc-b595-40761445f073

### 📝 Steps to Reproduce

1. Misskeyのアカウントでフォローしているkbinなどのアカウントで”リンク”の投稿をする or 投稿を照会する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): DIY PC Windows 11 Pro 22H2
* Browser: Vivaldi 6.6.3271.61 (Stable channel) (64-bit) 
* Server URL: mi.kyanos.one (misskey.io)
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Ubuntu 23.10, Proxmox VM, Ubuntu版Misskeyインストール方法詳説
* Misskey: 2024.3.1
* Node: v20.12.2
* PostgreSQL: 16.2
* Redis: 7.0.12
* OS and Architecture: Ubuntu 23.10 (GNU/Linux 6.5.0-27-generic x86_64)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by mei23** [comment]
attachmentの中のリンクを添付扱いしてしまっている
```json5
{
  type: 'Page',
  :
  attachment: [
    {
      href: 'https://www.youtube.com/watch?v=iMmMqfQZkxA',
      type: 'Link'
    }
  ]
}
```
