### ISSUE TITLE
特定のハッシュタグの投稿が連合先から参照すると連合元のハッシュタグリンクになる

### ISSUE THREAD

**Issue by Misaki0331** [syuilo/Misskey#13731]
### 💡 Summary

題名の通り、特定の文字列を含むハッシュタグを投稿すると連合先でリンク化し、連合元のハッシュタグのリンクに飛ばされる。

### 🥰 Expected Behavior

全てのハッシュタグにおいて自分のサーバーで参照する。

### 🤬 Actual Behavior

「！」「？」「①(囲み数字)」「Ⅰ(ローマ数字)」等記号を使用したハッシュタグが全て連合元のハッシュタグにリンク化する

例(逆も同じ)：
Misskey.io上での投稿
```
#テスト！
#テスト？
#テスト①
#テストⅠ
```

外部Misskey(2024.3.1)インスタンスから見た投稿
```
[#テスト！](<https://misskey.io/tags/テスト！>) 
[#テスト？](<https://misskey.io/tags/テスト？>) 
[#テスト①](<https://misskey.io/tags/テスト①>) 
[#テストⅠ](<https://misskey.io/tags/テストⅠ>)
```

### 💻 Frontend Environment

```markdown
Misskey1: ingen.work 2024.3.1
Misskey2: misskey.backspace.fm 2024.3.1-bsk-5.2.5
Misskey3: misskey.io 2024.3.1-io.6
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
#13192 で条件下でMFMを省略してhtmlのみ送信しパースする形になった際、パース側でのハッシュタグの復元がうまく行ってなさそうですね。MFM省略が行われないものでは連合がうまく行っています。

https://misskey.io/notes/9s9p5vmphu9t00ev

https://misskey.io/notes/9s9pcekia7d200dq

**Comment by anatawa12** [comment]
HTMLのパース時には完全一致でハッシュタグのマッチをしているけどAP上の`tag:[]`はNFKCノーマライズ済なのでマッチしないようですね。HTML => MFM時にnormalizeForSearchをかけるのがよさそう？
(`#テスト①`が`#テスト1`にノーマライズされてる)

HTML => MFM
https://github.com/misskey-dev/misskey/blob/ea9aa6fdb41d3d5c0611f17fdacedee4861fdd37/packages/backend/src/core/MfmService.ts#L88

MFM => tags
https://github.com/misskey-dev/misskey/blob/ea9aa6fdb41d3d5c0611f17fdacedee4861fdd37/packages/backend/src/core/NoteCreateService.ts#L419

<img width="398" alt="image" src="https://github.com/misskey-dev/misskey/assets/22656849/6520e509-42b7-497f-894f-50db8ac58502">
