### ISSUE TITLE
`pnpm dev`の前にdevcontainerなりなんなりでpostgresとredisを立ち上げておく必要があることを明記してほしい

### ISSUE THREAD

**Issue by 1inguini** [syuilo/Misskey#13753]
### Summary

CONTRIBUTING.mdには`pnpm dev`するといいぐらいしか書かれておらずPostgreSQLとかRedisが必要なことが分かりづらいです
いやまあMisskeyがPostgresとか使ってることは知られてますし、即devcontainerを立ち上げていれば意識する必要もないのかもしれないですがひとことふたことあったほうが親切だと思います

### Purpose

ドキュメンテーションを充実させ、(特にMisskeyの技術スタックに馴染みの薄い初心者が)開発を初めやすくする

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by KisaragiEffective** [comment]
同様の問題が`pnpm dlx typeorm migration:generate -d ormconfig.js`にもあると思う:

```
$ pnpm dlx typeorm migration:generate -d ormconfig.js forceSensitiveEmojiToNonPublic
Error during migration generation:
Error: getaddrinfo ENOTFOUND db
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'db'
}
```
