### ISSUE TITLE
backend: Misskeyから連合されたノートにCWやセンシティブなメディアが存在すると非センシティブなメディアもセンシティブとして連合されてくる

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13755]
### 💡 Summary

リモートサーバーからのノートにCWやセンシティブなメディアが存在すると、同じノートに存在する非センシティブなメディアもセンシティブとして連合されてくる

### 🥰 Expected Behavior

非センシティブは非センシティブとして連合されてほしい

### 🤬 Actual Behavior

非センシティブもセンシティブとして連合される

### 📝 Steps to Reproduce

1. サーバーAで条件に当てはまるノートをする
2. (サーバーAがサーバーBにノートを連合する)
3. サーバーBから当該ノートを見る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): `6.6.13+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15) GNU/Linux` (`uname -ovr`)
* Browser: Mozilla Firefox 125.0.1
* Server URL: https://buicha.social -> https://misskey.niri.la
* Misskey: 2024.3.1-buiso.2 -> 2024.3.1-kinel.4
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A (not admin)
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by mei23** [comment]
たいていMastodonがNote単位でsensitiveなせい
![image](https://github.com/misskey-dev/misskey/assets/30769358/d01c4339-1bd5-44fb-b54a-74de09c672ba)

**Comment by KisaragiEffective** [comment]
> たいていMastodonがNote単位でsensitiveなせい
はい。とはいえMisskey同士ではattachment.sensitiveが存在することが保障されているのであるんだったらそっちを見てほしいなぁという気持ちです

**Comment by mei23** [comment]
> Misskey同士ではattachment.sensitiveが存在することが保障されている

いや、これがされてないどころか送られてくることはないはずなのだわ。

attachmentにsensitiveは存在しない (Document扱いで送るので)
https://github.com/misskey-dev/misskey/blob/e2ff5f58b2357b2433313b2885e7de7923f65205/packages/backend/src/core/activitypub/ApRendererService.ts#L163-L170

でもなぜか、アバターとヘッダーには付いてる (Image扱いで送るので)
https://github.com/misskey-dev/misskey/blob/e2ff5f58b2357b2433313b2885e7de7923f65205/packages/backend/src/core/activitypub/ApRendererService.ts#L243-L250

**Comment by KisaragiEffective** [comment]
> attachmentにsensitiveは存在しない (Document扱いで送るので)

> でもなぜか、アバターとヘッダーには付いてる (Image扱いで送るので)

？？？

**Comment by mei23** [comment]
> attachmentにsensitiveは存在しない (Document扱いで送るので)
> でもなぜか、アバターとヘッダーには付いてる (Image扱いで送るので)

とくに変更したことについて言及されてなかったのでこうなった経緯はわからなかったわ
https://github.com/misskey-dev/misskey/pull/7518/files#diff-f05b88a76131371efe8ae5c3215ca321914db8230135fbdc3d1e5f01f2bebebf

**Comment by KisaragiEffective** [comment]
とりあえずsensitiveをrenderDocumentから送る方向で調整しました

**Comment by mei23** [comment]
Related https://github.com/misskey-dev/misskey/issues/11209

**Comment by mei23** [comment]
> attachmentにsensitiveは存在しない (Document扱いで送るので)
> でもなぜか、アバターとヘッダーには付いてる (Image扱いで送るので)

は、v4.25.0 (6年前) あたりからあった実装ミスっぽいわ
https://github.com/misskey-dev/misskey/commit/ec2b1ec3f0035466585d9cc2a7842e519e14e31a
