### ISSUE TITLE
文字数制限の「もっと見る」を回避できるポリシーを追加

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13763]
### Summary

お知らせアカウントなど、「もっと見る」が出てしまうと困るアカウントに対して当該ポリシーを適用することができるようにする

![image](https://github.com/misskey-dev/misskey/assets/67428053/aa3730dc-810b-4b0b-96ff-26f34e7daaa9)
（↑ これを回避して、強制的に全体を表示できるようなロールポリシー）

### Purpose

モデレーションをやりやすくする

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
もっと見るが出たとしてもそんなに困らない気はする
むしろUXが損なわれる可能性があるデメリットの方が大きそう

**Comment by syuilo** [comment]
> ユーザーが困るというよりかは鯖管が困るというかんじかも

鯖缶として困らないのではないかと思った
