### ISSUE TITLE
自分以外のクリップ内のノート個数が見えることがある

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#13781]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/67428053/d2cbcfb3-426c-4cea-badd-c46d6141a9d3)

### 🥰 Expected Behavior

見えない or 残数の計算をしない

### 🤬 Actual Behavior

見える＋残数は自分のベースロールをもとに計算される

### 💻 Frontend Environment

```markdown
OS: Windows 11
Browser: 124.0.6367.91 (Official Build) （64 ビット） (cohort: Stable)
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
![image](https://github.com/misskey-dev/misskey/assets/48310258/d48f73e5-77b0-41d6-80f6-ce9453eb7554)
ちょうど首かしげていた
