### ISSUE TITLE
Check Misskey JS autogen / generate-misskey-js (pull_request_target) がコケる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#13813]
### 💡 Summary

```
Run pnpm build
 ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.6 of pnpm. Your current pnpm is v9.1.0

If you want to bypass this version check, you can set the "package-manager-strict" configuration to "false" or set the "COREPACK_ENABLE_STRICT" environment variable to "0"
Error: Process completed with exit code 1.
```

とのこと。

### 🥰 Expected Behavior

CIが動作する

### 🤬 Actual Behavior

CIが動作しない

### 📝 Steps to Reproduce

Check Misskey JS autogen / generate-misskey-js (pull_request_target)を動作させる

### 💻 Frontend Environment

```markdown
※CIの問題なので記載なし
```

### 🛰 Backend Environment (for server admin)

```markdown
※CIの問題なので記載なし
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by anatawa12** [comment]
そういえばこの問題自体は https://github.com/misskey-dev/misskey/pull/13825 で治った？ pnpm を更新するのは別としてあるべきな気がするけど

**Comment by samunohito** [comment]
最近は起こってないようなので（たぶんanatawaさんの仰る通り）、こちらはcloseします。
