### ISSUE TITLE
「見たことのあるリノートを省略して表示」機能の名前変更

### ISSUE THREAD

**Issue by nenohi** [syuilo/Misskey#13822]
### 💡 Summary

「見たことのあるリノートを省略して表示」機能が現状、リアクションを行わないと省略されないため、名前の変更が必要

### 🥰 Expected Behavior

機能と名前の一致

### 🤬 Actual Behavior

実機能と名前が不一致状態

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Windows
* Browser:Google Chrome
* Server URL:misskey.io
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
「リアクションしたリノートを省略して表示」で良いのでは…？🤔

**Comment by syamatsumi** [comment]
「反応を返したリノートを省略して表示」てのはどうでしょう？

**Comment by syuilo** [comment]
今後改修されることは十分考えられるので、機能名は「リノートのスマート省略」とかにしといて説明は別途表示させれば良さそう
