### ISSUE TITLE
ノートアクションバーに「お気に入り」を追加。

### ISSUE THREAD

**Issue by slormo** [syuilo/Misskey#13831]
### Summary

他のどのアクションよりも投稿をお気に入りに入れるのは一般的です。タイムライン上で投稿をお気に入りする場合、いちいちサブメニューを使うのは不便です。ノートアクションバーに直接お気に入りボタンを追加できるようにしてください。

文法がおかしかったらすみません。ありがとうございました！

### Purpose

Favouriting a note is one of the most common actions a user does, however the to favourite a note is hidden behind a sub-menu, which disrupts the flow of browsing. Adding it directly to the note actions will be more comfortable for users.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
「お気に入り」は上位互換機能である「クリップ」に置き換えられる予定です。
クリップは既にノートアクションバーに表示することが可能です。

**Comment by slormo** [comment]
そうでしたか。

私としては、お気に入りが同じ機能を満たし、量に制限されないのであれば、クリップを使う必然性はないと思います。ただ、後で見返すために分類されていないリストにメモを追加したいときは、お気に入り機能の方がはるかに便利で有用です。クリップは50ノートまでなので、整理するときに制限があります。その点、お気に入りの方が制限が少ないと感じます。

要するに、「お気に入り 」セクションは私にとって、追加できる投稿が無限にある、既製のクリップなのです。


迅速な対応に感謝します！

**Comment by t1nyb0x** [comment]
「お気に入り」が「クリップ」に置き換えられる予定のため、未計画としてクローズします。
