### ISSUE TITLE
絵文字が空文字であってもノートにリアクションとして登録できてしまう

### ISSUE THREAD

**Issue by Misaki0331** [syuilo/Misskey#13832]
### 💡 Summary

notes/reactions/create のエンドポイントにて
``reaction : ""``として叩いても❤にならずに見えないリアクションが登録できてしまう

ローカル環境でも同様の不具合を再現しました。

以下は問題が発生する該当のノート、画像が表示されない絵文字にクリックしてリアクションをすることでも同様の現象が発生する。(ノートの内容をコピーして各自でテストすることを推奨します)
https://misskey.io/notes/9tgfn7rgtcjj0bh4

### 🥰 Expected Behavior

存在しない絵文字は「❤」に置き換えられてリアクションされる。

### 🤬 Actual Behavior

空文字としてリアクションを登録できてしまう
ユーザーページのリアクションではノートが表示されるがリアクションとして表示されない。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:2024.5.0
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #13804 ?

**Comment by Misaki0331** [comment]
> duplicate of #13804 ?
かも

重複していたようなので閉じます🙏
