### ISSUE TITLE
Migration Bug Cannot create an alias  if the  UI language is spanish

### ISSUE THREAD

**Issue by nekoprogram** [syuilo/Misskey#13848]
### 💡 Summary

When i've tried to migrate my account from aethy.com a mastodon instance, to my account in misskey account located in https://misskey.social if the UI is set in Spanish the migration settings to write the alias don't show the <input /> to write the handle from your origin instance in this case was aethy.com 

The developer console output throws an error that i will attach to this issue

When i've changed the UI to english this bug is not happened and the input has been revealed.
![Captura de pantalla 2024-05-20 222652 - copia](https://github.com/misskey-dev/misskey/assets/153431754/e2c4ad85-1653-4de2-9430-6b78794d1c84)

If ui is changed to English the UI Input shows and console don't throws any error
![Captura de pantalla 2024-05-20 222805](https://github.com/misskey-dev/misskey/assets/153431754/d4412397-d40c-4e80-960e-b152821ff8f6)

 

### 🥰 Expected Behavior

The text box should have been displayed regardless of the user's language. 

### 🤬 Actual Behavior

the  input don't  has not been displayed 

### 📝 Steps to Reproduce

1. Go to https://misskey.social and create an account  
2. Change UI language to Spanish
3. Go to settings / Configuración >> Account migration / Migración de cuenta >> Migrate an account to this one / Trasladar de otra cuenta a ésta 
4. Clic on Add Button with Developer tools open. The console shows the error
![Captura de pantalla 2024-05-20 222652](https://github.com/misskey-dev/misskey/assets/153431754/88d0cf2c-f410-43f9-839b-5209d59f97f9)

I also checked with other misskey instance (https://submarin.online/) Misskey version  v2024.3.1 And can reproduce the same bug 
![submarin](https://github.com/misskey-dev/misskey/assets/153431754/31fb972d-9149-4551-b0f6-e631050cf747)
If change the language in this instace the error dissapears
![othe](https://github.com/misskey-dev/misskey/assets/153431754/ade97d44-f949-493a-8704-14a9cb31186e)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): PC Windows 10 Build 10.0.19045.4412
* Browser: Google Chrome Version 125.0.6422.60
* Server URL: https://misskey.social/
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Mar0xy** [comment]
This was a bug caused by the locales being messed up in some languages missing the parameter that was suppose to be used.

This was fixed in this commit https://github.com/misskey-dev/misskey/pull/13500/commits/dc181cfca361b303720c6cc71696d3fff0250781 but obviously it only is available in a beta release currently.

**Comment by nekoprogram** [comment]
Seems the issue has been resoved with the last update Thank you so much !
![misskey_fixed](https://github.com/user-attachments/assets/fc40c1ae-0c75-4e06-a235-f1842a0b8983)
