### ISSUE TITLE
RATE_LIMIT_EXCEEDED while using API with admin privileges

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#13873]
### 💡 Summary

When you exceed API requests number within a certain limit, API will return 429 HTTP error saying RATE_LIMIT_EXCEEDED

### 🥰 Expected Behavior

When I create an API token, I have option for give it administration privileges.  
As Administrator, I expected a **BYPASS RATE LIMIT** administrative privilege.

### 🤬 Actual Behavior

API calls made by administrative tokens are RATE LIMITED.

### 📝 Steps to Reproduce

1. login with administrator profile
2. create an API token having all administrative privileges
3. do a sequence of API calls, such as deleting remote notes and their attachments
4. iterate that sequence until you reach RATE_LIMIT_EXCEEDED exception

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): API calls
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker master branch
* Misskey: 2024.3.1
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by acid-chicken** [comment]
> As Administrator, I expected a BYPASS RATE LIMIT administrative privilege.

You should configure policies of the Administrator role manually to disable rate limits.
![](https://github.com/misskey-dev/misskey/assets/20679825/4c0db113-6713-43e1-97ed-65a7a451c6bc)

**Comment by tassoman** [comment]
Thanks @acid-chicken !
I have to admit, that role's feature was unclear to me. I will also update Italian translations to make it more clear.
