### ISSUE TITLE
コンテキストメニューをブラウザのデフォルトに戻す機能がほしい

### ISSUE THREAD

**Issue by shirokuronemuri** [syuilo/Misskey#13914]
### Summary

misskeyのコンテキストメニューをブラウザのデフォルトのやつに設定で変えたいけど今のところはできないらしいからそれをお願いしたいです。

### Purpose

カスタムのメニューに全然慣れてないから使いづらいです。特に辛いのは「新しいタブで開く」の操作がデフォよりずっと下にいることです。普通は一瞬しかかからない操作に毎回数秒費やすのがちょっとイライラします。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by t1nyb0x** [comment]
> 特に辛いのは「新しいタブで開く」の操作がデフォよりずっと下にいることです

具体的にどこの画面での操作のことを指しているのでしょうか。
