### ISSUE TITLE
bash-installでdockerを用いてインストールした際、サーバーが立ち上がらない

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#13925]
### 💡 Summary

misskeyのdockerイメージを立ち上げようとすると、unhealtyのままになる

（おそらく原因がbash-installではなくDockerfileにあるのでここにissueを上げる）

`pnpm@9.0.6`を使うことになった影響で`pnpm`を呼び出そうとすると対話式で9.0.6をインストールしようとするのが原因？

### 🥰 Expected Behavior

healthyになってほしい

### 🤬 Actual Behavior

unhealthyとなって立ち上がらない

`docker logs -t ${container id}`した結果はこう

```log
Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.6.tgz.
```

![image](https://github.com/misskey-dev/misskey/assets/40626578/ad46eb14-2dce-4a54-afa3-0ec475b9208d)
↑
画像の状態で静止して立ち上がらない

### 📝 Steps to Reproduce

1. bash-installの手順に沿ってdocker環境を選択してMisskeyサーバーを立ち上げる
2. 起動しない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: bash-install v3 (docker) 
6db958e
* Misskey: 2024.5.0 (docker-hub misskey/misskey:latest on 2024/06/01 19:31 JST)
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture: Ubuntu 22.04
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
上に書いたログ部分は自分のサーバーで起こったログで添付画像は再現性チェックのために1から立ち上げたやつ

**Comment by tai-cha** [comment]
bash-installのupdate.ubuntu.shでも同様に起こるがおそらくDockerfileのほうを何とかする必要がある

**Comment by tai-cha** [comment]
一時的な対応として`docker exec -it /bin/bash`とかでコンテナに入ってあげて
```
pnpm install
pnpm migrate
```
をした後にコンテナ再起動したら立ち上がりはした
でもコンテナ消したらおそらくもう一度やらなければいけない

**Comment by tai-cha** [comment]
多分起動用に`pnpm run migrateandstart`を呼ぶけどそもそもpnpm入ってないよってなってる

**Comment by tai-cha** [comment]
Corepackで対話式ではなくpackageVersionに合わせたpnpmをインストールしておけるのかしら

**Comment by anatawa12** [comment]
ちょっとぐぐってみたら`corepack pack`が使えそう？

**Comment by anatawa12** [comment]
`corepack install`っぽいです

**Comment by tai-cha** [comment]
Dockerfileに書いて早めに新バージョンを出す必要がありそう

**Comment by anatawa12** [comment]
今手元でもう少し試した感じ、stdinがない/consoleでない場合には止まらずに勝手にCorepackはダウンロードするようで、`docker run --rm misskey/misskey:2024.5.0`した感じ止まることはなかったのでdocker containerのネットの設定等に依存する可能性もあるかもしれない？

```
$ docker run --rm misskey/misskey:2024.5.0
Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.6.tgz.

> misskey@2024.5.0 migrateandstart /misskey
> pnpm migrate && pnpm start


> misskey@2024.5.0 migrate /misskey
> cd packages/backend && pnpm migrate


> backend@ migrate /misskey/packages/backend
> pnpm typeorm migration:run -d ormconfig.js

Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". ENOENT: no such file or directory, open '/misskey/.config/default.yml'
    at CommandUtils.loadDataSource (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.11.5/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_pg@8.11.5/node_modules/typeorm/commands/MigrationRunCommand.js:40:26)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ```

ビルド時にダウンロードしたほうがいいことには変わりないと思いますが。

**Comment by anatawa12** [comment]
https://pnpm.io/ja/next/docker#example-2-build-multiple-docker-images-in-a-monorepo

これとか見ると`corepack install`してなかったりするのでdockerfile側の問題かは少し怪しいところがあるかもしれない？

```
Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.6.tgz.
```

で止まるのの再現例他のところからもほしいきがします

**Comment by tai-cha** [comment]
ちなみにこれupdate deps前は起きていないので謎
