### ISSUE TITLE
アイコン/バナーを設定出来なくするロール権限が欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#13935]
### Summary

現状、アイコンやバナーの設定を解除することは出来ますが、ユーザーは再設定することが出来ます。
また、リモートユーザーの場合は、ローカルでの対処にかかわらず一定時間後に自動でアイコン/バナーが復活します。
従って、これを設定出来なくするロール権限を追加して欲しいです。

なお、アイコンとバナーをセットで扱って良いと考えていますが、別々である方が良いと考えられる場合は別々でも問題ありません。

### Purpose

モデレーションに必要

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
ちょっとrelated: #13676

**Comment by u1-liquid** [comment]
FYI: https://github.com/MisskeyIO/misskey/pull/374
