### ISSUE TITLE
Support nodejs 21.x

### ISSUE THREAD

**Issue by spirillen** [syuilo/Misskey#13934]
### 💡 Summary

sudo npm install -g 20
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

### 🥰 Expected Behavior

The opposed of this, as version 20.x with it's deps is full of security bugs

```
Process: pnpm install;
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/home/misskey/misskey/packages/backend".

Expected version: ^20.10.0
Got: v21.7.3

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
Process: start daemon;
```

### 🤬 Actual Behavior

See above

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
related: https://github.com/misskey-dev/misskey/pull/13928

**Comment by anatawa12** [comment]
We're not planned to support node v21, which is not LTS, at least for now.
It's a expected behavior to denying node 21.

Could you explain why do you want nodejs 21?

**Comment by spirillen** [comment]
> Could you explain why do you want nodejs 21 support?

Please see the "Expected Behavior" above, and it is used by other software on the box like peertube

And misskey have been running fine under version 21 for month, I have nothing to complain about there

**Comment by anatawa12** [comment]
> Please see the "Expected Behavior" above

> **🥰 Expected Behavior**
> 
> The opposed of this, as version 20.x with it's deps is full of security bugs


If you're saying about several deprecated message when executing `npm i -g 20`, it's not related to node.js v20.
The command `npm i -g 20` installs npm package named 20 (https://www.npmjs.com/package/20) but Misskey requires node.js version 20, which should be installed from https://nodejs.org/en/download.

> and it is used by other software on the box like peertube

You should use different node.js for software requires different node.js. 

> And misskey have been running fine under version 21 for month, I have nothing to complain about there

Allowing using node.js 21 or later was a bug and fixed recently.

**Comment by anatawa12** [comment]
We are not planned to support node v21 so closing this issue.
