### ISSUE TITLE
The Golang / Rust backend project!

### ISSUE THREAD

**Issue by PichuChen** [syuilo/Misskey#13938]
### Summary

Impliment the golang / rust backend.
golang/Rust バックエンドを実装します。

### Purpose

The rps between Rust / Go and Node.js is about 4 times and more [1][2]
Rust / Go と Node.js の RPS は約 4 倍以上です。[1][2]

But we have about 371 Endpoints to be refactored to Rust / Go.
If we refactor 2 API one week, it will take about 3.5 years to complete the refactoring. (371 / 2 / 52 = 3.5)
約 371 のエンドポイントを Rust / Go にリファクタリングする必要があります。
1 週間に 2 つの API をリファクタリングした場合、リファクタリングを完了するには約 3.5 年かかります。 (371 / 2 / 52 = 3.5)
![image](https://github.com/misskey-dev/misskey/assets/600238/c9467116-6150-4b82-aa88-6e1dc2c0b3ca)

And we will still have new feature to develop.
そして、新しい機能を開発する必要があります。

So I suggest to impliment golang / rust backend and proxy the unrefactored endpoints to the node.js backend.
そのため、golang / rust バックエンドを実装し、リファクタリングされていないエンドポイントを node.js バックエンドにプロキシします。

In fact, I don't think the site that users less then 100 will get any benefit from the refactoring.
実際、100 未満のユーザーを持つサイトは、リファクタリングから何の利益も得られないと思います。

But we have a site more the 52K user now, the poor performance means the huge cost.
しかし、現在 52K 以上のユーザーを持つサイトがあり、パフォーマンスの低下は莫大なコストを意味します。

So this thing is very important for us.
したがって、このことは私たちにとって非常に重要です。

I think we will have a golang and rust backend in December, and it will take over some tidous works from the node.js backend.
For example, reply inbox request, assign access token, etc. And new features (for example, games) will be developed in node.js
12 月には golang と rust バックエンドがあり、node.js バックエンドからいくつかの煩雑な作業を引き継ぎます。
たとえば、返信インボックスリクエスト、アクセストークンの割り当てなどです。新機能（たとえば、ゲーム）は node.js で開発されます。

I already have a version of this project.
このプロジェクトのバージョンはすでに持っています。

https://github.com/PichuChen/misskey/tree/backend2

I have almost 10 years experience in golang and about 2 days in rust, so I think I can not make the perfect rust code in a short time.
私は golang でほぼ 10 年の経験があり、rust で約 2 日の経験があるため、短期間で完璧な rust コードを作成することはできないと思います。

There are a sentence called 「拋磚引玉」  in Chinese, which means throw a brick to attract jade. 
It means I will write some code in rust, and hope the rust expert can help me to improve it.
中国語には「拋磚引玉」という言葉があります。これは、玉を引き寄せるために煉瓦を投げるという意味です。
これは、私が rust でいくつかのコードを書き、rust の専門家がそれを改善するのを助けてくれることを願っています。

And we can compare the performance between the golang / rust (and node.js) backend. The site owner can choose the best backend for their site.
そして、golang / rust（および node.js）バックエンドのパフォーマンスを比較できます。サイトの所有者は、サイトに最適なバックエンドを選択できます。

I think it is the instresting part of open source project.
これはオープンソースプロジェクトの面白い部分だと思います。

[1] https://www.linkedin.com/pulse/bun-node-go-rust-rps-benchmark-srivin-prabhash/
[2] https://dev.to/ocodista/node-vs-go-api-showdown-4njl

https://discord.com/channels/891696148849508423/1246351116720017408

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tamaina** [comment]
Duplicate of #11078
