### ISSUE TITLE
gen-spec.ts does not follow the OpenAPI specification, giving the same operatorId

### ISSUE THREAD

**Issue by Lhcfl** [syuilo/Misskey#13939]
### 💡 Summary

`gen-spec.ts` does not follow the OpenAPI specification, giving the same `operatorId`, which causes problems when viewing api doc using other tools (such as [Elements](https://github.com/stoplightio/elements))

https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/openapi/gen-spec.ts#L214

> `operationId` is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API. https://swagger.io/docs/specification/paths-and-operations/

### 🥰 Expected Behavior

`get` and `post` should use different `operatorId`

### 🤬 Actual Behavior

`gen-spec.ts` does not follow the OpenAPI specification, giving the same `operatorId`, which causes problems when viewing api doc using other tools (such as [Elements](https://github.com/stoplightio/elements))

An example is: 

```json
"/emoji": {
            "get": {
                "operationId": "emoji",
                 // ...
            }
            "post": {
                "operationId": "emoji",
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
related: #13498
