### ISSUE TITLE
showNoteActionsOnlyHover

### ISSUE THREAD

**Issue by GimGaram** [syuilo/Misskey#13944]
こんにちは。

Misskeyの「設定」で「全般」の「ノートの表示」にある「ミュートされた単語を含むノートを非表示にする」がCrowdinにないので、他の言語では長い間英語の文のまま「Hide notes containing muted words」と表示されています。

個人的にはこれが意図的な設計なのかどうか分かりませんので、ご確認いただけますと幸いです。

**Comment by t1nyb0x** [comment]
この表示は翻訳データがないために表示されています。

すみませんが、テンプレートに従った記入をしていただけないでしょうか。
こちらのIssueクローズさせていただきます。
