### ISSUE TITLE
meidの非推奨化

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13947]
### Summary

Misskeyの採番として採用されているmeidを非推奨にします。

### Purpose

meidはconfigの例示で説明されているようなミリ秒単位の[精度](https://github.com/misskey-dev/misskey/blob/43cccaaee9be42fab38eaa9ca04bb5e55b5d8db7/.config/example.yml#L199)を保証できていません。これは、ミリ秒に加算するオフセットが`Number.MAX_SAFE_INTEGER`を越していることに起因します。

具体的には、 https://github.com/misskey-dev/misskey/blob/43cccaaee9be42fab38eaa9ca04bb5e55b5d8db7/packages/backend/src/misc/id/meid.ts から型注釈を取り除いた\[code 1\]を用いて、\[code 2\]を実行すると、\[snippet 3\]が得られます。
\[code 1\]:
```js
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

const CHARS = '0123456789abcdef';

// same as object-id
const meidRegExp = /^[0-9a-f]{24}$/;

function getTime(time) {
    if (time < 0) time = 0;
    if (time === 0) {
        return CHARS[0];
    }

    time += 0x800000000000;

    return time.toString(16).padStart(12, CHARS[0]);
}

function getRandom() {
    let str = '';

    for (let i = 0; i < 12; i++) {
        str += CHARS[Math.floor(Math.random() * CHARS.length)];
    }

    return str;
}

function genMeid(t) {
    return getTime(t) + getRandom();
}

function parseMeid(id) {
    return {
        date: new Date(parseInt(id.slice(0, 12), 16) - 0x800000000000),
    };
}

function isSafeMeidT(t) {
    return t > 0;
}
```

\[code 2\]:
```
console.log(genMeid(Date.now("2024-06-04T12:34:56+0900")))
// genMeid(Date.now("2024-06-04T12:34:56+0900")) で生成したmeidの一つ
console.log(parseMeid("818fe317a7936680af670e22").toISOString())
```

\[snippet 3\]:
```
818fe317a7936680af670e22
2024-06-04T11:52:09.363Z
```

しかし、これは`Date.now()`から得られた`const n: number` に対して、 `parseMeid(genMeid(n)).date.getTime() == n`がいつも成り立つとは限らないことを示しています。
記憶が正しければ、現行の実装は付番されたIDから作成日時を抽出しているため、meidを付番形式として採用しているインスタンスは半日程度の作成時間のズレが生じてしまい、実質的に作成日時が意味をなさないものとなってしまっています。

そこで、`meid`を非推奨化することを提案します。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by zyoshoka** [comment]
[code 2] で `Date.now("2024-06-04T12:34:56+0900")` となっていますが、`Date.parse("2024-06-04T12:34:56+0900")` とするとちゃんと再現されるかと思います。

**Comment by KisaragiEffective** [comment]
> [code 2] で `Date.now("2024-06-04T12:34:56+0900")` となっていますが、`Date.parse("2024-06-04T12:34:56+0900")` とするとちゃんと再現されるかと思います。

確かに
```
console.log(genMeid(Date.parse("2024-06-04T12:34:56+0900")));
console.log(parseMeid("818fe1506f0067797c82d7b7").date.toISOString());
```

とすると、

```
818fe1506f0067797c82d7b7
2024-06-04T03:34:56.000Z
```

となり合致しました。
お騒がせしました。
