### ISSUE TITLE
frontend: リモートユーザーのユーザーページの追加情報ラベルに絵文字が含まれている場合、ローカルの絵文字で表示されてしまう

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13953]
### 💡 Summary

リモートユーザーのユーザーページの追加情報のラベルにカスタム絵文字が含まれている場合、ローカルのカスタム絵文字で表示されてしまう

### 🥰 Expected Behavior

リモートのカスタム絵文字で表示されてほしい

### 🤬 Actual Behavior

ローカルのカスタム絵文字として表示されてしまう

### 📝 Steps to Reproduce

1. サーバーAからサーバーBのリモートユーザーを照会する
    * リモートユーザーの追加情報にカスタム絵文字が入っている必要がある
2. そのリモートユーザーの追加情報のラベルを見る
3. そのカスタム絵文字がローカルのemojiCodeで引かれる
4. リモートのカスタム絵文字が表示されず、ローカルのカスタム絵文字になったりテキストになったりする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Linux 6.6.13+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15) x86_64
* Browser: Mozilla Firefox 125.0.2
* Server URL: https://misskey.niri.la/
* Misskey: 2024.5.0-kinel.1
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A (not a server admin)
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
確認点1: 絵文字というのはunicode絵文字ではなくemojiCode(`:emoji:`)のことを指している認識で間違いないですよね
(ローカル/リモートの区別があるので自明かもしれませんが)
確認点2: 追加情報のラベル部分、本文共に発生していますか？
- おそらくラベル部分のはず

```vue
<Mfm :text="field.name" :plain="true" :colored="false"/>
```
https://github.com/misskey-dev/misskey/blob/9849aab40283cbde2184e74d4795aec8ef8ccba3/packages/frontend/src/pages/user/home.vue#L97-L107
詳細情報のラベルにはauthorが渡されていなくて本文にはauthorが渡されているのが原因そう

**Comment by KisaragiEffective** [comment]
> * 確認点1: 絵文字というのはunicode絵文字ではなくemojiCode(`:emoji:`)のことを指している認識で間違いないですよね
>       (ローカル/リモートの区別があるので自明かもしれませんが)

はい、emojiCodeを意図しています

>     * 確認点2: 追加情報のラベル部分、本文共に発生していますか？
>       
>       * おそらくラベル部分のはず

ラベルのみ発生していて、本文 (値) の方は発生していません

> ```
> <Mfm :text="field.name" :plain="true" :colored="false"/>
> ```
> 
> https://github.com/misskey-dev/misskey/blob/9849aab40283cbde2184e74d4795aec8ef8ccba3/packages/frontend/src/pages/user/home.vue#L97-L107
> 
> 詳細情報のラベルにはauthorが渡されていなくて本文にはauthorが渡されているのが原因そう

👀
