### ISSUE TITLE
Dockleのworkflowの機嫌が悪い

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13976]
[Dockleのworkflow](https://github.com/misskey-dev/misskey/blob/c51347d78bc6dd30b6b4db2af64f0ea4bc83091e/.github/workflows/dockle.yml) は変わっていないのにここ数日落ちる割合が[高まっている](https://github.com/misskey-dev/misskey/actions/workflows/dockle.yml)ようです。

**Comment by tai-cha** [comment]
misskey-dev/misskeyではdockle-actionは使っていないけどこれと同じ事象かもしれません
https://github.com/goodwithtech/dockle-action/issues/7

**Comment by tai-cha** [comment]
メモ:まずはdockleを最新にあげてもいいかも

**Comment by anatawa12** [comment]
https://github.com/anatawa12/misskey/pull/30

更新したらなんか通ったわ
