### ISSUE TITLE
issueを作るとき、Q&A などは Discussionに誘導する

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#13982]
文脈: https://github.com/misskey-dev/misskey/discussions/13964#discussioncomment-9761343

CONTRIBUTING.mdにも沿っているし[できる](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) のでやりたい

**Comment by tai-cha** [comment]
そもそもIssueテンプレートがあるのでそこに追加すれば誘導できそう

https://github.com/misskey-dev/misskey/blob/c51347d78bc6dd30b6b4db2af64f0ea4bc83091e/.github/ISSUE_TEMPLATE/config.yml
