### ISSUE TITLE
Develop に追従するとログインできない(dc3629e)

### ISSUE THREAD

**Issue by kanarikanaru** [syuilo/Misskey#13993]
### 💡 Summary

[feat\(backend\): report \`Retry-After\` if client hit rate limit \(#13949\) · misskey-dev/misskey@dc3629e · GitHub](https://github.com/misskey-dev/misskey/commit/dc3629e732e5aefd792452f0b43a7bb7fdaf103e)
これを適用すると、新規にログインできない等の問題が発生する。
現状Developブランチにのみにあるコミットです。

### 🥰 Expected Behavior

- 新規にログインできる
- デフォルトロールでノートやリアクションが消せる

### 🤬 Actual Behavior

- ログインするためにPOSTしても結果が返ってこない
- nginxのリバースプロキシを経由させなくても発生

### 📝 Steps to Reproduce

1. Developに追従する
2. 新しいブラウザでログインを試みる
3. ぐるぐる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacBook Pro (14inch, 2021), macOS Sonoma 14.5

* Browser: Chrome 125
* Server URL:misskey.backspace.fm
* Misskey:2024.05(Developに追従、該当コミットをrevertして通常通り動作することを確認)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:systemd
* Misskey: 2024.05(Developに追従、該当コミットをrevertして通常通り動作することを確認)
* Node: 20.14
* PostgreSQL: 15
* Redis: 7
* OS and Architecture: Ubuntu 22
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
追加：新規アカウント作成も通らないかも

**Comment by tai-cha** [comment]
ローカルdev環境では再現できず、misskey-tgaでは再現できる

**Comment by tamaina** [comment]
92367cf70065dca5e33ece2266f0318c3b682d1a の0keyでは起きないので[Retry-After](https://github.com/misskey-dev/misskey/commit/dc3629e732e5aefd792452f0b43a7bb7fdaf103e)周りなんだろうなとは

**Comment by KisaragiEffective** [comment]
外出中のため帰ったら確認します

**Comment by u1-liquid** [comment]
> ローカルdev環境では再現できず

👀
https://github.com/misskey-dev/misskey/blob/c51347d78bc6dd30b6b4db2af64f0ea4bc83091e/packages/backend/src/server/api/RateLimiterService.ts#L28-L30

**Comment by zyoshoka** [comment]
https://github.com/misskey-dev/misskey/blob/c51347d78bc6dd30b6b4db2af64f0ea4bc83091e/packages/backend/src/server/api/RateLimiterService.ts#L60

記法的に良いのか分かりませんがここをとりあえず
```ts
return max.then(ok).catch(e => reject(e));
```
とすると直りました

**Comment by anatawa12** [comment]
`max.then(ok, reject)`のほうが良さそう。PRはやします

**Comment by tai-cha** [comment]
自分も
`return max.then(ok).catch(reject);`
で動くのは確認してPR出そうと思ってました

**Comment by anatawa12** [comment]
ok(Promiseのresolveコールバック)がエラー出すこと多分ないけどthen(ok).catch(reject)だと両方呼ばれるリスクがあるので一応thenに２つのほうが良さそうとしました

**Comment by KisaragiEffective** [comment]
off-topic(?): resolveを呼んでいないのはESLintのno-floating-promiseで検知されているかと思ったが、CI実行時に--quietがついているためおそらく抑制されている。これも帰ったら見る。

**Comment by anatawa12** [comment]
voidにreturnしてるところで発火してもいい気はするけど、`new Promise`の`resolve`に関しては`limiter.get`のコールバックがいつどのように呼ばれるか不定だからlinterがどうにかできる範疇を超えてるきはする
