### ISSUE TITLE
多数のチャンネルをお気に入り登録している場合、「チャンネルヘリノート」が画面の外にあふれる

### ISSUE THREAD

**Issue by TASmasa3456** [syuilo/Misskey#13999]
### 💡 Summary

「チャンネルヘリノート」で表示される、お気に入り登録されたチャンネルの一覧はスクロールできない（PCの場合）ため、画面内に収まりきらない数のチャンネルをお気に入り登録している場合、一覧上部が画面外に隠れるため隠れたチャンネルにリノートできない

### 🥰 Expected Behavior

チャンネル一覧がスクロールでき、全てのチャンネルにリノートできる

### 🤬 Actual Behavior

下部画像のように、上部がウィンドウ境界を超えて表示され、スクロールもできない
![image](https://github.com/misskey-dev/misskey/assets/155567748/65f53862-81e1-4455-82a7-8827777012fe)

### 📝 Steps to Reproduce

1.チャンネルを一覧が画面内に収まらないくらいお気に入り登録
2.チャンネルヘリノート

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):hp pavilion aero 13-be(hp, 2023), Windows 11 version 23H2
* Browser:Chrome 125.0.6422.142
* Server URL:misskey.gamelore.fun, misskey.io
* Misskey:2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
@kakkokari-gtyih スクロールできるようにしたほうが良いかもしれないです
