### ISSUE TITLE
コンパネのロール画面で編集モードじゃなくても項目を動かせてしまう

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#14005]
### 💡 Summary

ロールの設定項目が、編集画面ではなくても操作できてしまう(が、保存ボタンがない)

### 🥰 Expected Behavior

閲覧画面ではトグルなどを変更することができない

### 🤬 Actual Behavior

操作できてしまうので、この画面で編集できるように勘違いしてしまう

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: Chrome, Safari
* Server URL:
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by fruitriin** [comment]
最近のエンバグではなくおそらくずっとバグっている
モデレーターしか触らない画面なので気をつければいいといえばそうなんだけど

**Comment by tai-cha** [comment]
バグというよりUIが良くない（たしかにずっと変更できるように見える）

**Comment by kanade** [comment]
設定したつもりで編集状態になっていなかった…というのあるあるでした。

**Comment by zyoshoka** [comment]
重複のためクローズします🙏

Duplicate of #12414
