### ISSUE TITLE
リアクション非対応のサーバーからの投稿は「いいねのみ」として取り扱う

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14004]
### Summary

**もうあった気がするけどどうしても見つからなかったので**

かいてあるとおり

### Purpose

いいねしか見えない相手にリアクションがつくとその後のコミュニケーションの障害になるかもしれない

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by 1STEP621** [comment]
:eyes:  #12901
