### ISSUE TITLE
「このPRによるapi.jsonの差分」が空だったとき「差分はありませんでした」と言う

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14015]
purpose: APIをいじらないPRを確認するための手間を1クリック減らせる

**Comment by yupix** [comment]
これと似通ってる気がします

https://github.com/misskey-dev/misskey/issues/12159

**Comment by anatawa12** [comment]
duplicateですね。ありがとうございます。

**Comment by anatawa12** [comment]
Duplicate of #12159
