### ISSUE TITLE
サウンドの設定でドライブの音声を使用している場合、使用している音声をドライブから削除すると空白になる

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#14016]
### 💡 Summary

サウンドの設定でドライブの音声を仕様にしている場合に、その使用している音声をドライブから削除すると、設定の中身が空白になる。

### 🥰 Expected Behavior

消してしまっても設定できるように。

### 🤬 Actual Behavior

<img width="519" alt=" 2024-06-16 3 51 41" src="https://github.com/misskey-dev/misskey/assets/89781396/47ff726a-cb00-4a9e-bff7-cabd863acfbe">

こう、、、中身がなくなる(キャッシュを完全に削除したら復活はする)

### 📝 Steps to Reproduce

1. サウンドの設定へ移動
2. 好きな通知オンにしたい項目を選んで、ドライブないの音声を使用を選択する
3. 選択した音声を消す
4. 中身なくなる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):　M1 Mac mini, macOS Sonoha
* Browser:ark 1.46.0 (Chromium Engine Version 125.0.6422.142)
* Server URL: 
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: 
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by nullnyat** [comment]
別インスタンス(v2024.5.0)+chromeでやってみたけど同じ現象が起きた。

**Comment by nullnyat** [comment]
助かるます🙏
