### ISSUE TITLE
登録時のメールアドレスもしくはドメインで禁止設定がほしい

### ISSUE THREAD

**Issue by schwarzewald** [syuilo/Misskey#14023]
### Summary

登録時のメールアドレスで登録を禁止するメールアドレスもしくはドメインを設定できる機能があると助かる

### Purpose

捨てアドなど一時的なメールアドレスでの登録を禁止したい

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
コントロールパネルの"セキュリティ"ページにある、"Banned Email Domains"がそれに当たるかと思います。

**Comment by schwarzewald** [comment]
ありがとうございます、見落としていました
