### ISSUE TITLE
ウィジェットやユーザーページにあるドロップシャドウの切れ目が目立ってしまう

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#14026]
### Summary

<img width="266" alt=" 2024-06-17 7 33 25" src="https://github.com/misskey-dev/misskey/assets/89781396/6f074a77-80ba-4ed8-9cf9-145765ad3d63">

こう、、、ブラーがなんか見切れててちょっとあれかも

あとここの色が固定なのでいい感じにしたい気持ち

### Purpose

デザインをいい感じにする

<img width="242" alt=" 2024-06-17 7 38 50" src="https://github.com/misskey-dev/misskey/assets/89781396/fc8a2cc2-afce-4b59-be62-20b381cbc98e">

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by t1nyb0x** [comment]
「あれ」であったり「いい感じ」という書き方は、読み手によって認識が変わり齟齬が発生する元となってしまうため、明言化していただけないでしょうか。

また、様々な人が見る場所のため、曖昧な書き方をしても良いという実績が作られるのは避けたいと考えています。

何卒よろしくお願いいたします。

**Comment by KisaragiEffective** [comment]
1. 「あれ」=ブラーのフェードアウトがうまくできていなくて矩形で区切れているように目立つのは見た目がよくないため、それを避けてほしい (添付)
2. 「いい感じ」=(多分) ダークテーマでも黒色の影が表示されてしまうのは好ましくないのでそれをテーマごとに変えるようにしよう

ということですか？

2についてはバックの背景を設定することによってどういう色にもなり得るので、しょうがないと思います。

添付画像:
![image](https://github.com/misskey-dev/misskey/assets/48310258/90400e76-2cbd-4ad8-854c-29a06acd089e)

**Comment by nullnyat** [comment]
言葉が足りなくて申し訳ございません。

ドロップシャドウが見切れている問題を解決したかったです。

2についてはテーマごとに変更するのは難しいと考えております。

**Comment by nullnyat** [comment]
テーマごとに変えるようにして見たけど、背景があることを考えるとやっぱり白黒固定が無難だなぁとなったり

**Comment by nullnyat** [comment]
試しにfgとbgのカラー当てて見たけどうーーーん。

難しい。。。

<img width="229" alt=" 2024-06-17 11 05 46" src="https://github.com/misskey-dev/misskey/assets/89781396/b38fa44e-c0e7-40f1-b1fe-40614d0731b8">

**Comment by nullnyat** [comment]
ユーザーページのシャドウも見切れていることに気づいてしまった👀

あと、text-shadowになっていたのでそこもdrop-shadowにしたい。

<img width="182" alt=" 2024-06-19 21 31 09" src="https://github.com/misskey-dev/misskey/assets/89781396/5371f454-08d8-46fe-8f4c-e46488d3c7d1">

**Comment by KisaragiEffective** [comment]
検索性のために、タイトルを編集させていただきました 🙏🏻

**Comment by nullnyat** [comment]
ウィジェットのみだけではなく、ユーザーのページ?の名前の部分も見切れてしまっております。

https://misskey.io/@nullmyat
<img width="184" alt=" 2024-06-20 12 32 08" src="https://github.com/misskey-dev/misskey/assets/89781396/84a7a184-926c-43bb-94e7-d21524efb7b1">

**Comment by nullnyat** [comment]
ありがとうございます🙏

**Comment by KisaragiEffective** [comment]
ご指摘ありがとうございます。再度編集しました 🙏🏻
