### ISSUE TITLE
カスタム絵文字の名前の変更を認めるかどうかというプロパティを(ライセンスが連合されるようになったら)追加して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#14024]
### Summary

将来的にカスタム絵文字のライセンスが連合されるようになった場合、名前の変更を認めるかどうかがライセンスによって分かれる可能性があります。
そこで、絵文字がインポートされた後にその名前を変更することを認めるかどうかを、予め設定しておけると良いと思いました。

related: #10822 #10859

### Purpose

絵文字のインポート関連の状況を改善
権利関係等の都合

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
(#13962 と重複だったかもしれません…?)

**Comment by KisaragiEffective** [comment]
別に連合される前にあってもうれしいっちゃうれしいと思う
人様のサーバーで申請するときにわざわざその人のノートとかページとか掘るのめんどうなので

**Comment by noellabo** [comment]
運用上の問題ですが、重複不可避な名前を固定設定されると扱いが面倒になりそうですね。
kawaii, iineのような単純な読み、blob_iine のような組みあわせが頻繁に衝突しています。

重複OKの original_name を追加して正式な名称はそちらに設定し、nameは識別用に重複回避措置をとったユニークな名前に改変可（prefix, suffixつけるなど）とするなど、仕組みでも工夫しておいた方がいいかも。

**Comment by Sayamame-beans** [comment]
> 別に連合される前にあってもうれしいっちゃうれしいと思う 人様のサーバーで申請するときにわざわざその人のノートとかページとか掘るのめんどうなので

連合前に項目作っておく分には、連合時に含めればよい話なのでそうかもしれないです
ただ、そもそも連合する流れにならない場合はライセンス欄で十分だなと思ったので…

**Comment by KisaragiEffective** [comment]
> ライセンス欄で十分
意外とそうでもない。例えば`:blobcat_pikapika:` はnijimiss.moeに登録されているが、そのライセンス欄には製作者のアカウントしか書かれていないので、名前の変更を認める・インポートを認めるなどの情報が一切ない (運用上の問題といえば、それはそうなのだけど)

**Comment by KisaragiEffective** [comment]
> > ライセンス欄で十分
> 
> 意外とそうでもない。例えば`:blobcat_pikapika:` はnijimiss.moeに登録されているが、そのライセンス欄には製作者のアカウントしか書かれていないので、名前の変更を認める・インポートを認めるなどの情報が一切ない (運用上の問題といえば、それはそうなのだけど)

サンプルをとって確かめたが、運用上の問題かもしれない (※個人の認識)。あとで全件走査する

**Comment by anatawa12** [comment]
正直これシステム上でやる必要が私は感じられてないです。ライセンス連合でライセンス情報を下に運営者が適切な範囲で名前をつけるでいいと思う

**Comment by Sayamame-beans** [comment]
では、システム的にやらないと困りそうな例を思い付いたらまた開きますね…
