### ISSUE TITLE
Can create antenna/list/clip more than role policy limits

### ISSUE THREAD

**Issue by Astro-CQM** [syuilo/Misskey#14034]
### 💡 Summary

Can create clips/lists/antennas more than role policy limits.

### 🥰 Expected Behavior

If `antennaLimit` value is 0, user can't create antenna at all.

### 🤬 Actual Behavior

user can create up to 1 antenna.

### 📝 Steps to Reproduce

1. set antennaLimit policy to 0
2. create antenna

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2 (22631.3737)
* Browser: Chrome 125.0.6422.176
* Server URL: oscar.surf (but not server related)
* Misskey: 2024.5.0-oscar.1a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2024.5.0-oscar.1a
* Node: 20.11.1
* PostgreSQL: 15.6-1.pgdg22.04+1
* Redis: 7.2.4
* OS and Architecture: Ubuntu 22.04.4 LTS aarch64
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by SWREI** [comment]
this is for context (Photo on k.lapy.link)

## Role Policy
![image](https://github.com/misskey-dev/misskey/assets/92716173/bbf53a99-d30e-45ca-b3a5-399487abae20)

## Antenna List
![image](https://github.com/misskey-dev/misskey/assets/92716173/9aa10088-6193-4cc6-956e-2600f80e9bce)

**Comment by zyoshoka** [comment]
Related to #12279
