### ISSUE TITLE
接続中の全クライアントを強制再読み込みする（or 再読み込みを促す）機能

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14074]
### Summary

管理者向けの機能

### Purpose

instanceの変更（特にベースロールの変更）や新バージョン更新に伴うキャッシュ不整合の解消などのために、管理者側から一括再読み込みをかけられるようにする

（ノートの下書き中とかだと悲惨なことになりそうなのでそのあたりのケアもどうするか考える）

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by acid-chicken** [comment]
Duplicate of #12380
