### ISSUE TITLE
プロフィール編集時に名前を空白文字列のみにできてしまう

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#14088]
### 💡 Summary

プロフィールの、自分の名前を空白文字のみで構成する文字列にして保存すると、空白が削除されずにそのまま名前が無になる。

### 🥰 Expected Behavior

空白がトリムされて、名前未設定時の挙動となる
あるいは、エラーとなる？

### 🤬 Actual Behavior

空白文字のみで構成された名前がそのまま保存される

### 📝 Steps to Reproduce

1. プロフィール編集画面へ移動
2. 名前を空白文字のみにして保存する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacBook Air (M1, 2020), macOS Sonoma 14.1.1
* Browser: Chrome 125.0.6422.142
* Server URL: mk.shrimpia.network, misskey.io
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
個人的な疑問なのですが、表示名が空ですとどのように問題があるでしょうか…?
リアクションやRNの通知ではアイコンと表示名しか(現状)表示されていないようなので、その部分でしょうか?
