### ISSUE TITLE
Error when running `pnpm --filter backend dev`

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#14121]
### 💡 Summary

https://github.com/misskey-dev/misskey/commit/427648c4b8c5b7699c92afa95a14097bb9329ee8 以降、`pnpm --filter backend dev` を実行すると以下のようなエラーが出ます。

```
node:internal/child_process/serialization:109
    ser.writeValue(message);
        ^

Error: function (settings, ready) {
  reset();
  var config = this;
  load(settings, config.options, config, function ...<omitted>...
} could not be cloned.
```

おそらく `execa` の破壊的変更を踏んだように見えます。

### 🥰 Expected Behavior

エラーが出ない

### 🤬 Actual Behavior

エラーが出る

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: https://github.com/misskey-dev/misskey/commit/427648c4b8c5b7699c92afa95a14097bb9329ee8
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
リリースノート
https://github.com/sindresorhus/execa/releases/tag/v9.0.0

**Comment by samunohito** [comment]
プロジェクトを見渡すとちょいちょい8.0.1が残っているので、これらもついでに統一したいですね

**Comment by samunohito** [comment]
このipcをtrueにするとだめっぽい
![image](https://github.com/misskey-dev/misskey/assets/46447427/6a728c50-88a3-47ea-9631-bb0b919ffd6d)

**Comment by anatawa12** [comment]
nodemonがload/resetという関数を持ったオブジェクトをprocess.sendに渡しているけどexecaが関数を無視しなくなったって仕様変更がおきた感じかな

**Comment by anatawa12** [comment]
node.jsの`process.send()`は`JSON.stringify`を使うため、関数は無視されるので、execaのバグ。

**Comment by anatawa12** [comment]
nodemonがadvancedを対応していないってissueは立てていいけど、一旦jsonすることで動いているのは確認した

<img width="654" alt="image" src="https://github.com/misskey-dev/misskey/assets/22656849/61c2cae1-7bcc-4e6e-96a9-3c244c0486b3">
