### ISSUE TITLE
リモートからアンケートの選択肢が流れてきたとき、選択肢内の絵文字がリモートの絵文字として描画されない

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14129]
### 💡 Summary

リモートからアンケートの選択肢が流れてきたとき、選択肢内の絵文字がリモートの絵文字として描画されない

### 🥰 Expected Behavior

選択肢内の絵文字がリモートの絵文字として描画されてほしい

### 🤬 Actual Behavior

選択肢内の絵文字がリモートの絵文字として描画されない

### 📝 Steps to Reproduce

1. ノートにアンケートをつける
2. 選択肢に絵文字を入れる
3. そのノートを配送先サーバーから見る
4. 絵文字が配送元サーバーの文脈で解決されず、配送先サーバーの文脈で解決されてしまう

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): `6.7.12+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1~bpo12+1 (2024-05-06) x86_64`
* Browser: Mozilla Firefox 127.0.1
* Server URL: https://misskey.io/
* Misskey: 2024.5.0-io.1a
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A (not server admin)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kozakura913** [comment]
#11763 と重複？

**Comment by KisaragiEffective** [comment]
> #11763 と重複？

自分でコメントしたのに忘れていた😇
重複なので閉じます
