### ISSUE TITLE
Example for misskey-js does not work out of box with node.js

### ISSUE THREAD

**Issue by suvam0451** [syuilo/Misskey#14134]
### 💡 Summary

Unable to run the hello world example.

Any examples or documentation references are welcome!

日本語でも大丈夫です。私はあなたの返事を翻訳して、適切に返信します。

### 🥰 Expected Behavior

Should be able hello world example with ts-node

### 🤬 Actual Behavior

Getting export errors

### 📝 Steps to Reproduce

1. Create a new new project from scratch
2. Install `misskey-js`
3. Try initialising a client in typescript
4. Run the script with `ts-node`

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacOS (M2, 2022)
* Browser: N/A
* Server URL: misskey.io
* Misskey: N/A
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by suvam0451** [comment]
Here is a simple example.

<img width="661" alt="Screenshot 2024-07-05 at 3 01 49 PM" src="https://github.com/misskey-dev/misskey/assets/44526763/42dfdbeb-c37e-46c2-9568-7a80de6d1794">

**Comment by KisaragiEffective** [comment]
@suvam0451 
Thank you for your contact.
Please provide the package.json to investigate whether our definition is problematic.

**Comment by suvam0451** [comment]
@KisaragiEffective 
Thank you!

Here is a minimal codebase reproducing the issue:

https://github.com/suvam0451/misskey-14134-unable-to-run-with-ts

**Comment by anatawa12** [comment]
it looks you're trying to use misskey-js from commonjs but misskey-js is esmodules so using esmodules in your project might fix problem

**Comment by suvam0451** [comment]
@anatawa12 @KisaragiEffective Thank you for your time.

I solved it. Here is solution for anyone else who might run into this:

1. Set value of `type` from `commonjs` -> `module` In `package.json`
2. Set value of `module` from `commonjs` -> `NodeNext` in `tsconfig.json`
2. Then you have ways of running the code:
  
<img width="845" alt="Screenshot 2024-07-06 at 9 18 25 AM" src="https://github.com/misskey-dev/misskey/assets/44526763/6544c268-c691-4b8a-84b6-845eaf37c022">

Unfortunately, the rest of my react-native project is in commonjs. 
But, I think this is a good starting point for integration. 😄

Feel free to close 👌.
