### ISSUE TITLE
catodon.socialを照会できないことがある

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14135]
### 💡 Summary

書いてあるとおり
（サーバー管理者に問い合わせて先方のインフラ側の問題ではないことを確認済み）

### 🥰 Expected Behavior

照会可能

### 🤬 Actual Behavior

複数のサーバーで照会できないとの報告あり
（catodon.socialと連合したことがまだ一度もなかったサーバーで発生しているという説もあるが、そこに因果関係があるかどうかは不明）

### 📝 Steps to Reproduce

1. 照会
2. `@catodon@catodon.social` を照会

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): N/A
* Browser: N/A
* Server: BackspaceKey, 0key.dev など複数のサーバー（io, にりらみすきー部, なですきーでは照会成功）
* Misskey: Various
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
みすてむずでも成功

**Comment by kozakura913** [comment]
`m1.kzkr.xyz`で初観測、照会成功

**Comment by syuilo** [comment]
↑を行っても 401 が返ってくるケースがある

謎すぎる

**Comment by syuilo** [comment]
同じMisskeyでもサーバーによって疎通可否が異なるのが謎

**Comment by syuilo** [comment]
ヌァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァンンンンオオオオンンオンオンオンオンンンンンンンンン゛ン゛！！！！！！！！！！！！！！！！

**Comment by syuilo** [comment]
解決された方に報奨金を進呈

**Comment by KisaragiEffective** [comment]
同じサーバーで一貫した結果が返ってくるかどうかによって考えられる可能性が異なってくると思う

**Comment by hos1miya** [comment]
連合周りだとDNS周りとかの可能性

**Comment by syuilo** [comment]
DNSで401って返ってくるかしら

**Comment by KisaragiEffective** [comment]
DNSが変な方向に向いてしまっている、とか？

**Comment by KisaragiEffective** [comment]
参考: 
```
$ dig catodon.social

; <<>> DiG 9.18.24-1-Debian <<>> catodon.social
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9651
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;catodon.social.			IN	A

;; ANSWER SECTION:
catodon.social.		600	IN	A	49.13.197.4

;; Query time: 104 msec
;; SERVER: 192.168.1.1#53(192.168.1.1) (UDP)
;; WHEN: Sun Jul 14 12:48:45 JST 2024
;; MSG SIZE  rcvd: 59
```

**Comment by syuilo** [comment]
signToActivityPubGet が false になっている可能性が出てきた(確認中)

**Comment by kleuzjatob** [comment]
以前、弊サーバーでどうしてもGoToSocial製のサーバーと疎通せねばならなくなった時に https://github.com/misskey-dev/misskey/issues/9435 （`signToActivityPubGet`を`true`にする）で解決できた事がございます。それがトリガーかは判りませんが2024/2/18の初観測以来今も疎通は出来ている様です（前述の`true`化でinstance.actorが作られたのは2023/4/21の様で大分離れていますが）。

**Comment by syuilo** [comment]
> signToActivityPubGet が false になっている可能性が出てきた(確認中)

これでした🙏🙏🙏

**Comment by KisaragiEffective** [comment]
note for future reference: https://misskey.xsns.jp/notes/9vsuyddblvzc0exd

**Comment by tai-cha** [comment]
ノートを貼り付けるときは参照できなくなる可能性があるのでなるべく引用などの形式を取ってほしい

**Comment by KisaragiEffective** [comment]
> 引用などの形式を取ってほしい

done
