### ISSUE TITLE
画像にユーザーをメンションできるようにしたい

### ISSUE THREAD

**Issue by MattyaDaihuku** [syuilo/Misskey#14142]
### Summary

タイトルの通り

### Purpose

投稿する画像の説明として

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
Twitterではツイート単位でタグ付け(≒メンション)されるので、画像単位である必要は無いのかもしれません…?
画像や動画などのファイルが添付されているときだけ、投稿に直接書かずともメンション出来るような形になれば…? (表示するためのUIは作らないとですが)

**Comment by syuilo** [comment]
Xは添付ファイルと投稿が一体化されているけど、Misskeyでは別々だからなぁ

**Comment by MattyaDaihuku** [comment]
なるほど、、、
