### ISSUE TITLE
フォロー中のユーザが一定期間非アクティブである場合サジェストされなくなる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#14149]
### 💡 Summary

今現在、`users/search-by-username-and-host`の動作は下記のようになっています。

①フォロー中のユーザのうちアクティブ[^1]なユーザを抽出
②1の結果がlimitに満たない場合、自分がフォローしていないかつupdatedAt != nullなユーザを抽出し、1と合体

[^1]: 過去30日の間で`user.updatedAt`が更新されたユーザ

上記の条件ですと「フォローしているが非アクティブなユーザ」が表示されなくなり、該当ユーザをメンションしたい時に若干不便な状態になってしまっています。

そこで、以下の優先順位でユーザを抽出するようにし、上記の課題を解決したいです。

①フォロー中のユーザのうちアクティブなユーザ
②フォロー中のユーザのうち非アクティブなユーザ
③未フォローのユーザのうちアクティブなユーザ
④未フォローのユーザのうちアクティブなユーザ

また、抽出されたユーザのソートも行われていますが、`user.usernameLower`の昇順と`user.updatedAt`の降順の組み合わせでまちまちなので、これらも一律`user.usernameLower`したいです。

### 🥰 Expected Behavior

フォローしている非アクティブユーザもサジェストに出る

### 🤬 Actual Behavior

出ない

### 📝 Steps to Reproduce

フォローしている非アクティブユーザめがけてメンションしようとする

### 💻 Frontend Environment

```markdown
-
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [x] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
（あと、自分自身のIDを省くようにクエリが組まれているけれども…特殊な意図が無いようであれば、これも解除して自分自身のIDをサジェスト出来るようにもしたい）

**Comment by syuilo** [comment]
クライアント側でケアすれば良いんじゃないかしら

**Comment by samunohito** [comment]
というと…？

**Comment by syuilo** [comment]
自分の情報はクライアントが持っているからAPIからレスポンスする必要はないわね

**Comment by samunohito** [comment]
ああ、 https://github.com/misskey-dev/misskey/issues/14149#issuecomment-2212380813 の件…なるほど。

**Comment by samunohito** [comment]
ただ、「今入力しているキーワードが自分のアカウントと前方一致しているか」というのをクライアント側で常に判定しなければならなくなり、かつ検索結果のキャッシュにも入れておく必要があるので、もし自身を含めていいのであればサーバサイドの[WHERE](https://github.com/misskey-dev/misskey/blob/c1514ce91dc08481a092a789ee37da546cdb4583/packages/backend/src/server/api/endpoints/users/search-by-username-and-host.ts#L93)から消した方がシンプルに済みそうな気もしており

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by syuilo** [comment]
> ただ、「今入力しているキーワードが自分のアカウントと前方一致しているか」というのをクライアント側で常に判定しなければならなくなり

常に表示しておくのはダメかしら

**Comment by syuilo** [comment]
あーサジェストか
