### ISSUE TITLE
ドライブにてスマホ使用時にフォルダに画像等を移動できない

### ISSUE THREAD

**Issue by arch-herobrine** [syuilo/Misskey#14150]
### 💡 Summary

おそらくスクロールに判定吸われたりしてドラッグアンドドロップの判定が出ていないものかと

### 🥰 Expected Behavior

右クリックメニュー(長押し時のメニュー)からフォルダに画像等を移動できるようにする

### 🤬 Actual Behavior

ドラッグアンドドロップされずにスクロールされる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Xperia 10 V(Android 14)
* Browser: Chrome 126.0.6478.122
* Server URL: misskey.io
* Misskey: 2024.5.0-io.1a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kanade** [comment]
たしかiOSのSafariだと長押し（タップ） → ドラッグで移動できたかと思いますが、Androidだとどの機種でもできなくてうちのサーバーにもそのことを嘆いているユーザーさんがいました。
なんらかの手段でフォルダの整理ができれば嬉しいなと思います。
