### ISSUE TITLE
ノート投稿時、複数アカウントでログインしている状態でアカウントを切り替えると添付ファイルのあるノートができない

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#14168]
### 💡 Summary

アカウントを投稿画面で切り替えてノートできるが、この際にファイルがメインで開いているアカウントでアップロードされてしまうためノートに添付できない

### 🥰 Expected Behavior

アカウント切り替え後のアカウントにファイルをアップロードしてノートできる

### 🤬 Actual Behavior

別にログイン中のアカウントではファイルを添付したノートができない

### 📝 Steps to Reproduce

1. アカウントAでログインする
2. アカウントBでもログインする
3. アカウントAを開いているとき、アカウントBで画像を添付してノートしようとする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
エラーメッセージは「Some files are not found.」
![image](https://github.com/misskey-dev/misskey/assets/40626578/76b51c8d-7469-4e66-b536-73d46c2e479d)

**Comment by Sayamame-beans** [comment]
duplicate of #11464
