### ISSUE TITLE
Load settings via environment variables

### ISSUE THREAD

**Issue by 5ouma** [syuilo/Misskey#14173]
### Summary

Currently, we need to hardcode the database username or password (and more..) in the [`default.yml`](https://github.com/misskey-dev/misskey/blob/develop/.config/docker_example.yml).
It's better to load environment variables defined in the [`docker.env`](https://github.com/misskey-dev/misskey/blob/develop/.config/docker_example.env).

### Purpose

I want to make the Misskey config files (compose.yml, default.yml, etc) public on GitHub but I can't due to the security issue.
It's good to be able to set the database settings in the `compose.yml` with `environment` or `env_file`.

### Details

I'd like to tweak these values to load environment variables.

- `Source.url`
- `Source.db.db`
- `Source.db.user`
- `Source.db.pass`

This is the same idea with this.

https://github.com/misskey-dev/misskey/blob/80f3cb96b02eaaeb513670224d33b8842414963e/packages/backend/src/config.ts#L222

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

**Comment by 5ouma** [comment]
@syuilo いかがでしょうか？

**Comment by syuilo** [comment]
確認できてません🙏

**Comment by 5ouma** [comment]
催促してすみません。お時間のある時で構いませんので、レビューしていただけると嬉しいです。
