### ISSUE TITLE
特定の手順を踏むとページが正常に描画されない

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#14170]
### 💡 Summary

![image](https://github.com/misskey-dev/misskey/assets/56515516/a0370641-431a-4f30-95bb-667dce8a7afb)
このような感じになり、リロードをしない限り正常に閲覧することができない。

### 🥰 Expected Behavior

正常に閲覧できる

### 🤬 Actual Behavior

正常に閲覧できない

### 📝 Steps to Reproduce

1. Google Chromeなどの 開発者ツール の パフォーマンスタブ から CPUをx6ぐらいにスロットリングする
![image](https://github.com/misskey-dev/misskey/assets/56515516/93113541-441e-4ac1-9976-1c95d38e7d2f)
2. タイムライン を開いた状態で、リロードして 通知 を連打する
3.添付画像のようになる
文章にするのが難しいのでGifを添付します。
![bug](https://github.com/misskey-dev/misskey/assets/56515516/82f84669-8cce-4e53-9a7a-e021b2826446)

 https://mattyaski.co , https://prismisskey.space , https://misskey.io と手元の開発用サーバーで同様の問題を起こすことができます。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11
* Browser: Vivaldi 6.8.3381.46
* Server URL: https://misskey.io 
* Misskey: 2024.5.0-io.1a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by fruitriin** [comment]
スマホで見てるとTLがシュッと消えて操作不能になるやつの気がする
エラーメッセージは parentNode がうんちゃらっぽい

**Comment by fruitriin** [comment]
![image](https://github.com/misskey-dev/misskey/assets/18308639/c7678dad-babe-4e45-9c76-02ade7ea0fa4)

**Comment by mattyatea** [comment]
関係あるかわからないけどpnpm devのほうでログを見ると 
```
nirax.ts:373 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 
  at <KeepAlive max=3 exclude=undefined > 
  at <RouterView> 
  at <MkStickyContainer ref="contents" class="ui-universal-contents" style= {container-type: 'inline-size'}  ... > 
  at <Universal> 
  at <AsyncComponentWrapper>
```
っていうログを吐いてる

**Comment by fruitriin** [comment]
KeepAliveのexcludeにundefined渡したら死にそう
https://ja.vuejs.org/api/built-in-components.html#keepalive

```
interface KeepAliveProps {
  /**
   * 指定された場合、`include` でマッチした名前の
   * コンポーネントのみがキャッシュされます。
   */
  include?: MatchPattern
  /**
   * `exclude` でマッチした名前のコンポーネントは
   * キャッシュされません。
   */
  exclude?: MatchPattern
  /**
   * キャッシュするコンポーネントインスタンスの最大数。
   */
  max?: number | string
}

type MatchPattern = string | RegExp | (string | RegExp)[]
```

**Comment by KisaragiEffective** [comment]
`exactOptionalPropertyTypes`が無効なので意図的にundefinedを渡すことができる

**Comment by mattyatea** [comment]
https://soranakiproject.com/notes/9v9r1tzgya
https://soranakiproject.com/notes/9vihow2ms7
私以外のユーザーからの報告で気がついたバグだったりします👀

**Comment by fruitriin** [comment]
iPhoneのSafariで頻発する、MacのSafariでも稀に起きることがあるからメモリ周りをスロットリングすると再現するかも

**Comment by MineCake147E** [comment]
そういえばAndroidのFirefoxでも開いてすぐ通知ページに移動するとこのようになりますね...

**Comment by Sayamame-beans** [comment]
> iPhoneのSafariで頻発する、MacのSafariでも稀に起きることがあるからメモリ周りをスロットリングすると再現するかも

(私の環境において)iPhoneでスワイプして前のページに戻ったりすると高頻度でフリーズしてMisskeyが操作不能になる(絵文字のアニメーションなども止まる)挙動があるなと思ってたんですが、確かにこれかもしれません…

**Comment by mattyatea** [comment]
https://github.com/vuejs/core/issues/10899
これな気がする
開発環境でvueのバージョンを最新にしたら治った気がする

**Comment by mattyatea** [comment]
![bug-fix](https://github.com/misskey-dev/misskey/assets/56515516/07ddc5b7-b169-4d7e-b45c-e65db9d76913)
少なくとも自分の環境では Vueのバージョンを上げる ことで解決できた気がする

**Comment by mattyatea** [comment]
連打って書いてるのは再現が一番しやすかったのが連打だったから書いてるだけかも

**Comment by mattyatea** [comment]
今最新コミットで確かめましたが再現できました

**Comment by tai-cha** [comment]
関連するかわからないけど高速じゃなくてもコントロールパネルと設定を交互に遷移すると表示が狂うと聞いた

**Comment by samunohito** [comment]
バージョンを下げれば発生しなくなったりとかしないですかね…？
特定バージョンまで落として発生しないのであれば一旦そこまで落として、↑がfixされたら引き上げるとか

**Comment by syuilo** [comment]
ゔえ
