### ISSUE TITLE
Developに追従するとノート作成画面でカスタム絵文字を入力できない(385969e適用以降)

### ISSUE THREAD

**Issue by kanarikanaru** [syuilo/Misskey#14188]
### 💡 Summary

- fix(frontend): フォーカスの挙動を修正 (https://github.com/misskey-dev/misskey/pull/14158) (385969e) を適用するとノート作成画面でカスタム絵文字ピッカーを起動した際にフォーカスが当たらない
- 該当のコミットをrevertすることで再現しないことを確認

### 🥰 Expected Behavior

- ノート作成画面でカスタム絵文字ピッカー起動時にピッカーにフォーカスがいく

### 🤬 Actual Behavior

- フォーカスが当たらない

### 📝 Steps to Reproduce

1. 追従してpnpm run
2. ノート作成画面を開いてカスタム絵文字ピッカーを起動
3. wow

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacBook Pro (14inch, 2021), macOS 14.5 (23F79)
* Browser: Google Chrome Version 126.0.6478.127 (Official Build) (arm64)
* Server URL: dev container + misskey.backspace.fm(revert済み)
* Misskey: developまで追従(6cd1527)
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: development environment + systemd
* Misskey: developまで追従(6cd1527)
* Node: 20.x
* PostgreSQL: 15.x
* Redis: 7.x
* OS and Architecture: Ubuntu 22
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
強火

**Comment by samunohito** [comment]
@kakkokari-gtyih 
心当たりあります？

**Comment by samunohito** [comment]
![image](https://github.com/user-attachments/assets/79bdaf2a-7eb7-4303-9fe3-a2c1f9d4a1c1)
ピッカーの親要素にinertが当たってる…？

**Comment by samunohito** [comment]
①絵文字ピッカー・リアクションピッカーは常にDOM上で待機してる（[このへん](https://github.com/misskey-dev/misskey/blob/a5407131d4d15edca924e2718902cefd81e49ee2/packages/frontend/src/boot/main-boot.ts#L34-L35)によるもの）
②新しくダイアログが生成された時に、それ以外の要素に対してinertを当てる

①＋②＝新しくダイアログが生成された時にDOM上で控えてた絵文字ピッカーに対してinertを当てる

**Comment by samunohito** [comment]
けど、domを見る限り当たってしまってるので、その条件に漏れがありそう…？

**Comment by samunohito** [comment]
> 本当に表示されているかどうか

これどこか教えてほしいです
ソース見てるんだけど、分からなくて…

**Comment by samunohito** [comment]
![image](https://github.com/user-attachments/assets/9c2ad281-122e-438d-9cfe-1c2edadeb45c)
まず、ページ表示直後はこいつらがいて（常駐してるピッカーたち）

![image](https://github.com/user-attachments/assets/d5d8789d-56fa-49e5-98fc-72e16637deb2)
MkPostForm（黄枠）を表示した段階で、ピッカーたちにinertが設定される

![image](https://github.com/user-attachments/assets/c6fcd71d-64e4-4cfa-b1e6-af5bd0dec6a2)
その状態でMkPostFormの絵文字ボタンを押すと、inertが設定されたピッカーが表に出てくる

**Comment by samunohito** [comment]
「自分自身」に対してはModalの制御で良いけど、他の要素に対してまでは及んでない認識

**Comment by samunohito** [comment]
inertする要素の除外条件を増やした方が丸そうですかね（idふるなり、data-*で独自属性をつけて判定するなり）

**Comment by samunohito** [comment]
@kanarikanaru 
 #14189 でもだめそうであれば、お手数ですが再度openいただけますと幸いです。
