### ISSUE TITLE
eslintが遅いので結果をキャッシュしたい

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14184]
eslintが遅い。特にフロントエンドは毎回8分ぐらいかかる。
https://madogiwa0124.hatenablog.com/entry/2022/08/07/112051 を参考にしてキャッシュしたい

**Comment by 1673beta** [comment]
Lint目的ならoxlintとかどうでしょうか。
私のリポジトリだと11分かかったフロントエンドのLintが50秒かからずに終わるようになりました
https://oxc.rs/docs/guide/usage/linter.html

**Comment by KisaragiEffective** [comment]
ありがとうございます。それも選択肢の一つかとは存じますが、少なくとも私は以下の2点の懸念から一旦見送りたいと考えています。

1. サードパーティーのプラグインが移行できない可能性がある点。
2. 実際に許容可能な実行時間のラインよりも大幅に短縮される可能性はあるものの、労力に見合わない可能性がある点。
1についてですが、例えばfrontendでは`vue/*`系列のルールを多数採用していますが、 https://github.com/oxc-project/oxc/issues/2575 によると一部のルールが移行できない可能性が示唆されています。
2についてですが、現状のMisskeyの開発においては、主に`backend`、`frontend`、`misskey-js`のリント及びテストが並列に走ります。PRをマージするためにそれらのワークフローすべてが通るまでの時間を短縮することを考えたときに、リンターのみを短縮してもボトルネックがbackendのテスト (現行は3分ぐらいです) に移ると考えられます。しかし、oxlintへの移行のほうが必然的に作業量が多くなることが考えられるため、もしeslintのキャッシュを活用してそのボトルネックを移せるのであれば、一旦はeslintを活用するままにしておくというのが労力的に現実的な選択だと考えられます。(補足: oxlintへの移行を排除するものではありません)

**Comment by fruitriin** [comment]
es lintってキャッシュできたんだ！
eslint標準に入ってるってことはバグの心配もすくなそうだしよさそう
pnpm clean-allの中にeslintのキャッシュ削除も入ってるとなおよしかも
(記事の中ではnode_modules配下に置き場所を変更してるから不要かも

**Comment by fruitriin** [comment]
サクッと試してみてダメそうならoxlintって話まででてきてめでたい

**Comment by KisaragiEffective** [comment]
なんか有意な変化がない

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/runs/9927973726/job/27423684884#step:13:2

> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

そもそもキャッシュが保存されてない。

**Comment by KisaragiEffective** [comment]
`--cache-location`、各子プロジェクトに対する相対パス説が出てきた

**Comment by anatawa12** [comment]
そもそもeslintが実行される時点ではcwdは書くプロジェクトのはず

**Comment by anatawa12** [comment]
見直してみるとキャッシュがfrontendとbackendとで共有される形にもなってるので色々細かくいじらないといけなさそう

**Comment by KisaragiEffective** [comment]
Implemented by #14506
