### ISSUE TITLE
チャンネルの管理人(作成者)をWEB上から変更したい

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#14225]
### Summary

チャンネルの管理人(作成者)をWEB上から変更したい

### Purpose

チャンネルのバナーや説明文の変更、ピン留めなどの作業ができるのはチャンネルの作成者とサーバーのモデレーターのみである認識である
チャンネルの作成者が引退する場合、一般ユーザーによって変更が行えないので、UI上から後任を選べるなどの機能があるととてもうれしい

今の所、私のサーバーでは利用者からの依頼で管理人の変更をSQLで行っている
(そして、頻繁ではないもののしばしば発生する)

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #11718

**Comment by fruitriin** [comment]
11ヶ月ぶり2回目のissue
