### ISSUE TITLE
`getApType()`で`cannot detect type`エラーになる場合をvoidで返すようにしたい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#14239]
### Summary

`getApType()`で`cannot detect type`エラーになる場合をvoidで返すようにしたい

### Purpose

- if評価文中でエラーハンドリングが煩雑であるため
- もっぱら`getApType(activity) === 'Note'`というような用途でしか使われないためvoidでも問題なさそう

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tai-cha** [comment]
あまり母数は多くないけどジョブキューに溜まるので早めに直したい気持ちがややある
