### ISSUE TITLE
changelogの検査ワークフローが不整合を検出している

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14234]
仕様？

https://github.com/misskey-dev/misskey/actions/workflows/changelog-check.yml?query=branch%3Adevelop

**Comment by anatawa12** [comment]
前回のリリース時点でmasterに`Unreleased`のエントリが入っているのが原因っぽそう

**Comment by KisaragiEffective** [comment]
じゃあdevelop側に`# Unreleased`を足せば良いのかな…… 🤔

**Comment by anatawa12** [comment]
#13917 のheadが cc1ee0106f7f0cae9dc01ebaf2669e050ed44003 であるべきところが 2b8056a8525e1b38536aa0406ba9446a88b365b9 になっちゃってる

**Comment by anatawa12** [comment]
> じゃあdevelop側に`# Unreleased`を足せば良いのかな…… 🤔

それはあまり良くないと思う
一時的にワークフローにパッチを当てれば一応良さそうかなぁ

**Comment by anatawa12** [comment]
とりあえず仕様ではあるけど無視するか対策するかは議論で決めるべきだと思います

**Comment by tamaina** [comment]
> じゃあdevelop側に# Unreleasedを足せば良いのかな…… 🤔

これをやられてしまうとRelease actionsの挙動に問題が出そう

（だし正式リリース後にChangelogにテンプレートを自動で付加するのでUnreleasedは不要）

**Comment by tamaina** [comment]
Release actionsのお節介機能（Unreleasedをバージョンに書き換えたりリリース後にテンプレートを付加したり）とchangelog-checkerの相性というか考え方が全くあってなさそう

**Comment by anatawa12** [comment]
Unreleasedの追加がDevelop側だけなのであれば、問題なく動くはずです

**Comment by tamaina** [comment]
masterにUnreleasedが追加されちゃってるのが一番の問題点かしら？

**Comment by tamaina** [comment]
> masterにUnreleasedが追加されちゃってるのが一番の問題点かしら？

と

> https://github.com/misskey-dev/misskey/pull/13917 のheadが https://github.com/misskey-dev/misskey/commit/cc1ee0106f7f0cae9dc01ebaf2669e050ed44003 であるべきところが https://github.com/misskey-dev/misskey/commit/2b8056a8525e1b38536aa0406ba9446a88b365b9 になっちゃってる

とは同じこと言ってるんだろうけど

**Comment by anatawa12** [comment]
消したほうがいいのはそう。Pullreqによるバイパスをしゅいろさんにつけてもらう必要はあるかも

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/actions/runs/9986019295/job/27597816498?pr=14233

ちゃんと通るようになった

**Comment by KisaragiEffective** [comment]
多分解決したので閉じる
