### ISSUE TITLE
eslintが失敗したときPull requestに表示したい

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14252]
CIが死んだ理由をactionsから拾ってくるのはやや面倒

cc @tamaina 愚直にやると`@repo@p1.a9z.dev` がやかましくなりそうなのでいい方法を教えてほしい

**Comment by anatawa12** [comment]
既に各pullreqに github pull request annotations が出てたきがする

**Comment by anatawa12** [comment]
#14251 でも files欄に出てきてた

**Comment by KisaragiEffective** [comment]
annotationsあるならいいか
