### ISSUE TITLE
Android版 Firefox NightlyでUIのアイコンがロードできない

### ISSUE THREAD

**Issue by Mai-Shinano** [syuilo/Misskey#14271]
### 💡 Summary

Android版Firefox NitghtlyでMisskey v13のみUIのアイコンがロードできない。
Misskey v12ベースのFork(https://beta.romneko.net とhttps://nekomiya.net )では症状が確認できないため、v13のみの症状だと考えられる
見た感じなかったけどもしかしたらIssueが重複してるかもしれない
<img width="300" alt="User-page" src="https://github.com/user-attachments/assets/d28e9bfe-8923-406a-a99d-5ee518d5e331">

### 🥰 Expected Behavior

アイコンが見れるようにする

### 🤬 Actual Behavior

アイコンがロードできず、全部四角形で表示される

### 📝 Steps to Reproduce

1,Android版 Firefox NightlyでMisskey v13サーバーにログインする。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Motorola g24(Android 14) and VANKYO S30(Android9)
* Browser:Firefox Nightly 130.0a1 Build #2016033063
* Server URL:https://misskey.io https://misskey.niri.la https://misskey.systems https://submarin.online
* Misskey:2024.5.0-io.1a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by DA-TENSHI** [comment]
やはり先に立ってましたか。
ありがとうございました。

**Comment by m1sk9** [comment]
https://github.com/tabler/tabler-icons/issues/476 でも言及されていることですが, Firefox Nightly の Profile にある `gfx.downloadable_fonts.otl_validation` の値を変更すれば正しく表示されることは確認済みです.  (私は iPhome しか持っていないので Android 版の `about:config` に設定値が存在するかは不明です. もし困っていたら参考にしてください.)

**Comment by DA-TENSHI** [comment]
@m1sk9 ありがとうございます。アドバイス通り泥版Firefox Nightlyで`gfx.downloadable_fonts.otl_validatio`を変更して正しく表示されることを確認しました。
