### ISSUE TITLE
api-docでbearer tokenでの使用例が示されてしまう

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14275]
### 💡 Summary

> >  WebでそれをやるとCORSのpre-flightリクエストが発生してアレだから非推奨
> 
> 新api-docでheaderのほうに書いてたからそっちのほうがいいかと思っちゃったわね
> 
> ![image](https://github.com/user-attachments/assets/e0a71948-ee99-407e-8ff5-65f80f11decb)

https://misskey.io/notes/9vx4v5bxfk9n0d7l

### 🥰 Expected Behavior

`i`をJSONペイロード内部に含む例が表示される

### 🤬 Actual Behavior

Bearerでの認証方式が表示される

### 📝 Steps to Reproduce

1. v2024.7.0-beta.0 以降で `/api-doc` を開く
2. 適当なエンドポイントを参照する

### 💻 Frontend Environment

```markdown
* Server URL: 0key.dev
* Misskey: v2024.7.0-beta.1-commit.25714+e716c201c
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
（参考までに）
過去にこのような経緯があり、iを省いてBearerに設定するようにしていました
https://github.com/misskey-dev/misskey/pull/12403#discussion_r1401512890
