### ISSUE TITLE
コントロールパネル→連合の"連合中"にブロック/配送停止中のサーバーを表示しないようにして欲しい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#14272]
### Summary

コントロールパネル→連合の"連合中"にブロック/配送停止中のサーバーを表示しないようにして欲しい

Cotrol Panel, Federation, Federating

### Purpose

純粋に生きているサーバーを見たい

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by tai-cha** [comment]
要はこういう？
```diff
- state.value === 'federating' ? { federating: true }
+ state.value === 'federating' ? { federating: true, suspended: false }
```

**Comment by tamaina** [comment]
subscribingとpublishingも同様にそうしてほしいわね

**Comment by tamaina** [comment]
(API側の挙動でデフォルトがそうなって欲しい感じもちょっとするけどやめたほうが良さそう

**Comment by tai-cha** [comment]
API側の取れる値的に絞り込みのクエリが複雑化しそうだったのでやるとしたらいったんこうな気がする

**Comment by tai-cha** [comment]
逆にこの変更があって困る人がいたらどういうときに困りそうかを上げてほしい
（自分はあまり想像できてないので）

**Comment by tai-cha** [comment]
あんまり困る人がいなさそうなためやるか

**Comment by tai-cha** [comment]
（整合性を図るためにコンパネじゃないほうの連合でも同じように変更すると思います）

**Comment by tai-cha** [comment]
モデログとかの重いこと本格的にやる前にまずこれ片づけるか
