### ISSUE TITLE
ダイレクト投稿を削除して編集すると宛先(visibleuserids)が保持されない

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#14279]
### 💡 Summary

ダイレクト投稿を削除して編集すると宛先(visibleuserids)が保持されず、メンションを行っていない場合には復元することが娘を何である

### 🥰 Expected Behavior

ダイレクト投稿を削除して編集すると宛先が保持される

### 🤬 Actual Behavior

ダイレクト投稿を削除して編集すると宛先が保持されない

### 📝 Steps to Reproduce

1. 誰かを宛先にしたダイレクト投稿を送信する
2. その投稿を削除して編集するとダイレクト投稿の宛先がからの状態の投稿画面になっている

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): win11
* Browser:firefox
* Server URL:https://misskey.niri.la/
* Misskey:2024.5.0-kinel.4
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
> 娘を何である

難しくなる…？

**Comment by kussy-tessy** [comment]
困難である

**Comment by Sayamame-beans** [comment]
Related: #13717 
下書きでは実装されたが
https://github.com/misskey-dev/misskey/blob/337b42bcb179bdfb993888ed94342a0158e8f3cb/packages/frontend/src/components/MkPostForm.vue#L976-L995

削除して編集には無い
https://github.com/misskey-dev/misskey/blob/337b42bcb179bdfb993888ed94342a0158e8f3cb/packages/frontend/src/components/MkPostForm.vue#L997-L1015

無い

**Comment by Sayamame-beans** [comment]
reactionAcceptanceも保持されていない
