### ISSUE TITLE
管理者用webhookに新規ユーザー登録の項目が欲しい

### ISSUE THREAD

**Issue by tai-cha** [syuilo/Misskey#14281]
### Summary

2024.7.0のbetaで通報をwebhookで見れるようになったが、新規ユーザー登録も同様に監視したいことがある（特に登録の頻度が多くないサーバーでは）

### Purpose

怪しい新規ユーザー作成を監視していち早く対応したい

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kanade** [comment]
運用しているのは小規模サーバーですが、例のスパム騒動以降は新規登録をいち早く確認したいためGoogle Apps Scriptで定期的に監視してました。
MisskeyそのものからWebhook発火できるならぜひほしいです！

**Comment by samunohito** [comment]
やるか…

**Comment by samunohito** [comment]
prにも記載していますが、このようなペイロードで送信されます。
（MisskeyHubのメンテは追々…）

```json
{
  "server": "http://misskey.local",
  "hookId": "9wahlb3v36ut0004",
  "eventId": "8ed2ff19-24ec-482c-9ecf-cff4ae512ca1",
  "createdAt": 1722253521128,
  "type": "userCreated",
  "body": {
    "id": "9wahlb6h36ut0006",
    "name": null,
    "username": "alice",
    "host": null,
    "avatarUrl": "http://misskey.local/identicon/alice@misskey.local",
    "avatarBlurhash": null,
    "avatarDecorations": [],
    "isBot": false,
    "isCat": false,
    "emojis": {},
    "onlineStatus": "unknown",
    "badgeRoles": []
  }
}
```
