### ISSUE TITLE
「通報の通知先を追加」ダイアログを開いて閉じると操作を受け付けなくなる

### ISSUE THREAD

**Issue by miyakogi** [syuilo/Misskey#14304]
### 💡 Summary

「コントロールパネル」→「通報」→「通知設定」→「通報の連絡先を追加」を押してダイアログを開き、（追加してもしなくても）「OK」または「キャンセル」または右上閉じるボタンで閉じるとリロードするまで画面が一切操作できなくなってしまう。

### 🥰 Expected Behavior

「通報の連絡先を追加」ダイアログを閉じたあと画面が操作できる。

### 🤬 Actual Behavior

「通報の連絡先を追加」ダイアログを閉じたあとリロードするまで画面が操作できない（マウスクリックが作用しない）

### 📝 Steps to Reproduce

1. 「コントロールパネル」→「通報」→「通知設定」→「通報の連絡先を追加」を押してダイアログを開く
2. ダイアログを閉じる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux
* Browser: Firefox 128.0.2 (64-bit)
* Server URL: ローカル及び https://mi.miyaco.moe/
* Misskey: 2024.7.0-beta.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
inertが解除されていない模様
