### ISSUE TITLE
フォロー確認ダイアログで名前に含まれる絵文字がローカルのものと置き換わる

### ISSUE THREAD

**Issue by chan-mai** [syuilo/Misskey#14308]
### 💡 Summary

リモートユーザーの名前に絵文字が含まれていた場合、フォロー確認ダイアログに表示される絵文字がローカルのもにと置き換わる  
https://shahu.ski/notes/9w6bwkqp23go06yk

### 🥰 Expected Behavior

ユーザー名に含まれる絵文字にリモートのものが正しく表示される

### 🤬 Actual Behavior

ユーザー名に含まれる絵文字がローカルのものに置き換わって表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: 6.8.3381.48 (Stable channel) (64-bit) 
* Server URL: https://shahu.ski
* Misskey: 2024.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2024.5.0
* Node: v20.10.0
* PostgreSQL: PostgreSQL 15.7
* Redis:
* OS and Architecture: Ubuntu 22.04.4 LTS
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #13952
