### ISSUE TITLE
[2024.7.0-rc.8] デフォルト表示時およびクラシック表示時（またはスマホ表示時）、リストのボタンがヘッダに無い

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#14338]
### 💡 Summary

![image](https://github.com/user-attachments/assets/7a85e3a6-0020-4a66-9c07-5a8eb74852e1)

掲題と上記画像の通り、ヘッダからボタンが消えてしまっています。
特に、スマホ表示時は導線が大きく削られてしまうので、2024.7.0リリースまでに直したいところ…

### 🥰 Expected Behavior

ボタンがある

### 🤬 Actual Behavior

ない

### 📝 Steps to Reproduce

デフォルト表示またはスマホ表示にする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: any
* Misskey: 2024.7.0-rc.8
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
このコミットによるものだと思われます

https://github.com/misskey-dev/misskey/commit/fccc5b6d620ca6893a0a5649ea9f0d0693727b3b#diff-9d0ecf3d29c90746cf6d45be08336b3ac3c4a9b3bb75be8638dbdc8ab5e6384aL283-L308

**Comment by tai-cha** [comment]
@anatawa12 もうやってます？まだやってなければ手元でFixできてるので #14337 に入れちゃいます
