### ISSUE TITLE
STL appears even if LTL is disabled by a role

### ISSUE THREAD

**Issue by 5ouma** [syuilo/Misskey#14336]
### 💡 Summary

I disable LTL for local and remote users by a role.
Before 2024.7.0-rc.5, STL is also disabled with that role. After updating 2024.7.0-rc.8, STL appeared but it outputs an error.

If I disable LTL from the Role template, STL will be disabled though.

### 🥰 Expected Behavior

STL is disabled with LTL.

### 🤬 Actual Behavior

STL appears even LTL is disabled.

### 📝 Steps to Reproduce

1. Enable LTL in the Role template.
2. Create a role with this config.
```json

{
  "name": "Disable Local Timeline",
  "description": "Disable the local timeline to logged-in users",
  "color": null,
  "iconUrl": null,
  "isModerator": false,
  "isAdministrator": false,
  "displayOrder": 0,
  "target": "conditional",
  "condFormula": {
    "type": "or",
    "values": [{ "type": "isLocal" }, { "type": "isRemote" }]
  },
  "isPublic": false,
  "isExplorable": false,
  "asBadge": false,
  "canEditMembersByModerator": false,
  "policies": { "ltlAvailable": { "value": false, "priority": 1 } }
}
```

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iOS 17.6
* Browser: PWA
* Server URL: https://misskey.5ouma.me
* Misskey: 2024.7.0-rc.8
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Docker
* Misskey: 2024.7.0-rc.8
* Node:
* PostgreSQL: 16.3
* Redis: 7.2.5-alpine3.19
* OS and Architecture: macOS, amd64

For the full compose.yml, see this.
https://github.com/5ouma/homelab/blob/26aca33e59c4bbd9750d1750381a49eaee2d66ed/misskey/compose.yml
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
I confirmed latest develop
