### ISSUE TITLE
「コンソールに何か貼り付けろはすべて詐欺です」という文言をログに出力する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14347]
### Summary

> あったほうが良いかも
> `JSON.parse(localStorage.getItem('account')).token` とか叩いたら簡単にトークン取得できるし

https://submarin.online/notes/9wd92004dl

### Purpose

Self-XSSがあぶない
（別に文言をタイトル通りにするつもりはない）

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
こういうの本来ブラウザの仕事な気がするけどね

**Comment by blueset** [comment]
> こういうの本来ブラウザの仕事な気がするけどね

もうしてるらしい（Chrome 系）
https://developer.chrome.com/blog/self-xss

**Comment by taiyme** [comment]
> こういうの本来ブラウザの仕事な気がするけどね

Self-XSS対策とかは二の次に、単にコンソールにこれ出てたらおもろいと思った

**Comment by kleuzjatob** [comment]
ご参考まで、web版Discordでの様子です（タイトルから直ちにこちらが思い浮かびました）
![image](https://github.com/user-attachments/assets/3b27ce8e-46ed-4ac0-a2ef-ee2d58cfba73)
