### ISSUE TITLE
compose.ymlが追跡対象外になっていない？

### ISSUE THREAD

**Issue by t1nyb0x** [syuilo/Misskey#14344]
### Summary

docker-compose.ymlがcompose.ymlに置き換わったと思うのですが、今までignoreされていたdocker-compose.ymlが消されcompose.ymlが設定されていないように見えます。

https://github.com/misskey-dev/misskey/blob/develop/.gitignore#L33-L39

そのため、compose.ymlを追跡対象外に設定したほうが良いと考えています

### Purpose

docker-compose.ymlから推奨されているファイル名であるcompose.ymlに変更されていますが、
compose.ymlが追跡対象外から外れてしまっています。
また、docker-compose.ymlも追跡対象から外されているため、今までこのファイルでMisskeyコンテナを立てていたユーザーだと追跡対象としてコミットできてしまいます。

元々の設定を考えると、docker-compose.ymlとcompose.ymlは両方とも追跡対象外であるべきだと思うのですがいかがでしょうか？

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by t1nyb0x** [comment]
exampleがあって、そこからコピーをかけて自分用のcompose.ymlを作るということを考えると除外されていたほうが良いように見えますが違うってことですよね・・・

元々あった設定を外すということを考えるとどういう意図でignoreされなくなったのかは気になります。

**Comment by anatawa12** [comment]
https://github.com/misskey-dev/misskey/commits/develop/.devcontainer/docker-compose.yml

あとはこのタイミングで削除が走ってるので`.devcontiner/docker-compose.yml`は残らないと思います

**Comment by t1nyb0x** [comment]
`.devcontainer/docker-compose.yml` ではなく、 ルート配下の `docker-compose.yml` のことを気にしていました。

サーバーを運用する際、ルート配下の `docker-compose.yml` を `docker-compose.example.yml` からコピーして使っていたので・・・。

**Comment by t1nyb0x** [comment]
とりあえずPR作ってみました。
必要であれば確認お願いいたします。

**Comment by tai-cha** [comment]
別issueでもいいものの #14096 で .dockerignoreからもcompose.ymlが消えているかも
