### ISSUE TITLE
[版本2024.7]Android手机上，在“频道”中，点击“复制链接”不起作用

### ISSUE THREAD

**Issue by Pisces-Moze** [syuilo/Misskey#14366]
### 💡 Summary

在安卓手机上的“频道”中，点击“复制链接”不起作用

### 🥰 Expected Behavior

点击后应该复制频道链接到粘贴板

### 🤬 Actual Behavior

在docker中似乎没有报错，应该是前端问题，在“频道”中点击“复制链接”没反应[注意：仅限于Android手机]

### 📝 Steps to Reproduce

在安卓手机上打开misskey的“频道”，点击“复制链接”，没反应

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):HarmonyOS4(Android13)
* Browser:Edge-Android
* Server URL:play.cyberpaws.icu:1145
* Misskey:2024.7
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:docker compose
* Misskey:2024.7
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:debian
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by bzmid** [comment]
yes

在 2024-08-05 13:05:42，"おさむのひと" ***@***.***> 写道：


すれ違いを無くすため、2つ質問をさせてほしいです。

点击“复制链接”不起作用

image.png (view on web)

赤い丸で囲んだボタンのことですか？

Browser:Edge-Android

Microsoft EdgeのAndroid版ということでしょうか？

**Comment by bzmid** [comment]
刚才又测试了一下，在手机上不止"频道"中的复制链接按钮无法使用，似乎是大部分复制链接的按钮都无法使用，例如：网盘中文件链接的复制按钮

在 2024-08-05 13:05:42，"おさむのひと" ***@***.***> 写道：


すれ違いを無くすため、2つ質問をさせてほしいです。

点击“复制链接”不起作用

image.png (view on web)

赤い丸で囲んだボタンのことですか？

Browser:Edge-Android

Microsoft EdgeのAndroid版ということでしょうか？

**Comment by bzmid** [comment]
ok,right

在 2024-08-06 23:33:19，"かっこかり" ***@***.***> 写道：


@/scripts/copy-to-clipboard.tsはHTTPS環境下でないと使用できないためこれはバグではなく予期された動作だと考えられます。HTTPSでないと連合時に不都合が生じるため証明書を取得することをお勧めします。

フォールバックで従来の動作を入れる…？と思ったが特殊な環境でない限りHTTPS接続にするべきだろうし、そこまでしなくてもいいかと思ったりした
