### ISSUE TITLE
mCaptcha is not correctly detected

### ISSUE THREAD

**Issue by Albirew** [syuilo/Misskey#14372]
### 💡 Summary

I get a notification in admin panel saying that bot protection is not configured, even  when mCaptcha is set and seems like working
cc @MomentQYC maybe...
![Screenshot 2024-08-07 at 02-37-59 Panneau de configuration ソーシャルですが](https://github.com/user-attachments/assets/c7f0c891-3c22-4c6e-8d5d-ad8a59b16d33)

### 🥰 Expected Behavior

bot protection warning disapearing after mCaptcha being set.

### 🤬 Actual Behavior

bot protection warning still apearing even after mCaptcha being set.

### 📝 Steps to Reproduce

1. configuring mCaptcha in Misskey configuration

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): ASUS MAXIMUS VIII HERO, Linux Mint 21.3
* Browser: Firefox 128.0.3
* Server URL: soshar.dess.ga
* Misskey: 2024.7.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker compose
* Misskey: 2024.7.0
* Node:whatever's been compiled in docker compose build
* PostgreSQL:15-alpine
* Redis:7-alpine
* OS and Architecture: Debian 12 x86_64
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by zyoshoka** [comment]
Seems like forgot to add a condition here
https://github.com/misskey-dev/misskey/blob/008a66d73f58956b6a9c30f2d48cd554df865ac9/packages/frontend/src/pages/admin/index.vue#L65
