### ISSUE TITLE
メンション入力中のサジェストに表示される「ユーザーを選択」でユーザーを選択してもメンションは入力されない

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#14386]
### 💡 Summary

ノート投稿フォームを含む幾つかの場所において、メンションのサジェストが利用出来ます。

例えばノート投稿フォームにおいて、メンション入力中のサジェストに表示される「ユーザーを選択」でユーザーを選択してもメンションは入力されません。
![image](https://github.com/user-attachments/assets/d17526b7-76ab-48fe-802c-5894d8e021e1)
↓
![image](https://github.com/user-attachments/assets/722d03b4-c1f5-4e46-b7e4-c37b31099175)
↓
(変化なし)

### 🥰 Expected Behavior

メンションが入力される

### 🤬 Actual Behavior

メンションが入力されない

### 📝 Steps to Reproduce

1. ノート投稿フォームを開く
2. `@`を入力する
3. 「ユーザーを選択」を選択する
4. ユーザーを選択して決定する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: https://misskey.niri.la/
* Misskey: 2024.7.0-kinel.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment]
Duplicate of #12703
