### ISSUE TITLE
リバーシ:対局の設定が反映されない

### ISSUE THREAD

**Issue by penginn-net** [syuilo/Misskey#14397]
### 💡 Summary

リバーシで対局の設定が反映されない
2024.5.0では動いてました(フォークインスタンス)
### 🥰 Expected Behavior

リバーシで対局の設定が反映される

### 🤬 Actual Behavior

リバーシで対局の設定が反映されない

### 📝 Steps to Reproduce

1.対戦相手を見つける
2.準備画面で設定をポチポチする
3.反映されない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:https://m1.kzkr.xyz/
* Misskey:2024.7.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
特にリバーシの変更を加えていないなですきー2024.7.0-nade.1.5.6でも確認

**Comment by samunohito** [comment]
https://github.com/misskey-dev/misskey/blob/f50941389d8724442ce2d7326afe9fbdadd3b58e/packages/backend/src/server/api/stream/channels/reversi-game.ts#L50
ログを埋めて確認したところ、ここの条件で弾かれてしまっていました。

![image](https://github.com/user-attachments/assets/beb448ff-1439-4ebd-bf98-e1588159bd14)
上記のようにupdateSettingsはボード選択以外valueにオブジェクトが設定されることはないと思われるので、
対処としては引用箇所のif文を消せば良さそうです。
