### ISSUE TITLE
自分の投稿を閲覧するのにログイン必須にする設定

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#14473]
### Summary

自分の投稿を閲覧するのにログイン必須にする設定

### Purpose

AI、検索エンジンといったクローラーを避けたい時などに使えそう

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
既存のインデックス拒否オプションやフォロワー限定投稿とは別に、ということです?
(また、他のサーバーを経由すれば見えそうですが、連合無し限定とかです…?)

**Comment by syuilo** [comment]
別だわね

**Comment by samunohito** [comment]
インデックス拒否　→ただの意思表示
この件　→ソフトレベルで弾く

みたいな…？

**Comment by syuilo** [comment]
そうね

**Comment by samunohito** [comment]
（見ず知らずのサーバ未ログインユーザに対して自身の投稿を見せたくない設定であり、AIや検索エンジンをブロックできるのは副次的なメリットであると理解）

**Comment by tamaina** [comment]
ActivityPubで見れてしまわないかしら

（SignedGetででしか取得できないようにするとか？）

**Comment by syuilo** [comment]
それは別に良いんじゃないかしら
あとそういうの気にする人は連合無しとかにしてる人も多そう

**Comment by Sayamame-beans** [comment]
固定ノートとかは見えた方が良い気がしています(アカウントの存在を知ることも困難になりそう?)

**Comment by syuilo** [comment]
ほむん

**Comment by anatawa12** [comment]
mastodonで引用ノート見るときにこれあると困る気がする。リンクしかないので。

**Comment by syuilo** [comment]
というと？

**Comment by syuilo** [comment]
ほむん
それが目的の機能(プライバシーのためそのサーバーにアカウントがあるユーザーにしか見せない機能)だわね

**Comment by syuilo** [comment]
あー

**Comment by syuilo** [comment]
> mastodonで引用ノート見るときにこれあると困る気がする。リンクしかないので。

なんかMastodon引用対応する予定だった気がするからそこまで問題にはならなそう

**Comment by syuilo** [comment]
まあ機能上多少の不便が生じることは仕方ないわね

**Comment by anatawa12** [comment]
うーん仕方ないという範囲の規模じゃない気がする......

**Comment by syuilo** [comment]
気になる場合はオンにしなければ良いのではないかしら

**Comment by Sayamame-beans** [comment]
それは"見る側が"困るのでちょっと違う気がします

**Comment by syuilo** [comment]
見る側に不便が生じることよりプライバシーを優先したい人はオンにし、見る側を気にする人はオフにすればいいだけな気がするわね

**Comment by anatawa12** [comment]
見えるべき人に見えない可能性があることが明記されてたらまぁそうかも? メッセージの更新の話になってくるけど

**Comment by syuilo** [comment]
そこら辺の詳細な説明はmisskey hubに置く予定

**Comment by Sayamame-beans** [comment]
設定項目にも書くべきかと(今は見えてしまう可能性がある方向の表記しかないので)

**Comment by syuilo** [comment]
設定項目の方に全てを書くと長くなりすぎるわね(他にも説明したいことがいくつかある)

**Comment by anatawa12** [comment]
全体的になんかこの機能を入れてもfakeな安心感だけを与えて実際は違うってなってしまってあまりよくない気がする....

**Comment by syuilo** [comment]
というと？

**Comment by anatawa12** [comment]
どうせactivity+jsonでリクエストすれば取れるし、リモートで作りの悪いクローラーに見えることは発生し得るし

**Comment by syuilo** [comment]
主に連合をオフにする機能と併用されることを想定している

**Comment by syuilo** [comment]
そこら辺の説明も書く予定

**Comment by anatawa12** [comment]
連合なし想定ならそうか....

連合ありは適用しないとかのほうがなんかリモートを含めた動作の一貫性はあって良さそうな気もする

**Comment by syuilo** [comment]
連合ありだったとしてもこのオプションが有効であれば無効時よりリスクを減らせることは確実だから意味はあるんじゃないかしら(説明としても「絶対に」情報が収集されなくなるとは書いてないし)

**Comment by syuilo** [comment]
絶対にプライバシーが保証されるわけではない機能としてはフォロワーのみ投稿とかダイレクト投稿とかも既にあるし(それに従うかはサーバー次第)

**Comment by anatawa12** [comment]
仕様としてあってというのと独自拡張だとまた話が少し違うと思う......

**Comment by syuilo** [comment]
> 連合ありだったとしてもこのオプションが有効であれば無効時よりリスクを減らせることは確実だから意味はあるんじゃないかしら(説明としても「絶対に」情報が収集されなくなるとは書いてないし)

これに反対されている理由を知りたいわね

**Comment by anatawa12** [comment]
> https://mstdn.virtecam.net/@taichan@mi.taichan.site/113327756485855749
> 
> こういうのの引用元ノートを見るときにその人がログイン必須にしてるとそのサーバーにアカウントを作らない限り内容が追えなくなる
> 
> リンクミスってますすみません

このデメリットに釣り合わないと思ってる

**Comment by syuilo** [comment]
これについてユーザーの意見を今まで何回か聞いてるけど釣り合うと思っているユーザーが多そう

**Comment by Sayamame-beans** [comment]
> 釣り合うか釣り合わないかはそれぞれのユーザーが決めることじゃないかしら

であれば、その説明はMisskey内で尽くされているべきなような気がします…?
Hubまで見に行かないと正しい挙動が分からない、というのはそことちょっと噛み合っていない感じが個人的にはしています。

**Comment by syuilo** [comment]
繰り返すけど、設定項目内で説明をすると画面が埋まるくらいになっちゃうし、Hubで何も問題ないと思うわね
ユーザーの手間としては１クリック増えるだけだし

**Comment by syuilo** [comment]
Hubだと画像使ったり翻訳したりもMisskey本体と比べて容易

**Comment by Sayamame-beans** [comment]
わざわざ別ページまで説明を読みに行ってくれるユーザーは多くない気がしていますが実際どうなんでしょうね…

**Comment by syuilo** [comment]
「説明を読まず、デメリットをよく理解せずにオンにしてしまうユーザーがいるのではないか」というのが争点かしら

**Comment by syuilo** [comment]
オンにする前に「注意事項を読み、理解した上でオンにします」みたいなダイアログ挟めばよさそう
読んでないのにOKするユーザーについては自己責任としか言いようがないんじゃないかしら

**Comment by anatawa12** [comment]
「説明を読まず、デメリットをよく理解せずにオンにしてしまうユーザーがいる」のデメリットに影響されるのが読まなかった人じゃない別の人に被るのを問題視してますが、デメリットを消せないという前提では「説明を読まず、デメリットをよく理解せずにオンにしてしまうユーザーがいるのではないか」でだいたいあってるかな

**Comment by Sayamame-beans** [comment]
現状だと説明を読んでも誤解することになるのは問題かなぁと思います
Hubに載せて、そのリンクがMisskey側の機能説明欄に載るならまあ…読んでくれる人はいそうです

**Comment by syuilo** [comment]
> デメリットに影響されるのが読まなかった人じゃない別の人に被る

そのデメリットを認識してオンにした場合は問題ないという認識かしら
自分は問題ないという認識

**Comment by anatawa12** [comment]
まぁそれはフォロワー限定にするのと同じではある気がする。

(けど正しく認知されるとはあまり思ってない)

**Comment by syuilo** [comment]
あと「この機能は連合なしのノートにしか適用されない」というふうにしてしまうと、逆説的に「連合ありで投稿するリスクが増える」ことになるからFediverse的には負の影響がありそう

**Comment by anatawa12** [comment]
うーん負の影響のほうが正しい気がするのよね....マージされたけど

**Comment by syuilo** [comment]
連合に対応しているソフトウェアな以上「連合ありで投稿するのは推奨されない」みたいな感じにはしたくないのよね

**Comment by anatawa12** [comment]
推奨されないとは違うと思う...

**Comment by syuilo** [comment]
ユーザーが理解して使用しないのではないかという懸念が払拭されてない感じかしら

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by syuilo** [comment]
他の方々の意見も聞きたいわね

**Comment by tai-cha** [comment]
マージ済みなことを確認したうえで一応自分のユースケースで困る場面を言っておくと「返信」「引用リノート」「リノート数」「リアクション」の完全なデータはリモートでしか見られないので、たびたびリモートに見に行っているけどこれがオンだとみられなくなる

**Comment by anatawa12** [comment]
そういえばこれ(とvisibility変更)、ローカルでも引用と引用者よ芋に引用者の意図に反して見えないとかが発生するから、ユーザがこれをオンにしてるかどうかが容易に見えてあるべきな気がした。(引用とかする前にリモートに自分のノートの意図が正しく見えない可能性があるかを確認できるべき)

**Comment by syuilo** [comment]
今知ったけどBlueskyも投稿見るのにログイン必須っぽい

**Comment by tamaina** [comment]
リモートのユーザーをフォローバックする際にどういう人か見たい時にこれが設定されていると全く情報が得られないため、私は結構困ってる

**Comment by tamaina** [comment]
リモートのユーザーをフォローバックする際にどういう人か見たい時にこれが設定されていると全く情報が得られないため、私は結構困ってる

**Comment by tamaina** [comment]
> 今知ったけどBlueskyも投稿見るのにログイン必須っぽい

設定で変更可能

**Comment by syuilo** [comment]
> リモートのユーザーをフォローバックする際にどういう人か見たい時にこれが設定されていると全く情報が得られないため、私は結構困ってる

これは本人がそれを希望しているのだから従うしかないんじゃないかしら

**Comment by syuilo** [comment]
あとアカウント作れば済む

**Comment by tamaina** [comment]
> あとアカウント作れば済む

見たいユーザーがいるサーバーにいちいちアカウント作るのはちょっと…招待制のところも多いし

> これは本人がそれを希望しているのだから

デフォルトでオフなのね（オンにしてる人が相当多いからデフォルトでオンなのかと）

**Comment by meronmks** [comment]
> 今知ったけどBlueskyも投稿見るのにログイン必須っぽい

設定でのopt-in方式でユーザの意思で必須にできるみたいですね。
説明文の参考としてスクショと説明文中にあるリンクのURLを置いておきますね。
![Image](https://github.com/user-attachments/assets/0fb43472-3446-4236-b33e-a2217d53d50c)
https://blueskyweb.zendesk.com/hc/en-us/articles/15835264007693-Data-Privacy

**Comment by kleuzjatob** [comment]
ログイン必須投稿について対象を連合なし分のみに絞るオプションをリクエストする手前でしたが、こちらが議論中でしたのでissueの発行を保留しております。

幾年前から何かと公開範囲を使い分けてきた身としては、連合したくない意志を持った投稿かつその場合に限りログイン限定とした方が何かと使い勝手が良い、という期待でリクエストを書いておりましたが、現に起きている所として

> > > [tamaina on Nov 7, 2024](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2461190270)
> > > リモートのユーザーをフォローバックする際にどういう人か見たい時にこれが設定されていると全く情報が得られないため、私は結構困ってる
> > 
> > [syuilo on Nov 7, 2024](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2461191677)
> > これは本人がそれを希望しているのだから従うしかないんじゃないかしら
> 
> [tamaina on Nov 7, 2024](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2461196640)
> デフォルトでオフなのね（オンにしてる人が相当多い

こちら、（リレーサーバー越しが大半の）弊GTLから見に行っても本当に本機能を使われる方が多いと感じる傍ら、「ログイン必須化しているため公開投稿はリモートから確認を」との旨で断っている方もしばしば見かける気がいたします。
現機能の有効化がご本人の希望を表しているかは、副作用（過剰適用）に目を瞑って渋々使われている方もしばしばいらっしゃるだろうとは存じます。

> [syuilo on Oct 20, 2024](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2424816456)
> 「この機能は連合なしのノートにしか適用されない」というふうにしてしまうと、逆説的に「連合ありで投稿するリスクが増える」ことになるからFediverse的には負の影響がありそう
> [syuilo on Oct 21, 2024](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2426153401)
> 連合に対応しているソフトウェアな以上「連合ありで投稿するのは推奨されない」みたいな感じにはしたくないのよね

連合ありノートの印象については検討した際に恐らく本件のログイン必須化とは別機能の場で対応される気がいたしますし、もとい本件が負う事も無いかと存じますので、別issueに切り離されては如何か、というのが私の思う所です。

最初のリクエストの件について、連合ありノートの印象への懸念と密に関わっているなら余計に話をもつれさせるかと止めていましたが、問題無いのでしたら発行しておきます。
