### ISSUE TITLE
Weird AP derivered chart in control panel

### ISSUE THREAD

**Issue by zyoshoka** [syuilo/Misskey#14480]
### 💡 Summary

コントロールパネル内の Ap requests に表示されているチャートの表示が変です。

### 🥰 Expected Behavior

Out: Fail が 0 のとき、チャート上では 0 のところにプロットされる

### 🤬 Actual Behavior

Out: Fail が 0 のとき、チャート上では 0 のところにプロットされていない
<img width="830" alt="コントロールパネル内のAp Requestsのスクリーンショット" src="https://github.com/user-attachments/assets/6d43cd64-485b-418e-9d51-f5616340aa0f">

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey: 2024.8.0
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
バグっぽいのでバグ認定
