### ISSUE TITLE
アイコンデコレーションの管理画面の一覧でデコレーションを確認できるようにしてほしい

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#14490]
### Summary

一覧でデコレーションの名前と一緒に画像を表示してほしい

### Purpose

いまのところ、デコレーション名しか確認できないので、
何を登録して何を登録していないのか確認するのが地味に手間だったりする
デコレーションの画像も確認したい

下の画像は現状

<img src="https://github.com/user-attachments/assets/ea778515-1547-4e84-8d27-d91448f63f3a" width="50%" />

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by fruitriin** [comment]
ふつうに一般用の一覧UIって確認しやすいよねとか
![スクリーンショット 2024-09-03 17 38 45](https://github.com/user-attachments/assets/0c1408c2-b230-49e8-bb69-4c664fb8995a)

雑コラ的にはなるべく差分少なくやろうと考えるとこういうのとか
![スクリーンショット 2024-09-03 17 08 19](https://github.com/user-attachments/assets/b3b53ed7-82b7-4ebe-b77f-c212b9d7395a)

**Comment by samunohito** [comment]
（ライトテーマ・ダークテーマの目安として、白背景・黒背景のプレビューもあるとなおいいかも…？）
