### ISSUE TITLE
アンテナの更新時にキーワードを与えないと内部エラーが報告される

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14492]
### 💡 Summary

アンテナの更新時にキーワードを与えないと内部エラーが報告される

reported in https://misskey.niri.la/notes/9xqwlovlre

### 🥰 Expected Behavior

内部エラーではなく単なるエラーとして報告するべき。
現状の実装では`Error`が投げられているが、`ApiError`ではないため内部エラーとしてフロントに出て不都合

### 🤬 Actual Behavior

内部エラーとして報告される

### 📝 Steps to Reproduce

1. アンテナを作成する
2. そのアンテナについて包含キーワード及び除外キーワードを空にして更新しようとする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): ?
* Browser: ?
* Server URL: misskey.niri.la
* Misskey: 2024.8.0-kinel.1
```

### 🛰 Backend Environment (for server admin)

```markdown
n/a (not server admin)
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
(そもそも: 多分フロント側でもvalidationされるべき)

**Comment by samunohito** [comment]
更新時だけでなく、作成時も同様の模様…

https://github.com/misskey-dev/misskey/blob/c1514ce91dc08481a092a789ee37da546cdb4583/packages/backend/src/server/api/endpoints/antennas/create.ts#L89-L91

**Comment by samunohito** [comment]
@KisaragiEffective 
作成時も併せて対応いただくことは可能でしょうか…？

**Comment by KisaragiEffective** [comment]
> @KisaragiEffective 作成時も併せて対応いただくことは可能でしょうか…？

やります！
