### ISSUE TITLE
copy button bug

### ISSUE THREAD

**Issue by JokerPan12** [syuilo/Misskey#14527]
### 💡 Summary

![微信图片_20240909152653](https://github.com/user-attachments/assets/6afdb03d-5100-473f-8561-e8e9257c56de)
Press the copy button shown in the above picture
after that
![微信图片_20240909152726](https://github.com/user-attachments/assets/b98d5101-5128-4cf3-89e2-7b81c6ba27ec)

### 🥰 Expected Behavior

Fixed the bug where the copy button did not respond when clicked and the console reported an error

### 🤬 Actual Behavior

The bug where clicking the copy button does not respond and the console reports an error

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
Is your browser very outdated?
The navigator.clipboard.writeText is relatively new and legacy browser does not have it.
