### ISSUE TITLE
frontend: frontend-embed/src/to-be-shared を共通化する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14530]
### Summary

書いてある通り

### Purpose

挙動をそろえる・保守性を上げるなど

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
ref. https://github.com/misskey-dev/misskey/pull/13929#issuecomment-2338024113
