### ISSUE TITLE
リロードしますか？のモーダルが多重に表示される問題

### ISSUE THREAD

**Issue by MattyaDaihuku** [syuilo/Misskey#14541]
### 💡 Summary

タイトルの通りです。
![image](https://github.com/user-attachments/assets/39e50bd8-9598-4e2f-ad4f-177fa25c68dc)
このモーダルが多重に表示されます。
なぜか多重に表示されず、正常に動くこともあり不安定です

### 🥰 Expected Behavior

一度だけ表示される

### 🤬 Actual Behavior

多重に表示されている

### 📝 Steps to Reproduce

1. 設定→全般
2. "リアクションの最大横幅を制限し、縮小して表示する"のトグルを操作する
3. 多重に表示される

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): ChromeBook
* Browser: Google Chrome 121.0.6167.212
* Server URL: mi.nakn.jp
* Misskey: 2024.8.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
reopenします
> Do not close issues that are about to be resolved. It should remain open until a commit that actually resolves it is merged.
> https://github.com/misskey-dev/misskey/blob/837a8e15d893a670ab2ce51b3ec87e6b62a51da7/CONTRIBUTING.md

**Comment by MattyaDaihuku** [comment]
すみません、ちゃんと読んでなかったです
