### ISSUE TITLE
テキスト無しで引用ができてしまう

### ISSUE THREAD

**Issue by 35enidoi** [syuilo/Misskey#14547]
### 💡 Summary

![image](https://github.com/user-attachments/assets/e037a446-d687-4561-830e-d22ba270042a)
画像を添付していないテキスト無しの引用をすることができてしまう
リノートの扱いになる

[はなみすきー](https://misskey.flowers)でも同様の問題が発生することを確認済み

### 🥰 Expected Behavior

テキスト無しで引用できない

### 🤬 Actual Behavior

テキスト無しで引用できてしまう

### 📝 Steps to Reproduce

1. 何かをノートする
2. そのノートを引用(リノートボタンの方から、ノートに添付するほうじゃない)をする
3. テキスト無しでノートできてしまう

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11
* Browser: Opera GX
* Server URL: misskey.io
* Misskey: 2024.5.0-io.2d
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
仕様だと思います。

**Comment by anatawa12** [comment]
リノートの一つの方法としてバグではなく仕様だと認識しています。
