### ISSUE TITLE
管理画面側の絵文字表示をカテゴリ表示に対応させる

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14591]
### Summary

https://activitypub.software/TransFem-org/Sharkey/-/issues/670

/about#emojis にあるカテゴリ別に分けるUIを絵文字の管理画面でも使えるようにする

### Purpose

見やすさ向上

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #12546 ?
