### ISSUE TITLE
Misskeyサーバー側からのメール通知のデザインをいい感じにしたい

### ISSUE THREAD

**Issue by Mai-Shinano** [syuilo/Misskey#14599]
### Summary

現在はこのやうにインスタンスのアイコン(しかもクソデカ)と内容だけのシンプルなメール
![image](https://github.com/user-attachments/assets/22cb8ff9-44d5-48de-b7f8-9e5acab52460)
(スクリーンショットはにりらみすきー部より配信されたメールです)
もっとデザインをいい感じにしたい

### Purpose

メール通知が見やすくなる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by DA-TENSHI** [comment]
日本語化などもできそう。
