### ISSUE TITLE
RBTに表記ゆれがある

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#14624]
### Summary

Reaction Buffering TechnologyとReaction Boost Technologyがあり、UIやドキュメント（内部的な名称を除く）で統一されていない

### Purpose

合わせておいたほうがわかりやすいかも

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
UI上では後者にした

**Comment by syuilo** [comment]
👍
