### ISSUE TITLE
[2024.9.0-alpha.11] 名前が横方向に押しつぶされて読めなくなる

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#14642]
### 💡 Summary

横幅が狭いとｷﾞﾁｷﾞﾁ

### 🥰 Expected Behavior

どうしよう

### 🤬 Actual Behavior

https://misskey.gamelore.fun/notes/9yp749jsh6

![image](https://github.com/user-attachments/assets/3085928a-e961-4ce4-bee8-63aec78f06e3)

https://misskey.gamelore.fun/notes/9yp77rf0ax

![image](https://github.com/user-attachments/assets/6438413d-85d6-4324-9d67-1cb956e67d05)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by fruitriin** [comment]
仕様なら仕様ということでCloseでもいいです

**Comment by KisaragiEffective** [comment]
多分昔からの問題だと思います。
昔はオーバーフローしてたら日付でクリップされてて見えなくなったのをアスペクト比を変えて表示するようになった副作用だった気がしますが覚えていません。
ですが同様のことはデスクトップでもおそらくは再現できるものと思われます。

**Comment by fruitriin** [comment]
ロールアイコンが左詰めから右詰めに変わってるので、この近辺にデザイン調整が入った余波とおもわれる

**Comment by tai-cha** [comment]
まあ見づらいしFixするでもいいと思うんだけどExpected Behavior的なほうどうしたらいいんだろうの気持ち

**Comment by KisaragiEffective** [comment]
> 多分昔からの問題だと思います。 昔はオーバーフローしてたら日付でクリップされてて見えなくなったのをアスペクト比を変えて表示するようになった副作用だった気がしますが覚えていません。 ですが同様のことはデスクトップでもおそらくは再現できるものと思われます。

言及した現象、ハンドルだけ潰れるやつだったけど今回は名前も潰れてるから違いそうなきがしてきた

**Comment by syuilo** [comment]
省略するのと縮めるの併用したいけど出来なさそう

**Comment by syuilo** [comment]
MkCondensedLineでtext-overflow: ellipsis;を使う方法募集中

**Comment by syuilo** [comment]
TASUKETE

**Comment by fruitriin** [comment]
ちなみにサンプルで貼った画像はマシなほうで、リモートからのノートは
・インスタンスのドメインがユーザーIDの後ろに来る
・引用されると引用された中のノートの幅は70%くらいになる

この辺の合わせ技でとてもせまい

**Comment by fruitriin** [comment]
elipsisもwebkit-line-clampも、はみ出した部分をhiddenにしてその手前に……を置くcssなので、文字を指定範囲に収めるcssと組み合わせられないような気がするなあ

**Comment by syuilo** [comment]
minScaleを0.5とかにしたらはみ出すから組み合わせられてしかるべきな気がする

**Comment by fruitriin** [comment]
それならいけるかも

**Comment by syuilo** [comment]
> 省略するのと縮めるの併用したいけど出来なさそう

成功した

**Comment by syuilo** [comment]
![chrome_PXNZDLaa8N](https://github.com/user-attachments/assets/1403ee8d-e3c4-4faf-b2db-26b68448d97e)

**Comment by fruitriin** [comment]
よさそうにみえる
