### ISSUE TITLE
/signin の設計がおかしい可能性がある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#14699]
### Summary

仕様通り想定して飛んできているリクエストに対してエラーを返すのはおかしい

### Purpose

あ

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
そうね

**Comment by syuilo** [comment]
successというよりfinishとかの方がよさそう

**Comment by anatawa12** [comment]
> 仕様通り想定して飛んできているリクエストに対してエラーを返すのはおかしい

私はおかしくないと思います。

資格情報が足りない状態でのレスポンスに200は強い違和感を持ちます

403が違うってのはある程度同意しますし、401は不適当ですし400あたりがよいと私は感じます

**Comment by syuilo** [comment]
API側の実装がこれで正しいとしたら、クライアント側をエラーが出ないようにリクエストするように修正するべきだわね

**Comment by syuilo** [comment]
そう、だからどちらかの設計がおかしいということになる

**Comment by syuilo** [comment]
そもそもsigninという名のAPIがsignin以外の処理(次のステップを指定するなど)を担当している時点で若干おかしい

**Comment by syuilo** [comment]
> エラーとして返ってくるのってそんなにまずいかしら

とてもまずい
発生したエラーを報告するような仕組みが入っていたとしたら、(正常な手順で)ログインするたびにエラーが報告されることになる

**Comment by syuilo** [comment]
ステータスコードじゃなく、実際にプログラム上もエラーやfailedとして表現されている

**Comment by anatawa12** [comment]
バックエンド的にはエラーではあると思う。

フロント的にはthrowしない方が適切かも

**Comment by syuilo** [comment]
バックエンド的にエラーなのだとしたら、フロントエンドはバックエンドがエラーになってしまわないように正しく実装するべきという話になる
でも現在のフロントエンドの実装が問題ないのだとしたら間違っているのはバックエンドということになりそう

**Comment by anatawa12** [comment]
> そもそもsigninという名のAPIがsignin以外の処理(次のステップを指定するなど)を担当している時点で若干おかしい

これも資格情報不足でチャレンジ種別を返すはそこまでおかしくないと思います(401もそうなってるし)

**Comment by syuilo** [comment]
そこまでおかしくはないけど、ちょっとはおかしい(直感的ではない)
ちょっとでもおかしいのであれば直した方が良い

**Comment by anatawa12** [comment]
別のエンドポイントとして必要資格情報を返すエンドポイントは追加した方が良いかも

けどsigninは足りない資格情報がある時は4xxを返してあげるべきだと思う。(ここに必要資格情報を含めるかはどっちでもいいけど今あるならついてて良さそう)

**Comment by syuilo** [comment]
エンドポイント分けると場合によってはリクエストが二度手間というか無駄になる場合がありそう

**Comment by anatawa12** [comment]
> これすると二要素認証が有効化されているかどうかなどが簡単に取れてしまう（UserDetailedに二要素認証関連のプロパティが公開されているのと何ら変わらなくなる）ので目的を達成できなくなる（工夫次第かも？）

これサインイン試行でも同じこと起きるものだと私は認識してるのですが違う感じですか(現状の理解不足があるかも)

**Comment by syuilo** [comment]
> > エラーとして返ってくるのってそんなにまずいかしら
> 
> とてもまずい 発生したエラーを報告するような仕組みが入っていたとしたら、(正常な手順で)ログインするたびにエラーが報告されることになる

一般にエラーは問題だとして通知される傾向にある
例えばブラウザの開発者ツールでもリクエストがエラーになったら目立つようにされている
けど今回のケースはこれら一連のフローは事前に想定されたもので、すべて仕様通りに動いてるわけだから問題であるとして通知される必要はない

**Comment by anatawa12** [comment]
> 
> 二要素認証（ワンタイムパスワード）が必要かどうかはパスワードを入力して送信するまでわからない（次に必要な資格情報を一回ごとに返す仕様になっているので）

なるほど


エラーを集める仕組みにかんしては後処理でどうにかするべきな気がする


別言語の例になっちゃうけどjavaのClassLoaderではとあるローダで見つからなかったのを例外とするんだけど、複数のローダを組み合わせて使う場合はそのエラーは別のローダへのフォールバックのトリガーになるので、ある意味意図しているもので、そういうのはthrowされたタイミングでログが残されるべきではないし残されないようにログの収集側がするべきだと私は思ってる

**Comment by syuilo** [comment]
API側もこのフローを想定して実装されているのだから、エラー系のステータスコードを返すのはおかしいように思う

**Comment by syuilo** [comment]
エラートラッキングサービスなどがあることからも分かるように、エラーは

- 報告されるべきもの
- 起こしてはならないもの
- 修正されるべきもの

といった意味が含まれているけど、今回はどれにも当てはまらない(仕様通りでこれを前提としたフローなのだから報告される必要もないし起こしてはならないものでもないし修正されるべきものでもない)

**Comment by anatawa12** [comment]
HTTPのステータスコードには起こさないべきものという程の意味はないと思うけどなぁ...(そういう意味付けをしてるツールがあるかもしれないけど)

400はリクエストのどっかが期待したもの(今回は2faトークン等)ではなかったということで、実際サインインするという操作については足りないっていうエラーを返すべきだと思う

**Comment by syuilo** [comment]
実態にあまりそぐわない /signin という名前だから「情報が足りなかったらエラーにする」のが正しいように思えてしまうのだと思う
これが /process-signin-flow みたいな名前だとしたらどうだろうか

**Comment by anatawa12** [comment]
> これが /process-signin-flow みたいな名前だとしたらどうだろうか

あーこれなら200でもいいと感じる

**Comment by syuilo** [comment]
このAPIはサインインするにあたっての情報が足りない状態でリクエストされることを期待しているのだから何もエラー要素がない

**Comment by syuilo** [comment]
消す
