### ISSUE TITLE
MkSparkleの動作がおかしい

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#14710]
### 💡 Summary

全然きらっとしない

### 🥰 Expected Behavior

きらっとする

### 🤬 Actual Behavior

ほとんどきらっとしない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
duplicate https://github.com/misskey-dev/misskey/issues/14155 ?

**Comment by syuilo** [comment]
それっぽいけど手元の確認ではmisskey 2024.9.0時点では正常で、debelop最新だと動かないという感じになってる

**Comment by syuilo** [comment]
ちなみにchrome

**Comment by syuilo** [comment]
firefoxで試すか

**Comment by syuilo** [comment]
- firefoxでは期待する動作をした
- misskey 2024.9.0時点では正常と言ったけどよく見たらやっぱり少なかったので嘘だった

**Comment by syuilo** [comment]
duplicate https://github.com/misskey-dev/misskey/issues/14155
