### ISSUE TITLE
[スパム対策]管理者またはモデレーターが一定期間ログインしなかったサーバーは自動で新規登録を一時中断する

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#14729]
### Summary

いわゆる放置サーバー問題への対処。管理者またはモデレーターが一定期間(1週間以上?)ログインがなかった場合は新規登録を一時中断し、再度管理者またはモデレーターがログインして解除操作を行わない限り新規登録をできないようにする
ほぼ同じ→ #13437

### Purpose

ロボットチェックもメールアドレスチェックもほぼ無意味になってきているため、根本的なところを閉じる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by KisaragiEffective** [comment]
related: #13437

**Comment by samunohito** [comment]
（むしろ、ほぼduplicate…？）

**Comment by tkmrgit** [comment]
#13437
2月にも提案されてて実装されてにゃいのか...
