### ISSUE TITLE
2024.9 以降 ノート投稿時のプレビューエリアに斜線がかかるようになった

### ISSUE THREAD

**Issue by camilla-ett** [syuilo/Misskey#14734]
### 💡 Summary

表題および Expected Behavior / Actual Behavior に掲載した図の通りです。これは2024.9以降の正式な仕様でしょうか。それともデザイン崩れでしょうか

### 🥰 Expected Behavior

![image](https://github.com/user-attachments/assets/a44c239f-4fe8-4cc3-adbd-51b89b0ffc89)

### 🤬 Actual Behavior

![image](https://github.com/user-attachments/assets/ff55415d-ff64-48e1-8465-3f0768693499)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
デザインとなっております
