### ISSUE TITLE
POST:admin/emoji/update​のパラメーターを一部指定で送信すると「name already exists」エラーが出る

### ISSUE THREAD

**Issue by mendakon** [syuilo/Misskey#14747]
### 💡 Summary

例えば以下のようなjsonで
```
{
    "id": "9yoba11106",
    "isSensitive": true
}
```
POST:admin/emoji/updateを使用して絵文字更新を行おうとすると、
```
{
    "error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "name already exists",
                "code": "Error",
                "id": "63e11af7-e4c8-4a17-9f04-a698895e9697"
            }
        }
    }
}
```
というエラーが出る。

```
{
    "id": "9dohxjvw1t",
    "name": "kiken",
    "category": "文字",
    "aliases": [
        "危険",
        "きけん"
    ],
    "license": "made in sushi.ski",
    "isSensitive": true,
    "localOnly": false,
    "roleIdsThatCanBeUsedThisEmojiAsReaction": []
}
```

のような形式ですべての項目を指定すると正常に更新できる
![image](https://github.com/user-attachments/assets/8d4b8456-5fd1-483a-9552-76c648322b07)

あと、apiドキュメントに、requiredの項目が存在しないのが気になる。（画像参照）意図的にそうしている可能性もありそうですが
赤丸のどれかがrequiredになるべきなのでは？

### 🥰 Expected Behavior

例え以下のようなjsonで
```
{
    "id": "9yoba11106",
    "isSensitive": true
}
```
部分的な指定でも正常にアップデートが行える

### 🤬 Actual Behavior

部分指定で、
```
{
    "id": "9yoba11106",
    "isSensitive": true
}
```
POST:admin/emoji/updateを使用して絵文字更新を行おうとすると、
```
{
    "error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "name already exists",
                "code": "Error",
                "id": "63e11af7-e4c8-4a17-9f04-a698895e9697"
            }
        }
    }
}
```
というエラーが出る。

### 📝 Steps to Reproduce

1. 設定からmisskeyの絵文字操作ができるapiキーを取得する
2. 以下の内容でPOST /admin/emoji/updateエンドポイントにpostmanなどで対してリクエストを送信する。
```
{
    "id": "9yoba11106",
    "isSensitive": true
}
```
3. 上記のリクエストに対してエラーレスポンスが返ってくる。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:chrome(というかapiリクエストはpostmanで送った)
* Server URL:https://sushi.ski
* Misskey:2024.10.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:2024.10.0
* Node:v20.11.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by FineArchs** [comment]
私の開発環境で該当バージョン（ 6de7c275221996011b03699a6f618909100cd44e ）をチェックアウトして試したところ、APIコンソールとcurlでのリクエストは正常に完了しました。
```bash
# curlの例(bash)
curl -X POST -H "Content-Type: application/json" -d '{"id": "9z7ogqt1twus0003", "isSensitive": true, "i": "FGYDmrkZDvsYWX4C"}' localhost:3000/api/admin/emoji/update
```
postmanでは未確認です。

**Comment by FineArchs** [comment]
開発環境が絵文字一個という特殊な環境だったため絵文字を増やしてから実行したところ、該当エラーが再現できました。
https://github.com/misskey-dev/misskey/blob/d376aab45edc2170592a256a429a1d0b364bd7f5/packages/backend/src/core/CustomEmojiService.ts#L117
ここでnameがundefinedの検索が行われるのが原因と思われます。

**Comment by samunohito** [comment]
パラメータから引き込んだnameがundefinedのときはsameNameEmojiの取得及び重複チェックをしないようにする必要がありそうですね

**Comment by FineArchs** [comment]
apiドキュメントの方は、このエンドポイントが「"id"か"name"のどちらかが必要」なのでどちらにもrequiredがつかない感じです。
それ用の表示があればいいんですが、ドキュメント生成は外部ライブラリに頼っているので改善は難しそうです
