### ISSUE TITLE
2024.10.xで通報機能が使用できない。

### ISSUE THREAD

**Issue by trpgerasami** [syuilo/Misskey#14759]
### 💡 Summary

通報機能がエラーで使えなくなっている。

### 🥰 Expected Behavior

通報機能を従来通りに使えるようになる。

### 🤬 Actual Behavior

通報しようとするとエラーが発生する。

``Endpoint: users/report-abuse
Info: {"e":{"message":"column \"moderationNote\" of relation \"abuse_user_report\" does not exist","code":"QueryFailedError","id":"43857686-807d-4e82-96ea-3d0e965e75f2"}}
Date: 2024-10-12T23:01:46.472Z``

### 📝 Steps to Reproduce

1. 2024.10.0にアップデートする
2. 通報機能を使用する
3. エラーが発生する

### 💻 Frontend Environment

```markdown
Model and OS of the device(s): windows11, ios17.6.1
Browser: Chrome 129.0.6668.90
Server URL: trpger.us
Misskey: 2024.10.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Misskey:2024.10.0
*通報時の通知設定については設定済である
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
アップデートの際マイグレーションは実行されていますでしょうか？
