### ISSUE TITLE
絵文字ピッカーで入力できない絵文字がある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#14758]
### 💡 Summary

🈚️とか

### 🥰 Expected Behavior

確定できる

### 🤬 Actual Behavior

確定できない

### 📝 Steps to Reproduce

絵文字ピッカーの検索欄で🈚️などを入力して確定しようとする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): iPadOS 18.1
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by zyoshoka** [comment]
Duplicate of #13845

🈚️ ではなく 🈚 だと可能です

**Comment by syuilo** [comment]
iOSからだと一緒に見えるわね
