### ISSUE TITLE
Playの保存ボタンなどの位置がおかしい

### ISSUE THREAD

**Issue by FineArchs** [syuilo/Misskey#14754]
### 💡 Summary

Play編集画面やハッシュタグのページを
- スマートフォンから
- ページ内ウィンドウで

開いた時に、下付きのabsolute要素の下に不自然な空きがあります。

### 🥰 Expected Behavior

ウィンドウ下部に隙間なくついている

### 🤬 Actual Behavior

ハッシュタグの場合
![Screenshot_20241012_095729_com android chrome_edit_348223505458840](https://github.com/user-attachments/assets/1e9ae57e-6841-4e33-922e-b6c529d66a16)
「このハッシュタグで投稿」ボタンの位置が不自然に上。

Play編集画面の場合
![Screenshot_20241012_094830_com android chrome_edit_348206910215613](https://github.com/user-attachments/assets/64f59ab3-40c5-4cc7-afa6-c2e642b1345a)
Save, Showボタンの位置が不自然に上。

### 📝 Steps to Reproduce

1. スマートフォンでmisskeyを開く。
2. Playの編集画面またはハッシュタグのページを、長押しで表示されるメニュー→ウィンドウで開く　で開く。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Huawei EMUI12
* Browser: Chrome
* Server URL: sushi.ski
* Misskey: 2024.10.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by syuilo** [comment]
> Playの編集画面またはハッシュタグのページを、長押しで表示されるメニュー→ウィンドウで開く　で開く。

Androidじゃないとこの手順は実行できなさそうかしら
