### ISSUE TITLE
カスタム絵文字の管理タブを検索できるようにして欲しい

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#14808]
### Summary

カスタム絵文字の管理タブを検索できるようにして欲しい

### Purpose

https://novelskey.tarbin.net/notes/9zkyt48th2

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
「カスタム絵文字の管理タブ」とは何を指しているかsリラ

**Comment by zyoshoka** [comment]
元ノート、おそらく fork に対する機能要望に見えますが（カスタム絵文字管理画面での絵文字検索機能なら既にありますので）
