### ISSUE TITLE
baraag.netのユーザーをフォローできない

### ISSUE THREAD

**Issue by a-ru2016** [syuilo/Misskey#14809]
### 💡 Summary

misskey.ioでhttps://misskey.io/@anatanuki@baraag.net をフォローしようとしたところ処理中と出続けてフォローが完了しませんでした。

### 🥰 Expected Behavior

フォローできる

### 🤬 Actual Behavior

処理中から進まない

### 💻 Frontend Environment

* Model and OS of the device(s):M1macboockpro
* Browser:vivaldi
* Server URL:misskey.io
* Misskey:

### 🛰 Backend Environment (for server admin)

* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment]
恐れ入りますが、このサイトはMisskeyというソフトウェアについて管理するサイトとなっております。
個々のサーバーの詳細やご不明な点についてはお使いのサーバーの担当者へお問い合わせください。
