### ISSUE TITLE
Send delete requests when making notes hidden

### ISSUE THREAD

**Issue by Natsuki-Kaede** [syuilo/Misskey#14819]
### Summary

Making notes hidden locally only doesn't seem very useful. Maybe add a switch to select whether to delete them from the remote server or not.

### Purpose

Send delete requests when making notes hidden.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
It makes restoring notes harder, and federation cost would be worse, I think.

**Comment by Natsuki-Kaede** [comment]
> It makes restoring notes harder, and federation cost would be worse, I think.

No, it is just a way for protect users’ privacy.
If I set notes hidden but can be see in anywhere, what is the use of this?
It's better to let the user choose.
