### ISSUE TITLE
miAuth認証画面で認証するアカウントを明示的にしてほしい

### ISSUE THREAD

**Issue by MizuiMiduki** [syuilo/Misskey#14827]
### Summary

miauth認証画面に認証中のアカウントを明示的に表示するようにしていただきたいです

### Purpose

miauth認証は非常に便利なのですが、現状ではどのアカウントを認証しようとしているか表示されていないため、同一サーバーに複数アカウント持っているユーザーではUXが低下していると考えます。

それを改善するために、miauth認証画面上にユーザー名・アイコンなどを表示し明示的に認証するアカウントを表示するようにしていただきたいです

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
認証対象のユーザーを表示するのであれば、その場で対象アカウントの切り替えも出来ると良さそうですね
