### ISSUE TITLE
[misskey-js] StreamをNodejs環境で扱うことが困難になっている

### ISSUE THREAD

**Issue by 3-x-3** [syuilo/Misskey#14847]
### 💡 Summary

https://github.com/misskey-dev/misskey/pull/14277 にて
https://github.com/misskey-dev/misskey/commit/3d8eda14a299dbf97cd135f7087c1797bd1ebb37#diff-e2885eeaffb0662816c98c56cd9f1d9d80060ca1908620f14a8c707b7e2c9661R2969
misskey-jsのStreamのWebSocketの型が`WebSocket`に限定されている。

この`Websocket`型はブラウザで扱う場合のWebSocketの型であり、Node.jsで扱う際にはブラウザのWebSocket型と完全には互換性のない'ws'パッケージでのWebSocketを扱うこととなるがこれではmisskey-jsを利用してNode上でStreamを扱えない

※現段階でのmisskey-jsは(README)[https://github.com/misskey-dev/misskey/blob/develop/packages/misskey-js/README.md]によればNodeでも動作することになっている

### 🥰 Expected Behavior

Node.js環境でもWebSocketを扱える

### 🤬 Actual Behavior

TSで扱うと型エラーが発生しそもそも動かない
![Image](https://github.com/user-attachments/assets/7ab242dd-d4f1-4643-bab5-ac33ab49afa3)

### 📝 Steps to Reproduce

1. node.js環境でmisskey-jsを導入
2. Misskey.Streamを呼び出す
  - この際、従来であればWebSocketにwsパッケージのWebSocketを渡すことで一応動作していた
  - 現在は動作させられない（型エラーが起こるため）
  - 本来はコンストラクタを渡さなくてもNode環境であればwsのStreamでも動いてほしい

### Environment

* misskey-js: 2024.10.2-alpha.1
* Node: 20.5.0
* OS and Architecture Ubuntu 22.04.4 LTS on WSL2

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tai-cha** [comment]
依然動作していたのであればこのように`as unknown as globalThis.WebSocket`とすれば一応は動くのではないでしょうか？
```ts
import WebSocket from "ws";

new Mi.Stream(
	server.origin,
	{token: server.credential},
	{WebSocket: WebSocket as unknown as globalThis.WebSocket},
)
```
