### ISSUE TITLE
処理中のフォローの一覧が欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#14852]
### Summary

タイトル通りです。
処理中で止まっているフォローを一覧で確認することは出来なかったと思うので、あると良いと思います。
フォロー許可待ちも同様にあると良いかもしれませんが、そこは賛否ありそうなので要検討です。場合によっては別issueを立てます。

少し関連: #14851 

### Purpose

フォロー未達であることを忘れずに済む

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by syuilo** [comment]
フォローリクエスト一覧ページをタブに分け、受信したフォローリクエストと送信したフォローリクエストを表示できるようにし、かつアカウントの状態によらず当該ページへの動線を常に表示するようにすれば同時に https://github.com/misskey-dev/misskey/issues/12268 も解決しそう

**Comment by Sayamame-beans** [comment]
確かに
