### ISSUE TITLE
Misskey 2024.10.2-alpha.2で内部・外部の画像が表示できない

### ISSUE THREAD

**Issue by erisunaga** [syuilo/Misskey#14934]
### 💡 Summary

2024年10月にインスタンスを立てました。
当初13.13.2で立て（参考サイトがそうだったからで、深い意味はないです）、
先月？から下記不調（きっかけとかは不明、立てた当初は問題なかったです）で、
2024.10.2-alpha.2にアップデートした後も自力で対処できそうになく、こちらにあげさせていただきます。

# できないこと

- ユーザーのアイコン表示
    -  `13.13.2`のときは、猫モードだと耳が透けて見える
    - `2024.10.2-alpha.2`にしたら、元画像のざっくりした色のキャンバスで表示（画像の表示はできていない）
        - 画像のURLを叩くと404エラー（R2のアドレス） 
- 投稿画像の参照
     - リモートユーザーが投稿した画像は見れたり見れなかったり（見れない方が多い） 
     - 自分でアップした画像も404
- 新規プロフィール画像のクリップ
    - ずっとぐるぐる読み込み中
    - クリップせずにアップすることはできる

### 🥰 Expected Behavior

全ての画像が問題なく読み込める

### 🤬 Actual Behavior

ほとんどの画像が表示できない

### 💻 Frontend Environment

```markdown
* Macbook Air M1
    * OS: Sonoma 14.7 
* Browser:
    * Safari :バージョン17.6 (19618.3.11.11.5)
    * Chrome :バージョン: 130.0.6723.117（Official Build）（arm64）
* Server URL: misskey.eri-sunaga.com
* Misskey:2024.10.2-alpha.2
```

### 🛰 Backend Environment (for server admin)

```markdown
- Docker Compose: v2.29.7-desktop.1
    - Misskey: 2024.10.2-alpha.2
    - cloudflare : 2024.11.0-arm64
        - Cloudflare Tunnel
    - redis:7-alpine
    - postgres: 15-alpine
    - meilisearch:v1.1.1
- Cloudflare R2
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by fruitriin** [comment]
オブジェクトストレージかメディアプロクシの設定がおかしそう

**Comment by EriSunaga** [comment]
@fruitriin 
さっそくありがとうございます。
メディアプロキシは設定していなくて、あるとすればオブジェクトストレージとして使っているCloudflare R2かなと…
ただ、`13.13.2`のときは使っていない状態で事象が出ていたので、R2を導入してしまったことが余計に事態をややこしくしているかもしれません。。。
いったんR2を解除して、もう少しいろいろ叩いてみます。
