### ISSUE TITLE
管理任用Webhookだけじゃなくてユーザー向けWebhookの設定もテスト送信できたら便利だよね

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#14938]
### Summary

テスト送信機能ほしい

### Purpose

![Image](https://github.com/user-attachments/assets/35d53946-bdbf-4a2a-a435-f20ff7f3b8c8)
実際に飛んでくるのか来ないのかやってみないとわからないので大変なので改善されたら嬉しい

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by fruitriin** [comment]
PS. 管理画面で事前にテストできる機能は神でした

**Comment by Sayamame-beans** [comment]
Related: #14445 #14489
実装するとされているので、もしかしてUIが抜けている…? (変更内容未確認)

**Comment by fruitriin** [comment]
えっ、そうなんだ :exploding_head:

**Comment by Sayamame-beans** [comment]
@samunohito 機構的には作成してからじゃないと無理な感じでしたっけ…? (管理者側の方のときに、設定保存しなくても飛ばせられないかみたいな話をしてた気がして)

**Comment by samunohito** [comment]
@Sayamame-beans そうですね。仕組み上、1度作成いただく必要があります。
ただ、編集時は保存せずとも仮入力した状態の値で試行可能です
