### ISSUE TITLE
Bridgy FedによるBlueskey->misskey.io向けのアカウントではヘッダー画像が反映されない

### ISSUE THREAD

**Issue by sivaDog** [syuilo/Misskey#14956]
### 💡 Summary

Blueskey側のアカウントで設定したヘッダー画像が反映されない

### 🥰 Expected Behavior

Blueskey側で設定したヘッダーやアイコン画像がMisskeyに反映される

### 🤬 Actual Behavior

Bridgy Fedをつかって  
Blueskeyで作成したアカウントをMisskeyでも見えるように試した  

しかし、ヘッダー画像(バナー画像)とアカウントアイコンが正常に反映されない不具合  
- アカウントアイコン画像 : 1度Blueskey側で画像変更をすると適応できる
- ヘッダー画像 : 正常反映されない

### 📝 Steps to Reproduce

参考サイト : https://note.com/99cafe/n/nf24f95277a5c

1. Blueskeyでアカウント作成
2. Blueskey側で[Bridgy Fedのアカウント](https://bsky.app/profile/ap.brid.gy)をフォロー
3. Misskey上で「@○○○.bsky.social@bsky.brid.gy」アカウントを確認

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
triage: 以下を(誰かが)確認する必要がありそうです。
- [ ] io以外でも発生している問題であるかを確認
- [ ] Misskey以外の、Mastodon等のサービスでは問題なく反映されるか(つまり、Bridgyから来るデータにそもそもあるか否か)を確認

**Comment by Ruruke** [comment]
自鯖(mi.ruruke.moe)とpawooで確認しましたが
両方ともBlueskey側で設定したヘッダーやアイコン画像の更新が反映されてませんでしたね。
