### ISSUE TITLE
ロールによるモデレーションを強化(〇〇禁止系など)

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#14957]
### Summary

どこかにissueありそうなのですが、上手く掘り起こせないので新規で開きます。
列挙した全てが必要とは限らないので、適宜実装されていくと良いなと思います。

- ノート禁止\
  (現在はパブリック禁止のみ)
- ダイレクト投稿禁止\
  (現状ダイレクト投稿のモデレーションが出来ないので禁止機能だけあっても渋いですが、ある方が良いとは思います)
- 連合ありノート禁止\
  (内側に留める)
- 他者へのリプライ禁止\
  (無くても良さそうな気は若干しますが、今もメンション禁止は出来るので…)
- 他者へのリノート/引用禁止\
  (無くても良さそうな気は若干します。"他者への"じゃなくて良い可能性もあります。)
- リアクション禁止\
  (ハートへのfallbackもさせない)
- 画像添付禁止
- 画像アップロード禁止\
  (もしかして: ドライブ容量の欄を0MBにすると現在も実現可能?)
- ~~アクセストークンの発行数制限~~ アクセストークンを使用したリクエストの禁止\
  (上記を書きながら思いつきました。サードパーティクライアントを締め出してしまうので利用には注意が必要です。)\
  samunohitoさんからの意見を聞いて書き換え。実装するなら発行を制限するより使用を制限した方が良さそうなため。
- (追記) アクセストークンを使用した書き込み・変更の禁止\
  取得は出来るけれど、投稿は出来ない、みたいな方向もありかもしれません。

### Purpose

モデレーション強化

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by samunohito** [comment]
> - アクセストークンの発行数制限

に関連して、

- アクセストークン経由でのリクエスト許可・禁止

とかもありな気がしております

**Comment by Sayamame-beans** [comment]
あ～
例えば取得系に限るようにするとかっていうのは面白いかも
