### ISSUE TITLE
Webhookのダミーで送信されるオブジェクトの構造が実際に送信されるものと異なる

### ISSUE THREAD

**Issue by MateChan** [syuilo/Misskey#14967]
### 💡 Summary

Webhookの編集ページにあるダミー送信機能で送信されるオブジェクトの構造が、実際のイベントで送信されるものと異なります（特にnoteの位置などが問題になるかなと思います）。

### 🥰 Expected Behavior

ダミーで送信されるオブジェクトの構造が実際に送信されるものと同じになるとよいと思います。

### 🤬 Actual Behavior

noteイベントの場合、実際に送信されるものはnoteが { body: note: {} } の位置にありますが、ダミーで送信されるものはbodyそのものがnoteになっています。

他のトリガーについては確認できていませんが、同様の状態であれば同じように修正していただけるとありがたいです。

![ダミーで送信される内容](https://github.com/user-attachments/assets/c7117df5-8f59-4131-ade6-97b0873d8f7b)

![実際に送信される内容](https://github.com/user-attachments/assets/bc47a96d-5422-42c2-90ad-a572254c22dd)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: team.matechan.com
* Misskey: 2024.10.1-taiyme.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: 2024.10.1-taiyme.2
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment]
triage: #14863 で修正されている可能性

**Comment by Sayamame-beans** [comment]
よく見たら #14862 がそのものでした 🙏

**Comment by MateChan** [comment]
すみません！確認不足でした🙇
