### ISSUE TITLE
引用リノートでサーバーミュートが貫通する

### ISSUE THREAD

**Issue by painomi0587** [syuilo/Misskey#14993]
### 💡 Summary

引用元のサーバーをミュートしていても表示される

### 🥰 Expected Behavior

ミュートされているサーバーのノートが含まれる引用リノート自体が表示されない様に

### 🤬 Actual Behavior

ミュートしているサーバーのノートが引用リノートだと表示される

### 📝 Steps to Reproduce

1. サーバーAをミュート
2. フォローしているサーバーBのユーザーがサーバーAのノートを引用リノート

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Android 15; Pixel 7 Build/BP11.241025.006
* Browser:Vivaldi 7.0.3505.69
* Server URL:misskey.systems
* Misskey:2024.11.0-alpha.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Painomidayo** [comment]
024.11.0-alpha.1の環境でもう一度確認してみます

**Comment by samunohito** [comment]
2024.11.0-alphaベースのサーバ（FTT有効）で確認しましたが再現しませんでした。
ストリーミングで流れてくることも、リロード時に表示される（WebAPIのレスポンスに含まれる）こともなく…

**Comment by Painomidayo** [comment]
再度こちらでも確認してみましたが再現しませんでした。
キャッシュの都合かもしれないです

**Comment by Painomidayo** [comment]
3サーバーで再現しました。
UserA@Server1

- Server3をServerミュート
- UserBをフォロー

UserB@Server2

UserC@Server3

1. UserBがUseCを引用リノート
2. UserAのホームタイムラインに表示される

**Comment by Painomidayo** [comment]
追記します

1. UserBがUseCを引用リノート
2. UserBが「1」の投稿を自己リノート
3. UserAのホームタイムラインに表示される

**Comment by Sayamame-beans** [comment]
それはもしかすると、 #12396 と同じタイプの現象かもしれません。
現状、リノートした引用リノートには引用元の情報が(直接は)含まれていないため、引用元がミュート対象であった場合にすり抜ける事象が起きています…

**Comment by Painomidayo** [comment]
なるほど、こちらの下調べ不足でした。

**Comment by Sayamame-beans** [comment]
いえいえ、最終的には解決したい事象ではありますね…
12396の方に追記しておきます🙏
