### ISSUE TITLE
投稿検索はいつサポートされますか?

### ISSUE THREAD

**Issue by zimuyou2** [syuilo/Misskey#15019]
### Summary

投稿者さん、投稿検索はいつサポートされるのでしょうか?

### Purpose

投稿検索

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
Misskeyには検索機能が既にあります。
もう少し詳しくお聞かせ願えますか?

**Comment by zimuyou2** [comment]
> Misskeyには検索機能が既にあります。 もう少し詳しくお聞かせ願えますか?

彼は言った:投稿の検索は利用できません
![Image](https://github.com/user-attachments/assets/ac18fab8-b849-4473-a6b0-93e16243b06d)

**Comment by Sayamame-beans** [comment]
検索を行うための権限が与えられていないようです。
検索を行うための権限は、各サーバーにある"ロール"の権限設定によって決まります。
ご利用のサーバーの管理者にお問い合わせください🙏
