### ISSUE TITLE
アドレスバーに入力など直接ユーザのプロフィール画面を開くと概要タブの中身が描画されない

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#15032]
### 💡 Summary

こんな感じになります。
![Image](https://github.com/user-attachments/assets/b8037896-f60d-42d5-853e-04ce856a73e7)

コンソールを見るとエラーが出ていました。
![Image](https://github.com/user-attachments/assets/a9c7cd1e-b6d6-4be4-8f52-caaf9c4f4df7)

### 🥰 Expected Behavior

描画される

### 🤬 Actual Behavior

されない

### 📝 Steps to Reproduce

サーバに未ログイン状態でプロフィール画面を開く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): any
* Browser: any
* Server URL: any
* Misskey: 2024.11.0 (以前からかは未確認)
```

### 🛰 Backend Environment (for server admin)

```markdown
-
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by samunohito** [comment]
![Image](https://github.com/user-attachments/assets/be5807e0-6518-4bcb-80d3-5d558d832419)
赤線の部分でエラーになっています。
`messageToFollower`というキーを使っている個所は1つしかなく、そのあたりのガード処理が甘い可能性が高いです
https://github.com/misskey-dev/misskey/blob/17d9aca5a7ec6149a8dbf0c1607c81ab188e7015/packages/frontend/src/pages/user/home.vue#L50-L63

**Comment by samunohito** [comment]
![Image](https://github.com/user-attachments/assets/a6411142-8a9f-4577-a5c4-7bb30d802077)
2つ目はこのあたりで、`user.birthday.split`してるところは同様に1箇所しかなく、以下である可能性が高いです
https://github.com/misskey-dev/misskey/blob/17d9aca5a7ec6149a8dbf0c1607c81ab188e7015/packages/frontend/src/pages/user/home.vue#L297-L315

**Comment by samunohito** [comment]
2つ目は1年近くコードが変わっておらず、自分が見る限り問題もなさそうです。
1つ目により描画が止まり、それに引きずられて発生しているものと推測します。

**Comment by samunohito** [comment]
（コミットログ確認中…）

**Comment by syuilo** [comment]
🤯

**Comment by samunohito** [comment]
`packages/frontend/src/pages/user/home.vue`はUserDetailed前提なので、上記の取得処理もそれに合わせる必要がありそうです
