### ISSUE TITLE
投稿したメッセージの送信日時を変更する方法を教えてください

### ISSUE THREAD

**Issue by yuqiao9** [syuilo/Misskey#15085]
投稿したメッセージの送信日時を変更する方法を教えてください

**Comment by yuqiao9** [comment]
> 意図を詳しく教えていただけますか? (そのような機能に心当たりがないため)

2024年12月2日に投稿したメッセージがありますが、2023年1月1日のように日付を変更する方法はありますか。

**Comment by Sayamame-beans** [comment]
ないですね…
(サーバー管理者であれば、ローカルにあるデータをDBから書き換えること自体は可能だとは思いますけれど)

**Comment by yuqiao9** [comment]
> ないですね… (サーバー管理者であれば、ローカルにあるデータをDBから書き換えること自体は可能だとは思いますけれど)

はい、私は管理者ですが、データベースのどのテーブルに対応するデータを変更すべきかはわかりません

**Comment by sakuhanight** [comment]
そのような機能について想定されていないと思います。意図を詳しく教えていただけますか?
