### ISSUE TITLE
フォローリクエストページのタブ名が多言語化されていない

### ISSUE THREAD

**Issue by KisaragiEffective** [syuilo/Misskey#15167]
### 💡 Summary

SSSIA:

![Image](https://github.com/user-attachments/assets/e8edf52c-c4ba-4c14-828c-b9953c87caec)

### 🥰 Expected Behavior

多言語化されている

### 🤬 Actual Behavior

多言語化されていない

### 📝 Steps to Reproduce

1. (前提: 未処理のフォローリクエストがある)
2. 言語を日本語以外の何かしらに設定する
3. フォローリクエストのポップアップを開く

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Linux 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
* Browser: Mozilla Firefox 133.0.3
* Server URL: https://misskey.niri.la/
* Misskey: 2024.11.0-kinel.1
```

### 🛰 Backend Environment (for server admin)

```markdown
N/A (not a server admin)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
Crowdin Updatesが来てないだけ

https://github.com/misskey-dev/misskey/blob/3c81926f71f04b43455dd6a5e6302eb2c35f58ba/packages/frontend/src/pages/follow-requests.vue#L93-L103
