### ISSUE TITLE
ノートを投稿するときに追加のノートも一緒に投稿できるようにしてほしい

### ISSUE THREAD

**Issue by sorairolake** [syuilo/Misskey#15181]
### Summary

Xでは、以下の画像のようにポストに追加のポストを追加することができ、それらを一括して投稿することができます。

![Xのスクリーンショット](https://github.com/user-attachments/assets/ce077f26-a73e-465e-aa21-39ad6938cdd4)

Misskeyでもこれと同様に、ノートに追加のノートを追加することができ、それらを一括して投稿できる機能がほしいです。
Misskeyのノートは3,000文字まで対応してますが、ある話題を一つのノートではなくスレッド形式にして投稿したいときにこの機能があると便利だと思います。

また、この機能で投稿された一連のノートは可能であればXのようにスレッド形式で繋げて表示できると良いと思います。

### Purpose

スレッド形式のノートを投稿したいときの利便性の向上。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment]
duplicate of #13402
