### ISSUE TITLE
すべての言語版でRenoteの略称がRNとなってしまう

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#7795]
## 💡 Summary
そのままRe-noteとすると別の意味の言葉になってしまうためにRenoteという訳語にはしていない言語やキリル文字圏などの言語版においても略称がRenoteの頭文字二文字のRNと表示されてしまう。

## 🙂 Expected Behavior
Crowdinで言語毎に「RN」の文字列を充てられるようにする

## ☹️ Actual Behavior
Crowdinには「RN」の文字列が存在しない。ただし「Renote」はある。

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by ghost** [comment]
なぜこの内容でFeatureに付け替えられたのでしょう……現在の実装は意図された仕様になっているというわけではないと思うのですが

**Comment by tamaina** [comment]
> Crowdinで言語毎に「RN」の文字列を充てられるように

というのが開発者的に「新機能の追加」であると感じたのでFeatureに分類しました。

**Comment by ghost** [comment]
補足：
これが意図された仕様なのか疑わしいということです

**Comment by ghost** [comment]
> > Crowdinで言語毎に「RN」の文字列を充てられるように
> 
> というのが開発者的に「新機能の追加」であると感じたのでFeatureに分類しました。

そういうことならラベル両方つけてしまうというのはどうなのでしょう。

**Comment by tamaina** [comment]
> これが意図された仕様なのか

この仕様・実装は実装者(しゅいろ？)あまり考えずに実装したものであって、意図したかと聞かれると白黒はっきりと回答ができない

**Comment by tamaina** [comment]
> ラベル両方つけてしまう

それがいいかもです

**Comment by syuilo** [comment]
> Renoteという訳語にはしていない言語

RenoteはMisskey用語だからすべての言語でRenoteであってほしいけど、これあるのかな

**Comment by syuilo** [comment]
(既にRenote翻訳ファイルに含めてたからRNも追加しても良いとは思うけど)

**Comment by ghost** [comment]
> > Renoteという訳語にはしていない言語
> 
> RenoteはMisskey用語だからすべての言語でRenoteであってほしいけど、これあるのかな

・Esperanto: 私が「転送」と云う意味の言葉 Plusend をあてています（メール用語から）。
　「ノート」はそのまま（Noto）。
・French/Italia: 翻訳者が「note/noto はOKだけど Renote/Rinoto はだめ」という私と同様の見解をコメント欄に書かれています。
・Deutsch: RenoteはそのままRenoteですが、ノートはNoteではなくNotizenです。
・Czech: Přeposlat となっており、今調べたところ「再送」という意味のようです（メール用語から）。

　普通に考えて英語風の言葉は欧州では外来語ではなく自分たちの日常語です。

**Comment by ghost** [comment]
語源不明のカタカナの用語として通せるのは日本語だからですよ

**Comment by rinsuki** [comment]
ReNoteの元のRetweetはtweetが(一応元ネタはあるとはいえ)ほぼ「Twitterの投稿」を表す固有名詞として伝わるようになったのでどの言語でもなんとかなるのに対してNoteはMisskeyが独占するにはいささか一般用語すぎるのでつらいというのはある。

それはそうとして結局引用非対応実装には `引用文 RN https://misskey.example/notes/aaa` みたいな形で伝わるのは変えようがない (そこの表記を言語ごとに変えるのはいろいろな都合で現実的ではないはず) ので RN はそういうものですと言うことにしてもいいかもしれない。もしくはUIからそもそもRNは消して緑の枠だけにするとか。

(余談: なぜか Mastodon の場合ブーストされた投稿のcontentは `RT @example: 元投稿…` になる https://mstdn.rinsuki.net/api/v1/statuses/106951028320050358 )

**Comment by syuilo** [comment]
> それはそうとして結局引用非対応実装には 引用文 RN https://misskey.example/notes/aaa みたいな形で伝わるのは変えようがない (そこの表記を言語ごとに変えるのはいろいろな都合で現実的ではないはず) ので RN はそういうものですと言うことにしてもいいかもしれない。

そういえばそうだった

ので一貫性を保つためRNのままにします
かつ将来的にはUIからRNを無くすかも
