### ISSUE TITLE
501 typescript errors when attempting to build on three different systems.

### ISSUE THREAD

**Issue by knisshoku** [syuilo/Misskey#7800]
## 💡 Summary

After going through the steps in the setup guide, when trying to build misskey using NODE_ENV=production yarn build, multiple errors show (501, to be exact)

I've provided the log file below.

## 📝 Steps to Reproduce

Go through the installation process via the guide provided by misskey.

## 📌 Environment
Ubuntu 20.04 server, Debian 11, Arch Latest. Node.js 14, and PostgreSQL 13.

[log.txt](https://github.com/misskey-dev/misskey/files/7166211/log.txt)

**Comment by luka-devnull** [comment]
While working together, we went back over 6 different version tags (12.90.1, 12.90.0, 12.89.2, 12.89.1, 12.88.0, 12.85.1) on the Ubuntu container and still couldn't get it to work, but got progressively less build errors (484 was the final count)

**Comment by nullobsi** [comment]
I think these are just typescript errors. Misskey still builds and runs correctly

**Comment by knisshoku** [comment]
> I think these are just typescript errors. Misskey still builds and runs correctly

I know they're typescript errors.

I've tried building on multiple machines and it doesn't build or run correctly. This is the only thing that's showing up.

I've followed the installation guide to a T.

**Comment by okpierre** [comment]
> I've tried building on multiple machines and it doesn't build or run correctly. This is the only thing that's showing up.

This is an issue that has been present for several versions. It'll be nice to see this made priority over all new features.

> I think these are just typescript errors. Misskey still builds and runs correctly

From what I can tell it does run but it's not something new users and admin are not comfortable seeing.

**Comment by knisshoku** [comment]
> This is an issue that has been present for several versions. It'll be nice to see this made priority over all new features.

This just confuses me more then on why it's not working... I'd love to use Misskey, but I'm back on pleroma for now.

**Comment by KisaragiEffective** [comment]
triage: this does not happen in 2024.5.0.
