### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#7804]
## Summary

今更感はあるけど、開発体験向上のため

**Comment by syuilo** [comment]
Vue CLIとか使った方が良いかも

**Comment by syuilo** [comment]
webpack-dev-server を使う必要があるっぽいけど、それ使う場合はMisskeyサーバーとの兼ね合いどうするんだろうというのが

**Comment by syuilo** [comment]
こういうの使うことになりそう
https://github.com/shellscape/koa-webpack

**Comment by syuilo** [comment]
API提供サーバーとクライアント提供サーバーが同じというのが諸悪の根源(?)な気がするな

**Comment by syuilo** [comment]
ただ分離するとインスタンス運営者にサブドメインとか作ってもらう必要が生じて面倒

**Comment by rinsuki** [comment]
webpack-dev-server 普通にproxyあるよ

**Comment by syuilo** [comment]
なるほどなるほど
その場合はAPIサーバーを通常とは違うポートで立てておく感じか

**Comment by syuilo** [comment]
クライアントを読み込むためのHTMLもサーバーから返されるから、全てのリクエストをproxyする感じになりそうだけど動くのかしら

**Comment by rinsuki** [comment]
普通は動く、ws通すにはちょっと設定しないといけない

**Comment by syuilo** [comment]
viteになった

**Comment by tamaina** [comment]
現状のbuild watchだとHMR無理かも

(viteを開発サーバーモードで起動する必要があると思うんだけど、Koaに手を加える必要がありそうで面倒なのでやめた。viteの開発サーバーとrollupの動作が乖離しているし)

**Comment by syuilo** [comment]
> viteの開発サーバーとrollupの動作が乖離しているし

vite 3.0でここ改善してそう

> In v3, Vite uses esbuild to optimize dependencies by default. Doing so, it removes one of the most significant differences between dev and prod present in v2.

**Comment by syuilo** [comment]
設定のしかたがよく分からなかった

**Comment by syuilo** [comment]
```
		server: {
			hmr: true,
			base: '/',
			port: 80,
			proxy: {
				'/api': 'http://localhost:3000',
				'/': 'http://localhost:3000',
				'/streaming': {
					target: 'ws://localhost:3000',
					ws: true,
				},
			},
		},
```
って設定追加してviteサーバー起動したけどHMRされない

**Comment by syuilo** [comment]
報奨金 ¥3000

**Comment by tamaina** [comment]
くるぞ
