### ISSUE TITLE
コントロールパネルのファイル一覧を廃止

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#7812]
## Summary

活用する方法が無さそう

**Comment by tkmrgit** [comment]
誤解招きそうなので一応貼っておく。一覧を見えなくするだけで個別には変更できるようにするという認識でOK？
>めいすきーはアップロード画像の一覧部分は潰してあるのだわ
https://misskey.m544.net/notes/717bf8b5dc70c2ee569b27f8

**Comment by syuilo** [comment]
OK

**Comment by syuilo** [comment]
活用しているインスタンスもあるっぽい

**Comment by syuilo** [comment]
話を聞いた感じだと、むしろ強化していく必要ありそう

**Comment by mei23** [comment]
具体例を書かないとなんだかわからない

**Comment by tamaina** [comment]
> 強化

新しいファイルが来たらストリームで通知される機能とかほしい

**Comment by syuilo** [comment]
> 具体例を書かないとなんだかわからない

定期的にファイル一覧を確認して、児童ポルノがアップロードされているのを発見できたり

**Comment by mei23** [comment]
> 新しいファイルが来たらストリームで通知される機能とかほしい

誤送信でもなんでもいきなりモデレーター全員に通知されるのはちょっと…

> 定期的にファイル一覧を確認して、児童ポルノがアップロードされているのを発見できたり
> 新しいファイルが来たらストリームで通知される機能とかほしい

運用の話だから機能とは直接関係ないけど、結局モデレーターが全部見きれるのか微妙。

**Comment by syuilo** [comment]
> 運用の話だから機能とは直接関係ないけど、結局モデレーターが全部見きれるのか微妙。

個人的な感想だと、ローカルに限れば意外と多くない印象

特定のユーザーに絞ったり、グリッド表示したりすればより運用楽になると思う
