### ISSUE TITLE
メインTLでリストやアンテナを表示するとヘッダーがバグる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#7815]
## 💡 Summary
メインTLでリストやアンテナを表示するとヘッダーの表示がバグる  
表示されることが想定されていなさそう

## 🙂 Expected Behavior
リスト名とかが表示されるとよさそう

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/7973572/133917164-4ede022f-7aec-42b4-92ad-f0feaff95aa1.png)

## 📌 Environment
Misskey develop @ 8a0a46b

**Comment by ghost** [comment]
もう少し具体的にどうバグるのだろう…と思い手元のこモバイルブラウザで試してみたらタイムラインの名前が【ホーム】になりました。ホームタイムラインではないですね

**Comment by syuilo** [comment]
リストタイムライン個別のページにしようと思ってるからそれで解決するかも

**Comment by syuilo** [comment]
↑やった
