### ISSUE TITLE
アカウントのbotフラグはUIで操作できないように

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#7832]
## Summary
主にmisskey.ioにおいて一般ユーザーなのにbotフラグを付けているユーザーがおり、botフラグが適正運用されていない。
↓  
bot作者はAPIコンソールでプロフィールを変更できるはず  
↓  
botフラグをUIでオンにできる必要はない

**Comment by syuilo** [comment]
API叩く必要あると億劫になって利用が促進されなさそう
botフラグがオンなアカウントはUIから投稿の作成できないようにすれば良さそうと思ってる
