### ISSUE TITLE
botフラグがオンなアカウントはUIから投稿の作成ができないように

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#7833]
## Summary
See https://github.com/misskey-dev/misskey/issues/7832#issuecomment-926370623

## Reason
> 「Botが反応しないのですが」のような問い合わせが結構ある

BotはBotに返信しないようになっていることが多い（そうしないと無限に返信し続ける場合がある）

**Comment by rinsuki** [comment]
それはそれでbot障害のお知らせの時とかにめんどそう
まあrenoteすればいいか

**Comment by rinsuki** [comment]
でもrenote切ってる人とか作者ミュート／ブロックしてる人のことも考えるとrenoteで済ませるのは微妙だな

**Comment by tamaina** [comment]
ほらAPIコンソールでnotes/createすれば…(

けどbot作者は #7832 の方が楽だと思う気がするなぁ

**Comment by mei23** [comment]
サードパーティでも投稿できるしなんか微妙

そもそも
主にmisskey.ioにおいて一般ユーザーなのにbotフラグを付けているユーザーがおり、botフラグが適正運用されていない。
↓
機能を潰したり改修したりして防ごう。
が、アプローチとはしてはあっても最善の案にはならない気がする。

特定のインスタンスでどうやってもbotフラグを適正運用してもらえなくて困ってるから強制的になんとかしたい
ってレベルなら付けてみるとか、オプションで付けてみるとかみたいな感じかなと。

**Comment by EbiseLutica** [comment]
@tamaina botフラグの用途外利用による懸念点があるのであればそれを明記してほしい。個人的に、技術的に対処すべき事由とは思えないので…。

**Comment by syuilo** [comment]
> @tamaina botフラグの用途外利用による懸念点があるのであればそれを明記してほしい。個人的に、技術的に対処すべき事由とは思えないので…。

「Botが反応しないのですが」のような問い合わせが結構ある

**Comment by marihachi** [comment]
やるとしても、投稿フォームに「このアカウントはbotとして設定されています」的なメッセージを出す程度で良い気がする。
投稿できなくするのは過剰じゃないかな、botもAPI経由で投稿するわけだし。

**Comment by EbiseLutica** [comment]
(Botが反応しないのですが は作者に言えとしか)

**Comment by syuilo** [comment]
Botでのログイン時は画面に常に警告を表示するようにしたからそれで良さそう
