### ISSUE TITLE
ログインしていなくてもログイン必須のページが表示されてしまう

### ISSUE THREAD

**Issue by YuzuRyo61** [syuilo/Misskey#7836]
## 💡 Summary

ログインしていなくても、表示されるべきでないページが表示されてしまう。

※フロントエンド側の問題

## 🙂 Expected Behavior

表示されるべきではない

ログインしていないときはトップページに遷移させるべき（一例）

## ☹️ Actual Behavior

ログインしていなくても表示されてしまう

表示できたページ（一例）
- `/settings`
- `/instance` (子ページ含む)
- `/my/messages`

もちろんこれらのページはAPIで認証が必要という結果が返っている

## 📝 Steps to Reproduce

1. Misskeyインスタンスからログアウトしている状態であること
2. MisskeyインスタンスのURLに、ログインしているときは表示できるページのURLを入力(`/settings`など)

## 📌 Environment

Misskey: 12.91.0

**Comment by syuilo** [comment]
/settingsはクライアント設定も含むのでログイン必須ではない(非ログイン時にクライアント設定調整したい需要なさそうだからログイン必須でもいいかもしれないけど)

**Comment by KisaragiEffective** [comment]
triage: 以下理由により閉じます。もし残っているようであればre-openしてください。
1. `/settings` は非ログイン状態で開こうとすると認証ポップアップが出る。それを拒否するとトップページへリダイレクトされる。
2. `/instance` 及び `/my/messages` は存在しない
