### ISSUE TITLE
IPアドレスを記録する

### ISSUE THREAD

**Issue by SanMurakami** [syuilo/Misskey#7840]
## なぜ

ログイン時のIPアドレスだけだと動的IPや携帯回線などの頻繁にIPが変わる回線で追跡ができず、法的に問題のあるファイルがアップロードされた時に対応が大変になったり、十分な証拠にならない可能性があるため。

**Comment by syuilo** [comment]
いいと思うけど補足

- ログイン時のIPアドレス記録は管理者が追跡とか警察に提出する目的は想定していなくて、ユーザーがあとから不審なログインを確認するときに役立てる目的
  - だからこの機能をあまりモデレーション目的で当てにしない方が良さそう(将来的に変更される可能性がある)
- アクセスログとかIPアドレス記録はあまりMisskeyマターではないのかなとも思った

**Comment by mei23** [comment]
> アクセスログとかIPアドレス記録はあまりMisskeyマターではないのかなとも思った

これは別途取得手段があっても最終紐付けに困るので
インスタンス管理者が指定した紐付けに足る情報が取れるといいと思います。
```
Properties
(ip): Resolved IP address
(remote-addr): Original remote address
(user-id): User ID
(token): User token

HTTP headers
x-forwarded-for: Original X-Forwarded-For
cf-ray: Cloudflare Ray ID
:
```

**Comment by tamaina** [comment]
ファイルだけでなくノートやチャットについても問題になりそう

**Comment by tamaina** [comment]
> 最終紐付けに困る

(補足・確認)リバースプロキシのアクセスログの日時とファイルやノートの作成日時を照合して一対一で紐付けるのは無理があるという理解で良い？

**Comment by mei23** [comment]
> (補足・確認)リバースプロキシのアクセスログの日時とファイルやノートの作成日時を照合して一対一で紐付けるのは無理があるという理解で良い？

それ
ファイルやノートの作成なんていっぱいあるしKoaのipは偽装可能

**Comment by syuilo** [comment]
やる

**Comment by syuilo** [comment]
普通に全てのリクエストを記録してたら大変になりそうだから何か良い感じの方法を考えないと

**Comment by syuilo** [comment]
記録するのは10分に1回だけとかにする？

**Comment by tamaina** [comment]
「あるアクセストークンに対して違うIPアドレスからリクエストがあったらそれを記録する」とかでいいんじゃない？

**Comment by syuilo** [comment]
そうする

**Comment by syuilo** [comment]
記録するのはユーザーID、IPアドレス、記録日時の組で良いかしら

> Koaのipは偽装可能

というのが気になってる

あと Resolved IP address と Original remote address の違いがわからない

**Comment by tamaina** [comment]
(いいと思うけど、ユーザー削除されたらuser idとusernameの紐づけできなくない？と思った)

**Comment by mei23** [comment]
> Koaのipは偽装可能

例えば、ローカルのnginxなどを経由している場合は常にIPアドレスは 127.0.0.1 などになるはずで
この場合、リバースプロキシなどが追加したヘッダー `X-forwarded-For: <Original address>` などを参照して解決する必要がある。
Koaにはそれを解決する機能があるが、接続元アドレス (上では 127.0.0.1) が信頼されているプロキシのアドレスでなくとも X-forwarded-For を参照してしまうので、`X-forwarded-For` を付けたリクエストで偽装されてしまう可能性がある。
(今はNode.js直接アクセス出来るパターンがないから偽装は出来ない？)

**Comment by mei23** [comment]
> あと Resolved IP address と Original remote address の違いがわからない

> (ip): Resolved IP address
> (remote-addr): Original remote address

Resolved/Original という呼び方は一般的なわけじゃないかもだけど

とりあえずKoaにおいては
- remote-addr が直接接続しているPeerのアドレス (たいてい127.0.0.1とかになる)
- ip がリバースプロキシの先のアドレスを解決したもの

になってるはずだわ

**Comment by mei23** [comment]
>  (今はNode.js直接アクセス出来るパターンがないから偽装は出来ない？)

いや、Koaの仕様は見てないけど存在しないアドレスを再帰解決していく仕様だったりすると偽装できちゃうかもだわ

`X-forwarded-For: <Addr1>, <Addr2>`

**Comment by mei23** [comment]
`X-forwarded-For`とかの探索数は`app.maxIpsCount`で制御できるみたいなので設定したほうがいいかも
https://github.com/koajs/koa/blob/master/docs/api/index.md#settings

**Comment by Johann150** [comment]
In my opinion a very privacy invasive feature. It is also very problematic if it can not be turned off because IP addresses are considered personal data under GDPR.

> アクセスログとかIPアドレス記録はあまりMisskeyマターではないのかなとも思った

I think if you want to log IP addresses you should use log files of the reverse proxy you are now required to use. This means administrators should be easily able to enable/disable and otherwise configure logging (and also automatic deletion of logs, e.g. with logrotate).

**Comment by tamaina** [comment]
If you are concerned about invasion of privacy, you should create and use your own instance.

I don't think the reverse proxy logs are complete in linking users to IPs.

**Comment by Johann150** [comment]
> If you are concerned about invasion of privacy, you should create and use your own instance.

I don't think you read all I wrote: It is problematic **if it can not be turned off**. The current PR does not make it configurable.

> I don't think the reverse proxy logs are complete in linking users to IPs.

What do you mean? You can [configure e.g. nginx to log](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/) the [connecting IP address](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_addr) and other things if you want. And if nginx does not know the correct IP, Misskey will not be able to know the IP either.
Of course another issue is that Misskey uses a non-standard authentication mechanism, but I think Misskey clients will connect to `/streaming?i=<token>&_t=...` which you could use for tracking.

**Comment by tamaina** [comment]
I am not positive about making IP registration optional, as it will only bring criticism to the instance administrator who enables it.

In cases where new registrations are restricted, it might be nice to have an option to disable IP records.

**Comment by Johann150** [comment]
Let me reiterate: IP addresses are considered personal data under GDPR. This means that administrators would be responsible for potentially unlawfully processing personal data, which I am not comfortable with.

> I am not positive about making IP registration optional, as it will only bring criticism to the instance administrator who enables it.

If an administrator enables it, they would have to disclose that they are processing personal data (IP addresses) because of GDPR. And if the administrator is unable to turn it off, what should they do?

**Comment by Johann150** [comment]
Even beyond that, logging IP addresses does not make too much sense. People may share IPv4 addresses with others due to NAT or CGNAT. IP addresses are often dynamic. People can use VPNs/Proxies/Tor/etc. So I think logging or blocking based on IP does not make much sense.

**Comment by mei23** [comment]
> 普通に全てのリクエストを記録してたら大変になりそうだから何か良い感じの方法を考えないと
> 記録するのは10分に1回だけとかにする？
> 「あるアクセストークンに対して違うIPアドレスからリクエストがあったらそれを記録する」とかでいいんじゃない？

本来モデレーションに必要なのは、特定投稿やファイルに紐づくリクエスト情報だと思われ

モデレーターがIPアドレスのログを確認して紐づけなければならないのは、不便なばかりでなく
ユーザーがいつどこからアクセスしたといった、モデレーションには不要なセンシティな情報を得てしまうことになるので非常に不味いと思います。

**Comment by syuilo** [comment]
> ユーザーがいつどこからアクセスしたといった、モデレーションには不要なセンシティな情報を得てしまう

これはどうやっても回避できない気がしたけど良い方法あるかしら

**Comment by mei23** [comment]
普通にNoteやDriveFileに紐づければいいのではと思うのだわ

**Comment by syuilo** [comment]
IPアドレスカラムを追加するみたいな感じ？

**Comment by tamaina** [comment]
It seems inconsistent to treat meaningless data as personal information (although it's pointless for me to point that out to you here).

**Comment by mei23** [comment]
> IPアドレスカラムを追加するみたいな感じ？

まあIPアドレスだけならそれでもいいかもだけど

そもそもIPアドレスだけ取得しても、不正確だったり役に立たなかったりするので
管理者の設定でカスタムヘッダーなんかが保存できるといいのではとも思うのだわ。

**Comment by syuilo** [comment]
ふむむ
投稿やファイルと紐付けることでなぜ

> ユーザーがいつどこからアクセスしたといった、モデレーションには不要なセンシティな情報を得てしまう

が回避できることになるかがよくわかってない

あと紐付ける方法だと
- 最終的にはユーザーが作成するコンテンツのテーブル全てにそういうカラムを追加しないといけない？
- テーブルのサイズが大きくなりそう？

という懸念があるわね

**Comment by mei23** [comment]
というか、どういう情報を取得すればモデレーションに役に立つかなんてインスタンスによって違うから
すんなりこの仕様がいいって言えるものでもない気がするわ

**Comment by syuilo** [comment]
ユーザーのIPアドレスが見れるようにしてほしいという要望を多くもらうけどそれをどのように役立てるのかはよく聞いてないわね

**Comment by mei23** [comment]
> 最終的にはユーザーが作成するコンテンツのテーブル全てにそういうカラムを追加しないといけない？

そう → たしかにめんどい → でもそれがないとモデレーターがめんどくさい紐づけを行うことになるだけ

て思うのだわ

**Comment by tamaina** [comment]
> 法的に問題のあるファイルがアップロードされた時に対応が大変になったり、十分な証拠にならない可能性がある

①発信者情報開示請求に答えるため

あと考えられるのは

②IP BANできる

ぐらいだと思う

**Comment by tamaina** [comment]
I wonder if IP addresses are ever required to take judicial action abroad outside Japan.

**Comment by tamaina** [comment]
[発信者情報開示に関する諸外国の制度について]  
https://www.soumu.go.jp/main_content/000726380.pdf

**Comment by tamaina** [comment]
I believe IP addresses should be recorded to prevent defamatory statements. This is more important than privacy.

However, Misskey should be made as GDPR compliant as possible.

**Comment by tamaina** [comment]
まあでもoptionalでいいか

**Comment by syuilo** [comment]
とりあえず(現在実装している)UserIpsテーブル+ファイルなどの特に重要度が高そうなコンテンツについては個別にIP(+ヘッダー)を保存するようにするのでどうかしら
ファイルならそんな頻繁に作成されるものじゃないから追加でリクエストヘッダー保存するようにしても負担はそこまで大きくならなそうだし

**Comment by ThatOneCalculator** [comment]
> However, Misskey should be made as GDPR compliant as possible.

Mastodon is also GDPR compliant iirc and they store IP addresses and let admins see them, so it *should* be fine.

**Comment by 4ioskd** [comment]
ふと疑問に思ったのですが、、
もしユーザーのIPアドレスを記録して第三者に流すことを目的とした、登録開放型のMisskeyインスタンスが現れたらどうしましょうか。

**Comment by syuilo** [comment]
注意喚起するくらいかしらね
あるインスタンスを信頼して利用するというのはユーザーの責任だと思われる
運営者に悪意があればIPアドレスに限らずプライベートなメッセージを閲覧したりメールアドレスを悪用したりとかいくらでもできる

**Comment by tamaina** [comment]
> もしユーザーのIPアドレスを記録して第三者に流すことを目的とした、登録開放型のMisskeyインスタンス

これはMisskeyの実装あるないに関わらずできるし……（簡単になることは確かだけど）

**Comment by 4ioskd** [comment]
>注意喚起するくらいかしらね

うーん、、注意喚起。ただFediverseではご存知の通り、情報の拡散性が低く（Twitterのように拡散されない）、MisskeyだけでなくマストドンやPleromaなどの他のFediソフトウェアのインスタンスやユーザーに広く、かつすぐに周知させることはかなり難しい。その悪意あるインスタンスの主言語が日本語でも、外国語だったとしても。

>これはMisskeyの実装あるないに関わらずできるし……（簡単になることは確かだけど）

そう。Misskeyの実装あるないに関わらずできるのだけど、そういったことをする敷居が低くなってしまう。私は悪意あるインスタンス管理者の責任はもちろんとして、この機能を開発した人やその開発に関係した人が責任を問われないか不安を覚えざるをえない。

**Comment by rinsuki** [comment]
そもそもそんなにIPアドレス知られたくない人はTorとかなんか適当な串でも刺しとくべきで自己責任では

**Comment by Johann150** [comment]
> そもそもそんなにIPアドレス知られたくない人はTorとかなんか適当な串でも刺しとくべきで自己責任では

Once again one of the reasons why I think it does not make much sense to log IP addresses in the first place.

**Comment by syuilo** [comment]
I don't know if it actually helps or not, but police will ask you to submit an IP address.

**Comment by rinsuki** [comment]
Tor or even some proxies are *might be* works for hides raw IP address, but it isn't reason for not saving IP address, since some peoples are still posting shitty illegal things without any proxies. court/police sometimes requests their IP address to server admins, and (depends on country/laws though) server admins are need to provide IP address.
