### ISSUE TITLE
二段階認証設定時にQRコードの他に秘密鍵を表示する

### ISSUE THREAD

**Issue by argxentakato** [syuilo/Misskey#7846]
## Summary
[現状では二段階認証のセットアップ時にはQRコードしか表示されない。デスクトップで動作する認証アプリ (Bitwardenとか) のセットアップ時に不便なので秘密鍵を表示するべき。

![image](https://user-images.githubusercontent.com/14871483/134917568-782c88b6-e3dc-4efb-9d00-396986be3194.png)

**Comment by tamaina** [comment]
Duplicate of #7253

**Comment by tamaina** [comment]
#7261 をreopenするつもりでこちらをreopenしてしまった
