### ISSUE TITLE
Problems with running the instance after an update

### ISSUE THREAD

**Issue by MoeruIshiki** [syuilo/Misskey#7847]
I apologize if this is a silly question, but after upgrading Misskey to version 12.91.0, my instance stopped working, giving a "502 Bad Gateway nginx/1.18.0 (Ubuntu)" error. My configs didn't change in any way, and the status of misskey and nginx in systemd are active. I tried looking at the /var/log/nginx/error.log file, it contains a lot of errors like this:

`2021/09/27 19:28:25 [error] 3681113#3681113: *353 connect() failed (111: Connection refused) while connecting to upstream, client: 95.000.00.000, server: misskey.example.com, request: "POST /inbox HTTP/1.1", upstream: "http://127.0.0.1:3000/inbox", host: "misskey.example.com"`

But I don't understand what the problem is... Tell me if I am doing something wrong. Thank you.

**Comment by MoeruIshiki** [comment]
For some reason I could not find a similar error the first time, but after some searching I tried "npm rebuild" and everything worked again. My bad.

**Comment by ghost** [comment]
I am also having this issue and running `npm rebuild` did nothing to help.
