### ISSUE TITLE
ユーザープロフィールの串焼きアイコンの数が多すぎる

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#7848]
## 💡 Summary
現状では2つある意味がない。
![IMG_20210928_191903](https://user-images.githubusercontent.com/89968079/135069290-7829e977-f348-48fc-9f62-a2d819749b26.jpg)

## 🙂 Expected Behavior
1つに統合する

## ☹️ Actual Behavior
片方のメニューにある項目は「共有」の1つだけ。

**Comment by zyoshoka** [comment]
現在ではヘッダーに当該アイコンが無くなっていますのでクローズします🙏
