### ISSUE TITLE
他鯖のアカウントでリモートフォローするためのUIを設置する

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#7849]
## Summary
ActivityPub 形式のURI（@ユーザー名@ドメイン名）を渡すことで他鯖のアカウントがそのユーザーをリモートフォローすることのできるフォームを各ユーザープロフィールに表示する。

**Comment by ghost** [comment]
今までに誰も気づかなかったのが不思議

**Comment by syuilo** [comment]
duplicate of https://github.com/misskey-dev/misskey/issues/2518

**Comment by ghost** [comment]
なぜやらない。その指摘も遅すぎる

**Comment by syuilo** [comment]
あまりIssue確認する時間が取れず
