### ISSUE TITLE
nesting <small> makes text unreadable

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#7852]
## 💡 Summary

If the MFM `<small>` is nested multiple times, each level reduces the `opacity`. If combined with `$[x4 ]` the text size is readable, but the opacity is not visible.

related to misskey-dev/mfm.js#56

## 🙂 Expected Behavior

Nesting `<small>` reduces the opacity only once.
![image](https://user-images.githubusercontent.com/20990607/135253421-3c339247-0933-478b-ac97-5a9041b914cb.png)

## ☹️ Actual Behavior

Opacity is reduced every time.
![image](https://user-images.githubusercontent.com/20990607/135253490-0527ecd3-5bc4-44b1-a526-fe15a2e22498.png)
https://mk.catgirlsfor.science/notes/8r8x8bje0z

## 📝 Steps to Reproduce

Use MFM
```
$[x4 <small><small><small><small><small><small><small><small><small>You Lost the Game</small></small></small></small></small></small></small></small></small>]
```

## 📌 Environment

Misskey 12.91.0 and earlier

**Comment by Johann150** [comment]
I think a possible solution would be to change `src/client/components/mfm.ts` to make `small` tag use a CSS class and add some selector like this:
```
.mfm-small {
    opacity: 0.7;
}

.mfm-small .mfm-small {
    opacity: initial;
}
```

**Comment by syuilo** [comment]
そのように過剰にsmallタグをネストする場合は、(ジョーク的に)テキストを読めなくすることを目的としていると思うので、特に問題は無いと思います。
