### ISSUE TITLE
prelude/urlでquerystringを使用しているがブラウザには存在しない

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#7854]
## Summary
[prelude/url](https://github.com/misskey-dev/misskey/blob/414f1d11582510f77ea3a927053fe68fa160278b/src/prelude/url.ts#L1)で`querystring`をimportしているが、本来Nodeにしか存在しないはずなので
ブラウザから使われた場合は、たまたま依存関係で読み込まれた https://www.npmjs.com/package/querystring が使われているに過ぎないみたい 。(Webpack v4の時はたぶんpolyfillだった)
少なくとも明示的にdependenciesに入れるか、別の物を使用するようにする。

**Comment by rinsuki** [comment]
URLSearchParamsとかでよさそう

**Comment by mei23** [comment]
エスケープしないとダメ
