### ISSUE TITLE
外部サービス連携のアカウントのプロフィール掲載を復活してほしい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#7862]
## Summary
v10にはあったけど、v11か12で消えた。#7818 を実装することを考えたとき、掲載するかどうか選べると嬉しい。

**Comment by syuilo** [comment]
連合どうするか考えないといけないな

**Comment by rinsuki** [comment]
連合は適当に補足情報フィールド(名前忘れた)に入れとけばよさそう

**Comment by syuilo** [comment]
補足情報フィールドは相手によっては4つくらいまでしか設定できなかった気がする
そうだとするとgithub, twitter, discord連携すると残り一つしかなくなる

**Comment by syuilo** [comment]
たしかそれが理由で廃止した

**Comment by rinsuki** [comment]
MastodonはUI上は4つしか設定できないけど連合からの分は無制限だった気がする

**Comment by ThatOneCalculator** [comment]
Since the additional field limit is now 16, bumping this issue

**Comment by ThatOneCalculator** [comment]
Maybe it could appear with the location/birthday instead?

(mockup) 
![image](https://user-images.githubusercontent.com/44733677/155866356-ee832f21-c577-45ef-99d2-89c55731a693.png)

**Comment by tamaina** [comment]
#7300 でwontfixになってるのに気づいたけど、

> FYI:  
> Some people don't want their linked services to be public, so each service will need to have a "Show in profile" option when implementing this.  
> https://github.com/misskey-dev/misskey/issues/7300#issuecomment-797497621

と言っているので公開するかどうか選べればいいよね
私も隠したい需要があることは理解してる  

（最初にも言ったけど #7818 を実装する場合は明らかに公開出来たほうが良い

**Comment by ThatOneCalculator** [comment]
Yes, I think if it's ***opt-in*** specifically that'd be a good approach.

**Comment by futchitwo** [comment]
外部連携は廃止されました
