### ISSUE TITLE
pgpool-IIのオンメモリクエリキャッシュ使うとクエリ結果が古いままになる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#7864]
> v11の時から投稿とかDBからのデータ取得方法変わってると思うんだけど、pgpool-IIのオンメモリクエリキャッシュ使うと色々ぶっ壊れるっぽい
> 
> オンメモリクエリキャッシュはデータが更新されると自動的にキャッシュが破棄されるようになってるんだけど、それが上手く動かないクエリの投げ方（つまり投げ方を間違えている）をしている気がする

**Comment by syuilo** [comment]
データ取得方法変えたっけな

**Comment by syuilo** [comment]
思い当たるとしたら個別にfindしてたのを結合を使ったクエリにして一回で済ますようにしたとか

**Comment by syuilo** [comment]
> ちなみにオンメモリクエリキャッシュ（configで言う `memory_cache_enabled ` ）はダメだけどクエリキャッシュ（configで言う `enable_query_cache` ）は大丈夫
> 
> ただしクエリキャッシュはかなり弱いのと、既に非推奨で近い将来削除されることになっている

**Comment by syuilo** [comment]
エラーが出るわけではないみたい

**Comment by syuilo** [comment]
リロードするとタイムラインに投稿したものが消えたりするけど、ノート個別ページに行けば見れるから、やっぱり結合クエリが原因の可能性はある
ただそうだとしても結合禁止というのもPostgreSQL使うメリットが減るからやりたくない
キャッシュしている状態で結合をすると結果がおかしくなるというのはPostgreSQLの問題な気もする

**Comment by syuilo** [comment]
そもそもキャッシュする必要あるのかな
タイムラインとかで言えばほとんどの場合クエリするたびに結果は変わるしキャッシュの恩恵を受けにくそう

**Comment by syuilo** [comment]
あー、タイムラインは普通にnoteテーブル見るだけだから結合関係ないかも

**Comment by syuilo** [comment]
クエリキャッシュの説明を調べると、
> テーブルに INSERT/UPDATE/DELETE/TRUNCATE があったとき、DROP TABLE されたとき、 そのテーブルのキャッシュをすべて削除します。

ってのがあるけど、この説明通りなら普通に動く気がするけどな

**Comment by syuilo** [comment]
言えることは、少なくともNoteテーブルに対するキャッシュはほぼ無意味(頻繁に更新されるテーブルなのでキャッシュしても意味がない)そう

**Comment by syuilo** [comment]
あんまりMisskeyでキャッシュが有効に活用できるテーブルないんじゃないかしら
更新の頻度が低いようなテーブルならキャッシュの意味があるけど、そういうテーブルはそもそもキャッシュ無しでも高速にクエリできる場合が多そう

**Comment by syuilo** [comment]
あと調べるとキャッシュ有効だとSelectクエリの結果が必ずしも正しいとは限らないみたいな記述:
> キャッシュされると都合の悪い SELECT がキャッシュされていることはないでしょうか？ もし、特定の SELECT だけキャッシュしたくない、という場合には、 文頭に「/* NO QUERY CACHE */」をつけることで 除外されるようになります。

もあったからやっぱり銀の弾丸ではなさそう

**Comment by mei23** [comment]
https://www.pgpool.net/docs/pgpool-II-3.2.16/doc/pgpool-ja.html#memqcache
> オンメモリクエリキャッシュの制限事項
>
> オンメモリクエリキャッシュでは、テーブルに変更があると、関連するキャッシュを自動的に削除して古いデータが返却されないようにする機能があります。 このため、pgpoolは常にUPDATEやINSERTやALTER TABLEなどのコマンドが発行されたかどうかをモニタしています。 しかし、トリガ、外部キーやDROP TABLE CASCADEなどの働きによって暗黙的にテーブルが更新されたことはpgpool-IIからはわからないため、この機能が働きません。 この問題を回避するためには、memqcache_expireを使って一定時間経過したキャッシュを削除するようにするか、black_memqcache_table_listを使って、該当テーブルがキャッシュされないようにしてください。
>
> 複数のpgpool-IIを動かす環境で共有メモリを使ったオンメモリクエリキャッシュを使用すると、あるpgpool-II経由でテーブルが更新された時に、他のpgpool-IIのキャッシュが削除されず、古いデータを読みだしてしまうことがあります。 このような環境では、キャッシュストレージにmemcachedを使ってください。

**Comment by syuilo** [comment]
ノート投稿ではCASCADEとか関係ないからタイムライン更新されない問題は

> 複数のpgpool-IIを動かす環境で共有メモリを使ったオンメモリクエリキャッシュを使用すると、

の方かな

ただCASCADEも他の箇所では使ってるから

> しかし、トリガ、外部キーやDROP TABLE CASCADEなどの働きによって暗黙的にテーブルが更新されたことはpgpool-IIからはわからないため

の方もいずれ(というかもう？)問題になりそう

**Comment by mei23** [comment]
>> 複数のpgpool-IIを動かす環境で共有メモリを使ったオンメモリクエリキャッシュを使用すると、
>
> の方かな

たぶん

**Comment by syuilo** [comment]
pgpool-IIを複数動かしてはないっぽい

**Comment by mei23** [comment]
> pgpool-IIを複数動かしてはないっぽい

pgpoolを通らないところで書き込みが発生するとNGだから、どこかにスルーして書き込み出来ちゃうフローがあるとか。
あと、Misskey自体あんまりがっつりテーブル間でトランザクション組んでないからどこかに抜けがあるとか。

**Comment by SanMurakami** [comment]
ちなみにこれまだ直ってない

**Comment by syuilo** [comment]
レプリケーション対応したためpgpoolを使う必要がなくなった
