### ISSUE TITLE
モデレーターからブロックできない

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#7868]
## 💡 Summary

8e2be5e のcommitでモデレーターをブロックできなくなったが、実際は
非モデレーターは誰でもブロックできるけど、モデレーターからは誰もブロックできない

## 🙂 Expected Behavior

非モデレーターはモデレーターをブロックできない
モデレーターからは誰でもブロックできる

## ☹️ Actual Behavior

非モデレーターは誰でもブロックできる
モデレーターからは誰もブロックできない

## 📝 Steps to Reproduce

1.非モデレーターがモデレーターをブロックする
2.できる

1.モデレーターが誰かをブロックする
2.Cannot block a moderator or an admin.

## 📌 Environment

3dc70f9878385ce34c3d4f8ae35006fbe690f8d2

**Comment by syuilo** [comment]
コード見る限り問題なさそう
謎

**Comment by syuilo** [comment]
あれ、ローカルでも期待通りに動いた

**Comment by syuilo** [comment]
misskey.ioでは再現した

**Comment by syuilo** [comment]
あー、このコミット時点では確かにバグあるね
https://github.com/misskey-dev/misskey/commit/ba6959b8c1c4faafccdeb0f76eb26fc29e02af2d

でもこのコミットで直った
https://github.com/misskey-dev/misskey/commit/8e2be5e9a7c9a851bcdbbd77bf079a40ead598dc

**Comment by tamaina** [comment]
同じコミットじゃね？

**Comment by syuilo** [comment]
あーミス
最初の方は
https://github.com/misskey-dev/misskey/commit/ba6959b8c1c4faafccdeb0f76eb26fc29e02af2d

**Comment by tamaina** [comment]
でも @kabo2468 さんが最初に提示したEnvironmentは3dc70f9で、それには8e2be5eも含まれているはず

**Comment by syuilo** [comment]
ふーむ
こっちでは再現しないんだよな

**Comment by tamaina** [comment]
（Environment間違ってる説があるけど、わざわざコミットID書いてあるし疑問を挟むのはちょっと違うかなって思って言わなかった）

**Comment by syuilo** [comment]
最新のコミットで再度確認してもらうのが良さそう

**Comment by kabo2468** [comment]
Environmentが間違ってました
ioが 8e2be5e もマージしてると思ったらしてませんでした
https://github.com/MisskeyIO/misskey/releases/tag/v12.91.1-6
