### ISSUE TITLE
Assistance required with federated user profiles

### ISSUE THREAD

**Issue by AMoonRabbit** [syuilo/Misskey#7869]
I'll preface this with that this is not urgent or critical. My instance is only a single user instance whilst I play about with things.

Problem: following attempts to resolve federation issues with remote instances, I cleared the user_profile table but managed to resurrect my profile. So that's fine. The issue is that remote users my server knows, do not have working profiles on my instance. This also means that the ability to follow is broken too. 

Unfortunately, being inexperienced with anything like this, and mad, I do not have backups.

What I think I need is to clear something which will then force the server to re-populate the user_profile table and that would then resolve this issue. I have not, however, found out how to do this.

Misskey instance: misskey.amoonrabbit.reisen
Version: 12.91.0
Install type: Docker container

Bonus issue:

Since a day or two to downtime on my instance, it has stopped sending notes to remote instances. My profile on remote instances are out of date, but if someone unfollows and refollows, they then see new notes. Notes that mention users will still go through. 

I've had this before with pleroma, and the resolution was to clear the instance table in the database but that was more the server being on during the ISP outage so my instance marked all remote instances as unreachable. This time, the instance was off, so it's likely the remote instances have decided my instance is unreachable instead. Any quick fix?

Sorry it's a bit of a mess, but I am actually learning stuff through these issues.

**Comment by AMoonRabbit** [comment]
So with the profile issue, I can use the following to manually re-add profile ID's and profiles will then be accessible again
![image](https://user-images.githubusercontent.com/3766988/137552499-525be9e9-471e-44eb-a211-b6752cbfd191.png)
However, my method of obtaining the IDs is far from efficient. I have to watch the logs and visit known broken profiles, pause the logging and copy out the ID's. 

Is there a way to scrape ID's from the following log messages like below?
```
ERR  1	[api]	Internal error occurred in users/show: Could not find any entity of type "UserProfile" matching: "8m14hor9zr"
```

**Comment by AMoonRabbit** [comment]
Okay, so a friend has helped out with pulling the ID's caught in the errors from the logs using the following command:
```
docker logs <containername> 2>&1| grep "users/show" | awk -F'[""]' '{print $4}' > /tmp/my_log
```
With the above, this exports just the ID's it captures from the available logs. Granted it won't be everything, only what has been reported, but it still gives me something to work off. 

I have then used the database `INSERT INTO` command to bulk add the missing ID's I have discovered. 

Still not there yet as I'd like to see if there is some way at least of having the instance self repair.

**Comment by tamaina** [comment]
To manually delete the user_profile table is to irreversibly destroy the database.  
There is no way to recover it except by restoring a backup.

**Comment by syuilo** [comment]
Thank you, Issue is used for bug reports and feature requests. Please use Discord or Forum to discuss any troubles 🙏

**Comment by AMoonRabbit** [comment]
Ah okay, sorry Syuilo
