### ISSUE TITLE
[MFM] 関数が存在しないときの表示方法

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#7874]
## Summary
現状で、例えば`$[honi text]`と入力すると`[honi text]`と表記される。
しかし、これは旧構文の表記なので改善したい。

改善方法として2パターンある。
1. 単純に新構文にアップデートする
メリット：構文の入力ミスがわかりやすい（`$[honi text]`→`$[honi text]`）
デメリット：独自カスタマイズのMFMや新しいMFMがそのまま表示されてしまう

2. 関数の中身のみ表示する（`$[honi text]`→`text`）
メリット：対応していないMFMでも美しく表示できる
デメリット：バグがあった場合、入力ミスと区別がつきにくい

## 該当箇所
https://github.com/misskey-dev/misskey/blob/7974dbf4778c022747a34bff9189d03393bf0c4e/src/client/components/mfm.ts#L188

**Comment by syuilo** [comment]
> 独自カスタマイズのMFMや新しいMFM

これが来ることってまずなさそうと思った

**Comment by syuilo** [comment]
いやそんなことないか

**Comment by futchitwo** [comment]
> 独自カスタマイズ

例えばGroundpolisには`$[rotate honi]`が、めいすきーには`[rgbshift honi]`が存在する

>新しいMFM

$[sparkle debobigego]は少し古いと表示できない
将来的に新しいMFM関数が追加される可能性がある

**Comment by EbiseLutica** [comment]
マストドンなどの非MFM環境ではプレーンテキストにサニタイズされることを加味すると、プレーンテキスト化してほしい気持ちはあります

**Comment by Johann150** [comment]
> 2. 関数の中身のみ表示する（`$[honi text]`→`text`）
> メリット：対応していないMFMでも美しく表示できる

👎 sometimes people that are not using Misskey accidentally use MFM syntax (this was especially commmon with the old syntax that did not use the dollar sign). in this case important text could be removed

**Comment by syuilo** [comment]
> 👎 sometimes people that are not using Misskey accidentally use MFM syntax (this was especially commmon with the old syntax that did not use the dollar sign). in this case important text could be removed

たしかにそのデメリットはありますが、MFMとして意図されていない`$[foo bar]`形式の文字列が来ることはほぼ考えられないと思うので、無視できるデメリットかとは思います

**Comment by Johann150** [comment]
🤔 maybe text from SNS that are not Misskey should never be treated as MFM. but that is probably complicated and could easily break.

**Comment by EbiseLutica** [comment]
非MFM文字列をMFMとして解釈してしまうこと自体が問題であるため、それをデメリットと挙げるのは違うと思う

**Comment by syuilo** [comment]
2 でいくか

**Comment by tamaina** [comment]
> たしかにそのデメリットはありますが、MFMとして意図されていない$[foo bar]形式の文字列が来ることはほぼ考えられない

私はそうは思わないけど  
(今存在しなくても似た構文使う言語が世の中にできる可能性はゼロではない気がする

**Comment by tamaina** [comment]
構文がシンプルなMFMの場合はそこまで汚いと思わないので、1で表示するのが無難だと私は思います

**Comment by syuilo** [comment]
1でいくか

**Comment by mei23** [comment]
`[]`構文がない今、`$[]` → `[]` に変換してしまうのはただのバグだと思うので、とりあえずまず`$[]`にするようになおすべき。
フォールバックの方法はまた検討 (それがここのFeatureなんだけど) って思うのだわ。

**Comment by tamaina** [comment]
（自分で言っといてなんだけど、同じ構文の別の言語を食った場合の解釈云々、関係あるように見えて関係ない感じが。「MFMにその構文名がない」のはあまり問題にならないが、「同じ構文名で違う意味付け」の場合はどうなるって話になる…  
根本的な解決をするには*これはMFMですよ～*とわかりやすくする識別子が必要かも。(`$[mfm 内容]`構文とか？)  
とりあえず私は1派（表示されていてもあまり汚いとは思わないので））

**Comment by syuilo** [comment]
同じ構文の別の言語の場合は、多分MastodonのようにHTMLで送ってくるだろうから問題にはならなそう

**Comment by EbiseLutica** [comment]
1で行っちゃっていいの？存在するかもわからないケースと、下の画像のようなケースを天秤にかけたら2のほうが良いと思うけど...
<img src="https://user-images.githubusercontent.com/7106976/137615187-14d5f65d-f34e-4310-876c-b26cd96a7cdc.png" height="180"/>

**Comment by tamaina** [comment]
1で良いと思う

**Comment by marihachi** [comment]
1かなあと思う
特別な意味がない場合は元のテキストにフォールバックするほうが自然

**Comment by EbiseLutica** [comment]
確かにWikiなんかは普通そうだから、自然なのはわかる

**Comment by mei23** [comment]
バグ修正 vs 機能改善 の選択肢になってるからまとまらない

**Comment by marihachi** [comment]
これそもそも前からバグってる
- #7460

**Comment by marihachi** [comment]
それがMFM関数であるかどうかは実際には分からない。
使用できる関数であればMFM関数として解釈して、それ以外の場合は関数として扱わない方が無難かも。

基本的に、構文の適用は最小限に抑えたい

**Comment by futchitwo** [comment]
もし元のテキストを保持したくて1にするなら、#7882 を取り込んだ方がいい
現状のやり方だと`$[honi.funi momi]`とかが`$[honi momi]`になってしまう
ということに気づきました

**Comment by futchitwo** [comment]
とりあえず1になったので、2にしたいときは新issueを立ててください
