### ISSUE TITLE
Logs page needs edits

### ISSUE THREAD

**Issue by okpierre** [syuilo/Misskey#7878]
## 💡 Summary

Log page needs some edits - will submit PR

## 🙂 Expected Behavior

Log page matches other page format

## ☹️ Actual Behavior

Page requires some edits

## 📝 Steps to Reproduce

1. Login as admin
2. View instance > Logs

## 📌 Environment

Misskey 12.92.0

**Comment by okpierre** [comment]
## added photo to better explain issues @syuilo 

![misskeylogsissue](https://user-images.githubusercontent.com/1679025/137613759-09c3f7a8-4d4f-4c4f-b74f-66d8fbb886b0.png)

**Comment by scottAnselmo** [comment]
@okpierre  Where is this 'Logs' page? I'm not seeing anything under 'Control Panel' that references logs. Trying to find logs to work an S3 initial setup issue. Running 12.100.1.

**Comment by okpierre** [comment]
@sanecito log page was removed. Try your server syslog instead.
