### ISSUE TITLE
ユーザーのサジェスト順の改善

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#7880]
## Summary
`@username`のサジェスト (API: `users/search`) は、「ローカルの前方一致のアクティブ順, なければ リモート前方一致のアクティブ順」で返るようになっているが
- 常にローカルが優先されるので、ローカルユーザーが非アクティブでも上に来てしまう。
- usernameが短いユーザーが、そのusernameで始まる他のユーザーのせいで下に行ったり出てこなかったりする。
- 前方一致のアクティブ順は、実際に見てみると探しづらい気がする。
  (探しているものが一覧にあるかを見て探す際に、ワード順ならばseek的なことができるが、アクティブ順だと全件scan的な感じになる。)

といった問題があるので改善したい。

例えば「ローカル/リモート問わず完全一致のアクティブ順, ローカル/リモート問わず前方一致のワード順」にするなど。

あと、API: `users/search` には `offset` があるが完全には機能しなそう。
APIでは、完全一致/前方一致, ～順, ローカル/リモート/両方 などを選べるようにしてマージは行わないようにして
マージはクライアント側で行うとかするなど？
https://github.com/misskey-dev/misskey/blob/0c21ae226bdf8d904a8736f11ef339bdb9aaa137/src/server/api/endpoints/users/search.ts#L54-L75

Related: https://github.com/misskey-dev/misskey/issues/7877

**Comment by syuilo** [comment]
> APIでは、完全一致/前方一致, ～順, ローカル/リモート/両方 などを選べるようにしてマージは行わないようにして

今ちょうど手元でそんな感じの実装書いてた

**Comment by mei23** [comment]
API [users](https://github.com/misskey-dev/misskey/blob/0c21ae226bdf8d904a8736f11ef339bdb9aaa137/src/server/api/endpoints/users.ts) に
- username完全一致フィルタ/username前方一致フィルタ
- usernameソート

とか追加しちゃえばいいのかなとか思ってた。

**Comment by syuilo** [comment]
とりあえず書いてたやつコミット
https://github.com/misskey-dev/misskey/commit/dec69cc67b060eec244eb8d2df7dcd362359514b

ローカル/リモート/両方 選べるようにしてる

**Comment by syuilo** [comment]
あとしばらく使われてないアカウントは除外するようにしてある

**Comment by syuilo** [comment]
ただ前方一致のアクティブ順ということにまだ変わりない

**Comment by mei23** [comment]
やっぱり、完全一致はほしいかも。

揺れてるのが気になる
API `users/search`: `scope: local/remote/both`
API `users`: `origin: local/remote/combined`

ローカルだけlastActiveDateで切るのっている？
ローカル/リモートを同一条件でクエリした時点で十分であえてローカルを弱くする必要くない？
確かにローカルは補足されやすいけど、ローカル/リモート共にupdatedAtでソートすれば公平に並んだりしない？
ってのがあるのだわ。

**Comment by syuilo** [comment]
> 揺れてるのが気になる

直す🙏

> ローカルだけlastActiveDateで切るのっている？

明らかに使われていないアカウントは除外した方が良いと思った

**Comment by syuilo** [comment]
ローカル/リモート共にupdatedAtでソート かつ updatedAt が一定以上古い(1か月とか)ものは除外するとかで良いか

**Comment by syuilo** [comment]
完全一致はオートコンプリート的な使い方においてはあまり意味無くなっちゃうから、クライアントからは使うことないかもしれないけどオプションとして実装しておくかしら

**Comment by syuilo** [comment]
最初に完全一致で検索して、limitに達しなかったら前方一致で埋めるとか

**Comment by mei23** [comment]
lastActiveDateで切っちゃうと
- サードパーティやbotなどでStreaming接続機能のないものを使ってるユーザーが消えてしまう
- 3日で切られるのはきつい
- 最終的にソースコードを見ないとわからないパラメーターで切られるのは混乱を招きそう

というのがあるのだわ。

**Comment by mei23** [comment]
> 最初に完全一致で検索して、limitに達しなかったら前方一致で埋めるとか

クライアント側で両方のAPIリクエストを出してクライアント側でマージするみたいなの考えてたのだわ。
(これをすればAPIのoffsetの意味がなくなるのを防げる)

**Comment by mei23** [comment]
> クライアント側で両方のAPIリクエストを出してクライアント側でマージするみたいなの考えてたのだわ。

で
https://github.com/misskey-dev/misskey/issues/7880#issuecomment-945071857
いじったほうがいいのではというやつだわ。

**Comment by syuilo** [comment]
フォローしているユーザーを優先して検索したりもしたいんだよね
そうするとクライアントでマージする方法だと一回タイプするごとに少なくとも3回リクエスト発生するの微妙感がある
offsetについては廃止でもいいかも

**Comment by syuilo** [comment]
search-by-username-and-host については
1. ローカル/リモート問わずフォローしているユーザーで、前方一致のワード順(ただし非アクティブは除外)
2. ローカル/リモート問わずフォローしていないユーザーで、前方一致のアクティブ順
にしようかな

**Comment by tamaina** [comment]
closeしていいかも？

**Comment by tamaina** [comment]
> 1. ローカル/リモート問わずフォローしているユーザーで、前方一致のワード順(ただし非アクティブは除外)
> 2. ローカル/リモート問わずフォローしていないユーザーで、前方一致のアクティブ順

両方達成されていそう
