### ISSUE TITLE
pope UI: side view broken since 12.92.0

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#7890]
## 💡 Summary

Since upgrading to 12.92.0, using the side view no longer works in pope UI.

## 🙂 Expected Behavior

Side view can be opened.

## ☹️ Actual Behavior

Nothing happens when attempting to open the side view.

## 📝 Steps to Reproduce

https://user-images.githubusercontent.com/652892/137961153-fa0ccb89-ad75-49b1-9bb7-0c1c0584f833.mp4

## 📌 Environment

openSUSE Tumbleweed, Node.js 16.6.2, Misskey: v12.92.0

**Comment by futchitwo** [comment]
https://github.com/misskey-dev/misskey/blob/ef4d78dda25e741c536f535aece0b20b488b9af4/packages/client/src/ui/universal.vue#L176

ここだけOptionsAPIになってる？
