### ISSUE TITLE
delete-accountが重い

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#7892]
インスタンス全体が停止してしまっているのをたまに見かける
少なくともNote削除自体はデータベース上で完結できるからそうするとか

**Comment by syuilo** [comment]
何が重いのか不明

**Comment by syuilo** [comment]
とりあえず原因と対策分かるまで無効にしておくか

**Comment by xianonn** [comment]
私のインスタンスでもたまに停止してしまっているので調べたところ、チャートのファイル増減で減っているタイミングとインスタンスが停止するタイミングが一致することが分かりました。
遅いクエリを調べてみると  `WHERE $1 = ANY("fileIds")` のクエリで該当するのは次の 2 箇所です。
https://github.com/misskey-dev/misskey/blob/71d9c2a53d116a61f4c9b21ff98712a0000412b8/src/services/drive/delete-file.ts#L137
https://github.com/misskey-dev/misskey/blob/71d9c2a53d116a61f4c9b21ff98712a0000412b8/src/services/drive/delete-file.ts#L109-L111

アカウント削除処理では

1.そのユーザーの note を全て削除
↓
2.そのユーザーの drive_file を全て削除
↓
3.そのユーザーの drive_file を使用している note を全て削除
↓
4.必要に応じてそのユーザーの user を削除

という流れになっていますが、1. でユーザーの note を全て削除しているので 3. で再度 note を削除しなくてもいいと考え私のインスタンスではアカウント削除処理の場合は 3. の処理をしないようにしました。 https://gitlab.com/xianon/misskey/-/commit/b8204573ebb21b2e930cbf9a50e95a63cba6f82b

3.の処理をしないようにしてからファイルの削除があってもインスタンスは停止しておらず効果があると思われるので上記コミットをプルリクしたいところですが、次の点において本当に 3. の処理をしなくても良いのか気になっています。

あるユーザーの note (ローカル/リモートを問わない)に別ユーザーの drive_file が紐付く可能性はありますか？

もし yes なら 3. の処理は必要ということになるのでこのコミットは正しくない処理となります。
なお、クエリ監視していたここ 3 日間で delete-file.ts#137 が実行された回数は 943 回ですが取得できたレコード数は 0 でした。

**Comment by syuilo** [comment]
詳しくありがとうございます！
ファイルにひもづくノート削除のクエリが負荷の大部分であった、という認識で合ってますか？

> あるユーザーの note (ローカル/リモートを問わない)に別ユーザーの drive_file が紐付く可能性はありますか？

これはNoですね。ただ将来的にどうなるかは分かりません(おそらく変わらないと思いますが)
とはいえ、添付ファイルが削除されたらノートも一緒に削除されるという仕様自体再考の余地があるので、どのみち No で良さそうです。

なので、

> 1. でユーザーの note を全て削除しているので 3. で再度 note を削除しなくてもいいと考え私のインスタンスではアカウント削除処理の場合は 3. の処理をしないようにしました

は正しい改修です。

よろしければPRお願いします！

**Comment by xianonn** [comment]
>ファイルにひもづくノート削除のクエリが負荷の大部分であった、という認識で合ってますか？

遅いクエリを確認したところファイルに紐付くノート削除の部分だった、ということで他のクエリが遅いかどうかは確認していないです。
とは言えファイルに紐付くノート削除はかなりの負荷でした。

質問の回答が no ということなのですぐに PR 出します。

**Comment by mei23** [comment]
単純にファイル→ノート削除処理ごと消してOK。
今は`DriveFile.pack`で無視される。
https://github.com/misskey-dev/misskey/issues/7346
https://github.com/misskey-dev/misskey/pull/7345

**Comment by xianonn** [comment]
PR 出しちゃってるけどそれに追加でファイル削除時のノート削除処理を消すコミット出しちゃって良いのかな？

**Comment by syuilo** [comment]
> PR 出しちゃってるけどそれに追加でファイル削除時のノート削除処理を消すコミット出しちゃって良いのかな？

👍

**Comment by mei23** [comment]
これ閉じていいじゃないかしら。
そして重いのは`delete-account`ではなくて`delete-file`だわね。

**Comment by syuilo** [comment]
delete-account自体に重い処理が無いのであれば

**Comment by cliqsocial** [comment]
> これ閉じていいじゃないかしら。 そして重いのは`delete-account`ではなくて`delete-file`だわね。

Any relation to this issue we reported early this year?

https://github.com/misskey-dev/misskey/issues/7364
