### ISSUE TITLE
モデレーターをリモートからブロックすると、相手側のフォローが外れない

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#7898]
## 💡 Summary

リモートインスタンスのユーザーをブロックしたとき、そのユーザーがインスタンスのモデレーターであった場合、相手からは自分が相手をブロックしていないことになる。また、自分に対するフォローが外れない。

これにより、本来見られないはずのフォロワー限定投稿も見られてしまう。

## 🙂 Expected Behavior

ブロックが正しく実行される

## ☹️ Actual Behavior

ブロックが相手のインスタンスでは正常に行われない

## 📝 Steps to Reproduce

1. リモートインスタンスのモデレーターをブロックする

## 📌 Environment

Misskey 12.92.0

**Comment by mei23** [comment]
ブロックに投稿を見れなくする効果を追加する
↓
「投稿が見れなくなるとモデレーションに支障が～」という話が出てくる
↓
とりあえずモデレーターをブロックできないようにする
↓
モデレーターにフォローを解除させることも出来なくなる (ローカルでもリモートでも)

**Comment by EbiseLutica** [comment]
リモートにまで波及するところが不具合だと思っています

**Comment by mei23** [comment]
ローカルでもモデレーターにフォローされたらフォロー解除させられないのも微妙な感じが

**Comment by syuilo** [comment]
フォロー解除についてはそもそもブロックすることでしか行えないのが問題だから、フォロー解除させる機能をブロックとは別に実装予定

**Comment by mei23** [comment]
> フォロー解除させる機能

あったはず。
リモートからフォロー解除を受信すれば解除するけどMisskeyから発信する機能はない。

**Comment by EbiseLutica** [comment]
フォロー解除機能の実装は別issueで。本issueが提起している問題は、1インスタンスのモデレーターの権力がリモートユーザーにまで及ぶことにあるので...。

**Comment by syuilo** [comment]
リモートユーザーがスパムである可能性もあるから、リモートユーザーであっても自インスタンスのモデレーターをブロックできない仕様で良さそうではある

**Comment by syuilo** [comment]
(フォローの解除だけは可能)

**Comment by mei23** [comment]
> フォロー解除機能の実装は別issueで。本issueが提起している問題は、1インスタンスのモデレーターの権力がリモートユーザーにまで及ぶことにあるので...。

確かに、フォロー解除機能が別にあってそれが正しく動いたとしてもIssueの問題は解決しないわね。

**Comment by syuilo** [comment]
このIssueで問題になっているのって

> 本来見られないはずのフォロワー限定投稿も見られてしまう。

じゃない？

**Comment by mei23** [comment]
> フォロー解除させる機能をブロックとは **別に** 実装予定

少なくともブロックとは **別に** 実装だと問題は解決しない。

**Comment by syuilo** [comment]
別に実装 + リモートからブロックされた時にモデレーターであってもフォロー解除だけは実行する感じかな

**Comment by mei23** [comment]
> 別に実装 + リモートからブロックされた時にモデレーターであってもフォロー解除だけは実行する感じかな

それならギリギリなんとか

**Comment by EbiseLutica** [comment]
> リモートユーザーがスパムである可能性

それを加味するなら #7734 のようにブロックはできれどホーム以上の投稿は見れるよ、という仕様を採用し、件のブロック拒否機能を廃止すべきかなと思う

もっと踏み込むなら、管理パネルみたいな通常アクセスしない場所じゃないとブロックされた人の投稿を見られる力を行使できなくしてほしい（工数がかかりそう）

**Comment by syuilo** [comment]
モデレーターをブロックできない仕様取りやめるのが一番楽そう(モデレーションについては別途考えるとして…)

**Comment by mei23** [comment]
そもそも「モデレーターはブロック出来ない」自体、
- 既にブロックされていたら効果がない
- モデレーターの状態でブロックを避けた後にモデレーターを解任されたらどうする

みたいなのがあるから微妙。

**Comment by EbiseLutica** [comment]
* モデレーターブロックブロック機能の廃止
* モデレーターはブロックされている相手ユーザーのパブリック|ホーム投稿を見れる

という仕様でいいんじゃないかな。その上で

* ブロックされているユーザーの投稿を見る前にワンクッション操作を必要とさせる (より良い)
* ブロックされているユーザーの投稿を見る専用の画面を管理画面に提供する (めちゃ良い)

って感じでどうかなあ
