### ISSUE TITLE
フォロー解除させる機能

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#7899]
## Summary

フォロー解除させたいだけでも、一旦ブロック→ブロック解除という手順を踏む必要がありスマートではない

**Comment by syuilo** [comment]
ユースケース
- フォロー解除機能が無いbotなどにフォロー解除してもらいたいとき
- ブロックするほどでもないが、できれば投稿を見られたくない時
- 等

**Comment by marihachi** [comment]
botへの対応としては賛成。

人に対しては、フォローされている以上は相手もフォローしているという認識があるわけで、勝手にそれを解除できるとトラブルにも繋がりそう。このユースケースでは機能を利用せずに、相互で交渉するほうが良いと思う。

**Comment by syuilo** [comment]
> 人に対しては、フォローされている以上は相手もフォローしているという認識があるわけで、勝手にそれを解除できるとトラブルにも繋がりそう。

勝手にフォロー解除させるのはブロック→ブロック解除で既に実現できているから別Issueそう

このIssueはそれを(どうせできるのならば)より便利にしたいというIssue

**Comment by rinsuki** [comment]
そもそも現状でもブロブロ解で解除できるし(一応こっちからのフォローが外れるか外れないかという違いはあるが)、フォロー外したい人間がいるシチュエーションだと外したい相手と交渉したくなさそう

**Comment by rinsuki** [comment]
Mastodon等との相互運用性どうなんだっけという問題はある

**Comment by syuilo** [comment]
> 勝手にフォロー解除させるのはブロック→ブロック解除で既に実現できているから別Issueそう

んで多分ブロックしても相手からフォロー解除されないように仕様変更するのは厳しいと思う(あまりブロックの意味がなくなる)

**Comment by syuilo** [comment]
あとブロックというよりトラブルに繋がる可能性の高い機能が既にあるから、フォロー解除というそれの優しいバージョンを追加的に実装するのは問題ないように思える

**Comment by marihachi** [comment]
この機能を追加することで、今までブロ/ブロ解を別の目的として使って結果的にフォローを外せるというのを公式に認めることになる・推奨することになると思う。
トラブルになる可能性が分かっているのならば、推奨しないほうが良いのでは

**Comment by syuilo** [comment]
ブロックは「相手からフォローさせない/既にされてたら解除させる」が主な目的の機能だから(ドキュメントにも明記してある)、フォロー解除は「結果的」ではなくて、むしろそれが目的で行うから、既に「公式に認めている・推奨している」状態だと思う

**Comment by tamaina** [comment]
> この機能を追加することで、今までブロ/ブロ解を別の目的として使って結果的にフォローを外せるというのを公式に認めることになる・推奨することになると思う。

そう？？？  
(追記)というか推奨して何か悪いことが起きる？

> トラブルになる可能性が分かっているのならば、推奨しないほうが良い

しゅいろの発言の意図はフォロー解除させる機能よりブロック機能のほうがトラブルが起きやすい…ということだと思う

**Comment by weepjp** [comment]
これは実質 Twitter で最近導入された「フォロワーを削除する」機能ですね。
他SNSでも追従して欲しいなと思っていたので 👍 しときました。
フォロワーさん想いの方には理解が得られない機能ではありますが、ブロック＆ブロック解除をやってる利用者も居なくはないはず。
これがワンボタンで済むなら良い。

**Comment by tamaina** [comment]
## Off Topic?

私の場合、フォローしてるかどうか記憶していないので、フォロー解除させられてもまたフォローし直している場合がありそう。  
この機能、あってもいいと思うけど、そういうことがあるので効果や価値があるかどうか私は疑問に思っている。

**Comment by mei23** [comment]
フォロー解除機能は既に部分的に付いている。

> Mastodon等との相互運用性どうなんだっけという問題はある

Mastodonにはその機能があってMisskeyは受信したらちゃんと処理する。
Misskeyから発信する手段はない。
#5587

> これは実質 Twitter で最近導入された「フォロワーを削除する」機能ですね。

TwitterはMastodonのパクリ🔥

**Comment by syuilo** [comment]
> ## Off Topic?
> 私の場合、フォローしてるかどうか記憶していないので、フォロー解除させられてもまたフォローし直している場合がありそう。 あってもいいと思うけど、そういうことがあるので私はこの機能に効果や価値があるかどうか疑問。

ブロック&ブロック解除っていうワードは個人的にはよく聞くから需要はあるんだと思う

**Comment by marihachi** [comment]
> ブロックは「相手からフォローさせない/既にされてたら解除させる」が主な目的の機能だから(ドキュメントにも明記してある)、フォロー解除は「結果的」ではなくて、むしろそれが目的で行うから、既に「公式に認めている・推奨している」状態だと思う

そうは思わないかな、もっと恒常的なものだと思ってたけど。
まあ推奨してるなら良いと思う。

**Comment by tamaina** [comment]
逆にまりはち氏がブロック機能に何を期待していたのかが気になる

**Comment by marihachi** [comment]
単純に交流を拒否するものだと思ってた。

**Comment by marihachi** [comment]
何か迷惑行為に遭った際とかね

**Comment by EbiseLutica** [comment]
ブロックは相手から自分の投稿の閲覧権を奪うことにもなり、関わりを断るという強い意志の表現でもあるから重たいよ

**Comment by mei23** [comment]
だから既に付いてるって言ってる

**Comment by tamaina** [comment]
交流を拒否する主な手段として「相手からフォローさせない/既にされてたら解除させる」があると私は思っていた

**Comment by syuilo** [comment]
ブロックにフォロー解除機能持たせないとなると、鍵アカウントにしようが何しようが永遠に相手から自分の投稿を見られてしまうことになり、あまりブロックの意味が無くなりそうと思ってる

**Comment by marihachi** [comment]
> ブロックにフォロー解除機能持たせないとなると、鍵アカウントにしようが何しようが永遠に相手から自分の投稿を見られてしまうことになり、あまりブロックの意味が無くなりそうと思ってる

いやいや、ブロックはフォロー解除+閲覧禁止でいいと思う
その目的はわりと恒常的に関係を断つってことだと思ってた

**Comment by tamaina** [comment]
この会話、相手→自分のフォロー解除なのか自分→相手のフォロー解除なのかがごっちゃになってそうな気配がある

**Comment by marihachi** [comment]
ブロックの目的とかは完全に別Issueなのでここで話す内容ではなかった

**Comment by tamaina** [comment]
たしかに  
(反対する理由をもうちょっと明確に聞きたかったので聞いてみた

**Comment by mei23** [comment]
APIでは`following/requests/reject`で被フォロー解除も出来る。今は500になるけど。

**Comment by EbiseLutica** [comment]
オフトピでボコボコになってるので要点を整理しますた。

## 目的

ブロック→ブロック解除という手順をわざわざ取ることなく相手のフォローを解除したい

## 懸念点とその反論

* 一方的なフォロー解除はトラブルの原因になるのでは？
  * 既にブロック機能が同等の挙動を起こす。その問題は本issueの範囲外
* Mastodonと互換性あるのか
  * あるが、受信のみ。Misskeyからはできない
* 本実装により、ブロ解を公認することになる
  * 公認による悪影響が知りたい
* 需要ある？
  * 言葉としてブロック＆ブロック解除をよく聞くので需要あると判断

## 私の意見

* トラブルの原因になるかどうかは考えなくて良いと思うし、ブロック以外にもトラブルの原因はたくさんあるので議論するなら別機会にすべき
* 個人的に、フォロー解除は「ノートを見たくないし見られたくない。けど完全に閲覧権を奪うのはなんか違う。」という心情を満たす存在だと考えている

**Comment by EbiseLutica** [comment]
また、めいめいの発言通りActivityPub実装とAPIのレベルでは実装済みなので、本issueはフロントエンドに実装するかどうかが厳密な目的になるかな。

**Comment by mei23** [comment]
被フォロー解除の実装状況はたぶんこんな感じ
ActivityPub: 実装済み
API: 謎

ActivityPub的に、フォローリクエスト拒否とフォロー解除はActivityが同じ (Reject Follow)
なので Reject Follow が来たら、フォローリクエスト拒否とフォロー解除の両方を行っている。
↓
Rejectの処理はActivityPubとAPIで共通。
↓
API`following/requests/reject`ではガッツリ制御してるわけではないので
仕様なのかバグなのか裏技なのかは知らないがこのAPIで被フォロー解除処理が出来てしまう。
(今はtypeの扱いでエラーになる)

**Comment by syuilo** [comment]
フォロワー解除できるようになった
