### ISSUE TITLE
web search engine setting missing

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#7917]
## 💡 Summary

The setting for the web search engine introduced in #3406 is missing.

It seems it was removed in v12 <https://github.com/misskey-dev/misskey/commit/f6154dc0af1a0d65819e87240f4385f9573095cb#diff-1b57999747089126c1d8f750bf413bed9d15fcd81999f00a9cbedff6c745fb52L153-L159>, but the code to select the search engine still is in the client: https://github.com/misskey-dev/misskey/blob/a5bbb6732d8ec03e3e9ae560f0dcc1a31155330c/src/client/components/google.vue#L24-L25

Maybe the setting was just accidentally removed?

## 🙂 Expected Behavior

The user can select a web search engine.

## ☹️ Actual Behavior

Always uses Google. (bad for privacy)

## 📌 Environment

Misskey since v12.0.0

If it is okay to add this again, I would like to do it.

**Comment by syuilo** [comment]
See https://github.com/misskey-dev/misskey/pull/7920#issuecomment-952997272

**Comment by Johann150** [comment]
I think even if it is intended as a joke, it would be responsible to not put users in the dangerous hands of Google. Maybe the search engine should be changed for everyone.

**Comment by syuilo** [comment]
Googleがどのように危険なのか分かりません...。Google検索は広く使われています(大量の広告は好きではありませんが)
そのほかの検索エンジンについても、いつでも危険になる可能性はあると思います。

**Comment by acid-chicken** [comment]
> そのほかの検索エンジンについても、いつでも危険になる可能性はあると思います。

Google が危険かどうかとその他のエンジンが危険になるかどうかはあまり関係ないと思うし、そもそもインターネット検索エンジン以外にも `https://misskey.example/search?q={{query}}` といった使い方はできるわけで、そういう点からもクエリ送信先を選択できた方が嬉しくないですか？

**Comment by syuilo** [comment]
> > そのほかの検索エンジンについても、いつでも危険になる可能性はあると思います。
> 
> Google が危険かどうかとその他のエンジンが危険になるかどうかはあまり関係ないと思うし、そもそもインターネット検索エンジン以外にも `https://misskey.example/search?q={{query}}` といった使い方はできるわけで、そういう点からもクエリ送信先を選択できた方が嬉しくないですか？

嬉しいけど、ジョーク機能をそこまで作り込みたくない

**Comment by EbiseLutica** [comment]
怖いなら押さなければ良いと思う。インターネットのリンクが全て安全であると思うほうが愚かなので。

**Comment by acid-chicken** [comment]
> インターネットのリンクが全て安全であると思うほうが愚か

というのは利用者が提供者に対して性悪説的に振る舞うべきという話であって、それを根拠に

> 怖いなら押さなければ良いと思う

というのを*提供者として*主張するのはあまり適切には感じない。


ともかく機能を廃止するのであればこれ以上話しても仕方がない。

**Comment by rinsuki** [comment]
逆にジョークとして検索ボタン押したらどのサイトで検索する？って100個くらい出てきてもいいかも

**Comment by EbiseLutica** [comment]
まあ放置でいいような気もする。あまりに反対意見が大量に降ってくるようなら考えてもいいし、そんなに嫌ならグーグルフリーなMisskey作ってもろて...って思う

**Comment by Johann150** [comment]
I think its funny that the issue was closed but still so many people seem to have something to say about this.

If you want to understand why Google is dangerous, you could look into press coverage of the current U.S.'s Antitrust filings against Google (e.g. https://www.bloomberg.com/news/articles/2021-09-01/u-s-doj-readying-google-antitrust-lawsuit-over-ad-tech-business ).

**Comment by futchitwo** [comment]
この要望OSSでfediverceやってる限り定期的に湧いてきそう
労力を割く必要はないけど、プルリクエストが来たときはマージぐらいしてもいいと思います
あとこれ自体に保守コストはそこまでかからない気がします(チリが積もれば…と言われたら反論はできないけど)
