### ISSUE TITLE
グループに招待しても何も起こらない場合がある

### ISSUE THREAD

**Issue by SanMurakami** [syuilo/Misskey#7921]
## 💡 Summary

連合済みのユーザーをグループに招待しても何も起こらない（相手に通知されない）場合がある。

## 🙂 Expected Behavior

招待一覧に出てくる

## ☹️ Actual Behavior

招待一覧に出てこない

## 📝 Steps to Reproduce

1.連合のユーザーをグループに招待する
2.
3.

## 📌 Environment
Misskey.io v12.94.1 <-> honi.club v12.94.1
Misskey.io v12.94.1 <-> sushi.ski v12.94.1
honi.club v12.94.1 <-> sushi.ski v12.94.1

**Comment by mei23** [comment]
グループの連合は実装されてないから
Expected Behavior はエラーにするかそもそも出来ないようにするか

**Comment by SanMurakami** [comment]
honi.clubとsushi.skiで連合出来てると言ってる人が居る

**Comment by mei23** [comment]
たぶんダイレクトチャットの連合あたりと勘違いしてるとかだわ

**Comment by mei23** [comment]
または、あたかもローカルだけ見ると正常にリモートユーザーを招待できてるように見えるからそこで出来てると誤解してる。

あくまでもこの挙動のはず
> 連合済みのユーザーをグループに招待しても何も起こらない（相手に通知されない）

**Comment by SanMurakami** [comment]
なるほど
勘違いだった見たいと連絡もらった

**Comment by tamaina** [comment]
グループ廃止
