### ISSUE TITLE
Explore page missing text

### ISSUE THREAD

**Issue by okpierre** [syuilo/Misskey#7931]
## 💡 Summary

Explore page missing text

## 🙂 Expected Behavior

Text is visible when visiting Explore page

## ☹️ Actual Behavior

Blank space after Remote

Screenshot

![misskeyexplore](https://user-images.githubusercontent.com/1679025/139515895-f4fee8f4-53d2-46c0-849e-d250ba2eb26e.png)

## 📝 Steps to Reproduce

1. Login
2. Go to Explore
3. At the top, go to Search

## 📌 Environment

Misskey 12.94.1 Firefox and Chrome

**Comment by Johann150** [comment]
This is using a missing string `both`. I think in analogy to these two selection boxes it should use `all` instead
https://github.com/misskey-dev/misskey/blob/1c38c7010d9a9604df979faa867cd8f9e7d825c9/src/client/pages/admin/abuses.vue#L12-L23

```diff
diff --git a/src/client/pages/explore.vue b/src/client/pages/explore.vue
index a77b4e53c..5a23d34d2 100644
--- a/src/client/pages/explore.vue
+++ b/src/client/pages/explore.vue
@@ -70,7 +70,7 @@
                                        <MkRadios v-model="searchOrigin">
                                                <option value="local">{{ $ts.local }}</option>
                                                <option value="remote">{{ $ts.remote }}</option>
-                                               <option value="both">{{ $ts.both }}</option>
+                                               <option value="both">{{ $ts.all }}</option>
                                        </MkRadios>
                                </div>
```

**Comment by okpierre** [comment]
I also see `all` being used for files so seems correct. Do you want to submit PR?
