### ISSUE TITLE
Typo in the repo's description

### ISSUE THREAD

**Issue by BedrockDigger** [syuilo/Misskey#7961]
## 💡 Summary

AFAIK "an" instead of "a" goes before words that begin with vowels, just like the adjective "interplanetary".
You can refer to [docs like this](https://owl.purdue.edu/owl/general_writing/grammar/articles_a_versus_an.html).

## 🙂 Expected Behavior

The description of this repo should be "**An** interplanetary communication platform"

## ☹️ Actual Behavior

But it's currently "**A** interplanetary communication platform"

## 📝 Steps to Reproduce

-

## 📌 Environment

-

**Comment by syuilo** [comment]
Fixed🙏
