### ISSUE TITLE
Performance issue: delete from note

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#7963]
## 💡 Summary

```
DELETE FROM "note" WHERE $1 = ANY("fileIds") - duration: 60415.424 ms
DELETE FROM "note" WHERE $1 = ANY("fileIds") - duration: 60422.520 ms
DELETE FROM "note" WHERE $1 = ANY("fileIds") - duration: 60414.976 ms
DELETE FROM "note" WHERE $1 = ANY("fileIds") - duration: 60415.090 ms
DELETE FROM "note" WHERE $1 = ANY("fileIds") - duration: 59693.417 ms
```

@mei23 did respond to this report but not sure of the technical details

reference: https://cliq.social/notes/8sn6acryma 

## 🙂 Expected Behavior

Lower duration

## ☹️ Actual Behavior

Very high and causes performance issue

## 📝 Steps to Reproduce

1. unsure if this is caused from local or remote

## 📌 Environment
12.94.1 / PostgreSQL 13.4

**Comment by mei23** [comment]
Fixed in develop branch
https://github.com/misskey-dev/misskey/pull/7958
