### ISSUE TITLE
proxy account following accounts needlessly

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#7966]
## 💡 Summary

The proxy account seems to be following anyone who gets added to a list, even if those people are already being followed by other users on that instance.
(in addition, there doesn't seem to be a way to remove a proxy account from the control panel, but that is a separate issue)

## 🙂 Expected Behavior

1. Add a remote user I'm already following to a list
2. The user gets added to the list without receiving a follow request from the proxy account

## ☹️ Actual Behavior

1. Add a remote user I'm already following to a list
2. The user gets added to the list and the proxy account requests a follow from them, even though there is no need to.

## 📝 Steps to Reproduce

1. Follow a user on a remote instance.
2. Add them to a list.
3. Check that the proxy account has followed them as well.

## 📌 Environment

Misskey 12.95.0
Node.jsv 16.13.0
PostgreSQL 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
Redis 5.0.7
Vue 3.2.20

**Comment by blackskye-sx** [comment]
That's the purpose of the proxy account. When someone adds an account to a list, the proxy account will follow them to make sure that any posts get pulled down. That way the user doesn't have to also follow the account AND add them to the list.

We do need a way to cancel that action though. Like remove the proxy account (blank field).

**Comment by ghost** [comment]
okay, I guess I just misunderstood the way it worked from the description. I will close this issue and open one regarding the lack of a way to remove the account.

Thanks
