### ISSUE TITLE
The option to never repeat posts in the timeline

### ISSUE THREAD

**Issue by Freeplayg** [syuilo/Misskey#7967]
## Summary
Sometimes the timeline gets cluttered when many people you follow renote the same thing. So maybe to help with this, add the option to never show the same option twice. Along with maybe showing "Renoted by User, User, and User" instead.

**Comment by turtlegarden** [comment]
If renoted the post should again appear on your timeline, but dissapear earlier.

**Comment by turtlegarden** [comment]
And I also think your renotes should be seperate.

**Comment by tamaina** [comment]
Duplicate of #1792
