### ISSUE TITLE
Slow mode and other Misskey wellness settings

### ISSUE THREAD

**Issue by turtlegarden** [syuilo/Misskey#7969]
# It is easy to overnote on Misskey.
So here are some things that I thought about that could help many people (including me) not overnote.
## Grayscale mode
Remove all of the color from your Misskey making it less addictive. Like in [Pinafore](https://pinafore.social).
## Slow mode
Like in Mastodon, do not auto display new notes and notifications, add a button to display them. This could also hide the "There are new notes" button.
## Remove notification dots
Like in Pinafore. No notification dots to wait for.
## Category in client settings for these
That is self explanatory.

I'm looking forward to working on some of these, maybe. Thanks so much!
[@forever@misskey.ai](https://misskey.ai/@forever)

**Comment by Johann150** [comment]
I think remove notification dots and probably also greyscale mode can already be achieved by using custom CSS.

For example, to remove the blinking dots:
```css
.indicator, .fa-circle {
  display: none;
}
```

For greyscale mode you could probably start by using Client Settings > Themes > Make a Theme.

**Comment by turtlegarden** [comment]
Indeed, I already do some of these with custom CSS. However, the goal is to make them easily accessible to new users. :)

I was also thinking greyscale mode would grey out everything. But that would be kinda hard :'(

I'm still gonna keep this open. Mostly for the Slow Mode.

**Comment by soupglasses** [comment]
I currently have a ublock origin rule to hide the "There are new notes" button.
```
example.com##button:has-text(/There are new notes/)
```

I hope to see this become an included feature to disable to help keeping its addictive nature down.

**Comment by turtlegarden** [comment]
stale

**Comment by kakkokari-gtyih** [comment]
Slow mode is being discussed in https://github.com/misskey-dev/misskey/issues/12227
