### ISSUE TITLE
PRでのlintが機能していない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8002]
明らかにLint違反のコード(キーワード間にスペースが無いとか)でもなぜかエラーになっていない
同じコードをローカルでlintするとちゃんと怒られる

**Comment by tamaina** [comment]
> 同じコードをローカルでlintするとちゃんと怒られる

怒られない件

![image](https://user-images.githubusercontent.com/7973572/144240660-c74cf906-828d-44ee-a9b7-6379dc307361.png)

**Comment by syuilo** [comment]
どんなコードでやってる？

**Comment by tamaina** [comment]
npm run lint

**Comment by syuilo** [comment]
どんなコードをlintしてる？

**Comment by tamaina** [comment]
あー、 #7712

**Comment by syuilo** [comment]
それに関しては特にlint違反のコードはないんじゃないかな

**Comment by tamaina** [comment]
ダブル/シングルクオートってlint違反ではないんだったか

**Comment by syuilo** [comment]
lint違反にしたつもりだったけど、
https://github.com/misskey-dev/misskey/issues/8002#issuecomment-983628818
ということであればなってないんだと思う
もしくはバックエンドだけでフロントエンドの方には適用されてないとか

**Comment by syuilo** [comment]
バックエンドの方に関してはwarnする設定になってた
https://github.com/misskey-dev/misskey/blob/4cc2a561d5cc34b5d8eab2d2f429ef0db9c4a93a/packages/shared/.eslintrc.js#L24

**Comment by syuilo** [comment]
フロントエンドの方に関しては、VueのlintプラグインとTypeScriptのlintプラグインとの相性が悪いのか、一緒に使うとエラーになるからVueだけしかしてない

**Comment by tamaina** [comment]
バックエンドで違反してみても特に怒られない感

![image](https://user-images.githubusercontent.com/7973572/144242446-c8b0cccc-325e-4a17-a7b1-745173f9cc9e.png)

**Comment by syuilo** [comment]
今のところerrorじゃなくてwarnだからnpm run lintでは怒られないね

**Comment by tamaina** [comment]
なるほど

**Comment by tamaina** [comment]
でも'error', 'always'なセミコロン抜きやってみてもエラーが出ないのでなんかおかしい感

![image](https://user-images.githubusercontent.com/7973572/144243242-16cd6e15-81c8-4947-93d5-c453ffd451b8.png)

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/144243836-830def77-b57e-4652-86f9-119c78a0b6dc.png)
こっちだとセミコロン抜くとエラーになった

**Comment by tamaina** [comment]
なんだろう？？OSの違いとか？？

**Comment by syuilo** [comment]
:nazo:

**Comment by acid-chicken** [comment]
> でも'error', 'always'なセミコロン抜きやってみてもエラーが出ないのでなんかおかしい感
> 
> ![image](https://user-images.githubusercontent.com/7973572/144243242-16cd6e15-81c8-4947-93d5-c453ffd451b8.png)

その環境で `DEBUG=eslint:* npm run lint` してみてほしい

**Comment by tamaina** [comment]
> DEBUG=eslint:* npm run lint

えぐい量のログが出てきて何を報告すればいいのかわからない(

**Comment by Johann150** [comment]
Would updating node help?
https://github.com/misskey-dev/misskey/blob/aebd77ad38583ee3a5d7e922435191b7d504339d/.github/workflows/lint.yml#L17-L19

**Comment by Johann150** [comment]
```text
error got@12.0.2: The engine "node" is incompatible with this module. Expected version ">=14.16". Got "12.22.10"
```
https://github.com/misskey-dev/misskey/runs/5617061295?check_suite_focus=true#step:5:13
