### ISSUE TITLE
Forgot password box missing styling

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#8003]
## 💡 Summary

The forgot password box margin is missing

## 🙂 Expected Behavior

Same styling as login with correct margin

## ☹️ Actual Behavior

No margin for message

![misskeyforgotpasswordstyling](https://user-images.githubusercontent.com/60059665/142515718-392ca3f5-3247-4f52-adea-3682e630f69d.png)

## 📝 Steps to Reproduce

1. View main page
2. Click Sign In
3. Click Forgot Password

## 📌 Environment

12.96.1 / PostgreSQL 13.4 / nginx

**Comment by Johann150** [comment]
This seems to be fixed when testing on a current version.
