### ISSUE TITLE
Privacy settings missing translation

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#8004]
## 💡 Summary

Missing translation for Privacy settings

## 🙂 Expected Behavior

Text is translated

## ☹️ Actual Behavior

Text in different language

![misskeyprivacytranslation](https://user-images.githubusercontent.com/60059665/142515993-d0e0b4a6-faf6-497c-a8f2-0676a69146f4.png)

## 📝 Steps to Reproduce

1. Click on Settings
2. Click on Privacy

## 📌 Environment

12.96.1 / PostgreSQL 13.4 / nginx

**Comment by Johann150** [comment]
If a translation is missing it means nobody has gotten around to translate it yet. You are welcome to help localising misskey, but this is not a bug IMO.

Instructions for contributing to localisation are in the contribution guide:
> ## [Localisation (l10n)](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md#localization-l10n)
> Misskey uses Crowdin for localization management. You can improve our translations with your Crowdin account. Your changes in Crowdin are automatically submitted as a PR (with the title "New Crowdin translations") to the repository. The owner syuilo merges the PR into the develop branch before the next release.
