### ISSUE TITLE
can't view or edit lists after updating to v12.97 even after clearing cache

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8005]
## 💡 Summary

```
 Failed to load page.

This is normally caused by network errors or the browser's cache. Try clearing the cache and then try again after waiting a little while.

Troubleshooting

ERROR: ChunkLoadError: Loading chunk src_components_form_textarea_vue failed. (error: https://<domain>/assets/src_components_form_textarea_vue.12.97.1.js)
```
Lists don't seem to work for me after the update. I've cleared cache, tried a different browser, private window, and on different device and internet entirely. I always get this error message. It seems to be related to caching but I can't figure out how to fix it.

## 🙂 Expected Behavior

Can view lists and edit them.

## ☹️ Actual Behavior

Opening lists results in error message above.

## 📝 Steps to Reproduce

1. Open any list

## 📌 Environment
Misskey 12.97.1
Node.js v16.13.0
PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
Redis 5.0.7
Vue 3.2.21

Manage list menu, opening a list from any page.

**Comment by ghost** [comment]
I also can't edit antennas.

**Comment by syuilo** [comment]
I can not reproduce it.
Try rebuild Misskey.

**Comment by ghost** [comment]
I managed to fix it.
I think it was an issue caused by an inconsistency with my instance URL
My URL was both "misskey.[domain].com" and "[domain].com" and only the misskey.domain was wonky.
Ensuring the URL is consistent everywhere and simply redirecting mk.[domain].com to [domain].com fixed the issue.
