### ISSUE TITLE
画像ビューワーで全体表示した時に上側の一部しか表示されない画像がある

### ISSUE THREAD

**Issue by xianonn** [syuilo/Misskey#8013]
## 💡 Summary

Exif によって横に回転している画像を画像ビューワーで全体表示した時に上側の一部しか表示されない

## 🙂 Expected Behavior

画像全体が表示される

## ☹️ Actual Behavior

画像が拡大されすぎて上側の一部が表示される

## 📝 Steps to Reproduce

1.ノートに添付されている、Exif によって横に回転している画像をクリックする
2.画像ビューワーで全体表示されずに上側の一部が表示される
<p><img src="https://user-images.githubusercontent.com/91555638/142895147-effcaa3e-639e-4d2e-b7fa-f96b37f5ab89.png" alt="画像ノート" width="50%"></p>
<p><img src="https://user-images.githubusercontent.com/91555638/142895162-55f1116b-5ac0-461f-948e-ea002404882a.png" alt="画像ビューワー" width="50%"></p>

## 📌 Environment

Misskey 12.97.1

**Comment by mei23** [comment]
つまりAPIの応答がおかしくて、クライアントでその値を使うからおかしくなっちゃう。
![image](https://user-images.githubusercontent.com/30769358/142948080-fb4773b4-f799-4d36-acd9-bb8cc20b265b.png)

**Comment by tamaina** [comment]
画像ビューワーがwidth, heightを使っているのが根本の問題なので、orientationプロパティを付けるとかをするのは話が大きくなりがち

webpublicの確実なサイズ値を取得するのなら次のようにすればいいので、小さな話に抑えるならクライアント側の修正だけで対処可能そう。

```js
const img = new Image();
img.onload = () => console.log({width: img.width, height: img.height});
img.src = 'https://p1.a9z.dev/files/webpublic-f672fa73-e1fc-43a0-ad63-59634408f3ef';

// { width: 1478, height: 1109  }
```
