### ISSUE TITLE
Word mute page missing styling

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#8018]
## 💡 Summary

Word mute page missing styling

reference to `@perfor` for reporting this:
https://cliq.social/notes/8tfz81gjfw

## 🙂 Expected Behavior

mute and blocks page showing spacing at the top of page

should look like this
![misskeymuteblock](https://user-images.githubusercontent.com/60059665/143141853-7efcd85b-e1ef-43aa-bcf3-ec52b6613f19.jpg)

## ☹️ Actual Behavior

Buttons touch top of browser bar

should not look like this
![misskeywordmute](https://user-images.githubusercontent.com/60059665/143141916-7a730a27-ce31-4efe-98ce-b7a60f8ef48a.jpg)

## 📝 Steps to Reproduce

1. Login
2. Click on settings
3. Click on word mute

## 📌 Environment

12.96.1 / PostgreSQL 13.4 / nginx

**Comment by syuilo** [comment]
Fixed
