### ISSUE TITLE
ブラウザの戻るボタンで画像ビューワを閉じられるようにする

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey#8023]
## Summary

開いた画像の縦横比がブラウザのウィンドウと同じだと背景を押して閉じる方法がなくなってマウスで閉じる方法が

- ×ボタンを押しに行く(だるい、小さい)
- 上から下にドラッグ(PCだとそういう動作あんまりしないので気づきにくい)

しかなくて閉じるのが難しい

**Comment by syuilo** [comment]
画像をクリックした時の挙動をズームではなくて閉じるのにすれば良いかも
個人的にはクリックで拡大したいことがなくて、マウスホイールでズームできれば事足りそう

**Comment by syuilo** [comment]
画像をクリックしたら閉じるようにした + 画像の周りに余白を追加して縦横比がブラウザのウィンドウと同じでも背景をクリックできる余地を残すようにしてみた

**Comment by syuilo** [comment]
戻るボタンの検知はちょっと面倒そう

**Comment by Sayamame-beans** [comment]
triage: プレビュー表示中はURLに`/#pwsp`が付き、戻れるようになっている
