### ISSUE TITLE
FirefoxでKaTeXの改行を使うと特定条件で表示がおかしくなる

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#8027]
## 💡 Summary

通常、行の先頭でKaTeX改行`\\`をしても無視されるが、MFM関数、引用、中央揃えの中で普通に(KaTeX外で)改行したあとKaTeX内で改行をすると、Firefoxのみ改行されるように見える。

https://co.misskey.io/notes/8ta3udzym9
例えば上のノートのバグでは、通常の改行した後KaTeXでも改行をしている。ChromeやSafariでは改行が1回のみだが、Firefoxでは2回改行がされているように見える。

firefoxでMFMアートが崩れる原因になっている。
また、フォークであるめいすきーやGroundpolisでは起こらない。

## 🙂 Expected Behavior

Firefox使用時にMFM関数、引用、中央揃えの中で普通の改行したあとKaTeXの改行をしても改行されない

## ☹️ Actual Behavior

改行されたようにみえる

## 📝 Steps to Reproduce

MFM関数、引用、中央揃えの中で普通に(KaTeX外)改行したあとKaTeX内で改行をする

## 📌 Environment

Misskey v12.97.1
firefox windows/android

**Comment by rinsuki** [comment]
Firefox Nightly 97.0a1 (2021-12-07) で直ってそう

**Comment by futchitwo** [comment]
正式版でも直ってた
~~Misskey側の問題だと思ってたけどまさかFirefoxサイドが修正してくれるとは~~
