### ISSUE TITLE
透明な画像の背景を市松模様にする

### ISSUE THREAD

**Issue by argxentakato** [syuilo/Misskey#8043]
## Summary

前景に単色しか使われず (Emojiみたいな画像)、かつ背景が透明な画像を投稿すると背景と前景の色が同じになってしまい見えにくくなるから。

Photoshopなどの画像編集ソフトのように市松模様を背景にすべきではないかと考える。

**Comment by syuilo** [comment]
画像が透過かどうか簡単に判定する術がないから難しそう

**Comment by tamaina** [comment]
> 画像が透過かどうか簡単に判定する

鯖側ならsharp.stats().isOpaqueで検出できる

…そもそも背景を画像の平均色にする意味ってある？

**Comment by syuilo** [comment]
> 鯖側ならsharp.stats().isOpaqueで検出できる

これ前試してたけどかなり当てにならない

**Comment by syuilo** [comment]
> そもそも背景を画像の平均色にする意味ってある？

無さそうだったんでやめた

**Comment by syuilo** [comment]
> 背景が透明な画像を投稿すると背景と前景の色が同じになってしまい見えにくくなる

がほぼ解決されたためClose
