### ISSUE TITLE
コントロールパネルの連合リストのソートが正常にできない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#8045]
## 💡 Summary

コントロールパネルの「連合」にて、ソートが正しく行われない

## 🙂 Expected Behavior

ソートしたい項目を選ぶとリストが再読み込みされて、並び替えられる。

## ☹️ Actual Behavior

ソートしたい項目を選んでもリストが変わらない。
さらに、スクロールダウンして隠れているリストが読み込まれたときに、新しくソートされたリストが割り込んでおかしくなる。

## 📝 Steps to Reproduce

1. コントロールパネルの「連合」に移動
2. ソートで任意の項目を選ぶ
3. 下にスクロールする

## 📌 Environment
Misskey 12.98.0
Android 11, Chrome 96.0.4664.45

**Comment by syuilo** [comment]
直ってそう
