### ISSUE TITLE
Allow changing the number of files in a note

### ISSUE THREAD

**Issue by outloudvi** [syuilo/Misskey#8054]
## Summary

(Sorry for not being able to search if there are Japanese duplicates.)

Currently there is a fixed number of maximum 4 files in a note:

https://github.com/misskey-dev/misskey/blob/d95fafb5b35729638f0c5f9f26dd2be78c822170/packages/backend/src/server/api/endpoints/notes/create.ts#L81

https://github.com/misskey-dev/misskey/blob/d95fafb5b35729638f0c5f9f26dd2be78c822170/packages/client/src/components/post-form-attaches.vue#L13

However, 4 is a pretty small number. Probably the number can be increased or [even be configurable](https://github.com/outloudvi/misskey/tree/feat/maxFileNumber).

**Comment by Johann150** [comment]
I think this limit is related to mastodon only accepting 4 media files: https://github.com/mastodon/mastodon/blob/0fc73bbcb937d62c47a37325794825c77ef8a8a7/app/lib/activitypub/activity/create.rb#L113

That said, there is also a similar feature request for mastodon open currently: https://github.com/mastodon/mastodon/issues/14336

**Comment by outloudvi** [comment]
> I think this limit is related to mastodon only accepting 4 media files: https://github.com/mastodon/mastodon/blob/0fc73bbcb937d62c47a37325794825c77ef8a8a7/app/lib/activitypub/activity/create.rb#L113

Oh, I got it!

That said, since many other implementations like Friendica and Pleroma ([at least in my example](https://social.outv.im/notice/A9yy6wNhDE0KMYSsuO)) do not limit or at least have a such low limit, probably it's still okay to let instance choose whether to lift the limit, although it may bring inconsistence with Mastodon.

**Comment by marihachi** [comment]
Mastodonなどの他のサービスに仕様を合わせないといけないのならMisskeyである必要はないのでは？という話が前に出ていました。
基本的にはこれがMisskeyのスタンスだと認識しています。

**Comment by syuilo** [comment]
> Mastodonなどの他のサービスに仕様を合わせないといけないのならMisskeyである必要はないのでは？という話が前に出ていました。
> 基本的にはこれがMisskeyのスタンスだと認識しています。

👍

ただファイル数に関しては、4つは少ない気がするからもう少し増やしても良さそう

**Comment by Johann150** [comment]
So if I understand correctly, this is only a client issue, because the backend already handles arbitrary amounts of attachments. For example here is a post with 19 attachments https://genau.qwertqwefsday.eu/notes/8e5mjro93b
You can see that the styling would have to be adjusted too (not sure if there is already an issue for this)

**Comment by outloudvi** [comment]
Shall I draft a PR on [adding an option on the maximum number of files](https://github.com/outloudvi/misskey/commit/5f3e43b2e99ac93819f9fe34df12051ff846170e)?

**Comment by Johann150** [comment]
Maybe we should just abolish the maximum number of files completely. The maximum file sizes would be regulated by the Misskey Drive quota.

**Comment by outloudvi** [comment]
> Maybe we should just abolish the maximum number of files completely. The maximum file sizes would be regulated by the Misskey Drive quota.

Oh, that makes sense!

**Comment by tamaina** [comment]
ノートの文字数に制限があるなら、ファイルの数に制限がある方が自然そう

（ノートの文字数制限が要るかどうか怪しいところではあるけど

**Comment by tamaina** [comment]
In my opinion, first and foremost, we need to think about a suitable note UI for cases where the number of files exceeds four.

**Comment by Johann150** [comment]
> ノートの文字数に制限があるなら、ファイルの数に制限がある方が自然そう
>（ノートの文字数制限が要るかどうか怪しいところではあるけど）

I think the character limit is useful to discourage giant notes that take up too much disk space. But for files this is already solved with the Misskey drive quota.

**Comment by tamaina** [comment]
> giant notes that take up too much disk space

実は、ノートの文字数制限はハードコーディングで8192文字に制限されています。

https://github.com/misskey-dev/misskey/blob/c69b72e1999578cba15e34677ebd366482cba734/packages/backend/src/server/api/endpoints/admin/update-meta.ts#L77

**Comment by Johann150** [comment]
I think limits of note lengths are off topic here.
***
> In my opinion, first and foremost, we need to think about a suitable note UI for cases where the number of files exceeds four.

my ideas for a changed UI design:
Since we already have the gallery when clicking on an image we could just limit the number of images that are displayed inline (maybe 4 or 8). In addition to that
1. a note at the bottom like "+ 5 more images" (this was suggested in the Mastodon issue I linked)
2. overlay "+ 5" on the last image similar to the NSFW screen
3. ...

**Comment by outloudvi** [comment]
Closing (e3a5584d).
