### ISSUE TITLE
右クリックメニューが裏に行く

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#8063]
## 💡 Summary

![image](https://user-images.githubusercontent.com/28654659/146512905-37403704-e597-4cf2-a852-3dd5a443d198.png)

ドライブでファイルを左クリックしたときは手前に表示されるが、右クリックだと裏に行く

## 🙂 Expected Behavior

手前に出てくる

## ☹️ Actual Behavior

ウィンドウの裏に行ってしまう

## 📝 Steps to Reproduce

1.ドライブやノートなどのウィンドウを出す
2.ファイルやウィンドウのタイトルバーを右クリックする
3.裏に行く

## 📌 Environment

v12.100

**Comment by futchitwo** [comment]
- ウィンドウのタイトルバーを右クリックしたとき
- ドライブのアイテムを右クリックしたとき

の他、

- ページの余白を右クリックしたとき
- リンクを右クリックしたとき
- サイドメニューの「もっと！」で表示されるパネルのアイテムを右クリックしたとき

に背面に隠れました。

- ノートの三点ボタンのメニュー
- ページヘッダーの三点ボタンのメニュー
- ユーザーのアバター画像にホバーしたときに出るパネル

は背面に隠れませんでした。
