### ISSUE TITLE
モバイル画面のヘッダーをタップして出てくるメニューがドロワーではなくポップアップになることがある

### ISSUE THREAD

**Issue by xianonn** [syuilo/Misskey#8070]
## 💡 Summary

モバイル画面でブラウザの表示を**更新した直後**にヘッダーに表示されている「…」アイコンをタップするとメニューがドロワーではなくポップアップで表示されてしまう。
<img src="https://user-images.githubusercontent.com/91555638/146677273-7bce83d2-f13e-4c82-9eac-d0ab1f57e5ec.JPG" alt="ポップアップメニュー表示" width="80%">

なお、画面上のどこかを一度でも触ってから「…」アイコンをタップするとドロワーメニューで表示される。
<img src="https://user-images.githubusercontent.com/91555638/146677268-8d3ec738-b169-4ab8-a3a3-f76a44acacee.JPG" alt="ドロワーメニュー表示" width="80%">

## 🙂 Expected Behavior

「…」アイコンをタップするとドロワーメニューを表示する。

## ☹️ Actual Behavior

「…」アイコンをタップするとポップアップメニューが表示される。

## 📝 Steps to Reproduce

1. スマホのブラウザで表示を更新する
2. 他の場所は触らずにヘッダーの「…」をタップする

## 📌 Environment

Misskey.io v12.100.2

**Comment by syuilo** [comment]
Note:
ドロワーメニューが表示される条件のひとつに「タッチ操作しているか否か」というのが設定してあります
Webでは、予めタッチ操作しているか否か(≒スマホで使っているか否か)を取得する方法が存在せず、実際に画面がタッチされてからでないとタッチ操作していることを感知できないので、このIssueのケースのように起動してから初っ端でメニューを出すような操作をすると、タッチ操作の有無の取得が間に合わずそのようになります

**Comment by syuilo** [comment]
Note:
maxTouchPointsを取得する方法 ... タッチ機能付きディスプレイを使用しているが実際の操作はマウスでしか行わないような場合でもタッチ操作していると判定される
ユーザーエージェントを見る方法 ... 最近はプライバシー上の理由でUAには詳しい情報が入ってこず、UAだけでスマホ/タブレットか否かを判定するのは困難 仮に出来たとしても将来仕様が変わる可能性が高く不確実性が高い
画面サイズを見る方法 … デスクトップのブラウザでも指定のページをサイドに表示するような機能を備えているものもあり、画面サイズだけでは判定できない ただデスクトップであっても表示領域が狭いのであればドロワーメニューにしても良いかもしれない

**Comment by xianonn** [comment]
ヘッダーの tabs (ホームやグローバルを選ぶところ)のタップなら更新直後でもドロワー表示されるんですよね。

**Comment by EbiseLutica** [comment]
ドロワーを出す条件、viewpoint幅で検知するようにしてみてはどうだろう
