### ISSUE TITLE
ノートを削除してもプロフィールのノート数が減らない

### ISSUE THREAD

**Issue by moonaileen** [syuilo/Misskey#8075]
## 💡 Summary

ノートを削除してもプロフィールのノート数が減らない。
返信のノートを削除しても元のノートの返信アイコンの数字が減らない。

## 🙂 Expected Behavior

ノートを削除したらプロフィールのノート数が減る。
返信のノートを削除したら返信アイコンの数字が減る。

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/2804132/146717930-1971a8d7-e445-4292-9543-6f411cd95cef.png)
ご覧のように、２つの返信しかないのに、返信アイコンの数字が４です。その中の２つは削除されたノートです。

## 📝 Steps to Reproduce

1.ノートを書く
2.書き間違ったノートを削除する
3.ノート数が減らない

**Comment by tamaina** [comment]
仕様だと思ってた

**Comment by moonaileen** [comment]
仕様だったんですか！？

**Comment by Johann150** [comment]
`repliesCount` is incremented here https://github.com/misskey-dev/misskey/blob/5c1e2e5d7ae0e55d5a6c2e30d1b197abecc132c2/packages/backend/src/services/note/create.ts#L614

but there is no place where it is decremented. However, in the file where the decrementing should be, it e.g. does decrement the number of notes a remote instance has:
https://github.com/misskey-dev/misskey/blob/5c1e2e5d7ae0e55d5a6c2e30d1b197abecc132c2/packages/backend/src/services/note/delete.ts#L71

**Comment by Johann150** [comment]
Duplicate of #7208
