### ISSUE TITLE
メニューをドロワー表示しないオプションの追加

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8076]
## Summary
- 縦長なスマホや画面の大きいスマホが増えている中で、ドロワー表示は指を動かす距離が増える。
- 全く関係ない下部に表示されるのは感覚的ではないと思う

私的には使いにくくなったと思うし[他の人の意見も](https://p1.a9z.dev/notes/8uibnvied2)ある

**Comment by EbiseLutica** [comment]
オフにできます。
![image](https://user-images.githubusercontent.com/7106976/146781700-77d06253-62fb-4fb4-9bd9-7578f4d498fe.png)

**Comment by tamaina** [comment]
メニューは設定項目が見当たらないんじゃー

**Comment by EbiseLutica** [comment]
リアクションに限らず全体的に適用されるように、というissueにしてみましたがどうかな

**Comment by tamaina** [comment]
まあ解決策はそうなるとは思う

**Comment by tamaina** [comment]
メニューとリアクションは分けた方が良さそう
