### ISSUE TITLE
ノートのインスタンス情報の文字色が白で固定されているため、明るい背景だと視認不能になる

### ISSUE THREAD

**Issue by weepjp** [syuilo/Misskey#8079]
## 💡 Summary
- ノートのインスタンス情報が背景色＝文字色で文字列（サイト名）が読めなくなるケースがあります。

## 🙂 Expected Behavior
- ノートのインスタンス情報が背景色と異なる文字色（背景色の補色であるとより良い）で文字列が読めます。

## ☹️ Actual Behavior
- 具体的には、対象サーバーが PeerTube であるケースが確認されています（他のケースもあるかもしれません）。
![資料画像A](https://cdn.masto.host/miyonmiyonorg/media_attachments/files/107/477/443/686/377/467/original/49d62593e97deb1e.png "資料画像A")

- ドラッグをすると対象サーバー名の文字列が確認できるので、背景色と文字色の両者が白色になっていることがわかります。
![資料画像B](https://cdn.masto.host/miyonmiyonorg/media_attachments/files/107/477/444/055/555/378/original/6764d0e7f486aab3.png "資料画像B")

## 📝 Steps to Reproduce
1. 対象サーバーからどやって色情報を取得してるのかは、おいらは把握できてませんが、「背景色≒文字色」や「色がうまく取得できない」となった場合の対策をする。そうなった場合は強制的に白地の黒文字にするとか、取得した背景色の補色を求めて文字色にするとかなどしかおいらには思いつきませんでした。。
2. まったくの参考にはならない補足ですが、元ネタ的な InstanceTicker では、SNSのソフトウェアごとにデフォルト値を予め定義しています（サーバー管理者から情報変更や非表示の要請があった場合はこの限りではありません）。

## 📌 Environment
Misskey 12.100.2 (sushi.ski および honi.club ほか)
Misskey v12.87.0 (oran.ski) ほか

**Comment by EbiseLutica** [comment]
詳細ソースしっかり読んでいない身ですが、たしかMisskeyのインスタンス情報バッジは対象のホストのHTMLに記されたテーマカラーを元にしていたような？

色から明度を取って白・黒のどっちで色を出すかってやつは既に導入されているtinycolorとかでできるのでそうしたら良いかもしれない

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/12.100.2/packages/backend/src/services/fetch-instance-metadata.ts#L203

ソースコードを見つけた

**Comment by tamaina** [comment]
テーマカラーの抽出どうこうより、文字色が白固定なのが問題だったわね

https://github.com/misskey-dev/misskey/blob/12.100.2/packages/client/src/components/instance-ticker.vue

> 色から明度を取って白・黒のどっちで色を出すかってやつは既に導入されているtinycolorとかでできるのでそうしたら良いかもしれない

が解決策かと

**Comment by 4ioskd** [comment]
FYI: 最新のv12.107.1-0(misskey.io)でも視認不能になります

**Comment by xianonn** [comment]
tinycolor の isDark (輝度の値が最大の半分未満) だった場合に文字色を黒にするとこんな感じになります。
![黒文字](https://user-images.githubusercontent.com/91555638/168631460-1047985b-78e6-47a2-8a00-ee054b820369.png)
黒文字が見なれないのでちょっと違和感があるような気がしますが、まあ見やすいかなと思います。

下の画像では文字色が白のまま影を付けてみました。
![影付き文字](https://user-images.githubusercontent.com/91555638/168631627-1bf5793a-602b-4458-b387-504df21d3681.png)
背景白で文字白でもまあ見られますが、背景色がカラフルだと影があることでちょっと汚れたような感じ？もするような気がします。

上の画像は両方ともスマホの表示なのですが、PC (Windows) で表示するとフォントなのか解像度なのか白/白の影付き文字はちょっと見にくいです。
![PC](https://user-images.githubusercontent.com/91555638/168633412-81dd02b4-d381-4721-b41d-e255c6738782.png)

文字色を黒にするのと、文字色を白のまま影を付けるのだとどちらが良いと思いますか？

**Comment by weepjp** [comment]
text-shadow の加減は好みだなぁ。。

場違いかもしれないですが参考として、おいらのとこの #InstanceTicker のお話をさせて下さい。

こちらでは、text-shadow を使って、四方1px色入れるという、まどろっこしいやり方にしてます。

文字の可視化は高められても、CSSの書き方としてはとても美しくないで、本当に好みの問題にはなるかと。

#InstanceTicker では、各ソフトウェアのロゴマークデザインを貴重にした色設定をデフォルトにしています。

text-shadow の色は、文字色と同一にするか、帯の背景色と同一にするかで、バリエーションを増やしつつ文字の可視化を高めています。

`color:#000; text-shadow:#fff 1px 1px,#fff -1px 1px,#fff 1px -1px,#fff -1px -1px;`

（このCSS例の画像を置いてみる）

![image](https://user-images.githubusercontent.com/3696720/168737990-044b2f47-6ded-4912-990f-d723aac320fc.png)

![image](https://user-images.githubusercontent.com/3696720/168738228-465b51d1-22a7-4569-9bd8-205c6df08bc4.png)

右への透過グラデーションである以上は、表示名の文字数や本体側の背景色の影響次第では、相当見づらくなると思うので、それを想定して行き着いた先が「四方1px色入れる」姑息な手段でした。

まぁ、なんの参考にもならないとは思いますが、いろいろ試して文字の可視化を突き詰めた結果がこうだったというお話でした。

**Comment by xianonn** [comment]
参考。
`color:#fff; text-shadow:#000 1px 1px,#000 -1px 1px,#000 1px -1px,#000 -1px -1px;`

![影付き文字1px](https://user-images.githubusercontent.com/91555638/168823963-d2c130d0-b1b7-4324-859a-b4acf9387cf1.png)

**Comment by weepjp** [comment]
どうやら解決に向かいそうなので Close します。

**Comment by tamaina** [comment]
PullRequestがマージされれば自動でcloseされますので、勝手に閉じないでください。
