### ISSUE TITLE
Cannot read properties of undefined (reading 'series')

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#8082]
## 💡 Summary

Console error after clicking on settings

## 🙂 Expected Behavior

No error message

## ☹️ Actual Behavior

<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'series')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="https://cliq.social/assets/976.12.100.2.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">976.12.100.2.js:1</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at R (<span class="devtools-link" role="link" tabindex="-1" title="https://cliq.social/assets/976.12.100.2.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">976.12.100.2.js:1</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono, monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonymous) | @ | 976.12.100.2.js:1
-- | -- | -- | --
  | R | @ | 976.12.100.2.js:1
  | await in R (async) |   |  
  | (anonymous) | @ | 976.12.100.2.js:1
  | wn | @ | app.12.100.2.js:2
  | _n | @ | app.12.100.2.js:2
  | t.__weh.t.__weh | @ | app.12.100.2.js:2
  | Fn | @ | app.12.100.2.js:2
  | Hn | @ | app.12.100.2.js:2
  | Promise.then (async) |   |  
  | Ln | @ | app.12.100.2.js:2
  | Nn | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | D | @ | app.12.100.2.js:2
  | I | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | e.<computed> | @ | app.12.100.2.js:2
  | P | @ | app.12.100.2.js:2
  | info | @ | 8070.12.100.2.js:1
  | wn | @ | app.12.100.2.js:2
  | _n | @ | app.12.100.2.js:2
  | n | @ | app.12.100.2.js:2

</span></div>
## 📝 Steps to Reproduce

1. Sign in
2. Click on Control Panel and then Federation
3. Choose Not Responding and then choose instance
4. Click Settings
5. Error 

## 📌 Environment

12.100.2 / PostgreSQL 13.4 / nginx

**Comment by tamaina** [comment]
再現した

**Comment by Johann150** [comment]
can not reproduce in 12.100.1, so seems to be newly introduced

**Comment by tamaina** [comment]
これまだ再現しますかね

**Comment by Johann150** [comment]
I can not reproduce this any more. It must have gotten fixed somewhere along the way.
