### ISSUE TITLE
Failed to create admin account

### ISSUE THREAD

**Issue by MicroSic** [syuilo/Misskey#8087]
## 💡 Summary

I am a beginner. I run Misskey in Docker and I use image `misskey/misskey:latest`. After registering an @admin account in the website, I try to mark the account as a Administrators. I run `docker-compose run --rm web node built/tools/mark-admin @admin` but i failed. 

## 🙂 Expected Behavior

Success

## ☹️ Actual Behavior

Something goes wrong just like this:

![圖片](https://user-images.githubusercontent.com/62823814/147350033-e8204c8a-a543-4570-aadd-455a3794e15c.png)

## 📝 Steps to Reproduce

1. Create a account @admin in the website
2. Run  `docker-compose run --rm web node built/tools/mark-admin @admin` 
3.

## 📌 Environment

Ubuntu 18.04 Docker-compose

**Comment by syuilo** [comment]
正しいパスは packages/backend/built/tools/mark-admin です。
ドキュメントが間違っているので修正します🙏

FYI: Web上drアカウントを作成した場合、手動で mark-admin を実行する必要はありません。

**Comment by MicroSic** [comment]
I run `docker-compose run --rm web node packages/backend/built/tools/mark-admin @admin` and it works! 🥳

**Comment by gongjuecloak** [comment]
I run also the error message

**Comment by gongjuecloak** [comment]
![](https://user-images.githubusercontent.com/100070999/237548317-60ad4ede-1706-4719-82b2-a1815bc33066.png)
