### ISSUE TITLE
perf(MFM): sparkle effect very resource intensive

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8088]
## Summary
When there is a note with the `sparkle` MFM function on my timeline, the CPU & GPU usage of my laptop jumps very high.

I think doing the animation in JavaScript by simulating all the particles is too resource intensive and it should be done in CSS, maybe using a GIF or APNG with the sparkles prerendered.

**Comment by marihachi** [comment]
sparkleアニメーションをオプションにするのも良さそう

**Comment by syuilo** [comment]
「動きのあるMFMを無効にする」で無効にできる

**Comment by Johann150** [comment]
I want to see MFM animations, but this one animation seems to be excessively resource intensive.

**Comment by Johann150** [comment]
I just don't understand why this animation is done with a complicated and resource intensive JavaScript snippet, when it could probably easily be achieved with a simple animated graphic.

**Comment by syuilo** [comment]
![m](https://user-images.githubusercontent.com/4439005/147599192-98ec841b-0ffb-4693-bc36-9b921c3d526f.gif)
SVGを使用するようにしました

**Comment by Johann150** [comment]
Thanks 🙏
