### ISSUE TITLE
Error 401 when getting remote users, can't federate with some mastodon instances

### ISSUE THREAD

**Issue by m33m33** [syuilo/Misskey#8093]
## 💡 Summary

- Can't follow or send DMs do a remote mastodon instance.
- I was able to reproduce the issue on my own instance (https://pasta.ga) and on https://minidisc.tokyo too. The webUI shows "an error has occured" when you click on follow the remote account.
- The misskey's server logs show a 401 error
- The problem seems related to the autorization fetch, or maybe the misskey instance hasn't fetched all public keys from remote instances, according to the mastodon admin of a particular instance that I had a chat with.
- The remote mastodon instance is not even listed in the "federation" admin webui (it seems normal according to the above)

## 🙂 Expected Behavior

Following remote users
Federating with remote instance

## ☹️ Actual Behavior

I can search for a remote user, click on follow it, and I get this in my misskey instance's log:
[remote resolve-user]   WebFinger for m33@octodon.social
[remote resolve-user]   return new remote user: m33@octodon.social
[api]   failed to resolve remote user: StatusError: 401 Unauthorized

(same for other remote users)

## 📝 Steps to Reproduce

1. Connect your own misskey instance
2. Try to follow my account on this mastodon instance: m33@octodon.social
3. See the error log in misskey logs

I'm new to misskey, you may point me to additional debug informations, or way to find traces, error logs and test cases, I will happily investigate this issue as far as my skills permit, contact: @m33@pasta.ga

## 📌 Environment

Misskey 12.100.2
Node.js v16.13.1
PostgreSQL 14.1
Redis 4.0.14
Vue 3.2.24

Host: arm64, plenty of CPU, RAM, Disk ressources available.
Nginx frontend. No error seen there during the operations.

**Comment by Johann150** [comment]
From your report it doesn't seem like you enabled authorized fetch in misskey (it is disabled by default). Try adding the line
```YAML
signToActivityPubGet: true
```
to your `misskey/.config/default.yml` configuration file (or changing the value to `true` respectively).

**Comment by m33m33** [comment]
> From your report it doesn't seem like you enabled authorized fetch in misskey (it is disabled by default). Try adding the line
> 
> ```yaml
> signToActivityPubGet: true
> ```
> 
> to your `misskey/.config/default.yml` configuration file (or changing the value to `true` respectively).

You are absolutely right. Thanks a lot I will close this issue.

BTW Why on earth is it disabled by default ?

**Comment by acid-chicken** [comment]
@Johann150 thank you for your help.

> BTW Why on earth is it disabled by default ?

@m33m33 fyi: https://github.com/misskey-dev/misskey/issues/6727#issuecomment-709703543

**Comment by oluceps** [comment]
I encountered this issue at `2024.8.0` and with `signToActivityPubGet: true`

```
Sep 21 01:23:56 hastur misskey[879537]: {
Sep 21 01:23:56 hastur misskey[879537]:   code: 'BRIEF_REQUEST_INTERVAL',
Sep 21 01:23:56 hastur misskey[879537]:   info: { remaining: 0, reset: 1726856636, resetMs: 1726856636840, total: 1 }
Sep 21 01:23:56 hastur misskey[879537]: }
Sep 21 01:23:58 hastur misskey[879537]: ERR  1        [queue deliver]        failed(UnrecoverableError: 401 Unauthorized
Sep 21 01:23:58 hastur misskey[879537]:     at DeliverProcessorService.process (file:///misskey/packages/backend/built/queue/processors/DeliverProcessorService.js:140:27)
Sep 21 01:23:58 hastur misskey[879537]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 21 01:23:58 hastur misskey[879537]:     at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)
Sep 21 01:23:58 hastur misskey[879537]:     at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)) id=410 attempts=1/12 age=4291ms to=https://wayland.social/users/compositor/inbox
Sep 21 01:24:01 hastur misskey[879537]: ERR  1        [queue deliver]        failed(UnrecoverableError: 401 Unauthorized
Sep 21 01:24:01 hastur misskey[879537]:     at DeliverProcessorService.process (file:///misskey/packages/backend/built/queue/processors/DeliverProcessorService.js:140:27)
Sep 21 01:24:01 hastur misskey[879537]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 21 01:24:01 hastur misskey[879537]:     at async Worker.processJob (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:445:28)
Sep 21 01:24:01 hastur misskey[879537]:     at async Worker.retryIfFailed (/misskey/node_modules/.pnpm/bullmq@5.10.4/node_modules/bullmq/dist/cjs/classes/worker.js:634:24)) id=411 attempts=1/12 age=4300ms to=https://wayland.social/users/compositor/inbox
```
