### ISSUE TITLE
ファイルのプレビューは許可された形式しか表示しないようにする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8111]
## Summary
クライアント側でもoctet-streamな画像を読み込んで表示させるような仕様にならないようにするべき

**Comment by syuilo** [comment]
これはなぜ？

**Comment by tamaina** [comment]
なんか純粋にバグる

RAW画像の例→ https://p1.a9z.dev/notes/8v0tytp7e7

**Comment by tamaina** [comment]
RAW画像だからバグるのかもしれないけど、octet-streamかつattachmentであるとわかりきっている画像を表示しようとするような実装にすべきではないと思う

**Comment by tamaina** [comment]
説明不足感あったので補足すると

1. RW2はtype: image/x-panasonic-rw2となる
2. クライアントは、image/から始まるからイメージとしてプレビューしようとする
3. わけわからん画像を表示しようとするのでバグる
