### ISSUE TITLE
Remote follow support through OStatus

### ISSUE THREAD

**Issue by hynet-mel** [syuilo/Misskey#8114]
## Summary

Apparently the endpoint for `ostatus_subscribe` isn't something that's implemented, this ends up giving 404 whenever I remotely try to follow someone through my Misskey instance.

**Comment by Johann150** [comment]
Misskey does not support OStatus https://github.com/misskey-dev/misskey/issues/2493#issuecomment-416865662

**Comment by KisaragiEffective** [comment]
triage: 多分won't fix
cc @syuilo
