### ISSUE TITLE
Unifying Misskey-specific IRIs in JSON-LD `@context`

### ISSUE THREAD

**Issue by gudzpoz** [syuilo/Misskey#8116]
## Summary

Misskey is using the URL of the instance in the `@context` of JSON-LDs: https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/remote/activitypub/renderer/index.ts
```js
{
  misskey: `${config.url}/ns#`,
  '_misskey_content': 'misskey:_misskey_content',
  '_misskey_quote': 'misskey:_misskey_quote',
  '_misskey_reaction': 'misskey:_misskey_reaction',
  '_misskey_votes': 'misskey:_misskey_votes',
  '_misskey_talk': 'misskey:_misskey_talk',
  'isCat': 'misskey:isCat',
}
```
But in the [expanded or flattened form](https://json-ld.org/spec/FCGS/json-ld-api/20180607/#expansion) of the JSON-LD documents, using non-uniform `@context` leads to different outputs, e.g.:
```js
[{ ... // instance 1
  "https://misskey.io/ns#isCat": true,
... }]
[{ ... // instance 2
  "https://instance1.domain/ns#isCat": true,
.. }]
```
In this example, this makes it impossible to tell whether a person is a cat after JSON-LD operations.

In mastodon (or LitePub for example), they are using unified domain names for all instances:
```js
{
  "toot": "http://joinmastodon.org/ns#",
  "Emoji": "toot:Emoji"
}
```
so that `Emoji`'s expanded form is always `http://joinmastodon.org/ns#Emoji`. Is this possible for Misskey to do this too? Thank you!

**Comment by mei23** [comment]
@syuilo 
`https://misskey-hub.net/ns#` にでもしときゃいいかしら

**Comment by syuilo** [comment]
> @syuilo `https://misskey-hub.net/ns#` にでもしときゃいいかしら

よさそう
