### ISSUE TITLE
Pizzaxのプロパティアクセスを廃止

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8120]
## Summary

stateへのプロパティアクセス廃止して全部asyncなget関数とかで取得するようにすれば、https://github.com/misskey-dev/misskey/pull/8098 取り込み後でもstoreを事前にreadyする必要がなくなったり一度に全てのデータをメモリにロードせずに良くなって良いかなと思ったけど、全てのコンポーネントをComposition APIに移行してからの方が良いかも

**Comment by tamaina** [comment]
いったんstate/reactiveStateをデフォルト値で埋めておいて必要な時にreadyするようにすれば良いのでは

**Comment by tamaina** [comment]
（なるべくstateではなくreactiveStateを使うようにする

**Comment by tamaina** [comment]
（そういえば: reactiveStateあれば単純なmakeGetterSetterは要らないんじゃ？と思ったけど何か使い分けがあるのだろうか

**Comment by tamaina** [comment]
> 全部asyncなget関数とかで取得する

get関数の返値を他のコンポーネントからの変更にリアクティブに対応するとかなると沼に嵌りそうなのでやめたほうがいい気がする  
(なるべくreactiveStateを参照するようにすればええんでない？

**Comment by syuilo** [comment]
> get関数の返値を他のコンポーネントからの変更にリアクティブに対応するとかなると沼に嵌りそうなのでやめたほうがいい気がする

ref返す予定だったけどダメかしら

**Comment by tamaina** [comment]
ref返すならasyncなget関数にする必要はないと思う

**Comment by tamaina** [comment]
つまり

```
<template>
<div>{{ hoge }}</div>
<div>{{ fuga }}</div>
</template>

<script setup>
import { defaultStore } from '@/store';

const { hoge, fuga } = defaultStore.reactiveState;
</script>
```

みたいにすればよくない？と思った

**Comment by syuilo** [comment]
事前のreadyの必要性とメモリロードの必要性を無くすためには関数にするしかないけど、どちらもそこまで重要じゃないし良いか

**Comment by syuilo** [comment]
デフォルト値を非同期に決定したい場合があり、やっぱりやりたくなってきた

**Comment by syuilo** [comment]
あと事前にreadyする必要があると、複数のファイルからimportされる場合にタイミングによってはエラーになる可能性がありそう

**Comment by syuilo** [comment]
と思ったけどそうするとかなりの数のVueコンポーネントがSuspenseにならざるを得ないなど代償が大きすぎるのでやっぱり保留
