### ISSUE TITLE
NodeInfo にユーザー数と投稿数の情報を追加する

### ISSUE THREAD

**Issue by xianonn** [syuilo/Misskey#8123]
## Summary

[FediDB](https://fedidb.org/software/misskey)、[Fediverse Observer](https://misskey.fediverse.observer/list)、[The Federation](https://the-federation.info/misskey)(※) のような Fediverse のインスタンスのデータを集計するサイトがありますが、その多くは NodeInfo からデータを取得しているようです。
※The Federation については Misskey のデータを取得する際に /meta API を使用している。

Misskey も NodeInfo の出力に対応していますが、ユーザー数と投稿数に関するデータは出力されていません。

以前は NodeInfo にユーザー数と投稿数が出力されていたこともあるようですが、#4239 によると nodeinfo にアクセスするとしばらく投稿も TL 参照もできなくなってしまうということで無効化されたようです。

しかし現在のバージョンではトップページや /about ページ等でユーザー数や投稿数が表示されていますが、それによって投稿や TL 参照ができなくなるということはなく、NodeInfo にユーザー数と投稿数が出力できない理由はなくなったと考えます。

Fediverse のソフトウェアを比較する際ユーザー数や投稿数の多さも重要な指標になると思いますので、これらのデータを NodeInfo に追加して表示されるようにしたいです。

なお、私のおひとりさまインスタンスでは[このようにして](https://gitlab.com/xianon/misskey/-/commit/b16e224fcc707c9c883baf0565e9bafec37611cf) NodeInfo にユーザー数と投稿数に関するデータを出力するようにしていますが、/stats API で 1 ヶ月または半年のアクティブユーザー数等を取得できるようにして NodeInfo から /stats API を取得するようにしてもいいかもしれません。

**Comment by syuilo** [comment]
やっぱりインスタンスによってはかなり重くなる気がする

**Comment by xianonn** [comment]
クエリ自体はかなり重いんですよね。
チャートのデータを取ってくるようにすれば軽くなるとは思うんですが、データベースから直接取ってきたデータとチャートのデータが一致しないのが少し気になる。

**Comment by xianonn** [comment]
チャートから取ってくるにしてもローカルユーザー数しか取ってこれませんでした。
おそらく負荷がかかっているのはレコード数の多い投稿数の取得の方なので、今のままでチャートから取ってくるのは微妙かも。

私のインスタンスでの[元の実装](https://gitlab.com/xianon/misskey/-/commit/b16e224fcc707c9c883baf0565e9bafec37611cf)では TypeORM で1時間キャッシュされるようにしていましたが、同じようにして1日くらいキャッシュしても良いのかも。

**Comment by mei23** [comment]
コメント機能はない (FBみたいなコメント付きのSNSじゃないので…リプライはコメントじゃないと思う)
投稿数なので削除されてる可能性のある投稿レコードの値をカウントするのは違うと思う
ので
localPosts: charts/notes の local inc
localComments: 0
でいいんじゃないかしら

**Comment by mei23** [comment]
あ、いや違う。コメント分けないならそもそもチャート見なくていいわね。
localPosts: 普通にローカル投稿数
localComments: 0

**Comment by xianonn** [comment]
チャート見ずにローカル投稿数って`Notes.count({ where: { userHost: null } })`ということですかね？
チャート見なくても localComments のクエリがなくなって負荷は減るけど。

**Comment by mei23** [comment]
そう、statsのoriginalNotesCountとおなじ
https://github.com/misskey-dev/misskey/blob/0b462feff6be22f0da8ea773a2a5af24d6300240/packages/backend/src/server/api/endpoints/stats.ts#L63
