### ISSUE TITLE
The Pixelfed icon is not displayed

### ISSUE THREAD

**Issue by HSDChannel** [syuilo/Misskey#8127]
![image](https://user-images.githubusercontent.com/72506029/148649297-db3f469d-483c-4271-80ff-343d96eefe7b.png)

**Comment by Johann150** [comment]
The problem is that pixelfed advertises its favicon as a `link` with `rel="shortcut icon"` but Misskey expects `rel="icon"`.
https://github.com/misskey-dev/misskey/blob/149edaecab3d160a1f480160caee055e2aff28bf/packages/backend/src/services/fetch-instance-metadata.ts#L159
