### ISSUE TITLE
Gallery page is missing margins

### ISSUE THREAD

**Issue by outloudvi** [syuilo/Misskey#8128]
## 💡 Summary
Unlike other sub-pages, there is no margin between the gallary page and the frame. Also, there is no margin between the icons and the text "Recent posts" and "Popular posts".

## 🙂 Expected Behavior
Margins exists to make the page look better and correspond to the design with other pages.

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/19144373/148651113-2fce2886-2384-4278-850b-be6200c7d1ec.png)

## 📝 Steps to Reproduce
1. Go to `https://INSTANCE_HOST/gallery`.

## 📌 Environment
Misskey v12.101.1, Firefox 97.0 alpha 1

The problem persists on Chromium so it does not seem to be a browser-compatability issue.

**Comment by futchitwo** [comment]
fixed at https://github.com/misskey-dev/misskey/commit/699f24f3dcdb156838eb70602885c0b2cdd02cbc

**Comment by Johann150** [comment]
The margin between the icons and text still seems to be absent.

**Comment by outloudvi** [comment]
Seems fixed as of Firefox Nightly 2024-02-25 and Misskey 2024.2.0-io.2d, closing.
(Using misskey.io to test as I don't have a gallery on my instance.)

![Normal margin on the Gallery page](https://github.com/misskey-dev/misskey/assets/19144373/8c019c15-53f9-4e02-8495-c9ac1bdbe731)
