### ISSUE TITLE
pizzaxから(静的な)stateを削除する？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8129]
## Summary
静的なstateを別に定義しておく必要のある場面はないように思える。reactiveStateがあれば十分そう。  

削除する理由は…メモリの節制とか。

**Comment by tamaina** [comment]
パフォーマンス的にstateを使ったほうがいい場面も多いからナシだな

**Comment by syuilo** [comment]
> パフォーマンス的にstateを使ったほうがいい場面も多いからナシだな

例ある？

**Comment by tamaina** [comment]
たとえば絵文字ピッカーの表示でポップアップにするかどうか設定から検討する↓

https://github.com/misskey-dev/misskey/blob/b3548b5df50f383bdc309bb03f9330e8bd08e439/packages/client/src/components/emoji-picker-dialog.vue#L6

のような場面ではリアクティブである意味がない。  
リアクティブが必要のない場面でリアクティブにするとvueのコストが増えて返って重くなる（かもしれないという感覚的な判断）

**Comment by syuilo** [comment]
あーそうね
そういう理由でreactiveStateと静的stateを分けてたの思い出した
特に大量にレンダリングされるコンポーネントだと影響ありそう
