### ISSUE TITLE
Follows/Followers Visibility changes won't be saved unless clicking on an other checkbox

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#8130]
## 💡 Summary
Follows/Followers Visibility changes won't be saved unless I clicking on an other checkbox.

## 🙂 Expected Behavior
Changes should be saved when I modifying Follows/Followers Visibility in Privacy Settings.

## ☹️ Actual Behavior
It seems that the saving operation will only be executed when I clicking on a checkbox. So in the case I just change the visibility, that change won't be saved.

## 📝 Steps to Reproduce

1. Navigate to Settings -> Privacy, find Follows/Followers Visibility
2. Change the visibility only
3. Navigate to anywhere else and then back to step 1.

## 📌 Environment
- Misskey 12.101.1 (docker)
- Firefox 95.0.2

**Comment by 4ioskd** [comment]
This issue isn't solved.
Same behavior is occured in latest misskey 12.103.1

**Comment by Johann150** [comment]
`@update:modelValue="save()"` needs to be added to `ffVisibility` setting in `packages/client/src/pages/settings/privacy.vue`

**Comment by tamaina** [comment]
:(bind)をv-model:にしなかった…というわけでもなさそう？

**Comment by tamaina** [comment]
(v-modelの省略記号ってあったっけ

**Comment by Johann150** [comment]
> :(bind)をv-model:にしなかった…というわけでもなさそう？

`v-model` is used, but if I understand correctly the issue is that the values are saved in the client, but they also have to be saved on the server using the API in the `save` function.

> (v-modelの省略記号ってあったっけ

I think not https://v3.vuejs.org/guide/migration/v-model.html#v-model-arguments

**Comment by Johann150** [comment]
~~I wonder if there could be `@update` on the `_formRoot` element to catch all the different update events?~~
That would not be a good idea because that would also call the `save` function also for properties that can not be saved via the API, causing unnecessary network congestion and/or server load.
