### ISSUE TITLE
「Bot防御」設定でreCaptchaの選択が無視される

### ISSUE THREAD

**Issue by nice714106tall** [syuilo/Misskey#8132]
## 💡 Summary
*（スマホ用ページで確認しました。PC版ではまだ確認していません）*
bot防御の設定でreCaptchaを使用するよう設定しているにも関わらず、hCaptchaが表示されてしまう

## 🙂 Expected Behavior
- reCaptchaが表示される

## ☹️ Actual Behavior
- hCaptchaが表示されるが、APIキーはGoogle reCaptchaの物なのでエラー表示となる

## 📝 Steps to Reproduce

1.管理者アカウントでログインする
2.画面左下のハンバーガーメニューから「コントロールパネル」を開く
3.「設定」グループ内の「🔒セキュリティ」を開く
4.「Bot防御    なし(非推奨)」をクリック
5.「reCaptcha」のラジオボタンにチェック、然るべきサイトキーとシークレットキーを入力し「💾保存」をクリックする
6.プレビュー表示にサイトキーが正しくない旨のエラーを吐いているhCaptchaが表示される
7.その後、アカウントの新規作成をする際にも6.と同様のエラーを吐いたhCaptchaが表示される

## 📌 Environment
misskey 12.101.1
![IMG_20220110_223329](https://user-images.githubusercontent.com/83388768/148781110-1adf46d8-54f9-4dbe-ae38-a9f59278e3e3.jpg)
![IMG_20220110_223259](https://user-images.githubusercontent.com/83388768/148781116-78d94d55-7e6e-4ee9-b126-1224ffb6e15c.jpg)

**Comment by tamaina** [comment]
#8133 と #8134 が関わっていそう

**Comment by tamaina** [comment]
ブラウザを再読み込みしてコントロールパネルを開かずにアカウント新規作成するとちゃんとreCAPTCHAが表示されるはず

**Comment by nice714106tall** [comment]
> ブラウザを再読み込みしてコントロールパネルを開かずにアカウント新規作成するとちゃんとreCAPTCHAが表示されるはず

ありがとうございます。その方法で解決しました。
