### ISSUE TITLE
コントロールパネルのreCaptcha設定で、hCaptchaがreCaptchaの動作を上書きするのに対応していない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8133]
## 📝 Steps to Reproduce

1. コントロールパネル - セキュリティ - Botプロテクション を開く
2. hCaptchaを選択
3. reCAPTCHAを選択

## 🙂 Expected Behavior
プレビューにreCAPTCHAが表示される

## ☹️ Actual Behavior
プレビューにhCaptchaが表示される

## 📌 Environment
Misskey @ 12.101.1

**Comment by acid-chicken** [comment]
`recaptchacompat=off` で直るらしい https://docs.hcaptcha.com/configuration/
