### ISSUE TITLE
匿名投票を可能に

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#8145]
## Summary

現在のMisskeyの投票機能には匿名で投票する機能がなく、通知とグラフの推移を見れば誰が投票したのか分かる状態になっている。

通知とグラフを一緒に見れば匿名性が失われると考えるので、追加してほしい。

## 想定される挙動
匿名投票と設定すると、投稿者には通知が届かないようにする。
これによって完全に誰がどこに投票しているのか分からなくなる。

**Comment by 4ioskd** [comment]
when i have made a poll and enabled "Votes on polls" in Notification settings, i could easily know who votes via my notification. this kind of information is a very sensitive one for a voter. Poll must be anonymized.

**Comment by syuilo** [comment]
投票されたときに通知が作成される必要ないかも

**Comment by 4ioskd** [comment]
投票のノートがバズると当然誰か投票したか、という通知が増えてサーバーに負荷がかかるという点でも、通知がわざわざ作成される必要はあるのかは微妙な気がしますね

**Comment by CyberRex0** [comment]
v13で誰が投票したという通知が削除されたのでとりあえず解決扱い
