### ISSUE TITLE
NSFWに設定しているギャラリーが一覧に表示されてしまう

### ISSUE THREAD

**Issue by SanMurakami** [syuilo/Misskey#8149]
## 💡 Summary
NSFWに設定しているギャラリーがギャラリー一覧にサムネイル付きで表示されてしまう。

## 🙂 Expected Behavior
NSFWが設定されているギャラリーは表示しない or サムネイルを隠した上で警告

## ☹️ Actual Behavior
サムネイルを含んだ状態で表示されてしまう

## 📝 Steps to Reproduce

1.NSFWでギャラリーを作成
2.インスタンスのギャラリー一覧を開く
3.

## 📌 Environment
v12.101.1

**Comment by kabo2468** [comment]
related to #7591

**Comment by CyberRex0** [comment]
修正お願いしたい @syuilo

**Comment by acid-chicken** [comment]
@CyberRex0 チケット内容の同意はするけど、メンバーの作業内容は（別途契約でもない限りは）基本的に自身の裁量によって決定されるべきなので、実装を催促するぐらいならご自身で PR を投げていただいた方が話が早いと思います。

**Comment by CyberRex0** [comment]
連投はしてないですね
#7591 でも同じようなの投げてるの忘れてました

**Comment by acid-chicken** [comment]
認識に誤りがありました、申し訳ありません。

**Comment by syuilo** [comment]
> 修正お願いしたい @syuilo

ギャラリーテコ入れするか

**Comment by acid-chicken** [comment]
@syuilo 書き忘れで不甲斐ないんだけど nsfw で blurhash をキープするようにするのだけ書いてみた

**Comment by acid-chicken** [comment]
https://6428f7d7b962f0b79f97d6e4-vturhtgbjw.chromatic.com/?path=/story/components-mkgallerypostpreview--default
https://6428f7d7b962f0b79f97d6e4-vturhtgbjw.chromatic.com/?path=/story/components-mkgallerypostpreview--sensitive
