### ISSUE TITLE
packedUserの一部のプロパティが"falsy"になっているが、普通のbooleanにしたほうがいいのでは？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8153]
## Summary
[packedUser](https://github.com/misskey-dev/misskey/blob/9885c6ba6cb17c38ff723e529834ec2fff210d86/packages/backend/src/models/repositories/user.ts#L210)では、一部のbooleanプロパティで`detailed: !true`の場合かつその値がfalseの場合、undefinedを返すという仕様がある。

通信量の削減には焼け石に水であるにもかかわらず、このような変則的な型だとJavaScript以外の言語だと扱いにくくなるらしい。  
変なことはせず普通にfalseを返すべきだと思う。

**Comment by KisaragiEffective** [comment]
fixed by #12096
