### ISSUE TITLE
Reaction can't be reordered in Firefox 96.0.2

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#8166]
## 💡 Summary

![image](https://user-images.githubusercontent.com/31585494/150522296-b327cd23-4f27-40ec-8db0-5b24fcf08a1a.png)
If you move the cursor while holding down the left mouse button, only the cursor will move.

## 🙂 Expected Behavior

Reactions can be reordered as well as Chromium Edge.

## ☹️ Actual Behavior

Reactions can't be reordered.

## 📝 Steps to Reproduce

1. Install Firefox if needed.
2. Sign in Misskey.io if needed and go to Settings->Reactions.
3. Try to drag an emoji.

## 📌 Environment

- Firefox 96.0.2
- Windows 10.0.19044(21H2)

**Comment by ThatOneCalculator** [comment]
This is also a problem for me. 

- Mozilla Firefox 96.0.2
- Linux
- Misskey Master, af6d52e4c86695ca36147e1c830b7374ded65c02

**Comment by MineCake147E** [comment]
No longer reproducing.
Closing.
