### ISSUE TITLE
ドライブに画像ファイルをアップロードするときオリジナル画像を破棄してwebpublicのみ保持する機能がほしい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8167]
Origin: #7704

## Summary
ドライブ容量を削減できるので、ユーザーとサーバー管理者双方にメリットがある

### API
- drive/files/createにオリジナルを破棄するオプションを設定
- (optional) 既存のファイルに対してオリジナル画像を破棄する操作をするエンドポイントがあるとうれしい

### Client
- 投稿フォームにペースト/D&Dするときは基本的にオリジナル画像は破棄する (動作は設定で変更できるといいかも)
- ドライブページ/ウィンドウでアップロードする場合
  * ~~オリジナルを維持する~~
  * ~~(optional) ↳メニューでオリジナル画像を破棄する操作ができるとよい~~
  * ~~アップロードと同時に選択するようなUX/UIは煩雑そう~~ → コメントに新たな案を書いた

## 関連
#5694

**Comment by mei23** [comment]
> drive/files/createにオリジナルを破棄するオプションを設定

クライアントで変換するのそんなに難しくないからクライアントで変換しちゃったほうがメリットあるのだわ
変換した後は`isWebpublic`とか適当なプロパティ回して、サーバー側ではリモートと同じようにwebpublicを生成しない方に回せばOK。
https://github.com/misskey-dev/misskey/issues/7704#issuecomment-1019031823

**Comment by mei23** [comment]
> - ライブページ/ウィンドウでアップロードする場合
>   - オリジナルを維持する
>   - (optional) ↳メニューでオリジナル画像を破棄する操作ができるとよい
>   - アップロードと同時に選択するようなUX/UIは煩雑そう

転送量課金, オブジェクトストレージのトランザクション課金, オブジェクトストレージの最低保存期間課金, サーバーでの処理 が減らないから、一旦格納して後削除ってあまり嬉しくないんだわ。

**Comment by tamaina** [comment]
こういう感じのUIでオリジナルを保持するかしないか指定できればいいなと思った

![image](https://user-images.githubusercontent.com/7973572/150629306-438e6d0c-f988-4a4b-9d61-5536268f1f48.png)

**Comment by tamaina** [comment]
Composition APIにしがてらメニューをいじるか
