### ISSUE TITLE
画像の圧縮(webpublic化)をクライアントサイドで行う

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8173]
## Summary
https://github.com/misskey-dev/misskey/issues/7704#issuecomment-1019031823  
https://github.com/misskey-dev/misskey/issues/8167#issuecomment-1019033441

#8167 (webpublicのみ保持する) 場合、画像の圧縮はブラウザサイドで行い、サーバーは圧縮作業をパスする。

画像圧縮は現代の半導体を使っていれば負荷は気にならないと思う。  
一方でアップロード時の通信量を圧縮できるのは大きい。

## 圧縮作業のパススルーについて
アップロード時にisWebpublicとしてwebpublicとして圧縮済みであるフラグを付けるのもいいけど、サードパーティアプリが適切なファイルを送ってくるとは限らないと思う。

そこで、generateAltsで「元データがwebpublicとして使えるか検査し、使えるようであればwebpublicをnullにする」のような処理を作ればwebpublicであることを確実にしつつ圧縮を省略できると思った。

**Comment by mei23** [comment]
> 「元データがwebpublicとして使えるか検査し、使えるようであればwebpublicをnullにする」

えー、1回開いてサイズ/orientation/EXIFまで見るのかしら
→ でも、どうせサムネのために1回は開くから別にいいのかも

**Comment by tamaina** [comment]
うん、generateAltsを実行すれば一回は開くので処理が増えるわけではなさそう

https://github.com/syuilo/misskey/blob/59520c31fde073f7cb0ede81162898f2bc340b4f/packages/backend/src/services/drive/add-file.ts#L184
