### ISSUE TITLE
リモートファイル未保存の場合のリモートファイル処理を減らす

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#8175]
## Summary
リモートファイル未保存の場合でも、各種メタデータのためにフルダウンロードと展開を行っているが帯域と処理能力の無駄なので軽減したい。

### blurhash
これは連合できる https://github.com/misskey-dev/misskey/issues/8174
MisskeyはしないがMastodonはしてくる

### type
実装によるが連合されてくるはず、または probe-image-size でヘッダだけで取れるかも。

### width, height
MisskeyはしないがMastodonは連合してくる、または probe-image-size でヘッダだけで取れるかも。
※ Misskeyはwebpublicの値をDBに格納してない

### orientation
probe-image-size でヘッダだけで取れるかも。

### size
HTTPヘッダで取れるかどうか
でもこれいる？

### md5
これいる？

## メモ
- type, width, height, orientation, size, md5 はAPIで返しているけど、originalとwebpublicを区別してないなど嘘をついてる部分がある。
- width, height, orientation は、photoswipe で使っている。(このパラメーターなくてもよしなにやってほしいけど)

**Comment by syuilo** [comment]
sizeとmd5はどちらも実際にファイルとして保存している場合にしか主に用途がないプロパティだから未保存なら省略されても大きな問題にはならなそう

**Comment by mei23** [comment]
Blurhash https://github.com/misskey-dev/misskey/issues/8174 だけで十分そう
