### ISSUE TITLE
No `img-src` or `media-src` in `Content-Security-Policy` header for files or media proxy

### ISSUE THREAD

**Issue by shibaobun** [syuilo/Misskey#8187]
## 💡 Summary

For the file drive or media proxy, there is no "img-src" or "media-src" in the Content-Security-Policy.
If a browser adds an HTML viewer or otherwise embeds the source file, the image/video will not show.
This can be manually overridden via a reverse-proxy, but isn't ideal.

## 🙂 Expected Behavior

When loading a video from the file drive or media proxy in Chromium 97.0.4692.71, the video should show.

## ☹️ Actual Behavior

Video is blocked with a CSP Warning:
![20220124_22h55m07s_grim](https://user-images.githubusercontent.com/73508390/150908047-a7a2d0e7-62ce-417e-8a5a-0b7dc77191f0.png)

## 📝 Steps to Reproduce

1. Add a video to the file drive or media proxy
2. Attempt to view the link directly

## 📌 Environment

All installations

**Comment by shibaobun** [comment]
Since this is a simple fix, I have included a PR that includes the changes. Please let me know if there is anything that is needed!

**Comment by tamaina** [comment]
> If a browser adds an HTML viewer or otherwise embeds the source file

がどのような状況なのかが想像がつかなかった（私が使っている状況ではエラーが出ないので）

**Comment by shibaobun** [comment]
> がどのような状況なのかが想像がつかなかった（私が使っている状況ではエラーが出ないので）

i think chrome loads videos in their own viewer that is html, if you right click and view source you can see that it displays the `<video>` tag in an html page, which is the reason why this bug errors without `media-src`. however, using `curl` it's just a binary file.

example from loading a video in chromium:
![20220126_13h25m31s_grim](https://user-images.githubusercontent.com/73508390/151223892-bfc5c1d3-19a3-4cce-89b5-3d851757a4ff.png)
