### ISSUE TITLE
削除したノートがタイムラインから自動で消えない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#8201]
## 💡 Summary

ノートを消した場合、本来はタイムラインからノートが消えるが、最新版ではノートを削除してもリロードするまで削除したノートがタイムラインから消えない。

## 🙂 Expected Behavior

削除したタイミングでノートがタイムラインに表示されなくなる

## ☹️ Actual Behavior

削除しても表示がタイムラインに残り続ける

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey v12.102.0

**Comment by syuilo** [comment]
fixed

**Comment by tamaina** [comment]
ん？コミットどれ？

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/commit/389350ba770f9332b0abb6f651e39450c6048a2f

**Comment by nullobsi** [comment]
I am still having this issue on the latest development branch

**Comment by tamaina** [comment]
@nullobsi I'd like to see the console error log if possible.

**Comment by nullobsi** [comment]
@tamaina When I delete the note, there is no error in DevTools. It just doesn't disappear
