### ISSUE TITLE
チャットで他インスタンスユーザーとの会話が見えない

### ISSUE THREAD

**Issue by numaaqours** [syuilo/Misskey#8204]
## 💡 Summary

チャットで他インスタンスユーザーとの会話が見えない

## ☹️ Actual Behavior

他インスタンスのユーザーとチャットを開始すると会話内容が見えない。モバイル、PCともに発生
## 📌 Environment

Android: Chrome 97.0.4692.98
iOS: MobileSafari 15.3
Windows: Microsoft Edge 97.0.1072.69

**Comment by tamaina** [comment]
チャット廃止
