### ISSUE TITLE
「クリップ」ページが開かない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#8206]
## 💡 Summary

サイドメニューからクリップを選んでもクリップページが表示されない

## 🙂 Expected Behavior

クリップ一覧が表示される

## ☹️ Actual Behavior

表示されない
## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey v12.102.1

**Comment by syuilo** [comment]
fixed
