### ISSUE TITLE
投稿のNSFW画像を表示したあとにリアクションが更新されると画像が非表示になる

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#8208]
## 💡 Summary

![2022-01-28_00-01-04_vivaldi](https://user-images.githubusercontent.com/28654659/151385025-b60cd422-0b90-4e98-bc23-b97d744435bd.gif)

## 🙂 Expected Behavior

リアクションが更新されても画像はそのまま

## ☹️ Actual Behavior

リアクションがついたり消えたりすると画像のマスクが再度表示される

## 📝 Steps to Reproduce

1.NSFW設定した画像を添付して投稿する
2.その投稿の画像を表示する
3.リアクションをつける（つく/消す）

## 📌 Environment

v12.102.0

**Comment by tamaina** [comment]
仕様かと思っていた
