### ISSUE TITLE
weird profile bug if you remove the trending widget

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8214]
## 💡 Summary

Currently there is a bug where profiles will show as 2 columns (picture below) instead of 1 if the trending widget is turned off.
![image](https://user-images.githubusercontent.com/98621152/151627890-511a1ef6-97f0-400b-9896-5a1da851552f.png)

after adding trending:
![image](https://user-images.githubusercontent.com/98621152/151628300-d5e78032-0a4c-4c14-b102-9482e7255dd7.png)

in order to get the profiles to display normally, the trending widget must be re-added and must be below the calendar.
Resizing the window does not affect the 2-column layout.

## 🙂 Expected Behavior

Profiles display normally

## ☹️ Actual Behavior

Profiles display in 2 columns, with "images" and "activity" placed to the right of bio and notes.

## 📝 Steps to Reproduce

1. go to edit widgets
2. remove the trending widget
3. visit a user profile with images

## 📌 Environment

12.102.1

**Comment by nullobsi** [comment]
I am able to reproduce this even with the trending widget

**Comment by KisaragiEffective** [comment]
triage: `2024.5.0` always render user's page as 2-column layout no matter if trending widget is enabled.
