### ISSUE TITLE
サイドビューで開くをONにすると画面推移ができなくなる

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#8217]
## 💡 Summary
サイドビューで開くをONにすると画面推移ができなくなる

## 🙂 Expected Behavior
サイドビューで開く

## ☹️ Actual Behavior
どこにも移動できない

## 📝 Steps to Reproduce

1.設定→全般→デフォルトのナビゲーションのサイドビューで開くをONにする
2.再読み込み
3.移動できなくなる

## 📌 Environment
Misskey 12.102.1
デフォルトUI

そもそもサイドビュー自体が壊れてるかも（右クリックメニューからもサイドビューで開かない）

**Comment by Johann150** [comment]
is this related to #7890 ?

**Comment by tamaina** [comment]
duplicate of #7890
