### ISSUE TITLE
Allow instance admins to change the number of max additional information fields

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8225]
## Summary

If the number of max additional profile fields could be configured beyond 4, that'd be great.

**Comment by ThatOneCalculator** [comment]
Fixed by #8234 !

**Comment by syuilo** [comment]
Reopen this because the PR has not been merged yet.

**Comment by syuilo** [comment]
Mastodonが4つまでしか表示できなかった気がするけどどうだろう

**Comment by Johann150** [comment]
Pleroma also allows a larger number of fields so I think we should not be limited by Mastodon.

**Comment by syuilo** [comment]
I don't feel the need to allow admins to set limits.
As with attachments of note, I think it is best to just relax the limit to about 16.

**Comment by Johann150** [comment]
Why is it necessary to set a limit at all?

**Comment by syuilo** [comment]
If there is no limit, theoretically, it would be possible to store several MB of data.

**Comment by ThatOneCalculator** [comment]
> Mastodonが4つまでしか表示できなかった気がするけどどうだろう

Mastodon can display up to 20, and the masto-tweaks / glitch-soc versions let instance admins configure the number
