### ISSUE TITLE
Adding reactions to default reaction menu doesn't work

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8226]
## 💡 Summary

Under /settings/reaction, I can't click the `+` button, reorder items, or even preview.

## 📝 Steps to Reproduce

1. Upgrade server to latest release
2. Go to /settings/reaction

## 📌 Environment

Latest on master
Tested on Firefox, Chromium, and Surf.

**Comment by Johann150** [comment]
related to #8166

**Comment by ThatOneCalculator** [comment]
> related to #8166 

Somewhat. Before (at the time of commenting), i was able to do it fine on other browsers. Now i cant on anything

**Comment by nullobsi** [comment]
I can't reproduce this on Chromium with the latest dev build, perhaps it has been fixed already

**Comment by ThatOneCalculator** [comment]
> I can't reproduce this on Chromium with the latest dev build, perhaps it has been fixed already

Switched over to dev and it's fixed. Just a `master` issue.

**Comment by ThatOneCalculator** [comment]
Update: adding/deleting works on Firefox, but re-ordering doesn't. Guess it's more related again to #8166 now.
