### ISSUE TITLE
ウィンドウをポップアウトしてもページが見つからないエラーが出る

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8227]
## 💡 Summary
Popping out the window gives a page not found error

## 🙂 Expected Behavior
ちゃんとウィンドウの内容が表示される

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/7973572/151702403-a76170db-4245-4164-9ad3-9ef8df7538ce.png)

## 📝 Steps to Reproduce

1. ウィンドウを開く
2. ポップアウト

## 📌 Environment
misskey.io, p1.a9z.dev

**Comment by futchitwo** [comment]
related 
- #8170

**Comment by Fluffkin** [comment]
Now it seems to be the opposite problem to #8710 
Pop out urls are formed https://url.url//@username?zen (broken double //) instead of https://url.url/@username?zen (would work)
Misskey v12.110.0
