### ISSUE TITLE
コントロールパネルでadmin/federation/refresh-remote-instance-metadataを叩きたい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8231]
## Summary
コントロールパネルの連合のインスタンス詳細ページのメニューにadmin/federation/refresh-remote-instance-metadataを叩く項目があると便利だと思う

**Comment by Johann150** [comment]
I was surprised that I did not find this when I was testing #8220. I thought we already had this, but maybe I confuse it with the button to refresh user information.
