### ISSUE TITLE
API endpoint broken in 12.103.1? drive/files/create

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8243]
## 💡 Summary

API calls to `drive/files/create` are no longer working after updating to 12.103.1 and I'm not sure why (can't see error)
After reverting to 12.102.1 they are working again. Can someone please verify if this is a bug with 12.103 or a new change? I'm sorry if it's not a bug and please close this if so. I'm sorry there's not more information.

## 🙂 Expected Behavior

API call to `drive/files/create` successfully uploads file.

## ☹️ Actual Behavior

API call to `drive/files/create` fails (I'm sorry, I can't tell which error because the exception isn't working either on Misskey.py and I don't know how to do it manually since I am not a coder ><)

## 📝 Steps to Reproduce

1. make api call to drive/files/create endpoint with parameters `file` pointing to a valid image

## 📌 Environment

Misskey 12.103.1

**Comment by ghost** [comment]
looking back i think this is intended behaviour because of the refactor and the misskey.py itself needs to be updated, so I'm closing it. Sorry!

**Comment by mei23** [comment]
The parsing method when specifying boolean in multipart/form-data (used in drive/files/create) has changed.

Before
```
# input string => parsed boolean
true => true
True => false !
false => false
False => false
foo => false
```

After
```
true => true
True => (error)
false => false
False => (error)
foo => (error)
```
