### ISSUE TITLE
Timeline loads old posts but not new posts, notifications work

### ISSUE THREAD

**Issue by Luchtspieg** [syuilo/Misskey#8245]
## 💡 Summary
When logged into my account, older posts will load, but newer posts from people I follow will not load.
This happens regardless of browser or device, but other accounts load fine in the same browser and device.

Version 12.102.1 would load neither old or new posts; version 12.103.1 loads old posts, but not new.

## 🙂 Expected Behavior
As people I follow make posts, they load into my timeline within a reasonable time frame.

## ☹️ Actual Behavior
Notification sound for new posts goes off, but no post loads.
[Console log shows the same error over and over](https://github.com/misskey-dev/misskey/files/7988521/msky_log.txt).

## 📝 Steps to Reproduce
1. Log in
2. Wait for new posts from people you follow

## 📌 Environment
Any device and web broswer, so long as you sign in with this specific account.

**Comment by Johann150** [comment]
Due to the minfication the error message is not very helpful, but the error `SyntaxError: nothing to repeat` seems to usually be caused by regular expressions.

**Comment by syuilo** [comment]
ワードミュートの設定はどうなっていますか？

**Comment by Luchtspieg** [comment]
There was a regular expression in my muted wordlist; I removed it, and it all works now.
Thank you for your help, and please excuse the inconvenience!

For reference: the regex was aimed to hide posts using the `$[rainbow ]` function.

**Comment by syuilo** [comment]
It is not nice to have an internal error when a user enters a wrong regular expression, so I think we need to fix this.

**Comment by Johann150** [comment]
> I think we need to fix this.

I agree. You should reopen the issue.
