### ISSUE TITLE
自分のノートのインスタンス情報が表示されない。

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8246]
## 💡 Summary
ノートのインスタンス情報を常に表示を選択しても、自分のノートのインスタンス情報が表示されない。

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/89781396/152222864-7a3cb5d1-f0ac-4b23-a628-27b69ea57750.png)
![image](https://user-images.githubusercontent.com/89781396/152222869-a7f9e78f-df2d-4ea6-a367-a2f4551608ba.png)
モバイル、PCともに発生している。

## 📌 Environment
OS: Win10 21H2
Browser: Firefox96.0.3
OS: Android12   
Browser: Vivaldi 5.0.2498.36

**Comment by ghost** [comment]
related to my issue #8205 i think
you have to go in options to change this settings
![image](https://user-images.githubusercontent.com/95146426/152672891-d1203f47-c31a-4e10-a789-afcf71a3bdb5.png)

but currently it breaks the timeline if you set it to 常に表示

**Comment by syuilo** [comment]
fixed
