### ISSUE TITLE
Some notes are blinking/disappear

### ISSUE THREAD

**Issue by nice714106tall** [syuilo/Misskey#8247]
## 💡 Summary

Some texts didn't displayed.

## 🥰 Expected Behavior

![Screenshot_2022-02-03-12-12-48-384_com.android.chrome.jpg](https://user-images.githubusercontent.com/83388768/152275713-bbc7d197-4ab6-4c69-be53-61db12a0194b.jpg)

## 🤬 Actual Behavior

1.![Screenshot_2022-02-03-12-12-10-888_com.android.chrome.jpg](https://user-images.githubusercontent.com/83388768/152275645-5790f257-c025-4efe-945c-dd7c86a4f4a9.jpg)
2.![Screenshot_2022-02-03-12-12-27-529_com.android.chrome.jpg](https://user-images.githubusercontent.com/83388768/152275695-1aed309c-d82a-4f8e-874b-f90de2954151.jpg)

## 📝 Steps to Reproduce

1.Just visit the timeline page.

## 📌 Environment

Misskey version:12.103
Your OS:Android11
Your browser:Chrome

**Comment by nice714106tall** [comment]
additional information:
- Theme is `Mi Dark`
- Appearance settings are below:
![Screenshot_2022-02-03-12-22-35-395_com.android.chrome.jpg](https://user-images.githubusercontent.com/83388768/152276199-ab5fb1e0-8ee4-43d1-b8dc-639f57e7ba4e.jpg)

**Comment by tamaina** [comment]
この問題はまだ発生していますか？

**Comment by KisaragiEffective** [comment]
Triage: this needs more information about your client side. Please re-open if this is still able to reproduce on latest `misskey.io`'s release and other instance based on `2024.5.0`.
