### ISSUE TITLE
クライアントがノートのオブジェクトの参照を使いまわしてしまっている

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8248]
## 💡 Summary
デッキなどで同じ種類のタイムラインを複数表示すると…

## 🥰 Expected Behavior
新着リアクションのついた数が正しい

## 🤬 Actual Behavior
タイムラインが表示されている数の倍数分だけ新着リアクションの数字が多く表示される

![image](https://user-images.githubusercontent.com/7973572/152361178-07233e76-773c-4de5-ab97-78feeb138f82.png)

## 📝 Steps to Reproduce

1. デッキで同じタイムラインを開く
2. ストリームからリアクションの更新通知が届く

## 📌 Environment
Misskey version: 12.103.1, misskey.io & p1.a9z.dev
Your OS: Windows 11
Your browser: Firefox, Chrome

**Comment by syuilo** [comment]
考えられる解決策
- 各ノートコンポーネントは、マウントする際にpropsで渡されたノートオブジェクトをdeep copyする
- リアクションなど変動する情報だけ別に持つ
- ノート情報をグローバルに管理する

**Comment by syuilo** [comment]
一番シンプルで理に適ってそうなのは

> 各ノートコンポーネントは、マウントする際にpropsで渡されたノートオブジェクトをdeep copyする

なんだけど、メモリ使用量が2倍になるのが無駄に感じるのと、deep copyするコストも発生する
まあどちらもごく僅かだけど

**Comment by tamaina** [comment]
Misskey.jsのStreamクライアントがキャプチャを統制して1つのノートに対するキャプチャを1つに制限するというのではだめなのかしら

**Comment by syuilo** [comment]
キャプチャが複数回行われることが原因ではなくて、ノートオブジェクトの参照が使いまわされることによって、イベントが降ってくるとそれぞれのノートコンポーネントが各々値をインクリメントするからn倍になる

**Comment by syuilo** [comment]
だから解決するにはノートの参照をぶっちぎるか、参照が繋がってても良いようにキャプチャ管理をグローバル(not misskey.js)に行うか

**Comment by tamaina** [comment]
> ノートオブジェクトの参照が使いまわされる

あ～～～～～、なるほど

https://github.com/misskey-dev/misskey/blob/fix-msg-room/packages/client/src/components/timeline.vue#L31

で、このバグが発生するのはストリーミングから降ってきた投稿に限定されるわけね（ようやくバグのロジックを理解した）

**Comment by mei23** [comment]
前あってdeep copyしてなおしたやつかしら
https://github.com/misskey-dev/misskey/pull/6275

**Comment by syuilo** [comment]
こういうのフレームワークに限らず遭遇する問題だと思うからベストプラクティス知りたい

**Comment by tamaina** [comment]
> ノート情報をグローバルに管理する

が一番スマートそうではあるけど、なんかそれよりやるべきことあるだろ的な感じもする

**Comment by tamaina** [comment]
削除して編集するとTLからは削除されないがpost-formの変更内容が古いノートビューに反映されるw

グローバルに管理するようにしちゃってもいい気がした

**Comment by syuilo** [comment]
するか

**Comment by syuilo** [comment]
結構面倒そう
グローバルに管理するとそのままだとメモリにたまり続けるから不要になったノートは消していかないといけないけど、どれが不要か(=参照してるコンポーネントが無いかどうか)判定するためには参照カウントみたいなのも一緒に管理しないといけないとか...

**Comment by syuilo** [comment]
とりあえずJSON.parse(JSON.stringify())するか

**Comment by tamaina** [comment]
Vueコンポーネントならunmountが発行されるから大丈夫じゃね（まあでもぶら下がるのがVueコンポーネントであるとは限らんなぁ）

**Comment by syuilo** [comment]
> とりあえずJSON.parse(JSON.stringify())するか

したのでclose
