### ISSUE TITLE
cafyやめる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8251]
## Summary

JSON Schemaでバリデーションするようにする

- 一般的な形式なためツールのサポートが充実している
- cafyだとバリデータから型を取得するのが完ぺきではない(enumの扱いなど)
  - この点についてはJSON Schemaにすれば解決するのかは不明
- fastify移行する際にも有利そう

**Comment by acid-chicken** [comment]
fyi: https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/

**Comment by syuilo** [comment]
ajv使う + JTDで定義する でやっていくことにする

**Comment by syuilo** [comment]
JTDは値の検証というよりは型を定義することに主眼を置いてそうで、例えば数値の範囲だったり配列の数だったり文字列の形式などなどを定義する機能は無いっぽくて、まあまあ不便そうだからやっぱりJSON Schemaで良いかも

**Comment by syuilo** [comment]
あーーー、JSON Schemaだと**スキーマ定義から型を推論してくれない**みたいで、スキーマ定義とは別に型定義も行わないといけないことが判明(JTDならスキーマ定義から型も生成してくれるけど、https://github.com/misskey-dev/misskey/issues/8251#issuecomment-1041078213 の問題がある)
これじゃcafyの方が楽ということに

**Comment by syuilo** [comment]
こんなのあった
https://github.com/ThomasAribart/json-schema-to-ts

**Comment by syuilo** [comment]
↑なぜこれ(もしくは同様のシステム)をajvが採用しないのか謎
なにか制限がある？

**Comment by tamaina** [comment]
Misskey謹製SchemaTypeを使った方が早くね説

**Comment by syuilo** [comment]
> なにか制限がある？

`nullable`のサポートが今のところ無いっぽい？
https://github.com/ThomasAribart/json-schema-to-ts/pull/37

**Comment by tamaina** [comment]
いや違うわ、TypeScriptなtype定義からJavaScriptで検査するのが不可能

**Comment by syuilo** [comment]
> > なにか制限がある？
> 
> `nullable`のサポートが無いっぽい？ [ThomasAribart/json-schema-to-ts#37](https://github.com/ThomasAribart/json-schema-to-ts/pull/37)

`nullable`ってJSON Schemaの仕様には無いのか...

**Comment by tamaina** [comment]
（というかfastifyでなんとかしてくれるような機能ないのかしら

**Comment by tamaina** [comment]
> JSON Schemaだとスキーマ定義から型を推論してくれないみたいで、スキーマ定義とは別に型定義も行わないといけない

これ別々じゃだめなのかしら

**Comment by syuilo** [comment]
> > JSON Schemaだとスキーマ定義から型を推論してくれないみたいで、スキーマ定義とは別に型定義も行わないといけない
> 
> これ別々じゃだめなのかしら

めんどくさい・無駄というデメリットはあれど、メリットがほぼなさそう

**Comment by syuilo** [comment]
(スキーマ定義と型定義が別々だと実際の値と型定義が異なることが起き得るというデメリットもあるかなと思ったけど、それについては型定義を`JSONSchemaType`に渡したうえでスキーマ定義すれば型定義に沿っていないスキーマ定義するとエラーになってくれそうだから回避できそう)

**Comment by tamaina** [comment]
どんなパッケージでも「スキーマ定義を基に型定義として再現する」というプロセスがありそうだしそのデメリット(副作用)が付いて回る…気がする。

**Comment by syuilo** [comment]
ぬ？
スキーマ定義を基に型定義として再現する場合のデメリットって何かしら

**Comment by tamaina** [comment]
> スキーマ定義を基に型定義として再現する場合のデメリット

あるとしたら型定義を完璧に再現できないとか  

しゅいろが言ってるのってスキーマ定義と型定義を両方自分で手打ちしようって話なのかしら？

**Comment by syuilo** [comment]
> しゅいろが言ってるのってスキーマ定義と型定義を両方自分で手打ちしようって話なのかしら？

私がやりたいのは、JSON SchemaでAPIパラメータのスキーマ定義を行って、その定義から自動でパラメータの型も付くようにしたい
私がやりたくないのは、JSON Schemaでスキーマ定義を行ったうえでさらにパラメータの型定義も手動で行うこと

現状のcafy実装では、cafyでバリデータ定義するだけでAPI本体処理の`ps`も自動で型つくよね
それと同じ状態をajvに移行した後でも維持したいということ

**Comment by acid-chicken** [comment]
cafy みたいな手法によって型定義も JSON Schema も両方生成するのじゃいかんの

**Comment by tamaina** [comment]
私の考えとしては、バリデーターはajvで決まりで、ajvの返値に型がつかないなら、SchemaTypeなりjson-schema-to-tsなりの型で定義（上書き）してしまえばいいと思う

**Comment by tamaina** [comment]
（…というのは  
> JSONSchemaTypeに渡したうえでスキーマ定義すれば型定義に沿っていないスキーマ定義するとエラーになってくれそうだから回避

と同じことを言っていると思う）

**Comment by syuilo** [comment]
> cafy みたいな手法によって型定義も JSON Schema も両方生成するのじゃいかんの

そもそもJSON Schemaをソースとしたい
理由は https://github.com/misskey-dev/misskey/issues/8251#issue-1123727919 の通り

> 私の考えとしては、バリデーターはajvで決まりで、ajvの返値に型がつかないなら、SchemaTypeなりjson-schema-to-tsなりの型で定義（上書き）してしまえばいいと思う

そうすることになりそう

**Comment by syuilo** [comment]
> そうすることになりそう

んだけど、https://github.com/misskey-dev/misskey/issues/8251#issuecomment-1041117213 でも言ったけど

- 明らかにそうした方が便利なのにajv公式でそうなっていないのは何か重大な理由があるんじゃ？というのと、
- json-schema-to-tsでは現時点では`nullable`対応してなくて微妙感がある

**Comment by tamaina** [comment]
これJTDじゃだめなの

https://ajv.js.org/guide/typescript.html#utility-type-for-jtd-data-type

**Comment by syuilo** [comment]
JTDは https://github.com/misskey-dev/misskey/issues/8251#issuecomment-1041078213 の問題がある

**Comment by tamaina** [comment]
ah~

**Comment by marihachi** [comment]
多分、JSON SchemaがJSONでスキーマを記述するってコンセプトだから、
TypeScriptの型を入力として受け入れて検証をしないってだけじゃない？

あくまでも、JSONのスキーマを記述しやすいようにTypeGuardを提供する、に留めてそう

**Comment by syuilo** [comment]
この辺か
https://github.com/ajv-validator/ajv/issues/1792

**Comment by syuilo** [comment]
https://github.com/ThomasAribart/json-schema-to-ts/ 使ってみたけど、型が深すぎてエラーになった

**Comment by syuilo** [comment]
nullable対応してない問題もあるし、おとなしく二重に定義するしかないかも

**Comment by tamaina** [comment]
Misskey謹製のSchemaTypeそのまま使っちゃえばいいんじゃないかしら

**Comment by syuilo** [comment]
それちょっと思った
ただSchemaTypeは若干対応しているJSON Schemaのバージョンが古そう(optionalがあったりとか)

**Comment by syuilo** [comment]
そこまで改修するのちょっとめんどい

**Comment by tamaina** [comment]
なるほど

https://stackoverflow.com/questions/16204871/what-is-the-difference-between-required-vs-optional-in-json-schema

(私なら改修しちゃうけど)

**Comment by syuilo** [comment]
それ改修するとなるとAPIのres定義まで変える必要があって大変そう

**Comment by tamaina** [comment]
resとps別で定義する (psはref定義とかも削除して良さそう) or optionalとrequired併存できるかもとも思った

**Comment by syuilo** [comment]
> https://github.com/ThomasAribart/json-schema-to-ts/ 使ってみたけど、型が深すぎてエラーになった

パラメータ定義をmetaの外に出したらエラーでなくなた

**Comment by syuilo** [comment]
json-schema-to-ts云々関係なしにmetaの外にあった方が型定義上拡張性があるから外だししたいけど、300近いエンドポイントすべてを変更するのめんどい

**Comment by syuilo** [comment]
やっていってる
![m](https://user-images.githubusercontent.com/4439005/154631818-ed7bb458-6810-41aa-9b0a-c9713d6a9c85.gif)

**Comment by syuilo** [comment]
あー、json-schema-to-ts は`nullable`対応してない他にも`default`にも対応してなさそうだからやっぱり使えないな

**Comment by syuilo** [comment]
SchemaType改修しようとしたけどrequired対応が難しくて挫折

**Comment by syuilo** [comment]
いやできるかも

**Comment by syuilo** [comment]
ぬおーrequired対応とdefault対応どっちもできた

**Comment by tamaina** [comment]
derfaultって対応する意味あるのかしら  
(というかconstが再現されない？)

**Comment by tamaina** [comment]
あ、defaultがあればoptionalではないようにする必要があるのか

**Comment by tamaina** [comment]
…補完(validate)前と補完後ではdefaultがオプショナルかどうかが違う気がする

**Comment by syuilo** [comment]
> …補完(validate)前と補完後ではdefaultがオプショナルかどうかが違う気がする

どゆこと？

**Comment by tamaina** [comment]
この型の付け方(defaultが必須)だと、入力側（validate前）でdefaultのあるプロパティを記入する必要があるように言われてしまう。validateで補完されるので本当は入力する必要はないのに。

**Comment by syuilo** [comment]
validate関数の引数はanyであるべきと思うんだけどそうなってない？

**Comment by tamaina** [comment]
まあでもそうか型チェックはしなくていいのか  
(res側で不整合が起きるかなとも思ったけどdefaultの補完は自分でやるからいいのか)

**Comment by syuilo** [comment]
> まあでもそうか型チェックはしなくていいのか

validateに入力する値の型が決まってるならvalidateする必要が無いからそう思った

> (res側で不整合が起きるかなとも思ったけどdefaultの補完は自分でやるからいいのか)

ほむ

**Comment by tamaina** [comment]
https://www.npmjs.com/package/json-schema-to-ts と https://www.npmjs.com/package/json-schema-to-typescript が存在するの何

**Comment by tamaina** [comment]
json-schema-to-typescriptはファイルとして出力するだけだったわ
