### ISSUE TITLE
コントロールパネルのユーザー、ファイルにて、インスタンスの表示範囲切り替えが機能しない

### ISSUE THREAD

**Issue by frfs** [syuilo/Misskey#8252]
## 💡 Summary
コントロールパネルの「ユーザー」、「ファイル」にて、インスタンスの表示範囲を変更しても表示が切り替わらない

## 🥰 Expected Behavior
インスタンスの表示範囲を変更すると、適切な表示範囲の内容になる

## 🤬 Actual Behavior
インスタンスの表示範囲を変更してもなにも起こらない
![Animation](https://user-images.githubusercontent.com/8694755/152507433-69508a5f-fd4b-437a-9ec4-f1bfabe8b27e.gif)

## 📝 Steps to Reproduce

1. コントロールパネルからユーザーまたは、ファイルを開く
2. 「インスタンス」から表示範囲を変更する

## 📌 Environment

Misskey version: 12.103.1
Your OS: Win11
Your browser: Chrome 98.0.4758.82

**Comment by Johann150** [comment]
`Uncaught TypeError: props.instance is undefined` can be seen on the console. I think this is because for local users, the instance data is set to `null`.
