### ISSUE TITLE
dependabot定義の修正

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#8259]
## Summary
dependabotは、今ルートの package.json しか見ていないのであまり意味がないことになっている。
packages/下も見るようにすることもできるけど、それだと各 package.json ごとにバラバラに (バージョンが統一されることがなく) プルリクが出されるのでうれしくない。※ 各package.jsonごとに制限値の数まで出されるのでバージョンがバラバラになる。

特にdependabotのプルリク活用されてなさそうなので、各 package.json でセキュリティのみプルリクを出すようにしてはどうかと。

このように
https://github.com/mei23/misskey-v12/blob/dc4c5cac2d7ddf731bae1d5fc6e045c330fb0ad9/.github/dependabot.yml

**Comment by mei23** [comment]
今はbackendのSecurity Pull requestが飛んでこない

**Comment by mei23** [comment]
@syuilo これやるかしら？

**Comment by syuilo** [comment]
やる予定

**Comment by mei23** [comment]
もしかしてこの辺有効にしないとSecurity Pull requestが飛んでこない？

![image](https://user-images.githubusercontent.com/30769358/153401211-01aab0c9-13d3-43da-8d04-5bd888584f03.png)

**Comment by syuilo** [comment]
してみた

**Comment by mei23** [comment]
うおお、きたわきたわ
