### ISSUE TITLE
鍵RNが連合されない

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8261]
## 💡 Summary
鍵RNが連合されない。

## 🥰 Expected Behavior
鍵RNが連合される。

## 🤬 Actual Behavior
されない。

## 📝 Steps to Reproduce

1.引用RNから公開範囲をフォロワーのみに選択
2.RNする

## 📌 Environment

Misskey version: 12.103.1
Your OS: Windows10 21H2
Your browser: Firefox96.0.3

**Comment by Johann150** [comment]
Can you check that `☣ Local only` is not enabled?

**Comment by Johann150** [comment]
(sorry, Japanese name is `☣ ローカルのみ`)

**Comment by tamaina** [comment]
私もバグが再現した

**Comment by nenohi** [comment]
local only is disabled
misskey.io    sushi.ski 
![image](https://user-images.githubusercontent.com/18223268/152780110-cb93a86d-2bce-4d23-a7d0-491e80b2506d.png)

**Comment by mei23** [comment]
なんか仕様だった気がする

**Comment by mei23** [comment]
なんでだっけ

**Comment by mei23** [comment]
あーフォロワー限定でRenoteするとMastodonが公開範囲無視して公開しちゃうから (今は大丈夫かも) 連合しないようになってたのだわ

**Comment by ghost** [comment]
なるほどなのだわ！💙

**Comment by rinsuki** [comment]
Mastodonにも鍵BTあるしなんとかなるんじゃないかという気がする

**Comment by mei23** [comment]
フォロワー限定拡散なんて訳わかんないもの実装するくらいなら、とっとと引用投稿実装すればいいのに…

**Comment by saschanaz** [comment]
#10291 で修正しました
