### ISSUE TITLE
APIでGETリクエストを受け付ける

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8263]
## Summary

 - 要望が多い
 - 情報が古くても良いユースケースでキャッシュ可能になる

**Comment by mei23** [comment]
- 意外と実装は簡単
  https://github.com/mei23/misskey/commit/50239a9b01a628c81d81e7f71c5f04e28d540a94
- 意外と使い道がない
  - ユーザーやノートを参照しているものはミューブロ反映する必要があるのであまり使えない
  - metaが一番効果あるけど meta, admin/meta みたいにendpointを分ける必要がある
  - stats, chartは効果ありそうだけどあまり参照されない

な感じだったわ

**Comment by tamaina** [comment]
（metaとadmin/metaは分けていいのではと思うんだけど）

**Comment by Johann150** [comment]
`meta` and `admin/meta` have separate URLs so they are already separately cached?

**Comment by syuilo** [comment]
やるか(UIの改修でchartを大量に参照するようになったためキャッシュが効いてきそう)

**Comment by syuilo** [comment]
クエリだと全部文字列になるから数値パラメータを変換しないといけないわね

**Comment by mei23** [comment]
> クエリだと全部文字列になるから数値パラメータを変換しないといけないわね

ここを
https://github.com/misskey-dev/misskey/blob/d5ef68336a18ca90c0885a00f55c7e599a745930/packages/backend/src/server/api/call.ts#L96-L97

```
(ep.meta.requireFile || ctx?.method === 'GET')
```
にするだけで動くようしといたはずだわ
