### ISSUE TITLE
Renamed/deleted emojis not removed from emoiji picker

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8264]
## 💡 Summary

If you remove or rename an emoji, it won't dissapear from the picker without a full client flush.

![Screenshot_2022-02-07-01-54-03_2560x1440](https://user-images.githubusercontent.com/44733677/152878673-3380d6d3-066d-474b-9fce-c40e0bdbe34f.png)

## 🥰 Expected Behavior

Emoji isn't there

## 🤬 Actual Behavior

It's there but just text

## 📝 Steps to Reproduce

1. Delete or rename emoji
2. Reload page without clearing cache or flushing
3. See emoji in emoji picker

## 📌 Environment

Misskey version: develop (latest)
Your OS: Linux
Your browser: Firefox

**Comment by Johann150** [comment]
I would say this is a duplicate of #8207 for the special case of changing or deleting emojis.
