### ISSUE TITLE
Let instance admins configure search engine for `google.vue`

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8266]
## Summary

Many people don't like the Google search engine, letting instance admins change the default search engine here

https://github.com/misskey-dev/misskey/blob/5416f38eb498b4f646747001eb33185128699332/packages/client/src/components/google.vue#L18

in the control panel would be great. I manually edited mine to 
```js
window.open(`https://gowogle.voring.me/search?q=${query.value}`, '_blank');
```

This would be ***especially*** for instance admins who run Whoogle/SearX/SearXNG instances.

**Comment by nullobsi** [comment]
related/duplicate of #2479 ?

this would be a nice feature, along with it being user-customizable :)

**Comment by ThatOneCalculator** [comment]
> related/duplicate of #2479 ?
> 
> this would be a nice feature, along with it being user-customizable :)

Related. I'll keep it open as this goes into more description, I guess? Up to you idk

**Comment by futchitwo** [comment]
related
- #7920
- #7917

**Comment by Johann150** [comment]
Please note that the underlying code mentioned in #7917 was removed in c2ae160d23, making this reintegration a bit more complicated.

**Comment by Johann150** [comment]
I think it would make most sense if this is configurable in the client (as in the PR linked above and as implemented by #3406 before) so the server code does not have to be changed to accommodate for different search engines.

**Comment by syuilo** [comment]
The search syntax itself may be removed.

**Comment by tamaina** [comment]
どのサービスにしても文句言われそうなので、面倒だからなくていいと思う

**Comment by acid-chicken** [comment]
去年 https://github.com/misskey-dev/misskey/pull/7920#issuecomment-952997272 って言ってもう 3 ヶ月ぐらい経つけど、具体的な予定は決まってるの？（消すタイミングが決まっていてそれまでの待機期間にいる？あるいは誰かしらによる PR が出るなら消す？はたまたそういった単純な回答が難しい？）

**Comment by syuilo** [comment]
> 去年 https://github.com/misskey-dev/misskey/pull/7920#issuecomment-952997272 って言ってもう 3 ヶ月ぐらい経つけど、具体的な予定は決まってるの？

これはもうすでに行われてる

**Comment by acid-chicken** [comment]
> > 去年 [#7920 (comment)](https://github.com/misskey-dev/misskey/pull/7920#issuecomment-952997272) って言ってもう 3 ヶ月ぐらい経つけど、具体的な予定は決まってるの？
> 
> これはもうすでに行われてる

あ、このタイミングではまだ検索構文自体の廃止について言及したわけではなかったのか（勘違いしていました）

**Comment by syuilo** [comment]
↑それを復活させようというのがこのIssueだと思ってる

**Comment by mei23** [comment]
別に検索押しても何処にも飛ばなくすればいいんじゃないかしら

**Comment by Johann150** [comment]
> 別に検索押しても何処にも飛ばなくすればいいんじゃないかしら

Maybe it should lead to the Instance Note search. (`/search?q=...` on the client)

**Comment by ThatOneCalculator** [comment]
> Maybe it should lead to the Instance Note search. (`/search?q=...` on the client)

Note that Google/Whoogle/SearX use `/search?q=...`, but DDG uses `/?q=...`

**Comment by syuilo** [comment]
- 廃止したいけどこの構文を活用するBotも既にあったりして難しいので構文自体は残す
- ドキュメントからは消してdeprecated扱いにする
- 検索ボタンに「Google検索」と明示して、「意図せずGoogleに飛ばされる」という問題を回避する

にする
