### ISSUE TITLE
bullでcron指定してあるジョブが動いていない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8272]
## 💡 Summary

cron指定してあるけど、見る感じ動いてなさそう

## 🥰 Expected Behavior

cronで指定した通りにジョブが定期実行される

## 🤬 Actual Behavior

されていない

## 📝 Steps to Reproduce

1. 

## 📌 Environment

Misskey version: 12.103.1

**Comment by mei23** [comment]
`systemQueue.process()` 呼んでなくないかしら？

**Comment by syuilo** [comment]
あーそれっぽい🙏🙏🙏
