### ISSUE TITLE
Keep content warnings when replying

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8275]
## Summary

When replying to a post, it's very annoying that content warnings aren't also kept in the comment. Adding a `Re:` beforehand would be even better.

**Comment by Johann150** [comment]
Duplicate of #6605

Misskey can already do this. Go to Settings > Privacy > Keep content warnings. (last checkbox on the page)

**Comment by ThatOneCalculator** [comment]
> Duplicate of #6605
> 
> Misskey can already do this. Go to Settings > Privacy > Keep content warnings. (last checkbox on the page)

Gotcha. Is there a way to make this on by default for all users?
