### ISSUE TITLE
[I forgor] Make mobile emoji drawer bigger

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8297]
## Summary

I mean....just look at this

![Screenshot_20220210-172143.jpg](https://user-images.githubusercontent.com/44733677/153523934-893fef76-7c5e-4bb6-811c-911ef0cc1f11.jpg)

**Comment by syuilo** [comment]
Try change Settings->Reactions->Height

**Comment by ThatOneCalculator** [comment]
> Try change Settings->Reactions->Height

I completely forgot about that. Sorry.
