### ISSUE TITLE
ユーザーに簡単に警告を送れる機能

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8312]
## Summary

いくつかの理由の中から選択、もしくはカスタムテキストで内容を設定して、メールか何かで警告を送れる機能

**Comment by 4ioskd** [comment]
Webクライアント経由とメール経由の両方が良さそうですね。両方に送れば、さすがに見逃すことはないでしょう。

**Comment by syuilo** [comment]
ユーザーごとのお知らせ機能によりほぼ実装された
