### ISSUE TITLE
タッチ操作だとウィジェットの編集がしにくい

### ISSUE THREAD

**Issue by minetaro12** [syuilo/Misskey#8316]
## 💡 Summary

タッチ操作でXボタンや設定ボタンに触れるとウィジェットが移動してしまいなかなか押せない

## 🥰 Expected Behavior

ウィジェットを削除したり編集ができる

## 🤬 Actual Behavior

ボタンに触れるとウィジェットが移動してしまい押せない

https://user-images.githubusercontent.com/77948036/153746835-500f9530-51a4-431b-a341-c34b63e933bc.mp4

## 📝 Steps to Reproduce

1.ウィジェットボタンを押す
2.ウィジェットを編集を押す
3.ウィジェットのXボタンや設定ボタン押すと移動してしまい押せない

## 📌 Environment

Misskey version: v12.107.0
Your OS: Android11
Your browser: Chrome 98.0.4758.87

**Comment by 4ioskd** [comment]
ping @syuilo and @tamaina

**Comment by tamaina** [comment]
iOS Safariだと大丈夫なのか

**Comment by tamaina** [comment]
Color OS V11 + Chrome Beta 99 (だったと思う) @ p1.a9z.dev だと普通に使えますね

**Comment by minetaro12** [comment]
ChromeBetaや他のインスタンスでも試してみましたが特に症状は変わらなかったです

**Comment by tamaina** [comment]
私はmisskey.ioでも問題なかった

**Comment by tamaina** [comment]
押し方の問題とか？  
（本当にポンと軽く押す必要がある？

**Comment by tamaina** [comment]
（それよりスクロールしにくいのが気になるけど）

**Comment by dx6682** [comment]
ウィジェットが上から下まで埋まっているとスクロールできない
長押ししたらで長押ししたらでドラッグになってしまう

**Comment by tamaina** [comment]
右端をつかむといいと思う

**Comment by syuilo** [comment]
> 押し方の問題とか？
> （本当にポンと軽く押す必要がある？

これ前再現したことある(環境は忘れた)けどどうやっても押せなかった記憶が

**Comment by tamaina** [comment]
ちゃんとpreventDefaultとstopPropagationを付けているので、問題を解決するにはDraggableとの関係をより深く探っていく必要がありそう

https://github.com/misskey-dev/misskey/blob/develop/packages/client/src/components/widgets.vue#L19

**Comment by minetaro12** [comment]
別端末でも試しましたが症状変わらずです
Firefoxでは普通に操作することができました

**Comment by syuilo** [comment]
手持ちのiPhone(iOS 15.3) Chromeでmisskey.ioで試したら押しにくいけどポンしたら消せた

**Comment by dx6682** [comment]
WebKit系は問題ないのかなiOS 15.3.1のiPhone 13 Proも編集ボタンに関しては問題ない（たださっきのスクロールできない問題はある）

**Comment by tamaina** [comment]
p1.a9z.devでボタンの大きさを1.5倍にしてみたので試していただけると有難いです

**Comment by minetaro12** [comment]
ボタンが大きくなったので押しやすくはなりましたが、やはりあまり変わらないです
かなり軽くポンと押すと反応する時があります

**Comment by minetaro12** [comment]
Firefoxの場合はこんな感じで特に問題なくウィジェットの編集が可能です

https://user-images.githubusercontent.com/77948036/154493368-b54f8644-57e7-4930-9674-6e7336d9f915.mp4

**Comment by xianonn** [comment]
タップするとすぐにドラッグが開始されるためボタンが押せなくなっているようです。
ただしタップした瞬間はまだドラッグが開始されていないみたいで、すぐに離せばボタンが押せるということのようです。

弊鯖では編集ボタンと削除ボタンをドラッグの対象から外すことでタップできるようにしました。
https://gitlab.com/xianon/misskey/-/commit/52d5624a18b60966387cf8194da1f504071ae131

これで良ければプルリク出しますけど。

**Comment by tamaina** [comment]
お願いします:pray:
