### ISSUE TITLE
register_note_view_interruptor()が動かない

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#8318]
## 💡 Summary

MisskeyプラグインのPlugin:register_note_view_interruptor()が動かない（半年前までは動いてた？）

## 🥰 Expected Behavior

`Plugin:register_note_view_interruptor(honi)`でノートが来た際に`@honi()`が実行される

## 🤬 Actual Behavior

`Plugin:register_note_view_interruptor(honi)`でノートが来た際に`@honi()`が実行されない

## 📝 Steps to Reproduce

1. `Plugin:register_note_view_interruptor()`を使ったMisskeyプラグインをインストール
2. TLを眺める

## 📌 Environment

Misskey version: 12.107.0
Your OS: Windows 10 (x64)
Your browser: Google Chrome 98.0.4758.102

**Comment by ThinaticSystem** [comment]
v12.102.0から動かなくなっているようです

なんもわからんのですが時期的に https://github.com/misskey-dev/misskey/commit/28193f12ca0fd20544b0c9807661fb9a7e7c2a0e のコミットの
packages/client/src/components/note.vue
packages/client/src/components/note-detailed.vue
が怪しい気がしています（noteViewInterruptors周りの処理が消滅している？ため）

**Comment by Johann150** [comment]
Should `noteViewInterruptors` be handled before `checkWordMute`? This was not the case in the old implementation but I think it would make more sense.
