### ISSUE TITLE
Merge Conflict for Dockerfile

### ISSUE THREAD

**Issue by AMoonRabbit** [syuilo/Misskey#8320]
## 💡 Summary

When attempting to use the command `git stash pop` after pulling the current repo for master branch, terminal throws the following:
```
Auto-merging Dockerfile
CONFLICT (content): Merge conflict in Dockerfile
The stash entry is kept in case you need it again.
```

## 🥰 Expected Behavior

No conflicts with git repo

## 🤬 Actual Behavior

Dockerfile is causing a conflict

## 📝 Steps to Reproduce

1. `git stash`
2. `git checkout master`
3. `git pull`
4. `git stash pop`

## 📌 Environment

Misskey version: 12.103.1 --> latest
Your OS: Ubuntu 20.04.3 LTS aarch64, Docker 20.10.12
Your browser: N/A

I am not sure how to resolve the conflict, so any assistance will be greatly appreciated.

**Comment by Johann150** [comment]
If you have to use `git stash` you must have made some modifications to the Dockerfile. We are not able to offer support in this case as your Modifications are not part of Misskey.

Please do not ask for troubleshooting advice in issues as [stated in the Contribution Guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md#issues).

**Comment by AMoonRabbit** [comment]
I don't think I have made any special modifications though. I thought `git stash` was part of the update process. Is there a way I can clear the stash and try without using that command?
