### ISSUE TITLE
ノートの最大文字数を管理者が決められる機能を廃止

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8323]
## Summary

- 動的な文字数制限は静的なJSON Schemaに落とし込むことが出来ず面倒
- そもそも管理者が決められる必要性が無さそう(3000文字もあれば十分そう)
- この機能があることで、添付できるファイル数とかプロフィールの追加情報も最大数を管理者が設定できるようにしろという話が出てくる一因になる(当然そんなことやってたらキリがないし煩雑になる)
- インスタンスごとで完全にバラバラであるよりもある程度統一されていた方が便利そう
- どうしても最大文字数を変えたい場合はコード書き換えて、で良さそう
- もし最大文字数変えたいというニーズがあまりにも多かったら設定ファイルで静的に設定できるようにするので良さそう
  - (設定ファイルにすることで
    > 動的な文字数制限は静的なJSON Schemaに落とし込むことが出来ず面倒

    は解決するため)

**Comment by tamaina** [comment]
私的には

- 8000文字を上限にする
- UIから残り文字数表示を削除
- もし8000文字を超えたら投稿できないとエラーを出す

みたいな感じでいいんじゃないかなとも思った

**Comment by futchitwo** [comment]
> - 8000文字を上限にする
> - UIから残り文字数表示を削除

おそらくユーザーに文字制限を認識させない意図があると思うけど、結局8000字を超えてエラーになるならその時何文字減らしたらいいかがわからないと不便だから、8000文字に近づいたら残り文字数を表示するくらいはしたほうがいいと思います

あとナンセンスな指摘かもしれないけど、8000文字かけたらそれはもはやミニブログではない気もする😅
ただ文字数の限界は広いほうが嬉しいだろうし(ほんまか)、数千字超えて設定してるインスタンスでも制限いっぱいのノートを見かけることはないので杞憂か

**Comment by Johann150** [comment]
Why was it not moved to the configuration file like you said initially? I know many instances that changed the character limit.

**Comment by Johann150** [comment]
Also, I think this is a bad idea because it is a **☢️Breaking** change.

**Comment by KawaneRio** [comment]
8000文字ってにゃんかキリが良くないので、8192文字上限がいいとおもふ。

> あとナンセンスな指摘かもしれないけど、8000文字かけたらそれはもはやミニブログではない気もするsweat_smile

個人的にはMisskeyを自分のOSのログ日記とかねて使ふてるので、4000字では少し物足りないと思ふてた。

**Comment by KawaneRio** [comment]
あっ、Issue閉じてた。ごめんなさい。

**Comment by 4ioskd** [comment]
>もし最大文字数変えたいというニーズがあまりにも多かったら設定ファイルで静的に設定できるようにするので良さそう
>  (設定ファイルにすることで
>動的な文字数制限は静的なJSON Schemaに落とし込むことが出来ず面倒
>は解決するため)

Johannが言うように、専用の設定ファイルを作ればこのissueは解決する気がする。

**Comment by Johann150** [comment]
I still think that this behaviour is not backward compatible because it removes something from the public API. SemVer rule 8:
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

**Comment by syuilo** [comment]
MisskeyはSemVerを採用していません。メジャーバージョンを上げるほどの大きな変更ではないと思います。

**Comment by nullobsi** [comment]
If it is added to the migration, is it possible for the migration script on `up` to write the previous value to the config file? It would make a smoother transition.

**Comment by Johann150** [comment]
> If it is added to the migration, is it possible for the migration script on up to write the previous value to the config file?

This might be possible by adding it to the end of the file, but I'm not sure how the `down` would work in that case.

**Comment by syuilo** [comment]
I don't think it is necessary to make it possible to set the maximum number of characters in a note in the configuration file yet, since there are not many needs to set the maximum number of characters arbitrarily at present.
