### ISSUE TITLE
ステージング環境

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8331]
## Summary

developブランチの内容を自動でデプロイするようにしたい

あとPRが来たらそのブランチの状態でデプロイするようにもしたい

**Comment by syuilo** [comment]
Kubernetesっての使いそう？

**Comment by tamaina** [comment]
どこにそんなことができるサーバーが…？(

**Comment by syuilo** [comment]
サーバーは用意する予定

**Comment by tamaina** [comment]
コミットごとにDockerイメージ作ってローカル環境で確認みたいなのでよくない？（適当）

**Comment by syuilo** [comment]
ローカルでなんやかんやするには布団から出る必要などが生じて面倒

**Comment by syuilo** [comment]
なんもわからん

**Comment by syuilo** [comment]
oktetoっての試してみたけど、k8sなんもわからんというのは置いといて
- デプロイされることになるURLをデプロイ前のビルド段階で知る方法が不明
- ビルド段階で設定ファイルのコピーなどのコマンドを実行させる方法が不明(oktetoの設定ファイルに書いてみたけど動いてなさそう)

**Comment by syuilo** [comment]
> ビルド段階で設定ファイルのコピーなどのコマンドを実行させる方法が不明(oktetoの設定ファイルに書いてみたけど動いてなさそう)

これは出来た(設定ファイルがコピーされたことも確認)けど起動時に`no such file or directory, open '/misskey/packages/backend/built/config/../../../../.config/default.yml'`が出る

**Comment by syuilo** [comment]
:tasukete:

**Comment by syuilo** [comment]
ブランチはこちら
https://github.com/misskey-dev/misskey/tree/okteto

**Comment by syuilo** [comment]
> k8sクラスターをよっこらしょして、Misskey本体とDBとRedisをステージング環境用のnyamespaceにデプロイして、JenkinsとかBuildkiteあたりのCI/CDツールのパイプラインを用意して…みたいにゃ

という方法もあるみたい

**Comment by futchitwo** [comment]
> developブランチの内容を自動でデプロイするようにしたい

co.misskey.ioとかdemo.misskey.ioでやってる事と同じだと思う(余談だけどco.misskey.ioの管理者しゅいろなんだ)

プルリク毎にデプロイするとかだと別だけど

**Comment by syuilo** [comment]
解決した人には¥5000進呈します

**Comment by tamaina** [comment]
pin外していい？

**Comment by syuilo** [comment]
外した

**Comment by syuilo** [comment]
自動じゃなくて手動でデプロイするようにしたい(自動だとすぐデプロイ上限に達するので)

**Comment by ikuradon** [comment]
手動でデプロイ、okteto/deploy-previewが対応してくれないとimjohnbo/ok-to-testが使えないので泣いています…

**Comment by syuilo** [comment]
oktetoに頼らずとも頑張れば自前で手動デプロイシステム作れそう😌

**Comment by syuilo** [comment]
もしくはoktetoがAPI公開しているのであればそれを叩くとか...？

**Comment by tamaina** [comment]
ん？.github/workflows/preview.yamlを[手動でトリガー](https://docs.github.com/ja/actions/managing-workflow-runs/manually-running-a-workflow)すればいいんじゃないのかしら

**Comment by syuilo** [comment]
あれpreview.yamlってどこかしら

**Comment by tamaina** [comment]
そもそも存在しない件

**Comment by tamaina** [comment]
> PR時に動くようにするには次のファイルが必要（ユーザー名設定とかあるのでコミットには含めていない）
> https://github.com/misskey-dev/misskey/pull/8335

**Comment by tamaina** [comment]
ちがうわ

> Okteto自身がPR監視できるようになったため、GitHub Actionsが要らない≒Secrets問題解決したっぽい

**Comment by syuilo** [comment]
それは要らない結論になってるわね
https://github.com/misskey-dev/misskey/pull/8335#issuecomment-1077513992

**Comment by ikuradon** [comment]
Oktetoがイベント監視してくれる設定が出たので要らないって書いたけど、イベント監視≒全てデプロイなので…

**Comment by ikuradon** [comment]
あと、dispatcherがpull_request以外だとokteto/deploy-previewがちゃんと動かないっぽいのでそこら辺を見ないといけない

**Comment by ikuradon** [comment]
コマンド直叩きはここら辺でなんとかなりそう
https://www.okteto.com/docs/reference/cli/#deploy-2

**Comment by tamaina** [comment]
workflow_dispatchって外部ブランチからのPull Request使えない感じがする

([pull_request_targetでラベルで制御するみたいな解決策がある](https://pankona.github.io/blog/2021/03/29/github-actions-pull-request-target/)らしいけどスマートではない…w)

**Comment by ikuradon** [comment]
ok-to-testとdeploy-previewを動くようにしています…

**Comment by ikuradon** [comment]
#8799 から動くようになった`/deploy`、コマンドを叩くたびに再デプロイされ、永続化されていないPostgresがリセットされる挙動なのでご注意ください

**Comment by syuilo** [comment]
`sha=foo`の部分省略できないかな

**Comment by acid-chicken** [comment]
🚀
