### ISSUE TITLE
Improve "Keep Content Warnings", add `re:` option

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8336]
## Summary

- Keep Content Warnings should be *on* by default for all users
- There should be an option to enable `re:` on Keep Content warnings.

ex. 
Post is: 
```
Dogs
▼
here is a picture of my dog
```

With re option on, reply is:
```
re: Dogs
▼
⮩ @user what a cute dog!
```

**Comment by Johann150** [comment]
The 1st point could be easily addressed by changing the default value in `packages/client/src/store.ts`.

And IMHO the 2nd point should not be supported since it would complicate the implementation unnecessarily.
