### ISSUE TITLE
Safari 15.4でアバターのposition: stickyがバグる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8338]
![image](https://user-images.githubusercontent.com/7973572/154888580-732ea54d-7027-47e5-9f2d-ef4dcb62ced8.png)

ノートの中でtopが効いている状態になってしまう

## 📌 Environment

Misskey version: 12.107.0
Your OS: iOS 15.4 Beta 3
Your browser: Safari 15.4 Beta

**Comment by syuilo** [comment]
CSS Containmentを使うとそうなるっぽい

**Comment by tamaina** [comment]
CSS Containmentの趣旨としては正しそう

**Comment by syuilo** [comment]
> CSS Containmentの趣旨としては正しそう

そう？
BlinkとGeckoでは付いてくるしWebkitのバグじゃないかしら

**Comment by tamaina** [comment]
まあたしかに、stickyは親要素に影響を与えるわけではなさそうなので動いてもいいとは思う

**Comment by tamaina** [comment]
正式リリースでも直らなかった

**Comment by tamaina** [comment]
> CSS Containmentのスイッチ自体はiOS 15.3.1以前でもデフォルトでオンだったから、今バージョンから何かしらの変更が入ってるのは明らか
https://misskey.io/notes/8xulx2n5a4

らしい

**Comment by tamaina** [comment]
contain: content; を外してもバグるぞこれ

**Comment by tamaina** [comment]
(ついでに実験的機能でclipをオンにして)  

note.vue(.tkcbzcuz)のoverflow: clipとcontain: contentの両方を削除したらこうなった(topの基準がひとつ外に出てきた)

![image](https://user-images.githubusercontent.com/7973572/161308762-cfe86311-8d99-4ee8-a95a-08a3ae02b62c.png)

**Comment by tamaina** [comment]
._panel (._blockがextend)のoverflow: clipを削除したら意図した動きになった

![image](https://user-images.githubusercontent.com/7973572/161309671-1d99c667-7fdf-4c97-a2e9-8b10e8066802.png)

**Comment by tamaina** [comment]
- contain: contentを外したところで、overflow: clipが実験的機能でなくなった際に同じような事象が起きる
- SafariのバグなのかCSSの厳密な仕様なのか私はわかってない（ただ、仕様に厳格とされるFirefoxでは意図した動作をする）

**Comment by syuilo** [comment]
よく分かってないけどoverflow: clipがSafariではoverflow: hiddenと同じような扱いになってしまってるってことかしら

**Comment by syuilo** [comment]
本来:
hiddenの中でposition: stickyは使えないけど、clipの中でなら使える

Safari:
hiddenの中でposition: stickyは使えないし、clipの中でも使えない

**Comment by tamaina** [comment]
そんな感じ

**Comment by tamaina** [comment]
containについては、contain: paintで誤動作を起こし、contain: layoutでは意図した動作になった

**Comment by tamaina** [comment]
タイムラインのモックアップ  
https://codepen.io/tamaina/pen/wvprLNB

**Comment by tamaina** [comment]
contain: paintのほう→ https://codepen.io/tamaina/pen/GRyOKQO
overflow; clipのほう→ https://codepen.io/tamaina/pen/OJzOLQv

本当はBugzillaにでも書きたいところだけどビルドアーカイブを試すためのMacなんて持ってない

https://webkit.org/build-archives/#mac-monterey-x86_64%20arm64

**Comment by syuilo** [comment]
15.5 public beta 2 で直った

**Comment by tamaina** [comment]
https://bugs.webkit.org/show_bug.cgi?id=231953  
https://bugs.webkit.org/show_bug.cgi?id=238016
両方直ったっぽいな
