### ISSUE TITLE
Oversized emojis cause big/big+ reaction drawer on mobile to misbehave

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8339]
## 💡 Summary

Having the big/big+ emoji reaction drawers on mobile leads to this:

https://user-images.githubusercontent.com/44733677/155006767-4052e1aa-7be8-4057-a3d4-819bf5ffe65e.mp4

https://user-images.githubusercontent.com/44733677/155003318-ef19cd20-6dcc-4650-b407-789623c56b18.mp4

## 📌 Environment

Misskey version: 12.107.0
Your OS: Android
Your browser: Chromium mobile, Hermit

**Comment by 4ioskd** [comment]
maybe... too many Big/Big+ emojis in your instance lead to these?

**Comment by futchitwo** [comment]
Try disabling "Use blur effects in the UI" (and "Use blur effect for modals") in Settings > General > Appearance.

**Comment by ThatOneCalculator** [comment]
> Try disabling "Use blur effects in the UI" (and "Use blur effect for modals") in Settings > General > Appearance.

Ok...that worked, but what's weird is that blur is ***still present*** despite the setting being off, but the bug is gone.

**Comment by Johann150** [comment]
Did you try reloading the page after changing the setting? Maybe just the preview is broken and we need to add a dialog box similar to other settings that this setting only applies after a page reload.

**Comment by ThatOneCalculator** [comment]
> Did you try reloading the page after changing the setting? Maybe just the preview is broken and we need to add a dialog box similar to other settings that this setting only applies after a page reload.

I reloaded, and even after restarting my phone it's the same

**Comment by nullobsi** [comment]
I can't reproduce this on Bromite, even with blur on or off.

**Comment by ThatOneCalculator** [comment]
I can reproduce in Bromite, but to a lesser extent than Firefox.

**Comment by ThatOneCalculator** [comment]
Update: I can reproduce this on Chrome mobile on my mom's phone, so it's not just my device.

**Comment by nullobsi** [comment]
What are the models of the devices used?
Mine: Note 20 Ultra, android 12

**Comment by ThatOneCalculator** [comment]
> What are the models of the devices used?
> Mine: Note 20 Ultra, android 12

Devices used: 

- OnePlus 7 Pro, Android 11
- OnePlus 8 Pro, Android 11

**Comment by ThatOneCalculator** [comment]
Update: after resetting my default emojis, the issue went away; it seems to be related to having odd-sized emojis maybe

**Comment by ThatOneCalculator** [comment]
Closing now that this is irrelevant and i can no longer reproduce the issue
