### ISSUE TITLE
Wrong info during initial user set

### ISSUE THREAD

**Issue by thunderclap82** [syuilo/Misskey#8340]
## 💡 Summary

During welcome tutorial the user is told "You can do this by pressing the pencil icon on the top of the screen."

## 🥰 Expected Behavior

A pencil icon at the top of the screen.

## 🤬 Actual Behavior

Pencil icon at the bottom of of the left column.

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by futchitwo** [comment]
Note that on mobile it is in the lower right corner of the screen

**Comment by Johann150** [comment]
I think the localisation would need to be fixed @robflop

**Comment by robflop** [comment]
Thanks for the report, I've updated the EN+DE translation. The problem however persists in the original japanese (and all other languages), fyi. That needs a separate fix that I can't do.

**Comment by syuilo** [comment]
NOTE:
「画面上」は「画面の上部」(top of the screen)という意味ではなく、「画面の中(画面のどこか)」(on the screen)という意味です。

**Comment by robflop** [comment]
おっ、なるほど、じゃあそれは僕の勘違いです。英語とドイツ語の翻訳を調整して欲しいですか？チュートリアルに特定の位置を教えたらいいと思います、けど変更が望んだらそうします。

**Comment by syuilo** [comment]
投稿ボタンの位置は使用しているデバイスやUIによって変わるので、具体的な位置を文章内で明示するのは難しいと思います。

> けど変更が望んだらそうします。

お願いします🙏

**Comment by robflop** [comment]
調整しました
