### ISSUE TITLE
デフォルトUI(PC)で設定の子ページのリンクを正しく開けない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#8342]
## 💡 Summary

https://misskey.io/settings/general などの設定の子ページへのリンクを開いたとき、メインカラムの内容がプロフィール設定になる。
![image](https://user-images.githubusercontent.com/74236683/155207876-1e232248-7cbc-41d1-83b5-a38d50b13e8d.png)

## 🥰 Expected Behavior

メインカラムのコンテンツとして正しいものが表示される

## 🤬 Actual Behavior

メインカラムのコンテンツがプロフィール設定ページになる

## 📝 Steps to Reproduce

1. (https://misskey.io/settings/general など)
2.
3.

## 📌 Environment

Misskey version:　v12.107.0
Your OS: windows10
Your browser: chrome

**Comment by futchitwo** [comment]
#8507 プルリクが出ているのでこちらをクローズ

**Comment by tamaina** [comment]
Duplicate of #8507

(管理用
