### ISSUE TITLE
(モバイルでは)デフォルトでぼかし効果を無効にする

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#8343]
## Summary
#7274 #7296 (#8339？) のように、スペックの低いAndroidやＷindows端末では、ぼかし効果によって動作がもっさりしたりリアクションピッカーが正しく表示されなくなったりしてUXに支障をもたらすため。

**Comment by tamaina** [comment]
Rakuten Hand, Redmi 9T, OPPO A73ではそんなに気にならなかったので、原因はスペックの高低じゃないような気がする

**Comment by tamaina** [comment]
(ブラーが重い問題、村上さんに結構文句言われてもそのままだったので、しゅいろはあんまり対処したがらない…

**Comment by futchitwo** [comment]
fixed by https://github.com/misskey-dev/misskey/commit/cef448f0f290e0ef265dad0ba22e05b1e220ddb7
