### ISSUE TITLE
Grouping Notifications

### ISSUE THREAD

**Issue by Freeplayg** [syuilo/Misskey#8347]
## Summary
Example from Twitter:
![image](https://user-images.githubusercontent.com/40742947/155366766-f9cf0518-58da-4957-b0f2-d5d9b0dac576.png)

**Comment by Johann150** [comment]
related to #8269

**Comment by syuilo** [comment]
Misskeyは同じ投稿に対して様々なリアクションが付けられますが、どのようにグルーピングしますか？

**Comment by Freeplayg** [comment]
(I translated above)
Something like this maybe?
![image](https://user-images.githubusercontent.com/40742947/155900595-8a91a892-142d-44fa-b187-2afc1fbdb73d.png)

Hovering over the emoji's could show who reacted

**Comment by kakkokari-gtyih** [comment]
Done in f62ad3ed3eccfd242b2d1f1e25f00276f2bfff77
