### ISSUE TITLE
NSFW posts with links don't have image previews blurred

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8351]
## 💡 Summary

If there's a post with NSFW media but it has links with previews, the previews aren't blurred

## 🥰 Expected Behavior

Previews are also blurred

## 🤬 Actual Behavior

(Manual censoring with red bars)
![image](https://user-images.githubusercontent.com/44733677/155584216-219c5fe0-f2ae-45e2-a2ba-c46c7d3aa5f2.png)

## 📌 Environment

Misskey version: [c0fd769](https://github.com/misskey-dev/misskey/commit/c0fd7697b9d1e9b0d22bf9d10870b8ac94be659b)
Your OS: Linux
Your browser: Librewolf

**Comment by 4ioskd** [comment]
maybe related to #4128 and mei23#1475
if syuilo can't improve summlay or don't have a time to improve it, summaly is needed to remove?
by the way, i think it's worth of considering #3905

**Comment by ThatOneCalculator** [comment]
I agree mostly, but Misskey is already a heavy webapp as it is, machine learning (#3905) would be way too heavy for most web browsers.

**Comment by syuilo** [comment]
Since NSFW is a flag that is assigned to individual files, there is no problem with this behavior. Probably CW should be used in this case, and it is an operational issue for the user.

**Comment by syuilo** [comment]
The issue of sensitive images possibly appearing as thumbnails in URL previews should be a separate Issue if necessary.

**Comment by ThatOneCalculator** [comment]
> The issue of sensitive images possibly appearing as thumbnails in URL previews should be a separate Issue if necessary.

I feel like that's the major discussion of this issue :/

**Comment by 4ioskd** [comment]
>The issue of sensitive images possibly appearing as thumbnails in URL previews should be a separate Issue if necessary.

このissueは「NSFWなメディア（画像？リンク先から自動でフェッチしたものであろう）のある投稿をすると、そのメディアはぼかされるがリンクプレビュー内のメディアがぼかされない」という話であり、確かにメディアに対してはNSFWフラッグが付いているものの、基本的にはここで議論することに間違いは無いように思える。
NSFW(NotSafeForWork)なメディアは基本的にセンシティブ（扱いに注意を要する）ものであり、児童ポルノや青少年にとって有害な画像がリンクプレビュー内に掲載されてもぼかされない可能性があるなら、これはThatOneCalculatorの言うように

>I feel like that's the major discussion of this issue :/

このissueは大きな議論の対象と思える。

**Comment by syuilo** [comment]
CWを使ってもらえば良さそう

**Comment by Johann150** [comment]
> Since NSFW is a flag that is assigned to individual files, there is no problem with this behavior. Probably CW should be used in this case, and it is an operational issue for the user.

To put it differently: The solution is that if the post has a CW, the URL preview will not be displayed. The post itself does not have a NSFW flag other than the CW, and the NSFW flags of attachments are individual and separate from the CW of the post.

**Comment by nullobsi** [comment]
I agree, instead a CW should be applied by the bot.
It doesn't make sense to disable link previews just if a media is flagged as sensitive; that's a very loose heuristic.

Or, is there a way to disable link previews on MFM?
A syntax like:
`<https://url>`
could potentially disable the link from embedding.

**Comment by syuilo** [comment]
> Or, is there a way to disable link previews on MFM?

you can use
`?[text](https://misskey.io/)`

**Comment by ThatOneCalculator** [comment]
That's good! Sadly the bot that this was posted from is on Mastodon, but in the future that's good to know. Maybe mention that in the mfm-cheat-sheet?

**Comment by Johann150** [comment]
FYI: URLs in angle brackets are already a syntax for recognizing URLs with special characters. (e.g. misskey-dev/mfm.js#98) You are of course welcome to add this to the MFM documentation in Misskey hub.

> the bot that this was posted from is on Mastodon

If they use a CW for the entire post, the URL preview would be hidden.
