### ISSUE TITLE
An event planner

### ISSUE THREAD

**Issue by akr2002** [syuilo/Misskey#8353]
I was going through my other social network accounts and stumbled upon this event planner in MeWe. It'd be cool to have something like this in Misskey too

![image](https://user-images.githubusercontent.com/21287366/155667847-b6a0a9c5-d633-4b3b-b260-9ccc6e95e1e8.png)

**Comment by Johann150** [comment]
Since Misskey is on the Fediverse you could use another service like [Mobilizon](https://mobilizon.org/). But adding this feature to Misskey itself would probably be quite complicated so I don't think we would want to do it.

**Comment by akr2002** [comment]
Neat stuff :eyes:
