### ISSUE TITLE
Option to display integrated accounts on public profile

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8355]
## Summary

Since we can already have that information privately, it would be good let users optionally display it on their profiles, given many people already put their Twitter handles/Github profiles/Discord tags in their bio/additional information.

![image](https://user-images.githubusercontent.com/44733677/155686125-fdc8c2db-eb0b-4ea6-bd7a-e5d772c58d8c.png)

**Comment by futchitwo** [comment]
duplicate of #7862
