### ISSUE TITLE
meta.errorImageUrl is unused

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8356]
## 💡 Summary

The database field `meta.errorImageUrl` is unused.

1. Use it in the client to solve #7043. It should also be added back to the admin menu.
2. Remove the dead code and database field.

## 📌 Environment

Misskey version: all 12.x.x

**Comment by 4ioskd** [comment]
藍.moeのサイトがメンテナンスされているのか分かりませんが...
misskey本体の開発等でしゅいろ氏が忙しいのなら、 meta.errorImageUrl を利用してクライアント内部に藍.moe由来のエラー画像をビルトインで埋め込むと、先々のサイトの維持やしゅいろ氏の負荷を踏まえて考えると良い気がします。

**Comment by Johann150** [comment]
I think it is similar for `meta.mascotImageUrl`. I could not find it in the client.

**Comment by 4ioskd** [comment]
related to https://github.com/misskey-dev/misskey/issues/3581 https://github.com/misskey-dev/misskey/pull/3589

**Comment by Johann150** [comment]
> インスタンス管理者が簡単に画像を差し替えられるようにしても良さそうですね
> It would be nice if the instance administrator could easily replace the image.

https://github.com/misskey-dev/misskey/pull/3589#issuecomment-446121344

So I think the first alternative is the correct one.

**Comment by 4ioskd** [comment]
>Ai is Misskey's official mascot.
https://misskey-hub.net/en/docs/glossary.html#ai

> Who's that cute cat-eared girl that you see sometimes?
>It's Misskey's guardian deity, Ai.(They called Ai cute, yay!)
>ℹ️ To read more about Ai, check here (Japanese-only).
https://misskey-hub.net/en/docs/misskey.html#who-s-that-cute-cat-eared-girl-that-you-see-sometimes

Ai(藍) is an official mascot character such like mastodon's mascot and has been received a huge love more than 3 years, as far as I know. I think many users(especially JP users) don't want to replace not-found Ai image with another image. I just wanna move its image from an external site( https://藍.moe ) to a local instance.

**Comment by 4ioskd** [comment]
As of this rencent issue https://github.com/misskey-dev/misskey/issues/8640#issue-1230652451 , I think we need to move an external site ( https://藍.moe ) images to a local instance. 

>Misskey で使用することの承認を得ているなら、ビルド時に外部依存として取り込んで再配布する分にはライセンス問題を回避できそう

I think this comment https://github.com/misskey-dev/misskey/pull/7044#issuecomment-753891800 solves Licence problem around Ai-chan's not-found images.
