### ISSUE TITLE
絵文字URL

### ISSUE THREAD

**Issue by Neko7sora** [syuilo/Misskey#8357]
## 💡 Summary
![image](https://user-images.githubusercontent.com/75793267/155736861-9cc57919-c420-4ae0-a204-6ef15e25b838.png)

## 🥰 Expected Behavior
リンクにクリックしてアクセスできる

https://🐱⭐🌈🐰.y.at/

## 🤬 Actual Behavior
リンクにクリックしてアクセスできない

## 📝 Steps to Reproduce

リンクを貼り付けてノートする

## 📌 Environment

Misskey version: 12.107.1-0
Your OS: Windows 11
Your browser: Edge

**Comment by Johann150** [comment]
Duplicate of misskey-dev/mfm.js#98
