### ISSUE TITLE
Bugs with the player

### ISSUE THREAD

**Issue by HSDChannel** [syuilo/Misskey#8360]
![chrome_wcbu6L4Dly](https://user-images.githubusercontent.com/72506029/155830165-8fabfe2c-d1be-4820-afa2-a8284fbedb69.gif)
Browser: Chrome

**Comment by Johann150** [comment]
As far as I know the Video player is not part of Misskey itself, but is the built in browser player. Could you try using another browser?

**Comment by ThatOneCalculator** [comment]
> Browser: Chrome


This is a known issue with Chrome/Chromium. Not Misskey related.
