### ISSUE TITLE
Editing notes

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8362]
## Summary

As of [17 days ago](https://github.com/mastodon/mastodon/commit/63002cde03a836b4510aca5da564504ecaedb5e9), Mastodon supports editing notes (and viewing the edit history). I think this is a major feature that would be a really big enhancement for Misskey, and shouldn't be *too* hard to implement.

**Comment by Johann150** [comment]
First of all I think that the ability to edit a note is a bad idea. I also don't understand how you get the idea that it would be "not too hard to implement".

In my opinion, the current delete & redraft system works fine. It can fix everything that you could fix by editing a note, while avoiding the many pitfalls that come with editing an existing note.

Furthermore Misskey is not Mastodon, so just because they do it doesn't mean we have to do it too.

**Comment by syuilo** [comment]
> First of all I think that the ability to edit a note is a bad idea. I also don't understand how you get the idea that it would be "not too hard to implement".
> 
> In my opinion, the current delete & redraft system works fine. It can fix everything that you could fix by editing a note, while avoiding the many pitfalls that come with editing an existing note.
> 
> Furthermore Misskey is not Mastodon, so just because they do it doesn't mean we have to do it too.

It is true that there are not many occasions when people want to edit a Note, and the current "delete and edit" is not much of a problem, so it would be a low priority.

**Comment by nullobsi** [comment]
I'm not sure about the implementation details of Mastodon's editing feature. Perhaps a new issue should be opened for at least federating/receiving post edits from Mastodon?

**Comment by tamaina** [comment]
How does mastodon implement federation of this feature?
@mei23

**Comment by Johann150** [comment]
> How does mastodon implement federation of this feature?

https://github.com/mastodon/mastodon/pull/16697 implemented receiving updates from the federation and showing what was changed. Then https://github.com/mastodon/mastodon/pull/17320 later allowed changing some attributes of a note via Mastodon's API. It is federated as an `Update` activity here:
https://github.com/mastodon/mastodon/blob/cb2e198d89dfb86a81fff8e11eac531b658e9ef2/app/workers/activitypub/status_update_distribution_worker.rb#L19-L27

**Comment by tamaina** [comment]
I have one more question: Does Misskey support `Update` activity from remote?

**Comment by Johann150** [comment]
Looks like only Actors and `Question`s can be updated currently:
https://github.com/misskey-dev/misskey/blob/d69f7baaf519c30e2775c7cebfcee625f6a9740e/packages/backend/src/remote/activitypub/kernel/update/index.ts#L25-L33

**Comment by tamaina** [comment]
I think Misskey should support updation of note text from remote immediately.

**Comment by Johann150** [comment]
> I think Misskey should support updation of note text from remote immediately.

👀👇
> Perhaps a new issue should be opened for at least federating/receiving post edits from Mastodon?

Since this issue is about being able to edit notes when you are on Misskey.

**Comment by tusooa** [comment]
I implemented editing in Pleroma: https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3678

**Comment by ThatOneCalculator** [comment]
Off-topic, but you should also PR that to Akkoma. Nice work!

**Comment by Johann150** [comment]
I think the correct issue for that is #8364.

**Comment by tamaina** [comment]
個人的な意見

- Misskeyにノート編集(notes/update, Note Update)を実装する必要はない、編集すると何に対してリアクションしたかが変わってくるので削除して編集の方が適切だと思う
- Mastodonなどの他のソフトで行われた変更を受信した際は編集を適用しリアルタイムに反映する必要がある→ https://github.com/misskey-dev/misskey/issues/8364
- Misskeyでリモートの編集履歴を保持する必要はない、編集履歴はオリジナルを参照すれば良い（Mastodonは嘘をつかないだろう）  
  編集済みフラグを保持し、何かしらの編集がされたことを表示するだけ

**Comment by rinsuki** [comment]
mastodon.socialとかならさておき別に悪意あるサーバーなら嘘つきまくれる

**Comment by kato83** [comment]
削除して編集でも良いとは思うのですが、Misskey をマイクロブログ（ブログ）として扱い人にとっては  
コンテンツを編集してしまうと投稿時に URL が変わってしまうのが Google 検索だったり他のサイト等からの  
自然流入の観点的には喜べるものでは無いのかなと思ったりしました。  
（issueでそんな観点が挙がってないのでそのような用途ではあまり使用されていないのかもしれないですが……）

SNS として使う分には上でのやりとりの通り問題ないかなと。

**Comment by acid-chicken** [comment]
ノートが編集できた方が自然なユースケースが出てきた (See #3217)

**Comment by suoko** [comment]
It woukd be a really nice feature

**Comment by ThatOneCalculator** [comment]
Inbound and outbound editing has already been implemented and refined in Calckey, and Misskey is free to reference our implementation.

**Comment by Vavency** [comment]
It could be worth taking a look at sharkey for this due to it being a recent fork that has note edits.

**Comment by syuilo** [comment]
done

**Comment by ThatOneCalculator** [comment]
This issue should be reopened. As far as I understand, editing has only been implemented for local posts (and newly fetching previously edited remote posts)

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/issues/11929

**Comment by syuilo** [comment]
後からメンションとかハッシュタグ追加された場合の対応などが面倒ということがわかった

**Comment by syuilo** [comment]
廃止したい

**Comment by syuilo** [comment]
実装コストに見合う価値がなさそうだし廃止するかしら

**Comment by tamaina** [comment]
廃止に賛成

削除して編集でいい

**Comment by acid-chicken** [comment]
少なくとも今の実装を据え置くよりは廃止した方が良い

**Comment by saschanaz** [comment]
>削除して編集でいい

マストドンからの編集への対応は必要かなと
