### ISSUE TITLE
🚨Upgrade & Migration to latest commit leads to migration error

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8363]
## 💡 Summary

After running `git pull` to get d071d18dd7a394298d454d4ef6c5ca885164dd47, running `NODE_ENV=production npm run build && npm run migrate` produces a successful build but a failed migration

## 🥰 Expected Behavior

Successful migration

## 🤬 Actual Behavior

```
> misskey@12.107.0-t1c-10 migrate
> cd packages/backend && npx typeorm migration:run
Error during migration run:
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/misskey/misskey/packages/backend/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/misskey/misskey/packages/backend/ormconfig.js:1:16
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

## 📝 Steps to Reproduce

1. `git pull`
2. `NODE_ENV=production npm run build && npm run migrate`

## 📌 Environment

Misskey version: d071d18dd7a394298d454d4ef6c5ca885164dd47
Your OS: Linux

**Comment by ThatOneCalculator** [comment]
Update: tried this on a *fresh clone* of Misskey and the same thing happens. I'd consider this breaking.

```
> misskey@12.107.0 migrate
> cd packages/backend && npx typeorm migration:run

Error during migration run:
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/misskey/misskey-test/packages/backend/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/misskey/misskey-test/packages/backend/ormconfig.js:1:16
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

**Comment by syuilo** [comment]
Strictly speaking, this is not the latest version, as it is still in the develop branch and has not been released yet.

**Comment by ThatOneCalculator** [comment]
> Strictly speaking, this is not the latest version, as it is still in the develop branch and has not been released yet.

Fair enough, but it's still a problem

**Comment by ThatOneCalculator** [comment]
Looks like this caused another error; Misskey won't even launch now.

```
INFO *  [core boot]     Starting 1 worker...
SyntaxError: Unexpected identifier
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
```

**Comment by syuilo** [comment]
Try using Node.js 16.14.0

**Comment by ThatOneCalculator** [comment]
> Try using Node.js 16.14.0

Upgrading seems to have fixed it, but I'm getting a bunch of other brand new errors, especially with file uploading that I've never seen before.

Ex. https://stepbro.voring.me/hteresisha
Ex. `ERR  1  [drive downloader]      Failed to create drive file: TypeError: S3 is not a constructor`
Ex. 
```
TypeError: push.setVapidDetails is not a function
    at default (file:///home/misskey/misskey/packages/backend/built/services/push-notification.js:25:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ThatOneCalculator** [comment]
And now Misskey entirely broke...

![image](https://user-images.githubusercontent.com/44733677/156033888-fc04db7d-17a5-4c32-bb18-9d928c0fab88.png)

**Comment by ThatOneCalculator** [comment]
@syuilo Could you please check DMs on Discord? It seems like my instance has now entirely broken...
