### ISSUE TITLE
Combine Notifications and Mentions

### ISSUE THREAD

**Issue by Freeplayg** [syuilo/Misskey#8365]
I feel like them being in separate pages is unnecessary, and having to click into Mentions to get rid of that new mention dot when I've already seen the message in notifications is annoying.
I would rather it be a tab in Notifications 
![image](https://user-images.githubusercontent.com/40742947/155894857-35828bbb-4c58-467a-9ee7-a72925dac7ca.png)

**Comment by Johann150** [comment]
Sounds like what you really want is to apply the read status across the tabs, which sounds more like a bug. I think having separate tabs makes sense.

**Comment by futchitwo** [comment]
The direct notes page seems to have the same issue

**Comment by Johann150** [comment]
I wonder if it is solved by commit 0f1c0a42a253dcc5758e4811aaa116708d482305

**Comment by ThatOneCalculator** [comment]
It is.
