### ISSUE TITLE
How do I disable two-factor authentication for a user?

### ISSUE THREAD

**Issue by lagemeet** [syuilo/Misskey#8368]
How do I disable two-factor authentication for a user?
No recovery code or something, how can i disable it?
I'm administrator of instance i have full access to it

**Comment by Johann150** [comment]
The administrator could disable two factor authentication with this SQL query:
```sql
UPDATE "user_profile" SET "twoFactorEnabled" = false WHERE "userHost" IS NULL AND "userId" = '<id>';
```
Replace `<id>` with the ID of the user (leave the single quotes). You can find the ID of a user by going to their profile page, click the three dots next to the follow button and select the "About" menu entry.

**Comment by absturztau-be** [comment]
it would be nice for admins to be able to do this in the UI

**Comment by Johann150** [comment]
I do not think it would be sensible to allow administrators to change any user setting. For this particular situation I think recovery keys or another recovery strategy would be more sensible. As such, this is a duplicate of #7253.

**Comment by Johann150** [comment]
Resetting 2FA was also covered in #6143.
