### ISSUE TITLE
User settings shouldn't be accessible when logged out

### ISSUE THREAD

**Issue by pixeldesu** [syuilo/Misskey#8377]
## 💡 Summary

If you are not logged in, user settings pages (`/settings/*`) are accessible, but don't render anything because no user information is available. Nothing really can be done here, but it is a UX problem regardless.

## 🥰 Expected Behavior

Instead of seeing an empty/broken page, we should either see the login dialog pop up, prompting a login or a redirect to a login page, that brings us back after successfully authenticating.

## 🤬 Actual Behavior

It's possible to visit any settings page without being logged in.

## 📝 Steps to Reproduce

1. Be not logged in to a Misskey instance (log out or open a private window)
2. Navigate to a settings page over a URL (e.g. `/settings/general`)
3. Be presented an empty page

## Additional Info

Considering I already ported the settings index to the Composition API (#8374) I want to work on this task right away too. I got relatively far already (showing the login dialog on `/settings/*` if no one is logged in, but there are a few problems:

If the dialog is closed manually (user did not log in), the user should be redirected away from the page, but there is no real way to achieve this yet. `signin-dialog` only emits `closed` which also is used on successfully logging in.

I looked a bit more into `XModalWindow` and further emitting `close` (manual closing event) from the sign-in dialog instead of just calling `dialog.close()` might fix this (with an `onClose` method of course).

**Comment by sandycorzeta** [comment]
Please do if you willing to fix it. I already tried to ask this directly to @syuilo [few months ago](https://misskey.io/notes/8ttqqnloi8), but it seems still not in urgent or important enough due no confidential information / risking stuff is shown on settings page.

**Comment by NovaAndrom3da** [comment]
> due no confidential information / risking stuff is shown on settings page.

Wait, aren't user profile options included in the settings page?

**Comment by Johann150** [comment]
The API is authenticated, so the settings pages will be empty or have errors when trying to fetch information. This is not a security concern.
