### ISSUE TITLE
"Add caption" dialog is broken in mobile

### ISSUE THREAD

**Issue by nullobsi** [syuilo/Misskey#8381]
## 💡 Summary
On mobile, it is hard to use the image caption dialog with some images. There used to be a scroll bar, but now it does not appear. If the image takes up a lot of vertical space, the text box is unreachable.

## 🥰 Expected Behavior
The entire dialog should be scrollable, like it was in earlier Misskey versions.

## 🤬 Actual Behavior
It is not scrollable, and the image crowds out the text box.

## 📌 Environment

Misskey version: 12.107.0
Your OS: Android
Your browser: Firefox mobile & Chromium mobile

**Comment by ThatOneCalculator** [comment]
Im unable to reproduce this issue (Chromium, Android 11, latest Misskey commit)

https://user-images.githubusercontent.com/44733677/157086513-7ae8e03d-6e07-4d42-9926-e997957a608f.mp4

**Comment by nullobsi** [comment]
The text box is scrollable. What I mean is, when there is a large image; the text box becomes inaccessible, especially when the mobile keyboard is visible.

**Comment by nullobsi** [comment]
<details>
<summary>screen recording</summary>

https://user-images.githubusercontent.com/22283693/157089456-080ebcb2-e6dd-4a0d-9a80-560ac48c7e2f.mp4
</details>

AFAIK this occurs on both Firefox and Chromium mobile browsers.

**Comment by ThatOneCalculator** [comment]
That's really weird. I can't reproduce this on any of my mobile browsers, are you running the latest commits on the dev branch like my instance or the release ver 12.107.0?

**Comment by nullobsi** [comment]
Release version. Perhaps this was fixed

**Comment by nullobsi** [comment]
The issue still occurs on stop.voring.me.
![Screenshot_20220307-095303_Bromite](https://user-images.githubusercontent.com/22283693/157090126-c9272e31-534c-4d9a-b3a7-3748bdf4714f.jpg)

**Comment by ThatOneCalculator** [comment]
What phone/android version are you on? This is really weird, as Im unable to reproduce this on two seperate phones. Also, I doubt it's the issue but have you tried with a non-gruvbox theme?

**Comment by nullobsi** [comment]
That is a screenshot. Here's a better example image:

As you can see, the text input is there; But as soon as the image loads it is impossible to reach.

<details>
<summary>screen recording</summary>

https://user-images.githubusercontent.com/22283693/157091774-3fcd4e23-59d6-49e6-8624-9d679c6b2f19.mp4
</details>

<details>
<summary>2nd screen recording</summary>

https://user-images.githubusercontent.com/22283693/157091785-c4b2ea2e-9b49-4623-960f-aceea3a4cffd.mp4
</details>

**Comment by ThatOneCalculator** [comment]
With a vertical sized image, i actually was able to reproduce. 

https://user-images.githubusercontent.com/44733677/157095674-01c2a6d8-a167-47ed-bc78-a8f4333d2850.mp4

**Comment by nullobsi** [comment]
Yes, that's the point of this issue. :)
