### ISSUE TITLE
Warn user if `node` is outdated

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8387]
## Summary

Since a lot of people are coming from 12.107.0 and many don't have Node 16.14.0 installed yet, maybe have Misskey exit and display a message telling them to install the latest ver if `SyntaxError: Unexpected identifier` occurs. (As seen in errors such as #8386)

Proposed output:

```
$ NODE_ENV=production npm run start

> misskey@12.108.0 start
> cd packages/backend && node --experimental-json-modules ./built/index.js
  _____ _         _
 |     |_|___ ___| |_ ___ _ _
 | | | | |_ -|_ -| '_| -_| | |
 |_|_|_|_|___|___|_,_|___|_  |
 v12.108.0               |___|
 Misskey is an open-source decentralized microblogging platform.
 If you like Misskey, please donate to support development. https://www.patreon.com/syuilo
--- destiny.zotan.network (PID: 1362295) ---
INFO *        [core boot]        Welcome to Misskey!
INFO *        [core boot]        Misskey v12.108.0
INFO *        [core boot env]        NODE_ENV: production
INFO *        [core boot env]        You do not have root privileges
INFO *        [core boot nodejs]        Version 16.13.2
DONE *        [core boot config]        Loaded
INFO *        [core boot db]        Connecting...
DONE *        [core boot db]        Connected: v13.4
DONE *        [core boot]        Misskey initialized
INFO *        [core boot]        Starting 1 worker...
SyntaxError: Unexpected identifier
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)

===============================
Please install NodeJS 16.14.0!
===============================

$ 
```

**Comment by Johann150** [comment]
Administrators should also read the Changelog regardless. I know there has not been the best track record in the past, but it is in the changelog this time.

**Comment by ThatOneCalculator** [comment]
The changelog is only in Japanese though, afaik.

**Comment by Johann150** [comment]
yes but that does not stop you from using a translator

**Comment by 4ioskd** [comment]
related to https://github.com/misskey-dev/misskey/issues/4693

**Comment by Johann150** [comment]
This already seems to be something to do this, it was just not maintained with the current version:
https://github.com/misskey-dev/misskey/blob/6cd3ff5848426c766958f52238548c4c897a0a23/packages/backend/src/boot/master.ts#L91-L93
Either this has to be updated as well as the `.node-version` file, or it could be read from there `.node-version`, if the file content is better maintained.

**Comment by nbsp** [comment]
> Administrators should also read the Changelog regardless. I know there has not been the best track record in the past, but it is in the changelog this time.

just as an aside, I think it would make sense to have a copy of the changelog in the git tag as well, or better -- pipe the git shortlog into the tag description. it's quite annoying to have to pull the repository and look in `CHANGELOG.md` instead of just receiving it by email through GitHub.
