### ISSUE TITLE
ノートを作成時のリアクションピッカーが自分の選択したサイズにならない

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8389]
## 💡 Summary
リアクションピッカーが自分の選択したサイズにならない

## 🥰 Expected Behavior
リアクションピッカーが自分の選択したサイズになる

## 🤬 Actual Behavior
サイズ大、列の数9、高さ大＋を選択しているのに、nきーを押してノートを作成しようとしてリアクションピッカーを開くと自分が選択したサイズと異なったサイズになったしまう
![image](https://user-images.githubusercontent.com/89781396/157583622-d2092247-039c-48a8-9553-7e24e5d7171e.png)
![image](https://user-images.githubusercontent.com/89781396/157583955-da29da4a-08a5-4c78-9c51-53490bb94dee.png)

## 📝 Steps to Reproduce

1.nきーを押してノートを作成しようとする
2.リアクションピッカーを開くボタンを選択する

## 📌 Environment

Misskey version: 12.108.0
Your OS: windows11Pro
Your browser: chrome99.0.4844.51, firefox98.0

**Comment by ThatOneCalculator** [comment]
Related (possibly duplicate):  #8345
