### ISSUE TITLE
Allow admins/mods to delete channels

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8391]
## Summary

On the instance I own, there's a channel a user made which I can't seem to delete. Admins and moderators should be able to delete channels.

**Comment by Johann150** [comment]
There is currently no API functionality to delete channels thus no ability to allow moderators to delete channels. I don't know if it is planned, although I would assume so.

As admin with direct database access you should be able to delete a channel with a `DELETE FROM channel WHERE ...` etc. query. Note that this will also cascade the delete to all notes in that channel.

**Comment by Johann150** [comment]
I think there is no need to keep a separate issue, the main issue is #7171. The comments above may be added to the consideration.
