### ISSUE TITLE
link preview on Pleroma no longer shows post

### ISSUE THREAD

**Issue by nbsp** [syuilo/Misskey#8392]
## 💡 Summary
possibly out of scope, but seeing as this used to work fine until 12.108.0, I thought I'd mention it.

Misskey no longer sends the relevant data to link previews, meaning Pleroma users can't see what posts quotes refer to.

## 🥰 Expected Behavior

up until and including 12.107.0, whenever a Misskey post was quoted, Pleroma users could see what the quote was referring to using the link preview feature:

![pleroma screenshot of misskey quote, where the link preview shows the text of the original post](https://user-images.githubusercontent.com/57151943/157703880-25dbea8f-bcf5-42d7-a707-8fc5685cfa3f.png)

## 🤬 Actual Behavior

however, since the recent update, Misskey links seem to show the instance homepage metadata, regardless of what's being linked.

![pleroma screenshot of misskey quote, showing the instance metadata and information instead of the original post](https://user-images.githubusercontent.com/57151943/157703892-a65ab5e8-68a8-4c7c-a1f2-2375c71e015b.png)

## 📝 Steps to Reproduce

1. QRT any post from a Misskey instance running 12.108.0
2. view the quote on pleroma

## 📌 Environment

Misskey version: 12.108.0
Your OS: N/A
Your browser: N/A

**Comment by Johann150** [comment]
It seems that the URL parameters are not being replaced by koa. The value of `ctx.params.note` is `:note` as I found out by logging it before this line is executed: https://github.com/misskey-dev/misskey/blob/6cd3ff5848426c766958f52238548c4c897a0a23/packages/backend/src/server/web/index.ts#L232

This seems to also be the case for other routes, for example if you try to go to a users RSS feed you will get an error page (the `@:user.rss` route).
