### ISSUE TITLE
API consoleのParamsの自動入力が動かなくなっている

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#8415]
## 💡 Summary

少なくとも12.107.1時点までWebクライアントのAPI consoleでEndpointを指定するとParamsに有効なパラメーターが自動で入力されていましたが、現状(12.108.1)動かなくなっています。
ref. https://misskey.io/notes/8xx0vrbaa3

お得機能だったので何卒復活させてあげてほしい…

## 🥰 Expected Behavior

エンドポイントを指定すると有効なパラメーターが自動でParamsに入力される

## 🤬 Actual Behavior

エンドポイントを指定してもParamsが空のまま

## 📝 Steps to Reproduce

1. API consoleで任意のエンドポイントを指定する

## 📌 Environment

Misskey version: 12.108.1
Your OS: Windows 10 (21H1)
Your browser: Google Chrome 99.0.4844.51 (Official Build)

**Comment by Johann150** [comment]
`/api/endpoint` is not working correctly.

**Comment by ThinaticSystem** [comment]
Thank you!🥰
