### ISSUE TITLE
ActivityPub delivery can cause race conditions in 3rd party software

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8428]
## 💡 Summary
If both a `Followers` and `Direct` recipe are added to the Deliver Manager, two activities may be sent to the same instance.
This can for example happen when sending a reaction, because it is sent directly to the author of the note and to all followers.

I came across this while testing something and it caused a race condition in Pleroma, leading to the activities not being performed correctly. It also leads to unecessary network congestion and load on remote servers.

## 🥰 Expected Behavior

Each activity is only sent to each instance once.

## 🤬 Actual Behavior

Activities may be sent two or more times.

## 📝 Steps to Reproduce

There are multiple ways in which this issue can occur and because it is a race condition in 3rd party software, it may not always work. I found that it often happened when doing this:

1. React to note from a Pleroma instance.
2. Remove reaction.
3. Reaction is not removed on Pleroma.

## 📌 Environment

Misskey version: at least all versions since 44ab428803c086255ad552502764238589b4860b

## 🔧 Possible Solutions

The issue occurs because of how `Direct` recipies are handled:
https://github.com/misskey-dev/misskey/blob/c928941d297c5db383afcfd7df8df8a0be3d7caa/packages/backend/src/remote/activitypub/deliver-manager.ts#L95-L99

If multiple recipients from `Direct` recipies happen to have the same shared inbox, Misskey ignores this. Misskey also ignores if the shared inbox of a direct recipient is already in the inboxes list.

This could be solved by:
1. Always use the shared inbox if it is available for a user. This ensures deduplication across direct and follower recipies.
2. When building inboxes, get both the inbox and shared inbox. Then deduplicate by shared inbox. If only one user from a specific instance is in the list, they will get the message to their individual inbox.

Alternative 1 is easier to implement. I think alternative 2 is just unnecessary work because individual and shared inboxes are often handled exactly the same anyway (Misskey also handles them the same). Therefore I think alternative 1 is the best solution.

**Comment by mei23** [comment]
At the very least, sending direct to the `sharedInbox` (alternative 1) can be a mistake.
In particular, I think Pleroma made a strict distinction between `inbox` and `sharedInbox`.

Also, if you exclude in deliverManager, not only `Like` but also `Note` will be affected.

Both `Note` and `Like` are now delivered to both `inbox` and `sharedInbox`, and I don't think this behavior itself is a mistake.
(Also, Duplicate activity usually happens when you think about relays.)

In this case, I think the receiving instance should be deduplicated by Activity ID.
(No change on the sender side.)

**Comment by mei23** [comment]
Maybe only deliverToFollowers is enough for `Like`?  
However, I don't know how other implementations will receive it.

**Comment by mei23** [comment]
> Maybe only deliverToFollowers is enough for Like?
> However, I don't know how other implementations will receive it.

When I tried it, it seems that it will reach both Mastodon and Pleroma just by delivering followers.

So you can simply delete the following. (Same for delete)
https://github.com/misskey-dev/misskey/blob/f68b6468788b33e10c8ad86104cf8792862eb5e9/packages/backend/src/services/note/reaction/create.ts#L123-L126

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/issues/8428#issuecomment-1073166904
Oops, it's possible that you're not followed, this is incomplete.

**Comment by Johann150** [comment]
> At the very least, sending direct to the `sharedInbox` (alternative 1) can be a mistake.

I think this behaviour is completely covered by the ActivityPub specification, I assume you are referring to this paragraph:

> Origin servers sending publicly addressed activities to `sharedInbox` endpoints MUST
> (1) still deliver to actors and collections otherwise addressed (through `to`, `bto`, `cc`, `bcc`, and `audience`) which do not have a `sharedInbox`
>**and**
> (2) would not otherwise receive the activity through the `sharedInbox` mechanism. 
- https://www.w3.org/TR/activitypub/#shared-inbox-delivery (reformatted by me)

Alternative 1 is in compliance with this because if an actor does not have a shared inbox, their direct inbox is used instead. This means that they will get the message if they do not have a `sharedInbox` (1). And as I understand it, if they do have a shared inbox and we deliver to the shared inbox, (2) makes it unnecessary to deliver it to the direct inbox again.

> Both `Note` and `Like` are now delivered to both `inbox` and `sharedInbox`, and I don't think this behavior itself is a mistake.

Yes, the current behaviour is not a mistake for ActivityPub, but that is not the issue. The problem is caused because other programs (like Pleroma) are apparently not prepared for behaviour like this:

> Also, Duplicate activity usually happens when you think about relays. In this case, I think the receiving instance should be deduplicated by Activity ID. (No change on the sender side.)

The difference between duplicate activities from relays and duplicates from the original instance is, that the original instance sends the two messages at *almost the same time*, while a relay usually takes a bit longer because they have to create a separate connection etc. When the two messages are sent at almost the same time, it can cause race conditions in other software while they are trying to deduplicate by activity ID.
Of course this means that the problem is strictly speaking not a Misskey problem, but because we still want our activities to federate correctly, we should be nice and accomodate them.

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/issues/8428#issuecomment-1073212214
Probably not mentioned in the specification and it seems that individuals addressed to should not be sent to shared.

**Comment by mei23** [comment]
Since `Follow` activity etc. are sent to the inbox, there is concern about changing it.

**Comment by mei23** [comment]
I found Misskey not giving a unique id to **Undo** Like Activity (Like Activity is unique). Check that it may be the cause.

**Comment by Johann150** [comment]
> I found Misskey not giving a unique id to Undo Like Activity (Like Activity is unique). Check that it may be the cause.

Oh, I did not see that before and I think it is likely related to the issue. I checked the [Undo Like test case for pleroma](https://git.pleroma.social/pleroma/pleroma/-/blob/develop/test/fixtures/mastodon-undo-like.json) and they use an ID that is just the same ID of the activity with `/undo` appended. I think we should be able to do the same.

Nevertheless, I think it would be good to not send duplicate activities because of the other reasons I mentioned: It leads to unnecessary network congestion and load on remote servers.

> Probably not mentioned in the specification and it seems that individuals addressed to should not be sent to shared.

It does not say it is forbidden so I assume it is allowed.

**Comment by mei23** [comment]
> I found Misskey not giving a unique id to Undo Like Activity (Like Activity is unique). Check that it may be the cause.

Made `Undo Like Activity id` unique, but not fixed.

As far as `Like Activity` is concerned, there is no concept of destination, so I think there is no problem with sharedInbox. 
However, I don't want to change destinations other than `Like Activity`. 


> It does not say it is forbidden so I assume it is allowed.

I don't want to trust the ActivityPub specifications.
I've heard implementations that separate processing, at least inbox or sharedInbox, so I think it's best to avoid changes.

**Comment by Johann150** [comment]
If there may be duplicate activities sent, the fallback ID generator is probably not a good idea because it may lead to similar issues:

https://github.com/misskey-dev/misskey/blob/aebd77ad38583ee3a5d7e922435191b7d504339d/packages/backend/src/remote/activitypub/renderer/index.ts#L11-L13

**Comment by mei23** [comment]
`duplicated activities may have different IDs` doesn't seem to have anything to do with this issue.
So I think it's better to create another issue. 

> I found Misskey not giving a unique id to Undo Like Activity (Like Activity is unique). Check that it may be the cause.

Made Undo Like Activity id unique, but not fixed.

**Comment by mei23** [comment]
Deduplication has fixed the problem.
