### ISSUE TITLE
設定でメールアドレスが更新できない/新規登録できない

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8430]
## 💡 Summary

設定からメールアドレスを変えようとすると内部エラーで更新できない。
また、新規登録のモーダルでメールアドレスを入力するとエラーが発生する。
そのまま無視して登録するとエラーが発生する。

## 🥰 Expected Behavior

メールアドレスが更新できる。

新規登録できる。

## 🤬 Actual Behavior

設定からメールアドレスを変えようとするとこんなモーダルが出る。

<img width="529" alt="スクリーンショット 2022-03-20 9 23 20" src="https://user-images.githubusercontent.com/79352785/159143280-e430f3e4-b910-420f-bef1-a058f0375806.png">

`i/update-email` のレスポンス:
```json
{
  "error": {
    "message": "Internal error occurred. Please contact us if the error persists.",
    "code": "INTERNAL_ERROR",
    "id": "削除しました",
    "kind": "server",
    "info": {
      "e": {
        "message": "validateEmail is not a function",
        "code": "TypeError",
        "stack": "TypeError: validateEmail is not a function\n    at validateEmailForAccount (file:///path/to/misskey/packages/backend/built/services/validate-email-for-account.js:8:29)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async file:///path/to/misskey/packages/backend/built/server/api/endpoints/i/update-email.js:48:27\n    at async default (file:///path/to/misskey/packages/backend/built/server/api/call.js:89:12)"
      }
    }
  }
}
```

---

また、新規登録のモーダルでメールアドレスを入力するとこんな表示が出る:
<img width="337" alt="スクリーンショット 2022-03-20 9 51 18" src="https://user-images.githubusercontent.com/79352785/159143459-38cd79fa-afbd-4005-bf0f-2084c17f6fa9.png">

無視して登録するとエラーが起きる:
<img width="343" alt="スクリーンショット 2022-03-20 9 52 28" src="https://user-images.githubusercontent.com/79352785/159143505-8d05787c-2361-4a76-997c-2dea8907f75f.png">

`email-address/availabe` のレスポンス:

```json
{
  "error": {
    "message": "Internal error occurred. Please contact us if the error persists.",
    "code": "INTERNAL_ERROR",
    "id": "削除しました",
    "kind": "server",
    "info": {
      "e": {
        "message": "validateEmail is not a function",
        "code": "TypeError",
        "stack": "TypeError: validateEmail is not a function\n    at validateEmailForAccount (file:///path/to/misskey/packages/backend/built/services/validate-email-for-account.js:8:29)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async file:///path/to/misskey/packages/backend/built/server/api/endpoints/email-address/available.js:30:12\n    at async default (file:///path/to/misskey/packages/backend/built/server/api/call.js:89:12)"
      }
    }
  }
}
```

## 📝 Steps to Reproduce

1. 「設定」の「メール」を開く
2. メールアドレスを入力する
3. 保存ボタンを押す
4. パスワードを入力する

---

1. 新規登録のボタンを押す
2. 各種情報を入力する
3. 「始める」ボタンを押す

発見したのは自分が建てたインスタンスですが、misskey.ioでも同じエラーを確認しました。

## 📌 Environment

Misskey version: 12.108.1
Your OS: macOS Big Sur (11.6)
Your browser: Google Chrome 99.0.4844.74（Official Build） （x86_64）

**Comment by acid-chicken** [comment]
Duplicate of #8404

次リリースで修正されます。
