### ISSUE TITLE
Cat Mode Breaking Mentions

### ISSUE THREAD

**Issue by NovaAndrom3da** [syuilo/Misskey#8431]
## 💡 Summary
"Cat mode" breaks mentions in users and instances containing "nu" or "na" by inserting a "y".

## 🥰 Expected Behavior
Mentions should be exempt from the cat mode filter

**Comment by ThatOneCalculator** [comment]
I can't reproduce this. 

(Screenshot below is me, with cat mode on, mentioning someone with "na" in their tag)
![image](https://user-images.githubusercontent.com/44733677/159202152-8cfaeb8c-3f81-4c2a-89fb-6880d2b47e20.png)

**Comment by Johann150** [comment]
I know that these exist, so just to be sure: are you using plugins to "nyaify" texts?

**Comment by Johann150** [comment]
I can also not reproduce this, and the responsible code was not changed recently. It only modifies `text` MFM nodes which means it does not touch mentions.
https://github.com/misskey-dev/misskey/blob/725b78349a9bb34e5f084a802ae7ea5369dc0bd3/packages/backend/src/models/repositories/note.ts#L268-L273

Therefore I heavily suspect you are using a plugin for which we can not provide support here.
