### ISSUE TITLE
通知が届かないことがある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8435]
## 💡 Summary

ストリーミングでは流れてきてるけど、UIに反映されないケースと、そもそもストリーミングに流れてこないケースの二種類がありそう

misskey.ioで確認
軽く試した感じmk.f72u.netでは再現しなかった
ローカルではまだ検証していない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

ChromeでもFirefoxでも発生する

Misskey version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
ioだけの現象の可能性が高くなってきた

**Comment by SanMurakami** [comment]
ioは特に特殊なことはしてない（通知周りは何もいじってない）のでioだけの可能性って考えにくい。

構成としてはMisskey本体が複数立ってて同じRedis、PostgreSQLに接続されてるのが複数ある。
そしてMisskey本体からNginx、セキュリティルーターを通ってCloudflareで公開。

RedisやPostgreSQLとの通信は各ノード20ms程度だし、今までも2年近くこの構成で運用してきたから直接的な原因とは考えにくい。

**Comment by SanMurakami** [comment]
投稿数や利用人数、負荷などで発生する可能性を考慮してほしい。
それらで発生する場合はio規模ではたまに発生するけど、個人インスタンスや小規模インスタンスでは発生しない可能性がある。

**Comment by mei23** [comment]
idが被ってるのでは
aid かつ 複数ノードだと結構被るはずだわ
https://github.com/misskey-dev/misskey/issues/6439

**Comment by syuilo** [comment]
あまりアクティブユーザーが少ない時間帯でやっても発生するから、被りの可能性は低そう
とはいえ現状のaid廃止したいわね

**Comment by syuilo** [comment]
あと最近急に発生するようになった気がする

**Comment by mei23** [comment]
> あまりアクティブユーザーが少ない時間帯でやっても発生するから、被りの可能性は低そう
> あと最近急に発生するようになった気がする

プロセスごとに 00 - zz (1296通り) のカウンタを乱数起点で巡回するから
最初の乱数の引きとか運が悪いと (他のid生成の量によらず) ずっと被り続けるかもと

**Comment by syuilo** [comment]
ほむ
でもレコード自体は作成されてるのにストリーミングでイベントが流れてこないことにid被り関係するかしら

**Comment by mei23** [comment]
レコード作成が成功しているならid被りは関係ないかもだわ

**Comment by syuilo** [comment]
なんか再現しなくなった気がする(Misskey側は何も変えてない)

**Comment by SanMurakami** [comment]
こっちも特に何もいじってない

**Comment by syuilo** [comment]
全く再現しなくなったから一時的な回線の不調とかかも
