### ISSUE TITLE
`<style module>` (CSS Modules)を使うようにする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8459]
## Summary
旧題名: パフォーマンスのためにCSSのネストをなるべく浅くする
For performance, CSS selectors should not be nested (not be combined, reduce combinator) as possible.

こういう記事を見つけた: https://qiita.com/mamiyan/items/778183160e9e58546824  
（ただし最新ブラウザでもう一度検証する必要はある）

**Comment by tamaina** [comment]
正確な数値取りとかしてないけどとりあえずnoteコンポーネントを改造してみた

https://github.com/tamaina/misskey/commit/cbbd835f8e6ac45f383b0e02032c0daa5128b8ce

うーん、体感できるほど改善していないような気もする

**Comment by tamaina** [comment]
divとか> spanとか> buttonとか> articleみたいな多くの要素に引っかかりそうなセレクタを狙い撃ちで潰していくのがいいのかも

**Comment by syuilo** [comment]
> 正確な数値取りとかしてないけどとりあえずnoteコンポーネントを改造してみた
> 
> [tamaina@cbbd835](https://github.com/tamaina/misskey/commit/cbbd835f8e6ac45f383b0e02032c0daa5128b8ce)
> 
> うーん、体感できるほど改善していないような気もする

徹底してやるならCSS Modules使った方が便利そう

**Comment by tamaina** [comment]
https://v3.ja.vuejs.org/api/sfc-style.html#style-module

こういうのあるんだ

**Comment by tamaina** [comment]
max-width/min-widthとかはどうしよう（datasetでいいか）

**Comment by tamaina** [comment]
あと、単純にハイフンで付け足していくなら`&-hoge`みたいなセレクタにすればいいことを思い出した

**Comment by tamaina** [comment]
> こういうのあるんだ

正直CSS Modulesをあんまり知らなかったのはまああるんだけど、Misskeyが採用しないならとVueにないんじゃねと勝手に思っていた（なぜ採用されていなかったのかは知らない）

というわけでこれから全部CSS Modulesにしようぜ！

**Comment by syuilo** [comment]
> （なぜ採用されていなかったのかは知らない）

スタイル当てたい要素全てに一意な名前付けなきゃいけないのめんどくさそう
全部のクラスがフラットになるからSCSSの入れ子表記も使えなくなって書きにくい

**Comment by tamaina** [comment]
> スタイル当てたい要素全てに一意な名前付けなきゃいけないのめんどくさそう
> SCSSの入れ子表記

SCSSなので、`&`使えば入れ子表現をそのままに文字列を親の後ろに結合できる（ただしHTMLのクラス指定は長くなってしまう）

![image](https://user-images.githubusercontent.com/7973572/163593273-aa07940d-1d93-440d-82d0-4e557cebe01e.png)

**Comment by syuilo** [comment]
> （ただしHTMLのクラス指定は長くなってしまう）

prodビルドなら適当なIDに置き換えられそうな気はするわね

**Comment by tamaina** [comment]
> （ただしHTMLのクラス指定は長くなってしまう）

言い方が悪かったけど、カスタム注入名の話なのでソースコードの話  
https://v3.ja.vuejs.org/api/sfc-style.html#style-module

**Comment by tamaina** [comment]
命名チェーンは適当なところでリセットしちゃえばいいとは思う  
(SCSSにはat-rootという便利なものがあるらしいし)

**Comment by tamaina** [comment]
Duplicate of #7810

**Comment by acid-chicken** [comment]
CSS Modules だと 1 sfc 内で重複しなければいいので名前をネストする必要すらないはずでは（もし重複するのなら、それは十中八九コンポーネントのスケールが大きすぎるので切り出しをやるべき場面）

**Comment by tamaina** [comment]
名前のネストは可読性やメンテナンス性の問題

**Comment by acid-chicken** [comment]
自分は CSS Modules ベースのシャローな CSS を 2 年ぐらいメインで使ってるから具体的にどういう点で問題が出るのかは気になる

**Comment by tamaina** [comment]
> 自分は CSS Modules ベースのシャローな CSS を 2 年ぐらいメインで使ってるから具体的にどういう点で問題が出るのかは気になる

Misskeyはわりと複雑なコンポーネントは多い（切り分けると可読性が逆に低下するようなものもあるし、そもそもCSS Modules化のためだけにそこまでいじりたくない）

&でクラス名をネスト可能ではあるのでそれを活用すれば良さそう

**Comment by acid-chicken** [comment]
既にそこまで複雑でもない気がするけどなぁ
名前のアンパサンドチェインは IntelliSense が少し気になるけど自分は分からない
