### ISSUE TITLE
"/admin/settings"で保存を押すと、エラーが出る

### ISSUE THREAD

**Issue by na2na-p** [syuilo/Misskey#8465]
## 💡 Summary

"/admin/settings"で保存を押すと、エラーが出て設定の保存ができない。

## 🥰 Expected Behavior

設定が保存される

## 🤬 Actual Behavior

![Error](https://misskey.na2na.dev/media/media/30a1f48e-8d13-47b9-bed8-a2b93181045a.png)

設定の編集をした/していない問わず、画像のようにエラーが出て設定が保存されない。

## 📝 Steps to Reproduce

1. 管理者のアカウントでログインしている状態
1. "/admin/settings"にアクセスする
1. 設定の変更をする(必須ではない)
1. エラーが出る

### Environment 1

Misskey version: 12.109.1
Your OS: Ubuntu 21.10
Your browser: Vivaldi 5.0.2497.32 (Stable channel) stable (64-bit)

### Environment 2
Misskey version: 12.109.1
Your OS: Android12(Pixel5)
Your browser: Chrome 99.0.4844.88

### 備考
後者はジョブキューダッシュボード有効化のためにログインし直しをしてる。
キャッシュクリアも試した。

**Comment by kabo2468** [comment]
サーバーから出てるエラー
```
ERR  1 [api] Internal error occurred in admin/update-meta: You must provide selection conditions in order to find a single row.
```

**Comment by ThatOneCalculator** [comment]
Can reproduce. Cc @syuilo as this should be high priority.

**Comment by syuilo** [comment]
fixed by 408d54f2e
