### ISSUE TITLE
Can't enable checkbox "Receive notifications from this instance"

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8474]
## 💡 Summary

Can't enable checkbox "Receive notifications from this instance"

## 🥰 Expected Behavior

Enable mail sending

## 🤬 Actual Behavior

No changes by clicking

## 📝 Steps to Reproduce

./.

## 📌 Environment

Misskey version: v12.109.2
Your OS: Debian Buster
Your browser: Chrome / Firefox / Edge

![misskey-mail-checkbox](https://user-images.githubusercontent.com/58190287/161936032-5db6c059-75e9-477c-bce6-d9390278fd1a.jpg)

**Comment by robflop** [comment]
I'm assuming this is related to email sending itself being disabled in the code (for unknown reasons): https://github.com/misskey-dev/misskey/issues/8417#issuecomment-1069434762

**Comment by ghost** [comment]
So it is known, and I will wait patiently - thank you for your prompt reply 😀

**Comment by robflop** [comment]
No problem! I think it's fine to leave the issue open, as the problem does technically still exist (unless one of the maintainers disagrees).

**Comment by ghost** [comment]
Any news about this topic - or have developers given up to solve this?

**Comment by ThatOneCalculator** [comment]
Email notifs are still disabled afaik, not sure if any of the devs plan to bring them back. I could plan it for my fork but it'd be low-prio.

**Comment by robflop** [comment]
I don't think there's anything, not because of giving up but rather because it hasn't been looked at though.

**Comment by ghost** [comment]
So I still hope that there will be a solution for this - sometime.

**Comment by robflop** [comment]
@syuilo このIssueを見る時間はあるかな？だいぶ前のだから

**Comment by ghost** [comment]
Under what circumstances should emails be sent?
No notifications have arrived yet.

Email delivery works for new registrations and forgotten password.

**Comment by robflop** [comment]
This is configurable in the same menu as the checkbox in the screenshot of your original post, and should send emails according to those checked options.
(If your instance isn't running the latest commit - or at least the above one that fixed this - these changes won't take effect for you just yet and you'll have to wait for it to update to either the next release whenever that is or to said commit)

**Comment by ghost** [comment]
I'm running Misskey version: 12.117.1 on Debian 11 Bullseye for 7 hours.

So it should, I think, but it doesn't - yet.

**Comment by ghost** [comment]
Is it possible that the emails are only sent when I'm not logged in?

**Comment by robflop** [comment]
Oh, my bad - I misread and thought the fix was implemented before the release of 12.117.1.
In that case I can't help further here, it should send the mails immediately when the checked actions occur from my knowledge.
Not sure whether it has any detection to only send mails when you're not logged in, though.

**Comment by ghost** [comment]
I'll keep an eye on it then and hope for the best.

**Comment by ghost** [comment]
Nope - no email @syuilo
