### ISSUE TITLE
リモートインスタンスへのダイレクト投稿が届かない

### ISSUE THREAD

**Issue by na2na-p** [syuilo/Misskey#8477]
## 💡 Summary

リモートインスタンスのユーザーに対し、ダイレクト投稿を行っても届かない。  
送信元が12.109.1,12.109.2の場合に確認しています。  
12.108.1の場合は問題なく相手側に送信されているようでした。  
送信相手のバージョンは関係なさそう。

## 🥰 Expected Behavior

ダイレクト投稿したメッセージが届く。

## 🤬 Actual Behavior

相手がリモートのユーザーの場合に限って、ダイレクト投稿しても相手には届かない。

## 📝 Steps to Reproduce

1. ダイレクト投稿をする。宛先が2人でも発生したのは確認しています。

## 📌 Environment

Misskey version: 12.109.1, 12.109.2
Your OS: Windows11 (21H2)
Your browser: Vivaldi

**Comment by na2na-p** [comment]
12.108系から届いたダイレクト投稿に対し12.109.2からリアクションしても届いてないっぽい
![送信元](https://misskey.na2na.dev/media/media/webpublic-e007a6e6-a186-4ead-96a6-abb9f1e72552.png)  
  
![送信相手](https://misskey.na2na.dev/media/media/webpublic-2bff3657-62e7-4be6-854d-4bd000430d2b.png)

**Comment by syuilo** [comment]
remote\activitypub\deliver-manager.ts 辺り怪しい

**Comment by syuilo** [comment]
謎

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/commit/41c2aed7dc760d8a89cd09c32cfbee620596fb61#diff-748d41ff497c12c8fd0ad89d56763cd6ecf9fd8229343f0db06ddd48bf5469fd でなおってる
なのでlintではなくbugfix
後ろのカンマはいらない気がする

**Comment by mei23** [comment]
バクの仕込みにくさと保守性を考えると for of にしちゃった方がいい気はするけどだわ

**Comment by syuilo** [comment]
> [41c2aed#diff-748d41ff497c12c8fd0ad89d56763cd6ecf9fd8229343f0db06ddd48bf5469fd](https://github.com/misskey-dev/misskey/commit/41c2aed7dc760d8a89cd09c32cfbee620596fb61#diff-748d41ff497c12c8fd0ad89d56763cd6ecf9fd8229343f0db06ddd48bf5469fd) でなおってる なのでlintではなくbugfix 後ろのカンマはいらない気がする

あーーそゆことか
