### ISSUE TITLE
Upgrade from 12.109.2 to 12.110.0 fails with error

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8487]
## 💡 Summary

**Upgrade fails with error:**

```
2022-04-12 10:30:40,047: DEBUG - CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
2022-04-12 10:30:40,048: DEBUG -     at DataSource.destroy (/var/www/misskey/packages/backend/node_modules/typeorm/data-source/DataSource.js:169:19)
2022-04-12 10:30:40,048: DEBUG -     at Object.handler (/var/www/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:67:34)
```

## 📌 Environment

Misskey version: 12.109.2
Your OS: Debian 10 Buster

**Comment by ThatOneCalculator** [comment]
Seems to be some sort of a database problem. 

Did your upgrade consist of `yarn run build` and then `yarn run migrate`?

**Comment by ghost** [comment]
I did that. I'm currently uninstalling two programs (Plume and Invidious) that also access the Postgres database server. Maybe there is an overlap.

**Comment by ThatOneCalculator** [comment]
> I did that. I'm currently uninstalling two programs (Plume and Invidious) that also access the Postgres database server. Maybe there is an overlap.

Yea, if you're actively doing that there's probably some overlap with the ORM. Wait until the other two are uninstalled and try again :)

**Comment by ghost** [comment]
No changes at all. I even restarted the server after uninstalling.

**Comment by ghost** [comment]
i'm also having this issue. can't upgrade to the latest from 12.108. i have nothing else using postgres
edit: i followed the steps in https://misskey-hub.net/en/docs/install/manual.html#how-to-update-your-misskey-server-to-the-latest-version for the update. it fails at `yarn migrate`

**Comment by ghost** [comment]
I don't know if it's relevant, but I updated Yarn just before:

Upgrade: yarn:amd64 (1.22.17-1, 1.22.18-1)

**Comment by Johann150** [comment]
I could not reproduce this, migrating worked fine for me. This might be an issue in TypeORM unrelated to Misskey: https://github.com/typeorm/typeorm/issues/8885

**Comment by ghost** [comment]
Thanks for this advice.

**Comment by ghost** [comment]
i was finally able to migrate.
i ran:
```
yarn cleanall
yarn install
NODE_ENV=production yarn build
yarn migrate
```

**Comment by memo-567** [comment]
Doesn't work here 🙁
No change, same error messages.

**Comment by ghost** [comment]
That worked perfectly. Thanks :+1: :grinning: :+1:
