### ISSUE TITLE
アンテナの取得に時間がかかる(or 取得できない)

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#8489]
## 💡 Summary

honi.clubの環境(3 vCore, 2GB RAM, SSD)で毎回約16秒かかります。
早く取得できるアンテナも存在し、そのアンテナでは1秒もかからず取得できるようです（謎）

## 🥰 Expected Behavior

アンテナ内容の取得(antennas/show)が1秒以内に返ってくる

## 🤬 Actual Behavior

アンテナ内容の取得(antennas/show)を投げると
クエリ実行でタイムアウトしエラーが返される

.config/default.ymlのタイムアウト時間を緩和させた場合
antennas/showが返ってくるのに約16秒かかる（タイムアウト既定値の10秒に間に合わない）

## 📝 Steps to Reproduce

1. antennas/show
2. ⏳

## 📌 Environment

Misskey version: 12.110.0
Your OS: Ubuntu 20.04.4 LTS x86_64
Your browser:

**Comment by ThinaticSystem** [comment]
リストの投稿取得(users/lists/show)も同じくらい時間がかかるため関連する可能性あるかも

**Comment by ThinaticSystem** [comment]
古いノートを含まないアンテナでも同じように時間がかかるっぽい

**Comment by xianonn** [comment]
弊鯖ではアンテナの辺りを少し改造しているのでクエリがちょっと違うのですが、以前にアンテナのクエリが遅すぎてタイムアウトしてしまうのでサブクエリの部分を内部結合に変更して高速化しました。

改造してないアンテナのクエリだとこんな感じになります。
https://github.com/xianonn/misskey/commit/1f9abc919c07f291538f52976e725ea3d16f0741

**Comment by futchitwo** [comment]
#8413 クリップが重いのも似た原因かもしれない？

**Comment by xianonn** [comment]
私のインスタンスでもクリップを表示してみたら遅くてタイムアウトしていました。
アンテナのクエリの高速化と同じ方法でクリップの方も試してみたところ、クリップも速く表示できるようになったのを確認しました。

やはりサブクエリを内部結合に変更すれば速くなりそうなので、似たようなクエリ構成になっているクリップとリストも修正する PR を出します。
