### ISSUE TITLE
ログインしていなくてもログインページで投稿フォームが表示される

### ISSUE THREAD

**Issue by soldray** [syuilo/Misskey#8491]
## 💡 Summary

タイトルの通り
https://github.com/misskey-dev/misskey/issues/5851
と同様ですが…

## 🥰 Expected Behavior
（仕様でなければ）出ない
## 🤬 Actual Behavior
出る
## 📝 Steps to Reproduce

0. ログイン済みであればログアウトする
1. ログインページで n または p を押す

## 📌 Environment

Misskey version: 12.110.0
Your browser: Chromium, Safari

**Comment by pixeldesu** [comment]
If someone wants to attempt fixing this, the code relevant for providing this hotkey is in `init.ts`
https://github.com/misskey-dev/misskey/blob/develop/packages/client/src/init.ts#L297-L304
