### ISSUE TITLE
ウィジェット編集ボタンが機能しない

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8492]
## 💡 Summary
デッキの時ウィジェットが空の状態でウィジェット編集ボタンが機能しない

## 🥰 Expected Behavior
ウィジェット編集ボタンを押すとウィジェットを追加することができる

## 🤬 Actual Behavior
編集ボタンを押しても何も反応せずウィジェットを追加することができない

## 📝 Steps to Reproduce
1.デッキモードにする
2.カラムを追加でウィジェットを選択する
3.空のウィジェットを編集しようとする

## 📌 Environment
Misskey version: 12.110.0
Your OS: windows11
Your browser: firefox 99.0 & chrome 100.0.4896.88

**Comment by adzukyat** [comment]
再現しました

Misskey 12.110.0
Windows 11 21H2
Chrome 100.0.4896.127
