### ISSUE TITLE
Drive: Directory sorts

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8495]
## Summary
It would be of great help if folders in Drive could be sorted either alphabetically and/or manually.

Above a certain number, the view becomes confusing

![20220414-0930](https://user-images.githubusercontent.com/58190287/163336266-f64292e3-3672-4bc0-86ba-3f3c8efde77c.jpg)
.

**Comment by ghost** [comment]
i would love it you could sort uploads by oldest first instead of newest

**Comment by Sayamame-beans** [comment]
duplicate of #8920
