### ISSUE TITLE
Add yunohost to the installations options

### ISSUE THREAD

**Issue by DeMiro5001** [syuilo/Misskey#8504]
## Misskey can be installed in a [yunohost server](https://yunohost.org/) :
[Misskey for YunoHost](https://github.com/YunoHost-Apps/misskey_ynh)

Can be added this guide : 
https://misskey-hub.net/en/docs/install.html

**Comment by 4ioskd** [comment]
If you want to add YunoHost to Misskey-Hub ( https://misskey-hub.net/en/docs/install.html )  as one of installation's option, you should open this issue on its repo( https://github.com/misskey-dev/misskey-hub ).
This repo is basicllay specialized for a development of Misskey itself.

**Comment by tamaina** [comment]
READMEとかに追加してほしいという話では

**Comment by DeMiro5001** [comment]
As suggested by @4ioskd, I opened an issue in the dedicated repo and sent a pull request.
