### ISSUE TITLE
Supports Unicode Emoji 14.0

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#8505]
## Summary

Unicode Emoji 14.0 に対応したいが、Assetsが [@discordapp/twemoji](https://github.com/discord/twemoji) に依存しているのでこれが更新されないと対応できない。
やはり misskey-dev にforkしてnpm publishするしかない？
経緯: https://github.com/misskey-dev/misskey/pull/7897

## Motivation

これが出来れば (絵文字対応に関しては) Discord側の更新を待たずに出来るようになる

**Comment by rinsuki** [comment]
`@discordapp/twemoji` が更新されるのが一番楽なのでとりあえず pull-req 送ってみた https://github.com/discord/twemoji/pull/1

**Comment by mei23** [comment]
とりあえずうえのふとうごうけしておくかしら

**Comment by mei23** [comment]
自分のとこで使うためにメンテしてそうだからどうだろうというのもあり…

**Comment by Johann150** [comment]
What is the reason we are not using Twitter's Twemoji repository? It already supports v14 and the SVG files are available from [their repo](https://github.com/twitter/twemoji/tree/master/assets/svg) that we could include as a git submodule for example. (I think it is not necessary to use npm for this.)

**Comment by Johann150** [comment]
(The emojis could be added to [misskey-assets](https://github.com/misskey-dev/assets/) for example.)

**Comment by mei23** [comment]
The Twitter repository doesn't publish svg to npm, so it can't be used in dependencies.
It's possible to add assets to Misskey itself, but it wasn't adopted because the repository is bloated.
So now we are using the Discord repository, which is modifies the Twitter repository to be published on npm.
Publishing npm isn't that complicated, so it's possible to fork and maintain it with Misskey. (Like a Discord repository)

**Comment by mei23** [comment]
> `@discordapp/twemoji` が更新されるのが一番楽

これ言い出すと [twitter/twemoji](https://github.com/twitter/twemoji) がnpmにsvg publishしてくれるのが一番楽になるのだわね

見込みはないけどだわ
https://github.com/twitter/twemoji/issues/356
https://github.com/twitter/twemoji/issues/359
https://github.com/twitter/twemoji/issues/431

**Comment by tamaina** [comment]
Twemojiの公式リポジトリをsubmoduleに追加して参照すればまるっと解決するぜ！

（なお https://github.com/misskey-dev/misskey/pull/7891 ）

**Comment by mei23** [comment]
`@discordapp/twemoji` は更新された模様
https://www.npmjs.com/package/@discordapp/twemoji

作業中
https://github.com/misskey-dev/misskey/pull/8699
