### ISSUE TITLE
クライアント設定を名前を付けてサーバー（registry）に保存・読み込みする機能

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8506]
## Summary
The function (feature) to save client preferences to the server (registry)

#7400 #7403 あたりの実装

## 機能と一連の動作
たとえばユーザーが新しい端末/ブラウザを導入して初めてMisskeyにログインするとき、あらかじめ古い端末/ブラウザで設定を「名前を付けて保存」しておき、新しい端末/ブラウザで「読み込み」を行えば、ほとんどの設定が復元される。

pizzaxの`where: 'account'`のように自動同期はされない。手動で保存・読み込みする必要がある。

## UI
設定に「プロファイル」ページを追加する（リスト上ではクライアント設定に属する）

まずは現在のプロファイルを名前を付けて保存するボタンがある。
名前を付けて保存ボタンを押すと、名前入力ダイアログを表示する。OKを押すと保存してアップロードできる。  
もし同じ名前のプロファイルがあったら上書きするか確認する。キャンセルの場合はもう一度名前を入力させる。

保存されたプロファイルの一覧がリストで表示される。

保存されたプロファイルは「読み込み」「上書き保存」「削除」が行える。

プロファイルを読み込む前は、現在の設定がすべて上書きされる旨の確認ダイアログを表示する。  
読み込んだ後は画面の再読み込みをさせる。

上書き保存や削除を選択すると、確認ダイアログが表示され、それぞれの操作を行う。

### レジストリ
スコープ `['client', 'profiles']`

#### データ構造
プロパティ名はuuidにする。defaultStore(`where: 'account'`を除く)とColdDeviceStorageの内容を保存する。  
なんとなく作成時刻とアップデート日時も保持しておく。

```js
profiles = {
  [x: uuid]: {
    name: string, // 名前
    updatedAt: Date,
    createdAt: Date,
    defaultStore: object, // defaultStore (includes widget setting) EXCLUDING where: 'account'
    coldDeviceStorage: object, // ColdDeviceStorage (includes theme setting)
  },
};
```

**Comment by syuilo** [comment]
コストに見合う価値があるかは分からんけど仕様は良さそう

**Comment by tamaina** [comment]
@tkmrgit がM1 MacBook Air買ってくれるらしいしサクッと実装するか

**Comment by tamaina** [comment]
設定画面弄る前に #8508 を直す必要があって全然サクッといかなかった
