### ISSUE TITLE
クリップ機能の削除

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8510]
## Summary
Abolition of Clips feature

クリップ機能はあまり保守できている感じではないし、ページのノート埋め込み機能で十二分だと思うので、廃止してよさそう

**Comment by syuilo** [comment]
> クリップ機能はあまり保守できている感じではない

そうかしら

> ページのノート埋め込み機能で十二分

投稿数が多くなってくるとページングできないし大変そう
あと投稿のメニューから直接入れたい

活用しているユーザーが割といるから廃止すると混乱しそう
