### ISSUE TITLE
壁紙が表示されない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8513]
## 💡 Summary
Wallpaper doesn't works on Chromium (Chrome, Edge)

CSSの適用順序が問題なのだと思うが、Edge, Chromeで壁紙が表示されない

FirefoxだとクラシックUIのみで壁紙を表示できる

## 📌 Environment

Misskey version: 12.110.0
Your OS: Windows 11
Your browser: Edge 100, Chrome 100

**Comment by tamaina** [comment]
うちの鯖の問題だった

**Comment by tamaina** [comment]
（とはいえユニバーサルUIで壁紙が考慮されてないのはなんとかしたくない？）

**Comment by syuilo** [comment]
壁紙考慮したデザイン難しいから廃止したい

**Comment by marihachi** [comment]
壁紙廃止しようぜ

**Comment by robflop** [comment]
デフォルトでMisskeyの壁紙は不毛(?)すぎるのでその機能を保った方がいい。

例（usercssを使ってる）：
![vivaldi_2022-04-17_10-12-08](https://user-images.githubusercontent.com/8159402/163706404-af034d51-51d4-4e70-b46f-2eff105258a5.png)

![vivaldi_2022-04-17_10-14-29](https://user-images.githubusercontent.com/8159402/163706413-6f833228-2cd3-49d9-b222-9fb2738c36f4.png)

一つ目のスクショに生きがない感じがあると思う。（画面余白もめっちゃある問題もあるけどそれは別）
