### ISSUE TITLE
SchemaTypeDef の anyOf が機能していない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8514]
## 💡 Summary
drive/files/show とかで、psがanyになる

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
解決した方に報奨金を進呈

**Comment by tamaina** [comment]
anyOfの中身全てにtype: 'object'を指定すると動く

**Comment by tamaina** [comment]
Swagger 3のanyOfのサブスキーマってtypeなくていいんだろうか…
