### ISSUE TITLE
SchemaTypeDefで`型 'string | number | symbol' を型 'string | number' に割り当てることはできません。`エラーが出る

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8517]
## 💡 Summary
https://github.com/misskey-dev/misskey/blob/d338ea2591f724e485aa84c824268371e77a6ad4/packages/backend/src/misc/schema.ts#L161

symbolがどこから湧いてきたかがわからない

**Comment by tamaina** [comment]
こまったときのStackOverflow

https://stackoverflow.com/questions/71979824/type-string-number-symbol-is-not-assignable-to-type-string

**Comment by syuilo** [comment]
既に質問があったのかと思ったら`asked 8 mins ago tamaina`だった

**Comment by tamaina** [comment]
requiredにkeyof this['properties']を使う必要性あるかしら

**Comment by tamaina** [comment]
解決した

![image](https://user-images.githubusercontent.com/7973572/164917375-4d359d7b-4456-4650-9c53-b837ac07f884.png)

**Comment by tamaina** [comment]
いや確かにエラーは消えるけどObjがneverになるわ

**Comment by tamaina** [comment]
Fixed by #8538
