### ISSUE TITLE
some emoji are hard to see in own reactions

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8520]
## 💡 Summary

Some emoji are hard to see when they are shown in a users own reaction to a note. This is especially problematic if the emoji is in a colour that is the same as the background.

## 🥰 Expected Behavior

Emojis are easy to see.

## 🤬 Actual Behavior

![⛳ on a green background](https://user-images.githubusercontent.com/20990607/164080709-f1505792-9e3c-48fc-a7de-4e914f97e340.png)

![🦕 on a green background](https://user-images.githubusercontent.com/20990607/164080896-38a86fac-e53a-4976-9525-690e30c59518.png)

## 📌 Environment

Misskey version: 12.110.0

## 🔧 Possible Solutions
- Change theme colours
    ⚠️ Other emoji colours may accidentally be used.
- Add a bit of shadow to the emoji.
```
.reacted > .mk-emoji {
	filter: drop-shadow(0 0 3px var(--bg));
}
```
![⛳ on a green background, with a slight shadow](https://user-images.githubusercontent.com/20990607/164082110-03f759c5-6e5a-446f-9c90-80c6290f26b7.png)

![🦕 on a green background, with a slight shadow](https://user-images.githubusercontent.com/20990607/164082037-157e910e-c003-487c-94ef-e6017de236ff.png)

**Comment by lavender-sys** [comment]
also an issue for colored heart emojis
<img src="https://user-images.githubusercontent.com/13684891/167317404-6f896e61-e22f-4304-9364-8ddfc9a90695.jpeg" height="100"/>

**Comment by Johann150** [comment]
I think the current solution of adding shadows to all emojis is not a good solution. For example it "breaks" MFM art that combines multiple emoji.
