### ISSUE TITLE
http/https, got/node-fetchの代わりにNode.js公式のundici, Node.jsネイティブのfetch関数を使う

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8522]
## Summary
Use Node.js official undici and `fetch()` instead of `http`/`https`, `got` and `node-fetch`.

Node.js v18からオプションなしで[undici](https://undici.nodejs.org/#/)やundiciによるwhatwgのfetch()を利用できるようになった。  
リクエスト周りは今後undiciベースに置き換えるのが好ましそう。

（Node v18自体リリースしたてなので時期尚早なのは知っているけど、それは一旦忘れてください）

**Comment by rinsuki** [comment]
fetch、proxy対応してなさそう

**Comment by tamaina** [comment]
undiciのClientあたりを使えばいけそう（undiciの名前を出したのはそのため）

https://undici.nodejs.org/#/docs/best-practices/proxy

**Comment by rinsuki** [comment]
Clientにはfetchないしfetchじゃないんだったらあんまり使う意味も…

**Comment by tamaina** [comment]
あ、今気づいた、めんどくさ

（そもそもそこらへんがfetchが生やしてるわけないか

**Comment by tamaina** [comment]
undiciのdispatcherのrequestとFetch APIのRequestは関係ないっぽいな

関係ない(?)けどdenoはclientにproxiedなクライアントを食わせることができるようになってるっぽい  
https://github.com/denoland/deno/pull/10907

**Comment by tamaina** [comment]
とりあえずIssue作成してみた

https://github.com/nodejs/undici/issues/1350

**Comment by tamaina** [comment]
https://github.com/nodejs/undici/issues/1350#issuecomment-1137916129

**Comment by tamaina** [comment]
あ〜〜、これDNSキャッシュ制御をいじろうとするとconnect関数作る必要があるらしいのでやりたくない〜〜〜

**Comment by tamaina** [comment]
現状のようにcacheable-lookupを適用するには[buildConnector](https://github.com/nodejs/undici/blob/v5.14.0/lib/core/connect.js#L96)の[tls.connect](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)にdns.lookup()の代わりになる関数をものを挿入してやる必要が…あ、これbuildConnectorが...optsで受け取るのか、なんだ楽じゃん

**Comment by syuilo** [comment]
そもそもcacheable-lookup要る？って話なかったっけ

**Comment by mei23** [comment]
> そもそもcacheable-lookup要る？って話なかったっけ

キャッシュという観点だといらないんだわ。
最近のSystemdベースのLinuxではsystemd-resolvedあたりでキャッシュが入るので、Node.jsでもキャッシュする必要は多分なし。
Alpine Linuxだとおそらくされないけど、もうDockerはDebianベースなのでもうDockerでも不要。

Node.js デフォルトの`dns.lookup()`を使わずに別モジュールを使用しているのはパフォーマンスの問題のため。
https://nodejs.org/api/dns.html#implementation-considerations
`dns.lookup()` ではなく `dns.resolve4()` OR `dns.resolve6()` を使用するようにしてパフォーマンスを上げるのが目的。
キャッシュすることは特に目的ではない。むしろキャッシュを各プロセスで持つのはメモリの無駄かも。

単純にキャッシュモジュールをはずすと`dns.lookup()`のパフォーマンス問題が出るので、Wrapはしてあげる必要はあるわ。
https://github.com/mei23/misskey/blob/mei-m544/src/misc/dns.ts

**Comment by tamaina** [comment]
> そもそもcacheable-lookup要る？って話なかったっけ

maxTtlを1hoursに設定しているので、DNSが提案するTTLを無視して**浸透**待ちの期間を減らす目的で設定しているのかなと思った

**Comment by mei23** [comment]
> maxTtlを1hoursに設定しているので、DNSが提案するTTLを無視して浸透待ちの期間を減らす目的で設定しているのかなと思った

上位にDNSキャッシュがあるのでそれやっても意味ないわね。そしてDNSは浸透しないわね。
