### ISSUE TITLE
クライアント起動時にとても重くなるのをなんとかしたい

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8525]
## Summary
I want to do something about the very slow operation at client startup.

（Surface Pro 7 i3/4GBを使っているのもあるけど）クライアント起動時にかなり動作が重たくなるので軽量化したい

**Comment by tamaina** [comment]
Firefox Profilerを試した結果

![2022-04-22 13-45-40 1](https://user-images.githubusercontent.com/7973572/164604931-02a38443-ff73-4677-a29a-de25ba86e39b.png)

**Comment by tamaina** [comment]
ふかい

![image](https://user-images.githubusercontent.com/7973572/164607491-c63ebcef-7542-44e0-beb6-8c3935d3bdda.png)

**Comment by tamaina** [comment]
ふむ

![image](https://user-images.githubusercontent.com/7973572/164609136-6ad38ac9-f840-4b37-9d28-d424cb5ad4cc.png)

**Comment by ThatOneCalculator** [comment]
Misskey has always had bad performance on Firefox. I hope it gets fixed soon :pray:

**Comment by tamaina** [comment]
Viteにすれば治るんじゃね（超適当）

https://github.com/misskey-dev/misskey/issues/6845

**Comment by ThatOneCalculator** [comment]
I recently used vue for a [project](https://github.com/zer0bin-dev/zer0bin) and it's pretty easy to get a hold of, and [performs great](https://github.com/zer0bin-dev/zer0bin/wiki/Benchmarks). I'd love to see Misskey incorporate Vite 😊

**Comment by tamaina** [comment]
Viteぜんぜんわからん

importを解決しようとしてくれない

![image](https://user-images.githubusercontent.com/7973572/164625289-546bd123-6440-4882-89b8-6e2261aeca59.png)

**Comment by ThatOneCalculator** [comment]
Vite can be a bit... strange 😆 I'd reccomend looking at the Vite docs for making a config

**Comment by tamaina** [comment]
どういうことをしたらmp2tを吐き出すようになるんだ…

![2022-04-22 23-37-39 1](https://user-images.githubusercontent.com/7973572/164737350-8d8ee6ef-3e9f-4437-9e6f-a729262bdb11.png)

**Comment by tamaina** [comment]
…なんとかいい感じになった

さて、rollupって基本的にファイルにランダムなハッシュを付けてくるのだけれど、どう実装しようかしら

**Comment by ThatOneCalculator** [comment]
When building for prod it should add hashes automatically :)

**Comment by tamaina** [comment]
本当にそう思う

**Comment by tamaina** [comment]
Viteでスクリプトをビルドして読めるようにしてみたけど、import()が動作しなくて困っている

https://github.com/tamaina/misskey/pull/67
