### ISSUE TITLE
Images flow out of the note block in Safari on iOS and macOS

### ISSUE THREAD

**Issue by kostyakoz** [syuilo/Misskey#8526]
## 💡 Summary

Images flow out of the note block in Safari on iOS and macOS. I see it on every Misskey instance.

## 🥰 Expected Behavior

Image or multiple images should be inside the block of the note (so note should auto resize for its content). 

## 🤬 Actual Behavior

But instead images flow out of note block, so it broke page and makes next note unreadable on Safari.

## 📝 Steps to Reproduce

1. View note with image/gallery on Safari. 

On macOS:
<img width="1376" alt="Screenshot 2022-04-22 at 11 35 48" src="https://user-images.githubusercontent.com/1935229/164652313-dc483ddd-d96f-4c29-9229-5ffa7c9abc11.png">

On iOS:
![IMG_EBD02F257E72-1](https://user-images.githubusercontent.com/1935229/164652442-9cfb9db3-a303-4eb5-b070-72198dd4504f.jpeg)

## 📌 Environment

Misskey version: 12.110.0
Your OS: macOS 10.15.7 / iOS 14.8.1
Your browser: 13.1.3 / iOS 14.8.1

**Comment by tamaina** [comment]
Use iOS 15.

See #6811 #7949
