### ISSUE TITLE
Excessive stack depth comparing types 'SchemaTypeDef<?>' and 'SchemaTypeDef<?>'

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8535]
#8332 由来のエラー。

admin/emoji/add-aliases-bulkのような単純な型でも発生する。

https://github.com/misskey-dev/misskey/blob/f23d5a75f4cb64328a99e25f8a17150fe5b8a4d3/packages/backend/src/server/api/endpoints/admin/emoji/add-aliases-bulk.ts

（Arrayが問題らしい？）

**Comment by tamaina** [comment]
問題なのはArrayではなくて、関数定義まわりが原因なんだと思われる

![image](https://user-images.githubusercontent.com/7973572/164954578-9a1e5bfa-70e6-4955-a1b0-e733849e25db.png)

https://www.typescriptlang.org/play?#code/PTAEEEHEAUBlQMwDoAMpAdJKAzgTwK4CWANgPYA0oALgIYC21BAdtaNYwCagmUAWApgCdQAWQJYsAaz45QAYxKNKAggCM8lEgKwAobXwAeAB02U5CrKYF8AZllABeUAG9tASGElZEgEo2AXM7aoMFUOIZ8AQDkJCoAVnyylJGsdvKMFmRBoAC+KWbplJnZANy6BsYCppRhfKDQ1F587AA8+qAGlHwcdlI4JNah4f2gVrYAfA6gAMqy-PQAKjXN1UMDo1gA2voAumOl2iu1i+FTSkwA5jaTkYx4RETJAD6gkSokJER8bE8vTJ2XAh+NzwtBUgiBFmUjHOQOoAgE1BwQJi8USsMYSNKh2mZ2hABEbPMSMc+M15u19J1uqASacoZdrBN7G5yR0uuw7MD7skAPygW73UB+FkUqkcl5vD5fRi80CSz5sIUitnUyJ-PgA2W3UGCJWuVmU9mc7VgwGgPkm3XC-Wio0vSEXWUO6GgZ546idPUGsWcuEIpHm0C+ajsBREHDgeGI5psHATa3eu3ROIJJKB3zyAQtZ3nCix+NuWP7ECgHiUSiGLB+EBYADu1HOAKQBBIwCw4VkBGsBFkHpbjGAPKwKiwXwEs3sJEMlH71CIAGIsLM+PQALQo1MHGqgADy1hmcxYjhcrisIbDMlje55AWDocY4cj-uaB5X1D2bjP9-DXEYfGvt5fN+EZRjgL7LvQH6nkBF6sPcAFBjBD4gc+r6QaU2RlEYJigOqAjWA0tRoSwKrinuxGBNB57IYMfA3jSNR0hcNilFRwH8ncRDUConz0fK0qsV+sFTjOChznx7wKowglIT+BCdLQWD0cRMnUT+hgCFOggznwSkBDucSlCEIyyTIVgAI6EFY7D0XeF5PtGACilIIokzS9MMAByCieZx3GfMsPBiBskQaVplQELpkS7BQOZjFBQk0ewumyMo079vROaqexBh0IYvEBEWn6maA1iaPQlCZbi5zZbBoz0R5AyHMM6y1TRXQgrZpkOWBcVtT+yUEXclUBAAFLwwWRIc0W2tStLVVcfJMfihLEksE2bFNNTRfGrAYgAlK6HH3P1Mj0PosBdOcvD0ZaAinaAtBMJd0I3QEd0Ybo2K+JZBDWdAmnhJUOCeXQunNHYpF2AZsRMpRGwANK4YwoCNdg2zWq4JZI2I-LcFw6ViUQbiuJsCPbCFImzg82yzeKBFEKOgZI5j2OltQdiDdQw2gAAbnOeB8CTZMU5EXPDTNUPHUQR05kdd1HfxirPBmmjZtVFB4IwEiMCQtaMBMfIs-yfC84I2jZBsaNYNs+zlDh2Iw5MqtZhDGvTBB7529hlS0bucQkhDdPQ3EFA-VZTQA1OkOGtS1tMm4TigKuiU-hs0DI6j0jDDbyme4HmzQLsOSgAAZInyepzI6eZ+Hf2R4DNsBMRBfp8XuTl64ScpyVNdMIhv3-YD2kg2DWAQ2MGMe4erdFxMJRfduvnwQIACqHA2EwTTNIYwfT2+FDzAnriGCFApcTxfCS7H4pKILJM8iflOE8wNN73fQuuF-fKjeSzzn0dLWg0t7sH2iTVwY0-7SzAV-AIp9ogvznNfH0VABD3y-q4H+UCgGbz-KA8BAR5jFjAGWCsVYaw0C8CQM2+FSC1iQPIWgwBLK6VEukYAABWAALAATgQAADgAIxcMEcAQ4S40qUFXGkGhUitb9lXBoVceFRyJH7NoEskA+CmBUamfspVNK0FAPIhQoAtzhFAOvfsRIACSihBCqLYc0VecNRqrz3rGQMo0JABFXodewExeYkAIJwd6ptBCHSlqNbxAQmDWF1DY-xgTgmgMDDYoUJsaHENLOWSs1ZgDnHkjwPAKgGEkCYU9cQvRVzJV5sASpkhpDAEMJxYAQiuFcPnOwMQsg8DiH7AAfQEAAdn4RwgATPw4ZHCJkaLAESUAlxTAmMYBQWstQ+m1AAAYADF3geIxIGAAEiQS4zQ9kkF2n+GhWzzG1CsQoFuSwSI3zsFXPaOANjbAoAADT3hRRw1ANh3WLo4P5UtPFLXzksH5Vzwn3TuRAUCDzGBkjhomakkKkXPiPhk65ghihmL0D7Ko24nnhAJNYHe-zPbH3gdNWmUsuQPEDAA609LtqMteb8exmpWUglNHqDl4RkFJjulqAVVo3DCqvlylBkQcyylGiTeBHVaCiupO8nMXzzTgNVdqaKwLJUCFppjJ+kQyoCAqhq8UYsPR8EUQQWgV9AxywCCWd0nRADWDIATQZADRDIAfH+A3gJzG4Q67KQoMr3q8SS0pZRKxRhGraIq5VJg3GiLxKqQqjBtT0bOTUagtRsHYPk9RGgtHgTm4uYSaGuizaFYeEUoqpupN5Rgy8L4BRhobf2sRA7wLCkDHSWBooUDbR2-ypJK18EHk0HaRqdQmrhbWx49arzWFzYhNSKFozER7Si8lU6Qrrp2mXOocIZxzmcYwaxJA7GdC0HohQ17+yHp3sejEe4drxTxfCutX94FziIF+lt4o7LIR6uBQ8+6b0KFsfYx9ajn0HuheEd9kQgMgZ-TW82rhw3SsjZy6NfpERKvrfJFcI7QPQ33J7TNGD4EUcUoajDn6N3Ua3cBSDe7AwoZnkscdflL7oaY1Rj9OAsNjB1WaxjCkxPRD-CBve4HHygSg2+HtPUUUvseah0kgn7iTpE3JljCh-zsfigWBjIVRMscw+x5T3U1M8b5Ci+DD7HH9h04wN9BnO1HrVCZ0W9nv1SdNeA-FAgSb4YAzZoLe8-NGZc-vBYNRKXGco-O8LX9YxfLDUKymimHNSxUzusCyW+Nvn7YV8zp7rRFWJRUUlFi327yljxxwHadxrw3t2PBO8KCHvS4YeK+xGs4TSBYUAhg4R0EpZME8hwojpqSJkE+jbh0BBPK4EJW3aJREVRQS1FUogNN6H4EJyRshreu8VWd7AAg2fYKOi2eRJuUH2MlWQXErClS1khlG+hmjQBjigvdo0ZsIloAEEHR3-tjTySl6ggcQdjCSXzFJ+0AhBJCfsfQEPZu0EpRQCHWB0cnisJQPAAgUYbErM2dg2wLZgKAA

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
これはダメだけど
![image](https://user-images.githubusercontent.com/4439005/165251638-c08e28db-7cd8-42a5-8b25-0ed6d28ade7b.png)

これは良いらしい(`<T>`を消した)
![image](https://user-images.githubusercontent.com/4439005/165251690-74fc1021-c2a0-450c-9545-57e57c14f942.png)

**Comment by syuilo** [comment]
> これはダメだけど
> ![image](https://user-images.githubusercontent.com/4439005/165251638-c08e28db-7cd8-42a5-8b25-0ed6d28ade7b.png)

ここまで単純化した型でもエラーになるからどうしようもなさそう

**Comment by syuilo** [comment]
あ、objectのrequired対応部分を消したらエラー出なくなったから、原因はそこっぽい
required関係の型定義を工夫することで回避できる可能性あるかも

https://www.typescriptlang.org/play?#code/PTAEEEHEAUBlQMwDoAMpAdJKAzgTwK4CWANgPYA0oALgIYC21BAdtaNYwCagmUAWApgCdQAWQJYsAaz45QAYxKNKAggCM8lEgKwAobXwAeAB02U5CrKYF8AZllABeUAG9tASGElZEgEo2AXM7aoMFUOIZ8AQDkJCoAVnyylJGsdvKMFmRBoAC+KWbplJnZANy6BsYCppRhfKDQ1F587AA8+qAGlHwcdlI4JNah4f2gVrYAfA6gAMqy-PQAKjXN1UMDo1gA2voAumOl2iu1i+FTSkwA5jaTkYx4RETJAD6gkSokJER8bE8vTJ2XAh+NzwtBUgiBFmUjHOQOoAgE1BwQJi8USsMYSNKh2mZ2hABEbPMSMc+M15u19J1uqASacoZdrBN7G5yR0uuw7MD7skAPygW73UB+FkUqkcl5vD5fRi80CSz5sIUitnUyJ-PgA2W3UGCJWuVmU9mc7VgwGgPkm3XC-Wio0vSEXWUO6GgZ546idPUGsWcuEIpHm0C+ajsBREHDgeGI5psHATa3eu3ROIJJKB3zyAQtZ3nCix+NuWP7ECgHiUSiGLB+EBYADu1HOAKQBBIwCw4VkBGsBFkHpbjGAPKwKiwXwEs3sJEMlH71CIAGIsLM+PQALQo1MHGqgADy1hmcxYjhcrisIbDMlje55AWDocY4cj-uaB5X1D2bjP9-DXEYfGvt5fN+EZRjgL7LvQH6nkBF6sPcAFBjBD4gc+r6QaU2RlEYJigOqAjWA0tRoSwKrinuxGBNB57IYMfA3jSNR0hcNilFRwH8ncRDUConz0fK0qsV+sFTjOChznx7wKowglIT+BCdLQWD0cRMnUT+hgCFOggznwSkBDucSlCEIyyTIVgAI6EFY7D0XeF5PtGACilIIokzS9MMAByCieZx3GfMsPBiBskQaVplQELpkS7BQOZjFBQk0ewumyMo079vROaqexBh0IYvEBEWn6maA1iaPQlCZbi5zZbBoz0R5AyHMM6y1TRXQgrZpkOWBcVtT+yUEXclUBAAFLwwWRIc0W2tStLVVcfJMfihLEksE2bFNNTRfGrAYgAlK6HH3P1Mj0PosBdOcvD0ZaAinaAtBMJd0I3QEd0YVhFRVNuBmxJMGaaNm1UUMRH56NhlS0bucQks0dikXYf1Mm4TigKuiU-hs0C4YwoCNdg2zKRB1Bw5s0C7Dk+zYr58ECAAqhwNhME0zSGLN4rERQ8wo64hghQKXE8XwM2I1QAh4HwbiuDyfMhSJs4PNsHN2EokvSzLoCjeSzyC0deBM92f7sPtGtjTrx1EKbriuAE-PROlYlKyr4vqzbmva-rhssybZs0sWYBlhWVY1jQXgkAAboI1ikLWSDyLQwCWbponpMAACsAAsACcCAABwAIyZwXwCHEuaWUKuaRR5Uq4G-2q4aKueGjok-baCWkB8KYLepv2pWabQoD1wooBbuEoCM-2RIAJKKIIrep809NMlr9Mu7GgajRIAT04d9gTBHJAEJw718DXh1i6N28BEw1i6jP++H8fJuBjPQr8ufggB6W5aVtWwBzjyR4HgFQ8cSCJyeuIXoq5koR2AFAyQ0hgCGE4sAQumdM7znYGIWQeBxD9gAPoCAAOx53TgAJjziQ9OlCO5gCJKAS4pgR6MAoLWWo+DagAAMABi7wN4YkDAACRIJcZo-CSC7T-DXbh49ahTwUMROGJFDTUkxpeDEGxtgUAABouwoo4agGw7qU0cPosWm8lokzhro6RX97ryIgKBRRjAySr0TNSKxzjnw8w-jI7+Y8IbfWhsomoBJrBswMSTXm9tprKzFlyB4gY9bWjidtBJajxRqnnpqFJIJTR6nSeEUWWTjQFPBPknUQg0khXiS7SIOZZSjWlvbDqtBSk+hMmpGQOZtHmg1m07U0UTEVIEMra0Nt7ZlQEBVTpSZ2Aej4I3AgtARaBhzB-Es7pOiAGsGQAmgyAGiGQA+P-HI1jmNwh1albRKZkrprxJLSllPxRU1z6mJI3GiLerSQqjHmdSAmzU1g2DsHyeojQWj2z+ZTM+NdXQ-NCppcIEUop3LtN5RgtMhYBWRoGP6cN7ZhWRTpLAO1-EOPhVMkKV5rD-PFHZZCPVwKHgmHyVxYTwhs2pRiPcZKABkdQ4QzjnMvRg08SBz06FoPuChRX9g5aSe2NKdrxXJXCx4CK5xEF5Wi6kDLHygWZW+Vlk8xUKFnvPaVbdZXspsUsJV8FaW7HsTXS5RS6kZIaX6REzSEXyRXKS3VZF9wk2+e7e2-rFIjMiMqoNdh9UoWjGDQMtrDxwwxVi-yiqQqRsDdynAOr4r9MmXLNUCk83RD-Dql2CamXJr5D1VxcqlF2s5RmvywsuVloDdGhQ-4nXxQLOGnN5bo1aurWLWthr62mvFZKheMq3GprfOmnyHaAoRtHdsaljqVVjGLRrAJAhpZXL9Vul27b7hZqNZBQMCqIldtzTtA9NtYzaLddcvtE6ymIR6XWmJKazWMAVV2r9A69RFWCThbEIH2Zi2TY4LFO4Gbe2NmzUGra+APsMPFfYUGoZpAsKAQwcI6ARMmCeQ4URPlJEyHzJF2lIpVkoq4E+AQ0ZUftNVSIFAZkVSiIg3ofgT7JGyHRsTxVLIEGsgEHN7BopFDyIRyg+xkqyC4lYUqBtrV430M0aACMf1g1GiRhEtAAgGd49psa-9piYf01gMYT9QBHxPvtAIrn2D7H0CZ0jtAIkUBM1gZzJ4rCUDwAIPGGxKzNnYNsbQ2RTZAA

**Comment by acid-chicken** [comment]
> ```ts
> type NullOrUndefined<p extends Schema, T> =
> 	p['nullable'] extends true
> 		?	p['optional'] extends true
> 			? (T | null | undefined)
> 			: (T | null)
> 		: p['optional'] extends true
> 			? (T | undefined)
> 			: T;
> ```

この方がブランチ短い

```ts
type NullOrUndefined<p extends Schema, T> =
	| (p['nullable'] extends true ? null : never)
	| (p['optional'] extends true ? undefined : never)
	| T;
```

**Comment by tamaina** [comment]
ObjTypeを交差型でないようにしたらいけた

```ts
export type ObjType<s extends Obj, RequiredProps extends keyof s> =
	{ -readonly [P in keyof s]: P extends RequiredPropertyNames<RequiredProps, s> ? SchemaType<s[P]> : SchemaType<s[P]> | undefined };
```

ただOptionalと`hoge | undefined`は異なるので、どうするか

**Comment by tamaina** [comment]
```ts
export type ObjType<s extends Obj, RequiredProps extends keyof s> =
	UnionToIntersection<{
		-readonly [P in keyof s]?: SchemaType<s[P]>;
	} | {
		-readonly [S in RequiredPropertyNames<RequiredProps, s>]: SchemaType<s[S]>;
	}>;
```

あーうん、UnionToIntersectionってTypeScriptの型検査機を騙すから、これでいけるんだよな

**Comment by tamaina** [comment]
これでいいか

**Comment by tamaina** [comment]
TypeScriptはinferで騙されるので、unionではなくintersectionを突っ込んでもおｋっぽい

```
export type ObjType<s extends Obj, RequiredProps extends keyof s> =
	UnionToIntersection<{
		-readonly [P in keyof s]?: SchemaType<s[P]>;
	} & {
		-readonly [S in RequiredPropertyNames<RequiredProps, s>]: SchemaType<s[S]>;
	}>;
```
