### ISSUE TITLE
Following users after 3cf226d doesn't work (Promises not defined) 

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8543]
## 💡 Summary

Pressing the Follow button for a user doesn't work, console gives this error:
```
ERR  1  [api]   Internal error occurred in following/create: Promises is not defined
```

## 🥰 Expected Behavior

Follows user

## 🤬 Actual Behavior

Button doesn't do anything, reloading the page does show the follow but the follower count doesn't increase

## 📝 Steps to Reproduce

1. Try to follow user

## 📌 Environment

Misskey version: 12.110.1 (git 3f9a914718e13c99cbef51944938ab687d81d6c2)
Your OS: Linux
Your browser: Firefox

**Comment by ThatOneCalculator** [comment]
Note that this behavior does NOT occur in v12.110.0

**Comment by ThatOneCalculator** [comment]
Seems to be related to 3cf226d

**Comment by syuilo** [comment]
note: That commit has not actually been released yet, so it does not affect actual instances at this time.

**Comment by ThatOneCalculator** [comment]
Ah, is that not part of 12.110.1? Either way, `git revert 3cf226d534d10261c693ed51ba3db440fe8e8be9` does fix the issue so it's definitely that commit.
