### ISSUE TITLE
Androidで絵文字ピッカーの候補が文字を確定しないと表示されない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#8546]
## 💡 Summary
Androidで絵文字ピッカーの候補が文字を確定しないと表示されない

## 🥰 Expected Behavior
iOSのように入力途中でも候補が出る

## 🤬 Actual Behavior
文字を確定しないと表示されない

## 📝 Steps to Reproduce

1.リアクションピッカーを開く
2.絵文字idを打つ
3.確定しない

## 📌 Environment

Misskey version: 12.110.1
Your OS: Android 12.1, 11.0
IME: Gboard 11.6.11.433184565, Galaxyキーボード 5.3.50.2
Your browser: Chrome 100.0.4896.127

**Comment by Johann150** [comment]
probably related to https://github.com/vuejs/vue/issues/9777#issuecomment-478831263

**Comment by syuilo** [comment]
fixed by https://github.com/misskey-dev/misskey/pull/9385
