### ISSUE TITLE
ARM64 Support for Docker Hub Image

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8555]
## Summary
High demand but building on GitHub Action is too slow.

**Comment by tamaina** [comment]
Pull Requestで議論するような話題ではないのでIssueを立ててみたものの、単純にお金かけるか不便を強いるかの2択なのよね

**Comment by tamaina** [comment]
Q. Actionsで時間がかかるのって問題？

**Comment by tamaina** [comment]
Resolved?

**Comment by tamaina** [comment]
Closed by #9920

**Comment by zyoshoka** [comment]
閉じ忘れ？
