### ISSUE TITLE
show user IP to administrator (or moderators)

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8564]
## Summary

Please allow mods/admins to IP ban people, there's someone on my instance who I keep suspending and they keep making new accounts.

**Comment by Candinya** [comment]
You may consider using firewall rules for better performance and maintainability concerns.

**Comment by jrasanen** [comment]
While I see why this is useful, I consider this to be responsibility of the network layer, not misskey / the application servers

**Comment by ThatOneCalculator** [comment]
At least let Misskey admins see the IP addresses of users like Mastodon/Pleroma

**Comment by Johann150** [comment]
I agree that this can be more easily and efficiently solved on a lower layer than Misskey. If you want to completely block the user from seeing your instance you may want to use a firewall to block their IP. If you want to only block them from registration you can block the IP from the `/signup` or `/signin` paths with your reverse proxy. Be advised that their IP may change due to IP address rotation by a carrier or by them using VPNs.

**Comment by ThatOneCalculator** [comment]
Yea, but right now I can't even see the IPs of users raiding.

**Comment by syuilo** [comment]
The ability to display a user's IP address may be necessary, but the actual access restriction should be done at nginx etc or at a lower layer.
If Misskey does this, it adds unnecessary complexity to the software and increases the load as a decision is made on every request.

**Comment by Johann150** [comment]
The IP address is recorded in the sign in history. So currently you can reset the password to go into the account and see the sign in history. (or view the sign in history via the database)

**Comment by Candinya** [comment]
You can execute this SQL to query user IPs from database before further implementations deployed:
``` SQL
SELECT ip FROM signin WHERE "userId" = (
    SELECT id FROM public.user WHERE host IS NULL AND username = 'TARGET_USERNAME'
);
```

**Comment by YokaiRick** [comment]
Also (at least in Germany),  User IP Addresses are dynamic.. so blocking one IP doesn't solve anything in that case ^^c

**Comment by Johann150** [comment]
Duplicate of #5502
