### ISSUE TITLE
[UX] Keybind/Hotkey should not be captured until logged in

### ISSUE THREAD

**Issue by sandycorzeta** [syuilo/Misskey#8567]
## 💡 Summary
When you visit a misskey instance homepage without logged in, if you happen accidentally pressing "n" button, the Note creation dialog will appear.

## 🥰 Expected Behavior
any keybinding or shortcut key should have activated when the user already logged in and not working if the user is not logged in yet

## 🤬 Actual Behavior
The keybinding or shortcut key is working although the user is not logged in

## 📝 Steps to Reproduce

1. Go to any misskey instance homepage
2. press "N" for open the Note creation dialog or "D" to toggle color-scheme mode

https://user-images.githubusercontent.com/4186454/165992103-08502ba5-7bc8-4b2f-a25e-c87fc2244de6.mp4

3. Results like in the video 

## 📌 Environment

Misskey version: 12.110.1
Your OS: macOS Monterey
Your browser: Safari

**Comment by Johann150** [comment]
Duplicate of #8491
