### ISSUE TITLE
No rel attribute on <Link /> in /.well-known/host-meta

### ISSUE THREAD

**Issue by DelilahHoare** [syuilo/Misskey#8582]
I don't know much about the fediverse protocols, and I can't find a spec for whatever is supposed to be happening here, so forgive me if this isn't your bug.  I've been trying to figure out why GNU Social won't talk to Misskey, and I think it's because it looks for a link with `rel="lrdd"` in `/.well-known/host-meta`.  When talking to Mastodon, it finds a link to webfinger there.  Misskey has a link to webfinger in that file, but it doesn't have a `rel` attribute at all, and GNU Social gives up.

**Comment by mei23** [comment]
Oops
https://github.com/misskey-dev/misskey/pull/4330/files#diff-01164bf98124d6732b426469d545ac6cc874fb8aa64a55dbe2009e48e7cbeda4
