### ISSUE TITLE
Extreme MFM able to escape bounds of box

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8602]
## 💡 Summary

This occurs when viewing `Current mood: $[twitch.speed=0.1s $[x2 $[spin.y,speed=0.4s $[spin.x,speed=0.4s  $[spin.z,speed=0.1s Contrapasso]]]]]` in the timeline

https://user-images.githubusercontent.com/44733677/166194926-c609b5fb-afd9-4c30-a346-724ad89a30c4.mp4

Link: https://stop.voring.me/notes/8zrx3ufprh

## 🥰 Expected Behavior

Doesn't glitch out of box

## 🤬 Actual Behavior

Text glitches out of box

## 📝 Steps to Reproduce

Post `Current mood: $[twitch.speed=0.1s $[x2 $[spin.y,speed=0.4s $[spin.x,speed=0.4s  $[spin.z,speed=0.1s Contrapasso]]]]]`

## 📌 Environment

Misskey version: 12.110.1 (latest commit to develop)
Your OS: Linux
Your browser: Firefox

**Comment by ThatOneCalculator** [comment]
It's more noticeable when the text is selected


https://user-images.githubusercontent.com/44733677/166195375-72cbaf7d-875b-43da-8edb-3f49276ffae3.mp4

**Comment by tamaina** [comment]
Does `overflow: clip` not work?

**Comment by ThatOneCalculator** [comment]
I guess not :sweat_smile:

**Comment by ThatOneCalculator** [comment]
Also, this only seems to be an issue on desktop, it behaves normally on mobile.

**Comment by Johann150** [comment]
Are you using any custom CSS in your client?

**Comment by ThatOneCalculator** [comment]
For that screenshot, I wasn't outside of the font

**Comment by KisaragiEffective** [comment]
triage: it is non-escapeable on `2024.5.0`. Please re-open if that's not true.
