### ISSUE TITLE
Vite causes incompatibility with older browsers

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8603]
## 💡 Summary

The new Vite build system causes older phones to not load Misskey. 

## 🥰 Expected Behavior

Phones load Misskey

## 🤬 Actual Behavior

<details>
<summary><b>Click to see screenshots from other people</b></summary>

![e006b7008c134dd246ac9f953459195eb85f7390ddb60a277755671674f0e7acb4729dcc6f913f5387fbdf6aad7c2eb46da1ac3d3a8eb1732471865ef7f2b778.png](https://user-images.githubusercontent.com/44733677/166260859-5627ea8f-3673-4393-9320-41da6e54c59b.png)
![8439ea7719fc93139e88c5353acf6e19a030c8a20c19e07566983a179b66a94264669f3a5cac84045902f978e8298b2b17b1933bf5dda88d69547f266b50750a.png](https://user-images.githubusercontent.com/44733677/166260894-9329d8fc-8fd1-427d-91e3-ca60f2eee6fd.png)
![a8c57d4d415f71eec51998ca16833abf3f0732a34bc82961f4116fe443f89a865f7afc4e0e1f78f54045a75e54bb5e5aa2bd0ade5567e5b56a9a27d47fa042b6.png](https://user-images.githubusercontent.com/44733677/166260907-07f0e251-59a4-4077-a201-3073b08e00b2.png)

</details>

## 📌 Environment

Misskey version: 12.110.1 (latest commit)
Your OS: iOS before 15 (unknown), Android 9
Your browser: Safari(?), Firefox, Chromium

**Comment by ThatOneCalculator** [comment]
This also recently happened with Waterfox G3 on someone else's computer.

**Comment by tamaina** [comment]
We cannot help you resolve this issue without knowing your browser version.

**Comment by ThatOneCalculator** [comment]
The problem is this has all been issues from other people. All my devices are up to date so I can't reproduce the issue. 

The one browser with *somewhat* of a version is Waterfox G3.

**Comment by acid-chicken** [comment]
iOS 14.8.1 ![image](https://user-images.githubusercontent.com/20679825/173187500-c6263f54-d0bf-462c-9c88-f55e287d934c.png)

**Comment by pixeldesu** [comment]
This issue also affects QtWebEngine browsers (qutebrowser, Falcon, Konqueror)

Most likely coming from Vite targeting evergreen browser feature-sets and the older browsers most likely don't support those (yet). A possible mitigation for this issue would be implementing [vite/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) but I'm not sure how well this would work in our setup (ping @tamaina, I guess?)

**Comment by tamaina** [comment]
Viteビルドのターゲットバージョン上げすぎたわね  
(そこまで古いバージョンのブラウザを使っている人間が多いと思わなかった)

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/develop/packages/client/vite.config.ts#L48-L48

今ちょっとコード触れないんですがここを変えるだけで改善するかも

**Comment by pixeldesu** [comment]
I wonder if setting `build.target` to `es2017` would fix it? That at least is the version 110.1 used for compilation 🤔 

(we should be able to specify that according to https://esbuild.github.io/api/#target)

**Comment by tamaina** [comment]
以前のビルドターゲットもesnextじゃなかった？

**Comment by pixeldesu** [comment]
I'm not exactly sure which one TS uses preferably in this case, but _both_ are set
https://github.com/misskey-dev/misskey/blob/12.110.1/packages/client/tsconfig.json#L12-L13

**Comment by ghost** [comment]
When setting the build target to either es2017 or chrome87 (stable QtWebEngine is based on that):
```
rendering chunks (57)...[vite:esbuild-transpile] Transform failed with 1 error:
emojilist.da090e24.js:4:19: ERROR: Top-level await is not available in the configured target environment ("chrome87", "firefox100", "safari15")

Top-level await is not available in the configured target environment ("chrome87", "firefox100", "safari15")
2  |
3  |  const unicodeEmojiCategories = ["face", "people", "animals_and_nature", "food_and_drink", "activity", "travel_and_places", "objects", "symbols", "flags"];
4  |  const emojilist = (await __vitePreload(() => import('./emojilist.86faef74.js'),true?"__VITE_PRELOAD__":void 0)).default;
   |                     ^
5  |
6  |  export { emojilist as e, unicodeEmojiCategories as u };

error during build:
Error: Transform failed with 1 error:
emojilist.da090e24.js:4:19: ERROR: Top-level await is not available in the configured target environment ("chrome87", "firefox100", "safari15")
    at failureErrorWithLog (/home/misskey/misskey/packages/client/node_modules/esbuild/lib/main.js:1603:15)
    at /home/misskey/misskey/packages/client/node_modules/esbuild/lib/main.js:1392:29
    at /home/misskey/misskey/packages/client/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/home/misskey/misskey/packages/client/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/home/misskey/misskey/packages/client/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
/home/misskey/misskey/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: npm run build
    at makeError (/home/misskey/misskey/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/misskey/misskey/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/misskey/misskey/scripts/build.js:14:2 {
  shortMessage: 'Command failed with exit code 1: npm run build',
  command: 'npm run build',
  escapedCommand: 'npm run build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by tamaina** [comment]
es2017指定でいいかも

**Comment by tamaina** [comment]
だめらしい

**Comment by ghost** [comment]
https://github.com/Menci/vite-plugin-top-level-await this seems to be a workaround for that issue

**Comment by rinsuki** [comment]
:eyes: https://github.com/Menci/vite-plugin-top-level-await

**Comment by ghost** [comment]
<img width="248" alt="Screenshot_20220611_144716" src="https://user-images.githubusercontent.com/652892/173188576-8635f099-a4dc-438a-9b56-e1646f22ba76.png">

looks like it’s working!

**Comment by ThatOneCalculator** [comment]
@mia-0 I added that package/config to my instance, can you see if https://stop.voring.me works on an older device?

**Comment by ghost** [comment]
seems to work.

however i noticed dialog boxes (search, voting, pasting note URLs etc.) are not showing up

**Comment by ThatOneCalculator** [comment]
Yep, also with the delete message prompt. Removing the plugin fixes the issue.

**Comment by tamaina** [comment]
環境別の私見

## iOS/Safari 14以前
ユーザーが15にアップデートするべき

## QtWebEngine v5
QtWebEngine 6.3.0はChromium v94なので、多分esnextで大丈夫なんじゃないかなと

問題はQtWebEngine v5環境(Chromium v87)

qutebrowser, Falcon, Konquerorはv6に対応していないので問題が発生する

https://wiki.qt.io/QtWebEngine/ChromiumVersions

Chromium 87は2年前に出たわけだけど、正直そんな古いバージョンをサポートするのは面倒。ほかのサービスにもこれからサポートを切られると思うので、ブラウザをアップデートしてもらうしかないと思う。

## Androidの一部ブラウザ？
どのブラウザが古いChromiumを使っているのかは情報不足だけど、どちらにせよ積極的にサポートする気にはなれない
