### ISSUE TITLE
Crash when processing certain PNGs in ARM64

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#8605]
## 💡 Summary
ARM64上で稼働しているインスタンスで特定のPNGを処理しようとするとクラッシュします。

```
malloc(): corrupted top size
ERR  *        [core cluster]        [1] died :(
```

特定のPNGとして Pixelfed のデフォルト [favicon.png](https://github.com/pixelfed/pixelfed/raw/28bbd63300fbe81b969039373eed8a70a77b4938/public/img/favicon.png) などが該当するため、URLプレビューで Pixelfed インスタンスを表示しようとした時などにクラッシュします。

起きる環境の例
```
Ubuntu 20.04.4 on AWS t4g
Linux hostname 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:14:11 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

Ubuntu 20.04.4 on OCI A1
Linux hostname 5.13.0-1027-oracle #32~20.04.1-Ubuntu SMP Fri Apr 15 06:01:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

sharpが0.30.0以降だと起きる
```
OK sharp 0.29.3
NG sharp 0.30.0 - 0.30.4 
```

## 🥰 Expected Behavior
クラッシュしない

## 🤬 Actual Behavior
クラッシュする

## 📝 Steps to Reproduce

1. ARM64上でMisskeyインスタンスを構築する
2. PixelfedインスタンスのURLを投稿してURLプレビューを表示させようとする

## 📌 Environment
Misskey version: 12.110.1
Summary を参照

**Comment by acid-chicken** [comment]
https://github.com/lovell/sharp/compare/v0.29.3...v0.30.0
https://github.com/libvips/libvips/compare/v8.11.4...v8.12.2

**Comment by mei23** [comment]
`await sharp('favicon.png').toBuffer()` だけで落ちる
`jemalloc`を使うようにすると起きないらしい

**Comment by 4ioskd** [comment]
@syuilo PRの消化等で忙しくてお忘れかもしれませんが、high priorityのラベルが貼られてますので、対応頂けたら幸いです。私の知っている限りでは複数のARM64インスタンスでクラッシュしてるのを観測しています。
FYI( めいめい先生のめいすきーでの対応策 )： https://github.com/mei23/misskey/commit/32e4ef4721a555de073c2068627d88954ddcd1b2

**Comment by tamaina** [comment]
これじゃだめなんだっけ  
(どちらにしろ面倒か)

https://misskey.xianon.net/notes/8zrrs9qm9c

**Comment by tamaina** [comment]
とりあえず https://github.com/mei23/misskey/commit/32e4ef4721a555de073c2068627d88954ddcd1b2 と同じ対応でいいかしらね

sharp.jsのGitHubにはこれに関係するIssueはない？

**Comment by mei23** [comment]
0.30.x に依存する機能は使ってないので 0.29.x にすればいいと思うのだわ。
sharp.js にIssueはないけど結局 libvips 依存だとは思うのだわ。

**Comment by syuilo** [comment]
とりあえず戻そう

**Comment by tamaina** [comment]
Issue書いた  
https://github.com/lovell/sharp/issues/3225

**Comment by tamaina** [comment]
Sharp v0.30.1 以降で直るらしい

**Comment by mei23** [comment]
v0.31.x 以降だわね

**Comment by mei23** [comment]
いや、v0.30.1以下か v0.31.x以降なら起きない と言ってる？！
