### ISSUE TITLE
MiAuth doesn't support callbacks with query segment

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8608]
## 💡 Summary

As part of the MiAuth flow, misskey expects apps to perform a redirect to the permission grant page at `https://{host}/miauth/{session}` with a `callback` URL that the user will land on after permission is granted.

Currently when the user clicks accept [the relevant code](https://github.com/misskey-dev/misskey/blob/1f222e6cd19dcf2f4bb679e810090f11ce6fdc6a/packages/client/src/pages/miauth.vue#L85) just blindly appends `?session=...`, which - if used with redirect URLs like `https://blahaj.club/login/callback?type=misskey` - will result in a URL that (while *technically* valid) is hard to parse correctly.

This behavior has been present ever since MiAuth was introduced with 6be127e18bdbea6031698baeb8632f917a8346eb.

Because of how long this went (seemingly) unnoticed I'm not entirely sure if this is a bug or if MiAuth simply doesn't support this usecase. If it _is_ a valid bug I'd be happy to fix it.

## 🥰 Expected Behavior

The query segment is retained and correctly appended to (if present)

## 🤬 Actual Behavior

The callback URL ends up having two `?`s and requires mildly annoying workarounds to parse correctly.

## 📝 Steps to Reproduce

- Use the `/miauth/{session}` endpoint with a redirect URL like `https://blahaj.club/login/callback?type=misskey`

**Comment by Johann150** [comment]
I think your use case is valid and this should work. A solution similar to #8494 should probably be an easy fix.
