### ISSUE TITLE
通報一覧で状態等のフィルターが反映されない

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#8609]
## 💡 Summary

インスタンスの通報一覧で状態やリモートなどのフィルターが変更しても反映されない

## 🥰 Expected Behavior

変更したら反映される

## 🤬 Actual Behavior

変更しても反映されない

## 📝 Steps to Reproduce

1. 通報一覧を開く
2. 状態などのフィルターを変える
3. 何も変わらない

## 📌 Environment

Misskey version: 12.110.1
Your OS: Windows10
Your browser: Vivaldi 5.2.2623.41 (Stable channel) (64-bit)

**Comment by Johann150** [comment]
Duplicate of #8479
