### ISSUE TITLE
Uploading from Phone Gallery doesn't appear as option in Android PWA

### ISSUE THREAD

**Issue by sandycorzeta** [syuilo/Misskey#8623]
## 💡 Summary

The Android PWA doesnt have uploading from Gallery app unlike the iOS does. But its possible through Files app. Is this a limitation of Android system?

## 🥰 Expected Behavior

Can upload through Gallery/Photos Library app.

## 🤬 Actual Behavior

Gallery/Photos Library app doesnt appear

## 📝 Steps to Reproduce

1. Create Note
2. Click upload button
3. Choose from files
4. Option only appear (Camera, Camcorder, Audio Recorder, and Files)

This is what in Android PWA looks like 

<img src="https://obj.misskey.id/media/bf03939b-f367-49dd-92fc-2b6c494034cd.jpg" height="500"/>

This is what in iOS PWA looks like
>The Photos Library option is equivalent to Gallery app in Android
<img src="https://obj.misskey.id/media/8bdd34b6-6242-4182-bd46-cf1ddbf8853f.png" height="500"/>

## 📌 Environment

Misskey version: 12.110.1
Your OS: Android
Your browser: PWA

**Comment by Johann150** [comment]
Are pictures from the gallery maybe included in Files? 

Either way I'm not sure how much influence Misskey has over either of these selection dialogs as they seem to be browser components.

**Comment by AMoonRabbit** [comment]
As Johann150 mentioned, you can get to Photos app, and others through the Files option. I think this is more down to the underlying browser than the PWA itself.

**Comment by sandycorzeta** [comment]
In my android phone, the gallery can be accessed through Files too as its shown in the picture. But yea its a 2-step process. Is there a possibility to bring the Gallery option straight in the picker just like iOS did?
<img src="https://obj.misskey.id/media/6a8e2f19-913a-4f5d-a2ce-09a4a2087e49.jpg" height="500"/>

**Comment by AMoonRabbit** [comment]
The problem is it's two different OSs, and the way they handle integration. Of the PWAs I have installed, none offer direct links to installed image apps, just the Files option which then gives you access beyond that. Do you have an example of a PWA that does work the way you intend?

**Comment by sandycorzeta** [comment]
>Do you have an example of a PWA that does work the way you intend?

No, i guess my only problem is just the user experience of it that have to be 2-step process. If its possible to make gallery app as choosable option like Files and Camera that would be great. But, if its the browser limitation... i guess 2-step process is okay for now.

**Comment by Johann150** [comment]
According to [this medium article](https://daviddalbusco.medium.com/take-photo-and-access-the-picture-library-in-your-pwa-without-plugins-876dc92989b) there is a way to tell the browser to only allow image uploads in which case it might show selection specific to images, but Misskey allows more than just image uploads. I think it is not possible for Misskey to change anything about this.
