### ISSUE TITLE
Connecting to Diaspora, Lemmy, and Mobilizon instances

### ISSUE THREAD

**Issue by wolfsgrove** [syuilo/Misskey#8629]
## Summary

I'm a new Misskey user and tried to connect to my other Fediverse accounts. Three connections failed: Diaspora (sysad.org), Lemmy (sopuli.xyz), and Mobilizon (events.nixnet.services). Only Friendica has been successful in connecting to everything.

I'd like to be able to see my activity from those other instances/services on Misskey. Is implementing this possible?

My notes on this on Misskey: https://mk.nixnet.social/notes/8zzvj2sm3d

**Comment by Johann150** [comment]
maybe related to #8165

**Comment by 4ioskd** [comment]
Diaspora uses their own "diaspora* federation protocol" to federate with another Diaspora server. Its protocol is different from ActivityPub used by Misskey,Lemmy and Mobilizion and can't be connected to Misskey. In addition, Misskey only supports ActivityPub. 
So, I think the current misskey-dev team doesn't have a plan and afford to implement additional protocol like diaspora one. But there is a possibility of supporting Lemmy and Mobilizion through ActivityPub.

**Comment by Johann150** [comment]
Yes, Diaspora interoperability is not planned. I hope the other two should be fixed by the PR linked above. The issue will close when the PR is merged.

If it still does not work after that, please also wait for #8689 to be merged because I think that might be a related issue.
