### ISSUE TITLE
contact details

### ISSUE THREAD

**Issue by Rik44444** [syuilo/Misskey#8636]
Dear Misskey,
does your initiative come with a secretariat, and a general contact email address for that organization? 
thanks,
Rik

**Comment by Johann150** [comment]
Misskey does not really have a rigid organizational structure nor a secretariat. If you can describe the nature of what you want to know we might be able to help you here.

**Comment by Rik44444** [comment]
ah my name is Rik Viergever, i work for Murena, we make an open-source, privacy-safe version of Android for mobile phones and tablets. Our website is: www.e.foundation 
i was hoping to speak to someone about a possible collaboration in terms of advocacy that we are setting up with a group of other open-source organizations and initiatives.

**Comment by Johann150** [comment]
Is it not possible to discuss this publicly?

**Comment by Rik44444** [comment]
ah sure, it is all open and nothing is secret, but we usually discuss it with people verbally. I'll close this comment, feel free to contact me if someone from Misskey wants to discuss it! rikviergever@e.email
