### ISSUE TITLE
添付した画像の順番がドライブに上げた順になる

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#8647]
## 💡 Summary

画像を下記のように添付しても https://misskey.io/notes/905gpqcna5 になってしまう

![image](https://user-images.githubusercontent.com/28654659/167917813-b3280b19-4669-426b-a99b-93dec82c681e.png)

## 🥰 Expected Behavior

ドライブで選択した順番になる（以前の挙動）

## 🤬 Actual Behavior

ドライブに上げた順になる（fileIdの降順で表示される？）

## 📝 Steps to Reproduce

1.画像を上げる
2.ドライブから選択する
3.順番が異なる

## 📌 Environment

Misskey version: 12.110.1
Your OS: Windows 10
Your browser:
- Vivaldi 5.2.2623.41 (Stable channel) (64-bit)
- Chrome 101.0.4951.54 (Official Build) （64 ビット） (cohort: Stable)
- FireFox 100.0 (64 ビット)

**Comment by Johann150** [comment]
The client seems to send the `fileIds` to the API in the same order, no matter how they are ordered in the UI. So this seems to be a client issue.

**Comment by Johann150** [comment]
I think this was broken in commit 9f7cdb4bc734e02be0acc03bfae5abe94ac7466c.
