### ISSUE TITLE
Bot protection warning shouldn't be displayed if user registration is deactivated

### ISSUE THREAD

**Issue by YokaiRick** [syuilo/Misskey#8651]
## 💡 Summary
I think Misskey shouldn't display the Bot protection warning when new user registration is disabled. 
![1652387782-grim](https://user-images.githubusercontent.com/24204874/168164397-99f9675f-38bf-4cb5-9153-8a07a905683e.png)
![1652387821-grim](https://user-images.githubusercontent.com/24204874/168164411-0baa02b6-3702-43ca-9acd-f20b8f86517a.png)

## 🥰 Expected Behavior
Bot protection warning is not shown if bot configuration is enabled or if new user registration is disabled

## 🤬 Actual Behavior
Bot protection warning is shown, even user registration is disabled.

## 📝 Steps to Reproduce

1. Go to Control Panel
2. Deactivate new User registration
3. Warning about Bot protection (for user registration) is still shown in admin panel

## 📌 Environment

Misskey version: 12.110.1
Your OS: Arch Linux
Your browser: Firefox 100.0

**Comment by 4ioskd** [comment]
I agree. Bump up.

**Comment by syuilo** [comment]
CAPTCHAs could be used for more than just signups, so I don't see the need to fix this.

**Comment by pixeldesu** [comment]
> CAPTCHAs could be used for more than just signups, so I don't see the need to fix this.

@syuilo what other area aside of signups would make sense for a CAPTCHA? If someone already gets an account to spam/etc. then the user can just be taken care of using moderation.

And even so, we could remove the warning for now and add it back once we have another use-case for CAPTCHAs!
