### ISSUE TITLE
Clearing notifications in the settings is missing feedback

### ISSUE THREAD

**Issue by pixeldesu** [syuilo/Misskey#8653]
## Summary

Currently, clearing the notifications over any button on `/settings/notifications` does not give any feedback. The notification count might be cleared, but if it isn't visible, nothing is happening for the user even if the request succeeds.

Some feedback using one of the success popups (like `os.success()`) should be given.

**Comment by Johann150** [comment]
I think using `os.apiWithDialog` for those API requests makes the most sense to fix this.
