### ISSUE TITLE
federation: follow request does not have a proper `id`

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8655]
## 💡 Summary
When Misskey sends a follow request, the activity `id` may be missing.

## 🥰 Expected Behavior
Follow requests always have meaningful `id`s.

## 🤬 Actual Behavior
Follow requests have fallback `id`s that misskey can not resolve again when receiving them, breaking interaction with other Fediverse software. (see https://github.com/owncast/owncast/issues/1690)

## 📝 Steps to Reproduce

1. Misskey sends follow request.
2. Other side responds with only the id of the follow request instead of a full follow request `object`.
3. Follow can not be completed. Job is stuck in the inbox queue with the error from this comment: https://github.com/misskey-dev/misskey/pull/8635#issuecomment-1125355809

## 📌 Environment

Misskey version: 12.110.1 with #8635 applied
Owncast version: 0.0.11

**Comment by mei23** [comment]
May be related
https://github.com/misskey-dev/misskey/issues/8218
