### ISSUE TITLE
It is possible to listen to high ports as non-root

### ISSUE THREAD

**Issue by alpharde** [syuilo/Misskey#8668]
## 💡 Summary

It is possible to listen to high ports (<1024) as non-root with the proper capabilities set. Misskey with exit with error if ran on port 80 without root.

## 🥰 Expected Behavior

Misskey properly binding on port.

## 🤬 Actual Behavior

```
You need root privileges to listen on well-known port on Linux
The process is going to exit with code 1
```

## 📝 Steps to Reproduce

1. `setcap 'cap_net_bind_service=+ep' /usr/bin/node`
2. start the program: `cd /opt/misskey && NODE_ENV=production npm start` etc...

## 📌 Environment

Alpine Linux

**Comment by ledlamp** [comment]
+1, it should try to listen and then say that if it can't, not make assumptions.

**Comment by tamaina** [comment]
I believe that Misskey should be used with nginx (or other proxies). So I am reluctant to handle high ports with Misskey.

**Comment by mei23** [comment]
もちろん Well-Known port で Listen することは推奨できませんが、あえて事前拒否するものでもないと思います。

- 今はconfigにport 3000だけが明示されているため、間違ってポートを変更する可能性は低い。
- rootチェックやportチェックのために、環境依存や古いモジュールに依存したり起動遅延につながる。

などの理由もあります。

なぜ、現状のMisskeyで事前にポート等のチェックがされているかを考えると
単純にチェックを外すとListen失敗時にスタックしてしまう (master processが実際にListenを行うsub processからのreadyを受け取れるまで待ち続けてしまう) 問題のせいなのではと思います。

sub processでListenに失敗した場合にのみ、ちゃんとエラーをハンドルするようにして、適切にmaster processが終了するようにして、メッセージも表示できるようにすれば問題ないかと思います。
(環境依存のコードもなくなり正常時の起動もスムーズになる)

**Comment by Johann150** [comment]
We already check that the port is available separately:
https://github.com/misskey-dev/misskey/blob/e3f2d469c0a42536bed59ff626cbbf05d7c0baf1/packages/backend/src/boot/master.ts#L172-L175
Although there could be a race condition where another program takes the port while starting the workers, but I think the chances are low because Misskey is running in a trusted environment. Ideally we would check for a used port in the worker, but I think we could get away without checking.

**Comment by Johann150** [comment]
For specific error handling we could add a rejection here:
https://github.com/misskey-dev/misskey/blob/e3f2d469c0a42536bed59ff626cbbf05d7c0baf1/packages/backend/src/server/index.ts#L140-L146
If the second `reject` parameter gets added, maybe even just `server.on('error', reject);` which might be a good idea to add independently of allowing listening on high ports.

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/blob/e3f2d469c0a42536bed59ff626cbbf05d7c0baf1/packages/backend/src/boot/master.ts#L167
Mac, BSD, ... 🙄
