### ISSUE TITLE
Resolver tries to fetch local ActivityPub content via HTTP

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8688]
## 💡 Summary
The current resolver implementation always tries to fetch content from the web. This also applies to content generated by the server itself.
While this works, it is very inefficient because it has to go through the complete HTTP stack and takes up resources in the reverse proxy server.

## 📌 Environment
Misskey version: 12.110.1

**Comment by mei23** [comment]
Wow, I didn't expect to be able to Resovle and process local objects with `activitypub/kernel`.
(I'm not an implementer, so I don't know the original intention.)

In many places, local uri has a process that does not call Resolver in the first place.

**Comment by Johann150** [comment]
> In many places, local uri has a process that does not call Resolver in the first place.

I should have looked into that more in detail. But I think it would be nice if there is a way where you do not have to think about resolving a URL too much. And I think the most obvious solution would for `Resolver.resolve` to check if a URL is local. It could then make use of `DbResolver` functionality.

But there is a difference between `Resolver` and `DbResolver`: The former returns the ActivityStreams representation and the other returns the Misskey object representation. So some mapping might still be necessary.

Or alternatively, uses of `Resolver.resolve` should be checked if they can use `DbResolver` instead.

**Comment by mei23** [comment]
If Resolver can use local uri, I think there is a part that will be smart.
However, both functions are different, so I think you will need both.

**Comment by Johann150** [comment]
Maybe `DbResolver` should have functionality like the `api/ap/show` endpoint.

side note: That endpoint should probably be refactored to use `DbResolver.parseUri` or the new `Resolver.resolve` functionality I described above.

**Comment by Johann150** [comment]
I wonder if we should also prefer checking the database to making a HTTPS request in the normal `Resolver`, even for non-local URLs.
