### ISSUE TITLE
Support Move activities

### ISSUE THREAD

**Issue by Gargron** [syuilo/Misskey#8690]
## Summary

Support ActivityPub `Move` activities. When the `object` is an account (and it is the same account as the `actor`) and `target` is an account, and the `target` account lists the `object` account in its `alsoKnownAs` property, local followers of the `object` account should unfollow that account and follow the new one automatically.

**Comment by nbsp** [comment]
for reference, this is how Pleroma respects incoming `Move` activities:
- there is a user-level toggle in the settings, to allow auto-follow when following account moves
- if enabled, when an account moves, it auto-follows the new one and sends the user a notification that the account has been migrated. as far as I can tell Pleroma does not unfollow the original account

**Comment by Gargron** [comment]
The reason for unfollowing the old account is to dissuade people from farming and then selling followers. If you do not unfollow the old account, the original owner can keep sending out `Move` activities to different accounts.

**Comment by robflop** [comment]
That's a good idea, and a feature I've seen people talk about wanting a few times already.

Logically speaking, successive moves should form a chain of moves from accounts where there is never a pair of successive moves from the same account in a row, so I believe the unfollow restriction handles that well.

**Comment by 4ioskd** [comment]
Hello @Gargron
I'm Dignified Silence. One of Misskey contributor.

Out of context, I personally welcome you opening an issue on Misskey. I first joined the Fediverse through Mastodon, then moved to Pleroma and am now on Misskey. In that sense, I would not be where I am today without Mastodon. I thank Mastodon so much for giving me the opportunity to join the Fediverse.

By the way, it may be that you suddenly opened an issue here, but while some people on Misskey are as welcoming as I am, others are confused or don't know how to react. Why did you suddenly open this issue? Perhaps there is another reason??

**Comment by tamaina** [comment]
Duplicate of #5475
