### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by alpharde** [syuilo/Misskey#8692]
## Summary

My community run on ldap however it seems that Misskey does not support it.

**Comment by Johann150** [comment]
I think LDAP would add a large amount of complexity to the backend and I am not sure we are prepared to do that. I personally think it is too complex and not needed in most cases.

**Comment by alpharde** [comment]
Minimal "just check if account exists" functionality does it for me, however LDAP is multi-domain by nature and I have no idea if misskey does support this.

**Comment by Johann150** [comment]
Misskey is intended for running on a single (DNS) domain. I'm not too familiar with LDAP but I think it (or Active Directory) has a slightly different concept of domains so I'm not sure if DNS domains is what you mean here.

Regardless, I do not think LDAP is something we can or should support at this time.

**Comment by xtexChooser** [comment]
@Johann150 could you reopen this? LDAP could also be used with only one domain.
