### ISSUE TITLE
Vite causes FOUC

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8717]
## 💡 Summary

This:

https://user-images.githubusercontent.com/44733677/169630637-41744971-8cd0-442c-8c32-66def7ba1186.mp4

https://user-images.githubusercontent.com/44733677/169630698-8a04c040-a231-4d80-8f59-e7b58633b180.mp4

## 📝 Steps to Reproduce

1. Load Misskey

This seems to be a problem with Vite, as this didn't happen before Vite.

## 📌 Environment

Misskey version: Latest git (12.110.1)
Your OS: Linux, Android
Your browser: Firefox, Chrome

**Comment by syuilo** [comment]
This seems to be a vite issue. (FOUC)

**Comment by ThatOneCalculator** [comment]
I think it's the problem of Vite not loading styles at startup. Seems like I'm not the only one with this issue: https://stop.voring.me/notes/90itqps1g3

**Comment by tamaina** [comment]
I have asked the question on the Vite Discord but received no response.

> **Note**
> PR of Vite https://github.com/misskey-dev/misskey/pull/8575

**Comment by tamaina** [comment]
いつの間にかVite 3のalphaが出ておる…

**Comment by tamaina** [comment]
もしかしたら、Viteのバージョンを2.9.9などに上げれば直るかもしれない

**Comment by 4ioskd** [comment]
FYI: 現在はv3.0.0-alpha.2が出てます
https://github.com/vitejs/vite/releases

**Comment by ThatOneCalculator** [comment]
I switched my instance to build with Vite 3 Alpha 4 (with the Alpha 3 Vue plugin) and sadly it didn't fix the issue.

**Comment by NovaAndrom3da** [comment]
Oh. I've had this/a very similar issue with vite. Try disabling HMR (hot module replacement) in the vite json config file.

```js
  "hmr": false,
```

Although, doing this will cause you to have to restart the server each time you make a change on the server, which shouldn't be a big deal if you are attempting to run in a production deployment, but would get annoying in a development environment.

**Comment by NovaAndrom3da** [comment]
This can sometimes be fixed by setting the HMR client port to 443 (as mentioned here: https://github.com/vitejs/vite/issues/4259) but (IIRC) it didn't work for me when I had this issue.

**Comment by NovaAndrom3da** [comment]
Just to make sure, do you see `connection to server lost, polling for restart` when you open DevTools?

**Comment by tamaina** [comment]
We are using `vite build --watch` and do not use HMR, so I don't think it will solve the problem.

**Comment by tamaina** [comment]
I confirm that updating vite to 2.9.9 and `server.hmr: false` does not solve the problem in my local environment.

**Comment by tamaina** [comment]
Issue出すにしてもminimal reproducible exampleだと再現しない…

**Comment by acid-chicken** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20679825/170820173-f1eb0f13-bffb-4739-b6c0-35ca905b3e97.png">

FOUC だから当たり前だけど CSS の読み込みタイミングが遅すぎる

ここら辺関連しそう？ https://github.com/vitejs/vite/issues/2460#issuecomment-799520371

**Comment by acid-chicken** [comment]
現に preload 指定してる fontawesome の css は一番に読み込まれているので、rollup でビルドした結果を元に必要な必須チャンクを決定して、HTML 生成時に注入することが解決になりそう。 https://github.com/misskey-dev/misskey/blob/708fba989adab95b3a4c381f6b351979c5973591/packages/backend/src/server/web/views/base.pug#L33

**Comment by acid-chicken** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20679825/170821325-15b993ea-a0f7-4b4a-b6e0-2ab60ed29842.png">

手前の読み込みが長すぎて待ってくれてなさそう

もしかしてここが原因では

https://github.com/misskey-dev/misskey/blob/38e6202bdc2d4c935da652e42a3844463bf1395a/packages/client/src/scripts/theme.ts#L13-L36

**Comment by acid-chicken** [comment]
@tamaina `applyTheme` の処理どうせ CSS Paint 挟むから実質非同期だし、 src/scripts/theme.ts で即時読み込みせずに遅延読み込みにするか `Promise` のまま渡してもいいんじゃない？

**Comment by tamaina** [comment]
@acid-chicken なるほど、テーマ周りは深く考えずにrequireを置換したのでリファクタの余地がありそう

**Comment by acid-chicken** [comment]
直接的原因であるないに関わらずこれは読み込みに大きな問題を引き起こしている

**Comment by acid-chicken** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20679825/170822304-bf47d91e-24ad-406c-b492-c96d17ef7fe2.png">

`await import` が並ぶと黄色の枠のような虚無区間を生成することになる

**Comment by tamaina** [comment]
(良く考えたらせめてPromise.allを使うべきだったわ…)

**Comment by tamaina** [comment]
（PR出す前に先にコメント書くけど）テーマは関係ないっぽいなぁ

![image](https://user-images.githubusercontent.com/7973572/170825815-6dacc7a9-67e7-4303-af01-378d7f3bef33.png)
![image](https://user-images.githubusercontent.com/7973572/170825871-8c831f81-8299-482e-82d6-f035ba289269.png)

**Comment by tamaina** [comment]
仮説: CSSは読み込まれているが、scopeを判別するための[data-hoge]が後から付けられている

**Comment by ishowta** [comment]
~style.scss~app.hoge.cssだけ遅れてるかも？

**Comment by tamaina** [comment]
> 仮説: CSSは読み込まれているが、scopeを判別するための[data-hoge]が後から付けられている

css moduleもちゃんとFOUCになっているので違う気がする…？でもcss moduleも同じか？

> style.scssだけ遅れてるかも？

style.scssというかapp.hoge.css？デッキやユニバーサルUIの骨組みだけは描画されたりしているので確かにそうかも…！
