### ISSUE TITLE
Make misskey work with sqlite

### ISSUE THREAD

**Issue by bil-ash** [syuilo/Misskey#8738]
## Summary

I would like to use sqlite as a database instead of postgresql . This is because backing up a postgresql database is quite difficult task. In comparison, backing up a sqlite database is quite easy. We can periodically backup the dbname.db file or use https://litestream.io/

 Since an orm(typeorm) is being used, will only changing the db connection string from postgresql to that of sqlite work? Or is it necessary to make other changes also?

**Comment by Johann150** [comment]
I am quite sure that despite use of the ORM, Misskey is still using SQL syntax and functions that are Postgres-specific. It would probably be necessary to find and check each bit of SQL that is used anywhere in Misskey.

For example, Misskey relies on Postgres support for array data types which have some special operators. I am not sure if sqlite supports something like that. Supporting more than one database would also most likely cause significant additional workload as well.

If you use a sqlite connection I would expect at least some parts of Misskey to break. And I do not think we will be able to support it.

**Comment by Amolith** [comment]
> This is because backing up a postgresql database is quite difficult task.

It should be as simple as `pg_dump misskey > dump.sql`, then you can back `dump.sql` up however you plan to back SQLite up.

**Comment by ThatOneCalculator** [comment]
I wrote a simple bash script that runs on a cron job every day that makes a backup of Misskey, keeps all backups for the last 3 days locally and sends the backup it just took to my homelab for safe-keeping. 


```
#!/usr/bin/env bash

FILE='misskey_backup.tar'
FILE=${FILE%.*}_`date +%d-%b-%y-%s`.${FILE#*.}
echo "Making backup..."
pg_dump -F c misskey_production > $HOME/misskey_backups/$FILE
echo "Created backup"
echo "Sending data to server..."
scp $HOME/misskey_backups/$FILE my@homelab:~/voringme-backup/
find $HOME/misskey_backups/* -type f -mtime +3 -delete
echo "All done!"
```

**Comment by Amolith** [comment]
@ThatOneCalculator that's somewhat similar to the setup I have :ok_hand: 
https://docs.nixnet.services/Tarsnap#Scripting_the_dumps

**Comment by ThatOneCalculator** [comment]
Omg we're on the same brainwave bestie 🤩🤩🤩

Im too lazy to Photoshop the image, pretend it says "Berigoo to Berigoo communication"

![imgres.jpg](https://user-images.githubusercontent.com/44733677/170547273-405eef46-6c7a-4107-992d-702f54d21ad3.jpg)

**Comment by bil-ash** [comment]
Thanks for pointing out that misskey requires postgresql arrays which is not supported in sqlite.So will go with backing up postgresql regularly
