### ISSUE TITLE
Notes with no content can be made

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8747]
## 💡 Summary

When using a third party client, notes can be made with no text and no attachments. This should not be allowed. 

## 🥰 Expected Behavior

Doesn't let you make notes with no content

## 🤬 Actual Behavior

https://misskey.io/notes/90qjol4flf

## 📝 Steps to Reproduce

1. Use third party client (Kaiteki)
2. Post with nothing

## 📌 Environment

Misskey version: 12.110.1
Your OS: Android
Your browser: Firefox

**Comment by 4ioskd** [comment]
First of all, did you confirm that this problem is not on Kaiteki side but on misskey side before making this issue? Also, Note URL from misskey.io , it seems to be posted by a developer of Kaiteki. Did you get permission from the developer before making the issue?

**Comment by syuilo** [comment]
No matter what client you use, the possibility of making notes without content is a problem for Misskey.

**Comment by Johann150** [comment]
I wondered if empty `text` should be disallowed in all cases, but `''` will be treated the same as undefined when creating the note:
https://github.com/misskey-dev/misskey/blob/21d54f2758903c31714c49f278141c00e33294c9/packages/backend/src/server/api/endpoints/notes/create.ts#L259
So I think the current fix should be enough to stop creation of empty notes.
