### ISSUE TITLE
Re-registering for 2FA after disabling it but not changing your password results in a blank error

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8755]
## 💡 Summary

I used to have 2FA disabled, then I disabled it, and as I went to enable it again, I got this:

![image](https://user-images.githubusercontent.com/44733677/170853093-8efbc8a2-8407-44b4-9abc-22a16034f010.png)

Changing my Misskey password fixed the issue.

## 📝 Steps to Reproduce

1. Register for 2FA
2. Disable 2FA
3. Re-register for 2FA: ***Blank error here***
4. Change password, re-register : ***Fixes the problem***

## 📌 Environment

Misskey version: latest git (12.110.1)
Your OS: Linux
Your browser: Firefox

**Comment by Johann150** [comment]
Are there any errors in the developer console or in the server logs?

**Comment by ThatOneCalculator** [comment]
> Are there any errors in the developer console or in the server logs?

I didn't open the developer logs at the time, I *might* recreate this issue when I have time :/

**Comment by Johann150** [comment]
I just tried but can not reproduce when unregistering the 2FA token via the UI.

**Comment by Johann150** [comment]
Since I can not reproduce it I assume there must have been something wrong with your setup. Unless you can give steps to reliably reproduce this bug I think it should be closed.

**Comment by ThatOneCalculator** [comment]
I couldn't recreate it either. Probably just a one off occurrence.
