### ISSUE TITLE
Emoji search input acts as password field

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8757]
## 💡 Summary

Emoji search input acts as password field when opening the emoji picker. Reloading the page made it go away, so not sure if it's a one time bug... :thinking: 

## 🥰 Expected Behavior

Emoji search is a normal input

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/170854200-0d323261-45f8-43ec-b01b-c930af610917.png)

## 📝 Steps to Reproduce

1. Open emoji picker

## 📌 Environment

Misskey version: Latest git (12.110.1)
Your OS: Linux
Your browser: Firefox

**Comment by ThatOneCalculator** [comment]
Not sure if this is related to the issue, but as I was opening the reaction picker, I was blocked by the user (without my knowledge), so maybe this is caused by reacting to a post right as you're being blocked??

**Comment by tamaina** [comment]
これめっちゃうざい

**Comment by syuilo** [comment]
input type=search にすれば直る可能性あるかしら

**Comment by Johann150** [comment]
how about `autocomplete="off"`

**Comment by pixeldesu** [comment]
> how about `autocomplete="off"`

From [MDN `autocomplete` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#sect2):

> **Note:** In most modern browsers, setting autocomplete to `"off"` will not prevent a password manager from asking the user if they would like to save username and password information, or from automatically filling in those values in a site's login form. See [the autocomplete attribute and login fields](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields).

**Comment by 4ioskd** [comment]
`autocomplete="new-password"` or disabling the autocomplete with Javascript?
https://www.w3docs.com/snippets/html/how-to-disable-browser-autocomplete-and-autofill-on-html-form-and-input-fields.html
