### ISSUE TITLE
メタ議論：他人のノートのURLを無断で貼ったり、@をつけてメンションをする行為の禁止

### ISSUE THREAD

**Issue by 4ioskd** [syuilo/Misskey#8763]
Github上でissueやプルリクエストを作成したりコメントをする際に、他人のノートのURLを許可なく貼ったり@をつけてメンションすると、misskey.ioの @ repo アカウントやmisskey official discord内のGithubで発生したイベントのお知らせを経由して、特定のユーザーに通知が届いたり迷惑をかけてしまうことになります。前者の「他人のノートのURLを許可なく貼る」はもちろんアウトであり、「@をつけてメンションする」という行為はメンションする側が便利な一方でメンションされる側としては時に迷惑なことがあります。

以上の２点についてはコントリビューションガイドで禁止行為として明記すべきではなかろうかと思うのですが、いかがでしょうか。また他に禁止すべき行為として明記すべきものはないでしょうか。
（そもそも@ repo アカウントやmisskey official discord内のGithubで発生したイベントのお知らせを廃止すれば、このIssueは解決すると考えます。）

**Comment by tamaina** [comment]
@ repo の挙動が問題なのではないかしら

**Comment by tamaina** [comment]
（Discordでも通知が届くの…？）

**Comment by rinsuki** [comment]
- Discord は <at>everyone とかやらない限り通知が行かないはず
- 受け手が迷惑なら@repoの通知をミュートしたらいい (自分が言及されてることを知りたいこともありそう)

でいいのでは

**Comment by CyberRex0** [comment]
Discordではいかなる場合においても埋め込みの中からメンションすることはできません（表示上はできているように見えますが通知は飛びません）
ので、無害ではありそうです

（一応参考まで）

**Comment by rinsuki** [comment]
ちょっと試しに… <@265102069655011328>

**Comment by tamaina** [comment]
他人のノートを貼ることによってどのような実害があるかわからない（嫌な気分になる以外で）

後者を禁止するのはさすがに無理があるのでは…？GitHub内で無関係なGitHubユーザーをメンションするのはそもそもあり得ないし

**Comment by 4ioskd** [comment]
Discordでも通知が届くという報告を頂いたので書きましたが、私も改めて確認しましたが特に通知は届かなかったので、この点については問題無しと考えます。

>他人のノートを貼ることによってどのような実害があるかわからない（嫌な気分になる以外で）

例えば、Githubがどこの会社に所有されているかを考えると...プライバシーの問題と捉える人もいる。

>受け手が迷惑なら@repoの通知をミュートしたらいい (自分が言及されてることを知りたいこともありそう)
>後者を禁止するのはさすがに無理があるのでは…？GitHub内で無関係なGitHubユーザーをメンションするのはそもそもあり得ないし

既に述べた通り、そもそも@ repo アカウントを廃止すれば本件は解決する。@ repo アカウントはGithubで起こるイベントや自分が言及されていることをリアルタイムで把握できて非常に便利なのだけれども、一方で自分や自分が関わっているissueがリアルタイムで言及されて時にストレスを感じるというのはみなさんも経験があろうかとは思う。また、様々な事情からオフトピックでマークすべき内容が流れたりもするので、Githubで起こるイベント全てを流すのはいかがなものかとはたまに思う。そもそも、Githubで起こるイベントを取得したい人はRSSを利用したり、APIを叩いて個人的に情報を取ればそれで良いのでは（そういう意味では、どうして@ repo アカウントが出来たか知りたいですね）
またこのアカウントに直接リプライをしたり、misskeyに関する質問を投げている時があるので、アカウントとしての@ repoも時にどうなのだろう、と考える。

**Comment by tamaina** [comment]
> Githubがどこの会社に所有されているかを考えると...プライバシーの問題と捉える人

MisskeyのリポジトリがGitLabに移転するまで納得してくれなさそう

repo botは色々問題があるけど、私はこれで情報を得ているので廃止されてもされなくても私のサーバーで稼働させる予定

> 一方で自分や自分が関わっているissueがリアルタイムで言及されて時にストレスを感じるというのはみなさんも経験があろうか

ない（どうせメールで通知されるし）

**Comment by rinsuki** [comment]
> 例えば、Githubがどこの会社に所有されているかを考えると...プライバシーの問題と捉える人もいる。

あちこちのよくわからんクローラーが日夜走りまくってる現状のインターネットでその程度のプライバシーを真に気にするのだったら全部ローカル&フォロワー限定投稿にするべき

> 一方で自分や自分が関わっているissueがリアルタイムで言及されて時にストレスを感じるというのはみなさんも経験があろうかとは思う

ない (というかストレス感じるならミュートしなよ)

> Githubで起こるイベントを取得したい人はRSSを利用したり、APIを叩いて個人的に情報を取ればそれで良いのでは

リアルタイムで受け取れるのは Webhook と GitHub アプリとメールしかないけど、メールの通知はたまに見逃したりするし、自分の場合はメールはPCでしかプッシュ通知が来る設定にしていないのでリアルタイム性に欠ける。とはいえ GitHub の自分に関係ない Issue/PR の通知までもを全部モバイルに送るのも邪魔だし、Discord は未読扱いになるのがアレでミュートしてるので、適当にTLに垂れ流れてるとスマホでTL見てる時にたまにメールをPCで読むより早く気づけることがあって便利

**Comment by mei23** [comment]
> @ repo の挙動が問題なのではないかしら

まあそうだし簡単に修正できるはずなのだわ
https://github.com/syuilo/misskey-github-notifier/pull/7

**Comment by acid-chicken** [comment]
(そもそも \@\repo ってメンテされてるの syuilo/misskey-github-notifier#1)

**Comment by tamaina** [comment]
@ repo@ miskey.ioは私たちがメンテできる状況であるとは言えない

…ので https://p1.a9z.dev/@repo を始めました

**Comment by mei23** [comment]
リポジトリの方はしゅいろが管理は出来るけど、ioのBOTを運用しているのは誰だったっけってレベルなのだわ。

**Comment by 4ioskd** [comment]
めいめい氏、対応ありがとうございます！＞https://github.com/misskey-dev/misskey/issues/8763#issuecomment-1141618544

>ioのBOTを運用しているのは誰だったっけってレベルなのだわ。

>@ repo@ miskey.ioは私たちがメンテできる状況であるとは言えない

...@ repo アカウントの管理者が誰か知ってる上でみなさん議論されてるのかとてっきり思ってましたし、それがちゃんとメンテされているかどうかを知らないまたはメンテできないおよびメンテできていない状態（この１、２ヶ月で複数回突然アカウントが停止したり再起動していますが）では、ioの@ repo アカウントは廃止された方が良い。
いずれにしても@ repo アカウント自体は廃止された方が良いという考えに変わりはなかったりはしますが。

>あちこちのよくわからんクローラーが日夜走りまくってる現状のインターネットでその程度のプライバシーを真に気にするのだったら全部ローカル&フォロワー限定投稿にするべき

情報をシェアしておきますと、この１年ぐらいに増えたmisskeyの海外ユーザーの中にはプライバシー等の思想信条に基づいてGithubの利用を嫌う、または利用したくないユーザーが一定数存在します。この結果、misskeyインスタンスやmisskeyのサードパーティークライアントのgitの置き場所をgitlabやGiteaやCodeberg等に置く傾向があり、misskeyのリポジトリがGithubにあるためにissueやプルリクエストが出されないという機会損失が発生しています（私がmisskeyでの問題についてissueやプルリクエストを出したら？と提案しても、無視されることは珍しくはなかったりします）。もちろん、継続的なコントリビューターになってくれたかもしれない人を失うということも発生しているかもしれません。よって、gitlabやGiteaのインスタンスを建ててGithubのコードをクローンさせて両方を同時に運用するか（例えばPeerTube,Lemmy,Plumeとか）、gitlabやGiteaやCodebergのどれかでのみ運用する（例えばPleromaやGnu social)、fediverseソフトウェアは多くありますね。

ちなみに私自身はGithubやgitlabやGiteaやCodebergのどれを利用するのも全然構いませんが。あと、@ repo アカウントは既にミュートしてますね。

**Comment by rinsuki** [comment]
それは GitHub にコメントなり何なり書き込む時の話で GitHub に自分の投稿のURLが貼られる話じゃないでしょう

**Comment by tamaina** [comment]
> ...@ repo アカウントの管理者が誰か知ってる

それが一回問題になったので今はわかっているけど、その名前を言ったところで誰も得をしないので出していないだけです。

<details>
<summary>
Off Topic
</summary>
<blockquote>
Githubの利用を嫌う
</blockquote>
GitHubについて危険だなんだ言う人と正直関わりたくないと思っているけど、私もPayPalアンチなので人のことを言えないかもしれない
</details>

**Comment by 4ioskd** [comment]
>それは GitHub にコメントなり何なり書き込む時の話で GitHub に自分の投稿のURLが貼られる話じゃないでしょう

私がシェアした内容の背景があるので、自分のノートのURLがGithubに貼られるのが嫌だという人もいますからね。元々の話としてはタイトル通りで「他人のノートのURLを無断で貼る行為の禁止」という人のモラル的な話ですから、この話はここまでにしたいところです。

**Comment by acid-chicken** [comment]
モラルがどうみたいな話をコントリビューションガイドにいちいち書くとキリがない。
モラル的に適切でないとメンバーが判断したか、あるいは通報を受けた際、メンバーはそれを適切に処理するだろうし、「それがモラルの話なら」その運用で十分でしょう。

ちなみに嫌だという話をすると、私は GitHub のことを Github と表記したテキストを見るのがかなり嫌です。
