### ISSUE TITLE
Simple refresh page when sw detects offline

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8765]
## Summary

Right now, when Misskey's offline, it just shows a single line message:

https://github.com/misskey-dev/misskey/blob/ebc2566130c785924380d504c76b270198bdc2c2/packages/sw/src/sw.ts#L29

If there's a way it could instead respond with a basic page like this, it'd be a lot more user friendly:

![image](https://user-images.githubusercontent.com/44733677/170900117-e19e4134-ef09-41a0-9a40-f0c4e1d0470d.png)

**Comment by Johann150** [comment]
I think it might also be nice to show the reason why the service worker thinks you are offline. Because currently any fetch error will cause the service worker to think you are offline.

Noticed this when I did not renew my TLS certificate on time and got the "Offline" screen.

**Comment by tamaina** [comment]
fetchは、サーバーが4xxや5xxを応答した時はresolveになります。fetchがreject(error)になるのは、(主としてユーザーの)回線に問題があるときです。これはofflineと言っていい状況です。

**Comment by YokaiRick** [comment]
@ThatOneCalculator dunno if i understand you correctly, but you actually can already set a warning page like you suggested:
<img src="https://user-images.githubusercontent.com/24204874/171509600-86ad6bad-fd38-432d-aaeb-d72d954dcaaf.png" height="200"/>
- - -
<img src="https://user-images.githubusercontent.com/24204874/171509337-a239705d-2dd1-4799-a209-1b51c45c35c7.png" height="500"/>

**Comment by Johann150** [comment]
That warning will only be shown when the web client detects that the server goes offline while you are already using the client. The service worker error shown above would be shown when the server is already offline when you navigate to the website and the service worker is already cached in your browser.
