### ISSUE TITLE
Email / password fields are not auto-completed correctly on Sign-up form

### ISSUE THREAD

**Issue by siketyan** [syuilo/Misskey#8795]
## 💡 Summary

Sign-up form has fields of email address and password (and their confirmation), which is not auto-completed from 1Password or other autofill correctly because value of `[autocomplete]` attribute is invalid.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/12772118/172537258-1a0d0af0-764f-4f01-b4b1-7e8087137094.png">

## 🥰 Expected Behavior

Value of `[autocomplete]` should be `new-password`, and should be auto-completed correctly from password managers.

## 🤬 Actual Behavior

Value of `[autocomplete]` is random decimal, and not auto-completed correctly. 

## 📝 Steps to Reproduce

1. Open the sign-up form.
2. See the DOM.

## 📌 Environment

https://misskey.io/

**Comment by syuilo** [comment]
Signing up creates a new account, so it was often inconvenient to have the email address and password of an existing account autocomplete.

**Comment by siketyan** [comment]
@syuilo 

Password fields in signing-up form should be marked as `[autocomplete="new-password"]`, then password managers can auto-complete them by generating a new password.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#:~:text=or%20account%20name.-,%22new%2Dpassword%22,-A%20new%20password

**Comment by siketyan** [comment]
Although `[autocomplete="(random decimal)"]` is invalid against the HTML specification or semantics, should be considered as a bug.

**Comment by syuilo** [comment]
This is not a bug as it is intended, but `new-password` should be used.
