### ISSUE TITLE
Regression: Frontend broken with QtWebEngine

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8810]
## 💡 Summary

The frontend app is broken with QtWebEngine. Used to work with Misskey 12.110.1.

## 🥰 Expected Behavior

The frontend app works with QtWebEngine.

## 🤬 Actual Behavior

ERROR CODE: APP_FETCH_FAILED
Details:
{}

No errors in devtools.

## 📝 Steps to Reproduce

1. Open Misskey in a browser that uses QtWebEngine (e.g. qutebrowser, Falkon, Konqueror…)

## 📌 Environment

Misskey version: 12.111.0
Your OS: openSUSE Tumbleweed 20220609
Your browser:
qutebrowser v2.5.0
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Comment by pixeldesu** [comment]
Probably (most likely) the same issue as #8603. I'll close this as a duplicate and reference the browsers in the other issue.

Thank you for reporting! ❤️

**Comment by Johann150** [comment]
Reopening since the duplicate issue has disappeared...

**Comment by ghost** [comment]
Original issue has been restored, closing. Please readd the duplicate tag.
