### ISSUE TITLE
Yarn install fails with `--force` flag

### ISSUE THREAD

**Issue by yitsushi** [syuilo/Misskey#8811]
## 💡 Summary

`yarn install` throws an error because it tries to use the `--force` flag and it's not there.

## 🥰 Expected Behavior

I can call `yarn install` without issues.

## 🤬 Actual Behavior

```
misskey@slippy:~/misskey$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
...
➤ YN0000: ┌ Link step
➤ YN0007: │ misskey@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ misskey@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-fc87e0a0/build.log)
➤ YN0000: └ Completed in 2s 976ms
➤ YN0000: Failed with errors in 33s 420ms
```

```
misskey@slippy:~/misskey$ cat /tmp/xfs-fc87e0a0/build.log
# This file contains the result of Yarn building a package (misskey@workspace:.)
# Script name: postinstall

installing dependencies of packages/backend ...
Unknown Syntax Error: Unsupported option name ("--force").

...
$ yarn unplug [-A,--all] [-R,--recursive] [--json] ...
/home/misskey/misskey/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: yarn --force install
    at makeError (/home/misskey/misskey/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/misskey/misskey/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/misskey/misskey/scripts/install-packages.js:6:2 {
  shortMessage: 'Command failed with exit code 1: yarn --force install',
  command: 'yarn --force install',
  escapedCommand: 'yarn --force install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
```
misskey@slippy:~/misskey$ yarn --version
3.2.1
```

## 📝 Steps to Reproduce

1. Checked out 12.111.0
2. `yarn install`

## 📌 Environment

Misskey version: Upgrade from 12.110.0 to 12.111.0
Your OS: Linux
Your browser: N/A

**Comment by rinsuki** [comment]
you should use yarn 1.x until #8764 gets merged

**Comment by yitsushi** [comment]
Hmm... it was not an issue until now.

**Comment by ghost** [comment]
same issue
edit: running yarn version v1.22.18

**Comment by rinsuki** [comment]
since your error is occurred by #8770's change, but anyway modern yarn (>=2.0) is not expected by misskey and may breaks with any time (but missing on english version of misskey-hub documents... may need to update?)

@smio102 I think it is different error; can you paste logs (for check to same error or not)?

**Comment by yitsushi** [comment]
It seems I'm blocked on that one for a while now :( I'm so sad about it. I couldn't find a good way to install / use yarn `1.x` as `yarn set version 1.x` just does not work.

It's annoying as I always have to check everything in the changelog if i have to bump up nodejs version again (and it's good, I have no issue with that), but yarn is still an outdated fossil.

So now I'm forced to upgrade Node.js to `v16.15.0` from `v16.14.2`, but I'm not allowed to use newer yarn versions than `v1.x`.

---
Update: I managed to install older version (only for the misskey user so other sites will not be broken)

**Comment by ghost** [comment]
@rinsuki My bad, it was a permission issue for me. I managed to install with `sudo`

**Comment by yitsushi** [comment]
With 1.x yarn, everything is working. I'm disappointed to be forced to downgrade, but at least it works.

**Comment by ThatOneCalculator** [comment]
I just removed `--force` from `install-packages.js` and that fixed the issue for me.
