### ISSUE TITLE
GenerateVideoThumbnail failed

### ISSUE THREAD

**Issue by tastytea** [syuilo/Misskey#8814]
## 💡 Summary

Video thumbnails are not generated since upgrading to 12.111.0. It worked with 12.110.1 after applying <https://github.com/misskey-dev/misskey/pull/8696>.

## 🥰 Expected Behavior

Video thumbnails are generated.

## 🤬 Actual Behavior

Video thumbnails are not generated. I get this in the log:

```
INFO 1  [drive register]        {"size":11388127,"md5":"ca3a79307344819607654b1ba7d6eb62","type":{"mime":"video/mp4","ext":"mp4"},"warnings":[]}
WARN 1  [drive register]        GenerateVideoThumbnail failed: Error: Unsupported input '498' of type number
DONE 1  [drive register]        drive file has been created 91dwpocd5l
```

This is the answer from the API:

```json
{
	"id": "91dwwbi765",
	"createdAt": "2022-06-11T20:46:15.103Z",
	"name": "file.mp4",
	"type": "video/mp4",
	"md5": "ca3a79307344819607654b1ba7d6eb62",
	"size": 11388127,
	"isSensitive": false,
	"blurhash": null,
	"properties": {},
	"url": "https://very.tastytea.de/files/de0cac52-e843-423c-aa7d-83c3a4e6a2e4",
	"thumbnailUrl": null,
	"comment": null,
	"folderId": null,
	"folder": null,
	"userId": null,
	"user": null
}
```

## 📝 Steps to Reproduce

1. Upload video
2. No thumbnail

## 📌 Environment

Misskey version: 12.111.0
Your OS: Gentoo Linux
Your browser: Firefox 91.10.0esr

**Comment by mei23** [comment]
ここ
https://github.com/misskey-dev/misskey/pull/8713/files/f065c125269987d4ddccc214cab0c74c7078cb2c#diff-da33e30f51eac1463b1efa7d624678e29bbd9bbe0b46b1c820dbc6f6b909082d

**Comment by tastytea** [comment]
The patch in #8820 fixed that error, but now i get “Input file contains unsupported image format”. I also tested it with a video/mp4. I'm pretty sure these videos created with SimpleScreenRecorder worked before, although i can't find proof at the moment. `ffmpeg -i test.mp4 -frames:v 1 thumbnail.jpeg` works with the file.

```
INFO 1  [drive register]        {"size":52443,"md5":"2bac934d1fb15522facb5ffb4691114c","type":{"mime":"video/webm","ext":"webm"},"warnings":[]}
WARN 1  [drive register]        GenerateVideoThumbnail failed: Error: Input file contains unsupported image format
DONE 1  [drive register]        drive file has been created 91f0ea0r35
```


test file: https://user-images.githubusercontent.com/3681516/173239960-1720cf37-abd5-48bb-b873-903192f49fbb.mp4

**Comment by mei23** [comment]
Perhaps temp filename must have a `.png` extension.

**Comment by tastytea** [comment]
Thanks, the patch in #8825 works for me. :sparkling_heart:
