### ISSUE TITLE
v12.111.0における通知周りのスロークエリ及びエラー

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#8816]
## 💡 Summary

このような感じになりバックエンドでCPU負荷がかかります
https://gist.github.com/ThinaticSystem/8f38b08893afa37a680eab5315b01158
https://gist.github.com/frfs/966898716e2ce1bd74a4000b08f86244

## 📝 Steps to Reproduce

謎

## 📌 Environment

Misskey version: 12.110.0
OS: Ubuntu 20.04.4 LTS x86_64
Postgresql: 14.3 
Node.js: 18.0.0

**Comment by ThinaticSystem** [comment]
https://mk.f72u.net/notes/91ehm4niiy
>しなちへ
> 多分通知を開くかLTLを開いたら重くなります
> ふるふるより #frfr

**Comment by tamaina** [comment]
もしかしてここが原因？（私が変えた覚えがあるだけ）

https://github.com/misskey-dev/misskey/blob/12.111.0/packages/backend/src/server/api/endpoints/notifications/read.ts#L37

**Comment by mei23** [comment]
ServiceWorkerのイベントで既読が出まくっていて最終的に `notifications/read` が Array で呼ばれているのでは？と
https://github.com/misskey-dev/misskey/blob/3a987b00063e69805ab7f3b75e86ac06ff0abdb1/packages/sw/src/sw.ts#L161
https://github.com/misskey-dev/misskey/blob/3a987b00063e69805ab7f3b75e86ac06ff0abdb1/packages/sw/src/sw.ts#L173

**Comment by tamaina** [comment]
いや、

> WARN 1        [api]        SLOW API CALL DETECTED: i/notifications (4849.911375001073ms)

なのでService Workerとかの周囲は関係ないかも

**Comment by mei23** [comment]
`i/notifications` は最大でも100しか出せないから違うかなって思ったのだわ

**Comment by tamaina** [comment]
Service Workerの既読処理キューを空にし忘れていたのが原因かも？

**Comment by mi-24v** [comment]
同様の問題が発生しましたがコントロールパネルでService Workerのpush通知を切って数時間放置してると負荷が消えました。緩和策になるかもです

`2022-06-12 05:38:51 +0900`にデプロイして設定を変えたのは多分1時間後ぐらいだったと思います
![負荷グラフ](https://media-miwkey.miwpayou0808.info/main-media/e8714e00-f955-4e0e-bfa9-4b74960ee554.png)

このとき`_notification.emptyPushNotificationMessage` (`en-US`で`Push notifications have been updated`、ja-JPで`プッシュ通知の更新をしました`)がブラウザ上で大量に出たり消えたりしてましたがいまはないっぽいです


## 📌 Environment
Misskey version: 12.110.0
OS:  Amazon Linux 2 x86_64 (ECS最適化AMI`ami-0beba7dd29d72a203`使用)
Postgresql: 12.8
Node.js: 18.0.0
Docker Image: [`miwpayou0808/misskey:140c64c2`](https://hub.docker.com/layers/misskey/miwpayou0808/misskey/140c64c2/images/sha256-842e198438dadd03e783cebbf1a085084bbaf67cc8a8be7700c50756906b84e2?context=repo)

**Comment by ThinaticSystem** [comment]
[honi.club](https://honi.club)でhttps://github.com/misskey-dev/misskey/pull/8819 動かしてみてます
よさそう

**Comment by ThinaticSystem** [comment]
> 


> [honi.club](https://honi.club)で#8819 動かしてみてます よさそう

やっぱり変化ないかも…

**Comment by mei23** [comment]
> Service Workerの既読処理キューを空にし忘れていたのが原因かも？

たぶんそれ、100個既読にしたら全部で5050個分飛ぶ。

**Comment by tamaina** [comment]
これなくなったかしら

**Comment by ThinaticSystem** [comment]
![image](https://user-images.githubusercontent.com/37925599/177778637-cedf3196-72d6-4168-8303-3206aa82694d.png)
なくなってないっぽい(@12.112.1)

**Comment by ThinaticSystem** [comment]
なおりました！
@mei23 ありがとうございます🙏
