### ISSUE TITLE
"Push notifications have been updated" message pops up every time Misskey is opened

### ISSUE THREAD

**Issue by normikoto** [syuilo/Misskey#8824]
## 💡 Summary

Whenever I open Misskey with notifications enabled, I get a "Push notifications have been updated" message every time.
This message seems to also pop up when I access Misskey from a different browser at the same time.

## 🥰 Expected Behavior

No notifications should show up unless there are unread ones.

## 🤬 Actual Behavior

A "Push notifications have been updated" notification appears when logging in.
No message appears in the browser Javascript console for me.

## 📝 Steps to Reproduce

1. Log into Misskey (or just open a new session if already logged in)
2. Notification "Push notifications have been updated" appears
3. (optional) Open Misskey in another browser, message will appear again

## 📌 Environment

Misskey version: 12.111.1
Your OS: Linux (Fedora 36)
Your browser: Google Chrome 102.0.5005.115 and Firefox 101.0

**Comment by Johann150** [comment]
not sure if this is related to #8819

**Comment by normikoto** [comment]
Yeah that got merged into 12.111.1 but I still get this

**Comment by mi-24v** [comment]
see #8816 
this might be cause high pressure at backend

**Comment by tamaina** [comment]
please translate

このメッセージはuser_visible_auto_notificationの出現を防止するためのメッセージです。  
このメッセージがサーバーに負荷をかけることはありません。

readについてのプッシュメッセージを受けて通知を取り下げた時にuser_visible_auto_notificationが出現するのを防ぐ為にあえてプッシュ通知を短い期間表示しています。

**Comment by tamaina** [comment]
より詳しく言うと、このメッセージはreadNotificationsやreadAllNotificationsなどが発行されるたびに表示されます。

Misskeyを開いたときに通知リストを表示するような画面構成になっている場合、i/notificationsの結果としてreadNotificationsかreadAllNotificationsが発行されます。

これがMisskeyを開くとそのメッセージが表示される原理です。

**Comment by tamaina** [comment]
これが不快な実装であることは私も共感しますが、user_visible_auto_notificationにまつわる制約がある限りはこの実装が最善であると思っています。

もしくは既読で通知を取り下げるのを諦めるかです。

**Comment by tamaina** [comment]
(ところで、なんとなく通知のcloseって機能してない気がするんだけど)

**Comment by nvisser** [comment]
私の場合も表示されるようです。デスクトップでウェブ版を開いてからSubwayTooterを開くと、https://borg.social/notes/91dipha6av のように、無限に `POST /api/i/notifications` を要求してくることに気づきました。

#8819 をマージして インストールしても、この問題は解決しません。(私はこのコミットを使用しています 3c67a5c7d89dd68c854b321bdf1d176e28010787)

もし、もっと詳しく知りたいということであれば、喜んでお教えします。

申し訳ございません、機械翻訳を使用しています

**Comment by tamaina** [comment]
> 無限に POST /api/i/notifications を要求してくる

I think it is SubwayTooter's bug.

**Comment by tamaina** [comment]
> (ところで、なんとなく通知のcloseって機能してない気がするんだけど)

いや、ちゃんと動いている

**Comment by tamaina** [comment]
SubwayTooter、たしかに通知を無限に送りまくってる…

![Screenshot_20220614-145224-830.png](https://user-images.githubusercontent.com/7973572/173503211-0a5d267f-9ead-4e31-9647-4a95e0fb7215.png)

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/173503350-8ef97479-15d0-49de-8a92-b344a49288b4.png)

わわわ

**Comment by rinsuki** [comment]
> もしくは既読で通知を取り下げるのを諦めるかです。

プッシュ通知なんかサーバー側の既読状態と同期されないがちなことが多い気がするしこのオプションあってもいいかもしれない

**Comment by tamaina** [comment]
SubwayTooterの問題は #8835 で

**Comment by ghost** [comment]
This pop up message will appear instead of the post, as it was done in the previous version, except direct messages.

DM works in notifications as usual.

**Comment by tamaina** [comment]
#8979 で直ったと思うのでclose（直ってなかったらreopenしてください）
