### ISSUE TITLE
ダークモードフラッシュが発生する

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#8829]
## 💡 Summary
12.111.0から、再読込時にダークモードフラッシュ（一瞬ライトモード）が発生する

## 🥰 Expected Behavior
ずっとダークモード

## 🤬 Actual Behavior
ダークモードフラッシュが発生する（一瞬ライトモードになる）

## 📝 Steps to Reproduce

1. 12.111.0以降にする
2. ダークモードにする
3. 再読み込み

## 📌 Environment

Misskey version: 12.111.1
Your OS: Android 12.1, Windows 10
Your browser: Chrome 102.0.5005.78, Chrome 102.0.5005.63

**Comment by Johann150** [comment]
maybe related to #8717?

**Comment by sim1222** [comment]
ごめんなさい、Misskey側の問題ではないかもしれません。
CloudflareのRocket Loaderを有効にしていると発生するようです
