### ISSUE TITLE
SubwayTooter requests i/notifications endlessly.

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8835]
Spin off from #8824 https://github.com/misskey-dev/misskey/issues/8824#issuecomment-1154349357

SubwayTooterがi/notificationsを無限に叩きまくるので、インスタンスの負荷がかなり高まる。

とりあえずAPI制限を強めるべき

**Comment by tamaina** [comment]
SubwayTooterにもissue書いた https://github.com/tateisu/SubwayTooter/issues/191

**Comment by syuilo** [comment]
10分間に100回までとか？

**Comment by tamaina** [comment]
1分間に10回までのほうがいい気がする
