### ISSUE TITLE
チャットを無効化する機能

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8839]
## Summary
- モデレーションが面倒だから無効化したいニーズがありそう
- そこまで需要がなさそう

**Comment by nexryai** [comment]
チャットでトラブルが起こり通報があってもチャットの中身を直接覗く方法がなく、正直に言って対応のしようがないので無効化できると助かります

**Comment by fu-sen** [comment]
賛成に 1 票入れます。本日無駄に `ああああああああああああああああああああ` と送られたチャットを受け取りました。そのために TL からチャットに切り替えないといけなくなったので。外でも Plerroma はチャットがあるのですが派生している akkoma はチャットをなくしています。

**Comment by tamaina** [comment]
個人的にチャット廃止派（ダイレクト投稿で代替可能なので）

> 本日無駄に ああああああああああああああああああああ と送られたチャットを受け取りました。

ダイレクト投稿もあるのでそういうイタズラとかは無くならなさそう

**Comment by nexryai** [comment]
これロール機能で設定できると柔軟性が上がるんじゃないかって思いました

**Comment by syuilo** [comment]
チャットは廃止して、ダイレクト投稿をチャット風に表示するUIを実装する方向で
