### ISSUE TITLE
oembed for peertube ?

### ISSUE THREAD

**Issue by fwn0** [syuilo/Misskey#8845]
Is it possible to embed some of peertube shared content ? I can not get this option to misskey; you can see in attachment, that for example yt, bitchute links are working, but peertube get me only the external link to video, other options for sharing in peertube does not working (iframe).

![misskey peerversum net](https://user-images.githubusercontent.com/35877841/174309285-1e98534f-bbaa-46d2-9c7e-ef982f26c879.jpg)

**Comment by mei23** [comment]
Summaly logic needs to be modified.

// @syuilo, @tamaina, Member アサイン私にしておいていいのだわ

**Comment by syuilo** [comment]
2.6.0をリリースした
