### ISSUE TITLE
Failed websockets connection

### ISSUE THREAD

**Issue by JohnnyEn** [syuilo/Misskey#8853]
## 💡 Summary

I'm experiencing right now failed websockets connection on my fresh built instance. 

## 🥰 Expected Behavior

0 red errors in the web dev console caused by websockets.

## 📝 Steps to Reproduce

1. Build docker image
2. Run on server

## 📌 Environment

Misskey version: v12.111.1
Your OS: Ubuntu 22.04 LTS
Your browser: Vivaldi 5.3.2679.38

**Comment by tamaina** [comment]
dockerだけで不具合が出ている気がする

**Comment by tamaina** [comment]
I don't use Docker much, so I can't say it's all Docker's fault, but I'll give you some general troubleshooting tips anyway: 

- Check your reverse proxy settings, such as nginx. how to use WebSockets with nginx: https://www.nginx.com/blog/websocket-nginx/
- Cloudflare Tunnel is said to make WebSockets unstable. https://community.cloudflare.com/t/cloudflared-tunnel-very-flakey-with-websockets/387565

**Comment by JohnnyEn** [comment]
Thank you so much!

It wasn't issue caused by Docker. I had misconfiguration in the Nginx config. I have remembered this has been issue with Mastodon too. 

```
server_name xxxxxx.xxxxx.dev; # managed by Certbot

    location / {
      try_files $uri @proxy;
    }

    location @proxy {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Proxy "";
        proxy_pass_header Server;

        proxy_pass http://127.0.0.1:3333;
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        tcp_nodelay on;
    }
```

Even this has been related with non responsive notifications, now everything looks to be working!

Have a nice day.

**Comment by tamaina** [comment]
There is nginx config sample for Misskey, I recommend to use it.

https://misskey-hub.net/en/docs/admin/nginx.html

Have a nice day.
