### ISSUE TITLE
"Unresolved reports" error showed as blank

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8859]
## 💡 Summary

There's just a blank error in the control panel, no console log.

## 🥰 Expected Behavior

No blank error

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/174878245-560d1a3a-55c2-442c-8102-cdb1bfcf10e6.png)

## 📝 Steps to Reproduce

1. Go to control panel

## 📌 Environment

Misskey version: e44cb42de41c5378910d9b9240b951629bf1720c
Your OS: Linux, Android
Your browser: Firefox, Bromite

**Comment by Johann150** [comment]
Probably related to commit 2d181ba5afcc141befde4bcbe540bdf106d79083, but it works correctly for me. If you are building from source you probably have to "clear cache" to reload the internationalization strings.

side note: "latest git" is not a version and "12.111-test.1" is not a tag I could find. Probably better idea to name the commit ID.

**Comment by ThatOneCalculator** [comment]
@Johann150 I cleared cache on my browser for stop.voring.me but the blank error is still there.

**Comment by Johann150** [comment]
Have you also tried clearing the cache in the Misskey settings?

**Comment by ThatOneCalculator** [comment]
Tried that too, still a blank error.

**Comment by Johann150** [comment]
I'm still positive that it works in local testing for me, albeit not translated from Japanese yet.
<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/20990607/174899735-5a6eb8eb-724a-4108-82ff-5f685f3c4050.png)
</details>

Maybe you have some other kind of caching that is also going on somewhere (e.g.: nginx caching, Cloudflare) that you might want to reset. The order of clearing the caches might be a factor too: Only after you have cleared the cache in Misskey settings will Misskey reload the locales URI.

**Comment by ThatOneCalculator** [comment]
I've tried every-which-way and I still can't get it to go away.

**Comment by ThatOneCalculator** [comment]
@Johann150 I've 

- Rebuilt Misskey from source
- Tried on multiple devices
- Cleared every cache imaginable

And it ***still*** won't go away.

**Comment by ThatOneCalculator** [comment]
After updating Misskey to the latest version, it finally changed into a real error.

![image](https://user-images.githubusercontent.com/44733677/175186859-e43ef5b1-0503-46ea-a7fc-df1eaac7feae.png)
