### ISSUE TITLE
Theme editor blank

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8861]
## 💡 Summary

Theme editor doesn't show.

![image](https://user-images.githubusercontent.com/44733677/174910453-61640ffe-cad5-48af-9fb4-7411aa274699.png)

## 📌 Environment

Misskey version: e44cb42de41c5378910d9b9240b951629bf1720c
Your OS: Linux
Your browser: Firefox

**Comment by Johann150** [comment]
I think its a regression from #8846. In development mode this is the console error I get in the client:

```
Uncaught (in promise) ReferenceError: onBeforeRouteLeave is not defined
    fe use-leave-guard.ts:9
    setup theme-editor.vue:126
    [more stack tracke lines from runtime-core.esm-bundler.js ...]
```

**Comment by Johann150** [comment]
```shellsession
$ git show 699f24f3dcdb156838eb70602885c0b2cdd02cbc -- packages/client/src/scripts/use-leave-guard.ts
commit 699f24f3dcdb156838eb70602885c0b2cdd02cbc
Author: syuilo <Syuilotan@yahoo.co.jp>
Date:   Mon Jun 20 17:38:49 2022 +0900

    refactor(client): Refine routing (#8846)

```
```diff
diff --git a/packages/client/src/scripts/use-leave-guard.ts b/packages/client/src/scripts/use-leave-guard.ts
index 33eea6b52..379a7e577 100644
--- a/packages/client/src/scripts/use-leave-guard.ts
+++ b/packages/client/src/scripts/use-leave-guard.ts
@@ -1,5 +1,4 @@
 import { inject, onUnmounted, Ref } from 'vue';
-import { onBeforeRouteLeave } from 'vue-router';
 import { i18n } from '@/i18n';
 import * as os from '@/os';
```

The import was removed, but the function call was not changed: https://github.com/misskey-dev/misskey/blob/d1e151172b8e7b41e443e4ce33e2ad710aa0de55/packages/client/src/scripts/use-leave-guard.ts#L20

**Comment by Johann150** [comment]
Noticed while testing that other things like e.g. logout are also broken...

**Comment by ThatOneCalculator** [comment]
@syuilo could you please take a look at this?
