### ISSUE TITLE
migrate to vite 3.0

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8865]
## Summary

(when 3.0 released)

https://main.vitejs.dev/guide/migration.html

**Comment by syuilo** [comment]
betaだけど実験的に使ってみようかしら
パフォーマンスかなり向上してそうだし

**Comment by ThatOneCalculator** [comment]
https://stop.voring.me is running Vite v3.0.0-beta.4 with no problems, and it's very fast.

**Comment by syuilo** [comment]
Wow
Was migration easy?

**Comment by ThatOneCalculator** [comment]
Super easy! I didn't have to change config files at all :relaxed:

**Comment by ThatOneCalculator** [comment]
I think this is a pretty good point for upgrading asap :smile: https://stop.voring.me/notes/921z8tsv9r

**Comment by syuilo** [comment]
done
