### ISSUE TITLE
notes/mentionsが異常に重い場合がある

### ISSUE THREAD

**Issue by frfs** [syuilo/Misskey#8868]
## 💡 Summary
notes/mentionsの読み込み時、DBアクセスでタイムアウトを食らうレベルのクエリが呼ばれる。
（全ユーザーではない模様。起きる原因はよくわからない。ただしこのAPI自体はもともとヘビーなクエリを叩いているっぽい？）
参考:
https://mk.f72u.net/notes/91taa64hzf
https://mk.f72u.net/notes/91ta6ixrwz

## 🥰 Expected Behavior
正常なレスポンスが返ってくる

## 🤬 Actual Behavior
タイムアウトする

## 📝 Steps to Reproduce

1. 当該APIを呼び出す

## 📌 Environment

Misskey version: 12.111.1
Your OS: Win11
Your browser: Chrome 103

**Comment by frfs** [comment]
検証が必要だけれど、大量のリプが付いてるノートがあると重たくなるかも

**Comment by Johann150** [comment]
Duplicate of #7632
