### ISSUE TITLE
niraxで/shareがエラーを吐く

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8876]
ルーター設定にクエリが設定されていないのが原因？

（niraxの仕様がまったくわかってないしなんかドキュメントないのかしら）

**Comment by syuilo** [comment]
ローカルだと再現しないわね
エラー出るURL知りたい

**Comment by tamaina** [comment]
https://p1.a9z.dev/share/?text=%24%5Bbounce+%F0%9F%92%AC%5D+Commented+on+%22nirax%E3%81%A7%2Fshare%E3%81%8C%E3%82%A8%E3%83%A9%E3%83%BC%E3%82%92%E5%90%90%E3%81%8F%22%3A+syuilo+%22%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%A0%E3%81%A8%E5%86%8D%E7%8F%BE%E3%81%97%E3%81%AA%E3%81%84%E3%82%8F%E3%81%AD%0D%0A%E3%82%A8%E3%83%A9%E3%83%BC%E5%87%BA%E3%82%8BURL%E7%9F%A5%E3%82%8A%E3%81%9F%E3%81%84%22%0Ahttps%3A%2F%2Fgithub.com%2Fmisskey-dev%2Fmisskey%2Fissues%2F8876%23issuecomment-1164566476&title=Misskey+GitHub+Notifier+%40p1.a9z.dev%E3%81%AE%E3%83%8E%E3%83%BC%E3%83%88&url=https%3A%2F%2Fp1.a9z.dev%2Fnotes%2F91ur40gugr

**Comment by tamaina** [comment]
なるほど単純なクエリだと確かにエラー出ないわね

**Comment by syuilo** [comment]
`share/?`じゃなくて`share?`だといけた

**Comment by tamaina** [comment]
あ、とりあえずmanifest変えればいいか

**Comment by tamaina** [comment]
https://web.dev/manifest-updates/#cr-desktop-trigger

アップデート条件が狭くて悲しい

**Comment by tamaina** [comment]
パス末尾に/があってもいい感じになるようにしたさがある

**Comment by syuilo** [comment]
直ったはず
