### ISSUE TITLE
Delete a note will couse timeline failed to load

### ISSUE THREAD

**Issue by CHN-beta** [syuilo/Misskey#8887]
## 💡 Summary

Sometimes if I send a note and then delete it, the timeline will fail to load around the note that is deleted.

## 🥰 Expected Behavior

The deleted note disappear, but other notes could be loaded.

## 🤬 Actual Behavior

The timeline will fail to load around the note that is deleted. That is, for example, if no new notes on the local instance are made after deleting the note, the local timeline will simply fail to load, showing a frustrated kanban musume; if I make enough posts after deleting this thread, the local timeline will load, but when scrolling down near the deleted post, it will fail to continue scrolling down.

The log said:

```
Jun 25 13:45:17 chn-nas yarn[1470279]: ERR  3        [api]        Internal error occurred in notes/local-timeline: Could not find any entity of type "Note" matching: {
Jun 25 13:45:17 chn-nas yarn[1470279]:     "id": "91t4vs4g1g"
Jun 25 13:45:17 chn-nas yarn[1470279]: }
```

## 📝 Steps to Reproduce

There seems no 100% step to reproduce. This may be caused by a poor internet connection or any other uncertainties.

Sorry that I have nearly zero knowledge about Node.js and PostgreSQL. I even could not find out how the backend could still remember the deleted note id `91t4vs4g1g`, but I searched the whole database with the string `91t4vs4g1g` using DBeaver and found nothing.

Note that I had an accidental power failure on my server several weeks ago. After that I have to export the full database and import it again to make Postgresql work, and manually deleted a few data to make misskey do not complain about "duplicate key" and so on.

## 📌 Environment

Misskey version: 12.111.1, but the problem also exists on old versions such as 12.110.0
Your OS: Gentoo Linux, both server and client
Your browser: Google Chrome 103.0.5060.53, but firefox have the same issue.
Node.js version: 18.3.0

**Comment by Johann150** [comment]
I can not reproduce this bug on either 12.111.1 or commit 5e95a1f7af841f10646133ad0cc155a2c5cea9fd.

**Comment by CHN-beta** [comment]
> I can not reproduce this bug on either 12.111.1 or commit [5e95a1f](https://github.com/misskey-dev/misskey/commit/5e95a1f7af841f10646133ad0cc155a2c5cea9fd).

I have tried to reproduce but failed on newly installed machines, but in my instance, this could be easily reproduced.

I decided to reinstall the instance.
