### ISSUE TITLE
HTMLメールが崩れる

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8888]
CSSはインラインで書かないと認識されないらしい

https://github.com/SLaks/Styliner 使うと良いらしいけどメンテされてない

**Comment by acid-chicken** [comment]
専用のライブラリ使わなくても、汎用的な SSR ライブラリにインラインスタイル出力可能な CSS-in-JS ライブラリを組み合わせて使えばいい気がする。

**Comment by acid-chicken** [comment]
or https://github.com/posthtml/posthtml-inline-css

**Comment by syuilo** [comment]
HTMLメールを良い感じにしてくれる方募集中

**Comment by acid-chicken** [comment]
やるかも（未定）

**Comment by syuilo** [comment]
🙏🏻🙏🏻🙏🏻

**Comment by Sayamame-beans** [comment]
from 14599
現状の様子
> ![image](https://github.com/user-attachments/assets/22cb8ff9-44d5-48de-b7f8-9e5acab52460)

**Comment by 1673beta** [comment]
想定してたのこんな感じのですか？(juiceというライブラリでインラインにしてみた)
![image](https://github.com/user-attachments/assets/b1bb6a0c-14c4-49da-9be7-8c0a9bd7ea5f)

**Comment by syuilo** [comment]
👍🏿
