### ISSUE TITLE
can not disable notifications for ended polls

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8890]
## 💡 Summary
There are notifications for ended polls, but unlike other notifications it is not possible to disable them.

## 🥰 Expected Behavior
Notification settings dialog has option to disable poll ended notification.

## 🤬 Actual Behavior
![image](https://user-images.githubusercontent.com/20990607/175767668-e876a2de-974d-4cfe-850d-eb8d69896dea.png)

## 📝 Steps to Reproduce

1. Go to: ⚙️ Settings > Basic settings > 🔔 Notifications > ⚙️ Notification settings
2. Option "Polls ending" is missing, even though the string exists in the locales.
    https://github.com/misskey-dev/misskey/blob/c67c0df76248ca23dd3ee2223da09b0f9bc9196c/locales/ja-JP.yml#L1696

## 📌 Environment

Misskey version: d5ef68336a18ca90c0885a00f55c7e599a745930

**Comment by Johann150** [comment]
Fix see https://github.com/misskey-dev/misskey.js/issues/45

**Comment by zyoshoka** [comment]
Seems to have been fixed in #12434.
