### ISSUE TITLE
Pull theme-color from nodeinfo instead of HTML/PWA config

### ISSUE THREAD

**Issue by FloatingGhost** [syuilo/Misskey#8897]
## 💡 Summary

Currently, `theme-colour`, used for the banner on posts, [is pulled from](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/services/fetch-instance-metadata.ts#L211):
- HTML meta tags on the `/` path
- A PWA-specific `manifest.json` property

These should be considered instance-internal paths and should not be used for federated information

## 🥰 Expected Behavior

Theme-color should have a fallback (or, priority?) in the nodeinfo - `metadata.nodeAccentColor`? (take your pick on the actual property)

**Comment by Johann150** [comment]
The `<meta name="theme-color" value="..." />` tag is [part of the HTML Living Standard](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color) and is set on most client paths. https://github.com/misskey-dev/misskey/blob/596a61ce186d9a633a93aea07059c3930767e8bf/packages/backend/src/server/web/views/base.pug#L26

Using nodeinfo metadata for things like this seems like a bad idea to me because unlike for example JSON-LD you can not uniquely define what the semantics of a property are supposed to be.

**Comment by FloatingGhost** [comment]
>The <meta name="theme-color" value="..." /> tag is [part of the HTML Living Standard](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color) and is set on most client paths.

this is true, but note that it says "clients", i don't think that remote servers should be relying on the frontend of other instances to provide identifying information; this will break if the instance does not provide a frontend or PWA

>unlike for example JSON-LD you can not uniquely define what the semantics of a property are supposed to be.

that's fine though - http://nodeinfo.diaspora.software/ns/schema/2.1

according to the schema, ` "description": "Free form key value pairs for software specific values. Clients should not rely on any specific key present.",`

it feels awfully fragile to rely on something a remote server only intends to be used for clients that attach directly to it

**Comment by Johann150** [comment]
The standard says "user agents" not "clients", and I don't think you specify what Misskey's "intent" is. :P

My issue is that using "free form key value pairs for software specific values" means the meaning is not well defined and I do not see how that is any less fragile. Would you not have to check the software name (and maybe also version) to find out what the intended meaning of a field is supposed to be? And keep a list of other softwares?

**Comment by FloatingGhost** [comment]
and misskey isn't a user agent, is my point, instance information pulls aren't user-initiated

if you want information about remote instances, you should ask it, instead of scraping from its client - it'd be a bit silly for me to pull the `<title>` property to get info that can be given by `nodeName`

otherwise you force other frontend implementations (not backend AP implementations) to add compatibility with your way of doing things, which is a bit bizarre
