### ISSUE TITLE
作ったWebhookの詳細が見れない

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#8908]
## 💡 Summary

作ったWebhookの詳細が見れない

## 🥰 Expected Behavior

見れる

## 🤬 Actual Behavior

見れない
400エラーが返ってくる
一覧から選んだときに`webhookId`が指定されてないのが原因

（下は別問題？ウィンドウ関連のバグ　必要なら別issue立てます）
また、エラーが起きた後戻るボタンを押して戻り、再度Webhookを見ようとするとそのままスタックしてウィンドウが閉じれなくなる
↓のエラーが出てる
![image](https://user-images.githubusercontent.com/28654659/176485739-aa8a9b92-6f97-42b0-9a4a-768cd9684eec.png)

## 📝 Steps to Reproduce

1.Webhookを作る
2.詳細を見ようとする
3.見れない

## 📌 Environment

Misskey version: 12.110.1
Your OS: Windows 10 Home 21H2
Your browser: Vivaldi 5.3.2679.61 (Stable channel) (64-bit)

**Comment by Johann150** [comment]
Duplicate of #8817
