### ISSUE TITLE
TLの本文が消失する

### ISSUE THREAD

**Issue by ikuradon** [syuilo/Misskey#8914]
## 🥰 Expected Behavior
TLが正しく表示される

## 🤬 Actual Behavior
![vivaldi_cbqJkeIgo8](https://user-images.githubusercontent.com/713033/176803834-7c87f23e-535e-4eae-b91b-ef5fb741e56b.png)

## 📝 Steps to Reproduce

1. `66b27bdc9765088468c216ff98015e1fadf77732`にアップデートする
2. Dockerイメージを作り、デプロイする
3. 受信したTLを見る

## 📌 Environment

Misskey version: 66b27bdc9765088468c216ff98015e1fadf77732
Your OS:
Your browser:

**Comment by ikuradon** [comment]
`30aa1dcdcd3f16eaaad0d41634390098f26c75a0`まで戻したら直ったので、それ以降で壊れた可能性があるのかも

**Comment by ThatOneCalculator** [comment]
I'm getting this issue too. @syuilo this should be considered high-priority/breaking.

**Comment by syuilo** [comment]
parse5をメジャーアップデートしたのが原因だわね

**Comment by ThatOneCalculator** [comment]
It seems to happen whenever a non english-alphabetic letter is the first letter of a note.

**Comment by ThatOneCalculator** [comment]
Never mind, that seems to have been a false assumption. It's seemingly random... :(

**Comment by mei23** [comment]
> parse5をメジャーアップデートしたのが原因だわね

あーテストコケてるのこのせいなんだわね
https://github.com/misskey-dev/misskey/runs/7134543792?check_suite_focus=true#step:9:394

**Comment by ThatOneCalculator** [comment]
Seems like backend's package.json is now broken, as `yarn install` fails with this error

```
# This file contains the result of Yarn building a package (misskey@workspace:.)
# Script name: postinstall

installing dependencies of packages/backend ...
Usage Error: Invalid package.json in package.json

$ yarn ...
/home/misskey/misskey-new/node_modules/execa/lib/error.js:60
		error = new Error(message);
		       ^

Error: Command failed with exit code 1: yarn install
    at makeError (/home/misskey/misskey-new/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/misskey/misskey-new/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/misskey/misskey-new/scripts/install-packages.js:6:2 {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  escapedCommand: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.4.0
```
