### ISSUE TITLE
migrate parse5 to 7.0.0

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8915]
## Summary

チャレンジしたけど上手くいかなかった

**Comment by mei23** [comment]
me too

**Comment by ThatOneCalculator** [comment]
They put this link in the release notes for v7: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by mei23** [comment]
ESMまわりは大丈夫

defaultTreeAdapter と parse5-htmlparser2-tree-adapter はもともと別物だと思うから、そっちに変えるのはたぶん間違い。
https://github.com/misskey-dev/misskey/commit/e3bf53ea84427a57dfb21fb5ff3d2ed05c42e971#diff-c8d0b46f9c437538a3c1b48932dfbea3b13965e0066e186dfff77c9ead419ff4

そのまま defaultTreeAdapter を使うだけでいいはずだけど、type とか export されてなくて、んーってなる。
https://github.com/inikulin/parse5/issues/555
