### ISSUE TITLE
Sort polls in Explore tab newest to oldest

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8922]
## Summary

Right now polls in the Explore tab are sorted oldest to newest, but I think it'd be better if it was the other way around @syuilo 

![Screenshot_20220701-105019.png](https://user-images.githubusercontent.com/44733677/176945764-87edda9d-a783-4366-998c-a8cc807ad9d2.png)

**Comment by futchitwo** [comment]
fixed at https://github.com/misskey-dev/misskey/commit/52a1ec9af12cbd89cf4d3d585b38a9f11894a793
