### ISSUE TITLE
Add back groups

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8923]
## Summary

It was great being able to have group chats, now even though the "Start a new chat" button says Private chat or Group chat, you can't make new group chats.

**Comment by ThatOneCalculator** [comment]
@syuilo Please consider bringing groups back... I have to add a new moderator to the group chat but I can't now because groups are gone 😢

**Comment by 4ioskd** [comment]
Why Groups is suddenly omitted?? I know that current Misskey v12 is a huge software. and it needs reduce some main functions though...

**Comment by ThatOneCalculator** [comment]
I understand that it's large, but removing groups has been detrimental for many users :(

**Comment by tamaina** [comment]
> グループメンテニャンス出来にゃかったからUI上から消した

https://p1.a9z.dev/notes/92g6i2ptcb

**Comment by ThatOneCalculator** [comment]
On top of this, Akkoma is *adding* federated groups. I think if Misskey made brought back groups and made them Akkoma compatible that would be a step in the right direction. https://meta.akkoma.dev/t/groups-what-do-people-want-from-them/16

**Comment by SeqSEE** [comment]
It is possible to still create groups from the API endpoint `users/groups/create` with `{ name: 'somename'}` for parameters.

Is this something that's considered safe to do? Is there a plan to remove the API endpoint also?

**Comment by kordaris** [comment]
Hello! One of the main reasons we chose Misskey was the feature of chat groups. We have our instance under development right now. @syuilo Is there any reason why the Groups were disabled? Is there any plan of bringing them back? Or at least, as @SeqSEE mentioned, can we use the API endpoint with a custom implementation or is there a plan to remove it? Thank you!

**Comment by ThatOneCalculator** [comment]
[My fork](https://codeberg.org/thatonecalculator/calckey) has the groups UI added back!

**Comment by mackiexx** [comment]
Group chats are really interesting and i must say it was one of the features that attracted me to misskey

**Comment by kordaris** [comment]
@mackiexx I strongly suggest to check [Calckey](https://codeberg.org/thatonecalculator/calckey) (it's @ThatOneCalculator 's misskey fork), it has the Groups chat feature added back and other improvements compared to misskey. You can migrate easily from misskey. We used it for our instance and we didn't regret it. Groups are functioning again properly.

**Comment by mackiexx** [comment]
> @mackiexx I strongly suggest to check [Calckey](https://codeberg.org/thatonecalculator/calckey) (it's @ThatOneCalculator 's misskey fork), it has the Groups chat feature added back and other improvements compared to misskey. You can migrate easily from misskey. We used it for our instance and we didn't regret it. Groups are functioning again properly.

How can i migrate? cause i have already installed misskey

**Comment by kordaris** [comment]
> > @mackiexx I strongly suggest to check [Calckey](https://codeberg.org/thatonecalculator/calckey) (it's @ThatOneCalculator 's misskey fork), it has the Groups chat feature added back and other improvements compared to misskey. You can migrate easily from misskey. We used it for our instance and we didn't regret it. Groups are functioning again properly.
> 
> How can i migrate? cause i have already installed misskey

Check the readme file here: https://codeberg.org/thatonecalculator/calckey#migrating-from-misskey-to-calckey

**Comment by mackiexx** [comment]
> https://codeberg.org/thatonecalculator/calckey#migrating-from-misskey-to-calckey

Does it have all the features that misskey has? none was omitted?

**Comment by kordaris** [comment]
> Does it have all the features that misskey has? none was omitted?

Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.

**Comment by mackiexx** [comment]
> > Does it have all the features that misskey has? none was omitted?
> 
> Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.

I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?

**Comment by kordaris** [comment]
> > > Does it have all the features that misskey has? none was omitted?
> > 
> > 
> > Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.
> 
> I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?

No, the Groups in Misskey/Calckey are a way to create private group chats. Channels are a bit more similar to facebook groups, there you can join and post notes under a category (channel).

**Comment by mackiexx** [comment]
> > > > Does it have all the features that misskey has? none was omitted?
> > > 
> > > 
> > > Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.
> > 
> > 
> > I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?
> 
> No, the Groups in Misskey/Calckey are a way to create private group chats. Channels are a bit more similar to facebook groups, there you can join and post notes under a category (channel).

That's great. I will definitely migrate and check it out. i like the UI. i noticed iphone doesn't have the pull to refresh. On misskey, after i have left my pwa app for awhile, when i come back and write a post, it doesn't update immediately. i don't know if it is same with calckey

**Comment by mackiexx** [comment]
> > > > Does it have all the features that misskey has? none was omitted?
> > > 
> > > 
> > > Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.
> > 
> > 
> > I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?
> 
> No, the Groups in Misskey/Calckey are a way to create private group chats. Channels are a bit more similar to facebook groups, there you can join and post notes under a category (channel).

ALso if i make some css changes, do i need to use "sudo bash update.sh" to rebuild so it updates or how does it work with calckey? How do i make sure my css updates after i change them? i used shell to installed misskey

**Comment by mackiexx** [comment]
> > > > Does it have all the features that misskey has? none was omitted?
> > > 
> > > 
> > > Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.
> > 
> > 
> > I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?
> 
> No, the Groups in Misskey/Calckey are a way to create private group chats. Channels are a bit more similar to facebook groups, there you can join and post notes under a category (channel).

I have followed the instruction to migrate. Misskey is still showing on my website. i have also updated my nginx file to point to calckey, i don't know what. i am doing wrong

**Comment by ThatOneCalculator** [comment]
For calckey support, move the ticket to calckey's repo :)

**Comment by mackiexx** [comment]
> For calckey support, move the ticket to calckey's repo :)

I have already commented in https://codeberg.org/thatonecalculator/calckey/issues/9052

**Comment by mackiexx** [comment]
> > > > Does it have all the features that misskey has? none was omitted?
> > > 
> > > 
> > > Yes, I didn't find anything missing, only improvements. But you can install it and migrate, check it yourself and revert back to misskey easily if for some reason it doesn't fit you.
> > 
> > 
> > I just checked it out, it seems that the group is different. I am confused on how it works, especially how to create post in it. Doesn't it work like facebook groups where you can chat and search for groups to join?
> 
> No, the Groups in Misskey/Calckey are a way to create private group chats. Channels are a bit more similar to facebook groups, there you can join and post notes under a category (channel).

i Finally checked out calckey, however, there are some bugs that i noticed which aren't in misskey and i am thinking of migrating back to misskey.

1. pinned users doesn't show in explore.
2. the highlight in explore doesn't change with button active.
3. posts i made doesn't show in explore page. only one post shows.
4. Since only one post shows in explore, on the signup page, post aren't displayed

Does these work in yours?

i have commented the issue but no response yet. I like the Ui Design of calckey but i am thinking of migrating back to misskey as this is delaying my website launch

**Comment by ThatOneCalculator** [comment]
Those are all bugs on dev. I told you to switch to the main branch if you don't want pre-release software with bugs 😐

**Comment by mackiexx** [comment]
> Those are all bugs on dev. I told you to switch to the main branch if you don't want pre-release software with bugs 😐

I don't know how to switch to the main branch. i followed the instructions on the docs. How do i switch to main branch?

**Comment by ThatOneCalculator** [comment]
In the future, please keep calckey issues on the Calckey repo. 

Since you previously built on dev, the main build is going to have a lower build number. 

1. `git checkout main`
2. Edit the version `package.json` with a `-1` on the end, or something similar to make it unique
3. `NODE_ENV=production yarn run build`
4. Restart

**Comment by mackiexx** [comment]
> In the future, please keep calckey issues on the Calckey repo.
> 
> Since you previously built on dev, the main build is going to have a lower build number.
> 
> 1. `git checkout main`
> 2. Edit the version `package.json` with a `-1` on the end, or something similar to make it unique
> 3. `NODE_ENV=production yarn run build`
> 4. Restart

It takes time for you to reply on the Calckey repo. That's why i am asking here and maybe someone might know. it is over 3 days and i am unable to set up my site cause of the issues. Now i am facing a new issue https://codeberg.org/thatonecalculator/calckey/issues/9061
