### ISSUE TITLE
regression: loading more chat messages has wrong direction

### ISSUE THREAD

**Issue by Johann150** [syuilo/Misskey#8924]
## 💡 Summary
When I go to a chat with a lot of messages there is a "Load more" button at the top. When I click it, it loads the same messages that are already shown, but in reverse order. The previous messages are not shown.

## 🥰 Expected Behavior
"Load more" loads earlier chat history.

## 🤬 Actual Behavior
"Load more" loads later messages, but in reverse order, and adds them to the top of the chat.

## 📝 Steps to Reproduce

1. Go to chat with many messages.
2. Click button to load more messages.

## 📌 Environment

Misskey version: 01d5a97a4fab5f311f977b897e779a1393c1cd05

**Comment by ThatOneCalculator** [comment]
Chat is pretty broken rn, #8857 exists too and might be related?

**Comment by ThatOneCalculator** [comment]
Also there seems to be quite a few things loading in reverse order, such as polls under featured. Maybe a dep update changed some behavior?

**Comment by Johann150** [comment]
Maybe a bug with the pagination code? But both client and backend side of pagination code have not been edited recently.

**Comment by ThatOneCalculator** [comment]
![](https://cdn.discordapp.com/attachments/895293596662648838/992542048957767700/caption.gif)

**Comment by syuilo** [comment]
maybe this? https://github.com/misskey-dev/misskey/pull/8850
