### ISSUE TITLE
Import emoji sets used in notes from remote instance automatically

### ISSUE THREAD

**Issue by gerardkieffer** [syuilo/Misskey#8928]
##Summary

When fetching a note from a remote instance, emoji sets used in this post should be automatically downloaded. Not in a way that installs them permanently on the local instance (because that's the admin's choice), but rather in a similar way that attachments or photos from the note are downloaded and cached.
This would allow notes to display correctly even when an emoji set is not installed on the local instance.

Now... maybe this is a feature that should be added to the ActivityPub protocol and not to misskey? I'm not sure at which level this could be implemented, that's above my tech level.

**Comment by ThatOneCalculator** [comment]
"Emoji sets" can't really federate afaik.

**Comment by Johann150** [comment]
I do not quite understand what you mean with this. First of all it is not clear to me what you mean by "emoji set". Secondly custom emojis do not need to be "installed" on the local instance for you to be able to see them.

Currently, requests for the image file of a custom emoji are proxied through Misskey, so you can set up the reverse proxy to do caching as you wish.

**Comment by ThatOneCalculator** [comment]
OP could either be referring to

- The entire catalogue of emojis on a singular instance
- A feature that some Pleroma instances have that split emojis into packs (which don't federate)

Either way I think this issue should be closed as not planned.

**Comment by gerardkieffer** [comment]
> "Emoji sets" can't really federate afaik

> Either way I think this issue should be closed as not planned.

okay. thanks.
