### ISSUE TITLE
Clicking a hashtag in a bio or explore redirects to `/explore`

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8953]
## 💡 Summary

- Clicking a hashtag in a bio redirects to `/explore`
- Clicking a hashtag in the remote section of explore takes me to `/explore`

## 🥰 Expected Behavior

Clicking the hashtag takes me to other people with the hashtag

## 🤬 Actual Behavior

It takes me to `/explore`

Seems like `https://instance.tld/explore/tags/test` doesn't behave properly since the explore page rewrite.

## 📌 Environment

Misskey version: 7775eb964159c0bf808462c405779029e28dc6f5
Your OS: Linux
Your browser: Firefox

**Comment by mappi-pr** [comment]
@syuilo 
resolved? https://github.com/misskey-dev/misskey/commit/f0cb587c8906cf20d9e04ac6550914510aacc142
