### ISSUE TITLE
アンテナが見れない

### ISSUE THREAD

**Issue by frfs** [syuilo/Misskey#8960]
## 💡 Summary
アンテナを開こうとすると、アンテナの管理の方に飛ばされてアンテナが表示できない

## 🥰 Expected Behavior
アンテナが表示できる

## 🤬 Actual Behavior
アンテナの管理画面が出る

![Animation](https://user-images.githubusercontent.com/8694755/177779066-c04d597e-5cb3-4f25-9fb3-279039813c3f.gif)

## 📝 Steps to Reproduce

1.左メニュー「…」
2.アンテナを押す
3.「アンテナの管理」モーダルが開くことを確認する

## 📌 Environment

Misskey version:12.112.1
Your OS:Win11
Your browser:Chrome 103.0.5060.114

**Comment by syuilo** [comment]
これは仕様
タイムラインの上に並んでるアイコンから見れる

**Comment by frfs** [comment]
Release NoteのChangesから読み取れないのは問題かも
