### ISSUE TITLE
APIを直接叩くと虚無投稿ができる

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey#8971]
WebUIは封じられているがサーバー側で塞いでいない
![image](https://user-images.githubusercontent.com/6533808/178078665-a4edb445-546c-4067-86b9-52027a5f2043.png)

**Comment by sh1ma** [comment]
#8747 と一緒のやつかな？解決済みっぽいです

**Comment by rinsuki** [comment]
解決されてそう
