### ISSUE TITLE
デッキUIの時に、Misskeyの外で踏んだノートへのリンクが表示されない

### ISSUE THREAD

**Issue by na2na-p** [syuilo/Misskey#8972]
## 💡 Summary

タイトルの通り。

https://user-images.githubusercontent.com/49822810/178083931-92dfef53-5e53-4eeb-af93-d13e7f2bec6a.mp4

## 🥰 Expected Behavior

何らかの形で対象のノートが表示される

## 🤬 Actual Behavior

対象のノートが表示されない。  
動画ではWindowsTerminalですが、Discordに貼ったノートURLを踏んでも再現してます。

## 📝 Steps to Reproduce

1. デッキUIにする
2. 外部に貼られた、ノートへのリンクURLをクリックする)
3. ノートが表示されない

## 📌 Environment

Misskey version: 12.112.1
Your OS: Windows11(21H2)
Your browser: Vivaldi (5.3.2679.68 (Stable channel) (64-bit) )

**Comment by futchitwo** [comment]
メインカラムを表示していないことが原因かと思われます。

**Comment by yszkst** [comment]
メインカラムの存在に関わらずデッキの時はウインドウで出して欲しい気がしました。

**Comment by na2na-p** [comment]
改めて気になったのですが、「メインカラム」という名前のカラムはどのような役割を持っているのでしょうか？そこがわかりづらい原因の一つになっている気がします

**Comment by na2na-p** [comment]
が、ここのIssueは解決していてCloseしていませんでした。すみません。Closeします
