### ISSUE TITLE
Add Vietnamese to language selection

### ISSUE THREAD

**Issue by honhatduy** [syuilo/Misskey#8975]
## Add Vietnamese to language selection
The translation of [Vietnamese](https://crowdin.com/project/misskey/vi) is done 100%. Please include it into UI. Thank you

**Comment by robflop** [comment]
@syuilo このIssueをみてください。Crowdinで連絡されたのでGitHubのIssueを開けるがいいと言った。

**Comment by syuilo** [comment]
Arigathanks gozaimuch
