### ISSUE TITLE
リモートユーザーをブロックしようとするとエラーが発生する。

### ISSUE THREAD

**Issue by na2204** [syuilo/Misskey#8976]
## 💡 Summary
任意のリモートユーザーをブロックしようとするとエラーが発生します。  
(*ローカルユーザーの場合は発生しません。)  
  
![gif](https://user-images.githubusercontent.com/78205092/178104642-d4a0c07c-e172-4381-9299-2f31b090f42f.gif)

## 🥰 Expected Behavior

リモートユーザーをブロックしてもエラーが出ない。  

## 🤬 Actual Behavior

リモートユーザーをブロックしようとするとエラーがでる。 

`コンソールログ` 
![2022-07-09_21h07_10](https://user-images.githubusercontent.com/78205092/178104981-358d15c8-02d4-4765-b23e-31b2f5b6ecc0.png)

## 📝 Steps to Reproduce

1. リモートユーザーのプロフィールを開く
2. ブロックする
3. エラーが発生する*
  
*ポップアップに出てきたエラー
```
>> 最初に押したとき
Internal error occurred. Please contact us if the error persists.
5d37dbcb-891e-41ca-a3d6-e690c97775ac

>> それ以降
You are not blocking that user.
291b2efa-60c6-45c0-9f6a-045c8f9b02cd

>> これが出る場合もある
You are already blocking that user.
787fed64-acb9-464a-82eb-afbd745b9614
```

## 📌 Environment

Misskey version: 12.112.3  
OS: Windows10(21H2) & iOS15.5(iPhone)  
Browser: Brave & Safari  

## ちなみに
(どこに該当するのかわからないので新たな見出しを...)  
エラーが発生したとは出るものの、操作を行った後にページを更新して確認してみると‘ブロック解除`に表示が変わっていて、フォローボタンは押せなくなっています。相手側のアカウントでもフォローが解除されています。なのでブロック自体はきちんと行われている気がします。  
(これは仕様かもしれませんが)ブロックした相手からのDMは通常通り受け取れます。

**Comment by syuilo** [comment]
謎
