### ISSUE TITLE
Streaming repeatedly stops and moves

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8988]
ストリーミングが止まったり動いたりを繰り返す

#Streaming #WebSocket

## 💡 Summary
エラーを吐くわけではない模様

misskey.ioでも発生？

https://misskey.io/notes/92mgt5z62q

## 🥰 Expected Behavior
タイムラインなどストリーミングが止まらない

## 🤬 Actual Behavior
タイムラインなどストリーミングが止まる

## 📝 Steps to Reproduce

1. タイムラインをぼーっと眺める
2. 突然ストリーミングが止まる
3. 数分経過するとまた動き出す

## 📌 Environment

Misskey version: ~ 12.113.0-beta.2
Your browser: Edge
Instances: misskey.io, p1.a9z.dev

### p1.a9z.dev Environment
Misskey 12.113.0-beta2p1.1  
Node.js v18.4.0  
PostgreSQL 13.7 (Ubuntu 13.7-1.pgdg20.04+1)  
Redis 6.0.6  
Vue 3.2.37  
nginx 1.22.0

Using Cloudflare

**Comment by syuilo** [comment]
謎

**Comment by tamaina** [comment]
回線(docomo)のせいかなとちょっと思った

**Comment by tamaina** [comment]
今は大丈夫
