### ISSUE TITLE
[Invalid] Cannot mention certain username(s)

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8989]
## 💡 Summary

![image](https://user-images.githubusercontent.com/44733677/178660729-764e6dc6-727c-46f2-aaa1-c948cae77ddd.png)

## 🥰 Expected Behavior

I can mention `@naln1`

## 📌 Environment

Misskey version: 4550a4459bb9fc021211e438d135d464c018ce47
Your OS: Linux
Your browser: Firefox

**Comment by ThatOneCalculator** [comment]
cc @syuilo

**Comment by syuilo** [comment]
cc @marihachi

**Comment by ThatOneCalculator** [comment]
Never mind, it was a de-nyaify plugin that I installed which was causing the issue. This shouldn't be a problem in regular Misskey, apologies for hastily opening this issue.
