### ISSUE TITLE
ℹ️ button looks strange on ad

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8994]
## 💡 Summary

The ℹ️ button on ads looks like it's cutting off part of the ad

## 🥰 Expected Behavior

ℹ️ doesn't interfere with ad, or at least make square cutout

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/178853469-c201d62a-b792-4c3f-9c85-3fa64244f158.png)

## 📌 Environment

Misskey version: 12.113.0
Your OS: Linux
Your browser: Firefox

**Comment by KormiMeiko** [comment]
I think this ℹ️ icon should not be displayed by default, and if the user slides the mouse into the range of the ad, it will be displayed. Then ℹ️ the background of the icon should be transparent, it would be better.
