### ISSUE TITLE
クライアントが永久に読み込めなくなることがある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8998]
## 🤬 Actual Behavior

![22FF3E6C-4553-446D-AFCF-DA430149536C](https://user-images.githubusercontent.com/4439005/178968434-4e3551cf-7676-4a63-80d6-592c7834427a.jpeg)

## 📝 Steps to Reproduce

1. 不明
2.
3.

## 📌 Environment

Misskey version: 12.113.0
Your OS: iOS 16
Your browser: Chrome

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
es2017対応revertした状態だとエラー変化した
![60098B08-DE92-4888-81D2-D6E88C71DE18](https://user-images.githubusercontent.com/4439005/178980659-71d990a7-1855-459c-ba2c-2945139fe63b.jpeg)

バージョン情報のlogまで処理が到達していることも考えると、init.ts内の処理でエラー発生している可能性が高いと思われる

**Comment by syuilo** [comment]
なぜかブラウザのリロードボタンではなくて画面上のrefreshボタンを押してリロードした直後だけはエラー出ない

**Comment by syuilo** [comment]
ログアウトした状態でもエラー出る

**Comment by syuilo** [comment]
ブラウザのdisableCacheモードをオンにしている状態だとエラー出ない

**Comment by tamaina** [comment]
Service Workerのonfetchが悪さしているかもしれない気がする

（とりあえずskipWaitingを削除してみたけど変わらなかった）

**Comment by syuilo** [comment]
![00896A57-8519-47CF-B66F-A1503638072A](https://user-images.githubusercontent.com/4439005/178983713-0cea1df0-0792-4148-a0d0-42b2391632f0.jpeg)

**Comment by syuilo** [comment]
``` ts
// https://github.com/misskey-dev/misskey/pull/8575#issuecomment-1114239210
// なぜかinit.tsの内容が2回実行されることがあるため、mountするdivを1つに制限する
const rootEl = (() => {
	const MISSKEY_MOUNT_DIV_ID = 'misskey_app';

	const currentEl = document.getElementById(MISSKEY_MOUNT_DIV_ID);

	if (currentEl) {
		console.warn('multiple import detected');
		return currentEl;
	}

	const rootEl = document.createElement('div');
	rootEl.id = MISSKEY_MOUNT_DIV_ID;
	document.body.appendChild(rootEl);
	return rootEl;
})();
```

でエラー起きてるっぽい

**Comment by syuilo** [comment]
``` ts
document.body.appendChild(rootEl);
```
でエラー起きてるっぽい

**Comment by tamaina** [comment]
まさか: DOMContentLoaded

**Comment by syuilo** [comment]
これ以降エラー出なくなったかも
https://github.com/misskey-dev/misskey/commit/f2e91f4d629cd40c8f956cca2d30058048192dfd

**Comment by syuilo** [comment]
DOMContentLoadedが永久に発火しない時がありそう(タイミングによっては既にDOMが構築された後にbootが走ることがある？)

**Comment by syuilo** [comment]
https://stackoverflow.com/questions/39993676/code-inside-domcontentloaded-event-not-working

**Comment by syuilo** [comment]
解決
