### ISSUE TITLE
Notifications have trouble loading when multiple tabs are open

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#9002]
## 💡 Summary

Notifications are often glitchy/don't load on desktop

## 🥰 Expected Behavior

Notifications are normal

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/179167691-c2caacf2-3d4b-43fb-934e-38387a60f959.png)

## 📝 Steps to reproduce

- Load multiple tabs of Misskey
- Open notifications

## 📌 Environment

Misskey version: 12.114.0-beta.6
Your OS: Linux
Your browser: Firefox

Note: this does NOT seem to occur on Android.

**Comment by syuilo** [comment]
It is a rate limit.

**Comment by ThatOneCalculator** [comment]
> It is a rate limit.

The rate limit seems to come way too fast. This never happened before...

**Comment by syuilo** [comment]
This is due to performance reasons.

**Comment by ThatOneCalculator** [comment]
Is there a way I can disable ratelimiting?

**Comment by KisaragiEffective** [comment]
IIRC you can make a new role, assign lenient ratelimiter, and assign the role onto you.
Please let us know if that is not applicable.

**Comment by ThatOneCalculator** [comment]
This issue was filed before roles were introduced fwiw
