### ISSUE TITLE
`/api-doc` is broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#9003]
## 💡 Summary

Visiting https://stop.voring.me/api-doc shows a blank page until force-reloaded

## 🥰 Expected Behavior

API Docs show on first load

## 🤬 Actual Behavior

`None of the “sha256” hashes in the integrity attribute match the content of the subresource.` (from console)

## 📝 Steps to reproduce

1. Go to `/api-doc` (blank page w/ console error)
2. Force-reload (page is normal)

## 📌 Environment

Misskey version: 12.114.0-beta.6
Your OS: Linux
Your browser: Firefox

**Comment by Lakr233** [comment]
Same issue on Misskey 13.0

**Comment by tamaina** [comment]
api-docは廃止？ @syuilo

**Comment by CyberRex0** [comment]
> かも(Misskey Hubに移動)
https://misskey.io/notes/99s39gdk7e

**Comment by tamaina** [comment]
api-doc is removed

**Comment by Lakr233** [comment]
But on misskey hub:

<img width="1245" alt="截屏2023-01-16 22 00 05" src="https://user-images.githubusercontent.com/25259084/212695595-36660069-f03b-4d73-86df-925171c068f3.png">

<img width="865" alt="截屏2023-01-16 22 00 26" src="https://user-images.githubusercontent.com/25259084/212695646-e49a22f8-da90-4430-8d95-ee1a5f9a9803.png">

So where can I get new doc?

**Comment by tamaina** [comment]
多分普通にFastifyに書き忘れてるだけだわこれ

**Comment by tamaina** [comment]
api.jsonの取得可否をテストに書いてるのに放置してるし（やっぱしゅいろテストに興味ないんだよな…）

**Comment by syuilo** [comment]
テストが落ちるのが普通になってるので

**Comment by Lakr233** [comment]
I've doing my job writing client for Misskey, it is hard to get job done if doc is missing. Please consider add it back. 🥹

https://github.com/Lakr233/Kimis
