### ISSUE TITLE
デッキ設定の「常にメインカラムを表示」が機能していない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#9008]
## 💡 Summary

- デッキ設定の「常にメインカラムを表示」が有効でもメインカラムが表示されない
- デフォルトでメインカラムが表示されないので、意図せずに #8972 のようなことが起こる
## 🥰 Expected Behavior

「常にメインカラムを表示」が有効の場合、強制的にメインカラムを表示

## 🤬 Actual Behavior

 
「常にメインカラムを表示」が有効でも、メインカラムが表示されない

## 📝 Steps to Reproduce

1. 「常にメインカラムを表示」を有効化（デフォルトで有効）
2. デッキを使う

## 📌 Environment

Misskey version: 12.116.0.beta-1
Your OS:
Your browser:

**Comment by syuilo** [comment]
再現せず

**Comment by syuilo** [comment]
「常にメインカラムを表示」っていう設定名が分かりにくいかも
実際の挙動は「(メインカラムが設置してある場合、`/`にいる状態でも)メインカラムを隠さない」だったと思う

**Comment by futchitwo** [comment]
なるほど勘違いしていました（確かにわかりにくい）
