### ISSUE TITLE
デッキUI時に ページで表示 ボタンが機能しない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#9010]
## 💡 Summary
デッキUI時に"ページで表示"ボタンが機能しない

## 🥰 Expected Behavior
ページで表示 を押すとメインカラムにウィンドウの内容が飛ぶ（ページ移動する）

## 🤬 Actual Behavior
デッキの設定にて `デフォルトのナビゲーション: ウィンドウで開く` を ON に設定している際に
ページで表示 を押してもページで表示されない（ウィンドウが閉じて再度開く）

## 📝 Steps to Reproduce

1. デッキの設定の `デフォルトのナビゲーション: ウィンドウで開く` を ON にする
2. リンクを右クリック or ウィンドウヘッダーの ページで表示 ボタンを押す
3. ウィンドウで再度表示される

## 📌 Environment

Misskey version: 12.116.0
Your OS: Windows 10 Version 21H2 (Build 19044.1766)
Your browser: Chrome103.0.5060.114 (Official Build) （64 ビット） (cohort: Stable)

**Comment by syuilo** [comment]
これ難しい
