### ISSUE TITLE
Emoji picker pops up behind windows

### ISSUE THREAD

**Issue by tastytea** [syuilo/Misskey#9015]
## 💡 Summary

When i have a note open in a window and click on the react button, the emoji picker pops up behind the window. The row with the default emojis is hidden.

![screenshot window and emoji picker](https://user-images.githubusercontent.com/3681516/179502536-a30801e8-4d6a-4cd6-ae8b-0c61dc26d6f3.png)

I haven't seen this in 12.116.1, but i'm not sure i ever reacted from a window on this version. :thinking: 

## 🥰 Expected Behavior

emoji picker pops up above window.

## 🤬 Actual Behavior

emoji picker pops up behind window.

## 📝 Steps to Reproduce

1. Open note in window
2. click the react button

## 📌 Environment

Misskey version: 12.117.0
Your OS: Gentoo Linux
Your browser: Firefox 91.11.0esr

Also happens on Android 11 (LineageOS 18.1) with Firefox 102.2.1

**Comment by tastytea** [comment]
Probably related: Full screen images are behind windows too.

![screenshot of full screen image behind windows](https://user-images.githubusercontent.com/3681516/179529315-52903045-553f-4217-bc75-22a3aafde9ae.png)

The file-from-drive picker and the edit custom emoji dialogue are behind windows too.

![grafik](https://user-images.githubusercontent.com/3681516/179530536-4421146b-939e-44f6-9f93-da13fcf9ac0c.png)

**Comment by tastytea** [comment]
The window's `z-index` is `2010200`. Overriding it like this seems to fix things:

``` css
.ebkgocck {
  z-index: 1000000 !important;
}
```

The edit custom emoji dialogue's `z-index` is `1000200`.

**Comment by syuilo** [comment]
fixed https://github.com/misskey-dev/misskey/commit/264a6cda8e228de4669c4cdc134c6f6b6566f4e9
