### ISSUE TITLE
AAC(m4a)ファイルをアップロードできない

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#9018]
## 💡 Summary

AAC(m4a)のファイル（映像ストリームのない動画コンテナファイル）をアップロードしようとするとffmpegがサムネイルの生成に失敗してアップロード処理ができない。
```
ERR  1        [api]        Error: ffmpeg exited with code 1: Codec AVOption skip_frame (skip decoding for the selected frames) specified for input file #0 (/tmp/4e47de83b277b8633c774c8679426a1d) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.
Output #0, image2, to '/tmp/tmp-1805730-oiSGTv3uHW19/%d.png':
Output file #0 does not contain any stream
```
![クライアントでのエラー](https://user-images.githubusercontent.com/37925599/179537392-2f0d2fe2-cfe0-4153-9f2a-93a27244f16a.png)

## 🥰 Expected Behavior

どうするのが正解なんでしょう…。\
とりあえず上げれたら嬉しいです。\
映像ストリームがない場合は代替の画像を用意してそれをサムネイルとする…？

## 🤬 Actual Behavior

しいたけが出る
![クライアントでのエラー](https://user-images.githubusercontent.com/37925599/179537392-2f0d2fe2-cfe0-4153-9f2a-93a27244f16a.png)

## 📝 Steps to Reproduce

1. ドライブにAACファイルをアップロードする

## 📌 Environment

Misskey version: 12.116.1\
Your OS: Ubuntu 20.04\
Your ffmpeg: 4.2.7-0ubuntu0.1\
Your browser: Chrome 103.0.5060.114

**Comment by acid-chicken** [comment]
サムネ生成に失敗してるというか、動画トラックのないファイルも NSFW 判定しようとしてコケてる
