### ISSUE TITLE
GNU socialをフォローできない

### ISSUE THREAD

**Issue by ohaguro** [syuilo/Misskey#9019]
バグなのか仕様なのかわかりませんが、一応報告
https://gnusocial.jp のユーザーをフォローできません。
https://gnusocial.jp/gnusocialjp/subscribers を見る限りマストドンユーザーはいるので、AP対応版のGNU socialを使用している模様。
であるならば、misskeyからフォローできてもよさそうなものと思えます。

**Comment by rinsuki** [comment]
![image](https://user-images.githubusercontent.com/6533808/179619276-aa535a1f-e29f-4974-b73f-d9abe0dd9c61.png)

確かにプロフィールは引けるけどフォローは処理中になる謎

**Comment by 4ioskd** [comment]
Related to https://github.com/misskey-dev/misskey/issues/2493

どうやらGNU SocialにはActivityPub専用プラグインがあるようです。GNU SocialはOstatusプロトコルのみに対応していると長らく思い込んでた。。

GNU Socialの公式リポジトリより:
ActivityPub plugin for GNU social
https://notabug.org/diogo/gnu-social/src/master/plugins/ActivityPub

**Comment by senooken** [comment]
@ohaguro さん。issue登録ありがとうございました。

GNU social [v2.0.0beta0](https://notabug.org/diogo/gnu-social/src/v2.0.0beta0)に「[Correct bugs preventing GNU Social from following accounts on Misskey - NotABug.org: Free code hosting](https://notabug.org/diogo/gnu-social/pulls/279)」のパッチを適用すると、GNU socialからMisskeyへの通信はほとんど問題ないように見えています。

具体的には以下の動作は問題ありませんでした。

# 正常動作

1. GSからMisskeyのへのメンション、Misskeyの投稿に対する返信・お気に入りはMisskey側での通知も含めてOK。
2. 投稿URLでの検索は双方問題なくヒット。アバター画像も表示。

しかし、MisskeyからGNU socialへの通信で何か問題があるようにみえます。具体的には、以下の動作に問題がありました。misskey.ioとgnusocial.jpで確認しました (gnusocial.jpには上記パッチ適用済み)。

# 異常動作

1. GS→Misskeyへのフォロー。フォロー一覧でMisskeyのアバター画像がGS側で表示されない。
2. Misskey→GSへのフォロー。Misskey側で [処理中] となったまま処理が終わらずフォローできない。
3. GS→Misskeyフォロー後、Misskeyの投稿はGSのホーム画面に流れてこない。
4. Misskey→GSへのメンション、GSの投稿に対する返信はできるものの、共にGS側で該当投稿のURL検索後、投稿をお気に入りしないと通知を受信できない。
5. GSの投稿に対するMisskeyからのお気に入りはGS側で通知を受信できない。

特にMisskeyからGNU socialへのフォローができない点、Misskey開始の処理の問題が多いので、Misskey内部で何かエラーが起きている可能性を感じました。Misskey側の処理に何も問題がなく、GNU social側の問題の場合、それを教えていただけますと、GNU social側の[issue](https://notabug.org/diogo/gnu-social/issues/226)に情報を追加して対応します。GNU social側ではログに特にエラーはありませんでした。

検証する際は、<https://gnusocial.jp/test> か、gnusocial.jpにアカウントを作っていただいて問題ありません。よければどうぞよろしくお願いします。

なお、サイトにも同じ内容の情報を整理して掲載しています ([GNU social v2でのMisskeyとの通信問題 | GNU social JP](https://web.gnusocial.jp/post/2022/07/25/))。

なお、その後 <https://social.pseudo-whiskey.bar/@tacumi> のMisskeyユーザーからGSをフォローされましたので、Misskeyのバージョンなどによってはフォローできるのかもしれません。

GSをフォローできるMisskeyがGSをフォローすると、GSから自分でMisskeyをフォローしたのと、アカウントが別に認識されており、 <https://gnusocial.jp/gnusocialjp/subscribers> から同じアカウントをフォローすると、アバター画像が表示され、ホーム画面にも投稿が流れてくるようになりました。動作が謎です。Misskeyの他にGS側にも何か別の問題があるのかもしれません。

**Comment by ohaguro** [comment]
フォロー作業中だったものを中断取り消し、改めてフォローボタンを押すとフォローできました。
お騒がせしました。

**Comment by ohaguro** [comment]
misskey.ioからgnusocialjpは無事にフォローできたが
何故かsocial.senooken.jpはフォローできない模様。何故だろう？

**Comment by senooken** [comment]
@ohaguro さん。こちら (<https://social.senooken.jp/notice/4418856>) の依頼通り、senooken@social.senooken.jpのフォローのお試しありがとうございました。social.senooken.jpにもGS側のパッチを適用済みです。

私がこちらに情報を投稿してから、@syuilo さんが <https://misskey.io/notes/934d4l2isu> の投稿を2022-07-25 Monにしてから、gnusocial.jpをフォローできるようになったとみています。

2022-07-25 Monにこの投稿を見て、その後すぐsenooken@misskey.ioからsenooken@social.senooken.jpをフォローできました。しかし、本日念のためフォローを解除してフォローし直すと、フォローできなくなっていました。gnusocial.jpは問題ありませんでした。social.senooken.jp側ではエラーログはありませんでした。

少なくともmisskey.ioについては、私の指摘後コードか設定を修正された可能性が高いと思っています。ホワイトリストかブラックリストのようなものを設定しているのではないかと思っています。

<https://social.senooken.jp/test> にテストアカウントを用意していますので、よければご検証お願いします。

**Comment by rinsuki** [comment]
misskey.ioは何か独自のフィルタを適用してるっぽいので、他のインスタンスで再現するかを確かめて、再現しない場合はまず misskey.io の管理者に問い合わせてください (というのを連合系issueのマニュアルにしたい)。misskey.noellabo.jp では問題なく動きました

**Comment by senooken** [comment]
@rinsuki ありがとうございました。了解しました。開発者が運営しているので、安定していてスタンダードなこと想定して、アカウント作成・動作確認に使ったので、特殊な仕様になっているのは想定外でした。別のサーバーを今後は試すことにします。

**Comment by syuilo** [comment]
Off topic:
misskey.ioはスパム対策で出来て直ぐのインスタンスとは通信できなかった気がします。あとmisskey.ioの運営には開発者は関わっていないです。

**Comment by senooken** [comment]
@syuilo さん。ありがとうございます。運営には関わっていないとのことで、こちらの見落として勘違いして失礼しました。
できてすぐのサーバーとは通信できないとのことですが、月曜日のコメント後はフォローできたので、何か前後でされたのかと思いました。今後は、まずはサイト運営者・サポートに確認します。

**Comment by senooken** [comment]
その後、[misskey.ioのサポート](https://misskey.io/@support)に問い合わせて、解決できました。参考までにその際の回答をこちらにも記しておきます。

> こちらの件を確認したところ、過去に数日間通信ができない期間が発生していたことからインスタンスへの配信が停止されていたようです。
> アクティビティの送信を再開しましたのでご確認いただけますでしょうか。

misskey.io側で「インスタンスへの配信、アクティビティの送信」がなされていなかったのが、misskey.ioのアカウントからsocial.senooken.jpのアカウントをフォローできない原因のようでした。
