### ISSUE TITLE
アンテナタイムライン（ストリーミング）が、フォローしていないユーザーの鍵投稿も拾ってしまう

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9025]
## 💡 Summary

自分をフォローしていないユーザーが、自分のアンテナに引っかかるノートを投稿したとき、そのノートがアンテナに収集されてしまう。

投稿の内容は隠されていて閲覧できない（`()` と表示される）が、アンテナの条件次第では何を言っているのか推論できてしまう。

## 📝 Steps to Reproduce

1. アンテナを作成し、表示したままにする
2. 自分をフォローしていないサブアカウント等（自分のインスタンスと連合しているか、同じインスタンスのユーザーであること）にて、1.で作成したアンテナの収集条件を満たすノートを公開範囲「フォロワー」で作成する
3. 1.のアンテナを確認する

## 📌 Environment

Misskey version: 12.110.1
Your OS: macOS 12
Your browser: Chrome

**Comment by syuilo** [comment]
めんどくさいからフォローしているユーザーであっても鍵投稿は一律でアンテナの対象にはならないようにするか

**Comment by syuilo** [comment]
あれコード上はフォロワーかどうかチェックしてた

**Comment by syuilo** [comment]
あーストリーミングオンリーね

**Comment by EbiseLutica** [comment]
@syuilo これ結局ストリーミング以外も鍵はアンテナ対象外になっちゃった感じ？

**Comment by syuilo** [comment]
> @syuilo これ結局ストリーミング以外も鍵はアンテナ対象外になっちゃった感じ？

yes
