### ISSUE TITLE
MiAuth is broken

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9026]
## 💡 Summary
MiAuthがまったく機能していない

## 🥰 Expected Behavior
要求されている権限が表示され、「許可」ボタンを押すと認証できる。

## 🤬 Actual Behavior
権限が正しく表示されず、空の箇条書き行がたくさん表示され、許可ボタンが押せない。
![Screenshot_20220721-214923~2](https://user-images.githubusercontent.com/26585194/180218889-54d974bd-d879-4f77-85ce-629365ae0c52.png)

## 📝 Steps to Reproduce

MiAuthを使う

## 📌 Environment

Misskey version: 12.117.1
Your OS: Android 11, Windows 10
Your Browser: Chrome 103

**Comment by syuilo** [comment]
URLはどのようになってますか？

**Comment by CyberRex0** [comment]
`/miauth/b6247f94-0d4e-432f-9b06-8f471295bac1?name=ExternalApp&permission=read%3Aaccount%2Cread%3Adrive%2Cwrite%3Adrive%2Cwrite%3Anotes%2Cread%3Anotifications%2Cread%3Areactions%3Awrite%3Areactions&callback=http%3A%2F%2Flocalhost%3A8888%2Fauth%2Fcallback`
