### ISSUE TITLE
Misskey側で既読になった通知をOSの通知センターから消さないようにする or オプトイン/アウトにする

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey#9033]
## Summary

- 裏で開いているとか放置しているマシンで開いているだけでも WebUI が生きてると既読になって他端末からプッシュ通知が消える
  - というかそもそも Misskey の通知既読判定が緩すぎ？
- ↑の結果プッシュ通知が読めない
- しかも音だけ鳴る
- 「プッシュ通知の更新をしました」がOS標準の通知音とともに鳴る(うえすぐ消える)ので余所見していた時にOSの通知センターに何も残っておらず混乱する

### Environment

Firefox Nightly 104.0a1 (2022-07-22) + macOS 12.5

**Comment by tamaina** [comment]
Related to #6360

(実装方針) エンドポイントごとに設定をサーバーに記憶させる (プッシュがあったときSWが通知を出さなければブラウザが通知を出してしまうため)

> 「プッシュ通知の更新をしました」がOS標準の通知音とともに鳴る(うえすぐ消える)

Firefox+macOSだと鳴ってしまうのか (silentのはずなので鳴らないのが正しい挙動かなぁと…)

> 裏で開いているとか放置しているマシンで開いているだけでも WebUI が生きてると既読になって他端末からプッシュ通知が消える
> 
> というかそもそも Misskey の通知既読判定が緩すぎ？

こっちが根本原因だと思う……放置(アイドル)を判定して、放置時は既読を付けないようにするほうがいいかも？

https://www.npmjs.com/package/idle-js

**Comment by rinsuki** [comment]
そもそも音が鳴らなくても何かが画面に出て(既読扱いされて)すぐ消えたというのは体験としてよくないし、画面を放置してるけどちゃんと見てる時と全然見てないというパターンもあるので放置判定も難しい (やらないよりはマシだが)

それはそうと自分は既読が付いてようが通知センターに残っていてほしいので通知を消してほしくない。

**Comment by tamaina** [comment]
> 音が鳴らなくても何かが画面に出て(既読扱いされて)すぐ消えたというのは体験としてよくない

これは実装当初から思っていた

今思いついたけど、インスタンス名とかをかっこよく表示してお茶を濁すのがよさそう

**Comment by rinsuki** [comment]
それ結局いらないプッシュ通知が来るというところは直っていないし…

次の通知送る時についでにもう見た通知を消すとかできないもんかな

**Comment by tamaina** [comment]
> 次の通知送る時についでにもう見た通知を消すとかできないもんかな

技術的には可能

**Comment by tamaina** [comment]
> > 「プッシュ通知の更新をしました」がOS標準の通知音とともに鳴る(うえすぐ消える)
> 
> Firefox+macOSだと鳴ってしまうのか

Leitz Phone 1も鳴る…

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/203316717-ad71a732-a6c3-4447-bd0a-435fdd6bbc1e.png)

macOS Safariで登録してみたけどこれはw

**Comment by tamaina** [comment]
…userVisibleOnly: falseでsubscribeすればメッセージ要らんのでは…

**Comment by tamaina** [comment]
> userVisibleOnly: falseでsubscribe

SafariとChromeでは拒否られた
