### ISSUE TITLE
## REUSE: best practices for copyright and licensing information

### ISSUE THREAD

**Issue by elif17** [syuilo/Misskey#9040]
## Summary

Hello! I work for the Free Software Foundation Europe (FSFE), and we are helping software projects that have applied for and accepted into the Next Generation Internet Zero Initiative (https://www.ngi.eu/ngi-projects/ngi-zero/) with their licensing and copyright management. After a quick check on your repository, I would like to propose some updates regarding copyright and licensing information, using our REUSE framework.

REUSE: best practices for copyright and licensing information
REUSE (https://reuse.software/) is an FSFE developed initiative intended to make licensing easier by establishing a single way to display all copyright and licensing information through comment headers on source files that can be human- and machine-readable. This in turn helps with maintaining clear communication of copyright and licensing information to avoid legal issues downstream.

The REUSE tool makes the process of applying licenses to files and compliance checking much easier. Instructions on how to install the REUSE tool can be found here:

https://reuse.readthedocs.io/en/stable/readme.html#install

You can also check out this screencast for more instructions on how to use the REUSE tool: https://download.fsfe.org/videos/reuse/screencasts/reuse-tool.gif

Files with missing copyright and licensing information
To serve as an example, I am planing to add the SPDX headers with copyright and license information to the copyrightable files in your packages/client/src/pages/admin folder. This should give you an idea of how comment headers should look like in a REUSE compliant repository (where all files would have such headers to communicate license and copyright information). You can find it here:
https://github.com/elif17/misskey

LICENSES Directory in the Root of the Project
I am planing to move to this directory the file that contained the AGPL-3.0-only license text.
Additionally, I want to include in this text the CC0 license text. This is because you have files in your project that you do not find copyrightable, for example configuration files such as .gitignore. As the fundamental idea of REUSE is that all of your files will clearly have their copyright and licensing marked, I want to apply the CC0 license to .gitignore, which is functionally identical to putting the file in the public domain.

If you find REUSE useful, we will offer a wide range of tools to help you continuously check and display compliance with the REUSE guidelines.

Hope that this helps you to consider to implement REUSE, happy to help in this process.

Best,
Elif Kenan

**Comment by elif17** [comment]
reopening issue

**Comment by KisaragiEffective** [comment]
triage: #11155 が達成されているので主要な目的は達成できていそう。

**Comment by KisaragiEffective** [comment]
re-visit: I think the Project codebase is (loosely) compliant with REUSE spec by checking both author and SPDX license identifier in GitHub workflow. For now, I mark this issue with complete because similar issue ( #11155 ) is completed in past.
