### ISSUE TITLE
Blocking / unblocking doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [syuilo/Misskey#9042]
## 💡 Summary
When I try to block or unblock a user an error message pops up about an internal server error.

![Screenshot_20220806-173626](https://user-images.githubusercontent.com/3656054/183256077-f7f1d350-20e2-4fb4-b756-3c387e2b0d49.png)

When I try to block or unblock that user again a message appears that the user is already blocked / unblocked. 

![Screenshot_20220806-173644](https://user-images.githubusercontent.com/3656054/183256126-16e7ee97-2e3a-4509-b2be-43720acfd4e6.png)

There is no indication in the UI that the blocking / unblocking was successful

## 🥰 Expected Behavior
Blocking and unblocking a user should work without an error message.

## 🤬 Actual Behavior
Blocking / unblocking doesn't work. An error message pops up.

## 📝 Steps to Reproduce
1. Go to the global timeline and find some random user
2. Try to block that user
3. Try again

## 📌 Environment
Instance: misskey.de 
Misskey version: 12.117.1 
Node.js: 16.16.0 
Vue: 3.2.37 
PostgreSQL: 14.4 
Redis: 6.0.16 
Your OS: Ubuntu 22.04 LTS 
Your browser: Firefox on Android

**Comment by syuilo** [comment]
Try 12.118.0

**Comment by AlfredSK** [comment]
Great! Works with Misskey 12.118.0. :tada:
