### ISSUE TITLE
Misskey fails to update on Yunohost

### ISSUE THREAD

**Issue by AidanTheBandit** [syuilo/Misskey#9044]
## 💡 Summary

I have YunoHost beta 11 because that's the only version that is supposed to work with the latest versions of Misskey. When I try to update it fails to

## 🥰 Expected Behavior

Updates Misskey to the latest version

## 🤬 Actual Behavior

Fails to upgrade with several error

## 📝 Steps to Reproduce

1. Login to Root on Debian 10 VPS
2. Install with either `sudo yunohost app upgrade misskey -u https://github.com/YunoHost-Apps/misskey_ynh/tree/memo-567-patch-1 --debug` or `sudo yunohost app upgrade misskey -u https://github.com/YunoHost-Apps/misskey_ynh/tree/bullseye --debug`

## 📌 Environment

Misskey version: 12.110.1~ynh2 -> 12.118.0~ynh1
Your OS: Debian 10
Your browser: Brave Browser

Logs: https://paste.yunohost.org/raw/atonuduzed

Specs:
Processor: 2 vCore
--
Memory: 4 GB
Storage: 80 GB SSD NVMe

**Comment by ThatOneCalculator** [comment]
This seems more appropriate for https://github.com/YunoHost-Apps/misskey_ynh

**Comment by AidanTheBandit** [comment]
> This seems more appropriate for https://github.com/YunoHost-Apps/misskey_ynh

https://github.com/YunoHost-Apps/misskey_ynh/issues/118

**Comment by AidanTheBandit** [comment]
Im using YunoHost because installing normally causes the same issues when using Docker, Script, and Manully

**Comment by ThatOneCalculator** [comment]
Ah. Looking at those comments, ARM compatibility is currently borked due to the TensorFlow integration.

**Comment by AidanTheBandit** [comment]
Im on amd64 though

**Comment by ThatOneCalculator** [comment]
hm... not sure. I'm looking through the log but can't tell what the exact problem is, maybe a migration gone wrong? :shrug: I'm probably wrong tho.

**Comment by rinsuki** [comment]
it seems error is this:

```
2022-08-08 05:44:10,723: DEBUG - + sudo -u misskey env PATH=/opt/node_n/n/versions/node/16.15.0/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin yarn cleanall
2022-08-08 05:44:12,136: DEBUG - [31m[1mInternal Error[22m[39m: misskey@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
2022-08-08 05:44:12,136: DEBUG -     at TR.getCandidates (/var/www/misskey/.yarn/releases/yarn-3.2.2.cjs:435:5226)
2022-08-08 05:44:12,137: DEBUG -     at wd.getCandidates (/var/www/misskey/.yarn/releases/yarn-3.2.2.cjs:391:1281)
2022-08-08 05:44:12,137: DEBUG -     at /var/www/misskey/.yarn/releases/yarn-3.2.2.cjs:439:7764
2022-08-08 05:44:12,137: DEBUG -     at Lg (/var/www/misskey/.yarn/releases/yarn-3.2.2.cjs:390:11154)
2022-08-08 05:44:12,137: DEBUG -     at ce (/var/www/misskey/.yarn/releases/yarn-3.2.2.cjs:439:7744)
```

but I'm not sure why this error will occurs.

also FYI, if you are running under Docker, this error will not occurs since docker environment doesn't needs `yarn cleanall`

**Comment by AidanTheBandit** [comment]
Ok. I can try to migrate from YunoHost to docker to see if maybe that fixes the issue

**Comment by rinsuki** [comment]
wait, i think this error is somehows you are using yarn v3.

can you retry with `rm /var/www/misskey/.yarnrc.yml && rm -r /var/www/misskey/.yarn`?

**Comment by AidanTheBandit** [comment]
Ok. I just ran that

**Comment by ghost** [comment]
@AidanTheBandit1  Did this solve your problem?

**Comment by AidanTheBandit** [comment]
Not yet

**Comment by AidanTheBandit1** [comment]
Errors when using Docker
`
fatal: not a git repository (or any of the parent directories): .git
ERROR: Service 'web' failed to build: The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128
root@yunohost:/var/www/misskey# git stash
fatal: not a git repository (or any of the parent directories): .git
root@yunohost:/var/www/misskey# git submodule update --init
fatal: not a git repository (or any of the parent directories): .git
root@yunohost:/var/www/misskey# sudo docker-compose up -d
Building web
Step 1/23 : FROM node:16.15.1-bullseye AS builder
 ---> e43982a1ad0e
Step 2/23 : ARG NODE_ENV=production
 ---> Using cache
 ---> 163ae1a53cbb
Step 3/23 : WORKDIR /misskey
 ---> Using cache
 ---> 4d8ef35e8b15
Step 4/23 : COPY . ./
 ---> Using cache
 ---> e865a3b99328
Step 5/23 : RUN apt-get update
 ---> Using cache
 ---> a49dfddc989e
Step 6/23 : RUN apt-get install -y build-essential
 ---> Using cache
 ---> 0e42ba125a2d
Step 7/23 : RUN git submodule update --init
 ---> Running in d68fd91b95e2
fatal: not a git repository (or any of the parent directories): .git
ERROR: Service 'web' failed to build: The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128
`

**Comment by AidanTheBandit1** [comment]
Errors when using Docker
```
fatal: not a git repository (or any of the parent directories): .git ERROR: Service 'web' failed to build: The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128 root@yunohost:/var/www/misskey# git stash fatal: not a git repository (or any of the parent directories): .git root@yunohost:/var/www/misskey# git submodule update --init fatal: not a git repository (or any of the parent directories): .git root@yunohost:/var/www/misskey# sudo docker-compose up -d Building web Step 1/23 : FROM node:16.15.1-bullseye AS builder ---> e43982a1ad0e Step 2/23 : ARG NODE_ENV=production ---> Using cache ---> 163ae1a53cbb Step 3/23 : WORKDIR /misskey ---> Using cache ---> 4d8ef35e8b15 Step 4/23 : COPY . ./ ---> Using cache ---> e865a3b99328 Step 5/23 : RUN apt-get update ---> Using cache ---> a49dfddc989e Step 6/23 : RUN apt-get install -y build-essential ---> Using cache ---> 0e42ba125a2d Step 7/23 : RUN git submodule update --init ---> Running in d68fd91b95e2 fatal: not a git repository (or any of the parent directories): .git ERROR: Service 'web' failed to build: The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128
```

**Comment by AidanTheBandit** [comment]
I just backed up Misskey and reinstalled a fresh version of Debian 11 then loaded the backup I took and upgraded the backup and it upgraded successfully. For mobile the login screen now seems to load forever though. I haven't tested on my desktop yet

**Comment by AidanTheBandit** [comment]
![brave_F5NXqI7nQL](https://user-images.githubusercontent.com/84136868/183767486-b317a1db-5caf-4e6a-93f2-33726dd0d95e.png)

**Comment by AidanTheBandit** [comment]
@rinsuki @ThatOneCalculator any solutions? Here is what is looks like on mobile ![image](https://user-images.githubusercontent.com/84136868/183769115-eac9d1f2-5d70-46f4-b6e2-6ee0280008c4.jpeg)

**Comment by ThatOneCalculator** [comment]
That message means your device is offline (or the SW isn't working)

**Comment by AidanTheBandit** [comment]
I got it to turn on but now the login screen just loads forever

**Comment by AidanTheBandit** [comment]
> ![brave_F5NXqI7nQL](https://user-images.githubusercontent.com/84136868/183767486-b317a1db-5caf-4e6a-93f2-33726dd0d95e.png)

**Comment by AidanTheBandit** [comment]
I got it to update but its stuck loading
