### ISSUE TITLE
Misskey stuck loading after upgrade

### ISSUE THREAD

**Issue by AidanTheBandit** [syuilo/Misskey#9049]
## 💡 Summary

Misskey loads forever after upgrading from 12.110.1 to 12.118.1

## 🥰 Expected Behavior

Loads into updated Misskey

## 🤬 Actual Behavior

Stuck on loading screen forever

## 📝 Steps to Reproduce

1. Upgrade from 12.110.1 to 12.118.1 using Yunohost

## 📌 Environment

Yunohost
2 Cores
AMD64
4GB ram
80GB storage

Misskey version: 1.118.1
Your OS: Debian 11
Your browser: Brave

**Comment by AidanTheBandit** [comment]
I have started a thread on the forums. https://forum.misskey.io/d/107-misskey-stuck-after-upgrade

**Comment by cafkafk** [comment]
Updating via docker-compose as specified in https://misskey-hub.net/en/docs/install/docker.html also made the page be stuck loading for me.

However, only when trying to log in, you can go to the site like normal. Just can't log in.

**Comment by cafkafk** [comment]
I found out that the cloudflare setting Rocket Loader™ broke this, and removing that fixed it for me

**Comment by AidanTheBandit** [comment]
Ima try this real quick. You may have just saved my life

**Comment by AidanTheBandit** [comment]
This fixed the Issue! Thanks so much!
