### ISSUE TITLE
HomeBarと画面下部のpaddingを調整する

### ISSUE THREAD

**Issue by adzukyat** [syuilo/Misskey#9052]
## Summary

もともとあるpaddingと`env(safe-area-inset-bottom, 0px)`が二重になっていて少し間隔が開きすぎている気がするので、
1. ビューポートに空きがある(iOSでHomeBarが存在するなどの)場合は`env(safe-area-inset-bottom, 0px)`を使い、
2. 無い場合はもとのpaddingを使う

ようにしたいです。
![Description](https://user-images.githubusercontent.com/44765629/184530622-8e3d24c1-a2e4-41e9-a4e1-070f702f783d.png)

また、現状ではemoji-pickerに適切なpaddingが設定されていないため、HomeBarと検索ボックスが次のように重なります。
![IMG_0364](https://user-images.githubusercontent.com/44765629/184530951-7893d3e2-6bcd-4713-8dab-be237a2fca46.jpg)

**Comment by syuilo** [comment]
iOS側の都合に合わせてデザインするのはアレだけど仕方ないか
(safe-area-inset-bottomで申告された値よりも実際のバーはそれより小さいというのはOS側の仕様の為)

**Comment by tamaina** [comment]
safe-area-inset-bottomは「サーバーから切断されました」のトーストに適用されていない

**Comment by adzukyat** [comment]
ついでに追加するかしら

**Comment by adzukyat** [comment]
> iOS側の都合に合わせてデザインするのはアレだけど仕方ないか (safe-area-inset-bottomで申告された値よりも実際のバーはそれより小さいというのはOS側の仕様の為)

`safe-area-inset-bottom`はHomeBarの高さを示してるんじゃなくてただ単に下に挿入されるべきマージンの値を示してるだけだと思う（Androidも同じく）

そう考えるとやっぱりpaddingが2重になってるのは不適切な気がする

**Comment by adzukyat** [comment]
リアクションピッカーに関しては #10534 で解決されたっぽいけど、「ウィジェットを編集」のリンクがまだおかしい

**Comment by tamaina** [comment]
ウィジェットドロワーのウィジェットを編集が押せないというやつか
