### ISSUE TITLE
新着チャットが来るとTLがスクロールされる

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/Misskey#9055]
## 💡 Summary

チャット画面からTLへ遷移した状態でチャットを受信するとTLがスクロールされます。

## 🥰 Expected Behavior

TLがスクロールされない

## 🤬 Actual Behavior

honi.club(手前のウィンドウ) → misskey.io(背面のウィンドウ)\
へチャットを送信したときの挙動

![例](https://user-images.githubusercontent.com/37925599/184539505-906b1103-edcb-447a-8830-cb229925fbd0.gif)

## 📝 Steps to Reproduce

1. チャットを開く
2. TLへ移動する
3. 1で開いていたユーザーからチャットが飛んでくる
4. TLがスクロールされる

## 📌 Environment

Misskey version: 12.118.1、12.117.1など
Your OS: Windows 11
Your browser: Chrome 104.0.5112.81

**Comment by sh1ma** [comment]
再現しました

ただし再現するためには更に条件があって、スクロールされる方でも一度メッセージルームを開いている必要がありそうです

**Comment by sh1ma** [comment]
ここが意図せず動いてるっぽい

https://github.com/misskey-dev/misskey/blob/develop/packages/client/src/pages/messaging/messaging-room.vue#L143

**Comment by KisaragiEffective** [comment]
triage: チャットが消滅したのでcloseします 🙏🏻
