### ISSUE TITLE
Troubles with api keys

### ISSUE THREAD

**Issue by DarkShyMW** [syuilo/Misskey#9066]
## 💡 Summary

there are some problems with access keys and tokens. Now, at least in my instance, it is not possible to get a list of all the keys. When you click on the button, an error message is displayed that such a page has not been found

## 🥰 Expected Behavior

When you click on the button that is responsible for the list of all API keys, a page with all API keys should open.

## 🤬 Actual Behavior

there are some problems with access keys and tokens. Now, at least in my instance, it is not possible to get a list of all the keys. When you click on the button, an error message is displayed that such a page has not been found

## 📝 Steps to Reproduce

1. Install clear latest version
2. Create API key
3. Take error

## 📌 Environment

Misskey version: 12.118.1
Node.js: v16.17.0
PostgreSQL: 14.5 (Ubuntu 14.5-1.pgdg22.04+1)
Redis: 6.0.16
Vue: 3.2.37

**Comment by futchitwo** [comment]
fixed by #9064
