### ISSUE TITLE
SyntaxError on misskey.io

### ISSUE THREAD

**Issue by nonetrix** [syuilo/Misskey#9084]
## 💡 Summary
I am aware this might be the wrong place as I think this issue is instance related, but I can't find a better way to contact and this is the main flagship misskey instance to my knowledge so it is definitely relevant. I have reproduced this on all Chrome, Firefox, Linux, Android, and all mixtures in-between. This only happens on misskey.io not on other instances running the same software (e.g. https://skippers-bin.com )

Upon loading misskey.io this error appears every time, refreshing usually resolves it however this is very annoying so needs to be fixed. I am the only one facing this issue(and for a while actually) apparently by searching online, fediverse itself and of course Github however I have been able to reproduce it on many different devices, networks and browsers which is strange.

Misskey error page:
![Screenshot_20220906-031412](https://user-images.githubusercontent.com/45698918/188583106-d31cab59-6943-4848-932d-0939fedf5e8c.png)
Kiwi browser JavaScript console:
![Screenshot_20220906-032552](https://user-images.githubusercontent.com/45698918/188585677-be376cff-1bbd-4711-80eb-07015158ee8c.png)

I understand the error message is not very descriptive but it's all it gives me unfortunately I hope it can be of use :-)

## 🥰 Expected Behavior
Website loads the first time without a error message that needs to be refreshed

## 🤬 Actual Behavior
Error message upon first load 50% of the time

## 📝 Steps to Reproduce

1. Open any browser on literally any operating system
2. Open misskey.io(signed in or out doesn't matter)
3. See error
4. Click refresh
5. Everything is fine until a cold refresh(e.g. refresh button, opening in new tab, anything that is actually reloading it instead of just changing the content with Vue?*)

## 📌 Environment

Misskey version: v12.118.1
Your OS: Linux, Android
Your browser: Chromium(Brave, Kiwi browser), Gecko(Firefox, Librewolf), WebKit(GNOME Web)

**Comment by CyberRex0** [comment]
maybe duplicate of #9037 ?

**Comment by nonetrix** [comment]
Seems like it I will close this issue thanks for the quick response

I will reopen if needed for some reason
