### ISSUE TITLE
Pages: セクションやもしブロック内にブロックを追加できない

### ISSUE THREAD

**Issue by nafu-at** [syuilo/Misskey#9091]
## 💡 Summary

Pagesにてセクションやもしブロック内にブロックを追加する事ができない。
また、既存テキストブロックをセクション内に移動すると消滅する。

## 🥰 Expected Behavior

ブロックが追加される

## 🤬 Actual Behavior

ブロックが追加されない

```
TypeError: Cannot read properties of undefined (reading 'push')
    at i (page-editor.88376028.js:3:6879)
```

## 📝 Steps to Reproduce

1. ページを作成する / ページを編集する
2. コンテンツに "セクション" もしくは "もし" を追加する
3. "セクション" もしくは "もし" 内にブロックを追加する

## 📌 Environment

Misskey version: 12.119.0
Your OS: macOS 12.6
Your browser: Google Chrome 105.0.5195.125

**Comment by futchitwo** [comment]
動的Pages廃止によりclose？

**Comment by syuilo** [comment]
fixed
