### ISSUE TITLE
YoutubeURLプレビューのウィンドウプレイヤー

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#9094]
## Summary
YoutubeのURLプレビューの再生ボタンを押したときにMisskey内ウィンドウでプレーヤーを開くようにします
スマホでは従来の埋め込みプレーヤーになります

![image](https://user-images.githubusercontent.com/50144466/190691407-b31ade8d-1b56-449d-8716-768ba0f502b1.png)

https://user-images.githubusercontent.com/50144466/190691483-ad42d7de-e709-46bc-a22c-5cc17546a478.mp4

## なぜ
埋め込みプレーヤーだとTLがスクロールされたときに見失ってしまうとの意見が多いため
便利そう

kokt.clubで稼働中

**Comment by tamaina** [comment]
Related to #85

**Comment by syuilo** [comment]
done
