### ISSUE TITLE
Jestが突然終了する時がある

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9096]
テストの途中で exit status 1 でプロセスが終了することがある(エラーなどは吐かない)

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
原因を究明した方に¥3000進呈

**Comment by syuilo** [comment]
エラーもなんも吐かないから手掛かりが全くない

**Comment by syuilo** [comment]
¥4000に増額

**Comment by syuilo** [comment]
ちなみにテストは test/unit 下にあるものしかやらないようにしている

**Comment by syuilo** [comment]
¥5000に

**Comment by syuilo** [comment]
メモリを少なくとも500MBくらい消費してることが判明した
これが原因である可能性ありそう

**Comment by syuilo** [comment]
ほぼ空のテストファイルでも150MBほどメモリ消費した
ts-jestが非常に怪しい

**Comment by syuilo** [comment]
似たような問題が報告されていた
https://github.com/facebook/jest/issues/11601

**Comment by syuilo** [comment]
懸賞金 ¥6000

**Comment by syuilo** [comment]
ts-jestやめてesbuild-jestとか使うと解決するかなと思ったけど上手く動かなかった

**Comment by syuilo** [comment]
あーキャッシュが無い状態でやると必ず再現しそう

**Comment by syuilo** [comment]
いや関係なかった

**Comment by syuilo** [comment]
swc使ってみたけど、動くときもあるけどやっぱり突然終了するときもある
ts-jest関係ないかも

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
- `--runInBand`は外しても発生することがあるためそれは関係なさそう
- テストファイルの先頭にconsole.log書いてみたけど、突然終了するときはそれすらも呼ばれない

**Comment by syuilo** [comment]
懸賞金 ¥7000

**Comment by syuilo** [comment]
Chromeのデバッガ繋いだ時に限って再現しなくなる

**Comment by syuilo** [comment]
関係あるか分からないけどたまにこれが出るときがある(これが出るときは突然終了しない場合)
![image](https://user-images.githubusercontent.com/4439005/191604321-e7f360af-a376-450f-9210-a4031eb33aaa.png)

**Comment by syuilo** [comment]
ヌァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァンンンンオオオオンンオンオンオンオンンンンンンンンン゛ン゛！！！！！！！！！！！！！！！！

**Comment by syuilo** [comment]
懸賞金 ¥10000

**Comment by syuilo** [comment]
ここまで来るとあとはJestのコードリーディングしてプリントデバッグするくらいしかなさそう

**Comment by syuilo** [comment]
こまこまのこまり

**Comment by syuilo** [comment]
Jestのコード読んでる

**Comment by syuilo** [comment]
@jest/core/build/TestScheduler.js でtsをコンパイルしたりテストを走らせたりするっぽい

**Comment by syuilo** [comment]
jest-runner/build/runTest.js までは到達

**Comment by syuilo** [comment]
jest-runtime/build/index.js まで来たけど3000行近くあってきつい

**Comment by syuilo** [comment]
collect-v8-coverage が怪しい

**Comment by syuilo** [comment]
いや関係ない

**Comment by syuilo** [comment]
jest-circus 内部で何らかの問題が発生してそう

**Comment by syuilo** [comment]
_state.dispatch か _utils.makeRunResult が怪しい

**Comment by syuilo** [comment]
突然exit status 1で終了するのにエラーを吐かないのは
- jest内部でエラーを握りつぶしている箇所がある(だとしたらプロセス異常終了しないのでは？)
- nodeやv8レベルの問題が発生している(にしてもエラー吐くのでは？)
- OSからプロセス殺されている(その場合 exit status 1 は合ってないのでは？)
- jest内部でログなど吐かずに process.exit(1) を呼んでいる箇所がある

のどれかだと思うけどどれだろう

**Comment by syuilo** [comment]
> _state.dispatch か _utils.makeRunResult が怪しい

関係なさそう

**Comment by syuilo** [comment]
うーん jest-circus が怪しいというとこまでしか分からない

**Comment by syuilo** [comment]
具体的には、`jest-runner`の
```js
result = await testFramework(
        globalConfig,
        projectConfig,
        environment,
        runtime,
        path,
        sendMessageToJest
      );
```
の前後にlog(before / after)仕込むと、異常終了するときはbeforeは出力されるけどafterは出ない
`testFramework`というのは `jest-circus`(の`run`関数) への参照で、`run`内にもログ仕込んだりしたけど、どうも`run`内ではなにもエラーは起きてなさそうだった
また `result = await testFramework` を囲んでいるtryにもエラーは捕捉されないことから、`run`で(少なくともJSの)エラーは起きてなさそう
でも`run`の直後のlogが出力されないことも事実だから`run`(=`jest-circus`)に何らかの問題があると考えて良いのではないか

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
> 突然exit status 1で終了するのにエラーを吐かないのは
> 
> * jest内部でエラーを握りつぶしている箇所がある(だとしたらプロセス異常終了しないのでは？)
> * nodeやv8レベルの問題が発生している(にしてもエラー吐くのでは？)
> * OSからプロセス殺されている(その場合 exit status 1 は合ってないのでは？)
> * jest内部でログなど吐かずに process.exit(1) を呼んでいる箇所がある
> 
> のどれかだと思うけどどれだろう

- 異常終了するかどうかはランダム
- エラーも何も吐かない

ということから、JSレイヤーの話ではない気がするんだよな

**Comment by syuilo** [comment]
お手上げ🤷‍♂️

**Comment by syuilo** [comment]
ﾝﾆｬｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞｺﾞ

**Comment by acid-chicken** [comment]
一旦 `jest-jasmine2` でも試してみて原因が `jest-circus` 内かどうか切り分けてみては
https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults

**Comment by tamaina** [comment]
ローカルではきちんと動くけどGitHub Actionsでは失敗する、という感じ？

**Comment by syuilo** [comment]
ローカルでも再現するわね

**Comment by syuilo** [comment]
あーjest-jasmine2でも再現した

**Comment by syuilo** [comment]
なんもわからん

**Comment by syuilo** [comment]
Misskeyでテストは諦めるしかない運命なのか

**Comment by syuilo** [comment]
しゅいろさんのMPは尽きた

**Comment by syuilo** [comment]
jsonldをimportしないようにしたら再現しなくなった
やっぱりこれ関係あったっぽい
https://github.com/misskey-dev/misskey/issues/9096#issuecomment-1254196827

**Comment by syuilo** [comment]
当該箇所は
```js
const kyOriginalPromise = import('ky-universal')
  .then(({default: ky}) => ky);
```
となっていて、なぜ`a dynamic import callback was not specified`が出るのかよく分からない

**Comment by syuilo** [comment]
`a dynamic import callback was not specified`って誰が出してるエラーなんだ
node? jest?

**Comment by tamaina** [comment]
https://github.com/facebook/jest/issues/9580  
https://github.com/facebook/jest/issues/9430

ここらへんが関係ある？

**Comment by tamaina** [comment]
(jsonldモジュールの話だからimport('*.json')(json modules)とは関係ない？)

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/191898161-0936672f-0216-4b6e-9839-cb268131ad0a.png)

こういう感じで怒られたけどこれは違うか

**Comment by syuilo** [comment]
> ![image](https://user-images.githubusercontent.com/7973572/191898161-0936672f-0216-4b6e-9839-cb268131ad0a.png)
> 
> こういう感じで怒られたけどこれは違うか

あーそれは関係ないわね
(MetaService.tsを消しても異常終了は再現する)

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/191898694-d9607dce-6b7b-4527-8fed-ce9a7dd46cdb.png)

--no-cacheでやろうとしたら1回だけ`Segmentation fault (core dumped)`って言われた（これきりだけど…）

**Comment by tamaina** [comment]
>  (MetaService.tsを消しても異常終了は再現する)

私しないんだけど

`node node_modules/jest/bin/jest.js --clearCache`後にtest/unit/RelayService.tsで`Segmentation fault (core dumped)`と言われることがある（が直近は成功した）

**Comment by tamaina** [comment]
あとはこんな感じでタイムアウトと`the user is already exists`がたまにある

![image](https://user-images.githubusercontent.com/7973572/191899714-d1d11e1f-60cf-4444-a9aa-669e5eff0646.png)

**Comment by syuilo** [comment]
> あとはこんな感じでタイムアウトと`the user is already exists`がたまにある
> 
> ![image](https://user-images.githubusercontent.com/7973572/191899714-d1d11e1f-60cf-4444-a9aa-669e5eff0646.png)

これらはこっちでは出たことないな

**Comment by syuilo** [comment]
jsonldをimportするコードが含まれるのがRelayServiceだからSegfaultもそれに関係してるかも？

**Comment by ikuradon** [comment]
手元で検証してみたところ、Node.js 16だと問題なく、18だとSegmentation faultを出すのかな
https://github.com/misskey-dev/misskey/blob/develop/.github/workflows/test.yml#L16
で18を指定しているっぽい？

**Comment by CyberRex0** [comment]
クラッシュしなかった
Node 18.5 + Ubuntu 20.04.5 LTS
AMD EPYC 7282 16-Core Processor

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/191904513-94a7e82b-7866-49b3-bb70-cccd85f3a4ea.png)

MetaSeriviceでもSegfaultした

**Comment by tamaina** [comment]
SegfaultはOCI A1 (arm64)特有の問題かもしれない

**Comment by syuilo** [comment]
ちなみに私はずっとwindows + node 16で検証してました

**Comment by tamaina** [comment]
ところで: --detectOpenHandles試したことある？

**Comment by syuilo** [comment]
> ところで: --detectOpenHandles試したことある？

むしろずっとそれしてたけどパフォーマンスに影響があるらしいからやめた

**Comment by tamaina** [comment]
いま外出先なのでスクショ貼れないんだけど、--detectOpenHandlesだと必ず最後にhttp2ストリームが残っててなんとかかんとかって言われるので、ky-universalが何か関与してる？

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/191923485-83617cbf-5ee6-4846-9540-1cc20a67689b.png)

**Comment by tamaina** [comment]
> SegfaultはOCI A1 (arm64)特有の問題かもしれない

x64なWSL2 Ubuntuでも再現した

**Comment by syuilo** [comment]
> ![image](https://user-images.githubusercontent.com/7973572/191923485-83617cbf-5ee6-4846-9540-1cc20a67689b.png)

まあこれはライブラリの仕様(importしただけで副作用を発生させるのは問題な気はする)だからしょうがないわね

**Comment by ikuradon** [comment]
メモリリークが原因かと思って同じテストを11回ずつまわしてるけど全然落ちないわね…
![image](https://user-images.githubusercontent.com/713033/192098384-706213ae-c0d7-451c-8c28-b14358a594c2.png)


yarn: 1.22.19
node: v16.17.0
command: `rm -rf /tmp/jest_0/ && NODE_ENV=test node --expose-gc --experimental-vm-modules --experimental-import-meta-resolve node_modules/jest/bin/jest.js --forceExit --runInBand --detectOpenHandles --logHeapUsage`

**Comment by syuilo** [comment]
Note: このコミットで一時的に原因と思われる箇所を消してるので、再現させたい時はこれより前の状態でやった方が良いかも
https://github.com/misskey-dev/misskey/commit/da88e3a3b177a98c84745ab9e8d707d1dcb99183

**Comment by syuilo** [comment]
そのコミット以降Actions上で一回も異常終了してないからやっぱりjsonldパッケージが原因ということで間違いなさそうになってきた

**Comment by ikuradon** [comment]
Segmentation fault再現してます
![image](https://user-images.githubusercontent.com/713033/192130707-6fc37010-6ed9-4c5b-a606-3d92e3c4f8ff.png)

yarn: 1.22.19
node: v16.17.0
commit: dabe5bf7

**Comment by CyberRex0** [comment]
Apple Siliconだと発現しない
Node 16で動かしてる

**Comment by ikuradon** [comment]
> Apple Siliconだと発現しない Node 16で動かしてる

MetaService.tsを複数コピーして(`for i in {1..10};do cp test/unit/MetaService.{,$i.}ts;done`)動かすと落ちる確率が上がるけどどうなんじゃろ

**Comment by CyberRex0** [comment]
> MetaService.tsを複数コピーして(`for i in {1..10};do cp test/unit/MetaService.{,$i.}ts;done`)動かすと落ちる確率が上がるけどどうなんじゃろ

クラッシュしなかった

**Comment by ikuradon** [comment]
依然として落ちる環境と落ちない環境の違いがよくわかりませんが、jsonldにパッチを当てたところ落ちなくなった気がするので貼っておきます
```
--- node_modules/jsonld/lib/jsonld.orig.js      2022-09-25 10:34:08.252571149 +0000
+++ node_modules/jsonld/lib/jsonld.js   2022-09-25 09:28:59.067598275 +0000
@@ -34,7 +34,7 @@
  * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  */
 const canonize = require('rdf-canonize');
-const platform = require('./platform');
+// const platform = require('./platform');
 const util = require('./util');
 const ContextResolver = require('./ContextResolver');
 const IdentifierIssuer = util.IdentifierIssuer;
@@ -1017,8 +1017,8 @@
        /* WebIDL API */
        jsonld.JsonLdProcessor = require('./JsonLdProcessor')(jsonld);
 
-       platform.setupGlobals(jsonld);
-       platform.setupDocumentLoaders(jsonld);
+       // platform.setupGlobals(jsonld);
+       // platform.setupDocumentLoaders(jsonld);
 
        function _setDefaults(options, {
                documentLoader = jsonld.documentLoader,
```

**Comment by cffnpwr** [comment]
色々やってたら落ちなくなったので報告します

`MetaService.ts`だけで落ちてる感じなのでこれを除いてJestを動かして見たら動いたので、このファイルが怪しいなという感じで色々してみました
どうやらファイル内にテストが1つもない状態が良くないらしく以下のような絶対成功するテストを追加して`yarn jest`を実行したら通りました

```ts
//  絶対に成功するテスト
it('alwaysCorrectTest', () => {
    expect(true).toBe(true);
});
```

以下環境です
OS: Ubuntu 22.04.1 LTS x86_64 
node: v18.9.1
yarn: 1.22.19
commit: df0a90f69f151b3a0a5d88f1dba2e502231d604c

**Comment by syuilo** [comment]
MetaServiceで落ちてるのはまた別の問題ですね
このIssueの内容としてはテスト実行中に突然exit code 1で異常終了するというもので、これはMetaServiceのテストファイルが無い状態でも再現します

**Comment by cffnpwr** [comment]
なるほど
自環境だと再現してないのでますます謎ですね

**Comment by massongit** [comment]
https://qiita.com/kawanet/items/cfedd535990b32710c50

ヒープ領域が不足している可能性があるかもしれないです。

**Comment by syuilo** [comment]
起きなくなった気がする？

**Comment by syuilo** [comment]
起きなくなった 🙏🏻
