### ISSUE TITLE
特定の条件で通報が見れない問題

### ISSUE THREAD

**Issue by GrapeApple0** [syuilo/Misskey#9100]
## 問題
特定の条件で通報が見れない問題が発生してます
![screenshot 222](https://user-images.githubusercontent.com/84321396/191450328-918447fb-ce42-43e7-9b88-38847020d837.jpg)

## 条件
こちらで条件を試した結果
`通報先:すべて,通報元: すべて`
`通報先:すべて,通報元: ローカル`
`通報先:リモート,通報元: ローカル`
の場合発生していました。

## 環境
問題が発生している環境は,
Misskey version: Misskey 12.119.0
Your OS: Client: Windows 10, Server: Ubuntu 22.04 LTS
Your browser: Chrome 105.0.5195.127
です

**Comment by atsu1125** [comment]
Try running this SQL

```
DELETE FROM "abuse_user_report" WHERE "targetUserId" NOT IN (SELECT "id" FROM "user")
```

```
ALTER TABLE "abuse_user_report" ADD CONSTRAINT "FK_a9021cc2e1feb5f72d3db6e9f5f" FOREIGN KEY ("targetUserId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
```

This may be same as https://github.com/misskey-dev/misskey/issues/9183 
Because of https://github.com/misskey-dev/misskey/commit/bec2d9e3fafd721f116066f6a7e3ff0507b27de9

**Comment by GrapeApple0** [comment]
Thanks for reply.
So, I tried this sql, but it sql cmd was error.(error msg  "ERROR:  relation "abuse_user_report" does not exist")

**Comment by GrapeApple0** [comment]
> Thanks for reply. So, I tried this sql, but it sql cmd was error.(error msg "ERROR: relation "abuse_user_report" does not exist")

Sorry, I had the wrong database connected.
And, It sql cmd is success.
