### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by mackiexx** [syuilo/Misskey#9119]
## Summary

It will be great to have pull to refresh in PWA because when you create a note, it doesn't show automatically on top and a pull to refresh is needed to fetch the post without having to close and open the app again. Also it will be nice if the new post can show in real time without having to close and open the app or refresh.

**Comment by ThatOneCalculator** [comment]
You can pull to refresh on Chromium-based PWAs. Pull to refresh behavior is dependent on the browser, not the website/pwa.

**Comment by Trif4** [comment]
Using the browser pull to refresh will refresh the whole app. That's overkill for just wanting your timeline to update.

Pull to refresh on the timeline is a very reasonable suggestion.

**Comment by syuilo** [comment]
やりたいけどまともなライブラリが無いため自前で実装する必要があり面倒

**Comment by syuilo** [comment]
https://github.com/BoxFactura/pulltorefresh.js/ はVueもしくはMisskey Webと相性が悪いのかレンダリングがおかしくなり動作しなかった

**Comment by syuilo** [comment]
VueのライブラリもあったけどVue3に対応してなかった

**Comment by syuilo** [comment]
> https://github.com/BoxFactura/pulltorefresh.js/ はVueもしくはMisskey Webと相性が悪いのかレンダリングがおかしくなり動作しなかった

というか要素指定に文字列(=セレクタ)しか渡せない点が嫌

**Comment by syuilo** [comment]
誰か実装する人おる？
いなければしゅいろさんがトライするけど

**Comment by EbiseLutica** [comment]
しゅいろさん任せた:pray:

**Comment by syuilo** [comment]
と思ったけど意外と複雑そう🥴

**Comment by u1-liquid** [comment]
もしかしたら参考になるかも
https://vant-contrib.gitee.io/vant/#/en-US/pull-refresh
https://github.com/youzan/vant/tree/main/packages/vant/src/pull-refresh
