### ISSUE TITLE
Docs for hosting misskey on fly.io

### ISSUE THREAD

**Issue by bil-ash** [syuilo/Misskey#9120]
## Summary

I would like to host a small misskey instance on fly.io free tier. Would be of great help if misskey and fly.io join hands to simplify the process. It will lead to gread adoption of misskey.
Related post on fly.io forum is at https://community.fly.io/t/host-misskey/7751

**Comment by ThatOneCalculator** [comment]
Why can't you just use the built-in Dockerfile?

https://fly.io/docs/languages-and-frameworks/dockerfile/

**Comment by bil-ash** [comment]
Some Context-
I recently hosted misskey on a VPS(for a month), but then stopped because my instance did not gain users and I felt I was overpaying for running misskey(on the VPS). 

I do not have much idea about docker. Still by reading the dockerfile what I understood is that the PG db, redis db and main app are bound together. I do not want that and instead want to use the pg(https://fly.io/docs/reference/postgres/) and redis(https://fly.io/docs/reference/redis/) offered by fly.io so that I do not have to worry about the databases and can scale one or the other component separately later on if needed.

**Comment by bil-ash** [comment]
Finally was able to host on fly.io . So closing the issue
