### ISSUE TITLE
Croping image loads forever

### ISSUE THREAD

**Issue by AidanTheBandit** [syuilo/Misskey#9124]
## 💡 Summary
When a user tries to crop an image for a profile picture or banner it loads forever

## 🥰 Expected Behavior

Should let the user crop and set the image

## 🤬 Actual Behavior

Loads forever

## 📝 Steps to Reproduce

1. Upload profile picture/banner
2. Try to crop the image

## 📌 Environment

Misskey version: 12.19.0
Your OS: Windows 11
Your browser: Firefox

**Comment by rinsuki** [comment]
Did you have a any error in browsers console?

**Comment by AidanTheBandit** [comment]
Yes the error is:
GET https://app.barkle.xy image.webp:1z/proxy/image.webp?url=https%3A%2F%2Fbarkle.us-east-1.linenodeobjects.com%Fbk_2Fb263e164-5885-4a12-9b79-bcbeb6cddcd1.png 500

**Comment by AidanTheBandit** [comment]
@Rinsuki any ideas?

**Comment by JohnnyEn** [comment]
Is the API returning any response with error mesaage? Did you tried to crop image on the other MK instance? Did you tried crop image on local environment? Is the bug replicable?

**Comment by AidanTheBandit** [comment]
In the console it posted this when I tried crop the image. The Misskey instance also fails to pull images from links too.

Oct 25 16:01:24 npm[38746]: INFO 1        [chart]        perUserFollowing: Write skipped
Oct 25 16:01:24 npm[38746]: INFO 1        [chart]        perUserDrive: Write skipped
Oct 25 16:01:24 npm[38746]: INFO 1        [chart]        apRequest: Write skipped
Oct 25 16:01:24 npm[38746]: INFO 1        [chart]        activeUsers(hour): New commit created
Oct 25 16:01:24 npm[38746]: INFO 1        [chart]        activeUsers: Updated
Oct 25 16:05:00 npm[38746]: INFO 1        [queue check-expired-mutings]        Checking expired mutings...
Oct 25 16:05:00 npm[38746]: DONE 1        [queue check-expired-mutings]        All expired mutings checked.
Oct 25 16:06:26 npm[38746]: INFO 1        [url-preview]        (Proxy) Getting preview of https://music.youtube.com/playlist?list=PLaY0MKbsH8vk-tIXPpa8vnIzYeY_7YWbp&feature=share@en-US ...
Oct 25 16:06:26 npm[38746]: DONE 1        [url-preview]        Got preview of https://music.youtube.com/playlist?list=PLaY0MKbsH8vk-tIXPpa8vnIzYeY_7YWbp&feature=share: Moosic 2022
Oct 25 16:06:27 npm[38746]: INFO 1        [download]        Downloading https://preview.webp ...
Oct 25 16:06:27 npm[38746]: ERR  1        [server]        RequestError: cacheableLookup ENOTFOUND preview.webp
Oct 25 16:06:27 npm[38746]: INFO 1        [download]        Downloading https://preview.webp ...
Oct 25 16:06:27 npm[38746]: ERR  1        [server]        RequestError: cacheableLookup ENOTFOUND preview.webp
Oct 25 16:06:27 npm[38746]: INFO 1        [url-preview]        (Proxy) Getting preview of https://music.youtube.com/playlist?list=PLaY0MKbsH8vkJnxkaIKCZoHyjd3kOwIqe&feature=share@en-US ...
Oct 25 16:06:27 npm[38746]: DONE 1        [url-preview]        Got preview of https://music.youtube.com/playlist?list=PLaY0MKbsH8vkJnxkaIKCZoHyjd3kOwIqe&feature=share: Menu music
Oct 25 16:06:27 npm[38746]: INFO 1        [download]        Downloading https://preview.webp ...
Oct 25 16:06:27 npm[38746]: ERR  1        [server]        RequestError: cacheableLookup ENOTFOUND preview.webp
Oct 25 16:06:28 npm[38746]: INFO 1        [download]        Downloading https://preview.webp ...
Oct 25 16:06:28 npm[38746]: ERR  1        [server]        RequestError: cacheableLookup ENOTFOUND preview.webp
Oct 25 16:07:04 npm[38746]: INFO 1        [download]        Downloading https://image.webp ...
Oct 25 16:07:04 npm[38746]: ERR  1        [server]        RequestError: cacheableLookup ENOTFOUND image.webp

**Comment by AidanTheBandit** [comment]
@JohnnyEn

**Comment by AidanTheBandit** [comment]
I fixed this by switching away from a .xyz domain

**Comment by EIREXE** [comment]
This issue is still happening, seems to happen to .moe domains too
