### ISSUE TITLE
Embedded WebM file fails to play on iPad

### ISSUE THREAD

**Issue by Koischappi** [syuilo/Misskey#9127]
## 💡 Summary
WebM video files fail to play on iPadOS browsers (WebKit).
The same videos play on desktop computers, and MP4 files play without issue.

## 🥰 Expected Behavior
Play an embedded WebM file within a post.

## 🤬 Actual Behavior
The length of the video is indicated as 0 seconds, and pressing "play" does not show a loading animation or the video itself. The only sign that the "play" action has been registered is a change in the icon.

## 📝 Steps to Reproduce

1. [Open this post (cw: spiders)](https://misskey.io/notes/96b38y1pyc) on an iPad internet browser.
2. Attempt to play it.

## 📌 Environment

Misskey version: 12.118.1
Your OS: iPadOS 15.6.1
Your browser: Safari, Google Chrome

**Comment by pixeldesu** [comment]
Safari on iOS/iPadOS does not support WebM.

**Comment by Koischappi** [comment]
I see. Thank you for your prompt answer and apologies.
