### ISSUE TITLE
Blocking may not remove remote follower

### ISSUE THREAD

**Issue by atsu1125** [syuilo/Misskey#9137]
## 💡 Summary
In some cases Blocking do not remove remote follower.

As per UserBlockingService, Misskey send UndoFollow to AP if blocker is following Remote blockee. 
However Misskey do not send RejectFollow to AP if blocker is followed by Remote blockee, and remove blockee from follower internally. 
Misskey surely send Block to AP if blockee is remote, 
but It's not sure blockee instance do UndoFollow when they receive Block from Remote, and blockee may see private statuses of blocker.

For Mastodon, she sends RejectFollow if blocker is followed by blockee.
https://github.com/mastodon/mastodon/blob/main/app/services/block_service.rb

## 🥰 Expected Behavior
Blocking remove follower

## 🤬 Actual Behavior
Blocking may not remove follower

Misskey version: v12.117.1

**Comment by mei23** [comment]
PleromaとかGNU socialあたりが、Block, UndoFollowだけではなくRejectFollowも送ってあげないとフォロー解除されないらしい。

**Comment by mei23** [comment]
> As per UserBlockingService, Misskey send UndoFollow to AP if blocker is following Remote blockee.
> PleromaとかGNU socialあたりが、Block, UndoFollowだけではなくRejectFollowも送ってあげないとフォロー解除されないらしい。

現状ブロック時にリモートフォロワーに対してはUndoFollowは送ってない。
(Blockは送ってる。送ってるのはこっちからフォローしていた場合のUndoFollow。)
