### ISSUE TITLE
Web UI bug for 'clips' in user profiles

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#9144]
## 💡 Summary

The Web UI for 'clips' in user profiles looks really weird. It seems like no codes have been written for it to specify how it should appear in the interface.

## 🥰 Expected Behavior
I expect the UI should look like that of 'pages'. 

<img width="921" alt="Screen Shot 2022-11-06 at 9 12 03 am" src="https://user-images.githubusercontent.com/106132975/200143366-397dbadd-d47f-4ca4-ba44-93ed5e5e1432.png">

## 🤬 Actual Behavior

But actually it looks like this. FYI, 'new' and 'test' are two different clips. However, they appear in the same line and I think each one of them should have their own section just like how the 'pages' interface looks.

<img width="918" alt="Screen Shot 2022-11-06 at 9 12 16 am" src="https://user-images.githubusercontent.com/106132975/200143404-b62d8425-5225-4861-abf2-b3f8ff77b04c.png">

## 📝 Steps to Reproduce

1. create two or more public clips
2. click on your profile
3. click on 'clips' 

## 📌 Environment

Misskey version: 12.119.0
Your OS: MacOS
Your browser: Chrome

**Comment by futchitwo** [comment]
fixed by #9179
