### ISSUE TITLE
cant install due to node version

### ISSUE THREAD

**Issue by hacknorris-code** [syuilo/Misskey#9149]
## 💡 Summary

yarn checks for exact version of node just to fail due cause of too new version

## 🥰 Expected Behavior

yarn install completed, duh

## 🤬 Actual Behavior

look below ↓↓↓

## 📝 Steps to Reproduce

1. install dependencies (with software versions like below ofcourse)
2. create users and download - still okay
3. `yarn install`
4. wait about 30 secs
5. error like from [attachment](#attachment) - putted as file cause size about 1 mb so text couldnt fit =]

## 📌 Environment

1. misskey version - this from docs (you caught a noob)
2. OS - slackware 15 (linux, no systemd, manual compiling like on gentoo)
3. node version - 19.0.1
6. postgres version - 14.3
7. yarn version - 1.22.10

## attachment:

[damnode.txt](https://github.com/misskey-dev/misskey/files/9953875/damnode.txt)

when they will learn about security...

**Comment by tamaina** [comment]
Please use node.js v18 as Misskey has not been tested at all with node.js v19.

It is good information that Misskey breaks in node.js v19. Thank you very much.

**Comment by hacknorris-code** [comment]
its more a security issue XD

**Comment by okpierre** [comment]
> its more a security issue XD

@hacknorris-aka-penguin please share what security issue

Node.js 18.x.x is considered long term support (LTS) and will be supported until April 2025

**Comment by hacknorris-code** [comment]
anyway - now having installed. got problems with postgres. moment, just lemme go into #discussions =]

**Comment by KisaragiEffective** [comment]
triage: 2024.5.0 requires v20 series or v22 series.
