### ISSUE TITLE
ノートのどこでもクリックすることで詳細画面に遷移する機能 / Ability to click anywhere in the note to go to the detail screen

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#9154]
## Summary

現在のTwitterやMastodonは投稿時間のリンクだけではなく、投稿のどこをクリックしても詳細画面に遷移するようになっています。
一方現在のMisskeyは投稿時間のリンクでしか遷移できないため、（特にTwitterスマホアプリを常用している人は）詳細画面を表示する方法が分かりにくいです。
（余談ですが、自分も昔はリンクから詳細画面に遷移できることに気づかず、一度Misskeyを辞めたことがあります）
なので、Misskeyも他と同じように、投稿の任意の場所をクリックして詳細画面に遷移できるようになると良いと思います

**Comment by KawaneRio** [comment]
どこでも押せるのはたしかに わかりやすいが、閒違ひ押しが増し、使ひやすさが下がると思ふ。（by どこでも押せるのは嫌ひな人）

初心者案内にての 解説に 「ノートの投稿時閒をクリックすると返信が見れます♪」などを 挾むはうが 良いのでは？と考へてみたり。

**Comment by futchitwo** [comment]
オプションでオンオフ出来るようにする手もある
（ただ現時点でオプショナルな機能が多すぎるので無闇に増やしたくない）

初心者案内への表示は一番実装が楽そうだけど使い勝手は変わらないし根本的な解決になっているかと言われたら微妙な気も…？

**Comment by acid-chicken** [comment]
Duplicate of #8804

**Comment by KawaneRio** [comment]
> オプションでオンオフ出来るようにする手もある

個人的にはこちらのほうが理想的だけど...（實裝の手間） :zzz:
