### ISSUE TITLE
長い名前を設定している状態でスレッドを開くと名前のフォントサイズが大きくなる

### ISSUE THREAD

**Issue by na2204** [syuilo/Misskey#9155]
## 💡 Summary
絵文字を含んだ長い名前を設定するとスレッド画面で名前やIDのフォントサイズが大きくなります。

## 🥰 Expected Behavior
フォントのサイズが変わらない(収まりきらない部分は削る)

## 🤬 Actual Behavior
名前やIDのフォントサイズが大きくなっていく。

`通常時`
![image](https://user-images.githubusercontent.com/78205092/200849470-3023d33a-15e0-4756-bef5-f0c61571e98a.jpeg)

`長い名前`
![image](https://user-images.githubusercontent.com/78205092/200849707-ae287604-b4c8-49a2-b36e-4d18b9299a32.jpeg)

`絵文字を含んだ長い名前`
![image](https://user-images.githubusercontent.com/78205092/200849591-3078472e-2d9c-42da-8c7f-af7f3966e6fc.jpeg)

## 📝 Steps to Reproduce

1.絵文字を含んだ状態で長い名前を設定する(26文字程度)
2.適当な投稿をする
3.スレッドを表示する

## 📌 Environment

Misskey version:12.119.0
Your OS: iOS16.1
Your browser: Safari

**Comment by tamaina** [comment]
- developで直っているか確認お願いします
- 絵文字の種類を教えていただけるとありがたいです(カスタム絵文字なのか、TwEmojiなのか、OS標準の絵文字か)
