### ISSUE TITLE
Cant signup when any captcha is enabled

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#9157]
## 💡 Summary

Cant signup when captcha is enabled

## 🥰 Expected Behavior

You signup and it works

## 🤬 Actual Behavior

It does nothing when you click begin

## 📝 Steps to Reproduce

1. Install misskey as specified in the docs for docker
2. Enable a captcha service, ReCaptcha, HCaptcha, Turnstile etc
3. Try signing up

## 📌 Environment

Misskey version: 12.120.0-alpha.7
Your OS: Arch Linux for the server MacOS 13 and Windows 11 for the clients
Your browser: Chromium

If anyone can help it would be appreciated.

**Comment by tamaina** [comment]
Fixed by https://github.com/misskey-dev/misskey/commit/dd93a07c0f89d6be1b297d23a3d22ac9c6588498
