### ISSUE TITLE
MFMルビ振《ぶ》り 機能《きのう》🙏🙏🙏 | Make <ruby> tag usable in MFM

### ISSUE THREAD

**Issue by KawaneRio** [syuilo/Misskey#9161]
\$\ \$
## <ruby>Misskey<rp>《</rp><rt>ミスキー</rt><rp>》</ruby>に、<ruby>留備<rp>《</rp><rt>るび</rt></ruby>を。
HTMLの`<ruby>`<ruby>系<rp>(</rp><rt>けい</rt><rp>)</rp></ruby>はすっっごく<ruby>面倒<rp>(</rp><rt>めんどう</rt><rp>)</rp></ruby>といはれてゐることは<ruby>承知<rp>(</rp><rt>しょうち</rt><rp>)</rp></ruby>してをりますが、それでもMFMにルビ<ruby>振<rp>(</rp><rt>ぶ</rt><rp>)</rp></ruby>り<ruby>機能<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby>を<ruby>實裝<rp>(</rp><rt>じっさう</rt><rp>)</rp></ruby>していただきたければすっっっごく<ruby>嬉<rp>(</rp><rt>うれ</rt><rp>)</rp></ruby>しく<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>ひます。

### <ruby>實裝例<rp>(</rp><rt>じっさうれい</rt><rp>)</rp></ruby>１：<ruby>青空文庫方式<rp>《</rp><rt>あおぞらぶんこほうしき</rt><rp>》</rp></ruby>

<ruby>下記<rp>《</rp><rt>かき</rt><rp>》</rp></ruby>にて[<ruby>硫酸鶏<rp>《</rp><rt>acid-chicken</rt><rp>》</rp></ruby><ruby>氏<rp>《</rp><rt>し</rt><rp>》</rp></ruby>が twista に<ruby>實裝<rp>《</rp><rt>じっさう</rt><rp>》</rp></ruby>してた](https://github.com/misskey-dev/misskey/issues/9161#issuecomment-1311397602)り、[<ruby>tar-bin<rp>《</rp><rt>たーびん</rt><rp>》</rp></ruby><ruby>氏<rp>《</rp><rt>し</rt><rp>》</rp></ruby>がノベルスキーに<ruby>實裝<rp>《</rp><rt>じっさう</rt><rp>》</rp></ruby>してゐる](https://github.com/misskey-dev/misskey/issues/9161#issuecomment-1480470451)<ruby>方式<rp>《</rp><rt>はうしき</rt><rp>》</rp></ruby>です。
`｜漢字《かんじ》`のやうに<ruby>記述<rp>《</rp><rt>きじゅつ</rt><rp>》</rp></ruby>します。<ruby>樣〻<rp>《</rp><rt>さまざま</rt><rp>》</rp></ruby>な<ruby>小説投稿<rp>《</rp><rt>しょうせつとうかう</rt><rp>》</rp></ruby><ruby>網場<rp>《</rp><rt>サイト</rt><rp>》</rp></ruby>でも<ruby>使<rp>《</rp><rt>つか</rt><rp>》</rp></ruby>はれてをり、<ruby>現在<rp>《</rp><rt>げんざい</rt><rp>》</rp></ruby>、<ruby>世界<rp>《</rp><rt>せかい</rt><rp>》</rp></ruby>で<ruby>最<rp>《</rp><rt>もっと</rt><rp>》</rp></ruby>も<ruby>廣<rp>《</rp><rt>ひろ</rt><rp>》</rp></ruby>く<ruby>用<rp>《</rp><rt>もち</rt><rp>》</rp></ruby>ゐられてゐる<ruby>形式<rp>《</rp><rt>けいしき</rt><rp>》</rp></ruby>かと<ruby>思<rp>《</rp><rt>おも</rt><rp>》</rp></ruby>ひます。

### <ruby>實裝例<rp>(</rp><rt>じっさうれい</rt><rp>)</rp></ruby>２：HTMLの`<ruby>`タグをそのまま<ruby>輸入<rp>《</rp><rt>ゆにゅう</rt><rp>》</rp></ruby>
HTMLの`<ruby>`<ruby>系<rp>(</rp><rt>けい</rt><rp>)</rp></ruby>を<ruby>全部<rp>(</rp><rt>ぜんぶ</rt><rp>)</rp></ruby>MFMで<ruby>使用可能<rp>(</rp><rt>しようかのう</rt><rp>)</rp></ruby>にしてあげるほうです。

<ruby>具体的<rp>(</rp><rt>ぐたいてき</rt><rp>)</rp></ruby>には、ノートに「`<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>`」って<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>くと「<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>」って<ruby>表示<rp>(</rp><rt>ひょうじ</rt><rp>)</rp></ruby>してくれる<ruby>方<rp>(</rp><rt>ほう</rt><rp>)</rp></ruby>です。</p><p><ruby>利用者<rp>(</rp><rt>りようしゃ</rt><rp>)</rp></ruby>さんにとって<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>くのはちょっぴり<ruby>面倒<rp>(</rp><rt>めんどう</rt><rp>)</rp></ruby>です<s>が、それでも \$\LaTeX\$ の<ruby>力<rp>(</rp><rt>ちから</rt><rp>)</rp></ruby>で<ruby>無理矢理<rp>(</rp><rt>むりやり</rt><rp>)</rp></ruby>ルビっぽいものを<ruby>作<rp>(</rp><rt>つく</rt><rp>)</rp></ruby>るよりは<ruby>簡<rp>(</rp><rt>かん</rt><rp>)</rp></ruby><ruby>單<rp>(</rp><rt>たん</rt><rp>)</rp></ruby>だと<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>ひます</s> <b>Misskey v13 の<ruby>版上<rp>《</rp><rt>ばんあ</rt><rp>》</rp></ruby>げ(Version Update)に<ruby>伴<rp>《</rp><rt>ともな</rt><rp>》</rp></ruby>ひ、</b> \$\LaTeX\$ <b>での<ruby>留備<rp>《</rp><rt>るび</rt><rp>》</rp></ruby><ruby>振<rp>《</rp><rt>ぶ</rt><rp>》</rp></ruby>りは<ruby>使用不可能<rp>《</rp><rt>しようふかのう</rt><rp>》</rp></ruby>となりました。<ruby>今一度<rp>《</rp><rt>いまいちど</rt><rp>》</rp></ruby>、この<ruby>機能<rp>《</rp><rt>きのう</rt><rp>》</rp></ruby>をご<ruby>檢討<rp>《</rp><rt>けんとう</rt><rp>》</rp></ruby>いただければ<ruby>幸<rp>《</rp><rt>さいは</rt><rp>》</rp></ruby>ひです🙇</b>

<ruby>上記<rp>《</rp><rt>じゃうき</rt><rp>》</rp></ruby>にて<ruby>紹介<rp>《</rp><rt>しょうかい</rt><rp>》</rp></ruby>した<ruby>青空文庫方式<rp>《</rp><rt>あをぞらぶんこはうしき</rt><rp>》</rp></ruby><ruby>及<rp>《</rp><rt>およ</rt><rp>》</rp></ruby>びHTMLのrubyタグ<ruby>方式<rp>《</rp><rt>はうしき</rt><rp>》</rp></ruby>はなんと<ruby>兩者<rp>《</rp><rt>りゃうしゃ</rt><rp>》</rp></ruby>とも[ノベルスキー](https://novelskey.tarbin.net/@tar_bin/pages/1679502043059)（Misskey v13.10.2）にて<ruby>實裝<rp>《</rp><rt>じっさう</rt><rp>》</rp></ruby>されてゐるやうです。

<ruby>网上<rp>(</rp><rt>あみうへ</rt><rp>)</rp></ruby>には<ruby>自動<rp>(</rp><rt>じどう</rt><rp>)</rp></ruby>で<ruby>留備<rp>(</rp><rt>るび</rt><rp>)</rp></ruby>を<ruby>振<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>ってくれるところがありますので、それと<ruby>合<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>はせてMisskeyを<ruby>使<rp>(</rp><rt>つか</rt><rp>)</rp></ruby>へばもう<ruby>最強<rp>(</rp><rt>さいきょう</rt><rp>)</rp></ruby>になれると<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>ひます。

# 
　

<ruby>日本<rp>(</rp><rt>にほん</rt><rp>)</rp></ruby><ruby>製<rp>(</rp><rt>せい</rt><rp>)</rp></ruby>SNSであるMisskeyにて「<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>に<ruby>文字<rp>(</rp><rt>もじ</rt><rp>)</rp></ruby>を<ruby>振<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>る」といふこの<ruby>美<rp>(</rp><rt>うつく</rt><rp>)</rp></ruby>しき<ruby>日本<rp>(</rp><rt>にほん</rt><rp>)</rp></ruby>の<ruby>文化<rp>(</rp><rt>ぶんか</rt><rp>)</rp></ruby>をどうかこの<ruby>機<rp>(</rp><rt>き</rt><rp>)</rp></ruby>に<ruby>加<rp>(</rp><rt>か</rt><rp>)</rp></ruby>へていただけると<ruby>本當<rp>(</rp><rt>ほんたう</rt><rp>)</rp></ruby>に<ruby>助<rp>(</rp><rt>たす</rt><rp>)</rp></ruby>かります。

どうかご<ruby>檢討<rp>(</rp><rt>けんとう</rt><rp>)</rp></ruby>をよろしくおねがいします🙇

**Comment by acid-chicken** [comment]
Related to c7272e4d15ce5c94e722f539da1066e35e9e5c38

**Comment by KawaneRio** [comment]
もう舞臺裏にて實裝中だと・・・！？

**Comment by acid-chicken** [comment]
舞台裏でもなんでもなく、当時 fork だった twista で 3 年半前にルビ機能が実装されました。
その構文は `｜明日《あした》` といった形式でしたが、これは青空文庫のマークアップに由来しており（<https://www.aozora.gr.jp/aozora-manual/index-input.html#markup>）、パース処理の簡素化のために起点を `｜` で明示するように制約を強めていました。
（こっちに話が持ち込まれた記録がなかったので、備忘録として）

**Comment by KawaneRio** [comment]
なるほど。


...ちなみに青空文庫の`|漢字《かんじ》`は[小説家になろう](https://syosetu.com/man/ruby/)や[カクヨム](https://kakuyomu.jp/help/entry/notation)を初めとする多くの小説投稿网場にて使用されてゐる書記方式なので、それを導入するのは互換性がありてとっても良いことだと思ひます。

上記の`漢字(^かんじ)`といふ書き方は[デラング](https://dlt.kitetu.com/KNo.F85E/4686-BA7C)の[ルビ記法](https://dlt.kitetu.com/KNo.F85E/E74C-3FBF)に基づきてゐます。同じ漢字が續く場合は`|`ではなく` `(空白)で區切りをつけるので使ひやすく、`|《》`のかはりに`(^)`と`（＾）`の兩者を採用してゐるので打ちやすいといふ點があります。

**Comment by HarunaT** [comment]
漢󠄁字以外の文字にもルビを振りたい場合が有り得る事を考慮すると、ルビ振り開始位置が明示される青空文庫式記法の方が望󠄂ましい樣に思はれます。

**Comment by 417Nazuna** [comment]
「小説家になろう」をはじめとした、メジャーな小説投稿サイトでは青空文庫式記法が多く取り入れられている印象です。
唯一pixivは青空文庫式記法には対応していませんが、[青空文庫ルビ→pixiv 変換器](http://zonuexe.github.io/aozora-ruby-parser.js/)といったものがあります。

個人的には、一番やってもらいたいものから順番に言うと
1. 青空文庫式記法がそのまま使える
2. PixivのようにMisskey独自のルビ記法を採用するが、青空文庫式記法からMisskeyのルビ記法に変換する機能などのサポートがある
3. Misskey独自のルビ記法を採用する。変換などはユーザーでやってもらう、丸投げ。

といった感じですね。

**Comment by ghost** [comment]
ちょっとioでお見かけしたのでコメント。

私の運営サーバー(ノベルスキー)での独自実装ですが、こういう感じでいけました。
https://github.com/tar-bin/misskey/commit/3f8c2dda491ef9f5f1914f81c050334659f7539b

`packages/frontend/src/components/mfm.ts` への小規模なパッチで実現はできるかと思います。

**Comment by MineCake147E** [comment]
私から独自文法の提案です。
```
$[rb.t="ルビ" 流火]
```
<ruby>流火<rp>(</rp><rt>ルビ</rt><rp>)</rp></ruby>
ダブルクオーテーション囲いのテキストのパースや、一部文字のエスケープを実装する必要はありますが、既存構文の応用であるため、既存のパーサーとの相性も比較的良く、実装後の拡張も容易だと思います。

**Comment by yuriha-chan** [comment]
$[ruby 流火 ルビ] 方式だと実装が容易である上に、漢字と振り仮名両方にMFM装飾を適用可能てす。
https://github.com/misskey-dev/misskey/compare/develop...yuriha-chan:misskey:mfm-ruby-fn

**Comment by ghost** [comment]
> $[ruby 流火 ルビ] 方式だと実装が容易である上に、漢字と振り仮名両方にMFM装飾を適用可能てす。 [develop...yuriha-chan:misskey:mfm-ruby-fn](https://github.com/misskey-dev/misskey/compare/develop...yuriha-chan:misskey:mfm-ruby-fn)

ユーザにとっても開発者にとっても平易なすばらしい実装で、ルビ実装を熱望する身としてはもうこのままPRしていただいていいように思ってしまうのですが、この実装ではなにか問題などあるのでしょうか？
