### ISSUE TITLE
Add "details" link to note/note menu

### ISSUE THREAD

**Issue by fu5ha** [syuilo/Misskey#9164]
## Summary

Add a "detail" link to note element and note menu, i.e. the menu shown under "..." or on right click on a note. These links should have the same functionality as clicking on the time the note was posted, i.e. opening the note on the local instance for details.

![image](https://user-images.githubusercontent.com/887711/201386944-d1f86d97-807f-4d13-a94a-6e14be6f03c7.png)

As shown here, and also within the "..." menu.

## Why
Currently the only way to get to a note detail page is clicking on the time listed. This is not very intuitive or discoverable from a UX point of view.

**Comment by futchitwo** [comment]
closed by #9166
