### ISSUE TITLE
Cant upload images

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#9181]
## 💡 Summary

Cant upload images with out a crash

## 🥰 Expected Behavior

It stays online

## 🤬 Actual Behavior

The server refuses connections with this error in the logs
```
Error: read ECONNRESET at TCP.onStreamRead
```

## 📝 Steps to Reproduce

1. Get misskey 12.119.0 on docker
2. Upload an image
3. Get this error

## 📌 Environment

Docker (On Arch Linux), Behind Cloudflare Tunnels.

Misskey version: 12.119.0
Your OS: MacOS for the client Arch Linux for the server
Your browser: Chromium

**Comment by tamaina** [comment]
It has been quite some time, so we will close it. If the problem still persists, please reopen with more information.
