### ISSUE TITLE
”ERROR [builder 8/9] RUN yarn build “when I run docker-compose build

### ISSUE THREAD

**Issue by JiHeWeiHuan** [syuilo/Misskey#9230]
## 💡 Actual Behavior
[builder 8/9] RUN yarn build:
#0 0.428 yarn run v1.22.19
#0 0.466 $ yarn workspaces foreach run build && yarn run gulp
#0 0.616 **error Invalid subcommand. Try "info, run"**
#0 0.616 info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
#0 0.630 error Command failed with exit code 1.
#0 0.630 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## 📝 Steps to Reproduce

docker-compose build

## 📌 Environment

Misskey version:12.119.0(Master Branch)
Your OS:Win11 22h2

**Comment by nykma** [comment]
Same here. Yarn version `v1.22.19`.

**Comment by CyberRex0** [comment]
Now Misskey uses yarn v3 and build commands are changed for its version but yarn version in container is still v1.
v3's commands are not supported in v1.

**Comment by bharath-naik** [comment]
facing same issue here. Thanks in advance
