### ISSUE TITLE
Bundle all PrismJS languages

### ISSUE THREAD

**Issue by dakkar** [syuilo/Misskey#9233]
## Summary

Currently, code blocks only highlight "markup" languages (html&c), CSS, Javascript, and "clike". These are the ones that are bundled by default in prismjs.

It's possible to bundle more language highlight definitions, at the expense of a larger prismjs file: bundling all languages produces 564KB file.

Doing so is a bit tricky ([see my commit](https://github.com/misskey-dev/misskey/compare/develop...dakkar:misskey-thenautilus:code-highlight-all-languages)) but it works.

Is this a thing that could be merged?

**Comment by kakkokari-gtyih** [comment]
Not applicable as the highlighter has been changed to Shiki
