### ISSUE TITLE
"Unexpected token '<', "<!DOCTYPE "... is not valid JSON in the mail server settings undefined" and fails.

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#9243]
## 💡 Summary

When I set up the mail server and try to send a test message, I get the message "Unexpected token '<', "<!DOCTYPE "... is not valid JSON
undefined" and the mail server cannot be used.

Since I installed with systemd from bash below, updating with bash fails.
https://misskey-hub.net/docs/install/bash.html

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:12.119.0
Your OS:Ubuntu22.04
Your browser:Chrome and Brave

**Comment by tamaina** [comment]
Please reload the browser screen and try the email sending test again (don't expect it to resolve).

**Comment by PYU224** [comment]
It didn't change...

**Comment by PYU224** [comment]
遅くなりましたが解決しました。

**Comment by futchitwo** [comment]
closeして良さそうです
(バグの原因が結局わかっていませんが、解決したのならすでに修正済みか設定ミスによるものでしょうか？)

**Comment by PYU224** [comment]
Closeお願いします。
原因がサーバ側でメールが送れない設定になっていたと分かったので。

**Comment by futchitwo** [comment]
issue作成者はコメントボタンの左の close issue からclose できると思います
