### ISSUE TITLE
Sign up with Passkeys

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9249]
## Summary
トレンドらしいので

https://support.apple.com/ja-jp/guide/iphone/iphf538ea8d0/ios  
https://fidoalliance.org/passkeys/?lang=ja

**Comment by tamaina** [comment]
パスキー、結局AppleかGoogleのキーチェーンに依存するので最悪じゃない？  
(トレンドだしWeb標準だし、AppleかGoogle(もしくはMozilla)のキーチェーンにパスワード保存するのもまあ他の手段よりはマシだとは思うので実装しようとは思うけど)

**Comment by Trif4** [comment]
WebAuthn allows you to use both passkeys and security keys, so users don't *have* to use a cloud keychain. But passkeys are much easier for people to use, so I think it will see more widespread adoption than security keys.

**Comment by ThatOneCalculator** [comment]
https://github.com/teamhanko/hanko + https://simplewebauthn.dev/ might be a useful reference

**Comment by tamaina** [comment]
詳しいドキュメント全く読んでないけどWebAuthnの経路で普通にPasskeyの登録・認証ができるようだ  

Safariではできるが、Chromeでは問題がある

**Comment by syuilo** [comment]
done
