### ISSUE TITLE
Specifying forbidden words

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#9257]
## Summary

I want you to be able to set prohibited words because vandalism comes out.

**Comment by PYU224** [comment]
I would like you to make it so that prohibited words cannot be posted or account registered, or that prohibited words can be replaced.

**Comment by KawaneRio** [comment]
Why not just use [Word Mute](https://misskey.io/settings/word-mute)? If you don't even wanna see the note, you can set it as a "Hard" mute.

**Comment by MomentQYC** [comment]
I think this may cause unnecessary trouble for ordinary users, it should be set to specify the vocabulary, when detected in the local timeline can be submitted to the administrator for review, but at the same time the relevant content should be able to be published normally.

> Why not just use [Word Mute](https://misskey.io/settings/word-mute)? If you don't even wanna see the note, you can set it as a "Hard" mute.

There may be problems such as harassment from gambling ads.

**Comment by PYU224** [comment]
Because I want to restrict some users from annoying other users by saying words they don't understand.

**Comment by tamaina** [comment]
As an instance administrator, I know you want to set a forbidden word, and I agree with you that it would be a good idea to implement it.

**Comment by PYU224** [comment]
I'm not familiar with programming languages, so I would like to ask the people involved in the development of Misskey to implement prohibited word restrictions.

**Comment by tamaina** [comment]
ローカルユーザーの投稿だけを検査するなら

1. データベースのMetaエンティティに禁止ワード設定カラムを作る
2. admin/update-metaで設定できるようにする
3. notes/createでtext, cw, pollあたりを検査して禁止ワードがあったらエラーにして投稿できないようにする

の3つがあればいいと思うので割と簡単

**Comment by PYU224** [comment]
難しいですね・・・それにユーザーの名前も制限する必要があります。

**Comment by tamaina** [comment]
ユーザーの名前の変更のAPIはi/update

**Comment by PYU224** [comment]
それはよく分からないのですがコンソールからDBにアクセスしていじれるんですか？

**Comment by tamaina** [comment]
いいえ本体を改造してください

**Comment by tamaina** [comment]
（本体改造が面倒ならアンテナ機能で手動(もしくは自動)でいい感じにできるかもしれません）

**Comment by PYU224** [comment]
本体を改造する必要があるんですか？
アンテナ機能とは検索しても出てこない機能ですね。調べてみます。

**Comment by PYU224** [comment]
検索してまだ結果は出ませんが、上記のNGワードは要望として出しますね。

**Comment by syuilo** [comment]
指定した文字列が含まれる投稿の公開範囲を自動でホームにする機能は実装された

**Comment by PYU224** [comment]
ありがとうございます。

**Comment by t1nyb0x** [comment]
問題なさそうでしたので、クローズさせていただきます。
何かありましたら、リオープンお願い致します。

**Comment by KisaragiEffective** [comment]
↑ #13207
