### ISSUE TITLE
I can't add an avatar to my Misskey profile settings

### ISSUE THREAD

**Issue by aasandr0** [syuilo/Misskey#9271]
**Environment**:

Win10
Brave Desktop v1.46.134, (Chromium to 108.0.5359.94)
Misskey version: 12.119.2
OS: Debian 11, kernel version and architecture: 5.10.0-19-amd64 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Steps**:

1. Log in to your user account;
2. Go to profile settings, at: https://$instance.tld/settings/profile
3. Click on the button responsible for the "Change avatar" function
4. Select a photo.

**Expected result**: the photo is uploaded to the user's drive and set as an avatar;

Actual result: the photo is uploaded to the user's drive, but the avatar is not changed and remains in the "eternal download.
![image](https://user-images.githubusercontent.com/119762559/205479249-8b144c85-b797-42a3-b732-9f5ea7ec1c54.png)
![image](https://user-images.githubusercontent.com/119762559/205479261-aa39ab6a-37af-4ae7-a347-2bdd13c625b2.png)

**Comment by kinkuroai** [comment]
Just here to confirm that on v12.119.2 anything cropping related - not only avatars - gets stuck loading (cropping avatars, banners, etc).

**Comment by tamaina** [comment]
再現しないためclose
