### ISSUE TITLE
Firefox can’t establish websocket connection

### ISSUE THREAD

**Issue by creamlike1024** [syuilo/Misskey#9272]
## 💡 Summary

Firefox cannot establish websocket connection with most misskey instance

The error message is similar to https://github.com/misskey-dev/misskey/issues/3652 But the problem is still exist after using the nginx configuration provided by this issue.

## 🥰 Expected Behavior

Firefox can auto refresh timeline and no websocket error in console.

## 🤬 Actual Behavior

Browser console exports a lot of errors of `Firefox can’t establish a connection to the server at wss://...` and `The connection to wss://... was interrupted while the page was loading.`

And the timeline do not auto refresh

![image](https://user-images.githubusercontent.com/25699126/205498358-ac3c259c-f137-410a-8e56-77d9dabf6b51.png)

Everything is OK with Chrome108

## 📝 Steps to Reproduce

1. Open misskey instance (e.g misskey.io)
2. Press F12 to open development tool, switch to console

## 📌 Environment

Misskey version:
Your OS: Linux 6.0.11
Your browser: Firefox 107.0.1

**Comment by tamaina** [comment]
@icedtangerine7 Your token is leaked.

Do `Regenerate login token` in Settings > Security immediately.

**Comment by tamaina** [comment]
スクショでトークン漏れてると思ったけどそもそもトークンなかった

**Comment by tamaina** [comment]
I'm using Firefox 107.0.1 on macOS 13.0.1, I have never experienced such streaming problems at all.

There is no token(i) with the wss requests, does this happen even if you are logged in?

**Comment by creamlike1024** [comment]
> I'm using Firefox 107.0.1 on macOS 13.0.1, I have never experienced such streaming problems at all.
> 
> There is no token(i) with the wss requests, does this happen even if you are logged in?

Oh I'm very sorry this problem should be on my side. I tested with another windows device and there is no problem. It suddenly occurred to me that this issue may be caused by some of my network proxy settings.

Sorry to bother you.
