### ISSUE TITLE
Detect AVIF as an image file

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9275]
## Summary

Uploading an AVIF file is possible, but it's not detected as an image and generates no preview.

It's now supported by Safari 16, so maybe a good time to support it.

**Comment by saschanaz** [comment]
Might also be worth to change the compression format? That's a different issue, though.

https://github.com/misskey-dev/misskey/blob/c0c23b135c036326b5c846d7c4d2d07753520ec2/packages/client/src/scripts/upload.ts#L19-L23

**Comment by tamaina** [comment]
> Might also be worth to change the compression format?

I agree, but the compression uploaded from the browser depends on the implementation of HTMLCanvasElement.toDataURL() and the server generated webpublic must be Mastodon readable.

**Comment by saschanaz** [comment]
I think Mastodon now supports AVIF as of 4.0, but let's open a separate issue for that.
