### ISSUE TITLE
Add a way to compress PNG images when uploading

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9277]
## Summary

I just set my profile header image from Snipping Tool on Windows, which generates PNG image by default. That caused a big 1 MB header. I don't want to let any visitors to download that much just for a silly header image.

It seems PNG is never compressed per the following code, if I'm reading right:

https://github.com/misskey-dev/misskey/blob/c0c23b135c036326b5c846d7c4d2d07753520ec2/packages/client/src/scripts/upload.ts#L19-L23

Maybe PNG should also be compressed by default since there is an explicit flag to opt-out?

**Comment by tamaina** [comment]
Client compression of png is disabled because apng cannot be processed (correctly, the processing implementation was put off).

https://github.com/misskey-dev/misskey/pull/8216

**Comment by tamaina** [comment]
MEMO

[How to identify whether webp image is static or animated?](https://stackoverflow.com/questions/45190469/how-to-identify-whether-webp-image-is-static-or-animated)
