### ISSUE TITLE
Tooltips for visibility indicators

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9285]
## Summary

![1 minute(s) ago 🔒, 8 minute(s) ago 🏠, 10 minute(s) ago](https://user-images.githubusercontent.com/3396686/205705537-ece6fc52-6a5e-4793-ab77-7aad820af7ef.png)

Those lock and home icons are not super intuitive especially for newcomers, maybe some mouse tooltips can help?

**Comment by ssmucny** [comment]
This should be a simple addition. I would need the issued assigned to me though.

**Comment by syuilo** [comment]
done
