### ISSUE TITLE
docker run have been failed since yarn v3 introduced

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9291]
```
$ npm run migrateandstart

> yarn migrate && yarn start

Error: The project in /misskey/package.json doesn't seem to have been installed - running an install there might help
```

## Reason
~~DockerfileのCOPYはシンボリックリンクをコピーしてくれない（原理上することができなさそう）~~

~~docker run時にyarn installを改めて走らせるのはちょっと…~~

**Comment by tamaina** [comment]
@rinsuki @acid-chicken @ThatOneCalculator なんとかして

**Comment by acid-chicken** [comment]
Related to https://github.com/misskey-dev/misskey/pull/8764#issuecomment-1152926470

**Comment by ThatOneCalculator** [comment]
> ```
> Error: The project in /misskey/package.json doesn't seem to have been installed - running an install there might help
> ```

That error can occur when you accidentally run `yarn` in the directory below the miskey dir. Run `cd ..` and remove .yarn, node_modules, .yarnrc.yml, etc

**Comment by tamaina** [comment]
.yarn/cacheすらコピーしてなかったわ

**Comment by tamaina** [comment]
docker run時にyarn installを改めて走らせるのは最終手段だよね…

**Comment by tamaina** [comment]
.yarn/cacheは関係ないわ

**Comment by ThatOneCalculator** [comment]
Could you see if you can reproduce the issue with Calckey? I think the way Calckey implemented Yarn 3 is slightly different than that of Misskey.

**Comment by rinsuki** [comment]
.yarn/install-state.gz あたりが必要かも

**Comment by tamaina** [comment]
node_modulesの中身あったしシンボリックリンクではないらしい？

**Comment by tamaina** [comment]
> .yarn/install-state.gz あたりが必要かも

これがビンゴだと思う

**Comment by tamaina** [comment]
> > .yarn/install-state.gz あたりが必要かも
> 
> これがビンゴだと思う

ローカルでは動いたけどOktetoではダメだった

**Comment by tamaina** [comment]
https://codeberg.org/thatonecalculator/calckey/pulls/9020

Dockerfile訳わからんしこれパクるか

**Comment by tamaina** [comment]
Dockerfile理解した(ぇ)

alpineにしただけなのとあとはCMDをyarn migrateandstartに変えたのか

**Comment by rinsuki** [comment]
どこかのタイミングでシンボリックリンク先にするべきパスが変わることがある？
```
root@bfb96f24e2c0:/misskey# yarn run migrateandstart
Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". Cannot find package 'typeorm' imported from /misskey/packages/backend/ormconfig.js
    at CommandUtils.loadDataSource (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/node_modules/.store/typeorm-virtual-64a74d098c/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
root@bfb96f24e2c0:/misskey# ls -l packages/backend/node_modules/typeorm 
lrwxrwxrwx 1 root root 76 Dec  3 15:16 packages/backend/node_modules/typeorm -> ../../../node_modules/.store/typeorm-virtual-4475c43461/node_modules/typeorm
root@bfb96f24e2c0:/misskey# ls -l node_modules/.store | grep typeorm
drwxr-xr-x 3 root root 4096 Dec  7 21:48 typeorm-virtual-64a74d098c
```

**Comment by rinsuki** [comment]
これホストから packages/*/node_modules 持ってきちゃってるからか (直しておきます)

**Comment by tamaina** [comment]
> ホストから packages/*/node_modules 持ってきちゃってるから

あ〜、dockerignoreか

**Comment by tamaina** [comment]
とはいえdockerignoreはOktetoで動かないのとは関係ないかも（ホストでyarn installしているわけではないしnodeすらインストールしない）

**Comment by rinsuki** [comment]
それもそうだな (それはそうとして Okteto のログってどっかで見れるの)

**Comment by tamaina** [comment]
しゅいろに頼めば出てくる

https://github.com/misskey-dev/misskey/pull/9281#issuecomment-1338894633

**Comment by tamaina** [comment]
これなんで治ったんだっけ

**Comment by tamaina** [comment]
これなんで治ったんだっけ(2回目)

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/pull/9239

これかな
