### ISSUE TITLE
update-metaにやたら時間がかかる？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9299]
update-metaにやたら時間がかかる

タイムアウトしても送信した内容は適用されている

## 📌 Environment

Misskey version: 12.120.0-alpha.12

**Comment by tamaina** [comment]
admin/delete-accountも遅い？

**Comment by tamaina** [comment]
(ドライブも開けないし単にデータベースが遅いだけ？

あ、開けた

**Comment by tamaina** [comment]
リストにユーザー追加したときもなんとなく同じ感じ

（FastifyとPromiseの相性なのか、FastifyとnginxやCloudflareの相性が悪くて返事を返せてないのか、PromiseがResolveされていないのか…）

**Comment by syuilo** [comment]
あきうすきーで再現した
ローカルでも再現するか確認する

**Comment by tamaina** [comment]
うちのおま環かも

**Comment by syuilo** [comment]
ローカルでも再現したわ

**Comment by syuilo** [comment]
成功時にコンテンツを返さない(=HTTP 204)エンドポイントで起こっている可能性がありそう

**Comment by tamaina** [comment]
> 成功時にコンテンツを返さない(=HTTP 204)エンドポイントで起こっている可能性がありそう

通知のmark-all-as-readもだめ
