### ISSUE TITLE
ユニバーサルUI以外のUIで一部のスタイルが適用されない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9302]
![image](https://user-images.githubusercontent.com/7973572/206853876-120003a0-1e6d-45cf-bbb7-e0442f24ebee.png)

![image](https://user-images.githubusercontent.com/7973572/206853890-d5984ef9-0f7d-400d-b2a4-df7335789416.png)

Vite v4が関係しているかも？  
どのスタイルを読み込めていないのか把握できていない

Misskey version: v12.120.0-alpha.14
Your OS: macOS Ventura
Your browser: Chrome, Firefox, Safari

**Comment by syuilo** [comment]
ローカルでは再現しなかったわ
productionモードでビルドするとそうなるのかな

**Comment by tamaina** [comment]
@syuilo これと関係があるかわからないけどyarn.lockが正しいか確認してみてほしい

**Comment by tamaina** [comment]
developmentモードでもこうなるような…

**Comment by tamaina** [comment]
うん、NODE_ENV=developmentでもぶっ壊れる

**Comment by tamaina** [comment]
update depsはdevelopにプッシュした

**Comment by tamaina** [comment]
https://vitejs.dev/guide/migration.html#importing-css-as-a-string

順当に考えると原因これだろうなぁ

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/blob/bae7939d79a52983b714513794604d5a209f94cc/packages/backend/src/server/web/views/base.pug#L41

style.scssが読み込めていないのかなと思ってここをrel='stylesheet'にしてみたけどダメだった

**Comment by tamaina** [comment]
> style.scssが読み込めていないのかなと思ってここをrel='stylesheet'にしてみたけどダメだった

これやるとユニバーサルUIもぶっ壊れる

**Comment by tamaina** [comment]
iOS Safariだと問答無用で崩壊した

**Comment by tamaina** [comment]
これ`import baseStyle from '@/style.scss?inline';`でCSSをstringで取得して(baseStyleはstring)適当にstyle作って突っ込めってことなんか？

**Comment by tamaina** [comment]
そもそも使い方がおかしかった説（だからと言ってどうやってimportしようか悩むところではある）

**Comment by tamaina** [comment]
visitorで最初に一瞬だけ見えるこれってなんだろうか

![image](https://user-images.githubusercontent.com/7973572/206861014-346df76c-50b8-4408-9ae0-4a5962f43293.png)

**Comment by tamaina** [comment]
> visitorで最初に一瞬だけ見えるこれってなんだろうか

MkLoadingっぽい？

**Comment by tamaina** [comment]
ほう、MkLoadingやMkPageHeaderのCSSも欠けてる

ということはcomponents/globalもダメそう

**Comment by tamaina** [comment]
@/style.scssはcommon.vueで@use "../../style.scss";することにする

**Comment by tamaina** [comment]
> これimport baseStyle from '@/style.scss?inline';でCSSをstringで取得して(baseStyleはstring)適当にstyle作って突っ込めってことなんか？

Stackblitzのサンプルではimport './style.css'をガッツリ使っているのでそんなことはなさそう

![image](https://user-images.githubusercontent.com/7973572/206862520-13d2890f-0079-428b-a215-c1ca8fdd3cd9.png)

**Comment by tamaina** [comment]
> ローカルでは再現しなかったわ

これ怪奇現象なんだけど（Windowsだから再現しないの？？）

**Comment by CyberRex0** [comment]
macOSのSafariだと未ログイン時のトップページが崩れるだけで他は問題なかった

**Comment by syuilo** [comment]
> > ローカルでは再現しなかったわ
> 
> これ怪奇現象なんだけど（Windowsだから再現しないの？？）

あーデッキで再現した

**Comment by tamaina** [comment]
Minimum Reproductionから逃げてるんだけど誰か作って欲しい()

**Comment by tamaina** [comment]
Vite v4のせいではない説が濃厚になってきた

これのせい？  
https://github.com/misskey-dev/misskey/commit/2f9de0c7651d52adadcda8c17d3e523f4be7634d

**Comment by tamaina** [comment]
> Vite v4のせいではない説が濃厚になってきた
> 
> これのせい？ [2f9de0c](https://github.com/misskey-dev/misskey/commit/2f9de0c7651d52adadcda8c17d3e523f4be7634d)

これも違うっぽい

**Comment by tamaina** [comment]
コミット1つずつおってくか

206718032813c6dfde93e545d5b1e134784d2aa7 →動く

**Comment by tamaina** [comment]
c5213dddbf91e4f7dcc6af38e31abfe3b7ba09b0 →動かない ←犯人

**Comment by tamaina** [comment]
rollupOptions.outputを書けばreproductするかもしれないけど書くまでが面倒だわね

**Comment by tamaina** [comment]
https://vitejs.dev/config/build-options.html#build-modulepreload
>  it is necessary to manually import the polyfill in your custom entry:

I have overlooked this until now, this could be part of the cause
