### ISSUE TITLE
Links to local accounts don't show up in profile fields

### ISSUE THREAD

**Issue by tastytea** [syuilo/Misskey#9304]
## 💡 Summary

I want to link to my other account on the same server in a profile field. When i put it in like `@otheraccount@example.org` it works, but it is not clickable in Mastodon. When i put it in like `https://example.org/@otheraccount` it is clickable in Mastodon, but invisible on my local Misskey instance. However, it is visible on remote Misskey instances.

## 🥰 Expected Behavior

The link is shown

## 🤬 Actual Behavior

The I see this HTML for the field:

```html
<dl class="field" data-v-e348ec23="">
    <dt class="name" data-v-e348ec23="">
        <span class="havbbuyv" colored="false" data-v-64b45eac="" data-v-e348ec23="">lewd account</span>
    </dt>
    <dd class="value" data-v-e348ec23="">
        <span class="havbbuyv" colored="false" data-v-64b45eac="" data-v-e348ec23=""><!----></span>
    </dd>
</dl>
```

This is how it looks on my instance:

![screenshot on my instance](https://user-images.githubusercontent.com/3681516/206879268-d934b4a2-b79b-4ba2-b86c-35a1fbe0aa4b.png)

This is how it looks on another Misskey instance:

![screenshot on another Misskey instance](https://user-images.githubusercontent.com/3681516/206879417-c7a205f3-3671-44de-811c-05285a91d510.png)

## 📝 Steps to Reproduce

1. Add a link to another account in one of your profile fields
2. Look at your profile

## 📌 Environment

Misskey version: 12.119.2
Your OS: Gentoo Linux
Your browser: Firefox 102.5.0esr

**Comment by futchitwo** [comment]
Probably the same bug as #9142.
This has been fixed and will be reflected in the next update.

**Comment by tastytea** [comment]
Yes, that patch fixed it. Thank you! 💖
