### ISSUE TITLE
ハイライト廃止 / Remove Featured

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9306]
## Summary
結局炎上した投稿ばかりが上位にくるのでハイライトは廃止しよう

Related to #6019, #6050, #6839

**Comment by CyberRex0** [comment]
インスタンスによってハイライトが機能してるかどうかは異なるので、せめて機能として有効化無効化を選べるようにしたほうがいい

**Comment by marihachi** [comment]
改善する方向が良いと思う
ただでさえユーザーをみつける手段が少ないため

**Comment by tamaina** [comment]
廃止する必要はないか(メンヘラ)
