### ISSUE TITLE
init.tsのcreateAppでUIを出しわけず、UIを出し分けるSFCを作ってそれをcreateAppに食わせるように

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9310]
Viteのエラー対策

**Comment by syuilo** [comment]
ほぼ全てのコンポーネントの親が1つ増えることになるからパフォーマンス上の懸念があるけど気にするほどでもないか

**Comment by tamaina** [comment]
残念ながらこれは https://github.com/misskey-dev/misskey/issues/9302 の解消にならないらしい…

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/207034948-d81017b8-7a4b-4f78-83ad-63f4e5d1a1e5.png)

てか状況が悪化してない？
