### ISSUE TITLE
TLをPush型にする

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9325]
## Summary

DBへのリクエストを1でも減らしたい

**Comment by syuilo** [comment]
Redisはなかなかハードル高いからまずはnodeにキャッシュする？
ただ複数サーバーで運営しているインスタンスだと効果が少なくなる

**Comment by tamaina** [comment]
> まずはnodeにキャッシュする？

再起動したらすぐにパーになる

**Comment by syuilo** [comment]
RedisにTLをキャッシュ(というより構築)するデメリットとしては、TLを取得する際の負荷は劇的に減るけど代わりに投稿する際の負荷が今と比べてかなり高くなる

TwitterもMastodonもそういうTLの実装してるらしい(Push型というらしい)からそのデメリットよりメリットの方が上回るんだろうけど

**Comment by tamaina** [comment]
アンテナもPush型…だがちょっと負荷高いか

**Comment by syuilo** [comment]
あと単にデータベースにクエリ投げるだけじゃなくなるから実装も結構複雑になる

**Comment by syuilo** [comment]
負荷的にはユーザー全員がタイムラインというアンテナを持つようなものだと思っている

**Comment by syuilo** [comment]
TwitterやMastodonと違って、Misskeyはそれぞれのノートがリアクション情報を持っているからRedisにあるそれらも適宜更新する必要があるからちょっと他のソフトウェアとは事情が違うかも

**Comment by ikuradon** [comment]
FYI: Mastodonでの実装 https://github.com/mastodon/mastodon/blob/fdd1facba16db75e425c02807323eb2666688652/app/lib/feed_manager.rb

**Comment by syuilo** [comment]
> TwitterやMastodonと違って、Misskeyはそれぞれのノートがリアクション情報を持っているからRedisにあるそれらも適宜更新する必要があるからちょっと他のソフトウェアとは事情が違うかも

IDだけ置いとけばいいか

**Comment by tamaina** [comment]
なんならidでソートも可能

**Comment by syuilo** [comment]
> 負荷的にはユーザー全員がタイムラインというアンテナを持つようなものだと思っている

データベースにレコードを挿入するのとRedisに値を追加するのだったら後者の方が圧倒的に負荷は低いだろうからそこまで重くはないと思われる

ただローカルのフォロワーが100人いたら100回Redisにリクエスト投げなきゃいけないのかが気になる
1回のリクエストにまとめられるかな

**Comment by tamaina** [comment]
別の案

1. ユーザーごとの自身のノート一覧もRedisにためておく
2. フォローしている各ユーザーのノート一覧を結合してソートしてタイムラインとする  
    Push型のTLにはしない  
3. フォロー数が多いと結合ソートが大変かもしれないので、Push型TLを採用する？

（リストでも同様のことを行えそう）

**Comment by syuilo** [comment]
> ただローカルのフォロワーが100人いたら100回Redisにリクエスト投げなきゃいけないのかが気になる
1回のリクエストにまとめられるかな

まとめられないっぽい

**Comment by syuilo** [comment]
memo
![image](https://user-images.githubusercontent.com/4439005/217230745-4ae9a21a-07e5-46c4-8019-d2bac51ddcbd.png)

**Comment by tamaina** [comment]
添付ファイルありのみのTLもキャッシュしたさがある

**Comment by tamaina** [comment]
Renoteを積極的に表示しないようにするとなると意外とRenote周りの扱いがきわどいか、というかもういっそのことPostgreSQLにRenote保持しなくてよくねとすら思い始めてきた

**Comment by pantasystem** [comment]
RenoteをPostgresql上に保持しなかった場合通知周りの構造はどうなる感じでしょうか？
仮にPostgresql上に保持させないようにする場合
通知にRenoteのNoteを参照させるのではなく、Renote先のNoteを参照させるようになる感じでしょうか？

**Comment by acid-chicken** [comment]
MongoDB をキャッシュ用に使うのってどうだろう

**Comment by syuilo** [comment]
二種類DB扱うのアレだからPostgreSQLをキャッシュには使えないかな

**Comment by acid-chicken** [comment]
ポスグレへのアクセスを減らしたいのならポスグレでキャッシュ作るのが目的を満たしてるのかよくわからない

**Comment by syuilo** [comment]
別のポスグレにするとか

**Comment by acid-chicken** [comment]
確かに理論上可能だけどキャッシュみたいな捨てる前提のデータベースにマイグレーションとか too much すぎないかとか逆に運用の観点から二つ存在するのがややこしくならないかとかは気になる

**Comment by tamaina** [comment]
キャッシュとはいうものの、捨てる前提でRedisにタイムラインを蓄積していたらそれはそれで厄介な実装になりそう

**Comment by syuilo** [comment]
キャッシュというか「構築」の方が近いかも

**Comment by tamaina** [comment]
なのでRedisを永続化する必要があり、運用の観点的には面倒だと思う

**Comment by acid-chicken** [comment]
例えば MongoDB の Capped Collection (規定サイズを超えたら勝手にデータを捨てる) とかを想像している

**Comment by acid-chicken** [comment]
あー永続化するのか

**Comment by rinsuki** [comment]
> ポスグレへのアクセスを減らしたいのならポスグレでキャッシュ作るのが目的を満たしてるのかよくわからない

というよりかは複雑なタイムラインクエリが(恐らく)悪いので、ホームタイムラインの投稿IDだけを入れたテーブルを作って全投稿JOINしてもそっちのほうが早い気はする

**Comment by rinsuki** [comment]
> なのでRedisを永続化する必要があり、運用の観点的には面倒だと思う

1. そもそもジョブキューあるんだからRedisはもともと永続化されてないと困る
2. ホームタイムラインもどうせ新規投稿来たら構築し直されるので飛んでも最悪なんとかなる

**Comment by acid-chicken** [comment]
MongoDB での構想だけど timeline と note の 2 collection を作って insertMany で timeline (userId, type, notes をもつオブジェクト) の notes (noteId と userId をもつオブジェクト) に `$addToSet` していくとかを現在イメージしている

**Comment by acid-chicken** [comment]
> > ポスグレへのアクセスを減らしたいのならポスグレでキャッシュ作るのが目的を満たしてるのかよくわからない
>
> というよりかは複雑なタイムラインクエリが(恐らく)悪いので、ホームタイムラインの投稿IDだけを入れたテーブルを作って全投稿JOINしてもそっちのほうが早い気はする

永続化を前提に再考しててなんとなく納得した

**Comment by tamaina** [comment]
なんかこう、PostgreSQLでなんとかする方法を考えてほしいかも（容量と速度を考えつつ）

**Comment by rinsuki** [comment]
というかまあPostgreSQLに入れるのであればアンテナ周りの仕組み持ってきたらいい気はする

**Comment by acid-chicken** [comment]
アンテナが重いみたいな話の状況調査からやった方が良さそう

**Comment by pantasystem** [comment]
下記リンクのpdfがどこまで信頼できるかはわかりませんが
MongoDBとPostgreSQLのベンチマークのスコアの比較です。
RDB以外をキャッシュに選んでいる企業などが多いのはそれなりに理由があるのではないかと思われます。
https://info.enterprisedb.com/rs/069-ALB-339/images/PostgreSQL_MongoDB_Benchmark-WhitepaperFinal.pdf

またキャッシュの状態を永続化してしまうとRAM上にキャッシュするときと比較し他時に
キャッシュの状態に問題が発生した時にトラブルの解決が困難になるのではないでしょうか？

**Comment by rinsuki** [comment]
そもそもアンテナでやってるのでだめだったらアンテナがもうだめ

**Comment by pantasystem** [comment]
ioを運営している村上さんから使用していないアンテナを削除しほしいというお願いが出ているので
そういうこととも考えられるのではないでしょうか？

**Comment by rinsuki** [comment]
そもそもアンテナが重いの閲覧はindexがアンテナID→ノートIDになってなくてソートでインデックス使えないからな気がする (ある程度大規模なサーバー持ってないので知らないけど)
https://github.com/misskey-dev/misskey/blob/0691901345ac38a9374f3659a19cccb6d00e85c8/packages/backend/src/models/entities/AntennaNote.ts#L7

**Comment by rinsuki** [comment]
(単純にinsertが重いという話だったら知らんけど、まあホームタイムラインはどうせ following しか出ないのでアンテナで空条件入れられて全投稿insertよりはマシだと思う)

**Comment by acid-chicken** [comment]
開発者がこの問題を探索するには大規模なインスタンスに相当する DB がどのみち必要になりかねないし、ひとまずタイムラインの構築だけいろんなストアでやってみて実験した方が話が早そう

**Comment by syuilo** [comment]
テストした範囲では https://github.com/misskey-dev/misskey/pull/10106 で爆速になったから必要ない可能性

**Comment by tamaina** [comment]
アンテナだけはRedisに保存してもいい気がした

**Comment by syuilo** [comment]
アンテナとかチャンネル投稿は(IDだけ)Redisに置くようになった

**Comment by syuilo** [comment]
この流れで本丸のHTLもやっていきたい

**Comment by syuilo** [comment]
難しい

**Comment by syuilo** [comment]
1万のローカルフォロワーがいたら投稿するごとに1万リクエストをRedisに送信しなきゃいけないのはしんどそう
フォロワーのうちアクティブなユーザーだけに限るとしても、アクティブだけに絞る処理自体が若干重そうだし処理自体もキャッシュとの兼ね合いで複雑になってきそう

**Comment by syuilo** [comment]
1リクエストRedisに送る処理が1msだったとしても1ms*10000=10s間はNodeのプロセスが止まりそう

**Comment by syuilo** [comment]
よく考えたらアクティブなユーザーだけに限ったとしてもインスタンス規模によっては普通に1万以上はフォロワーがいるわね

**Comment by rinsuki** [comment]
* 別に送って応答待つところはawaitなので他のことができる
* Redis は bulk insert できたはず

**Comment by syuilo** [comment]
> 別に送って応答待つところはawaitなので他のことができる

待たなくても「送る」という処理自体が多少なりとも同期的に時間かからない？

> Redis は bulk insert できたはず

おー

**Comment by syuilo** [comment]
redis xadd bulk で調べても情報がない

**Comment by rinsuki** [comment]
bulk insert というかコマンドまとめて送るくんか https://github.com/luin/ioredis#pipelining

**Comment by rinsuki** [comment]
まあそんな遅さを気にするんだったら適当にキューに積んでやらせるとかでいいかもしれん

**Comment by syuilo** [comment]
あとこれをやって本当にパフォーマンス向上するのかが気になってる
投稿全体をRedisに載せられれば良いんだけど、リアクション情報が動的でそれは難しいからIDだけ載せる感じになるし

**Comment by acid-chicken** [comment]
こればっかりは実際にやったときの実測データが全てを語るので
考えすぎてもあまりみたいなのはあるかも

**Comment by yuriha-chan** [comment]
フォロワーの取得から各TLにIDを入れるまでLuaスクリプトでやる想定でどれくらい速度がでそうか実験
https://colab.research.google.com/drive/1incmhgdmhDuwefB8xCJLLVJq_EG-tQTg?usp=sharing
呼び出し側はほぼ負担なしで、redis側もフォロワー10kがたまに投稿するくらいなら一台でも捌けそうな印象（0.1秒とかくらい）

**Comment by tamaina** [comment]
LTLだけはpush型にしてもよかったのでは…

**Comment by tamaina** [comment]
というか混雑対策としてSTLとLTLをストリーミングのみにする（local-timeline/hybrid-timelineが空配列を返す）モードがあるとよさそう？

**Comment by tamaina** [comment]
というよりはストリーミングを先に繋いで後からapi叩いた結果を繋げばいいか

**Comment by syuilo** [comment]
やるか

**Comment by syuilo** [comment]
ミュートの考慮が面倒そう

**Comment by syuilo** [comment]
難しい

**Comment by syuilo** [comment]
ミュートはTL取得時に処理する

**Comment by syuilo** [comment]
ファイルが添付されたノートのみオプションが指定されている場合の対応も難しい
