### ISSUE TITLE
ChromeもしくはWindowsでPasskeyをキーとして登録しようとすると失敗する

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9344]
> publicKey.pubKeyCredParams is missing at least one of the default algorithm identifiers: ES256 and RS256. This can result in registration failures on incompatible authenticators. See https://chromium.googlesource.com/chromium/src/+/main/content/browser/webauth/pub_key_cred_params.md for details

https://github.com/misskey-dev/misskey/blob/4ecc42744c3c8b68e38f58bfe03919bf437f137a/packages/client/src/pages/settings/2fa.vue#L190

## Reproduction
1. セキュリティキーのキーを登録
2. パスワードを入力
3. Passkeyの登録を許可
4. 名前を入力
5. セキュリティキーを登録する
6. ぐるぐる (この時エラーが出て中断されている)

パスワードを間違えても何もメッセージが表示されないなど、WebAuthn周りのUIは何かと不親切なのでごっそり変えてしまいたい

## 📌 Environment

Misskey version: 12.120.0-alpha.15 (fork)
Your OS: macOS Ventura
Your browser: Google Chrome v108.0.5359.124（Official Build） （arm64）

**Comment by tamaina** [comment]
そもそもi/2fa/key-doneにself attestation is not supportedと言われるのが原因っぽい

```
{"error":{"message":"Internal error occurred. Please contact us if the error persists.","code":"INTERNAL_ERROR","id":"5d37dbcb-891e-41ca-a3d6-e690c97775ac","kind":"server","info":{"e":{"message":"self attestation is not supported","code":"Error","stack":"Error: self attestation is not supported\n    at Object.verify (file:///home/misskey/misskey/packages/backend/built/core/TwoFactorAuthenticationService.js:258:31)\n    at file:///home/misskey/misskey/packages/backend/built/server/api/endpoints/i/2fa/key-done.js:101:66\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ApiCallService.call (file:///home/misskey/misskey/packages/backend/built/server/api/ApiCallService.js:259:16)"}}}}
```

**Comment by tamaina** [comment]
WebAuthnわからんけどとりあえずUIだけはまともにするかというモチベーション

**Comment by tamaina** [comment]
Windows 11のPasskeyはサーバーがunsupported fmtと言う

**Comment by u1-liquid** [comment]
> Windows 11のPasskeyはサーバーがunsupported fmtと言う

related: #8691

**Comment by syuilo** [comment]
done
