### ISSUE TITLE
Can't see any reactions on notes

### ISSUE THREAD

**Issue by FunctionalHacker** [syuilo/Misskey#9360]
## 💡 Summary

I can't see any reactions to notes. I only have myself on my instance so it might be only on remote posts. I need to click "view in remote instance" to see any reactions

## 🥰 Expected Behavior

Reactions to notes should be shown

## 🤬 Actual Behavior

No reactions are shown. No errors on the server output.

## 📌 Environment

Misskey version: 12.119.2 (Docker)
Your OS: Arch Linux
Your browser: Librewolf

**Comment by norz** [comment]
You should see remote reactions to your notes… 🤔  

And you should see remote reactions on *remote* notes from accounts you follow at least.

**Comment by KisaragiEffective** [comment]
triage: I'm going to close this issue as staled. Please let us know if you are experiencing this issue on 2024.5.0 🙏🏻
