### ISSUE TITLE
Remote instances logos/icons not passed through summaly

### ISSUE THREAD

**Issue by skid9000** [syuilo/Misskey#9363]
## 💡 Summary

Icons from remote instance are fetched directly by client without passing though summaly.

## 🥰 Expected Behavior

Client shouldn't fetch ressources from remote servers directly.

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/26208369/208531085-95c6de79-58ed-433b-bc75-0f840b42fc67.png)

## 📝 Steps to Reproduce

1. Login to misskey
2. Check what's loading through network tab on dev console or umatrix

## 📌 Environment

Misskey version: 12.119.0
Server Environment : Debian 11, Node 16.18.1, Postgresql 14
Client OS: Archlinux
Your browser: Firefox Stable 108

**Comment by syuilo** [comment]
Already fixed in develop branch🙏
