### ISSUE TITLE
Catフラグの具体的な説明を追加

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9364]
## Summary
現状、Catフラグの項目の説明は、フラグを立てると何が起きるかは説明されていないので、Misskeyを初めて触る人がなんとなくで有効にすると文章が変換されてパニックに陥ることがある。
例を入れるなどしてこの機能がどのように働くかを説明する必要がある。
<img width="489" alt="image" src="https://user-images.githubusercontent.com/26585194/208557160-49c1e166-255e-41ad-91c3-131a713379a5.png">

**Comment by L1n4r1A** [comment]
「にゃんかにゃがにゃににゃってる！にゃにこれ！」が多すぎるのでこれ欲しい
isBotも遊びでつける人がいるのでついでに欲しいかも、いらないかも

**Comment by syuilo** [comment]
パニックにさせることが目的の機能ではある

**Comment by EbiseLutica** [comment]
こういうのはどうだろう

1. オンにする
2. 画面に、突然大量のネコが出てくる
3. 「あなたはねこににゃった！」みたいにゃダイアログが出てくる

パニックにさせる目的は達成できそう

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/209458804-e53398b9-777c-4513-9b00-8b72ee6fcef0.png)
