### ISSUE TITLE
Compress PNG to WebP if non-animated and non-transparent

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9370]
## Summary

Following #9277.

For now Misskey only compresses big PNGs to smaller PNGs, but small PNGs are still have significantly large file size compared to lossy formats. A screenshot from a Windows machine with a 1920x1080 display can eat 2 megabytes for example even when such image does not use any alpha value.

One caveat is that the only way to detect transparency from a PNG file is to scan every pixel in JS, which may take some time. 🤔 (Windows uses RGBA without any transparency. 🤷)

Q: Why not WebP?
A: Not usable yet because of Mastodon v3. https://github.com/misskey-dev/misskey/pull/9334#issuecomment-1356098046

**Comment by saschanaz** [comment]
@tamaina What's your point to keep it PNG, btw?

**Comment by tamaina** [comment]
@saschanaz 

I protest vigorously. I hate lossy images anyway.

**Comment by saschanaz** [comment]
Not even WebP? 👀

This could be an option, but generally I don't think it's a good storage/network use to keep PNG by default.

This could be much cleaner if Mastodon v3 didn't just fail on WebP but at least tried something with its backing ImageMagick 😭

**Comment by norz** [comment]
The benefits of this proposal far outweigh the drawbacks imho.

**Comment by saschanaz** [comment]
@tamaina これまだダメです？ Windowsでスクリーンショット上げるユーザー少なくないので対応したい

**Comment by tamaina** [comment]
う〜〜ん、低圧縮のlossy webpならいいのかも？

ただwebpをブラウザで実装するのが辛いのか

**Comment by saschanaz** [comment]
>ただwebpをブラウザで実装するのが辛いのか

特に問題ないと思いますが

**Comment by acid-chicken** [comment]
https://caniuse.com/mdn-api_htmlcanvaselement_toblob_type_parameter_webp

**Comment by saschanaz** [comment]
WebP対応出来ているブラウザーではWebPにして他ではそのままにするとかどうでしょう

**Comment by acid-chicken** [comment]
iPad をそのままにしてしまうとあまり解決にならないかも ![image](https://user-images.githubusercontent.com/20679825/224479931-9a607a8e-7de9-4aa5-a3c5-0d6386db6a4d.jpeg)

**Comment by saschanaz** [comment]
....SafariではJPEGにしてしまえば💢（悪魔の声）

でも他に手あります？そのまま vs JPEGに

**Comment by acid-chicken** [comment]
画像周りの話、悩ましいし、ややこしいし、この際 Epic Issue 立てて一旦整理したい……

**Comment by saschanaz** [comment]
wasm使って全部AVIFにしようって話があったような

**Comment by acid-chicken** [comment]
> wasm使って全部AVIFにしようって話があったような

理想を言えばこれができると一番嬉しい
デコードの観点ではそのうちメジャーブラウザが全てサポートするようになりそうなのであまり心配がない（連合はまぁ……連合先が対応して欲しいんだけどなぁ）
エンコードの観点では wasm でエンコーダーを持ち込むことでのサポートになるが、実際にやってみてパフォーマンステストしてみないといけない（あと多分 wasm SIMD に対応させないといけない）

**Comment by saschanaz** [comment]
理想と言えばSafariにWebPエンコードをサポートさせるのが理想ですね

一旦はWebPサポートしているブラウザーのみ対応して後は別の件で話したいです（最近のSafariの変化がかなり大きくて希望を持ってもいいかなって）

**Comment by acid-chicken** [comment]
> 一旦はWebPサポートしているブラウザーのみ対応して後は別の件で話したいです（最近のSafariの変化がかなり大きくて希望を持ってもいいかなって）

その方針で良いと思います

**Comment by tamaina** [comment]
> WebP対応出来ているブラウザーではWebPにして他ではそのままにするとかどうでしょう

> iPad をそのままにしてしまうとあまり解決にならないかも 

とりあえずSafariはpngにすればいいと思う（iPadのスクショは16bit PNG /w Display P3らしいので、8bit・色域メタデータなしにするだけでも相当軽くなるはず

（本当はavifにしたいんだよな…Mastodon…）

**Comment by tamaina** [comment]
でも2MBだから微妙だなぁ

**Comment by tamaina** [comment]
toBlob webp、Safariだとquality無視されるけど一応生成できなかったっけ？

**Comment by acid-chicken** [comment]
> toBlob webp、Safariだとquality無視されるけど一応生成できなかったっけ？

これ本当なら MDN のデータの方修正しようぜ

https://github.com/mdn/browser-compat-data/blame/e74cd55301d99b723aafa7218047511c73ffcafc/api/HTMLCanvasElement.json#L1051-L1084

**Comment by acid-chicken** [comment]
https://codepen.io/acid-chicken/pen/abaqNqO

**Comment by saschanaz** [comment]
> toBlob webp、Safariだとquality無視されるけど一応生成できなかったっけ？

webpじゃなくPNGが出てきてしまう件について

**Comment by saschanaz** [comment]
https://html.spec.whatwg.org/multipage/canvas.html#serialising-bitmaps-to-a-file

>User agents must support PNG ("[image/png](https://html.spec.whatwg.org/multipage/indices.html#image/png)"). User agents may support other types. If the user agent does not support the requested type, then it must create the file using the PNG format. [[PNG]](https://html.spec.whatwg.org/multipage/references.html#refsPNG)

仕様だった件

**Comment by tamaina** [comment]
なるほど〜〜

**Comment by tamaina** [comment]
（エラーにならないんだ…

**Comment by acid-chicken** [comment]
若干逸れた話題かもしれないけど、しばらく [oxipng](https://github.com/shssoichiro/oxipng) を使ってみたところかなりいい感じだった
