### ISSUE TITLE
nyaizeされていないtextの提供

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9371]
## Summary
アプリケーションによっては投稿の文章を扱うものがあって、利用者がCatだった場合にnyaizeされた文章が取り込まれてしまう。
そのため無加工の文章を提供する方法があればいいなと考えた。

### 1 未加工の文章をレスポンスに含める
```json
{
 "text": "ばにゃにゃ大好き",
 "original_text": "ばなな大好き"
}
```
メリット: パラメータをつけて改めて取得する必要もなく、便利。
デメリット: 転送量がおよそ2倍になる。(圧縮しない場合)

### 2 未加工の文章を提供するオプションを設ける
`{"noteId": "38dy8by23", "noFilter": true}`

```json
{
 "text": "ばなな大好き"
}
```

メリット: 既存のアプリケーションでコードの変更が不要
デメリット: ノートをレスポンスに含めるエンドポイントすべてに`noFilter`などのパラメータを設ける必要あり。また、nyaizeしない文章が必要なときにもう1回APIにリクエストを送る必要があるかもしれない。

**Comment by rinsuki** [comment]
duplicate of #5221 ?
