### ISSUE TITLE
コントロールパネルや設定のスタイルが壊れている

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9374]
## 🥰 Expected Behavior
![image](https://user-images.githubusercontent.com/7973572/208657747-6afcb063-f1f5-4eef-aac7-acdffd987c35.png)

## 🤬 Actual Behavior
![70A177F4-AD0E-4092-89CB-EB1B81CB9798](https://user-images.githubusercontent.com/7973572/208657668-b4dbe60a-f0e9-4a02-b808-a756ce8f3358.jpeg)

## 📝 Steps to Reproduce

1. コントロールパネルをモバイル幅で開く

## 📌 Environment

Misskey version: v13.0.0-alpha.1
Your OS: iPad OS 16.2
Your browser: Safari (PWA)

**Comment by syuilo** [comment]
Safariだけっぽい？

**Comment by tamaina** [comment]
Firefoxではおk

**Comment by tamaina** [comment]
macOS Chromeもおk

**Comment by tamaina** [comment]
macOS SafariもNG

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/208658368-ea61fb7b-af02-4252-885d-bae8ac866a45.png)

ふむ

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/208663404-c57ac604-e259-4f7d-8da7-66cd21d76638.png)

ん、これでいいのかしら(Firefoxでも同じ感じ)

**Comment by syuilo** [comment]
調整は要りそう
(布団からコミット)
