### ISSUE TITLE
メールサーバーでメールが送れない

### ISSUE THREAD

**Issue by PYU224** [syuilo/Misskey#9380]
## 💡 Summary

Misskey本体のバグかどうか分かりませんが報告します。
メールサーバを設定してテストメールを送ろうとしても「Internal error occurred. Please contact us if the error persists.
5d37dbcb-891e-41ca-a3d6-e690c97775ac」のメッセージが出てメールが送れません。

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:12.119.2
Your OS:Ubuntu20.04
Your browser:Chrome

**Comment by PYU224** [comment]
すみません解決しました。

**Comment by NoverNobida** [comment]
解決方法を聞いてもいいですか？ 私も同じ問題に遭遇しました。

**Comment by PYU224** [comment]
私の場合はサーバ会社に用意してもらったサーバが良くなかったみたいで、サーバを取り換えてもらったら解決できました。

**Comment by nukora** [comment]
私も同じ問題に遭遇しました。
私の場合はメールサーバーの設定で国外IPからのアクセス制限機能をOFFにしたら正常に送れるようになりました。
参考になれば。
