### ISSUE TITLE
Termuxでyarn installが失敗する

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9382]
## 💡 Summary
Gitからのパッケージインストールで躓く

## 🥰 Expected Behavior
エラーなしでインストールできる

## 🤬 Actual Behavior
エラーが発生する

```
➤ YN0058: │ syslog-pro@https://github.com/misskey-dev/SyslogPro.git#commit=2772b33fa126784fc6e21377786471a918b22dc7: Packing the package failed (exit code 1, logs can be found here: /data/data/com.termux/files/usr/tmp/xfs-660934b1/pack.log)
➤ YN0000: └ Completed in 12s 681ms
➤ YN0000: Failed with errors in 13s 270ms
```

・原因は不明。詳細ログを見てもまったくエラーの原因やきっかけになるものが書かれていないため、おそらくyarnのバグ？

解決方法は存在する。

## 📝 Steps to Reproduce

1. `yarn install` or `yarn workspaces focus --all --production`
## 📌 Environment

Misskey version: 13.0.0-alpha.3
Your OS: Android 11
Yarn: v3.3.0

**Comment by rinsuki** [comment]
![Screenshot_1671679690](https://user-images.githubusercontent.com/6533808/209049336-a671422b-44cf-4f64-9371-6e2c7c62dfc9.png)
yarnじゃなくてnpmが悪い

**Comment by rinsuki** [comment]
っていうかそもそもなんでsyslog-pro forkしてるんだっけ

**Comment by syuilo** [comment]
> っていうかそもそもなんでsyslog-pro forkしてるんだっけ

https://github.com/cyamato/SyslogPro/issues/8

**Comment by rinsuki** [comment]
![Screenshot_1671680055](https://user-images.githubusercontent.com/6533808/209049911-abe3f490-5c53-43f3-adbc-01988280ee42.png)
syslog-pro の package-lock.json が古いのが悪い？

**Comment by rinsuki** [comment]
なんか Termux だと npm がうまく package-lock.json のバージョンを更新できないらしい
とりあえず https://github.com/misskey-dev/SyslogPro/pull/1

**Comment by rinsuki** [comment]
それはそうとして cypress とかAndroid対応してないしTermuxで動かすの厳しそう

**Comment by rinsuki** [comment]
コケるもの
* cypress
* sharp

`pkg install python3` で直るもの
* bufferutil (Python入れれば直る)
* utf-8-validate (Python入れれば直る)
* re2 (Python入れれば直る)

**Comment by rinsuki** [comment]
たぶん素直に Pixel 7 買って QEMU で動かすのが安定してていいと思う https://androplus.org/entry/pixel-7-no-root-linux/

**Comment by rinsuki** [comment]
sharp は追加で `pkg install binutils-is-llvm` すれば通る…かと思いきや `#include <glib-object.h>` がないと言ってコケる (`/usr/include/glib-2.0/glib-object.h`に存在はする)

**Comment by CyberRex0** [comment]
そこまで複雑な手段は踏まなくとも、ネイティブでインストール・動作できます
- `cypress`は無理なのでproductionモードでインストールすれば回避できます
- `sharp`はlibvips-staticとxorgproto (x11-repo有効化必須) をaptで入れたら、ソースからビルドしなくてもyarnでインストールできます

前述の通りTermuxではCypressなどを回避するためにproductionでinstallする`yarn workspaces focus --all --production`をyarn installの代わりに使います。

https://zenn.dev/cyberrex/articles/d546d0bbcfc555

**Comment by CyberRex0** [comment]
そしてこの件についてはリポジトリをtar.gzで落とせば解決できるというふうに黒ヰ樹さんから[コメント](https://misskey.io/notes/98zn828k9a)もらっているので、それに従って PR #9383 を用意しました (Macで動作検証済み)
もしかして #〜でバージョン指定するのやめたらDependabotの邪魔になるとか？

**Comment by CyberRex0** [comment]
これどうするんだろ...

**Comment by acid-chicken** [comment]
PR で Yarn が通らないのは**バグではなく**

> CIコケてるのはインストール先変わったのに yarn.lock 変わってないからでは
https://github.com/misskey-dev/misskey/pull/9383#issuecomment-1362463508

なので、どうすると言われても……

**Comment by CyberRex0** [comment]
yarn.lockをコミットしたほうがいい？

**Comment by acid-chicken** [comment]
@CyberRex0

> yarn.lockをコミットしたほうがいい？

Short Answer: はい、package.json に変更を加える際は必ず同様にステージしてコミットしてください。
Long Answer: https://yarnpkg.com/getting-started/qa#should-lockfiles-be-committed-to-the-repository

**Comment by CyberRex0** [comment]
コミットしておきました

**Comment by acid-chicken** [comment]
And related to npm/statusboard#395

**Comment by acid-chicken** [comment]
かつその間に

> misskey-dev/SyslogPro#1

はマージ済みだし 

> dependabot が困る気もするがそもそも tar.gz のURL指定って基本 npm pack でできたものを指定する想定なはずなので (一応任意名前のフォルダ/package.jsonになってれば動くらしいけど) GitHub の自動生成tar.gzを指定するのは動きはしてもアレかもしれない
https://github.com/misskey-dev/misskey/pull/9383#issuecomment-1362463508

なのでそもそも tarball を代替として充てるのは本当に正しいの？（よくわからんがまぁ動くからヨシ！になってない？）みたいなところがある

**Comment by CyberRex0** [comment]
pnpmに移行したらエラーが出なくなったので解決
