### ISSUE TITLE
bot アカウントでの投稿時/リアクション時に確認ダイアログを出す

### ISSUE THREAD

**Issue by acid-chicken** [syuilo/Misskey#9386]
## Summary

SSIA

- アカウント切り替えを誤って bot アカウントでログインしている際の誤操作防止になるため
- bot アカウントで投稿する場合、ユーザー向けインフォメーションを発信するなどといった、ダブルチェックがあって困らないシチュエーションでのアクションが十分想定できるため
- 人間が常用的にアカウントを使用する場合、確認ダイアログが出てくることで諸操作が煩雑になり、みだりに isBot フラグがつけられるのを抑止する効果が期待できるため

**Comment by syuilo** [comment]
Botアカウントでログインしている間は画面上にそれが分かる表示を常に出しておくとかも良いかもしれない

**Comment by syuilo** [comment]
> Botアカウントでログインしている間は画面上にそれが分かる表示を常に出しておくとかも良いかもしれない

これやったからよさそう
