### ISSUE TITLE
npm run dev does not work with docker 

### ISSUE THREAD

**Issue by chualuoi** [syuilo/Misskey#9392]
## 🥰 Expected Behavior

Able to use docker for development by running `npm run dev`

## 🤬 Actual Behavior

Getting error message

```
Cannot find module '/misskey/packages/backend/built/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## 📝 Steps to Reproduce

1. Change Dockerfile CMD from `["npm", "run", "migrateandstart"]` to `["npm", "run", "dev"]`
2. Build and launch as guided in https://misskey-hub.net/en/docs/install/docker.html

Note: Misskey can start sucessfully with CMD `["npm", "run", "migrateandstart"]`.

## 📌 Environment

Misskey version: 12.119.2
Your OS: Debian
Your browser:

**Comment by KisaragiEffective** [comment]
triage: this is fixed in earlier than #14235, see https://github.com/misskey-dev/misskey/blob/ec1c392f1e409e707ba81dfcd45112efb418c7aa/CONTRIBUTING.md#use-docker-compose
