### ISSUE TITLE
/notes/:noteIdに直接アクセスするとActivityPubのjsonが返ってくる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9393]
## 💡 Summary
ローカルのノートにアクセスするとjsonが返ってくる

https://p1.a9z.dev/notes/992iuz3mid

キャッシュがだめなのかも？  
ただv13以降で発生するようになったのでFastifyが関係している可能性は高い

## 🥰 Expected Behavior
html(pug)が返ってくる

## 🤬 Actual Behavior
jsonが返ってくる

Misskey version: v13 alpha

**Comment by mei23** [comment]
Varyヘッダ吐いてないわね
だからたぶんnginxでAP/HTMLのキャッシュが混ざってる

**Comment by syuilo** [comment]
やっぱりAP用のパス変えたい
