### ISSUE TITLE
`/pages`のスタイルがなんかおかしい / The styles in `/pages` looks off

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9394]
## 💡 Summary

Something looks off on `/pages/`

なーんかこう見えちゃダメな気がする

## 🥰 Expected Behavior

Some margins between blocks and buttons?

## 🤬 Actual Behavior

![The screenshot from one of pages](https://user-images.githubusercontent.com/3396686/209125422-90f40958-9204-43c3-95d2-8a981664a023.png)

## 📝 Steps to Reproduce

1. Open https://misskey.io/@kot/pages/1601777473999
2. See the page styles are correct

## 📌 Environment

Misskey version: 12.119.2
Your OS: Windows 11
Your browser: Firefox

**Comment by KisaragiEffective** [comment]
triage: #9514 で指摘されている通り、2023年2月にリリースされたFirefox 110以降を使うと治る可能性があります。

実際、2024.5.0-kinel.4 (2024.5.0ベース) をFirefox 128で開くと、マージンが正常に当たっているように見えます:

![image](https://github.com/user-attachments/assets/e6ac6cd6-9aa9-42e9-b160-6f08999216d2)

もしこの現象がFirefox 110以降でも再発するようであればお知らせください 🙏🏻
