### ISSUE TITLE
ユーザーがアップロードした音源を通知音に使用できる機能

### ISSUE THREAD

**Issue by Allianaab2m** [syuilo/Misskey#9403]
- 現状インスタンス管理者のみが音源を追加出来る
- 一般ユーザーも音源を追加して自身の通知音を変更できるようにすることが目的
- ユーザーのドライブからデータを参照する？

以下のノートから着想を得ました。
https://misskey.io/notes/993sjuy2i4

**Comment by syuilo** [comment]
同じIssueあった気がする

**Comment by Allianaab2m** [comment]
既出でしたか。申し訳ないです

**Comment by syuilo** [comment]
いやわからない

**Comment by acid-chicken** [comment]
#4684?
