### ISSUE TITLE
APIにGETで接続すると接続が開きっぱなしになる（情報やエラーが返ってこない）

### ISSUE THREAD

**Issue by ikuradon** [syuilo/Misskey#9404]
## 💡 Summary
/api/*にGETするとnginxなりのReadTimeoutが発生するまで接続が開きっぱなしになる

## 🥰 Expected Behavior
情報/エラーが返ってくる

## 📝 Steps to Reproduce

1. `curl https://<HOSTNAME>/api/meta`

## 📌 Environment

Misskey version: 49ab2eb07f6d51b181f237326054d7c1b3614170

**Comment by syuilo** [comment]
`curl http://<HOSTNAME>/api/federation/stats`
とかは成功するから、GET非対応APIにGETでリクエストするとそうなるっぽい
