### ISSUE TITLE
フォロー申請のアイコンがない

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9405]
![image](https://user-images.githubusercontent.com/7973572/209446751-b53ebf0a-7338-41b9-90c3-c50ef28a5ec3.png)

Related to #9354 (Use Tabler Icons)

ここら辺のどっかを使う？

![image](https://user-images.githubusercontent.com/7973572/209446796-0f7fb732-3b3f-4e5a-aa08-a2ff33498a8c.png)

**Comment by syuilo** [comment]
user-plusで良さそう

**Comment by syuilo** [comment]
done
