### ISSUE TITLE
ノート本文が大きいとクライアントがMFMパースでフリーズする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9407]
## Summary
ノート本文が大きいとMFMパーサーが長時間メインスレッドを占有してMisskeyがフリーズする

**Comment by syuilo** [comment]
長時間メインスレッドを占有するほど大きい本文をもつノートってあるかな

**Comment by syuilo** [comment]
あるとしたらスパムだと思うから処理せずに弾けば良さそう

**Comment by tamaina** [comment]
まあ確かにそんな長い投稿を受け付けてることが問題ではある

**Comment by acid-chicken** [comment]
どうせ DB に字数制限あるんだから受け取った時点で最大サイズでスライスすれば良いのでは

**Comment by mei23** [comment]
DB制限は8192だったけどいつの間にか消えてて、INSERT前にチェックもしてたはずだけどいつの間にか消えてるのだわ。

**Comment by acid-chicken** [comment]
えぇ……

**Comment by mei23** [comment]
> INSERT前にチェックもしてたはずだけど

いや、これは元から連合分はチェックしてなかったみたいだわ。

DBスキーマの8192はどこかでmodelからもmigrationからも消えてそうだわ。

**Comment by syuilo** [comment]
PostgreSQLにしたときからnoteのtextはtext型じゃなかったっけ(これvarcharにしたいって昔から思ってるけど難しそう)

**Comment by syuilo** [comment]
~~textでも文字数制限付けられるのか~~

**Comment by syuilo** [comment]
IssueタイトルはHowじゃなくてWhatの方が良い

**Comment by acid-chicken** [comment]
@tamaina issue 切るときは「まず」課題ベースで切って手段が煮詰まったらぶら下げで手段を切った方が良いと思う

**Comment by acid-chicken** [comment]
同じこと書いてた……

**Comment by mei23** [comment]
> PostgreSQLにしたときからnoteのtextはtext型じゃなかったっけ(これvarcharにしたいって昔から思ってるけど難しそう)

PG移行時はtextで、直後にmodelだけ8192にしてmigrationは作成せず
なので最初にDBを作成した方法によってtextと8192のインスタンスがあるはずだわ。 (でもたぶんほとんどtext)

**Comment by tamaina** [comment]
反応が欲しくて高いボールを投げがちになってしまう()

あと私はフロントエンドの話をしていた

**Comment by syuilo** [comment]
あー

**Comment by acid-chicken** [comment]
~~じゃあフリーズするのはブラウザなのでは~~

**Comment by tamaina** [comment]
ブラウザ自体はフリーズしないかも

**Comment by acid-chicken** [comment]
まあどちらにせよそんなものを流し込んでるサーバー側が悪いのでクライアントの課題ではない

**Comment by rinsuki** [comment]
クライアントの話: 結局パースをworkerでやろうがworkerとの送受信とかDOM操作がかなり重そう

**Comment by syuilo** [comment]
ノート本文に限らずプロフィールとかでも発生しそう

**Comment by syuilo** [comment]
> ノート本文に限らずプロフィールとかでも発生しそう

truncateしてたわ

**Comment by mei23** [comment]
うちはtextサイズで切ってたけどそれでも1MBは重くなったので、そもそもinboxキューに入れる前にハードリミットがあった方が良さそう

**Comment by tamaina** [comment]
いちいちWorkerを立ててWorkerとのメッセージングしてたらどうしてもラグは起きそう

**Comment by mei23** [comment]
> うちはtextサイズで切ってたけどそれでも1MBは重くなったので、そもそもinboxキューに入れる前にハードリミットがあった方が良さそう

このあたり (Fastifyでの書き方はわからない)
https://github.com/mei23/misskey/commit/691568ab42f4265de263af4601684bd4d227e2e9

**Comment by syuilo** [comment]
それと似たようなことやろうと思ったけど、そこで制限しても結局resolverとかで取ってくるときに巨大なオブジェクト受け取る可能性あるから意味ないかなと思ってた

ただ少なくともRedisのメモリが圧迫されるのを防ぐことはできそうだからやる

**Comment by syuilo** [comment]
ヘッダのcontent-lengthって信用していいのかな

**Comment by mei23** [comment]
> ヘッダのcontent-lengthって信用していいのかな

完全ではないので、ヘッダで切って実サイズで切る必要があると思うのだわ。

**Comment by acid-chicken** [comment]
わからないけど nginx って Content-Length ヘッダー補完したりしないのかな

**Comment by syuilo** [comment]
やった
https://github.com/misskey-dev/misskey/commit/b518c35e0021ed25f152477924ec9fd092e23f25

**Comment by syuilo** [comment]
もっと小さくても良いか

**Comment by mei23** [comment]
-v12にinboxリミットを適用する場合は、JSONパースで制限したほうが良さそう。
https://github.com/mei23/misskey/commit/2191075e8c7560e76c3509f9059699c18bdf8995

デフォルトで1mbのリミットがあるらしい。
https://github.com/venables/koa-json-body#options
