### ISSUE TITLE
/api/signin always returns 429 when request header x-forwarded-for contains client port

### ISSUE THREAD

**Issue by recumbented** [syuilo/Misskey#9408]
## 💡 Summary
Some reverse-proxy software send x-forwarded-for that contains client's ip port number in addition to IP address.(Ex. Azure App Service)
But current code expected ip not contains port in source below:
 https://github.com/misskey-dev/misskey/blob/a5a74f4434b179cdb1f97af98bf294c8b18de0e2/packages/backend/src/misc/get-ip-hash.ts#L7

As result, if ip contains port number (ex. 127.0.0.1:6789),
 IPCIDR.createAddress(ip) throws `[AddressError]: Bad characters detected in address`,
and signin fail with status code 429 and code 'TOO_MANY_AUTHENTICATION_FAILURES'.

## 🥰 Expected Behavior
User can signin.

## 🤬 Actual Behavior
Every user fails signin with code 'TOO_MANY_AUTHENTICATION_FAILURES'.

## 📝 Steps to Reproduce
Deploy Misskey behind of reverse-proxy that send x-forwarded-for header with value including client port(ex. 127.0.0.1:6789).

## 📌 Environment
Misskey version:12.119.2
Your OS: macOS 13.1 / iOS 16.2
Your browser: Safari

**Comment by Johann150** [comment]
I think it is poor behaviour to add the port number here and you should configure your reverse proxy to not do that. If you are using IPv6 addresses it may generate a different, but valid (i.e. spoofed) IPv6 address if you add the port number with a colon.

Lets say the request comes from `2001:db8::1` using port `9999`. If you concatenate them with a colon it becomes `2001:db8::1:9999` which is also a valid, but different IPv6 address. Or maybe for IPv6 addresses the other common notational convention with square brackets is used (i.e. `[2001:db8::1]:9999`)? In that case this issue has not been fixed for IPv6.
