### ISSUE TITLE
絵文字のプロキシURLの改善

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9413]
## Summary
現在のコードでは絵文字のプロキシURLを以下のように構成している。
`${config.url}/proxy/${encodeURIComponent((new URL(emojiUrl)).pathname)}?${query({ url: emojiUrl })}`
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/CustomEmojiService.ts#L120

`/proxy/〇〇?url=` の〇〇に絵文字ファイルのpathnameを入れているが、pathnameは「/」から始まり、直前の/と連なる形となるのでブラウザ・ライブラリなどのソフトウェア間でURL正規化の問題が発生する可能性がある（発生している）
実際にはpathnameはエンコードされるので`/`は`%2F`になるが、これを`/`に直してくるソフトウェアがいる。(FFmpeg？など)
何かしら絵文字ファイルのパスを含めたい場合はpathnameではなく、pathモジュールの`basename`を使ってファイル名だけを使ったほうがいいと思う。

**Comment by tamaina** [comment]
そもそもここでプロキシ突っ込む意味がなくなってきた（バックエンドでプロキシのURLを指定すること自体がナンセンスなのかもしれない）
