### ISSUE TITLE
特定のインスタンスについて、リモートユーザーのアバター画像が正常に表示されない

### ISSUE THREAD

**Issue by iRi-E** [syuilo/Misskey#9430]
## 💡 Summary

misskey.ioから、特定のインスタンスに登録されているリモートユーザーを見ると、全ユーザーのアバター画像（アイコン）が破損状態または未設定状態として表示される（リモート側で確認すると実際には設定されている）

不具合が発生するリモートのインスタンスの例
mastodon.social
mastodon.art
masto.hostを利用する全てのインスタンス

なお、misskey.io以外のインスタンスから、例えばmisskey.noellabo.jp（のえすきー）からリモートユーザーを見た場合は正常に表示される

CDN絡みの不具合っぽい？

## 📝 Steps to Reproduce

1. misskey.ioにログインする
2. 「みつける」から「mastodon.social」でリモートユーザーを検索する
3. 同様に「masto.host」でリモートユーザーを検索する

## 📌 Environment

Misskey version: 12.119.2 (misskey.io)

**Comment by syuilo** [comment]
misskeyのリポジトリではインスタンス固有と思われる問題は受け付けてませんので、インスタンス管理者までご報告お願いします🙏

**Comment by iRi-E** [comment]
すみません、インスタンス固有ではなくCDN利用するインスタンスで一般的に発生するのかどうか判断つかなかったのでこっちに報告しました

とりあえずいくつか他のインスタンスで確認してみます

**Comment by iRi-E** [comment]
今のところ他に問題発生するインスタンスが見つからないので、ここは閉じておきます
