### ISSUE TITLE
Misskey is unable to federate with GotoSocial at all

### ISSUE THREAD

**Issue by jkumeboshi** [syuilo/Misskey#9435]
## 💡 Summary

Misskey is unable to federate with GotoSocial at all, can't read remote user info or access any remote post.

## 🥰 Expected Behavior

Misskey should be able to interrogate remote user information or to read a remote post.

As an example, you can check `@gotosocial@gts.superseriousbusiness.org` user

## 🤬 Actual Behavior

When I try to get user information, such as for user `@gotosocial@gts.superseriousbusiness.org`, I get a generic error in the UI and I can read following in the log:

```
web_1    | DONE 1       [remote resolve-user]   return new remote user: gotosocial@gts.superseriousbusiness.org
web_1    | WARN 1       [api]   failed to resolve remote user: StatusError: 401 Unauthorized
```

If I try to access a remote content, such as
`https://gts.superseriousbusiness.org/@gotosocial/statuses/01GMT9YX9BJGGHJ0B2X16K3E53`

I get Following error:
```
web_1    | ERR  1       [api]   Internal error occurred in ap/show: 401 Unauthorized
```

## 📝 Steps to Reproduce

look for an user id:
1. in the search box enter `@gotosocial@gts.superseriousbusiness.org`
2. you get generic error in the UI
3. you will find the error in the log

access remot econtent:
1. in the search box enter `https://gts.superseriousbusiness.org/@gotosocial/statuses/01GMT9YX9BJGGHJ0B2X16K3E53`
2. you get generic error in the UI
3. you will find the error in the log

## 📌 Environment

Misskey version: 12.119.2
Your OS: Windows 11
Your browser: Firefox 108.0.1 (64 bit)

**Comment by rinsuki** [comment]
can you try with enable `signToActivityPubGet` in `config/*.yml`?

**Comment by jkumeboshi** [comment]
@rinsuki GREAT! It works perfectly now!
I think that should be noted somewhere, since this issue is going to be closed...

Well, at least to keep track of that until in future `signToActivityPubGet` would be set default to true

**Comment by rinsuki** [comment]
in next version, it will be enabled by default https://github.com/misskey-dev/misskey/commit/3402131b7d3ea207e3db00a5472b0a204aebb2f3
