### ISSUE TITLE
Client: Cannot import client preference backup fails with 'Unnecessary properties exist'

### ISSUE THREAD

**Issue by ltlapy** [syuilo/Misskey#9438]
## 💡 Summary
Client Preference import fails with 'Unnecessary properties exist'

## 🥰 Expected Behavior
Import client preference successfully
ダウンロードしたクライアント設定のバックアップが正常にインポートされる

## 🤬 Actual Behavior
Throws an error 'Unnecessary properties exist', even with legit backup files
'Unnecessary properties exist'のエラーが表示され、インポートされない

## 📝 Steps to Reproduce
From web client `/settings/preferences-backups`
1. Create new backup
2. Download the backup
3. Import Downloaded backup

## 📌 Environment

Misskey version: v12.119.2

**Comment by ltlapy** [comment]
`/packages/client/src/pages/settings/preferences-backups.vue:L104`の`const profileProps`に `hosts`が欠けてあることが原因と判断されます

**Comment by tamaina** [comment]
> `/packages/client/src/pages/settings/preferences-backups.vue:L104`の`const profileProps`に `hosts`が欠けてあることが原因と判断されます

hostでは
