### ISSUE TITLE
Safariではリンク長押しでプレビューが表示されるが、例えばデッキモードにしているとデッキ画面がそこに表示されるので無意味

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9446]
## Summary
Safariのロングタップ（長押し）プレビューを制御するか無効化したい

以下の点が不便

- ユーザープレビューを表示したいときに長押ししてもSafariのプレビューが出てくる
- デッキモードにしているとプレビューにデッキが表示されるので無意味

（Webサイトから制御する方法をまとめた記事があれば教えて欲しい）

**Comment by tamaina** [comment]
webkit-touch-callout

https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-touch-callout

**Comment by syuilo** [comment]
ユーザープレビュー関係ないかつデッキでもないケースでプレビューwp表示したい人もいるかも

**Comment by tamaina** [comment]
> ユーザープレビュー関係ないかつデッキでもないケースでプレビューwp表示したい人もいるかも

かもしれないけどヘッダーとかがやっぱり邪魔  
全部消しちゃったのはプレビューして便利に感じたのがユーザー以外になかったというのもある
