### ISSUE TITLE
MiAuth: コールバックURLが壊れている

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9448]
## 💡 Summary

コールバックURLが例えば `https://example.com?session%3Dea5a436e-b1ab-4c36-aab6-3a540c7c9a17=session%3Dea5a436e-b1ab-4c36-aab6-3a540c7c9a17` のようにおかしな値になっている

## 📝 Steps to Reproduce

1. MiAuth APIをコールバックありで呼び出す

## 📌 Environment

Misskey version: 13.0.0-beta.14
Your OS: Windows 11
Your browser: Chrome

**Comment by tamaina** [comment]
なんかバックエンドの問題のように捉えられてるけどクライアントの問題やんこれ

**Comment by syuilo** [comment]
これって12では発生しない？

**Comment by HotoRas** [comment]
Not a issue on 12. However I checked this issue on a fork from 13.0.0-alpha.5, so changes before then would have triggered this.
