### ISSUE TITLE
Misskeyの使い方 5 / 7 の「ハイライト」リンクが切れている 

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#9456]
## 💡 Summary

アカウント登録直後のホームを参照した時に表示されている **Misskeyの使い方** のうち **5 / 7** に記載されている **ハイライト** のリンクが切れていて参照できません。

![スクリーンショット 2023-01-01 22 19 25](https://user-images.githubusercontent.com/5434159/210193290-903d020b-0166-4723-998b-a3d19eb448d0.jpg)

参考:
- https://misskey.io/notes/99f5opb8gb
- https://misskey.io/notes/99gytgyf8a

## 🥰 Expected Behavior

`https://インスタンス/explore` （みつける 内 ハイライト）が適切なリンク先と思われます。

## 🤬 Actual Behavior

**💡 Summary** のとおり

## 📝 Steps to Reproduce

1. 新たなアカウントを作成し、ログイン
2. Misskeyの使い方 5 / 7 まで手順を進める
3. ハイライト をクリック

## 📌 Environment

Misskey version: 12.119.2
Your OS: Windows 10
Your browser: Google Chrome

ただし、OS・ブラウザ に依存しないと思われます。報告時 v13 は未確認。

**Comment by syobon-tech** [comment]
未ログイン状態でノートのリンク等を踏んだ際に画面上部に出現する「ハイライト」をクリックしても同様の現象が発生します(<インスタンスドメイン>/featuredに飛ばされます)。
添付画像はmisskey.ioのものですが、misskey.cf、misskey.cloud等でも確認しました。

![Screenshot_20230102_133337](https://user-images.githubusercontent.com/46315199/210195345-2234f36e-d479-42f2-94ee-c6a6bda54fa3.png)

**Comment by syobon-tech** [comment]
@fu-sen 
確認したところチュートリアルの件はv13で修正されていそうです。
master→ https://github.com/misskey-dev/misskey/blob/master/packages/client/src/pages/timeline.tutorial.vue#L28
develop→ https://github.com/misskey-dev/misskey/blob/develop/packages/frontend/src/pages/timeline.tutorial.vue#L39


未ログイン時の「ハイライト」の件はv13が動いているインスタンス(beta.mi-wo.site)でも確認できました。
