### ISSUE TITLE
ビデオをクライアントサイドで再エンコードさせる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9473]
## Summary
ユーザーがアップロードする動画エンコードやサイズがまちまちなので他のユーザーが再生できない場合がある / Videos uploaded by users vary in encoding and size, so other users may not be able to play them 
タイトルにはWhyを書いてみたけど正直**クライアントサイドで再エンコード**させたい

## なぜクライアントサイド？
とにかくGPU支援でないと動画エンコードは厳しい。  
適当なVPSでGPU支援が受けられるわけではない。

## 再エンコード先のターゲットは？
Misskeyは動画サイトではないので、720p60を上限にして良さそう（その代わり画質をちょっとよくしたい）

問題はコーデック(とコンテナ)だが…
ビデオは、結局コンシューマー向けのSoC/GPUで圧縮するとなるとH264しかない？
オーディオは、Safariはopusに対応していないらしいのでaacか？

### A: WebCodecs, VideoEncoderを使う
ブラウザネイティブAPIである[WebCodecs](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder), VideoEncoderなどを使う  
ネイティブAPIなんだから一番早いんじゃないだろうか（超適当）

でだ、なんと、WebCodecsではコンテナを扱うことができない！  
https://github.com/w3c/webcodecs/issues/24

ということでWeb APIだけではMux/Demuxできないので他の手段を用いる必要がある（ffmpegと組み合わせればいける、Uint8Arrayでしか引渡できないのでメモリを食い潰す懸念があるが、Misskeyのアップロード制限は100MB以下が多いため問題になる場面は少ないだろう）

FirefoxはWebCodecsに対応していないが、圧縮しなければ良さそう

### B: wasmでなんとかする？
ffmpeg.wasmでffmpegが扱える  
https://github.com/ffmpegwasm/ffmpeg.wasm

GPU支援なんてなく、CPUエンコードなのであまり現実的ではない（wasmからGPUの動画エンコーダーを扱うのは極めて困難ではなかろうか…）

**Comment by acid-chicken** [comment]
Duplicate of #4091

**Comment by rinsuki** [comment]
言うほど duplicated かというと…

**Comment by tamaina** [comment]
名前変えた

**Comment by rinsuki** [comment]
それはそうとして webcodecs 来るの待つよりかは、お前の上げようとしている動画ファイルは互換性が微妙だけどいいのか？って聞くのがいいと思う

**Comment by EbiseLutica** [comment]
#4091 はサーバーサイドでエンコーディングしようというIssueで、
本issueはクライアントサイドでエンコーディングしようというIssueですよね

**Comment by tamaina** [comment]
別に #4091 はサーバーサイドに限定してあるわけではないし…

**Comment by acid-chicken** [comment]
まあそうかも
ただ目的は同じだし、再エンコの話バラバラにやっても嬉しくないので

**Comment by EbiseLutica** [comment]
なぜ閉じた？

**Comment by tamaina** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/4091

**Comment by tamaina** [comment]
> それはそうとして webcodecs 来るの待つよりかは、お前の上げようとしている動画ファイルは互換性が微妙だけどいいのか？って聞くのがいいと思う

うーんまあでも通信量削減も狙いたいので圧縮はしたい

あ〜、うんまあIssue立て直すか

**Comment by tamaina** [comment]
> A: WebCodecs, VideoEncoderを使う

試しに作ったことならあるが…

https://github.com/tamaina/venc2
