### ISSUE TITLE
Misskey v13でAPNGなアニメーション絵文字がアニメーションされない

### ISSUE THREAD

**Issue by Steve-0628** [syuilo/Misskey#9477]
## 💡 Summary
Misskey v13において、
apngのアニメーション絵文字がWebPに変換されると、静止画になる。
gifのアニメーション絵文字がWebPに変換されたやつは正常にアニメーションされる。

## 🥰 Expected Behavior

アニメーションされる

## 🤬 Actual Behavior

アニメーションされない

[このノートのリアクション](https://honi.stesan.dev/notes/99nm5avbbi)
[このノートのリアクション](https://p1.a9z.dev/notes/99no0r58qg)
[このノートの本文とリアクション](https://honi.stesan.dev/notes/99no4bv4q5)

## 📝 Steps to Reproduce

1. apngのアニメーション絵文字を見つける(ここではmisskey.ioの:emergency:)
2. 投稿する or リアクションする
3. v13なインスタンスで見る

## 📌 Environment

Misskey version: [13.0.0-beta.20](https://github.com/ThinaticSystem/honisskey/tree/Thinatic/migrateToV13) / [13.0.0-beta.23-p1.1](https://p1.a9z.dev/)
Your OS: Windows 10
Your browser: Firefox 108.0.2 / Chrome 108.0.5359.125

**Comment by tamaina** [comment]
sharp周りだろうけど…

**Comment by tamaina** [comment]
https://github.com/lovell/sharp/issues/2375

apng対応してないのか

**Comment by Steve-0628** [comment]
これまだ発生してるかも
[このノートのリアクション](https://honi.stesan.dev/notes/99rxjgja26)
[このノートのリアクション](https://p1.a9z.dev/notes/99no0r58qg)
Chrome 108.0.5359.125 / Firefox 108.0.2

**Comment by syuilo** [comment]
キャッシュの問題ではなくて？

**Comment by Steve-0628** [comment]
キャッシュの問題だったかも、ごめんなさい
