### ISSUE TITLE
非ログイン時でも「Misskeyについて」ページから投稿フォームを出せてしまう

### ISSUE THREAD

**Issue by okayurisotto** [syuilo/Misskey#9486]
## 💡 Summary

タイトルの通りです。
投稿フォームが出るだけで投稿自体はできません。

## 🥰 Expected Behavior

出ない。

## 🤬 Actual Behavior

出てしまう。

## 📝 Steps to Reproduce

1. ログアウトなどをしてログインしていない状態にする
2. そのインスタンスの`/about-misskey`ページへ移動するか、「Misskeyについて」ボタンを押してポップアップを開く
3. 「`I ❤️ #Misskey`」ボタンを押す

## 📌 Environment

Misskey version: 少なくとも`v12.119.2`と`v13.0.0-beta.21`では発生しました

**Comment by kakkokari-gtyih** [comment]
（ここに投稿するのが適切かわかっていないですが）

一応、[投稿フォームが出ないようにする修正を入れたもの](https://github.com/kakkokari-gtyih/misskey/commit/02b67c088db6873239c32ca7a80bb525bf975b44)を作ってみました。

この修正では、投稿フォームの代わりにこんなダイアログが出るようになっています。

![image](https://user-images.githubusercontent.com/67428053/225218412-ac22dfe6-798d-40d0-a4e7-e86a9e4fce64.png)

ただ、あまりにも味気ないので、何か代わりのイースターエッグを入れるのもありかなぁと…
（それか、いっその事非会員にはこのボタンを表示させないようにするか）

**Comment by kakkokari-gtyih** [comment]
@okayurisotto さんはどうするのがいいと思いますか？

**Comment by EbiseLutica** [comment]
横からすみません。タイムラインのRenoteボタンなどは押すとこういうダイアログが出るので、一貫性を持たせるならこれでも良いかも
<img width="303" alt="image" src="https://user-images.githubusercontent.com/7106976/225808851-575d2372-96ef-4430-8b5e-53c3bf4b7b41.png">

**Comment by okayurisotto** [comment]
> @okayurisotto さんはどうするのがいいと思いますか？

@kakkokari-gtyih さんのダイアログはとてもよくできているように見えますが、そもそも私は気付いたバグを報告しただけの一般人ですのでどうすべきかの判断はできません。すみません。

> タイムラインのRenoteボタンなどは押すとこういうダイアログが出るので、一貫性を持たせるならこれでも良いかも

@EbiseLutica さんのコメントを受け確認してみたところ、たしかにすでに同様の機能を持ったダイアログが実装されているようでした。これを素直に再利用するのが、今後のメンテナンスコスト的にもよさそうに思えます。

私がこのIssueを作成した時点では、非ログイン状態でのタイムライン閲覧機能は実装されていなかったように記憶しています。状況が変わったということで、この状況では、すでに実装されているダイアログを再利用するのがよさそうです。

実装については私には難しくできそうにないため、誰かできる人に代わりにやっていただけるとうれしいです。

**Comment by kakkokari-gtyih** [comment]
@EbiseLutica なるほど！そういうものがあるのですね。一度そちらで実装しなおしてみます…

@okayurisotto さんに関しても了解しました！ご意見ありがとうございます。
