### ISSUE TITLE
install script v1.4.0 stop installing with ExperimentalWarning 

### ISSUE THREAD

**Issue by momoirodouhu** [syuilo/Misskey#9488]
## 💡 Summary

After migrating,install script v1.4.0 stop with werning `ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time`

## 🥰 Expected Behavior

install script complete installing

## 🤬 Actual Behavior

It stops with ExperimentalWarning

![Screenshot_20230107-215220.png](https://user-images.githubusercontent.com/66015725/211151816-194c0f49-dc74-438e-a1bb-c51e2e13558e.png)

## 📝 Steps to Reproduce

1.`sudo bash ubuntu.sh`
2.Do you use systemd? yes
3.Set up nginx? no

## 📌 Environment

Misskey version:12.119.2
Your OS:Ubuntu 22.04
Your browser:none

mem:2048M
The server was installed only nginx and qemu-guest-agent

**Comment by tamaina** [comment]
Please copy to https://github.com/joinmisskey/bash-install/issues

**Comment by momoirodouhu** [comment]
Thank you.
But this problem was solved by add memory and CPU resource.
Sorry.
