### ISSUE TITLE
公開範囲「フォロワー」のアイコンを 🔓 から 🔒 にしたい

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9498]
## 概要

開発中のMisskey v13でアイコンセットが変わったので、合わせて公開範囲の鍵アイコンも 🔒 に変更したら如何でしょうか。

* 現状の 🔓 は実際の公開範囲と合わず直感的でない
* 「🔒 自分のみ」が廃止されたため、🔒を使わない理由が無い
* マストドン等も同様の公開範囲に「🔒」を採用しているため、認識がより一致する

以上の理由から提案します。

**Comment by KawaneRio** [comment]
<ruby>自分<rp>《</rp><rt>じぶん</rt><rp>》</rp></ruby>が<ruby>鍵垢<rp>《</rp><rt>かぎあか</rt><rp>》</rp></ruby>(private account)になってる（＝`フォロー認証`しなければいけない）<ruby>場合<rp>《</rp><rt>ばあひ</rt><rp>》</rp></ruby>は🔒にして、
<ruby>逆<rp>《</rp><rt>ぎゃく</rt><rp>》</rp></ruby>に、<ruby>自分<rp>《</rp><rt>じぶん</rt><rp>》</rp></ruby>の<ruby>垢<rp>《</rp><rt>あか</rt><rp>》</rp></ruby>が<ruby>公開<rp>《</rp><rt>こうかい</rt><rp>》</rp></ruby>されてる（＝<ruby>誰<rp>《</rp><rt>だれ</rt><rp>》</rp></ruby>でも`フォロー`ができちゃう＝<ruby>誰<rp>《</rp><rt>だれ</rt><rp>》</rp></ruby>でも<ruby>投稿<rp>《</rp><rt>とうこう</rt><rp>》</rp></ruby>が<ruby>見<rp>《</rp><rt>み</rt><rp>》</rp></ruby>れちゃう）<ruby>場合<rp>《</rp><rt>ばあひ</rt><rp>》</rp></ruby>は🔓にする...ってのは<ruby>如何<rp>《</rp><rt>いかが</rt><rp>》</rp></ruby>ですか？
~~（さうやって仕事を増やしていく）~~
