### ISSUE TITLE
1Passwordでユーザー名を補完できない

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#9500]
[1Password](https://1password.com/)にMisskeyの認証情報を登録し、ログイン時に補完しようとすると、パスワードは補完されますが、ユーザー名は補完されません。
従って、1Passwordでユーザー名が補完できるようにしていただけるとありがたいです。

## 再現環境
* Misskey v12.119.2
* MacBook Air (M1, 2020)
* macOS 12.6.2
* Chrome 108.0.5359.124

## 参考
* https://developer.1password.com/docs/web/compatible-website-design/

**Comment by massongit** [comment]
追加で調査しましたが、 `misskey` を含むドメイン名のインスタンスの場合 (IDフォームのsuffixに `misskey` が含まれる場合) に補完できないような感じがします。

**Comment by syuilo** [comment]
謎

**Comment by rinsuki** [comment]
なんかユーザー名のautocompletionがfalseになっているのが悪い気がする
![image](https://user-images.githubusercontent.com/6533808/211392338-b5c77f86-4fea-4b50-8a01-b9a255ea1e54.png)

**Comment by massongit** [comment]
IDフォームのclassに `username` を指定すると補完されそうな感じがします。
