### ISSUE TITLE
nodeinfoが重い

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9505]
## 💡 Summary

`/nodeinfo/2.0` が重いインスタンスがある
おそらくクエリがキャッシュされていないことが原因？

## 🥰 Expected Behavior

すぐにレスポンスが返ってくる

## 🤬 Actual Behavior
応答に10秒以上かかり`Internal Server Error` または JSONのエラーが返ってくる
```json
{
  "statusCode": 500,
  "code": "57014",
  "error": "Internal Server Error",
  "message": "canceling statement due to statement timeout"
}
```

## 📝 Steps to Reproduce

インスタンスの `/nodeinfo/2.0` にアクセス

## Additional Infomation

ノート数が多いところで発生する確率が高い
nodeinfoが取得できないところではそもそもインスタンスの統計 (/api/stats)も表示できない模様
<img width="501" alt="image" src="https://user-images.githubusercontent.com/26585194/211327823-49f7f1d6-b295-4a1d-9867-cf9900315511.png">

参考:
https://submarin.online/nodeinfo/2.0

misskey.ioも大規模だが独自にキャッシュを効かせているのか、まったく重くなかった (/api/stats も同様)

## 📌 Environment

Misskey version: 12.119.2
Your OS: macOS Monterey
Your browser: Vivaldi 5.6.2867.50 (Stable channel) （arm64） 

※v13のインスタンスは大規模なところがないため、未検証

**Comment by acid-chicken** [comment]
See #4176

**Comment by syuilo** [comment]
チャートの情報を利用するか

**Comment by syuilo** [comment]
activeHalfyearとactiveMonth要る？
