### ISSUE TITLE
Integrated note element in pages, doesn't work

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#9513]
## 💡 Summary

Integrated note element lets you load a specific note inside the page by filling an input text field having that NoteID or URL.

## 🥰 Expected Behavior

I expect to fill the field with a remote or local url, then get the note shown in its box inside the page.

## 🤬 Actual Behavior

You enter the NodeID or Node URL, then save. You get "wakatta" mesg box, but page won't be saved.  Field stills filled but when you reload the edit page with CTRL+R, after saved, field is empty.

Console throws an error of Bad HTTP API request (probably noteID is empty) 400

## 📝 Steps to Reproduce

1. create a new firefox profile (with no extensions)
2. open beta website
3. create a page and add note element
4. fill up NoteID field with a local URL of a note
5. Click save page
6. see: wakatta
7. reload CTRL+R
8. see: noteID disappeared
9. optional see: page preview with missing note and HTTP error in console

## 📌 Environment

Misskey version: 13.0.0-beta32
Your OS: Ubuntu 22.10
Your browser: Chromium 108.0.5359.124 + Firefox 108.0.2

**Comment by futchitwo** [comment]
fixed by #9604

**Comment by tassoman** [comment]
どうも!
Verified into 13.0.0-rc10
