### ISSUE TITLE
Missing margins in timelines, Firefox

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#9514]
## 💡 Summary

Using firefox you have no margins for timelines, in default view. ~~Probably related to: #9394 #8128~~

## 🥰 Expected Behavior

![screenshot-beta misskey social-2023 01 10-00_43_36](https://user-images.githubusercontent.com/92727/211430267-384f59d9-f611-42af-bfeb-4df9d123fa36.png)

Chromium Screenshot

## 🤬 Actual Behavior

![immagine](https://user-images.githubusercontent.com/92727/211430312-e96715bb-2fa8-4c96-a6cf-0bebb385fb18.png)

Firefox Screenshot

## 📝 Steps to Reproduce

1. open firefox 108.0.2 with empty profile
2. open beta website
3. see: no margins

## 📌 Environment

Misskey version: 13.0.0-b32
Your OS: Ubuntu 22.10
Your browser: Firefox 108.0.2

**Comment by tassoman** [comment]
Also Modals are affected

![immagine](https://user-images.githubusercontent.com/92727/211430659-97e42181-aba5-44ba-818d-71077486fe70.png)

**Comment by tamaina** [comment]
The cause is Firefox 108 doesn't support Container Queries.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

**Comment by tassoman** [comment]
⭕ **Wakatta** https://caniuse.com/css-container-query-units

as a Note, [FF109 is going to be released later, this week](https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates).

**Comment by tamaina** [comment]
FF 109 won't support container queries...

**Comment by syuilo** [comment]
109でもフラグ有効にすれば使えそう？

**Comment by tamaina** [comment]
使える

**Comment by tassoman** [comment]
Fixed by FF110 installation
いつもありがとうございます
