### ISSUE TITLE
nodesourceがNode.js v18.13.0をまだ配信していないためDebian/Ubuntuで起動できない / nodesource has not yet delivered Node.js v18.13.0 and cannot boot on Debian/Ubuntu

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9518]
## 💡 Summary
Debian/UbuntuのパッケージリポジトリはNode.jsからnodesourceが案内されているが、  
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

nodesourceが18.13.0を提供していないためインストールできない
https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/

v19にすれば動くかもしれないがLTSで動かないのはちょっと…？

Link: https://github.com/nodesource/distributions/issues/1497

## 📝 Steps to Reproduce

1. Misskeyを起動する
2.  ERR  *        [core boot nodejs]        At least Node.js v18.13.0 required!

## 📌 Environment

Misskey version: v13.0.0-beta.37
Your OS:  Ubuntu 22.04

**Comment by syuilo** [comment]
foxed
