### ISSUE TITLE
新しいMFM関数

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9527]
## Summary

- 位置変更
- 色変更
- 背景色変更
- etc

**Comment by adzukyat** [comment]
端末間で差異なく表示されるような工夫が組み込まれれば評価が上がりそう

例えばTeXの数式環境みたいにArt環境を用意して、その中ではフォントは等幅に固定、キャンバスからはみ出た場合はスクロールできるようにする（もちろん現実的な範囲の長さであった場合のみ）など
