### ISSUE TITLE
pnpmにする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9532]
## Summary
なんかpnpmの方がいいらしい  
（個人的にはnodeのパッケージ管理に全く興味がないので、面倒なことが起きないnpmで良いと思っているけど）

（あとどうしてyarn v3を選んだのか（pnpmの名前が一言も出てこなかったのか）がわかってない）

**Comment by tamaina** [comment]
> Resolve #9532
> # What
> 
> パッケージマネージャーを Yarn v3 から pnpm に切り替える。
> # Why
> 
> ・セキュリティの向上 (意図しないパッケージへのアクセス制限) ・Yarnよりも速く、省スペース ・ビルドの並列実行による高速化 ・Shell Emulatorが搭載されていてどのプラットフォームでも同じ構文のスクリプトを実行可能 (Yarnと同等) ・改良されたアルゴリズムで二重インストールや余分なスペースの使用を抑制 ・Gitからのインストールがバグらない ・Yarn v3のようなパッケージマネージャー本体の同梱が不要 ・npmよりかはマシ (速さやパッケージのセキュリティチェックなど)
https://github.com/misskey-dev/misskey/pull/9531#issue-1530546394

**Comment by tamaina** [comment]
> sharpとかが壊れて[こうなる](https://github.com/TeamBlackCrystal/ayuskey/issues/136)から変えたほうがいいかも
https://github.com/misskey-dev/misskey/pull/9531

pnpmではそういうことは起きないのかしら？  
(npmでもビルドが壊れる問題はあったような気がする)

**Comment by tamaina** [comment]
> Yarn v3のようなパッケージマネージャー本体の同梱が不要

本体同梱はDocker対応のための苦肉の(?)策と認識しているんだけど、pnpmではそれが不要ということ？ @CyberRex0

**Comment by CyberRex0** [comment]
> 本体同梱はDocker対応のための苦肉の(?)策と認識しているんだけど、pnpmではそれが不要ということ？

はい

**Comment by sousuke0422** [comment]
> > sharpとかが壊れて[こうなる](https://github.com/TeamBlackCrystal/ayuskey/issues/136)から変えたほうがいいかも
> https://github.com/misskey-dev/misskey/pull/9531
> 
> pnpmではそういうことは起きないのかしら？  
> (npmでもビルドが壊れる問題はあったような気がする)

少なくとも今のところは壊れてない
