### ISSUE TITLE
フォローリクエスト一覧のapiのページネーションが機能していない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#9547]
## 💡 Summary
フォローリクエスト一覧のapiのページネーションが機能していない

## 🥰 Expected Behavior

スクロールすると続きが帰ってくる

## 🤬 Actual Behavior

同じ内容しか帰ってこない

## 📝 Steps to Reproduce

1. `api/following/requests/list`を叩く

## 📌 Environment

Misskey version: 13.0.0-beta.42
Your OS: Windows 11
Your browser: 109.0.5414.75

**Comment by syuilo** [comment]
これv12では発生しなかった？

**Comment by sim1222** [comment]
v12.120.0でも発生してるかも(この現象らしい挙動に気づいたのは2ヶ月前くらいから)
gitのログを見る限り結構前から発生してたかもしれない？
