### ISSUE TITLE
[v13] Custom Emoji not functioning as expected

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9549]
## 💡 Summary

I have encountered issues with custom emoji after updating to Misskey version 13.0.0-beta.40~42. It seems that the problem is that custom emoji are not being updated immediately.

## 🥰 Expected Behavior

When adding or updating a custom emoji, the changes should be reflected immediately.

## 🤬 Actual Behavior

Despite adding or updating a custom emoji, the changes are not reflected, and the emoji does not appear in the emoji picker. However, if the emoji name is used in a note, the emoji will appear in the note.

There have been instances where previously registered emojis appeared normally in the emoji picker after updating from beta.40 to beta.42. However, the problem still persists. Two emojis have not been working since updating to beta.40 from beta.1 and there have been TypeErrors for these emojis in the server log.

```
INFO 1     [download]      Downloading https://cdn.stella.place/D1/e95337b8-499b-47b2-811e-e1f4398efc69.gif to /tmp/tmp-112-80emfMf81BQT ...
INFO 4     [download]      Downloading https://cdn.stella.place/D1/51240ea1-345e-4d43-a293-300dc968197a.gif to /tmp/tmp-112-AUZUJ562TSAq ...
ERR  1     [server]        TypeError: terminated
ERR  4     [server]        TypeError: terminated
```

## 📝 Steps to Reproduce

1. Add or update a custom emoji.
2. Check the custom emoji in the custom emoji list in the instance information or open the emoji picker or attempt autocompletion of the custom emoji by typing ':' in the note writing window.
3. Confirm that the changes have been applied successfully.

## 📌 Environment

Misskey version: Misskey version: v13.0.0-beta.42
Your OS: Windows 11 Pro Insider Preview 25276.1000
Your browser: Microsoft Edge 110.0.1587.6 (Official build) dev (64-bit)

**Comment by syuilo** [comment]
This is a specification since custom emojis are being cached, but there may be room for improvement.
