### ISSUE TITLE
[v13] Drive upload failed (permission denied)

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9564]
## 💡 Summary

When attempting to upload files to Drive while object storage is not in use, a permission error occurs.

## 🥰 Expected Behavior

Drive uploads should be successful.

## 🤬 Actual Behavior

An error occurs during the upload process.

```
Internal error occurred. Please contact us if the error persists.
INTERNAL_ERROR
5d37dbcb-891e-41ca-a3d6-e690c97775ac
```

```
INFO 1     [drive register]        {"size":331649,"md5":"73605fac407cf773f8b90ceabe527b3e","type":{"mime":"image/png","ext":"png"},"width":2048,"height":1222,"blurhash":"e12=[it5oMx?.8_3RQMzawt8%gt2flt3W;xvn$WZoJWE%MjqkWaxof","sensitive":false,"porn":false,"warnings":[]}
INFO 1     [drive register]        web image not created (original satisfies webpublic)
Error: EACCES: permission denied, copyfile '/tmp/tmp-101-KTUXrsyKXfUj' -> '/misskey/files/89551aa4-3b5b-4a6f-8c64-5e56c8e38587'
    at Module.copyFileSync (node:fs:2866:3)
    at InternalStorageService.saveFromPath (file:///misskey/packages/backend/built/core/InternalStorageService.js:35:12)
    at DriveService.save (file:///misskey/packages/backend/built/core/DriveService.js:152:53)
    at async DriveService.addFile (file:///misskey/packages/backend/built/core/DriveService.js:482:20)
    at async file:///misskey/packages/backend/built/server/api/endpoints/drive/files/create.js:88:35
    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:271:16) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/tmp/tmp-101-KTUXrsyKXfUj',
  dest: '/misskey/files/89551aa4-3b5b-4a6f-8c64-5e56c8e38587'
}
```

## 📝 Steps to Reproduce

1. Disable object storage.
2. Attempt to upload files to Drive.

## 📌 Environment

Misskey version: 13.0.0-rc.5
Your OS: Windows 11 Pro Insider Preview 25276.1000
Your browser: Microsoft Edge 110.0.1587.6 (Official build) dev (64-bit)

**Comment by ikuradon** [comment]
Due to https://github.com/misskey-dev/misskey/pull/9560, you need to execute `chown -hR 991.991 ./files` on misskey directory.

**Comment by caipira113** [comment]
> Due to #9560, you need to execute `chown -hR 991.991 ./files` on misskey directory.

It's a docker environment, does the same apply?

**Comment by ikuradon** [comment]
This command only needs on docker environment.

**Comment by caipira113** [comment]
> Due to #9560, you need to execute `chown -hR 991.991 ./files` on misskey directory.

Do I have to create and proceed with the same groups and users on the server?

**Comment by ikuradon** [comment]
> Do I have to create and proceed with the same groups and users on the server?

No, just run the command. The user exists in the Docker image.

**Comment by caipira113** [comment]
Should we close the issue?

**Comment by orzklv** [comment]
However, running command results to:
`chown: changing ownership of './files': Operation not permitted`

**Comment by caipira113** [comment]
> However, running command results to: `chown: changing ownership of './files': Operation not permitted`

Did you try it with appropriate permissions? Please try again as root or prepend the command with sudo.

**Comment by orzklv** [comment]
> > However, running command results to: `chown: changing ownership of './files': Operation not permitted`
> 
> Did you try it with appropriate permissions? Please try again as root or prepend the command with sudo.

I'm actually running misskey in a docker container and I tried to execute the command as misskey user. Can't su to root or whatever. Checked issues and there were an issue where it said that docker container was transitioned to rootless container and now quite not sure what to do with it )

**Comment by caipira113** [comment]
> > > However, running command results to: `chown: changing ownership of './files': Operation not permitted`
> > 
> > 
> > Did you try it with appropriate permissions? Please try again as root or prepend the command with sudo.
> 
> I'm actually running misskey in a docker container and I tried to execute the command as misskey user. Can't su to root or whatever. Checked issues and there were an issue where it said that docker container was transitioned to rootless container and now quite not sure what to do with it )

I need to execute the command on the host system, not inside the container. Please run the command again on the host.

**Comment by orzklv** [comment]
> > > > However, running command results to: `chown: changing ownership of './files': Operation not permitted`
> > > 
> > > 
> > > Did you try it with appropriate permissions? Please try again as root or prepend the command with sudo.
> > 
> > 
> > I'm actually running misskey in a docker container and I tried to execute the command as misskey user. Can't su to root or whatever. Checked issues and there were an issue where it said that docker container was transitioned to rootless container and now quite not sure what to do with it )
> 
> I need to execute the command on the host system, not inside the container. Please run the command again on the host.

❯ sudo chown -hR 991.991 ./files
chown: warning: '.' should be ':': ‘991.991’

ok, let' see...

**Comment by orzklv** [comment]
ok, it worked! thank you very much for your assistance <3 @caipira113
