### ISSUE TITLE
[v13] Failed to upload file.

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#9567]
## 💡 Summary
Failed to upload file

## 🤬 Actual Behavior
INTERNAL_ERROR 5d37dbcb-891e-41ca-a3d6-e690c97775ac
![image](https://user-images.githubusercontent.com/26847027/212477302-164b6f7b-030b-4d73-b6a1-77183e4bf4ad.png)

![image](https://user-images.githubusercontent.com/26847027/212477289-307e1ef0-f2d5-4a8a-8074-f3a22794322d.png)

## 📝 Steps to Reproduce

1. Upload an image.

## 📌 Environment

Misskey version: 13.0.0-rc.5 (docker)
Your OS: GNU Guix
Your browser: GNU IceCat 102.6.0esr

**Comment by tamaina** [comment]
Did you check https://github.com/misskey-dev/misskey/issues/9564 ?

**Comment by rakino** [comment]
@tamaina That's exact the issue, thank you!
