### ISSUE TITLE
gulpやめる

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#9575]
gulpの最終リリースは4年前となっており ( https://www.npmjs.com/package/gulp )、メンテナンス面や脆弱性対応の面で難がある状態になっています。
従って、別のビルドシステムに乗り換えるのが良いかと思います。

**Comment by CyberRex0** [comment]
~~Gruntはどうかと思ったけど、去年5月で開発が止まっている~~
そもそもgulpの先祖だったのでなし

**Comment by rinsuki** [comment]
gulpに脆弱性があるとしてどこから付けるのかはかなり謎な気がしますし、なかなかいい代わりのものもないような…。

**Comment by massongit** [comment]
webpackに乗り換える、みたいなのはなしなのですかね？

**Comment by tamaina** [comment]
そうかー gulp4からもう4年か…（遠い目

**Comment by tamaina** [comment]
> Let's start by clearing up a common misconception. Webpack is a module bundler like Browserify or Brunch. It is not a task runner like Make, Grunt, or Gulp.

https://webpack.js.org/guides/integrations/

**Comment by syuilo** [comment]
コピーくらいしかしてないし生JSで良い説

**Comment by CyberRex0** [comment]
terserとcssnanoを直接使って独自のビルドスクリプトを書けば・・と思ったけど保守性がないか

**Comment by massongit** [comment]
>コピーくらいしかしてないし生JSで良い説

>terserとcssnanoを直接使って独自のビルドスクリプトを書けば・・と思ったけど保守性がないか

この辺りで良さそうな感じしますね。

**Comment by tamaina** [comment]
gulp由来のdeprecatedが多い（source-map-resolve, urix, resolve-urlあたり）

https://github.com/misskey-dev/misskey/issues/8940
