### ISSUE TITLE
ログアウトボタン追加

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#9576]
共用PCで一時的にログインしている、一時的にあるアカウントに切り替えるなど、ログアウトの上アカウントを切り替えたい場合もあると思うので、ログアウトボタンを追加すると良さそうです。

**Comment by tamaina** [comment]
ナビゲーションバーに追加したいということでしょうか？

**Comment by massongit** [comment]
具体的な場所はあまり考えていなかったですが、ナビゲーションバーで良いように思います。

**Comment by tamaina** [comment]
ナビゲーションバーというか、一番左下のアカウントメニュー内にあると親切かも

**Comment by massongit** [comment]
確かに。
そちらの方が分かりやすいですね。

**Comment by massongit** [comment]
13.3.4にてログアウトボタンが存在することを確認。

**Comment by tamaina** [comment]
（やっぱり見つけられていないだけだったのか
