### ISSUE TITLE
検索ダイアログで変換確定するとそのまま検索されてしまう

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#9598]
## 💡 Summary

検索ダイアログで変換確定 (変換候補選択後エンター押下) するとそのまま検索されてしまい、続く文字列が入力できません。

## 🥰 Expected Behavior

検索ダイアログで変換確定 (変換候補選択後エンター押下) すると続く文字列が入力できる。

## 🤬 Actual Behavior

検索ダイアログで変換確定 (変換候補選択後エンター押下) すると検索される。

## 📝 Steps to Reproduce

1. ナビゲーションバーの検索ボタン押下
2. 文字列を入力し変換確定

## 📌 Environment

Misskey version: 12.119.2, 13.0.0-rc.9
Your OS: macOS 12.6.2 (MacBook Air (M1, 2020))
Your browser: Google Chrome 109.0.5414.87

**Comment by tamaina** [comment]
Firefoxでは起きないけどChromeだと再現する
