### ISSUE TITLE
[v13] [docker] Fluent Emoji not found.

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#9601]
## 💡 Summary

![image](https://user-images.githubusercontent.com/26847027/212544884-fa419825-4825-491d-8e6b-2785846f6437.png)

## 🥰 Expected Behavior

Fluent Emoji.

## 🤬 Actual Behavior

Emojis not found, alt texts (native emojis) are used instead.

## 📝 Steps to Reproduce

1. Navigate to `<baseURL>/settings/general`
2. Select Fluent Emoji.

## 📌 Environment

Misskey version: 13.0.0-rc.9 (Docker)
Your OS: Guix System
Your browser: GNU IceCat 102.6.0esr

**Comment by CyberRex0** [comment]
fluent emoji assets are stored in another repository, it is as submodule
`git submodule update --init` to download them

**Comment by rakino** [comment]
@CyberRex0 Thank you! I thought about that at first, howerer later I found there was actually already a line in the [Dockerfile](https://github.com/misskey-dev/misskey/blob/e1bd61c70ee512a90666904eba8cf279f4366808/Dockerfile#L24):
```Dockerfile
RUN git submodule update --init
```

**Comment by CyberRex0** [comment]
Can you add this line into Dockerfile after line 48 and solve this?
`COPY --chown=misskey:misskey --from=builder /misskey/fluent-emojis /misskey/fluent-emojis`

**Comment by rakino** [comment]
It works!
