### ISSUE TITLE
[v13] Avatar images within a button are linked to the profile page.

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#9606]
## 💡 Summary

![image](https://user-images.githubusercontent.com/26847027/212550481-fd83acf8-ef23-4bdf-a1b7-4bb8c7682ab9.png)

![image](https://user-images.githubusercontent.com/26847027/212550604-fb62ed2e-0fd9-4dc1-9220-1b4d59095e3e.png)

## 🥰 Expected Behavior

No link for the image.

## 🤬 Actual Behavior

When clicking the button, the image might be clicked instead, opening the profile page as a result.

## 📌 Environment

Misskey version: 13.0.0-rc.9 (Docker)
Your OS: Guix System
Your browser: GNU IceCat 102.6.0esr

**Comment by tamaina** [comment]
投稿フォームのアカウント切り替えもリンクになってしまっている

**Comment by tamaina** [comment]
kebab-caseの指定をcamelCaseのpropに変換できなくなったようなんだが、どの時点でなぜそうなったのかまだ把握していない

**Comment by tamaina** [comment]
**disable-linkが削除されているだけだった**  
なぜ？
