### ISSUE TITLE
pnpmをcorepack経由でインストールする

### ISSUE THREAD

**Issue by ikuradon** [syuilo/Misskey#9611]
## Summary

(主にDockerの話)
せっかくpackage.json内で`packageManager`を使っているので`npm i -g pnpm`ではなく`corepack enable`で処理させたい

**Comment by ikuradon** [comment]
non-Dockerの方々はお好きにpnpmを入れてくれ…というか強制する方法無くない？

**Comment by tamaina** [comment]
corepack enableするように案内したいけどmisskey-hubの改訂が追いついていない

**Comment by tamaina** [comment]
misskey-hubは記述変えた
