### ISSUE TITLE
Visibility Picker is Misaligned and Displaying on the Left

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9612]
## 💡 Summary

The Visibility Picker is not properly aligned and is displaying on the left side instead of the center.

## 🥰 Expected Behavior

The visibility picker should be centered.

## 🤬 Actual Behavior

<img width="30%" alt="Screenshot_20230116_153825_Chrome Dev" src="https://user-images.githubusercontent.com/54402969/212613744-133f4402-2bbd-46ad-94f4-5337af171bd5.png">

As seen in the attached screenshot, the Visibility Picker is displayed on the left side of the screen, rather than being centered.

## 📝 Steps to Reproduce

1. Open the Visibility Picker on a mobile device.

## 📌 Environment

Misskey version: v13.0.0
Your OS: Android 13
Your browser: Chrome 111.0.5531.3 (Official build) dev (64-bit)

**Comment by kazukyakayashi** [comment]
Same on Fennec/Firefox on Android 11.

**Comment by caipira113** [comment]
Close this issue as #10442 appears to have resolved the issue.
