### ISSUE TITLE
カスタム絵文字の更新を即時反映する

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9618]
## Summary
- custom-emojis.tsのcustomEmojisをrefにする
- custom-emoji-managerで変更を叩いたら即座にfetchCustomEmojis()

**Comment by EbiseLutica** [comment]
これだと変更した当人にしか反映されないかも…。

**Comment by tamaina** [comment]
気休めに10分おきにfetchCustomEmojisするようにするか

**Comment by tamaina** [comment]
ストリーミングで一斉伝達は流石にきついか

**Comment by EbiseLutica** [comment]
変更イベントみたいなのを送ってfetch　→　同接3ケタなで死にそう
ストリーミングで差分を送る　→　工数かかりそうだけど最善策？

**Comment by syuilo** [comment]
そんな頻繁に変更されるものではない気がするし要る？

**Comment by syuilo** [comment]
設定からキャッシュクリアしてもらうことですぐに反映させることはできる

**Comment by tamaina** [comment]
頻繁にキャッシュクリアするのは微妙だし、すぐ変更されないとちょっとフラストレーションが溜まる

**Comment by tamaina** [comment]
> すぐ変更されないとちょっとフラストレーションが溜まる

特におひとり様運用だと

**Comment by EbiseLutica** [comment]
頻繁に変更はされづらいかもだけど、追加は頻繁に行うので現状は不便

**Comment by EbiseLutica** [comment]
Related to #9549
