### ISSUE TITLE
Starting SW building... Could not resolve v13

### ISSUE THREAD

**Issue by okpierre** [syuilo/Misskey#9624]
## 💡 Summary
```

│ Error: Build failed with 5 errors:
│ src/filters/user.ts:2:22: ERROR: Could not resolve "misskey-js/built/acct"
│ src/scripts/get-account-from-id.ts:1:20: ERROR: Could not resolve "idb-keyval"
│ src/scripts/lang.ts:4:25: ERROR: Could not resolve "idb-keyval"
│ src/scripts/notification-read.ts:1:20: ERROR: Could not resolve "idb-keyval"
│ src/scripts/operations.ts:5:25: ERROR: Could not resolve "misskey-js"
```

## 🥰 Expected Behavior

No build errors for new install

## 🤬 Actual Behavior

all the errors https://pastebin.com/u8PzTeiH

## 📝 Steps to Reproduce

1. follow installation docs
2. errors during build process 

## 📌 Environment

Misskey version: v13 https://github.com/misskey-dev/misskey/commit/9d64ac6d6f4050b260d1a3ff39efbd932f4a523f
Your OS: Ubuntu Linux VPS 2GB memory

**Comment by tamaina** [comment]
> follow installation docs

The installation doc is useless because they still use yarn.  
https://misskey-hub.net/en/docs/install/manual.html

Please use pnpm instead of yarn.

**Comment by tamaina** [comment]
I updated misskey-hub.

**Comment by Sakrecoer** [comment]
Thank you @tamaina! Wouldn't the systemd service also need to refer to pnpm? 
Currently it shows `ExecStart=/usr/bin/npm start`

**Comment by tamaina** [comment]
> Wouldn't the systemd service also need to refer to pnpm?

Either npm or pnpm may be acceptable...I do not have a clear answer.

**Comment by yitsushi** [comment]
Can be related: https://github.com/misskey-dev/misskey/issues/9328#issuecomment-1504435146

**Comment by KisaragiEffective** [comment]
triage: we use pnpm in recent releases.
