### ISSUE TITLE
users/search-by-username-and-host がリモートユーザーしか検索しない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9627]
## 💡 Summary

users/search-by-username-and-host がリモートユーザーのみ検索してローカルユーザーを表示してくれない

## 🥰 Expected Behavior

hostが空の場合はローカルのユーザーも検索結果に現れる。

## 🤬 Actual Behavior

現れない。hostに自分のホスト名を入れても無理だった

## 📝 Steps to Reproduce

メンション先の追加などで試す

## 📌 Environment

Misskey version: 13.0.0
Your OS: macOS Monterey 
Your browser: 5.6.2867.58 (Stable channel) （arm64）

**Comment by tamaina** [comment]
hostをnullにすれば良かったはず

**Comment by syuilo** [comment]
再現しなかった

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/212807964-fb180f4e-04c4-4000-bb0a-ca81f3611798.png)

**Comment by tamaina** [comment]
![Screenshot_20230117-130856.png](https://user-images.githubusercontent.com/7973572/212808092-80dd05eb-1255-4992-b44f-1a5fae01c2a3.png)

**Comment by tamaina** [comment]
通常の検索になってしまっているらしい（hostの指定が無効？）

**Comment by CyberRex0** [comment]
んー……
リモートにも同じIDでアカウントが複数あると変になるみたい？

自分のところに あずきゃさん (melt_adzuki) と こけっちさん (_kokt) がカッコの中のIDで登録してるので検索してみて
https://mi.cbrx.io/

**Comment by tamaina** [comment]
エンドポイントやコンポーネントの挙動が変というよりは、ロールの指定のときにはローカルユーザーだ検索してほしいのにその制限がついていないというのが問題なんじゃ

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/212808582-67c92004-ca95-4dbf-ba66-0fd4eda93b2a.png)
![image](https://user-images.githubusercontent.com/4439005/212808608-b433ad6b-cf15-449a-a02b-89b61c5f0465.png)
でた

**Comment by syuilo** [comment]
> エンドポイントやコンポーネントの挙動が変というよりは、ロールの指定のときにはローカルユーザーだ検索してほしいのにその制限がついていないというのが問題なんじゃ

リモートユーザーにもロール付けたいときは普通にありそう

**Comment by CyberRex0** [comment]
…………🤔
昨日の自分が見間違っていたのだろうか
もう一度見てみる

**Comment by CyberRex0** [comment]
これ原因分かった
画面幅に合わせて表示数が変わってて、ローカルユーザーが出てくる手前で途切れたのかも

**Comment by tamaina** [comment]
> リモートユーザーにもロール付けたいときは普通にありそう

あーたしかに…

**Comment by syuilo** [comment]
> 画面幅に合わせて表示数が変わってて

あれそんな機能実装したっけか

**Comment by tamaina** [comment]
ローカルユーザとリモートユーザーを一発で出し分けてほしいものだけど、スマートなUiがパッとおもいつかない

**Comment by CyberRex0** [comment]
ピッカーをローカルとリモートでタブ分けるか、ローカルを優先的に表示することができるなどの柔軟性を備えるか？

**Comment by CyberRex0** [comment]
一定期間アクティブじゃないと検索から除外されるのが働いてる？
どういう順番で検索してるのかちょっと理解できてないから怪しいんだけど

**Comment by sim1222** [comment]
`users/search-by-username-and-host`はupdatedAtがNULLまたは30日以降の場合検索から除外するようになっているので、一度も使われていないまたは30日使用されていないユーザーが表示されないのが原因かもしれません。
メンションなどの入力時にアクティブユーザーのみの検索をすることは合理的ではありますが、ロール設定時にもアクティブユーザーのみに絞り込むのは少し不便なので、`admin/show-users`に向けるか、`users/search-by-username-and-host`のパラメーターを追加するなどしてすべてのユーザーを検索できるようにする必要があるかもしれません。

**Comment by nexryai** [comment]
#9130 と関係してる可能性？
