### ISSUE TITLE
icons not very understandable

### ISSUE THREAD

**Issue by kazukyakayashi** [syuilo/Misskey#9628]
## 💡 Summary

Some of the icons are not very understandable, for example the one used for the local TL, which is also used in the dashboard for the Instances.

<img width="331" alt="Capture d’écran 2023-01-16 à 13 27 56" src="https://user-images.githubusercontent.com/39823221/212681028-2729a6a9-bb61-4550-8ef7-909c23e76426.png">

<img width="819" alt="Capture d’écran 2023-01-16 à 13 36 59" src="https://user-images.githubusercontent.com/39823221/212681035-6871ce34-9d3a-4b25-b65d-88eb2fb53a52.png">

It would be better adapted to the global TL and would match with the dashboard.

The same goes for the icon for the social TL which looks more like an icon for a discovery function.

**Comment by kazukyakayashi** [comment]
I test with other icons.

<img width="256" alt="Capture d’écran 2023-01-16 à 14 19 20" src="https://user-images.githubusercontent.com/39823221/212688284-cef41eec-d202-495d-b7c5-18c8a9563ace.png">

I haven't found better for the local TL for the moment (which makes me think of something like small local business so something local but it's not great either)

**Comment by tassoman** [comment]
It's an interplanetary platform :thinking: 
If anything, antenna and TV turns me into the Showa era... But we need it

:tokyo_tower: This is a powerful antenna

**Comment by KawaneRio** [comment]
Probably just need some time to get used to it. I mean, when I first started Misskey, the mere concept of having more than one Timeline was already new.

And also, like tassoman had wrote, the idea of having planets, rockets, and galaxies does indeed line up with the tagline of *Misskey──An Interplanetary Microblogging Platform* :)

**Comment by kazukyakayashi** [comment]
The problem is rather in the coherence of the icons, the planet icon is used both for the local TL but also to represent the federation in the dashboard (showing the number of known instances) while at the same time another icon (ti-whirl, which I can't find/see on Tabler's website) is used for the global federated TL and for the Federation menu in the admin control panel.

The icons have to be understandable from the beginning, especially for newcomers.

**Comment by tassoman** [comment]
I agree with the need of coherence. In addition we need to remember basic Nielsen rule: **Always know where you are, where you came from, where you're going to**.

In the dashboard they probably wanted to assure number of planets as number of local instances (different from ours). So it's a whole galaxy.

- Home timeline, it's ok.
- Local timeline can't be a country o region, so I agree with the planet. Maybe earth, but it's always used for geolocation
- Rocket it's ok for a visit of other planets in the galaxy, with our friends (so, it's social timeline)
- Galaxy is ok for the complex of fediversity
