### ISSUE TITLE
V13.0.0 Can not upload anything to Drive

### ISSUE THREAD

**Issue by Morethanevil** [syuilo/Misskey#9629]
Everytime I want to upload a jpg or png, I get the same error

Hochladen fehlgeschlagen Internal error occurred. 
Please contact us if the error persists. 
INTERNAL_ERROR 5d37dbcb-891e-41ca-a3d6-e690c97775ac

The ID at the end is always the same. I can create folders or remove files from Drive, but uploading is not possible

**Comment by CyberRex0** [comment]
What is your environment? (Server type, OS, is it docker etc.)

**Comment by Morethanevil** [comment]
Ubuntu Server 22.04
Misskey runs in docker
Postgres 15.1
Redis 7.0.7
I upgraded from latest V12 to V13

**Comment by Morethanevil** [comment]
Okay it works now
The user changed to ID 991

Sudo chown -hR 991:991 ./files
Did the trick. This should be mentioned in the changelog

**Comment by jberger** [comment]
I had this same problem, please mention

**Comment by Ahwxorg** [comment]
Had the same problem, please mention!

**Comment by imashen** [comment]
ME TOOOOOOOOOOOO!
Internal error occurred. Please contact us if the error persists.
INTERNAL_ERROR
5d37dbcb-891e-41ca-a3d6-e690c97775ac
![bug?](https://github.com/user-attachments/assets/c7779900-946e-40bb-bf92-3e5c5f8db2d7)

**Comment by KisaragiEffective** [comment]
> ME TOOOOOOOOOOOO! Internal error occurred. Please contact us if the error persists. INTERNAL_ERROR 5d37dbcb-891e-41ca-a3d6-e690c97775ac

Could you provide related logs if you are an admin of there? The screen capture said nothing other than happened.
