### ISSUE TITLE
Renote元のノートがワードミュート対象であっても表示されてしまう

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9653]
## 💡 Summary

Renoteがワードミュートをすり抜ける模様

ハードミュートでしか検証していない

## 🥰 Expected Behavior

Renote元のノートがワードミュート対象なら表示しない

## 🤬 Actual Behavior

Renote元のノートがワードミュート対象であっても表示されてしまう

## 📝 Steps to Reproduce

1. ワードミュートに任意の単語を追加する
2. ミュートされた単語を含むノートを別アカウントでRenoteする
3. TLにそのRenoteがあることを確認する

## 📌 Environment

Misskey version: Misskey v13 (v12以前から確認されている)
Your OS: Windows 11
Your browser: Chrome

**Comment by samunohito** [comment]
@EbiseLutica 
> Misskey version: Misskey v13 (v12以前から確認されている)

ワードミュートの仕組みを一新したときに直った可能性が高いです（2023.12.0-beta.1では発生しない）。
…ので、このissueを閉じようかと思いますが、問題ございませんか？
（現行バージョンに近い環境で起こったら新しいissueかreopenするみたいな形で…）

以下、ローカルで動作検証したときのキャプチャ

〇ミュートワードの設定
<img width=30% src="https://github.com/misskey-dev/misskey/assets/46447427/54b60f25-0dff-4497-bd61-ba5016cc38b7" />

〇別アカウントでノート
<img width=30% src="https://github.com/misskey-dev/misskey/assets/46447427/190044e2-a9ba-402e-9bb9-a58949a3c52e" />

〇ミュートワードを設定した側のTL表示
<img width=30% src="https://github.com/misskey-dev/misskey/assets/46447427/977f8348-d268-4daa-9445-7df9c8d26418" />

〇↑を展開した様子
<img width=30% src="https://github.com/misskey-dev/misskey/assets/46447427/a0fd573c-c7b2-4a09-926c-33776f11c949" />

**Comment by samunohito** [comment]
こちら、上記の通りなのでcloseします。
直近のバージョンでも発生するようでしたら、お手数ですが改めて起票をよろしくお願いいたします。
