### ISSUE TITLE
MTM animation autocomplete is still there

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#9655]
## 💡 Summary

MTM animations were gone but autocomplete still works

## 🥰 Expected Behavior
autocomplete only left MTM commands (x2 x3 x4 etc...)

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/92727/213110791-abd21e42-04a7-4e95-a9fe-5b6f332c15a1.png)

## 📝 Steps to Reproduce

1. Install 13.0.0-rc10
2. new post
3. write `$[`
4. see drop-down autocomplete menu

## 📌 Environment

Misskey: 13.0.0-rc10
Your OS: Docker Compose / any client
Your browser: any

**Comment by EbiseLutica** [comment]
@tassoman These commands are still available in the latest version.

However, Misskey v13 disabled "animated MFM" as default. You can  re-enable it manually to see the previous behavior.

**Comment by tassoman** [comment]
Thank you for your reply! This is wonderful, is a configuration of `default.yml` ?

**Comment by tassoman** [comment]
There is a flag for disabling animation in each profile configuration, default enabled.
