### ISSUE TITLE
[v13] [MFM] No animation on Chrome.

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#9657]
## 💡 Summary

One user reported that some MFM contents were not animated.  However they are displayed well in my environment (Firefox variants).

## 🥰 Expected Behavior

MFM animation.

## 🤬 Actual Behavior

Static contents.

## 📝 Steps to Reproduce

1. Show a note with MFM animation (<https://misskey.io/notes/97u1ybua0j> for example).

## 📌 Environment

Misskey version: 13.0.0
Your OS: Microsoft Windows 11
Your browser: Google Chrome 109.0.5414.75

**Comment by tamaina** [comment]
Please check → Settings - General - (Appearance) Disable MFM with animation

**Comment by rakino** [comment]
That's it! Thank you!
