### ISSUE TITLE
twitterと連携するときに autwh is not a function と言われて

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#9658]
## 💡 Summary
twitterと連携しようとすると `{"statusCode":500,"error":"Internal Server Error","message":"autwh is not a function"}` が帰ってくる

## 🥰 Expected Behavior
ちゃんと連携できる🥰

## 🤬 Actual Behavior
連携できない

## 📝 Steps to Reproduce

1.設定 -> 連携 -> twitterの接続する
2.エラーが出る

## 📌 Environment

Misskey version: 13.0.0
Your OS: windows 11
Your browser: floorp

**Comment by syuilo** [comment]
謎

**Comment by CyberRex0** [comment]
authのtypoでは？

**Comment by CyberRex0** [comment]
typoじゃなかった
そういうモジュールだった
