### ISSUE TITLE
リモートの絵文字が通知に表示されたときに？になってしまう

### ISSUE THREAD

**Issue by Steve-0628** [syuilo/Misskey#9664]
## 💡 Summary

タイトルの通り

## 🥰 Expected Behavior
？にならない

## 🤬 Actual Behavior
？になる

[こんな感じ](https://honi.stesan.dev/notes/9a6m5p0qwh)

## 📝 Steps to Reproduce

1. リモートで絵文字付きのノートをする
2. ローカルで引用する
3. 引用に対してリアクションをして、通知に出す

## 📌 Environment

Misskey version: 13.0.0-23.01.0
Your OS: Windows 10
Your browser: Firefox

Enterを誤爆して空っぽのIssueを作ってしまいました、すみません。

**Comment by caipira113** [comment]
Check this issue #9561

**Comment by Steve-0628** [comment]
Sorry, I missed that issue. Thanks.
