### ISSUE TITLE
一つのアチーブメントの通知が複数届く？

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9674]
https://p1.a9z.dev/notes/9a99nfodqw

**Comment by syuilo** [comment]
獲得した実績の更新はアトミックな処理ではないから、瞬間的に大量の実績を獲得する処理が走ると一部が抜けることがある(抜けても通知は作成される)

**Comment by syuilo** [comment]
リクエストの間隔を開けることで対処
