### ISSUE TITLE
Cannot install 13.0.0-rc.11 (and 13.1.1) in docker-compose

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#9681]
## 💡 Summary

I messed up my beta environment. So I tried to instal from zero. I chose 13.0.0-rc.11 before but not working. So I chose 13.1.1 just released. But not working too.

## 🥰 Expected Behavior

I expected to run initialization script

## 🤬 Actual Behavior

```
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". ENOENT: no such file or directory, open '/misskey/packages/backend/built/../../../.config/default.yml'
    at CommandUtils.loadDataSource (/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/node_modules/.pnpm/typeorm@0.3.11_ioredis@4.28.5+pg@8.8.0/node_modules/typeorm/commands/MigrationRunCommand.js:41:26)
```

The problem is `ormconfig.js` asking  missing file `/misskey/packages/backend/built/../../../.config/default.yml` should be: `/misskey/.config/docker.yml`

I temporary solved by symlinking the two files, inside docker host :

```
cd .config
ln -s docker.yml default.yml
```

## 📝 Steps to Reproduce

1. checkout 13.1.1
2. exec: sudo docker-compose build (ok)
3. exec: sudo docker-compose run --rm web pnpm run init
4. watch: failing logs

## 📌 Environment

Misskey version: 13.1.1 and 13.0.0-rc.11
Your OS: ubuntu + docker
Your browser: any

**Comment by tassoman** [comment]
First user I created isn't not administrator. It's normal user.

Running psql inside the db container:

```
misskey=# select * from user; 
 user 
------
 mku
(1 row)
```

I expected to have the complete table of local users

**Comment by Trif4** [comment]
In postgres, selecting from `user` will query database users. To query the Misskey user table, add quotes around the table name, i.e. `"user"`.
