### ISSUE TITLE
There is an issue with custom emojis being displayed as text

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9682]
## 💡 Summary

There is an issue with the recent update where a custom emoji displayed in note reaction is not displaying as an image, but rather as text. This affects both local and remote emojis.

## 🥰 Expected Behavior

Custom emojis should be displayed as images, not text.

## 🤬 Actual Behavior

<img width="651" alt="image" src="https://user-images.githubusercontent.com/54402969/213885646-6136612d-4206-4f93-af97-140043b13dea.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/54402969/213885452-563606d3-1236-4d74-ab63-83795613d798.png">
All custom emojis are displayed as text.

## 📝 Steps to Reproduce

1. Update to version 13.1.1.
2. View custom emojis in note reaction.

## 📌 Environment

Misskey version: v13.1.1
Your OS: Windows 11 Pro Insider Preview 25276.1000
Your browser: Microsoft Edge 111.0.1619.2 (Official build) dev (64-bit)

**Comment by syuilo** [comment]
Try clear cache

**Comment by caipira113** [comment]
> Try clear cache

Still the same in note reactions 🤔

**Comment by syuilo** [comment]
Thank you for reporting 🙏🏻
