### ISSUE TITLE
Local custom emojis are partially broken after 13.1.x upgrade

### ISSUE THREAD

**Issue by zotanmew** [syuilo/Misskey#9684]
## 💡 Summary

Local custom emojis are partially broken after 13.1.x upgrade, though only some are broken. I can't find a pattern between the ones that are still working and the ones that aren't.

## 🥰 Expected Behavior

<img width="312" alt="image" src="https://user-images.githubusercontent.com/18512463/213889367-f9fb356f-8e1b-4088-b16d-6cadbb87fb10.png">

## 🤬 Actual Behavior

<img width="304" alt="image" src="https://user-images.githubusercontent.com/18512463/213889373-4c131a13-f7ad-40f3-bbd3-8851c5014895.png">

## 📌 Environment

Misskey version: 13.1.3
Your OS: ArchLinux
Your browser: Chrome latest stable

**Comment by HotoRas** [comment]
Flush the cache on settings and try it again ;)

**Comment by usuyuki** [comment]
I also faced the same issue.
You can't just do a browser super reload.
In Chrome, you flush the  cache like this,

<img width="251" alt="image" src="https://user-images.githubusercontent.com/63891531/213899974-25812d2e-91b1-4c99-b89e-d9aea996e559.png">

↓

<img width="239" alt="image" src="https://user-images.githubusercontent.com/63891531/213899930-cf03ea4d-be04-4703-95b0-e1070aaf9b90.png">

↓

<img width="503" alt="image" src="https://user-images.githubusercontent.com/63891531/213899942-b72fefb2-621b-426b-b0ff-99fc25a3e87e.png">

**Comment by syuilo** [comment]
fixed
