### ISSUE TITLE
Clicking on the post part will to the detail page. / 投稿内容部分をクリックで詳細ページに移動するようにする

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/Misskey#9687]
## Summary

表題の通り、TwitterやMastodon等のSNSで使用されている作法にMisskeyも合わせる。
Misskeyは昔から投稿時間部分のクリックで詳細ページに移動するが、理解がしづらいユーザー(主に
Twitterしか利用したことのない初心者?)もいる。
そもそもこれが実現されていないということは何かMisskey側に不都合があったりするのだろうか？

## 備考
投稿内のリンク部分及び投票部分等の他の場所に移動しなければならない部分はそのままクリックで作動するようにする必要がある(z-indexを上にで解消できる?)

**Comment by syuilo** [comment]
これ https://github.com/misskey-dev/misskey/issues/8804

**Comment by rinsuki** [comment]
duplicateはこっち
