### ISSUE TITLE
`13.1.8` Users no longer able to see cutsom emojis

### ISSUE THREAD

**Issue by Sakrecoer** [syuilo/Misskey#9697]
## 💡 Summary
When opening the emoji picker (reaction and note-composer), custom emoji's are displayed as text for all user except the instance admin.

![image](https://user-images.githubusercontent.com/3484593/213934199-a80d20fb-d602-4840-be10-aacfbac8547d.png)

## 🥰 Expected Behavior
open emoji-picker see all emojis, including custom emojis

## 🤬 Actual Behavior
emoji-picker only show default emojis (except for admin)

## 📌 Environment

Misskey version: 13.1.8
Your OS: Ubuntu 20.04
Your browser: behaviour seen in firefox and chromium

**Comment by AruMoon** [comment]
I can confirm same is happening for me after updating

**Comment by syuilo** [comment]
have you tried clearing the cache?

**Comment by AruMoon** [comment]
> have you tried clearing the cache?

That worked

**Comment by Sakrecoer** [comment]
That was easy, thank you very much!
closing
