### ISSUE TITLE
Something strange with the font on the iPhone.

### ISSUE THREAD

**Issue by DarkShyMW** [syuilo/Misskey#9698]
## 🤬 Actual Behavior

Something strange with the font on the iPhone. It does not depend on either the browser or the OS version.

## 📝 Steps to Reproduce

1. Buy IPhone 
2. join to misskey site
3. ta-da!

## 📌 Environment

Misskey version: 13.1.8
Your OS: Ios 16.1.1 / 16.2
Your browser: Chrome, Yandex, etc
![image](https://user-images.githubusercontent.com/30442729/213934367-35fc9e01-ec0b-4637-ac5c-769d8021e4cc.png)

**Comment by zyoshoka** [comment]
Let's merge this issue with #13368.
