### ISSUE TITLE
no role user cant view timeline / ロールがアサインされていないとタイムラインが表示されない

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9700]
## 💡 Summary

ロールがひとつもアサインされないと、タイムラインが表示されない
roleが何もアサインされてないとき i のレスポンスに policiesのキーが生えてなくて undefined key access になる

## 🥰 Expected Behavior
タイムラインが表示されない

## 🤬 Actual Behavior
ログインできるがタイムラインが表示されない

## 📝 Steps to Reproduce

1. 
2.
3.

## 📌 Environment

Misskey version: v13
Your OS:
Your browser:

**Comment by syuilo** [comment]
再現できなかった

**Comment by fruitriin** [comment]
@syuilo 
アクセストークン由来のログインのとき限定？みたい
