### ISSUE TITLE
リノートしたノートが削除されると虚無投稿になる

### ISSUE THREAD

**Issue by nexryai** [syuilo/Misskey#9705]
## 💡 Summary
リノートしたノートが削除されると虚無投稿になります

## 🥰 Expected Behavior
リノートしたノートが削除されるとリノートも消される

## 🤬 Actual Behavior
リノートしたノートが削除されると虚無投稿になる  
![Screenshot from 2023-01-23 14-05-25](https://user-images.githubusercontent.com/61890205/213969214-b76d29e3-7bd7-49dd-8683-8d8a36d1f42f.png)

## 📝 Steps to Reproduce

1. 何かリノートする
2. リノート元を削除
3. 虚無になる

## 📌 Environment

Misskey version: v13.1.8
Your OS: Fedora37
Your browser: Firefox 109

**Comment by syuilo** [comment]
これはio固有の問題ですね🙏
