### ISSUE TITLE
postgres on docker compose unhealthy after upgrade

### ISSUE THREAD

**Issue by sevi-kun** [syuilo/Misskey#9708]
## 💡 Summary

After upgrading from 12.119.0 to 13.2.0. After upgrade, compose doesn't start anymore. postgres:15-alpine container is unhealthy and gets into a boot-loop every time I try to start it. 

## 🥰 Expected Behavior

Container starting. Not being unhealthy.

## 🤬 Actual Behavior

Docker-compose startup command quits with following error: 

root@docker:/mnt/misskey/misskey# docker-compose up -d
misskey_redis_1 is up-to-date
misskey_db_1 is up-to-date
 packages/backend/src/remote/activitypub/renderer/accept.ts   |     8 -
ERROR: for web  Container "73a40c9247f8" is unhealthy.
ERROR: Encountered errors while bringing up the project

## 📝 Steps to Reproduce

1. Upgrade from 12.119.2j to 13.2.0
2. Start docker-compose.

## 📌 Environment

Ubuntu 22.04.1 lxc container with docker 1.5-2 and docker-compose 1.29.2-1.

Misskey version: 13.2.0
Your OS: ubuntu 22.04

**Comment by tassoman** [comment]
You should provide more context, for example with `docker-compose logs -f`.
When I tried to upgrade my beta testing instance, this was screwed up while upgrading to RC11. So I solved by re installing from scratch.
The problem was PostgreSql files from version 12 are not compatible with version 15 and fails. I can't say if you're facing the same problem.

**Comment by tassoman** [comment]
Maybe [pg_upgrade](https://www.postgresql.org/docs/current/pgupgrade.html) is needed?

**Comment by tamaina** [comment]
> Maybe pg_upgrade is needed?

Exact.

**Comment by sevi-kun** [comment]
Sorry. Had to check again. I was actually upgrading from 12.119.0. 

Regarding the logs, it takes some time to pull them out.. I checked the tail, but didn't see anything suspicious. 

I thought it could be the db's version... I'm just not really a pro regarding docker-compose.. (And also dbs) 
For what do I have to watch out?

**Comment by sevi-kun** [comment]
Just checked the PG_VERSION file in the db dir. Version 12. So I definetly need to upgrade.

I'm reading through the man right now, but maybe you can send me the right command? That would be really helpful. Thank you for your help.

**Comment by tamaina** [comment]
There is documentation created by an user, but it is written in Japanese.

https://gist.github.com/CyberRex0/a42c99f9299a9385cfc6ede87185da27

**Comment by sevi-kun** [comment]
I'll try that. (Hopefully translaters will give me the right direction. uwu)

**Comment by sevi-kun** [comment]
That did it. Thank you so much for your help.
