### ISSUE TITLE
undici.fetchのパフォーマンスが悪い？

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9710]
## Summary

なんかパフォーマンス上の問題があるらしい

**Comment by rinsuki** [comment]
たぶんオプションにするくらいだったらそっちに移行したほうが楽

**Comment by syuilo** [comment]
undiciのrequest使えば解決する可能性もありそう

**Comment by tamaina** [comment]
とりあえずrequestでお茶を濁してみるか

**Comment by syuilo** [comment]
あっ
https://github.com/misskey-dev/misskey/blob/9fd1b35d958523205444fecb7e9184072a1720e4/packages/backend/src/core/activitypub/ApRequestService.ts#L166

**Comment by syuilo** [comment]
これbodyをconsumeしてないからモロに

> it is important to always either consume or cancel the response body.

に該当するのでは

https://github.com/nodejs/undici#garbage-collection

**Comment by tamaina** [comment]
あ〜なるほど

**Comment by syuilo** [comment]
consumeするようにすれば解決しそうだけどそれはそうとしてrequest使いたい

**Comment by tamaina** [comment]
書いてるなう

**Comment by tamaina** [comment]
意外と簡単

**Comment by syuilo** [comment]
これMisskeyならinbox受信時は202返してるけどこの場合レスポンスにbodyって入ってるんだろうか
あとMastodonとかも202なんだろうか

**Comment by syuilo** [comment]
request使った場合でもbodyのconsumeはしないといけないらしい

> All response bodies must always be fully consumed or destroyed.
> https://github.com/nodejs/undici/blob/main/docs/api/Dispatcher.md#dispatcherrequestoptions-callback

**Comment by rinsuki** [comment]
undici.fetchやめるならいっそ got あたりで HTTP/2 の恩恵受けたいという気もしてくる (undici って fetch のための採用だったような)

**Comment by tamaina** [comment]
> HTTP/2 の恩恵

…ある？（ほぼないと思っている）

**Comment by CyberRex0** [comment]
HTTP/2では1つのコネクションで並列リクエストをすることができるからちょっとぐらいは変わるんじゃないか

**Comment by syuilo** [comment]
> consumeするようにすれば解決しそうだけどそれはそうとしてrequest使いたい

なんか解決しないっぽい

**Comment by syuilo** [comment]
> HTTP/2では1つのコネクションで並列リクエストをすることができるからちょっとぐらいは変わるんじゃないか

これってリクエスト先が違っても並列にできるってこと？

**Comment by CyberRex0** [comment]
> これってリクエスト先が違っても並列にできるってこと？

オリジンが変わったら無理かも

**Comment by syuilo** [comment]
Misskeyの場合同じオリジンに短時間で複数回リクエストすることは無さそうだからあんまり効果無いかも

**Comment by CyberRex0** [comment]
MisskeyはリクエストにKeep-Alive使ってないんだっけ

**Comment by tamaina** [comment]
> Misskeyの場合同じオリジンに短時間で複数回リクエストすることは無さそうだからあんまり効果無いかも

これを考えた（ただ、キューが溜まると割と恩恵は受けられるのかもしれない）

> MisskeyはリクエストにKeep-Alive使ってないんだっけ

Keep-Aliveは使う(UndiciはデフォルトでKeep-Alive有効)

**Comment by CyberRex0** [comment]
小さい鯖やテストではHTTP/2の効果が現れにくい…(意図的にsleep挟んで詰まらせれば分かるかもしれないが)
障壁がないならサポートしてもいいんじゃないかと思うけど余計なバグが生まれそうなら今のままでも

**Comment by tamaina** [comment]
misskey.ioのWaitingがなくなるまでは保留よな

**Comment by tamaina** [comment]
![webpublic-0b601db3-83c8-4a5e-b11f-b3b20e78ddb9](https://user-images.githubusercontent.com/7973572/214232836-fe7e841e-8143-43c0-a304-f020fe3b34e6.png)

misskey.ioの場合はPub/Subが純増していることも考慮に入れる必要があるかも？  
（とはいえundiciのパフォーマンスは微妙なんだけど）

**Comment by tamaina** [comment]
![webpublic-fef4dfd6-cdb0-4a01-9436-41856a29112c](https://user-images.githubusercontent.com/7973572/214237467-0ccdecde-c0c6-448f-9f1a-e2bc92505297.png)

リクエスト数が倍増しててやばそう

**Comment by rinsuki** [comment]
> > HTTP/2 の恩恵
> 
> …ある？（ほぼないと思っている）

並列リクエストもそうだけどヘッダ圧縮とかでちょっと稼げるかも

**Comment by syuilo** [comment]
undiciFetcherのタイムアウトデフォルトで30秒になってるけど長すぎない？
3秒くらいで良いんじゃないかしら

**Comment by tamaina** [comment]
> undiciFetcherのタイムアウトデフォルトで30秒

30秒というのはkeepAliveのタイムアウト？コネクション確立 + ヘッダー受信 + ボディ受信（それぞれ10秒）のタイムアウト？

**Comment by syuilo** [comment]
わかんないけどbodyTimeoutっていうオプション(Misskeyでは無指定)のデフォルト値見たら30秒だった

**Comment by tamaina** [comment]
> Misskeyでは無指定

clientDefaultsで指定している

**Comment by syuilo** [comment]
headerTimeoutっていうオプションも別にあるけど

**Comment by syuilo** [comment]
> > Misskeyでは無指定
> 
> clientDefaultsで指定している

あー見逃してた

**Comment by syuilo** [comment]
やっぱり直ってないっぽい

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
got試す

**Comment by syuilo** [comment]
戻してみた

**Comment by tamaina** [comment]
治った？（←自分のサーバーで直す気がない）

**Comment by tamaina** [comment]
連合周りだけ戻すか

**Comment by syuilo** [comment]
> 治った？（←自分のサーバーで直す気がない）

まだ不明

**Comment by tamaina** [comment]
配送は速くなったけどCPU使用率が増えた

**Comment by syuilo** [comment]
配送が速くなる=処理されるジョブの数も多くなる=CPU使用率も増える
ということかと思ったけどそうではない？

**Comment by tamaina** [comment]
undiciもタイムアウトを短くするとかでなんとかなるんじゃないかとも思うけど、安定する手段を選んだ方が良さそう

**Comment by tamaina** [comment]
> 配送が速くなる=処理されるジョブの数も多くなる=CPU使用率も増える
> ということかと思ったけどそうではない？

正直トータルで考えた時のCPU使用率は増えすぎな感じがある

**Comment by tamaina** [comment]
色々数字いじってもパフォーマンス上がらないのでundiciはダメということで

**Comment by tamaina** [comment]
> I can confirm that undici.fetch() is significantly slower than node-fetch. Its whole point is spec compatibility, not really speed.
> 
> BTW the bottleneck right now is not in undici at all - it’s in Node.js Web Stream impl.
> 
> This is the tracking issue:
https://twitter.com/matteocollina/status/1610923179920470016

なるほど (このIssueの内容を3行でまとめてって言ったことあるけど2行でまとめたツイートがあったわ)
