### ISSUE TITLE
存在しないAPIにアクセスするとなぜかHTTP 200が戻ってくる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9714]
## 🥰 Expected Behavior

HTTP 404が欲しい

## 🤬 Actual Behavior

HTTP 200になる

## 📝 Steps to Reproduce

1. `curl -v https://misskey.io/api/i/instance`
2. HTTP Statusを確認 (200になる)
3. `curl -d "{}" -v https://misskey.io/api/i/instance`
2. HTTP Statusを再び確認 (今度は404になる)

## 📌 Environment

Misskey version: 13.2.0
Your OS: Windows 11
Your browser: Firefox 111

**Comment by tamaina** [comment]
Duplicate of #128

**Comment by saschanaz** [comment]
https://misskey.io/api/i/instance とか存在しないAPIエンドポイントもHTTP 200になるので何とかしたいと思いますが🤔

**Comment by tamaina** [comment]
> 存在しないAPIエンドポイントもHTTP 200になる

apiはたしかにまずいと思うけど、このIssueの内容とはちょっと違う

**Comment by saschanaz** [comment]
修正してみました
