### ISSUE TITLE
アニメーションをオフに設定しても絵文字のアニメーションが止まらない

### ISSUE THREAD

**Issue by Hiiragi283** [syuilo/Misskey#9720]
## 💡 Summary

以下の手順で設定を変更したが、絵文字のアニメーションが止まらない

設定->クライアント設定->全般->アニメーション画像を再生しない->オンにする

## 🥰 Expected Behavior

一部のスタンプがチカチカするため、アニメーションを切れるようにしたい

## 🤬 Actual Behavior

設定を変更しても絵文字のアニメーションが止まらない

## 📝 Steps to Reproduce

1. 設定->クライアント設定->全般->アニメーション画像を再生しない->オンにする

## 📌 Environment

Misskey version: 13.2.1
Your OS: Windows 10
Your browser: Chrome

**Comment by Hiiragi283** [comment]
この現象、misskey.ioのv13.3.4で再発している気がします
よろしければ再び確認をお願いしたいです

**Comment by rinsuki** [comment]
misskey.io 固有っぽい https://github.com/misskey-dev/misskey/issues/9821#issuecomment-1418926202
