### ISSUE TITLE
[v13] Missing name display when remote Mastodon user leaves name field blank

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9723]
## 💡 Summary

When a remote Mastodon user does not fill in their name, there is an issue where their name does not display and appears missing in Misskey. This was not a problem in v12, but seems to have occurred in v13 (13.1.3 to 13.2.2 have been confirmed to have this issue).

## 🥰 Expected Behavior

If a remote Mastodon user does not fill in their name, Misskey should display their username in place of their name.

## 🤬 Actual Behavior

The name appears empty in the user's profile.

## 📝 Steps to Reproduce

1. Update to version 13.
2. Leave the name field blank in the profile of a remote Mastodon user.
3. Update the remote user's information in Misskey.

## 📌 Environment

Misskey version: v13.2.2
Your OS: Windows 11 Pro Insider Preview 25281.1000
Your browser: Microsoft Edge 111.0.1619.2 (Official build) dev (64-bit)

**Comment by saschanaz** [comment]
Misskey: An empty username sets the `name` field in ActivityStreams to `null`
Mastodon: An empty username sets it to an empty string

The behavior changed in 13.0.0-beta.16 in dcfc526453ccaa5e5a4e0cb237c3380d80eb1a42 where it started to use `??` instead of `||`. 

Not sure null is an allowed value in the spec: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-name

**Comment by saschanaz** [comment]
https://www.w3.org/TR/activitystreams-core/#syntaxconventions

>When serialized, absent properties are represented by either (a) setting the property value to null, or (b) by omitting the property declaration altogether at the option of the publisher. These representations are semantically equivalent.

That allows null value, I guess.

Edit: Because `name` is "may be used on ActivityPub Actors" per the AP spec https://www.w3.org/TR/activitypub/#actor-objects

**Comment by saschanaz** [comment]
So my suggestion is that Misskey should somehow normalize the `name` value either to the empty string or to null. IMO null is better in this case.
