### ISSUE TITLE
[13.2.2] Instance blocks are not saved

### ISSUE THREAD

**Issue by Sakrecoer** [syuilo/Misskey#9725]
## 💡 Summary
Flipping the switch to block an instance in `/instance-info/www.domain-to-block.tld` reloading the page the switch is off again and nothing is shown in `/admin/federation` when list is filtering for "blocked".
![image](https://user-images.githubusercontent.com/3484593/214632071-c4c53937-2deb-4509-a56d-be4c8dc70fb0.png)

![image](https://user-images.githubusercontent.com/3484593/214632165-dd6ad44e-74c2-4e52-8149-2f8838b91423.png)

## 🥰 Expected Behavior

Flipping the block switch on `/instance-info` should block an instance
## 🤬 Actual Behavior

Flipping the block switch has no effect

## 📝 Steps to Reproduce

1. go to `/instance-info/www.domain-to-block.tld`
2. flip the switch labeled "block this instance"
3. refresh the page: the flip is switched back

## 📌 Environment

Misskey version: `13.2.2`
Your OS: ubuntu 20.04

**Comment by Sakrecoer** [comment]
It appears to work fine when entering the domain manually  in `/admin/instance-block` which is.... neat. (never a fun thing to do... :disappointed:)

**Comment by DarkRTA** [comment]
I am having this issue too.  There is almost certainly a bug here.

**Comment by zyoshoka** [comment]
API error issue when there are no blocked hosts has been fixed in #10258 (13.10.0) and this issue fixed in #11429 (2023.9.0), so closing.
