### ISSUE TITLE
投稿本文の描画領域の制限

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9731]
## Summary
まれにMFMを利用した、一部分が埋まる、文字や絵文字が操作部に干渉する形で表示される、大きなスペースが空くという過剰な表現が見受けられる。
そこで描画領域の制限を設ければ、少なくとも操作に影響を及ぼさないのではないかと考える。

補足: もしかして制限してないのはリンクのホバー表示などポップアップ系に不都合が起きるから？

**Comment by syuilo** [comment]
ノートコンポーネント内にクリップされるようにすでに制限してある

**Comment by CyberRex0** [comment]
操作部(アイコンや下のボタン)にまではみ出ないようにするのは難しそう？

**Comment by syuilo** [comment]
難しい

**Comment by syuilo** [comment]
それをするとちょっとしたscaleによる拡大でもクリップされることになり実質的にscaleなどの構文が無意味になる

**Comment by syuilo** [comment]
操作ができないことが問題なら操作部のz-indexを上げれば解決しそう

**Comment by syuilo** [comment]
> もしかして制限してないのはリンクのホバー表示などポップアップ系に不都合が起きるから？

これは関係しない

**Comment by KawaneRio** [comment]
このissueの名前を「操作部のz-indexを上げる」にすることを提案したい。

**Comment by Sayamame-beans** [comment]
fixed by #9999 ?
