### ISSUE TITLE
Independent MediaProxy

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9733]
## Summary

メディアプロキシの負荷を別サーバーに分離したいユースケースがあるため

- データベースと繋ぐか否か

**Comment by tamaina** [comment]
https://github.com/misskey-dev/media-proxy

データベースと繋がない版のFastifyプラグイン書いてみた

**Comment by acid-chicken** [comment]
Media Proxy を Cloudflare Workers とか Fastly Compute@Edge みたいな CDN エッジコンピューティング向けに移植しても良さそうな気はする

**Comment by tamaina** [comment]
~~面倒だから各自で用意して欲しいという気持ちだった~~

**Comment by tamaina** [comment]
Cloudflare WorkersでFastifyを動かす公式な手段はないのか

（エッジコンピューティングとかサーバーレスとかあんまり深く触ったことない）

**Comment by tamaina** [comment]
あー、Cloudflare WorkersだともっとWebっぽく書く必要があるのか

**Comment by tamaina** [comment]
素のV8のエッジはStreamどころかsharp.jsすら使えないのでほぼ書き直しという感じがある

でもFastify版はFastify版として維持する必要もありそう。3つのコードを保守しなければならないことになり若干負担が大きいかもしれない

**Comment by tamaina** [comment]
> Cloudflare Workers とか Fastly Compute@Edge みたいな CDN エッジコンピューティング向けに移植

そもそもCDNエッジコンピューティングが画像変換に向いているかというとなんか微妙じゃないかしら？  
（できないことはないと思うんだけど、AWS Lambdaのようなサーバーレスコンピューティングの方が向いているような気もする）

**Comment by tamaina** [comment]
Cloudflare Workersでどうやって画像処理するんだろうと思って調べたらこういうのがあるらしい  
（Cloudflare Workers専用ではある）

https://developers.cloudflare.com/images/image-resizing/resize-with-workers/#configure-a-worker

**Comment by acid-chicken** [comment]
> （エッジコンピューティングとかサーバーレスとかあんまり深く触ったことない）

シンプルに Web Worker がブラウザじゃなくて CDN エッジで動いてるイメージがわかりやすい

> > Cloudflare Workers とか Fastly Compute@Edge みたいな CDN エッジコンピューティング向けに移植
> 
> そもそもCDNエッジコンピューティングが画像変換に向いているかというとなんか微妙じゃないかしら？ （できないことはないと思うんだけど、AWS Lambdaのようなサーバーレスコンピューティングの方が向いているような気もする）

Cloudflare Image Resize で機能が事足りるならそれに越したことはないんだけど、別に wasm で入れればいいのでどの道できないことはない

**Comment by tamaina** [comment]
例えばCloudflare Workersはコード量制限が1MBや5MBなので、wasmを仕込むのは厳しそう

**Comment by acid-chicken** [comment]
sharp そのもののサイズは計ったことないから分からんけど rust の image crate 使った実装とかはやったことある

**Comment by acid-chicken** [comment]
現状 #9787 で想定している、外部プロキシが画像に対してやることって何？リサイズして webp にするだけ？（読み込めておらず申し訳ない）

**Comment by acid-chicken** [comment]
他はこれか https://github.com/misskey-dev/media-proxy/blob/d463560ef92aaf9dfbfcdb218f67bc9e7d6f9a85/src/index.ts#L100-L134

**Comment by acid-chicken** [comment]
この際だし仕様明文化しようぜ、というか `?thumbnail` とか乱立してるの後から付け足してカオス化した感じがすごいし `?for=thumbnail` みたいな感じにした方が良さそう

**Comment by tamaina** [comment]
AWS Lambdaでリファレンス実装のを試してみたけどなんか遅い（500ms前後？OCI A1で動かしている自分のインスタンスの内蔵プロキシの方が明らかに早い）

https://github.com/tamaina/media-proxy-lambda

**Comment by tamaina** [comment]
> この際だし仕様明文化しようぜ

いいと思うけど、ここだけドキュメント分厚く整備するんかいな感があって微妙な気もする  
（リファレンス実装を作ったので他のことをやりたい）

**Comment by acid-chicken** [comment]
> いいと思うけど、ここだけドキュメント分厚く整備するんかいな感があって微妙な気もする

まぁそんなに大層なものでもなくていいと思うけど、一応形としては外部と連携になるのでどちらが主従になるかも含めて最低きっちりしていた方が良さそう

**Comment by tamaina** [comment]
**AWS Lambdaってペイロード上限が6MBらしい**

これは使い物にならないかもしれない
