### ISSUE TITLE
ついているはずのリアクションが突然消えることがある？

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9735]
## 💡 Summary

v13.2.3より、何度かリアクションの表示が消える現象が起きています。

再現方法がまだ判明していないため、分かり次第更新します

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: Misskey 13.2.3
Your OS:
Your browser:

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/commit/6670c72f8bfd9cd1c076fe85acdf126fb132d026

これは関係ない？

**Comment by EbiseLutica** [comment]
あるかも 13.2.4が出て、しばらく再現しなかったら閉じます

**Comment by EbiseLutica** [comment]
直っているぽいので閉じます。
