### ISSUE TITLE
v13.2.4: build failed ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  sw@ build: `node build.js`

### ISSUE THREAD

**Issue by HolgerHuo** [syuilo/Misskey#9736]
## 💡 Summary

latest release failed to build.

`ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  sw@ build: `node build.js``

`Expected value for define "_DEV_" to be a string, got boolean instea`

## 📝 Steps to Reproduce

1. Checkout v13.2.4 code
2. download modules
3. build source files

## 📌 Environment

Misskey version: v13.2.4
Your OS: RHEL 9
Your browser: N/A

**Comment by syuilo** [comment]
fixed
