### ISSUE TITLE
ユーザーページに Play 一覧を表示してほしい | Show Play list on user page

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#9746]
## Summary

v13 より Misskey Play が もっと！ に表示されるようになりましたが、
ユーザーが作成した Play を一覧表示で確認する手段がなく、ページで作成する必要があります。
ユーザーページでそのユーザーから Play 一覧が表示されるのが良いように思われますので、
これを提案します。よろしくお願いいたします。

**Comment by kakkokari-gtyih** [comment]
Done in #11445
