### ISSUE TITLE
MFMチートシート の アニメーション 一部を削除した方が良い？

### ISSUE THREAD

**Issue by fu-sen** [syuilo/Misskey#9748]
## Summary

Misskey レベルで MFMチートシート が含まれている事を確認しています。

(`https://インスタンス/mfm-cheat-sheet`)
例: https://misskey.io/mfm-cheat-sheet

v13 の MFM で「動きのあるMFMを無効にする」がオンの状態がデフォルトになったため、
MFMチートシートに含まれているアニメーションの一部が動作していない状態が発生しています。
そこで、該当するアニメーションは削除しても良いように思い、提案を入れます。
よろしくお願いいたします。

**Comment by futchitwo** [comment]
機能として存在するので、注釈を入れて残した方がいいと思います

**Comment by fu-sen** [comment]
気をつけてほしいのは、ソースレベルなので、
**言語ファイルにも影響が出る** 部分になります。

https://github.com/misskey-dev/misskey/blob/b906ff3fedf2ec420a057a6d2c851df2b7b77495/locales/ja-JP.yml#L1340-L1405

**Comment by fu-sen** [comment]
**13.6.0 で MFMチートシート そのものが削除されました。** そのため、この issues は討論不要になりました。
クローズします。
