### ISSUE TITLE
Misskey.js で v13インスタンスのAPIを叩くことができない

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9756]
## 💡 Summary

Misskey.jsをnpmにpublishしてほしい
それともForkしたものをnpmにpushしたほうがいい？

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by syuilo** [comment]
0.0.15を出した
