### ISSUE TITLE
api/i/notifications working exception

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#9763]
## 💡 Summary

`api/i/notifications` works abnormally and abruptly from time to time
## 🥰 Expected Behavior

Notifications can be viewed normally
## 🤬 Actual Behavior

`api/i/notifications` will display the 429 status code
## 📝 Steps to Reproduce
Currently not looking for a stable trigger method, but there is a higher probability that the problem will occur in a short period of time with multiple refreshes

## 📌 Environment

Misskey version:13.2.6
Your OS:Windows 11
Your browser:Edge 109

**Comment by fruitriin** [comment]
429 is rate limited.
Check your roll, admin setup the roll rate limit.
It calculate method maybe not you(admin) think.
