### ISSUE TITLE
Error Encountered while Accessing Misskey in private window on Firefox

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#9769]
## 💡 Summary

An issue has been identified while accessing Misskey in a private window using Firefox.

## 🥰 Expected Behavior

Misskey should load without any issues.

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/54402969/216337336-2ca82286-0b21-4f63-92d8-b46487d88c8f.png)
<img width="553" alt="image" src="https://user-images.githubusercontent.com/54402969/216335238-e8bfeead-44c2-41c3-9ad8-a4dfa181d394.png">
As per the screenshot provided, there is an error that occurs when accessing Misskey in a private window in Firefox.

## 📝 Steps to Reproduce

1. Upgrade to the latest commit (~`ed3e035a`)
2. Open Misskey in a private window using Firefox.

## 📌 Environment

Misskey version: v13.2.6 (`ed3e035a`)
Your OS: Windows 11 Pro Insider Preview 25284.1000
Your browser: Firefox (release 109.0.1, dev 110.0b8)

**Comment by caipira113** [comment]
![image](https://user-images.githubusercontent.com/54402969/216338974-04da3592-c5b1-4cde-8fa2-e451243363b7.png)
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/54402969/216339714-9873c5be-1789-4064-8ceb-ca0b859d958e.png">
Additionally, the `/flush` also appears to be failing.

**Comment by saschanaz** [comment]
Probably #9225, because IndexedDB is not available on Firefox private browsing mode.

**Comment by acid-chicken** [comment]
How about using [fake-indexeddb](https://github.com/dumbmatter/fakeIndexedDB) as a fallback? cc: @tamaina

**Comment by acid-chicken** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

And note that you can temporarily avoid this problem by enabling IndexedDB from `dom.indexedDB.privateBrowsing.enabled` on about:config instead, at the loss of some privateness (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1639548).

**Comment by tamaina** [comment]
idb-proxyでlocalStorageにフォールバックするようにしたんだけどちょっと実装が微妙だったのかも

**Comment by tamaina** [comment]
手元のFirefoxではプライベートウィンドウで開けるようになった
