### ISSUE TITLE
GitHub連携ログインができない

### ISSUE THREAD

**Issue by nakkaa** [syuilo/Misskey#9770]
## 💡 Summary

連携機能でログインできない。

## 🥰 Expected Behavior

連携機能でログインできる。

## 🤬 Actual Behavior

連携機能でログインできない。

## 📝 Steps to Reproduce

1. (コンパネで)連携機能のGitHubを有効にし、キーを入力して保存する。
2. アカウントの設定ページに行き、連携からGitHubと連携する。
3. ログアウトし、ログイン画面でGitHubを選ぶと、` {"statusCode":400,"error":"Bad Request","message":"invalid session"}` と表示される。

## 📌 Environment

Misskey version: 13.2.6 Docker版
Your OS: macOS 13.1
Your browser: Safari 16.2

**Comment by syuilo** [comment]
廃止されました
