### ISSUE TITLE
"Delete and edit" will put the substituted string in the reposting form when you are cat / 猫になっているときに「削除して編集」機能を使うと再投稿の画面に置換後の文字列が入る

### ISSUE THREAD

**Issue by naskya** [syuilo/Misskey#9773]
## 💡 Summary

As the Issue title states.
Issue の題名のとおりです。

## 🥰 Expected Behavior

Original (unreplaced) text will be put into the reposting form.
(`na`, `な`, `ナ`) が (`nya`, `にゃ`, `ニャ`) に置換されていない文字列が再投稿の画面に入る。

## 🤬 Actual Behavior

Replaced text will be put into the reposting form.
(`na`, `な`, `ナ`) が (`nya`, `にゃ`, `ニャ`) に置換された文字列が再投稿の画面に入る。

## 📝 Steps to Reproduce

1. Post a note. / ノートを投稿する。
2. Use "Delete and edit" feature. /「削除して編集」機能を使う。

![2023-02-03_04:27:43](https://user-images.githubusercontent.com/48414671/216433315-b9eb8c38-eb66-4865-adb4-eb21e8328d82.png)

![2023-02-03_04:28:11](https://user-images.githubusercontent.com/48414671/216433357-06ed180b-4c20-49f5-9cca-a0e37841f45a.png)

![2023-02-03_04:28:24](https://user-images.githubusercontent.com/48414671/216433371-49225c8e-0ad2-41cf-b184-2234e6b3ba10.png)

## 📌 Environment

Misskey version: 13.2.3 ([Misskey.io](https://misskey.io/))
Your OS: Arch Linux (Linux 6.1.7-arch1-1)
Your browser: Mozilla Firefox for Arch Linux 109.0.1 (64-bit)

**Comment by naskya** [comment]
I found that the same phenomenon occurs when you click "…" → "Copy contents"
「…」→「内容をコピー」でも同じこと（置換後の文字列になっている）が起きることに気づきました

**Comment by tamaina** [comment]
これ直ったんじゃない？

**Comment by zyoshoka** [comment]
https://github.com/misskey-dev/misskey/commit/30efd932a5828def2cd394e65d333fdbdb447231 で nyaize は表示時にするようになったので直っています。
