### ISSUE TITLE
syslogのサポートを削除

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9774]
## Summary

まともにメンテナンスされているライブラリが存在しないため

**Comment by mei23** [comment]
syslogを飛ばすくらいOSやコンテナの機能で出来るのではという気もするし
未ハンドル例外とかネットワークの問題とかでアプリから飛ばせないこともありそうなので
OSやコンテナ基盤の機能にまかせてアプリから飛ばす機能はいらないのではという気がしてるわね。

ただ、なぜアプリからsyslogを飛ばすことにした経緯がわからないのでそれ次第かしら。
