### ISSUE TITLE
連携ログインの削除

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#9775]
## Summary

- メンテナンスが面倒
- 分散型なのに中央集権的なものに依存するのはどうなのかという意見がたまにある
- Cookieを使う必要がなくなる

**Comment by sisiruirui-sisi** [comment]
僭越ながらご意見を
・discord連携はあっていいと思う
・でもメンテが大変なので無くて良い
・問題が起きた時(API有料など)対応が大変になるので連携ログインは無くて良いと思います

**Comment by ghost** [comment]
使ってる人いるのかな...（僕は使っていない＆使っている人を見たことがない）
導入してる鯖も少ないし、利用者も少なさそうだし、必要性を感じないので消していいと思う。

**Comment by nexryai** [comment]
自分のサーバーでも特に使ってないし消していいと思います（ログイン関係なので脆弱性にも繋がるかもだし）

**Comment by tamaina** [comment]
個人的には、Cookieを使うなどMisskeyにとっては特殊な処理があるため廃止賛成

(GitHubやDiscordのアカウントをちゃんとした形でプロフィールに表示したい欲求はなくはないけど、本当にメンテが面倒)

**Comment by ghost** [comment]
メンテコストを考えると消していいのでは...

**Comment by nenohi** [comment]
連携ログインは消してもいいと思うけど
連携自体はあってもいいと個人的には思うかな
DiscordとかTwitchとかはユーザー本人かどうかの証明とかになりやすいと思うので

**Comment by YuzuRyo61** [comment]
最近のMisskeyだとログインだけで、プロフィールにも掲載されないので、個人的にはあまり使っていません。

あとは連携アカウントでログインできれば、Misskeyの2段階認証をバイパスできてしまうので、万が一連携しているアカウントが乗っ取られた場合は、最悪の事態を招く場合もあります。

**Comment by lynlynlynx** [comment]
パスワード忘れの保険的に使ってもらうために導入してるけど、メルアドでパスワード回復出来るし実際の所無くても困らなさそう。Twitterログインは来週で廃止しますって使ってる数人に声掛けたけど全員特に困らないとのことだった。
メンテが面倒なら消してもよさそう。

**Comment by syuilo** [comment]
消すことにする
