### ISSUE TITLE
v13.3.0 breaks on latest firefox

### ISSUE THREAD

**Issue by HolgerHuo** [syuilo/Misskey#9784]
## 💡 Summary

When opening misskey in latest firefox without login, the page breaks with the following error:

![screenshot of the error](https://i.ibb.co/vVkjJkN/image.png)

## 🥰 Expected Behavior

Misskey frontend opens without error

## 🤬 Actual Behavior

Misskey frontend throws error

## 📝 Steps to Reproduce

1. Update misskey to v13.3.0
2. Open Misskey in Firefox

## 📌 Environment

Misskey version: v13.3.0
Your OS: Windows 10 x64
Your browser: Firefox 109.0.1

**Comment by HolgerHuo** [comment]
I have to correct a mistake. The problem occurs only in Private Browsing mode.

It seems to be related to IndexedDB usage.

![console log](https://i.ibb.co/G72qr3r/image.png)

**Comment by acid-chicken** [comment]
Duplicate of #9769
