### ISSUE TITLE
グループを作る機能もしくは権限の付与がない？

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9785]
## 💡 Summary
グループを作りたいが管理者でも作れないっぽい（UIがない）

## 🥰 Expected Behavior
グループが作れる

## 🤬 Actual Behavior
グループを作る導線がもっと！の中にない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:13.2.6
Your OS: Mac
Your browser: Chrome

**Comment by CyberRex0** [comment]
グループは廃止予定

**Comment by syuilo** [comment]
まだ決まってない

**Comment by tamaina** [comment]
グループ廃止
