### ISSUE TITLE
Media player fails to load remote media due to CORS

### ISSUE THREAD

**Issue by zotanmew** [syuilo/Misskey#9786]
## 💡 Summary

Media player fails to load remote media due to CORS policy

## 🥰 Expected Behavior

The old browser-default player appears to have mostly ignored CORS and played everything fine

## 🤬 Actual Behavior

Player is stuck on loading, console says `has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

## 📝 Steps to Reproduce

1. View post from remote instance containing a video attachment
2. Try to play it

## 📌 Environment

Misskey version: 13.3.0
Your OS: ArchLinux latest
Your browser: Chrome latest stable

**Comment by RoxyBoxxy** [comment]
in ur nginx configuration add 

```
add_header 'Access-Control-Allow-Origin' '*' always;
```

to your location under proxy_pass i put mine under `proxy_redirect off;`

**Comment by zotanmew** [comment]
Heya, that sadly does not solve the problem as this would need to be added to the configuration of every remote instance :/

**Comment by RoxyBoxxy** [comment]
huh i didnt have any problem playing content from any other instance, could you send me your profile on ur instance and i can try it out on my own

**Comment by RoxyBoxxy** [comment]
I just did a test from a mastodon instance to my misskey instance and seems to work fine over here 
![image](https://user-images.githubusercontent.com/8870878/216707732-cb8d625f-7f72-4de5-b822-1cea13bf088b.png)

**Comment by zotanmew** [comment]
Broken post example: https://botsin.space/@hackers_gifs/109802917994699880
Working post example: https://glitterkitten.co.uk/@doot/109802986994518206

**Comment by zotanmew** [comment]
The working instance sends a cors header, the broken one doesn't. Most appear to not do this by default.

**Comment by zotanmew** [comment]
Oh, also: I have remote media caching disabled. I presume this bug does not occur when remote media caching is enabled, because all requests would go to the local server.

**Comment by RoxyBoxxy** [comment]
> Oh, also: I have remote media caching disabled. I presume this bug does not occur when remote media caching is enabled, because all requests would go to the local server.

yer i think i run remote media caching as i also use a cdn service for all files, also i saw that you was loading gifs? as the links you sent only contain gifs

**Comment by zotanmew** [comment]
Huh. Yeah, looks like it. Pre v13.3 this worked fine as it just used the browser internal player which apparently doesn't check CORS?

**Comment by RoxyBoxxy** [comment]
> Huh. Yeah, looks like it. Pre v13.3 this worked fine as it just used the browser internal player which apparently doesn't check CORS?

i shall have a look, i just followed the non working on my dev intance to have a look

**Comment by RoxyBoxxy** [comment]
Fixed in PR #9790

**Comment by zotanmew** [comment]
Thanks a lot!

**Comment by zotanmew** [comment]
Cherry-picked the commits from the PR, confirmed working. Should I leave this open til the PR is merged?

**Comment by RoxyBoxxy** [comment]
> Cherry-picked the commits from the PR, confirmed working. Should I leave this open til the PR is merged?

leave it open till it gets pushed as if anybody else is having this issue it would be up there for them

**Comment by zotanmew** [comment]
Fixed in 13.3.1
