### ISSUE TITLE
Misskey is not opening properly in 13.3.1

### ISSUE THREAD

**Issue by makachanm** [syuilo/Misskey#9791]
## 💡 Summary
Misskey is not opening properly in 13.3.1.
It cannot load Main UI of Misskey and just falling into Error Screen.

## 🤬 Actual Behavior
![image](https://user-images.githubusercontent.com/55223245/216750187-3c18b40c-bfc8-4f31-978f-e6f3c122b1c7.png)
It cannot load Main UI of Misskey and just falling into Error Screen.
After doing clear(/flush), it keeps throwing error in while loading.

It also throwing Syntax Error into JavaScript Console.
![image](https://user-images.githubusercontent.com/55223245/216750336-f21be3e8-88cc-40c0-9dd2-404b27c8b4de.png)

## 📝 Steps to Reproduce

1. Load a Misskey Page.
2.
3.

## 📌 Environment

Misskey version: Misskey 13.3.1
Your OS: Microsoft Windows 11 Home 25290.1000
Your browser: Firefox Nightly 111.0a1

**Comment by fu-sen** [comment]
I'm running into this issue on a few instances updated to 13.3.0 or later on Japanese instances.
日本語のインスタンスで 13.3.0 以降に更新されたいくつかのインスタンスでこの問題が発生しています。

- https://mattyaski.co/
- https://mi-wo.site/
- https://mi.syobon.net/
- https://sudo.mkdir.uk/ 

It's a pretty serious problem because it's currently impossible to recover from this state.
現在、この状態から回復することは不可能であるため、かなり深刻な問題です。

幸い自分が 13.3.0 で気がついて io ノートしていたので、いくつかのサーバ管理者は更新を控えました。
https://misskey.io/notes/9as3q1yy94
また、io は13.3.0リリース後に更新していますが、13.2.6 だったので正常に稼働し続けています。これは幸いでした。

**Comment by syuilo** [comment]
> I'm running into this issue on a few instances updated to 13.3.0 or later on Japanese instances. 日本語のインスタンスで 13.3.0 以降に更新されたいくつかのインスタンスでこの問題が発生しています。
> 
> * https://mattyaski.co/
> * https://mi-wo.site/
> * https://mi.syobon.net/
> * https://sudo.mkdir.uk/
> 
> It's a pretty serious problem because it's currently impossible to recover from this state. 現在、この状態から回復することは不可能であるため、かなり深刻な問題です。
> 
> 幸い自分が 13.3.0 で気がついて io ノートしていたので、いくつかのサーバ管理者は更新を控えました。 https://misskey.io/notes/9as3q1yy94 また、io は13.3.0リリース後に更新していますが、13.2.6 だったので正常に稼働し続けています。これは幸いでした。

ブラウザは分かりますか？

**Comment by fu-sen** [comment]
> ブラウザは分かりますか？

Chromim 系確認しましたが、全滅です。OS 問わず。

https://mattyaski.co/ だけキャッシュ方法が特殊なようで、一時的に見える環境もある事を確認しています。

**Comment by syuilo** [comment]
うーむ手元では再現しないから謎

**Comment by L-y-a** [comment]
Linux の Firefox110 のスクリーンショットです

![image](https://user-images.githubusercontent.com/114819113/216758341-c61bae61-62bf-4b32-a216-55f6cb94a2c2.png)

**Comment by syobocat** [comment]
> 現在、この状態から回復することは不可能であるため、かなり深刻な問題です。

Cloudflareのキャッシュをパージすると一時的に回復するっぽいです

**Comment by mattyatea** [comment]
mattyaskiのcacheが特殊ってことはないかも
cloudflareでキャッシュさせてるだけなので

ブラウザのサイトデータを消してcloudflareのcacheをpurgeしたら正常に見れた

**Comment by fruitriin** [comment]
鯖缶からエラーログ貰って来た方がはやいかも

**Comment by mattyatea** [comment]
https://mattyaski.co にアクセスだれかしてみてほしいです
エラーが出る方で

**Comment by syuilo** [comment]
構文エラーってことはブラウザが古い可能性がある？
ただ

> Firefox Nightly 111.0a1

での報告があるから謎

**Comment by nexryai** [comment]
mattyaski.coとsudo.mkdir.ukにアクセスしたところAndroid12上のBromite（Chromium）で再現しました。  
Fedora上のFirefox109では正常にアクセスできます。

**Comment by 7ka-Hiira** [comment]
> https://mattyaski.co にアクセスだれかしてみてほしいです エラーが出る方で

同じブラウザでキャッシュありタブはログイン成功、プライベートタブでエラーになりました

**Comment by nexryai** [comment]
> mattyaski.coとsudo.mkdir.ukにアクセスしたところAndroid12上のBromite（Chromium）で再現しました。 Fedora上のFirefox109では正常にアクセスできます。

訂正: Cookieとサイトデータを消したらどちらの環境でもアクセスできません...  <br>
![Screenshot from 2023-02-04 17-58-31](https://user-images.githubusercontent.com/61890205/216758563-24fb6da3-2142-4929-8aeb-5d80bf241e58.png)

**Comment by syuilo** [comment]
https://mattyaski.co/ にアクセスしたら再現した

**Comment by syuilo** [comment]
productionモードでビルドすることが条件だったりしそう

**Comment by mattyatea** [comment]
んーずっとサーバーでログ取ってるけど該当するエラーはなさそうかも

**Comment by nexryai** [comment]
![Screenshot from 2023-02-04 18-01-26](https://user-images.githubusercontent.com/61890205/216758681-ef61e5fd-d79c-47cb-9e81-de7adecdca23.png)
<br>
`/flush`にも失敗するみたい

**Comment by syuilo** [comment]
具体的にどこで Invalid or unexpected token になってるか分からないから難しい

**Comment by sim1222** [comment]
CloudflareのSpeed→最適化→Auto MinifyのJSのチェックを外してからキャッシュをパージすると直りました。
v13からCloudflareのAuto Minifyとの相性が悪いようでCSSにもエラーが発生することがあるのでAuto Minifyは全て無効にするのがいいかもしれません。

**Comment by CyberRex0** [comment]
> /flushにも失敗するみたい

sw.jsもAuto Minifyの影響で壊れてしまっているので

**Comment by Zel9278** [comment]
![chrome_nlqXWcTHWe](https://user-images.githubusercontent.com/43949163/216758743-bc787fbb-2cbb-46ea-a76c-9c96df1c70f6.png)
{}の中身が無いのがわからなすぎる。。。

**Comment by 7ka-Hiira** [comment]
キャッシュのパージで直りませんでした...
追記：しばらくしたら直りました

**Comment by sim1222** [comment]
Auto MinifyによってJSファイル自体が破壊されているのでブラウザは関係ないようです（Safari Chromeで確認）

**Comment by mattyatea** [comment]
mattyaskiもsim1222氏が言ってるようにしてみたかも

**Comment by syobocat** [comment]
> CloudflareのSpeed→最適化→Auto MinifyのJSのチェックを外してからキャッシュをパージすると直りました。

たしかにこれでなおったかも

**Comment by syuilo** [comment]
> CloudflareのSpeed→最適化→Auto MinifyのJSのチェックを外してからキャッシュをパージすると直りました。

あー昔からこういうことあったわ

**Comment by syuilo** [comment]
Cloudflare、最新のJavaScriptを解釈してくれず、MisskeyのJSを破壊してくる

**Comment by syuilo** [comment]
そもそもMisskeyのコードは既にminifyされているから、さらにCloudflareにminifyされるのは無駄でしかないのでオフにしてください

**Comment by fu-sen** [comment]
Cloudflare's Auto Minify is breaking Misskey's js code. Please disable this.

Then **Shift+Reload**  or run **Clear Cache** your web browser.

You should now be able to see it normally.

**Comment by fu-sen** [comment]
> * https://mattyaski.co/
> * https://mi-wo.site/
> * https://mi.syobon.net/
> * https://sudo.mkdir.uk/

すべて回復を確認できました。

**この問題に遭遇したサーバ管理者へ** Cloudflare の Auto MInify を無効にした後、ブラウザを Shift+再読み込み または キャッシュをクリア して JS を強制的に再読み込みして下さい。それで表示できるようになります。（問い合わせがあった場合も同様に）

**Comment by Injabie3** [comment]
Landed here after reading the docs. I ran into a similar issue with Cloudflare while setting up Misskey 13.11.3. In my case, the workaround was to create a Configuration Rule on Cloudflare:
1. Go to `Rules` > `Configuration Rules (Beta)`
2. Create a rule for the Misskey domain.
3. Add `Disable Apps` to the rule.
4. Add `Rocket Loader` to the rule, and **disable** it.
5. Deploy.

**Comment by ThatOneCalculator** [comment]
It seems that adding the HTTP header `Cache-Control: no-transform` stops Cloudflare from auto-minifying.

**Comment by veronoicc** [comment]
The note about Auto Minify can be removed after 2024-08-05, as Cloudflare is remove the (now deprecated) feature then (as per https://developers.cloudflare.com/speed/optimization/content/auto-minify/)
