### ISSUE TITLE
SyntaxError: No identifiers allowed directly after numeric literalが出て利用できない

### ISSUE THREAD

**Issue by sizumita** [syuilo/Misskey#9793]
## 💡 Summary

misskeyのサーバーを立てようとして、最新バージョンのmisskeyをcloneしてdocker compose経由で立てようとした. 管理者アカウントを作成したところSyntaxError: No identifiers allowed directly after numeric literalが表示されて動かない.

## 🥰 Expected Behavior

misskeyを正常に利用できる.

## 🤬 Actual Behavior

このような画面が表示され動かない。

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/17804838/216762127-4a677aa5-a427-452d-8537-140a981ff7d5.png">

## 📝 Steps to Reproduce

1. https://misskey-hub.net/docs/install/docker.html をもとにmisskeyのインスタンスを立てる。
2. nginx(Cloudflare Origin CA)を用いてプロキシをする、またCloudflare を経由させる。
3. 最初の画面で管理アカウントを作りログインする。

## 📌 Environment

Misskey version: 13.3.3
Server OS: aarch64 Oracle Linux 5.4.17-2136.301.1.4.el7uek.aarch64 (OCIのARMインスタンスを利用しています。)

Your OS: macOS Monterey 12.5
Your browser: safari バージョン15.6 (17613.3.9.1.5)
iOS15.3のsafariでも起こりました。

**Comment by syuilo** [comment]
see https://github.com/misskey-dev/misskey/issues/9791#issuecomment-1416704170

**Comment by sizumita** [comment]
Thanks, I'll check it out.
