### ISSUE TITLE
ユーザープロフィールのタグ検索ができない

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9813]
## 💡 Summary

ユーザープロフィールの文中にあるハッシュタグをクリックしても、ハイライトが表示される。

## 🥰 Expected Behavior

同じタグを付けているユーザーの検索画面が出てくる。

## 🤬 Actual Behavior

ハイライトが表示される

## 📝 Steps to Reproduce

プロフィールについているタグをクリック

## Memo
`/explore/tags/...` が `/explore` と同じページにルーティングされている。<br>
しかしユーザータグの検索機能は実装されていない

## 📌 Environment

Misskey version: 13.3.4
Your OS: macOS Monterey
Your browser: Chrome 109.0.5414.119 (Official Build) （arm64）

**Comment by syuilo** [comment]
fixed
