### ISSUE TITLE
misskeyのアイコン画面のぐるぐるが止まらない

### ISSUE THREAD

**Issue by CharlieMalphas** [syuilo/Misskey#9815]
## 💡 Summary

misskeyのアイコンを作るために画像をmisskeyに送信した後、クロップしてどの部分をアイコンにするかの調節までは行けたが、調節後にチェックマークをクリックしたが、ぐるぐるが止まらない

## 🥰 Expected Behavior

画像サイズに問題はなくそのままクロップ画面へと移動する。

## 🤬 Actual Behavior

クロップした後にチェックマークをクリックするとそのままロード地獄へと陥る。

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version: v13.3.4
Your OS: Windows 11
Your browser: Google Chrome

**Comment by syuilo** [comment]
`DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

**Comment by Kami-0x10** [comment]
横やり失礼します。
ウェブ上でうpするのではなく、subway tooterなどのアプリでうpするとあげられるので、できない方はバグがなおるまで検討よろしくです。

**Comment by CyberRex0** [comment]
@Chamin-programmer misskey.io での話ですかね？このバグは修正されたようですが、まだmisskey.ioではアップデートしてないみたいです。

**Comment by Kami-0x10** [comment]
> @Chamin-programmer misskey.io での話ですかね？このバグは修正されたようですが、まだmisskey.ioではアップデートしてないみたいです。

まじすか。　失礼しました。

**Comment by tamaina** [comment]
CORS周りだろうけどなんかよくわからない

**Comment by tamaina** [comment]
穴が開くことになるけど、特定の場合だけ本体で処理するしかない

**Comment by tamaina** [comment]
https://github.com/misskey-dev/media-proxy/issues/5
