### ISSUE TITLE
ActivityPub deliverなどのUser-Agentがnode-fetchになっている

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#9817]
## 💡 Summary
ActivityPub deliverなどのUser-Agentが`node-fetch`になっている

## 🥰 Expected Behavior
`Misskey/~` になるはず

## 🤬 Actual Behavior
`node-fetch`になっている

## 📝 Steps to Reproduce

1. AP deliverが発生することをする
2. リモートのログをみる

## 📌 Environment
Misskey version: 13.3.4
Your OS:
Your browser:

**Comment by tamaina** [comment]
今これ知ったけど徐々に問題になってきているらしい
