### ISSUE TITLE
動くカスタム絵文字を標準で静止画にする #光過敏性防止関連｜Disable gifs/apngs by Default

### ISSUE THREAD

**Issue by KawaneRio** [syuilo/Misskey#9821]
## <ruby>概要<rp>《</rp><rt>がいよー</rt><rp>》</rp></ruby>

.gif や .apng などといった、アニメーションがあるカスタム<ruby>絵文字<rp>《</rp><rt>えもじ</rt><rp>》</rp></ruby>を<ruby>標準<rp>《</rp><rt>デフォルト</rt><rp>》</rp></ruby>で1frame<ruby>目<rp>《</rp><rt>め</rt><rp>》</rp></ruby>の<ruby>静止画<rp>《</rp><rt>せいしが</rt><rp>》</rp></ruby>にする。

### なぜ
<ruby>新規<rp>《</rp><rt>しんき</rt><rp>》</rp></ruby>さん（<ruby>特<rp>《</rp><rt>とく</rt><rp>》</rp></ruby>に<ruby>児童<rp>《</rp><rt>じどー</rt><rp>》</rp></ruby>など）に[<ruby>光過敏性<rp>《</rp><rt>ひかりにびんかん</rt><rp>》</rp></ruby>](https://ja.wikipedia.org/wiki/%E5%85%89%E9%81%8E%E6%95%8F%E6%80%A7%E7%99%BA%E4%BD%9C)の<ruby>方<rp>《</rp><rt>かた</rt><rp>》</rp></ruby>が<ruby>居<rp>《</rp><rt>ゐ</rt><rp>》</rp></ruby>る<ruby>場合<rp>《</rp><rt>ばあい</rt><rp>》</rp></ruby>を<ruby>考慮<rp>《</rp><rt>こうりょ</rt><rp>》</rp></ruby>し、アニメーションを<ruby>伴<rp>《</rp><rt>ともな</rt><rp>》</rp></ruby>うカスタム<ruby>絵文字<rp>《</rp><rt>えもじ</rt><rp>》</rp></ruby>は<ruby>設定<rp>《</rp><rt>せってい</rt><rp>》</rp></ruby>でONにしないと<ruby>動<rp>《</rp><rt>うご</rt><rp>》</rp></ruby>かないようにした<ruby>方<rp>《</rp><rt>ほう</rt><rp>》</rp></ruby>がより<ruby>安全<rp>《</rp><rt>あんぜん</rt><rp>》</rp></ruby>なミスキーライフをおくれる<ruby>気<rp>《</rp><rt>ふぃーりんぐ</rt><rp>》</rp></ruby>がしますっ！

<details><summary>一例⚠ポリゴンショック注意⚠</summary><div>

https://co.misskey.io/notes/9avwfne2fv

![Peek 2023-02-06 14-47](https://user-images.githubusercontent.com/61252570/216893542-8b375207-5a5a-470b-ae8a-4d68f704c376.gif)

</div></details>

## Summary
Disable gifs and apngs (animated pngs) by default. 

### Why
Because some animated custom emojis can [cause seizures/epilepsies to those who are hypersensitive to flashing lights](https://en.wikipedia.org/wiki/Photosensitive_epilepsy).

<details><summary>⚠SEIZURE WARNING⚠</summary><div>

https://co.misskey.io/notes/9avwfne2fv

![Peek 2023-02-06 14-47](https://user-images.githubusercontent.com/61252570/216893542-8b375207-5a5a-470b-ae8a-4d68f704c376.gif)

</div></details>

**Comment by KawaneRio** [comment]
`設定 > クライアント設定 > アピアランス > 動きのあるMFMを無効にする ` にカスタム絵文字のアニメーションの有無もまとめたほうが良い気がします。

**Comment by EbiseLutica** [comment]
悪用されるからという理由で、表現力を損なうように仕様を変えちゃまずいかも。それは各サーバーの規約に任せるべき領分だと思います

**Comment by nexryai** [comment]
デフォルト無効は影響が大きすぎる気がするのでチュートリアルに光過敏性とかの人向けにアクセシビリティ設定を紹介するとかがいいと思う

**Comment by KawaneRio** [comment]
> デフォルト無効は影響が大きすぎる気がするのでチュートリアルに光過敏性とかの人向けにアクセシビリティ設定を紹介するとかがいいと思う

どのみちGIF/APNGを静止画にする機能は設定に欲しいかも。

**Comment by EbiseLutica** [comment]
「アニメーション画像を表示しない」は絵文字に及ばないんだっけ。これ系のissueがすでにあったような気がする

**Comment by L1n4r1A** [comment]
「アニメーション画像を表示しない」は絵文字にも反映されますね

**Comment by KawaneRio** [comment]
> 「アニメーション画像を表示しない」は絵文字にも反映されますね

 我の環境（`Misskey v13.1.8`, Firefox v109.0.1, Kubuntu）だと反映されないんだが・・・
 <details><summary>Screenshots/gif</summary><div>

![image](https://user-images.githubusercontent.com/61252570/216904949-b2168339-9182-4348-8a7a-d8308359c547.png)
![image](https://user-images.githubusercontent.com/61252570/216905056-a80fe7b9-7e66-4c7a-bbf2-5ae52e570a24.png)
![Peek 2023-02-06 16-04](https://user-images.githubusercontent.com/61252570/216905715-652a2540-95ef-4eba-8480-a181705e2f02.gif)

</div></details>

**Comment by L1n4r1A** [comment]
v13.3.4(v13.hisubway.me)で確認してみましたが止まりますね……
環境はWin10 Chrome(109.0.5414.120)です。

**Comment by KawaneRio** [comment]
こちら Misskey.io (Misskey v13.3.4) でも見てみましたが、やはりカスタム絵文字は止まらなかったので、もしすでに実装されてたらもうしわけありませんが、環境問題の可能性が高いです。。。


<details><summary>ポリゴンショック注意⚠️</summary><div>

![Peek 2023-02-06 17-16](https://user-images.githubusercontent.com/61252570/216922642-b028f5c9-abb3-42a3-9ead-854e84ef6f57.gif)


</div></details>

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/commit/d78e15cc1a4166d6f08ab4914a6d9ec61d8a33da

これで直したはずだし13.3.1以降のリリースで修正されているはずなんだけどなぜかmisskey.ioでは直っていない

**Comment by tamaina** [comment]
misskey.ioはMediaProxyを早速導入しているみたいだけど、nos3.arkjp.netはstaticオプションに対応してないっぽい？

**Comment by tamaina** [comment]
初期設定はprefers-reduced-motionをフォローするようにすれば良さそう

**Comment by KawaneRio** [comment]
> misskey.ioはMediaProxyを早速導入しているみたいだけど、nos3.arkjp.netはstaticオプションに対応してないっぽい？

もしかしてインスタンス問題っぽい？このissueの名前を【チュートリアルに光過敏性とかの人向けにアクセシビリティ設定を紹介する】に変更していい感じ？

**Comment by tamaina** [comment]
> チュートリアルに光過敏性とかの人向けにアクセシビリティ設定を紹介する

Misskeyでどうこうできる問題ではないので…

**Comment by KawaneRio** [comment]
チュートリアルってMisskey側の設定じゃないんだ・・・ありがとうございます。

**Comment by tamaina** [comment]
チュートリアルはMisskeyの範疇内だけど、OS設定でどうにかしてほしいという意味で  
（光過敏性等の診断を受けている人はOSの設定はいじってあるだろうし）

**Comment by nullkal** [comment]
もうクローズされたIssueだけど念のため。
光過敏性発作を起こす人で前もって診断されてる人は稀だと思います。
(発症する人は突然発症するので……)

ポリゴンショックも、前もって診断される病気だったらここまで大事にはなってないはずです。
表現を損なうのは悲しいことだし、ソフトウェア的に出来ることはそこまでなさそうだけど、サーバー運営者側である程度配慮しないといけない事項であることは把握しておいて欲しいです。

**Comment by mj-hd** [comment]
WCAGだと、点滅などの動きと閃光（発作を引き起こすもの）は区別されてますね。発作が起こってからでは遅いので、停止オプションがあったとしても許容されない、という説明のされ方をしてます。

>「点滅」は、利用者の注意を散漫にさせる問題を引き起こすコンテンツを指している。点滅は、それを停止する (又は停止させることができる) 限り、短時間であれば許容することができる。
>「閃光」は、(1 秒間に 3 回よりも多く、大きさと明るさが十分な場合には) 光過敏性発作を引き起こす恐れのあるコンテンツを指している。これは、光過敏性発作を引き起こす恐れがあるため、たとえ 1 秒間だけであったとしても許容されない。光過敏性発作は利用者が止める前に引き起こす恐れがあるため、閃光を止めることも選択肢にはならない。

https://waic.jp/translations/UNDERSTANDING-WCAG20/time-limits-pause.html

ガイドラインを見ると、nullkalさんの説明の通り、実際に発作が起こるまで疾患に気づけないこと、子供は警告を見逃してしまうことなどが記載されています。

> 発作性障害のある利用者は、閃光を放つ視覚的なコンテンツによって発作を引き起こすことがある。ほとんどの利用者は、発作が起こすまでは自分がこの疾患を持っていることに気づかない。1997 年に、日本でテレビのアニメ番組が 700 人以上の子どもたちを病院に搬送させる事態を招き、そのうち約 500 人が発作を引き起こした。特に、警告を実際に読むことができない子どもの利用者に警告はよく見逃されるので、その警告はあまり効果がない。

https://waic.jp/translations/UNDERSTANDING-WCAG20/seizure.html
