### ISSUE TITLE
Reactionのwebhookがenableにしても飛んできてない

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9824]
## 💡 Summary
Reactionのwebhookが飛んできてない気がする。
再現する？

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by tamaina** [comment]
気のせいじゃない

**Comment by sim1222** [comment]
related to  #9485 ?

**Comment by tamaina** [comment]
Duplicate of #9485
