### ISSUE TITLE
miauthのコールバックURLにhttp,https 以外のスキーマを指定するとコールバックしない

### ISSUE THREAD

**Issue by tateisu** [syuilo/Misskey#9825]
## 💡 Summary

miauthはコールバックURLにhttp,https 以外のスキーマを指定するとコールバックしない。

[#SubwayTooter](https://mastodon.juggler.jp/tags/SubwayTooter) で [#Misskey](https://mastodon.juggler.jp/tags/Misskey) 13 にログインできなくなった件です。

## 🥰 Expected Behavior

過去の認証方法と同様、カスタムURLスキーマに対応する。

## 🤬 Actual Behavior

`Error: invalid url at v (miauth-a004a6ac.js:1:1099)`  って出てる。
`if(!["http:","https:"].includes(i.protocol))throw new Error("invalid url");` だそうです。

## 📝 Steps to Reproduce

2. Android端末のUSBデバッグをONにしてPCにつなぐ
1. Subway Tooter (開発版かもしれない)でmisskey.io にログインを試みる。しかしmiauth画面でアプリにコールバックしない。
3. PC版Chromeで chrome://inspect/#devices を開いてmiauthの認証画面を見る
4. コンソールを見るとエラーが出ている。`Error: invalid url at v (miauth-a004a6ac.js:1:1099)`

**Comment by tateisu** [comment]
アプリ側の実装当時は動作確認とおってたのになんで。。と思って見てみたら、２日前のこのコミットらしい
https://github.com/misskey-dev/misskey/commit/788ae2f6ca37d297e912bfba02821543e8566522

**Comment by pantasystem** [comment]
アプリ認証の方はまだ変更されていないようですが、
Androidだと任意のhttps, httpのURLでアプリを起動することが困難になったので
コールバック先のスキーマをhttp, https以外も許容できるようにしないと同じく厳しいです。

https://developer.android.com/training/app-links/verify-android-applinks?hl=ja

**Comment by syuilo** [comment]
https以外が使えると脆弱性になってしまうので制限するようにしています。

**Comment by tateisu** [comment]
禁止したいプロトコルを明示して制限する方式にするべきだと思います。

個人的には「HTTPSなら脆弱性ではない」という判定基準がよくわかりませんし、
そもそもこのURLが使われるのはユーザが明示的に同意した後なのではないでしょうか。

**Comment by tateisu** [comment]
現状のmiauthでHTTPSだけを使ってユーザ認証を行うことは、アプリがWebViewを使えば可能です。

しかしそれはクッキーなどの認証情報を（ユーザが普段使っている）外部ブラウザではなく、アプリ側のストレージに持つことになります。

認証情報が複数の場所に分散するほうがより脆弱なので、なるべく外部ブラウザ経由での認証にしたいという思いです。

サービス側の意思でソレがダメなのであればWebViewを組み込むだけですが。

**Comment by syuilo** [comment]
例えばjavacriptスキーマを使うことで任意のJSを実行させることができます。
他にもこのような危険性のあるスキーマが無いとは自信を持てなかったのと、今後追加されることも否定はできないと思ったのでhttp/httpsのみにしています。
http/httpsなら脆弱性になる危険性はありません。

**Comment by tateisu** [comment]
https://www.techscore.com/blog/2015/04/25/scheme-security/
このあたりの話でしょうか。 少なくとも javascript と data を禁止するべきだというのはわかりました。ありがとうございます。

未知のスキーマを全て禁止する方向については、上に書いたWebViewによるログイン情報の分散の危険の方が大きいと思います。

**Comment by acid-chicken** [comment]
危険性というと、どちらかというとカスタムスキームによるトークンの横取りができるという点かなぁと
fyi: https://akaki.io/2021/authz_code_interception

**Comment by tateisu** [comment]
> 危険性というと、どちらかというとカスタムスキームによるトークンの横取りができるという点かなぁと fyi: https://akaki.io/2021/authz_code_interception

ページ中の再現動画を見ましたけど、カスタムURLスキーマが同一のアプリが複数あるときに「どちらで開くか選ぶ画面」が出てこないのがやや不自然に感じました。iOSってそうなんですか？

「どちらで開くか選ぶ画面」の例です。
https://m1j.zzz.ac/media_attachments/files/109/828/906/830/339/219/original/b1fb8425c3418b2c.png

また、コールバックURLに含まれる情報で何ができるのかというと
misskeyの過去の認証ではコールバックURL中のトークン(漏れるかもしれない) とappSecret(第三者に漏れてない)の両方を使ってアクセストークンを得るので、コールバックのトークンだけ漏れてもあまり被害が大きくなりません。
一方でmiauth はコールバックURLに含まれる sessionId だけで認証結果を取得できます。

**Comment by acid-chicken** [comment]
> misskeyの過去の認証ではコールバックURL中のトークン(漏れるかもしれない) とappSecret(第三者に漏れてない)の両方を使ってアクセストークンを得るので、コールバックのトークンだけ漏れてもあまり被害が大きくなりません。
> 一方でmiauth はコールバックURLに含まれる sessionId だけで認証結果を取得できます。

はい、なので miauth は（自前で PKCE を組まない限り）ネイティブアプリの認証に向かない気がします (related to #9779?)

**Comment by tateisu** [comment]
http,https ならホスト名解決をある程度信用できるのでmiauthの方式でも問題はないないですね。
カスタムURLスキーマだとスキーマ部分もauthority部分、あとアプリの見た目を真似られたらsessionIdを盗まれる恐れがある。

…とはいえmiauthって元々簡単な認証方法なので、わざわざ他アプリのコールバックを奪うより偽アプリ側で実装しろよという感想です。

**Comment by tateisu** [comment]
SubwayTooter 的にはこのissueを投げた時点でmiauth使用は控える方向です。
今後はしばらく旧認証方式を使い続けて、miauthではなくOAuthが使えるようになったら切り替えるのがよさそう。

**Comment by syuilo** [comment]
ブラックリスト形式にしました
