### ISSUE TITLE
ノートのデフォルトの公開範囲が違う複数のアカウントを並行して運用する際、ノートのデフォルトの公開範囲が適切なものにならないことがある

### ISSUE THREAD

**Issue by miketako3** [syuilo/Misskey#9828]
## 💡 Summary

ノートのデフォルトの公開範囲が違う複数のアカウントを並行して運用する際、ノートのデフォルトの公開範囲が適切なものにならないことがあります。

例えば、このバグが再現している時、デフォルトの公開範囲がフォロワーのアカウントに切り替えた後、ノート投稿ボタンを押下すると、公開範囲がパブリックになっていることがあります。

## 🥰 Expected Behavior

アカウントを切り替えた後にノート投稿ボタンを押下した場合、切り替え後のアカウントのデフォルトの公開範囲がセットされている。

## 🤬 Actual Behavior

アカウントを切り替えた後にノート投稿ボタンを押下した場合、切り替え後のアカウントのデフォルトの公開範囲とは違う公開範囲がセットされていることがある。

## 📝 Steps to Reproduce

1. デフォルトの公開範囲が違う2つのアカウントを用意し、どちらもログインしておく
2. アカウントを切り替えたり、ノート投稿画面で公開範囲を選び直したりする
3. 2を何度も繰り返す
4. 再現する

(2の部分に曖昧性はありますが) この手順を何度やっても確実に再現します。一方で、何がどうバグっているのかは特定できていません。

一見下書き状態で引き継がれているのかと思いましたが、アカウントを切り替えて戻してという動作を行うと公開範囲が変わっていることもあるため、おそらく別の原因かと思われます。

## 📌 Environment

Misskey version: 13.3.4
Your OS: iOS 16.2
Your browser: Safari 604.1

**Comment by KisaragiEffective** [comment]
triage: (おそらく #9916 により) 2024.5.0ではアカウントを切り替えた後に投稿しても、切り替え前の公開範囲ではなく、切り替え語彙のアカウントの公開範囲がセットされるようになりました。
