### ISSUE TITLE
safari で AiScript プラグインが1つしか実際に有効にならない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/Misskey#9829]
## 💡 Summary

プラグイン管理画面で複数のプラグインを有効にしているにも関わらず、1つのプラグインしか有効にならない
（例えば、plugin:register_note_action に対応したプラグインを複数インストールしても、ノートメニューには1つしか表示されない）

## 🥰 Expected Behavior

有効な全てのプラグインが実行

## 🤬 Actual Behavior
有効なプラグインのうち1つしか実際に有効にならない

## 📝 Steps to Reproduce

1. plugin:register_note_action に対応したプラグインを複数インストール
2. ノートメニューを確認
3.

## 📌 Environment

Misskey version: 13.3.4 (13.2.6以前は正しく動作することを確認)
Your OS: iPadOS 16.2
Your browser: safari

**Comment by futchitwo** [comment]
Microsoft Edge バージョン 109.0.1518.78 では複数表示されたのでsafariのバグ説
ただ、複数のインスタンスでためしたのでインスタンス固有のバグではないはずです

**Comment by futchitwo** [comment]
調査の過程でplugin:register_note_actionの有無に関わらずプラグイン1つしか使えないことが判明
https://github.com/misskey-dev/misskey/blob/3c01c0cbf2d13cf0c1ee146ab6f2a232122e29a9/packages/frontend/src/plugin.ts#L84-L86
でpluginContextsに当たると1つしか実行できなくなる
```js
function initPlugin({ plugin, aiscript }) {
 	alert("honi") //複数回実行される
	alert(pluginContexts) //1回しか実行されない
 	pluginContexts.set(plugin.id, aiscript); 
 }
```
ただ、当該ソースは13.2.6〜13.3.4間で何も変更が加わっていないので謎は深まるばかり

**Comment by slofp** [comment]
今回プラグインを公開した際に同様の問題に出くわしたので、修正したいと思います。

**Comment by slofp** [comment]
@futchitwo すいません... 解決しましたがPRに`Closes`をつけるのを忘れてしまったのでcloseしてもらえますか？

**Comment by futchitwo** [comment]
Closeしました！修正ありがとうございます！
