### ISSUE TITLE
v12 LTS

### ISSUE THREAD

**Issue by massongit** [syuilo/Misskey#9835]
## Summary

インスタンス運営者からv13は安定性に難があるという声を聞く機会があり、実際、インスタンスの安定稼働のために前バージョンであるv12のLTS版を作ろうという動きも散見されています。

* https://github.com/mei23/misskey-v12
* https://github.com/atsu1125/misskey-v12
* https://atsuchan.page/@atsuchan/109828843650655518

従って、公式でv12 LTSを用意した方が良いのではないかと考えられます。

**Comment by acid-chicken** [comment]
これは能動的な意味（misskey-dev は今後も当面の間 v12 を主体的にメンテナンスすべきである）なのか受動的な意味（misskey-dev は v12 のメンテナンスを行う場を提供し、リリース等を集約すべきである）なのかどちらが近いですか？

**Comment by massongit** [comment]
>能動的な意味（misskey-dev は今後も当面の間 v12 を主体的にメンテナンスすべきである）

こちらですね。
v13の差分のうち、脆弱性対応などバックポートすべきものをv12にバックポートする流れになると思いますが、その判断を最新版の開発メンバー以外の人が行うというのは一般的でないと感じます。

**Comment by massongit** [comment]
すなわち、本来公式が行うべきものを有志が行っている現状は是正されるべきではないか、という立場です。

**Comment by acid-chicken** [comment]
OSS なので fork は自由に行われるべきだし是正というとちょっと違うとは思いますが、人的リソースの面から misskey-dev が今後もメンテナンスを続けるのはあまり現実的ではないと思います

- 例えば特に syuilo 氏が主体となってメンテナンスを行う場合、性格的に相性の悪い開発コストを強要することになり、プロジェクトそのものの健全性の観点から良くない
- 例えば特に syuilo 氏以外が主体となってメンテナンスを行う場合、現状機能開発などに積極的に参加できるほど時間を割けているのが tamaina 氏のみ（例えば私はせいぜいレビューやトリアージ程度）であり、かつメンバーは把握する限りこのプロジェクトに伴う援助を受けない慈善行為の状況での貢献になるので、実質的に tamaina 氏の興味次第になる
- 実際過去に v10 で保守サポートを試みたが v11 の更新速度の速さについていけず破綻した例がある

**Comment by fruitriin** [comment]
misskeyにはバグ報告くらいしかしてないけど、12の継続メンテは必要な人がやればいいんでない？
つまり、最初に言い出した人とか

13系はぽすぐれ15系を必須にしたことで12からのマイグレーションが非常に難しいということて必要性は理解した上で、
でももう自分のサーバーは13にしちゃったし……という立場

**Comment by massongit** [comment]
v12 LTSのサポートはリソース的に難しい旨了承しました。
それであれば、せめて最新版の安定性を上げる対策を行うのが良いのではないか、と感じます。
一定の安定性が確保されていればv12 LTSを作ろうという動きも出てこなかったのではないかと思うので。
具体的には以下のようなものが考えられます。

* 正式リリース前にRC版を設け、1,2日程度は間を空けて不具合がなければ正式リリースとする、というフローを (v12 -> v13のような大きなリリースだけでなく) 必ず行う
* CIが落ちている箇所を修正する、過去に発生した不具合を検知できるCI・テストを設ける、などすることで、CIによってリリース前の段階で不具合を検知できるようにする

**Comment by fruitriin** [comment]
他のところは"一般的に""普通"そうしているからここでもそうするべきだ、というのなら一旦ちょっと立ち止まってほしいと思った。
もちろん misskey-dev がそのほうが望ましい、と考えたうえで採用するのはありえるけど。

**Comment by acid-chicken** [comment]
理想論としてはそうかもしれないですが、

> * 正式リリース前にRC版を設け、1,2日程度は間を空けて不具合がなければ正式リリースとする、というフローを (v12 -> v13のような大きなリリースだけでなく) 必ず行う

RC 版があったとして、不具合がないというのをどのように定義づけるかによって次に分岐するものと思います

- チェックを毎回 misskey-dev がやる → 人的リソースを要することには変わりない
- テストを充実させて自動化する → 基盤作りをしないといけないが、突き詰めるとコストが増加し続ける（例えば、単純なユニットテスト→結合テスト→サーバーを立ててクライアントの E2E テスト→サーバー同士を連合させて連合周りの E2E テスト）ので助けてほしい（過去にはある程度私もテスト周りを触れていたけど、今は時間がない）
- 特にチェックをしない → 運用者がリリースから数日待つのと実質的に変わりない

> CIが落ちている箇所を修正する、

See #9096

> 過去に発生した不具合を検知できるCI・テストを設ける、

まぁこれはあってもいいかもしれないけど、どの道まず安定してテストできるようにするのが先（アーキテクチャや手法自体を見直すかもしれないので）

> などすることで、CIによってリリース前の段階で不具合を検知できるようにする

前項で触れた通り

といった感じです

**Comment by tamaina** [comment]
一言だけ: 言いたいことはわかるけどリソースが足りない

**Comment by EbiseLutica** [comment]
LTS、RC、どちらの件についても首がちぎれるほど同意ですが、私もリソース不足を理由に現状は難しい…と考えています。

**Comment by acid-chicken** [comment]
そもそも [ROADMAP.md](https://github.com/misskey-dev/misskey/blob/develop/ROADMAP.md#1-improve-maintainability-current-phase) に保守性の向上が第一の課題であるとそのまま書いてあって、かつこの通りメンバー間でもリソース不足が共通認識という感じなので、どうかご理解いただければ幸いです。もちろん貢献は歓迎します

**Comment by tamaina** [comment]
（もっと突っ込んだ話をすると、ここのところの人気上昇でリソースは足りてくるのかもしれないけどしゅいろメインの個人開発の方向性だと多人数での開発をするのが厳しいと言うのがある

**Comment by acid-chicken** [comment]
とりあえず v12 LTS は現実的に実施できないので形としては close しておきます
保守周りの話は Issue にできる状態になるまではここでやってもいいと思う

**Comment by massongit** [comment]
ありがとうございます。
リソース不足等の理由でv12 LTSも保守性向上も不可能と結論が出ているので、議論としてもcloseで良いと思います。
