### ISSUE TITLE
チュートリアル ：鉛筆マークの位置で誤った説明

### ISSUE THREAD

**Issue by masayatoy** [syuilo/Misskey#9849]
チュートリアルにおいて
「画面上にある鉛筆マークのボタンを押すとフォームが開きます。」と表示されている。
しかし、鉛筆マークは左下にある。

環境はPCのブラウザ。

私には翻訳できない。
https://github.com/misskey-dev/misskey/search?q=step3_2

**Comment by syuilo** [comment]
「画面上」の「上」は「on」という意味なので正しいです。

**Comment by syuilo** [comment]
また、鉛筆マークがどこにあるかはUIや表示するデバイスによって異なるので翻訳ファイルで位置を決め打ちすることは難しいです。

**Comment by masayatoy** [comment]
画面上（がめんうえ）ではなく画面上（がめんじょう）だったのですね。
すみません。
