### ISSUE TITLE
絵文字を追加しても見れない

### ISSUE THREAD

**Issue by mattyatea** [syuilo/Misskey#9853]
## 💡 Summary
絵文字を追加しても見れない(追加した直後は見れるけどリロードすると見れなくなる

## 🥰 Expected Behavior
追加してリロードしても見れる状態にあること

## 🤬 Actual Behavior
リロードするとみれない

## 📝 Steps to Reproduce

1.絵文字を追加する
2.絵文字をノートする
3.リロードする
4.文字列になる

## 📌 Environment

Misskey version: v13.5.5
Your OS: windows 11 
Your browser: google chrome 110.0.5481.78

**Comment by tamaina** [comment]
ストリーミングで絵文字の更新が流れてくるんだけど、その変更内容をブラウザに保存するべきだった
