### ISSUE TITLE
タイムライン上にある同じ投稿のリノートを1つに制限する

### ISSUE THREAD

**Issue by CyberRex0** [syuilo/Misskey#9854]
## Summary
多くの人にリノートされるとタイムラインが埋まってしまうため。(特にLTL)

**Comment by syuilo** [comment]
誰がリノートしたかというのも情報のひとつだからそれを見れなくするというのはどうなのかしら

**Comment by L1n4r1A** [comment]
流石に単純に全部をひとまとめにしちゃうのは誰が度のタイミングでどうRNしたのかわからないからダメかも

**Comment by CyberRex0** [comment]
それこそオプション式に
または、「A，Bがリノート」というまとめた形式にするとか
それはクライアントでの表現が難しい？

**Comment by EbiseLutica** [comment]
個人的には、まとめず今のままの方が好み

**Comment by syuilo** [comment]
> または、「A，Bがリノート」というまとめた形式にするとか それはクライアントでの表現が難しい？

やりたいけど複雑になりそう

あと間にリノート以外が入ったらまとめられないから結局は今と同じになってそんなに効果無さそう

**Comment by L1n4r1A** [comment]
同一人物が複数回RNして重なった(連続で重複してしまった)場合はまとめてしまっていいかも。
っていってもこれはラグで複数回押しちゃったとか、故意的に連打したくらいしか発生しないけど……。

**Comment by tamaina** [comment]
Duplicate of #1792

**Comment by syuilo** [comment]
やるとしたらオプションで、一度自分が見たリノートをクライアントに記録しておいてそれがまたTLに流れてきても無視するような実装かなあ

**Comment by syuilo** [comment]
厳密にはこっちは「1つに制限する」で、あっちは「省略表示をする」だから違うかも

**Comment by syuilo** [comment]
(Issueで「困っていること」を書かずに「解決方法」をタイトルにしてしまうからこうなる)

**Comment by tamaina** [comment]
> 厳密にはこっちは「1つに制限する」で、あっちは「省略表示をする」だから違う

厳密には省略表示するという表現には1つに制限するということが含まれると思った

**Comment by CyberRex0** [comment]
ちょっと曖昧だった　ごめん
