### ISSUE TITLE
Misskey Play：プリセットのインデントをタブからスペースに変更する

### ISSUE THREAD

**Issue by masayatoy** [syuilo/Misskey#9856]
## Summary
Misskey Playのプリセットのインデントは現在タブになっている。
しかし、Misskey Playのスクリプトをブラウザで入力している時にタブを入力すると別の項目に移る。
そのため、プリセットのインデントはスペースの方がよいのでは。

**Comment by syuilo** [comment]
タブをインデントとして入力できるように対応すれば解決できる
