### ISSUE TITLE
チャンネルからのReNoteの公開範囲をチャンネル内に限定する機能

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9860]
## Summary
misskey.gamelore.fun ではゲームごとにチャンネルを作る文化ができつつあるが、現状チャンネル内からReNoteしたときに公開範囲をチャンネル内に留める方法がない

ReNoteまたは引用をチャンネル内に限定する機能がもしあればとても嬉しいかも

**Comment by pantasystem** [comment]
Misskeyの挙動としてチャンネル内でRenoteできるのってどうなんでしょうか？
チャンネル内でRenoteをした場合、ageに近いものとして考えられる感じでしょうか？
API的には制限がないのでフロントエンドでchannelIdを指定してapi/notes/createをしたら
そのままrenoteできる感じなのでバックエンド的にはOKな挙動のようですが・・・

**Comment by syuilo** [comment]
ageがよくわからないけどチャンネル内Renoteは想定していたと思う

**Comment by syuilo** [comment]
done
