### ISSUE TITLE
/api/channels/followed のページネーションが働いていない

### ISSUE THREAD

**Issue by sim1222** [syuilo/Misskey#9861]
## 💡 Summary

/api/channels/followed のページネーションが働いていません

## 🥰 Expected Behavior

ページネーションが働いて続きが表示される

## 🤬 Actual Behavior

untilIdに値を入れてもDBの一番最後のチャンネル1つのみが帰ってくる？（空の配列が帰ってくるときもある）

## 📝 Steps to Reproduce

1. /channels のフォロー中を開く
2. 
3.

## 📌 Environment

Misskey version: 13.5.2 / 12.120.0
Your OS: Windows 11 22H2
Your browser: Google Chrome 109.0.5414.120 (Official Build) （64 ビット） (cohort: Stable)

**Comment by pantasystem** [comment]
このPRで修正PRが上がっていたようですがプロジェクト構造が合わずClosedされしまったようですね・・・
https://github.com/misskey-dev/misskey/pull/6706

コードを見たところ反映はされてなさそうですね
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/channels/followed.ts#L47

**Comment by sim1222** [comment]
現時点では修正されているようなので、Closeしておきます。
（https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/QueryService.ts#L43 このへんの変更によって一緒に解決された？）
