### ISSUE TITLE
ドライブのファイル一覧表示が遅いことがある

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9864]

**Comment by tamaina** [comment]
#9205 と似た事象だと思われる

**Comment by tamaina** [comment]
デフォルトのアップロード先をフォルダにしていて、ルートをたまにしか使っていない場合ダメなんだけど、2回目以降は結構速い（Redisかなんかのキャッシュが効いてそう）

**Comment by tamaina** [comment]
例えばインデックスの使い方が悪いとか  
（userId IS $1を探せば速いところfolderId IS NULLを先に検索してしまっているとかの可能性はありそう

**Comment by lynlynlynx** [comment]
これ結構困ってて、
私の環境だと、 `https://example.com/api/drive/files` がアクセスして最初の数回は10秒ほどで500を返してくるためリロードを数回行う必要がある。
それ自体はしょうがないで現状は割り切ってるけど。500を返して来てエラーになってるのにUIにクルクルが表示されたまま変わらないで、今の状態が応答待ちなのかエラーが出てストップしてるか分からなくて手動でリロードをかけるタイミングがわからないのが一番つらい。（PCだと開発者ツールを見て適宜リロードできるけど、スマホだと難しい）
ので500が出たらエラー出たからリロードしてって表示してくれるようになったらとても助かる。

**Comment by tamaina** [comment]
Duplicate of #14287
