### ISSUE TITLE
チャンネルに新規投稿がある時に新規通知のバッジがチャンネルの文字列に重なって読みにくい

### ISSUE THREAD

**Issue by mochi-sann** [syuilo/Misskey#9865]
## 💡 Summary
デフォルトUIでチャンネルへ切り替えるときに出てくるプルダウンについて、チャンネルに新規投稿がある時に新規通知の緑色の丸ががチャンネルの名前に重なって文字が読みにくい。
![screenshot 2023-02-10 19 18 16](https://user-images.githubusercontent.com/44772513/218068163-afd4a5bb-a96f-4930-ba10-71f1660af493.png)

## 🥰 Expected Behavior

新規通知のアイコンとチャンネルの文字が重ならないようにする

## 🤬 Actual Behavior
新規通知のアイコンとチャンネルの文字が重なっていて読みにくい

## 📝 Steps to Reproduce

1. どこかのチャンネルに入る
2. そのチャンネルで誰かが投稿する

## 📌 Environment

Misskey version: 13.5.2
Your OS: MacOS 13.1（22C65） 
Your browser: Vivaldi 5.6.2867.62 (Stable channel) (x86_64)

**Comment by KisaragiEffective** [comment]
triage: 2024.5.0では、未読通知がチャンネル名の右側に表示されます。
