### ISSUE TITLE
Docker self-build: ARMv7 support broken

### ISSUE THREAD

**Issue by jkumeboshi** [syuilo/Misskey#9867]
## 💡 Summary
Until v12 I was able to build a docker image for ARMv7 (armhf) CPU type, but with v13 there is a component that complaint unsupported CPU

## 🥰 Expected Behavior

The build process should not sopt if "cypress" component fails.

## 🤬 Actual Behavior

Since the component looks like a dev component to make unit tests, It should not fails if is missing.
 
## 📝 Steps to Reproduce
Just try to build docker image for ARMv7 CPU

the build proce3ss stops with following log:

```
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall$ node index.js --exec install
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: The Cypress App could not be installed. Your machine does not meet the operating system requirements.
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: https://on.cypress.io/guides/getting-started/installing-cypress#system-requirements
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: ----------
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: Platform: linux-ia32 (Debian - 11.6)
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: Cypress Version: 12.5.1
#0 470.8 .../cypress@12.5.1/node_modules/cypress postinstall: Failed


```

## 📌 Environment

Misskey version: 13.5.5
Your OS: Armbian 22.11.1 (Focal)

**Comment by tamaina** [comment]
v12ってarmhfでも動いていたのか

**Comment by jkumeboshi** [comment]
@tamaina 
Sorry, I don't speak Japanese.
Yes, I'm currently using v12.119.2 on an armhf ODROID HC2.

**Comment by saschanaz** [comment]
> Sorry, I don't speak Japanese.

There are many free translators you can use, so no need to say sorry 👀

**Comment by acid-chicken** [comment]
Many of people use Japanese because there are many Miskists in Japan (including misskey-dev), but using English is also good for global searchablility.

**Comment by KisaragiEffective** [comment]
triage: closing as it is upstream issue, and your processor would not receive support: https://github.com/cypress-io/cypress/issues/9272

consider upgrade your system.
