### ISSUE TITLE
typeormのマイグレーションが死んでる?

### ISSUE THREAD

**Issue by rassi0429** [syuilo/Misskey#9868]
## 💡 Summary
`pnpm run migrate` が通らなくなった。
ごちゃごちゃやっていたら、
おそらく https://github.com/misskey-dev/misskey/commit/1ff14d81c154df557bd22962c05c48c83d06b068 のパッケージアップデート後壊れてしまったようです。 typeormの~マイナー~パッチが上がっているようなので、それかも？ (未検証)
とりあえず報告としてissueを作りました。

## 🥰 Expected Behavior
マイグレーションが通る

## 🤬 Actual Behavior
migrationが空っぽになる

## 📝 Steps to Reproduce

1. 13.5.6にHEADを合わせる
2. pnpm run build 後 pnpm run migrate

## 📌 Environment
node 18.13.0

Misskey version:
Your OS:
Your browser:

**Comment by tamaina** [comment]
私のサーバーでは普通に動いていますね…

**Comment by rassi0429** [comment]
デプロイ環境では多分動いている（docker内）んですが、developからpullして、ローカル開発環境で初期のマイグレーションから動かそうとしているときにコケています。

4369d12eec476e16cdc517f944e56e38de377435 だと 
``` \misskey\packages\backend> pnpm typeorm migration:show -d .\ormconfig.js``` をすると
```
[X] 1 Init1000000000000
[X] 2 Pages1556348509290
[X] 3 UserProfile1556746559567
....
[X] 175 loggedInDates1674255666603
[X] 176 cleanup1675404035646
[X] 177 roleIconBadge1675557528704
```
(migration済みですが、空っぽであればXはつきません)  
と出ますが、 1ff14d81c154df557bd22962c05c48c83d06b068 の後 `pnpm install`をして同じコマンドを打つと何も帰ってきません。

ローカル環境がだいぶ汚れているのでいったんきれいにして再構築してもう一度報告します。

**Comment by tamaina** [comment]
開発環境でも動いてますね…（dockerではなくUTM VMで開発しています）

**Comment by rassi0429** [comment]
Dockerも吹き飛ばして再現しました。
DBを飛ばして、`pnpm run migrate`が正常に完了しません。


おそらく13.5になってからマイグレファイルが発生してないので事故ってないんだと思っています。
間違っていたらすいません。
node 18.13.0
pnpm 7.26.3
です。

**Comment by rassi0429** [comment]
https://github.com/typeorm/typeorm/issues/9769
症状的にこれっぽいみたいです、typeormのバージョンを一時的に下げる必要があるかもしれないです

**Comment by tamaina** [comment]
あ〜、イニシャライズでダメということか

（一応最初のコマンドは~~pnpm init~~pnpm run initなんだけどな〜）

**Comment by tamaina** [comment]
pnpm run initだ

**Comment by tamaina** [comment]
でも新しいデータベースでpnpm run initするのもちゃんと動いた

**Comment by rassi0429** [comment]
ごちゃごちゃのメモ
https://misskey.neos.love/notes/9b24ypnlep

結論: typeormのパッチアップデートがWindows環境のみで事故るようだった。
対策: WSLなどのLinux環境で開発する

**note: misskeyをLinux環境で動かすように推奨するようにしたほうがいいかもしれません**
