### ISSUE TITLE
MFMの一部記法のオプトイン化について

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#9873]
b0616b52eaebad83c982f9b3295f950147b28404 にて一部のMFM記法がデフォルトで無効化された件について、この変更は既存のノートの表示に甚大な影響を及ぼすため、慎重に考えたいと思いissueを立てました

## 意図を明らかにしてほしい

そもそもissueを立てて話し合いで決まった変更でないため、意図を明らかにしたほうがよさそう

## リスク

本変更は次のようなリスクがあります

* 既存のノートが大きく崩れてしまう（それによりバグと思われてしまうかも）
* MFMアート機能で遊んでも、環境によっては正常に表示されない

## 備考

（misskey.io等における荒らし行為を受けてのことと想定して主張すると、）荒らし対策はMisskeyの領分ではなく、規約等で縛るべきものではないかと思うし、それを理由にするにはあまりにも破壊的変更が過ぎると思います

## どうすべきか

* revertする
* 管理者がどちらをデフォルトとするか選べるようにする
* オプトインからオプトアウトにする
* この仕様で続行する

**Comment by syuilo** [comment]
opt-outにするか

**Comment by syuilo** [comment]
そのうえで
https://github.com/misskey-dev/misskey/issues/9862
をやると良さそう

**Comment by EbiseLutica** [comment]
他のコントリビューターからも意見聞いたほうが良さそう。この主張も、結局私の主観でしかない

**Comment by EbiseLutica** [comment]
まあ多分、optout + #9862 で大丈夫そう

**Comment by EbiseLutica** [comment]
良さそうなので閉じます～
