### ISSUE TITLE
【MFM】scale もしくは x2/x3/x4 を含む投稿を文字数関わらず強制的に`もっと見る`をつける

### ISSUE THREAD

**Issue by KawaneRio** [syuilo/Misskey#9882]
# <ruby>概要<rp>《</rp><rt>がいよう</rt><rp>》</rp></ruby>
<ruby>投稿<rp>《</rp><rt>ノート</rt><rp>》</rp></ruby>に `$[scale `もしくは `$[x2 ` `$[x3 ` `$[x4 ` いづれかの<ruby>文字列<rp>《</rp><rt>もじれつ</rt><rp>》</rp></ruby>が<ruby>検出<rp>《</rp><rt>けんしゅつ</rt><rp>》</rp></ruby>されれば、その<ruby>投稿<rp>《</rp><rt>ノート</rt><rp>》</rp></ruby>の<ruby>文字数<rp>《</rp><rt>もじすう</rt><rp>》</rp>関<rp>《</rp><rt>かか</rt><rp>》</rp></ruby>わらず<ruby>強制的<rp>《</rp><rt>きょうせいてき</rt><rp>》</rp></ruby>に `もっと見る` で<ruby>折<rp>《</rp><rt>を</rt><rp>》</rp></ruby>りたたまれるやうにしてほしい。

### <ruby>理想<rp>《</rp><rt>りさう</rt><rp>》</rp></ruby>

![image](https://user-images.githubusercontent.com/61252570/218260277-35e40c07-c9b6-4463-b306-84a81cc3e98a.png)

<details><summary><ruby>現狀<rp>《</rp><rt>げんじゃう</rt><rp>》</rp></ruby></summary><div>

![image](https://user-images.githubusercontent.com/61252570/218259884-c5f56d87-21e9-4e2e-a12e-7762031e323f.png)

 </div></details>

# Summary 

Fold notes automatically when note contains any of the following string: `$[scale ` `$[x2 ` `$[x3 ` `$[x4 ` (See attached image)

**Comment by kabo2468** [comment]
age
少なくともx3 x4には適用したほうがいい
デカくしてTLを埋めないわけがない

**Comment by KawaneRio** [comment]
@kabo2468  かぼさん、[pull](https://github.com/misskey-dev/misskey/pull/10012)ありがとうございます。

ただ、x3とx4だけではなく、scale と x2 関数も含めていただけないでしょうか・・・？

もしもこのfeatureが通ればそもそも警告画面の必要がなくなりますし（強制的にもっと見るになるので）、 https://github.com/misskey-dev/misskey/issues/9947 も同時解決できるかと我は思ひます。

**Comment by kabo2468** [comment]
含めるか
もっと見るのボタンがちょっと小さかったりスマホからだと下のボタンの裏に隠れちゃったりするので、そこも改善しないと警告は消せないかも
