### ISSUE TITLE
Moderation note が保存できない

### ISSUE THREAD

**Issue by KawaneRio** [syuilo/Misskey#9883]
## 💡 <ruby>概要<rp>《</rp><rt>がいよう</rt><rp>》</rp></ruby> 〜Summary

`Moderation note` が<ruby>保存<rp>《</rp><rt>セーブ</rt><rp>》</rp></ruby>できない

## 🥰 <ruby>期待<rp>《</rp><rt>きたい</rt><rp>》</rp></ruby>されし<ruby>動作<rp>《</rp><rt>どうさ</rt><rp>》</rp></ruby> 〜Expected Behavior

`Moderation note` が<ruby>保存<rp>《</rp><rt>セーブ</rt><rp>》</rp></ruby>される

## 😕 <ruby>実際<rp>《</rp><rt>じっさい</rt><rp>》</rp></ruby>の<ruby>動作<rp>《</rp><rt>どうさ</rt><rp>》</rp></ruby> 〜Actual Behavior

![Peek 2023-02-11 22-32](https://user-images.githubusercontent.com/61252570/218261233-840bee3f-3e09-4272-ab66-a876a1bac1f7.gif)

## 📝 <ruby>再現手順<rp>《</rp><rt>さいげんてじゅん</rt><rp>》</rp></ruby> 〜Steps to Reproduce

1. [Moderation note](https://misskey.io/user-info/93ut8vdhq3#moderation)に<ruby>握接<rp>《</rp><rt>アクセス</rt><rp>》</rp></ruby>する
2. なにかを<ruby>書<rp>《</rp><rt>か</rt><rp>》</rp></ruby>く
3. `保存`をする
4. ¡驚きの白さ!

## 📌 <ruby>手定め<rp>《</rp><rt>テスト</rt><rp>》</rp></ruby><ruby>環境<rp>《</rp><rt>かんきょう</rt><rp>》</rp></ruby> 〜Environment

Misskey version: Tested on `Misskey v13.5.3` ([Misskey.io](https://misskey.io)) and `Misskey v13.5.6` ([Mattyaski.co](https://mattyaski.co))
Your OS: `Kubuntu 22.04.1 LTS x86_64`
Your browser: `Mozilla Firefox 109.0.1`

**Comment by syuilo** [comment]
再現できなかった

**Comment by KawaneRio** [comment]
ぬぬぬ・・・もしかしたらロールの<ruby>影響<rp>《</rp><rt>えいきょう</rt><rp>》</rp></ruby>かもしれぬ・・・（？）

**Comment by kabo2468** [comment]
関係あるかはわからないけど、保存ボタンを押す度に飛ぶリクエストが倍になる
上はlocalhost v13.6.0 adminアカウント、下はmisskey.io v13.5.3 モデレーターアカウント
<details>
  <summary>画像</summary>

  ![image](https://user-images.githubusercontent.com/28654659/218285066-20a80e81-9dfb-4fd1-8873-f362d75f9ce1.png)

  ![image](https://user-images.githubusercontent.com/28654659/218285178-b128aa1a-afa1-4c1f-84bd-7d60a88eca6d.png)
</details>

**Comment by nenohi** [comment]
書き込み自体は行えてるっぽいかもしれない
モデレーターからユーザーノートの書き込みをする
↓
Adminロールのアカウントに切り替える
↓
ユーザーノートが書き換わってる
っていう現象までは見た
逆に`show-user`のレスポンスが
`isSuspended`しか見えてないのが原因になりそうかも

**Comment by KawaneRio** [comment]
これ完全に言うの忘れてたのですが、Misskey.ioがアップデートされた直後は普通に使えてましたが、今日また使えなくなっちゃいました。

**Comment by KawaneRio** [comment]
あー、待ってこれ原因わかったかも知れぬ。

**Comment by KawaneRio** [comment]
Moderation Note、Adminのアカウントでは反映されてるけど、モデレーターロールからだと反映された内容が見えない。
![Peek 2023-02-20 22-31](https://user-images.githubusercontent.com/61252570/220122382-5754b035-d602-4272-8807-965d0cbb9d61.gif)

**Comment by KawaneRio** [comment]
・・・ってすでに言われてましたね。ごめんなさい。。。
