### ISSUE TITLE
テスト落ちてる

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9889]
* Jestは 00d28826b9bb2bb65c90fc4c03ddd571faa7c7f6 (#9758. 以後 2cc98226cac2e0a08332e1ce281ba8917c5b58fc でまた失敗様相が変わりました)
* E2Eは 04f92bd6888b611c03962ffc202bc67f9592a372 (#9795. テスト失敗したり成功したりしますが最初の失敗はこっちです)

で落ちました。テスト結果を確認してください😛 (GitHubのbranch protectionとかどうでしょうか)

**Comment by futchitwo** [comment]
jestについては #9767 と #9096 にすでにissueが立っていますね
