### ISSUE TITLE
メインTLで、別のタブをクリックしても上に行ききらないことがある

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9890]
## 💡 Summary
メインタイムラインで、別のタブをクリックしてもスクロールが上に戻りきらないことがある

## 🥰 Expected Behavior
上に行ききる

## 🤬 Actual Behavior
上に行ききらない

## 📝 Steps to Reproduce

1. ホーム画面（メインタイムライン）でたとえばホームTLを表示しておく
2. ローカルTLを表示する
3. もう一度ホームTLを表示する

## 📌 Environment

Misskey version: 13.5.3 (misskey.io)
Your browser: Firefox, Chrome

**Comment by pumpkin2048b** [comment]
同じ事象でIssueを立てようかと思っていたところに本Issueを見つけたので詳細な再現手順を記載します。
## 📝 Steps to Reproduce
1. 最低でも30程度のノートがある状態にする　※追加読み込みが発生する程度
2. デフォルト、またはクラシックUIにする　※デッキUIでは問題なし
3. 任意のTLで一番下までスクロールする　※追加読み込み＋下まで
4. 別のTLを表示させる

## 📌 Environment
Misskey version: 13.10.3
Your browser: Chrome

**Comment by tamaina** [comment]
なんかよくわからんけど治ってそう
