### ISSUE TITLE
縦に長い画像を添付するとiOSだとメディア枠が大きくなる

### ISSUE THREAD

**Issue by kabo2468** [syuilo/Misskey#9893]
## 💡 Summary

https://misskey.io/notes/9b257rclts
1000px x 1pxの画像
PCやAndroidだと正常に表示する
iOSだとメディア枠自体が大きくなって邪魔

多分Webkitが悪そう

## 🥰 Expected Behavior

他の画像と同じように表示される

## 🤬 Actual Behavior

メディア枠が大きく表示される

## 📝 Steps to Reproduce

1.縦長の画像を添付して投稿する
2.メディア枠が大きく表示される

## 📌 Environment

Misskey version: v13～？
Your OS: iOS 16 / iPadOS 15
Your browser: Safari

**Comment by syuilo** [comment]
最新版では修正されている
