### ISSUE TITLE
虚無のノートが作れてしまう

### ISSUE THREAD

**Issue by frfs** [syuilo/Misskey#9902]
## 💡 Summary
表題の通り
![image](https://user-images.githubusercontent.com/8694755/218301363-a5fd20b6-8b71-4de3-aa96-b5901677f502.png)

## 🥰 Expected Behavior
投稿時にエラーが出る？要検討そう。

## 🤬 Actual Behavior
虚無ノートができる

## 📝 Steps to Reproduce

1. 画像を添付したノートの下書きを作る
2. 一旦投稿画面を閉じてドライブを開く
3. ドライブから1で添付した画像を消す
4. 投稿画面を開き直して、そのまま投稿する 

## 📌 Environment

Misskey version: 13.2.6
Your OS: Win 11
Your browser: Chrome 109.0.5414.120

**Comment by tamaina** [comment]
サーバー側でparamDefを元にバリデーションして弾いてくれるはずなんだけどそうなっていない？

**Comment by tamaina** [comment]
あ、、ドライブからファイルを消すとバリデーションは通過するな

**Comment by ThinaticSystem** [comment]
多分対応別issueになるとは思いますがこういうのもあるっぽい
https://misskey.io/notes/9b57djkva0
