### ISSUE TITLE
ページ上で、{}で囲まれた部分がNULLとして表示される

### ISSUE THREAD

**Issue by Sayamame-beans** [syuilo/Misskey#9908]
## 💡 Summary

作成したMisskey Pluginを掲載するためにPages上でコードブロックを用いてAiScriptを記述した際、`{}`で囲まれた一部の内容がNULLに置き換わって表示されていることに気付きました。
ノート上ではこの現象は発生しません。

[検証用ページ](https://misskey.niri.la/@Sayabeans/pages/1676208996567)によれば、コードブロック内、plain構文内、構文無しのいずれの場合においても本現象が発生している事が分かります。

更に、以下のリンク先でも本現象が発生しているところを確認することが出来ます。
[AiScriptメモ(docのリンク、役立ち情報等)](https://misskey.io/@salano_ym/pages/aiscript-memo)

## 🥰 Expected Behavior

前述の検証用ページにおいて
```
print(Json:stringify({key: "value"}))
let a = @(){print("test")}
```
print(Json:stringify({key: "value"}))
let a = @(){print("test")}
と表示。

## 🤬 Actual Behavior

前述の検証用ページにおいて
```
print(Json:stringify(NULL))
let a = @()NULL
```
print(Json:stringify(NULL))
let a = @()NULL
と表示。

## 📝 Steps to Reproduce

1. Pages上で{}で囲まれた内容(例: AiScriptのオブジェクトや関数)を記述し、保存する
2. 作成したPagesを開く

## 📌 Environment

Misskey version: 13.6.0(2つのインスタンス), 13.5.3(misskey.io)
Your OS: Windows 10 Pro 22H2
Your browser: Google Chrome 109.0.5414.120

**Comment by syuilo** [comment]
fixed
