### ISSUE TITLE
Custom emojis from closed servers are shown as texts

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9912]
## 💡 Summary

Example: https://k.lapy.link/notes/951xifgh7m

![image](https://user-images.githubusercontent.com/3396686/218329585-62816925-132d-43f1-bd30-e1a4bbeb7aa2.png)

## 🥰 Expected Behavior

どうするのがいいでしょか

## 🤬 Actual Behavior

絵文字の代わりにテキストが現れる

## 📝 Steps to Reproduce

1. サーバー作る
2. 絵文字リアクションする
3. サーバー閉める
4. さっきの絵文字リアクションを見てみる

## 📌 Environment

Misskey version: 13.6.1
Your OS: Firefox
Your browser: Windows 11

**Comment by pantasystem** [comment]
参考までにですがFedibirdなどでは絵文字が消えるとリアクション自体を消しているようです
https://fedibird.com/@noellabo/109853203792401201

**Comment by acid-chicken** [comment]
Discord のSticker みたいに fallback となる絵文字（Unicode）を指定できるようにしてもいいかも

**Comment by kazu0617** [comment]
この2パターンぐらい…？かなと思っています。
ローカルにキャッシュするのは怖いので。
> 1. 閉鎖して取れない場合は一括してこちら側（受け取った側）のサーバにある代替リアクション,⭐などを指定し、altに元々のリアクションを表示(マウスホバー、Moreメニュー[リアクション]からオリジナル名を確認可能)
> 2. Google Archive / Wayback Machineから遅延でロード出来たらした上で、ダメ(400番台,403,404,410)なら1にフォールバック

**Comment by saschanaz** [comment]
>⭐などを指定し、altに元々のリアクションを表示

視覚的に見えるものとaltは一致したほうがいいと思いますので、どちらも⭐でいいかもです。

>Google Archive / Wayback Machineから遅延でロード出来たらした上で

edge caseですのでそのためにこうまでするのはoverkillじゃないかなって感じもしますが🤔

**Comment by kazu0617** [comment]
> 視覚的に見えるものとaltは一致したほうがいいと思いますので、どちらも⭐でいいかもです。

altに表示するのは本質的に☆を示したい場合でもないケースがあるのでオリジナルの名称をどこかに残しておくためですね。
オリジナルの名称が見えるのであれば正直altじゃなくてもいいと思います。

> edge caseですのでそのためにこうまでするのはoverkillじゃないかなって感じもしますが🤔

:soreha_sou: あくまでも
- 作っておいても鯖自体に負荷がかかるわけではなく（クライアント処理のため）
- 機能自体はデフォルトオフにしておけば何も知らないユーザーに余分な通信をさせる必要もなく
- かといってどうしても見たいというケースであれば（クライアント負担の上で）見ることもできる

といった意味で一応案として出した感じでした。オーバーキルなのはおっしゃる通りです。

**Comment by tamaina** [comment]
> Discord のSticker みたいに fallback となる絵文字（Unicode）を指定できるようにしてもいいかも

これ #6457

**Comment by acid-chicken** [comment]
> > Discord のSticker みたいに fallback となる絵文字（Unicode）を指定できるようにしてもいいかも
> 
> これ #6457

とはちょっと違う（Discord の Sticker はテキストとは別に紐づける Unicode 絵文字も選ぶ）

**Comment by tamaina** [comment]
（Unicode絵文字だけで良くねと思った）

**Comment by rinsuki** [comment]
自分のスタンス: 別にshortcodeでよくね？と思う (#6457 に対しても)

* shortcode は本来人間が可読可能な文字列であるべき (picker はおまけ) で、理解できない shortcode を設定するのは設定者が他人に理解させる意図がないとみなすべき (システム上の制限の場合は…そのシステムが悪い)
* Unicode絵文字に置換することが困難な絵文字も結構ある (というか置換していいならカスタム絵文字の有用性が疑わしい)
* Wayback Machine もそれはそれで微妙 (遅いし不安定だし金なさそうだし)
* 外部ユーザーがアップロードした画像が自サーバーにキャッシュされる設定の場合、カスタム絵文字もローカルにキャッシュするというのは十分にありだと思われる (というかそうなってなかったっけ？)

**Comment by saschanaz** [comment]
私的にはshortcode長すぎて面白くもないのでいっそ空白（U+3000とか）にしてもいいと思います（shortcodeは`alt/title`に残していいでしょう）

**Comment by tamaina** [comment]
> どうするのがいいでしょか

カラーバー画像とか？とか表示しとけばよさそう

**Comment by tamaina** [comment]
（プッシュ通知やノート本文とUI上のリアクションは別に考えたほうがよかったか

**Comment by fruitriin** [comment]
個人的にはショートコードで特に困ってない
ショートコードの名前見て面白いなあと思ったりしてる
頑張ってフォールバックするとかよりもなければないでしれっと見た目上消すのも結局誰も気づかなさそうだし実装もシンプルだしよいかなと思う

**Comment by saschanaz** [comment]
* Reaction UI: テキストでは長すぎるのでやっぱりなんとかしてほしい、隠すのもいいと思います（reaction多すぎる場合すでに一部隠しているので）
* Push: `:meowflower:` とか口で読むと意味わからないので、せめて「meowflowerの絵文字」とかになるともっとスクリーンリーダーに優しくなるかもです

**Comment by KawaneRio** [comment]
> Push: :meowflower: とか口で読むと意味わからないので、せめて「meowflowerの絵文字」とかになるともっとスクリーンリーダーに優しくなるかもです

それはMisskey側ではなくスクリーンリーダー側の問題な気がする（だって絵文字だってことは`:`と`:`で囲ってる時点で自明だし、そもそもリアクションピッカーにある時点で絵文字ってことはわかることだし、Misskey以外にも例えばTwitchやDiscordやTelegramでも絵文字/Emotesは`:`と`:`で囲ったShortcodeになってるので）

**Comment by rinsuki** [comment]
~~reaction多い場合は優先的に「もっと！」に押し込めるのはいいかも~~と思ったけど結局画像読んでみるまで読めないので微妙かも (なんか面倒な処理を挟めばできなくはない)

> だって絵文字だってことは:と:で囲ってる時点で自明だし

そんなことはない (e.g. IPv6アドレス)

 > リアクションピッカーにある時点で絵文字ってことはわかることだし

リアクションピッカーなんてスクリーンリーダーは知らない (Misskeyはスクリーンリーダーへそのような情報を提供していないはず)

**Comment by kazu0617** [comment]
WayBackMachineの案はさすがにぶっ飛んでるとして、
- shortcode
- :+1: などの汎用絵文字にフォールバック(クライアント設定で選択)
- 消す
をクライアント設定で選べるでよさそうな気がします。

---

shortcodeそのままはスマホ環境で読めるかといわれると横の文字と重なって読みづらいので何かしらの処理は挟んでおいてほしいです。とはいえ今現状読める環境&実装もシンプルなので選択肢として置いておきたい。

フォールバック絵文字を選択制（デフォは 👍🏼 とか。Mastodonからリアクションされたものと合わせている感じ）にしてそこに加算して表示することで総数変わるのはちょっと、という人はこれでよさそう。

消すのは総数変わるので自分は選ばないですが、上の処理に対してshortcodeから解決できなかった
→消すでそのまま作れるので選択肢から外す必要はないのかなという気はします。

**Comment by Sayamame-beans** [comment]
triage: ダミー絵文字を表示する形に変わっているのでClose(逆に、テキスト表示もしたいという別issueは開く余地ありかも)
