### ISSUE TITLE
Dev Containerの設定 init.sh

### ISSUE THREAD

**Issue by Neko7sora** [syuilo/Misskey#9917]
## 💡 Summary

![image](https://user-images.githubusercontent.com/75793267/218369454-f223307f-63a1-4166-81e1-c5bb2d355034.png)

https://github.com/misskey-dev/misskey/pull/9872

## 🥰 Expected Behavior

以下のコマンドが正常にgitが処理される

```sh
$ git config --global --add safe.directory /workspaces/${localWorkspaceFolderBasename}
```

## 🤬 Actual Behavior

```sh
node ➜ /workspaces/misskey $ git submodule update --init
fatal: detected dubious ownership in repository at '/workspaces/misskey'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/misskey
```

## 📝 Steps to Reproduce

1. Dev Containerで開く

## 📌 Environment

commit: develop [8d4c5de](https://github.com/misskey-dev/misskey/commit/8d4c5deb8dc173d59975e998dc1295c698af362b)
Your OS: Windows 11
docker: 4.16.2 (95914)
docker内のgit:  2.39.1

**Comment by Ry0taK** [comment]
おそらくなのですが、Git for WindowsでCloneするとこうなるような雰囲気がありそうでした。WSL内でCloneしてVSCodeで開くとどういった挙動になるかご確認頂けますか...?

**Comment by Neko7sora** [comment]
> WSL内でCloneしてVSCodeで開くとどういった挙動になるかご確認頂けますか...?

![image](https://user-images.githubusercontent.com/75793267/218377464-fb19ba35-d23a-4d50-930b-12086d460b99.png)

同じ挙動になります。

**Comment by Ry0taK** [comment]
なるほど、ありがとうございます。もう一点確認なのですが、WSL内のClone先はWindows上のディレクトリ (`/mnt/`配下)のものでしょうか？

**Comment by Neko7sora** [comment]
WSL内のClone先はWindows上のディレクトリ (/mnt/配下)のものです。

**Comment by Ry0taK** [comment]
承知いたしました。その場合、WSL内のホームディレクトリ (`/home/`配下)で再度Cloneして頂いたあとにVSCodeで開くと動作するかどうかをご確認いただけますでしょうか...?

**Comment by Neko7sora** [comment]
> 承知いたしました。その場合、WSL内のホームディレクトリ (/home/配下)で再度Cloneして頂いたあとにVSCodeで開くと動作するかどうかをご確認いただけますでしょうか...?

`init.sh`が自動実行時にエラーが発生し、Dev Containerに再接続して、bashで`git submodule update --init`コマンド入力しても、同じエラーが発生します。
![image](https://user-images.githubusercontent.com/75793267/218382665-b3442b72-4690-4af7-a688-4ebc9d099bf8.png)


BTW, `init.sh` の `set -xe` からbashを打つと、
![image](https://user-images.githubusercontent.com/75793267/218382900-45c5ddf6-e0ca-4407-a564-39ed97960e1d.png)

**Comment by Ry0taK** [comment]
調査した結果、以下のような問題を修正する必要がありそう
1. Git for WindowsでクローンしたリポジトリをDev Container内で開き直すと改行コードの違いによりシェルスクリプトの実行に失敗する -> CONTRIBUTING.mdにその旨を追記しておく
2. 特定のケースにおいてファイルの権限がめちゃくちゃになるので起動時にファイルの所有者を修正する

(後でプルリク作って送ります)
