### ISSUE TITLE
audio/video elementに`preload=metadata`を与える

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9923]
## Summary

~~基本`preload=auto`で~~、再生しなくても映像ダウンロードが起きますがそれを回避したいです。

Edit:

https://html.spec.whatwg.org/multipage/media.html#dom-media-preload

>The attribute's [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) and [invalid value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#invalid-value-default) are [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined), though the [Metadata](https://html.spec.whatwg.org/multipage/media.html#attr-media-preload-metadata-state) state is suggested as a compromise between reducing server load and providing an optimal user experience.

デフォルト`auto`じゃないんですね

**Comment by kakkokari-gtyih** [comment]
Done in #12925
