### ISSUE TITLE
グループの本格的削除

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9931]
## Summary
グループ機能は現状UIから削除されているが、本格的に廃止する？

インスタンスをもう少し小さいまとまりと考えて、インスタンス一単位やロールをグループとして扱う方が良さそう

**Comment by futchitwo** [comment]
チャット廃止に伴って議論する間も無く廃止になる感じだと思ってたんだけど（#7348 とかを実装しない限り）

一応参考程度に現在のグループ的なものをまとめておく
名称 | 作成できる人 | 他人が会話を見れるか | 他人がメンバーを見れるか  | HTLに表示されるか
-- | -- | -- | -- | --
インスタンス | 鯖缶 | 見れる(LTL) | 見れる | される
ロール | 許可された人 | 未実装 | 見れる | 未実装
チャンネル | 誰でも | 見れる | 見れない | フォローしているとされる
グループ | 誰でも | 見れない | 見れない | されない
メンション | 誰でも | 公開範囲による | 公開範囲による | される

**Comment by syuilo** [comment]
グループにも活躍の機会がないわけではないと思うけど、分散型的には一つの大きいインスタンスがあってその中にグループがいくつもできるよりも、より小さいまとまりでインスタンスがぽこぽこある方が理に適ってそうだし、実装も大変だしとりあえず消しても良さそう

**Comment by futchitwo** [comment]
あとチャンネルをActivityPubグループとして再実装して、グループフォロワーオンリーとかフォロー申請制グループができるようになったら割といい感じのグループの代替になりそう
