### ISSUE TITLE
【DM中にも】MFM迷惑投稿防止ダイアログの発生条件の改善【ホームに投稿しますか？】｜ Make the MFM post warning dialog only appear for public posts

### ISSUE THREAD

**Issue by KawaneRio** [syuilo/Misskey#9947]
# <ruby>問題<rp>《</rp><rt>もんだい</rt><rp>》</rp></ruby> 〜Problem

<details><summary>投稿範圍がホーム投稿・返信ノートでも警告UIが出る</summary><div>

![Peek 2023-02-14 17-55](https://user-images.githubusercontent.com/61252570/218687135-6c1a5222-67b5-4171-91fe-bdb082e1b727.gif)
</div></details>

<details><summary>投稿範圍がフォロワーのみでも「ホームに投稿しますか？」と聞かれる</summary><div>

![Peek 2023-02-15 21-11](https://user-images.githubusercontent.com/61252570/219024162-68f3bdd8-e6e9-4b8f-b490-3110019f3411.gif)
</div></details>

<details><summary>DM投稿でも「ホームに投稿」と聞かれる（）</summary><div>

しかもちゃんとホームに投稿されちゃう（⸘トラップカード‽）

![Peek 2023-02-15 21-15](https://user-images.githubusercontent.com/61252570/219025145-cbba6c2a-c1ed-40e4-a8e0-f4e84b0f37af.gif)
</div></details>

# <ruby>提案<rp>《</rp><rt>ていあん</rt><rp>》</rp></ruby> 〜Proposal

パブリック投稿時**のみ**に警告。それ以外の投稿（ホーム、フォロワー、ダイレクト投稿など）の過激MFMには警告ダイアログを表示しない。

![MFM_warning](https://user-images.githubusercontent.com/61252570/219028896-297e7a5f-0a71-4e89-bffa-1f3ff857219f.png)

**Comment by KisaragiEffective** [comment]
fixed by #10457
