### ISSUE TITLE
検索機能の統合

### ISSUE THREAD

**Issue by creeper-0910** [syuilo/Misskey#9949]
## 概要
ユーザーやノートを検索する場所が二箇所に別れていることに違和感を感じてしまうので、検索ボタンと"みつける"にある検索機能を一つにまとめることで見やすくなるかな?と感じました
## 例
スクリーンショットのような感じに上部にボタンを2つ配置し、それぞれ"ノート"、"ユーザー"と切り替えられるようにして、サイドバーの検索を押した時そのページに飛ぶ、もしくはそのページをウィンドウ表示すると使いやすいかなと感じました
![Screenshot_2023-02-16-02-00-16-62_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/56744841/219100775-db7c5fd6-5504-4ebc-baf4-04fcbd3425ef.jpg)
説明が下手ですみません。不明な点がありましたら補足します。

**Comment by syuilo** [comment]
done

**Comment by creeper-0910** [comment]
ありがとうございます！🙏
