### ISSUE TITLE
[BUG] Poll responses missing from notifications

### ISSUE THREAD

**Issue by NovaAndrom3da** [syuilo/Misskey#9952]
I don't get notifications for poll responses in misskey 13, so I'm unable to see who responded with what.

**Comment by syuilo** [comment]
This is intended.

**Comment by NovaAndrom3da** [comment]
@syuilo Why? Wouldn't it be better to have a toggle on the poll creation form so the OP can choose?

**Comment by syuilo** [comment]
This is because of performance issues and the need for anonymity in voting in many cases.
