### ISSUE TITLE
マイグレーションdropGroup1676434944993でinvalid input value for enum user_profile_mutingnotificationtypes_enum: "groupInvited"

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9953]
migration

mutingNotificationTypesへ新しいenum[]をALTER TYPEするときにgroupInvitedを削除しないとダメかも？  
どうしてantenna.srcやnotification.typeが大丈夫なのかがわからない（enumではよしなにやってくれるけどenum[]では自動で削除してくれない？）

**Comment by tamaina** [comment]
あくまでフォークで実行しているので、微妙にデータベースが壊れている可能性はある（同じバグを見た方はご報告いただけると幸いです）

**Comment by tamaina** [comment]
PostgreSQL 9まではそもそもenumを減らすのが御法度だったっぽいし、無理にマイグレーションでなんとかしようとせずDB上に残しちゃっても良いんじゃないか説があるけどどうだろう @syuilo

**Comment by tamaina** [comment]
（emailNotificationTypesはjsonbなんだなぁ）

**Comment by syuilo** [comment]
> PostgreSQL 9まではそもそもenumを減らすのが御法度だったっぽいし、無理にマイグレーションでなんとかしようとせずDB上に残しちゃっても良いんじゃないか説があるけどどうだろう @syuilo

いいと思う
