### ISSUE TITLE
スパムurl、またはそのリンクを含むノートを管理者がブロックできるようにする

### ISSUE THREAD

**Issue by creeper-0910** [syuilo/Misskey#9958]
## 概要
最近misskeyではスパムユーザーが少しずつ増えているようです。
なので、スパムurlを含むノート、もしくはurlからサイトに飛ぶのをブロックする機構、そしてスパムurlを投稿するユーザーの凍結が必要だと考えます。
## メリット
一括で不審なユーザーを減らすことが出来、ユーザーが安心して利用できるようになる。
## デメリット
urlブロックによりサーバーの負荷が増加する可能性(技術的なことは分からないためあくまで予測です

お忙しい中申し訳ありません、よろしくお願い致します。

**Comment by syuilo** [comment]
あるURLがスパムかどうかを判定するのは難しそう

**Comment by creeper-0910** [comment]
すみません、説明文に加えるのを忘れていました。
管理者の方がスパムと判断したurlをブラックリストの様な形で追加し、ブロックできるような仕組みがあるといいな、と考えています。

**Comment by tamaina** [comment]
Duplicate of #13207
