### ISSUE TITLE
notes/featuredはGETで取得できるように

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9959]
## Summary
非ログイン時のnotes/featuredをGETで取得させるようにするとキャッシュが効いてインスタンスが軽くなりそう

**Comment by pantasystem** [comment]
良いとは思うのですが後方互換性を持たせる予定はありますか？

**Comment by tamaina** [comment]
今回はPOSTでも取得可能  
（ユーザーごとにミュートを出し分ける必要があるため

（基本的にallowGetはPOSTでも取得可能だけど、方針転換でサーバーの性能的にクリティカルの場合はPOST禁止にするかもしれないので逃げ道を持った回答の仕方をしてみた
