### ISSUE TITLE
develop最新でDockerがビルドできない？

### ISSUE THREAD

**Issue by fruitriin** [syuilo/Misskey#9974]
## 💡 Summary
develop最新をpullしてきてビルドできない

## 🥰 Expected Behavior
ビルドできない

## 🤬 Actual Behavior
Building web
Sending build context to Docker daemon  163.1MB
Error response from daemon: dockerfile parse error line 19: Unknown flag: link
ERROR: Service 'web' failed to build : Build failed

## Note
ChatGPTによる回答
Dockerfileの先頭に記述するsyntax命令は、Dockerfileのバージョンを指定するために使用されます。docker/dockerfile:1.4は、Dockerfileのバージョン1.4を表しています。Dockerfileのバージョン1.4では、--linkフラグはサポートされていないため、syntax命令を変更しても、--linkフラグを使用することはできません。

Dockerfileのバージョン1.4以降であれば、syntax命令を変更することで、--linkフラグを使用することができます。たとえば、Dockerfileのバージョンを1.4から1.5に変更すると、--linkフラグを使用することができます。

## 📝 Steps to Reproduce

1.  
2.
3.

## 📌 Environment

Misskey version: 0f546b4
Your OS: Ubuntu 22 LTS
Your browser:

**Comment by rinsuki** [comment]
DOCKER_BUILDKIT=1 環境変数を設定してみてください

**Comment by Candinya** [comment]
For docker-compose users you might need this command

```shell
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
```

**Comment by fruitriin** [comment]
Thanks
