### ISSUE TITLE
Deckモードで /share を開いた際に投稿フォームが表示されない

### ISSUE THREAD

**Issue by youdofoo** [syuilo/Misskey#9981]
## 💡 Summary

Deck モードで下記の共有用投稿フォームが表示されない
https://misskey-hub.net/docs/features/share-form.html

## 🥰 Expected Behavior

投稿フォームが表示される

## 🤬 Actual Behavior

投稿フォームが表示されず、メインページのみが表示される

## 📝 Steps to Reproduce

1. UI切り替えで Deck モードにする
2. https://misskey.io/share?text=test を開く

## 📌 Environment

Misskey version: 13.6.1
Your OS: Windows 10
Your browser: Google Chrome 110.0.5481.104

**Comment by youdofoo** [comment]
こちらメインカラムを追加すれば、/share を開いた際にメインカラム内で投稿フォームが開かれることがわかったためクローズさせていただきます

**Comment by naskya** [comment]
`/share` のページだけでなく、Deck UI を表示させているときに別のページに（例えばアドレスバーに `https://google.com/` と入力して）移動しようとしても元の Deck UI を表示するページに戻ってきますが、それも同じ現象でしょうか
Deck UI 内で表示されているリンクをクリックするぶんにはちゃんと動きます（例えばノートに添付されている URL をクリックすると新しいタブでそのページが開き、誰かのアイコンをクリックするとユーザーページがウィンドウで開く）

Misskey version: 13.6.1 ([Misskey.io](https://misskey.io/), [喵窝](https://nya.one/))
Your OS: Arch Linux (Linux 6.1.11-arch1-1)
Your browser: Mozilla Firefox for Arch Linux 111.0 (64-bit)
