### ISSUE TITLE
インスタンスのユーザー分散を促すログイン画面の案

### ISSUE THREAD

**Issue by t-asa2000** [syuilo/Misskey#9986]
## Summary / 概要

大規模かつ知名度の高いインスタンスに新規ユーザーが多く流入することによって，管理者への負担の増加などの課題がある．また，中にはmisskeyが "分散型" だと知らずに登録される利用者も見受けられる．

インスタンスへの最初の入り口となるログイン画面に手を加えることで，それらの問題が多少は改善できるのではないかと考えました．

## Image / アイデアのイメージ

分散型であることを分かりやすくするため， **サーバー** って単語を強調してます．．．

**ローカルタイムラインを見てみる**
 - 未ログイン状態でもLTLが見れる画面へのリンク<br>[ex: misskey.io/timeline](https://misskey.io/timeline)

**別のサーバーを選択(ランダム)**
 - 当該サーバーと連合中の他のサーバーからランダムに，別のログインページに飛ぶ．
 - 完全なアトランダムの場合，怪しいスパム鯖などに飛ぶ可能性あり．

**別のサーバーを選択(リストから)**
 - 当該サーバーと連合中の他のサーバーを一覧表示．
 - 現在でも `インスタンス情報->連合` から見れるので，そのページをより見やすくした上で，ボタンのリンクとしたい．

![image](https://user-images.githubusercontent.com/44716771/219871917-a3738cf9-9214-43b1-ae74-d020d8a9d7a1.png)

**Comment by futchitwo** [comment]
分散化を促す場合、別のインスタンス/サーバーに登録してもらうことが目的になるので、特にランダムの場合は招待コードが不要なインスタンスが選ばれると良さそうです

**Comment by syuilo** [comment]
ランダムは実装方法がなさそうなためオミットするかも
