### ISSUE TITLE
Android Chromeで、セキュリティ設定画面でWebAuthnの鍵を追加しようとするとブラウザがクラッシュする

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#9993]
セキュリティ設定画面でセキュリティキーの追加をする場面で、Android Chromeがクラッシュする

## 💡 Summary

- navigator.credentials.createを発行してから一呼吸あけてクラッシュする（Chromeのクラッシュはあまり見ないので相当異常な状態）
- Android 11 (TONE e22)、Android 13（Xperia 10 IV A202SO）で発生
- PWAでないブラウザ画面でも発生

bugs.chromium.org

https://bugs.chromium.org/p/chromium/issues/detail?id=1417468

## 📝 Steps to Reproduce

1. セキュリティ設定画面を開く
2. TOTPを設定しておく
3. パスワードを入力などしてnavigator.credentials.createを呼ぶ

## 📌 Environment

Misskey version: misskey.io, #9985 
Your OS: Android 11, Android 13
Your browser: Chrome 110.0.5481.65

**Comment by saschanaz** [comment]
Crashは絶対Chromeのバグ

**Comment by tamaina** [comment]
bugs.chromium.org行きか？  
（他のサイトでも発生するかとか検証するのが面倒だけど…）

**Comment by tamaina** [comment]
webauthn.ioだと普通に登録できるんだなぁ

**Comment by acid-chicken** [comment]
ログない？ (chrome://device-log とか)

**Comment by saschanaz** [comment]
>他のサイトでも発生するかとか検証するのが面倒だけど

別に他のサイト確認しなくてもcrash発生は100%バグですので

**Comment by tamaina** [comment]
> ログ

device-logは履歴ないけどcrashesはたまっている

**Comment by acid-chicken** [comment]
ログから search terms を探索しないと進まなそう

**Comment by CyberRex0** [comment]
確かにクラッシュした
(Sony Xperia 5 IV、Android 13、Chrome 110.0.5481.65)

ここに貼っても意味ないけどログも
[chrome-crash-2023-02-19-17-29-09.log](https://github.com/misskey-dev/misskey/files/10776436/chrome-crash-2023-02-19-17-29-09.log)

**Comment by saschanaz** [comment]
確かにクラッシュした２
(Samsung Galaxy S22 Ultra, Android 13, Chrome 110.0.5481.65)

**Comment by saschanaz** [comment]
なぜかStep 3でパスワード間違えたらエラーでなくてスルーされる

**Comment by tamaina** [comment]
> なぜかStep 3でパスワード間違えたらエラーでなくてスルーされる

↓諸々改善（でもパスワード間違いもサーバーのエラーとして表示される気がするのでなんとかする必要はある）

https://github.com/misskey-dev/misskey/pull/9985

**Comment by tamaina** [comment]
bugs.chromium.org

https://bugs.chromium.org/p/chromium/issues/detail?id=1417468

**Comment by saschanaz** [comment]
セキュリティバグになっててアクセスできませんｗ

**Comment by tamaina** [comment]
クラッシュレポートにしたから？文中にsecurityが含まれているから？（URLを書けとテンプレートにあったのでhttps://misskey.io/settings/securityを書いた）

**Comment by tamaina** [comment]
Pixel 7でも再現した

**Comment by creeper-0910** [comment]
OPPO Reno Aでも同様でした

**Comment by tamaina** [comment]
Chrome Canaryで修正されたのでClose
