### ISSUE TITLE
[frontend] MkNote.vue, MkNoteDetailed.vue で、特定のMFMによってフッターのボタンが押せなくなる

### ISSUE THREAD

**Issue by hapo31** [syuilo/Misskey#9998]
## 💡 Summary

個別にノートの詳細を表示する画面( `/notes/${noteId}` )とデッキモード時に、ノートに以下のように全体の座標を大きく変えるようなMFMを指定したとき、  
フッターのボタンが押せなくなり、リアクションなどが出来なくなることがある。 ~(※この画面だけ)~

※追記
デッキモードでも再現した。

```
$[position.y=10 $[fg.color=0cf $[x2 **ブルー**]]$[fg.color=fff $[x2 **アーカイブ** ]]
$[position.x=7,y=-4.5 $[fg.color=fff  $[x3 $[rotate.deg=117 C ]]]]
$[position.x=7.5,y=-10.5 $[fg.color=0cf $[x3 $[rotate.deg=20 ー]]]]
$[fg.color=0cf $[position.x=6.4,y=-16.5 $[x4 $[rotate.deg=110 ー]]]]
$[position.x=10,y=-19 $[fg.color=fff BlueArchive]]]
```

再現 url
https://misskey.io/notes/9bcamd63fv

スクリーンショット
![image](https://user-images.githubusercontent.com/5890396/219948265-5b5ff172-b2dd-499b-89b1-b08eb1dc9edc.png)

## 🥰 Expected Behavior

リアクションなどが押せる

## 🤬 Actual Behavior

リアクションなどが押せない・・・

## 📝 Steps to Reproduce

1. 以下のクラスのスタイルに `overflow: clip;` を当てる  https://github.com/misskey-dev/misskey/blob/16ba1b3708b4aa5f97a86a600a8b2148d4c8213a/packages/frontend/src/components/MkNoteDetailed.vue#L557

2. PR は以下
https://github.com/misskey-dev/misskey/pull/9999

## 📌 Environment

Misskey version: 13.6.1
Your OS: Windows11
Your browser: Firefox 110.0 (64 ビット)

**Comment by CyberRex0** [comment]
duplicate of #9731 ?

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/224471231-58b93d60-1e76-4215-a8f9-df42259a7246.png)

https://misskey.io/notes/9c74fqk1rf

アバターも押せなくなるし詐称はまずい気がします
